### ISSUE TITLE
Old in-game textures 

### ISSUE THREAD

**Issue by Techwizz-somboo** [pizzaboxer/bloxstrap#1]
You should include old in-game textures. There are packs online like here for example https://gamebanana.com/mods/download/7661#FileInfo_547660 or you could rip them yourself.

**Comment by pizzaboxer** [comment]
A bit vague, do you mean UI textures or material textures?
In the case of UI textures (like the one you provided), it seems pretty much superfluous given you're never really going to get the old layout back, and honestly I really don't like the look.
If there's anyone who has ported the older material textures, then those could be included in the future. Thanks for the suggestion, though!

**Comment by Techwizz-somboo** [comment]
I meant material textures mostly, no clue what the one that I linked includes it was just something I found pretty quickly but I think it also includes material textures but not 100% sure.
