### ISSUE TITLE
1.4.1 detected as malware from windows defender

### ISSUE THREAD

**Issue by dopadream** [pizzaboxer/bloxstrap#10]
![image](https://user-images.githubusercontent.com/68942129/187051775-f13b1e66-66a8-4afb-947e-1ea89c4d926e.png)

**Comment by pizzaboxer** [comment]
Weird, looks like Defender is the only major antivirus that flags it as malware.
The only thing I can suggest for you to do is to add Bloxstrap (and the install directory) as an exclusion or to keep using v1.4.0 if it's not flagged.
