### ISSUE TITLE
Idea: Old Top Bar Icons Option

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#100]
So, recently i found out that in the folder /content/textures/ui/TopBar the icons for the top bar is located. It would be cool for there to be an option in the Bloxstrap Mod menu to replace the new textures with old textures, instead of having to do it one by one.
This is what the folder contains:
![image](https://user-images.githubusercontent.com/59868100/221138871-6d714362-1c3a-4f6f-8555-a1f31a1f68e9.png)
In the UI folder (/content/textures/ui), i also found the Chat, Backpack, Old menu, and the old Emotes icons:
/ui/Backpack
![Backpack@2x](https://user-images.githubusercontent.com/59868100/221139448-abcecb4b-fa63-48f2-a87a-132749bc0539.png) ![Backpack_Down@2x](https://user-images.githubusercontent.com/59868100/221139562-a777835d-3530-4d85-956b-6748a0e35437.png)
/ui/Chat
 ![Chat@2x](https://user-images.githubusercontent.com/59868100/221139700-e1bcb27a-84e5-41da-9972-7aebc8bb5e2e.png) ![ChatDown@2x](https://user-images.githubusercontent.com/59868100/221139738-85947845-a6da-495d-9ee2-af46dd8c5984.png)
/ui/Menu
![Hamburger@2x](https://user-images.githubusercontent.com/59868100/221139852-a6b9a088-4fbd-47f4-af74-ae521db2e241.png)![HamburgerDown@2x](https://user-images.githubusercontent.com/59868100/221139869-4c568f94-56b1-4e49-9b14-f06b54e423be.png)
/ui/Emotes
![EmotesIcon@3x](https://user-images.githubusercontent.com/59868100/221144473-f60f7fae-30b1-4d59-ad21-95381a75210c.png)
(PS: You don't have to download these icons from this issue, just search for them in your roblox install folder)
I also found the Leaderboard icons:
![image](https://user-images.githubusercontent.com/59868100/221146081-35407eac-c574-431e-92aa-5adf6481ffce.png)
Maybe you could replace the leaderboard icons with these ones: (icons on the left is are the new ones, on the right are the old ones)
/ui/PlayerList/
![PremiumIcon@3x](https://user-images.githubusercontent.com/59868100/221146235-08ae2e1c-17c2-4f33-b29b-7597763558d1.png)![icon_BC-16](https://user-images.githubusercontent.com/59868100/221146282-20030cc8-997f-4a91-8d19-10651a392737.png)![icon_TBC-16](https://user-images.githubusercontent.com/59868100/221146420-30c3cb0b-be41-4c04-b792-2f2674fbfe16.png)![icon_OBC-16](https://user-images.githubusercontent.com/59868100/221146436-444ffaaa-0b83-4670-ab18-afd8b383d122.png) (there should be an option to choose if you want the BC, TBC or OBC icon)
![AdminIcon@3x](https://user-images.githubusercontent.com/59868100/221146943-63398ba0-e08c-4246-8005-79886a737e04.png)![icon_admin-16](https://user-images.githubusercontent.com/59868100/221147086-4bff2605-5116-4824-a025-def2b1b46468.png)
![developer@3x](https://user-images.githubusercontent.com/59868100/221147397-ed129d57-f896-4e1a-ae95-b3cce8a0c255.png)![icon_placeowner](https://user-images.githubusercontent.com/59868100/221147444-6f0eab40-248d-40f1-a553-fe4f53f7dcd9.png)

(you are gonna have to download the icons on the right, beacuse they are not in the new roblox folder)
There is probably more old icons in the folder, but thats some that i could find.
Thanks in advance!

**Comment by pizzaboxer** [comment]
did you read the [help documentation on making custom mods](https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods)

**Comment by idkthegithub** [comment]
Guess you could ddo it like that.
