### ISSUE TITLE
[BUG] Cant See Bloxstrap Menu

### ISSUE THREAD

**Issue by Robloxionkad** [pizzaboxer/bloxstrap#1003]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I cant see the bloxstrap menu app in my search bar.

**Comment by pizzaboxer** [comment]
What if you look for it manually in your application list instead of using the search bar for it?
