### ISSUE TITLE
On WIndows 8.1 x64 it doesn't detect net desktop runtime even though ive reinstalled it twice.

### ISSUE THREAD

**Issue by SNIPERDEMON125** [pizzaboxer/bloxstrap#1007]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Please fix the bug.

**Comment by BokBoy** [comment]
Requires more information, such as what version of .net you have.

**Comment by pizzaboxer** [comment]
> Please fix the bug.

This is not my problem, this is .NET's problem.

If you open a Command Prompt window and run the following command: `dotnet --info` - what does it show?

**Comment by Acuelo-Azure** [comment]
Same issue for me and I'm on Windows 10 (Pro I think?)

**Comment by pizzaboxer** [comment]
@Acuelo-Azure Do what I asked OP to do please.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
