### ISSUE TITLE
Idea: Disable hurt texture

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#101]
In the /content/textures/ui/TopBar folder, i found this texture: 
![image](https://user-images.githubusercontent.com/59868100/221141442-6d9a6078-a5c6-4e02-8fd7-433f4cd3f634.png)
Im pretty sure this is the texture thats red when you take damage in a game. If, for some reason, this texture annoys somebody, there could be an option in the Bloxstrap mod menu to disable it. Thanks in advance!

**Comment by pizzaboxer** [comment]
did you read the [help documentation on making custom mods](https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods)

**Comment by idkthegithub** [comment]
Guess you could do it like that.
