### ISSUE TITLE
[BUG] bloxstrap cant startup

### ISSUE THREAD

**Issue by saikuu1** [pizzaboxer/bloxstrap#1010]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

whenever i try to startup bloxstrap it just dont work, neither does 'Roblox Player', anyone has the same issue? 

@pizzaboxer please fix it, im pretty sure other people also has the same problem as me.

**Comment by GodLightStem** [comment]
Hello, I am also having the same issue, when I open the roblox WEB APP, KEYWORD !!!WEB APP!!!!
I just get greeted with Roblox having a blank screen, and then crashing.
I tried downloading Bloxstrap to somehow fix the issue, but it is still there.
The version of windows is
Windows 11 Home
V23H2
Versión del sistema operativo	22631.2715
Experiencia	Windows Feature Experience Pack 1000.22677.1000.0
Im using a MSI laptop, with an RTX 4050 laptop gpu

**Comment by saikuu1** [comment]
@DED0026 im using brand razer, ive restarted this pc more then 4 times, the first time bloxstrap opens up but then after i closed it, it wont startup anymore.
