### ISSUE TITLE
[BUG] Roblox white screen of death/not responding

### ISSUE THREAD

**Issue by GodLightStem** [pizzaboxer/bloxstrap#1012]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello, since I got this MSI laptop, the first day that I launched roblox was fine, but the second day was the day it didnt want to open, ''White screen'' like many have was happening, so here I am, 2 weeks since the incident.
I encountered this custom roblox bootstrapper and I thought it would help me with this roblox issue. I downloaded it, launched it ANDDD!
Nothing... the same issue occurs, why is this? I don't get it, it's not my pc, nor the windows version, what is going on?
Ah, and here are my windows things

Edition	Windows 11 Home
Versión 23H2
Version 22631.2715
Windows Feature Experience Pack 1000.22677.1000.0

**Comment by pizzaboxer** [comment]
I have no idea why this happens, since from what I've just seen, it happens whenever it wants to. I can't really help you much here.

This issue board is only for issues related to Bloxstrap, so I'll close this. Hopefully you'll get it to work again.
