### ISSUE TITLE
[BUG] future (phase 3) preferred lighting technology not working

### ISSUE THREAD

**Issue by jjjetplane8950** [pizzaboxer/bloxstrap#1013]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when I open up roblox with bloxstrap, my custom fonts which I added worked. However, the lighting is roblox's default

**Comment by pizzaboxer** [comment]
What GPU are you using? Can I see the list of FastFlags you have configured by showing a picture of the flag editor?

**Comment by jjjetplane8950** [comment]
I don't think that the gpu us the problem. It worked without a problem until one day it just stopped working. Anyways I will send you the fast flags

![Bloxstrap Menu 6_12_2023 12_27_57 pm](https://github.com/pizzaboxer/bloxstrap/assets/152941167/41b5da0d-e14a-4c42-bd81-c25225d40f2a)
ed working. Anyways I will send you the fast flags

**Comment by pizzaboxer** [comment]
Show a picture of the flag editor.
