### ISSUE TITLE
When i try opening Bloxstrap, it only sends me to roblox with no settings or anything.

### ISSUE THREAD

**Issue by xhelpx** [pizzaboxer/bloxstrap#1014]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have tried reinstalling or deleting files for bloxstap but it wont let me go to the settings

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

You would've been told this upfront before installation, which would be surprising if you still missed it after reinstalling several times.
