### ISSUE TITLE
[REQ] Shift+P Free Cam

### ISSUE THREAD

**Issue by Veslydev** [pizzaboxer/bloxstrap#1015]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

The Free cam works for your games if its possible to work on any game by flags or smth if its possible can you add?
One kind of [video](https://www.youtube.com/watch?v=nM_zsbcdJRs)

**Comment by kkrnjc** [comment]
sounds very cool
