### ISSUE TITLE
[BUG] The "FFlagEnableInGameMenuChromeABTest" FFlag no longer works

### ISSUE THREAD

**Issue by Luximoz** [pizzaboxer/bloxstrap#1017]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After the latest ROBLOX update, they seem to have removed the FFlag, so that we can no longer get the previous CoreGUI that was a thousand times better than the current one :/
![ClientAppSettings json - Notepad_w1](https://github.com/pizzaboxer/bloxstrap/assets/94522544/a87f3845-afd7-4116-b3c3-c8fd3d19b25e)
![Roblox_w1](https://github.com/pizzaboxer/bloxstrap/assets/94522544/b817eb7b-6e63-48aa-b712-3a7743da505c)

**Comment by pizzaboxer** [comment]
Yep, can confirm that it's gone. Does setting just `FFlagEnableInGameMenuChrome` to `false` not work?

**Comment by pizzaboxer** [comment]
Moving discussion of this to #1017
