### ISSUE TITLE
Bloxstrap crashing (Not ROBLOX, only Bloxstrap)

### ISSUE THREAD

**Issue by YomiAAA** [pizzaboxer/bloxstrap#1019]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I play ANY game on Roblox while using Bloxstrap, after some time it crashes (when it crashes it doesn't even give me any pop up that Roblox has crashed, it just crashes and yeah that's all), when I try to play with normal Roblox it never crashes. Also, it didn't crash when I just downloaded Bloxstrap, it started crashing after like half a month I guess?

**Comment by YomiAAA** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/153300649/8010ab84-901b-4655-b3f7-96a6fd7e1e59)
I hope this works

**Comment by YomiAAA** [comment]
I just wasnt sure how to send pics on github

**Comment by YomiAAA** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/153300649/9fcc9b62-8adf-462e-8e09-97e282a1277e)

**Comment by pizzaboxer** [comment]
Try setting your framerate limit to zero, see if that changes anything.

**Comment by YomiAAA** [comment]
Okay

**Comment by YomiAAA** [comment]
I think the problem is solved, thanks!

**Comment by pizzaboxer** [comment]
Alright, good to hear. Let me know if anything goes wrong.
