### ISSUE TITLE
Bloxstrap settings resetting whenever i restart my computer

### ISSUE THREAD

**Issue by pairofsock** [pizzaboxer/bloxstrap#102]
when i restart my computer all my settings reset back to default and its quite annoying to have to recheck them everyday

**Comment by pizzaboxer** [comment]
> when i restart my computer all my settings reset back to default and its quite annoying to have to recheck them everyday

Do you have an antivirus installed? Something might be deleting the settings file. You could also check the logs to see what's happening when it reverts to default settings.

**Comment by pizzaboxer** [comment]
Closed for inactivity. I'll reopen if you follow up on this.
