### ISSUE TITLE
Roblox Vc

### ISSUE THREAD

**Issue by ThatOneDude447343534543** [pizzaboxer/bloxstrap#1021]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Okay so, whenever i used roblox vc, everyone complained about it being lagging and not working well. But when I tried it with regular roblox, not bloxstrap, people said that my mic worked fine. So can you please fix this?

**Comment by pizzaboxer** [comment]
The one thing I can suggest to you is to try setting your framerate limit to zero. See if that changes anything, and let me know if it doesn't so I can get you to try something else.

**Comment by ThatOneDude447343534543** [comment]
So I did that and people are saying that it’s still acting up.

**Comment by pizzaboxer** [comment]
Can you show me a picture of what you have configured in the FastFlag editor please?

**Comment by ThatOneDude447343534543** [comment]
![Screenshot 2023-12-10 131426](https://github.com/pizzaboxer/bloxstrap/assets/146670622/f16d4770-ba1b-410d-b30e-0d6164a16bb0)

**Comment by pizzaboxer** [comment]
In the editor, the button to access it is there if you scroll up.

That, and also try disabling all your integrations, and see if anything changes.

**Comment by AngryRico** [comment]
I think your just being trolled mate?
