### ISSUE TITLE
[QUESTION]  Is anti-afk-kick possible with BloxStrap?

### ISSUE THREAD

**Issue by mallusrgreatv2** [pizzaboxer/bloxstrap#1022]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Is it possible?

**Comment by canarydiscord** [comment]
it's not possible with bloxstrap but it's possible with an autoclicker

**Comment by pizzaboxer** [comment]
no
