### ISSUE TITLE
[BUG] no fps

### ISSUE THREAD

**Issue by MOVEda** [pizzaboxer/bloxstrap#1023]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i installed bloxstrap  i went to home screen and  pressed play and i played evade but i still had  60fps

**Comment by pizzaboxer** [comment]
Are you using a laptop?

**Comment by pizzaboxer** [comment]
Also, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter.

**Comment by MOVEda** [comment]
yes

**Comment by pizzaboxer** [comment]
Have you read through the Wiki page that I linked earlier?

**Comment by MOVEda** [comment]
yes

**Comment by MOVEda** [comment]
but i use huawei

**Comment by pizzaboxer** [comment]
Okay, did you follow the instructions that it gave? What happened?

**Comment by MOVEda** [comment]
i use HUWEI LAPTOP when i put in 300 fps and press install i do that and when i load the game only 60 fps

**Comment by pizzaboxer** [comment]
What about your performance settings?

**Comment by MOVEda** [comment]
what settings

**Comment by MOVEda** [comment]
roblox settings?

**Comment by MOVEda** [comment]
settings on bloxstrap?

**Comment by pizzaboxer** [comment]
...Did you read the Wiki page that I linked you?

**Comment by MOVEda** [comment]
yes

**Comment by MOVEda** [comment]
yes i did

**Comment by MOVEda** [comment]
i litterly read it 6 times

**Comment by pizzaboxer** [comment]
Do you see the section it says there about performance settings? Have you checked those?

**Comment by MOVEda** [comment]
what is required to get the fps on a huwei

**Comment by MOVEda** [comment]
yes i have and no work

**Comment by pizzaboxer** [comment]
At the very least, let me make sure that Bloxstrap is doing its job. 

Open the Bloxstrap Menu, go to the FastFlag editor, select 'Import JSON' and enter this in:
```json
{"FStringDebugShowFlagState": "DFIntTaskSchedulerTargetFps"}
```

Start Roblox, and show what the top-left section of the window looks like.

**Comment by MOVEda** [comment]
oh ok and happy new year

**Comment by MOVEda** [comment]
it didint work still no fps

**Comment by pizzaboxer** [comment]
As I asked, what does the top-left of the window show?

**Comment by MOVEda** [comment]
what do you mean

**Comment by pizzaboxer** [comment]
Do you not see something like this in the top left?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/7b2e78c8-0530-4402-87aa-87baa45afda6)

**Comment by MOVEda** [comment]
wait

**Comment by MOVEda** [comment]
how to do that

**Comment by MOVEda** [comment]
ok

**Comment by MOVEda** [comment]
![Uploading RobloxScreenShot20240106_115508576.png…]()

**Comment by MOVEda** [comment]
![RobloxScreenShot20240106_115508576](https://github.com/pizzaboxer/bloxstrap/assets/153387600/b8a51f55-d4f1-44d9-961c-21e4b10867cb)

**Comment by pizzaboxer** [comment]
Can you send me Roblox's latest log file from %localappdata%\Roblox\logs? Join the [Bloxstrap](https://discord.gg/bloxstrap) Discord server and DM it to me privately, do not send it here.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
