### ISSUE TITLE
[BUG] I always crash

### ISSUE THREAD

**Issue by icooln** [pizzaboxer/bloxstrap#1024]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello.I always crash and in normal roblox i  dont crash but in bloxstrap i crash 
[Bloxstrap_20231209T125628Z.log](https://github.com/pizzaboxer/bloxstrap/files/13625487/Bloxstrap_20231209T125628Z.log)

**Comment by TheMetalTechnet** [comment]
Are you using Vulkan by any chance?

**Comment by pizzaboxer** [comment]
This log file is showing Roblox working completely fine. It's just that here, Bloxstrap is encountering a one-off bug when it tries to cleanup after Roblox closes (which we are already aware of, before you ask). What do you mean by "I always crash"?

**Comment by icooln** [comment]
i crash a lot and it always gives me this error for some reasons but with normal roblox i dont crash at all

**Comment by icooln** [comment]
no i dont use vulkan

**Comment by icooln** [comment]
i think its something from my pc

**Comment by pizzaboxer** [comment]
> i crash a lot and it always gives me this error for some reasons but with normal roblox i dont crash at all

This log doesn't show Roblox crashing at all though, it shows it working perfectly fine.

Can you just confirm, what exactly do you see when a "crash" happens? What does the error message always say?

**Comment by icooln** [comment]
i will send a pic it says error
