### ISSUE TITLE
[BUG] fps not capping higher than 60

### ISSUE THREAD

**Issue by GenericNameGoesHere** [pizzaboxer/bloxstrap#1025]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

fps not changing, always caps at 60 no matter what i change it to. i click save and allat but nothing works. idk if this is a bug on my end or not

**Comment by bruh521** [comment]
Are you setting it to 0?

**Comment by GenericNameGoesHere** [comment]
> Are you setting it to 0?

nah i set it to 240

**Comment by pizzaboxer** [comment]
Are you using a laptop? Are you using exclusive fullscreen? Are your other flag changes applying (e.g. escape menu version)?

**Comment by GenericNameGoesHere** [comment]
> Are you using a laptop? Are you using exclusive fullscreen? Are your other flag changes applying (e.g. escape menu version)?

no laptop. dont know what exclusive fullscreen is, so probably not. no other flag changes.

**Comment by GenericNameGoesHere** [comment]
oh wait i fixed it, just had to mess around with the mod folder
