### ISSUE TITLE
[BUG] Roblox Crash When Opening From "Play Roblox"

### ISSUE THREAD

**Issue by ImLoadingUuU** [pizzaboxer/bloxstrap#1027]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Tried Switch Graphics API,Reboot,Check for updates
![NVIDIA_Share_Rbf0awTvac](https://github.com/pizzaboxer/bloxstrap/assets/69704016/980d18d4-46f9-4ba8-9c09-5fd5b72a8f51)

**Comment by ImLoadingUuU** [comment]
Seems its a bug only on Bloxstrap

**Comment by pizzaboxer** [comment]
Can you confirm that this doesn't happen when you try it with Roblox by itself? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ImLoadingUuU** [comment]
this also happen

**Comment by pizzaboxer** [comment]
Read the preliminary instructions next time. Though, thank you for quickly realizing that yourself.
