### ISSUE TITLE
[BUG] Can't play with Bloxstrap

### ISSUE THREAD

**Issue by DontGiveAFuck** [pizzaboxer/bloxstrap#1028]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've gotten this error launching roblox and I think bloxstrap is now detected by byfron.
I've closed many applications including bloxstrap and still couldn't launch roblox.
It only got fixed when I uninstalled bloxstrap.

![image_2023-12-10_221548898](https://github.com/pizzaboxer/bloxstrap/assets/55057630/adcb2198-b9fe-4cc9-9fe4-115063fd2065)

**Comment by pizzaboxer** [comment]
I think this is the second time that I've seen this happen (where it's claimed to be fixed after uninstalling), but I was never able to communicate well with that person to really track down what was causing it.

If you're willing to spend a bit of time to help figure out what's going on, the first thing you can do is just try reinstalling Bloxstrap, and see if the same thing continues to happen. Let me know if it still does.

**Comment by ImMejor35** [comment]
Its just Roblox validating the files in the version directory reinstall will most likely fix it

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
