### ISSUE TITLE
[REQ] Is it possible to add the playerlist from pre 2020

### ISSUE THREAD

**Issue by gamerloch10** [pizzaboxer/bloxstrap#1029]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

pretty much the title, though i don't understand fastflags so i don't know if its possible.

**Comment by canarydiscord** [comment]
no

**Comment by pizzaboxer** [comment]
Not possible, sorry.
