### ISSUE TITLE
Bug: Bloxstrap never closes when "Play Roblox" shortcut.

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#103]
So, i have found a bug, where if you use the Play Roblox shortcut in your start menu that Bloxstrap creates, it will work normally and open the browser (this only works if you have the disable desktop app mod enabled), but then it will stay open, even after the browser opened and loaded the web page, and it just says Starting Roblox...
Can you fix this?

**Comment by pizzaboxer** [comment]
> So, i have found a bug, where if you use the Play Roblox shortcut in your start menu that Bloxstrap creates, it will work normally and open the browser, but then it will stay open, even after the browser opened and loaded the web page, and it just says Starting Roblox...
> Can you fix this?

Oh, it's opening in your web browser. You have the disable desktop app mod enabled, right?

**Comment by idkthegithub** [comment]
Yep, i do.

**Comment by pizzaboxer** [comment]
Just got home and was able to reproduce this, thanks for letting me know.

**Comment by idkthegithub** [comment]
No problem!
