### ISSUE TITLE
[BUG] can't open v2 menu

### ISSUE THREAD

**Issue by bangbangyouall** [pizzaboxer/bloxstrap#1031]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i hover the roblox icon or press esc, the topbar just disappears & if i do the esc way, the topbar & escape menu is invisible. this doesn't happen with other menus like 2023 & 2015. also, i don't have the chrome menu a/b, just in case you gotta know.

**Comment by UserSwag** [comment]
yeah the bug happened with my today since i launched Bloxstrap, pizzaboxer if you are seeing this please fix it cuz i love the roblox v2 menu

**Comment by LucsterYT** [comment]
I have the same issue, it started yesterday as well. It seems that when I press ESC to open the menu it doesn't appear. But the Roblox icon on the top left disappears, indicating it should be open.

**Comment by canarydiscord** [comment]
the menu was abandoned years ago, stop using it

**Comment by pizzaboxer** [comment]
^

It's a bug with the V2 menu. If it's affecting you, then just don't use it.

**Comment by bangbangyouall** [comment]
damn, looks like v2 is over.

**Comment by githubberguy** [comment]
why does the v2 work still for me?

**Comment by UserSwag** [comment]
> why does the v2 work still for me?

it works now before it didn't

**Comment by githubberguy** [comment]
> > why does the v2 work still for me?
> 
> it works now before it didn't

well it worked when they had the issue :|
