### ISSUE TITLE
[BUG] Cant get the old version of bloxstrap, why?

### ISSUE THREAD

**Issue by SomeoneWithBadFPS803** [pizzaboxer/bloxstrap#1033]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So it just says this and I dont know what to do.
![Screenshot 2023-12-14 161403](https://github.com/pizzaboxer/bloxstrap/assets/150060083/0a2c6c22-e8b9-47f1-98ef-afafa482846f)

**Comment by pizzaboxer** [comment]
Read the preliminary instructions next time.

https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
