### ISSUE TITLE
[BUG] weird visual error 

### ISSUE THREAD

**Issue by minenerdz** [pizzaboxer/bloxstrap#1035]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

having a weird visual bug that happens whenever i hover over the buttons to toggle stuff in the installer and it stops me from ever actually installing anything 

Uploading ddwadwadwa.mp4…

**Comment by minenerdz** [comment]
hopin the video attached with it

**Comment by pizzaboxer** [comment]
You posted the issue before the video actually finished uploading. Reupload it.

**Comment by minenerdz** [comment]
https://github.com/pizzaboxer/bloxstrap/assets/151467474/41681b6e-78bf-4c33-a446-748b94ce127b

**Comment by minenerdz** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/151467474/7b2f4ce5-d2f1-4acc-a3a7-98a8e8f9b524)
visual bug is fixed but now its coming up with this when i try to install

**Comment by pizzaboxer** [comment]
> ddwadwadwa.mp4

Oh sweet, WPF graphics corruption. Just so you know, I can't actually do anything about this, and this will happen with any other application that uses WPF (like Visual Studio). However, this is almost always caused by applications that try to provide in-game graphics overlays ([SteelSeries Nahimic is a notably bad case of this](https://github.com/dotnet/wpf/issues/707)), so just check to see if you have any of those running.

> ![image](https://private-user-images.githubusercontent.com/151467474/290953208-7b2f4ce5-d2f1-4acc-a3a7-98a8e8f9b524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTk0MzIsIm5iZiI6MTcwMjcxOTEzMiwicGF0aCI6Ii8xNTE0Njc0NzQvMjkwOTUzMjA4LTdiMmY0Y2U1LWQyZjEtNGFjYy1hM2E3LTk4YThlOGY5YjUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwOTMyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzhjZjZlOTc0MDY2MmQxMjdlODM2YWE3YzQyMTVlYWU5YWU1OWNmZWU5YWQ3MjQ3ODkxMDE3Nzk2OGI0YmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D9SCgabPz1sNjt7CyXKWyf7m8EuQs4RZLK7U7P6bT7s) visual bug is fixed but now its coming up with this when i try to install

Is this happening every time you try to install? If so, this is likely being caused by an antivirus or something that's preventing it from connecting to the internet.

**Comment by minenerdz** [comment]
antivirus is off i cant seem to find anyway to get it to install even when every av is off

**Comment by pizzaboxer** [comment]
Something is blocking it, you'll have to figure out what it is.

**Comment by BokBoy** [comment]
> Something is blocking it, you'll have to figure out what it is.

Firewall??

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
