### ISSUE TITLE
Trying to download on Linux[BUG] 

### ISSUE THREAD

**Issue by Anoosyy** [pizzaboxer/bloxstrap#1040]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So I am not expecting an answer here, since I don't think this was made for Linux whatsoever, but I am hoping to get a hint as to why this happens.

So I tried to download the .exe file on Bloxstrap and ran it with Bottles, first time I did it. It worked, but when I tried launching it again, I accidentally ran the .exe installer file again and it tried to download it again. Usually on Windows it isn't an issue, but now I keep getting stuck at Installing WebView 2 screen. If anyone knows how I can get this working on Linux or why it gets stuck on WebView 2 screen, it would be very helpful.

**Comment by Anoosyy** [comment]
I GOT IT WORKING!!!! All I had to do was kill the Microsoft Edge process when it was trying to install WebView 2 and it works!!!! :D

**Comment by pizzaboxer** [comment]
Yeah, you'll have to do that. #625

**Comment by t4eoo** [comment]
how did u do it?
