### ISSUE TITLE
[BUG] Opaque On the 2015 UI Is Bugged Please fix it...

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1041]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2023-12-16 194815](https://github.com/pizzaboxer/bloxstrap/assets/145132255/c2289569-bf44-45a8-a351-d05b00ec2de2)

**Comment by githubberguy** [comment]
uh

**Comment by pizzaboxer** [comment]
Roblox isn't officially supporting the 2015 menu anymore. Stuff like this is to be expected.
