### ISSUE TITLE
[BUG] Roblox Keeps Freezeing

### ISSUE THREAD

**Issue by NoobKingerr** [pizzaboxer/bloxstrap#1042]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When Ever I Play Roblox With Bloxstrap, It Will Frezze When I Press A Button On My Keyboard. This Issue Seems To Only Happen With Bloxstarp. Is There A Way To Fix This?

**Comment by pizzaboxer** [comment]
Can I see the list of FastFlags you have configured in the Bloxstrap Menu? Show a picture of the FastFlag editor.

**Comment by NoobKingerr** [comment]
> Can I see the list of FastFlags you have configured in the Bloxstrap Menu? Show a picture of the FastFlag editor.

![Screenshot 2023-12-17 142108](https://github.com/pizzaboxer/bloxstrap/assets/154070114/526d56cd-fc14-4c1c-8023-db5d28b7c57f)

**Comment by pizzaboxer** [comment]
A picture of the FastFlag editor. The button that's there in the top left.

**Comment by aboalasamees** [comment]
I need help, When ever I play roblox with "Bloxstrap" Roblox crash after a few seconds when I join a game, Is there any fix for this issue??

**Comment by pizzaboxer** [comment]
Open a new thread, someone else is trying to get help here.

**Comment by NoobKingerr** [comment]
> A picture of the FastFlag editor. The button that's there in the top left.

![Screenshot 2023-12-18 154250](https://github.com/pizzaboxer/bloxstrap/assets/154070114/83ff02bf-6e14-4862-b98e-4a710081e755)

**Comment by aboalasamees** [comment]
Please, I need help.

**Comment by pizzaboxer** [comment]
> Please, I need help.

I have just asked you to open a new thread. Please do so.

**Comment by pizzaboxer** [comment]
> > A picture of the FastFlag editor. The button that's there in the top left.
> 
> ![Screenshot 2023-12-18 154250](https://private-user-images.githubusercontent.com/154070114/291433164-83ff02bf-6e14-4862-b98e-4a710081e755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzU0NDAsIm5iZiI6MTcwMjk3NTE0MCwicGF0aCI6Ii8xNTQwNzAxMTQvMjkxNDMzMTY0LTgzZmYwMmJmLTZlMTQtNDg2Mi1iOThlLTRhNzEwMDgxZTc1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwODM5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzYxOTI4MWIyMmEwYzk0ZTc0NTk4ZmU1NDhiYTI4MjNiMGZlM2QxNTU4OTI5OTc3MjA1NDhjNDM3YjNjMmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tv7JcqSrKbWQsegorSd3RdULoHPpj6-qRjCU5qDcGu0)

Can you try disabling all your integrations and see if that changes anything?

**Comment by BokBoy** [comment]
It could be your system's temperature being high?? Run a stress test to confirm it's not.

**Comment by Theoyeah** [comment]
> I need help, When ever I play roblox with "Bloxstrap" Roblox crash after a few seconds when I join a game, Is there any fix for this issue??

Im having the same issue since yesteday too it seems, but im not sure if it happens without Bloxstrap.

**Comment by pizzaboxer** [comment]
> but im not sure if it happens without Bloxstrap.

...You should check for that then. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by HelloKerem** [comment]
a a a a a a a
help

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
