### ISSUE TITLE
[BUG] Multi-Instance not working

### ISSUE THREAD

**Issue by Komas19-new** [pizzaboxer/bloxstrap#1043]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, i have LibreWolf (Firefox Fork), with Roblox, i launched roblox with librewolf, and then i join the same server with Microsoft Edge with a different account, and it just freezes Roblox then rejoins the server, without starting a new window.
I get no errors, its just like TeleportService teleporting me to the server.

![image](https://github.com/pizzaboxer/bloxstrap/assets/82937056/34d7f6d7-65e2-4570-9f9b-06c37d4aef48)
![image](https://github.com/pizzaboxer/bloxstrap/assets/82937056/8c3d743c-71df-480f-945a-934ec7ce9e6f)

**Comment by pizzaboxer** [comment]
Does it rejoin the server on the same account?

**Comment by idiotpuppi** [comment]
Also experiencing this, yes, it joins the server on the same account. 
Sometimes it completely freezes and doesn't even try to launch.

**Comment by pizzaboxer** [comment]
I'm kind of surprised by the "without starting a new window" part, I didn't even know that was possible. It's not like they changed any functionality either since it continues to work fine for me. I'm interested about that part though - can you try this again and then privately send me Roblox's latest log file from %localappdata%\Roblox\logs? Let me know when you have.

**Comment by idiotpuppi** [comment]
For me it seems to change between what I do. 
Example, invited an alt to pet sim 99, accepted the invite. It rejoins the same server on the main account, however it does close and reopen the window on occasion (first it did it without starting a new window, then it actually did start a new window when I tried again). I can't seem to replicate this, not 100% sure why.

No invite closes the roblox window and just joins on the other account. It simply won't launch 2 at a time, let alone more, despite it working right before roblox updated for me.

**Comment by idiotpuppi** [comment]
I am also unsure where to send the log file, I have never had any experience with any of that haha

**Comment by pizzaboxer** [comment]
Join the Discord server, DM me it.

Also, instead of launching from the browser, you should try launching a second instance through the desktop app, switching accounts in there, and then joining a game. See if that works.

**Comment by Komas19-new** [comment]
> I'm kind of surprised by the "without starting a new window" part, I didn't even know that was possible. It's not like they changed any functionality either since it continues to work fine for me. I'm interested about that part though - can you try this again and then privately send me Roblox's latest log file from %localappdata%\Roblox\logs? Let me know when you have.

Im using bloxstrap with administrator rights, this might be related, im using it with administrator rights because roblox is not launching with hyperion and having issues with windows 11 insider preview, and the same thing with uwp

**Comment by pizzaboxer** [comment]
> Im using bloxstrap with administrator rights, this might be related

As I asked before, does it open in the same window? And, see what I said above too.

Also, Hyperion typically doesn't work on Windows Insider builds.

**Comment by idiotpuppi** [comment]
I totally forgot but I've DMed you!

**Comment by Komas19-new** [comment]
> > Im using bloxstrap with administrator rights, this might be related
> 
> As I asked before, does it open in the same window? And, see what I said above too.
> 
> Also, Hyperion typically doesn't work on Windows Insider builds.

Ok so, it rejoins on the same account, and it doesn't even close the window, it just freezes then joins the same server, also, i am doing the same thing as idiotpuppi with the invite, could be an issue with the join button in the notifications
![image](https://github.com/pizzaboxer/bloxstrap/assets/82937056/d03580f6-80b3-45fa-9f53-e2e86c486901)
I have also tried without administrator right and same result happened.

But using the desktop app on the second account actually ran it on a second window. I have the log file if you want me to send it to you to fix the issue, since doing a workaround works (for me atleast)

**Comment by pizzaboxer** [comment]
Can I get your latest log file? I'm curious as to what the hell Roblox is doing since I've never heard of it reusing an existing instance when joining a game from the website.

**Comment by Komas19-new** [comment]
> Can I get your latest log file? I'm curious as to what the hell Roblox is doing since I've never heard of it reusing an existing instance when joining a game from the website. Don't forget, DM only.

i sent it

**Comment by pizzaboxer** [comment]
Issue was resolved in DMs (i think? correct me if it wasn't)
