### ISSUE TITLE
[BUG] asset download

### ISSUE THREAD

**Issue by jovhuhiewhdlidieh** [pizzaboxer/bloxstrap#1044]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The assets for the bloxstrap download won't work. I waited for like 30 mins that the assets loading but it won't working.

**Comment by githubberguy** [comment]
Hi! Here does your computer support like 64x bit? beacuse i was going through older versions and saw that its supported on 86x and 64x and btw check if your computer isn't that old..!

**Comment by pizzaboxer** [comment]
What do you mean by "the assets"?

**Comment by BokBoy** [comment]
> What do you mean by "the assets"?

He could mean Roblox player itself, it's not downloading?? Either that or the dotnet runtime

**Comment by Findyourlimit** [comment]
probably the assets in the game (example being models, animations, textures, and audio

**Comment by BokBoy** [comment]
> probably the assets in the game (example being models, animations, textures, and audio

I doubt it, it says the assets for bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
