### ISSUE TITLE
[QUESTION] When did Bloxstrap still support "Extravi Shade Present"? (Roshade)

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1045]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

here i really would like to know, is it the 2.5.0 or is it like more older? i'd like to know!

**Comment by githubberguy** [comment]
make me know about it!!

**Comment by pizzaboxer** [comment]
It was added in 2.0.0 and removed in 2.3.0. Don't think about trying to use it, it won't work.
