### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Markiplier0115** [pizzaboxer/bloxstrap#1046]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.IO.FileNotFoundException: Could not find file 'C:\Users\sofia\Downloads\Bloxstrap-v2.5.4.exe'.

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by BokBoy** [comment]
You didn't delete the file after you opened it??
