### ISSUE TITLE
Hello pizzaboxer can you add smooth camera in bloxstrap this is help for youtubers and tik tokers. I'm sorry for my literacy, I'm from Russia. :)

### ISSUE THREAD

**Issue by AXEL257Games** [pizzaboxer/bloxstrap#1047]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add smooth camera in bloxstrap.

**Comment by pizzaboxer** [comment]
What do you mean by a "smooth camera"?

**Comment by altatF12** [comment]
> What do you mean by a "smooth camera"?

I think that he meant to remove the camera snaps

**Comment by Specifix5** [comment]
Freecam?

**Comment by AXEL257Games** [comment]
I'm sorry I said it wrong, I wanted to make a freecam.

**Comment by AXEL257Games** [comment]
At first I wanted a smooth camera and then I realized that this happens if you increase your FPS. :)

**Comment by BokBoy** [comment]
> I'm sorry I said it wrong, I wanted to add a freecam.

A freecam may be bad for some games like bedwars... It's also game side so it might not work... I'll wait for Pizzaboxer

**Comment by pizzaboxer** [comment]
> I'm sorry I said it wrong, I wanted to add a freecam.

not only is this not possible, this would only be used for cheating lol

**Comment by Jakob3325** [comment]
bro, you can noclip, this is cheating too
