### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by andaubuoi** [pizzaboxer/bloxstrap#1048]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Capturek](https://github.com/pizzaboxer/bloxstrap/assets/129636774/594f491b-bee7-47d4-947a-c8150b1236b0)
Idk but it happens to me. It has never happened before. How can I fix it

**Comment by altatF12** [comment]
Try running it as an administrator

**Comment by pizzaboxer** [comment]
>  Idk but it happens to me. It has never happened before. How can I fix it

If you open the file properties for RobloxPlayerBeta.exe at the path given, what does it show under the "Compatibility" tab?

**Comment by BokBoy** [comment]
> Try running it as an administrator

No im pretty sure you need the exact opposite. There was an issue with this once...

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
