### ISSUE TITLE
[BUG] Can't play roblox with Bloxstrap

### ISSUE THREAD

**Issue by altatF12** [pizzaboxer/bloxstrap#1049]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It simply crashes when trying to play
Already checked logs and this is the error that keep happening:

![image](https://github.com/pizzaboxer/bloxstrap/assets/111399429/783ae4e3-c00f-4441-bfa3-964bb5e83d5b)

**Comment by pizzaboxer** [comment]
As stated in the preliminary instructions, have you confirmed that Roblox by itself works? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by altatF12** [comment]
Yes

**Comment by altatF12** [comment]
nvm, i clicked more times and removed some configs in fast flags and it now works
