### ISSUE TITLE
[BUG] Tabbing out with the Windows key not working

### ISSUE THREAD

**Issue by tomskarr** [pizzaboxer/bloxstrap#1052]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I can't tab out normally, I always have to do Alt + Tab and it's getting really annoying. I tried searching about this problem but couldn't really find a fix

**Comment by pizzaboxer** [comment]
Are you using exclusive fullscreen?

**Comment by tomskarr** [comment]
Tbh i have no idea, but now that you mention it that might be it. Which one do I disable exclusive full screen? (Bloxstrap menu, Play Bloxstrap or the Roblox client?)

**Comment by BokBoy** [comment]
Fast flags menu, there should be a button.

**Comment by pizzaboxer** [comment]
> but now that you mention it that might be it

If you don't know what it is, then you're certainly not using it, so forget I asked. Though, it does sound like you are using fullscreen. Does this happen in windows mode too?

**Comment by tomskarr** [comment]
It's always in full screen, when I go to the roblox settings and turn fullscreen off it's still fullscreen. And another thing, when i try to record with OBS, the screen will record a single frame of roblox and then freeze. Screenshotting is buggy too, idk how to explain it but it's like the photo capture GUI is on another layer, i can still take the photo but the GUI doesn't appear, idk tbh

**Comment by tomskarr** [comment]
I can record a video of it if you want

**Comment by BokBoy** [comment]
Ohhh wait, I know what you are talking about.
It's Roblox's problem not bloxstrap. I also get the issue, I know what you mean.

**Comment by pizzaboxer** [comment]
> It's always in full screen, when I go to the roblox settings and turn fullscreen off it's still fullscreen. And another thing, when i try to record with OBS, the screen will record a single frame of roblox and then freeze. Screenshotting is buggy too, idk how to explain it but it's like the photo capture GUI is on another layer, i can still take the photo but the GUI doesn't appear, idk tbh

Does pressing Alt+Enter bring you out of fullscreen? What FastFlags do you have configured?

**Comment by tomskarr** [comment]
I tried alt+enter but it did nothing, and the FastFlags I have are just a bunch of optimization thingies I found on YT: FFlagDebugGraphicsDisableDirect3D11
FFlagDebugGraphicsPreferOpenGL
FIntDebugFRMOptionalMSAALevelOverride
FStringPartTexturePackTablePre2022

**Comment by pizzaboxer** [comment]
What if you remove the first two flags?
