### ISSUE TITLE
[REQ] VARIABLE RESOLUTION built in! (Stretched res)

### ISSUE THREAD

**Issue by Latiov** [pizzaboxer/bloxstrap#1053]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

is there any way to have a fixed resolution while using it? i use different resolutions while playing video games to reduce render time (e.x 1280x720p) and improve performance. or use it like a stretched resolution (fullscreen on 1920x1080, but rendering 1280x720)

if there was a way to launch bloxtrap through the app natively at such a resolution, and be able to make it fullscreen [scaled](not just a floating display in the middle, problems like this would occur on monitors bigger than the example 1280x720p; like 1920x1080p monitors)

there is a way currently (has been known for a long time) just to simply launch display settings on windows and simply choose the resolution you want to play at, the only problem is it will change your whole monitor resolution to the chosen resolution, which means that after playing (watch youtube at monitor native res), you'd have to change it back, which is quite a hassle

**Comment by pizzaboxer** [comment]
I can't handle this, it's not like Roblox provides any way to do so. This should be handled entirely by your native GPU settings if you use exclusive fullscreen. Sorry.
