### ISSUE TITLE
[BUG] mouse cursor not appearing when in true Fullscreen

### ISSUE THREAD

**Issue by deepwokenclonetrooper** [pizzaboxer/bloxstrap#1056]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i went into true Fullscreen my mouse cursor didn't appear, i had changed the cursor with bloxstrap and it didn't work. Any fix?

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#exclusive-fullscreen

> Please note that Exclusive Fullscreen won't fully work for everyone. For instance, (...), the mouse cursor may not show properly. That's sort of just how it is. If you encounter that, and it noticeably impacts your gameplay, then you'll just have to not use it.
