### ISSUE TITLE
[BUG] Unable to connect to Roblox (Despite a 50 Mbps wifi)

### ISSUE THREAD

**Issue by Itsappuru** [pizzaboxer/bloxstrap#1058]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

[Inner Exception]
System.TimeoutException: A task was canceled.

[Inner Exception]
System.Threading.Tasks.TaskCanceledException: A task was canceled.

Any idea how to fix it? Or is it a major bug?

**Comment by pizzaboxer** [comment]
Not a bug. This is likely being caused by an antivirus or something preventing it from connecting to the internet. Make sure you don't have anything like that.

**Comment by BokBoy** [comment]
> Or is it a major bug?

Definitely not, I can do it.
>Any idea how to fix it?

Best way is what Pizzaboxer said for the antivirus.
If it doesn't work, check your firewall (simple one on windows defender) and check its set to private as it will let the most traffic through.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
