### ISSUE TITLE
[BUG] weird "insta" crashes

### ISSUE THREAD

**Issue by celakeniock** [pizzaboxer/bloxstrap#1059]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

basically when i play deepwoken or anything on roblox, it just crashes after some completely RANDOM time, it can keep up without crashing 2 hours or crash after 5 minutes, i dont really know what can cause that

**Comment by BokBoy** [comment]
~~ It sounds like an unstable computer... ~~
Nevermind...

Does it crash for the games that don't crash?? You said sometimes it doesn't crash, does it crash in the games that doesn't crash??

**Comment by pizzaboxer** [comment]
When it crashes, does it just suddenly close, or does it show a crash dialog? Also, can you do several playthroughs without Bloxstrap and see if the issue is gone? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Axelanse** [comment]
I've had the same issue and it was not related to bloxstrap. It may be different for you though.

**Comment by celakeniock** [comment]
> When it crashes, does it just suddenly close, or does it show a crash dialog? Also, can you do several playthroughs without Bloxstrap and see if the issue is gone? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

yea but let me say it kinda different, when i play for an example ANY GAME on roblox, doesnt matter what, after few minutes OR more, it crashes in game, when im playing a game. When it crashes theres no crash dialog, just a sudden close ingame (not when loading in)

**Comment by celakeniock** [comment]
yep it still crashed with bloxstrap turned off, so i guess its not related to bloxstrap, if you can could you help me cause its literally happening for me for a long time.
[0.605.3.6050660_20231226T184527Z_Player_825CD_last.log](https://github.com/pizzaboxer/bloxstrap/files/13773293/0.605.3.6050660_20231226T184527Z_Player_825CD_last.log)

**Comment by pizzaboxer** [comment]
> if you can could you help me cause its literally happening for me for a long time.

The best I can do is point you to this:

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

Other than that, I don't really have much information to offer you. Sorry.

**Comment by celakeniock** [comment]
ive found a solution, turns out that oculus app (main reason for most roblox weird crashes) just tries to inject some dlls and roblox crashes, just uninstalled it

**Comment by BokBoy** [comment]
> ive found a solution, turns out that oculus app (main reason for most roblox weird crashes) just tries to inject some dlls and roblox crashes, just uninstalled it

Ahh now if you said that earlier (not in a rude way)
Good job on fixing it yourself 👍

**Comment by celakeniock** [comment]
> > ive found a solution, turns out that oculus app (main reason for most roblox weird crashes) just tries to inject some dlls and roblox crashes, just uninstalled it
> 
> Ahh now if you said that earlier (not in a rude way) Good job on fixing it yourself 👍

sorry if i could be kinda rude i didnt really mean it and i still dont speak perfect english and yea i basically didnt know i could act kinda rude or something
