### ISSUE TITLE
API call to help closing the "Download and Install Roblox" modal on the website

### ISSUE THREAD

**Issue by 1011025m** [pizzaboxer/bloxstrap#106]
Hey,

There seems to be an API call from the official launcher that helps closing this modal whenever you've successfully launched a game
![image](https://user-images.githubusercontent.com/37438176/222618910-3ef968a0-555e-499f-b121-72777bebd805.png)

Doesn't really bother me that much but it feels unusual having to close the modal when I close the game to continue browsing the website.

From my initial observations I found that the website will poll an endpoint that's supposed to return client status every 3 seconds after a game's been launched. Apparently the player client doesn't make the player appears to have launched a game so it must be from the launcher.
![image](https://user-images.githubusercontent.com/37438176/222619781-ae256198-d38f-45a2-984f-5fd13327939e.png)

In the requests from the image above, they all returned "Unknown".

I'll have to do some more digging with the official launcher to see how to replicate that request and close the modal.

Thank you for the great work!

**Comment by pizzaboxer** [comment]
Oh, I kinda forgot about that. Yeah, I should add that, thanks for reminding me.

**Comment by 1011025m** [comment]
Huh, thought the browsertrackerid was there for analytics only. Guess I was wrong.
