### ISSUE TITLE
[BUG] Running the Roblox Studio (Bloxstrap) shortcut opens the Discover page instead of launching Roblox Studio

### ISSUE THREAD

**Issue by mamalord** [pizzaboxer/bloxstrap#1062]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to run the `Roblox Studio (Bloxstrap)` shortcut created after installing Bloxstrap, it doesn't launch Roblox Studio and instead opens the `https://www.roblox.com/games` page
Roblox Studio runs fine when launched from the original shortcut
I am using the latest release version from Actions (https://github.com/pizzaboxer/bloxstrap/actions/runs/7226398711)

**Comment by pizzaboxer** [comment]
You downloaded a debug build of a version that's yet to be released and you're opening an issue complaining that it's not working properly. Are you serious?

**Comment by BokBoy** [comment]
💀

**Comment by mamalord** [comment]
> Are you serious?
Yes

**Comment by mamalord** [comment]
Also I downloaded the one that said Release

**Comment by BokBoy** [comment]
That's still prerelease

**Comment by mamalord** [comment]
Yes I know I'm downloading the actual release (from the Releases tab) now

**Comment by mamalord** [comment]
There's no Bloxstrap shortcut for Studio there how quaint 
Oh well 🤷‍♂️

**Comment by mamalord** [comment]
And don't treat people like they know everything about your app btw :3

**Comment by BokBoy** [comment]
> And don't treat people like they are supposed to know everything about your app btw :3 

Mate, this isn't about the app it's about GitHub. You should know what actions folder is used for in GitHub, after that there is a wiki.
Respect Pizzaboxer for his work.

**Comment by mamalord** [comment]
There was nothing saying that there will be no support given for pre-release builds that's why I retaliated

**Comment by BokBoy** [comment]
> There was nothing saying that there will be no support given for pre-release builds that's why I retaliated

Mate, what are you saying.
Everyone knows that there isn't or almost no support for prerelease.
It's like saying that a beta software is the official release.

**Comment by pizzaboxer** [comment]
> And don't treat people like they are supposed to know everything about your app btw :3

> There was nothing saying that there will be no support given for pre-release builds that's why I retaliated

I think anybody would reasonably assume that complaining about an in-progress version that hasn't been finished yet of which you went out of your way to intentionally download is a stupid thing to do. What were you expecting?

**Comment by mamalord** [comment]
I assumed it was fine because [most](https://github.com/dosemu2/dosemu2) [of](https://github.com/NationalSecurityAgency/ghidra) [the](https://www.gnu.org/software/binutils/) [apps](https://github.com/godotengine/godot) [I](https://www.gnu.org/software/bash/) [use](https://www.kernel.org) are fine with reporting bugs for an in-dev version 🤷‍♂️

**Comment by pizzaboxer** [comment]
The difference betweel all those here is that this is not actively being worked on. I can't actively work on this. The last actual commit on main done by me was two months ago. It's insanely frustrating to receive complaints about unfinished work that I am obviously well aware of doesn't currently function properly. 

I hope you see where I'm coming from with this. I apologize if I was explosive at first, but I really think this should've been self-explanatory to anyone.

(by the way, comparing this to the linux kernel? really?)

**Comment by WaviestBalloon** [comment]
> I assumed it was fine because [most](https://github.com/dosemu2/dosemu2) [of](https://github.com/NationalSecurityAgency/ghidra) [the](https://www.gnu.org/software/binutils/) [apps](https://github.com/godotengine/godot) [I](https://www.gnu.org/software/bash/) [use](https://www.kernel.org) are fine with reporting bugs for an in-dev version 🤷‍♂️

No way you actually just compared a personal project against projects with TONS of developers and stars, this repo and project is only maintained by one person nobody else.

**Comment by BokBoy** [comment]
> I assumed it was fine because [most](https://github.com/dosemu2/dosemu2) [of](https://github.com/NationalSecurityAgency/ghidra) [the](https://www.gnu.org/software/binutils/) [apps](https://github.com/godotengine/godot) [I](https://www.gnu.org/software/bash/) [use](https://www.kernel.org) are fine with reporting bugs for an in-dev version 🤷‍♂️

Bro did he compare a Linux project to a GitHub project built with the community??
Mate Linux prerelease is different, they keep most of it until it's nearly ready.
💀
