### ISSUE TITLE
[REQ] Option to disable roblox's new spacial audio change

### ISSUE THREAD

**Issue by the9655a** [pizzaboxer/bloxstrap#1063]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Roblox recently changed their spacial audio where sounds coming from behind you are muffled and cant be heard at full volume, unlike when you look directly at where the sound is coming from. This has made certain games less enjoyable. My suggestion is having the option to disable it. Hopefully its possible to do this.

**Comment by pizzaboxer** [comment]
Hm, are you talking about this? https://devforum.roblox.com/t/the-volumetric-sounds-beta-is-here/1695240

If you're certain that your game didn't happen to add support for it, you can try setting the `DFFlagAudioToggleVolumetricPanning` flag to `False` in the FastFlag editor.

**Comment by the9655a** [comment]
That flag didn't work. I guess its something else then. Maybe this video might help to show you what I mean?
https://pixeldrain.com/u/qEmk1ZyC

Keep in mind this isn't exclusive to one game, I've tested many and it was never like this before. But it's fine if this is out of the scope of Bloxstrap.

**Comment by pizzaboxer** [comment]
Seems like this is outside of my scope. How recent is this? I really can't find anything else that could possibly relate to this.

**Comment by the9655a** [comment]
(I recorded the video today btw.) As far as I know, probably within the last 5 months. I hadn't played roblox for a while, and I only noticed this change around a month ago after playing again. So this has happened in between the last time I played and now, which is give or take 5 months.
