### ISSUE TITLE
[REQ] Possible to add older lighting from pre 2019 (i think) 

### ISSUE THREAD

**Issue by gamerloch10** [pizzaboxer/bloxstrap#1065]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It looks something like this (i found this off a old youtube video so it looks a bit bad)
![image](https://github.com/pizzaboxer/bloxstrap/assets/136502659/c4618207-281f-4ba8-b922-375fd664737f)

**Comment by d44df016fe28bc8d5974** [comment]
compability lighting?

**Comment by pizzaboxer** [comment]
Compatibility should do what you're looking for.

**Comment by gamerloch10** [comment]
> Compatibility

I am pretty dumb, how do i enable that?

**Comment by pizzaboxer** [comment]
Bloxstrap Menu, FastFlags tab, Preferred lighting technology.

**Comment by gamerloch10** [comment]
> Bloxstrap Menu, FastFlags tab, Preferred lighting technology.

do i need to update my bloxstrap, all i have is voxel shadowmap and future, or is it one of those and im just being stupid lol

**Comment by pizzaboxer** [comment]
Oh, I'm an idiot, excuse me. You can't actually choose to use compatibility lighting, my bad - I completely forgot.

Anyway, what you're trying to do isn't actually possible. Voxel is the oldest out of the three available, so it may make *some* games look older. Sorry about that.

**Comment by gamerloch10** [comment]
> Oh, I'm an idiot, excuse me. You can't actually choose to use compatibility lighting, my bad - I completely forgot.
> 
> Anyway, what you're trying to do isn't actually possible. Voxel is the oldest out of the three available, so using it may make _some_ games look older if they use anything newer. Other than that, there's not much you can do. Sorry about that.

Ohhhh ok, well ill try that out, thanks for you help
