### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xiaoniangaoh** [pizzaboxer/bloxstrap#1066]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20231226T063327Z.log](https://github.com/pizzaboxer/bloxstrap/files/13769240/Bloxstrap_20231226T063327Z.log)

**Comment by pizzaboxer** [comment]
Does this happen every time that you try to install Bloxstrap?
