### ISSUE TITLE
Speech bubbles not showing

### ISSUE THREAD

**Issue by OwOTerumiUwU** [pizzaboxer/bloxstrap#1067]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

(As the tittle says, the chat speach bubbles just don't appear, i reinstalled bloxstrap but it remains.)

![RobloxScreenShot20231226_072534563](https://github.com/pizzaboxer/bloxstrap/assets/97059318/4f0c1acb-773f-4b82-a3c1-1cdfc0c4a966)

**Comment by d44df016fe28bc8d5974** [comment]
the game might have bubblechat disabled

**Comment by pizzaboxer** [comment]
^

What game is this? Does this happen in any other games?

**Comment by OwOTerumiUwU** [comment]
> ^
> 
> What game is this? Does this happen in any other games?

Guts and Blackpowder, it happens in any game

**Comment by OwOTerumiUwU** [comment]
> ^
> 
> What game is this? Does this happen in any other games?

Guts & Blackpowder, it does not show in some games, i tried on centaura and it worked, but i tried on a lobby and it doesnt worked

**Comment by pizzaboxer** [comment]
> Guts & Blackpowder

This game doesn't have chat bubbles enabled.

>  it does not show in some games

Some games? Can you please specify what games exactly?
