### ISSUE TITLE
[BUG] Game just closes when I tab out

### ISSUE THREAD

**Issue by PulseFoir** [pizzaboxer/bloxstrap#1069]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This happened when I do Windows + D

**Comment by pizzaboxer** [comment]
Preliminary instructions. Can you confirm that this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by PulseFoir** [comment]
I just tried it, it only happens when using bloxstrap

**Comment by pizzaboxer** [comment]
Have you configured any FastFlags? If so, post a picture of the flag editor.

**Comment by PulseFoir** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/154741699/946d4515-fc02-4aa1-98f7-615a8c617fd9)
![image](https://github.com/pizzaboxer/bloxstrap/assets/154741699/4e7c4804-300e-4b09-b3cb-7113bdd07b2a)

**Comment by pizzaboxer** [comment]
Delete the Vulkan flag and see if the same thing still happens.

**Comment by PulseFoir** [comment]
It doesn't happen anymore, thank you!
