### ISSUE TITLE
[BUG] Freeze Every three+ seconds

### ISSUE THREAD

**Issue by RawLunaHub** [pizzaboxer/bloxstrap#1070]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Game freezing every three seconds for a while

**Comment by pizzaboxer** [comment]
Preliminary instructions. Please confirm that this doesn't happen without Bloxstrap. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by RawLunaHub** [comment]
its doesnt happen when i use normal roblox

**Comment by pizzaboxer** [comment]
What FastFlags do you have set? Does setting the framerate limit as zero change anything?

**Comment by RawLunaHub** [comment]
default fast flags that given in options

**Comment by RawLunaHub** [comment]
i am using 120 fps because i have 120 hz

**Comment by pizzaboxer** [comment]
Can you follow my suggestion about setting the framerate limit to zero please?

**Comment by RawLunaHub** [comment]
Alright

пн, 15 янв. 2024 г., 03:15 pizzaboxer ***@***.***>:

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
