### ISSUE TITLE
[REQ] FFlag Definitions

### ISSUE THREAD

**Issue by PulseFoir** [pizzaboxer/bloxstrap#1071]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Soo.. I have some FFlags enabled and some of them are causing delay.
Some of them that I don't understand :
![image](https://github.com/pizzaboxer/bloxstrap/assets/154741699/25190f67-6b20-475e-9000-b5bd4bc900dd)
Would be cool if Bloxtrap tells you what some of the FFlags might do

**Comment by d44df016fe28bc8d5974** [comment]
the fflags in your screenshot disable almost all  telemetry

**Comment by PulseFoir** [comment]
Does that make my game faster?

**Comment by pizzaboxer** [comment]
>  Would be cool if Bloxtrap tells you what some of the FFlags might do

No, that's your responsibility if you're the one adding them.

From https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags:

> It's worth mentioning that **you should only be configuring flags of which you know what they do**, and that you have as few of them as possible. If you don't fully understand what something does, it's possible that you may encounter problems in regards to stability, or other things that you may not be expecting.
