### ISSUE TITLE
roblox not opening

### ISSUE THREAD

**Issue by Mikrowo** [pizzaboxer/bloxstrap#1073]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i open bloxstrap (play roblox), or try to launch it from the website, it says connecting to roblox, then starting roblox then it just doesnt open.

**Comment by Mikrowo** [comment]
and yes roblox opens when i dont use bloxstrap.

**Comment by pizzaboxer** [comment]
What FastFlags do you have configured in the Bloxstrap Menu?

**Comment by Mikrowo** [comment]
![Screenshot 2023-12-29 184929](https://github.com/pizzaboxer/bloxstrap/assets/139611845/9950d093-7359-4c32-b886-3ed540d55645)

**Comment by Mikrowo** [comment]
otther than the presets i havent touched the editor

**Comment by pizzaboxer** [comment]
What about forcing a reinstallation in the behaviour tab?

**Comment by Mikrowo** [comment]
it appears to start but the app doesnnt show up
![image](https://github.com/pizzaboxer/bloxstrap/assets/139611845/b02d4f2b-6aff-47f7-a6bd-bc9fd1b3dd65)

**Comment by Mikrowo** [comment]
forcing a reinstallation doesnt work apparantly

**Comment by pizzaboxer** [comment]
Disable all your integrations, set the framerate limit to zero, see if the same thing continues to happen.

**Comment by shmn123** [comment]
> Disable all your integrations, set the framerate limit to zero, see if the same thing continues to happen.

still happening for me, was working fine like 30mins ago

**Comment by Mikrowo** [comment]
same thing

**Comment by pizzaboxer** [comment]
Both Roblox/Bloxstrap should have identical configurations now. I'll see if I can take a closer look myself. Send me your entire installation folder that's located at %localappdata%\Bloxstrap. Create a .rar archive out of it and upload it somewhere, and post it here.

**Comment by Mikrowo** [comment]
https://drive.google.com/file/d/1dTWtLit0vD5haFSROwPTUN2VlTJQDEM8/view?usp=sharing

i uploaded it to google drive, hope that isnt an issue.

**Comment by pizzaboxer** [comment]
> otther than the presets i havent touched the editor

So about that...

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/3d0a5bb1-e0e8-47b8-bed3-09b76ca8e9f6)

I think it's very clear what your problem here is.

**Comment by Mikrowo** [comment]
i didnt put anything in there, it was already in there when i opened it so i guessed it was normal.

**Comment by Mikrowo** [comment]
game works but my roblox freezing for no reason still happens, ill try to fix it (its on normal roblox as well) but thank you for fixing my bloxstrap.
