### ISSUE TITLE
[BUG] giga low scroll

### ISSUE THREAD

**Issue by attasityao** [pizzaboxer/bloxstrap#1074]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i scroll like half a pixel at a time on huds but not ingame camera

**Comment by pizzaboxer** [comment]
There's this flag named `FIntScrollWheelDeltaAmount` which you can set as a number, which should increase the rate of UI scrolling depending on how high you set it. Try that out.

**Comment by attasityao** [comment]
> There's this flag named `FIntScrollWheelDeltaAmount` which you can set as a number, which should increase the rate of UI scrolling depending on how high you set it. Try that out.

gotchu ty
