### ISSUE TITLE
[BUG] Bloxtrap not running roblox tho it appears its running in the task manager

### ISSUE THREAD

**Issue by PROLERXZ** [pizzaboxer/bloxstrap#1077]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i launched bloxtrap it didnt run tho roblox was running in the task manager but i could not play tho i can play in the normal roblox but its way slower

**Comment by pizzaboxer** [comment]
Have you ever configured any FastFlags? What do you have set?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
