### ISSUE TITLE
There is no cursor when using an xbox controller[BUG] 

### ISSUE THREAD

**Issue by PrinceYeti1841** [pizzaboxer/bloxstrap#1078]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

*when using an xbox controller with bloxstrap it has no cursor*

**Comment by pizzaboxer** [comment]
There's no white dot in the middle of the screen?

**Comment by JSkes** [comment]
> There's no white dot in the middle of the screen?

Yeah, he probably means that because I also face the same problem, the white dot just isn't there at all for some reason.

**Comment by pizzaboxer** [comment]
Roblox appears to have removed it. Not a bug.

**Comment by PrinceYeti1841** [comment]
what do i do

**Comment by PrinceYeti1841** [comment]
the cursor is still there with normel roblox

**Comment by pizzaboxer** [comment]
> the cursor is still there with normel roblox

Are you sure? It's not for me, show a screenshot of it.

**Comment by PrinceYeti1841** [comment]
OK

**Comment by PrinceYeti1841** [comment]
![Uploading image_2024-01-07_091731719.png…]()

**Comment by pizzaboxer** [comment]
You didn't upload it properly, wait for it to upload before posting.

**Comment by PrinceYeti1841** [comment]
![Uploading RobloxScreenShot20240107_091645311.png…]()

**Comment by PrinceYeti1841** [comment]
![no cursor](https://github.com/pizzaboxer/bloxstrap/assets/126952989/a9ac83b8-1541-4d69-a5e2-6cd6882a0e0f)

**Comment by pizzaboxer** [comment]
Where's the cursor?

**Comment by PrinceYeti1841** [comment]
![image_2024-01-08_151023931](https://github.com/pizzaboxer/bloxstrap/assets/126952989/32fc2fc0-1e48-442e-b86b-dd3f37ec45d0)

**Comment by PrinceYeti1841** [comment]
this is the normal roblox

**Comment by pizzaboxer** [comment]
Normal Roblox shows this for me though:

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/74339b5a-3cac-4546-b309-c5c8f9e4146b)

It's difficult for me to consider this as being a bug with Bloxstrap when this doesn't even be appear to be consistent with Roblox itself.

I'll briefly check one thing though. Can you open Bloxstrap's installation folder at `%localappdata%\Bloxstrap`, open `State.json` and send all the contents of it here?

**Comment by PrinceYeti1841** [comment]
there is no state.json file when i search %localappdata%\Bloxstrap there are normel json files state and settings

**Comment by PrinceYeti1841** [comment]
![WhatsApp Image 2024-01-10 at 07 53 09_af2e56ff](https://github.com/pizzaboxer/bloxstrap/assets/126952989/5583cff9-bf38-4e8c-8ea3-afccdd33a421)

**Comment by PrinceYeti1841** [comment]
![WhatsApp Image 2024-01-10 at 07 53 55_d51dca7a](https://github.com/pizzaboxer/bloxstrap/assets/126952989/3ae83f28-d200-4f70-bf01-3ae8e398c7c6)

**Comment by PrinceYeti1841** [comment]
![Uploading WhatsApp Image 2024-01-10 at 07.54.20_eb3a2be9.jpg…]()

**Comment by PrinceYeti1841** [comment]
![WhatsApp Image 2024-01-10 at 07 54 20_eb3a2be9](https://github.com/pizzaboxer/bloxstrap/assets/126952989/d8c6672b-a070-4a94-ac5e-d9fb24b6ed04)

**Comment by PrinceYeti1841** [comment]
![WhatsApp Image 2024-01-10 at 07 54 32_c38ac769](https://github.com/pizzaboxer/bloxstrap/assets/126952989/682cb3b1-82b8-48e9-9b2d-266d6bff873c)

**Comment by PrinceYeti1841** [comment]
[State.json](https://github.com/pizzaboxer/bloxstrap/files/13884802/State.json)

**Comment by pizzaboxer** [comment]
Everything seems fine here. Last ditch effort, does enabling the "force Roblox reinstallation" option in the behaviour tab help with anything?

**Comment by PrinceYeti1841** [comment]
it did not work

**Comment by pizzaboxer** [comment]
Seems like an issue with Roblox then, not a bug on my part. I can't really do much to help you there, sorry.
