### ISSUE TITLE
[REQ] Legacy Lighting Engine option.

### ISSUE THREAD

**Issue by MythicalTrashcan** [pizzaboxer/bloxstrap#1079]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Would this be a possible option in the lighting section. Add on to the 3 ones with the legacy 2017 lighting. Not sure which phase you would set that too though.

It could look something this.
![Untitled](https://github.com/pizzaboxer/bloxstrap/assets/79861302/c25b2ae7-3393-44f2-b15e-2c92ce36beee)

**Comment by pizzaboxer** [comment]
Not possible. I would've added it if it was.
