### ISSUE TITLE
[BUG] Different key placement after using bloxstrap.

### ISSUE THREAD

**Issue by PowerusMaximus** [pizzaboxer/bloxstrap#1080]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My friend has Azerty keyboard, and is used to the old keys placements to other games and default roblox, but when he installed bloxstrap he been forced to switch to Qwerty movement placement, he has to learn from 0 which frustrated him a lot and is also confusing, like default roblox was normal nothing changed but when he used bloxstrap the key placement changed to qwerty, so is there a way to fix this?

**Comment by pizzaboxer** [comment]
Doesn't that depend entirely on your system settings though? If he plays [Roblox without Bloxstrap](https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap), does the same thing happen>

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
