### ISSUE TITLE
[BUG] Don't show Rendering mod settings in the FastFlags section

### ISSUE THREAD

**Issue by PauseTube** [pizzaboxer/bloxstrap#1081]
Don't show Rendering mod settings in the FastFlags section
![Screenshot (2)](https://github.com/pizzaboxer/bloxstrap/assets/155341763/17ecdd30-701b-47d6-9ba7-de160bee5067)

**Comment by pizzaboxer** [comment]
Read the [latest release notes please](https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4).
