### ISSUE TITLE
Bloxstrap authentication error [BUG] 

### ISSUE THREAD

**Issue by itsariyan77** [pizzaboxer/bloxstrap#1082]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

recently in the roblox website whenever i try to open the game with bloxstrap, it gives an error code saying
403 error occured was encountered during authentication
<img width="653" alt="Screenshot 2024-01-01 231631" src="https://github.com/pizzaboxer/bloxstrap/assets/75169533/54b657b8-39c6-4b50-9f05-3382d315ee2c">

**Comment by pizzaboxer** [comment]
That error is coming from Roblox. Go to %localappdata%\Roblox and delete the LocalStorage folder, then play a game.

**Comment by OhRisk** [comment]
I did exacly that and it still shows up with the same error

**Comment by pizzaboxer** [comment]
If you're not using a browser VPN, then do what I said again, but afterwards launch Roblox through the desktop app ('Play Roblox' shortcut on the desktop) instead of launching it from the website
