### ISSUE TITLE
[REQ] Bring back graphics renderer switcher

### ISSUE THREAD

**Issue by JSkes** [pizzaboxer/bloxstrap#1083]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Can you please bring back the renderer switcher? Having it on Automatic doesn't even let me go above 70 FPS, sometimes fluctuates down to 30 and below, it's just that bad. Before the update I had it on OpenGL, that gave me great performance, like 200+ FPS, unlike now. I've tried to set my lighting quality back to Voxel, but it doesn't make a difference, it's just super annoying to play now with lag spikes constantly getting in my way.

**Comment by d44df016fe28bc8d5974** [comment]
upgrade to the better superior version of 2.5.3

**Comment by pizzaboxer** [comment]
We will be bringing it back in the next update with a bunch of changes to it. For now, you can do this. Open the FastFlag editor, choose 'Import JSON', and enter this in the dialog box:

```json
{"FFlagDebugGraphicsPreferOpenGL": "True"}
```

**Comment by JSkes** [comment]
Alright, thanks a bunch. (Also sorry for the extremely late response I was out of town)
