### ISSUE TITLE
[REQ]  Add "None" to style settings

### ISSUE THREAD

**Issue by Findyourlimits** [pizzaboxer/bloxstrap#1084]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

As the title says.

**Comment by pizzaboxer** [comment]
What the hell would "none" be?

**Comment by Findyourlimits** [comment]
Hidden basically

**Comment by pizzaboxer** [comment]
Progress indicators exist for a reason, it doesn't make any sense to do that.

**Comment by pizzaboxer** [comment]
If Roblox is updating then it'll take much longer to launch, in which case people would be frustrated as to why nothing is happening, or in other circumstances where launch time may be longer. This doesn't make any sense.
