### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XticJosh** [pizzaboxer/bloxstrap#1085]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Ever since i started using Blox strap my sensitivity on my controller has been too high
if i use roblox without blox strap my controller's sensitivity is fine. is there something im doing wrong?

**Comment by pizzaboxer** [comment]
Can't you control that in the escape menu?

**Comment by XticJosh** [comment]
Thats the thing i tried that multiple times and the sensitivity stays the same when i open roblox with blox strap
