### ISSUE TITLE
[BUG] its either js me  

### ISSUE THREAD

**Issue by urslcking** [pizzaboxer/bloxstrap#1087]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

or idk but i cant seem to change my font or take it off 
![image_2024-01-03_230719304](https://github.com/pizzaboxer/bloxstrap/assets/155607073/be8c4027-8a30-42f1-afef-3ece67c133a7)

**Comment by pizzaboxer** [comment]
Preliminary instructions. Send the log file.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
