### ISSUE TITLE
[BUG] cant open neither uninstall. idk if its a me problem tho

### ISSUE THREAD

**Issue by ricobanks** [pizzaboxer/bloxstrap#1089]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.IO.IOException: The file or directory is corrupted and unreadable. : 'C:\Users\\AppData\Local\Bloxstrap\Logs'

**Comment by pizzaboxer** [comment]
Closing this since this is being helped with over Discord
