### ISSUE TITLE
Change Icon dropdown to Custom automatically

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#109]
If you choose a custom icon in the new update, it wont apply unless you set the icon dropdown to Custom. It would be nice for it to automatically set to Custom if you start typing into the path or use the Brows option

**Comment by pizzaboxer** [comment]
Oh, don't know how I missed out on this. The subtext tells you to set the icon to custom though, so this isn't that much of a problem.
