### ISSUE TITLE
[BUG] bloxstrap volume so low all of a sudden?

### ISSUE THREAD

**Issue by Inctavious** [pizzaboxer/bloxstrap#1090]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

since today when I have been using Bloxstrap it has been incredibly quiet in game with my volume input at 10 and all my pc volume stuff at max pls fix this its fine when I use normal ROBLOX

**Comment by axellse** [comment]
If your sure it's not like that without bloxstrap then check your fastflags. This does sound (pun not intended) like a Roblox issue tho.

**Comment by pizzaboxer** [comment]
Sounds like it could be something from there, show a picture of what FastFlags you have configured. Also, just make sure that it's not lowered in the Windows Volume Mixer.

**Comment by ShadowCodeX-debug** [comment]
@Inctavious send your **ClientAppSettings.json** file.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
