### ISSUE TITLE
Roblox doesn't open

### ISSUE THREAD

**Issue by lunartoc** [pizzaboxer/bloxstrap#1091]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i installed bloxstrap and set up everything i tried to boot into a game and it looked normal but i waited and waited and the game didint boot up.I tried to change some settings but nothing worked.Then when i uninstalled bloxstrap i tried to boot up into roblox normally and i couldnt i had to reinstall roblox also.I really want to use bloxstrap to boost my fps and use other features but I cant. Please adress this problem as fast as you can

**Comment by pizzaboxer** [comment]
If Roblox itself wasn't working either than that sounds like a problem with Roblox, not me. Just to ensure a correlation, can you reinstall Bloxstrap and see if the same thing happens again?

**Comment by lunartoc** [comment]
I reinstalled bloxstrap around 3 times and its still the same problem maybe its roblox's fault, maybe after an update they will fix that but for now i don't know.But the desktop app works normally tho it just doesnt work when i want to launch roblox from my browser

**Comment by pizzaboxer** [comment]
> But the desktop app works normally tho it just doesnt work when i want to launch roblox from my browser

That's a really weird problem, I'm not sure why that wouldn't be working. Just to confirm, you're launching Roblox through the "Play Roblox" shortcut, right?

**Comment by lunartoc** [comment]
Yes i was doing that but im gonna install bloxstrap again and try and i will update you soon

**Comment by lunartoc** [comment]
This time it worked.I don't know why but sorry for causing you trouble

**Comment by ricobanks** [comment]
its happening to me too, its a problem with bloxstrap for me.

**Comment by angeerey** [comment]
Same here. I've also reinstalled bloxstrap but roblox is still crashing.

**Comment by pizzaboxer** [comment]
@ricobanks @angeerey Can I confirm that both of you have tried without Bloxstrap too?

**Comment by angeerey** [comment]
Strange, i've restarted my PC and bloxstrap seems to work like normal again.

**Comment by BokBoy** [comment]
> Strange, i've restarted my PC and bloxstrap seems to work like normal again.

Sounds like a common case of pc restart time.
