### ISSUE TITLE
[REQ] Import JSON Changes

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#1092]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Instead of the user having to grab the JSONs contents and pasting them into a text field, the user would just have to select the JSON (or maybe a TXT?) and it automatically paste the contents inside a text field. 

The reason why I don't say it should just automatically 'OK' it is because it be easier to fix any errors in the JSON formatting.

**Comment by pizzaboxer** [comment]
I'm already planning to improve how FastFlags can be added/imported since it does admittedly suck right now. Though, these are some nice suggestions that I wouldn't have thought of.

**Comment by ShadowCodeX-debug** [comment]
Although you are planning on making 2.6.0 auto correct errors within an invalid json so I don’t really know if text field would be necessary anymore.

**Comment by pizzaboxer** [comment]
I actually already added that in 2.5.4, my bad. All it does is just add curly brackets if they're missing.

**Comment by ShadowCodeX-debug** [comment]
Ah alright then disregard, we do need the text field.

**Comment by ShadowCodeX-debug** [comment]
Btw why do you ignore the idea of adding json exporting? It be very simple for you to accomplish.

**Comment by pizzaboxer** [comment]
I took the issue that talked about that as someone asking for help, so I closed it after I helped him do what he wanted to do. I did think it was a good idea to add, but kind of forgot to add it to the todo list.

**Comment by ShadowCodeX-debug** [comment]
Ah okay.

**Comment by ShadowCodeX-debug** [comment]
Oh right I forgot add this to my request, are you able to make comments (“//hello”) work with json importing? (And also to make some “note” column in the json editor. I’ll understand if it’s not possible, but it would be cool.

**Comment by pizzaboxer** [comment]
JSON isn't designed to support comments, what do you mean they work? Anyway, I'll be adding readable notes to them at the top anyway (as key/value pairs at the very top) for warnings and stuff.

**Comment by ShadowCodeX-debug** [comment]
Yeah I found out they worked when I got muted (and I got muted again and still am) in the discord by Matt for posting a cas file without saying what it does. So I tried to put a comment into the json and it worked, I did research that it shouldn’t work but maybe Roblox made it so.

**Comment by axellse** [comment]
> Yeah I found out they worked when I got muted (and I got muted again and still am) in the discord by Matt for posting a cas file without saying what it does. So I tried to put a comment into the json and it worked, I did research that it shouldn’t work but maybe Roblox made it so.

It's improper syntax to have comments in json, but the parser Roblox uses maybe supports it.

**Comment by pizzaboxer** [comment]
If so, seems like [C# can handle them too](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.readcommenthandling?view=netcore-3.1#System_Text_Json_JsonSerializerOptions_ReadCommentHandling). I'll be ensuring that this works.

**Comment by bluepilledgreat** [comment]
closed because of recent updates
