### ISSUE TITLE
[BUG] "Acess Denied." 

### ISSUE THREAD

**Issue by mrbeaaaaaast** [pizzaboxer/bloxstrap#1093]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When updating or installing Roblox after a blackout (Roblox was not open) i encountered this error every time i attempted to open trough Bloxstrap, this is a Bloxstrap only problem.

Screenshot:

![image](https://github.com/pizzaboxer/bloxstrap/assets/140016958/6f5bc0ae-5aea-4a

Log file:

[AcessDeniedBLOXSTRAP.txt](https://github.com/pizzaboxer/bloxstrap/files/13847839/AcessDeniedBLOXSTRAP.txt)
72-b667-82ad2d6f74c9)

**Comment by BokBoy** [comment]
Can't see image??

**Comment by pizzaboxer** [comment]
Go to the `%UserProfile%\AppData\Local\Bloxstrap\Versions\version-48a28da848b7420d\content\textures\` path in the file browser, check the file properties for `ArrowCursor.png` and `ArrowFarCursor.png` and ensure they're not marked as read-only.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
