### ISSUE TITLE
[REQ] Custom death sound effect

### ISSUE THREAD

**Issue by KhaiKhem** [pizzaboxer/bloxstrap#1094]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

If you add custom death sound effect option, that would be great

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

Death sound is located at content\sounds\ouch.ogg. We might consider making this a little bit easier as a preset though.
