### ISSUE TITLE
FFlag Editor v2 (Possibly v3.0.0?)

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#1097]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I've had a few thoughts of this concept.

So my first idea is to make the FFlag Editor the main tab, removing the flag preset tab. If somebody adds a well-known flag (like "DFIntTaskSchedulerTargetFps"), it would put a info symbol next to the flag name, and when hovering the cursor over it, it displays info about that flag. (Also the Show Preset button obviously wouldn’t exist.)

The Add Flag button will add a new row to the flag editor instead. If a row’s name section is empty it will show a drop down (or something similar) that displays some well-known flags which you can select and once a flag is selected.

More to the idea, once a well known flag is selected. It would make you select a value in which a dropdown (or something similar) would appear, which shows options for the specific flag. For example, if "DFIntTaskSchedulerTargetFps" is selected it would show the following options: Default (0), Synchronize (Your refresh rate), infinite (9999).

Next idea is the FFlag Editor being able to recognize flag types: Booleans, Integers, and String FastFlags, and putting their respective value types (toggles for FFlags, a text field or something else for FInts, and text fields for FStrings).

The current style of the Editor is nice so I don't really want anything to change in the style.
 
 My changes to the importing feature (#1092) would be included.

This seems a bit too much to accept right off the bat so I think this suggestion would be for like 3.0.0

**Comment by ShadowCodeX-debug** [comment]
I have too many ideas tbh, whenever I come across something I like (e.g. Bloxstrap) I think of a whole lotta ideas to make it better.

**Comment by ShadowCodeX-debug** [comment]
(A little edit to my first idea if you think it's a bit to much, is to just swap the so the Flag Editor would be first and the preset tab would just be in a sub-tab)

**Comment by pizzaboxer** [comment]
> removing the flag preset tab.

I'm sorry? Why would you want to do such a thing?

This entire suggestion is terrible and heavily compromises on user experience. Flag presets being shown prominently and upfront while the flag editor is quietly hidden away is done for a reason. How is a user being presented with "DFIntTaskSchedulerTargetFps" for a setting's name within a dense list format and important info being hidden away an improvement over "Framerate limit" with important information being shown upfront?

**Comment by ShadowCodeX-debug** [comment]
Well @pizzaboxer are you gonna consider the other idea...? The only things you've mentioned is about half of my request.

**Comment by pizzaboxer** [comment]
As I said in the other issue you mentioned, I am already planning to improve how FastFlags can be added/imported, and that included checking for valid flag types as you mentioned. Though, it's not clear if it's possible for me to change what type of input can be given here.

**Comment by ShadowCodeX-debug** [comment]
> As I said in the other issue you mentioned, I am already planning to improve how FastFlags can be added/imported, and that included checking for valid flag types as you mentioned. Though, it's not clear if it's possible for me to change what type of input can be given here.

Alright, thank you for responding.
