### ISSUE TITLE
Error fix?

### ISSUE THREAD

**Issue by Mlaofmd** [pizzaboxer/bloxstrap#11]
Hello, need change client to ZCanary, I clicking edit and giving that error. What is that and I can fix that?
screenshot on russain nvm
![п](https://user-images.githubusercontent.com/52864321/187213705-71f2b0c4-9f6d-4c17-95fc-62e58e55eb0c.png)

**Comment by pizzaboxer** [comment]
What did you click on?

**Comment by Mlaofmd** [comment]
> What did you click on?

Edit on control panel
![й](https://user-images.githubusercontent.com/52864321/187235860-38031c7f-0abb-4f93-9dab-dd9ef75fc4d2.png)

**Comment by pizzaboxer** [comment]
Does the "Configure Bloxstrap" option in the start menu do the same thing?

**Comment by pizzaboxer** [comment]
Closed due to inactivity.
