### ISSUE TITLE
Custom icon should replace the Bloxstrap logo and Roblox logo

### ISSUE THREAD

**Issue by ayvacs** [pizzaboxer/bloxstrap#110]
When you change the icon in Bloxstrap settings, apply that icon everywhere.

i.e. I selected the late 2015 icon, but the Bloxstrap logo and 2023 Roblox logo still appear.

![image](https://user-images.githubusercontent.com/74518502/224871008-d96eae9e-c1b2-4978-ac47-fb22dbb39ec0.png)
![image](https://user-images.githubusercontent.com/74518502/224871066-72623635-2dd2-44ab-8cef-86cb25ddd93a.png)

Furthermore, would it be possible to change the Roblox icon in the top left corner of the screen ingame? (the one that you click to open the Esc menu)

**Comment by pizzaboxer** [comment]
> When you change the icon in Bloxstrap settings, apply that icon everywhere.
See #9.

> Furthermore, would it be possible to change the Roblox icon in the top left corner of the screen ingame? (the one that you click to open the Esc menu)
Yeah, take a look at the help information on [creating custom mods](https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods). The icon is located somewhere in the content folder, you'll have to look for it. I'll update the guide to make it clearer on what you have to do to actually get started with modding.
