### ISSUE TITLE
[BUG] Bloxstrap wont let me join server

### ISSUE THREAD

**Issue by jake75552** [pizzaboxer/bloxstrap#1100]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Yes, i have tested it without bloxstrap and it works fine, but with bloxstrap it prevents me from joining servers.
It just gets stuck on the Joining server screen..

**Comment by pizzaboxer** [comment]
Can I see what FastFlags you have configured? Show a picture of the FastFlag editor.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
