### ISSUE TITLE
[REQ] FastFlag Pausing

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#1101]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Quite simple tbh, a button in the Bloxstrap Menu that if pressed, will stop fastflags/ClientAppSettings from being loaded when Roblox launches.

**Comment by pizzaboxer** [comment]
This is already planned to be added since this is going to be necessary for troubleshooting problems and stuff.

**Comment by bluepilledgreat** [comment]
closed because of recent updates
