### ISSUE TITLE
[BUG] Custom Cursor Reverting

### ISSUE THREAD

**Issue by Bvbble** [pizzaboxer/bloxstrap#1103]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I customize my cursor inside of Bloxstrap, after about a week it's gone. I know this happens with Roblox items but it shouldn't be happening with Bloxstrap. I haven't changed the mouse settings, I left it on default. All I did was change the cursor in Bloxstrap's modification settings.

**Comment by Bvbble** [comment]
I worded that really wrong. I haven't changed the mouse settings inside of Bloxstrap. A week ago, I changed the mouse to what I wanted it to be.

**Comment by pizzaboxer** [comment]
Do you see the Bloxstrap launcher show whenever you launch Roblox? Are your other things (old death sound, etc) applying too?

**Comment by Bvbble** [comment]
I do see the Bloxstrap launcher every time I launch Roblox. I don't have anything else enabled.

**Comment by pizzaboxer** [comment]
In the mods folder, can you confirm that the cursor you've placed is still there? Show a screenshot of it in the folder.

**Comment by Bvbble** [comment]
I put the cursor back, I'll show you it.
![image](https://github.com/pizzaboxer/bloxstrap/assets/147776194/7d48e96b-363e-4c03-9400-60ab43d650f3)

**Comment by pizzaboxer** [comment]
And when you launch Roblox, you don't see your custom cursor? Open the `%localappdata%\Bloxstrap\Logs` folder, get the latest log file (either at the top or bottom of the list) and send it here.

**Comment by Bvbble** [comment]
No, I know see the custom cursor. The cursor reverted back to normal when Roblox updated. I put back the cursor. I will send you the latest log file.
[Bloxstrap_20240108T004133Z.log](https://github.com/pizzaboxer/bloxstrap/files/13943780/Bloxstrap_20240108T004133Z.log)

**Comment by pizzaboxer** [comment]
> The cursor reverted back to normal when Roblox updated.

Sounds like it skipped over the mod check when updating Roblox because it detrected it still running in the background. In which case, if you encounter it again, be sure that it's not before you try launching.
