### ISSUE TITLE
[BUG] When launching Bloxstrap, it redirects to Roblox website

### ISSUE THREAD

**Issue by KILLERGAMER3** [pizzaboxer/bloxstrap#1104]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When launching Bloxstrap, it redirects me to the roblox.com/home website.

**Comment by pizzaboxer** [comment]
You've opted to disable the desktop app in the Mods section of the Bloxstrap Menu. Re-enable it if you want to use the desktop app.
