### ISSUE TITLE
[BUG] Reset callback is not changed when using a different menu version

### ISSUE THREAD

**Issue by LordUnadmin** [pizzaboxer/bloxstrap#1105]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have a game where I change the reset callback function to a custom one (StarterGui:SetCore("ResetButtonCallback", BindableEvent)) and it seems that when changing the menu fastflag, the custom callback does not work and uses the default Roblox callback instead, judging by it i believe it's a Roblox problem Bloxstrap cannot fix, but I believe its worth the heads up.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version

> Keep in mind that Roblox does not maintain any menu versions older than 2023 anymore, so some of the buttons and controls may not work properly. Minor visual or usability problems with them are to be expected.
