### ISSUE TITLE
[REQ] ADD rendering mode back 

### ISSUE THREAD

**Issue by viberblx83** [pizzaboxer/bloxstrap#1106]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

my roblox lags and when 2.53 version not lags because its have rendering mode when i set directx10

**Comment by pizzaboxer** [comment]
You can opt back into using Direct3D 10 manually by opening the FastFlag editor, selecting 'Import JSON', and then pasting this in:
```json
{"FFlagDebugGraphicsPreferD3D11FL10": "True"}
```
Let me know if you need any help with it.
