### ISSUE TITLE
[BUG] This may not be a bug but I'm not sure

### ISSUE THREAD

**Issue by JSkes** [pizzaboxer/bloxstrap#1107]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Why do I have debug options shown in my Bloxstrap? Is it a key combination I accidentally pressed or something?
![image](https://github.com/pizzaboxer/bloxstrap/assets/71411219/4991dab4-32f3-447a-9919-18a867af0fd6)
![image](https://github.com/pizzaboxer/bloxstrap/assets/71411219/2421719c-a149-4bab-b47a-f19ba3e0c7d1)

**Comment by pizzaboxer** [comment]
You didn't happen to manually edit Settings.json to enable a certain property that you thought looked interesting, did you?

**Comment by JSkes** [comment]
No? Is that Settings file in the Bloxstrap installation folder? I want to turn this off.

**Comment by JSkes** [comment]
Okay so it is in the installation folder and by "property that looked interesting" do you mean "OhHeyYouFoundMe", by chance?

**Comment by pizzaboxer** [comment]
Yes, yes I do.

**Comment by JSkes** [comment]
Okay, I've turned it off and now it's fixed. Thank you!
