### ISSUE TITLE
[BUG] System.OverflowException: ...

### ISSUE THREAD

**Issue by MeeIIs635** [pizzaboxer/bloxstrap#1108]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Upon installation, I encounter this bug: **System.OverflowException: Arithmetic operation resulted in an overflow.**
![image](https://github.com/pizzaboxer/bloxstrap/assets/86620152/ecabde80-6837-4e91-a47e-4052f0ec53c2)

**Comment by pizzaboxer** [comment]
Where's the log file?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
