### ISSUE TITLE
[REQ] Bloxstrap Verified System

### ISSUE THREAD

**Issue by corruptedgh** [pizzaboxer/bloxstrap#1109]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So, you see, there's this cool idea which is basically useless but would like for to be around, there's an FFlag that allows you to whitelist people as verified, and you see them as verified with the verified symbol from video stars, what if it sent a request to a github repo let's say before entering roblox and sets it in the clientsettings.json with all the ids from the github repo? (so that it's updated no matter what) and people can be verified with everyone using Bloxstrap seeing them as verified? I know this is useless but I wanted somewhere to put my idea in, I don't think this is a good idea and it would ruin the entire purpose of verifying, maybe if you added a few walls, like using it only for identifying people that are important in the community.

Anyways, enough yapping, this is the FFlag: ``"FStringWhitelistVerifiedUserId": "1",``
![image](https://github.com/pizzaboxer/bloxstrap/assets/140978878/9ecd753b-dcb1-46f7-b508-3e8208559779)

**Comment by pizzaboxer** [comment]
no
