### ISSUE TITLE
Stuck on Applying Roblox Modifications while downloading

### ISSUE THREAD

**Issue by bruhmoment226022** [pizzaboxer/bloxstrap#1110]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im stuck on this screen while downloading
![image_2024-01-13_113907076](https://github.com/pizzaboxer/bloxstrap/assets/132979895/92a8bfe6-816f-4d97-aeeb-9877495ceae0)

**Comment by pizzaboxer** [comment]
Seems like it might have screwed up somewhere on that stage. Terminate it in Task Manager, run it again, and it should work.

**Comment by pizzaboxer** [comment]
Assuming this has been resolved, please reopen if it hasn't.
