### ISSUE TITLE
[BUG] While im in a game, like after 20 - 30 minutes i crash (or even 10 - 5 minutes)

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1112]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

after like 20 - 30 (or 10 - 5) minutes, i crash for no reason and the players will vote me off the game (total roblox drama) bc i left, BUT I DIDNT MEAN IT TO LEAVE, ITS BLOXSTRAP!!!

**Comment by pizzaboxer** [comment]
Does this happen every time you play? You should confirm if it's really Bloxstrap causing this, try a play session without using Bloxstrap and see if you encounter any crashes. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by githubberguy** [comment]
yes, i use msii, and its not the real game roblox client, its only bloxstrap, it crashes every (20 - 30 - 10 - 5) minutes (the minutes are random) it happens when i join an "instance"

**Comment by githubberguy** [comment]
yeah but i dont wanna really use normal roblox, i need bloxstrap forced, bc i need old menus

**Comment by pizzaboxer** [comment]
Can I see what FastFlags you have configured? Show a screenshot of the FastFlag editor in the Bloxstrap Menu.

**Comment by githubberguy** [comment]
> Can I see what FastFlags you have configured? Show a screenshot of the FastFlag editor in the Bloxstrap Menu.

sure omg i was sleeping

**Comment by githubberguy** [comment]
![Uploading Screenshot 2024-01-19 162651.png…]()

**Comment by githubberguy** [comment]
![Screenshot 2024-01-19 162620](https://github.com/pizzaboxer/bloxstrap/assets/145132255/e38fb751-0db0-4b2a-a61a-a64ee6e537c5)
![Screenshot 2024-01-19 162629](https://github.com/pizzaboxer/bloxstrap/assets/145132255/eb449aef-5edb-4963-b484-4616cb364287)
![Screenshot 2024-01-19 162634](https://github.com/pizzaboxer/bloxstrap/assets/145132255/c419c0e3-9558-49e9-b8eb-005849ea51dd)
![Screenshot 2024-01-19 162639](https://github.com/pizzaboxer/bloxstrap/assets/145132255/e8d87221-9d55-4f90-9296-71fe7058eb3e)

**Comment by pizzaboxer** [comment]
Can you try removing all the flags you have set (Ctrl+A and then delete), and then try playing Roblox, and see if it works? You can back up your current flag config by opening the mods folder, going into the ClientSettings folder and copying ClientAppSettings.json somewhere else.

**Comment by githubberguy** [comment]
ok, i tried and it didnt work.. is this a MSII Problem? Or is it a MSII Bloxstrap not fixed for crashes, or is it my shitty windows 11 msii??

**Comment by pizzaboxer** [comment]
> ok, i tried and it didnt work

Can you just quickly confirm something, open the `%localappdata%\Bloxstrap\Logs` folder and send the latest log file here please.

**Comment by githubberguy** [comment]
this one happened right now:
![Uploading Screenshot 2024-01-20 171731.png…]()

**Comment by githubberguy** [comment]
![Screenshot 2024-01-20 171731](https://github.com/pizzaboxer/bloxstrap/assets/145132255/e706d641-f246-40de-bcc7-ac595fcb7869)

**Comment by pizzaboxer** [comment]
Yes, send the latest file here.

**Comment by githubberguy** [comment]
yeah i sent it

**Comment by CalebStevens0714** [comment]
if it helps, this has been happening to me to, sometimes it would crash when i just start the game

**Comment by pizzaboxer** [comment]
> yeah i sent it

**Comment by githubberguy** [comment]
you cant send files'??

**Comment by pizzaboxer** [comment]
> you cant send files'??

? 

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/503fd3d9-bdde-4a1e-9875-d0c064f140c5)

**Comment by bluepilledgreat** [comment]
No response for a month
