### ISSUE TITLE
fps ulocker not working

### ISSUE THREAD

**Issue by ShyKamcio** [pizzaboxer/bloxstrap#1114]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Im getting no fps unlock only down drop to 40 fps or maybe sometimes 60 Its so flustrating bc i did try everything and there is no help to do this and i tried rfo and it worked and fps unlocker and it worked to so please fix this bug

**Comment by pizzaboxer** [comment]
Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
