### ISSUE TITLE
I cannot launch the application because of this error, I do not know what I have .NET [BUG] 

### ISSUE THREAD

**Issue by timon666rt3** [pizzaboxer/bloxstrap#1116]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

you must install .NET

**Comment by cricketgoldYT** [comment]
You have to download this: https://dotnet.microsoft.com/en-us/

**Comment by AngryRico** [comment]
You didnt read the preliminary instructions, stop making issues for no reason when the fix is right on the github's starting page.

**Comment by pizzaboxer** [comment]
> you must install .NET

Then install it. You're brought to the download page when you click "yes" on the dialog box.
