### ISSUE TITLE
[BUG] I cannot remove a font

### ISSUE THREAD

**Issue by cricketgoldYT** [pizzaboxer/bloxstrap#1117]
it wont let me delete the custom font

**Comment by cricketgoldYT** [comment]
[Bloxstrap_20240114T113608Z.log](https://github.com/pizzaboxer/bloxstrap/files/13931260/Bloxstrap_20240114T113608Z.log)

**Comment by pizzaboxer** [comment]
Open the mods folder, go inside content -> fonts, open the file properties for CustomFont.ttf and ensure that it's not marked as read-only.

**Comment by cricketgoldYT** [comment]
It worked, thanks

**Comment by cricketgoldYT** [comment]
[CLOSED]
