### ISSUE TITLE
[REQ] Compatibility

### ISSUE THREAD

**Issue by randompersonhello21** [pizzaboxer/bloxstrap#1118]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

add Compatibility to prefered lighting technology

**Comment by d44df016fe28bc8d5974** [comment]
not possible

**Comment by randompersonhello21** [comment]
why?

**Comment by AngryRico** [comment]
because its just not

**Comment by pizzaboxer** [comment]
> why?

There isn't a way to externally enable it unlike the other lighting modes.
