### ISSUE TITLE
Suggestion: Ability to force Roblox to open on the second monitor without manually forcing to move the client window to the second monitor. 

### ISSUE THREAD

**Issue by AngryBirdsFanboy06** [pizzaboxer/bloxstrap#112]
I want to play Roblox on the Second monitor, since that's the monitor i use to play games on.
Sadly Roblox made it if the client is maxed windowed, it will automatically open in the main display instead of any display you choose to open.
I legit have to play Roblox "windowed" mode but try to make it look like its maxed windowed.

It would be cool if Bloxstrap had this feature. I think it would improve the gameplay of Roblox a lot.

**Comment by pizzaboxer** [comment]
There's not really anything Bloxstrap can do about this, but you're saying full screening on your second monitor makes it full screen on your primary monitor?

**Comment by AngryBirdsFanboy06** [comment]
Yea, if i make roblox be maxed windowed, and then i quit roblox and start it again, it goes to the primary display. Btw im talking about maxed out windows, not full screen.

**Comment by pizzaboxer** [comment]
Oh. What's wrong with just... moving it to your other screen? I'm pretty sure that's how every application launches.

**Comment by AngryBirdsFanboy06** [comment]
I tried it but it only works on non maxed out windows, other programs like photoshop, firefox and etc are able to automatically launch in maxed windowed in a second display, but both roblox player and roblox studio dont, plus my monitors have different sizes, so it makes roblox gui on the second monitor larger, i did found a fix for it but its annoying to be honest.

**Comment by pizzaboxer** [comment]
I'm still not really understanding. Whenever Roblox opens on your primary display, can't you just move it over to your second dispaly and maximise it there? Why does it have to be windowed on your second display?
Is the problem just that Roblox doesn't show on your second display automatically when it's maximised?

**Comment by AngryBirdsFanboy06** [comment]
Yea, it automatically moves to primary, i think roblox was never designed with multiple displays. Its honestly weird.

**Comment by pizzaboxer** [comment]
Sorry, but there's really nothing Bloxstrap can do about this. You've just got to move it over to your second display by yourself, which, if I'm being honest, really isn't that big of a deal. If it's annoying for you, here's some shortcuts that you can use to just do it quickly.

Windows + Shift + Left/Right Arrow - Move window to other display
Windows  + Up Arrow - Make windowed application maximised

Believe me, do this enough times and it'll basically become second nature to you.

**Comment by AngryBirdsFanboy06** [comment]
Ok thanks
