### ISSUE TITLE
[BUG] Roblox is crashing and freezing every 10 minutes 

### ISSUE THREAD

**Issue by shinez2202** [pizzaboxer/bloxstrap#1120]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I recently downloaded Bloxstrap and now Roblox is freezing and crashing every 10 minutes. I have zero idea why it's doing this.

**Comment by axellse** [comment]
Does it happen with the stock Roblox bootstrapper?

**Comment by shinez2202** [comment]
It doesn't happen anymore. Thanks anyway!
