### ISSUE TITLE
File is detected as malware when reviewed under VirusTotal. Please address.

### ISSUE THREAD

**Issue by LadyNoirality** [pizzaboxer/bloxstrap#1121]
Link to file sample downloaded to test. Version is current.
https://www.virustotal.com/gui/file/b2ac1e407ed3ecd7c7faa6de929a68fb51145662cf793c40b69eb59295bba6bc

**Comment by kingdempa** [comment]
i swear to god if you dont know about false positives

**Comment by LadyNoirality** [comment]
Not accusing the software of being malicious. Just reporting that the exe file showed up as malicious on a few other services, VirusTotal was just the initial one I reported.

**Comment by pizzaboxer** [comment]
> Just reporting that the exe file showed up as malicious on a few other services, 

Yes, I am well aware. I can't really do anything about this, nor should this ever really matter to anyone (seriously what the hell is "Bkav Pro"?).
