### ISSUE TITLE
[REQ] Customizable avatar background thing

### ISSUE THREAD

**Issue by jmxamongusmodder** [pizzaboxer/bloxstrap#1123]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So uh i dont like how it replaces it whenever i make my own (i believe the file is Mobile.rbxl) but uh i wanna use my own cuz i spent SO LONG making it and then i cant even use it
not fair mate

**Comment by pizzaboxer** [comment]
Preliminary instructions. Did you read through the Wiki at all?

https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

> An important thing to keep in mind is that you should disable any mod presets that may conflict with the files you've added (e.g. death sound, mouse cursor), as presets take priority over any files present. If the preset is configured with a dropdown selection, leave it on Default.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
