### ISSUE TITLE
[REQ] TopBar And Chat Type

### ISSUE THREAD

**Issue by iForestal** [pizzaboxer/bloxstrap#1125]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Customization for TopBar and Chat to 2015 and 2024, if is too hard so don't make it

**Comment by pizzaboxer** [comment]
Not possible, sorry. https://github.com/pizzaboxer/bloxstrap/issues?q=is%3Aissue+old+topbar

**Comment by Blue-Star-Technology** [comment]
i wanted this feature too i will never be able to bring back old roblox :(
