### ISSUE TITLE
Fastflags not working. [BUG] 

### ISSUE THREAD

**Issue by askerad2r23** [pizzaboxer/bloxstrap#1126]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

None of the fastflags work, any fix?

**Comment by pizzaboxer** [comment]
Are your mods applying (old death sound, etc)?

**Comment by askerad2r23** [comment]
Yep

**Comment by askerad2r23** [comment]
any help owner?
much appreciated.

**Comment by pizzaboxer** [comment]
Which ones are you trying to use that aren't working?

**Comment by xNumox** [comment]
I'm experiencing the same issue currently. I was launching ROBLOX using Bloxstrap and couldn't get the FFlags to work at all. Same issue occurred when launching from the website. I was using FPS Unlocker and Alt enter fullscreen.

My discord is begfoot if you have any other questions and I don't respond to this.

**Comment by bluepilledgreat** [comment]
closed because of recent updates
