### ISSUE TITLE
how do i change settings after i've already put them?

### ISSUE THREAD

**Issue by alepalex** [pizzaboxer/bloxstrap#1127]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

because it twice (even when i had what i should have) it failed, i decided to basically speedrun making it as i want to save time, forgeting some of the other ones i wanted, causing me to ask this

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
