### ISSUE TITLE
[BUG] fps not limiting

### ISSUE THREAD

**Issue by MOvepIzZAA** [pizzaboxer/bloxstrap#1128]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So I have recently downloaded blox strap thinking it would fix my Roblox lag problem but when I put my fps unlocked to 255 it didn’t work I still had 30-60 fps I tried to restart computer but it didn’t work please help

**Comment by codingfirewastaken** [comment]
thats not how fps unlockers work, they do not directly increase your FPS.

**Comment by axellse** [comment]
ass @codingfirewastaken said, if you get under 60fps with normal roblox, then its not roblox limiting your fps, its just your pc struggling to get higher framerates. You can however try to find flags to make roblox run smoother (like removing textures).

**Comment by pizzaboxer** [comment]
> thinking it would fix my Roblox lag problem

That's not what it does. If you're not reaching past 60 then you of course won't be reaching 255.
