### ISSUE TITLE
[BUG] When i wanna play Roblox It's Freezing and then it says it Crashed. What can i do?

### ISSUE THREAD

**Issue by biomis** [pizzaboxer/bloxstrap#1129]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I use bloxstrap with Framerate Limit and Old Textures.

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
