### ISSUE TITLE
Windows Defender flags Bloxstrap for Defense Evasion

### ISSUE THREAD

**Issue by MineatomTR** [pizzaboxer/bloxstrap#113]
![image](https://user-images.githubusercontent.com/43916299/225072314-93ef48df-13f3-4fc1-acb6-d708392d243d.png)

Completely deletes all files related to Bloxstrap after that, got any explanation on why this happens?

**Comment by MineatomTR** [comment]
It seems like the actual program files remained after I whitelisted Bloxstrap then relaunched the exe. Still odd though

**Comment by pizzaboxer** [comment]
oh god damn it this is still happening
if you allowed it and bloxstrap works fine now, then yeah it shouldn't be detected again hopefully
