### ISSUE TITLE
[BUG] ERROR CODE 403 WHEN LAUNCHING FROM ROBLOX WEBSITE AND EXCEPTION OCCURED ERROR

### ISSUE THREAD

**Issue by weebokun** [pizzaboxer/bloxstrap#1130]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Error code 403 when trying to open Roblox from Roblox website with Bloxstrap (Roblox.com, game, launch, bloxstrap opens, loads, error code 403) 
If not error code 403 then this error opens: an exception has occured while running bloxstrap
System.Net.Http.HttpRequestException: An error occurred while sending the request.

[Inner Exception]
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

[Inner Exception]
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.

[
[Bloxstrap_20240115T155425Z.log](https://github.com/pizzaboxer/bloxstrap/files/13940787/Bloxstrap_20240115T155425Z.log)
](url)

**Comment by pizzaboxer** [comment]
> Error code 403 when trying to open Roblox from Roblox website with Bloxstrap

This error is coming from Roblox itself and doesn't have anything to do with Bloxstrap. Open the Roblox desktop app by launching the 'Play Roblox' shortcut that's on the desktop, log out of your account there and stay logged out, then try and launch from the website. If that doesn't work then you will just have to launch Roblox through the desktop app.

>  If not error code 403 then this error opens: an exception has occured while running bloxstrap

This seems like your internet connection is being interrupted. You'll just have to relaunch whenever this happens.

**Comment by pizzaboxer** [comment]
Assuming this has been resolved, please reopen if it hasn't.

**Comment by 2023SMHrailwaygames** [comment]
I got banned for one day. I tried to log out but I'm stuck on the ban screen bloxstrap. I got banned for saying "I hate furry." 
I try desktop and web but no work.
