### ISSUE TITLE
[BUG]  Bloxstrap not downloading or being installed due to a " Bloxstrap exception ".

### ISSUE THREAD

**Issue by Cleacher** [pizzaboxer/bloxstrap#1134]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm trying to install Bloxstrap and it's not working, an error popup keeps occuring saying that " An exception occured while running Bloxstrap ", telling me to report it through a Github issue or Discord, along with a copy of the logfile that was created, which is this.
[Bloxstrap_20240114T101121Z.log](https://github.com/pizzaboxer/bloxstrap/files/13943934/Bloxstrap_20240114T101121Z.log)

**Comment by pizzaboxer** [comment]
This is not the correct log file, this one is from yesterday and shows no errors. Send the correct one please.

**Comment by Cleacher** [comment]
> This is not the correct log file, this one is from yesterday and shows no errors. Send the correct one please.

Right, my bad, I deleted Bloxstrap and tried again and the error popped up again, here's the correct one.
[Bloxstrap_20240116T222900Z.log](https://github.com/pizzaboxer/bloxstrap/files/13956359/Bloxstrap_20240116T222900Z.log)

**Comment by pizzaboxer** [comment]
Open the `%localappdata%\Bloxstrap` folder, delete the folder named `Versions`, then try and launch again and see if that fixes it.

**Comment by Cleacher** [comment]
Well that didn't work as planned-
[Bloxstrap_20240117T003210Z.log](https://github.com/pizzaboxer/bloxstrap/files/13957054/Bloxstrap_20240117T003210Z.log)

**Comment by Cleacher** [comment]
It also wont let me open roblox up at all, comes up with an error notification saying " Error Code: 403 An error was encountered during authentification. Please try again. " I don't know whats happening anymore

**Comment by pizzaboxer** [comment]
> Well I deleted the folder now it's showing another error for a different folder

...Did you mark everything in the folder as read-only? Open the `%localappdata%` folder, open the properties for the Bloxstrap folder and ensure the read-only attribute is disabled.

> Error Code: 403 An error was encountered during authentification. Please try again.

Are you launching from the website? Try launching Roblox through the Desktop app with the 'Play Roblox' shortcut.

**Comment by Cleacher** [comment]
oh my goodness you saved my life i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much i love you so much

**Comment by pizzaboxer** [comment]
Alright, I'm taking that as being resolved.

**Comment by doggy12345-cmyk** [comment]
bro mine is saying System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

what do i do
