### ISSUE TITLE
[BUG] Annoying Bar at the top of screen, cant enter fullscreen F11/Alt+Enter dont work

### ISSUE THREAD

**Issue by Slammpreal** [pizzaboxer/bloxstrap#1135]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I am in a game a bar shows as if its windowed and is annoying me Alt+enter, F11 dont seem to work. >:(
![Screenshot 2024-01-15 214900](https://github.com/pizzaboxer/bloxstrap/assets/134972959/c4396f78-c338-47dc-8ff7-91e2769aee5b)

**Comment by OrphanObliterator** [comment]
does it happen without bloxstrap?

**Comment by Slammpreal** [comment]
When I dont use Bloxstrap fullscreen works completely fine

**Comment by pizzaboxer** [comment]
Can you show a screenshot of the FastFlag editor in the Bloxstrap Menu please?

**Comment by Slammpreal** [comment]
Here, I watched a video that told me how to add a FastFlag to fix the issue. Sadly it didn't work.
![Screenshot 2024-01-16 184203](https://github.com/pizzaboxer/bloxstrap/assets/134972959/ea1cd964-b705-4487-9329-11422ceb6067)

**Comment by pizzaboxer** [comment]
What about the fullscreen option in the ingame escape menu? Can you try setting toggling it there?

**Comment by Slammpreal** [comment]
I tried doing that it has no effect to the window whatsoever

**Comment by pizzaboxer** [comment]
Have you opted to disable fullscreen optimizations in the mods section of the menu?

**Comment by Slammpreal** [comment]
Just tried that, did nothing.

**Comment by Slammpreal** [comment]
Oh wait nvm it fixed it thanks
