### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by scriptto** [pizzaboxer/bloxstrap#1138]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

An exception eccurred while running Bloxtrap plz help to fix this

**Comment by AngryRico** [comment]
Give more information, you also didnt read the preliminary instructions you dumbass loser.
Here you go idiot, this might help you: https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox

**Comment by pizzaboxer** [comment]
What's the error? You didn't show what the error was.

**Comment by scriptto** [comment]
roblox not install

**Comment by scriptto** [comment]
error fix is ok roblox install
