### ISSUE TITLE
[BUG] my mistake ;-;

### ISSUE THREAD

**Issue by Hanzreyn** [pizzaboxer/bloxstrap#1139]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I cant use Shift lock whenever i use Bloxstrap even when i reinstall it still wont work

**Comment by AngryRico** [comment]
How about you add an image or some footage?

**Comment by pizzaboxer** [comment]
Is it enabled in game settings?

**Comment by icymanred** [comment]
> Is it enabled in game settings?

🤓🤓🤓

**Comment by Hanzreyn** [comment]
ooops im sorry it seems its my pc the one is having the problem not the bloxstrap sorry...
