### ISSUE TITLE
[BUG] mods and settings are not applying in the installed bloxstrap roblox app

### ISSUE THREAD

**Issue by kokkokarre** [pizzaboxer/bloxstrap#1140]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?
the mods and the settings are not applying to the installed bloxstrap roblox app

**Comment by pizzaboxer** [comment]
Do you see the Bloxstrap launcher show whenever you launch Roblox?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by CutieJieum** [comment]
So i was testing cursors and emoji types and then when i set them to the lowest one, it was kinda mid so i was going to to change them to default and save it but it didnt work how can i fix this?
