### ISSUE TITLE
[BUG] How to I open the bloxstrap menu? It only launches roblox

### ISSUE THREAD

**Issue by raidenismotymym12** [pizzaboxer/bloxstrap#1142]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i click bloxstrap menu it only launches roblox and i cant see the menu

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

You were told about this when you first installed it.
