### ISSUE TITLE
[BUG] the ui is very broken for me for whatever reason

### ISSUE THREAD

**Issue by Stormyplex** [pizzaboxer/bloxstrap#1145]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/118007511/ace9f510-0b0b-4cad-a821-88d42194fe95)
 
![image](https://github.com/pizzaboxer/bloxstrap/assets/118007511/b7f15d8b-9482-4c9d-9df6-d04093ea59c9)
this sort of bug continues for every section of the menu
this is my first time installing it and yes i have all the requirements such as .NET 6 Desktop Runtime

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/issues/1035#issuecomment-1858774554

See what I said here. I can't do anything about this, be sure you don't have anything running that could potentially be causing this.

**Comment by Stormyplex** [comment]
i dont have anything running apart from my antivirus in the background

**Comment by pizzaboxer** [comment]
Nothing that can potentially provide graphics overlays?

**Comment by Stormyplex** [comment]
i dont think so

**Comment by pizzaboxer** [comment]
Well, I'm afraid that I can't really do much for you. All I can say is that there is definitely something running in the background that's causing this conflict. Sorry.
