### ISSUE TITLE
Extremely High Ping when fps is unlocked[BUG] 

### ISSUE THREAD

**Issue by NauniV** [pizzaboxer/bloxstrap#1149]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever my fps is unlocked my ping skyrockets to the thousands. I'm pretty sure its just the fps unlocker causing this.

**Comment by pizzaboxer** [comment]
> Whenever my fps is unlocked my ping skyrockets to the thousands. I'm pretty sure its just the fps unlocker causing this.

What do you have it set to? Ideally you should have it set to your main display's refesh rate, and not have it set to anything higher than 300. Ignore that subtext saying to set it to 9999, that's old bad advice that I haven't yet removed.

**Comment by NauniV** [comment]
When I have it set to my monitor's refresh rate, 240, the ping skyrockets. Having it at 0 fixes the ping issue, but I want them frames unlocked.

**Comment by pizzaboxer** [comment]
> Having it at 0 fixes the ping issue, but I want them frames unlocked.

You'll have to pick one or the other. It's a rare side-effect of unofficially unlocking the framerate limit. If you set it to something closer to 60 (i.e. 120), does it still happen?

**Comment by NauniV** [comment]
The same thing happens but to a lesser extent, doesn't go into the thousands anymore, but the high hundreds. This is a rare side effect? So not everyone has this same problem with their fps unlocker?

**Comment by pizzaboxer** [comment]
> This is a rare side effect? So not everyone has this same problem with their fps unlocker?

Yep.
