### ISSUE TITLE
how can i uninstall this easily?

### ISSUE THREAD

**Issue by Timurknk** [pizzaboxer/bloxstrap#115]
i cant seem to find a uninstall button anywhere for bloxstrap. maybe there is one but idk where the location of it is. every time i wanna delete bloxstrap, (because i sometimes do modifications on the client and it doesnt work when bloxstrap is there) i always need to uninstall roblox entirely. please sum1 help.

**Comment by pizzaboxer** [comment]
[Uninstall it like how you'd normally uninstall any other program](https://github.com/pizzaboxer/bloxstrap/wiki/Uninstalling-Bloxstrap).
