### ISSUE TITLE
[BUG] bloxstrap installer instantly freezing when reaching the "Applying Roblox Modifications" phase, then it doesn't download.

### ISSUE THREAD

**Issue by EATBADGE** [pizzaboxer/bloxstrap#1150]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

basically, once i select stuff that i want to have in bloxstrap and i install it, bloxstrap freezes once it reaches the "Appplying roblox modifications". Iv'e tried reinstalling it a new .exe file, and it did the same thing.

**Comment by pizzaboxer** [comment]
> bloxstrap freezes once it reaches the "Appplying roblox modifications".

Does the progress bar stop moving?

**Comment by ismael37343** [comment]
este error me esta ocurriendo

**Comment by bluepilledgreat** [comment]
No response for a month
