### ISSUE TITLE
Bloxstrap crashing but normal roblox isn't

### ISSUE THREAD

**Issue by TheRealGoofet** [pizzaboxer/bloxstrap#1151]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so as the title says my bloxtrap is crashing, I tried playing on normal roblox launcher but to my suprise that doesn't crash only if I play with bloxstapper, I have no idea what to do, can someone help me?

**Comment by pizzaboxer** [comment]
Have you configured any FastFlags in the Bloxstrap Menu?

**Comment by TheRealGoofet** [comment]
> Have you configured any FastFlags in the Bloxstrap Menu?

nope, I dont think so, I only set the quality and the fps, thats all

**Comment by pizzaboxer** [comment]
For one, go to the behaviour tab, enable the 'Force Roblox reinstallation' option, save and then try and launch. For another, try setting your framerate limit to zero and then launching.

**Comment by bluepilledgreat** [comment]
No response for a month
