### ISSUE TITLE
high ping and disconnecting when bloxstrap is downloaded[BUG] 

### ISSUE THREAD

**Issue by Gpat80** [pizzaboxer/bloxstrap#1153]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when I have bloxstrap enabled my ping exceeds 1k. without bloxstrap I average like 50-100. i've tried different ping tests and in other games outside of roblox my ping is fine

**Comment by devstacking** [comment]
not a bloxstrap issue

**Comment by pizzaboxer** [comment]
What do you have your framerate limit set to?

**Comment by Gpat80** [comment]
its set to defaults

**Comment by pizzaboxer** [comment]
What number specifically?

**Comment by Gpat80** [comment]
i put it at 0 to set it to defaults

**Comment by pizzaboxer** [comment]
Do you have any other options configured or enabled (mods, fastflags, etc)?

**Comment by bluepilledgreat** [comment]
No response for a month
