### ISSUE TITLE
[REQ] add discord overlay support

### ISSUE THREAD

**Issue by betaisinalpha** [pizzaboxer/bloxstrap#1154]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

dd discord overlay support

**Comment by ShadowCodeX-debug** [comment]
Wdym?

**Comment by pizzaboxer** [comment]
> dd discord overlay support

Add Discord overlay support to Roblox? That isn't really possible, sorry.
