### ISSUE TITLE
crashes when i play games [BUG] 

### ISSUE THREAD

**Issue by vularex** [pizzaboxer/bloxstrap#1155]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Most of the time when i join a game it just freezes or when i do load in and i play for about 5-10 minutes it crashes/freezes. One of my friends recommend me to uninstall Bloxsstrap and redownload it and when i did that it still did the same thing. Not to mention I know it is a Bloxsstrap problem because i currently have in uninstall and its not crashing one me anymore.

**Comment by pizzaboxer** [comment]
If you want to still use it, try reinstalling it, but this time with your framerate limit to zero in the FastFlags tab.. Don't change any other options.

**Comment by TheRealDood** [comment]
i have this problem too, only when in fullscreen though. If im windowed then it doesnt crash.

**Comment by pizzaboxer** [comment]
Have you opted to disable fullscreen optimization in the Mods section of the menu?

**Comment by bluepilledgreat** [comment]
No response for a month
