### ISSUE TITLE
[BUG] Bloxstrap is unable to connect to roblox

### ISSUE THREAD

**Issue by WormMusic** [pizzaboxer/bloxstrap#1156]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to play roblox this thing appears.
![someth](https://github.com/pizzaboxer/bloxstrap/assets/157200949/b7bd1261-3d72-4775-b525-63dbc1879c3a)

**Comment by pizzaboxer** [comment]
Your antivirus is preventing Bloxstrap from connecting to the internet. Make sure it's not interfering or otherwise potentially causing issues.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by kenpactchi-code** [comment]
> Your antivirus is preventing Bloxstrap from connecting to the internet. Make sure it's not interfering or otherwise potentially causing issues.

well i turned off my anti virus redownloaded roblox restarted my pc and launched bloxstrap nothing worked pls help
