### ISSUE TITLE
Error while downloading Reshade

### ISSUE THREAD

**Issue by FredDoesStuff** [pizzaboxer/bloxstrap#116]
How to replicate:
1. Open the Bloxstrap.exe (for installing)
2. Wait for it to configure/Download Reshade
3. Error
![image](https://user-images.githubusercontent.com/112592014/226154856-38b731af-bb83-4aaf-93fe-9529b809cab0.png)
Using version 2.1.0, tried launching both x86 and x64 (Should be able to run both of these) and still the same issue.

**Comment by FredDoesStuff** [comment]
And now this happens when I disabled using Reshade in the settings
![image](https://user-images.githubusercontent.com/112592014/226154953-8b38ab17-e59c-4617-851b-c6f48669bb40.png)
D:\Games is where I keep the Bloxstrap installer.

**Comment by pizzaboxer** [comment]
Can you send me more detailed logs from the Bloxstrap logs folder please? Be sure to check if they contain the relevant errors, they should be right at the bottom.

**Comment by FredDoesStuff** [comment]
[Bloxstrap_20230319T051702Z.log](https://github.com/pizzaboxer/bloxstrap/files/11011799/Bloxstrap_20230319T051702Z.log)
Heres the most recent one.

**Comment by pizzaboxer** [comment]
Seems like Roblox didn't install properly. To force it to reinstall, edit State.json in the Bloxstrap folder so that VersionGuid is empty, or you can change the selected channel in the menu's Installation tab. I'll add better checking for this.

**Comment by pizzaboxer** [comment]
Closed for inactivity, assuming my suggestion fixed the problem. If you're still having problems, just make a comment here.
