### ISSUE TITLE
[BUG] exception occured while running bloxstrap

### ISSUE THREAD

**Issue by CubeSeer** [pizzaboxer/bloxstrap#1161]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

while i was reinstalling bloxstrap, a window popped up telling me about an error and log file. i will link the error and log file.

System.UnauthorizedAccessException: Access to the path 'C:\Users\Mihael\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
[Bloxstrap_20240120T184717Z.log](https://github.com/pizzaboxer/bloxstrap/files/13998723/Bloxstrap_20240120T184717Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

Read the preliminary instructions before you click the checkbox next time.
