### ISSUE TITLE
[2ND REQ, sorry] Bring back Importing fflags with explorer, but with an option

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1162]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

you really could use both things, or loading it from explorer, or just write it
i wanna use most likely both, beacuse some cool fflags have to be on mediafire/mega
fact: this was used in like 2.5.0 and you could really bring back but instead when clicking import json, it will ask you: import from explorer or import it by the textbox

**Comment by pizzaboxer** [comment]
I already have this planned on the todo list for a future update. I'll close this since this won't be a new addition to the todo list.
