### ISSUE TITLE
[BUG] Bloxstrap struggling to run roblox

### ISSUE THREAD

**Issue by 40kq** [pizzaboxer/bloxstrap#1163]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My Internet is fine, I turned off windows antivirus, I tried reinstalling roblox and bloxstrap still takes a whole minute or two to launch roblox. (When I go to launch roblox by itself without bloxstrap it launches instantly.)

**Comment by pizzaboxer** [comment]
> bloxstrap still takes a whole minute or two to launch roblox

What message does it stay on the longest when launching?

**Comment by 40kq** [comment]
"Connecting to roblox..."

**Comment by 40kq** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/70741430/7c6584f0-f8bb-47d8-8b57-ef57807ccd62)

**Comment by pizzaboxer** [comment]
Known problem, see what I've said here:

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/25cd5cee-99fc-4407-baa4-cc3884c78ab2)

**Comment by 40kq** [comment]
alr thanx, it fixed itself this morning.
