### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ridwan2094** [pizzaboxer/bloxstrap#1167]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Alright so I already had bloxstrap install in my pc but had uninstalled it and when I tried to reinstall it by downloading the latest version, the exe file won't launch and I even checked in task manager for any signs of the exe running. I tried installing it with winget as well but I get this erorr.
![Screenshot 2024-01-21 182800](https://github.com/pizzaboxer/bloxstrap/assets/138690553/5bf22edc-e65d-4bfe-b39c-9effa21494da)

**Comment by pizzaboxer** [comment]
Do you have the latest version of the .NET 6 runtime installed? https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.26-windows-x64-installer?cid=getdotnetcore

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
