### ISSUE TITLE
[REQ] Bring back rendering mode (read the description)

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1168]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Bring it back without vulkan and opengl but only with Direct3D11 and D3D11FL10 (Direct3D10)
DO NOT ADD VULKAN AND DO NOT ADD OPENGL, ONLY THE ONE I SAID

**Comment by pizzaboxer** [comment]
Read the latest release notes.
> It will be added back in the future when better precautions are in place.

**Comment by githubberguy** [comment]
well vulkan is problematic, same with opengl, so why not adding the ones i said

**Comment by pizzaboxer** [comment]
> well vulkan is problematic, same with opengl, so why not adding the ones i said

Yes, I just said they will be added back in the future.

**Comment by githubberguy** [comment]
so why not adding the ones i said lol??

**Comment by pizzaboxer** [comment]
I just said they will be added back in the future.
