### ISSUE TITLE
Roblox Crashes for a few seconds and continues [BUG]

### ISSUE THREAD

**Issue by Glarusking** [pizzaboxer/bloxstrap#1173]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, when after I started using Bloxstrap Roblox randomly started to crash and not let me do anything for a few seconds and my game continues, and it happens multiple times. I am encountering this issue mostly when I am in first person.
Hope you can resolve it.

**Comment by pizzaboxer** [comment]
Can you confirm that you don't experience this issue without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Glarusking** [comment]
Hello, so I tested both client and the crash didn't happen again, but it could happen anytime soon, if it happens again I will reply again.

**Comment by pizzaboxer** [comment]
Alright, I'll wait just in case.

**Comment by pizzaboxer** [comment]
Having been a week, I am assuming that ths issue isn't occurring anymore. In which case, if it is, then I'll be glad to reopen.

**Comment by Glarusking** [comment]
The issue isn't occurring so yeah, thank you for your time.
