### ISSUE TITLE
[BUG] Bloxstrapper randomly freezes for 10 seconds.

### ISSUE THREAD

**Issue by LReaver** [pizzaboxer/bloxstrap#1174]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sometimes when I have bloxstrapper on and it works perfectly and out of nowhere roblox freezes for 10 seconds, then a 2nd one or a 3rd one for less and etc.
I have tried turning on and off most of the settings.
Whenever I switch to the roblox player it never happens even on maximum graphics.
Could you give me a solution or help, please?
Thanks.

**Comment by pizzaboxer** [comment]
What's your framerate limit set to? Try setting it to zero, see if anything changes.

**Comment by LReaver** [comment]
> What's your framerate limit set to? Try setting it to zero, see if anything changes.

I've tried setting it to zero, to maximum.
I tried turning most of the settings off and on and still can't seem to find what the issue is.
Do I try a different version or what would you suggest?

**Comment by pizzaboxer** [comment]
You've also tried disabling all the integrations, right?

**Comment by LReaver** [comment]
What do you mean by integrations?

**Comment by LReaver** [comment]
> Owner

yes, I have tried turning it all off but it doesnt work..

**Comment by pizzaboxer** [comment]
Okay, let me try out some troubleshooting steps here. Can you open the version folder inside the `%localappdata%\Bloxstrap\Versions` folder, then delete the `ClientSettings` folder, and then directly run RobloxPlayerBeta, and see if the issue still happens?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
