### ISSUE TITLE
[BUG] Roblox crashes on exit with "Disable Desktop app" enabled

### ISSUE THREAD

**Issue by IrisWasTaken1** [pizzaboxer/bloxstrap#1175]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

instead of exiting like normal, Roblox displays a error message saying "Roblox Game Client has stopped working"

**Comment by pizzaboxer** [comment]
This issue is rare and doesn't happen for everyone, but I am aware of it. We're working on a better way of handling disabling of the desktop app in a future version.

**Comment by ShadowCodeX-debug** [comment]
I think I got it two :D

![Image](https://github.com/pizzaboxer/bloxstrap/assets/93408587/422efbfc-b82b-4fe3-931b-18ee7aade4ba)
