### ISSUE TITLE
[BUG] Blue screen of death

### ISSUE THREAD

**Issue by florzye** [pizzaboxer/bloxstrap#1176]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I open Roblox with Bloxstrap, it works for a few minutes. Then the game crashes and so does my computer with the error code "VIDEO_DXGKRNL_FATAL_ERROR". However when I use Roblox without Bloxstrap this doesn't happen. Here is the photo. 
![IMG_1872](https://github.com/pizzaboxer/bloxstrap/assets/149651972/c5653366-a7e6-4b1e-b29e-1b0aab14f6d4)

**Comment by bluepilledgreat** [comment]
No response for a month

**Comment by DS4RV** [comment]
@pizzaboxer I also have this issue. The first 3 days it worked fine but after that when I opened bloxstrap it bluescreened me. I tried deleting all the files and deleting Roblox as well but when I downloaded bloxstrap and opened the file it blue screened again. I can’t even install it now, what should I do?
