### ISSUE TITLE
[BUG] im getting not responding while playing mid-game

### ISSUE THREAD

**Issue by Exiso100** [pizzaboxer/bloxstrap#1178]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i was playing counter blox and then roblox being not responding for a few mins after that and when i reopen roblox and try to play again,it got more often,ive checked all the crashing guide but its not working at all
![cea](https://github.com/pizzaboxer/bloxstrap/assets/90812996/1bdec3a5-2ef5-4d1d-aef0-d795d93ec559)

**Comment by Exiso100** [comment]
yeah it happening only when i installed bloxstrap somehow,roblox feels very smooth but when i switched it works fine but it makes roblox unplayable

**Comment by Exiso100** [comment]
sure i will show it but not right now cuz i'm cooking,sorry !

**Comment by Exiso100** [comment]
oh yeah i set my fps limit on fast flag as 60 and lightning is voxel and everything else is default though

**Comment by pizzaboxer** [comment]
One of the FastFlag editor itself too. Show a screenshot if there's anything there, or let me know if there isn't.

**Comment by Exiso100** [comment]
there is none at all

**Comment by pizzaboxer** [comment]
Do you have fullscreen optimizations disabled?

**Comment by Exiso100** [comment]
nah man,i dont play on full screen so

**Comment by Exiso100** [comment]
![aa](https://github.com/pizzaboxer/bloxstrap/assets/90812996/9ec5df13-6042-420a-92fd-10154a5420f6)
![aaaaa](https://github.com/pizzaboxer/bloxstrap/assets/90812996/fd19dd1b-407d-409f-81e0-dfdd3b238d7c)
anyways heres your screenshot you asked

**Comment by pizzaboxer** [comment]
In the Integrations section of the menu, can you try disabling everything there is there, and then try playing a game, see if the issue still happens?

**Comment by Exiso100** [comment]
alright ill try it later though

**Comment by Exiso100** [comment]
hmm no its not working i still get not responding
![Uploading saaaa.PNG…]()

**Comment by Exiso100** [comment]
its not working either 
![saaaa](https://github.com/pizzaboxer/bloxstrap/assets/90812996/a803727e-ab5e-4431-8ee0-b87c3a0d2db7)

**Comment by pizzaboxer** [comment]
Okay, I'm a little bit confused since there shouldn't be any functional differences between standard Roblox and Bloxstrap now.

Brief troubleshooting step, can you open the version folder in the `%localappdata%\Bloxstrap\Versions` folder, delete the `ClientSettings` folder, and then afterwards directly launch `RobloxPlayerBeta`?

**Comment by Exiso100** [comment]
alright ill do that later

**Comment by Exiso100** [comment]
alright its still not responding

**Comment by Exiso100** [comment]
can you add some sort of log for bloxstrap or roblox itself ?
it might helps alots

**Comment by pizzaboxer** [comment]
> alright its still not responding

This is implying an issue with Roblox itself then.

Now that I'm reading your original post again:

> yeah it happening only when i installed bloxstrap somehow

I'm not asking about whether it was happening before you installed it, I'm asking about if it currently happens only with Bloxstrap. Switch to the stock Roblox bootstrapper and see if you still encounter the issue there.

**Comment by Exiso100** [comment]
okay

**Comment by Exiso100** [comment]
its working fine with roblox default but bloxstrap make it not responding somehow

**Comment by pizzaboxer** [comment]
Last thing, in the behaviour section of the menu, can you try enabling the option to "force roblox reinstallation"?

**Comment by Exiso100** [comment]
it seems to be work ! thanks for your help
