### ISSUE TITLE
[BUG] Bloxstrap hangs on "Connecting to Roblox" for too long

### ISSUE THREAD

**Issue by neomiemo** [pizzaboxer/bloxstrap#1179]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap is stuck on Connecting to Roblox for so long. I don't know what causes this. Please help me.

**Comment by pizzaboxer** [comment]
If this happens every time you launch it and it happens for no longer than four minutes, then see what I've said here: https://github.com/pizzaboxer/bloxstrap/issues/1163#issuecomment-1902618243

**Comment by neomiemo** [comment]
okay thanks

**Comment by pizzaboxer** [comment]
Forgot an issue for this already exists at #958
