### ISSUE TITLE
Bloxstrap menu

### ISSUE THREAD

**Issue by watermelonslove** [pizzaboxer/bloxstrap#1181]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have been using bloxstrap on Windows 10, and when I download it, it doesn't show the menu app for it, but it does when you don't install it yet.

**Comment by pizzaboxer** [comment]
> when I download it, it doesn't show the menu app for it, but it does when you don't install it yet.

I'm sorry, what?

**Comment by bluepilledgreat** [comment]
No response for a month
