### ISSUE TITLE
Health bar

### ISSUE THREAD

**Issue by Killeryue7** [pizzaboxer/bloxstrap#1182]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Imagine a better health bar that u can se how much % or points of health u have instead of the fcking boring shit of roblox that maybe make u have 0.0000001 of health and u dont know if ur dead or not

**Comment by pizzaboxer** [comment]
Not possible for us to add, sorry.
