### ISSUE TITLE
[BUG] Bloxstrap crashing as soon as it opens

### ISSUE THREAD

**Issue by mmmm-chicken** [pizzaboxer/bloxstrap#1183]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try and use Bloxstrap it shows the loading tab but then it closes and only shows in the background. Roblox runs fine if I just use the Roblox player, but it doesn't work when I the website or Play Roblox. I tried to fully delete Roblox, Bloxstrap, and update .NET 6 Desktop Runtime but nothing has worked so far.

**Comment by pizzaboxer** [comment]
>  but it doesn't work when I the website

Just to be clear, when you were launching from the website, were you seeing Bloxstrap's launch dialog?

**Comment by shxnobi** [comment]
I have the exact same problem where it does not open, but when using the roblox launcher it works fine, and I see the Bloxstrap launch dialog, however I am unsure if mmmchicken also sees it.

**Comment by vihaan69** [comment]
same, I see the Bloxstrap launch dialog but it just crashes after showing "Starting Roblox..." and it works when I launch Roblox directly

**Comment by mmmm-chicken** [comment]
Yes, then it doesn't open and runs in the background

**Comment by pizzaboxer** [comment]
@shxnobi @vihaan69 For both of you, can you tell me what settings you've configured in the Bloxstrap Menu?

**Comment by mmmm-chicken** [comment]
I just tried it when I got home and i think it worked, but it didn't have unlocked fps so I couldn't tell. So I tried opening Bloxstrap menu and force closing Roblox and it doesn't work anymore.

**Comment by vihaan69** [comment]
**Mods**:
Use old death sound: True

**FastFlags:**
Framerate limit: 500
DFIntDebugFRMQualityLevelOverride : 1
FFlagDebugGraphicsDisableDirect3D11: True
FFlagDisablePostFx: True
FIntRenderShadowIntensity: 0
FFlagDebugGraphicsPreferVulkan: True

everything else is default

**Comment by pizzaboxer** [comment]
@vihaan69 Can you try removing the Vulkan flag?

@mmmm-chicken Okay, that's fine. I'd also like for you to share what settings you've configured.

**Comment by vihaan69** [comment]
@pizzaboxer Thank you! It fixed the error

**Comment by mmmm-chicken** [comment]
Framerate limit:9999
everthing else is default

**Comment by pizzaboxer** [comment]
Just some troubleshooting steps: open the version folder in the `%localappdata%\Bloxstrap\Versions` folder, delete the `ClientSettings` folder and then run RobloxPlayerBeta directly - play from there and see if you encounter the issue again.

**Comment by mmmm-chicken** [comment]
I deleted the ClientSettings folder and then directly ran RobloxPlayerBeta from the folder. Everything seems normal until I try to join a game; Roblox just stays on the joining server screen or the screen where you load into the game.

**Comment by pizzaboxer** [comment]
Is this happening only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by mmmm-chicken** [comment]
When I run RobloxPlayerBeta from C:\Users\(name)\AppData\Local\Bloxstrap\Versions\version-85c66b72a4fe4a74, what I described above happens. When I use Play Roblox, Bloxstrap runs in the background and when I use Roblox Player, Roblox works fine.

**Comment by pizzaboxer** [comment]
> However, now it does not even run.

I'd like to get a better idea on what your configuration looks like. Can you please upload your Bloxstrap installation folder somewhere for me to look at? It's located at `%localappdata%\Bloxstrap`. Create a .7z archive out of it or something, upload it somewhere, and send a link to it here.

**Comment by mmmm-chicken** [comment]
[](https://drive.google.com/file/d/11KDe64se5Ad3XSjdFYwrCCqRnW6vhQDp/view?usp=sharing)

**Comment by pizzaboxer** [comment]
> everything else is default

Really now?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/26df29e9-21eb-4fe9-bb0e-e77b6cec36d1)

Please remove all the flags you have configured in the flag editor, launch Roblox, and see if it works.

**Comment by mmmm-chicken** [comment]
I don't what flags are edited because as far as I know I only used the presets or the fps limit.

**Comment by pizzaboxer** [comment]
Open the flag editor, select everything with Ctrl+A, and delete them all.

**Comment by mmmm-chicken** [comment]
Thank you so much, it works now.
