### ISSUE TITLE
[BUG] Roblox crashes midgame (Not Responding Crash)

### ISSUE THREAD

**Issue by MissingReports** [pizzaboxer/bloxstrap#1184]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox crashes midgame without any errors, it only does it with bloxstrap btw

**Comment by pizzaboxer** [comment]
> Roblox crashes midgame without any errors, it only does it with bloxstrap btw

Have you made any alterations to the settings in the Bloxstrap Menu?

**Comment by MissingReports** [comment]
yes, FPS set to 9999, 21 quality button thing, multi instance

(i tried to set FPS to 0 for default but it just made the crash "An unexpected error occured and Roblox needs to quit. We're sorry" instead of not responding)

**Comment by pizzaboxer** [comment]
Just some troubleshooting here, can you open the version folder in the `%localappdata%\Bloxstrap\Versions` folder, delete the `ClientSettings` folder, then run RobloxPlayerBeta directly, play from there and see if the issue still continues?

**Comment by Jxm3sy** [comment]
i have a very similar issue but whenever i open any roblox (not UWP) it just shows white then a few seconds later just shows "Not responding"

**Comment by yellowham** [comment]
the same issue is happening to me with the roblox crash randomly not responding I tried deleting the client settings folder in the %localappdata%\Bloxstrap\Versions folder but i was still crashing

**Comment by pizzaboxer** [comment]
> but whenever i open any roblox

Is this without Bloxstrap too? I'm only concerned if your issue only happens with Bloxstrap. If it happens without it too, the best I can do is point you to https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

**Comment by bluepilledgreat** [comment]
No response for a month
