### ISSUE TITLE
[REQ] shaders

### ISSUE THREAD

**Issue by grubgrubperks** [pizzaboxer/bloxstrap#1186]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

would it be possible to make bloxstrap support nvidea freestyle? doing so would allow the ansel of the graphics card to be used on roblox

**Comment by pizzaboxer** [comment]
Duplicate of #997

**Comment by grubgrubperks** [comment]
mb
