### ISSUE TITLE
[BUG] I put my FPS limit to 9999 (no limit), yet roblox is running on 30-60 FPS

### ISSUE THREAD

**Issue by notorietyG** [pizzaboxer/bloxstrap#1189]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I did read the wiki, yet the solutions did nothing. I'm just wondering if there's another solution to this problem. Even if my graphics is on 1, it still stays on 30-60. Its pretty annoying now. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/157772659/dcf1d781-4441-4978-bb31-455954391e69)

**Comment by notorietyG** [comment]
It can also possibly go down to 1-10.

**Comment by pizzaboxer** [comment]
Are you actually capable of exceeding 60? In which case, of course you won't be going past 60.

I just want to ensure that this isn't a performance issue before I suggest configuration changes, so please momentarily switch back to stock Roblox and check if you experience similar performance issues there. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by notorietyG** [comment]
On roblox's bootstrapper, it's still the same, capped to 60 and it goes as low as 10. (I tested this on Arsenal)

**Comment by notorietyG** [comment]
It could be capped to 60 due to my pc being a laptop, but sharkblox (Who also used a laptop in reviewing bloxstrap) wasn't capped, and it ran smoothly. (Sorry for my bad english I'm asian.)

**Comment by pizzaboxer** [comment]
Okay, so you are being capped at 60 with Bloxstrap. Have you read through this? https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter

**Comment by notorietyG** [comment]
[Bloxstrap_20240122T092907Z.log](https://github.com/pizzaboxer/bloxstrap/files/14074776/Bloxstrap_20240122T092907Z.log)
this?

**Comment by notorietyG** [comment]
[Bloxstrap_20240128T025327Z.log](https://github.com/pizzaboxer/bloxstrap/files/14074782/Bloxstrap_20240128T025327Z.log)
this?

**Comment by pizzaboxer** [comment]
Yep, that's what I need, thanks.

It definitely is configuring the limiter. You haven't configured any other options in the menu, have you?

**Comment by notorietyG** [comment]
only changed the limiter to 0, as it ran more smoothly that 9999

**Comment by pizzaboxer** [comment]
Try setting it to 120, see what happens.

**Comment by notorietyG** [comment]
on it

**Comment by notorietyG** [comment]
![Screenshot 2024-01-28 235852](https://github.com/pizzaboxer/bloxstrap/assets/157772659/155b1e3f-2603-44a8-9efc-fe3edefbdb57) 
Average is 34. Tested this on Arsenal

**Comment by notorietyG** [comment]
It does go over 60 though, reaching only 70 maximum.

**Comment by notorietyG** [comment]
Be quick please its 12 am in the morning and I'm gonna sleep.

**Comment by pizzaboxer** [comment]
> It does go over 60 though, reaching only 70 maximum.

Alright, seems like it's working then.

**Comment by notorietyG** [comment]
thanks
