### ISSUE TITLE
failed to download or apply any critical settings 

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#1190]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Capture](https://github.com/pizzaboxer/bloxstrap/assets/86916029/82b6605b-9e5d-4843-aa68-5e494104b57f)
bloxstrap and roblox have the same problem
man i dunno what to do

**Comment by Boi2021Miceoos** [comment]
this just happen
[Bloxstrap_20240126T093053Z.log](https://github.com/pizzaboxer/bloxstrap/files/14062984/Bloxstrap_20240126T093053Z.log)
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/86916029/5964ca94-e177-4ad1-8e92-6c872089df6e)

**Comment by pizzaboxer** [comment]
Get the latest Roblox log file from the `%localappdata%\Roblox\logs` folder, and sent it to me privately over either [email](mailto:_@pizzaboxer.xyz) or Discord (by joining the Discord server), and I'll take a further look.

Also, are you facing any issues with using the Roblox website?

**Comment by Boi2021Miceoos** [comment]
> %localappdata%\Roblox\logs
facing issues with the roblox website: yes
sended the latest log to your email

**Comment by Boi2021Miceoos** [comment]
Edit: the issue seem to be just bloxstrap issue after switching to roblox default bootstrapper the issue is gone

**Comment by Boi2021Miceoos** [comment]
> > Edit: the issue seem to be just bloxstrap issue after switching to roblox default bootstrapper the issue is gone
> 
> You didn't actually send the correct log file, that's my bad for not telling you which one to get.
> 
> From the log file you did give me, it's clear that it's an internet connectivity issue (likely a firewall/antivirus blocking it). If Roblox is working fine now, I'd expect Bloxstrap to work fine now too.

didn't i tell you that it was fixed on your discord?
yeah my isp have been fixing some local fiber cables lately seem like they done
