### ISSUE TITLE
[BUG] Bloxstrap Error

### ISSUE THREAD

**Issue by Mrfranceskogr** [pizzaboxer/bloxstrap#1192]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i Press Install In Bloxstrap App this pops up. What Do I Do??
![Screenshot 2024-01-26 150459](https://github.com/pizzaboxer/bloxstrap/assets/67559797/5df9699d-da6d-4774-b913-9415d6b167da)

**Comment by pizzaboxer** [comment]
> When i Press Install

Are you reinstalling? In which case, you didn't close Roblox before you uninstalled it. Make sure Roblox isn't running in the background.

**Comment by cfors55** [comment]
Nothing changed
