### ISSUE TITLE
[REQ] Beta Updates | Canary Version

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1193]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

since many people would like to see a version, make beta versions, in settings there will be an option (to check)
"Beta Features", or name it "Beta Update"
i really want this in the 2.6.0, so we can have a real beta testing app, like "Chrome Beta": 
https://google-chrome-beta.en.softonic.com/
Maybe a "Bloxlink Beta".
You can make a canary version, with bloxstrap's logo being recolored yellow, it will ask you "Do you really want to overwrite your Bloxstrap with Bloxstrap Canary", it will add "Are you sure, this will NOT Save your data."
the meaning of "THIS WILL NOT SAVE YOUR DATA" means that wont save the canary data to the original/beta version.
the canary version will let you have a gui where you can serach fflags on the FFLAGS > FFLAG EDITOR > Canary New FFLAG Seracher (will be a gui on the app, this wont show every single fflag but the fflags that are on the discord).
and add (UNSTABLE) so they'll know this might lag their roblox, break their roblox..
you could add the beta, could be more better versus the canary
the canary version could have a "Mod Seracher", it can serach mods that are on discord
on the server btw, I suggest adding them both, or the beta,
this took me long enough to write.

**Comment by githubberguy** [comment]
i didnt mention that the beta data wont be saved on the canary or normal version

**Comment by pizzaboxer** [comment]
I appreciate the thought, but if I'm carrying out testing, I'd like to plan on doing it privately rather than having it organized to be open and public like this. Sorry.
