### ISSUE TITLE
Add the GPU change thing again. I haven't used or played roblox in months so i dont know when or why it was removed. But if it was removed for a bug issue or something alright, but if not and it was only removed because of some stupid reason. Add it back.  much love[REQ] 

### ISSUE THREAD

**Issue by Jathnielwhy** [pizzaboxer/bloxstrap#1194]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

If you can not understand or forgot what that GPU thing is. I dont even remember if its a Gpu thingy but it has Vulkan, etc. You could choose which you want to use or whats the most compatible with you're computer. Really helped me and one of the only reasons i downloaded this launcher. But if you can't cause of some issues, alright.

**Comment by Bamir235654** [comment]
He isn't able to add it because of byfron i assume.

**Comment by pizzaboxer** [comment]
Read the latest release notes at https://github.com/pizzaboxer/bloxstrap/releases/latest.

> Removed option to configure rendering mode due to how much instability it causes. It will be added back in the future when better precautions are in place.

If you wish to configure it, see this: https://github.com/GoingCrazyDude/fastflags-collection/blob/main/README.md#change-rendering-mode (use the 'Import JSON' utility for this).
