### ISSUE TITLE
Roblox popup stops Bloxstrap uninstaller from closing Roblox

### ISSUE THREAD

**Issue by Findyourlimit** [pizzaboxer/bloxstrap#1195]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The bloxstrap uninstaller doesn't close roblox if you haven't disabled the exit popup 
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/149321296/38100c4e-9f4c-4af5-90c4-73b41ce4cfc2)
(sorry if you already knew)

**Comment by pizzaboxer** [comment]
Oh, I actually did not know about this. Thanks for reporting!

**Comment by bluepilledgreat** [comment]
Can not reproduce this bug
