### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\ferna\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by microwavesphagetti** [pizzaboxer/bloxstrap#1197]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\ferna\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

How do I fix this?

![Screenshot (934)](https://github.com/pizzaboxer/bloxstrap/assets/134742087/955ec037-c1b0-4d7d-9424-6413dee1481a)

**Comment by Findyourlimit** [comment]
I'm not a professional, but try running it as administrator, if that doesn't work, wait for pizzaboxer to help

**Comment by Findyourlimit** [comment]
Also the screenshot contains the name of your user account which could be private, just letting you know in case you wanted to blur it out or something

**Comment by microwavesphagetti** [comment]
Whoops.

**Comment by microwavesphagetti** [comment]
Also Thank you it works.
