### ISSUE TITLE
[BUG] An Exception  occurred  while running Bloxstrap

### ISSUE THREAD

**Issue by RipAmBro** [pizzaboxer/bloxstrap#1198]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tryed to download Bloxstrap and somehow this error showed 
![image](https://github.com/pizzaboxer/bloxstrap/assets/144538923/cc2944e2-64a5-444e-aa60-6c5de07b1b39)

**Comment by Findyourlimit** [comment]
It appears to not have permission to access the file, pizzaboxer will probably assist you further

**Comment by RipAmBro** [comment]
ok

**Comment by pizzaboxer** [comment]
Read the preliminary instructions next time.

https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
