### ISSUE TITLE
[BUG] Custom font does not work in game

### ISSUE THREAD

**Issue by Razor7100** [pizzaboxer/bloxstrap#1199]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It doesnt work in some areas im not sure why (first image is the font and second image is showing the font not working)
![image](https://github.com/pizzaboxer/bloxstrap/assets/121650332/2b786b5b-8124-4030-934b-b3a6ec197569)
![image](https://github.com/pizzaboxer/bloxstrap/assets/121650332/80e1a306-6c66-41c8-8eef-cac8f65a9b55)

**Comment by Razor7100** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/121650332/ea706230-e060-4c96-8450-b9e947e90377)

**Comment by pizzaboxer** [comment]
Not all font files will be fully compatible with Roblox. Try using another one and find one that works.
