### ISSUE TITLE
Error while launching: System.IO.DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by nvthane** [pizzaboxer/bloxstrap#12]
Whenever I launch via Bloxstrap or even update Roblox with it, it gives me the error "System.IO.DirectoryNotFoundException: Could not find a part of the path". It happens after I updated Bloxstrap from 1.3.0 to 1.4.1.

How to replicate:
Update from 1.3.0 to 1.4.1 (Bloxstrap)
Before launching Bloxstrap, configure and set channel to ZAvatarTeam
Launch Bloxstrap

And now I can't launch Bloxstrap even if I set the channel to live or re-install it. (It did work on 1.3.0)
![image](https://user-images.githubusercontent.com/46616775/188168349-d34caf0b-ce59-465b-8ddd-a09a661b674a.png)

**Comment by pizzaboxer** [comment]
Just released [v1.4.2](https://github.com/pizzaboxer/bloxstrap/releases/tag/v1.4.2) and it should fix this issue. Try it and let me know if it works.

**Comment by nvthane** [comment]
It works, thanks.

**Comment by nvthane** [comment]
Update 1.4.2 fixes the issue.
