### ISSUE TITLE
Error downloading ReShade

### ISSUE THREAD

**Issue by TheSkout** [pizzaboxer/bloxstrap#120]
![image](https://user-images.githubusercontent.com/111308237/229346841-92e5adb5-f87f-416c-92e9-6232c6ee185c.png)

**Comment by pizzaboxer** [comment]
Can you please send the full log file from the Bloxstrap log folder? Sort the files in the log folder by newest to find it, and make sure it's the one with the error (it should be at the bottom of the file).

**Comment by TheSkout** [comment]
[Bloxstrap_20230402T101440Z.log](https://github.com/pizzaboxer/bloxstrap/files/11131983/Bloxstrap_20230402T101440Z.log)

**Comment by pizzaboxer** [comment]
What happens if you try to access [https://github.com/crosire/reshade-shaders/archive/refs/heads/master.zip](https://github.com/crosire/reshade-shaders/archive/refs/heads/master.zip) in your browser?
Also, a bit of an unrelated question, but what country do you reside in? The two previous people who've had this issue both lived in Russia, and I was never able to find out why from them.

**Comment by TheSkout** [comment]
\*Your connection is not private*

**Comment by pizzaboxer** [comment]
Show a screenshot of the error page, so I can see how to find the SSL details.

**Comment by TheSkout** [comment]
![image](https://user-images.githubusercontent.com/111308237/229349156-65ab102d-cf50-4bf9-87e4-9f2cfbd9fdff.png)
and yes, i reside in Russia

**Comment by TheSkout** [comment]
i tried with VPN, no success

**Comment by pizzaboxer** [comment]
Click on the `NET::ERR_CERT_COMMON_NAME_INVALID` message to show the SSL details and take another screenshot please.

**Comment by TheSkout** [comment]
![image](https://user-images.githubusercontent.com/111308237/229349218-72e12817-3482-4a5d-803d-5796423fbc8c.png)
![image](https://user-images.githubusercontent.com/111308237/229349223-1c540c82-1922-49aa-91cb-6657a4d94448.png)

**Comment by pizzaboxer** [comment]
Huh, I thought there'd be more to this.
Anyway, it seems like your ISP is blocking downloads from GitHub for some reason. There's really nothing I can do about that unfortunately. The only thing I can really suggest to do is disable ReShade when installing Bloxstrap.

**Comment by TheSkout** [comment]
how??

**Comment by pizzaboxer** [comment]
Are you installing Bloxstrap for the first time or trying to launch Roblox?

**Comment by TheSkout** [comment]
i used it before, i downloaded .exe file, and trying to run it

**Comment by pizzaboxer** [comment]
If the installation menu doesn't show when you run it, try searching "Bloxstrap Menu" in your start menu.

**Comment by TheSkout** [comment]
its not exists

**Comment by pizzaboxer** [comment]
Last resort, open the `Settings.json` file in the Bloxstrap folder, and change these two lines:
```json
"UseReShade": true,
"UseReShadeExtraviPresets": true,
```
to this:
```json
"UseReShade": false,
"UseReShadeExtraviPresets": false,
```

**Comment by TheSkout** [comment]
YES, YES, AND AGAIN YES
thank u very much

**Comment by pizzaboxer** [comment]
No problem.

**Comment by TheSkout** [comment]
btw, @pizzaboxer, my ISP fixed it, lol

**Comment by pizzaboxer** [comment]
brother this was three months ago

**Comment by Sahelantrophus** [comment]
what is your problem monkey
