### ISSUE TITLE
[BUG] Access to the path 'C:\Users\marce\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Bloxstrap' is denied.

### ISSUE THREAD

**Issue by JocaPadre** [pizzaboxer/bloxstrap#1200]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Access to the path 'C:\Users\marce\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Bloxstrap' is denied

**Comment by pizzaboxer** [comment]
Kind of sounds like your antivirus is interfering with Bloxstrap. Can you ensure that it's not doing anything which could be preventing it from modifying files and stuff?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
