### ISSUE TITLE
[BUG] Low Quality Texture / Texture Flickering

### ISSUE THREAD

**Issue by CATSarekittens** [pizzaboxer/bloxstrap#1202]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The textures randomly become very low quality or when tabbing back into Roblox after a bit. The textures also sometimes flicker between low and high quality. I tested on a fresh install of Roblox without Bloxstrap, but the bug did not replicate until I reinstalled Bloxstrap.

![NormalTextures](https://github.com/pizzaboxer/bloxstrap/assets/131730582/5eab3249-06e2-4a31-b822-f02df92db809)
![BlurryTextures](https://github.com/pizzaboxer/bloxstrap/assets/131730582/52bc3a4a-c822-4bc8-b0bb-e69b102bdee7)
![Texturebug](https://github.com/pizzaboxer/bloxstrap/assets/131730582/cb69cb8b-81f1-4fdd-80b6-69386e8b2d94)
![image](https://github.com/pizzaboxer/bloxstrap/assets/131730582/c6f17e60-4617-45b0-98d5-816be2663cf2)
https://github.com/pizzaboxer/bloxstrap/assets/131730582/2f921480-de9a-448d-bf04-fb5fea8d0b80

**Comment by pizzaboxer** [comment]
> I tested on a fresh install of Roblox without Bloxstrap, but the bug did not replicate until I reinstalled Bloxstrap.

You haven't configured any options in the Bloxstrap Menu, have you? 
If you haven't, the only real cause I can see of this is your GPU overriding the texture quality (as Bloxstrap installs to a different location that GPU software may not expect it to be).

The first thing I'd suggest to try and fix this is to add this FastFlag in the editor (using the Import JSON tool):
```json
{
    "DFFlagTextureQualityOverrideEnabled": "True",
    "DFIntTextureQualityOverride": "3"
}
```

**Comment by Blox123gg** [comment]
Hi, I used bloxstrap to solve a bug in the textures, where they were blurry. Bloxstrap solved my problem for a few weeks, I think it was close to a month. Yesterday, the textures were blurred again, I've done everything, I've tried making a new flash flag with the settings mentioned, but it didn't work, what can I do?

**Comment by renzcamus** [comment]
It stop working but other texture were high quality but my face and my accessories are blurred and the sky, terrain are also blurred, how do i fix it again?

**Comment by ismaelherrerasantiago16-stack** [comment]
Me too my textures are bug to medium texture how do i get high textures not bug of then from fast flags editor voidstrap???
