### ISSUE TITLE
Support For Mac

### ISSUE THREAD

**Issue by Xoticcccc** [pizzaboxer/bloxstrap#1203]
Dude pizzaboxer the only sole reason I am writing this is to tell you that you should make one that is supportive for MacOs so mac users can also enjoy the features not only the windows users. Thats all bro hopefully you make one for MacOs.

**Comment by Findyourlimit** [comment]
He is planning on it I think

**Comment by pizzaboxer** [comment]
I want to support it, but it's not happening anytime soon, as it would take an incredible amount of work to add support for it. I want to get 2.6.0 out first, then possibly start work on something that can support MacOS. But for now, it's not that much of a concern to me, so I'll close this.

**Comment by jackTabsCode** [comment]
If you want to support it, then don't close the issue as not planned? :)

**Comment by pizzaboxer** [comment]
> then don't close the issue as not planned? 😄

Not planned as of now, correct.

**Comment by Thyssenkrupp234** [comment]
This project seems super interesting to me! I want to make a client similar to this for macOS, but my knowledge of swift or C# is not great enough. If you were to make this for macOS, you'd probably want to use swift. .NET on macOS has always been really finicky, and with VS for mac dropping support, it's even worse

If you ever start mac support, I might try and contribute to the project.
