### ISSUE TITLE
[BUG] Pixelated lights and holes in a car model (greenville)

### ISSUE THREAD

**Issue by XRAZERGAMERX** [pizzaboxer/bloxstrap#1204]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i join a game the lights a pixelated and when i drive a car it has holes in the windshild not in the middle but under the winshield (this was never with roblox but it happend when i got bloxstrap and used fastflags . i dont know what fastflag could do this problem

![Screenshot 2024-01-29 185057](https://github.com/pizzaboxer/bloxstrap/assets/93815077/3c4a97fb-e6a7-48f4-9447-20274cdc1cb3)
![Screenshot 2024-01-29 184947](https://github.com/pizzaboxer/bloxstrap/assets/93815077/75887ecc-0c7d-4202-9bef-0fb22002ed3b)
) 

my FastFlags

{
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableV3MenuABTest3": "False",
  "FFlagEnableMenuModernizationABTest2": "False",
  "FFlagEnableMenuModernizationABTest": "False",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableInGameMenuModernization": "True",
  "FFlagEnableInGameMenuControls": "True",
  "FFlagFixGraphicsQuality": "True",
  "DFFlagDisableDPIScale": "True",
  "FFlagDebugForceFutureIsBrightPhase3": "True",
  "DFIntTaskSchedulerTargetFps": "999999999",
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "DFLogHttpTraceLight": "0",
  "DFIntCanHideGuiGroupId": "32380007",
  "FIntBootstrapperTelemetryReportingHundredthsPercentage": "0",
  "DFFlagGpuVsCpuBoundTelemetry": "False",
  "FFlagDebugGraphicsPreferVulkan": "True",
  "FFlagAvatarChatSettingsEnabled2": "False",
  "FFlagGraphicsCheckComputeSupport": "True",
  "FFlagGraphicsSettingsOnlyShowValidModes": "True",
  "FFlagBatchAssetApi": "True",
  "FFlagTrackPlaceIdForCrashEnabled": "False",
  "DFIntUserIdPlayerNameLifetimeSeconds": "86400",
  "FStringTerrainMaterialTablePre2022": "",
  "FFlagRenderPerformanceTelemetry": "False",
  "DFFlagDebugAnalyticsSendUserId": "False",
  "DFStringRobloxAnalyticsSubDomain": "opt-out",
  "DFIntS2PhysicsSenderRate": "250",
  "DFIntLoginTelemetryHundredthsPercent": "0",
  "DFIntHttpCurlConnectionCacheSize": "134217728",
  "FFlagEnableSoundTelemetry": "False",
  "FFlagEnableAccessibilitySettingsInExperienceMenu2": "True",
  "FintRenderGrassHeightScaler": "0",
  "DFStringAltHttpPointsReporterUrl": "null",
  "FFlagVoiceChatServiceManagerUseAvatarChat": "False",
  "DFIntTextureQualityOverride": "21",
  "DFStringAnalyticsEventStreamUrlEndpoint": "opt-out",
  "DFFlagQueueDataPingFromSendData": "True",
  "FStringImmersiveAdsUniverseWhitelist": "0",
  "DFIntRunningBaseOrientationP": "450",
  "FFlagDebugGraphicsDisableVulkan": "True",
  "FFlagEnableAdsAPI": "False",
  "FIntFontSizePadding": "3",
  "DFLogHttpTrace": "0",
  "DFFlagAvatarChatServiceUserPermissionsAudioOptIn": "False",
  "DFFlagEnableMemProfilingStorePlaceId": "False",
  "FFlagAddGameInstanceIdToSessionTracking": "False",
  "FFlagDebugDisableOTAMaterialTexture": "true",
  "FFlagDontCreatePingJob": "True",
  "FFlagDebugGraphicsDisableVulkan11": "True",
  "FFlagAnimationClipMemCacheEnabled": "True",
  "FFlagFacialAnimationStreamingServiceUniverseSettingsEnableAudio": "False",
  "FFlagWindowsLaunchAnalytics": "False",
  "FFlagEnableCameraByDefault": "False",
  "FIntTerrainOTAMaxTextureSize": "1024",
  "FIntEmotesAnimationsPerPlayerCacheSize": "16777216",
  "DFFlagCrashUploadFullDumps": "False",
  "FFlagReportFpsAndGfxQualityPercentiles": "False",
  "FStringErrorUploadToBacktraceBaseUrl": "https://opt-out.roblox.com",
  "FIntHSRClusterSymmetryDistancePercent": "10000",
  "FFlagEnableInGameMenuChrome": "true",
  "FFlagDebugRenderingSetDeterministic": "True",
  "DFIntConnectionMTUSize": "900",
  "DFIntCSGLevelOfDetailSwitchingDistanceL12": "0",
  "FIntPGSAngularDampingPermillPersecond": "9999999999",
  "FFlagAudioDeviceTelemetry": "false",
  "FIntRenderEnableGlobalInstancingD3D11Percent": "100",
  "DFIntDebugFRMQualityLevelOverride": "21",
  "DFIntLightstepHTTPTransportHundredthsPercent2": "0",
  "FStringCoreScriptBacktraceErrorUploadToken": "null",
  "DFFlagEnableHardwareTelemetry": "false",
  "FFlagEnableAccessibilitySettingsEffectsInCoreScripts2": "True",
  "FStringGamesUrlPath": "/games/",
  "FFlagDebugDisableTelemetryV2Stat": "True",
  "FIntMeshContentProviderForceCacheSize": "268435456",
  "DFIntNewRunningBaseAltitudeD": "50",
  "FIntLightingDefaultClearColorARGB": "True;255,255,255,255",
  "FFlagDebugDisableTelemetryPoint": "True",
  "DFFlagBaseNetworkMetrics": "False",
  "DFIntBrowserTrackerApiDeviceInitializeRolloutPercentage": "0",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "DFStringTelegrafHTTPTransportUrl": "null",
  "FFlagEnableInGameMenuV3": "False",
  "DFStringRobloxAnalyticsURL": "null",
  "FFlagPreloadAllFonts": "True",
  "DFFlagBrowserTrackerIdTelemetryEnabled": "False",
  "DFStringLightstepHTTPTransportUrlHost": "null",
  "DFStringLightstepHTTPTransportUrlPath": "null",
  "FIntLinkBrowserTrackerToDeviceRollout": "0",
  "FFlagDebugDisplayFPS": "False",
  "FFlagCoreGuiTypeSelfViewPresent": "False",
  "FFlagImmersiveAdsWhitelistDisabled": "False",
  "DFIntCSGLevelOfDetailSwitchingDistanceL23": "0",
  "FIntFlagUpdateVersion": "132",
  "FFlagEnableBatteryStateLogger": "False",
  "FIntDefaultMeshCacheSizeMB": "256",
  "FIntDebugForceMSAASamples": "0",
  "DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent": "0",
  "FFlagLuaAppSystemBar": "False",
  "FFlagFacialAnimationStreamingServiceUserSettingsOptInVideo": "False",
  "FIntRenderLocalLightFadeInMs_enabled": "99999",
  "FIntRenderShadowmapBias": "0",
  "FFlagGlobalWindRendering": "false",
  "FFlagInGameMenuV1FullScreenTitleBar": "False",
  "DFIntGoogleAnalyticsLoadPlayerHundredth": "0",
  "FFlagDebugGraphicsCrashOnLeaks": "False",
  "DFFlagEphemeralCounterInfluxReportingEnabled": "False",
  "DFStringLightstepToken": "null",
  "FFlagGraphicsEnableD3D10Compute": "True",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FIntFRMMinGrassDistance": "0",
  "FStringTerrainMaterialTable2022": "",
  "FFlagEnableAccessibilitySettingsEffectsInExperienceChat": "True",
  "FIntUITextureMaxRenderTextureSize": "1024",
  "DFFlagEnableFmodErrorsTelemetry": "False",
  "FFlagFastGPULightCulling3": "True",
  "DFStringAnalyticsNS1BeaconConfig": "https://opt-out.roblox.com",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FFlagDebugGraphicsDisableDirect3D11": "False",
  "DFIntDetectCrashEarlyPercentage": "0",
  "FFlagRenderCheckThreading": "True",
  "FFlagRenderGpuTextureCompressor": "True",
  "DFFlagVideoCaptureServiceEnabled": "False",
  "DFStringAltTelegrafHTTPTransportUrl": "null",
  "FFlagFacialAnimationStreamingServiceUniverseSettingsEnableVideo": "False",
  "DFFlagClientBaseNetworkMetrics": "False",
  "DFIntWriteFullDmpPercent": "0",
  "FFlagDebugGraphicsDisableOpenGL": "True",
  "FFlagAvatarChatServiceExposeClientFeaturesForVoiceChat": "False",
  "DFIntCrashReportingHundredthsPercentage": "0",
  "FFlagDebugGraphics": "False",
  "DFFlagEnableMemProfilingOutsideClient": "False",
  "FFlagDisablePostFx": "True",
  "FFlagEnableAudioOutputDevice": "false",
  "FIntRenderShadowIntensity": "0",
  "DFLogBatchAssetApiLog": "3",
  "FFlagEnableQuickGameLaunch": "False",
  "DFLogHttpTraceError": "0",
  "DFFlagEnableGCapsHardwareTelemetry": "False",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "FIntRenderGrassDetailStrands": "0",
  "FIntCameraMaxZoomDistance": "99999",
  "DFStringCrashUploadToBacktraceWindowsPlayerToken": "null",
  "DFFlagHttpCacheCleanBasedOnMemory": "True",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "DFFlagESGamePerfMonitorEnabled": "False",
  "\u0022DFIntCSGLevelOfDetailSwitchingDistanceL23\u0022": "0",
  "FIntStartupInfluxHundredthsPercentage": "0",
  "DFStringAnalyticsNS1ApplicationId": "opt-out",
  "FFlagGraphicsGLEnableHQShadersExclusion": "False",
  "\u0022DFIntCSGLevelOfDetailSwitchingDistance\u0022": "0",
  "DFFlagAddPublicGettersForGfxQualityAndFpsForTelemCounters2": "False",
  "FFlagGraphicsGLEnableSuperHQShadersExclusion": "False",
  "FFlagTopBarUseNewBadge": "false",
  "DFStringCrashUploadToBacktraceBaseUrl": "null",
  "FFlagTrackMacWebLaunchFlow": "False",
  "DFIntCSGLevelOfDetailSwitchingDistance": "1",
  "DFFlagDebugPerfMode": "True",
  "FIntV1MenuLanguageSelectionFeaturePerMillageRollout": "0",
  "FFlagCloudsReflectOnWater": "True",
  "FFlagNewLightAttenuation": "True",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "DFStringTelemetryV2Url": "null",
  "FFlagDebugGraphicsPreferVulkan_enabled": "True",
  "FFlagPreloadTextureItemsOption4": "True",
  "FFlagVoiceBetaBadge": "false",
  "FFlagAdServiceEnabled": "False",
  "FFlagPreloadMinimalFonts": "True",
  "DFIntCrashUploadToBacktracePercentage": "0",
  "DFIntPredictedOOMPercent": "0",
  "FFlagLocServicePerformanceAnalyticsEnabled": "False",
  "FIntReportDeviceInfoRollout": "0",
  "FFlagTrackWinWebLaunchFlow": "False",
  "FIntLmsClientRollout2": "0",
  "FFlagDebugGraphicsPreferMetal": "True",
  "\u0022FIntCameraMaxZoomDistance\u0022: \u002299999\u0022": "99999",
  "DFFlagAudioDeviceTelemetry": "False",
  "FStringPerformanceSendMeasurementAPISubdomain": "opt-out",
  "\u0022DFIntCSGLevelOfDetailSwitchingDistanceL12\u0022": "0",
  "DFStringCrashUploadToBacktraceMacPlayerToken": "null",
  "FFlagFacialAnimationStreamingServiceUserSettingsOptInAudio": "False",
  "FFlagNullCheckCloudsRendering": "True",
  "FIntAbuseReportScreenshotMaxSize": "0",
  "DFFlagEnableLightstepReporting2": "False",
  "DFFlagTextureQualityOverrideEnabled": "False",
  "DFFlagAddUserIdToSessionTracking": "False",
  "DFFlagPredictedOOM": "False",
  "FIntTaskSchedulerAutoThreadLimit": "8",
  "FFlagGpuGeometryManager7": "True",
  "DFIntUserIdPlayerNameCacheSize": "33554432",
  "DFIntStartupTracingInfluxRollout": "0",
  "\u0022DFIntCSGLevelOfDetailSwitchingDistanceL34\u0022": "0",
  "GoogleAnalyticsAccountPropertyID": "null",
  "FFlagCommitToGraphicsQualityFix": "True",
  "FFlagEnableInGameMenuChromeABTest": "True",
  "GoogleAnalyticsAccountPropertyIDPlayer": "null",
  "DFIntCSGLevelOfDetailSwitchingDistanceL34": "0",
  "DFStringHttpPointsReporterUrl": "null",
  "FIntFRMMaxGrassDistance": "0",
  "FFlagDebugForceChatDisabled": "False",
  "DFFlagAvatarChatServiceUserPermissionsAudioEligible": "False",
  "FFlagEnableAccessibilitySettingsAPIV2": "True",
  "FFlagEnableBetaBadgeLearnMore": "false",
  "FFlagBetaBadgeLearnMoreLinkFormview": "false",
  "FFlagControlBetaBadgeWithGuac": "false",
  "FStringVoiceBetaBadgeLearnMoreLink": "null"
}

**Comment by pizzaboxer** [comment]
You're using the RCO flag list. Delete all your flags and only use ones that you fully know the function of.

**Comment by XRAZERGAMERX** [comment]
Welö i need fps boosting

**Comment by pizzaboxer** [comment]
I don't care, don't use these or you're going to keep running into unexpected issues like this. If you want options that you could possibly use for FPS unlocking (that are actually better documented), then see [this megalist](https://github.com/GoingCrazyDude/fastflags-collection/blob/main/README.md).

**Comment by XRAZERGAMERX** [comment]
is this good ?

{
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableV3MenuABTest3": "False",
  "FFlagEnableMenuModernizationABTest2": "False",
  "FFlagEnableMenuModernizationABTest": "False",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableInGameMenuModernization": "True",
  "FFlagEnableInGameMenuControls": "True",
  "FFlagFixGraphicsQuality": "True",
  "DFFlagDisableDPIScale": "True",
  "FFlagDebugForceFutureIsBrightPhase3": "True",
  "DFIntTaskSchedulerTargetFps": "999999999",
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "DFLogHttpTraceLight": "0",
  "DFIntCanHideGuiGroupId": "32380007",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFIntDebugFRMQualityLevelOverride": "21",
  "FFlagDebugGraphicsPreferD3D11": "True",
  "FIntDebugForceMSAASamples": "3"
}

**Comment by pizzaboxer** [comment]
Yes, that is much better. Though, D3D11 is already used by default so you don't need to specify that. See if your issue still occurs.

**Comment by XRAZERGAMERX** [comment]
no problems occur
