### ISSUE TITLE
[BUG] Multi-instance launching sometimes not working properly

### ISSUE THREAD

**Issue by GrksReal** [pizzaboxer/bloxstrap#1207]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Trying to use multi-instance by joining the same server with 2 different account from 2 different browsers (Google Chrome and Opera GX) Once I'm trying to join the same server, it closes the prev one. Why?

**Comment by pizzaboxer** [comment]
The multi-instance handler is sort of picky and unreliable at the moment. Ensure that no instances of Roblox are running in the background (check Task Manager to make sure of that), and then launch all your instances. 

Also, be sure that you actually are using Bloxstrap (as in, you're seeing the launcher for it whenever you launch Roblox). If not, then launch the "Play Roblox" shortcut on the desktop to ensure Bloxstrap is used for web launches.

**Comment by NukeThief** [comment]
also, bloxstrap's multi-instance breaks sounds in games like REx:Reincarnated, even if there's no instances alongside it. When the feature is enabled. The sounds break, but with programs like Roblox Account Manager it's fine.

**Comment by pizzaboxer** [comment]
> even if there's no instances alongside it.

What? Are you saying that just having the option enabled in the menu causes this?

Also, breaks in what way?

**Comment by lokzz** [comment]
> and then launch all your instances.

in what way? do i launch them all at once?
because multi-instance is still broken for me

**Comment by pizzaboxer** [comment]
>  some sounds stop working

Do you have any integrations enabled in the menu?

**Comment by pizzaboxer** [comment]
>  because multi-instance is still broken for me

**Comment by lokzz** [comment]
yes, the old roblox (previously opened ~20s) closes.

**Comment by pizzaboxer** [comment]
> yes, the old roblox (previously opened ~20s) closes.

You're sure that there's no Roblox instances running first before you try launching multiple of them? If so, then launch only one instance, and send the latest log file from the `%localappdata%\Bloxstrap\Logs` folder, where it'll be at either the top or the bottom of the list.

**Comment by lokzz** [comment]
ok
[Bloxstrap_20240310T074154Z.log](https://github.com/pizzaboxer/bloxstrap/files/14549304/Bloxstrap_20240310T074154Z.log)

**Comment by lokzz** [comment]
ok
[Bloxstrap_20240310T074154Z.log](https://github.com/pizzaboxer/bloxstrap/files/14549307/Bloxstrap_20240310T074154Z.log)

**Comment by pizzaboxer** [comment]
```
2024-03-10T07:41:54Z [App::OnStartup] Creating singleton mutex
2024-03-10T07:41:54Z [App::OnStartup] Warning - singleton mutex already exists!
```

Are you sure you launched just one? There appears to still be something running in the background. You might want to restart your PC first before trying again.

**Comment by lokzz** [comment]
weird - using `taskkill /f /im robloxplayerbeta.exe` says no processes were found
will try rebooting later, thanks

**Comment by lokzz** [comment]
update - waited a while and it seemed to fix itself?

**Comment by lokzz** [comment]
update 2 - problem happens while [Roblox Account Manager](https://github.com/ic3w0lf22/Roblox-Account-Manager) is running
