### ISSUE TITLE
bloxstrap not working

### ISSUE THREAD

**Issue by BlueYoshi2007** [pizzaboxer/bloxstrap#1208]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

for some reason bloxstrap is not working for me it is probably because roblox got an update
![image_2024-01-30_105017562](https://github.com/pizzaboxer/bloxstrap/assets/156502140/b99c8be6-fc8d-4798-8f09-b3513e3aad36)
![hmm](https://github.com/pizzaboxer/bloxstrap/assets/156502140/947d61d0-c301-441e-9538-a721e9cd698e)

**Comment by pizzaboxer** [comment]
See sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
