### ISSUE TITLE
[REQ] Introduce BloxstrapRPC in-game tests.

### ISSUE THREAD

**Issue by apprehensions** [pizzaboxer/bloxstrap#1211]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Introduce BloxstrapRPC rich presence tests in the form of Roblox expriences. The game will submit BloxstrapRPC SetRichPresence commands, and perform other logic testing such as reserved servers, private servers (if applicable), teleporting, etc. It will ask the tester to check the Discord rich presence to what is expected or wanted in game.

This will be useful for other Roblox bootstrappers such as Applejuice, Vinegar, and even Bloxstrap itself when changing or rewriting certain ActivityWatcher logic.

**Comment by pizzaboxer** [comment]
oh yeah i forgot to add this to the todo list

**Comment by pizzaboxer** [comment]
yeah this should be good enough 

https://www.roblox.com/games/13307536247/Bloxstrap-Test-Place

**Comment by pizzaboxer** [comment]
fine

**Comment by pizzaboxer** [comment]
ok there
