### ISSUE TITLE
[REQ] Remove In-Game Menu V2 from the escape menu list

### ISSUE THREAD

**Issue by bluepilledgreat** [pizzaboxer/bloxstrap#1212]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Roblox updates are making it less stable

**Comment by pizzaboxer** [comment]
> Roblox updates are making it less stable

How bad is it now? It's been a while since I last checked.

**Comment by githubberguy** [comment]
but it works fine? you're ruining some lost media man.

**Comment by Kluts123** [comment]
Why remove the v2 menu? I like the v2 menu... :(

**Comment by githubberguy** [comment]
yeah, why bro?

**Comment by bluepilledgreat** [comment]
> Why remove the v2 menu? I like the v2 menu... :(

The menu is becoming increasingly broken with every UI update Roblox makes.

**Comment by Kluts123** [comment]
Well why not add a warn to it thats says that it is buggy...?

**Comment by pizzaboxer** [comment]
Unless it's borderline unusable, I'm simply leaning on just adding a warning for it like we are with the other potentially problematic presets.

**Comment by bluepilledgreat** [comment]
closed because of recent updates

**Comment by githubberguy** [comment]
wtf bloxstrap v3.0.0?
