### ISSUE TITLE
[BUG] My bloxstrap wont work Can u Please Fix This

### ISSUE THREAD

**Issue by chipflakey7** [pizzaboxer/bloxstrap#1213]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My Bloxstrap Wont Work

**Comment by pizzaboxer** [comment]
Can you be more specific about your issue please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
