### ISSUE TITLE
[BUG] the update never happens and it keeps looping the update

### ISSUE THREAD

**Issue by hadesiak130** [pizzaboxer/bloxstrap#1214]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

whenever it updates bloxstrap the progress goes to ~49% and jt just restarts

**Comment by pizzaboxer** [comment]
Open the `%localappdata%\Bloxstrap\Logs` folder, and upload the latest log file here please. It should either be at the top or bottom of the file list.

**Comment by hadesiak130** [comment]
[Bloxstrap_20240131T192237Z.log](https://github.com/pizzaboxer/bloxstrap/files/14126999/Bloxstrap_20240131T192237Z.log)

**Comment by pizzaboxer** [comment]
Alright, I see what's happening. If you had waited long enough then you would have eventually seen the error that was being described here:
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
This should be relevant to your issue, so read through the information given here and see if it can help you solve your issue.
