### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SimonHelping** [pizzaboxer/bloxstrap#1215]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Nothing is working is bloxstrap down i can open it but any mods / fastflags dont work

**Comment by pizzaboxer** [comment]
Read through sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter, it should help to address your issue.

**Comment by SimonHelping** [comment]
I have but it's still the same

**Comment by pizzaboxer** [comment]
Just so I can get a better idea of what's going on, what options have you configured that you're trying to use which aren't working?

**Comment by SimonHelping** [comment]
It's working now after I enabled all menumodrenization but it seems a bit laggy now
Can I ask you what menumodrenization is?

**Comment by pizzaboxer** [comment]
> It's working now after I enabled all menumodrenization but it seems a bit laggy now

What? You enabled what?

**Comment by SimonHelping** [comment]
![Screenshot_2024-02-04_113528](https://github.com/pizzaboxer/bloxstrap/assets/158373675/615f1191-3cb8-41ef-ac19-e27db62e4183)
I have no idea where they came from didn't have them before but it's doing something to make me lag

**Comment by pizzaboxer** [comment]
Okay, I'm a little confused here
- Why did you manually change the values of those flags?
- Changing those aren't the reason for it suddenly working now
- What do you mean by "it seems a bit laggy now"? In what way?

**Comment by SimonHelping** [comment]
1 I didn't change anything 
2 after disabling them it works fine now 
I have no idea where they came from as far as I know roblox updated and they came out of no where so I was confused with what they did and what they are (I still don't know what they do) but everything is normal now kind of.

As for why I was lagging I still don't know it had something to do with menumodrenization

Sorry if you're getting no where with this

**Comment by pizzaboxer** [comment]
> 1 I didn't change anything

You just said "It's working now after I enabled all menumodrenization"

> I have no idea where they came from 

These are preset flags that are configured when you choose a preferred escape menu version - they're hidden under preset flags for a reason.

> As for why I was lagging I still don't know it had something to do with menumodrenization

Lagging in what way?

If you believe this to be the correlation (which I doubt), then set the preferred escape menu version to 'Default' and see if it goes away

**Comment by SimonHelping** [comment]
My fast flags weren't working at all so I enabled all those menumodrenization then it was working fine again with lower fps for some reason then I turned off all menumodrenization and my flags were working fine still but again fps seems to be lower before I had any of these problems I was  running with 150 /200 fps now I get 60 /80 fps
Not sure if it had anything to do with bloxtrap but I can't find any other reason I could be getting fps drop also menu version was always on default.
 is there some way I can reset all settings?

**Comment by pizzaboxer** [comment]
> is there some way I can reset all settings?

By default all the options in the FastFlags menu are disabled, or are otherwise set on a default/neutral option. I'm assuming there's nothing else you've touched in the flag editor.

> now I get 60 /80 fps

That wouldn't have been caused by any of this.

**Comment by SimonHelping** [comment]
Right I'll look for the cause of my fps drop 
Thanks for the help sorry for the trouble
