### ISSUE TITLE
[BUG]Running in the background even after it closes.

### ISSUE THREAD

**Issue by qTani** [pizzaboxer/bloxstrap#1216]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i have been using bloxstrap for a day now and its running well but the only problem i have is when it comes to closing roblox after it closes in my taskbar but roblox is still running with bloxstrap in my task managaer.I do not know why it does this i tried everything please help.
![Screenshot 2024-01-31 224844](https://github.com/pizzaboxer/bloxstrap/assets/158404290/52f5d27f-d769-499d-b789-a7a854bca9b0)
Only closes after i end task it should just close it self after i close the game.

**Comment by qTani** [comment]
no i don't have it enabled

**Comment by pizzaboxer** [comment]
Just for the sake of clarity, is the toggle on or off?

**Comment by qTani** [comment]
its off

**Comment by qTani** [comment]
Okay im back so i fixed it.I uninstalled bloxstraps and roblox completely.Installed all flags and mods back it works properly now it closes in task manager as well.

**Comment by pizzaboxer** [comment]
Is this happening only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
