### ISSUE TITLE
[BUG] My friend doesn't have the "Bloxstrap Menu" app.

### ISSUE THREAD

**Issue by KiritosbigW** [pizzaboxer/bloxstrap#1217]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Basically, i made 2 of my friends install bloxstrap for the font features + other cool things, one of them works perfectly fine but the other's bloxstrap menu wont pop up.

**Comment by pizzaboxer** [comment]
> the other's bloxstrap menu wont pop up.

What happens when they try to open it?

**Comment by YTLaunchszn** [comment]
im having this same issue when i use it i cant seem to find the menu it just doesnt show when i search but i can open bloxstrap which just runs my roblox instead of the menu which i need to access

**Comment by pizzaboxer** [comment]
> it just doesnt show when i search

Instead of searching for it, look for it yourself in your application list.

**Comment by bluepilledgreat** [comment]
Closing as OP has not responded in a month
