### ISSUE TITLE
[REQ] Ability to toggle boolean flags

### ISSUE THREAD

**Issue by GoingCrazyDude** [pizzaboxer/bloxstrap#1223]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Instead of renaming the value to true or false, there should be some sort of keybind or button to just toggle the value to true or false. 

Repost of [this post](https://discord.com/channels/1099468797410283540/1202710540091396197) on the request of bluepilledgreat aka Matt

**Comment by GoingCrazyDude** [comment]
Also edge case of when a flag has a boolean and a integer in the same field has to be handled :p

**Comment by bluepilledgreat** [comment]
Low priority because of #1169

**Comment by GoingCrazyDude** [comment]
You are low priority
