### ISSUE TITLE
[BUG] bloxstrap disconnects from wifi as soon as i open it

### ISSUE THREAD

**Issue by A2Yves** [pizzaboxer/bloxstrap#1226]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I launch bloxstrap my pc disconnects from wifi this only happens when i open bloxstrap because it doesn't happen with roblox any fix for this ty

**Comment by pizzaboxer** [comment]
That's a weird issue, can you just better clarify when exactly it occurs? Is it when you first see the Bloxstrap launcher? Is it after Roblox launches?

**Comment by A2Yves** [comment]
Its after Roblox launches but i figured it out its every time i go above 60fps my game just disconnects from wifi or the ping gets really high and i get a lot of lag spikes any idea why? Ty

**Comment by pizzaboxer** [comment]
Yep, sounds like an issue with the framerate limiter. In which case, make sure it's set to 0 to restore it to its defaults. See if you still experience any issues there.

**Comment by A2Yves** [comment]
I did that when set to 0 there is no problems but does that mean that i cant use the fps unlocker?

**Comment by pizzaboxer** [comment]
>  does that mean that i cant use the fps unlocker?

Unfortunately, yes. https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#framerate-limit
