### ISSUE TITLE
[REQ] Ability to disable this

### ISSUE THREAD

**Issue by Itsappuru** [pizzaboxer/bloxstrap#1229]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Its kinda annoying cuz I'm testing stuff and i need to click a button eraaaaaaaaaaaaaahhhhhhhh
![image_2024-02-02_211218198](https://github.com/pizzaboxer/bloxstrap/assets/106469120/aa20b410-0d75-470c-af9a-314da63976ec)

**Comment by pizzaboxer** [comment]
Can be replaced with a non-obtrusive toast notification in the menu
