### ISSUE TITLE
[BUG]- My Bloxtrap crashes every time I open it

### ISSUE THREAD

**Issue by IchikaN1to** [pizzaboxer/bloxstrap#1233]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-02-02 173900](https://github.com/pizzaboxer/bloxstrap/assets/158605207/aca8c0d9-4fa6-4761-b839-e8af8dc7358c)

**Comment by IchikaN1to** [comment]
I know it says Roblox Crash but I promise you it isn't roblox, its bloxtrap

**Comment by IchikaN1to** [comment]
anyone help? Its been 4 hrs

**Comment by pizzaboxer** [comment]
Have you confirmed that this only happens with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by IchikaN1to** [comment]
> Have you confirmed that this only happens with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Yes

**Comment by pizzaboxer** [comment]
What settings have you configured in the Bloxstrap Menu?

**Comment by IchikaN1to** [comment]
> What settings have you configured in the Bloxstrap Menu?

is there a way to copy the settings?

**Comment by IchikaN1to** [comment]
activity tracking=On
see server location=Off
show game activity=On
allow activity joining=On
multi-instance launching=Off
old death sound=On
cursor=Default
OG editor background=Off
emulate OG character sounds=Off
disable desktop app=Off
emoji type=Default
disable fullscreen optimizations=Off
frame limit=9999 (I tried 0 and it didnt work)
lighting tech=Future
escape menu ver=Default
enable hide GUI=Off
OG textures=Off
preserver render quality with display scaling=Off
alt graphics quality selector=On
(appearance options are default)
auto update bloxstrap=On

**Comment by IchikaN1to** [comment]
> activity tracking=On see server location=Off show game activity=On allow activity joining=On multi-instance launching=Off old death sound=On cursor=Default OG editor background=Off emulate OG character sounds=Off disable desktop app=Off emoji type=Default disable fullscreen optimizations=Off frame limit=9999 (I tried 0 and it didnt work) lighting tech=Future escape menu ver=Default enable hide GUI=Off OG textures=Off preserver render quality with display scaling=Off alt graphics quality selector=On (appearance options are default) auto update bloxstrap=On

couldnt copy them but hopefully this works

**Comment by pizzaboxer** [comment]
What did you do?
