### ISSUE TITLE
[REQ] Add warning when setting "Preferred lighting technology"

### ISSUE THREAD

**Issue by 0xFE0F** [pizzaboxer/bloxstrap#1234]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I own a game running compatibility lighting, it specifically REQUIRES compatibility lighting for all the lighting in the game to look right.

With a recent update to my game that added lights with max brightness (isn't that intense on compatibility, but all other lighting technologies make it very bright), Bloxstrap users are making complaints of the lighting being messed up because they don't understand the impact lighting technology has on games

\-

This issue could be mitigated with a simple warning mentioning that lighting technology can heavily impact games' lighting, and to be mindful when using it

**Comment by d44df016fe28bc8d5974** [comment]
add this

**Comment by pizzaboxer** [comment]
> Bloxstrap users are making complaints of the lighting being messed up because they don't understand the impact lighting technology has on games

Yeah, we're well aware of that. People complain about it to us too, you're not alone on this. I've been wanting to lock this down and add extra warnings for this for a while, but I'm not actively working on this, and I won't be for quite a while. We're sort of stuck with this for now unfortunately.

**Comment by pizzaboxer** [comment]
Released in 2.7.0 (or at least I hope what I've done is sufficient)
