### ISSUE TITLE
[BUG] Rich Presence detecting wrong Discord account

### ISSUE THREAD

**Issue by lucii-morningstar** [pizzaboxer/bloxstrap#1236]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've downloaded Bloxstrap yesterday and the Rich Presence was working perfectly on my Discord account, however today it doesn't show up on my Discord profile. If it helps, I have Vencord on. I'm also sharing a computer with another user, however I troubleshooted that by quitting Discord and making sure that his Discord account isn't logged in my side of the computer. It still doesn't work. What else should I do?

**Comment by pizzaboxer** [comment]
If it's "detecting wrong Discord account", I don't know what to tell you other than that you're logged into the Discord desktop app with the wrong account.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
