### ISSUE TITLE
[REQ] Automatically delete %temp%/Roblox folder

### ISSUE THREAD

**Issue by DesMS** [pizzaboxer/bloxstrap#1237]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

There is currently a bug with Roblox where it will sometimes fail to start, and will never start up until you delete the %temp%/Roblox folder.

Video of the bug:
https://github.com/pizzaboxer/bloxstrap/assets/84988422/55833ca1-0e38-43e6-adcf-659be4960747

With this, there could be a feature to where it automatically deletes the %temp%/Roblox folder every startup, or every time roblox doesn't create a window in enough time.

**Comment by Findyourlimit** [comment]
no clue how that stops roblox from launching


nice desktop btw

**Comment by pizzaboxer** [comment]
> There is currently a bug with Roblox where it will sometimes fail to start, and will never start up until you delete the %temp%/Roblox folder.

...I guess that would explain why doing a disk cleanup (as described in https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch) helps to resolve issues with Roblox not launching? That's interesting.

**Comment by DesMS** [comment]
Using handle ([microsoft.com link](https://learn.microsoft.com/en-us/sysinternals/downloads/handle)), I got this for the normal roblox opening sequence (One that works):

![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/44fc670c-b620-4215-842e-d6c6ef2f3e85)

Checking on a failed startup, I noticed that the ReShade64.dll is loaded:

![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/a3109b4f-0250-4d80-b8a2-2880ad5f7c5d)

And that the temp folder isn't even accessed either time roblox is opened (What?)

I do have ReShade installed, but I have it configured for BeamNG.Drive, and not Roblox. I don't know why Roblox would even attempt to load the ReShade dll (Maybe it's some sort of weird way that ReShade checks if the game is to be loaded? And it's interfering with the Roblox anticheat?)

![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/72cbb5d5-62b6-4607-9745-fd794df5f222)

**Comment by DesMS** [comment]
I don't think this is an issue with Windows, it's either an issue with Roblox or ReShade (I'm guessing ReShade, but idk why it would fix it by deleting the Roblox temp folder, as that's not even where ReShade stores it's temporary stuff for programs)

**Comment by pizzaboxer** [comment]
> I do have ReShade installed, but I have it configured for BeamNG.Drive, and not Roblox. 

Are you sure that ReShade isn't globally injecting itself into any application that's using DirectX?

**Comment by DesMS** [comment]
Tbh I don't know how ReShade works, I think it launches itself with the Nvidia driver, but, I don't understand why clearing Roblox's temp folder would fix this

**Comment by DesMS** [comment]
After doing some research, ReShade injects itself into the graphics driver (In this case, Nvidia), and then, whenever a program that uses Vulkan (The mode I chose) launches, it will attempt to inject itself. What is confusing is that clearing the Roblox temp folder fixes this.

I saw online that there was an option to disable global vulkan injection, but reinstalling ReShade, it does not have an option to disable it.

I also saw that in order to disable it globally, you had to go into the registry and goto Vulkan, but there is nothing there relating to ReShade
![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/02a2c4ac-6e7b-4717-987e-3489f986ae4a)

**Comment by DesMS** [comment]
Just created some code that fixes it, https://github.com/pizzaboxer/bloxstrap/pull/1243

**Comment by DesMS** [comment]
Yup, that was where I got the idea for the pull request
![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/bb754c5f-a410-4b75-b666-fd7c97b22676)
It automatically does this if ReShade is installed (The other fixes don't work)

**Comment by bluepilledgreat** [comment]
This issue is entirely a Reshade issue, not ours.

**Comment by pizzaboxer** [comment]
Actually, what version of ReShade are you using?

**Comment by DesMS** [comment]
ReShade 6.0.1

**Comment by axellse** [comment]
Maybe you could just have a dialog box informing the user about why Roblox won't start?

**Comment by pizzaboxer** [comment]
I've just realized something: I completely forgot that I had ReShade installed!

![firefox_jcYQ8tgOL5](https://github.com/pizzaboxer/bloxstrap/assets/41478239/bf151a89-f03e-47e4-a2d2-69146cb942e1)

And I was wondering why Roblox with Vulkan wasn't working for me. Sure enough, temporarily renaming the folder in ProgramData makes Roblox laucnh again. I wonder how many other people this affects too.

> I also saw that in order to disable it globally, you had to go into the registry and goto Vulkan, but there is nothing there relating to ReShade

Look in HKEY_LOCAL_MACHINE, not HKEY_CURRENT_USER. It's definitely there.

If I'm going to add a workaround for this, I'm strongly gravitating towards simply altering the registry key instead of renaming the folder. Changing the value of the key from 0 to 1 will disable it. I mean, it would also require admin perms, but it wouldn't be as bad.

**Comment by DesMS** [comment]
Ah, I'm not the only person experiencing this, I'll check `HKEY_LOCAL_MACHINE` when I get home, I'll also check if setting it to a `1` will stop ReShade from launching with BeamNG

**Comment by DesMS** [comment]
Axellse, I think that's a good idea, if Roblox doesn't create a Window in, let's say 30 seconds, it will automatically ask you if you want to enable the ReShade fix (If ReShade is installed on the system)

**Comment by DesMS** [comment]
It's not, I said "If it detects that ReShade is installed", it's not hard to detect for dll injection (You can even do it with cmd), even if you don't want to test for dll injection, you can always check for the ReShade folder in ProgramData.

Also, notice how I said it should ask you if you would like to enable it, not automatically enable it. It's a much better system than just relying on you to know that ReShade is causing the issue

**Comment by DesMS** [comment]
> Using handle ([microsoft.com link](https://learn.microsoft.com/en-us/sysinternals/downloads/handle)), I got this for the normal roblox opening sequence (One that works):
> 
> ![image](https://private-user-images.githubusercontent.com/84988422/302058301-44fc670c-b620-4215-842e-d6c6ef2f3e85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTI0MTMsIm5iZiI6MTcwNzE1MjExMywicGF0aCI6Ii84NDk4ODQyMi8zMDIwNTgzMDEtNDRmYzY3MGMtYjYyMC00MjE1LTg0MmUtZDZjNmVmMmYzZTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGVlOGUxYTNhMzJiMmIwZTg1MTVhNjdlNGU3YzZmZGZjNDAwM2Q3YTU0MjdkNmIxNWY4NDA2YTRkN2NmMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EXnyt3EH462XgTEXMHwLe9x_uApQhPBT2uYAbguYab0)
> 
> Checking on a failed startup, I noticed that the ReShade64.dll is loaded:
> 
> ![image](https://private-user-images.githubusercontent.com/84988422/302058549-a3109b4f-0250-4d80-b8a2-2880ad5f7c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTI0MTMsIm5iZiI6MTcwNzE1MjExMywicGF0aCI6Ii84NDk4ODQyMi8zMDIwNTg1NDktYTMxMDliNGYtMDI1MC00ZDgwLWI4YTItMjg4MGFkNWY3YzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYjlmZjE5NzZkZWNjMDEwNDMwNGZmYzA1NWFkNGFhMjk5YzhlYzk4N2YxNmJhNDgyYjdiZTlkYzc5MjM1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oNAmmUDhvCLvX4lLFG1kDH5oWmJkztOxKLWy5oEjeNo)
> 
> And that the temp folder isn't even accessed either time roblox is opened (What?)
> 
> I do have ReShade installed, but I have it configured for BeamNG.Drive, and not Roblox. I don't know why Roblox would even attempt to load the ReShade dll (Maybe it's some sort of weird way that ReShade checks if the game is to be loaded? And it's interfering with the Roblox anticheat?)
> 
> ![image](https://private-user-images.githubusercontent.com/84988422/302059964-72cbb5d5-62b6-4607-9745-fd794df5f222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTI0MTMsIm5iZiI6MTcwNzE1MjExMywicGF0aCI6Ii84NDk4ODQyMi8zMDIwNTk5NjQtNzJjYmI1ZDUtNjJiNi00NjA3LTk3NDUtZmQ3OTRkZjVmMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNzE2YjIzNDViMGJkMGJkNDk2YTk0MTQ5ZDBiODU4NTJmNmIyNzlkZGM4YjQ1MzZiOTgyZjAzZDBkMzUxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJ_NHC2ahZEqDBGjgU5M-91sRkiz-bFUSrtHUiOb0jM)

Here is an example of how to check, using *cmd* (How I found out it was ReShade causing the issue)

**Comment by DesMS** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/bb7644db-00a0-49e4-96ed-9a1c678a2bc0)

Changing the key from a 0 to a 1 (In order to disable it) also disables it for BeamNG, and in order to re-enable it, you would likely have to request admin every time (Due to it being in `HKEY_LOCAL_MACHINE`).

Also, changing `Software\Khronos\Vulkan\ImplicitLayers` for every user, but keeping it different from the current user isn't ideal either

**Comment by DesMS** [comment]
I've also tried disabling it through `HKEY_CURRENT_USER\Software\Khronos\Vulkan\ImplicitLayers`, but adding a new `dword-32` key with the name `C:\ProgramData\ReShade\ReShade64.json`, and setting it to `1`, but that didn't work.

**Comment by pizzaboxer** [comment]
> Also, this is an issue with ReShade 5.0.0+, not 6.0.0+.

Right, that's what I was wondering.

> They removed the option in favor for "per-game" installation, but that installation is still bugged with it injecting itself into all programs, so this isn't even considered "global installation" to ReShade, but it still injects globally

In which case, shouldn't you just remove the global injection yourself?

**Comment by DesMS** [comment]
> In which case, shouldn't you just remove the global injection yourself?

When I get home, I'll check the difference between 4.9 and 5.0, and see if disabling global injection in 4.9 does the same thing as 5.0, or if it does something different. I also mean that it's 5.0.0+, not just 6.0.0+ (6.0 is also affected)

**Comment by pizzaboxer** [comment]
I know what you mean, but my suggestion still stands. If ReShade really isn't supposed to be injecting itself globally anymore, that needs to be brought up on the ReShade forum, and we should put an advisory for that on the Wiki instead of doing what we originally intended to do.

**Comment by DesMS** [comment]
I'll create a post, but I believe I saw somewhere where he said that the injected dll shouldn't activate a anticheat, due to it not loading anything if it's the wrong game

**Comment by bluepilledgreat** [comment]
> injected dll shouldn't activate a anticheat

Injecting any untrustworthy DLLs into the Roblox client will cause an immediate crash

**Comment by DesMS** [comment]
> Injecting any untrustworthy DLLs into the Roblox client will cause an immediate crash

We know that's what's causing the crash already

**Comment by DesMS** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/84988422/087d541b-068b-4b6c-b5d7-58708bf3a63c)

**Comment by axellse** [comment]
> Axellse, I think that's a good idea, if Roblox doesn't create a Window in, let's say 30 seconds, it will automatically ask you if you want to enable the ReShade fix (If ReShade is installed on the system)

my idea is not to ask the user to apply the fix, its just to inform the user why roblox wont start.

**Comment by SecondNewtonLaw** [comment]
The fact this deviated from "Automatically delete %TEMP%/Roblox Folder" to a talk about ReShade is quite funny. Either way, doing both is a arguably bad idea, the Roblox folder on temp holds caches on reciently visited games so you don't redownload assets, deleting it defeats the purpose of it, as for ReShade. I honestly don't understand why you would continue using it on Roblox, Hyperion won't load it without thinking its an attempt at dll injection (Which it is!)

**Comment by pizzaboxer** [comment]
> I honestly don't understand why you would continue using it on Roblox, 

They're not trying to use it on Roblox though. The problem is that ReShade globally injects itself into any Vulkan application.

**Comment by ProjectHSI** [comment]
> They're not trying to use it on Roblox though. The problem is that ReShade globally injects itself into any Vulkan application.

ReShade does this since it doesn't supplant the Vulkan DLL like DirectX or OpenGL. It works by registering itself into the registry as a "Implict Layer", meaning it will get loaded by Vulkan whether or not the program asks for it (unlike other layers in Vulkan, which have to be requested).

This may be incorrect but they have to register ReShade as a layer for it to work properly. Forgot why they needed to do this though.

**Comment by pizzaboxer** [comment]
Yeah, I realized pretty quickly why they have to do it that way.
