### ISSUE TITLE
[REQ] Close Roblox "Do not show again"

### ISSUE THREAD

**Issue by vsvpp** [pizzaboxer/bloxstrap#1245]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Do not show this again when closing Roblox using Bloxstrap Tray

![image](https://github.com/pizzaboxer/bloxstrap/assets/106433721/8fad9e96-9141-44d3-85b2-a5e15f0def02)

**Comment by GoingCrazyDude** [comment]
a wild fastvariable appears

**Comment by d44df016fe28bc8d5974** [comment]
fastvariable 🔥 🔥 🔥 🔥 🔥

**Comment by pizzaboxer** [comment]
closing this since it's too much effort for something pretty pointless honestly
