### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (clientsettings.roblox.com:443)

### ISSUE THREAD

**Issue by PyxlDebt** [pizzaboxer/bloxstrap#1246]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I run bloxstrap this error appears, "System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (clientsettings.roblox.com:443)."I've tried uninstalling bloxstrap and numerous times and nothing has happened. When I run Roblox while bloxstrap is uninstalled everything is perfectly fine. This is a screen shot showing what's happening. 
![Screenshot 2024-02-03 195559](https://github.com/pizzaboxer/bloxstrap/assets/146288652/38d630b8-a46f-4f82-aa1f-0bc38799c2a4)

**Comment by pizzaboxer** [comment]
Why'd you open this four hours after I had already responded to you on Discord?
