### ISSUE TITLE
[REQ] Icon Problem

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1247]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

you know how 2019 had 2 icons, a black one and the modern one
WHERE THE HECK IS THE BLACK ONEEEEEEEEEEE
fix now or i melt ur ice

**Comment by bluepilledgreat** [comment]
@pizzaboxer HOW COULD YOU!

**Comment by githubberguy** [comment]
YEAH HOW COULD HEEEEEEEE

**Comment by pizzaboxer** [comment]
>  WHERE THE HECK IS THE BLACK ONEEEEEEEEEEE

The black one was never used in the launcher. Case is null and void.

**Comment by githubberguy** [comment]
it was used, it was even used in the goddamn loading screen

**Comment by pizzaboxer** [comment]
> it was used

When was it used in the launcher?

**Comment by githubberguy** [comment]
i just said it "the app logo, the ROBLOX booting load not to a server the mobile one."
