### ISSUE TITLE
Something to read please.

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1249]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

ok, i thought no one did a beta 2.6.0, guess what? one of your devs forked it, it has some of the new features
i thought i suggested that about "Beta Test" updates... Seriously if you didnt do it you should fire the dev that did it, check the discord servers < support n bugs
i just got this 2.6.0 version, please if you do this then just make it real, not doing it secretly

**Comment by bluepilledgreat** [comment]
It is real

**Comment by githubberguy** [comment]
i know

**Comment by githubberguy** [comment]
i had forgor ur name

**Comment by GoingCrazyDude** [comment]
what
