### ISSUE TITLE
Additional FastFlag mod presets

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#125]
I'm planning to add more FastFlag mod presets to Bloxstrap in v2.2.0. So far, I'm thinking of adding these.

- [x] Setting TaskScheduler FPS cap to replace rbxfpsunlocker (`DFIntTaskSchedulerTargetFps`)
- [x] Toggle between Desktop and Mobile Lua app interface (`FFlagLuaAppSystemBar`)
- [x] Toggle between showing consolidated 0-10 or fine-grained 0-21 graphics quality levels in settings (`FFlagFixGraphicsQuality`)
- [x] Choosing between enabling the v1, v2 or v3 ingame menu (`FFlagDisableNewIGMinDUA` for v1 only, `FFlagEnableInGameMenuV3` for v3 only)
- [x] Toggle between Future and Voxel lighting (`FFlagForceFutureIsBrightPhase3`, `DFFlagDebugRenderForceTechnologyVoxel`, thanks @EasternBloxxer)
- [x] ~Disabling analytics and telemetry~ (cancelled, extremely inefficient, you're better off just installing adguard or smth)

If any of you guys see this and you can think of anything extra to add, feel free to leave a comment.

**Comment by EasternBloxxer** [comment]
FFlagForceFutureIsBrightPhase3 forces FiB

**Comment by pizzaboxer** [comment]
> FFlagForceFutureIsBrightPhase3 forces FiB

are you sure this actually does anything

![RobloxPlayerBeta_R817Hp8T1G](https://user-images.githubusercontent.com/41478239/232288989-478026d6-682c-4b5a-b4ac-c4fa2b23aaf2.jpg)
![RobloxPlayerBeta_NONz8fsaBd](https://user-images.githubusercontent.com/41478239/232288990-43e4dee2-e8a8-4e71-8c31-1fa9a5c1380b.jpg)

**Comment by EasternBloxxer** [comment]
It seems like they have recently removed it
![image](https://user-images.githubusercontent.com/54174182/232302534-0c43d067-ea8d-456f-a427-e8748faca699.png)

**Comment by EasternBloxxer** [comment]
Nevermind FFlagDebugForceFutureIsBrightPhase3 is a thing. Not sure if it was always named that and i messed it up or they changed it lmao
![image](https://user-images.githubusercontent.com/54174182/232303568-ac6fad44-f134-4be9-8e3f-3bdceaf64de7.png)

**Comment by EasternBloxxer** [comment]
> I feel like "FIntTaskSchedulerAutoThreadLimit": [cpu threads] improves performance by a lot

🤔

**Comment by Loge123** [comment]
> Nevermind FFlagDebugForceFutureIsBrightPhase3 is a thing. Not sure if it was always named that and i messed it up or they changed it lmao ![image](https://user-images.githubusercontent.com/54174182/232303568-ac6fad44-f134-4be9-8e3f-3bdceaf64de7.png)

I can't enable this, did it get removed?

**Comment by EasternBloxxer** [comment]
> > Nevermind FFlagDebugForceFutureIsBrightPhase3 is a thing. Not sure if it was always named that and i messed it up or they changed it lmao ![image](https://user-images.githubusercontent.com/54174182/232303568-ac6fad44-f134-4be9-8e3f-3bdceaf64de7.png)
> 
> I can't enable this, did it get removed?

`FFlagDebugForceFutureIsBrightPhase3` Is working fine for me.

**Comment by pizzaboxer** [comment]
oh this actually does do something, okay awesome i'll add it to the list

![RobloxPlayerBeta_L8AnsGA3aj](https://user-images.githubusercontent.com/41478239/233866485-992a52ee-c595-4e56-a669-0d9f9456ea65.jpg)
![RobloxPlayerBeta_vuqz0MNCqJ](https://user-images.githubusercontent.com/41478239/233866488-420d396b-8e7d-4c8c-bf0a-c926c337fbdc.png)

**Comment by EasternBloxxer** [comment]
There is also DebugRenderForceTechnologyVoxel. Not sure what this could be useful for but ¯\_(ツ)_/¯

**Comment by EasternBloxxer** [comment]
> Is there any FFlags that allow for forcing of different lighting modes besides FiB? Say forcing a game to run Compatibility Lighting instead of Future?

There is one for voxel.. but i am not sure if it works

**Comment by EasternBloxxer** [comment]
> > Is there any FFlags that allow for forcing of different lighting modes besides FiB? Say forcing a game to run Compatibility Lighting instead of Future?
> 
> There is one for voxel.. but i am not sure if it works
`DFFlagDebugRenderForceTechnologyVoxel` seems to be working now. Not sure what happened yesterday.
![image](https://user-images.githubusercontent.com/54174182/234796091-2e415bfd-3c67-4c49-838c-6df8289c578c.png)

**Comment by BaconismTV** [comment]
> > > Is there any FFlags that allow for forcing of different lighting modes besides FiB? Say forcing a game to run Compatibility Lighting instead of Future?
> > 
> > 
> > There is one for voxel.. but i am not sure if it works
> > `DFFlagDebugRenderForceTechnologyVoxel` seems to be working now. Not sure what happened yesterday.
> > ![image](https://user-images.githubusercontent.com/54174182/234796091-2e415bfd-3c67-4c49-838c-6df8289c578c.png)
 oh sweet thanks

**Comment by nonperforming** [comment]
Possibly setting `FFlagEnableReportAnythingAnalytics` to False or `DFStringRobloxAnalyticsURL` (currently set to https://ecsv2.roblox.com/, returns a blank page)  to localhost could disable analytics with one to a few flags

**Comment by pizzaboxer** [comment]
> Possibly setting `FFlagEnableReportAnythingAnalytics` to False or `DFStringRobloxAnalyticsURL` (currently set to https://ecsv2.roblox.com/, returns a blank page) to localhost could disable analytics with one to a few flags

I was considering this, but ultimately ended up abandoning this. FastFlags are not at all effective at disabling telemetry. You're better off just using something like AdGuard instead, and if you're really concerned about telemetry, it's a bonus since it applies for all websites and not just Roblox.

**Comment by Nooby-Hub** [comment]
how do i use FFlagLuaAppSystemBar?

**Comment by Melithical** [comment]
is there a fastflag for better ping in any area, or for no input lag?
