### ISSUE TITLE
Bloxstrap desktop bug

### ISSUE THREAD

**Issue by Globilly** [pizzaboxer/bloxstrap#1250]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime i open the Play Roblox, it doesn't open the roblox desktop app but opens a roblox tab on my browser. Does someone know how to fix this?

**Comment by pizzaboxer** [comment]
You have the desktop app disabled. You chose to disable it in the Bloxstrap Menu.

**Comment by Globilly** [comment]
> You have the desktop app disabled. You chose to disable it in the Bloxstrap Menu.

How can i enable it?

**Comment by pizzaboxer** [comment]
Open the Bloxstrap Menu, go to the Mods section. The option is there.
