### ISSUE TITLE
[BUG] Whenever i open roblox (not UWP version) it just shows white please help

### ISSUE THREAD

**Issue by Jxm3sy** [pizzaboxer/bloxstrap#1251]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever i open roblox it just shows white 
![image](https://github.com/pizzaboxer/bloxstrap/assets/158865468/b885fe03-a26c-4a44-b3fd-e1dd53d9b4d9)

**Comment by Vlad55432** [comment]
Can I see your mods & fflags?

**Comment by pizzaboxer** [comment]
> Whenever i open roblox it just shows white

Is this happening only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Jxm3sy** [comment]
No its not only happening with blox strap

**Comment by Jxm3sy** [comment]
it might be because of windows 10
im not sure

**Comment by Jxm3sy** [comment]
> Can I see your mods & fflags?

Everthing is normal nothing is changed

**Comment by pizzaboxer** [comment]
> No its not only happening with blox strap

This is an issue with Roblox itself then, which I can't really do anything about. The best I can do is point you to here: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

At the very least, does UWP work? If so, then you'll have to stick to using that.
