### ISSUE TITLE
[BUG] Escape Menu needed to walk after reset

### ISSUE THREAD

**Issue by Dessensce** [pizzaboxer/bloxstrap#1254]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Now, ill need to do more testing, but as far as im aware, this is a bloxstrap issue, anyway, when ever i reset, i have to open the escape menu to be able to walk, there aren't any errors in the log.

**Comment by pizzaboxer** [comment]
What version of the escape menu are you using?

**Comment by Dessensce** [comment]
Default

**Comment by pizzaboxer** [comment]
What other options have you enabled in the Bloxstrap Menu?

**Comment by Dessensce** [comment]
just FPS unc-locker and hide GUI

**Comment by pizzaboxer** [comment]
> just FPS unc-locker and hide GUI

What about in the flag editor?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
