### ISSUE TITLE
[BUG] EnableInGameMenuChromeABTest = True (Lua)

### ISSUE THREAD

**Issue by DarkPlaysGames** [pizzaboxer/bloxstrap#1256]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it says 'EnableInGameMenuChromeABTest = True (Lua)' at around the top left side of my screen, this is shown in any game i join. How can I remove this?

**Comment by DarkPlaysGames** [comment]
> idk, you tried to steal my 100th lol, still took it. oh well, i dont know actually just set it From settings not FFLags

i didnt see it srry

**Comment by pizzaboxer** [comment]
Open the flag editor, click "show preset flags", delete the "FStringDebugShowFlagState" entry.

What did you even do to add this if you don't know how to remove it?
