### ISSUE TITLE
Bloxstrap doesn't install

### ISSUE THREAD

**Issue by dumbmorongarbageidiot** [pizzaboxer/bloxstrap#1259]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i open bloxstrap after downloading it, it just instantly goes to "installing roblox" (without the actual menu showing up)

**Comment by pizzaboxer** [comment]
You had it installed prior but you clearly didn't uninstall it properly, so it thinks you already have it installed.

After the initial Roblox installation happens, just go straight to opening the Bloxstrap Menu, and you can adjust your settings there.

**Comment by dumbmorongarbageidiot** [comment]
> You had it installed prior but you clearly didn't uninstall it properly, so it thinks you already have it installed.
> 
> After the initial Roblox installation happens, just go straight to opening the Bloxstrap Menu, and you can adjust your settings there.
i reinstalled everything again and when i find bloxstrap menu and try to click on it it just says couldnt find bloxstrap.exe 
this happens to basically all of my apps
