### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kurd2x** [pizzaboxer/bloxstrap#1261]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

the problem is that it is not working starting bloxstrtap

**Comment by bluepilledgreat** [comment]
Can you provide a Bloxstrap log file?

**Comment by pizzaboxer** [comment]
I'm assuming that details were provided in #1262
