### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kurd2x** [pizzaboxer/bloxstrap#1262]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\tttgb\Documents\hhe\Versions\version-f2b5c592c03b4183\content\sounds\ouch.ogg' is denied.

**Comment by pizzaboxer** [comment]
What's in the contents of the `C:\Users\tttgb\Documents\hhe\` folder?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
