### ISSUE TITLE
[BUG] Roblox crashes out of nowhere (freezes and crashes)

### ISSUE THREAD

**Issue by JakoLol** [pizzaboxer/bloxstrap#1264]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, when I was playing roblox seemingly randomly at any given time my roblox freezes for about 10 seconds then starts for half a second and crashes, i've looked through other issue reports and #1184 and #1155 really stood out, tried the stuff under them like deleting clientsettings and not using fullscreen and the actual robloxplayerbeta but nothing worked. I have fullscreen optimizations emabled (default) and I didn't change any game files except the walk sounds and oof sound. Any ideas?

**Comment by JakoLol** [comment]
My cpu and gpu also goes to 0% usage I noticed, and I closed every app i can on task manager and anything that might trigger Hyperion

**Comment by JakoLol** [comment]
And if there is any fixes for bloxstrap please say so because i don't really wanna uninstall bloxstrap

**Comment by pizzaboxer** [comment]
Have you confirmed that this is only happening with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by JakoLol** [comment]
yes

**Comment by pizzaboxer** [comment]
What options have you configured in the Bloxstrap Menu?

**Comment by JakoLol** [comment]
Issue has seemed to fix itself but I'll still send my menu configs
![image](https://github.com/pizzaboxer/bloxstrap/assets/122135333/6fa864e9-c212-45d6-a570-ffd926a11a4d)
![image](https://github.com/pizzaboxer/bloxstrap/assets/122135333/f4efd404-566e-44d8-9b24-d1c78e4983f8)
![image](https://github.com/pizzaboxer/bloxstrap/assets/122135333/83f8e62c-3acc-4298-9c8e-adeb552169c5)
![image](https://github.com/pizzaboxer/bloxstrap/assets/122135333/c64dae97-947a-4a3b-a7cd-7d07e3172328)
![image](https://github.com/pizzaboxer/bloxstrap/assets/122135333/d0494bbd-c4d3-4a1f-b03b-106963d69626)
