### ISSUE TITLE
[BUG]blurry and super bright

### ISSUE THREAD

**Issue by banusnus123** [pizzaboxer/bloxstrap#1268]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

the clothes are blurry also the sign of the games are blurry and when i played mm2 all the maps are super bright pls fix

**Comment by pizzaboxer** [comment]
> and when i played mm2 all the maps are super bright pls fix

I wish you had read https://github.com/pizzaboxer/bloxstrap/wiki/Addressing-usability-problems-with-Bloxstrap-v2.5.4 before posting this. If you're encountering lighting artifacts then don't set a preferred lighting technology, keep it to "Chosen by game".

> the clothes are blurry also the sign of the games are blurry

Your GPU is likely low on VRAM. If you want to override the texture quality then you can do so as described at https://github.com/pizzaboxer/bloxstrap/issues/1202#issuecomment-1914334862.
