### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by goiaba123** [pizzaboxer/bloxstrap#1269]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

[Inner Exception]
System.TimeoutException: A task was canceled.

[Inner Exception]
System.Threading.Tasks.TaskCanceledException: A task was canceled.
help? pls

**Comment by pizzaboxer** [comment]
Internet connectivity issue. If this is happening every time you try using Bloxstrap, something is preventing it from connecting to the internet, like an antivirus. Else, if it just happened once, then you can ignore it and relaunch.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
