### ISSUE TITLE
[BUG] İ uptaded my windows and roblox didnt open what sould i do? (im turkish I may not have written properly)

### ISSUE THREAD

**Issue by Umut424** [pizzaboxer/bloxstrap#1271]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

pls help

**Comment by pizzaboxer** [comment]
Are you using Bloxstrap? If so, please confirm if Roblox works without it. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Umut424** [comment]
i tried but its not openig.

**Comment by pizzaboxer** [comment]
This is an issue with Roblox itself then. Unfortunately, I can't really help you much with that. The most I can do is point you to this article: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

Sorry.
