### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hassan8892** [pizzaboxer/bloxstrap#1272]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/159553695/265fe5e7-4826-4188-99ff-fda08600e7fe)
is there any fix for this?, ive been having this issue for a while now its not really a black screen but i cannot screen shot it when i press alt tab it takes atleast 20 seconds to load roblox, ive messaged many people friends, etc still not fixed it stays like that for about 20 seconds then roblox loads, when i go to my other microsoft account it laods perfectly fine withn a second.

**Comment by pizzaboxer** [comment]
Is this with you using Bloxstrap? Can you confirm that this doesn't happen with just Roblox itself? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by hassan8892** [comment]
> Is this with you using Bloxstrap? Can you confirm that this doesn't happen with just Roblox itself? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

its not with bloxtraps its roblox its self i just wanna know if you could help me

**Comment by hassan8892** [comment]
> Is this with you using Bloxstrap? Can you confirm that this doesn't happen with just Roblox itself? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

if you would like i can screenshare in discord.

**Comment by pizzaboxer** [comment]
> its not with bloxtraps its roblox its self i just wanna know if you could help me
