### ISSUE TITLE
[BUG] Roblox and Bloxstrap not starting anymore

### ISSUE THREAD

**Issue by Arameint** [pizzaboxer/bloxstrap#1275]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello,
i have the problem that my Roblox is not starting anymore after i installed Bloxstrap.
I tryd to start Roblox normally but it doesn't open anymore, i looked up in the taskmanager if Roblox is even running. It seams to crash as it closes itself after some short time or doesn't even start at all. I tried to reinstall Roblox, restart my PC, look into the issue websites from Roblox and Bloxstraps, nothing worked. I even tried to look if it would help if i use the Roblox launcher from the Micosoft Store and the resulst are the same. Has someone a solution for this? 😅 I even tryd to start Roblox on VR what of course didn't work, but it was worth a try. 🥲

**Comment by pizzaboxer** [comment]
> I tryd to start Roblox normally but it doesn't open anymore,

Can I just verify that you tried using the original bootstrapper without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
This is defnitely sounding like an issue with Roblox itself, if not even the Microsoft Store version is working. I'll safely say that this has no correlation to Bloxstrap. 

>  i have the problem that my Roblox is not starting anymore after i installed Bloxstrap.

How long has it been since you installed it?

**Comment by Arameint** [comment]
I am not sure, but i think it was like 16-17 hours ago.

**Comment by pizzaboxer** [comment]
I forgot to respond to this, my bad. Was the guide able to help you with your issue? If not, I can try and take a further look at this.

**Comment by Arameint** [comment]
No, the guide was not able to help because it was not a problem with Roblox or Bloxstraps. It was because of my Windows 11 22h2 insider version. I reinstalled my windows and everything works fine now. I have no idea if that was a general windows insider version problem that caused it or not. Its just a guess because since i got the version, many things didn't work anymore in general.

**Comment by pizzaboxer** [comment]
> It was because of my Windows 11 22h2 insider version.

...That's one of the points that the guide talked about.

Okay, good to hear that it helped, and that you've identified the cause of the issue.

**Comment by Arameint** [comment]
Sry, then i missed it :/
