### ISSUE TITLE
Roblox crashes as soon as I open Bloxstrap

### ISSUE THREAD

**Issue by treebarkbr** [pizzaboxer/bloxstrap#1276]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I click "Play Roblox" AND "Roblox Player", both of them return the same issue, crashing.

NOTE : Roblox detected I was using third-party software, A.K.A Bloxstrap.

**Comment by pizzaboxer** [comment]
> Roblox detected I was using third-party software, A.K.A Bloxstrap.

That error isn't being caused by Bloxstrap, I can safely say that. It won't be able to cause errors like that.

If using "Roblox Player" is showing that error too, then it isn't detecting Bloxstrap because Bloxstrap won't even be running, so what would it be detecting?

> both of them return the same issue, crashing.

Since you're also saying that it's showing that error dialog, can you better clarify on when Roblox is crashing?

**Comment by MikeyUsersREC** [comment]
@pizzaboxer I can reproduce. No third party modifications whatsoever, and I can't play Roblox right now. 

Here's what happens.
- Bloxstrap runs
- Gets to "Starting Roblox"
- Spawns ghost Roblox suspended subprocesses
- Nothing ever happens

That happens for both "Play Roblox" and Bloxstrap's interpretation of the URL protocol. 

Now, when I try to get ROBLOX to work, uninstall Bloxstrap, reinstall ROBLOX. It never works, and it spawns ghost ROBLOX subprocesses, no window forms whatsoever.

HOWEVER, when I follow a "tutorial troubleshooting step", by removing WebView2Loader.dll, it spawns "Failed to load library: WebView2Loader.dll", as well as a new "Unapproved third party applications or extensions detected" message.

**I have no other FPS unlockers, I have no other modifications. I solely use Bloxstrap.**
There is an associated thread on Discord here. I have provided a memory dump if you can use that information whatsoever.
https://discord.com/channels/1099468797410283540/1205937777259184209

**Comment by pizzaboxer** [comment]
Mike's issue was found to be caused by being on a Windows Insider/Dev build.

Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by treebarkbr** [comment]
Okay, uh, sorry for not replying for 2 weeks (i got busy). I did install something that had EAC bundled into it, I think that's why Roblox wouldn't open including Bloxstrap, of course. Also got the same error as Mike's.
![image_2024-04-12_162036583](https://github.com/pizzaboxer/bloxstrap/assets/142401119/63716a2c-2ae9-4997-bf17-3866a89f2f97)

**Comment by pizzaboxer** [comment]
>I think that's why Roblox wouldn't open including Bloxstrap, of course

Is it running in the background though? That's all that matters here.

**Comment by treebarkbr** [comment]
The weird thing was.... it wasn't. It may be a random background process.
