### ISSUE TITLE
Discord Overlay [BUG] 

### ISSUE THREAD

**Issue by xlnsanity** [pizzaboxer/bloxstrap#1278]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Discord Overlay doesn't work due to blox strap, I hope it gets fixed so I can see messages without opening discord,

**Comment by GoingCrazyDude** [comment]
not a bloxstrap issue

**Comment by pizzaboxer** [comment]
That's not due to Bloxstrap, that's just how Roblox is. It won't let other applications do graphical overlays.

**Comment by Encythe** [comment]
> It won't let other applications do graphical overlays.
The closest thing I have relating to this is this
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/8ac80606-426b-4405-826d-cd2de50c9c67)
Though I'm unsure if it's on the game or the WebView window.

**Comment by xlnsanity** [comment]
> > It won't let other applications do graphical overlays.
> 
> The closest thing I have relating to this is this ![image](https://private-user-images.githubusercontent.com/38755801/303893607-8ac80606-426b-4405-826d-cd2de50c9c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2Mjk5ODIsIm5iZiI6MTcwNzYyOTY4MiwicGF0aCI6Ii8zODc1NTgwMS8zMDM4OTM2MDctOGFjODA2MDYtNDI2Yi00NDA1LTgyNmQtY2QyZGU1MGM5YzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA1MzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMDBiZGY1MGJhMGFiMmU0YzdlMjY3OGIyZjhjNDE2YWZiNWQ1NDkxOTcyMTNjM2U3MzIxYWJlMTVjYmIxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6uBb3QxzMHG1aM7yoGiV0jDKbUZG0QXxqMfQCR6BKw) Though I'm unsure if it's on the game or the WebView window.

May I know how you did it?

**Comment by xlnsanity** [comment]
> That's not due to Bloxstrap, that's just how Roblox is. It won't let other applications do graphical overlays.

Used to work before

**Comment by Encythe** [comment]
> > > It won't let other applications do graphical overlays.
> > 
> > 
> > The closest thing I have relating to this is this ![image](https://private-user-images.githubusercontent.com/38755801/303893607-8ac80606-426b-4405-826d-cd2de50c9c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2Mjk5ODIsIm5iZiI6MTcwNzYyOTY4MiwicGF0aCI6Ii8zODc1NTgwMS8zMDM4OTM2MDctOGFjODA2MDYtNDI2Yi00NDA1LTgyNmQtY2QyZGU1MGM5YzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA1MzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMDBiZGY1MGJhMGFiMmU0YzdlMjY3OGIyZjhjNDE2YWZiNWQ1NDkxOTcyMTNjM2U3MzIxYWJlMTVjYmIxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6uBb3QxzMHG1aM7yoGiV0jDKbUZG0QXxqMfQCR6BKw) Though I'm unsure if it's on the game or the WebView window.
> 
> May I know how you did it?

I don't know, one day I enabled discord overlay and it kinda just, worked. It may be overlaying on WebView2 only and not the game but it's close enough.

**Comment by GoingCrazyDude** [comment]
You can use [this](https://discord.com/channels/1099468797410283540/1165211319583117443) for discord, but you will need voice chat access.

**Comment by pizzaboxer** [comment]
>  Though I'm unsure if it's on the game or the WebView window.

Given the gap at the top, that definitely looks like the WebView window. Wow, I had no idea it could do that?

**Comment by Encythe** [comment]
Some additional comments:
- It does not work when launching through the website directly
- It works when launching through the desktop app and jumping into a game through that, although only sometimes and inconsistently
