### ISSUE TITLE
[REQ] Remove Textures On MODS CATEGORY

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1279]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

instead of putting lots of stuff, why not adding it so lazy ppl finally can remove textures

**Comment by GoingCrazyDude** [comment]
planned

**Comment by pizzaboxer** [comment]
Already planned to be released. I'll close this since we already have it in our todo list, and it's already been completed.
