### ISSUE TITLE
[BUG] FPS capped and won't unlock

### ISSUE THREAD

**Issue by crwazydoll** [pizzaboxer/bloxstrap#1280]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My fps doesn't even get higher than 50 and I've already tried to address where the problem might be with YouTube video's and the Wiki page, but nothing really helped. I've switched the limiter from 9999 to 120 and tried a bunch of different settings, but it won't work. No fps unlocker has ever really worked on my pc, so I'm wondering if my own pc might be the problem

**Comment by githubberguy** [comment]
same here, its probably patched from roblox since theyre implementing their own fps unlocker.

**Comment by crwazydoll** [comment]
My friend recommended me this and she claims it still works for her so I have no clue

**Comment by bluepilledgreat** [comment]
> same here, its probably patched from roblox since theyre implementing their own fps unlocker.

No?

**Comment by Wheelz0** [comment]
Can confirm it seems broken

**Comment by pizzaboxer** [comment]
> My fps doesn't even get higher than 50

If you're FPS doesn't reach any higher than 50 then that's simply your PC not being powerful enough. Roblox caps to 60 by default.
