### ISSUE TITLE
MTU changer

### ISSUE THREAD

**Issue by LeventGameing** [pizzaboxer/bloxstrap#1281]
- [X] I have read and acknowledged the preliminary instructions.
MTU 

 would like to say could there be an MTU changer please cause roblox sets it to 1396 which slows my connection and i wanted to change it to 1500 this could help me alot with my connection cause normally when my MTU is set at 1500 i get like 20 ping which is very good

**Comment by GoingCrazyDude** [comment]
No

**Comment by OrphanObliterator** [comment]
set your mtu as 5000 for a free robux prize
