### ISSUE TITLE
Roblox Cursor not showing

### ISSUE THREAD

**Issue by Luuunar** [pizzaboxer/bloxstrap#1282]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Yesterday I downloaded a custom cursor and I put it into the Mods folder and it worked when you are in the roblox loading screen with the games title but when you fully join the game it turns into the normal roblox cusor.

**Comment by pizzaboxer** [comment]
Where did you place the cursor?

**Comment by Luuunar** [comment]
In the Textures folder

**Comment by pizzaboxer** [comment]
Can you show a screenshot please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
