### ISSUE TITLE
[REQ] FFlags to disable Request Async Compression

### ISSUE THREAD

**Issue by playervalley** [pizzaboxer/bloxstrap#1284]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

As of the past month, Roblox has released an update called "Request Async Compression". This would _look_ great as it improves performance and lowers power consumption, it does **not** look over what hardware it is on.

In other words, [hardware that is perfectly capable of rendering higher quality textures get compressed ones instead](https://devforum.roblox.com/t/blurry-compressed-materials-on-the-desktop-web-launched-client-despite-adequate-hardware-availability/2828682).

I'm not the one that provided the FFlag for this fix, [Ittr is](https://devforum.roblox.com/t/blurry-compressed-materials-on-the-desktop-web-launched-client-despite-adequate-hardware-availability/2828682/13), but I feel like this ruins most pixel peepers' experience (and some games) enough to request this addition.

Enough blabber, here is the FFlags for this:
`{"FIntTextureCompositorLowResFactor":"4","DFFlagEnableRequestAsyncCompression":"False"}`

**Comment by GoingCrazyDude** [comment]
This needs to be added

**Comment by pizzaboxer** [comment]
Does `DFFlagEnableRequestAsyncCompression` need to be set for this? We encountered a lot of users who were experiencing this too, but we always found that simply overriding the texture quality like this:

```json
{
    "DFFlagTextureQualityOverrideEnabled": "True",
    "DFIntTextureQualityOverride": "3"
}
```

always seemed to solve the issue too? And I suspect `FIntTextureCompositorLowResFactor` alone is simply just doing that too.

**Comment by PlayerValley** [comment]
I felt like the disable flag would play a role, but I haven't tested it extensively.

**Comment by bluepilledgreat** [comment]
closed because of recent updates
