### ISSUE TITLE
[BUG] System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by Mysk03** [pizzaboxer/bloxstrap#1287]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I know that this is duplicate of #1000 but the issue didnt solved after reading it and few wiki articles and i will explain it. I changed few hours ago name in users "C:\Users\..." and whenever i try to install or reinstall it pop up as wrong path (when i somehow install it, it creates new user with my old name inside C:\Users folder) and the best part of this is that my old name contains non-english characters so roblox can't save settings, this coused infinite loop  
![issue](https://github.com/pizzaboxer/bloxstrap/assets/159823859/adc1e9a8-5800-4236-871e-e1b3fffa910a)
EDIT: Is there way to change this to my current path?

**Comment by pizzaboxer** [comment]
Open the registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap`, and change the value of the `InstallLocation` attribute to reflect your new Windows username.

**Comment by Mysk03** [comment]
Worked, thanks for help
