### ISSUE TITLE
[ISSUE] An exeption occurred while running Bloxtrap

### ISSUE THREAD

**Issue by Nlkoh** [pizzaboxer/bloxstrap#1288]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: An error occurred while sending the request.

[Inner Exception]
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forced to be canceled by the remote host.

[Inner Exception]
System.Net.Sockets.SocketException: An existing connection was forced to be canceled by the remote host.
![An exeption occurred while running Bloxtrap](https://github.com/pizzaboxer/bloxstrap/assets/68163906/6aa1aad4-9cae-41e3-a822-abab539bcadb)

**Comment by josuech797** [comment]
it happened to me to

**Comment by Nlkoh** [comment]
> Is this happening everytime you launch, or did it just happen this one time?

It had happened twice, but after I installed the .NET files the program returned to normal

**Comment by Nlkoh** [comment]
> Is this happening everytime you launch, or did it just happen this one time?

It had happened twice, but after I installed the .NET files the program returned to normal

**Comment by josuech797** [comment]
where are the .NET files??

**Comment by Nlkoh** [comment]
> where are the .NET files??
> 
> 
> 

I don't know exactly, but I went to Control Panel to uninstall .NET 6

**Comment by Nlkoh** [comment]
> where are the .NET files??
> 
> 
> 

I don't know exactly, but I went to Control Panel to uninstall .NET 6

**Comment by josuech797** [comment]
oh ok how i enter the control panel btw??

**Comment by josuech797** [comment]
in bloxstrap files or where??

**Comment by josuech797** [comment]
oh nvm i just putted bloxstrap files in his own carpet but thanks for the help :)

**Comment by pizzaboxer** [comment]
> but after I installed the .NET files the program returned to normal
