### ISSUE TITLE
[BUG] Roblox sometimes closes itself

### ISSUE THREAD

**Issue by marzolmfao** [pizzaboxer/bloxstrap#1289]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Sometimes, when I play Roblox with Bloxstrap on, it just randomly and automatically closes its window, even while I'm playing. I tried to uninstall Bloxstrap and use default Roblox, it runs normally fine. I've also told this to my friend and he said this might be a ping issue and he doesn't know how to fix it.

**Comment by pizzaboxer** [comment]
What options have you configured in the Bloxstrap Menu?

**Comment by marzolmfao** [comment]
I used JSON from a youtuber for fps boost since it's obviously good and also some personal configurations like Voxel lighting, Windows 10 emojis etc. I hope that will clarify the issue.

**Comment by pizzaboxer** [comment]
> I used JSON from a youtuber for fps boost since it's obviously good

Read the big red warning at the top of https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags, please.

Remove all of them and see if your issue is fixed.

**Comment by pizzaboxer** [comment]
Assuming that the issue has been resolved. Let me know if you're still having problems.
