### ISSUE TITLE
Unable to find roblox

### ISSUE THREAD

**Issue by thriftydoge** [pizzaboxer/bloxstrap#129]
Okay so I recently went back to a restore point on my system and now bloxstrap doesnt want to launch. Funny thing is roblox sill launches normally but bloxstrap throws an error at me every time. I already tried reinstalling both bloxstrap and roblox but nothing seems to have changed
![image](https://user-images.githubusercontent.com/87211537/231056514-052e148f-131a-4210-9688-981e41e54fec.png)

**Comment by pizzaboxer** [comment]
Delete State.json in the Bloxstrap folder and try running it again.

**Comment by thriftydoge** [comment]
Thanks it works fine now

**Comment by pizzaboxer** [comment]
No problem. This is also going to be fixed soon anyway, see #128.
