### ISSUE TITLE
[BUG] Roblox closes when I try to open a game or it takes a long time to load a game. And also the menu during the game freezes for 3 seconds and then returns to normal

### ISSUE THREAD

**Issue by ZeroDiscoBox** [pizzaboxer/bloxstrap#1290]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

https://github.com/pizzaboxer/bloxstrap/assets/77170931/364181a1-5916-4949-a031-57bb139de5e5

**Comment by pizzaboxer** [comment]
Have you confirmed that this doesn't happen with the stock Roblox launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ZeroDiscoBox** [comment]
Yes I do, it's work normally

**Comment by ZeroDiscoBox** [comment]
What should I do?

**Comment by pizzaboxer** [comment]
> Yes I do, it's work normally

What options have you configured in the Bloxstrap Menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
