### ISSUE TITLE
Roblox crashes everytime and shows an error regarding unauthorized 3rd party plugins

### ISSUE THREAD

**Issue by Bright1Darkness** [pizzaboxer/bloxstrap#1291]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was experiencing an issue on which when i tried to run roblox it would just **crash**, i tried **uninstalling bloxtrap** and it started **working**. When I **downloaded bloxtrap** again it said "**Unauthorized 3rd party plugin---**" something like that i am not really sure, i forgot to take a screenshot. **Please help me resolve this issue**

**Comment by pizzaboxer** [comment]
I can assure you that isn't being caused by Bloxstrap. Are you sure that you're encountering this only when using Bloxstrap? Switch back to the stock launcher, launch Roblox a few times and see what you encounter. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Bright1Darkness** [comment]
Yes, this bug only occurs when bloxtrap is installed. When i install bloxtrap it bugs and wont fix again after reinstalling (via versions in appdata>local>roblox>versions>(whatever latest one)>RobloxPlayerLauncher) and restarting your computer, this has also been happening to a friend of mine. It is a reoccuring issue. Please elaborate on how i can fix this

**Comment by pizzaboxer** [comment]
> Please elaborate on how i can fix this

I can't really, because Bloxstrap isn't doing anything that could be possibly causing this. 

Since you mentioned that it's fixed after you reinstall Roblox with the original launcher and then restart your PC, have you tried using Bloxstrap again after restarting your PC?

**Comment by Bright1Darkness** [comment]
i did try using blox trap after the bug was fixed the but thing would happen once again

**Comment by Bright1Darkness** [comment]
![Uploading Screenshot 2024-02-17 105453.png…]()

**Comment by pizzaboxer** [comment]
> i did try using blox trap after the bug was fixed the but thing would happen once again

Try it again, but instead of launching through Bloxstrap, manually launch the RobloxPlayerBeta executable that's located at `%localappdata%\Bloxstrap\Versions\<version folder>`

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by Bright1Darkness** [comment]
the issue has seemed to somehow fixed itself?, but i thank you for your assistance and cooperation. thanks alot
