### ISSUE TITLE
[BUG] roblox wont open after uninstalling bloxstrap

### ISSUE THREAD

**Issue by badashat** [pizzaboxer/bloxstrap#1292]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-02-14 102734](https://github.com/pizzaboxer/bloxstrap/assets/160049434/8afa4877-7d8a-45a1-93c8-d6339765a2c1)
heres proof (roblox is not installed) i uninstalled the roblox player and installed it again but still wouldnt work

**Comment by pizzaboxer** [comment]
Are you saying that Roblox doesn't open after pressing the "Open URL" button?

**Comment by pizzaboxer** [comment]
Issue is being handled at https://discord.com/channels/1099468797410283540/1207347610713718824
