### ISSUE TITLE
CANNOT TALK

### ISSUE THREAD

**Issue by LeventGameing** [pizzaboxer/bloxstrap#1293]
I CANNOT TALK

i cannot talk in discord server idk why aka flemish.maps

**Comment by GoingCrazyDude** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/67791946/04c21fe3-579b-452c-89ae-bf53945af894)

**Comment by pizzaboxer** [comment]
don't necrobump like a million different threads (some as far back as september) while providing no information of value whatsoever

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/0a04beb2-081f-4eff-833b-d42d01f60df2)
