### ISSUE TITLE
It doesnt show the bloxstrao menu, it only opens roblox 

### ISSUE THREAD

**Issue by matismatico** [pizzaboxer/bloxstrap#1297]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i clicked in the bloxstrap app, its said, installing roblox, and then roblox launched, but there was no bloxstrap menu
![imagen_2024-02-15_143140899](https://github.com/pizzaboxer/bloxstrap/assets/160163466/e5687d60-6ab0-40aa-83a6-936bd2dea573)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
