### ISSUE TITLE
[BUG] Roblox Crashing

### ISSUE THREAD

**Issue by zrxxx22** [pizzaboxer/bloxstrap#1298]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Even after all the things i have tried on the list its still crashing after about 20 mins or so playing roblox. ive tried everything online and ive seen that resetting your pc does not rlly fix it either but i have yet to try. could you please help

**Comment by pizzaboxer** [comment]
> Even after all the things i have tried on the list 

Did you verify that this only happens with Bloxstrap?

**Comment by zrxxx22** [comment]
i did with an without and it pretty much does the same thing

**Comment by pizzaboxer** [comment]
Preliminary instructions. This isn't an issue with Bloxstrap then. The most I can do to help you here is for you to read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.
