### ISSUE TITLE
[BUG] roblox boots then instantly crashes

### ISSUE THREAD

**Issue by lucasbosce** [pizzaboxer/bloxstrap#1299]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i installed bloxstrap and when i opened roblox it instantly crashed, so i uninstalled it and now roblox isnt working at all, it opens and shows the loading screen and then crashes, ive tried basically every fix i can find and nothing seems to be working

**Comment by pizzaboxer** [comment]
Was it working before you installed Bloxstrap? If so, when was it last working?

**Comment by lucasbosce** [comment]
> Was it working before you installed Bloxstrap? If so, when was it last working?

yeah it was working fine but i had only played roblox a few times since i got a new computer

**Comment by pizzaboxer** [comment]
When was that though?

**Comment by lucasbosce** [comment]
> When was that though?

like the same day i tried installing it, forgot to mention but this issue started 2 around 2 weeks ago when i first tried installing bloxstrap

**Comment by pizzaboxer** [comment]
When you say "basically every fix", are you also referring to the ones in the Wiki page?

**Comment by lucasbosce** [comment]
just retried one of the fixes and it worked this time, thanks for the help though🙏
