### ISSUE TITLE
i can't move in roblox, in any game whatsoever.

### ISSUE THREAD

**Issue by dropier** [pizzaboxer/bloxstrap#13]
i don't know if this is a problem with bloxstrap, or roblox, but i've also tried plugging in another keyboard, switching the build channel, and nothing worked.

**Comment by pizzaboxer** [comment]
Uninstall Bloxstrap and see if the issue persists.

**Comment by paralltheshape** [comment]
never have gotten this, most likely a roblox fault rather then bloxstrap

**Comment by dropier** [comment]
i fixed it by doing that
thanks pizzaboxxer because i also thought it was roblox but when i tried everything i came to here lol
