### ISSUE TITLE
[BUG] Bloxstrap starts update, progress bar loops back a couple times, and then throws an error up.

### ISSUE THREAD

**Issue by WebbyLua** [pizzaboxer/bloxstrap#1301]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240216T113637Z.log](https://github.com/pizzaboxer/bloxstrap/files/14310466/Bloxstrap_20240216T113637Z.log)

**Comment by pizzaboxer** [comment]
Please read the preliminary instructions. https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
