### ISSUE TITLE
[BUG] My bloxstrap stays capped at 60FPS when i set it to 9999.

### ISSUE THREAD

**Issue by Gustevs1264** [pizzaboxer/bloxstrap#1302]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i put the FPS to infinite in Bloxstrap, the FPS stays capped at 60. Is there something i can do to fix it?

**Comment by pizzaboxer** [comment]
Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by Gustevs1264** [comment]
Yeah i did, and i could already fix it, sorry for givin ya trouble.
