### ISSUE TITLE
[BUG] grafics

### ISSUE THREAD

**Issue by Xpnp** [pizzaboxer/bloxstrap#1303]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

if u put the meniu from 2020 and acctivate the 1-21 grafics ur not going to get 1-21 only 1-10

**Comment by bluepilledgreat** [comment]
what do you expect from using an abandoned menu

**Comment by GoingCrazyDude** [comment]
grafics

**Comment by Xpnp** [comment]
they fixed it w
