### ISSUE TITLE
[BUG] Alt + Enter does not work. it doesn't make the application fullscreen

### ISSUE THREAD

**Issue by LulamoonLover** [pizzaboxer/bloxstrap#1304]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Yes, the "Disable fullscreen optimisations" option is off in the mods section of the bloxstrap menu.
The "Optimize windowed games" in my windows setting is also off. 
Whenever I press alt + enter it just immediately takes it back to windowed mode with the windows error sound playing.
F11 still works but it doesn't provide me the fps benefits

**Comment by pizzaboxer** [comment]
There's nothing that I can do about this. See https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#exclusive-fullscreen

Does it not work with the option on either?

**Comment by LulamoonLover** [comment]
> There's nothing that I can do about this. See https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#exclusive-fullscreen
> 
> Does it not work with the option on either?

Whenever I go to the bloxstrap menu, 
open the fastflag editor 
then edit that specific fastflag (FFlagHandleAltEnterFullscreenManually),
I see that it is set to "False"
I set it to "True" manually and it didn't do the job. I open the Bloxstrap Menu again and it showed that the "FFlagHandleAltEnterFullscreenManually" is still set to false even though I manually set it to true. It just keeps changing back every time.

**Comment by LulamoonLover** [comment]
Uploading Visual Clarification of the issue.mp4…

**Comment by pizzaboxer** [comment]
You're not supposed to set it to true, and that's not what I was asking you to do, I was referring to the "disable fullscreen optimizations" option. If you turn that on, does it still not work?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by nazv5** [comment]
Having the same problem.

**Comment by aqbd** [comment]
> You're not supposed to set it to true, and that's not what I was asking you to do, I was referring to the "disable fullscreen optimizations" option. If you turn that on, does it still not work?

Experienced the same thing. "FFlagHandleAltEnterFullscreenManually" set to false (untouched) and had my "Disable fullscreen optimizations" enabled. Still can't enter exclusive fullscreen and got window error sound
