### ISSUE TITLE
[REQ] Keep server location notifications in notification center

### ISSUE THREAD

**Issue by nodomw** [pizzaboxer/bloxstrap#1305]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Server location notifications should remain in notification center

**Comment by pizzaboxer** [comment]
Do they not stay in the notification center for you? How long do they last for?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
