### ISSUE TITLE
[BUG] Can't tp with both roblox account

### ISSUE THREAD

**Issue by H2ylen** [pizzaboxer/bloxstrap#1306]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I play stuff like a Tower Defense Game and i wanna carry My alt. With my alt joining my private server and joining a stage. But when i start the round **Only one of the account only gets Teleported to the stage and the other is met with a kick message.**

The Right is the one that got kicked and the Left is teleporting to the stage. How to i fix this? Or is it unfixable and i just have to ignore this and let only one tp
![image](https://github.com/pizzaboxer/bloxstrap/assets/160301272/63541cc3-0b62-4d5b-9691-bbf06c772daf)

**Comment by pizzaboxer** [comment]
> I play stuff like a Tower Defense Game and i wanna carry My alt.

Not interested.
