### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zalomeXZ** [pizzaboxer/bloxstrap#1308]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When ever i launch roblox i cant even hear sound it says Output no sound driver

@

**Comment by pizzaboxer** [comment]
Preliminary instructions. Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
