### ISSUE TITLE
Firewall problems

### ISSUE THREAD

**Issue by codesdumb** [pizzaboxer/bloxstrap#1309]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Im pretty sure bloxstrap is having issues with my firewall and it causes my internet to cut out on my PC randomly. So would it be a bad idea to make it run as administrator

**Comment by pizzaboxer** [comment]
> and it causes my internet to cut out on my PC randoml

I'm very doubtful to say the least. How do you know it's being caused by Bloxstrap?

**Comment by codesdumb** [comment]
> > and it causes my internet to cut out on my PC randoml
> 
> I'm very doubtful to say the least. How do you know it's being caused by Bloxstrap?

usually when my internet goes out it is only my computer not my router nor phone so it was just guess. My main question is, is it safe to make it run as administrator?

**Comment by pizzaboxer** [comment]
> usually when my internet goes out it is only my computer not my router nor phone so it was just guess

...What?

> My main question is, is it safe to make it run as administrator?

This is going to do nothing for your issues. But to generally answer your question, it's not "unsafe", but it may cause permission-related issues when you try to launch Roblox.
