### ISSUE TITLE
[BUG] bloxstrap not launching up after this pop up

### ISSUE THREAD

**Issue by helpmeplis47** [pizzaboxer/bloxstrap#1310]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my pc act weird today and when i try to load up roblox this error came up
"System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=6.0.0.0, Culture=neutral, .The file or directory is corrupted and unreadable. (0x80070570)" (i deleted the pubilckeytoken)

![image_2024-02-19_185506262](https://github.com/pizzaboxer/bloxstrap/assets/160492132/af1dd566-9d35-4548-bf91-304e1e0ed970)

the file that causing the problem 
![image](https://github.com/pizzaboxer/bloxstrap/assets/160492132/5d35a0ab-ff3f-4bad-a135-a149e3aa9348)

**Comment by pizzaboxer** [comment]
Assuming that the issue has been resolved. Please respond if there is still a problem.
