### ISSUE TITLE
[BUG] roblox and blox trap not opening

### ISSUE THREAD

**Issue by shawwnnnn** [pizzaboxer/bloxstrap#1312]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxtrap not opening or showing gui the same 2 roblox

**Comment by pizzaboxer** [comment]
> the same 2 roblox

Sounds like your issue is with Roblox itself then. I can't do much for you other than advise you to read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch. Sorry.
