### ISSUE TITLE
[BUG] mouse pointer not showing in exclusive fullscreen

### ISSUE THREAD

**Issue by gztxrd** [pizzaboxer/bloxstrap#1313]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i press alt+enter to go into exclusive fullscreen, my pointer becomes invisible but i can still hover over stuff and click it. if i go out of exclusive fullscreen its visible, also im using the default cursor if that matters.

**Comment by pizzaboxer** [comment]
This is to be expected. https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#exclusive-fullscreen
