### ISSUE TITLE
[BUG] 2015 menu not working

### ISSUE THREAD

**Issue by sheikzoro** [pizzaboxer/bloxstrap#1315]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I got the version 1 menu 2015 and it isn't working, it's just giving me the new small one, could someone give me a answer to why this is happening and how do I fix it?

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
