### ISSUE TITLE
[REQ] Old Chat Icon

### ISSUE THREAD

**Issue by sheikzoro** [pizzaboxer/bloxstrap#1316]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I suggest adding option to turning the new chat icon to the old one.

![download (3)](https://github.com/pizzaboxer/bloxstrap/assets/130099146/6ef85b94-e3e2-4a7f-9d3e-9fbeeb352959)

**Comment by TheMetalTechnet** [comment]
It's already possible, you just have to do it manually

**Comment by pizzaboxer** [comment]
This isn't something we'd want to officially add. You can do it yourself as described at https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods.
