### ISSUE TITLE
[REQ] Old zoom out and zoom in sound with the zoom effect too

### ISSUE THREAD

**Issue by sheikzoro** [pizzaboxer/bloxstrap#1317]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I suggest adding the old zoom out and zoom in option in the Bloxstrap Menu, also while doing that, add the old zoom effect with it as well.

**Comment by pizzaboxer** [comment]
Not possible, sorry.

**Comment by sheikzoro** [comment]
It's alright, but thank you.
