### ISSUE TITLE
[BUG] bloxstrap menu

### ISSUE THREAD

**Issue by SkidRBLX** [pizzaboxer/bloxstrap#1318]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i dont have bloxstrap menu but only the "Play Roblox" shortcut. how do i get the menu?

**Comment by pizzaboxer** [comment]
Did you read the preliminary instructions?

https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

You also would have been told about this when you first installed.
