### ISSUE TITLE
Could you possibly add an option to remove textures completely and replace them with the smooth plastic ones

### ISSUE THREAD

**Issue by Reisusuki** [pizzaboxer/bloxstrap#1319]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Could you possibly add an option to remove textures completely and replace them with the smooth plastic ones. Also is there a way I can have high render distance but low graphic quality and finally is there a fast flag you could use to remove grass on Roblox's new terrain?

**Comment by pizzaboxer** [comment]
Yeah, that's already planned to be added, if the functionality for it even exists until then.

To address those last two requests, see if this flag config works for you. This will force the quality to be as low as possible regardless of render distance, and set grass to never render.

```json
{
   "DFIntDebugFRMQualityLevelOverride": "1",
   "FIntFRMMaxGrassDistance": "0",
   "FIntFRMMinGrassDistance": "0"
}
```

Copy and paste this JSON config and import it into the flag editor, and it should work. Let me know if you have any issues.

**Comment by Reisusuki** [comment]
Thanks alot for your support I really appreciate it
