### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 7-luxury** [pizzaboxer/bloxstrap#1320]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The bloxstrap isn't working and not unlocking my FPS. It was working fine earlier and i had over 180+ FPS on Roblox but now it's not working make me stuck at 59-61 FPS every game I join. I have restarted Roblox and bloxstrap and it's still occuring.

**Comment by bluepilledgreat** [comment]
Local fast flags are gone, there is no fix.

**Comment by pizzaboxer** [comment]
Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
