### ISSUE TITLE
[BUG] Custom Cursor/Crosshair Reverting

### ISSUE THREAD

**Issue by Bvbble** [pizzaboxer/bloxstrap#1322]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This has been happening for a while. I put my cursor files into BloxStrap and everything works. Then near Wednesday-Friday (same time it would revert without BloxStrap) it reverts. I open with BloxStrap every time I use Roblox. What's happening?

**Comment by Bvbble** [comment]
C:\Users\Bubble\AppData\Local\Bloxstrap\Versions\version-70a2467227df4077\content\textures\Cursors\KeyboardMouse

**Comment by pizzaboxer** [comment]
Read through https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods please.
