### ISSUE TITLE
[REQ] in-game UI changing

### ISSUE THREAD

**Issue by Goldpunk** [pizzaboxer/bloxstrap#1323]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

new menu was just rolled out, kinda dumb and controversial can u please add something to toggle it off it's not very intuitive and the health bar in on the other side now
![Control-V (20)](https://github.com/pizzaboxer/bloxstrap/assets/58894007/10ef8f5c-c7ab-412f-b1cf-805eb752edbd)
![Control-V (21)](https://github.com/pizzaboxer/bloxstrap/assets/58894007/ac4e3626-1bd0-4ad7-8fb3-b591ef7c9364)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
