### ISSUE TITLE
roblox has timed out please restart your client.

### ISSUE THREAD

**Issue by Oyama-Mah1ro** [pizzaboxer/bloxstrap#1324]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i got no problem when using bloxstrap yesterday but i can't use it to join any game now, it become normal when i switch to roblox
![image_2024-02-22_150259708](https://github.com/pizzaboxer/bloxstrap/assets/160834259/ac64c423-2852-4faa-982a-121bed2196a4)

[Bloxstrap_20240222T080555Z.log](https://github.com/pizzaboxer/bloxstrap/files/14370768/Bloxstrap_20240222T080555Z.log)

**Comment by mesidex** [comment]
The update that was released today/yesterday broke Roblox again for some users. I assume this is Hyperion-related since I was able to play Roblox just fine yesterday, and after updating I am instantly crashing (not freezing, but Roblox exits after a couple seconds)

**Comment by pizzaboxer** [comment]
What flags have you configured in Bloxstrap's flag editor? Show a screenshot of it.

**Comment by mesidex** [comment]
This might be unrelated, but for anyone experiencing a crash after the most recent update, remove the following fflag:  `"FFlagVideoFrameYuvGPU": "True"`

**Comment by Afdah9a10** [comment]
Is this only a bloxstrap issue, I don't have bloxstrap but I get this issue whenever I join a game now

**Comment by pizzaboxer** [comment]
> I don't have bloxstrap but I get this issue whenever I join a game now

Have you seen what we've been saying here? Provide additional information relating to what we've been saying please.

**Comment by enphobic** [comment]
![image_2024-02-23_170003555](https://github.com/pizzaboxer/bloxstrap/assets/161014977/3a83b596-76e8-4b50-b5f6-5c3fa4cf6315)
![image](https://github.com/pizzaboxer/bloxstrap/assets/161014977/cc57641e-3830-4c0d-b2b7-1e10c89ae850)

its been crashing since months ago btw

**Comment by pizzaboxer** [comment]
Try setting your framerate limit to zero and see if that works.

**Comment by enphobic** [comment]
its going to ruin my gameplay, i was running no limit for frame rates

**Comment by pizzaboxer** [comment]
Are you sure this is only happening with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by enphobic** [comment]
i take it back, roblox did the same bullshit

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
