### ISSUE TITLE
[BUG] I uninstalled bloxstrap but noticed i couldn't play using websites but only the main game so I installed it again and when I played I has fps cap to 9999 but it was 20-30 and when i try to play on websites i just get a error notification

### ISSUE THREAD

**Issue by BEANSAREBEST** [pizzaboxer/bloxstrap#1325]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/160849727/ddbd8120-7c8b-484d-a2c3-67a0b0979167)

**Comment by BEANSAREBEST** [comment]
btw i uninstalled it bloxstrap but my fps is at 20 fps but it can go to 100 - 60 on average with the fps unlocker

**Comment by pizzaboxer** [comment]
Assuming this has been resolved, please follow-up if you're still having issues.

**Comment by lucaskenji792** [comment]
> Do you have the "Play Roblox" shortcut on your desktop? If so, then try running it, and try launching from the website afterwards.

dude me too now  i cant play roblox
