### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mirac7376** [pizzaboxer/bloxstrap#1326]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i wanna play with my friend and i try everything it doesnt starts, keeps giving me error even the roblox player app it says "another installation is downloading" smth like that and the error in bloxstrap says Signature does not match

**Comment by bluepilledgreat** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
