### ISSUE TITLE
[BUG]  Why I can't play roblox with a selected font

### ISSUE THREAD

**Issue by Sokoyotsuin** [pizzaboxer/bloxstrap#1327]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I opened **Bloxstrap** and I was trying to select a font called goldensun duo to see in roblox, when opening roblox I saw a **full gray screen** and I waited to play but roblox still don't **launch**. I tried different fonts but.
Roblox. Still. Don't. **Launch**.

![Screenshot 2024-02-22 183341](https://github.com/pizzaboxer/bloxstrap/assets/160977395/0212a007-5b28-4da4-9de1-6bba2b2d2ac4)

**Comment by Sokoyotsuin** [comment]
How do you fix this?
⬇Tell me in the comments here⬇

**Comment by pizzaboxer** [comment]
Does it work without a chosen font?

**Comment by GhoastYo** [comment]
When I got a font I unzipped and went into the file and chose one of the options. I got the minecraft font onto roblox and it looks great. You need to look inside the file and grab one of the open type font files and choose it as the font option. If you only use the folder it won't automatically apply one you need to go in the folder even if there's only one font inside.

**Comment by GhoastYo** [comment]
> How do you fix this? ⬇Tell me in the comments here⬇

^^

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
