### ISSUE TITLE
[READ] FFLAGs REMOVED?

### ISSUE THREAD

**Issue by githubberguy** [pizzaboxer/bloxstrap#1329]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

apparently yes, by the new version of 
![image](https://github.com/pizzaboxer/bloxstrap/assets/145132255/f95850a1-cb4b-4802-9f9d-37af1d1a3822)
bloxstrap, they decided to remove fast flags (NEWEST 2.60 VERSION)
![image](https://github.com/pizzaboxer/bloxstrap/assets/145132255/4862da76-75f0-476d-aed6-2597eba7e9d9)
these are all of the builds that removed fastflags, i still got a save of a 2.6.0 version with fastflags, 
if you need it.
Find the version of 2.6.0 bc im lazy to link the 2.6.0 old version
I HOPE you bring back fastflags, bc bloxstrap is actually famous for that, especially they make your game LOTS OF BETTER.

no it isnt bc i will uninstall it, but bc its so strange seeing bloxstrap without fflags, especially for somepeople who would downgrade again to 2.5.4
PLEASE DONT REMOVE FFLAGS IN FULL 2.6.0!

**Comment by githubberguy** [comment]
DO NOT CLOSE THIS, i am not doing stuff, just let people read

**Comment by pizzaboxer** [comment]
not my choice

**Comment by GoingCrazyDude** [comment]
bro is in so much denial

**Comment by totallyphysicallypossible** [comment]
feel like it should properly be explained as to why because most people here appear to be kids, but im guessing 
`[FLog::Warning] LoadClientSettingsFromLocal skipped for production client build`
 means that the client settings file won't be loaded anymore?

if that is the case, then yea remove fflags lol

**Comment by OrphanObliterator** [comment]
the crows are coming, githubberguy

**Comment by d44df016fe28bc8d5974** [comment]
you can probably use zflag and stay downgraded for 2 months
