### ISSUE TITLE
Check if latest version of current enrolled channel is out of date

### ISSUE THREAD

**Issue by MyszekGlonojad** [pizzaboxer/bloxstrap#133]
not sure if its a roblox or bloxstrap issue soooo

**Comment by MyszekGlonojad** [comment]
bloxstrap doesn't have the latest roblox version. opening roblox with RobloxPlayerLauncher doesn't give you the error

**Comment by pizzaboxer** [comment]
What channel do you have selected in the menu in the installation tab?

**Comment by MyszekGlonojad** [comment]
> 

none

**Comment by pizzaboxer** [comment]
Before you change it, can you please open State.json in the Bloxstrap folder and paste the file contents here?

**Comment by MyszekGlonojad** [comment]
{
  "VersionGuid": "version-e7bb50629c4f4926",
  "RbxFpsUnlockerVersion": "",
  "ReShadeConfigVersion": "",
  "ExtraviReShadePresetsVersion": "",
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\sounds\\ouch.ogg",
    "ExtraContent\\places\\Mobile.rbxl",
    "content\\textures\\Cursors\\KeyboardMouse\\ArrowCursor.png",
    "content\\textures\\Cursors\\KeyboardMouse\\ArrowFarCursor.png"
  ]
}

**Comment by pizzaboxer** [comment]
Whoops, I meant Settings.json

**Comment by MyszekGlonojad** [comment]
{
  "BootstrapperStyle": 3,
  "BootstrapperIcon": 3,
  "BootstrapperTitle": "Bloxstrap",
  "BootstrapperIconCustomLocation": "",
  "Theme": 2,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "MultiInstanceLaunching": false,
  "Channel": "zfeaturesignal-reduce-copies",
  "PromptChannelChange": false,
  "UseDiscordRichPresence": true,
  "HideRPCButtons": false,
  "RFUEnabled": false,
  "RFUAutoclose": false,
  "UseReShade": false,
  "UseReShadeExtraviPresets": false,
  "ShowServerDetails": true,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldMouseCursor": true,
  "UseDisableAppPatch": true,
  "DisableFullscreenOptimizations": false
}

**Comment by pizzaboxer** [comment]
Reopening as @bluepilledgreat just told me why this (possibly) happened, and I can definitely handle this better.

**Comment by pizzaboxer** [comment]
Delegated to v2.3.0 checklist.
