### ISSUE TITLE
[BUG] My Menu isnt working. I selected 2020 and I still have the new one

### ISSUE THREAD

**Issue by Sr3kw** [pizzaboxer/bloxstrap#1330]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I selected it. I also saved and when I loaded in it didnt work. Ive reinstalled many times and the same issue is happeneing.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
