### ISSUE TITLE
[BUG] neither bloxstrap or regular roblox are opening 

### ISSUE THREAD

**Issue by juniperfohx** [pizzaboxer/bloxstrap#1334]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

ive tried every fix and even checked the wiki but nothing works

**Comment by bluepilledgreat** [comment]
what flags do you have configured

**Comment by juniperfohx** [comment]
none

**Comment by juniperfohx** [comment]
and ive already uninstalled and reinstalled

**Comment by juniperfohx** [comment]
i just did another disk cleanup and it still doesnt open

**Comment by pizzaboxer** [comment]
> what flags do you have configured

they just said this happens with regular roblox too

> i just did another disk cleanup and it still doesnt open

If this is happening with Roblox too, I can't really help you beyond the information I've given on the Wiki. Sorry.
