### ISSUE TITLE
error An exception ocrrurred shile running bloxtrap

### ISSUE THREAD

**Issue by alanbeikers9** [pizzaboxer/bloxstrap#1335]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

esta instalando este programa y cuando le habia picado a instalar me aparecio esto error mientras se instalaba ahi les mando captura
![ScreenShot_20240224080936](https://github.com/pizzaboxer/bloxstrap/assets/161112138/8f797d4d-b935-4860-9652-c9edb98c8e6f)

**Comment by pizzaboxer** [comment]
Send the log file please

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
