### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Raijufr** [pizzaboxer/bloxstrap#1337]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Exception: Signature does not match!

**Comment by bluepilledgreat** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
