### ISSUE TITLE
SSL Error while trying to launch Roblox

### ISSUE THREAD

**Issue by zachariapopcorn** [pizzaboxer/bloxstrap#134]
So I'm trying to launch Roblox, but I keep getting this error
https://i.imgur.com/smmBQ8X.png

Log File: [Bloxstrap_20230415T010500Z.log](https://github.com/pizzaboxer/bloxstrap/files/11237969/Bloxstrap_20230415T010500Z.log)

**Comment by moshercise** [comment]
That's not Bloxstrap's fault.
![image](https://user-images.githubusercontent.com/105831555/232178281-64ac3e43-ab28-4569-93ca-38f2f6ad9841.png)

**Comment by zachariapopcorn** [comment]
Yea it is, I can go to it (specifically https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag) just fine in my browser and the regular launcher works fine

**Comment by zachariapopcorn** [comment]
I can still play with the normal Roblox launcher so I assume it's Bloxstrap's fault

**Comment by zachariapopcorn** [comment]
Seems like it works fine with a VPN (specifically Cloudflare WARP), but that's annoying

**Comment by pizzaboxer** [comment]
Let me guess, you live in Russia?
Yeah, this has been a big problem as ISPs like to block GitHub because people sometimes use it to host malicious software. There's nothing I can really do about that, you'll either have to use a VPN when starting Roblox or disable ReShade in the menu.

**Comment by pizzaboxer** [comment]
Huh, why are you unable to connect to [https://setup.rbxcdn.com](https://setup.rbxcdn.com)? Does the normal Roblox launcher do this either? The only time I've seen someone had this issue was because their ISPs were blocking downloads from GitHub that were needed for ReShade, but blocking the Roblox setup website?

**Comment by Razor7100** [comment]
Its only doing it with blox strap
the normal roblox works fine

**Comment by Razor7100** [comment]
> Seems like it works fine with a VPN (specifically Cloudflare WARP), but that's annoying

i would use a vpn but whenever my ip changes roblox logs me out its annoying to log back in every time

**Comment by pizzaboxer** [comment]
Are you able to access the second link?

**Comment by Razor7100** [comment]
![image](https://user-images.githubusercontent.com/121650332/232245192-9d92aeaf-bb77-43bf-86e7-dd987b3f2591.png)
![image](https://user-images.githubusercontent.com/121650332/232245217-e54a6820-d3bd-44b2-9819-10b2cdcf2243.png)

**Comment by pizzaboxer** [comment]
Okay, the second one works, great.
@moshercise @zachariapopcorn @nvthane - you three are also having the same issue, can you guys check too?
This is really weird, nobody has ever encountered an SSL issue on setup.rbxcdn.com before, and it just so happened like 4 people had the exact same problem starting on the exact same day. I have to wonder if there's a wider issue here. What ISPs do you guys use?

**Comment by zachariapopcorn** [comment]
I use Spectrum

**Comment by Razor7100** [comment]
I use spectrum too also im not in school

**Comment by Razor7100** [comment]
> I use Spectrum

Was your wifi really slow but still working yesterday too?

**Comment by zachariapopcorn** [comment]
> > I use Spectrum
> 
> Was your wifi really slow but still working yesterday too?

No, it was fast

@pizzaboxer I can access the second link with an access denied error, which seems to be expected

**Comment by Razor7100** [comment]
Ive been trying stuff to see if it anything fixes it but nothing has

**Comment by pizzaboxer** [comment]
Not even a VPN?

**Comment by pizzaboxer** [comment]
Whoops, forgot to ask you guys to do this, but what if you go to [http://setup.rbxcdn.com/](http://setup.rbxcdn.com/) (no HTTPS)?

**Comment by Razor7100** [comment]
My browser automatically puts the https if i put in setup.rbxcdn.com

**Comment by Razor7100** [comment]
When i go to setup.rbxcdn.com it still says it even if i go to http:// it still says it

**Comment by Razor7100** [comment]
the vpn makes it working for me

**Comment by Razor7100** [comment]
I think its something to do with spectrum internet

**Comment by zachariapopcorn** [comment]
> Whoops, forgot to ask you guys to do this, but what if you go to [http://setup.rbxcdn.com/](http://setup.rbxcdn.com/) (no HTTPS)?

Spectrum blocks it

**Comment by Razor7100** [comment]
Man that sucks

**Comment by Razor7100** [comment]
I wonder if it can be bypassed/fixed

**Comment by TrevorBMemes** [comment]
I'm experiencing it too.

**Comment by Razor7100** [comment]
do you have spectrum?

**Comment by TrevorBMemes** [comment]
I use Xfinity, seems like turning a VPN on and off fixed it.

**Comment by Razor7100** [comment]
only works when my vpn is on

**Comment by pizzaboxer** [comment]
Just released 2.1.1, can you guys confirm if this is still happening?

**Comment by zachariapopcorn** [comment]
2.1.1 seems to fix this issue. Thank you for the fix @pizzaboxer

**Comment by pizzaboxer** [comment]
Awesome. Sorry for taking a day to do this.
