### ISSUE TITLE
What is the best clientsettings fflag list for optimization

### ISSUE THREAD

**Issue by Reisusuki** [pizzaboxer/bloxstrap#1340]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I was just wondering what would be the best fflag list to improve ping and increase fflags (I don't mind if the game looks shit(but not too shit)) also while being able to have max render distance but no upgrade in quality

**Comment by user1126s** [comment]
T h e d i s c o r d s e r v e r has an entire channel for it

**Comment by Reisusuki** [comment]
what is the disc server
