### ISSUE TITLE
[BUG] Bloxstrap made the game crash out of nowhere

### ISSUE THREAD

**Issue by McIvanX** [pizzaboxer/bloxstrap#1341]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The first time I ran roblox with bloxstrap, it worked like a charm, now it doesnt at all...

I was using the Microsoft Store's build of Roblox along with Bloxstrap, now it crashes upon launching with no error at all, the game refuses to launch.

I've done my research, and I've been messing with Hyperion (or Byfron) since it was included in Fortnite, and I can tell this problem might be caused by their SID banning system, which bans your computer's SID and forces you to either change it (which is time consuming) or reinstall your windows to generate a new one.

Bloxstrap might NOT be crashing the game, but causing detection vectors which trigger Byfron and their SID banning system.

Reinstalling windows is the easiest path to go as of right now, my OS is: Windows 10 22H2 19045.3570 (winver)

**Comment by McIvanX** [comment]
UPDATE: 

Just as I thought, the problem was caused by their SID blacklisting system, I have solved it by changing my SID using this tool: 
https://www.stratesave.com/html/sidchg.html

This can be a really good solution for those who have the same problem as I do. Some of the advices I have are:

1. If your windows installation is corrupted (some features dont work, etc) it might be better to reinstall your OS
2. Make a backup of all your files before using the tool, and if it fails to change the SID and ends up messing with your windows, run the OS using secure boot and restore it.
3. Do NOT login or power off the computer while the SID is being changed, it will log you out and will show you a prompt when you try to log in, showing some info at the bottom.
4. Follow the guide on the website.

I'll test this method with friends and people who have the same issue, and I'll track the results here.

**Comment by juniperfohx** [comment]
This works, but beware that it signs you out if everything
so make sure you remember you logins

**Comment by Itsyoboymoon** [comment]
i have problem its when i open from bloxstrap it instantly crashes but the game is perfectly working and when i try to join a game it instantly closes/crashes with no errors when i try without bloxstrap it works normally please comment immetidaly

**Comment by BloxstrapRobloxUser** [comment]
Just run bloxstrap as administrator

**Comment by vaidik214** [comment]
I use bloxstrap since 4-5 months now and it was working fine until now. it causes my whole windows to crash even though it is a new gaming laptop with latest tech. what can i do?
