### ISSUE TITLE
Bloxstrap hangs on "Applying modifications"[BUG] 

### ISSUE THREAD

**Issue by RiddDoesStuff** [pizzaboxer/bloxstrap#1342]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So apparently whenever I open up a game on ROBLOX it just always gets stuck on the applying modifications screen. Is this something that happens regularly or is this odd? Please help me :D
https://github.com/pizzaboxer/bloxstrap/assets/161146673/f4c5c7aa-cd5f-473e-887b-735b14609d97

**Comment by pizzaboxer** [comment]
This happens whenever you launch? Get the latest log file from `%localappdata%\Bloxstrap\Logs` and upload it here please?

**Comment by RiddDoesStuff** [comment]
Sorry, it's fixed now. I just reinstalled Bloxstrap.

**Comment by pizzaboxer** [comment]
I really wish you had uploaded that log file.
