### ISSUE TITLE
[BUG]  Wont open

### ISSUE THREAD

**Issue by jinx-jai** [pizzaboxer/bloxstrap#1344]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It keeps getting stuck on "Reaching for an available server" and I even deleted and re installed it and it still doesn't work. I tried it on regular Roblox and it worked, Please fix this issue.

**Comment by Mugetsu895** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142404890/1e06e8f2-5f44-477d-8f7e-28ac622cb586)
