### ISSUE TITLE
HOW CAN I ADD CUSTOM SHIFTLOCK CURSOR ?[REQ] 

### ISSUE THREAD

**Issue by PKezi** [pizzaboxer/bloxstrap#1347]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

HOW CAN I ADD CUSTOM SHIFTLOCK CURSOR ?

**Comment by PKezi** [comment]
I did put those custom MouseLockedCursor.png on  do i have to copy a content to a modification file ?

**Comment by pizzaboxer** [comment]
> I did put those custom MouseLockedCursor.png on do i have to copy a content to a modification file ?

You simply place 'MouseLockedCursor.png' in the 'content\fonts' folder.

**Comment by hjyuh** [comment]
it isn't working for me, does it need to be in /fonts?

**Comment by pizzaboxer** [comment]
> it isn't working for me, does it need to be in /fonts?

My bad, I gave the wrong path, see https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods#locations-of-interest

**Comment by hjyuh** [comment]
content\textures\Cursors\KeyboardMouse\ ?

**Comment by pizzaboxer** [comment]
> content\textures\Cursors\KeyboardMouse\ ?

I gave the wrong path again, you actually just place it in `content\textures\`. I promise this time. You place it there with the name "MouseLockedCursor.png".

**Comment by probablygone** [comment]
tried that,didn't seem to work

**Comment by AlanPHPP** [comment]
sorry for necroposting but yeah i bump this, i've been trying to do this for half an hour or something and it doesn't matter how many textures named "MouseLockedCursor" you modify, ingame the cursor will just be transparent when you shiftlock / use your normal cursor icon, please add a fix to this.

bump
