### ISSUE TITLE
Error occured while starting roblox ssl connection cannot be estableshed

### ISSUE THREAD

**Issue by Razor7100** [pizzaboxer/bloxstrap#135]
i tried uninstalling blox strap and it worked fine
![image](https://user-images.githubusercontent.com/121650332/232178518-9ce62961-16ea-43a8-9101-1a8c8ad6e191.png)

**Comment by Razor7100** [comment]
i get this while installing blox strap or launching  a roblox game

**Comment by pizzaboxer** [comment]
Go to #134 since someone is discussing the same issue there.
