### ISSUE TITLE
[BUG] roblox has time out. please restar ur client help

### ISSUE THREAD

**Issue by mixTAa** [pizzaboxer/bloxstrap#1352]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/161335973/137dbd2d-4455-4663-a2ba-b49065c82c9d)

**Comment by mixTAa** [comment]
idk how ti fix this, i can play in peace

**Comment by NinDevs** [comment]
Just trying Bloxstrap for the first time, can confirm this is happening repeatedly. Can't play Roblox for more than around ~10 mins before having this error. All settings are default and no additional fast flags are used, fps limit on 120.

**Comment by pizzaboxer** [comment]
> Though honestly this could very well be Roblox itself as it has a history of crashing for no reason lol

Did you try playing without Bloxstrap then? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer I have found the problem, disabling the Desktop App makes this error pop up.

**Comment by Mugetsu895** [comment]
for me it's FFlagVideoFrameYuvGPU that does this

**Comment by pizzaboxer** [comment]
> @pizzaboxer I have found the problem, disabling the Desktop App makes this error pop up.

In that case, the error would only be showing when you try to close Roblox, which is not the concern here.

**Comment by declanipp2103** [comment]
Ok, so I think I found a fix. I had a power outage and I was having the problem. When I restarted the computer after it came back on the problem isn't persisting anymore.

**Comment by declanipp2103** [comment]
Another fix that worked on my laptop with the same drivers as my pc, is uninstalling 551.63 and installing a older version

**Comment by NinDevs** [comment]
> Did you try playing without Bloxstrap then? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Can confirm this is just a Roblox issue. Happens without bloxstrap as well.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
