### ISSUE TITLE
I cant start the game nor the launcher [BUG] 

### ISSUE THREAD

**Issue by VxntageMan** [pizzaboxer/bloxstrap#1353]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

https://github.com/pizzaboxer/bloxstrap/assets/161349756/2859ce20-1963-4166-a1c0-544124c26fed

I was clicking btw

**Comment by VxntageMan** [comment]
i reinstalled the game 3 times, nothing works

**Comment by pizzaboxer** [comment]
Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?
