### ISSUE TITLE
System.IO.IOException error

### ISSUE THREAD

**Issue by tjpjxd** [pizzaboxer/bloxstrap#1355]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

everytime I try to download bloxstrap, an error occurs saying System.IO.IOException: the file blah blah blah already exists, but when I delete the locate file it still does it. 
![image_2024-02-26_172432370](https://github.com/pizzaboxer/bloxstrap/assets/161387850/8b129395-742b-4f7a-bc05-5730ef023ad2)
The locate file is Bloxstrap_20240226T221808Z

**Comment by pizzaboxer** [comment]
>  The locate file is Bloxstrap_20240226T221808Z

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
