### ISSUE TITLE
no textures

### ISSUE THREAD

**Issue by Plumpyyreal** [pizzaboxer/bloxstrap#1356]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've been using a no texture fast flag for a while now and had been working fine. But now it hasn't, I've tried different versions but still hasn't worked. May I know what's the problem and how to fix it.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
