### ISSUE TITLE
[BUG] textures not working

### ISSUE THREAD

**Issue by rahhh1231312** [pizzaboxer/bloxstrap#1357]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Removed my jsons to play a horror game but when i imported them back in, the textures wont work. ive also tried other textures but none of them work.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
