### ISSUE TITLE
No Texture not working

### ISSUE THREAD

**Issue by AwesomeNoob** [pizzaboxer/bloxstrap#1358]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I load up the game and the no texture wasn't working, I tried fixing it but it didn't work

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer you should probably do a proper announcement explaining why more and more flags are not working anymore.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures

**Comment by AwesomeNoob** [comment]
Aight thank you
