### ISSUE TITLE
[BUG] Fastflags old material textures not working

### ISSUE THREAD

**Issue by Swagses** [pizzaboxer/bloxstrap#1359]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Cant use fastflags old material textures, have tried basically everything including reinstalling

**Comment by ShadowCodeX-debug** [comment]
FastFlags are being phased/patched out by Roblox skipping the application of local clientappsettings. A few commonly used FFlags like the one your trying to use has now been patched. Although their is a (temporary) fix which you can check in [here](https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
