### ISSUE TITLE
(FEATURE REQUEST) Invite Feature [DISCORD PRESENCE]

### ISSUE THREAD

**Issue by borjita2019** [pizzaboxer/bloxstrap#136]
If you have "Show game activity" turned on in BloxStrap, the user can invite anyone with BloxStrap installed to the game. Example:
![image](https://user-images.githubusercontent.com/63255187/232229442-3002797b-53e7-4ab7-88e5-72544d6044a7.png)

[Reference Alternative](https://github.com/thelennylord/rblx_rich_presence)

The reference is most likely dead, but rewrite branch is rewriting the whole program in Go.
I would really appreciate the addition of this feature, as i wanna invite my friends but TOO lazy to make them join through the Roblox website (government computers, yk?)

thanks kyji for telling me to make this feature request

**Comment by MafuSaku** [comment]
Doesn't bloxstrap already have a feature kind of like this where if you have the "Allow activity joining" enabled someone can press your profile and join you in the game in the same server with launch data?

**Comment by borjita2019** [comment]
> Doesn't bloxstrap already have a feature kind of like this where if you have the "Allow activity joining" enabled someone can press your profile and join you in the game in the same server with launch data?

what i mean is that, but through invites, because i don't want anyone to just join me through a public button

**Comment by pizzaboxer** [comment]
I kind of skipped over this because I didn't really understand how to make it work with Roblox. I'll take a look at it again, and if there's a real reason I can't make it work, I'll let you know.

**Comment by pizzaboxer** [comment]
Oh yeah, I just remembered some of the problems I realized when I first thought about this.

One big problem is that I don't really know how to handle join request notifications. All games that have support for this have it built in, of course, so they just do it through the in-game gui. My only option here is doing it with a dialog box or something, which can just completely interrupt whatever you're doing, and may not even show in full screen.

Another problem is that this is intended for joining game parties, and not really joining a server in general like this. That means to enable this, Discord has to also show information about the party (or server in this case), which I can't really do.

The feature just doesn't work with this. It's not really intended for this, and I have no way of implementing it effectively.

**Comment by borjita2019** [comment]
been relooking at this, and just remembered this project which has done something similar and myself have used before (https://github.com/thelennylord/rblx_rich_presence)

here's my idea on how this could work
> get server id / jobid
> invite someone on discord that also has bloxstrap
> bloxstrap opens and joins that server (could also show what game you're joining on the bootstrapper)

and for the party info (max players, etc)
just get the max amount of players of the game/place itself, not the server (although could be needed for showing how many players there are on the server)

**Comment by pizzaboxer** [comment]
I don't like the idea that this will only be usable by other people who use Bloxstrap too. The other concerns I had still remain.

> just get the max amount of players of the game/place itself

Discord won't let you set that many.
