### ISSUE TITLE
How do i enable this ui?

### ISSUE THREAD

**Issue by NukeThief** [pizzaboxer/bloxstrap#1362]
![image](https://github.com/pizzaboxer/bloxstrap/assets/81801547/692d4170-f2b7-42c2-b8b1-1deb5452c610)
i want this ui in my game, though with the chat button next to it if that's possible.

**Comment by ShadowCodeX-debug** [comment]
```json
{
"FFlagEnableInGameMenuChrome": true,
"FFlagEnableChromePinnedChat": true
}
```
