### ISSUE TITLE
[BUG] I cannot change the icon and title of the game

### ISSUE THREAD

**Issue by NajmiDhiyaAlfath** [pizzaboxer/bloxstrap#1363]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried to change the icon style and title but it wont work inside of the game

![image](https://github.com/pizzaboxer/bloxstrap/assets/161578538/6fc4d549-5c05-4e8d-a415-72d1d91da9f2)

![image](https://github.com/pizzaboxer/bloxstrap/assets/161578538/f1ffd890-9bdb-4ebd-bb07-fd6d2615ff98)

I hope it will be greateful if i can make custom stuff

**Comment by pizzaboxer** [comment]
The Appearance tab of the menu is strictly for the bootstrapper only.

**Comment by NajmiDhiyaAlfath** [comment]
Oh ok
