### ISSUE TITLE
[BUG] FPS capped at 60

### ISSUE THREAD

**Issue by C0D6WasTaken** [pizzaboxer/bloxstrap#1365]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have read the wiki and tried a few things such as:
- disabling additional flags
- reinstalling Roblox
- disabling any power reduction settings (laptop)

As of writing this I noticed that the flag itself doesn't seem to work anymore. And yes, other flags are still functional.

**Comment by ShadowCodeX-debug** [comment]
Could you send a screen shot of your flags?

**Comment by pizzaboxer** [comment]
If everything else is working, then it's definitely something on your PC that's capping it. As far as I'm concerned, Bloxstrap is doing its job correctly. Also, as shadow said, posting a list of all your flags would be helpful.

**Comment by C0D6WasTaken** [comment]
The issue has been fixed. Flags weren't the cause. It was all due to NVIDIA's whisper mode refusing to toggle off and thus limiting the framerate.
