### ISSUE TITLE
Bloxstrap not working or appearing in control panel

### ISSUE THREAD

**Issue by voobispro** [pizzaboxer/bloxstrap#1366]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My fast flags dont work at all and when I go to uninstall bloxstrap it does not appear in control panel. I remove it manually and reinstall but it still doesn't work.

**Comment by pizzaboxer** [comment]
I'll get you to properly reinstall it fresh, which should fix your issues.. Delete the folder at `%localappdata%\Bloxstrap\` manually, and then open the Registry Editor and delete the key at `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap`

**Comment by pizzaboxer** [comment]
Assuming to be resolved, please follow up with any issues that continue to occur.
