### ISSUE TITLE
is not wkring!!!!!!!!!!!!!![BUG] 

### ISSUE THREAD

**Issue by memerz1337** [pizzaboxer/bloxstrap#1369]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i oepn and it not work i clik on the ap says play roblxo

**Comment by memerz1337** [comment]
it stil no work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bluepilledgreat** [comment]
i am not going to attempt to read this

**Comment by GoingCrazyDude** [comment]
i can translate from 9 year old speak to english if you want

**Comment by ShadowCodeX-debug** [comment]
Find "Bloxstrap Menu" in your start menu, if it's not their then make a new extension with the Bloxstrap file path and the --menu arguement.
