### ISSUE TITLE
[BUG] Use old material textures function doesn't work

### ISSUE THREAD

**Issue by squch0** [pizzaboxer/bloxstrap#1370]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I launch Roblox by Bloxstrap and in FastFlags Use old material textures function is enabled but when I launch Roblox this function doesn't work I still have new textures.

**Comment by ShadowCodeX-debug** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
