### ISSUE TITLE
[BUG] I know i mentroned this before but it is stuck in aloob and i finally got to error

### ISSUE THREAD

**Issue by hadesiak130** [pizzaboxer/bloxstrap#1372]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240301T145452Z.log](https://github.com/pizzaboxer/bloxstrap/files/14462600/Bloxstrap_20240301T145452Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox

Did you read the preliminary instructions?

**Comment by hadesiak130** [comment]
thanks
