### ISSUE TITLE
[BUG] roblox stays connecting forever and does an error sometimes yeah

### ISSUE THREAD

**Issue by JackDoeaw** [pizzaboxer/bloxstrap#1374]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240302T001913Z.log](https://github.com/pizzaboxer/bloxstrap/files/14467156/Bloxstrap_20240302T001913Z.log)

**Comment by pizzaboxer** [comment]
Is this happening every single time you launch?

**Comment by JackDoeaw** [comment]
no, but it happens pretty much all of the time, sometimes it does work normally however

**Comment by pizzaboxer** [comment]
This is primarily suggesting an issue with your internet connection. This isn't an issue on my side.

**Comment by JackDoeaw** [comment]
i wouldnt say its an issue with my wifi since its pretty stable, imma reinstall bloxtrap to see if it fixes it

**Comment by pizzaboxer** [comment]
By that, it could also mean some application on your computer preventing it from connecting to the internet, like an antivirus.
