### ISSUE TITLE
Ping problem with Bloxstrap installed

### ISSUE THREAD

**Issue by frxgt** [pizzaboxer/bloxstrap#1375]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Normally my ping is about 60-80ms but with Bloxstrap installed, it is 300-2000ms. I've tried turning off all the features and setting the fps unlocker to 0 but it doesn't fix anything. When I uninstall it, Roblox runs normally again. Maybe this has something to do with Roblox patching FPS unlockers?

**Comment by pizzaboxer** [comment]
> When I uninstall it, Roblox runs normally again.

I'd like to get a better idea of what config you're using if setting the framerate limit to zero doesn't work. Can you show a screenshot of what your flag editor looks like please?

**Comment by frxgt** [comment]
> > When I uninstall it, Roblox runs normally again.
> 
> I'd like to get a better idea of what config you're using if setting the framerate limit to zero doesn't work. Can you show a screenshot of what your flag editor looks like please?

![image](https://github.com/pizzaboxer/bloxstrap/assets/161911667/c5224a98-6287-40c9-8251-599cd4562d86)

**Comment by pizzaboxer** [comment]
What about if you disable all of Bloxstrap's integrations?

**Comment by frxgt** [comment]
> What about if you disable all of Bloxstrap's integrations?

Even then, the ping spikes doesn't stop occurring

**Comment by pizzaboxer** [comment]
> but still had ping spikes every 4 or 5 seconds

Are you sure you don't encounter those with the standard Roblox launcher?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
