### ISSUE TITLE
[BUG Error code 403 when trying to open through chrome 

### ISSUE THREAD

**Issue by PANDaz0427** [pizzaboxer/bloxstrap#1376]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Ive been trying to get around 4 roblox tabs open at the same time but i constantly get this error code when roblox through chrome, if i try multible tabs on the roblox app it just closes the other. any fix to this code ](url)
Screenshot 2024-03-02 071736

**Comment by PANDaz0427** [comment]
![Uploading Screenshot 2024-03-02 071736.png…]()

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/issues/268#issuecomment-1974792524

**Comment by PANDaz0427** [comment]
even though i try to open it with the setting on it still doesnt work

**Comment by pizzaboxer** [comment]
Are you seeing the Bloxstrap launcher show before you launch Roblox?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
