### ISSUE TITLE
Why I cant Unfullscreen roblox? [BUG] 

### ISSUE THREAD

**Issue by Dxysuis** [pizzaboxer/bloxstrap#1377]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I cant unfullscreen roblox somehow

**Comment by Dxysuis** [comment]
![Screenshot 2024-03-02 211944](https://github.com/pizzaboxer/bloxstrap/assets/143704888/a2dbeb5b-e434-4a22-82cb-1fdc908aa255)
this is my fast flags if u even ask

**Comment by pizzaboxer** [comment]
Don't use OpenGL.
