### ISSUE TITLE
[FAQ] How to change the language?

### ISSUE THREAD

**Issue by BodiksWerx** [pizzaboxer/bloxstrap#1379]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

How to change the language?

**Comment by pizzaboxer** [comment]
Change the language of what?

**Comment by BodiksWerx** [comment]
How do I set up Bloxstrap if I don't understand English (I'm writing from a translator)

**Comment by pizzaboxer** [comment]
We currently don't have support for translations in different languages. sorry. That should hopefully be coming in a future version though.
