### ISSUE TITLE
[BUG] Every time turning on another instance, roblox forces an upgrade and overrides some changes.

### ISSUE THREAD

**Issue by NukeThief** [pizzaboxer/bloxstrap#1380]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Every time turning on another instance, roblox forces an upgrade and overrides some changes. what else can i say.

**Comment by NukeThief** [comment]
i found a workaround that uses using the play roblox app instead of the browser.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Using-multiple-instances-always-forces-a-Roblox-upgrade
