### ISSUE TITLE
[BUG] Roblox is not opening when trying to play a game

### ISSUE THREAD

**Issue by RelkzzRebranded** [pizzaboxer/bloxstrap#1382]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

can someone help me with bloxtrap closing after trying to play a game?
https://github.com/pizzaboxer/bloxstrap/assets/130754062/749bed96-ddf2-4894-9bb9-2487ec9632cb

LOGS:
[Bloxstrap_20240303T075734Z.log](https://github.com/pizzaboxer/bloxstrap/files/14472154/Bloxstrap_20240303T075734Z.log)

**Comment by pizzaboxer** [comment]
As per the preliminary instructions, is this happening only when launching with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by RelkzzRebranded** [comment]
> As per the preliminary instructions, is this happening only when launching with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Nope this also has been happening on the normal roblox, not sure why it wont launch and closes itself instantly

**Comment by pizzaboxer** [comment]
I can't help you much beyond telling you to read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch, sorry.
