### ISSUE TITLE
[BUG] Old textures not working

### ISSUE THREAD

**Issue by astralrayrrr2** [pizzaboxer/bloxstrap#1386]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i have the old textures checked in the bloxstrap menu but when i join a game it shows the new textures.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
