### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rbkkj** [pizzaboxer/bloxstrap#1387]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

will it work with roblox from the microsoft store?

**Comment by cub-has-injected** [comment]
Nope, It downloads a native windows version (not the UWP or "microsoft store version") of roblox on their website. (https://setup.rbxcdn.com/Roblox.exe or https://www.roblox.com/download/)

**Comment by pizzaboxer** [comment]
No.
