### ISSUE TITLE
[BUG] Controls are lagging

### ISSUE THREAD

**Issue by KehlanMetor** [pizzaboxer/bloxstrap#1388]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i know its not my internet connection. When i go into a game sometimes the controls have a bigg delay and like when you press w it moves 5 seconds later. It happened so many times and idk why

**Comment by ShadowCodeX-debug** [comment]
Mind sending a video of it happening? I might know what you are referring too.

**Comment by pizzaboxer** [comment]
> When i go into a game sometimes the controls have a bigg delay and like when you press w it moves 5 seconds later. It happened so many times and idk why

As per the preliminary instructions, have you verified that this only happens with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by KehlanMetor** [comment]
> As per the preliminary instructions, have you verified that this only happens with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I tried switching and the normal roblox version works well. I never happened to me before because bloxstrap worked well. But since a while, it sometimes started to have delays and its becoming more and more problematic.

**Comment by pizzaboxer** [comment]
What flags do you have configured in Bloxstrap's flag editor? Show a screenshot of it.

**Comment by KehlanMetor** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/82890272/fcdd9d1b-49f3-4394-a935-6f0c3487d1ea)
I didnt change much

**Comment by KehlanMetor** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/82890272/46a62ee5-9d88-4652-9acf-3e8e2e20f2f3)
there is nothing on the editor

**Comment by pizzaboxer** [comment]
Try disabling all the integrations provided in the integrations tab, and see if the issue still happens.

**Comment by KehlanMetor** [comment]
It not works perfectly well. Thank you verry much.
