### ISSUE TITLE
idfk bloxstrap aint openimg[BUG] 

### ISSUE THREAD

**Issue by ratfucker63** [pizzaboxer/bloxstrap#1389]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\D&K\Desktop\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json' is denied.
![Uploading Screenshot 2024-03-04 113124.png…]()

**Comment by pizzaboxer** [comment]
Open the mods folder, open the ClientSettings folder, open the file properties for ClientAppSettings.json and make sure it's not marked as read-only.
