### ISSUE TITLE
Option to use Roshade instead of Reshade

### ISSUE THREAD

**Issue by FredDoesStuff** [pizzaboxer/bloxstrap#139]
i prefer roshade over reshade, some people probably do too

**Comment by Extravi** [comment]
Roshade is just using Reshade; it's the same, it's just different presets. Also, Roshade presets cannot be disturbed. If you have feedback for Extravis ReShade Presets, let me know.

**Comment by FredDoesStuff** [comment]
Ok, thanks.

**Comment by Extravi** [comment]
If you want to submit feedback add me on discord cta#4015 thanks.

**Comment by pizzaboxer** [comment]
Also, see #20 for a more clear explanation.
