### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by waifuruns** [pizzaboxer/bloxstrap#1390]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I haven't encountered this bug since March 4, 2024; could you kindly repair it? 
**System.TypeInitializationException: The type initializer for 'System.Text.Encodings.Web.DefaultJavaScriptEncoder' threw an exception.

[Inner Exception]
System.BadImageFormatException: Could not load file or assembly 'System.Numerics.Vectors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Format of the executable (.exe) or library (.dll) is invalid.**

**Comment by waifuruns** [comment]
here is "corrupted" file
[Bloxstrap_20240304T100833Z.log](https://github.com/pizzaboxer/bloxstrap/files/14479954/Bloxstrap_20240304T100833Z.log)

**Comment by pizzaboxer** [comment]
Try reinstalling/repairing your .NET runtime installation. https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true

**Comment by pizzaboxer** [comment]
Assuming that this issue has been resolved now. Let me know if you're stiill facing difficulties.
