### ISSUE TITLE
[BUG] Logout problem

### ISSUE THREAD

**Issue by TheEmoBoy9887** [pizzaboxer/bloxstrap#1392]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The logout screen when u get banned for 1 day or more bugs out and u cant click it and basically covers the client and u can press log in and whatever but u cant see it. for more info on it add me on discord eggoofficial

**Comment by pizzaboxer** [comment]
As per the preliminary instructions, did you check if this only happened with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by Returnofxuqin** [comment]
Im also having the same problems, and it's only happening with bloxstrap.

**Comment by Returnofxuqin** [comment]
I fixed it; this is how. I opened the bloxstrap menu, went down to 'Behavior', and turned on Force Roblox Reinstallation. I went on the Roblox site, opened a game, then, after installing, opened the Roblox player, logged out from there, then opened the bloxstrap, and it should ask you to sign up or login.
