### ISSUE TITLE
Join a server from the instance id 

### ISSUE THREAD

**Issue by Maximanden99** [pizzaboxer/bloxstrap#1394]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Hello, firstly thanks for an awesome app.
In petsim99 we have private servers, recently they made a new world and we get shipped to different servers, because its like another place not in game we get teleported to "Reserved" servers  and alone so it is kinda private, but without beeing able to be together, like a private server, would it be possible to use the server instance id bloxstrap so nicely can provide to join each other?

**Comment by Maximanden99** [comment]
Because they ask to better ask a question here than in discord, and i think its a valid question if it will be possible, i dont see you beeing helpfull, so why even comment?

**Comment by pizzaboxer** [comment]
> would it be possible to use the server instance id bloxstrap so nicely can provide to join each other?

You can't join reserved servers using just a job ID. You also need a special one-time access token which only the gameserver issues when it's about to teleport a player.
