### ISSUE TITLE
[BUG] Functions.

### ISSUE THREAD

**Issue by SkidRBLX** [pizzaboxer/bloxstrap#1398]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The bloxstrap functions dont work as intended and bloxstrap doesnt launch as it should.
Thats literally the only explanation needed (for now).

**Comment by SkidRBLX** [comment]
I saved the functions and they did not do much aside from launching basic roblox and not bloxstrap.

**Comment by ShadowCodeX-debug** [comment]
Are you talking about it not loading up the Bloxstrap menu?

**Comment by SkidRBLX** [comment]
> Are you talking about it not loading up the Bloxstrap menu?

Not quite, the functions just do not work for me.

**Comment by ShadowCodeX-debug** [comment]
What 'functions' are you talking about???

**Comment by SkidRBLX** [comment]
> What 'functions' are you talking about???

Like the ones in the bloxstrap menu.

**Comment by bluepilledgreat** [comment]
Provide log files

**Comment by pizzaboxer** [comment]
> I saved the functions and they did not do much aside from launching basic roblox and not bloxstrap.

Are you not seeing the Bloxstrap launcher show whenever you launch Roblox?

**Comment by SkidRBLX** [comment]
> > I saved the functions and they did not do much aside from launching basic roblox and not bloxstrap.
> 
> Are you not seeing the Bloxstrap launcher show whenever you launch Roblox?

Yup.

**Comment by pizzaboxer** [comment]
> Yup.

Launch the 'Play Roblox' shortcut that's on your desktop. You should only have to do it once.
