### ISSUE TITLE
[BUG] 2015 esc menu not working

### ISSUE THREAD

**Issue by titantvm** [pizzaboxer/bloxstrap#1401]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i opened roblox the ui changed and when i pressed esc it showed the new menu and not the 2015 one i picked on bloxstrap.

**Comment by bluepilledgreat** [comment]
We are no longer helping with fast flag related issues. Please see #1321.
