### ISSUE TITLE
[REQ] 2 new flags

### ISSUE THREAD

**Issue by PepperMarioYT** [pizzaboxer/bloxstrap#1402]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Disable Chrome UI `FFlagEnableInGameMenuChromeABTest2`
Disable Report button `FFlagEnableReportAbuseMenuRoactABTest2`
Both are sliders

**Comment by bluepilledgreat** [comment]
#1321
