### ISSUE TITLE
[BUG] .NET downloaded but doesn't work

### ISSUE THREAD

**Issue by brvsiv** [pizzaboxer/bloxstrap#1404]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I found Bloxstrap recently but whenever I open the file it says I need to download .NET, it already is downloaded and it still wont work. yes I redownloaded Bloxstrap after downloading .NET

**Comment by ShadowCodeX-debug** [comment]
Did you download .Net Desktop Runtime 6.0?

**Comment by pizzaboxer** [comment]
Are you still seeing the prompt? Open a Command Prompt window and run this command: `dotnet --info`
Screenshot what you see then send it here.

**Comment by pizzaboxer** [comment]
You don't have the latest version of .NET 6 installed. Go and download it. Let me know if it doesn't work. https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true

**Comment by ShadowCodeX-debug** [comment]
Hey @pizzaboxer why specifically .NET 6? Why not .NET 8?

**Comment by GoingCrazyDude** [comment]
> Hey @pizzaboxer why specifically .NET 6? Why not .NET 8?

because it uses .net sdk 6
