### ISSUE TITLE
[BUG] An exception occurred while instal Bloxstrap

### ISSUE THREAD

**Issue by naufalrizky8795** [pizzaboxer/bloxstrap#1405]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't know what happened during installation but I was told where the missing files or errors were (I don't know) and I don't know how to solve the problem
![WhatsApp Image 2024-03-06 at 22 02 14](https://github.com/pizzaboxer/bloxstrap/assets/162469362/612b05c7-b90b-4858-aa8b-1395f171922f)

**Comment by pizzaboxer** [comment]
Open the `%localappdata%\Bloxstrap\` folder, and show a screenshot of what's in there.

**Comment by pizzaboxer** [comment]
Are you getting the same error when you try to install it even now?

**Comment by naufalrizky8795** [comment]
yeah

**Comment by pizzaboxer** [comment]
What?

Do you have showing hidden files enabled in Windows explorer? You can enable it in the View tab at the top. Show a screenshot then if you see anything different after enabling it.

**Comment by DaRialDipZvki** [comment]
![Errorrrr](https://github.com/pizzaboxer/bloxstrap/assets/164936247/a7ace1d9-99d0-4dea-b6be-faaf1c5554e4)

Could help me or explain to me what it means??

**Comment by pizzaboxer** [comment]
> Could help me or explain to me what it means??

Upload the log file please.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
