### ISSUE TITLE
[BUG] Error while running Strap

### ISSUE THREAD

**Issue by guihhhdd** [pizzaboxer/bloxstrap#1406]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried to change fonts but i cant bc everytime this text pops up"System.IO.IOException: The file 'C:\Users\User\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' already exists."
![image](https://github.com/pizzaboxer/bloxstrap/assets/162486937/6abe3ddf-e0b3-4028-ab6c-1792afb6941f)

**Comment by pizzaboxer** [comment]
> I tried to change fonts but i cant bc everytime this text pops up

In the menu, does the button initially ask you to remove it or does it ask you to choose one?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
