### ISSUE TITLE
[BUG] see for ur self

### ISSUE THREAD

**Issue by faefgs** [pizzaboxer/bloxstrap#1407]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The process cannot access the file 'C:\Users\user\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.)

[Inner Exception]
System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Bloxstrap\Versions\version-bca459bcd1854ce4\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.

**Comment by pizzaboxer** [comment]
Roblox is running in the background. Close it first before you do anything.
