### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MasterM62** [pizzaboxer/bloxstrap#1408]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

where is the channel button, i just need to know how to get to it or unhide it please

**Comment by ShadowCodeX-debug** [comment]
I believe you need to set "OhHeyYouFoundMe" to true in one of the json files of Bloxstrap.

**Comment by OrphanObliterator** [comment]
give me free minecoins and then we'll talk

**Comment by MasterM62** [comment]
@ShadowCodeX-debug  i looked into the only json file i seen, but i dont know were to go or what to specifically

**Comment by OrphanObliterator** [comment]
> @ShadowCodeX-debug i looked into the only json file i seen, but i dont know were to go or what to specifically

so about those minecoins

**Comment by ShadowCodeX-debug** [comment]
@MasterM62 Look in Settings.json -> set "OhHeyYouFoundMe" to true and see to the Bloxstrap menu.

**Comment by bulieme** [comment]
it doesnt appear for me
