### ISSUE TITLE
[BUG] Bloxstrap stopped automatically putting my mods and fast flags

### ISSUE THREAD

**Issue by AngryBirdsFanboy06** [pizzaboxer/bloxstrap#1409]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

No idea what happened today but when i switched to a different channel, Bloxstrap gave up on automatically putting my mods and fast flags settings to that version, i ended up a lot of configuring to see what issue was causing it (includes, reinstalling Roblox on Bloxstrap, reinstalling Bloxstrap itself, changing the settings.json file, switching back to LIVE), and when i manually put my mods and fast flags settings to the versions folder, it worked.

So I think Bloxstrap might have a issue where it legit doesnt automaticly add the modifications from the "modifications" folder to the current version folder.

**Comment by ShadowCodeX-debug** [comment]
Please provide a log file.

**Comment by AngryBirdsFanboy06** [comment]
which logs, bloxstraps or robloxs logs (which according to pizzaboxer, i shouldnt post my robloxs logs to anyone that i dont trust)

**Comment by ShadowCodeX-debug** [comment]
Most likely the Bloxstrap log file since Bloxstrap handles loading modifications.

**Comment by AngryBirdsFanboy06** [comment]
alright, just know that because i reinstalled bloxstrap, i unfortunately lost my older logs 
Heres my latest bloxstrap log
[Bloxstrap_20240307T170056Z.log](https://github.com/pizzaboxer/bloxstrap/files/14528181/Bloxstrap_20240307T170056Z.log)
[Bloxstrap_20240307T165941Z.log](https://github.com/pizzaboxer/bloxstrap/files/14528180/Bloxstrap_20240307T165941Z.log)
[Bloxstrap_20240307T175153Z.log (the latest)(https://github.com/pizzaboxer/bloxstrap/files/14528164/Bloxstrap_20240307T175153Z.log)

**Comment by ShadowCodeX-debug** [comment]
The first log file provided had something that could be related: "2024-03-07T17:00:56Z [Bootstrapper::ApplyModifications] Roblox is running, aborting mod check"

**Comment by AngryBirdsFanboy06** [comment]
Update: I decided to check the recent log and I think its working again.
I think the main issue was somehow, Roblox was running, my guess its probably something with the desktop app being the cause, since after manually putting the disable desktop app rblx file to the version and launching Roblox, Bloxstrap automatically started to put my mods and fastflags into it.
[Bloxstrap_20240307T181931Z.log](https://github.com/pizzaboxer/bloxstrap/files/14528398/Bloxstrap_20240307T181931Z.log)
