### ISSUE TITLE
[ASK] how to free cam?

### ISSUE THREAD

**Issue by NajmiDhiyaAlfath** [pizzaboxer/bloxstrap#1410]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

idk how to free cam
![image](https://github.com/pizzaboxer/bloxstrap/assets/161578538/6f439b37-3e88-45db-ad98-ce610ac74e40)
This came out of nowhere but doing the SHIFT + P does not work

**Comment by pizzaboxer** [comment]
The freecam option won't work, just ignore it.

**Comment by NajmiDhiyaAlfath** [comment]
Is the others apart of bloxstrap?
![image](https://github.com/pizzaboxer/bloxstrap/assets/161578538/1f03dea1-abb5-4d9e-89f7-693536290d95)

**Comment by pizzaboxer** [comment]
They come from you enabling this option.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/0242df43-687f-4722-9a04-c417c4f5c35e)

**Comment by hugu121012** [comment]
> The freecam option isn't supposed to work, just ignore it.

Can u make an freecam option ?

**Comment by Nam-Logic** [comment]
@NajmiDhiyaAlfath 

Only work your own creation (no need Shift + P)

I'm playing Blox Fruits try turn on Freecam but nothing happend

 <img width="513" height="61" alt="Image" src="https://github.com/user-attachments/assets/3d07460d-c477-4ff4-ac5a-679a8da50adf" />

**Comment by hugu1210122** [comment]
Ok thanks
