### ISSUE TITLE
Client is lagging out averaging 500 ping ms

### ISSUE THREAD

**Issue by u9er** [pizzaboxer/bloxstrap#1411]
I tested the internet and everything, It works well, But the client is lagging out badly, I've updated to the latest version Bloxstrap.

**Comment by u9er** [comment]
ive tried unistalling it and resinstalling it lastly updating to the latest version of windows 11

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this occur only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by u9er** [comment]
Ive done that and fixed the issue, it does not occur with bloxstrap. it does it with other games
