### ISSUE TITLE
[BUG] Lighting is broken and i can't see any light working.

### ISSUE THREAD

**Issue by Amyskunky** [pizzaboxer/bloxstrap#1413]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

What happens is that the game lighting won't work and, I cannot see in dark maps that have lighting.

**Comment by pizzaboxer** [comment]
Set your lighting technology to "Chosen by game". You should've read the information we told you to read before you started using Bloxstrap. https://github.com/pizzaboxer/bloxstrap/wiki/Addressing-usability-problems-with-Bloxstrap-v2.5.4

**Comment by tazifyy13** [comment]
Hello, in some games some lights are not visible. For example, what happens to me is that when I do a skill in a Roblox game, a red dot should appear on the players through the walls and it does not appear even though to set my lighting to chosen by game help pls

**Comment by Migonnes** [comment]
> Set your lighting technology to "Chosen by game". You should've read the information we told you to read before you started using Bloxstrap. https://github.com/pizzaboxer/bloxstrap/wiki/Addressing-usability-problems-with-Bloxstrap-v2.5.4

i have the same problem, tried this but didn't work
