### ISSUE TITLE
White screen when i open bloxstrap [BUG] 

### ISSUE THREAD

**Issue by Binguscatt** [pizzaboxer/bloxstrap#1414]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I downloaded bloxstrap and put everything how i wanted it to be and didn't touch the fast flag tab. But every time I open it it's just a white screen.

**Comment by pizzaboxer** [comment]
> But every time I open it it's just a white screen.

Can you show a screenshot please?

**Comment by Binguscatt** [comment]
Its all good now I just had to uninstall and reinstall
