### ISSUE TITLE
[BUG] it says "System.IO.IOException: The response ended prematurely, with at least 472592 additional bytes expected." when i try to install roblox

### ISSUE THREAD

**Issue by fork0101** [pizzaboxer/bloxstrap#1415]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[BUG] it says "System.IO.IOException: The response ended prematurely, with at least 472592 additional bytes expected." when i try to install roblox
![Ekran görüntüsü 2024-03-08 215858](https://github.com/pizzaboxer/bloxstrap/assets/162743089/a3efc353-10a0-4b94-9882-117093a37aaf)

**Comment by bluepilledgreat** [comment]
Do you have enough space to install Roblox?

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by fork0101** [comment]
> Do you have enough space to install Roblox?

Ye

**Comment by fork0101** [comment]
> Can you send the log file please?

What is a log file? Sorry i don't know

**Comment by pizzaboxer** [comment]
Click on the button that says "locate log file", and upload the file that is highlighted in the file explorer.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
