### ISSUE TITLE
[BUG] says: An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Boriso6** [pizzaboxer/bloxstrap#1416]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm not a computer expert, but it says something like:

=================================================================

An exception occurred while running Bloxstrap:

System.IO.FileNotFoundException: Could not find file '

C:\Users\thename\AppData\Local\Temp\scoped_dir11340_2126875606\Bloxstrap-v2.5.4.exe'.
   *i writed (thename) cuz its my real name*

=================================================================

![image_2024-03-08_225408514](https://github.com/pizzaboxer/bloxstrap/assets/151875684/a2c21f41-1aaf-45e3-a3df-6099d51ff32d)

**Comment by pizzaboxer** [comment]
Download it first and then run it instead of running it directly from your browser.
