### ISSUE TITLE
[BUG] System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by ultr1GOD** [pizzaboxer/bloxstrap#1417]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i trie using bloxtrap i have used before but it it says this System.Exception: Signature does not match! wile upgrading roblox

**Comment by ultr1GOD** [comment]
you know how to fix it?

**Comment by pizzaboxer** [comment]
Please read the preliminary instructions before you open an issue. https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
