### ISSUE TITLE
death sound not changing[BUG] 

### ISSUE THREAD

**Issue by Freddyfast** [pizzaboxer/bloxstrap#1418]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i have the setting set so it uses the oof death sound, but it just plays the offical death sound effect, can someone help me?

**Comment by pizzaboxer** [comment]
See sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter, and let me know if it helps with your issue.
