### ISSUE TITLE
[BUG] BLOX STRAP SAYING STARTING ROBLOX BUT MIDWAY CLOSES IT APPEARS IN TH EBACKGROUND PROCCESS

### ISSUE THREAD

**Issue by monkeyboyquan** [pizzaboxer/bloxstrap#1419]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/160008264/f6769a67-b19e-4286-b56f-b4c1ab91bc11)
 It quits midway heres my proof none of the solutions work please help 
 

https://github.com/pizzaboxer/bloxstrap/assets/160008264/b6bb1c5a-20ee-4055-8800-7ccb0dc11b7a

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by monkeyboyquan** [comment]
no,even roblox.player isn't opening.

**Comment by pizzaboxer** [comment]
This isn't a problem with Bloxstrap then. Read the information given in https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch for further help.
