### ISSUE TITLE
[BUG] Indefinite White Screen in Roblox

### ISSUE THREAD

**Issue by Neon4UltraPlays** [pizzaboxer/bloxstrap#1420]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/90380800/7189194b-148a-46f0-98bf-39ff5ca47315)
Hello Bloxstrap, I had this issue since May last year, and it still bugs me.
I cannot play Roblox on my PC because this white screen always covers the normal bootstrapper. When I used Bloxstrap, I was expecting not to see a white screen, but still, the program froze in just a white screen.

Please fix this error in my computer, and give recommendations.

Thank you!

**Comment by pizzaboxer** [comment]
> this white screen always covers the normal bootstrapper

This is an issue with Roblox itself then, I can't really help you here. Sorry.

**Comment by sqrona** [comment]
mine does this too why wont it work im angry

**Comment by DaGenericUser** [comment]
I've suddenly had this happen to me but it's literally only bloxstrap that's doing this.
