### ISSUE TITLE
the fps unlocker is not working for me [BUG] 

### ISSUE THREAD

**Issue by skullaf** [pizzaboxer/bloxstrap#1421]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i used to have between 500 - 200 but now i have between 65 to 30 even though my fps limit is 9999 which is unlimited, i uninstalled bloxtrap and roblox player to 3 times now and its still now working and its kinda unplayable and annoying now

**Comment by pizzaboxer** [comment]
You've read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter, right?

**Comment by skullaf** [comment]
> You've read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter, right?

i read it right now and none of the solutions work the fps unlocker is not capped for me, but it is lower as i said it used to be 500 to 200 and now between 80-30 and i didnt change none of the settings in bloxtrap or either roblox the graphics settings are the same and im pretty sure its not a problem in my pc.

**Comment by kuromian** [comment]
I have had it recently too, it might be an affect from that "fflag" update

**Comment by skullaf** [comment]
> I have had it recently too, it might be an affect from that "fflag" update although roblox account manager seems to be fine so it might be the settings you're using, don't know which one though will tell you

i changed the fps unlocker limit to 360 and its still not working. what exactly did you do to fix the issue.

**Comment by skullaf** [comment]
the problem is fixed by seeing the task manager it is not bloxtraps problem
