### ISSUE TITLE
[FIXED]  FPS gets capped to 60 when in Fullscreen

### ISSUE THREAD

**Issue by Mutagg** [pizzaboxer/bloxstrap#1423]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### Adrenaline was capping the FPS to 60

FPS gets capped to 60 when in Fullscreen. When losing focus or running in the background it uncaps itself and gets above 60. It is not "Exclusive Fullscreen". Framerate limit is set to 170. FastFlags used are in the picture (Doing Vulkan, because I want Roblox to fully utilise my AMD GPU) (Max buffer size is self explanatory) (MSAA to 16 because typical Roblox sharpening is ass) (GameBasicSettingsFramerateCap because im trying to fix this issue). This has happened today. Yesterday it was working fine. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/67800988/3b4a6483-2aaf-413a-9c0b-b4e0dd0662a8)
![image](https://github.com/pizzaboxer/bloxstrap/assets/67800988/56162fd8-23bd-4f42-9e86-026902777169)
https://streamable.com/yegh4i <- see the issue

**Comment by pizzaboxer** [comment]
Resolved on Discord
