### ISSUE TITLE
[BUG] Attempted to teleport to a place that is restricted. Error code 773

### ISSUE THREAD

**Issue by FTMteam** [pizzaboxer/bloxstrap#1424]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This only occurs with multiple instances launching . I was playing bedwars which has a party system and I invited both my alt and my main and started to queue into the restricted / private place . But only ONE account teleported 
![image](https://github.com/pizzaboxer/bloxstrap/assets/65016158/4756c277-39d9-470d-af98-2daec8f89604)
I launched both accounts from roblox.com through a public server.

**Comment by FTMteam** [comment]
Friends of mine has this worked , i don't really know is it I have a specific setting on or my specific pc

**Comment by pizzaboxer** [comment]
This is something to be expected if you're using multiple instances. There's no way that I know of to get around this, sorry.
