### ISSUE TITLE
[BUG] How can i use low-polu mode or no textures with bloxstrap?

### ISSUE THREAD

**Issue by asterouss** [pizzaboxer/bloxstrap#1425]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

title

**Comment by ShadowCodeX-debug** [comment]
No Textures:
```json
{
  "MSRefactor5": false,
  "FStringPartTexturePackTablePre2022": "{\"glass\":{\"color\":[254,254,254,7]}}",
  "FStringPartTexturePackTable2022": "{\"glass\":{\"color\":[254,254,254,7]}}"
}
```

**Comment by pizzaboxer** [comment]
See this, this may be of interest. 

https://github.com/GoingCrazyDude/fastflags-collection/blob/main/README.md

You use these by using Bloxstrap's "Import JSON" utility in the flag editor.
