### ISSUE TITLE
[BUG] The launcher takes too long to close along with the roblox tab, doesn't matter if i'm laggy or not

### ISSUE THREAD

**Issue by Trulyamoment** [pizzaboxer/bloxstrap#1426]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I close the tab, it doesn't close until 1-2 minutes after, I also tried older versions of Bloxstrap but same issue.
When i finish the task in task manager it still doesn't close, even if I finish Bloxstrap itself.
The tab stays open as well which is what annoys me mostly.
Only happens after loading the game fully apparently.
The consuming Roblox does after closing it or finishing the task caps at 123 mb with 10% of CPU usage

**Comment by pizzaboxer** [comment]
What do you mean by "close the tab"?

**Comment by Trulyamoment** [comment]
The tab where you play roblox on, which would be the bloxstrap launcher

**Comment by pizzaboxer** [comment]
You're saying that Roblox still stays open for a few minutes even after trying to close it. Follow this, please:

https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
