### ISSUE TITLE
[BUG] Roblox not saving my settings.

### ISSUE THREAD

**Issue by Anchovy1000** [pizzaboxer/bloxstrap#1427]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime I enter a game I have to go to roblox settings and enable shiftlock,reduce volume etc. I tried it with the normal roblox launcher and it was working fine.

**Comment by pizzaboxer** [comment]
Have you enabled the option to disable the desktop app in the Bloxstrap Menu?

**Comment by Anchovy1000** [comment]
> Have you enabled the option to disable the desktop app in the Bloxstrap Menu?

Yes I have

**Comment by pizzaboxer** [comment]
That's why. This is a known issue with the option. You may want to disable the option if this is causing too much problems for you.

Duplicate of #1175
