### ISSUE TITLE
No Menu

### ISSUE THREAD

**Issue by Flaxxi** [pizzaboxer/bloxstrap#1428]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I run Bloxstrap, It opens Roblox but not the menu and when I look at tutos the menu starts when they run Bloxstrap.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

Read the preliminary instructions before you open an issue next time. You were also told about this when you first installed it.
