### ISSUE TITLE
how can i uninstall the program

### ISSUE THREAD

**Issue by riot33k** [pizzaboxer/bloxstrap#143]
i cant find any setting to uninstall the program, how can i fully uninstall bloxstrap?

**Comment by KaneDbD** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Uninstalling-Bloxstrap

**Comment by pizzaboxer** [comment]
You uninstall it the same way you uninstall any other program on your computer.

**Comment by riot33k** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Uninstalling-Bloxstrap

thanks a bunch
