### ISSUE TITLE
[BUG] Bloxstrap lags horribly when played from Roblox website.

### ISSUE THREAD

**Issue by AXCWZ** [pizzaboxer/bloxstrap#1430]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When played from the Roblox website, the game will lag a lot, but when played from the desktop app, it runs smoothly.

**Comment by pizzaboxer** [comment]
You're launching the desktop app with the "Play Roblox" shortcut, right? There's no reason for there to be any difference between the two unless you're launching two different things.

**Comment by AXCWZ** [comment]
https://youtu.be/N8_SovVc1gQ?si=dUkWe2tqUlYhbkNb

**Comment by pizzaboxer** [comment]
Have you checked to confirm that this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by AXCWZ** [comment]
I've tested just now, it happens with Roblox too. I need to figure out a way to fix that. Thanks for the help!
