### ISSUE TITLE
[REQ] Option to toggle quiet mode

### ISSUE THREAD

**Issue by 1x4z** [pizzaboxer/bloxstrap#1432]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

-quiet is cool, I want to launch with it on the website

https://github.com/pizzaboxer/bloxstrap/assets/159259392/4e79af8b-2913-4ba2-a714-23965917e040

**Comment by pizzaboxer** [comment]
> I want to launch with it on the website

I would want to, but I can only imagine the amount of confusion this would cause for most people if I added this as a feature. I'll offer a solution just for you though:

Open the Registry Editor, go to `HKEY_CURRENT_USER\SOFTWARE\Classes\roblox\`, go to `shell\open\command\`, change the (Default) value from `[...]Bloxstrap.exe" %1` to `[...]Bloxstrap.exe" -quiet %1`. Do the same for `HKEY_CURRENT_USER\SOFTWARE\Classes\roblox-player\`. You can easily change this back if you want to.
