### ISSUE TITLE
[BUG] Cursor

### ISSUE THREAD

**Issue by chrisswat78** [pizzaboxer/bloxstrap#1434]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I chose the Angular 2013 cursor, i saved it and reloaded Roblox and it just doesn't show up? its only the regular default version of it and not the one i chose for. Could u fix this by any chance?

**Comment by pizzaboxer** [comment]
See sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter, it should solve your issue.
