### ISSUE TITLE
[BUG] Roblox Crash.

### ISSUE THREAD

**Issue by LutyOficial** [pizzaboxer/bloxstrap#1435]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i opened "Play Roblox" after Opening it said Was Crashed,i did the process mutiple times but still Crashes.

**Comment by DoILookLikeAJokeToYou** [comment]
Hi

**Comment by pizzaboxer** [comment]
Have you confirmed that this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by LutyOficial** [comment]
Yes

**Comment by Swordanimates** [comment]
Hey, my game client crashed too! This one a different one. When i ran Roblox with the Bloxstrap FastFlags, it would just crsh my game client, but if i removed the fastflags it didn't crashed. Maybe the fastflags were on ClientSettings file i guess. Roblox updated, i think they tried stopping people putting clientsettings on the client, I got this information from this trusted youtuber. Who exactly makes a bit of a mistake, saying that Roblox itself is adding it's own settings like "FPS Limit" or anything else for a boost. But it was slowly rolling down to people, none of us gets it. Can you fix this issue, and give me or anyone else who had the same problem fastflags work?

**Comment by LutyOficial** [comment]
I think its the exactly Problem i have

**Comment by pizzaboxer** [comment]
> Yes

Upload your configuration please. https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
> Can you fix this issue, and give me or anyone else who had the same problem fastflags work?

Read the warning at the top of https://github.com/pizzaboxer/bloxstrap/wiki/a-guide-to-FastFlags please.
