### ISSUE TITLE
Issue with inistallation, then once inistalled it doesnt even open roblox

### ISSUE THREAD

**Issue by MonkeAxel** [pizzaboxer/bloxstrap#1436]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\Administrator\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

[Bloxstrap_20240312T081911Z.log](https://github.com/pizzaboxer/bloxstrap/files/14569367/Bloxstrap_20240312T081911Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

Read the preliminary instructions before you open an issue please.
