### ISSUE TITLE
[BUG] multi instance

### ISSUE THREAD

**Issue by 54bodys** [pizzaboxer/bloxstrap#1439]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

the allow multi-instance is on however it just says "an error encountered during authentication. please try again"
![Screenshot 2024-03-13 163226](https://github.com/pizzaboxer/bloxstrap/assets/146805886/1a50d71f-831f-4b93-a29f-c176bea2a29e)
![Screenshot 2024-03-13 163416](https://github.com/pizzaboxer/bloxstrap/assets/146805886/693ee3a0-72ed-4a81-8dee-26ea9aa60043)

**Comment by pizzaboxer** [comment]
You'll need to do your account switching inside the desktop app instead of doing it on the website. Launch the desktop app, then switch accounts. then join your game.
