### ISSUE TITLE
Unable to use RoShade while using Bloxstrap

### ISSUE THREAD

**Issue by s3ussy** [pizzaboxer/bloxstrap#144]
So, I want to use Roshade instead of Reshade since Roshade has some stuff Reshade doesn't have, but everytime I try to install Roshade while bloxstrap is installed, it won't let me use it.

**Comment by pizzaboxer** [comment]
If you really want to use Roshade, you need to change Bloxstrap's install location from `<UserProfileFolder>\AppData\Local\Bloxstrap` to `<UserProfileFolder>\AppData\Local\Roblox` for it to be picked up by the Roshade installer. Keep in mind that uninstalling Bloxstrap would require reinstalling both player and studio.
