### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DRAGAYUSH** [pizzaboxer/bloxstrap#1440]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The process cannot access the file 'C:\Users\USER\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.)

[Inner Exception]
System.IO.IOException: The process cannot access the file 'C:\Users\USER\AppData\Local\Bloxstrap\Versions\version-97058ca6653344cd\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.
![image_2024-03-13_133742127](https://github.com/pizzaboxer/bloxstrap/assets/123809728/5cfbe16f-5936-49c3-a30e-0f6302dd9fb3)

**Comment by pizzaboxer** [comment]
Known bug, make sure Roblox is closed first before you try changing your font.

**Comment by Coderpawn** [comment]
I have the same issue, and I have ensured roblox is closed before changing fonts. The weird part for me is that this issue ONLY occurs when i attempt to open more than 4 instances of roblox.

**Comment by pizzaboxer** [comment]
The next time you get this error, send the log file and I'll take a closer look.
