### ISSUE TITLE
[BUG]  

### ISSUE THREAD

**Issue by yams2fly** [pizzaboxer/bloxstrap#1441]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im tryna install bloxstrap the menu is not showing up or that exe not running even tho i opened it a few times tried restarting my pc still the same

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
