### ISSUE TITLE
[BUG] whenever i open bloxstrap it just shows me a white screen

### ISSUE THREAD

**Issue by spadez123** [pizzaboxer/bloxstrap#1442]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

whenever i open bloxstrap it just shows me a white screen

**Comment by spadez123** [comment]
this is what i see

**Comment by spadez123** [comment]
![Screenshot 2023-09-23 173307](https://github.com/pizzaboxer/bloxstrap/assets/163327084/84cf0c44-ef1c-40c8-8932-114c94be83c8)

**Comment by spadez123** [comment]
![Screenshot 2024-03-13 194429](https://github.com/pizzaboxer/bloxstrap/assets/163327084/2e0bc7bd-8742-4054-86b8-5082d28d866b)

**Comment by spadez123** [comment]
i deleted and installed a fresh verison and it still does the same

**Comment by spadez123** [comment]
and the latest one

**Comment by spadez123** [comment]
bloxstrap

**Comment by pizzaboxer** [comment]
> it works fine on roblox but on bloxstrap its just a white screen

No, I mean what window does this show under? Show a screenshot like I asked.

**Comment by limmyz** [comment]
So basically everytime that I add a mod or change anything on bloxstrap, my ROBLOX gets stuck on a white screen after launch.

**Comment by pizzaboxer** [comment]
Apologies for not responding, I must've missed you since you're not the OP.

>  So basically everytime that I add a mod or change anything on bloxstrap, my ROBLOX gets stuck on a white screen after launch.

Just to clarify, it works all fine on default settings, right?

**Comment by limmyz** [comment]
Yeah, but now i just realized it only goes in the white screen when i add a custom font. everything else works fine

**Comment by pizzaboxer** [comment]
> Yeah, but now i just realized it only goes in the white screen when i add a custom font. everything else works fine

Was this happening with any font you tried? Give an example of one you tried to use.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

@limmyz You're free to follow up if you still want to.

**Comment by limmyz** [comment]
yup, it happened with any font. i also asked my friend for the font that he used and it didn't work either
