### ISSUE TITLE
Appdata removal

### ISSUE THREAD

**Issue by ysha10** [pizzaboxer/bloxstrap#1443]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello.
There's problem with Bloxstrap.
If you remove entire appdata on Bloxstrap, you **cannot** delete entire Bloxstrap program in Control Panel.

**Comment by ShadowCodeX-debug** [comment]
If the bloxstrap folder gets deleted then Bloxstrap isn’t an application on your system anymore. Pretty sure if you delete it then control panel will mention that it’s no longer there and asks to remove it from control panel.

**Comment by ysha10** [comment]
However, if you re-install Bloxstrap back, the Bloxstrap won't show on Control panel's Program and Components.

**Comment by ysha10** [comment]
That's why you need an button to actually uninstall Bloxstrap to fix the issue.
Once it is resolved, this issue will be closed, marked assolved.

**Comment by pizzaboxer** [comment]
>  If you remove entire appdata on Bloxstrap, you cannot delete entire Bloxstrap program in Control Panel.

...Yes? How will Bloxstrap uninstall itself if it doesn't exist anymore? Why are you even deleting it from AppData? We don't tell you to do that anywhere.

> However, if you re-install Bloxstrap back, the Bloxstrap won't show on Control panel's Program and Components.

It should reregister itself after a Roblox launch.
