### ISSUE TITLE
[BUG] No Bloxstrap Menu

### ISSUE THREAD

**Issue by Salkaiju** [pizzaboxer/bloxstrap#1446]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I downloaded bloxtrap and searched for the menu, it does not exist, i tried reinstalling and still does not appear to me.
![imagem_2024-03-14_120447025](https://github.com/pizzaboxer/bloxstrap/assets/116319547/6ad6eaf1-be7e-4287-8fb5-fb505f1b2da8) i don't know if i downloaded it incorrectly or something.

**Comment by Salkaiju** [comment]
Noticed something, i can open the menu if i go to configurations, then apps and search for bloxstrap then i click on modify, it will open the menu which kinda resolves my problem but there is no menu app tho

**Comment by Salkaiju** [comment]
![imagem_2024-03-14_121439164](https://github.com/pizzaboxer/bloxstrap/assets/116319547/9be15796-f837-43b9-b5a8-2a18eea3e982)
there, if i click modify on app configurations of my pc, i can open it, thats enough for now so i'll leave for now and come back later to see if someone clarified my situation, see ya.

**Comment by pizzaboxer** [comment]
Try looking for it in the Start menu yourself instead of searching for it.
