### ISSUE TITLE
[BUG] Multiple accounts not working properly

### ISSUE THREAD

**Issue by Albinftw** [pizzaboxer/bloxstrap#1448]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hey so i recently notised that whenever i attempt to yous the multiple accounts feature theres a bit of a bug. So basically i boot up the first account and join perfectly fine. Second account however says upgrading roblox when i boot it up so when it finishes it shutsdown the first instance of roblox. So i rejoined on the first account. But then the original roblox update meny came up without any of the bloxstrap features. I restarted my computer and the problem is still there i'll send log files you you want

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Using-multiple-instances-always-forces-a-Roblox-upgrade

Read the preliminary instructions before ticking the checkbox.
