### ISSUE TITLE
[BUG] This infinite update after 10 mins of an update

### ISSUE THREAD

**Issue by NotLotfi** [pizzaboxer/bloxstrap#1449]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I had this issues from like a month and it's still going. But now i also got an error here

https://github.com/pizzaboxer/bloxstrap/assets/163540023/2debb6e8-f1a7-4991-9c80-45349a39d6af

**Comment by pizzaboxer** [comment]
Did you read through https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox?

**Comment by NotLotfi** [comment]
but what about this log file?

**Comment by NotLotfi** [comment]
[Bloxstrap_20240319T122825Z.log](https://github.com/pizzaboxer/bloxstrap/files/14650508/Bloxstrap_20240319T122825Z.log)

**Comment by pizzaboxer** [comment]
The error relates to the same issue.
