### ISSUE TITLE
New Byfron Client Causes Issues

### ISSUE THREAD

**Issue by KyjiPaws** [pizzaboxer/bloxstrap#145]
The new Byfron client, somewhat expectedly, causes quite a few issues:
- Reshade support seems to be broken.
- `F11` and `Alt + Enter` no longer function in exclusive fullscreen. (Also noticing horrible screen tearing that wasn't happening before.)
- Probably more; haven't looked much.

This link *should* prompt Roblox to install the new client: (You have to paste it into the address bar manually.)
**`roblox-player:1+launchmode:app+channel:zwinplayer64`**

I'm expecting Reshade support to just be removed, seeing as the new client's purpose is to *prevent* it from working.

**Comment by pizzaboxer** [comment]
I already addressed these problems in v2.2.0. I'm the person who first discovered these problems. ZWinPlayer64 is a selectable channel in the Installation menu. Having ReShade enabled forces you to use the non-Byfron client.

**Comment by pizzaboxer** [comment]
I just checked and exclusive fullscreen still works fine, Alt+Tabbing to another window makes it exit fullscreen as expected.
