### ISSUE TITLE
Bloxstrap not changing UI

### ISSUE THREAD

**Issue by FifteenMC** [pizzaboxer/bloxstrap#1453]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Before Roblox added the new, unnecessary big, UI, Bloxstrap started to show that one, instead of the 2015 one which I was using before this update. Something weird is that it works on other browsers like Google and Microsoft Edge, but since last week it stopped working on Brave browser for some reason. How can I fix this without changing browsers? (I don't change mainly because I have extensions and I'm used to Brave)

**Comment by pizzaboxer** [comment]
Do you see the Bloxstrap launcher show before Roblox launches?

**Comment by FifteenMC** [comment]
Yes, it does show up. It was working perfectly fine before the big UI update, after that it stopped working.
As I said, I can see the 2015 UI if I play in Chrome or Microsoft browsers, but not Brave anymore

**Comment by FifteenMC** [comment]
Just noticed something. I played on my alt in Brave browser and for some reason I had the 2015 UI. But when I'm not in my main it doesn't work. What's going on...?

**Comment by pizzaboxer** [comment]
> But when I'm not in my main it doesn't work.

Oh, you're on different accounts. See these two Wiki pages:

https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
https://github.com/pizzaboxer/bloxstrap/wiki/Using-multiple-instances-always-forces-a-Roblox-upgrade

**Comment by FifteenMC** [comment]
It worked! Thank you so much!
