### ISSUE TITLE
[BUG] old textures not working

### ISSUE THREAD

**Issue by mehczz** [pizzaboxer/bloxstrap#1454]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i turn on old roblox textures it doesnt work

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
