### ISSUE TITLE
[BUG]  Roblox "Error 403 Authentication Error" on playing using website, and app crashing when logging in.

### ISSUE THREAD

**Issue by powderedd** [pizzaboxer/bloxstrap#1455]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I can't test this without bloxstrap, as roblox installer crashes without it
I have windowblinds installed and idk if that is the issue (If i uninstall it my lisence crack will break)
When i open from website, it error 403s
When i login from app, it crashes as soon as the 2factor auth screen shows, might be a webview issue

**Comment by powderedd** [comment]
nevermind? i managed to login via quick login, but it still only launches roblox 50% of the time

**Comment by powderedd** [comment]
Roblox still crashes at any webview page. i tried to open the server browser and it crashed

**Comment by pizzaboxer** [comment]
Do you actually have WebView installed? Search for it in your app list, see if it comes up.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/974e13e9-cd18-44e8-8b9e-1045ea215dcd)

**Comment by powderedd** [comment]
yep
![image](https://github.com/pizzaboxer/bloxstrap/assets/87124834/80680766-4926-456a-a2e8-7bc6575bb923)

**Comment by pizzaboxer** [comment]
Actually, I forgot to ask you if you're able to use WebView through the standard launcher, so go try that out: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by powderedd** [comment]
there is no roblox player. i cant download the standared launcher as robloxlauncher does not download and crashes halfway thru

**Comment by syxgio** [comment]
> there is no roblox player. i cant download the standared launcher as robloxlauncher does not download and crashes halfway thru

Can you access https://clientsettingscdn.roblox.com ? I'm having the same issue and the reason is because ROBLOX can't fetch "critical settings" for the client with that domain, and I require a VPN for launching the client since yesterday. I also can't redownload the client via RobloxPlayerInstaller, because it never starts downloading the client just like in your case.

**Comment by pizzaboxer** [comment]
> i cant download the standared launcher as robloxlauncher does not download and crashes halfway thru

Oh right, you did mention that.

What if you go into the Bloxstrap Menu, go to the Behaviour tab, and enable the "Force Roblox Reinstallation" option?

**Comment by pizzaboxer** [comment]
> doesnt work

Reinstall the WebView2 runtime as described here: https://github.com/pizzaboxer/bloxstrap/issues/635#issuecomment-2011668696
