### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Videogame-Oscar** [pizzaboxer/bloxstrap#1457]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\Oscar\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

Read the preliminary instructions before you say that you've acknowledged them.
