### ISSUE TITLE
[BUG] Error code 773 : attempted to teleport to a place that is restricted

### ISSUE THREAD

**Issue by UnixRoblox** [pizzaboxer/bloxstrap#1459]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I discovered the multi account feature in bloxtrap, it works good when the accounts are joining but when i invite them to a place it says its restricted, any fix on this????

**Comment by pizzaboxer** [comment]
> any fix on this????

If you're launching from the Roblox website, there isn't really much we can do to fix this. You may have better luck using [Roblox Account Manager](https://github.com/ic3w0lf22/Roblox-Account-Manager).
