### ISSUE TITLE
ReShade Update button

### ISSUE THREAD

**Issue by skjdjed** [pizzaboxer/bloxstrap#146]
It may be useful to add ReShade updating button instead of reinstalling it over and over again (because of low github speed) 
I've tried downloading ReShade installer from thier web and browse to the Bloxstrap Roblox versions folder,well.. Installer said it's updated but in game it still says that the version is outdated

**Comment by pizzaboxer** [comment]
We handle updating on our end. You don't have to worry about it. I'm in the process of having it updated, it just hasn't been updated it yet.

**Comment by Extravi** [comment]
updated
