### ISSUE TITLE
[BUG] I've installed Bloxstrap many times but I still don't see it.

### ISSUE THREAD

**Issue by QuickUser343** [pizzaboxer/bloxstrap#1460]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have installed it many times, but I sitll don't see it in my apps.

**Comment by pizzaboxer** [comment]
> but I sitll don't see it in my apps.

Are you looking in the Start menu? If you're searching for it, look for it in the list yourself, and it should be there.

**Comment by QuickUser343** [comment]
I did that but it still didn't work. But I found the problem, I wasen't
installing the newest version, and I installed the newest version and it
worked and I have it now. Thank you though.
