### ISSUE TITLE
[BUG] UI Hiding not working

### ISSUE THREAD

**Issue by Pieplup** [pizzaboxer/bloxstrap#1461]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

UI Hide does not work ( I am in the group)

**Comment by pizzaboxer** [comment]
If you open up the escape menu and scroll to the bottom, do you see toggles for GUI hiding?

**Comment by Pieplup** [comment]
> If you open up the escape menu and scroll to the bottom, do you see toggles for GUI hiding?

no

**Comment by Pieplup** [comment]
It's working nwo fr some reason not sure why
