### ISSUE TITLE
[BUG] Ansel

### ISSUE THREAD

**Issue by fffdsfdsfds** [pizzaboxer/bloxstrap#1462]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I followed everything i could, and theres 2 problems.
1, the only thing i see when i open up  game filter is a frozen image sharpening bar that i cant move
2. I have no idea how to change the installation name for bloxstrap. it keeps creating new .exe files when i rename it to "eurotrucks2"

**Comment by pizzaboxer** [comment]
We don't yet have support for Nvidia Ansel. I recommend that you check out [Bloxshade](https://bloxshade.com) for the time being.
