### ISSUE TITLE
[BUG] Completely new error (for me)

### ISSUE THREAD

**Issue by 948347893875338** [pizzaboxer/bloxstrap#1463]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Byfron has caught up.
Whenever i launch roblox via bloxstrap i get this error [shown in the image]
![image](https://github.com/pizzaboxer/bloxstrap/assets/121643321/b4ff6707-24a8-4e90-bb61-2bce921c10cc)

**Comment by pizzaboxer** [comment]
Have you confirmed that this happens only when launching with Bloxstrap? Also, upload your config please. https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by 948347893875338** [comment]
im gonna fuckin kill roblox
apparently now its fine
