### ISSUE TITLE
[BUG] In-Game menu stays standard even if you change its FastFlags to true

### ISSUE THREAD

**Issue by randwn** [pizzaboxer/bloxstrap#1464]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The new chrome UI does not show up if I enable it. Did they change the names? Because the other flags work.
![Screenshot 2024-03-18 150913](https://github.com/pizzaboxer/bloxstrap/assets/103916699/d5d94d0c-3cb4-43de-8e17-351169b9990b)
![Screenshot 2024-03-18 152233](https://github.com/pizzaboxer/bloxstrap/assets/103916699/54f45bd3-71b5-4e53-8c26-140bd2bd93d4)

**Comment by pizzaboxer** [comment]
You're only enabling the A/B test flags. Did you actually set the definitive "FFlagEnableInGameMenuChrome" flag?

**Comment by randwn** [comment]
Oh I haven't, I enabled it and it now shows the new UI. Didn't know this flag existed. Thanks
