### ISSUE TITLE
[BUG] Character freezing when you reset

### ISSUE THREAD

**Issue by Tomcar99** [pizzaboxer/bloxstrap#1465]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I am having a problem. Every time I reset my character, my character is unable to move. Only thing I can do is jump.

**Comment by pizzaboxer** [comment]
Have you confirmed that this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Tomcar99** [comment]
I have confirmed it's bloxstrap

**Comment by pizzaboxer** [comment]
Upload your flag configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

You only need to upload ClientAppSettings.json.
