### ISSUE TITLE
[BUG] Roblox Game Client just hanging in the background

### ISSUE THREAD

**Issue by auugashhgsyfusgs** [pizzaboxer/bloxstrap#1466]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/160515478/d8d4b596-e08b-4be2-96b8-e6a75cae1484)

after "starting roblox" it just disappears and makes a background process, i also do not have any windows insider builds or even in it. the normal roblox launcher works completely normal besides the bloxstrap one.

**Comment by pizzaboxer** [comment]
Do this please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
