### ISSUE TITLE
[BUG] .net saying i need to install .net runtime when its installed

### ISSUE THREAD

**Issue by zursware** [pizzaboxer/bloxstrap#1467]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i had to do a restore on my windows by like 50 mins and when i tried to use bloxstrap it gave me the runtime error i tried uninstalling the runtime,and bloxstrap and reinstalling it never worked i need a fix
![error](https://github.com/pizzaboxer/bloxstrap/assets/158216184/a7bd2556-09e7-4e79-8f8d-0f3d65f50a34)

and when i click yes nothing happens either.

**Comment by pizzaboxer** [comment]
To confirm that you have it installed, open a Command Prompt window, and run this command:

`dotnet --info`

Show a screenshot of what you see.

**Comment by zursware** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/158216184/6325c750-164c-4e9a-a59a-14341fe7eb6b)

ok i was missing a .dll i installed it and put it into the folder it was missing from but same error this is what happens when i do the cmd again. 

![image](https://github.com/pizzaboxer/bloxstrap/assets/158216184/eaa73a97-5c57-44ac-9b9a-a331c8c7e1e5)

**Comment by zursware** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/158216184/7eb07597-7f25-4c49-b695-96563ded1d89)

when i click yes it does direct me to the site now tho

**Comment by zursware** [comment]
I fixed it by deleting the "dotnet" folder in my "programfiles" and reinstalling the version it asked me to install
