### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by regiemarksanchez** [pizzaboxer/bloxstrap#1468]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I played DBZFS on ROBLOX it's working but when i queue my 2 Accounts to a Private place or Server like other World like TOP or Tournament Of Power and BROLY the Dimensional Rift, Only 1 of my Account can enter of that Server then the error appears the Attempting to teleport to a private server ERROR CODE: 773, Please fix like this.

**Comment by DovydasTEDS** [comment]
Clone of #1424
Please read closed and open issues before opening an issue.
