### ISSUE TITLE
[REQ] Add the option to change from DirectX 11 to Vulkan

### ISSUE THREAD

**Issue by ShadowLite1** [pizzaboxer/bloxstrap#1469]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

DirectX 11 just sucks on Roblox because it doesn't do any good for hardware and the ability to switch to Vulkan could work so much better and easier for everyone.

**Comment by TheMetalTechnet** [comment]
1. You can always add Vulkan FFlag manually
2. Vulkan triggers Hyperion for like 96% of people
3. Roblox implemented Vulkan to be a render that's used on mobile, because of that they don't update Vulkan on PC which causes the previously mentioned Hyperion triggering

**Comment by bluepilledgreat** [comment]
We are no longer taking fast flag related suggestions. Please see #1321.

**Comment by ShadowLite1** [comment]
> 1. You can always add Vulkan FFlag manually
> 2. Vulkan triggers Hyperion for like 96% of people
> 3. Roblox implemented Vulkan to be a render that's used on mobile, because of that they don't update Vulkan on PC which causes the previously mentioned Hyperion triggering

I tried to do Vulkan and it doesn't work for me

**Comment by ShadowLite1** [comment]
> 1. You can always add Vulkan FFlag manually
> 2. Vulkan triggers Hyperion for like 96% of people
> 3. Roblox implemented Vulkan to be a render that's used on mobile, because of that they don't update Vulkan on PC which causes the previously mentioned Hyperion triggering

Is there a version I could get which is non-Hyperion or is that not possible, because when I do try to enable it, it doesn't work.

**Comment by pizzaboxer** [comment]
Read the release notes of the latest version please. https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4
