### ISSUE TITLE
[FEATURE] Re-add FPS unlocker

### ISSUE THREAD

**Issue by AAA-A1a** [pizzaboxer/bloxstrap#147]
The new method of changing FPS (via the option in FastFlags) removes the ability to change the FPS in-game, which was previously possible with FPS Unlocker. (Either this or a way to change flags in game would work.) Additionally, it seems like this causes camera stutters. You can't even fix it by using FPSUnlocker instead since this flag overrides it...

**Comment by pizzaboxer** [comment]
There's not much of an alternative. If you've been paying attention, there's a very good reason I removed rbxfpsunlocker as part of this update. rbxfpsunlocker will not work with the new 64-bit client because of Hyperion.
