### ISSUE TITLE
[BUG] Unable to open 2 instances

### ISSUE THREAD

**Issue by EpicPlays982** [pizzaboxer/bloxstrap#1470]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have the setting enabled and the changed the settings in the notepad however whenever I try and open a second instance of Roblox, it automatically closes the first

**Comment by pizzaboxer** [comment]
> however whenever I try and open a second instance of Roblox, it automatically closes the first

Do you see the Bloxstrap launcehr show whenever Roblox launches?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
