### ISSUE TITLE
[BUG] Roblox Crashing Every Time I Open It THROUGH Blox Strap.

### ISSUE THREAD

**Issue by kloudzz** [pizzaboxer/bloxstrap#1471]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Last night my Blox Strap wasn't working, like the setting I applied weren't like I don't know how to explain it but it just wasn't working. Like an item in my game when you used the move it was all blocky, then the next day it wasn't so I uninstalled Blox Strap and re-installed it. And now my Roblox crashes every time I open Roblox through Blox Strap. I've tried everything can someone please help me?

![image_2024-03-20_115659668](https://github.com/pizzaboxer/bloxstrap/assets/164221530/99fae831-7992-4dac-8c50-6915bda18fb7)

![image_2024-03-20_115712161](https://github.com/pizzaboxer/bloxstrap/assets/164221530/445d3efa-3ef2-4f94-b412-98c56e04de63)

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, can you confirm that this doesn't happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
