### ISSUE TITLE
[BUG]  2015 Roblox escape menu not showing up

### ISSUE THREAD

**Issue by Jack122234** [pizzaboxer/bloxstrap#1472]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2015 roblox menu not showing up it only shows up the defult one

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
