### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dempul** [pizzaboxer/bloxstrap#1474]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240321T132953Z.log](https://github.com/pizzaboxer/bloxstrap/files/14695917/Bloxstrap_20240321T132953Z.log)
what happened on this? i got exception, its called "denied". idk 'bout that, can you fix this?
![ScreenShot 2024-03-21 204032](https://github.com/pizzaboxer/bloxstrap/assets/138563983/7b38923f-74be-48b4-9822-f746641c7a44)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

Read the preliminary instructions before you open an issue.
