### ISSUE TITLE
[BUG]  keeps updating on joining a game

### ISSUE THREAD

**Issue by Zhentor0** [pizzaboxer/bloxstrap#1475]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

can yall just fix it its so annoying and makes joining games take years

**Comment by pizzaboxer** [comment]
Are you launching from multiple accounts? If so, then see this: https://github.com/pizzaboxer/bloxstrap/wiki/Using-multiple-instances-always-forces-a-Roblox-upgrade

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
