### ISSUE TITLE
[BUG] Avast telling that Bloxstrap is somehow a malware

### ISSUE THREAD

**Issue by KlothoTheDev** [pizzaboxer/bloxstrap#1476]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello pizzaboxer 

At 8:29 PM the 03/21/2024 Avast blocked Bloxstrap for being a IDP.Generic
![Capture d’écran 2024-03-21 193055](https://github.com/pizzaboxer/bloxstrap/assets/143290091/c4de3ebb-1602-4f90-ab73-444df28d6b3d)

**Comment by pizzaboxer** [comment]
Given the fact that it's being detected as "IDP.Generic", it's very likely a false positive, especially given how the [VirusTotal report](https://www.virustotal.com/gui/file/b2ac1e407ed3ecd7c7faa6de929a68fb51145662cf793c40b69eb59295bba6bc) says it's completely clean. 
If you're sure that you downloaded it from here (at [http](https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4), then it's a false positive and you can safely allow it.

**Comment by packmcmeta** [comment]
you made a cookie logger be ashamed
