### ISSUE TITLE
[BUG] Possible Bloxstrap Error during installation(?)

### ISSUE THREAD

**Issue by OneMinuteNoZa** [pizzaboxer/bloxstrap#1477]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

# problem
i got a manifest error during installation but i don't know if its something to do with my pc or not 🤷‍♂️ 
# error
## install location
C:\Users\myuser\AppData\Local\Bloxstrap
## logged error
System.NotSupportedException: Unexpected package manifest version: <html><body onload="document.forms[0].submit()"> (expected v0!)
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/159163445/12493571-4a18-4fcf-95a4-4ec7e488ef68)

**Comment by pizzaboxer** [comment]
Is this happening every time you launch? If so, go to https://setup.rbxcdn.com/version-94a1a798754e4385-rbxPkgManifest.txt in your browser, and take a screenshot of what you see.

**Comment by OneMinuteNoZa** [comment]
it was. i ended up downgrading dotnet back to 6.0 and it ended up working. thank you for actually responding Pizzaboxer, i really apreciate it when the devs actually respond!
