### ISSUE TITLE
Where will version 3 be for the roblox escape menu?

### ISSUE THREAD

**Issue by Magicland1** [pizzaboxer/bloxstrap#1478]
### Acknowledgement of preliminary instructions

- [ ] I have read and acknowledged the preliminary instructions.

### What idea do you have?

you used to have version 3 but now its gone

**Comment by OneMinuteNoZa** [comment]
either roblox doesnt have esc menu v3 or it may just be buggy and they might add it back

**Comment by Magicland1** [comment]
yeah probably

**Comment by Magicland1** [comment]
Its probably bugged

**Comment by Magicland1** [comment]
But also they haven't brought it back since a long time ago, I downloaded it 2 years ago and it didn't have it

**Comment by Magicland1** [comment]
**> either Roblox doesn't have esc menu v3** or it may just be buggy and they might add it back

they did I saw other people with it

**Comment by pizzaboxer** [comment]
> you used to have version 3 but now its gone

Because Roblox removed the ability to use it. The option for it isn't gone for no reason.
