### ISSUE TITLE
[REQ] Being able to use ps links and not having bloxstrap forcefully be used 

### ISSUE THREAD

**Issue by Melimai** [pizzaboxer/bloxstrap#1479]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

basically bloxstrap bugs out one of the macros I use for a game, and I wanted to join ps servers but whenever I try to join via a link bloxstrap turns on and bugs my macro so I want a way to join ps server links without having the delate bloxstrap like a option to diable bloxstrap

**Comment by pizzaboxer** [comment]
I'm not interested in helping you use macros, so I'll decline helping you on this issue.
