### ISSUE TITLE
Add custom emojifonts, like Mozilla/Twemoji.ttf!

### ISSUE THREAD

**Issue by NikSavchenk0** [pizzaboxer/bloxstrap#148]
In 2020 they removed the images with sprites folder "emojis" and moved it to the folder "fonts" where there is TwemojiMozilla.ttf.

But I would like to have some kind of custom emoji fonts for Roblox. I can, send the files or even the repositories themselves.
![image](https://user-images.githubusercontent.com/58150480/233827824-a4391524-7309-4bb4-9f8a-d3ec99fa5a72.png)
![image](https://user-images.githubusercontent.com/58150480/233828173-dda22ba4-5c55-421d-8a19-1b0ed8af6355.png)
![image](https://user-images.githubusercontent.com/58150480/233828337-6c0559f8-63c6-4941-8858-05a1d75d8280.png)

**Comment by pizzaboxer** [comment]
Oh, that could make for a really nice mod preset actually. If you want to send the files here, go ahead!

**Comment by pizzaboxer** [comment]
Whoops, I misunderstood this like 3 times. Are you suggesting providing an option to choose between different emoji vendors?

**Comment by NikSavchenk0** [comment]
Well this is the emoji font selection catalogue of your choice, for example there are: msfluent11, ms10, ms8.1, ms8.0, etc.

**Comment by pizzaboxer** [comment]
Oh that's cool, this would be nice to make into an easily configurable mod preset. Though, I'm guessing most people would want to stick with Twemoji as everyone is already familiar with it. If you're able to find more commonly used compatible emoji fonts from vendors like Apple and old/new Android, I could consider adding these.

**Comment by NikSavchenk0** [comment]
Apple emojis for only Apple products, Noto Color Emojis aka Android available Windows, so only using (136x136), Twemoji using (100x100). For Android there is a program by name: zFont 3.

**Comment by pizzaboxer** [comment]
Oh, I guess I probably should've actually looked at this before suggesting, since none of them are compatible or available. I think if I'm to add this, I'd make the Windows 10 and 11 fonts the two other choosable options.

**Comment by NikSavchenk0** [comment]
Nah, wait, all fonts support on my repositories.
Catmoji is modded Twemoji, All Microsoft emojis working perfectly, OneMoji only contract emojis.

**Comment by pizzaboxer** [comment]
I mean, I'm kind of looking at emojis that most people would probably choose to use, so probably not the 8/8.1 fonts. I can consider the symbol emojis and Catmoji though.

**Comment by NikSavchenk0** [comment]
ms8.0 (unicode 6) this is contract emoji, ms8.1 (unicode 6) like ms10/ms11 (unicode 13).
