### ISSUE TITLE
[BUG] Crashes

### ISSUE THREAD

**Issue by BodikeWerx** [pizzaboxer/bloxstrap#1480]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox crashes when I go to more - settings - account info

https://github.com/pizzaboxer/bloxstrap/assets/164545620/e3ce23f3-2317-4519-b8c0-617abf452bd0

**Comment by OneMinuteNoZa** [comment]
what fps rate did you set for bloxstrap in fastflags? it may be an issue on roblox's side itself due to the grapics card and/or Ram on your computer

**Comment by OneMinuteNoZa** [comment]
i'd also recommend expierimenting with the fps settings on the bloxstrap installation starting with 120 fps

**Comment by BodikeWerx** [comment]
Back then, it was 120 FPS, even when I set it to 60, it still crashed

**Comment by pizzaboxer** [comment]
[Reinstall the WebView2 runtime.](https://github.com/pizzaboxer/bloxstrap/issues/635#issuecomment-2011668696)

You can find the Evergreen installer [here](https://developer.microsoft.com/en-gb/microsoft-edge/webview2/?form=MA13LH).
