### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by Hihellosile** [pizzaboxer/bloxstrap#1481]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It worked a few times, but it stopped for some reapsn
![image](https://github.com/pizzaboxer/bloxstrap/assets/164557905/18c0069a-d4cf-412f-8528-059c3884a01a)

**Comment by pizzaboxer** [comment]
> It worked a few times, but it stopped for some reapsn

Does it happen every time? Have you chosen to change your emoji font type in the Mods section of the menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
