### ISSUE TITLE
Make it so you can rename RobloxPlayerBeta and still be recognized by Bloxstrap

### ISSUE THREAD

**Issue by fluffyand3games** [pizzaboxer/bloxstrap#1482]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It's for shaders to work with the website

**Comment by fluffyand3games** [comment]
Don't mind the username my sister named it.

**Comment by pizzaboxer** [comment]
https://bloxshade.com
