### ISSUE TITLE
[REQ] RAM limiter

### ISSUE THREAD

**Issue by bigbrother12345** [pizzaboxer/bloxstrap#1484]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

A ram limiter(regardless of performance) would be a helpful feature to add.
For example, set the limit to 500MB and roblox's ram usage should not exceed that limit, although the performance will suffer.

**Comment by pizzaboxer** [comment]
It'd be best to use a third-party tool for that, rather than me integrating it manually. https://superuser.com/a/1263201
