### ISSUE TITLE
[BUG]  Mouse Cursor Flashes Repeatedly when Launching Bloxstrap

### ISSUE THREAD

**Issue by Maxey1950** [pizzaboxer/bloxstrap#1485]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When opening bloxstrap or pressing play roblox the app closes and spams the mouse cursor to hell, restart fixes this issue it's just really annoying when I'm trying to play roblox, has anyone got a fix or have seen this issue?

**Comment by pizzaboxer** [comment]
What do you mean by "the app closes"? What app? Additionally, have you confirmed that this happens only with Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
