### ISSUE TITLE
[BUG] so my bloxstrap ran into a problem!

### ISSUE THREAD

**Issue by TallMan4** [pizzaboxer/bloxstrap#1486]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

 so im using a custom font with bloxstrap, and i put a custom font. the font got deleted from my files somehow (idk) so it says theres an files and it cant be located, so what i did was re-download the font, but it still says the same exact thing!!! can someone help me with **this?*****

**Comment by pizzaboxer** [comment]
Can you get to the option for it in the menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
