### ISSUE TITLE
[RESIZE] BloxStrap

### ISSUE THREAD

**Issue by BlinkyBinders** [pizzaboxer/bloxstrap#1489]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Need to be able to resize window for bloxstrap. Too large. Trying to get 4 accounts up on screen.

**Comment by pizzaboxer** [comment]
Roblox doesn't let you resize the window any smaller than 800x600. There's no way to get around this unfortunately.
