### ISSUE TITLE
An error occured while starting ROBLOX

### ISSUE THREAD

**Issue by Profility** [pizzaboxer/bloxstrap#149]
Tried joining my private-server and was greeted with this error message.

![image](https://user-images.githubusercontent.com/72250349/233846112-80f47c96-586c-41b6-bdb2-30e55dab98d5.png)

**Comment by pizzaboxer** [comment]
Wow, that's weird. Out of curiosity, does connecting to [clientsettings.roblox.com](https://clientsettings.roblox.com) work fine? If it doesn't, how about [clientsettingscdn.roblox.com](https://clientsettingscdn.roblox.com )?

**Comment by Profility** [comment]
I can connect to the links you provided on my browser just fine, I'll try reinstalling Bloxstrap real quick.

**Comment by pizzaboxer** [comment]
If that doesn't work, I can quickly provide a patch that should at least fix this.

**Comment by Profility** [comment]
Just reinstalled Bloxstrap and joined my private-server just fine, it did take quite a while to join though.

**Comment by pizzaboxer** [comment]
Okay, cool. What part did it take the longest on when it was launching?

**Comment by Profility** [comment]
Nevermind, the error is back yet again. It shows the error at the "Connecting to Roblox.." part

**Comment by pizzaboxer** [comment]
Okay, here's a patch version. See if this is any different. If you currently have Bloxstrap installed, open the folder it's installed to and replace Bloxstrap.exe with this.

[Bloxstrap.exe](https://pizzaboxer.xyz/files/bloxstrap-debug/149/Bloxstrap.exe)

**Comment by Profility** [comment]
Sorry for taking so long; I tried reinstalling Bloxstrap, restarting my PC, checking if my network is bugging with me and tried your patched version.

I tried your patched version and it only shows the bootstrapper window then after the "Starting Roblox..." part, it just vanishes and doesn't open ROBLOX at all.

**Comment by Profility** [comment]
[0.572.1.5720486_20230423T151954Z_Player_3B5B0_last.log](https://github.com/pizzaboxer/bloxstrap/files/11304083/0.572.1.5720486_20230423T151954Z_Player_3B5B0_last.log)

Here is the latest log file.

**Comment by pizzaboxer** [comment]
Yep, that has to be a Roblox problem. Seems like it's just completely failing to connect to the Roblox website. Can you uninstall Bloxstrap and try to start Roblox again, to see if this still happens without Bloxstrap?

**Comment by Profility** [comment]
I tried starting ROBLOX without Bloxstrap and it's giving me the Authentication Failed error; so it is probably a Roblox problem.

**Comment by pizzaboxer** [comment]
Throwing a few ideas around, can you open up Internet Explorer/Microsoft Edge and go to http://clientsettings.roblox.com -  the http is important. Does anything weird happen?

**Comment by Profility** [comment]
Nothing weird happens; it still just shows "{"message":"OK"}"

**Comment by pizzaboxer** [comment]
Well, that was really my only idea. I can't think of a reason for why it works fine in your browser, but no desktop applications (Bloxstrap and Roblox) are unable to access the Roblox website. Other than there being some weird network configuration on your PC (proxy, etc), I can't think of much.

**Comment by Profility** [comment]
Quick Update: ROBLOX is working all fine but Bloxstrap itself really doesn't want to join a game; I uninstalled Bloxstrap entirely for now and I'm playing as normal

**Comment by pizzaboxer** [comment]
>  but Bloxstrap itself really doesn't want to join a game

What do you mean? What was it doing?

**Comment by mcdonaldHasWifi** [comment]
I try entering using bloxstrap,then its loads normally until the starting part then it completely vanishes and nothing load/comes up.COULD U PLEASE HELP ME WITH THIS ISSUE!!

**Comment by mcdonaldHasWifi** [comment]
now i just use the normal roblox,i need those fast flag editors to play roblox rivals.And get some fps boosts
