### ISSUE TITLE
[BUG] idk what it is

### ISSUE THREAD

**Issue by WhitefangY** [pizzaboxer/bloxstrap#1493]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..

[Inner Exception]
System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine.
that is the thing

**Comment by pizzaboxer** [comment]
Your internet connection is being interrupted. Relaunch again and it should work. If it doesn't check for any network/internet issues or anything.

**Comment by WhitefangY** [comment]
thank you pizzaboxer i appreciate the help
