### ISSUE TITLE
[BUG]  Not quite sure if this is from bloxstrap or Windows 10 itself.

### ISSUE THREAD

**Issue by VoiderzX** [pizzaboxer/bloxstrap#1497]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So it not necessarily a huge issue but it is quite annoying that i have a permanent yellow notification by my application taskbar even when i do go on the app/tab it just doesn't go away.  Now this started ever since I downloaded Bloxstrap now if this isn't from Bloxstrap problem can you please provide me with a solution this is a Windows 10 laptop, and I have been looking to fix this problem everywhere but nothing has worked.
![image](https://github.com/pizzaboxer/bloxstrap/assets/114313973/bda97a6d-7d8e-4e5e-813b-b845ec232184)

**Comment by pizzaboxer** [comment]
> Now this started ever since I downloaded Bloxstrap now 

Can you confirm that this doesn't happen with the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by VoiderzX** [comment]
> > Now this started ever since I downloaded Bloxstrap now
> 
> Can you confirm that this doesn't happen with the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Yes I've done this i can't seem to replicate the problem, (attempting to select another window so the yellow glow appears while roblox is opening and yet roblox does not gain this yellow glow regardless so it might be bloxstrap but correct me if I'm wrong.

**Comment by pizzaboxer** [comment]
When you use Bloxstrap, does Roblox work fine though?

**Comment by VoiderzX** [comment]
> When you use Bloxstrap, does Roblox work fine though?

oh it works fine but the yellow highlighter just slightly bothers me :/

**Comment by pizzaboxer** [comment]
In the Bloxstrap menu, if you disable all the integrations provided, does it go away?

**Comment by VoiderzX** [comment]
> In the Bloxstrap menu, if you disable all the integrations provided, does it go away?

I figured out the issue, its the multi instance lunching causing the issue that causes the permanent, even if i open up just 1 roblox instance. To clarify I did

Discord Rich Presence (Always Disabled)
Activity Tracking (Enabled) + Multi Instance (Enabled) = Highlighter Glitch, both when Lunching one instance or more than one
Activity Tracking (Disabled) + Multi Instance (Enabled) = Highlighter Glitch, both when Lunching one instance or more than one
Activity Tracking (Enabled) + Multi Instance (Disabled) = No Glitch

**Comment by pizzaboxer** [comment]
Oh, that actually makes sense. I didn't know that Roblox highlighted the application in the taskbar though, because it doesn't do that for me or anyone that I know. Seems like it's doing that because it's detecting another instance being open (Bloxstrap serves as one in order to make multi instance launching work).
