### ISSUE TITLE
Roblox Menu

### ISSUE THREAD

**Issue by FareesmineGithub** [pizzaboxer/bloxstrap#1499]
Not sure if this is a bug or intended but I've noticed that whenever I play Roblox (with Bloxstrap) it doesn't give me the new Roblox menu (the new modern round one).  Is there any way I could get the new menu while using Bloxstrap?

**Comment by FareesmineGithub** [comment]
And I don't mean the escape menu thing. Im talking about the menu you use to open the escape menu.

**Comment by FareesmineGithub** [comment]
Hm, i joined a game just now and it fixed itself but when i left and rejoined again it was back to the old menu thing

**Comment by pizzaboxer** [comment]
> Im talking about the menu you use to open the escape menu.

What?
