### ISSUE TITLE
[BUG] An exception occurred while instal Bloxstrap

### ISSUE THREAD

**Issue by DaRialDipZvki** [pizzaboxer/bloxstrap#1501]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Errorrrr](https://github.com/pizzaboxer/bloxstrap/assets/164936247/62ddedb1-1194-4d59-94a1-2dfb636886ba)
Could explain to me what this is?

**Comment by pizzaboxer** [comment]
Upload the log file please.

**Comment by kojize1** [comment]
i got the same issue, can i be the one to upload the log file instead?
[Bloxstrap_20240417T051302Z.log](https://github.com/pizzaboxer/bloxstrap/files/15005830/Bloxstrap_20240417T051302Z.log)

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
