### ISSUE TITLE
[BUG] problem while installing bloxstrap

### ISSUE THREAD

**Issue by MonkaiD** [pizzaboxer/bloxstrap#1502]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

signature doesnt match idk what it means but it told em to report it
![Captssure](https://github.com/pizzaboxer/bloxstrap/assets/165024478/15c622cc-28d6-49c3-b381-67dc38d5023b)

**Comment by MonkaiD** [comment]
wrong photo mb

![Captussre](https://github.com/pizzaboxer/bloxstrap/assets/165024478/ee17a8c9-ac33-472f-aebb-7ce32a3b244f)

**Comment by MonkaiD** [comment]
[Bloxstrap_20240326T113151Z.log](https://github.com/pizzaboxer/bloxstrap/files/14757770/Bloxstrap_20240326T113151Z.log)

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox?
