### ISSUE TITLE
[BUG] When launching roblox from Bloxstrap, it freezes onto white screen

### ISSUE THREAD

**Issue by limmyz** [pizzaboxer/bloxstrap#1503]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-03-26 124921](https://github.com/pizzaboxer/bloxstrap/assets/165061269/7a4513f9-dab7-44c4-bdcc-16ab37d1030c)

Basically when I add a mod or change anything on bloxstrap and then launch roblox from it, it freezes onto a white screen. I took the mods off and then it went back to nromal after relaunching

**Comment by pizzaboxer** [comment]
> I took the mods off and then it went back to nromal after relaunching

What specifically did you take off?

**Comment by Gunmaster12** [comment]
Well, nothing but its won't  install after I put on run on multiple clients. Then i turn it off again and nothing

**Comment by pizzaboxer** [comment]
There doesn't really seem to be a correlation here. Can you check right now to see if this happens with the standard launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
