### ISSUE TITLE
[BUG] Another bug?

### ISSUE THREAD

**Issue by Gunmaster12** [pizzaboxer/bloxstrap#1508]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i already have one bug then this pops up
![Screenshot 2024-03-26 174026](https://github.com/pizzaboxer/bloxstrap/assets/165096945/2de8e568-31db-4bcc-8aa2-3e4f2accdf02)

**Comment by pizzaboxer** [comment]
Send the log file please

**Comment by Gunmaster12** [comment]
ok

**Comment by pizzaboxer** [comment]
Where is it?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
