### ISSUE TITLE
[BUG] im putting a font in but its not showing up?

### ISSUE THREAD

**Issue by badowls** [pizzaboxer/bloxstrap#1510]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

font not showing up

**Comment by pizzaboxer** [comment]
Are you seeing the Bloxstrap launcher show whenever you launch Roblox?

**Comment by badowls** [comment]
yes

**Comment by badowls** [comment]
every other feature works except the font

**Comment by badowls** [comment]
> Are you seeing the Bloxstrap launcher show whenever you launch Roblox?

yes but every other feature works

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
