### ISSUE TITLE
[BUG] An exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by 333SOULJAA** [pizzaboxer/bloxstrap#1511]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So basically im tryna afk farm like usually with multiple instances but then I always keep getting this error messages (well sometimes) while trying to launch multiple accounts..
![Screenshot 2024-03-27 230612](https://github.com/pizzaboxer/bloxstrap/assets/165218726/84252233-b6eb-49f8-9b9f-eaac02a2c2c2)
[Bloxstrap_20240327T220211Z.log](https://github.com/pizzaboxer/bloxstrap/files/14781656/Bloxstrap_20240327T220211Z.log)
I think this is the logfile..

**Comment by pizzaboxer** [comment]
We don't support this use case for multiple instances, sorry.
