### ISSUE TITLE
[BUG] Alt+enter is not working.

### ISSUE THREAD

**Issue by nazv5** [pizzaboxer/bloxstrap#1512]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Alt + Enter is suddenly not working, I re-installed bloxstrap, Alt + Enter fullscreens roblox but it's a normal fullscreen, the screen doesn't turn black and I'm not getting any FPS boosts. Roblox is not flashing black momentarily like it would before, and I'm not getting an FPS boost, I don't know what rendering mode I'm using because there's no feature to change it because you guys removed it before I started using this. I put "Graphics mode" in roblox studio to automatic but I'll change it to Direct3d11 to see if it's causing the problem.

**Comment by pizzaboxer** [comment]
> I don't know what rendering mode I'm using because there's no feature to change it because you guys removed it before I started using this. 

If you don't have any flags set, then you're using Direct3D by default. Regardless, upload your configuration please: 

https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by glimm321** [comment]
is there a fix yet?

**Comment by NabHeyka22** [comment]
> is there a fix yet?

https://github.com/bloxstraplabs/bloxstrap/wiki/Manual-configuration-of-Fast-Flag-management
