### ISSUE TITLE
why am i stuck on a screen with something about an expectation ecured page

### ISSUE THREAD

**Issue by Lgisticsxx** [pizzaboxer/bloxstrap#1513]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

why am i stuck on a screen with something about an expectation ecured page

**Comment by pizzaboxer** [comment]
> why am i stuck on a screen with something about an expectation ecured page

Can you show a screenshot please?

**Comment by BloxstrapAIntWorking** [comment]
I have the same problem[

https://github.com/pizzaboxer/bloxstrap/assets/165416644/8dd4f731-176d-44e2-8c0c-ea508ce651cb

](url)

**Comment by BloxstrapAIntWorking** [comment]
I start by trying to open a roblox game and the screen stays grey, i don't know what to do.

**Comment by pizzaboxer** [comment]
> I start by trying to open a roblox game and the screen stays grey, i don't know what to do.

Can you confirm if this issue happens only with Bloxstrap please? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
