### ISSUE TITLE
bloxstrap wont upgrade!!

### ISSUE THREAD

**Issue by hvyden** [pizzaboxer/bloxstrap#1514]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxstrap wont upgrade and it gets to the point where it requests me to submit a problem via Github or Discord. i tried to reinstall the app, restart, shutdown my pc idk whats wrong with it "System.Exception: Signature does not match!"

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox?
