### ISSUE TITLE
How to Add Custom Sound Into Client and Play it on game by using directory on roblox studio

### ISSUE THREAD

**Issue by HelloKerem** [pizzaboxer/bloxstrap#1515]
so i was thinking i want upload this sound

https://github.com/pizzaboxer/bloxstrap/assets/98821815/04b1481d-910d-4c56-8a24-d57f09ada3d2
(Yeah its dioxide.exe first payload sound)

but idk how to direct it to work it
![image](https://github.com/pizzaboxer/bloxstrap/assets/98821815/3f408e7c-f65b-46f2-ae10-99f6e0bf8dba)

can someone help by doing that?

**Comment by pizzaboxer** [comment]
This place is strictly for help/support with Bloxstrap only, sorry.
