### ISSUE TITLE
[BUG] Whenever I Join a game Roblox crashes randomly

### ISSUE THREAD

**Issue by refheader** [pizzaboxer/bloxstrap#1517]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i try joining a game it keeps on crashing i tried reinstalling it but nothing works at all

**Comment by tr3kko** [comment]
i have the same issue i tried restarting my pc and unstill bloxtrap and stuff but nothing works

**Comment by pizzaboxer** [comment]
> When i try joining a game it keeps on crashing i tried reinstalling it but nothing works at all

Is this happening only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
