### ISSUE TITLE
Horrible lag spikes using bloxstrap even at 1 graphics 

### ISSUE THREAD

**Issue by andicity** [pizzaboxer/bloxstrap#1518]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I used bloxstrap and it kept giving me lag spikes, when i use the roblox launcher the only time i get lag spikes is at 8 graphics + while using bloxstrap even at 1 graphics it gives me bad lag spikes.

**Comment by lukas27892** [comment]
what type of settings did you use?

for all i know, only:
preferred lighting technology (PLT)
and preserve rendering quality with display scaling (PRQ)

are the only ones to really do much to your performance. if these were defaulted (chosen by game for PLT and off for PRQ) then there is nothing much i can say.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by andicity** [comment]
State.Json
{
  "LastEnrolledChannel": "LIVE",
  "VersionGuid": "version-f573c8cc796e4c97",
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\sounds\\ouch.ogg"
  ]
}

ClientAppSettings.Json
{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "DFIntTaskSchedulerTargetFps": "200",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "DFIntTextureQualityOverride": "3",
  "DFIntDebugFRMQualityLevelOverride": "1",
  "FIntRenderShadowmapBias": "75"
}

Settings.Json
{
  "BootstrapperStyle": 4,
  "BootstrapperIcon": 0,
  "BootstrapperTitle": "Bloxstrap",
  "BootstrapperIconCustomLocation": "",
  "Theme": 0,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "MultiInstanceLaunching": false,
  "OhHeyYouFoundMe": false,
  "Channel": "LIVE",
  "ChannelChangeMode": 0,
  "EnableActivityTracking": false,
  "UseDiscordRichPresence": false,
  "HideRPCButtons": true,
  "ShowServerDetails": false,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldCharacterSounds": false,
  "UseDisableAppPatch": false,
  "UseOldAvatarBackground": false,
  "CursorType": 0,
  "EmojiType": 0,
  "DisableFullscreenOptimizations": false
}

**Comment by pizzaboxer** [comment]
Remove all the flags you've configured and see if the issue continues to happen.

**Comment by andicity** [comment]
The issue still continues to happen.

**Comment by pizzaboxer** [comment]
Try disabling all the integrations provided in the integrations section of the menu.

**Comment by andicity** [comment]
All of them were already disabled but the issue still happens

**Comment by pizzaboxer** [comment]
Try removing all the custom flags you have set.

**Comment by andicity** [comment]
Very late reply but it was still lagging.

**Comment by andicity** [comment]
For now im using the roblox launcher because i only used bloxstrap for more render distance.

**Comment by pizzaboxer** [comment]
> Very late reply but it was still lagging.

In that case, the problem probably isn't in Bloxstrap's scope since at that point Bloxstrap is configured to work exactly like the original launcher.
