### ISSUE TITLE
[BUG] Bloxstrap bug

### ISSUE THREAD

**Issue by Bca5758** [pizzaboxer/bloxstrap#1519]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I try click bloxstrap "Play roblox", Its showing "Open file - security warning", it does do the loading but when i wating its take long time to show the game, when i check to task manager is already running, its always happend even i just reinstall(even the original roblox) it twice, maybe this bug or another issue
![Screenshot (1)](https://github.com/pizzaboxer/bloxstrap/assets/161095233/01dcd9ea-31c7-42a5-bad9-517f7fad3dc0)
![Screenshot (2)](https://github.com/pizzaboxer/bloxstrap/assets/161095233/d18d66fe-1ce8-4537-947e-96684721ba36)
![Screenshot (3)](https://github.com/pizzaboxer/bloxstrap/assets/161095233/0ac160c6-174f-49fd-a05c-dec132876bf2)*

**Comment by pizzaboxer** [comment]
Have you confirmed if this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Bca5758** [comment]
> Have you confirmed if this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

It is. I play on roblox original, its work

**Comment by Bca5758** [comment]
> > Have you confirmed if this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
> 
> It is. I play on roblox original, its work

It's happend when i reinstall the bloxstraps and the roblox

**Comment by pizzaboxer** [comment]
> It is. I play on roblox original, its work

I misunderstood your issue initially, my bad.

What options have you configured in Bloxstrap? Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Bca5758** [comment]
> > It is. I play on roblox original, its work
> 
> I misunderstood your issue initially, my bad.
> 
> What options have you configured in Bloxstrap? Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

![Screenshot (4)](https://github.com/pizzaboxer/bloxstrap/assets/161095233/2eb408d2-a6ca-4265-a3da-e140d5039697)
![Screenshot (6)](https://github.com/pizzaboxer/bloxstrap/assets/161095233/c0c94ce9-1ea8-46ef-be24-5aa8fb104dfd)

**Comment by pizzaboxer** [comment]
No, upload the files themselves. I need to see the file contents. Sending pictures of the files isn't very helpful.

**Comment by Bca5758** [comment]
[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/14817562/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/14817563/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/14817564/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
Are you launching Roblox from the website?

If you are, try these two things: clear your whole FastFlag list, and disable the "disable fullscreen optimizations" option. See if it works then.

**Comment by Bca5758** [comment]
AHhh Finally, It's working now, i tought i cant play roblox anymore without any drop fps

**Comment by pizzaboxer** [comment]
You might be able to re-enable the fullscreen optimizations option. If Roblox stops working when you enable that, then just disable it again.
