### ISSUE TITLE
Issue with certain sounds not playing in experiences.

### ISSUE THREAD

**Issue by AIfaO** [pizzaboxer/bloxstrap#152]
After using BloxStrap, I've noticed that certain sounds in experiences wouldn't play at all. This has also happened before when I installed RCO (Roblox-Client-Optimizer) using their [ClientAppSettings.json](https://github.com/L8X/Roblox-Client-Optimizer/blob/main/ClientAppSettings.json). Is this issue fixable?

**Comment by pizzaboxer** [comment]
You're not using RCO's FastFlag list with Bloxstrap, are you? Bloxstrap doesn't modify any sound-related flags at all, so I'm not sure how that could be happening. Whenever this happens, does anything in the developer console (F9) show?

**Comment by AIfaO** [comment]
I can make sure that I'm not using RCO's FastFlag list with Bloxstrap. How would I check that it's not there? Would I go under "C:\Users\\AppData\Local\Bloxstrap\Versions\version-40b6a27c6c4d46ef" and check if there is already a "ClientSettings" folder with the json file there?

![image](https://user-images.githubusercontent.com/71277753/234135197-9adfa8a6-7a1a-40ed-ab9e-98afbc360260.png)

**Comment by pizzaboxer** [comment]
Can you please paste the contents of the ClientAppSettings.json file here that's inside of the ClientSettings folder?

**Comment by AIfaO** [comment]
`{
  "FIntFlagUpdateVersion": 84,
  "FStringNewInGameMenuForcedUserIds": "2323539704;3822626535;4126963942;2627408279;4329723352",
  "DFIntSecondsBetweenDynamicVariableReloading": 31557600,
  "FIntRolloutEnrollmentExpirationMinutes": 31557600,
  "DFFlagDynamicFastVariableReloaderTest1": false,
  "FFlagExecDynInitTests": false,
  "DFFlagEarlyExitIfHang": false,
  "DFFlagRenderTC2_6": true,
  "FFlagRenderTC2_Disable": false,
  "FIntRenderTC2_PercentageRollout": 100,
  "FFlagRenderFixTC2MemoryLeak": true,
  "DFFlagRenderTC2PreferWidthPOT": true,
  "DFFlagRenderTC2_DiscardGeometryData2": true,
  "FIntRenderTC2BakeQueueSize": 6,
  "FLogRenderTC2LogGroupAsync": 6,
  "FLogRenderTC2LogGroupContent": 6,
  "FLogRenderTC2LogGroupFlow": 6,
  "FLogRenderTC2LogGroupLOD": true,
  "FFlagRenderTC2LogStateEnable": true,
  "FFlagLoadCoreScriptsFromPatchOnly": true,
  "FFlagIncrementalPatchBuilderConfigurableRebuildPeriod": true,
  "FIntMaxCachedPatches": 3,
  "DFFlagDynIpBlacklistBackoffEnabled": true,
  "DFIntAppLaunchFlowThrottlingRate": 0,
  "FIntMeshContentProviderForceCacheSize": 200000000,
  "FIntAnimationClipCacheBytes": 200000000,
  "FIntEmotesAnimationsPerPlayerCacheSize": 200000000,
  "FIntDefaultMeshCacheSizeMB": 2048,
  "FIntSmoothTerrainPhysicsCacheSize": 200000000,
  "DFIntHttpCurlConnectionCacheSize": 200000000,
  "DFIntUserIdPlayerNameCacheSize": 200000000,
  "DFIntUserIdPlayerNameLifetimeSeconds": 604800,
  "FIntTaskSchedulerAutoThreadLimit": 16,
  "DFIntTaskSchedulerTargetFps": 200000000,
  "FLogCSG3Details": 6,
  "FLogCSG3Errors": 6,
  "FLogCSG3Stats": 6,
  "FLogCSG3Debug": 6,
  "FLogCSGDetails": 6,
  "FLogCSGErrors": 6,
  "FLogTextureManager": 6,
  "FLogTextureQualityLog": 6,
  "FLogGraphicsTextureReductionD3D11": 6,
  "FLogGraphicsTextureReductionOpenGL": 6,
  "FLogGraphicsTextureReductionVulkan": 6,
  "FLogSSAO": 6,
  "FIntSSAOMipLevels": 0,
  "DFIntJoinDataCompressionLevel": 8,
  "DFIntClusterCompressionLevel": 8,
  "DFIntNetworkSchemaCompressionRatio": 18,
  "FFlagHandleAltEnterFullscreenManually": false,
  "DFFlagTaskSchedulerAvoidYieldInBackground": true,
  "DFFlagTaskSchedulerBlockingShutdownInClients": true,
  "FFlagTaskSchedulerUseRobloxRuntime": true,
  "FFlagEnableQuickGameLaunch": true,
  "FFlagFlagAPICaching": true,
  "FFlagPreloadAllFonts": true,
  "FFlagPreloadMinimalFonts": true,
  "FFlagRemoveRedundantFontPreloading": true,
  "FFlagPreloadTextureItemsOption4": true,
  "DFFlagContentProviderSupportsSymlinks": true,
  "DFFlagJointIrregularityOptimization": true,
  "DFFlagVariableDPIScale2": true,
  "DFFlagHttpClientOptimizeReqQueuing": true,
  "FFlagBatchAssetApi": true,
  "DFFlagReportHttpBatchApiRejectedUrl": true,
  "DFLogBatchAssetApiLog": 6,
  "DFIntBatchThumbnailLimit": 200,
  "DFIntBatchThumbnailMaxReqests": 4,
  "DFIntBatchThumbnailResultsSizeCap": 400,
  "DFIntHttpBatchApi_maxReqs": 16,
  "DFIntHttpBatchLimit": 256,
  "FFlagBatchGfxGui2": true,
  "FFlagFinishFetchingAssetsCorrectly": true,
  "FFlagEnableZeroLatencyCacheForVersionedAssets": true,
  "FFlagAnimationClipMemCacheEnabled": true,
  "FFlagRenderEnableGlobalInstancing3": true,
  "FIntRenderEnableGlobalInstancingD3D10Percent": 100,
  "FIntRenderEnableGlobalInstancingD3D11Percent": 100,
  "FIntRenderEnableGlobalInstancingVulkanPercent": 100,
  "FIntRenderEnableGlobalInstancingMetalPercent": 100,
  "FFlagEnablePrefetchTimeout": true,
  "DFFlagAddJobStartTimesExpiringPrefetch": true,
  "FFlagPrefetchOnEveryPlatform": true,
  "FFlagCacheRequestedMaxSize": true,
  "FFlagAudioAssetsInResizableCache2": true,
  "DFFlagCalculateKFSCachedDataEarly": true,
  "DFFlagEnablePerformanceControlSoundCache3": true,
  "DFFlagHttpCacheCleanBasedOnMemory": true,
  "DFFlagHttpCacheMissingRedirects": true,
  "FFlagSimCSG3MegaAssetFetcherSkipCached": true,
  "FFlagSimCSGV3CacheVerboseBSPMemory": true,
  "FFlagSimCSGV3CacheVerboseCanary": true,
  "FFlagSimCSGV3CacheVerboseOperation": true,
  "FFlagSimCSGV3CacheVerboseSeparateDealloc": true,
  "FFlagSimUseCSGV3TreeRule2Reduction": true,
  "FFlagSimCSGV3SeparateDetachedCoplanarGraphs": true,
  "FFlagSimCSGV3PruneNonManifoldVertexGraph": true,
  "FFlagSimCSGV3MeshFromCollarNilFragment": true,
  "FFlagSimCSGV3isPlaneValidBugFix": true,
  "FFlagSimCSGV3InitializeVertexMapFix": true,
  "FFlagSimCSGV3IncrementalTriangulationStreamingCompression": true,
  "FFlagSimCSGV3IncrementalTriangulationPhase3": true,
  "FFlagSimCSGV3IncrementalTriangulationPhase2": true,
  "FFlagSimCSGV3IncrementalTriangulationPhase1": true,
  "FFlagSimCSGV3EnableOperatorBodyPruning": true,
  "FFlagSimCSGV3AddIntersection": true,
  "FFlagSimCSGKeepPhysicalConfigData": true,
  "FFlagSimCSGAllowLocalOperations": true,
  "DFFlagSimCSG3UseQuadBallInExperience": true,
  "FFlagSimCSG3UseMovedBuilders": true,
  "FFlagSimCSG3NewAPIBreakApart": true,
  "FFlagSimCSG3EnableNewAPI": true,
  "FFlagSimCSG3AsyncWarmv2": true,
  "FFlagSimCSG3AllowBodyToSave": true,
  "FFlagCSGMeshDisableReadHash": true,
  "FFlagCSGMeshDisableWriteHash": true,
  "DFFlagCleanOldCSGData": true,
  "FFlagWrapDispatcherTickLimit": true,
  "FFlagGraphicsD3D11AllowThreadSafeTextureUpload": true,
  "FFlagGraphicsDeviceEvents": true,
  "FFlagGraphicsEnableD3D10Compute": true,
  "FFlagGraphicsTextureCopy": true,
  "FIntRenderD3D11UncleanShutdownPercent": 100,
  "FStringImmersiveAdsUniverseWhitelist": "0",
  "FFlagImmersiveAdsWhitelistDisabled": false,
  "FFlagAdGuiEnabled3": false,
  "FFlagEnableAdsAPI": false,
  "FFlagEnableBackendAdsProviderTimerService": false,
  "FFlagAdPortalEnabled3": false,
  "FFlagAdServiceEnabled": false,
  "FFlagEnableAdPortalTimerService2": false,
  "DFFlagEnableAdUnitName": false,
  "FFlagEnableAdGuiTimerService": false,
  "FFlagAdGuiTextLabelEnabled": false,
  "FFlagAdPortalAdFetchEnabled": false,
  "DFFlagAdGuiImpressionDisabled": true,
  "FIntEnableCullableScene2HundredthPercent": 500,
  "DFFlagAudioUseVolumetricPanning": true,
  "DFFlagAudioVolumetricUtilsRefactor": true,
  "DFFlagAudioEnableVolumetricPanningForMeshes": true,
  "DFFlagAudioEnableVolumetricPanningForPolys": true,
  "DFFlagAlwaysPutSoundsOnDiskWhenLowOnMemory": true,
  "FFlagRemoveMemoryApsGpu": true,
  "FFlagTrackAllDeviceMemory5": true,
  "FIntAbuseReportScreenshotMaxSize": 0,
  "DFIntCrashReportingHundredthsPercentage": 0,
  "DFIntCrashUploadErrorInfluxHundredthsPercentage": 0,
  "DFIntCrashUploadToBacktracePercentage": 0,
  "FFlagThreadCacheInit": true,
  "FFlagUpdateUICachesWithQuadTree3": true,
  "DFFlagExperimentalRuntimeTextureCreation": true,
  "FFlagFixGraphicsQuality": true,
  "FFlagCommitToGraphicsQualityFix": true,
  "FFlagFixTextureCompositorFramebufferManagement2": true,
  "FFlagMemoryPrioritizationEnabledForTextures": true,
  "FFlagTextureManagerMaySkipBlackReloadFallback": true,
  "FFlagTextureManagerUsePerfControl": true,
  "FFlagTextureManagerUsePerfControlDirectMapping": true,
  "FFlagTextureManagerUsePerfControlV2Api": true,
  "FFlagIntegrityCheckedProcessorUsePerfControl": true,
  "FFlagIntegrityCheckedProcessorPerfControlEffects": true,
  "FFlagIntegrityCheckedProcessorUsePerfControlV2Api": true,
  "FFlagPerfControlFireCallbacks2": true,
  "FFlagSoundServiceUsePerfControlV2Api": true,
  "FFlagPerformanceControlChangeTunableEagerly": true,
  "FFlagPerformanceControlDynamicUtilityCurves": true,
  "FFlagPerformanceControlMimicMemoryPrioritization": true,
  "DFFlagPerformanceControlProportionalPlanner": true,
  "DFFlagPerformanceControlProportionalPlannerForV2": true,
  "FFlagPerformanceControlSimpleMPLogic": true,
  "DFFlagESGamePerfMonitorEnabled": false,
  "DFIntESGamePerfMonitorHundredthsPercentage": 0,
  "FIntGamePerfMonitorPercentage": 0,
  "DFFlagEnablePerfAudioCollection": false,
  "DFFlagEnablePerfDataCoreCategoryTimersCollection2": false,
  "DFFlagEnablePerfDataCoreTimersCollection2": false,
  "DFFlagEnablePerfDataCountersCollection": false,
  "DFFlagEnablePerfDataGatherTelemetry2": false,
  "DFFlagEnablePerfDataMemoryCategoriesCollection2": false,
  "DFFlagEnablePerfDataMemoryCollection": false,
  "DFFlagEnablePerfDataMemoryPerformanceCleanup3": false,
  "DFFlagEnablePerfDataMemoryPressureCollection": false,
  "DFFlagEnablePerfDataReportThermals": false,
  "DFFlagEnablePerfDataSubsystemTimersCollection2": false,
  "DFFlagEnablePerfDataSummaryMode": false,
  "DFFlagEnablePerfRenderStatsCollection2": false,
  "DFFlagEnablePerfStatsCollection3": false,
  "FFlagRenderGpuTextureCompressor": true,
  "FFlagRenderLightGridEfficientTextureAtlasUpdate": true,
  "FFlagSkipRenderIfDataModelBusy": true,
  "DFIntRenderingThrottleDelayInMS": 100,
  "FFlagFontAtlasMipsAndRefactor": true,
  "FFlagAddFontAtlasMipmaps": true,
  "FFlagFixFontFamiliesNullCrash": true,
  "FFlagReadHSRAlwaysVisibleData": true,
  "FFlagApplyHSRAlwaysVisibleData": true,
  "FFlagLinearDeformerLocal": true,
  "FFlagEnableLinearCageDeformer2": true,
  "FFlagHSRClusterImprovement": true,
  "FFlagHSRRemoveDuplicateindices": true,
  "FFlagUseFallbackTextureStatusLoaded": true,
  "FFlagHumanoidDeferredSyncFunction5": true,
  "DFFlagHumanoidOnlyStepInWorkspace": true,
  "FFlagHumanoidParallelFasterSetCollision": true,
  "FFlagHumanoidParallelFasterWakeUp": true,
  "FFlagHumanoidParallelFixTickleFloor2": true,
  "FFlagHumanoidParallelOnStep2": true,
  "FFlagHumanoidParallelSafeCofmUpdate": true,
  "FFlagHumanoidParallelSafeUnseat": true,
  "FFlagHumanoidParallelUseManager4": true,
  "FFlagCloudsUseBC4Compression": true,
  "FIntClientCompressionFormatRequestPC": 3,
  "FFlagCloudsMvpForceNoHistory": true,
  "DFFlagThrottleDeveloperConsoleEvents": true,
  "FFlagFastGPULightCulling3": true,
  "FFlagDebugForceFSMCPULightCulling": true,
  "DFFlagSimIfNoInterp2": true,
  "DFFlagSimOptimizeInterpolationReturnPreviousIfSmallMovement2": true,
  "FFlagUseMediumpSamplers": true,
  "DFFlagClipMainAudioOutput": true,
  "DFFlagCollectibleItemInExperiencePurchaseEnabled": true,
  "DFFlagCollectibleItemInInspectAndBuyEnabled": true,
  "DFFlagFixUserInputServiceNotInitialized": true,
  "DFFlagIntegrateSendInPeer": true,
  "DFFlagLocServiceGetSourceLanguageFromWebAPI": true,
  "DFFlagPlayerConfigurer2886": true,
  "FFlagPlayerConfigurer2759": true,
  "DFFlagPredictedOOM": false,
  "DFFlagPredictedOOMAbs": false,
  "DFFlagPredictedOOMMessageKeepPlayingLeave": false,
  "FFlagBatchThumbnailFetcherTimedOutSupport": true,
  "FFlagFileMeshToChunks2": true,
  "FFlagKickClientOnCoreGuiRenderOverflow": false,
  "FFlagLuaAppSystemBar": true,
  "FFlagGraphicsGLTextureReduction": true,
  "FFlagFCCopyShadowVerticesFromWrapDeformer": true,
  "FFlagFCIgnoreDeformersNotReady2": true,
  "FFlagWriteFileMeshToChunks": true,
  "FFlagIxpPrefetchOnEveryPlatform": true,
  "DFFlagVoiceChatEnableEventCounters3": false,
  "DFFlagVoiceChatEnableEventLogging5": false,
  "DFFlagVoiceChatUnderrunErrorsTelemetry": false,
  "DFFlagVoiceChatHttpResultBodyEmptyTelemetry": false,
  "DFFlagVoiceChatAutoTest": true,
  "DFFlagVoiceChatFixJoinRetry": true,
  "DFFlagVoiceChatInputAudioSinkFix": true,
  "DFFlagVoiceChatRemoveDupesInQueuedSubs": true,
  "FFlagVoiceChatEnableBlockTelemetry": false,
  "FFlagVoiceChatReportTaskStats": false,
  "FFlagVoiceChatSignalRTimingCounterToStat": false,
  "FFlagVoiceChatStatsJoinSubsOnUsersError": false,
  "FFlagVoiceChatStatsMultistreamSubscriptionsV2": false,
  "FFlagVoiceChatWaitForSignalRJoinStageMetrics": false,
  "FFlagVoiceChatLockFreeBuffering3": true,
  "FFlagVoiceChatLockFreeEchoCancellation2": true,
  "FFlagVoiceChatLockFreeMixing": true,
  "FFlagVoiceChatUpdateSourcesOnSeparateThread": true,
  "FFlagVoiceChatUseCustomAudioDeviceProd6": true,
  "FFlagShrinkSpatialVoiceBuffers2": true,
  "DFLogHttpTrace": 0,
  "DFLogHttpTraceError": 0,
  "DFLogHttpTraceLight": 0,
  "DFFlagEnableHardwareTelemetry": false,
  "DFIntHardwareTelemetryHundredthsPercent": 0,
  "DFFlagEphemeralCounterInfluxReportingEnabled": false,
  "DFIntEphemeralCounterInfluxReportingPriorityHundredthsPercent": 0,
  "DFIntEphemeralCounterInfluxReportingThrottleHundredthsPercent": 100000,
  "DFIntEphemeralStatsInfluxReportingPriorityHundredthsPercent": 0,
  "DFIntEphemeralStatsInfluxReportingThrottleHundredthsPercent": 100000,
  "FFlagEnableFlagRolloutCrashReportingWindows": false,
  "DFFlagEnableTelemetryAppNameOverride": false,
  "DFIntLogFileTelemetryInfluxDbHundredthsPercentage": 0,
  "DFFlagBrowserTrackerIdTelemetryEnabled": false,
  "DFIntBrowserTrackerApiDeviceInitializeRolloutPercentage": 0,
  "DFIntBrowserTrackerIdTelemetryThrottleHundredthsPercent": 100000,
  "DFFlagDebugAnalyticsSendUserId": false,
  "DFStringAnalyticsEventStreamUrlEndpoint": "opt-out",
  "DFStringAltHttpPointsReporterUrl": "https://opt-out.roblox.com",
  "DFStringAltTelegrafHTTPTransportUrl": "http://opt-out.roblox.com",
  "DFStringTelegrafHTTPTransportUrl": "https://opt-out.roblox.com",
  "DFStringLmsRecipeEndpoint": "/opt-out",
  "DFStringLmsReportEndpoint": "/opt-out",
  "DFFlagEnableLightstepReporting2": false,
  "DFIntLightstepHTTPTransportHundredthsPercent2": 0,
  "DFStringLightstepHTTPTransportUrlHost": "https://opt-out.roblox.com",
  "DFStringLightstepHTTPTransportUrlPath": "/opt-out",
  "DFStringLightstepToken": "opt-out",
  "DFStringHttpPointsReporterUrl": "https://opt-out.roblox.com",
  "DFStringCrashUploadToBacktraceBaseUrl": "https://opt-out.roblox.com",
  "FStringErrorUploadToBacktraceBaseUrl": "https://opt-out.roblox.com",
  "DFStringRobloxAnalyticsSubDomain": "opt-out",
  "DFStringRobloxAnalyticsURL": "https://opt-out.roblox.com",
  "DFStringAnalyticsNS1ApplicationId": "opt-out",
  "DFStringAnalyticsNS1BeaconConfig": "https://opt-out.roblox.com",
  "DFFlagSendAllPhysicsPackets": true,
  "FFlagDebugGraphicsPreferD3D11": "True"
}`

**Comment by pizzaboxer** [comment]
Yeah, you're definitely using the RCO flags. Delete ClientAppSettings.json, and reopen the Bloxstrap menu to reconfigure any FastFlag mod presets you need.

**Comment by AIfaO** [comment]
Alright, thanks! So after deleting the json file from both of those places, and launching roblox again with Bloxstrap, I should be good to go?

**Comment by pizzaboxer** [comment]
Yeah. Don't forget to reconfigure any FastFlag settings you might need from inside the menu.
