### ISSUE TITLE
doesnt run[BUG] 

### ISSUE THREAD

**Issue by JanBDUser** [pizzaboxer/bloxstrap#1523]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it said an exception occured while running bloxstrap
[Bloxstrap_20240330T101347Z.log](https://github.com/pizzaboxer/bloxstrap/files/14811499/Bloxstrap_20240330T101347Z.log)

**Comment by pizzaboxer** [comment]
Download the installer to your Downloads folder first before running it, instead of running it directly from your browser.
