### ISSUE TITLE
Bloxstrap.. Won't work??

### ISSUE THREAD

**Issue by Sebbooster** [pizzaboxer/bloxstrap#1524]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My issue is that bloxstrap simply doesn't work. When I click on the application to install it, nothing opens. When I try to open the menu nothing happens. When I deleted all my files related to roblox, and reinstalled roblox, it worked just fine, but when I attempted to reinstall bloxstrap, I was unable to, even using the CMD prompt with winget. I was using bloxstrap months prior to this, and this issue has only happened today. If possible, look into this. Im not sure why this is happening.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?
