### ISSUE TITLE
[BUG] Create Desktop Icon

### ISSUE THREAD

**Issue by AsianMyAsians** [pizzaboxer/bloxstrap#1525]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When launching Roblox; "Create Desktop Icon" deactivates.

**Comment by pizzaboxer** [comment]
Yes, because the desktop icon has been created at that point.

**Comment by AsianMyAsians** [comment]
I am sorry, but how do I make the Roblox icon from grouping in my taskbar when I launch two accounts?

**Comment by pizzaboxer** [comment]
Are you asking how to **stop it** from grouping? You can't, you'll have to do that in your Windows taskbar settings.
