### ISSUE TITLE
fps menu

### ISSUE THREAD

**Issue by xyrie1** [pizzaboxer/bloxstrap#1526]
how to hide fps menu?

**Comment by pizzaboxer** [comment]
What do you mean by "fps menu"?

**Comment by xyrie1** [comment]
like the fps counter

**Comment by pizzaboxer** [comment]
What fps counter? Show a screenshot of it please.

**Comment by xyrie1** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/125039979/ddbd2ba3-c7b9-47e3-add3-4de93642450c)
 this

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags

Read the warning at the top and clear your entire flag list please.
