### ISSUE TITLE
FPS gets lower overtime

### ISSUE THREAD

**Issue by SmartaintSmart** [pizzaboxer/bloxstrap#1527]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

during my time using bloxstrap, I encountered a problem. I set my fps to 120, it worked splendidly. But as time went by, the fps dropped lower and lower reaching about 50 fps averagely. I do not understand why this is happening. probably because of my potato pc.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
