### ISSUE TITLE
launch args

### ISSUE THREAD

**Issue by MappleGaming208** [pizzaboxer/bloxstrap#1528]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

How does the launch args work in custom integrations? i can t find any use pls tell how to use them

**Comment by pizzaboxer** [comment]
Launch args are more commonly known as "command line arguments". They're entirely optional and you do not need to fill out the field unless necessary.
