### ISSUE TITLE
[BUG]  System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by adsihateem** [pizzaboxer/bloxstrap#1529]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

installing and then : System.Exception: Signature does not match!

**Comment by adsihateem** [comment]
.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox

Respond if you have any further questions.
