### ISSUE TITLE
Breaks Deeplinking

### ISSUE THREAD

**Issue by Jintenzo** [pizzaboxer/bloxstrap#153]
Whenever Bloxstrap is installed, [Deeplinking](https://devforum.roblox.com/t/developer-deeplinking-beta/1904069) (specifically Link 2) no longer works. It still opens the Bloxstrap window and does the whole startup thing, but it doesn't actually open Roblox.

**Comment by pizzaboxer** [comment]
Weird, since if the first one works then the second one should work too. Link 2 works fine for me. Does Link 1 still work fine?

**Comment by Jintenzo** [comment]
Neither work for me, Link 1 doesn't even work without Bloxstrap

**Comment by pizzaboxer** [comment]
Just to check if this is a problem with the URI not registering properly, can you please open the registry editor and go to `HKEY_CURRENT_USER\SOFTWARE\Classes\roblox\shell\open\command` and show me what's there?

**Comment by Jintenzo** [comment]
![image](https://user-images.githubusercontent.com/68517696/234263359-242085be-6ade-4fe3-b4b7-cc308ac3e790.png)

**Comment by pizzaboxer** [comment]
You mentioned that Bloxstrap still starts up at least. Just so I can get some more logs, replace Bloxstrap.exe in the Bloxstrap folder with this.

[Bloxstrap.exe](https://pizzaboxer.xyz/files/bloxstrap-debug/153/Bloxstrap.exe)

Once you've tried to launch a deeplink, get the latest Bloxstrap log file and send it to me privately, not here. (pizzaboxer#7142 on Discord if you want to do it that way)

**Comment by pizzaboxer** [comment]
Whoops, I completely forgot about something, which @bluepilledgreat just pointed out to me. You don't happen to have this setting enabled, do you?

![image](https://user-images.githubusercontent.com/41478239/234387158-bd450bc0-928e-4b85-a791-4099f37009d3.png)

**Comment by Jintenzo** [comment]
Yep, it works after I disable that, would be nice to be able to use deeplinking without the desktop app though (no idea if that's possible)

**Comment by pizzaboxer** [comment]
Just wondering, is there actually much reason to use this? Roblox has been giving the choice to return back to the desktop app or close the window when you try to exit for a while now.

**Comment by Jintenzo** [comment]
Use what? Deeplinking, the desktop app, or the setting?

**Comment by pizzaboxer** [comment]
Using the disable desktop app setting.

**Comment by pizzaboxer** [comment]
Okay, I see. I'll add a notice for it then.
