### ISSUE TITLE
[BUG] Future (Phase 3) making things turn green all of the sudden.

### ISSUE THREAD

**Issue by LizardFelandia** [pizzaboxer/bloxstrap#1530]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So I use Bloxstrap on my Windows 11 laptop and when I went onto roblox, things were turning green. 
Things would turn green like icons, a 1 second green flash inbetween motions like when the screen changes., and the lightning in the game would appear to be green.
I figured out that it was something with Future Is Bright (Future Phase 3) and when I turned it off, things werent turning green anymore.
Here is some screenshots that I took:
![SM1thbT 1](https://github.com/pizzaboxer/bloxstrap/assets/165609697/d9bd45b4-dbb4-42e3-942c-94d875529663)
![2dWTV2Q 1](https://github.com/pizzaboxer/bloxstrap/assets/165609697/d0decaa9-4fa6-4666-9a8a-8b01a9ed80d8)
(Don't mind the game im playing)

(It's not doing this anymore, i think it mustve been my grapics card)

**Comment by pizzaboxer** [comment]
That definitely looks like a GPU problem.
