### ISSUE TITLE
[BUG] Game close itself after a certain time

### ISSUE THREAD

**Issue by khaledDaGreat** [pizzaboxer/bloxstrap#1531]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i have this issue where my game keeps closing for some reason after a certain period for time 
if anyone knows a fix

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by khaledDaGreat** [comment]
i might've found a fix deleting the oculus app worked for me and had nothing to do with bloxstrap sorry for the inconvient

**Comment by pizzaboxer** [comment]
Interesting, I'll note that down. Thanks for the information.
