### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MaCrO09** [pizzaboxer/bloxstrap#1532]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever i join a game with bloxstrap and the "see server location when joining a game" enabled it now says "N/A (lookup failed)", but just yesterday it was working, ive tried uninstalling reinstalling and it wont work 
![image](https://github.com/pizzaboxer/bloxstrap/assets/86578089/765f8ece-791e-477a-8c06-de32c6a84dd8)

**Comment by pizzaboxer** [comment]
We fetch server information from https://ipinfo.io. It was briefly down, it's back up now.
