### ISSUE TITLE
[BUG] Server regions not being detected

### ISSUE THREAD

**Issue by iwantmyaccountback** [pizzaboxer/bloxstrap#1533]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The server region detect feature is outdated/bugged. it no longer finds the server region.
![image_2024-04-01_105117982](https://github.com/pizzaboxer/bloxstrap/assets/86072395/36bd88da-7d55-4398-b35b-6801f4057007)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/issues/1532#issuecomment-2029577688
