### ISSUE TITLE
[BUG] When launching roblox from bloxstrap, it freezes into a white screen.

### ISSUE THREAD

**Issue by 3243F** [pizzaboxer/bloxstrap#1534]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I open bloxstrap with a font mod added, it freezes into a white screen but without the font mod, it opens no problem.

**Comment by pizzaboxer** [comment]
If you had actually read the preliminary instructions and read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch, you would have found out why this is happening. Find a different font.
