### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Josh830-lab** [pizzaboxer/bloxstrap#1535]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: The requested address is not valid in its context. (clientsettings.roblox.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: The requested address is not valid in its context.
Every time I attempt to connect to Roblox using bloxstrap specifically, uninstalling bloxstrap allows me to connect to roblox fine and now on attempting to install bloxstrap I get the same error
https://clientsettingscdn.roblox.com returns "{"message":"OK"}"

**Comment by pizzaboxer** [comment]
Your antivirus or some other application on your computer is preventing Bloxstrap from connecting to the internet.

**Comment by Josh830-lab** [comment]
Disabling windows defender Realtime protection, adding the .exe as an exclusion, and allowing it through firewall with a special rule did not fix the issue.
