### ISSUE TITLE
[BUG] Multi-instances doesn't work and I can't switch roblox accounts after ban

### ISSUE THREAD

**Issue by aniiar** [pizzaboxer/bloxstrap#1536]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After logging out of the banned account on the roblox website, it doesn't let me launch roblox from another account. 
I have multi-instances on, but recently it has not been working, maybe that's the issue? (I don't know how to fix multi-instances not working.)

![image](https://github.com/pizzaboxer/bloxstrap/assets/165697169/c634ab15-6d88-4a31-9af5-ea247f42cac8)

**Comment by LeahMinhe** [comment]
I am having the same issue..

**Comment by pizzaboxer** [comment]
> After logging out of the banned account on the roblox website, it doesn't let me launch roblox from another account.

Are you able to log out of the desktop app first?

**Comment by aniiar** [comment]
My friend helped me fix it. Thanks to Elia x
