### ISSUE TITLE
[BUG] Bloxstrap broken after being banned

### ISSUE THREAD

**Issue by the9655a** [pizzaboxer/bloxstrap#1537]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, my brother got banned for a few days from roblox. After logging into a different account, trying to load bloxstrap shows this error.
![image](https://github.com/pizzaboxer/bloxstrap/assets/149513282/42c5e2fd-5187-4378-81b7-d2f85d39b93b)

The issue here is that the roblox desktop app is still logged in using the banned account, so you have to open it, and manually log out. Doing this fixes the issue.

However, this creates another problem. All your roblox settings reset and now, one of the bloxstrap settings doesnt seem to work and I'm not sure how to fix it.
![image](https://github.com/pizzaboxer/bloxstrap/assets/149513282/e46a501e-1527-4603-84ec-846f438f4139)

As you can see, the UI is unchanged despite having the setting there and saved correctly.

**Comment by pizzaboxer** [comment]
> So, my brother got banned for a few days from roblox. After logging into a different account, trying to load bloxstrap shows this error.

This is an issue with Roblox itself.

> As you can see, the UI is unchanged despite having the setting there and saved correctly.

https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
