### ISSUE TITLE
Multi Roblox

### ISSUE THREAD

**Issue by HEIl0W0RID** [pizzaboxer/bloxstrap#1539]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The multi Roblox instance feature doesn't work.

**Comment by pizzaboxer** [comment]
In what way does it not work? What happens when you try to use it?

**Comment by KlaikzCat** [comment]
Same issue. When trying to open another instance is just closes the other one, I have the multi instance option on.

**Comment by pizzaboxer** [comment]
> Same issue. When trying to open another instance is just closes the other one, I have the multi instance option on.

When you launch Roblox, do you see the Bloxstrap launcher show beforehand?

**Comment by KlaikzCat** [comment]
> > Same issue. When trying to open another instance is just closes the other one, I have the multi instance option on.
> 
> When you launch Roblox, do you see the Bloxstrap launcher show beforehand?

Seems to be working now, when it works it does open the Bloxstrap launcher. I believe that when it wasn't working that the Bloxstrap launcher wasn't opening the second instance.
