### ISSUE TITLE
Add alternative ways to show server details than relying on inconsistent Windows notification

### ISSUE THREAD

**Issue by IllusionZG** [pizzaboxer/bloxstrap#154]
well sometimes when you serverhop too fast it won't notify at all :\

**Comment by pizzaboxer** [comment]
I mean, there's not much other way to show show a notification. Though, I'll check if the problem is the notifications not showing for long enough, or if there's a problem with game activity detection. Currently the notifications have a 10 second timeout.

**Comment by Weeb1e** [comment]
sometimes it doesnt even work for me at all

**Comment by pizzaboxer** [comment]
Do you sometimes have Roblox in full screen mode?

**Comment by Empyrlum** [comment]
> Do you sometimes have Roblox in full screen mode?

yea

**Comment by Empyrlum** [comment]
> Windows notifications don't show when you're in full screen.

Could you use an alternative to display server locations??

**Comment by pizzaboxer** [comment]
I can't really think of any alternative, toast notifications are basically the best solution to this, and I guess it makes sense why they don't show in fullscreen.

**Comment by zachariapopcorn** [comment]
Sometimes the toast doesn't pop up at all
