### ISSUE TITLE
[BUG] Bloxstrap new instance memory issue

### ISSUE THREAD

**Issue by Eikereis** [pizzaboxer/bloxstrap#1540]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've noticed my ram increase slowly whilst using bloxstrap and after checking task manager I see 100+ bloxstrap instances using 3-50 mb's of Ram. 

Note: I'm using a python script to teleport into roblox places that have welcome badges, since im badge grinding, and it opens a new instance of bloxstrap to smoothly teleport. Unfortunately it doesnt seem like it fully closes the previous instance or something like that.
![Screenshot_100](https://github.com/pizzaboxer/bloxstrap/assets/145643947/b4949f2a-7675-4b9a-adcc-55dfc55f8ea1)

**Comment by pizzaboxer** [comment]
Do you have the option to run multiple instances enabled?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
