### ISSUE TITLE
I don't have a Cursor or textures folder in my content folder[BUG] 

### ISSUE THREAD

**Issue by bobwastaken123** [pizzaboxer/bloxstrap#1542]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't have a Cursor or textures folder in my content folder 
![image_2024-04-01_201151023](https://github.com/pizzaboxer/bloxstrap/assets/165734513/7bf83f6b-a840-4215-8511-afa1dfaf1742)

**Comment by bobwastaken123** [comment]
if i accidently deleted it is there a way to get it back please try sending a textures content folder

**Comment by pizzaboxer** [comment]
You need to make the folders.

https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/3f9726e1-5a9e-400b-acbd-6d17431f1d5e)

**Comment by sandallruby13-glitch** [comment]
if youve learnt how to do it please tell me!:D

**Comment by nabheyka880** [comment]
just make a Cursors folder
what problem are you having
