### ISSUE TITLE
[BUG] High ping after installation

### ISSUE THREAD

**Issue by Tele4achus** [pizzaboxer/bloxstrap#1545]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i use bloxtrap my ping becomes very high (200+), without bloxtrap the ping is back to 80-90.
How do i fix this. ( i already tried putting 0 on the fps unlocker and nothing changed)

**Comment by Freelopin** [comment]
fps is not related to ping. Try 60 fps and see if it works.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Tele4achus** [comment]
> Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

actually it got fixed automatically idk what happened but thank you for the reply and sorry for wasting your time
