### ISSUE TITLE
[BUG]  the 2015 gui not working 

### ISSUE THREAD

**Issue by Jack122234** [pizzaboxer/bloxstrap#1546]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Script is right but 2015 meun is not working

**Comment by pizzaboxer** [comment]
Are you sure you have it configured correctly? Upload your configuraton please (you only need to upload ClientAppSettings.json): https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by Jack122234** [comment]
Is fine now is working when I download roshade and uninstall it.
