### ISSUE TITLE
[question] High Priority, how do you do it?

### ISSUE THREAD

**Issue by Kixbiles** [pizzaboxer/bloxstrap#1547]
usually if you want better performance in your games you simply go to task manager > details, find the Roblox process and enable high priority, BUT this is somewhat my first time using bloxstrap, and i wanna do the high priority thing with it. which leads me to my question;

how does one use high priority with bloxstrap?

**Comment by pizzaboxer** [comment]
> how does one use high priority with bloxstrap?

You do the exact same thing.
