### ISSUE TITLE
Fucked up my ROBLOX website. 

### ISSUE THREAD

**Issue by adask12** [pizzaboxer/bloxstrap#1548]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox site was fine, but I wanted above 60fps, and an FPS Unlocker wasn't working, so I decided to try this. Installed it, boom, DNS error. Uninstalled, boom, DNS Error. Either Bloxstrap has fucked up my DNS, or this is very fucking coincidental timing.

**Comment by adask12** [comment]
Update: Now even the Desktop App wont open.

**Comment by axellse** [comment]
This is not a bloxstrap issue, but if your having dns issues, consider switching your dns to something like Cloudflare (1.1.1.1) or Google (8.8.8.8)

**Comment by adask12** [comment]
> This is not a bloxstrap issue, but if your having dns issues, consider switching your dns to something like Cloudflare (1.1.1.1) or Google (8.8.8.8)

I'm saying this as its only coincidentally happened after installing Bloxstrap.

**Comment by adask12** [comment]
Just tried to reinstall Roblox, and its still fucked up.

**Comment by axellse** [comment]
You need to do a dns flush

**Comment by adask12** [comment]
> You need to do a dns flush

Just tried, its still gone.

**Comment by pizzaboxer** [comment]
Are you the same person who opened this Discord thread? https://discord.com/channels/1099468797410283540/1225066553502994462

If so, then I'd prefer to help you there instead so I can figure out what's going on.

**Comment by pizzaboxer** [comment]
i'll close this thread since we've now established that it's not really a Bloxstrap issue.
https://github.com/pizzaboxer/bloxstrap/wiki/DNS-and-connectivity-issues-with-the-Roblox-Game-Client-or-Launcher
