### ISSUE TITLE
Dont download this fucking shit.

### ISSUE THREAD

**Issue by adask12** [pizzaboxer/bloxstrap#1549]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My roblox is now completely fucked up because of Bloxstrap. This "DNS Issue" was caused after downloading Bloxstrap.
These "DNS Resolving issues" Haven't worked and have probably fucked up my ROBLOX more.

**Comment by axellse** [comment]
Unless pizza knows of something new that could have caused this, please stop making issues here. This is almost certainly not an issue with bloxstrap.
