### ISSUE TITLE
Suggestion: FPS and Ping counter

### ISSUE THREAD

**Issue by iamprorororoorororororororro** [pizzaboxer/bloxstrap#155]
add an fps and ping counter in the corners of the screen

**Comment by pizzaboxer** [comment]
shift + f5 for fps, ctrl + shift + f7 for ping, or enable it in the settings menu

**Comment by iamprorororoorororororororro** [comment]
i was thinking of more like a small fps counter, like not one that blocks half your screen or prevents you from seeing certain things

**Comment by pizzaboxer** [comment]
just use fraps or something then

**Comment by iamprorororoorororororororro** [comment]
what about ping?

**Comment by pizzaboxer** [comment]
the only way is the gui overlay
