### ISSUE TITLE
[BUG] FPS capped at 60

### ISSUE THREAD

**Issue by tskdead** [pizzaboxer/bloxstrap#1551]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hi my fps still remains capped at 60 fps despite using the proper FFlags and pc settings. Could someone help me? 

I have done every step that is mentioned in this link and it still does not work: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter 

Here are the FFlags I use: 
![Screenshot_17](https://github.com/pizzaboxer/bloxstrap/assets/66751827/9e86ba3a-9f8a-4c05-a019-fc388ac7cc74)
![Screenshot_16](https://github.com/pizzaboxer/bloxstrap/assets/66751827/a5e61eaf-381e-4a7f-9a96-777fc2c8af6b)
![Screenshot_15](https://github.com/pizzaboxer/bloxstrap/assets/66751827/cbfbcc5c-c627-4a1d-b46f-055a91911418)
![Screenshot_14](https://github.com/pizzaboxer/bloxstrap/assets/66751827/93c602f2-08b3-4875-87c6-a1cef3db8736)

**Comment by tskdead** [comment]
> Do you notice any of your other options applying?

Yes, my other options were applying.

**Comment by pizzaboxer** [comment]
What GPU do you have?

**Comment by tskdead** [comment]
> What GPU do you have?

3050 ti

**Comment by pizzaboxer** [comment]
Open the NVIDIA Control Panel, go to 'Manage 3D Settings', and check to see if 'Max Frame Rate' has been configured
