### ISSUE TITLE
bloxstrap just straight up not applying my mods? [BUG] 

### ISSUE THREAD

**Issue by drogdaw** [pizzaboxer/bloxstrap#1553]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It's been installed correctly, and the launcher has been working. Its just when I launch Roblox, nothing happens. There isn't a change in font or sound of the death noise. And my configs are down below. 

[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/14863575/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/14863576/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/14863581/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
> Its just when I launch Roblox, nothing happens. 

Can you check to make sure that Roblox isn't already running in the background?

**Comment by Xantory** [comment]
I can confirm I have the same issue, mods won't work, I tried uninstalling Bloxstrap but nothing works.
Also made sure Roblox wasn't running in the background before that but still not, perhaps Roblox made an update that prevents Bloxstrap from working?

**Comment by PR0WN3D** [comment]
having this same issue as well right now

**Comment by disisnotacord** [comment]
Same thing is happening to me

**Comment by pizzaboxer** [comment]
For you three above, read sections 2 and 3 of this Wiki page: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter

Let me know if things still don't work.

**Comment by movieslol** [comment]
same here :(

**Comment by pizzaboxer** [comment]
> same here :(

**Comment by relgrowths** [comment]
ive done everything it's told me to and it still doesn't apply my mods

**Comment by pizzaboxer** [comment]
> ive done everything it's told me to and it still doesn't apply my mods

Get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` (either at the top or bottom) and send it here please

**Comment by relgrowths** [comment]
[Bloxstrap_20240504T023150Z.log](https://github.com/pizzaboxer/bloxstrap/files/15206404/Bloxstrap_20240504T023150Z.log)

**Comment by pizzaboxer** [comment]
`2024-05-04T02:31:51Z [Bootstrapper::ApplyModifications] Roblox is running, aborting mod check`

Are you sure you did everything?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
