### ISSUE TITLE
[BUG] Framerate option does not uncap framerate

### ISSUE THREAD

**Issue by TheGlitchTester** [pizzaboxer/bloxstrap#1555]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

If I try and set the framerate option to anything other than zero (I tried 9999, 999, 500, and 240) and hit save, the next time I join the game it remains capped at 60 fps despite what I have set it to.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by pizzaboxer** [comment]
> nor had I been able to find it when I did a quick search prior to posting the issue. 

Read the preliminary instructions next time before you open an issue.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/0be65a22-8b6b-474a-beee-7307cba4720c)
