### ISSUE TITLE
[BUG] i was playing dahood and i just pulled out a gun and it straight up fucking freezes my whole pc i got good pc tho intel i5 cpu 16 ram nvidia gtx 1650

### ISSUE THREAD

**Issue by uaintmycomp** [pizzaboxer/bloxstrap#1556]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

i just want to know how to fix it

**Comment by pizzaboxer** [comment]
Does this happen consistently/repeatedly?

**Comment by uaintmycomp** [comment]
every time like i join any game like dahood it just does the thing

**Comment by uaintmycomp** [comment]
so its repeatedly

**Comment by WaviestBalloon** [comment]
> every time like i join any game like dahood it just does the thing

Does this happen on different games that are not Da Hood?

**Comment by uaintmycomp** [comment]
i tested it in games that are like dahood but i have not tested in like arsenal or phantom forces or something

**Comment by uaintmycomp** [comment]
ima test it rn

**Comment by uaintmycomp** [comment]
arsenal works i think its just dahood based games

**Comment by pizzaboxer** [comment]
> so its repeatedly

Does it happen with the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by uaintmycomp** [comment]
> > so its repeatedly
> 
> Does it happen with the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

ima try rn

**Comment by uaintmycomp** [comment]
> > so its repeatedly
> 
> Does it happen with the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

crashes on normal rblx too

**Comment by WaviestBalloon** [comment]
> crashes on normal rblx too

So it's most likely Da Hood that's the issue, I would contact the developers of the game, this doesn't seem like a Bloxstrap issue at all

**Comment by uaintmycomp** [comment]
> > crashes on normal rblx too
> 
> So it's most likely Da Hood that's the issue, I would contact the developers of the game, this doesn't seem like a Bloxstrap issue at all

k
