### ISSUE TITLE
[BUG] Ban issue

### ISSUE THREAD

**Issue by Zhulcia** [pizzaboxer/bloxstrap#1557]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

got banned and it won't let me logout or press anything
![image](https://github.com/pizzaboxer/bloxstrap/assets/166075821/549c6bab-3cde-4d89-b6b0-d4bc9c2054ee)

**Comment by Profility** [comment]
This is not a problem/issue that is caused by Bloxstrap.

**Comment by Findyourlimit** [comment]
Try restarting/re-installing

**Comment by pizzaboxer** [comment]
> got banned and it won't let me logout or press anything

We've had similar reports of this. Just so I can quickly get you to debug this before you're unbanned, can you upload your configuration please? https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration
