### ISSUE TITLE
[BUG] bloxstrap saying error 401 unauthorized

### ISSUE THREAD

**Issue by Zane2tuff** [pizzaboxer/bloxstrap#1558]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have installed a roblox cheat and it says to change the channel inside of behavior to zbeta and when I type this in it shows “Failed to fetch information! (HTTP 401 - unauthorized)” any fix?
![Uploading image.jpg…]()

**Comment by Zane2tuff** [comment]
![Screenshot 2024-04-04 182255](https://github.com/pizzaboxer/bloxstrap/assets/166078333/4e41ef8c-e90f-49d4-93ef-ec52f8dccc51)
![Screenshot 2024-04-04 181619](https://github.com/pizzaboxer/bloxstrap/assets/166078333/5bcc5642-36df-4b32-a11b-218bf876c091)

**Comment by Findyourlimit** [comment]
The channels are locked down, therefore you cannot use them
Why are you even hacking anyway?

**Comment by pizzaboxer** [comment]
lmao

**Comment by regginator** [comment]
Least obvious cheat user (they just directly mention they're using a cheat)
