### ISSUE TITLE
[BUG] Bloxstrap crashing roblox (Literally not letting me play)

### ISSUE THREAD

**Issue by NoobCola2** [pizzaboxer/bloxstrap#1559]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Tried to play without blockstrap and everything started, but with it, it crashes at the loading stage

**Comment by southernray** [comment]
yea it just loading 
![image](https://github.com/pizzaboxer/bloxstrap/assets/166115116/15035deb-3d13-42e5-93d2-1432f0e629d6)
and after that it doesnt launch anything, checked the task manager and i think it crashed too

**Comment by pizzaboxer** [comment]
You've read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch, right?

**Comment by southernray** [comment]
read it recently, i tried methods that is close to my problem like closing gpu tweaks and cleanin cache but non of em work. earlier,  i tried roblox again without bloxstrap and it work perfectly fine, but one thing i always notice when updating roblox or installing is this 
![image](https://github.com/pizzaboxer/bloxstrap/assets/166115116/ff5f1af0-04df-40db-a677-163070011cde)

**Comment by NoobCola2** [comment]
I did the same

**Comment by pizzaboxer** [comment]
Both of you two, upload your configuration please:

https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by NoobCola2** [comment]
Ig just website bug or something like this

**Comment by NoobCola2** [comment]
I"m able to use app

**Comment by southernray** [comment]
wait actually yea i can use it again, just incase im gonna send it
https://drive.google.com/file/d/1FwJeSWVrAE9jkt2T8iOMTNV0EaKziOrL/view?usp=sharing

**Comment by pizzaboxer** [comment]
> wait actually yea i can use it again, just incase im gonna send it

Your configuration looks fine, let me know if you still encounter any problems.

@NoobCola2 Can you please clarify?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
