### ISSUE TITLE
[BUG] Bloxstrap was working fine earlier today, and now its crashing?

### ISSUE THREAD

**Issue by Ga1axy2109** [pizzaboxer/bloxstrap#1561]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't know what happened, but i am getting a crash from bloxstrap, before its even trying to launch Roblox. yes, i tried Roblox without bloxstrap and it worked fine. every time i use bloxstrap, it loads for like 2 seconds, then crashes. also the error report says the following.
System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\(my user for my pc)\AppData\Local\Bloxstrap\Versions\version-8764cc9c84a5459a\RobloxPlayerBeta.exe' with working directory 'C:\Windows\system32'. The specified executable is not a valid application for this OS platform.
i have tried clearing cache, reinstalled bloxstrap and roblox, rebooting my pc, clearing temp files, and changing some settings in the bloxstrap menu.
[Bloxstrap_20240406T035538Z.log](https://github.com/pizzaboxer/bloxstrap/files/14892251/Bloxstrap_20240406T035538Z.log)

**Comment by pizzaboxer** [comment]
That seems like your antivirus interfering with Bloxstrap. Check to make sure there isn't anything like that going on.

**Comment by Ga1axy2109** [comment]
Thanks for the response, but after some testing with windows antivirus settings, and fully turning it off, it still didnt load.
might be somthing with windows files???

**Comment by pizzaboxer** [comment]
No, there's definitely something interfering and preventing from Bloxstrap from launching it. 

Just to verify, open the path at `%localappdata%\Bloxstrap\Versions\version-8764cc9c84a5459a\`, and see if you can run RobloxPlayerBeta directly.

**Comment by Ga1axy2109** [comment]
I found the file, but when i try to run it windows throws an error saying 
"This file cant run on your pc"
"to find a version for your pc, check with the software publisher"
so im guessing its a compatibility issue? but im on the most recent ver of windows 10.

**Comment by Ga1axy2109** [comment]
also the file size is zero bytes??
