### ISSUE TITLE
 crashing

### ISSUE THREAD

**Issue by wexxxzzz** [pizzaboxer/bloxstrap#1562]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i launch bloxtraproblox it says that i have crashed any help please?

**Comment by pizzaboxer** [comment]
Have you checked to see if this happens only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
