### ISSUE TITLE
The Desktop bloxstrap shortcut got turned into random gibberish

### ISSUE THREAD

**Issue by Kronton1** [pizzaboxer/bloxstrap#1564]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Today I accessed my PC, everything was fine blah blah (also I used Bloxtrap) when later I did a "full" shutdown and restarted my PC the Bloxstrap shortcut got turned into random gibberish, images for more info (before it was simply named "Play Roblox" and I searched online for anything similar but I can't find a explanation there)(and "glitch info 3" the one with the censored pc name was cuz maybe its sensitive info?)(and I still didn't open it yet cause of fear)(YES I could just rename it but its kinda weird and shady that such a random thing just happened)
![glitch info3](https://github.com/pizzaboxer/bloxstrap/assets/116302157/b8c1c217-d27e-4a42-9606-478174a6fee7)
![glitch info2](https://github.com/pizzaboxer/bloxstrap/assets/116302157/3b5c5777-ed8b-4459-84bc-2de03e8305f8)
![glitch info1](https://github.com/pizzaboxer/bloxstrap/assets/116302157/297588c1-7cc0-4cab-ae08-b5f0485def18)
![glitch focused](https://github.com/pizzaboxer/bloxstrap/assets/116302157/b26053ba-fe62-4d1c-a1ba-98d58a944f03)

**Comment by Bruhdoas** [comment]
I am confident that a uninstall and reinstall would fix.

**Comment by pizzaboxer** [comment]
Bloxstrap itself definitely didn't cause that, and I'm even more puzzled by why it's showing the wrong icon. Are you certain you didn't just do that accidentally, especially given that they're all alphanumeric characters?

You can restore the icon by opening the Bloxstrap Menu, going to the Behaviour tab, and enabling the "Create desktop icon" option.
