### ISSUE TITLE
Request for Bloxstrap

### ISSUE THREAD

**Issue by Bruhdoas** [pizzaboxer/bloxstrap#1565]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Is it possible there can be a vs of Bloxstrap that doesn't require Admin rights?

**Comment by pizzaboxer** [comment]
> Is it possible there can be a vs of Bloxstrap that doesn't require Admin rights?

It doesn't require admin rights though. The only reason you'd need admin rights is to install the .NET runtime, which is one-time only, and you can't really get around.

**Comment by Bruhdoas** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/100976640/01a7e6bb-036f-45fd-9b82-69a96aee0b0d)

**Comment by pizzaboxer** [comment]
That seems like something is trying to prevent you from launching it. Check your antivirus, or anything else that could be doing that.
