### ISSUE TITLE
[BUG]  FPS Unlocker within Bloxstrap won't work.

### ISSUE THREAD

**Issue by AllanDevv** [pizzaboxer/bloxstrap#1567]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've reinstalled Bloxstrap many times and keep encountering the same issue. The FPS will not unlock even if i mess around with the cap limit.
![image](https://github.com/pizzaboxer/bloxstrap/assets/95610650/247dc787-10b8-433c-84f7-3df4284f0ba5)

**Comment by adask12** [comment]
Check your monitors refresh rate. It may be that you monitor is capped at 60Hz.

**Comment by AllanDevv** [comment]
> Check your monitors refresh rate. It may be that you monitor is capped at 60Hz.

![image](https://github.com/pizzaboxer/bloxstrap/assets/95610650/640ea826-0ad9-4867-87f9-ca18bb92dd81)
I assure that's not the issue.

**Comment by TheMetalTechnet** [comment]
You might be launching roblox without bloxstrap, try using "Play Roblox" shortcut

**Comment by AllanDevv** [comment]
> You might be launching roblox without bloxstrap, try using "Play Roblox" shortcut

![image](https://github.com/pizzaboxer/bloxstrap/assets/95610650/63977f92-b2a3-4fd8-af23-db1406456689)
Issue resolved, thank you!
