### ISSUE TITLE
adicionar o blox trap pra windos 32 bit

### ISSUE THREAD

**Issue by RFZN131** [pizzaboxer/bloxstrap#1572]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

*colocar o blox trap pra windos 32 bits ira ajudar muito as pessoas que nao tem windos 64 bits*

**Comment by pizzaboxer** [comment]
Roblox itself doesn't work on 32-bit systems anymore.
