### ISSUE TITLE
bug when you change into another game while in a game it says failed id 17

### ISSUE THREAD

**Issue by nelabu1** [pizzaboxer/bloxstrap#1573]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

while playing deepwoken when i get through the luminant gates (the ones that transport you to another game) and when i click the exit button (not the roblox one) to get sent to th emain menu i encounter failed id 17 and when i turn of bloxstrap everything is ok please fix it

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
