### ISSUE TITLE
After the Bloxtrap Installation my Bloxtrap menu launcher just dissapeared and I don't know what to do, I tried different methods like searching it up on my Windows searchbar neither my file folders there was non of my Bloxtrap menu launcher to be found.

### ISSUE THREAD

**Issue by SKYLIGHT2024** [pizzaboxer/bloxstrap#1574]
Pls can someone or the Creator of Bloxtrap fix this issue?

**Comment by SKYLIGHT2024** [comment]
Also I only have the Game launcher after the download but never got the Menu launcher back,

**Comment by SKYLIGHT2024** [comment]
I tried other options in order to delete the launcher fully with control panel after downloading It again the Menu launcher came back once but never came back after I Install it.

**Comment by pizzaboxer** [comment]
If you look through your application list, is it not there under the folder?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/506e6a75-7111-4be7-9890-b3be3a9e45e7)

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
