### ISSUE TITLE
[REQ] Automatically adjust graphics quality on launch

### ISSUE THREAD

**Issue by DevKilo1** [pizzaboxer/bloxstrap#1575]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

If Bloxstrap could launch Roblox with a lowered graphics quality for a set amount of time and then raise it back to what the user has it set to, some unoptimized larger games could load a lot quicker.

**Comment by pizzaboxer** [comment]
We can't change what the graphics quality is while Roblox is running though. Might be possible with macros though? That is a pretty interesting idea, I'll give you that, but it's not currently within the scope of what I do unfortunately.

**Comment by WaviestBalloon** [comment]
> Might be possible with macros though?

It should be possible by editing `GlobalBasicSettings_13.xml` before Roblox starts.
```xml
<int name="GraphicsQualityLevel">21</int>
```
