### ISSUE TITLE
MY BLOXSTRAP MULTI INSTANCE IS NOT WORKING [BUG] 

### ISSUE THREAD

**Issue by CriticalHD** [pizzaboxer/bloxstrap#1576]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i go on my main join game then i join my alt join same game it kick both

**Comment by pizzaboxer** [comment]
What error message do you get?

**Comment by CriticalHD** [comment]
i get none

**Comment by jsmeloo** [comment]
yeah, multi-instance is bugged for me as well. I can manage to join my alt and my main in the same game but when it comes to server hopping I get the error code " Failed attempt to teleport to a place that's restricted." (somewhat accurate to what it says.) on the account I joined first.

**Comment by jsmeloo** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/156387948/f45e7706-ad67-41b9-b1f1-6f535bbe92e1)

**Comment by CriticalHD** [comment]
lucky you it just dosent work at all for me

**Comment by pizzaboxer** [comment]
> yeah, multi-instance is bugged for me as well. I can manage to join my alt and my main in the same game but when it comes to server hopping I get the error code " Failed attempt to teleport to a place that's restricted." (somewhat accurate to what it says.) on the account I joined first.

Known issue. Try using Roblox Account Manager.

> i get none i join a game on my alt and same on main my alt closes bcuz i opened it first and then sometimes my main joins or it says followed user left

Do you have the option for it enabled in the menu under the Integrations tab? Are you seeing the Bloxstrap launcher show before Roblox launches?

**Comment by jsmeloo** [comment]
> > yeah, multi-instance is bugged for me as well. I can manage to join my alt and my main in the same game but when it comes to server hopping I get the error code " Failed attempt to teleport to a place that's restricted." (somewhat accurate to what it says.) on the account I joined first.
> 
> Known issue. Try using Roblox Account Manager.


Link please for this "Roblox Account manager."?

**Comment by jsmeloo** [comment]
> > > yeah, multi-instance is bugged for me as well. I can manage to join my alt and my main in the same game but when it comes to server hopping I get the error code " Failed attempt to teleport to a place that's restricted." (somewhat accurate to what it says.) on the account I joined first.
> > 
> > 
> > Known issue. Try using Roblox Account Manager.
> 
> Link please for this "Roblox Account manager."?

Also this problem never occurred until recently so... Im willing to do anything to fix it so I don't have to switch to another program

**Comment by pizzaboxer** [comment]
> Link please for this "Roblox Account manager."?

https://github.com/ic3w0lf22/Roblox-Account-Manager

**Comment by DesiredxV1to** [comment]
Roblox may have patched it, I can't run multiple instances either. It just closes out the other client completely, or even opening "Play Roblox" via Bloxstrap, it may more likely be patched or needs another workaround.

**Comment by pizzaboxer** [comment]
> It'll just close the other client out with no errors.

You're seeing the Bloxstrap launcher show before launching Roblox, right?

**Comment by DesiredxV1to** [comment]
Yes, I am. I'll do a quick screen record.

Nevermind it decided it wanted to work. :/

**Comment by jsmeloo** [comment]
Ok idk if youre js not getting it pizzaboxer or you just cant grasp the idea of whats happened. One out of 2 things happen

1. The first instance boots up perfectly fine but when the second one is booting up it closes out the first one that opens just like the regular roblox client would do. **(And yes the bloxtrap logo DOES appear before launching roblox for the 90th time.)**

2. Both instances boot up perfectly fine until you're changing **places** inside the **game** and the first instance gets brought up an error code when switching which is the one below. **(And yes the bloxtrap logo DOES appear before launching roblox for the 90th time.)**
![image](https://github.com/pizzaboxer/bloxstrap/assets/156387948/cbc873a2-c54e-4cd1-b1b5-d18f6a75fbd6)

Yall need to do what roblox account manager is doing or something. It was working perfectly fine before but this issue has been occurring recently. Idk if you were struggling to understand what the other people was tryna say or you js didn't get it at all. All love tho

**Comment by pizzaboxer** [comment]
> (And yes the bloxtrap logo DOES appear before launching roblox for the 90th time.)

...I was asking someone else that question who was having a completely different issue, not you.

I am fully aware of what this issue is about because numerous people have reported it several times before. You are by no means the first, so I'd appreciate it if you take a moment to stop being such a condescending prick.

> It was working perfectly fine before but this issue has been occurring recently.

It's been occurring recently **for you**. For some people, this issue has been always occurring. I am aware of it.. So, for now, just use Roblox Account Manager.

**Comment by pizzaboxer** [comment]
> One out of 2 things happen

Yes, I am aware of these two things happening. OP is having issue 1 and you're having issue 2. Where exactly does it seem like I don't understand what's happening?
