### ISSUE TITLE
[BUG] Graphic Slider not working

### ISSUE THREAD

**Issue by KokuroYuki** [pizzaboxer/bloxstrap#1579]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I join a game the 21 graphics slider option doesn't apply to my game even though I have it enabled (I've tried redownloading bloxstrap an it hasn't fixed the issue) I've also tried reapplying it an unapplying it an rejoining multiple times to see if its any different but no luck it seems to be completely bugged for now.
![image_2024-04-09_111723600](https://github.com/pizzaboxer/bloxstrap/assets/166463276/91cb689f-12f1-4361-8795-9d715ce7c0be)
![image_2024-04-09_111744358](https://github.com/pizzaboxer/bloxstrap/assets/166463276/a95f0836-8307-47d5-8602-a250b93b353c)

**Comment by pizzaboxer** [comment]
Are any of your other configured options applying?

**Comment by KokuroYuki** [comment]
No but now I'm not having the issue they are all working now

**Comment by luv4chriss** [comment]
wait howd u fix it

**Comment by luv4chriss** [comment]
currently having the same problem

**Comment by NabHeyka22** [comment]
you don't fix it
the fflag is removed
you can't do anything about it

**Comment by brav00s** [comment]
> you don't fix it the fflag is removed you can't do anything about it

wait how do you know it was removed?
