### ISSUE TITLE
bloxstrap roblox not opening

### ISSUE THREAD

**Issue by eahndahd833** [pizzaboxer/bloxstrap#1580]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i open play roblox, it doesnt load roblox and just stays as a white screen.
![Roblox 9_04_2024 11_00_06 AM](https://github.com/pizzaboxer/bloxstrap/assets/166464151/c8cd85aa-efa0-447b-a588-a22fcef4edcb)
I also made sure it wasn't a normal roblox error.

**Comment by pizzaboxer** [comment]
> When i open play roblox, it doesnt load roblox and just stays as a white screen.

Upload your configuration please

https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by zexursh** [comment]
how do upload then?

**Comment by pizzaboxer** [comment]
Just drag and drop the files into the comment textbox.

**Comment by eahndahd833** [comment]
[State.json](https://github.com/pizzaboxer/bloxstrap/files/14943849/State.json)

[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/14943860/Settings.json)
didnt let me upload the modification one :(

**Comment by zexursh** [comment]
> Just drag and drop the files into the comment textbox.



> Just drag and drop the files into the comment textbox.

setting.json -{
  "BootstrapperStyle": 4,
  "BootstrapperIcon": 0,
  "BootstrapperTitle": "Bloxstrap",
  "BootstrapperIconCustomLocation": "",
  "Theme": 0,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "MultiInstanceLaunching": false,
  "OhHeyYouFoundMe": false,
  "Channel": "LIVE",
  "ChannelChangeMode": 0,
  "EnableActivityTracking": true,
  "UseDiscordRichPresence": true,
  "HideRPCButtons": true,
  "ShowServerDetails": false,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldCharacterSounds": false,
  "UseDisableAppPatch": false,
  "UseOldAvatarBackground": false,
  "CursorType": 0,
  "EmojiType": 0,
  "DisableFullscreenOptimizations": false
}


state-{
  "LastEnrolledChannel": "",
  "VersionGuid": "version-8950870ea20941f9",
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\fonts\\trushdex.zip",
    "content\\sounds\\ouch.ogg"
  ]
}

**Comment by zexursh** [comment]
> Just drag and drop the files into the comment textbox.

[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/14944374/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/14944375/State.json)

**Comment by pizzaboxer** [comment]
>  didnt let me upload the modification one :(

Go into the folders and find ClientAppSettings.json, and upload that.

**Comment by pizzaboxer** [comment]
Seems fine, are you sure that this issue doesn't occur if you use the original Roblox launcher? I'd also suggest to try setting your framerate limit to zero.

**Comment by eahndahd833** [comment]
lol im tryna run 3 roblox at once
![Screenshot 2024-04-12 001834](https://github.com/pizzaboxer/bloxstrap/assets/166464151/2194e9a0-93c9-4632-8abc-204192b6f0e7)

**Comment by eahndahd833** [comment]
![Screenshot 2024-04-12 002106](https://github.com/pizzaboxer/bloxstrap/assets/166464151/17415b27-c795-4356-af08-43bb05bd86ac)

**Comment by eahndahd833** [comment]
do i need a vpn to open this?

**Comment by zexursh** [comment]
> Seems fine, are you sure that this issue doesn't occur if you use the original Roblox launcher? I'd also suggest to try setting your framerate limit to zero.

this only happens when i change my font and i load bloxstrap roblox up and my screen goes white

**Comment by pizzaboxer** [comment]
And it works fine without the font? What font did you try?

**Comment by zexursh** [comment]
> And it works fine without the font? What font did you try?

ive tried many but still white screen when i load it up

**Comment by pizzaboxer** [comment]
Give one that you tried.

**Comment by zexursh** [comment]
> Give one that you tried.

[sugar_cream.zip](https://github.com/pizzaboxer/bloxstrap/files/15047117/sugar_cream.zip)

**Comment by zexursh** [comment]
> Give one that you tried.

hello????

**Comment by pizzaboxer** [comment]
> hello????

Sorry for not replying to you. I'll ask for something a little different though: try applying the font, then open the mods folder, go to content\fonts\, and upload and send CustomFont.ttf here.

**Comment by zexursh** [comment]
![Screenshot 2024-05-05 152953](https://github.com/pizzaboxer/bloxstrap/assets/166647638/99970869-04e9-4bd7-9265-c16add618537)

**Comment by zexursh** [comment]
> > hello????
> 
> Sorry for not replying to you. I'll ask for something a little different though: try applying the font, then open the mods folder, go to content\fonts, and upload and send CustomFont.ttf here.

sais this when i try drag it

**Comment by zexursh** [comment]
![Screenshot 2024-05-05 153129](https://github.com/pizzaboxer/bloxstrap/assets/166647638/92a9ea1e-c458-45fa-a637-971f1098531d)

**Comment by pizzaboxer** [comment]
So how exactly were you applying the font?

**Comment by zexursh** [comment]
> So how exactly were you applying the font?

i was applying it exactly thru the bloxstrap menu

**Comment by pizzaboxer** [comment]
Right, but what file were you choosing? What was the name of the file? What type of file was it?

**Comment by zexursh** [comment]
> Right, but what file were you choosing? What was the full name of the file? What type of file was it?

![Screenshot 2024-05-06 114232](https://github.com/pizzaboxer/bloxstrap/assets/166647638/dc53bbfb-0c8e-4683-bcd6-5bb7023a1952)

**Comment by zexursh** [comment]
> Right, but what file were you choosing? What was the full name of the file? What type of file was it?

this was it

**Comment by pizzaboxer** [comment]
You need to extract it first. There is a reason why the font chooser dialog is specifically asking for font files.

**Comment by zexursh** [comment]
> You need to extract it first. There is a reason why the font chooser dialog is specifically asking for font files.

oo i seeee

**Comment by zexursh** [comment]
> You need to extract it first. There is a reason why the font chooser dialog is specifically asking for font files.

it worked thank u very much!!
