### ISSUE TITLE
I have a problem do you know the code error 279

### ISSUE THREAD

**Issue by Pakashi9** [pizzaboxer/bloxstrap#1581]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I need help i Can start bloxstrap but when i want to play a game is Say me code error 279. Is Say to me
![error-code-279-v0-dc2leb0xqayb1](https://github.com/pizzaboxer/bloxstrap/assets/166498940/4bba3274-11f4-42c3-9671-a3699b0835dc)

**Comment by WaviestBalloon** [comment]
This doesn't seem to be a Bloxstrap-related issue, does the same error occur with the normal Roblox client?
https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
This is not an issue with Bloxstrap, this is something to do with your internet connection. Though, can you upload your Bloxstrap configuration please? https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Pakashi9** [comment]
Ok thanks
