### ISSUE TITLE
Can't use any fonts 

### ISSUE THREAD

**Issue by Asher937** [pizzaboxer/bloxstrap#1582]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So the main reason I download blox strap is I saw a YouTuber using it for cool fonts. I've now been troubleshooting it for a day just to realize it's because of my font I can't even open Roblox when I have a font on i switched between 4 fonts on 2 websites even watched a video nothing worked please help I wanna use fonts.

**Comment by Asher937** [comment]
Idk I tried to use 4 fonts all from different websites is there a cool one you recommend that you think would work? If yes tell me where I can find it

**Comment by pizzaboxer** [comment]
Give me one you tried to use.

**Comment by Asher937** [comment]
Called bubbly on "wfonts.com" I got it recommend to me

**Comment by pizzaboxer** [comment]
Link the specific one you tried to use, there's over twenty results for the word "bubbly".

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by MHMHMHM121H** [comment]
it stopped working for me to

**Comment by AnonymousFandomCharacter** [comment]
I found what's likely the problem, true type fonts (.TTF) don't work, only open type fonts (.OTF). Check what type your font file is.
