### ISSUE TITLE
Why does it saySystem.Exception: Could not find an accessible Roblox deployment mirror, likely due to a bad internet connection. Please launch again. I already relaunced it does not work!!!

### ISSUE THREAD

**Issue by NyoOfTheMist** [pizzaboxer/bloxstrap#1584]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Exception: Could not find an accessible Roblox deployment mirror, likely due to a bad internet connection. Please launch again.
![Screenshot (204)](https://github.com/pizzaboxer/bloxstrap/assets/166529564/b5ec183c-e3f1-45ac-a4bf-22bcea1b02db)

**Comment by NyoOfTheMist** [comment]
> If this only happened one time, then just ignore it.
> 
> Else, check to see if the standard Roblox launcher works. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
> 
> If it does, then your antivirus (or something else) is preventing Bloxstrap from connecting to the internet, so check to make sure there isn't anything like that happening.

I was trying to install bloxtrap when this happened so i dont have the play roblox things

**Comment by pizzaboxer** [comment]
> I was trying to install bloxtrap when this happened so i dont have the play roblox things

The Roblox launcher uses the "Roblox Player" shortcut.

**Comment by princexian11** [comment]
still not

**Comment by princexian11** [comment]
i tried all

**Comment by princexian11** [comment]
how to fix it

**Comment by princexian11** [comment]
System.UnauthorizedAccessException: Access to the path 'C:\Users\Xian\AppData\Local\Temp\Bloxstrap_20240410T043706Z.log' is denied.

**Comment by pizzaboxer** [comment]
What happens when you try to use the Roblox launcher?

**Comment by NyoOfTheMist** [comment]
When I try to use the default roblox launcher it says like Install without
the flag file from bloxstrap.

**Comment by pizzaboxer** [comment]
> When I try to use the default roblox launcher it says like Install without
the flag file from bloxstrap.

What? Can you show a screenshot please?

Also, can you send the log file from the Bloxstrap error please?

**Comment by NyoOfTheMist** [comment]
I have factory reseted my pc its fine now
