### ISSUE TITLE
when i trying to execute the bloxstrap 2.5.4 exe file(installer) it gives me an error

### ISSUE THREAD

**Issue by AlexanderWoods50Roblox** [pizzaboxer/bloxstrap#1586]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/113291089/9927e74b-3419-4f16-88ac-f5357673fba2)

**Comment by chvoboss** [comment]
try to delete it in windows safe mode

**Comment by pizzaboxer** [comment]
Why did you install it to your documents? You're going to need to manually uninstall it to fix this.
Open the registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap`, delete the 'InstallLocation' property. Afterwards, run the installer again, and do not change the install locatioin.
