### ISSUE TITLE
[REQ] integrated reshade request 

### ISSUE THREAD

**Issue by echofallenn** [pizzaboxer/bloxstrap#1587]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

hey! why dont you add a integrated reshade option? it would be good!

**Comment by pizzaboxer** [comment]
> hey! why dont you add a integrated reshade option? 

Because ReShade doesn't work with Roblox. I'd suggest you to use https://bloxshade.com

**Comment by echofallenn** [comment]
oh, i dont have a nvida gpu tho (im a 2015 amd laptop user 💀)
