### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: The requested address is not valid in its context. (clientsettings.roblox.com:443)[Inner Exception]System.Net.Sockets.SocketException: The requested address is not valid in its context.

### ISSUE THREAD

**Issue by Dunnowhoami** [pizzaboxer/bloxstrap#1589]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to install BloxStrips i keep getting this pop up preventing me to install.

**Comment by Dunnowhoami** [comment]
![image_2024-04-09_205130353](https://github.com/pizzaboxer/bloxstrap/assets/166579955/97d5465f-4321-4f67-ba90-81286f47a0f7)

**Comment by pizzaboxer** [comment]
Do you have an antivirus installed? If so, check to see if it's interfering with Bloxstrap.

**Comment by Dunnowhoami** [comment]
no i dont and they were off when installing

**Comment by pizzaboxer** [comment]
Something is interfering with Bloxstrap though, you'll need to find out what is doing it.
