### ISSUE TITLE
Bloxstrap Terminates itself when opening for a first time.

### ISSUE THREAD

**Issue by 6665335** [pizzaboxer/bloxstrap#159]
Installed .NET 6, theres not a single log.

**Comment by pizzaboxer** [comment]
Logs should be stored in %temp% if it's not yet installed, is anything there?

**Comment by 6665335** [comment]
Nope, nothing

**Comment by pizzaboxer** [comment]
If you've just installed the .NET 6 runtime, I guess try restarting your PC. If it's still not working after that, try installing with Winget.
