### ISSUE TITLE
**my bloxstrap is running in the background**

### ISSUE THREAD

**Issue by yasseriscool123** [pizzaboxer/bloxstrap#1590]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i was literally starting it it was runninng in the background of my task manager but not appearing for some reason and i saw someone appeal about this, i did their solution but it still didn't work, i have already every single file in tact and im loking for a fix i tried everything u guys asked me to but it didn't work i also have net 6.0 or whatever its called installed so yea

**Comment by pizzaboxer** [comment]
Currently being answered at https://discord.com/channels/1099468797410283540/1227521311668961290
