### ISSUE TITLE
cant save bloxstrap changes

### ISSUE THREAD

**Issue by theasianhim** [pizzaboxer/bloxstrap#1591]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im using v2.5.4 in bloxstrap and when i change something it doesnt say save compared to other youtube videos

**Comment by pizzaboxer** [comment]
> im using v2.5.4 in bloxstrap and when i change something it doesnt say save compared to other youtube videos

What does it say?

**Comment by theasianhim** [comment]
I have, but somehow, I think this issue associates with how the Bloxstrap menu didn't install by itself.

**Comment by theasianhim** [comment]
The only things that changed was, the old death sound of Roblox and the graphics were divided.

**Comment by theasianhim** [comment]
The quandary hath been aptly vanquished through the employment of intricate machinations, whereby an amalgam of erudite methodologies hath been deftly wielded, accompanied by an exhaustive disquisition and the harmonious convergence of diverse cogitative paradigms, culminating in the formulation of an elaborate panacea.

**Comment by theasianhim** [comment]
The quandary hath been aptly vanquished through the employment of intricate machinations, whereby an amalgam of erudite methodologies hath been deftly wielded, accompanied by an exhaustive disquisition and the harmonious convergence of diverse cogitative paradigms, culminating in the formulation of an elaborate panacea.
