### ISSUE TITLE
[REQ] Menu should make it more clear I need to have Discord installed for RP

### ISSUE THREAD

**Issue by PhoenixWhitefire** [pizzaboxer/bloxstrap#1592]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It took me too long to figure out I needed to install the Discord desktop app to get Rich Presence to work. I've always just used the website. I think there should be a note somewhere to say that RP requires the desktop app, or a notification when launching a game with RP enabled without the desktop app.

**Comment by WaviestBalloon** [comment]
Discord is already mentioned under the integrations tab when enabling the feature.

![image](https://github.com/pizzaboxer/bloxstrap/assets/31796727/11f7cdac-ce87-4152-95ae-94a0dc79409a)

**Comment by pizzaboxer** [comment]
He was using the Discord website in his browser.

**Comment by pizzaboxer** [comment]
Fixed in 2.7.0
