### ISSUE TITLE
[BUG] Upgrading

### ISSUE THREAD

**Issue by twinkiepinkiejunkie** [pizzaboxer/bloxstrap#1593]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap starts "Upgrading Roblox" every single time I launch a different account for some reason

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Using-multiple-instances-always-forces-a-Roblox-upgrade, as the same fix applies to you.
