### ISSUE TITLE
[BUG] Feature Missing

### ISSUE THREAD

**Issue by Kouseiih17** [pizzaboxer/bloxstrap#1595]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hi, idk if this is just a problem of mine, but i saw some videos on how to install bloxstrap and get more FPS on roblox and they all have a feature to change the preferred rendering option, i just installed bloxstrap and everything went fine but mine doesnt have the preferred rendering option and but it says this under the text "Presets"
![Screenshot 2024-04-10 205104](https://github.com/pizzaboxer/bloxstrap/assets/102265175/2e96a894-ab69-45f7-ab3a-83ce11dc8960)

**Comment by pizzaboxer** [comment]
Read the release notes for the version you downloaded.

https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4

"Removed option to configure rendering mode due to how much instability it causes. It will be added back in the future when better precautions are in place."
