### ISSUE TITLE
[BUG] i can't even describe this. :/

### ISSUE THREAD

**Issue by Dakateth** [pizzaboxer/bloxstrap#1596]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Снимок экрана 2024-04-10 220310](https://github.com/pizzaboxer/bloxstrap/assets/166652774/c37e90b1-dd1c-4bb5-a46b-709c7a62d25a)

**Comment by Dakateth** [comment]
nvm, i fixed it, apparently i downloaded a texture pack and it's textures are only to read and can't be edited so i made them allowed to be edited

**Comment by ikonikisop** [comment]
Close the issue if you fixed it.
