### ISSUE TITLE
crashing [BUG] 

### ISSUE THREAD

**Issue by dwngrss** [pizzaboxer/bloxstrap#1597]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I go to open up Roblox through bloxstrap it just says 'an unexpected error occurred and Roblox needs to quit'. I'm not sure what's happening but it wont let me join any game at all, i tried re starting Roblox and turning my laptop off and on someone help please : ) .

**Comment by dwngrss** [comment]
![Roblox Crash 11_04_2024 01_13_47](https://github.com/pizzaboxer/bloxstrap/assets/166669443/81610fc6-5025-4267-aad9-ddb48089a061)

This is what it comes up with?.

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this occur only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
