### ISSUE TITLE
Mods do not apply, bad lag spikes, and FPS seems to get worse overtime [BUG] 

### ISSUE THREAD

**Issue by movieslol** [pizzaboxer/bloxstrap#1598]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Recently (issue seems to have occurred today, but I haven't played roblox in a while, so who knows), Bloxstrap seems to have been causing a ton of issues for Roblox. The title explains the issue.

To not waste your time, 
- No, another Roblox is not running in the background
- Yes, Bloxstrap is running
- Yes, my FPS is actually being capped at 60 (Supposed to be 120)
- I checked everything on https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter 
- The only fix I've seen is playing Roblox without Bloxstrap

Below are the files asked to be attached:
Files:
[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/14939036/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/14939039/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/14939043/ClientAppSettings.json)

Help would be appreciated!

**Comment by movieslol** [comment]
It appears that the Bloxstrap menu says that Roblox is running in the background, when task manager says completely otherwise...

**Comment by pizzaboxer** [comment]
> It appears that the Bloxstrap menu says that Roblox is running in the background, when task manager says completely otherwise...

If you were opening the menu right after closing Roblox, then Bloxstrap would've been picking up on Roblox before it had actually exited.

Only thing I can suggest for you to do is to try disabling the 'Disable Fullscreen Optimizations' option in the Mods tab.

It would also help if you clarified if this happens only when using Bloxstrap: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Regarding your FPS not going past 60, are you using an Nvidia GPU?

**Comment by movieslol** [comment]
Sorry for the late response - Randomly fixed itself. Thanks for the help though!
