### ISSUE TITLE
[BUG] System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by bashir444444444444** [pizzaboxer/bloxstrap#1599]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/130563628/3a72a001-9b6d-4a53-ab55-219b6744fe7d)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
