### ISSUE TITLE
can you please make a version of this app that DOESNT require you to install .NET x86?

### ISSUE THREAD

**Issue by KazookiTV** [pizzaboxer/bloxstrap#16]

**Comment by pizzaboxer** [comment]
It uses the .NET 6 framework, there's no getting around that.
It's a one-time installation only, what's stopping you from installing it?

**Comment by Instearstell** [comment]
the person prob doesnt have admin permissions.

**Comment by pizzaboxer** [comment]
Still, there's not really much else I can do. If that is the case, you've just got to get permission for one time only.
