### ISSUE TITLE
Installer failed with exit code: 3762504530 While trying to download with winget.

### ISSUE THREAD

**Issue by 6665335** [pizzaboxer/bloxstrap#160]
Im sorry for opening a new issue, i accidently closed the other one. This time i tried installing with winget

The error is in the title. (this still didnt create any logs)

**Comment by pizzaboxer** [comment]
Just checked online and the value for this error in hex is `0xe0434352`, which seems to indicate a problem with the runtime. You've installed it for the first time just now, right? Can I see the runtime listed in Apps & Features?

![image](https://user-images.githubusercontent.com/41478239/234950276-5f8b8c1e-d44b-40f5-8406-51fe7b2969c4.png)

**Comment by 6665335** [comment]
![obraz](https://user-images.githubusercontent.com/77754479/234950414-c1edf12a-0b6d-465e-a614-39175163f2b8.png)
sorry for the language but im polish, here you go.

**Comment by pizzaboxer** [comment]
Can you try uninstalling the first and the second one, and then [install this one](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer)?

**Comment by 6665335** [comment]
Alright, give me some minutes and ill try.

**Comment by 6665335** [comment]
Alright, it works. Thanks for support.

**Comment by pizzaboxer** [comment]
Oh, it does? Okay, great!
