### ISSUE TITLE
UK servers showing as egypt servers

### ISSUE THREAD

**Issue by pcxo** [pizzaboxer/bloxstrap#1600]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever i join a server which is located in the UK it shows up as "Al-'ubur, Qalyubia, EG" now i dont know what thats even saying and i know im joining UK servers. This randomly started happening yesterday
![b](https://github.com/pizzaboxer/bloxstrap/assets/124406961/7fb4f06d-2ebf-457c-af33-d02214bbddae)

**Comment by pizzaboxer** [comment]
Server locations are approximations, and are handled by https://ipinfo.io. If you know for certain where it's actually located, then just ignore it.
