### ISSUE TITLE
[BUG] authentication

### ISSUE THREAD

**Issue by Hakarisus** [pizzaboxer/bloxstrap#1603]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my problem is the authentication its in german but i can translate it: An error occurred during authentication. Please try again
![image](https://github.com/pizzaboxer/bloxstrap/assets/166731383/edfa26af-40a5-48a9-98b1-eee10f32c0df)

**Comment by pizzaboxer** [comment]
Are you using a browser VPN?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
