### ISSUE TITLE
it only lets me open 5 intants of rolblox at a time[BUG] 

### ISSUE THREAD

**Issue by UknownFlty** [pizzaboxer/bloxstrap#1605]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

if i try open more it sais teleport failed and you were disconnected for being idle, is there any fix for this if so please tell me.

**Comment by pizzaboxer** [comment]
> you were disconnected for being idle

You left your old instances idle for too long.

> sais teleport failed 

Try using Roblox Account Manager.
