### ISSUE TITLE
[BUG] Fps is only uncapped when using true Fullscreen

### ISSUE THREAD

**Issue by winnerwinnerchicken** [pizzaboxer/bloxstrap#1608]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I'm not using true full screen, my fps is capped but whenever I do use true full screen, my fps is uncapped

**Comment by pizzaboxer** [comment]
Check your GPU settings software to see if there's anything relating to maximum framerate that you can potentially change.

**Comment by winnerwinnerchicken** [comment]
That fixed my problem, thanks
