### ISSUE TITLE
[BUG] I cant open roblox!!

### ISSUE THREAD

**Issue by KawaiiNaomii** [pizzaboxer/bloxstrap#1609]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

for some reason, i cant open roblox. and whenever i do,  Roblox crashes or freezes. I have no clue what i did wrong!
![Screenshot (1)](https://github.com/pizzaboxer/bloxstrap/assets/166886140/6a83aced-83d8-4a2f-a5c5-a3ba2d0016a0)

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when you use Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by vanopikss09** [comment]
Yeah same also to me

**Comment by pizzaboxer** [comment]
> Yeah same also to me

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration
