### ISSUE TITLE
Byfron is here.

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#161]
How will that effect Bloxstrap?

**Comment by CinnamonLambda** [comment]
Bloxstrap v2.2.0 has support for the x64/Byfron build of Roblox. No Bloxstrap features were lost in the update.
As Byfron is still in testing it's impossible to say how Bloxstrap might be affected in the future. For now, it seems like the answer is "not at all".

**Comment by pizzaboxer** [comment]
have you seen the release notes for v2.2.0 or nah
