### ISSUE TITLE
[REQ] Add roblox settings fps unlocker fast flag

### ISSUE THREAD

**Issue by LukeDevsE** [pizzaboxer/bloxstrap#1611]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Basically, I found a fastflag that puts a fps unlocker into the roblox settings
```json
{
        "FFlagGameBasicSettingsFramerateCap": "True",
        "DFIntTaskSchedulerTargetFps": "0"
}
```
![image](https://github.com/pizzaboxer/bloxstrap/assets/108841495/a00807e0-6a3f-4ca7-bc3b-ede555c092d0)
Options: Default, 30, 60, 144, 240

**Comment by pizzaboxer** [comment]
We already know about this, thank you for the suggestion.
