### ISSUE TITLE
[BUG] Wont let me join

### ISSUE THREAD

**Issue by killerking1544** [pizzaboxer/bloxstrap#1612]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i try to join a game bloxstrap wont take me in and just leaves me on the home page it has never done it before until today and i have reinstalled it and tried other ways

**Comment by pizzaboxer** [comment]
Are you trying to join a game from the website? After you try joining a game, open the Roblox logs folder at `%localappdata%\Roblox\logs`, get the latest log file (either at the top or the bottom), and send the log file to me privately (either via [email](mailto:pizzaboxer@pizzaboxer.xyz) or [discord](https://discord.gg/nKjV3mGq6R)). Let me know once you have.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
