### ISSUE TITLE
[REQ] Add an option for it to run the background when clicking the default roblox player icon

### ISSUE THREAD

**Issue by foursplaysroblox** [pizzaboxer/bloxstrap#1613]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

You should add an option to let blostrap run in the background so that I do not have to search for play roblox (especially for discord rpc)

**Comment by 1011025m** [comment]
Bloxstrap runs in the background when you are playing games. What do you mean?

**Comment by foursplaysroblox** [comment]
Not like that I mean that everytime you click the roblox icon below it will launch bloxstrap
![image](https://github.com/pizzaboxer/bloxstrap/assets/82078139/a9009ce0-103e-4029-b1a9-9973cd9fdb77)

**Comment by 1011025m** [comment]
Search for the "Play Roblox" shortcut in start menu and click "Open File Location". Your explorer will open, now drag the "Play Roblox" shortcut from the explorer to your taskbar. You can now launch Roblox via Bloxstrap.

Additionally, if you'd like to have a separate icon from the Bloxstrap icon for this, right click the "Play Roblox" shortcut in the explorer. Right click to open the context menu, and click Properties. Head to the "Shortcut" tab and change the icon from there.
