### ISSUE TITLE
[BUG] Crash when use customfont (Bloxstrap)

### ISSUE THREAD

**Issue by BananaFromVietnam** [pizzaboxer/bloxstrap#1614]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I use custom font in bloxstrap, I always crash. And when I turn off custom font, bloxstrap returns to normal **(Also sing google translate)**
![Ảnh chụp màn hình 2024-04-13 182439](https://github.com/pizzaboxer/bloxstrap/assets/166916580/1c8467e1-6905-4cb6-86bb-2a98891b1087)

**Comment by 1011025m** [comment]
What font are you using?

**Comment by BananaFromVietnam** [comment]
coming sans

**Comment by BananaFromVietnam** [comment]
https://www.dafont.com/search.php?q=coming+sans

**Comment by BananaFromVietnam** [comment]
its the same for every font

**Comment by 1011025m** [comment]
Doesn't seem to be crashing on my end. I would assume this is a Roblox issue.

**Comment by BananaFromVietnam** [comment]
i think so

**Comment by pizzaboxer** [comment]
How exactly are you applying the font? What are the steps you do, from when you download it to when you try to launch Roblox?
