### ISSUE TITLE
[BUG] Roblox ban screen frozen. Cannot log out.

### ISSUE THREAD

**Issue by RoblxianKegan785** [pizzaboxer/bloxstrap#1616]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My roblox account was banned for 3 days. And for some reason, i CANNOT log out of my banned account as the screen is just frozen and the only thing moving is the cursor. I even tried logging out the official roblox app, re-installing bloxstrap and logging out the website. How will this be resolved?

**Comment by Gofseep** [comment]
i have the exact same problem, banned for three days and im unable to logout of bloxstrap as they just refuse to allow me to click logout

**Comment by pizzaboxer** [comment]
> i have the exact same problem, banned for three days and im unable to logout of bloxstrap as they just refuse to allow me to click logout

See if temporarily switching back to the original launcher lets you log out: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
