### ISSUE TITLE
Error Code 279

### ISSUE THREAD

**Issue by JY12334** [pizzaboxer/bloxstrap#1617]
It keeps saying error code 279 but works fine when I use the roblox app to join games. Other devices runs roblox just fine aswell but they don't have bloxstrap installed

**Comment by UTAsriel2015** [comment]
For some reason, I can't use the old textures before 2022

**Comment by pizzaboxer** [comment]
> For some reason, I can't use the old textures before 2022

You were told to read this before using Bloxstrap: https://github.com/pizzaboxer/bloxstrap/wiki/Addressing-usability-problems-with-Bloxstrap-v2.5.4

> It keeps saying error code 279 but works fine when I use the roblox app to join games. Other devices runs roblox just fine aswell but they don't have bloxstrap installed

Show a screenshot of the error message please

**Comment by UTAsriel2015** [comment]
I'm sorry

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by cullycat** [comment]
> It keeps saying error code 279 but works fine when I use the roblox app to join games. Other devices runs roblox just fine aswell but they don't have bloxstrap installed

A common issue, not just with Blockstrap is a network issue. Make sure you are on a secure network and not using a VPN.

**Comment by unw1nded** [comment]
hey there i am now currently experiencing this issue. when launching w/o bloxstrap roblox will fully work. with bloxstrap is the issue. i have tried resetting my router to attempt to fix this issue but it still persists
