### ISSUE TITLE
[BUG] its said System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (github.com:443)  [Inner Exception] System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.  so help me plz 

### ISSUE THREAD

**Issue by CVGX-472** [pizzaboxer/bloxstrap#1618]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image_2024-04-14_231332945](https://github.com/pizzaboxer/bloxstrap/assets/167017078/a9d8f8c9-ef6d-41ae-bddf-75ea1ad602bf)

**Comment by CVGX-472** [comment]
bro i fix it

**Comment by CVGX-472** [comment]
i need to open normal roblox first then i can open bloxstrap

**Comment by bluepilledgreat** [comment]
Can you go into your windows command line, run `ping github.com`, and send the response here?

**Comment by CVGX-472** [comment]
Pinging github.com [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

here

**Comment by CVGX-472** [comment]
> Collaborator

Pinging github.com [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64
Reply from 127.0.0.1: bytes=32 time<1ms TTL=64

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

**Comment by pizzaboxer** [comment]
...How are you even able to use the GitHub website here??

Either way, open Command Prompt as Administator, and run this command:
`notepad C:\Windows\System32\drivers\etc\hosts` 
Remove any lines that have '127.0.0.1'' in them, and then save.
Afterwards, run this command:
`ipconfig /flushdns`
Then, Bloxstrap should work. If it still doesn't, let me know.

**Comment by CVGX-472** [comment]
> ipconfig /flushdns

still doesn't :/

**Comment by pizzaboxer** [comment]
Show a screenshot of the hosts file open in Notepad please

**Comment by CVGX-472** [comment]
> notepad C:\Windows\System32\drivers\etc\hosts

![image](https://github.com/pizzaboxer/bloxstrap/assets/167017078/046cfedf-19b1-488f-a8e4-5123e678e6fc)

**Comment by CVGX-472** [comment]
> Show a screenshot of the hosts file open in Notepad please

![image](https://github.com/pizzaboxer/bloxstrap/assets/167017078/f662cb71-a7aa-4889-a6b2-7e6806304005)

**Comment by CVGX-472** [comment]
> Show a screenshot of the hosts file open in Notepad please

what  next?

**Comment by pizzaboxer** [comment]
I asked you to remove all lines that have "127.0.0.1" in them and then save. Did you not do that?

**Comment by CVGX-472** [comment]
> I asked you to remove all lines that have "127.0.0.1" in them and then save. Did you not do that?

![image](https://github.com/pizzaboxer/bloxstrap/assets/167017078/c6bd457a-a156-49d8-9244-b3a6b437096d)

**Comment by CVGX-472** [comment]
it cant save

**Comment by pizzaboxer** [comment]
> it cant save

Why not?

**Comment by CVGX-472** [comment]
> > it cant save
> 
> Why not?

it said u dont have permission to save here contract with system owner for some thing...

**Comment by CVGX-472** [comment]
> Did you run Notepad as an Administrator?

bruh i forgor but its works now thanks!
