### ISSUE TITLE
Black Screen Issue with Bloxstaps Launch and Intel® Rapid Storage Technology Error

### ISSUE THREAD

**Issue by guus6457** [pizzaboxer/bloxstrap#1619]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I open Bloxstaps, my PC screen goes black. Upon checking my event logs, I notice an error related to Intel® Rapid Storage Technology.

This issue arises consistently and affects the usability of my computer. I've attempted troubleshooting steps such as restarting the PC and checking for updates, but the problem persists.

I'm seeking assistance to understand the root cause of this error and find a solution to resolve it. Any guidance or suggestions would be greatly appreciated.!

![image](https://github.com/pizzaboxer/bloxstrap/assets/57826942/1fa83827-5c9a-4dfc-92d9-c1df5321eb4c)
![image](https://github.com/pizzaboxer/bloxstrap/assets/57826942/e56ae44b-6d3c-4205-9a13-56c9e8a3cd36)

**Comment by bluepilledgreat** [comment]
Does this issue happen when using Roblox's stock bootstrapper?

**Comment by guus6457** [comment]
Yes
