### ISSUE TITLE
Can't change rendering mode, stuck in D3D11

### ISSUE THREAD

**Issue by Luster-crypto** [pizzaboxer/bloxstrap#162]
I tried to change rendering mode from Direct3D 11 to something else but it would always change back to D3D11 when I relaunch the menu (Yes, I did click save). I tried changing it directly in the json both by removing ""FFlagDebugGraphicsPreferD3D11" and just changing it to false. Either way, it always just added it back or changing it to true. I turned off FSE and it still did not work. 
![image](https://user-images.githubusercontent.com/77598282/235132384-9755c2f7-3d23-46bb-bbe0-adff5c20e4d9.png)

**Comment by Luster-crypto** [comment]
nvm its in 2.3.0

**Comment by pizzaboxer** [comment]
Yeah, it's a bug that's gonna be fixed in the next release. Sorry about that.
