### ISSUE TITLE
[BUG] Error Code 268 (Unexpected Client Behaviour) when Joining a Game

### ISSUE THREAD

**Issue by Mattem300** [pizzaboxer/bloxstrap#1620]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try to Join a Game, I get the error code 268 (Unexpected Client Behaviour). I tried disabling stuff that could be causing this Error but to no avail. (I know this was addressed some time ago, [May 4th, 2023](https://github.com/pizzaboxer/bloxstrap/issues/193). But now it is happening again!) I tried to follow the steps on the Old Bug Report, but those did not work! I would like some help here.
![image](https://github.com/pizzaboxer/bloxstrap/assets/118678848/ba13c2b2-6f0a-453c-a35a-7c1e9b838685)

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Seems like there may be something running on your computer (probably in the background) that Roblox doesn't like. Either way, it's not a Bloxstrap issue, so I can't really help you much further.
