### ISSUE TITLE
[BUG] Error While Downloading Bloxstrap

### ISSUE THREAD

**Issue by iborich** [pizzaboxer/bloxstrap#1621]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

error while downloading bloxstrap - An exception occurred while running Bloxstrap

**Comment by iborich** [comment]
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

**Comment by pizzaboxer** [comment]
Send the log file please

**Comment by iborich** [comment]
i just fixed that, thanks, that was my bad, i have choosen incorrect font because on the next launch without my personal settings, all started working
