### ISSUE TITLE
Rn i get lag spikes no matter what i do [BUG] 

### ISSUE THREAD

**Issue by Averageguyhehe** [pizzaboxer/bloxstrap#1622]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

rn i use blox strap for about 2 days now and every time i get lag spikes even though i get 120 fps (i capped at 120 cause i have 120 hz) anyway all i use neext to blox strap is something called "bloxshade"and when i turn of that app it still lags me,pls help me

**Comment by Averageguyhehe** [comment]
btw bloxshade is something that is rtx and its used by rtx users only so if ur using AMD u cant download it

**Comment by Averageguyhehe** [comment]
and all stuff  i have enabled is the extra graphics thingy

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
