### ISSUE TITLE
Settings menu won't start

### ISSUE THREAD

**Issue by wertden75** [pizzaboxer/bloxstrap#1623]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I was installing Bloxstrap I accidentally skipped the setup step and immediately clicked on install, then I tried to set up through the launcher but I can no longer open the settings.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

**Comment by wertden75** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

Thank you very much
