### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Dinoul** [pizzaboxer/bloxstrap#1624]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So ive recently seen a player in youtube (https://www.youtube.com/watch?v=UNsrUI29HkA) he has a custom bloxstrap menu and im wondering how to get it?

**Comment by pizzaboxer** [comment]
> he has a custom bloxstrap menu

I think you mean the *escape menu*.

He's using a community-made theme mod, which can be found here if you join the Bloxstrap discord server: https://discord.com/channels/1099468797410283540/1208187394206203945
