### ISSUE TITLE
[BUG] BloxStrap is unable to connect to roblox

### ISSUE THREAD

**Issue by JSS-BugReporters** [pizzaboxer/bloxstrap#1625]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/152740294/f99f712a-287e-486a-8b64-5f031aa15b9f)
Someone Please help Me Fix This

**Comment by pizzaboxer** [comment]
What do you see if you access https://clientsettings.roblox.com/ in your browser?

**Comment by JSS-BugReporters** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/152740294/d73c2735-ae98-4a5a-9aeb-8f35e6a82b79)
this

**Comment by pizzaboxer** [comment]
That's interesting. Open a Command Prompt window and run this command:
`ping clientsettings.roblox.com`
Show a screenshot of the output it gives.

**Comment by JSS-BugReporters** [comment]
were do i do this?

**Comment by pizzaboxer** [comment]
Open the Command Prompt. Search for it in your applications, or directly run 'cmd.exe'.

**Comment by JSS-BugReporters** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/152740294/20b1d516-8c36-4d79-98fe-e2c97f462c2e)
got it

**Comment by JSS-BugReporters** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/152740294/7e4f8501-b3d9-45a8-b5d6-01802dbf3f20)

**Comment by JSS-BugReporters** [comment]
are you there?

**Comment by JSS-BugReporters** [comment]
hay are u doin somthin rn?

**Comment by JSS-BugReporters** [comment]
i figgered it out

**Comment by sarsurti** [comment]
The ping looks good but still , stuck in the same connecting screen , and It isnt my internet as It happens in others places too , It appears to show an type of timeout , is there any way to remove that?

**Comment by sarsurti** [comment]
forgot to say It , but It has been occuring Very often , and sometimes i need to do certain CMD commands for It to work

**Comment by pizzaboxer** [comment]
> It appears to show an type of timeout

I don't know what to tell you but that really just does sound like a bad internet connection
