### ISSUE TITLE
[BUG] Chat Breaks in certain games

### ISSUE THREAD

**Issue by Lagomorpheus** [pizzaboxer/bloxstrap#1626]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

In games with custom chat systems chat will get stuck above heads and not appear in the chat box.

Examples of games it happens to me in:
https://www.roblox.com/games/5233782396/W3-Creatures-of-Sonaria-Monster-Kaiju-Animal ; Chat functions normally initially but will break over time playing

https://www.roblox.com/games/2534724415/Emergency-Response-Liberty-County ; Chat breaks immediately, messages get stuck above heads.

This is most likely caused by the UI feature but I could be wrong as when I disabled the setting it still happened.

**Comment by bluepilledgreat** [comment]
What fast flags do you have have enabled?
Does this happen with Roblox's stock bootstrapper?

**Comment by Lagomorpheus** [comment]
I haven't tested if it happens in stock but it didn't used to happen on my other PC that runs normal Roblox

Sent from Proton Mail Android

-------- Original Message --------

**Comment by pizzaboxer** [comment]
> Chat breaks immediately, messages get stuck above heads.

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Lagomorpheus** [comment]
[State.json](https://github.com/pizzaboxer/bloxstrap/files/15013419/State.json)

**Comment by pizzaboxer** [comment]
Looks mostly good, nothing abnormal I can notice here. Try with the original launcher when you can, if you've confirmed it doesn't happen there then with Bloxstrap the only thing I can suggest is try setting your framerate limit to zero and see if that changes anything.

**Comment by Lagomorpheus** [comment]
Setting to zero kind of fixed it but it goes back to being broken again while playing.

**Comment by pizzaboxer** [comment]
If there's still something apparently causing it, then try setting your preferred escape menu version to the default.

**Comment by Lagomorpheus** [comment]
Apparently this was caused by Roblox's own doing, chat just breaks in games with custom chat systems in place, sometimes fixes it by setting system clock to automatic.
