### ISSUE TITLE
[BUG] My graphics wont change

### ISSUE THREAD

**Issue by Max080910** [pizzaboxer/bloxstrap#1628]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Ever since i downloaded bloxstrap, I haven't been able to change my graphic setting, so if i move the bar side to side, no matter the distance my graphics stay the same

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
