### ISSUE TITLE
All the sudden it starts crashing after using "click to move" in game

### ISSUE THREAD

**Issue by tdfghhngv** [pizzaboxer/bloxstrap#1629]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I dont know if its the client or my PC but, I run Windows **11** and when I used click to move, the game randomly crashed. My computer sent me a notification saying "⚠️_Roblox has crashed, please preform a clean boot_" then I did the clean boot like **5** times and still kept crashing.

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
