### ISSUE TITLE
[BUG] Roblox crashing when only using bloxstrap

### ISSUE THREAD

**Issue by winnerwinnerchicken** [pizzaboxer/bloxstrap#1631]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox keeps on crashing when I use bloxstrap.

**Comment by pizzaboxer** [comment]
When does it happen? How often does it happen? Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by winnerwinnerchicken** [comment]
It happens inconsistently, I have read the wiki page on crashing.

**Comment by winnerwinnerchicken** [comment]
Nevermind, this isn't a bloxstrap problem. it just happens less often when I don't use bloxstrap
