### ISSUE TITLE
[REQ] Cursor changer

### ISSUE THREAD

**Issue by outmaneuver** [pizzaboxer/bloxstrap#1632]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Make it easier to change cursor so we don't have to go through all the pain of doing this: [https://www.youtube.com/watch?v=BaiKkDwnEMU](url)

**Comment by pizzaboxer** [comment]
Forgot to reply to this, but we already have this planned on our feature list. Thank you for the thought though.
