### ISSUE TITLE
[BUG] Only roblox and bloxstrap arent connecting to my internet.

### ISSUE THREAD

**Issue by sarsurti** [pizzaboxer/bloxstrap#1633]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So , ive been lately playing bloxstrap and It have been quite strange , First , It was capped tô 60 fps even If o didnt put It that , Second, my changes are not saving on the menu, and the main one that its unable to connect to my internet, and even sometimes when Its on the background It makes steam and Google offline!!! now i have no way to do stuff and then i Just sit in my computer studying or organizing my files.

**Comment by pizzaboxer** [comment]
> First , It was capped tô 60 fps even If o didnt put It that 

Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?


> Second, my changes are not saving on the menu

Besides the framerate limit, what changes have you made that you've noticed aren't supposedly saving?

> and the main one that its unable to connect to my internet, and even sometimes when Its on the background It makes steam and Google offline!!! 

That really just sounds like your internet connection just doesn't work. I don't think you launching Bloxstrap has any correlation to causing that.

**Comment by sarsurti** [comment]
Okay , so checked It , by the way , Sorry for not telling this but every day i switch to my Workplace to my home , and It happens on  both , im on my phone but every time i need to do flushdns every time in my laptop.and my computer os on the best performance in the settings , so maybe its my computer or its roblox normally screwing me up , i have been searching for ways to fiz the internet problem , but It keeps coming back .

**Comment by sarsurti** [comment]
Sorry for bad lettering , i have problems typing on my phone.

**Comment by pizzaboxer** [comment]
Since you're claiming that Bloxstrap is the cause of your connection issues, can you try not using it and see if anything different hapepns? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by sarsurti** [comment]
Hmmm... Il try It

**Comment by sarsurti** [comment]
Nope , not even wanting to open , Just gave me an internet error. I guess ill stop playing roblox , as It doesnt want me in the platform , i will not be in the platform.

**Comment by sarsurti** [comment]
Fuck you in personal , roblox.

**Comment by pizzaboxer** [comment]
I'm just wondering, what error did it give?

**Comment by sarsurti** [comment]
An timeout error , It said like "this took more than 30 seconds or someting um without my laptop so i cant say what is It exactly

**Comment by pizzaboxer** [comment]
Take a screenshot of it and show it please

**Comment by sarsurti** [comment]
Sorry i cant , i already uninstalled It and now i have stopped playing roblox entirely.

**Comment by pizzaboxer** [comment]
I mean, do you want to try and fix it or not?

**Comment by sarsurti** [comment]
I already uninstalled It.

**Comment by pizzaboxer** [comment]
Well yes, but you can also reinstall it.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
