### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mythismyth** [pizzaboxer/bloxstrap#1634]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to search bloxstrap menu it doesnt show up when i try to redownload it still doesnt work i really need help.

**Comment by pizzaboxer** [comment]
Try looking for it in the app list instead of searching for it, as shown here: https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
