### ISSUE TITLE
[BUG] No folders in modification folder

### ISSUE THREAD

**Issue by Dally-DDLC** [pizzaboxer/bloxstrap#1637]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The thing is I deleted the modification folder because my mods were messed up and when i opened the bloxstrap (Using Play Roblox) shortcut, modification folder appeared but i cant put something like cursors because there's no "Cursors" folder thing
![image](https://github.com/pizzaboxer/bloxstrap/assets/74962341/ad8f4ae6-67fc-499d-95c1-1e05bbaefcc0)
![image](https://github.com/pizzaboxer/bloxstrap/assets/74962341/4adfec7a-873b-49da-9c00-e73f19f086f7)

**Comment by pizzaboxer** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

"By default, the mods folder does not have the directory structure of the version folder. So, you will often need to create new folders in order to represent your file's location within the version folder."
