### ISSUE TITLE
[BUG] cant find lol

### ISSUE THREAD

**Issue by alawihabibiA** [pizzaboxer/bloxstrap#1638]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cannot  find lol channel so i cannot change the channel to live so i can use ro-exec can u please fix it :D

**Comment by PizzMAN12** [comment]
Bro please how?

**Comment by Vlad55432** [comment]
> Bro please how?

![jWCWRLdG](https://github.com/pizzaboxer/bloxstrap/assets/78297186/184b1cdd-1850-4e30-9525-809e7f3a9f82)
