### ISSUE TITLE
[BUG] signature not found after restarting my computer 2 times

### ISSUE THREAD

**Issue by relasdas** [pizzaboxer/bloxstrap#1639]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i restarted 2 times and signature not found is fixed are there any more solution?

**Comment by pizzaboxer** [comment]
No, there's nothing more I can tell you other than what was stated in the Wiki page.
