### ISSUE TITLE
[BUG] Whenever i try to use my computer, wifi is fine, whenever i launch roblox, massive issues

### ISSUE THREAD

**Issue by iwanttodiepls** [pizzaboxer/bloxstrap#1640]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, i use ETHERNET, and usually my ethernet is fine when i use my computer for youtube, minecraft, literally anything. Its all fine until i decide to launch roblox with bloxstrap installed, whenever im in roblox, all the apps get really massive ping spikes (400 -  5000+ ms) and even DISSCONNECT sometimes every 3 - 10 seconds. I have no clue why this issue is happening, im playing in my region, and heres a list of things i have tried.
Making sure the ethernet is not on power saving mode

Trying different cables

Making sure all cables are secure, including power cable to router, on both ends

Making sure settings in router are on DHCP

Updating drivers for ethernet port & controller.

Heres the error log generated. 

[System.Net.Http.HttpRequestException: An error occurred while sending the request.

[Inner Exception]
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..

[Inner Exception]
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.]
[Bloxstrap_20240418T124125Z.log](https://github.com/pizzaboxer/bloxstrap/files/15025093/Bloxstrap_20240418T124125Z.log)

**Comment by pizzaboxer** [comment]
> (400 - 5000+ ms)

Where are you measuring this ping?

Anyway, can you try playing Roblox with the original launcher and see if the issues still occur? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
