### ISSUE TITLE
[REQ] bring back channel selector

### ISSUE THREAD

**Issue by loadstring1** [pizzaboxer/bloxstrap#1641]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

please bring it back to bloxstrap

im using older version of bloxstrap only because channel selector got removed

edit: the only way to bring it back right now is set %localappdata%/Bloxstrap/settings.json "OhYouFoundMeLol" to true

**Comment by d44df016fe28bc8d5974** [comment]
nah 
it should stay behind ohhey

**Comment by bluepilledgreat** [comment]
No
