### ISSUE TITLE
[BUG] roblox needs update when launching with BloxStrap

### ISSUE THREAD

**Issue by SpookyWarrior103** [pizzaboxer/bloxstrap#1642]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox needs an update when i launch it with BloxStrap, but it seems to not download it, ( i press on the button update and normally it would update but nope )

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
