### ISSUE TITLE
[REQ] Option to revert Roblox font change

### ISSUE THREAD

**Issue by Bedoh0617** [pizzaboxer/bloxstrap#1643]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

An option to revert the new font added by Roblox to the previous one, instead of the new “Builder” font.

**Comment by pizzaboxer** [comment]
100% in approval of. For now, I'll make a guide on the Wiki.

**Comment by pizzaboxer** [comment]
After taking a further look, it probably isn't possible to return it to how it used to be before, since it seems like they've adjusted the displayed weights/sizes for the new font. The best I can probably do is to bolden the lighter fonts so they're more readable. Sorry about that.

**Comment by corruptedgh** [comment]
pizza! you can use this fflag "FFlagEnableNewFontNameMappingABTest2" with the value "false"

**Comment by Bedoh0617** [comment]
Tested what corrupted said for the fast flags, it seems like it reverted the font change.

**Comment by pizzaboxer** [comment]
> pizza! you can use this fflag "FFlagEnableNewFontNameMappingABTest2" with the value "false"

Good catch, I didn't see that since the Roblox Client Tracker hasn't updated yet.

**Comment by pizzaboxer** [comment]
nullified
