### ISSUE TITLE
[BUG] My font is not changing

### ISSUE THREAD

**Issue by Thatsnice1938** [pizzaboxer/bloxstrap#1644]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i change the font it dosent show up.

**Comment by pizzaboxer** [comment]
What font did you try? Link it please.

**Comment by Thatsnice1938** [comment]
Nvm it works now i use mojang font https://www.dafont.com/mojang.font
