### ISSUE TITLE
[BUG] the game bloxtrap thing didn't show when i played roblox and i had to reinstall it again 

### ISSUE THREAD

**Issue by wacke15** [pizzaboxer/bloxstrap#1645]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-04-19 141213](https://github.com/pizzaboxer/bloxstrap/assets/165406154/c738b1f3-99e9-4433-896c-9391a1cc4d8b)
![Screenshot 2024-04-19 141205](https://github.com/pizzaboxer/bloxstrap/assets/165406154/5e2b87b7-73cf-4949-9654-903d5bac7bf0)
these was the things before reinstallation

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by wacke15** [comment]
it worked when i uninstalled and reinstalled idk why does this happen

**Comment by pizzaboxer** [comment]
I'm sure the Wiki page explains it to you.
