### ISSUE TITLE
[Fps Drop After Downloading Bloxstrap] 

### ISSUE THREAD

**Issue by YAM35C** [pizzaboxer/bloxstrap#1646]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i have been having this problem for months. But after i downloaded Bloxstrap My FPS Dropped in days and i used to get 210 fps now i get 150 to 100 fps???
Any Solutions to This?
It might be something with the gpu. But the FPS drop happened after i downlaoded bloxstrap.

**Comment by pizzaboxer** [comment]
> But after i downloaded Bloxstrap My FPS Dropped in days and i used to get 210 fps now i get 150 to 100 fps???

What were you using to unlock your FPS before using Bloxstrap?

**Comment by YAM35C** [comment]
Nothing but i fixed by using some codes i found and did some maintenance on my pc too so i think i should be good for now

**Comment by YAM35C** [comment]
now im back to 200 fps and even 300!!!

**Comment by pizzaboxer** [comment]
> but i fixed by using some codes i found 

Can you explain further please?

**Comment by YAM35C** [comment]
> Can you explain further please?
 
So i found A video that gave some codes for fastflags to get more fps and it works by removing some particles and stuff to make it fast and get more fps so i used it. Oiamd A question i have. How can i put Bloxstrap on Geforce Experience?

**Comment by Sourv4** [comment]
can u give me the vid cuz roblox with bloxtrap is running me 10 fps

**Comment by pizzaboxer** [comment]
> So i found A video that gave some codes for fastflags to get more fps and it works by removing some particles and stuff to make it fast and get more fps so i used it.

If they work for you then that's fine, but be wary of doing stuff like that as explained here: https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags

> can u give me the vid cuz roblox with bloxtrap is running me 10 fps

What does Roblox normally run at without using Bloxstrap?
