### ISSUE TITLE
[BUG] Argument error

### ISSUE THREAD

**Issue by baolapvn** [pizzaboxer/bloxstrap#1647]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i open roblox it say System.ArgumentException: '' is not a valid value for property 'Title'. I can't even deleted bloxstrap because it say the same thing. This is the log file 
[Bloxstrap_20240419T193335Z.log](https://github.com/pizzaboxer/bloxstrap/files/15045059/Bloxstrap_20240419T193335Z.log)

**Comment by pizzaboxer** [comment]
If you open the Bloxstrap Menu, under the Appearance tab, under 'Bootstrapper customization', what is the title set to?

**Comment by baolapvn** [comment]
the title is set to nothing, I didn't touch it

**Comment by baolapvn** [comment]
nvm i just fix it, ty
