### ISSUE TITLE
bloxstrap does not have enough disk space to dowload and install roblox. please free up some space and try again

### ISSUE THREAD

**Issue by DiegoGaming1** [pizzaboxer/bloxstrap#1648]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I open Bloxstrap I get the message bloxstrap does not have enough disk space to dowload and install roblox. please free up some space and try againbut every time I remove some stuff and i try again but  it always says it I don't know why it keeps happening and I want do see if some people know how to fix it

**Comment by pizzaboxer** [comment]
I know of one other person who's been having this issue. Haven't yet figured out what it is but I'm currently figuring it out. 
Join the Bloxstrap discord server if you haven't yet, and join this thread: https://discord.com/channels/1099468797410283540/1225864991513772032

**Comment by DiegoGaming1** [comment]
Alr thanks

**Comment by cryolithic** [comment]
`        internal static long GetFreeDiskSpace(string path)
        {
            foreach (DriveInfo drive in DriveInfo.GetDrives())
            {
                if (path.StartsWith(drive.Name))
                    return drive.AvailableFreeSpace;
            }

            return -1;
        }`

you want `path.ToUpper().StartsWith`

**Comment by pizzaboxer** [comment]
> you want path.ToUpper().StartsWith

Good point but I'm still not sure if that's what's causing it since everyone I was talking to did not change their install path from the default one

**Comment by cryolithic** [comment]
@pizzaboxer I was getting the error, this resolved it for me.

**Comment by pizzaboxer** [comment]
how the fuck

**Comment by cryolithic** [comment]
![Screenshot 2024-07-02 145150](https://github.com/pizzaboxer/bloxstrap/assets/11305845/aa7f1656-a0c7-4eaa-acb8-68ab3a53ab57)

Likely when he moved his user directories, he typed lower case here

**Comment by cryolithic** [comment]
I've been bitten enough by unexpected case changes that unless case is important to you, use a case insensitive comparison for all string comparisons.

**Comment by pizzaboxer** [comment]
Problem should now be resolved, thank you @cryolithic
