### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nazzy3320** [pizzaboxer/bloxstrap#1649]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Settings.json' is denied.

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
