### ISSUE TITLE
Question: is using Bloxstrap a risk with the new Byfron Anti-Cheat?

### ISSUE THREAD

**Issue by imskyyc** [pizzaboxer/bloxstrap#165]
Bloxstrap is a great tool for making Roblox simply better in my opinion. But I've been concerned about using it due to the new 64-bit client's anti cheat. Is my account at risk for using Bloxstrap in any way? (Apologies if this is not the place to ask questions, I'm not aware of anywhere else.)

**Comment by thatsprettygood** [comment]
Please read the release notes before making an issue.

**Comment by thatsprettygood** [comment]
Please read the release notes before making an issue, Sky.

**Comment by imskyyc** [comment]
I've read it, and I understand that it may not "trip" Hyperion, I'm just worried there's still a risk.

**Comment by 6665335** [comment]
I mean there is, but not as much as you think. This is just like a short term "bypass"

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-and-Hyperion

**Comment by imskyyc** [comment]
Thanks.
