### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by Sourv4** [pizzaboxer/bloxstrap#1653]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\hp\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\RobloxPlayerBeta.exe' with working directory 'C:\Users\hp\Desktop'. Access is denied.

**Comment by pizzaboxer** [comment]
Try reinstalling Bloxstrap. Do not reinstall it as an Administrator.
