### ISSUE TITLE
[BUG] when i try to change my font it says that there was a bug.

### ISSUE THREAD

**Issue by gkritsovas** [pizzaboxer/bloxstrap#1655]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when I try to change my font it says that there was an exception that occurred while running bloxtrap. specifically [System.UnauthorizedAccessException: Access to the path 'C:\Users\ft996\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' is denied.]

![Bloxstrap_fa4fM0Otfd](https://github.com/pizzaboxer/bloxstrap/assets/167632784/eda11914-2d79-4dd1-807d-bab42883e366)
 and I do not know what to do.

**Comment by pizzaboxer** [comment]
Open the file path given, open the file properties for CustomFont.ttf, and check to make sure it's not marked as read-only.

**Comment by gkritsovas** [comment]
![explorer_u2askzd7XF](https://github.com/pizzaboxer/bloxstrap/assets/167632784/c3999ac8-b918-4466-b2f2-2df55cd45377)

it doesnt work???

**Comment by pizzaboxer** [comment]
I'm talking about CustomFont.ttf.

**Comment by gkritsovas** [comment]
sorry for the troubles and thaks you.
