### ISSUE TITLE
[BUG] Reinstalling bloxstrap after changing user file 

### ISSUE THREAD

**Issue by furrysteak** [pizzaboxer/bloxstrap#1656]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Recently I changed my user file name because my old one was from the compony I bought the pc from and It felt weird to have it that, whenever I try reinstalling bloxstrap it gives me a window saying System.UnauthorizedAccessException: Access to the path 'C:\Users\Username\AppData\Local\Bloxstrap\Logs' is denied. 
If i were to run it in administrator it would create a file in users of the older user and even after that it would still give the same message. I'm unsure what to do please help. I understand this is a known issues but doing the things it says in the forum doesn't work.

**Comment by pizzaboxer** [comment]
Open the registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap`, and update the 'InstallLocation' property to point to the correct path.

**Comment by furrysteak** [comment]
thank you
