### ISSUE TITLE
[BUG] bloxstrap doesnt launching roblox (only in background)

### ISSUE THREAD

**Issue by RedMajor** [pizzaboxer/bloxstrap#1659]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxstrap doesnt launch roblox 
bloxstrap closed when is "starting roblox"
i tried everything
![dJforeC](https://github.com/pizzaboxer/bloxstrap/assets/143196536/f5e01947-9fa3-404e-811d-5fb5ecbc1af3)

![6RrcKt6](https://github.com/pizzaboxer/bloxstrap/assets/143196536/fbd13a56-e538-46ab-9a96-a5d637c82d22)
pls help i didnt play roblox 1 day

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by yerbowanie** [comment]
Hey i have the same issue as this user, but for me it only happens with bloxstrap, i guess the only solution is to use roblox player orrr?

**Comment by pizzaboxer** [comment]
> Hey i have the same issue as this user, but for me it only happens with bloxstrap, i guess the only solution is to use roblox player orrr?

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by yerbowanie** [comment]
[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/15067705/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/15067706/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/15067708/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch#b-d-f-bloxstrap-only-your-fastflag-configuration-is-unstable. Delete all of your configured FastFlags in the FastFlag editor, then try and launch again.

**Comment by yerbowanie** [comment]
Hello, ive deleted all of my fastflags and it worked, but nows the question,

how the fuck do i track down what fflag caused this

**Comment by pizzaboxer** [comment]
> how the fuck do i track down what fflag caused this

Read the warning at the top of https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags

You should only be adding stuff if you know what they do. This is heavily suggesting that you don't really know what any of them do. Even if you removed the one that was causing this specific issue, you would very likely run into other usability issues.

**Comment by lolololololgrgr** [comment]
Hello, none of the above helped and I didn’t have the file “_

> Modifications\ClientSettings\ClientAppSettings.json

_” Do I need to add it somehow or is it located somewhere?__

**Comment by pizzaboxer** [comment]
Do you not have it? Show a screenshot of the installation folder please.

**Comment by lolololololgrgr** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/168120200/09043983-2792-44bc-a0c3-aa2995808ab7)

**Comment by pizzaboxer** [comment]
The modifications folder is right there.

**Comment by lolololololgrgr** [comment]
Why then didn’t anything help me?

**Comment by pizzaboxer** [comment]
I'm a little confused, what issue are you having and what are you trying to do?

**Comment by 10kvibezzz** [comment]
Hey yesterday i had the exact same problem i deleted all flags and it worked today i had the same problem again i deletet all flags and its not working pls help

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by 10kvibezzz** [comment]
Yes

**Comment by pizzaboxer** [comment]
> Yes

If your issue is still happening, does it happen only when using Roblox?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
