### ISSUE TITLE
Option to Ignore Channel Changes

### ISSUE THREAD

**Issue by kyjikyjikyji** [pizzaboxer/bloxstrap#166]
I'd like to be able to stay on the 'LIVE' channel without having to deny a channel change every time I start Roblox.

Could the 'Prompt on Roblox-forced channel change' toggle instead be turned into a drop-down menu that has the old behavior along with an additional option to ignore requested channel changes entirely, without prompting the user?

**Comment by pizzaboxer** [comment]
Whoops, I had this in the 2.3.0 checklist because I thought it would be a good idea, but then thought it wasn't much of a problem anyway. Readding.

**Comment by pizzaboxer** [comment]
Pending release, but I have this in the todo list, so I'm closing this as redundant.
