### ISSUE TITLE
Higher quality hats in R6 [REQ] 

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [pizzaboxer/bloxstrap#1664]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

for some reason roblox makes hats in R6 lower quality so it looks kind of weird and this feature might be kind of useful for people that get bugged from that glitch (also i know pizzabloxer is probably on hiatus but  this is so annoying, also if its already a fastflag please tell me which one it is)

**Comment by pizzaboxer** [comment]
> for some reason roblox makes hats in R6 lower quality so it looks kind of weird and this feature might be kind of useful for people that get bugged from that glitch

Yeah, R6 just does that. Unfortunately, there is no way around this as far as we know.
