### ISSUE TITLE
[BUG] roblox wont launch on my new pc

### ISSUE THREAD

**Issue by thatguy12323** [pizzaboxer/bloxstrap#1665]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

at first before i downloaded bloxstrap, its working fine but when i downloaded bloxstrap it wont work now. please respond quickly! i tried uninstall bloxstrap and download original one it wont work, now i cant also uninstall original roblox. thats it, thanks also respond fast.

**Comment by thatguy12323** [comment]
it says starting roblox and after that it shows nothing.

**Comment by pizzaboxer** [comment]
> i tried uninstall bloxstrap and download original one it wont work, now i cant also uninstall original roblox.

You might not be happy with what I'm about to say, but this isn't an issue on my end. Bloxstrap is completely isolated from Roblox's own launcher, there's no reason at all for installing Bloxstrap to make using the original launcher not work. The only thing I can say is that this is an issue somewhere with Roblox itself.

Though, since you mention it:

> now i cant also uninstall original roblox

Why not? I'd expect that to still work fine.

**Comment by thatguy6321** [comment]
> > i tried uninstall bloxstrap and download original one it wont work, now i cant also uninstall original roblox.
> 
> You might not be happy with what I'm about to say, but this isn't an issue on my end. Bloxstrap is completely isolated from Roblox's own launcher, there's no reason at all for installing Bloxstrap to make using the original launcher not work. The only thing I can say is that this is an issue somewhere with Roblox itself.
> 
> Though, since you mention it:
> 
> > now i cant also uninstall original roblox
> 
> Why not? I'd expect that to still work fine.

i mean like sometimes it stucked at please wait at original one and it disappeared the original roblox didnt work also the same as microsoft one, blox strap it didnt launch the game after clicking play and it says starting roblox then it didnt show anything

**Comment by pizzaboxer** [comment]
> i mean like sometimes it stucked at please wait at original one and it disappeared 

So, not even the original launcher itself works when you try to use it? It just closes abruptly?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
