### ISSUE TITLE
[BUG] getting error and cannot install roblox 

### ISSUE THREAD

**Issue by GithubUser12341** [pizzaboxer/bloxstrap#1672]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[Inner Exception]
System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by GithubUser12341** [comment]
Fix it

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by Blady02** [comment]
It seems like im running into this exact same issue aswell. This is happening with both base roblox, roblox studio and Bloxstrap. Here is a log file from bloxstrap whenever this error appears. 

[Bloxstrap_20240503T212459Z.log](https://github.com/pizzaboxer/bloxstrap/files/15205203/Bloxstrap_20240503T212459Z.log)

**Comment by pizzaboxer** [comment]
What do you see when you try to access https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE in your browser?

**Comment by Blady02** [comment]
![firefox_qw5zw3xzvw](https://github.com/pizzaboxer/bloxstrap/assets/168870691/d593ebbb-bfc7-42ec-90ce-14c01ba35085)

One thing to mention is this happens specifically on my PC only. 

I tried switching wifis, switching my vpn on and off, updating dns, updating and resetting card drivers, and even redownloading both roblox and bloxstrap multiple times on multiple networks.

**Comment by Blady02** [comment]
I've just managed to find a fix to this.

Many methods showcased turning off your antivirus protection which i did to no avail. However, what i actually had to do was SHUT OFF the software entirely, and then it just loaded in. 

The problem is, when i turn it back on it immediately boots me off with the ssiconnectionfail error once again.

**Comment by Blady02** [comment]
I have managed to fully fix it. What i had to do was disable self defense in my antivirus software (I use kaspersky), then delete the reports log from the programfiles of Kaspersky Lab. 

This was such a horrendously personalized issue that it might just work for anyone who has tried every method and it still didnt work.

C:\ProgramData\Kaspersky Lab\AVP21.3\Report, then delete the entire folder, and reboot.

Now both Bloxstrap and Regular Roblox work again

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
