### ISSUE TITLE
[BUG]  for some reason my antivirus dosent like bloxstrap right now and it now its no starting

### ISSUE THREAD

**Issue by benhohohonoyes** [pizzaboxer/bloxstrap#1675]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/134026463/7e693718-48fd-4807-accf-16673a94d3bc)

**Comment by bluepilledgreat** [comment]
Fix your anti-virus then. What can we do?

**Comment by pizzaboxer** [comment]
I'm not sure if this is because of an antivirus conflict. Can you send the log file please?

**Comment by pizzaboxer** [comment]
Got some reports regarding the same issue, and it is an antivirus conflict. It's Avast being stupid. Whitelist it there please.
