### ISSUE TITLE
Displaying the wrong game on discord status when roblox opens[BUG] 

### ISSUE THREAD

**Issue by JoeNonPr0** [pizzaboxer/bloxstrap#1676]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i launch a game on Roblox, not the roblox launcher itselr, it displays the game on discord as “Euro Truck Simulator 2” when i dont even own that game anywhere on my pc. Is there anyway to fix this?

**Comment by JoeNonPr0** [comment]
I reinstalled both roblox and BloxStrap which seems to have fixed it for now. I will add another comment if it ever pops up again.

**Comment by pizzaboxer** [comment]
> it displays the game on discord as “Euro Truck Simulator 2” when i dont even own that game anywhere on my pc. Is there anyway to fix this?

Yes, that's how using Roblox with shaders works. That's to be expected.
