### ISSUE TITLE
[BUG] An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Sku77ed** [pizzaboxer/bloxstrap#1677]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.OverflowException: Arithmetic operation resulted in an overflow.
[Bloxstrap_20240424T023040Z.log](https://github.com/pizzaboxer/bloxstrap/files/15086803/Bloxstrap_20240424T023040Z.log)

**Comment by pizzaboxer** [comment]
Known bug, though thank you for reporting.
