### ISSUE TITLE
How to install roshade?

### ISSUE THREAD

**Issue by Danilmikhan** [pizzaboxer/bloxstrap#168]
I tried using the method where you use the roblox's install location but roshade doesnt work.

**Comment by pizzaboxer** [comment]
Try setting your Roblox channel to LIVE and enabling prompting for automatic channel changes as described in v2.2.0's release notes.

**Comment by Danilmikhan** [comment]
It didnt work

**Comment by Danilmikhan** [comment]
It didnt work

**Comment by pizzaboxer** [comment]
Did you reinstall Roshade after doing that?

**Comment by Danilmikhan** [comment]
let me try

**Comment by Danilmikhan** [comment]
Still didnt work

**Comment by pizzaboxer** [comment]
Can I see what settings you have configured in the Installation tab and the Behaviour tab?

**Comment by Danilmikhan** [comment]
![image](https://user-images.githubusercontent.com/128136925/235301934-a2b50d43-24da-4ed8-bbed-bb69787e91d8.png)

![image](https://user-images.githubusercontent.com/128136925/235301948-a9f7400e-3693-417c-b983-13e996966b6b.png)

**Comment by pizzaboxer** [comment]
Navigate to `%localappdata%\Roblox\Versions\version-31b938635c234124` in the file browser. Can you show the files listed in there?

**Comment by Danilmikhan** [comment]
![image](https://user-images.githubusercontent.com/128136925/235302060-54681e59-ace4-4c44-82d7-e8a8577c202e.png)

**Comment by Danilmikhan** [comment]
_**E**_

**Comment by pizzaboxer** [comment]
Are you sure you installed Roshade? The files for it don't seem to be there.

**Comment by Danilmikhan** [comment]
Yes i am sure
![image](https://user-images.githubusercontent.com/128136925/235302450-a9884c0b-9182-409f-adad-00c4238237b7.png)

**Comment by Danilmikhan** [comment]
### **E**

**Comment by Danilmikhan** [comment]
### _**E?**_

**Comment by pizzaboxer** [comment]
Seems like a Roshade problem then, since it's not properly installing to the Roblox version folder. I can't do much about that, so I suggest you just use the ReShade option in the menu instead.

**Comment by Danilmikhan** [comment]
ok

**Comment by Danilmikhan** [comment]
my computer is gonna melt lol
