### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GiftDUBB** [pizzaboxer/bloxstrap#1680]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I open Bloxstrap it is not loading and doesn't load(*)

**Comment by pizzaboxer** [comment]
Can you clarify further please? Do you see the Bloxstrap launcher show when Roblox tries to launch?

**Comment by GiftDUBB** [comment]
yes

**Comment by GiftDUBB** [comment]
i uninstalled it now it is back up and runing

**Comment by GiftDUBB** [comment]
but if Bloxstrap it is not loading and doesn't load can tell me how to fix it

**Comment by pizzaboxer** [comment]
> but if Bloxstrap it is not loading and doesn't load can tell me how to fix it

So, Roblox doesn't open only when you use Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
