### ISSUE TITLE
Can't enable Chrome UI

### ISSUE THREAD

**Issue by DarkCatto** [pizzaboxer/bloxstrap#1681]
I tried enable Chrome UI with flags and disabled multi instances but it don't helped

Im not very good at english

**Comment by pizzaboxer** [comment]
> I tried enable Chrome UI with flags and disabled multi instances but it don't helped

How did you try enabling iti?

**Comment by pizzaboxer** [comment]
What specifically did you do? What did you add?

**Comment by DarkCatto** [comment]
Sorry.
I added this flags:

{
    "FFlagEnableInGameMenuChromeABTest2": "True",
    "FFlagEnableReportAbuseMenuRoactABTest2": "True"
}

**Comment by pizzaboxer** [comment]
Those aren't what you need. You only need this one:

```json
{
    "FFlagEnableInGameMenuChrome": "True"
}
```
