### ISSUE TITLE
[BUG] It doesnt open anymore

### ISSUE THREAD

**Issue by WeakestTodoFan45** [pizzaboxer/bloxstrap#1682]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I watched a video on youtube to boost my fps while playing, here is the link to it: youtube.com/watch?v=3TSovm9RU_I
I followed the guide and did everything, once i tried to play, the game would send me a message saying that they have to quit me, even  though i kept hearing the game sounds. So i deleted the stuff i added, but it never worked again. So i decided to delete bloxtrap and try again, but i got this message, and again the game wouldnt open at all. 

System.AggregateException: One or more errors occurred. (The process cannot access the file 'C:\Users\Bedo\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.)

[Inner Exception]
System.IO.IOException: The process cannot access the file 'C:\Users\Bedo\AppData\Local\Bloxstrap\Versions\version-492b7f0827474659\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.

And here is the log file:
[Bloxstrap_20240424T202409Z.log](https://github.com/pizzaboxer/bloxstrap/files/15100095/Bloxstrap_20240424T202409Z.log)

**Comment by pizzaboxer** [comment]
> So i decided to delete bloxtrap and try again, but i got this message, and again the game wouldnt open at all.

You deleted Bloxstrap while Roblox was stiill running in the background. Close Roblox first then reinstall again. That would also explain why none of your changes were applying.
