### ISSUE TITLE
[BUG] Bloxstrap and bloxstrap menu are the same app

### ISSUE THREAD

**Issue by jakeiscool797979** [pizzaboxer/bloxstrap#1683]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap and bloxstrap menu are the same app so when i try and open the bloxstrap menu it just opens roblox and the only way to open the bloxstrap menu is if i manually go to settings and modify it

**Comment by pizzaboxer** [comment]
> So i decided to delete bloxtrap and try again, but i got this message, and again the game wouldnt open at all.

https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu

You would've been told about this when you first installed it.

**Comment by jakeiscool797979** [comment]
sorry and also it just fixed itself overnight for some reason
