### ISSUE TITLE
[BUG] Bloxstrap is unable to connect to bloxstrap

### ISSUE THREAD

**Issue by Maxyboy203** [pizzaboxer/bloxstrap#1684]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-04-25 094720](https://github.com/pizzaboxer/bloxstrap/assets/168062381/3c2e8245-cec6-44bd-9cf2-f7aea8de492a)

This has happened for 2 days straight I've been trying to play ROBLOX but bloxstrap isn't letting me in and I've checked playing without bloxstrap and it worked can you please check what's wrong?

**Comment by pizzaboxer** [comment]
> can you please check what's wrong?

Seems like an antivirus issue, check to make sure it's not causing any conflicts.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
