### ISSUE TITLE
The old cursor png are not completely erased

### ISSUE THREAD

**Issue by LatteLuis** [pizzaboxer/bloxstrap#1685]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

the far cursor png is bad and not completely :( please correct that

**Comment by pizzaboxer** [comment]
What?

**Comment by Synthesiz-ed** [comment]
im pretty sure this is what they mean 

https://github.com/pizzaboxer/bloxstrap/assets/148590223/f730a1b9-846d-4ad2-a876-cf43fa7588fe

![image](https://github.com/pizzaboxer/bloxstrap/assets/148590223/269db870-6454-410a-8bbe-d56d3de52d7e)

**Comment by LatteLuis** [comment]
YEAH THATS RIGHT

**Comment by LatteLuis** [comment]
I tried modifying the Bloxtrap assets but it didn't work :c

**Comment by pizzaboxer** [comment]
Yes, that's how it's supposed to be.

**Comment by LatteLuis** [comment]
can you correct that :,c or just put a new option of this cursor but
modified pls

**Comment by LatteLuis** [comment]
That makes me uncomfortable

**Comment by pizzaboxer** [comment]
> can you correct that :,c or just put a new option of this cursor but

That's how it's supposed to be.
