### ISSUE TITLE
[BUG] Today, most, if not all of my features were gone.

### ISSUE THREAD

**Issue by aqua8811** [pizzaboxer/bloxstrap#1686]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've already tried uninstalling, that didn't work, for my fast flag editor, i tried resetting that as well. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/168149157/3e3e8392-0315-4ce0-bedd-28dc6541be34)
![image_2024-04-25_200417152](https://github.com/pizzaboxer/bloxstrap/assets/168149157/87a30ed0-3614-49be-9fe0-265b6c551681)
![image_2024-04-25_200744964](https://github.com/pizzaboxer/bloxstrap/assets/168149157/259c4692-2fb6-4fd6-8458-13463822e87d)

*All the settings for these mods are turned on
For my custom cursor, I cant exactly show that with a screenshot, but I was using the cartoony version, now its back to the current cursor, and I'm sure there's more that I've yet to notice. But it'd be very nice to see some of these get fixed,

Edit*
Sorry, I might've messed up the screenshots. this is the first time doing it, and I'm not sure how to do it correctly or fix it, unless its manageable. 
also, I'm not very sure if you've already seen something like this, I did go over the instructions and what I thought fit my issue, but didn't see anything like this. So I'm sorry if this is an inconvenience.

**Comment by aqua8811** [comment]
Sorry, I might've messed up the screenshots. this is the first time doing it, and I'm not sure how to do it correctly or fix it, unless its manageable. 
also, I'm not very sure if you've already seen something like this, I did go over the instructions and what I thought fit my issue, but didn't see anything like this.

**Comment by jasdhkjahsfkjsdhfg** [comment]
Im experiencing the same issue

**Comment by aqua8811** [comment]
Yeah, I'm not sure what it is though, since I haven't changed anything prior to it being broken.

**Comment by espiraelthegoat** [comment]
Me aswell.

**Comment by pizzaboxer** [comment]
Roblox just updated. Make sure Roblox isn't running in the background first, then try launching again.
