### ISSUE TITLE
error code 403

### ISSUE THREAD

**Issue by prospike1** [pizzaboxer/bloxstrap#1688]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\user\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by aqua8811** [comment]
I'm pretty sure if this is what I think it is, you would either restart your pc or delete the file "%localappdata%\Bloxstrap" manually.
It's the 3rd line in the "Known Issues" section on the wiki. 

But take my word for a grain of salt, I'm just assuming.

**Comment by pizzaboxer** [comment]
Read the preliminary instructions. https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
