### ISSUE TITLE
Roblox Just Updated and now the fps unlocker doesn't work.[BUG] 

### ISSUE THREAD

**Issue by SomeRandomRobloxPlayer23145** [pizzaboxer/bloxstrap#1689]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I clicked on play and bloxstrap was installing roblox. When I was in the game, the fps was stuck at 60.

**Comment by pizzaboxer** [comment]
Read the preliminary instructions. https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter
