### ISSUE TITLE
Fake byfron launcher style for bootstrapper

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#169]
https://twitter.com/JamesDaPringles/status/1651608194349711360 because why not

**Comment by pizzaboxer** [comment]
lol i was actually thinking about doing this

**Comment by Anonymousperson0016** [comment]
You should add this as an option for the bootstrapper.

**Comment by EasternBloxxer** [comment]
> You should add this as an option for the bootstrapper.

Yeah

**Comment by EasternBloxxer** [comment]
> eh
> ![image](https://user-images.githubusercontent.com/37438176/236850448-30c8dafa-b0af-4a07-b096-71c56940e7b3.png)
> 

Send fr

**Comment by 1011025m** [comment]
Small issue though, I'm not sure where to put the cancel button (there's none since it's fake but bloxstrap requires it).

<sup>it doesn't work atm, it's just a mockup</sup>

**Comment by pizzaboxer** [comment]
Oh, good point... there's no space below the progress bar.

**Comment by EasternBloxxer** [comment]
I will send the byfron logo used when I'm home

**Comment by EasternBloxxer** [comment]
https://media.discordapp.net/attachments/960704166181896243/1101974811258920970/image.png real

**Comment by 1011025m** [comment]
> https://media.discordapp.net/attachments/960704166181896243/1101974811258920970/image.png real

I can probably rework this to make it bigger, but I'm not sure what font they used at the bottom (and the font they used for the version and message text). If you could find it out please let me know!

**Comment by EasternBloxxer** [comment]
The version should probably be the Roblox version

**Comment by 1011025m** [comment]
Kinda works!
![WS9Fprl8Yx](https://github.com/pizzaboxer/bloxstrap/assets/37438176/578c88bf-24b6-4324-8183-e933d63d74d7)

**Comment by 1011025m** [comment]
github is returning 500 when i try to fork smh...

**Comment by ojpifdsaew** [comment]
You dont need to make the Byfron logo bigger, its a perfect fit!
![image](https://github.com/pizzaboxer/bloxstrap/assets/68922095/04b78a95-fe9b-4eeb-a0e9-fb2731f2f600)

**Comment by 1011025m** [comment]
> You dont need to make the Byfron logo bigger, its a perfect fit!
Sorry, by that I mean the source image should be in full quality (as big as possible). This reminds me the Roblox logo should've been in SVG...

**Comment by ojpifdsaew** [comment]
Well an average person wouldn't notice that is not as crisp as it should be, so its not a big deal, but you know its your choice
