### ISSUE TITLE
Roblox crashing randomly, crashes without crashdump prompt, happens alot. [BUG] 

### ISSUE THREAD

**Issue by NineTails666** [pizzaboxer/bloxstrap#1690]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Event Logger crashdump:

Faulting application name: RobloxPlayerBeta.exe, version: 0.622.0.60086, time stamp: 0x032658bb
Faulting module name: RobloxPlayerBeta.dll, version: 0.0.0.0, time stamp: 0x8a45a6a2
Exception code: 0xc0000005
Fault offset: 0x0000000001c16f74
Faulting process id: 0x0x4944
Faulting application start time: 0x0x1DA9796AE5142A2
Faulting application path: C:\Users\(my user)\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\RobloxPlayerBeta.exe
Faulting module path: C:\Users\(my user)\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\RobloxPlayerBeta.dll
Report Id: 7e45befd-1471-49be-b401-c739e518d4c9
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by NineTails666** [comment]
> As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Its very hard to even reproduce since it is so random, but the only other time it has done this, but done it less frequent is when I was using rbxfpsunlocker, however it crashed way less when doing that, if I was to guess every once a week or so, with Bloxstrap it seems to crash very frequent, as of Thursday this week it crashed pretty much every time I was in a game for a little over 15 mins, then later I uninstalled all of Roblox and Bloxstrap reinstalled and the same thing occurred.

Another note I have noticed with Oculus being open and the OVR background apps are running it seems it crashes less, however this may be just lucky coincidence, another thing is that with OVR open games and Roblox loads faster which is weird because it isn't random it happens every time the OVR is open, but closed all games and Roblox itself loads slower.

This is a long reply, but i am making sure you are getting all of what I am having problems with so that you can tell me if its a Bloxstrap issue of something on my behalf.

**Comment by pizzaboxer** [comment]
> pretty much every time I was in a game for a little over 15 mins, then later I uninstalled all of Roblox and Bloxstrap reinstalled and the same thing occurred.

Let me see if there's a possible correlation. Can you upload your configuration please? https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by NineTails666** [comment]
[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/15140565/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/15140566/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/15140568/ClientAppSettings.json)

Hope this is of use to you. 
The only modifications I have done is change death sound to a custom one, and change the cursor to a custom one.

**Comment by pizzaboxer** [comment]
The only thing that can possibly be causing this is your configured framerate limit, so try setting it to zero and see if that changes anything. If it still occurs at the frequency though, then I'm not sure what correlation this is.

**Comment by NineTails666** [comment]
> The only thing that can possibly be causing this is your configured framerate limit, so try setting it to zero and see if that changes anything. If it still occurs at the frequency though, then I'm not sure what correlation this is.

Is there a reason why the set fps limit would cause a crash?
If so could you elaborate.

**Comment by pizzaboxer** [comment]
> Is there a reason why the set fps limit would cause a crash?

It's known to only cause crashes when teleporting between places, and it's because increasing it has some other minor side-effects, which I explain here: https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#framerate-limit

**Comment by Fartbawl** [comment]
I don't think it's an issue with bloxstrap. I have the same issue and I've factory reset my PC and roblox still crashes (no bloxstrap installed). Our logs are practically the same. Been going on for about a week or two now, very frustrating. Here's a devpost of someone else having the same issue, guess they're looking into it. [https://devforum.roblox.com/t/constant-crashing-in-any-game-i-go-into/2942779](url)

**Comment by pizzaboxer** [comment]
> I don't think it's an issue with bloxstrap. 

In your case, it's not. However, it's definitely not consistent, so I just want to find out for this person specifically.

**Comment by NineTails666** [comment]
> I don't think it's an issue with bloxstrap. I have the same issue and I've factory reset my PC and roblox still crashes (no bloxstrap installed). Our logs are practically the same. Been going on for about a week or two now, very frustrating. Here's a devpost of someone else having the same issue, guess they're looking into it. [https://devforum.roblox.com/t/constant-crashing-in-any-game-i-go-into/2942779](url)

I used regular Roblox for some time and I don't remember it crashing like it does now, I also don't recall it crashing ever.
The times it has done what it does now is when i used rbxfpsunlocker for a bit, then moved to Bloxstrap.

I as said I don't recall it crashing like it does now back when I used vanilla Roblox, it may have in the past but I don't remember.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
