### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by asasinul69** [pizzaboxer/bloxstrap#1692]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i open the app called "Play Roblox " it pops up the message with  : "starting roblox" but then it gives my an error saying:

                        -an exception occured while running Bloxstrap

      and bellow this , it shows up something like :   " system. component model .win32Exception : an error occured trying to start process 'c\users\hp" etc.... 

                          how do i fix it ? ( i will try to paste a file below with a imagine containing what it shows up )

![Capture](https://github.com/pizzaboxer/bloxstrap/assets/168231959/3c2e935e-0ae7-4b48-8913-5830f2b071e2)

**Comment by asasinul69** [comment]
NVM i rezolved the problem i just needed to make bloxstrap administrator

**Comment by pizzaboxer** [comment]
> NVM i rezolved the problem i just needed to make bloxstrap administrator

This is happening because you initially installed Bloxstrap as an administrator. Reinstall it without administrator perms.
