### ISSUE TITLE
[BUG] BloxStrap isn't opening after i launch it, tried everything the forum says, everything the discord member said, nothing works, i need help

### ISSUE THREAD

**Issue by CasanovaMista** [pizzaboxer/bloxstrap#1693]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

One day, when i launched bloxstrap, it didn't open. I thought it was just a PC bug so i restarted my pc. After that i retried but nothing worked. I tried to uninstall roblox and install it again, uninstall bloxstrap ( which doesn't work because it just won't open), Tried every Bloxstrap shortcut possible. But nothing works, i need help.

**Comment by pizzaboxer** [comment]
Does Bloxstrap create any log files in the `%localappdata%\Bloxstrap\Logs` folder?

**Comment by trulywes** [comment]
> Does Bloxstrap create any log files in the `%localappdata%\Bloxstrap\Logs` folder?
I have the same problem and when i checked the folder theres a bunch of text documents

**Comment by pizzaboxer** [comment]
> I have the same problem and when i checked the folder theres a bunch of text documents

Send the latest one here

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
