### ISSUE TITLE
Attempted to teleport to a restricted place

### ISSUE THREAD

**Issue by DragonAllahFire** [pizzaboxer/bloxstrap#1696]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When using the multi-feature, it works perfectly, but when I try to teleport into an instance (e.g. going from a tower defense game into one of their maps) it will say Attempted to teleport to a restriced place, error code 773. I thought this was a bug with roblox and not bloxtrap, however this applies to all the accounts running except from the one that has launched most recently. I have tried reinstalling bloxtrap entirely but this still did not fix this issue. Please help me find a solution 🙏

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Attempted-to-teleport-to-a-restriced-place%22-error-when-using-multiple-instances
