### ISSUE TITLE
[BUG] d

### ISSUE THREAD

**Issue by celexh** [pizzaboxer/bloxstrap#1697]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.ComponentModel.Win32Exception: Access is denied.
[Bloxstrap_20240428T034052Z.log](https://github.com/pizzaboxer/bloxstrap/files/15140677/Bloxstrap_20240428T034052Z.log)

**Comment by pizzaboxer** [comment]
This is sort of seeming like an antivirus issue since Bloxstrap isn't allowed to check to see if Roblox is currently running. Can you check if your antivirus is causing any issues please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
