### ISSUE TITLE
screen shakes [BUG] 

### ISSUE THREAD

**Issue by adfarwara** [pizzaboxer/bloxstrap#1698]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when im playing blox fruits when i punch or anything that would normally make the screen shake is severly over exaggerated when i do this when i have the software open i uninstalled and it wasnt doing it i really want to know what fixs it

**Comment by pizzaboxer** [comment]
> the screen shake is severly over exaggerated

If you set the framerate limit to zero, does the problem go away?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
