### ISSUE TITLE
Would it at all be possible to have an option to remove the new desktop app part from Bloxstrap?

### ISSUE THREAD

**Issue by Iamuss76** [pizzaboxer/bloxstrap#17]
https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app has managed to do this quite well, but i've just discovered bloxstrap and would like to see either them combined or be able to have the option here for what that one does

**Comment by pizzaboxer** [comment]
Bloxstrap is already designed to not use the desktop app when launched from the Roblox website. Do you mean having an option to enable using the desktop app on web launch?

**Comment by Iamuss76** [comment]
I guess an option could be nice for the 2 people who do like it, but I assumed it was part of it because when you download the exe, it opens the beta app

**Comment by pizzaboxer** [comment]
Oh, I see. No, it only does that after install/update. Launching through the desktop app is already supported with the "Play Roblox" option in the start menu too.
