### ISSUE TITLE
[BUG] Bloxstrap is unable to connect to Roblox

### ISSUE THREAD

**Issue by Venade** [pizzaboxer/bloxstrap#1700]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu. (clientsettings.roblox.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.

**Comment by pizzaboxer** [comment]
If this is happening every time you try to launch, then this is very likely an antivirus related issue. Is this still happening?
