### ISSUE TITLE
Luanching roblox error [BUG] 

### ISSUE THREAD

**Issue by alexwasnthere2** [pizzaboxer/bloxstrap#1701]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\Croosh Customs\AppData\Local\Bloxstrap\Versions\version-24872f7beace4d0a\RobloxPlayerBeta.exe' with working directory 'C:\WINDOWS\system32'. Access is denied.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22An-error-occurred-trying-to-start-process%22-error-when-launching-Roblox
