### ISSUE TITLE
[BUG] in the mods folder, theres no textures folder.

### ISSUE THREAD

**Issue by marggan** [pizzaboxer/bloxstrap#1702]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i open the mods folder and I saw that there was no content folder.

**Comment by pizzaboxer** [comment]
Read https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods.

"By default, the mods folder does not have the directory structure of the version folder. So, you will often need to create new folders in order to represent your file's location within the version folder."
