### ISSUE TITLE
[BUG] Roblox launching on backround

### ISSUE THREAD

**Issue by Flyzr** [pizzaboxer/bloxstrap#1703]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hi, recently i got a issue that happens on both, bloxtrap and Roblox. Everytime i launch roblox instance, it launches on backround, i tried reinstalling everything

**Comment by pizzaboxer** [comment]
This is an issue with Roblox itself. I can't do much to help you other than tell you to read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch for any potential fixes.
