### ISSUE TITLE
[REQ] Please make it so i can change the install location of the folder AFTER downloading

### ISSUE THREAD

**Issue by ClocknerTH** [pizzaboxer/bloxstrap#1705]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Just add a simple option in the "Installation" part that is called "Change Installation Folder" in which you can reselect where Bloxstrap is downloaded

**Comment by pizzaboxer** [comment]
> Just add a simple option in the "Installation" part that is called "Change Installation Folder" in which you can reselect where Bloxstrap is downloaded

Just reinstall it. However, in the future, we do plan to make this a lot better by just making it so you can move the folder without issue.
