### ISSUE TITLE
[BUG] Cannot Remove/Change Custom Font 

### ISSUE THREAD

**Issue by Arqxot** [pizzaboxer/bloxstrap#1707]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\Arqxot\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' is denied.

I applied a font and after I testing the font I like, I wanted to change it but this error code came in and I cannot change my font.

**Comment by pizzaboxer** [comment]
Open the mods folder, go to the content/fonts folder, open the file properties for CustomFont.ttf and ensure it's not marked as read-only.
