### ISSUE TITLE
[REQ] Is there a way to adjust the amount of particles?

### ISSUE THREAD

**Issue by daflame899** [pizzaboxer/bloxstrap#1708]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Is there a way to adjust the amount of particles? (I'm not sure if this exists but I couldn't find anything to adjust partciles, that's why I'm asking)

**Comment by pizzaboxer** [comment]
Not that I'm aware of, no. Sorry.
