### ISSUE TITLE
[BUG] "Access is denied."

### ISSUE THREAD

**Issue by ghost** [pizzaboxer/bloxstrap#1709]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240430T073156Z.log](https://github.com/pizzaboxer/bloxstrap/files/15160136/Bloxstrap_20240430T073156Z.log)
I keep getting the "Access is denied" message whenever I open Bloxstrap. I have restarted my computer and tried deleting the "Local" file, but none of them work.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
