### ISSUE TITLE
Custom game discord rich presence

### ISSUE THREAD

**Issue by EpixScripts** [pizzaboxer/bloxstrap#171]
When a Roblox game prints a message to the output, it also goes into the Roblox logs. This gives a way of a Roblox game "sending messages" to Bloxstrap by reading the log files.
I am thinking of designating a certain specific format string (like "RichPresenceSet...") that a game can print that lets them customize the rich presence status more than just the game name and icon.

Just a thing I came up with, for example in an open world game exploring different areas you could display what area you're in, or have custom functionality for joining "squads" with games that create reserved servers (joining through roblox's deeplinking feature).

**Comment by pizzaboxer** [comment]
Huh, interprocess communication between Roblox games and Bloxstrap was definitely not something I had in mind. Really neat idea, but I can't help but wonder if any developers are even going to bother using this.

**Comment by SWG64** [comment]
this could be cool but idk if many devs are gonna support it
i can imagine like 2 games with very low player counts having support for bloxstrap

**Comment by noblereign** [comment]
if this was added i would use it, i had a game that used to support the roactivity api so i can probably revive that with bloxstrap  
i dont really care if only a few people would ever have it i just think its neat

**Comment by pizzaboxer** [comment]
I think I got the implementation right: https://www.youtube.com/watch?v=8yGinJMO1Ms

**Comment by JaksonD** [comment]
It's really silly, sure, but I'd absolutely make use of this in the games I work on. The amount of people I've met who use Bloxstrap is certainly non-negligible.

Bonus points if there's some obscure way for a game to be able to tell if Bloxstrap is being used on the target PC so I'm not flooding the logs if someone doesn't use it.

**Comment by pizzaboxer** [comment]
> Bonus points if there's some obscure way for a game to be able to tell if Bloxstrap is being used on the target PC so I'm not flooding the logs if someone doesn't use it.

It's fine, you won't really be doing that much compared to how large log files usually get. It's one way communication only, so there's no way of telling - just fire the event and hope for the best.

**Comment by JaksonD** [comment]
> you won't really be doing that much compared to how large log files usually get

Apologies, I meant flooding the console (eg. an error happens, someone needs to be able to send me the error)

**Comment by noblereign** [comment]
[kit battle](https://www.roblox.com/games/6549663822/Kit-Battle-Beta-Testing) now supports this :+1:   
i wish i could change both lines like roactivity used to let me do since it's hard to fit a lot within the small area you get in one line  
but other than that it's a nice way to bring back some old functionality :) especially since it doesn't rely on any third party servers unlike roactivity

**Comment by pizzaboxer** [comment]
Awesome :D
I'm not sure if changing the first line would be suitable, since I'd rather keep that reserved for the game name. Thinking about it more, I can open up the option to change the small Roblox icon in the corner.
