### ISSUE TITLE
[BUG] when i open roblox its normally opens and i get an error on loading screen

### ISSUE THREAD

**Issue by Jasiu75879** [pizzaboxer/bloxstrap#1710]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Zrzut ekranu 2024-04-30 115320](https://github.com/pizzaboxer/bloxstrap/assets/168535979/eca48cd4-b4a2-48ef-a21b-7b22806bffea)

**Comment by Jasiu75879** [comment]
> As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Yes it is

**Comment by Jasiu75879** [comment]
> As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I want to play bloxstrap

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
