### ISSUE TITLE
Translator in 2020 menu version [REQ] 

### ISSUE THREAD

**Issue by AfonasGa** [pizzaboxer/bloxstrap#1711]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

2020 escape menu version dont have a translator, please add it

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version

"Keep in mind that Roblox does not maintain any menu versions older than 2023 anymore, so some of the buttons and controls may not work properly. Minor visual or usability problems with them are to be expected."
