### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by PAdur11** [pizzaboxer/bloxstrap#1712]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap overwriting ClientSettings folder on launch causing mods to not save.

**Comment by PAdur11** [comment]
The ClientAppSettings.json has a line of code that states {"FFlagHandleAltEnterFullscreenManually":"False"}. When changing the value from "False" to "True" Bloxstrap automatically changes the value back to "False" even after saving my settings.  I personally have better performance when the value is on "True".

**Comment by pizzaboxer** [comment]
> I personally have better performance when the value is on "True".

You're definitely just seeing things, because configuring this flag has zero impact on performance. I can tell you that for sure.
