### ISSUE TITLE
[BUG] It doesn't show the "Future is Bright" for me.

### ISSUE THREAD

**Issue by nowshadsifat1** [pizzaboxer/bloxstrap#1715]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/113196818/d400577c-7799-47d2-b87d-bc444791b49a)

**Comment by pizzaboxer** [comment]
Future (Phase 3) is what you're looking for.
