### ISSUE TITLE
[BUG] Bloxstrap menu not coming up in Windows even after reinstalling.

### ISSUE THREAD

**Issue by VRonGitHub** [pizzaboxer/bloxstrap#1716]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I reinstalled bloxstrap but the menu still would not come up after setting bloxstrap up.

**Comment by pizzaboxer** [comment]
It should be there. If you browse your list of applications instead of using Windows Search, do you see it?

**Comment by VRonGitHub** [comment]
@pizzaboxer I don't see it in list of apps 
![image](https://github.com/pizzaboxer/bloxstrap/assets/86602584/0ae0a2be-cbb5-4e5c-b8b1-37b500a0a207)

**Comment by VRonGitHub** [comment]
That doesn't take me to the menu.

**Comment by VRonGitHub** [comment]
I have a bad fix for it if I go to apps and press modify it comes up.

**Comment by pizzaboxer** [comment]
> @pizzaboxer I don't see it in list of apps

No, I'm talking about the application list in the start menu.

**Comment by unknownstuffbro** [comment]
bro me too i cant find my menu 😭

**Comment by unknownstuffbro** [comment]
i wanna change some stuff and suddenly its gone
