### ISSUE TITLE
[BUG] crash popup apears after i close roblox window

### ISSUE THREAD

**Issue by KhyDoesntKnowStuffYet** [pizzaboxer/bloxstrap#1717]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

as the title says, i have this error whenever i close the roblox window the roblox crash popup apears right after and i find it annoying. Also a few hours ago I set up the fflags just to be 100% sure it actually works. it may be from somewhere there in the screenshots but i have no idea now.. 

here's the fflags screenshots:
![image](https://github.com/pizzaboxer/bloxstrap/assets/151952382/ad48b4a7-0c14-4837-9c1c-06ff2c19c932)
![image](https://github.com/pizzaboxer/bloxstrap/assets/151952382/0522fb26-40da-490a-8f87-58136226ec69)

OK. after further inspecting i checked the roblox logs aaaaaand i found more info hopefully someone understands it (i edited the shadow density and other stuff while trying to figure out how to fix it btw)
![image](https://github.com/pizzaboxer/bloxstrap/assets/151952382/1da56dd5-3461-4cb3-b7c3-c26f35909e09)

**Comment by pizzaboxer** [comment]
Have you opted to disable the desktop app in the Mods tab?

**Comment by KhyDoesntKnowStuffYet** [comment]
no. let me do it right now and i will answer right after if it still going

**Comment by pizzaboxer** [comment]
Oh wait, the first time I saw this, I didn't see you had opted to use Vulkan. Don't do that. That's very likely causing it. Remove both the Vulkan and Direct3D flags.
