### ISSUE TITLE
[BUG] Bloxstrap doesn't apply to the cursor 

### ISSUE THREAD

**Issue by akihiro7812** [pizzaboxer/bloxstrap#1718]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I was playing Roblox after the update, the cursor became the new cartoony icon instead of the 2016 or 2007 cursor, and even when I applied it, it's still the same cartoony icon as in 2016 and 2006.

**Comment by pizzaboxer** [comment]
See sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter
