### ISSUE TITLE
[BUG] Fastflags wont load

### ISSUE THREAD

**Issue by noobthechezboi** [pizzaboxer/bloxstrap#1719]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was using bloxstrap earlier and one of the fastflags wasnt going away when I tried to remove it from the editor so I unistalled bloxstap and reinstalled it but now none of my fastflags want to load
[Bloxstrap_20240501T072528Z.log](https://github.com/pizzaboxer/bloxstrap/files/15174813/Bloxstrap_20240501T072528Z.log)

**Comment by pizzaboxer** [comment]
> but now none of my fastflags want to load

Did you add them back after reinstalling?

**Comment by noobthechezboi** [comment]
Yes, I did

**Comment by noobthechezboi** [comment]
Did not mean to close it

**Comment by sar1v1** [comment]
im getting the same issue

**Comment by BloxyReimu** [comment]
HMM, BLOX STRAP DOESN'T WORK ANYMORE WHAT.

**Comment by AttakDoge** [comment]
yeah i have to manually add the fastflags, this also includes any other mods such as old cursors

**Comment by pizzaboxer** [comment]
> Yes, I did

What have you configured that's not working? Upload your configuration please (just ClientAppSettings only): https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
