### ISSUE TITLE
Bug fix release?

### ISSUE THREAD

**Issue by thatsprettygood** [pizzaboxer/bloxstrap#172]
With the amount of stuff planned for 2.3.0, it seems it's going to take a while before it's released.
Can you release a bug fix for Direct3D 11 incorrectly being enforced? (2.2.1?)

**Comment by pizzaboxer** [comment]
I'm busy so no can do right now, but here, have an artifact build from the latest 2.3.0 commit:

[Bloxstrap (Release, x64).zip](https://github.com/pizzaboxer/bloxstrap/files/11359755/Bloxstrap.Release.x64.zip)

Just replace your current installed version of Bloxstrap.exe with this.
