### ISSUE TITLE
"System.Exception: Signature does not match!" Error

### ISSUE THREAD

**Issue by progamer31** [pizzaboxer/bloxstrap#1722]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i try to download bloxstrap it gives this error "System.Exception: Signature does not match!"

**Comment by pizzaboxer** [comment]
Read the preliminary instructions. https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
