### ISSUE TITLE
[BUG] With bloxstrap roblox games take ages to load things up and without bloxstrap it loads instantly 

### ISSUE THREAD

**Issue by Semireq** [pizzaboxer/bloxstrap#1723]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

With bloxstrap roblox games take ages to load things up and without bloxstrap it loads instantly.
Please fix the bug

**Comment by pizzaboxer** [comment]
What specifically is taking a long time to load? Assets?

**Comment by moyaimoment** [comment]
My guess is when you click the play button from the Roblox website, the Roblox Client doesn't actually appear for a little long, the Bloxstrap icon appears in the bottom right though, it's just the client itself to launch. It happens to me as well.

**Comment by pizzaboxer** [comment]
> My guess is when you click the play button from the Roblox website, the Roblox Client doesn't actually appear for a little long, the Bloxstrap icon appears in the bottom right though, it's just the client itself to launch. It happens to me as well.

I'm assuming that happens when using the original launcher too?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
