### ISSUE TITLE
[BUG]  When I pressed login to play Roblox I received this message: " System.Exception: Signature does not match! "  what is this ?

### ISSUE THREAD

**Issue by iiiYaagosYTiii** [pizzaboxer/bloxstrap#1724]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The problem I encountered was when I tried to open Roblox and when Blox Strap was installed, this error message appeared: "System.Exception: Signature does not match!"

**Comment by pizzaboxer** [comment]
Read the preliminary instructions. https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
