### ISSUE TITLE
Can you make the MouseLockedCursor a custom one?

### ISSUE THREAD

**Issue by Bvbble** [pizzaboxer/bloxstrap#1725]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im sorry for making my problem about a question. i tried myself and i got the other 3 to work. the shift lock just doesnt change. again, sorry for taking your time. it's not in the folder its outside of it. i tried to put it in and duplicate it, neither worked. its 15x15 dot
![MouseLockedCursor](https://github.com/pizzaboxer/bloxstrap/assets/147776194/ffabaee5-51b0-40c6-ad58-8f2be9c1f7fc)

**Comment by pizzaboxer** [comment]
What folder did you place it in?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
