### ISSUE TITLE
bloxstrap stops loading in the middle of download

### ISSUE THREAD

**Issue by idontknowlmao512** [pizzaboxer/bloxstrap#1726]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so I wanted to play roblox yesterday and bloxstrap tried to update. But when it gets to the middle of the update it just freezes and I cant play roblox

**Comment by pizzaboxer** [comment]
Get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` and send it here please

**Comment by idontknowlmao512** [comment]
it says windows cannot find it

**Comment by idontknowlmao512** [comment]
Ok hey pizzaboxer I finally found it but there are 6 log folders, do I give them all to you?

**Comment by pizzaboxer** [comment]
There's six log folders? Can you show a screenshot of them please?

**Comment by idontknowlmao512** [comment]
Hey sorry I just got home so I wasn't able to see your message but I don't know how to send a screenshot on github, do you possibly have discord?

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/806a8ba0-949b-41e1-b077-edfb256597de)

**Comment by idontknowlmao512** [comment]
oh when I try to do that it just gives a paste a random link and the link brings it to the bloxstrap download thing

**Comment by pizzaboxer** [comment]
What? That's the link to the image. Just upload the image please.

**Comment by idontknowlmao512** [comment]
Alright here you go just let me know if it doesn't work 
![image](https://github.com/pizzaboxer/bloxstrap/assets/168764047/c06028da-62a3-44c1-946f-63d87e487fb7)

**Comment by idontknowlmao512** [comment]
do you think it's an issue with my pc?

**Comment by pizzaboxer** [comment]
Where's the folders? Those are all just files.

Anyway, can you send the latest log file herer please? It's the one at the bottom.

**Comment by idontknowlmao512** [comment]
sorry I didn't mean folders I meant files my bad but here 
[Bloxstrap_20240505T211901Z.log](https://github.com/pizzaboxer/bloxstrap/files/15223305/Bloxstrap_20240505T211901Z.log)

**Comment by pizzaboxer** [comment]
Alright, I see what's happening. An error dialog is supposed to show here but isn't showing, which is a known bug. Sorry about that.

So this appears to happen every time you try to launch Bloxstrap. Does the original launcher work fine? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by idontknowlmao512** [comment]
no sadly the original launcher gets so close to opening then it just closes

**Comment by pizzaboxer** [comment]
> no sadly the original launcher gets so close to opening then it just closes

That's to be expected. You're actually having the same issue as described in this wiki page: https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox

You don't really have much options here other than to try out the Microsoft Store version and see if that works.

**Comment by idontknowlmao512** [comment]
so hey pizzaboxer the original roblox decided to work but when i try to install bloxstrap it doesn't want to download

**Comment by idontknowlmao512** [comment]
yoooooooooo pizzaboxer you were right it fixed itself tysm for letting me know it would fix itself
