### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VibezCity** [pizzaboxer/bloxstrap#1727]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240502T163240Z.log](https://github.com/pizzaboxer/bloxstrap/files/15191301/Bloxstrap_20240502T163240Z.log)

**Comment by pizzaboxer** [comment]
Are you getting this error every single time you launch?

**Comment by VibezCity** [comment]
I was, until I fully restarted my computer and reinstalled bloxstrap

**Comment by VibezCity** [comment]
> Are you getting this error every single time you launch?

My comment ^
Posted

**Comment by pizzaboxer** [comment]
Seems like restarting your computer would've been the only thing you needed to do since this was an issue with Windows somewhere.
