### ISSUE TITLE
[REQ] Please make an option to get the 2016 topbar and playerlist back on in bloxstrap so people who want the old topbar will use the option

### ISSUE THREAD

**Issue by BonziWORLDLOVER** [pizzaboxer/bloxstrap#1728]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Please make an option to get the 2016 topbar and playerlist back on in bloxstrap so people who want the old topbar will use the option

**Comment by pizzaboxer** [comment]
Not possible, sorry.
