### ISSUE TITLE
fast flag stopped working[BUG] 

### ISSUE THREAD

**Issue by NOOBMINE122** [pizzaboxer/bloxstrap#1729]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

some of the fast flags stopped working for no reason (after 3 days of using)

**Comment by pizzaboxer** [comment]
Only some? Which ones specifically?

**Comment by NOOBMINE122** [comment]
mostly fps boost ones,like force delete texture materials
delete grass and others, i cant put all of them since the json its long as hell

**Comment by pizzaboxer** [comment]
> like force delete texture materials

Is it only those ones? Those were recently nullified because of the latest Roblox update, so those don't work anymore. Besides the texture pack flags, what else don't work?

**Comment by NOOBMINE122** [comment]
> > like force delete texture materials
> 
> Is it only those ones? Those were recently nullified because of the latest Roblox update, so those don't work anymore. Besides the texture pack flags, what else don't work?

FFlagEnableV3MenuABTest3": "False",
  "FFlagEnableMenuModernizationABTest2": "False",
  "FFlagEnableMenuModernizationABTest": "False",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableInGameMenuControls": "False",
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableInGameMenuModernization": "False",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FFlagDebugDisableTelemetryPoint": "True",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "FFlagDebugDisableTelemetryV2Stat": "True",
  "FIntTerrainArraySliceSize": "8",
  "FIntFRMMinGrassDistance": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FIntRenderGrassDetailStrands": "0",
  "FintRenderGrassHeightScaler": "0",
  "FLogNetwork": "7",
  "DFIntDebugFRMQualityLevelOverride": "1",
  "FFlagNewLightAttenuation": "True",
  "FFlagDebugGraphicsPreferD3D11FL10": "True",
  "FFlagDisablePostFx": "True",
  "FIntDebugForceMSAASamples": "0",
  "FFlagDebugForceFutureIsBrightPhase2": "True",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFLogHttpTraceLight": "0",
  "FFlagDebugForceFutureIsBrightPhase3": "True",
  "FFlagEnableAccessibilitySettingsAPIV2": "True",
  "DFIntLightstepHTTPTransportHundredthsPercent2": "0",
  "FFlagEnableAccessibilitySettingsEffectsInCoreScripts2": "True",
  "DFStringRobloxAnalyticsURL": "null",
  "FFlagCoreGuiTypeSelfViewPresent": "False",
  "DFIntTextureQualityOverride": "6",
  "FFlagInGameMenuV1FullScreenTitleBar": "False",
  "DFStringCrashUploadToBacktraceBaseUrl": "null",
  "FStringGamesUrlPath": "/games/",
  "DFFlagBaseNetworkMetrics": "False",
  "DFStringTelemetryV2Url": "null",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "GoogleAnalyticsAccountPropertyIDPlayer": "null",
  "FIntCameraMaxZoomDistance": "99999",
  "DFStringAltTelegrafHTTPTransportUrl": "null",
  "FFlagVoiceBetaBadge": "false",
  "FFlagCommitToGraphicsQualityFix": "True",
  "FStringCoreScriptBacktraceErrorUploadToken": "null",
  "DFStringLightstepHTTPTransportUrlPath": "null",
  "DFStringLightstepToken": "null",
  "DFFlagEnableLightstepReporting2": "False",
  "DFStringLightstepHTTPTransportUrlHost": "null",
  "FFlagEnableInGameMenuV3": "False",
  "FFlagAdServiceEnabled": "False",
  "DFStringTelegrafHTTPTransportUrl": "null",
  "FFlagCloudsReflectOnWater": "True",
  "FFlagEnableAccessibilitySettingsInExperienceMenu2": "True",
  "FFlagPreloadAllFonts": "True",
  "DFFlagBrowserTrackerIdTelemetryEnabled": "False",
  "DFStringCrashUploadToBacktraceWindowsPlayerToken": "null",
  "DFStringAltHttpPointsReporterUrl": "null",
  "DFFlagDebugPerfMode": "True",
  "FFlagFastGPULightCulling3": "True",
  "DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent": "0",
  "DFStringHttpPointsReporterUrl": "null",
  "FFlagEnableAccessibilitySettingsEffectsInExperienceChat": "True",
  "GoogleAnalyticsAccountPropertyID": "null",
  "DFStringCrashUploadToBacktraceMacPlayerToken": "null",
  "FFlagLuaAppSystemBar": "False",
  "FFlagDontCreatePingJob": "True",
  "\u0022FIntCameraMaxZoomDistance\u0022: \u002299999\u0022": "99999",
  "DFStringAnalyticsEventStreamUrlEndpoint": "opt-out",
  "FFlagEnableBatteryStateLogger": "False",
  "FStringTerrainMaterialTablePre2022": "",
  "FIntMeshContentProviderForceCacheSize": "268435456",
  "DFIntCrashReportingHundredthsPercentage": "0",
  "FStringPerformanceSendMeasurementAPISubdomain": "opt-out",
  "FIntStartupInfluxHundredthsPercentage": "0",
  "FFlagRenderGpuTextureCompressor": "True",
  "FFlagImmersiveAdsWhitelistDisabled": "False",
  "DFFlagAddUserIdToSessionTracking": "False",
  "\u0022DFIntCSGLevelOfDetailSwitchingDistanceL23\u0022": "0",
  "FIntTerrainOTAMaxTextureSize": "1024",
  "FIntReportDeviceInfoRollout": "0",
  "DFFlagESGamePerfMonitorEnabled": "False",
  "FStringTerrainMaterialTable2022": "",
  "DFIntPredictedOOMPercent": "0",
  "FIntDefaultMeshCacheSizeMB": "256",
  "FIntFontSizePadding": "3",
  
 all of this and alot more

**Comment by pizzaboxer** [comment]
I thought you said it was only some that don't work. Is it some or all of them?

Also, I would recommend that you actually remove all of these first; see https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
