### ISSUE TITLE
Bloxstrap (86 BIT) Not Opening.

### ISSUE THREAD

**Issue by NathanielB198** [pizzaboxer/bloxstrap#173]
Hello! I am Nathaniel B, I am having problems with Bloxstrap. And the problem is, it will not work + even with "Open as administrator"

**Comment by pizzaboxer** [comment]
Can I quickly check what versions of the .NET runtime you have installed?
![image](https://user-images.githubusercontent.com/41478239/235326320-65d3b9a9-f9d1-4ac5-8df6-2270287f9953.png)

**Comment by jigguz** [comment]
Aint you Nathaniel B?

**Comment by NathanielB198** [comment]
![image](https://user-images.githubusercontent.com/132172106/235327988-8ae4e6bb-d3dc-41ad-aab4-561b3913c425.png)

**Comment by NathanielB198** [comment]
This is what the .NET runtime i have

**Comment by NathanielB198** [comment]
> Can I quickly check what versions of the .NET runtime you have installed? ![image](https://user-images.githubusercontent.com/41478239/235326320-65d3b9a9-f9d1-4ac5-8df6-2270287f9953.png)

**Comment by pizzaboxer** [comment]
Does installing with Winget work?

**Comment by NathanielB198** [comment]
Hmm, I'll try that. If it doesn't work I'll give a heads up!

**Comment by NathanielB198** [comment]
Do you know what I'm suppose to do? Kind of confused 
![image](https://user-images.githubusercontent.com/132172106/235349743-14a4089a-c1ee-4349-a34b-62b03722a8cb.png)

**Comment by pizzaboxer** [comment]
You just run `winget install bloxstrap` in the Command Prompt.

**Comment by NathanielB198** [comment]
![image](https://user-images.githubusercontent.com/132172106/235365975-f4a5bafd-c1b0-4f98-bdbe-79d850fdf475.png)
should i say Y or N?

**Comment by pizzaboxer** [comment]
Y

**Comment by NathanielB198** [comment]
Okay

**Comment by NathanielB198** [comment]
![image](https://user-images.githubusercontent.com/132172106/235366166-92ca86f9-5e74-41f2-b35c-73eb03b62b21.png)
This is what it said, and im trying to install 86 bit, not 64.

**Comment by pizzaboxer** [comment]
Can I ask why you're trying to use the 32-bit version and not the 64-bit version? [Install the 64-bit runtime here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer).

**Comment by NathanielB198** [comment]
My bad, I'll download the 64-bit

**Comment by NathanielB198** [comment]
![image](https://user-images.githubusercontent.com/132172106/235366383-9739e8d5-302c-40d2-9e1c-7f61526382ad.png)
Done, should i try installing it again? with winget.

**Comment by pizzaboxer** [comment]
Yes.

**Comment by NathanielB198** [comment]
Alright.

**Comment by NathanielB198** [comment]
![image](https://user-images.githubusercontent.com/132172106/235366573-281f3487-b60b-4e7c-b4f5-9bd31ef31289.png)

**Comment by pizzaboxer** [comment]
Does Bloxstrap launch when you try to open the menu? It's located in the Start menu. If it doesn't, open Event Viewer, go to Windows Logs -> Application, and send any errors related to Bloxstrap.

**Comment by NathanielB198** [comment]
Faulting application name: Bloxstrap.exe, version: 2.2.0.0, time stamp: 0x641cef7e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1555, time stamp: 0x235a45d0
Exception code: 0xe0434352
Fault offset: 0x000000000008fdec
Faulting process ID: 0x0x22BC
Faulting application start time: 0x0x1D97B872F45B5DA
Faulting application path: C:\Users\Natha\AppData\Local\Bloxstrap\Bloxstrap.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: aa6ea0d0-599c-4da3-82a9-20115344e6c1
Faulting package full name: 
Faulting package-relative application ID:

**Comment by NathanielB198** [comment]
Managed to found this.

**Comment by pizzaboxer** [comment]
Is there another one with `.NET Runtime` as the source?

**Comment by NathanielB198** [comment]
Im not sure but, found this. 

Description: A .NET application failed.
Application: Bloxstrap-v2.2.0-x64.exe
Path: C:\Users\Natha\AppData\Local\Temp\WinGet\pizzaboxer.Bloxstrap.2.2.0\Bloxstrap-v2.2.0-x64.exe
Message: A JSON parsing exception occurred in [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\Microsoft.NETCore.App.runtimeconfig.json], offset 0 (line 1, column 1): The document is empty.
Invalid framework config.json [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16\Microsoft.NETCore.App.runtimeconfig.json]

**Comment by pizzaboxer** [comment]
Any other ones? There should be multiple. Check any you can see. One should have a long stack trace.

**Comment by NathanielB198** [comment]
Faulting application name: Bloxstrap.exe, version: 2.2.0.0, time stamp: 0x641cef7e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1555, time stamp: 0x235a45d0
Exception code: 0xe0434352
Fault offset: 0x000000000008fdec
Faulting process ID: 0x0x55CC
Faulting application start time: 0x0x1D97B87271E1398
Faulting application path: C:\Users\Natha\AppData\Local\Bloxstrap\Bloxstrap.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: d477ea5c-277e-44a0-9886-6f5f23d6f66e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pizzaboxer** [comment]
Okay actually, any with Event ID `1026`?

**Comment by NathanielB198** [comment]
hm, ill see.

**Comment by NathanielB198** [comment]
This is what i found. There'll be more too i think.

Application: Bloxstrap.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Wpf.Ui.Interop.Dwmapi.DwmGetColorizationParameters(DWMCOLORIZATIONPARAMS& dwParameters)
   at Wpf.Ui.Interop.UnsafeNativeMethods.GetDwmColor()
   at Wpf.Ui.Appearance.Accent.GetColorizationColor()
   at Wpf.Ui.Appearance.Theme.Apply(ThemeType themeType, BackgroundType backgroundEffect, Boolean updateAccent, Boolean forceBackground)
   at Wpf.Ui.Mvvm.Services.ThemeService.SetTheme(ThemeType themeType)
   at Bloxstrap.Dialogs.FluentDialog..ctor()
   at Bloxstrap.Enums.BootstrapperStyleEx.GetNew(BootstrapperStyle bootstrapperStyle)
   at Bloxstrap.App.GlobalExceptionHandler(Object sender, DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Bloxstrap.App.Main()

**Comment by pizzaboxer** [comment]
Okay cool, looks like you're having the same problem as another guy. Here's a fix I've been meaning to test.

https://pizzaboxer.xyz/files/bloxstrap-debug/170/Bloxstrap.exe

Download it, run it, and let me know if Roblox launches.

**Comment by NathanielB198** [comment]
hmm, k.

**Comment by NathanielB198** [comment]
![image](https://user-images.githubusercontent.com/132172106/235367250-84d59136-bbde-4608-a835-2497c70f08f0.png)
it does

**Comment by pizzaboxer** [comment]
Okay, great, it works. Anyway, replace the Bloxstrap.exe file that's currently located in your installation folder with the one I just gave you. You can find the folder by navigating to `%localappdata%\Bloxstrap` in the file browser.

**Comment by NathanielB198** [comment]
I'm i able to access the bloxstrap menu too btw?

**Comment by NathanielB198** [comment]
nevermind, i can. Thanks for the help! I'll just go tell my other friend

**Comment by pizzaboxer** [comment]
Closing since this is being handled at #170.
