### ISSUE TITLE
[BUG] Bloxtrap aint working

### ISSUE THREAD

**Issue by jonthebuilder12** [pizzaboxer/bloxstrap#1730]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to launch roblox using bloxstrap nothing loads and its just a white screen (sometimes the error has occurred roblox error pops up)

**Comment by pizzaboxer** [comment]
Can you confirm that this only happens when launching from Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
