### ISSUE TITLE
I cant join roblox

### ISSUE THREAD

**Issue by Mynameisslimy** [pizzaboxer/bloxstrap#1731]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Its not letting me open roblox for some reason no matter how much i try.

**Comment by pizzaboxer** [comment]
Do you get an error message or something? Also, does this happen only when launching with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
