### ISSUE TITLE
[BUG]  FPS unlocker isnt working

### ISSUE THREAD

**Issue by tahaardaa** [pizzaboxer/bloxstrap#1734]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I changed my fps value to 9999, but when I enter the game  get 60 fps

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
