### ISSUE TITLE
[BUG] Roblox wont Open

### ISSUE THREAD

**Issue by 3nowe** [pizzaboxer/bloxstrap#1735]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime I try to open roblox it doesnt open but it runs in the backround I dont know what the problem is Pls help

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

If this happens with the stock Roblox launcher too, then read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

**Comment by 3nowe** [comment]
omg i had a preview build upd i didnt even know
Tysm
