### ISSUE TITLE
[BUG] Bloxstrap can't open/crashed

### ISSUE THREAD

**Issue by notrusheplayz** [pizzaboxer/bloxstrap#1736]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i was playing a game called "sol's rng roll test" and i preesed "instant roll" and my roll was "10m". That much rolls was too much that i made my Bloxstrap.

Proof:
![Roblox 03_05_2024 18_01_25](https://github.com/pizzaboxer/bloxstrap/assets/168877628/fc4ec06a-4200-40f4-93a5-3255acc8440d)

**Comment by pizzaboxer** [comment]
So, whenever you open Roblox, you see this?

Does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
