### ISSUE TITLE
[BUG] Bloxstrap will upgrade ROBLOX when pressing play. Even in the same account in the same browser rejoining into the same game.

### ISSUE THREAD

**Issue by NoOneLikesThisName** [pizzaboxer/bloxstrap#1737]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap will upgrade ROBLOX when pressing play. Even in the same account in the same browser rejoining into the same game. My problem **may have been addressed,** or I may have misunderstood whether or not if their problem is the same as mine. That troubleshoot did not work. I've also turned off the option in the Bloxstrap menu.
![image](https://github.com/pizzaboxer/bloxstrap/assets/168899544/d8cb7f0b-9164-49a0-be05-0908839d441b)

**Comment by pizzaboxer** [comment]
Get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs`, either at the top or the bottom, and send it here please.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
