### ISSUE TITLE
FPS UNLOCKER

### ISSUE THREAD

**Issue by monkeysrcool7** [pizzaboxer/bloxstrap#174]
when i download and open the bloxstrap, it doesn't show the fps unlocker for some reason ?? it only shows the discord rich presence, reshade, miscellaneous, and custom integrations ( i have the x64 downloaded )

**Comment by thatsprettygood** [comment]
Please use the left sidebar.

**Comment by monkeysrcool7** [comment]
> Please use the left sidebar. Also note that you must be 13 or older to use an GitHub account.

what left sidebar and i am older than 13?

**Comment by pizzaboxer** [comment]
We're not using rbxfpsunlocker anymore. Check your FPS in-game with Shift + F5 and see if it's being unlocked.

**Comment by monkeysrcool7** [comment]
> We're not using rbxfpsunlocker anymore. It's delegated to a FastFlag in the Mods tab now. Check your FPS in-game with Shift + F5 and see if it's being unlocked.

ty
