### ISSUE TITLE
[BUG] problem with browser

### ISSUE THREAD

**Issue by skaterbater** [pizzaboxer/bloxstrap#1740]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i use the opera browser, but whenever im using roblox and open the game, my opera browser closes. ive tried uninstalling opera and using different browsers but the problem seems to be with bloxstrap. not sure whether its a bug or just a setting but please help its so annoying to always open the browser again.

**Comment by pizzaboxer** [comment]
> but the problem seems to be with bloxstrap

This doesn't happen when you use the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by bazzybetter** [comment]
im having the same problem and no it doesnt happen when i use the normal roblox launcher
