### ISSUE TITLE
[BUG] blox trap not starting

### ISSUE THREAD

**Issue by seawflolik** [pizzaboxer/bloxstrap#1745]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?
blox trap not starting

the screenshot and log
[screnshoot](https://ibb.co/5YHK5D7)
[Bloxstrap_20240504T180341Z.log](https://github.com/pizzaboxer/bloxstrap/files/15210551/Bloxstrap_20240504T180341Z.log)

**Comment by pizzaboxer** [comment]
Known bug, see https://github.com/pizzaboxer/bloxstrap/wiki/Using-multiple-instances-always-forces-a-Roblox-upgrade
