### ISSUE TITLE
[BUG] Failed to open dlllist.txt for reading Error code: 2

### ISSUE THREAD

**Issue by Raazerr** [pizzaboxer/bloxstrap#1746]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try and open Bloxstrap it just tells me "Failed to open dlllist.txt for reading Error code: 2".
![Screenshot 2024-05-04 214347](https://github.com/pizzaboxer/bloxstrap/assets/78375495/2cc83600-2edf-480d-8590-bda2d29949c8)

**Comment by pizzaboxer** [comment]
Something you've installed in the past is causing this. Bloxstrap isn't causing this. I wouldn't know what it is, but you'll need to find out. Chances are it's from a mod for another game.
