### ISSUE TITLE
[BUG] Bloxstrap wont start

### ISSUE THREAD

**Issue by Fb942** [pizzaboxer/bloxstrap#1747]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

https://github.com/pizzaboxer/bloxstrap/assets/95187555/fe708d52-468e-4658-b228-5cfb87cd7484
Whenever I start bloxstrap, it opens and runs normally until it says "starting Roblox" and then it crashes without any error codes. this only happens on bloxstrap.

**Comment by 3nowe** [comment]
bro this happens to me also i havent found a fix

**Comment by coolboyblue** [comment]
Same issue. But I can get bloxstrap to open Roblox on my other accounts, but on one specific account, bloxstrap refuses to open all of a sudden. And it used to open on the account until yesterday.

**Comment by pizzaboxer** [comment]
>  Whenever I start bloxstrap, it opens and runs normally until it says "starting Roblox" and then it crashes without any error codes. this only happens on bloxstrap.

Have you checked to see if Roblox works with the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/=Switching-between-Roblox-and-Bloxstrap

**Comment by havin230** [comment]
same issue i cant opened the bloxtrap and my original roblox

**Comment by pizzaboxer** [comment]
@havin230 See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

@Fb942 
> this only happens on bloxstrap.

Didn't see that, sorry. Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Fb942** [comment]
closing it cuz bloxstrap is working now. I'm guessing that you just have to wait
