### ISSUE TITLE
roblox wont even let me play the game for some reason

### ISSUE THREAD

**Issue by theREALREALloser** [pizzaboxer/bloxstrap#175]
i was just playing a game but then the game just crashed on me without any error messages at all.
this also happpens other games if you have bloxstrap

**Comment by thedavesorh** [comment]
while loading btw

**Comment by thedavesorh** [comment]
i found a way on to stop crashing:
make the launcher and robloxplayerbeta run in admin mode

**Comment by thedavesorh** [comment]
nevermind it didnt fix the issue.

**Comment by pizzaboxer** [comment]
Are you sure that's a Bloxstrap issue? That's sounding like a Hyperion issue to me. Uninstall Bloxstrap and see if it's still happening.

**Comment by theREALREALloser** [comment]
no its like robloxs issue i Have no idea why so i dont know how to fix this.

**Comment by pizzaboxer** [comment]
Install Bloxstrap again, but set your channel in the installation tab to LIVE, and enable "prompt on automatic channel change" in the Behaviour tab. You'll have to click no whenever the prompt to switch channels comes up though.

**Comment by theREALREALloser** [comment]
its actullay fixed months later thanks
