### ISSUE TITLE
[BUG] i cant set any mods/fastflags in bloxstrap

### ISSUE THREAD

**Issue by Umut424** [pizzaboxer/bloxstrap#1750]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

https://github.com/pizzaboxer/bloxstrap/assets/136654432/7bd99b88-70c7-4d3e-b3dc-4fb5ca38ecd4

i set a bunch of fastflag/mod but its not applying pls help me

**Comment by pizzaboxer** [comment]
Strange, can I see Bloxstrap's latest log file please? Get it from `%localappdata%\Bloxstrap\Logs`, find the latest file at either the top or the bottom, and send it here please.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
