### ISSUE TITLE
[BUG] RPC not working.

### ISSUE THREAD

**Issue by Viccronusx** [pizzaboxer/bloxstrap#1752]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

With BloxStrap running, I'm playing QSERF trying to see the RPC. It's not showing up, I have tried reinstalling Roblox and BloxStrap. I don't know what to do.

**Comment by pizzaboxer** [comment]
- Are you sure that your activity privacy settings in Discord are correct?
- Are you able to see server location info in Bloxstrap? (Right-click on the notification area icon in the bottom-right)
- If you're using Vencord, can you ensure you don't have the NoRPC plugin enabled?
- Are you seeing a UAC prompt whenever you launch Discord? If so, then you need to reinstall Discord **without** administrator perms.

**Comment by Viccronusx** [comment]
All of this stuff is set to the correct settings. I am not seeing the UAC prompt. And I don't have vencord. Yes, I can see the server location.

**Comment by pizzaboxer** [comment]
Get Bloxstrap's latest log file from the `%localappdata%\Bloxstrap\Logs` folder and upload it here please. It'll be at etiher the top or the bottom.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
