### ISSUE TITLE
[REQ] Display channel names on bootstrapper dialogs

### ISSUE THREAD

**Issue by bluepilledgreat** [pizzaboxer/bloxstrap#1753]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

freaky

**Comment by d44df016fe28bc8d5974** [comment]
😮

**Comment by d44df016fe28bc8d5974** [comment]
is this going to be a ohhey only feature
you would have to enable it for it to display

**Comment by pizzaboxer** [comment]
i mean you can just like see it in the desktop app

**Comment by bluepilledgreat** [comment]
> i mean you can just like see it in the desktop app

ok but i'd prefer it to be on the bootstrapper dialog

**Comment by pizzaboxer** [comment]
but why
