### ISSUE TITLE
Keyboard layout changed after installing bloxstrap [BUG] 

### ISSUE THREAD

**Issue by Chmuren** [pizzaboxer/bloxstrap#1756]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After I installed Bloxstrap my layout in game changed from QWERTY to QWERTZ. It is set to a QWERTY layout in windows settings and everything works fine in other games.

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Chmuren** [comment]
Issue fixed on its own. Maybe restarting the pc helped. Not sure.
