### ISSUE TITLE
[BUG] Corechip SR9900 Driver Incompatible

### ISSUE THREAD

**Issue by SrHyenito** [pizzaboxer/bloxstrap#1758]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello, I'm sorry if I have any errors in the writing, my problem, I have a USB Ethernet Adapter because my Ethernet input broke down, when I open the game it shows me a compatibility error with the Corechip SR9900 adapter driver, I don't even have idea why :( I have to play without the Ethernet cable or the game crashes .

**Comment by pizzaboxer** [comment]
>  I don't even have idea why :(

GIven it's one of those cheap sketchy adapters, that's honestly not much of a surprise. You'll either need to just not use it, or get a new adapter that's actually good. Get one from Amazon that's actually USB 3.
