### ISSUE TITLE
fps unlocker capped at 73??[BUG] 

### ISSUE THREAD

**Issue by Morphos1** [pizzaboxer/bloxstrap#1759]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my fps unlocker is capped at 73, even when i try to lower it to 60 or make it smth like 240 its just stuck at 73

**Comment by pizzaboxer** [comment]
Are you playing Flood Escape 2?

**Comment by pizzaboxer** [comment]
Flood Escape 2 caps it to 73 intentionally.
