### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xzerlq** [pizzaboxer/bloxstrap#1760]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

in the blox starp menu if i change the settings it will change but if i close roblox out and repon it changes it?!?!?!

**Comment by Vlad55432** [comment]
uhhhh
what

**Comment by pizzaboxer** [comment]
> but if i close roblox out and repon it changes it

What settings does it change it to? The same as before you changed it?

**Comment by xzerlq** [comment]
no is changes too some random ones or default ones !!!

**Comment by pizzaboxer** [comment]
Just to better illustrate, are you able to show a video of this happening?

**Comment by xzerlq** [comment]
sure!!

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
