### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: refused visit

### ISSUE THREAD

**Issue by Blocwn** [pizzaboxer/bloxstrap#1761]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It just said System.ComponentModel.Win32Exception: refused visit. whenever i launch or reinstall.. and 
![image](https://github.com/pizzaboxer/bloxstrap/assets/169152275/23a92e39-78f7-4f42-ad07-404541a04bea)

**Comment by pizzaboxer** [comment]
Already answered on Discord: https://discord.com/channels/1099468797410283540/1237352734014046259
