### ISSUE TITLE
[BUG] apps window doesnt stacks

### ISSUE THREAD

**Issue by TheMix00** [pizzaboxer/bloxstrap#1762]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

just 1 account doesnt stack all others will stacks but 1 acc its just not
![resim_2024-05-07_144328454](https://github.com/pizzaboxer/bloxstrap/assets/168909495/2e853902-8d99-409e-b907-647ff3f872a4)

**Comment by pizzaboxer** [comment]
> just 1 account doesnt stack all others will stacks but 1 acc its just not

You're launching them all the same way, right?

**Comment by TheMix00** [comment]
yea same way i tried many account and some accounst use diffirent files in bloxstrap idk why this is happening

**Comment by pizzaboxer** [comment]
Neither do I. I can't seem to replicate this, and either way it's out of my control. Sorry.

**Comment by TheMix00** [comment]
np i fixed it just closed my rdp and done 
if u care 👍
