### ISSUE TITLE
[BUG] An Exception Occurred While running Bloxstrap! | Help

### ISSUE THREAD

**Issue by UltraUniv** [pizzaboxer/bloxstrap#1763]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Greetings! 

Im using bloxstrap for a couple of days now, it worked perfectly fine earlier, before i got met with this when i was trying to launch a game off roblox.

the error said | An Exception Occurred While running Bloxstrap.

The log also mention this | The requested operation requires elevation.

i don't know if this problem also occurred to other users but i did reinstall Bloxstrap Clean, but this still pops up when im trying to launch a game :(.

Heres a Provided Screenshot
![Screenshot 2024-05-07 224423xxoxox](https://github.com/pizzaboxer/bloxstrap/assets/102730617/b9a3c771-19c0-4a7c-ade2-21923c47a361)

**Comment by pizzaboxer** [comment]
> but i did reinstall Bloxstrap Clean

You didn't reinstall it as Administrator, did you?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
