### ISSUE TITLE
[QUESTION] graphics level not being immediate

### ISSUE THREAD

**Issue by ABB0527** [pizzaboxer/bloxstrap#1765]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've downloaded bloxstrap and it's amazing, however, when i change my graphics level it doesn't change until i join a new place or experience, is there any way to make it instant?

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by wxlvis** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/69386070/55f4c8c1-dac1-4437-8d08-bf76feebb874)
Having this issue too, graphics load extremely slow on my high end pc, icons are blurred and low quality as well as clothes. Models take incredibly longer than default roblox to load.

**Settings**
{
  "BootstrapperStyle": 4,
  "BootstrapperIcon": 8,
  "BootstrapperTitle": "removed",
  "BootstrapperIconCustomLocation": "removed",
  "Theme": 0,
  "CheckForUpdates": true,
  "CreateDesktopIcon": false,
  "MultiInstanceLaunching": true,
  "OhHeyYouFoundMe": false,
  "Channel": "LIVE",
  "ChannelChangeMode": 0,
  "EnableActivityTracking": true,
  "UseDiscordRichPresence": false,
  "HideRPCButtons": true,
  "ShowServerDetails": false,
  "CustomIntegrations": [],
  "UseOldDeathSound": true,
  "UseOldCharacterSounds": false,
  "UseDisableAppPatch": false,
  "UseOldAvatarBackground": false,
  "CursorType": 0,
  "EmojiType": 0,
  "DisableFullscreenOptimizations": false
}

**State**
{
  "LastEnrolledChannel": "LIVE",
  "VersionGuid": "version-7d64f40489634ca5",
  "ModManifest": [
    "ClientSettings\\ClientAppSettings.json",
    "content\\sounds\\ouch.ogg"
  ]
}

**Modifications > ClientAppSettings**
{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "DFIntTaskSchedulerTargetFps": "9999",
  "FFlagDebugForceFutureIsBrightPhase3": "True"
}

**Comment by ABB0527** [comment]
UPDATE: it doesn't even update anymore, now it's just stuck at 1 graphics

**Comment by pizzaboxer** [comment]
> UPDATE: it doesn't even update anymore, now it's just stuck at 1 graphics

Delete your entire flag list and see if the same issue still occurs.

**Comment by ABB0527** [comment]
Yeah that worked, i just saw bloxstrap through a youtube video and thought it looked pretty cool so i pasted the flags from the description to reduce lag. thanks for the help and sorry for the inconvenience.

**Comment by pizzaboxer** [comment]
>  i pasted the flags from the description to reduce lag.

Don't do that. The notice we tell you to read before you download Bloxstrap specifically tells you to not do that.
