### ISSUE TITLE
[BUG] Help me :(

### ISSUE THREAD

**Issue by ismael37343** [pizzaboxer/bloxstrap#1767]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Captura de pantalla 2024-05-07 162356](https://github.com/pizzaboxer/bloxstrap/assets/157171460/46141a49-cbc6-42db-9b30-c81e3b3753b4)
Help me!!!!:(

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
