### ISSUE TITLE
[BUG] what is this and how can i solve it

### ISSUE THREAD

**Issue by 123igotmyeyesonyou** [pizzaboxer/bloxstrap#1769]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image_2024-05-07_210742244](https://github.com/pizzaboxer/bloxstrap/assets/163061361/ca9772b0-d8ee-4293-b07b-706f2c9ea9af)
 what is this?

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
