### ISSUE TITLE
help whenever i run bloxstrap, i get an error named: "an exception occured while running bloxstrap"

### ISSUE THREAD

**Issue by computerplays69** [pizzaboxer/bloxstrap#1770]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (Checksum of RobloxPlayerBeta.exe post-extraction did not match manifest

This is very likely just an off-chance error. Please report this first, and then start Bloxstrap again.)

[Inner Exception]
Bloxstrap.Exceptions.AssertionException: Checksum of RobloxPlayerBeta.exe post-extraction did not match manifest

This is very likely just an off-chance error. Please report this first, and then start Bloxstrap again.
![Screenshot (205)](https://github.com/pizzaboxer/bloxstrap/assets/117497685/d0de8f3c-b964-4342-b211-ad0b997d0aa0)

**Comment by pizzaboxer** [comment]
Send the log file please

**Comment by KayIaS** [comment]
im having the same issue

**Comment by pizzaboxer** [comment]
Yes, can you send the log file you get please?

**Comment by KayIaS** [comment]
> Yes, can you send the log file you get please?

sorry for my late reply, it randomly decided to work but ill see if i can grab the file
[Bloxstrap_20240508T173449Z.log](https://github.com/pizzaboxer/bloxstrap/files/15260932/Bloxstrap_20240508T173449Z.log)
i think it's this one

**Comment by pizzaboxer** [comment]
That's not the correct log file, but it's fine, doesn't matter.

I'm assuming this issue has been fixed for OP too since it seems to be for other people who had the same issue too.
