### ISSUE TITLE
[BUG] blob:https://translate.google.com/dd487478-0835-46ed-9f8a-4c0132266593

### ISSUE THREAD

**Issue by ZhiMeow1120** [pizzaboxer/bloxstrap#1772]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[**Bloxstrap Exception**]
![dd487478-0835-46ed-9f8a-4c0132266593](https://github.com/pizzaboxer/bloxstrap/assets/169265196/43c61259-b253-4f2d-b9b8-e9669db561fb)

**Comment by pizzaboxer** [comment]
Assuming to be fixed now
