### ISSUE TITLE
[BUG] Bloxstrap fails to launch roblox, no clear error warning.

### ISSUE THREAD

**Issue by limbuscompanyy** [pizzaboxer/bloxstrap#1773]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap can't actually *run* Roblox. Whenever I try to join a game through Bloxstrap, the standard "An unexpected error has occurred and Roblox needs to quit. We're sorry!" window pops up. Joining through the normal bootstrapper works completely fine.

All mods I have on are soft r6 lighting, 2014 visuals pack and a different death sound.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by limbuscompanyy** [comment]
> Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/15259040/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/15259041/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/15259044/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
Can you try removing everything you have in your mods folder? Move them somewhere else and try and launch again.

**Comment by limbuscompanyy** [comment]
Trying this right now, everything works perfectly.
