### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Vemedf** [pizzaboxer/bloxstrap#1774]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

why I can't open more tap it's can ues just 2 tap sir
![Screenshot 2024-05-09 010633](https://github.com/pizzaboxer/bloxstrap/assets/169297266/a53fac99-e69b-48d2-b5da-2d738de24f17)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22TwemojiMozilla.ttf-being-used-by-another-process%22-error-when-launching-Roblox
