### ISSUE TITLE
Every time I open up Roblox it doesn't open [BUG] 

### ISSUE THREAD

**Issue by Cosmoswuztaken** [pizzaboxer/bloxstrap#1775]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Every time I click the Play Roblox it doesn't open and when I do it again it creates two instances of blox strap 

https://github.com/pizzaboxer/bloxstrap/assets/128423750/949b8e1a-db5f-4b5f-97e5-4947d84b9f58

**Comment by Cosmoswuztaken** [comment]
And when I try reinstalling it it does the same thing

**Comment by pizzaboxer** [comment]
As the preliminary instructions asked, does this happen only when you use Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Cosmoswuztaken** [comment]
It just recently started doing this

**Comment by Cosmoswuztaken** [comment]
fix it I just have to reinstall Windows

**Comment by Cosmoswuztaken** [comment]
I've fixed it I just had to reinstall Windows 11
