### ISSUE TITLE
[BUG] Bloxstrap dosen't work.

### ISSUE THREAD

**Issue by coolboyblue** [pizzaboxer/bloxstrap#1776]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to launch as game with bloxstrap as the bootstrapper, It says "starting roblox" and closes. Task Manager says it's running but i don't see anything else. this also happens with the main roblox player too. No matter what roblox account I use, bloxstrap refuses to start the game. I also don't get an error what so ever.

**Comment by ezsyu** [comment]
the same is happening to me.

**Comment by coolboyblue** [comment]
I'm pretty sure it's happening to alot of people if not everyone. super random issue.

**Comment by vidisep** [comment]
have you tried using the normal roblox launcher? Mine doesnt work for some reason

**Comment by Rikukaminari** [comment]
Same here, mine doesn't work either. It working yesterday why doesn't it not work anymore.

**Comment by coolboyblue** [comment]
> have you tried using the normal roblox launcher? Mine doesnt work for some reason

In the original post i said "this also happens with the main roblox player too" so yes, it happens for both bloxstrap and regular roblox player.

**Comment by vidisep** [comment]
Ah i see, well now i can use bloxstrap normally, maybe yours is fixed now

**Comment by coolboyblue** [comment]
> Ah i see, well now i can use bloxstrap normally, maybe yours is fixed now

nope, still refuses to work for me. Glad yours is working though.

**Comment by Necspt** [comment]
Still same for me it doesnt work

**Comment by pizzaboxer** [comment]
> this also happens with the main roblox player too

So then it's not a Bloxstrap issue. I'll close this because it's not relevant to Bloxstrap.

All I can do is advise you to read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch if you haven't yet.

**Comment by pizzaboxer** [comment]
Well, before I do that, how about you three @ezsyu @Necspt @Rikukaminari? Does it happen only using Bloxstrap? Have you read the wiki page linked above?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
