### ISSUE TITLE
[Question more than a bug] Cannot find a way to enable the chatbox at all times

### ISSUE THREAD

**Issue by HiGuysItsMeSussyBaka** [pizzaboxer/bloxstrap#1777]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've read through the FastFlags guide list, yet I cannot find anything on enabling the chatbox or bubble chat. Do you know which FastFlag I can use for this?

**Comment by pizzaboxer** [comment]
The chatbox and bubble chat being enabled depends entirely on the game. Is your issue that they don't appear in any game that you play?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
