### ISSUE TITLE
[BUG] BLOXSTRAP NOT INSTALLING PROPERLY

### ISSUE THREAD

**Issue by CombiningPlays** [pizzaboxer/bloxstrap#1778]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it does not install properly it does not gimme the settings it just straight up opens roblox and it also doesn't appear on desktop

**Comment by pizzaboxer** [comment]
It seems more like that you didn't uninstall it properly. How did you uninstall it? Also, have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu?

**Comment by CombiningPlays** [comment]
oh yeah i got another error too some code wont work

**Comment by pizzaboxer** [comment]
What's the error?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
