### ISSUE TITLE
[enhancement] Add support for custom FFlags

### ISSUE THREAD

**Issue by catb0x** [pizzaboxer/bloxstrap#178]
Kinda related to #125

I use RCO and I don't want Bloxstrap to mess the FFlags up, or conflicts to happen.
I would like for y'all to just add a toggle for the FFlags Bloxstrap adds/changes, straight up implement RCO FFlags or anything like that.

**Comment by NikSavchenk0** [comment]
check #142

**Comment by pizzaboxer** [comment]
You can import RCO's flag list into Bloxstrap by copying over the ClientAppSettings.json file into Bloxstrap's mods folder, inside the ClientSettings folder.
