### ISSUE TITLE
when i open bloxstrap its just a white screen BUG] 

### ISSUE THREAD

**Issue by yaya2humpy** [pizzaboxer/bloxstrap#1780]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I restarted my PC deleted it reinstalled it and everything I looked at multiple [le videos on YouTube and nothing is working but when I use the Roblox website it opens but it freezes and closes after loading in the game loading screen I need help please I'd appreciate it.

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Lourizyy** [comment]
im getting the same issue right now and im only using bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by ninjanadir22** [comment]
i have a similar issue where after installing bloxstrap or any fork like void strap or fish strap roblox is just a white screen even if i use the normal launcher the blox strap menu opens up fine but roblox is just a white screen after uninstalling blox strap or the forks it started to work bloxstraps basically the only way to make the game's playable for me

**Comment by ninjanadir22** [comment]
i had to do the most stupid things download forks download it again now it is finnally working i wish i could have gotten advice as it was painful to make it work
