### ISSUE TITLE
[BUG] Cant launching roblox menu.have reinstaling 3x times but dint work

### ISSUE THREAD

**Issue by havin230** [pizzaboxer/bloxstrap#1781]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so this happened when i want to open bloxtrap at 07:23 am,when i am entering the bloxtrap is not getting laucnhing the menu , so i decide to open normal roblox but it same cant open or launch it ,and i am checking the task mannager, the roblox client still work in background but cant launching in my laptop , yesterday its working like around 00.23 P,M , and  about like 1 month using bloxtrap and happened on this day,so i decide to change my personal ssd to my old ssd , and its the bloxtrap working on my old ssd ,now iam still on my old ssd ,please can dev fix it ?

https://github.com/pizzaboxer/bloxstrap/assets/169334857/a3a7b62b-ea45-4ed6-8871-e32cd4976661

Uploading 2024-05-09 13-17-53.mp4…

**Comment by havin230** [comment]
can you fix it?,because i had new ssd for this laptop i dont want to buy again its to expensive,ok i had 4x arrive to repair my laptop to fix it this issue the technician didn't know what was damaged in the file,btw i had to uninstaling my aseeto corsa and my big files because i thought my bloxtrap cant opened because that




Uploading 2024-05-09 13-24-09.mp4…

**Comment by FlorianFyzz** [comment]
same bro this is very annoying

**Comment by roxxie-bite** [comment]
Bro try disabling RTSS, I disabled it and it worked for me

**Comment by AVABUK11** [comment]
> Bro try disabling RTSS, I disabled it and it worked for me

Dude it happened to me too you need it to not hook to RBLX and monitor it and maybe disable it
and somehow bloxstrap in the process is stuck in my right bottom lol

**Comment by havin230** [comment]
> Bro try disabling RTSS, I disabled it and it worked for me

LMAOOOO ITS WORKED

**Comment by pizzaboxer** [comment]
> LMAOOOO ITS WORKED

Read the preliminary instructions next time.
