### ISSUE TITLE
[BUG] I downloaded and set up bloxstrap, but i didn't have the bloxstrap menu in my desktop.

### ISSUE THREAD

**Issue by nnklvv12** [pizzaboxer/bloxstrap#1782]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I set up the app, but i didn't have the bloxstrap menu on my desktop. I tried reinstalling and everything but it still wasn't there. Please help me with it if you can!

**Comment by zackybooo** [comment]
i not can install

**Comment by pizzaboxer** [comment]
> I set up the app, but i didn't have the bloxstrap menu on my desktop. I tried reinstalling and everything but it still wasn't there.

It's not on the desktop. We don't state anywhere that it is. It's located in your application list only, which you should be able to find by searching for it. You would've been told about this whenever you installed too.

https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
