### ISSUE TITLE
[BUG] Roblox not opening.

### ISSUE THREAD

**Issue by 9u3** [pizzaboxer/bloxstrap#1787]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have tried removing my fastflags and switching to the default roblox launcher and roblox is still not launching properly.
![image](https://github.com/pizzaboxer/bloxstrap/assets/48463140/93574ba6-8d44-41c8-befd-cc7ceab5d60f)
It is only in the background, I even tried reinstalling and that did not work. Restarting windows did not work either

**Comment by Turker9002** [comment]
If you mean that Roblox official launcher isn't working either then its not the bloxtrap devs problem.

**Comment by Turker9002** [comment]
If you use MSI Afterburner or RTSS disable them then restart your device, this is a possible solution.

**Comment by 9u3** [comment]
> If you use MSI Afterburner or RTSS disable them then restart your device, this is a possible solution.

RTSS is disabled in its own UI, same with MSI. I'm on stock settings. but ill try again

**Comment by SoftwareType** [comment]
What do you use Raser Synapse for

**Comment by pizzaboxer** [comment]
Only interested if your issue is related to Bloxstrap.
