### ISSUE TITLE
[BUG]  GAME NOT OPENING

### ISSUE THREAD

**Issue by Mndherozx** [pizzaboxer/bloxstrap#1788]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i open bloxstrap and i go into an game it doesnt open

**Comment by Turker9002** [comment]
Hey I may have found a solution from reading past issues that were solved, do you use MSI Afterburner or RTSS?

**Comment by SoftwareType** [comment]
MacType also have this

It's probably because of the anticheat engine, which prevents to join whether an injection is detected (can be just like what Turker says, MSIA and RTSS)

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
