### ISSUE TITLE
[BUG] QWERTY KEYBOARD ISSUE

### ISSUE THREAD

**Issue by toucanlc** [pizzaboxer/bloxstrap#1790]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my keyboard language is always in azerty, but when i join a roblox game it switch to qwerty, even if i press Win+Space, it will switch back to qwerty when i rejoin, so i think its a Fflag issue, i just need to know what the fix for it... 
Thanks.

**Comment by SoftwareType** [comment]
Interestingly enough, the same thing used to happen to me in ROBLOX, but all way back in 2016

But what you can probably do is to check whether there is something in the Studio settings causing it

**Comment by vnill4** [comment]
maybe stfu if u dont have a proper answer & dont waste time

**Comment by pizzaboxer** [comment]
> so i think its a Fflag issue

It isn't, they don't do this.
