### ISSUE TITLE
help

### ISSUE THREAD

**Issue by CsMan123** [pizzaboxer/bloxstrap#1791]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i set in bloxstarp menu that i want old avatar backround and for some reason every time i will open play roblox it will open in browser and i dont have the avatar backround  so how can i fix it

**Comment by SoftwareType** [comment]
It's for the app version, so you gotta have to verify if you haven't disabled anything related to it

**Comment by pizzaboxer** [comment]
> every time i will open play roblox it will open in browser 

You've opted to disable the desktop app. Re-enable it to use the desktop app. The option for it is right below the option to use the old avatar background.
