### ISSUE TITLE
[BUG] An Exception occured  while running Bloxstrap: System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by traxrarri** [pizzaboxer/bloxstrap#1792]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whilst it said upgrading because roblox has been updated it said:  System.Exception: Signature does not match!

**Comment by traxrarri** [comment]
![image_2024-05-11_025641182](https://github.com/pizzaboxer/bloxstrap/assets/164568042/c5689984-2bbc-47c8-8afc-90789bb4a25a)

**Comment by traxrarri** [comment]
[Bloxstrap_20240511T015255Z.log](https://github.com/pizzaboxer/bloxstrap/files/15281280/Bloxstrap_20240511T015255Z.log)

This is the log file

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox

**Comment by traxrarri** [comment]
Do i just reinstall bloxstrap after couple of days?
