### ISSUE TITLE
[BUG] Bloxstrap Wont Launch

### ISSUE THREAD

**Issue by NDZ3018** [pizzaboxer/bloxstrap#1793]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So I Was Trying To Play Roblox Via Bloxstrap Then After It Says Starting Roblox it Asks Me To Install it
and I Reinstall it and Try it Again and it still Wont Work
OS Windows 11

and it says Roblox Crashed Try Performing a Windows Clean Boot
![image](https://github.com/pizzaboxer/bloxstrap/assets/64868172/46e80298-3ced-419a-9aa8-b6745d352a79)

**Comment by Scripted-Dev** [comment]
This is happening for me too. Just use the Microsoft Store Version until it’s fixed.

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by NDZ3018** [comment]
yes i tried reinstalling and uninstalling it but still wont work

**Comment by pizzaboxer** [comment]
> yes i tried reinstalling and uninstalling it but still wont work

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by NDZ3018** [comment]
Got it Working I Deleted The Folder and Got it Working Again

**Comment by randomstuff69** [comment]
> Got it Working I Deleted The Folder and Got it Working Again

what folder

**Comment by NDZ3018** [comment]
was caused when Windowblinds wasnt launching when a theme was applied lucky i found a setting for not to patch when to launch
