### ISSUE TITLE
CAN'T FIND IN SEARCH BAR

### ISSUE THREAD

**Issue by Kyorsters** [pizzaboxer/bloxstrap#1794]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

whenever I tried searching for it, It wont show. how do i fix this? (using windows 10 pro) 
![image_2024-05-11_144142085](https://github.com/pizzaboxer/bloxstrap/assets/169517991/88791719-5719-4855-89f9-03f4d028ceff)

**Comment by jamesgarry1** [comment]
did you ran the exe and pressed download

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
