### ISSUE TITLE
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:9666)  [Inner Exception] System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Hinglory** [pizzaboxer/bloxstrap#1795]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:9666)

[Inner Exception]
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.

it says it can't connect to the internet

**Comment by pizzaboxer** [comment]
You have a proxy configured in Windows. Go to Control Panel -> Internet Options -> Connections -> LAN Settings and disable the use of a proxy server.
