### ISSUE TITLE
[BUG] texture

### ISSUE THREAD

**Issue by Fronger0800** [pizzaboxer/bloxstrap#1797]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I wanted to put black textures to boost FPS and make it more pleasant to the eyes, but that's the problem, they just don't work for me, the textures are just used those that are used in a regular roblox, and not those that I put, please help me

**Comment by jamesgarry1** [comment]
thats the thing. msfactor5 ff has been removed so you cant change the textures now

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#old-material-textures
