### ISSUE TITLE
[BUG] An exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by KubaKuba1411** [pizzaboxer/bloxstrap#1798]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[
[Bloxstrap_20240511T125853Z.log](https://github.com/pizzaboxer/bloxstrap/files/15282921/Bloxstrap_20240511T125853Z.log)
](url)

**Comment by pizzaboxer** [comment]
Are you sure this is the correct log file?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
