### ISSUE TITLE
[BUG] An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Gopanpun** [pizzaboxer/bloxstrap#1799]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Uploading image[1].png…]()

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
