### ISSUE TITLE
Eror can launch bloxstrap

### ISSUE THREAD

**Issue by Dkzgaming** [pizzaboxer/bloxstrap#1800]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i dont can launch bloxstrap. how to handle it 

_**System.UnauthorizedAccessException: Access to the path 'C:\Users\Administrator\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.**_

**Comment by WaviestBalloon** [comment]
Did you run the installer as an Administrator? I'm guessing that is what happened, try reinstalling Bloxstrap without administrative permissions.

**Comment by pizzaboxer** [comment]
Read the Wiki next time. https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
