### ISSUE TITLE
[BUG] High Ping issues

### ISSUE THREAD

**Issue by xignotlz** [pizzaboxer/bloxstrap#1801]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Recently I have been having problems with very high ping with Bloxstrap installed.

My ping simply jumps to a thousand or even thirty thousand ping in many cases. I've read some bug reports involving this same problem, but nothing has been resolved and I also don't use FPS unlocker, always set to default (0).

**Comment by Vendetta-S** [comment]
I agree with this one, for some ungodly reason I have been getting the high pings as well as getting kicked for my client being modified or something I forgot
But I don't this is only bloxtrap though, when using literally the normal version, I still get the same issue... Sadly, all you can do is just wait until it works fine again

**Comment by Vlad55432** [comment]
> I also don't use FPS unlocker

damn, that's 100% roblox issue then.

**Comment by jamesgarry1** [comment]
thats just a roblox issue

**Comment by pizzaboxer** [comment]
> Recently I have been having problems with very high ping with Bloxstrap installed.

Does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by xignotlz** [comment]
Yes, as i said before, bloxstrap just worsens the ping and sometimes it keeps disconnecting me.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by xignotlz** [comment]
[Settings.json](https://github.com/pizzaboxer/bloxstrap/files/15287466/Settings.json)
[State.json](https://github.com/pizzaboxer/bloxstrap/files/15287467/State.json)
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/15287469/ClientAppSettings.json)

Here.

**Comment by pizzaboxer** [comment]
Can you see if removing the D3D10 related flags and the shadow intensity flag changes anything?

**Comment by xignotlz** [comment]
No, actually these flags are just to improve my FPS.

**Comment by pizzaboxer** [comment]
Open Roblox's version folder at `%localappdata%\Bloxstrap\Versions`, delete the `ClientAppSettings` folder and then launch RobloxPlayerBeta directly. Does the same issue occur?

**Comment by xignotlz** [comment]
Hey, I think I fixed the high ping issue, it was just my PC wifi card driver that I forgot to update, even if that didn't really fixed the issue, it's fine, atleast for now.

**Comment by xignotlz** [comment]
.
