### ISSUE TITLE
[BUG] Can't download bloxstrap

### ISSUE THREAD

**Issue by Dioda6** [pizzaboxer/bloxstrap#1802]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try to open the Bloxstrap-v2.5.4.exe file all that pops up is a white screen

**Comment by pizzaboxer** [comment]
Can you ensure that you have the latest version of the .NET runtime installed? https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.29-windows-x64-installer?cid=getdotnetcore

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
