### ISSUE TITLE
[BUG] .NET error when launching, I have the latest .NET version.

### ISSUE THREAD

**Issue by TheDoctor1977** [pizzaboxer/bloxstrap#1803]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I am receiving this error when I try to launch Bloxstrap.
![image](https://github.com/pizzaboxer/bloxstrap/assets/108845723/a2b0e393-2096-45f5-afb7-53f93061636a)
I pressed "Yes" and ran the installer found on the page, but the error still occurs.

**Comment by pizzaboxer** [comment]
It's telling you to download the wrong version, download this one: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.29-windows-x64-installer?cid=getdotnetcore
