### ISSUE TITLE
[SOLVED] How do i open the bloxstrap menu? Its downloaded already.

### ISSUE THREAD

**Issue by Formidables** [pizzaboxer/bloxstrap#1804]
When i press it in files it just opens a roblox instance. I don't know how to reopen the menu. I tried to redownload it, but it just goes back to a roblox instance. How can I fix this?

**Comment by SoftwareType** [comment]
When searching for "Bloxstrap" in the search bar, does "Bloxstrap Settings" (or similar) appears to you?

**Comment by Formidables** [comment]
> When searching for "Bloxstrap" in the search bar, does "Bloxstrap Settings" (or similar) appears to you?

yeah, it showed up as 'Bloxstrap Menu'. Thank you!
