### ISSUE TITLE
is this available for mac

### ISSUE THREAD

**Issue by mickymatthews** [pizzaboxer/bloxstrap#1805]
can i get this on a macbook air?

**Comment by WaviestBalloon** [comment]
> can i get this on a macbook air?

No, Bloxstrap is not cross-platform whatsoever.

**Comment by SondreDj** [comment]
@mickymatthews might work with wine or proton.

**Comment by WaviestBalloon** [comment]
> @mickymatthews might work with wine or proton.

Wine support is blocked, do not use Wine or any forks like Proton.

**Comment by SondreDj** [comment]
They broke grapejuice and vinegar again?

**Comment by WaviestBalloon** [comment]
> will you guys add bloxstrap for macs soon?

Probably never.
