### ISSUE TITLE
[REQ] New options: Quick Game Launch, Remove Disconnect Blur/Loading Blur

### ISSUE THREAD

**Issue by xignotlz** [pizzaboxer/bloxstrap#1806]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

What about adding these new Quick Game Launch and remove blur features into bloxstrap menu? If users are looking for **_more performance_** or speed when entering a game, this is perfect.

**Quick Game Launch can be a little buggy** + **Both features have fast flags.**

**Comment by pizzaboxer** [comment]
What do you mean by "quick game launch"?

**Comment by xignotlz** [comment]
Quick Game Launch is a fast flag that skips roblox 'joining server' loading screen.

**Comment by pizzaboxer** [comment]
> Quick Game Launch is a fast flag that skips roblox 'joining server' loading screen. 

I don't think I've seen it, can youg ive it please?

**Comment by xignotlz** [comment]
> > Quick Game Launch is a fast flag that skips roblox 'joining server' loading screen.
> 
> I don't think I've seen it, can youg ive it please?

Ok, here you go:

**Quick Game Launch:**
"FFlagEnableQuickGameLaunch": "True"

**Remove Blur:**
"FIntRobloxGuiBlurIntensity": "0"

**Comment by pizzaboxer** [comment]
Are you sure the quick game launch flag skips the loading screen? It still does it for me.

**Comment by xignotlz** [comment]
As I said before, Quick Game Launch is a little buggy sometimes and may not work sometimes.
