### ISSUE TITLE
bloxstrap is not starting but in task manager

### ISSUE THREAD

**Issue by 10kvibezzz** [pizzaboxer/bloxstrap#1808]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i start bloxtrap it shows starting roblox and nothing happens i opened the task manager and bloxtrap is open but its not starting pls help
![Screenshot 2024-05-12 115631](https://github.com/pizzaboxer/bloxstrap/assets/169697715/ae2b80b0-209e-4687-b044-290f451b60d5)
![Screenshot 2024-05-12 115944](https://github.com/pizzaboxer/bloxstrap/assets/169697715/f74645a5-1cb4-49f0-ada5-5a3500273782)

**Comment by moyaimoment** [comment]
![IMG_0466](https://github.com/pizzaboxer/bloxstrap/assets/51049688/cae225fc-bdb4-40aa-ab89-7a307797c111)
someone didnt read it

**Comment by pizzaboxer** [comment]
> when i start bloxtrap it shows starting roblox and nothing happens i opened the task manager and bloxtrap is open but its not starting pls help

Read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch first before you ask for any more help.
