### ISSUE TITLE
Roblox Crashes Randomly

### ISSUE THREAD

**Issue by daagger** [pizzaboxer/bloxstrap#181]
(using 64 bit byfron version of roblox using bloxstrap) Game randomly crashes at some random point, it freezes then crashes. Ill list an example. 

https://user-images.githubusercontent.com/119818604/236091947-eb52f6be-41a7-4b7f-94cb-7725838a0bb9.mp4

It freezes, then later Roblox closes. Im not sure if this is a bloxstrap issue, because I am using custom fflags different from bloxstraps built  in fflags.

**Comment by pizzaboxer** [comment]
I've heard of other people experiencing this same crash with the new 64-bit client. Uninstall Bloxstrap to revert back to the original bootstrapper and see if it's still happening.

**Comment by Empyrlum** [comment]
> I've heard of other people experiencing this same crash with the new 64-bit client. Uninstall Bloxstrap to revert back to the original bootstrapper and see if it's still happening.

im using the original bootstrapper and i still experience crashes

**Comment by painelle** [comment]
> > I've heard of other people experiencing this same crash with the new 64-bit client. Uninstall Bloxstrap to revert back to the original bootstrapper and see if it's still happening.
> 
> im

 using the original bootstrapper and i still experience crashes


![Screenshot_1](https://user-images.githubusercontent.com/71561421/236589793-4b7be9be-c52f-44bd-ac25-86e5a5ad7af2.png)
same issue

**Comment by vipking-o1** [comment]
use zcanary channel its a temp fix

**Comment by painelle** [comment]
> use zcanary channel its a temp fix

doesn't work
![image](https://user-images.githubusercontent.com/71561421/236634964-2b94af93-d476-4d3c-8f31-90374d9dae7e.png)
didn't even let me play this time

**Comment by ThatOneOcto** [comment]
it makes me crash randomly without message

**Comment by Extravi** [comment]
set it back to 32 bit

**Comment by pizzaboxer** [comment]
Closing this since there's not much I can do about this, and it's a few weeks old at this point. Though, since then, I have made this Wiki page:

https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-crashes

**Comment by pizzaboxer** [comment]
> similar issue when i minimize my roblox tab it freezes and only the sounds could be heard very annoying when i need to close the tab to do something

Stop using Vulkan

**Comment by Strimnik** [comment]
send fflags
