### ISSUE TITLE
Menu Isn't Menuing

### ISSUE THREAD

**Issue by IDontKnowWhyIamHer** [pizzaboxer/bloxstrap#1810]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I open BloxStrap Menu, It takes me to Roblox Player. The reason why I want to open the menu is because I want to change fonts and stuff. Does anyone know why this is happening?

**Comment by Vlad55432** [comment]
can you demonstrate that?

**Comment by xignotlz** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> ### What problem did you encounter?
> When I open BloxStrap Menu, It takes me to Roblox Player. The reason why I want to open the menu is because I want to change fonts and stuff. Does anyone know why this is happening?

Just type "Bloxstrap Menu" in your Windows search bar and open it.
![Screenshot_1](https://github.com/pizzaboxer/bloxstrap/assets/169560873/d6305885-b126-461c-b958-80e0f0b4aabb)

**Comment by IDontKnowWhyIamHer** [comment]
It doesn't work for the people who ask me to search it on Windows, it sends me right to Roblox Player.

**Comment by pizzaboxer** [comment]
> it sends me right to Roblox Player.

Are you saying that searching for it only shows "Roblox Player" as a result, or that trying to open the Bloxstrap Menu directly opens Roblox?

**Comment by ShadowCodeX-debug** [comment]
Do Windows Key + R and paste in 
`%LocalAppData%\Bloxstrap\Bloxstrap.exe -menu`

_Originally posted by @moyaimoment in https://github.com/pizzaboxer/bloxstrap/issues/1836#issuecomment-2119052200_

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
