### ISSUE TITLE
[BUG]Bloxstrap menu

### ISSUE THREAD

**Issue by CICAGLISAQ** [pizzaboxer/bloxstrap#1811]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

How do I get back to bloxstrap menu if I already installed it?

**Comment by xignotlz** [comment]
You can open it by searching "Bloxstrap Menu" in your Windows search bar.
![330403054-d6305885-b126-461c-b958-80e0f0b4aabb](https://github.com/pizzaboxer/bloxstrap/assets/169560873/646763fd-0782-4482-a442-63177ecc05d1)

**Comment by IDontKnowWhyIamHer** [comment]
That sends me to Roblox Player tho.

**Comment by moyaimoment** [comment]
> That sends me to Roblox Player tho.

You made sure that you clicked "Bloxstrap Menu"?
