### ISSUE TITLE
[BUG] Bloxstrap launching Roblox but modifications not applying 

### ISSUE THREAD

**Issue by Get2Far** [pizzaboxer/bloxstrap#1813]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've been using Bloxstrap for over 2 weeks and counting now it was running completely fine and compatible with Roblox now on my Windows 7 Pro with no issues whatsoever, when I tried to put in a FastFlag to make my game's render distance further with no lag I booted up Bloxstrap but instead it opened up chrome, disabled desktop hide and it still did the same thing so I deleted and reinstalled Bstrap, modified it (2.54 and 2.53) and it won't modify Bstrap anymore, does anybody know how to fix this issue?

**Comment by jamesgarry1** [comment]
send your fflags

**Comment by xignotlz** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> ### What problem did you encounter?
> I've been using Bloxstrap for over 2 weeks and counting now it was running completely fine and compatible with Roblox now on my Windows 7 Pro with no issues whatsoever, when I tried to put in a FastFlag to make my game's render distance further with no lag I booted up Bloxstrap but instead it opened up chrome, disabled desktop hide and it still did the same thing so I deleted and reinstalled Bstrap, modified it (2.54 and 2.53) and it won't modify Bstrap anymore, does anybody know how to fix this issue?

Try this one:
Go to Roblox Player properties folder and then delete your _"ClientSettings"_ folder. And then open your Roblox Player again.
