### ISSUE TITLE
[BUG] fullscreen not working

### ISSUE THREAD

**Issue by misterlewi** [pizzaboxer/bloxstrap#1814]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so basically whenever I open bloxstrap and enter a game. And try to exit fullscreen using alt+enter it doesn't work. Even tried to exit fullscreen on the roblox menu itself. I restarted and even shutted down my computer to give it a rest cause I first thought that it was just pc being weird. But it's still the same

**Comment by xignotlz** [comment]
Try to **Alt+F4** whenever that happens.

**Comment by pizzaboxer** [comment]
> And try to exit fullscreen using alt+enter it doesn't work. 

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
