### ISSUE TITLE
"Bad Image" error

### ISSUE THREAD

**Issue by greentron3** [pizzaboxer/bloxstrap#1817]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when attempting to play roblox alongside bloxstrap I was met with a "bad image" error. Could not launch or even uninstall bloxstrap so I had to find it within its file location and purge it. Can play roblox normally now but when attempting to launch anything bloxstrap related I am met with "C:\Program Files\dotnet\host\fxr\6.0.40\hostfxr.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f.". My friend believed it was windows .NET framework and after numerous attempts at reinstalling and running command prompts to no avail. I really have no idea what the issue is and would appreciate some insight on how to fix this.
![image](https://github.com/pizzaboxer/bloxstrap/assets/20546701/d6d27c67-875b-422c-a1ef-4e89923f0c2a)

**Comment by pizzaboxer** [comment]
Are you sure you tried reinstalling the correct version? https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.30-windows-x64-installer?cid=getdotnetcore

**Comment by greentron3** [comment]
> Are you sure you tried reinstalling the correct version? https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.30-windows-x64-installer?cid=getdotnetcore

man i need to ask my friend about what he recommended and why it didn't work because i swear it was similar.
bottom line is i uninstalled then reinstalled what you provided and it is repaired now 🤠thanks!
