### ISSUE TITLE
[BUG]  403 error only when using bloxstrap.

### ISSUE THREAD

**Issue by Delatlevs** [pizzaboxer/bloxstrap#1820]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When attempting to open roblox, it says Error Code: 403 An error was encountered during authentication. Please try again. How do I fix this?

**Comment by BokBoy** [comment]
Hello!!

Just confirming you have read through this error? https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by ZenixScripts** [comment]
I still am getting 403 auth errors, it's mostly caused from a roblox account being logged in the player but on the website where you're trying to launch from is in a different account. .But mine I am not logged into the player and when I try to join from roblox website it's 403 error even if I am not logged in and if I am logged in then I can run it fine. I am trying to use multi-instance so is there any way you could help me?

**Comment by BokBoy** [comment]
Pizzaboxer dropped multi instance support a while ago. If you still have it, then it's because you haven't updated to the latest version.
That's probably the cause of the 403
