### ISSUE TITLE
[BUG] The file or folder is damaged. Reading is not possible

### ISSUE THREAD

**Issue by snack15** [pizzaboxer/bloxstrap#1821]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I, like all other roblox players, play with bloxstrap and two weeks ago I had an error that bloxstrap cannot access something in the wiki it was written to add bloxstrap to the antivirus exception but this did not help to solve this problem I every time I set the bloxstrap menu so that next time Roblox will be reinstalled and now I have this error (all my settings in bloxstrap are also lost) what do I need to do?
[Bloxstrap_20240516T071848Z.log](https://github.com/pizzaboxer/bloxstrap/files/15331124/Bloxstrap_20240516T071848Z.log)
![image](https://github.com/pizzaboxer/bloxstrap/assets/169978634/4fce90c3-1063-45f2-825b-8273423864fb)

**Comment by BokBoy** [comment]
Hello!! 

You appear to have a similar issue as my friend on discord! (https://discord.com/channels/1099468797410283540/1240552141421281331)

This is the guide I sent them. Try doing this and see if it works. Thanks!

> Alright, I see that you have installed this onto an external drive; heres what I'd suggest to do.

> Go to D:\блокстранпиа and delete that folder (which I am presuming is bloxstrap in russian). 

> Then go back onto https://github.com/pizzaboxer/bloxstrap then find the latest version and download the exe.

> The reason why is that I presume that once during the ejection or something of the external drive, some data has been corrupted from it and may require a full reinstall.

**Comment by pizzaboxer** [comment]
As mentioned above, reinstalling it again should fix it. Though, if this is a removable drive you're installing to, you might want to avoid installing there.
