### ISSUE TITLE
[BUG] when using controller on pc

### ISSUE THREAD

**Issue by RoobieRockSt4r** [pizzaboxer/bloxstrap#1822]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i use any program with an fps unlocker its messes up with camera and makes it sticky.

**Comment by BokBoy** [comment]
Hello...

Apologies but makes the what sticky??!! Can you share an example or something??!!

**Comment by pizzaboxer** [comment]
> When i use any program with an fps unlocker its messes up with camera and makes it sticky.

What does this have to do with Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
