### ISSUE TITLE
[BUG] Cant play on 2 acc even tho i turned it on

### ISSUE THREAD

**Issue by gimmeproplayer** [pizzaboxer/bloxstrap#1823]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Basicly i turned on the "Allow multi-instance launching" but i can't play on 2 acc or more. Please fix this bug

**Comment by jamesgarry1** [comment]
you need 2 different accounts

**Comment by pizzaboxer** [comment]
What's happening when you try to play on two or more accounts?

**Comment by Oshiro14** [comment]
For me it says this every time I try to join on the other account
![image](https://github.com/pizzaboxer/bloxstrap/assets/170225057/6964a958-53d7-4065-9a67-20ff1a670e5d)

**Comment by pizzaboxer** [comment]
> For me it says this every time I try to join on the other account

Not a Bloxstrap issue, that's a problem involving browser launching

**Comment by Oshiro14** [comment]
Do you know if there is any way of solving this issue?

**Comment by pizzaboxer** [comment]
Probably, but I'm only interested in issues specific to Bloxstrap

**Comment by MaskedBozo** [comment]
> Probably, but I'm only interested in issues specific to Bloxstrap
