### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jabawee** [pizzaboxer/bloxstrap#1825]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I had this error come up when launching Roblox with Bloxstrap. It's been for about a week since the last I turned on my PC and decided to play for a bit. When I tried to play a game, it encounters an error, saying "An Exception occurred while running Bloxstrap" and gabe me this code to report it in here:
`System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.

Can someone help me address this concern? Thanks in advance!
- Jabawee (@JabaweeYT)

![image](https://github.com/pizzaboxer/bloxstrap/assets/170019637/4fab79a3-51c1-4ac8-bca6-7e737ae45e26)

**Comment by alxspiker** [comment]
Hi @jabawee,

Thank you for reporting the issue. Here are a few steps that might help resolve the `System.Net.Http.HttpRequestException: No such host is known` error:

1. **Check Network Connection**: Ensure that your network connection is stable and active. A network issue could cause the inability to resolve the host.

2. **Verify DNS Configuration**: Sometimes, DNS issues can cause host resolution failures. Try changing your DNS server settings to a public DNS server like Google's (8.8.8.8 and 8.8.4.4).

3. **Check Host Availability**: Verify if `setup.rbxcdn.com` is accessible from your network. You can use the `ping` command or any online tools to check the server's status.

4. **Firewall/Antivirus Settings**: Check if any firewall or antivirus software is blocking the connection. Temporarily disable them to see if it resolves the issue.

5. **Check Application Updates**: Ensure that both Roblox and Bloxstrap are updated to the latest versions. Sometimes, updates contain fixes for such issues.

6. **Reinstall Bloxstrap**: If the above steps do not work, try reinstalling Bloxstrap. This can sometimes resolve configuration issues.

Please let us know if the issue persists or if you need further assistance.

Best regards,
The Bloxstrap Team
