### ISSUE TITLE
[REQ] Unlinked FPS caps.

### ISSUE THREAD

**Issue by NimbusIzayoi** [pizzaboxer/bloxstrap#1826]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Currently changing FPS requires closing all Roblox instances (not default behavior)
Have it check what the FPS cap is when opening an instance so we can have different FPS caps for different instances (default behavior)

IE: 60 FPS on one window, then 20 FPS others.

**Comment by pizzaboxer** [comment]
While we don't clearly state it here, we're not really interested in helping people who are blatantly just trying to farm on alt accounts.

**Comment by NimbusIzayoi** [comment]
This is a default feature of Roblox. Bloxstrap breaks it.
