### ISSUE TITLE
white screen when trying to start up the roblox play from bloxstrap

### ISSUE THREAD

**Issue by Vr36** [pizzaboxer/bloxstrap#1828]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i downloaded bloxstrap cuz i wanted the minecraft folts but then when i downloaded everything went well so i wanted to start up my roblox play from bloxstrap put then i just got the white screen it keeps staying on the white screen pleasee help me

**Comment by Vr36** [comment]
look i wil ascreen rocord for you

**Comment by Vr36** [comment]
https://github.com/pizzaboxer/bloxstrap/assets/170042255/53b0d747-6871-47cd-96d0-9bbb137b9049

**Comment by pizzaboxer** [comment]
You're supposed to first extract the .zip file that the download for the font gives you. You do not directly apply the .zip file as the font.
