### ISSUE TITLE
System.Net.Http.HttpRequestException: An error occurred while sending the request.

### ISSUE THREAD

**Issue by HubRobloxScript** [pizzaboxer/bloxstrap#1829]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Inner Exception]
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..

[Inner Exception]
System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine.

**Comment by pizzaboxer** [comment]
If this is not happening every time you launch then just ignore it. If it is, then it's something on your computer like an antivirus or VPN that's causing it.
