### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Modifications\content\fonts\CustomFont.ttf' is denied.

### ISSUE THREAD

**Issue by Winterslof** [pizzaboxer/bloxstrap#1830]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240517T214006Z.log](https://github.com/pizzaboxer/bloxstrap/files/15358450/Bloxstrap_20240517T214006Z.log)

**Comment by pizzaboxer** [comment]
[Open the mods folder, go to https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-when-trying-to-remove-a-custom-font](https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-when-trying-to-remove-a-custom-font)
