### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by NightBloodG51** [pizzaboxer/bloxstrap#1831]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240518T071453Z.log](https://github.com/pizzaboxer/bloxstrap/files/15360500/Bloxstrap_20240518T071453Z.log)

**Comment by moyaimoment** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-error-when-trying-to-reinstall-Bloxstrap

**Comment by NightBloodG51** [comment]
it was a "MSI Afterburner" i Used to Overclock my GPU And Other things, So i Closed MSI Afterburner Because **"Hyperions"** hates it alot. then Uninstall "bloxstrap" then Deleting the Folder After that I Reinstalled it and Run it again and it Launch. Thank You Guys :)
