### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\awby2\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by ahmedwaleed2002** [pizzaboxer/bloxstrap#1832]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\awby2\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by moyaimoment** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/51049688/12bc37d2-8365-4cd0-b05c-55e59fe02af6)
Liar

https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-error-when-trying-to-reinstall-Bloxstrap
