### ISSUE TITLE
[BUG] Unexpected Crash Error

### ISSUE THREAD

**Issue by BrowsingTheInternet** [pizzaboxer/bloxstrap#1833]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Dear Developers,

Bloxtrap bootstrapper has the tendency to crash either by simply joining a game or by joining an experience while in game, but that's not the case with the Roblox bootstrapper. My ClientSettings are filled with fast flags, yes, but that doesn't seem to be the problem. I've tested out the Roblox bootstrapper and Bloxtrap bootstrapper with ClientSettings and I still experience crashes on the Bloxtrap boostrapper, but not on the Roblox bootstrapper.

If this issue's not gonna be resolved, then I'll unfortunately be forced to stop using Bloxtrap, which I don't want to. Bloxtrap is a unique alternative that I wish to use for as long as it is, but with this issue that persists, I can't afford to use it.

I hope you, dear devs, look into the code and fix this awful issue within the Bloxtrap bootstrapper.

Sincerely, Untitled.

(cringe of me, ngl)

**Comment by BrowsingTheInternet** [comment]
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/15366270/ClientAppSettings.json)

If you're interested.

**Comment by moyaimoment** [comment]
Bloxstrap*

**Comment by BrowsingTheInternet** [comment]
💀

**Comment by pizzaboxer** [comment]
Did you at all check if your issue happens without having these set in Bloxstrap?

**Comment by BrowsingTheInternet** [comment]
I did, but the outcome is still the same. The Bloxstrap bootstrapper crashes more often than the Roblox Bootstrapper. I'm currently using Roblox bootstrapper with my ClientSettings imported to the version directory, and I'll reply back on my findings.
