### ISSUE TITLE
[BUG] An exception occured while Running Bloxstrap 

### ISSUE THREAD

**Issue by uhuhue** [pizzaboxer/bloxstrap#1834]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

please help me, when i try bloxstrap it says An exception occured while Running Bloxstrap because i dont have enough space in my disk. how to clear it up

**Comment by pizzaboxer** [comment]
Can you show the error message please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
