### ISSUE TITLE
[BUG] FPS is still capped at 60 after being raised while using the Bloxshade Version

### ISSUE THREAD

**Issue by therealkiddude** [pizzaboxer/bloxstrap#1835]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I am using Bloxshade with the bootstrapper, without bloxstrap the FPS unlocker works, but it does not with bloxshade, it's still capped at 60

**Comment by pizzaboxer** [comment]
Using Bloxshade caps it to your display refresh rate. You didn't think to ask Bloxshade support about this first?
