### ISSUE TITLE
[BUG] O BLOXSTRAP MENU SIMPLISE DOESN’T EXIST

### ISSUE THREAD

**Issue by kailailumen** [pizzaboxer/bloxstrap#1836]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I try to open the menu (which doesn't exist, even though I'm looking everywhere) it simply opens the Roblox launcher to start playing, even uninstalling and installing again I still can't open the Bloxstrap Menu. Please Help!!
![Captura de tela 2024-05-18 222108](https://github.com/pizzaboxer/bloxstrap/assets/170214824/46aef946-19b3-47a9-8630-134bd0707cdf)

![Captura de tela 2024-05-18 222148](https://github.com/pizzaboxer/bloxstrap/assets/170214824/0faa8a71-032d-451a-b420-b99f1adc0d17)

**Comment by moyaimoment** [comment]
Do Windows Key + R and paste in 
`%LocalAppData%\Bloxstrap\Bloxstrap.exe -menu`

**Comment by ShadowCodeX-debug** [comment]
> Do Windows Key + R and paste in `%LocalAppData%\Bloxstrap\Bloxstrap.exe -menu`

You can also copy this into a shortcut.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
