### ISSUE TITLE
[probleme while running bloxstrap]

### ISSUE THREAD

**Issue by ImDaRealAdrian** [pizzaboxer/bloxstrap#1837]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

hello,
i downloaded bloxstrap but when i try to play roblox {start roblox} i get a white screene 
what do i do?

**Comment by ShadowCodeX-debug** [comment]
What settings do you have enabled?

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
