### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\{My Name}\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied. [BUG] 

### ISSUE THREAD

**Issue by SlideShowGames** [pizzaboxer/bloxstrap#1839]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was installing base bloxstrap and got this error:
System.UnauthorizedAccessException: Access to the path 'C:\Users\{My Name}\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by moyaimoment** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-error-when-trying-to-reinstall-Bloxstrap
