### ISSUE TITLE
it didn't let me play roblox properly

### ISSUE THREAD

**Issue by NullProtector** [pizzaboxer/bloxstrap#184]
the problem is it says How to solve it???
![image_2023-05-04_181833266](https://user-images.githubusercontent.com/129590926/236235496-d252d94c-d158-40c6-86d8-b9ad127979c9.png)

**Comment by pizzaboxer** [comment]
Can you please send the latest Bloxstrap log file? You can find it by navigating to `%localappdata%\Bloxstrap\Logs` in the Windows file browser.

**Comment by sutnax** [comment]
If you're using byfron bypass script, delete it. Then open Bloxstrap menu and then go to Installations tab and change the channel to Zlive (Bloxstrap will automatically detect it).

**Comment by sutnax** [comment]
> If you're using byfron bypass script, delete it. Then open Bloxstrap menu and then go to Installations tab and change the channel to Zlive (Bloxstrap will automatically detect it).

I had this issue some minutes ago and i fixed this by doing this.

**Comment by pizzaboxer** [comment]
This is related to channel configuration? Thanks for the heads up, but I'd still like to see a log file so I can be sure.

**Comment by pizzaboxer** [comment]
Closing since it's not clear if this is a Bloxstrap problem or if it's just the Roblox website screwing up, and the post is inactive.
