### ISSUE TITLE
[BUG] no cursor floders in contents 

### ISSUE THREAD

**Issue by toucanlc** [pizzaboxer/bloxstrap#1842]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried to have a custo mouse cursor mod, but i can't any cursors folders in the contents folder
![Capteure](https://github.com/pizzaboxer/bloxstrap/assets/139295353/008a459b-5784-47fc-8924-0a6e3f418310)
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/139295353/b418934b-160a-41fa-b908-b8ddb54583ea)

**Comment by Vlad55432** [comment]
path of cursor is there
> Bloxstrap\Modifications\content\textures\Cursors\KeyboardMouse
![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/f3b1a936-87b2-46f4-95d1-55c089359d31)

You just need to create path and paste ArrowCursor and ArrowFarCursor pngs

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

>"By default, the mods folder does not have the directory structure of the version folder. So, you will often need to create new folders in order to represent your file's location within the version folder."
