### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rizamate** [pizzaboxer/bloxstrap#1843]
how to change the settings of the bloxstrap in a new way

**Comment by Vlad55432** [comment]
in bloxstrap menu? What Do you mean?

**Comment by 7valkio** [comment]
If you already have Bloxstrap installed, just simply search for **Bloxstrap Menu** in your start menu if you are on Windows and run it. You can change your settings and then save them. 

![image](https://github.com/pizzaboxer/bloxstrap/assets/113270877/9bfea459-60b4-4f7e-a0e8-ddddc962b6d2)
