### ISSUE TITLE
[BUG] Roblox losing graphic quality 

### ISSUE THREAD

**Issue by Sokio12** [pizzaboxer/bloxstrap#1844]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so basically everytime i lauch any game with bloxstrap the quality graphic get worse than before for some reason and i tried to enable "preserve rendering quality with display setting" and it didnt do anything. here some screenshot
@
![image_2024-05-21_134358266](https://github.com/pizzaboxer/bloxstrap/assets/170455579/2a0b5a20-b1b0-465a-91fb-e92f0397fea4)
![Screenshot 2024-05-21 133254](https://github.com/pizzaboxer/bloxstrap/assets/170455579/5b1a5ce2-f5a4-499b-ab0d-b0c0eb4faecd)

**Comment by NotWalking** [comment]
Is your graphics setting set to automatic? If so, turn it off and set it to a manual setting using the slider. This should solve it.

**Comment by Sokio12** [comment]
> Is your graphics setting set to automatic? If so, turn it off and set it to a manual setting using the slider. This should solve it.

its already at max and on manual

**Comment by Sokio12** [comment]
> Is your graphics setting set to automatic? If so, turn it off and set it to a manual setting using the slider. This should solve it.

even when its in the menu it does this weird low graphic bug 
![image_2024-05-21_184217490](https://github.com/pizzaboxer/bloxstrap/assets/170455579/edae15aa-6b99-4269-876d-2b4aaecb0844)

**Comment by pizzaboxer** [comment]
Does it happen only using Bloxstrap? If so, what does it normally look like?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
