### ISSUE TITLE
Virus Total (Trojan)

### ISSUE THREAD

**Issue by Kaixon986** [pizzaboxer/bloxstrap#1846]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Gridinsoft (no cloud)                                    [Trojan.Win64.AsyncRAT.tr](javascript:void(0);)

Those are virus total results when scanning Bloxstrap...anyone else have this problem?
![image](https://github.com/pizzaboxer/bloxstrap/assets/170569139/6c1321ef-2919-418d-a9c8-a23ffef4e5c0)

**Comment by Jalenzzz** [comment]
That's just a false positive lol plus that's just a single security vendor out of 72. Bloxstrap doesn't inject a trojan virus into your computer. If it did, it would have been widely known by now plus their code is open source so you can check for any changes at any time.
![image](https://github.com/pizzaboxer/bloxstrap/assets/126164913/da73e5f7-32db-41a2-aa65-0fcd6b207ba6)
