### ISSUE TITLE
[BUG] .net not working

### ISSUE THREAD

**Issue by toazet** [pizzaboxer/bloxstrap#1848]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i don't know if this is the right place for this, but im out of hope

I'm trying to instal Bloxstraps but i keep getting this error that sayd "you need to instad .net" witch i have, i dowloaded version 5.0.0, 6.0.0 and all the others but it just dosent work!

Please help

**Comment by pizzaboxer** [comment]
Did you install the version that I linked? https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true
