### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by keoni112** [pizzaboxer/bloxstrap#1849]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Well im trying to use the multi launch feature and it wont start the 2nd roblox it keeps saying
''System.Exception: Signature does not match!'' and said please report this exception through a github issue or in our discord chat 
[Bloxstrap_20240523T181015Z.log](https://github.com/pizzaboxer/bloxstrap/files/15420946/Bloxstrap_20240523T181015Z.log)

**Comment by keoni112** [comment]
Do i re install bloxstrap?

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
