### ISSUE TITLE
Can't change Client API from D3D11, still stuck with using D3D11

### ISSUE THREAD

**Issue by BaconismTV** [pizzaboxer/bloxstrap#185]
Using the Bloxstrap Menu to change the API doesn't seem to actually change it from D3D11 to Vulkan.  Even setting the FFlag, "FFlagDebugGraphicsPreferVulkan": "True" in the ClientAppSettings.json doesn't fix it.  It just changes it back to D3D11 when launching a game.

**Comment by pizzaboxer** [comment]
Are you running v2.3.0? And can I confirm that you do not have the "enable exclusive fullscreen" option enabled?

**Comment by BaconismTV** [comment]
> Are you running v2.3.0? And can I confirm that you do not have the "enable exclusive fullscreen" option enabled?

Yes, but I now realize that I did have Exclusive FS on, my bad lol
