### ISSUE TITLE
[BUG] Just a white screen but i can open regular roblox?

### ISSUE THREAD

**Issue by Klopoic** [pizzaboxer/bloxstrap#1850]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i open bloxstrap its just a white screen but normal roblox opens instantly, any tips?
![Screenshot 2024-05-23 202050](https://github.com/pizzaboxer/bloxstrap/assets/170665266/fb609292-c4c8-4727-8788-99c79bca21a0)

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
