### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FwJax** [pizzaboxer/bloxstrap#1851]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: An error occurred while sending the request.

[Inner Exception]
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..

[Inner Exception]
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by pizzaboxer** [comment]
If this happens every time you launch then check to make sure your antivirus isn't interfering.

**Comment by FwJax** [comment]
> If this happens every time you launch then check to make sure your antivirus isn't interfering.

thanks alot
