### ISSUE TITLE
[BUG] My ping goes very high when i use bloxtrap

### ISSUE THREAD

**Issue by StefElPapu** [pizzaboxer/bloxstrap#1853]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i was playing roblox whit bloxtrap, my ping was very high whit 400 when i normally play at 100 or 70, then, i opened roblox without bloxtrap and my ping went back to normal, i dont know how to fix this.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
