### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\win\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by bach32145** [pizzaboxer/bloxstrap#1855]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Uploading Screenshot 2024-05-24 201757.png…]()

**Comment by moyaimoment** [comment]
You didn't wait for your Screenshot to upload before sending your Issue.

Also read.
https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-error-when-trying-to-reinstall-Bloxstrap
