### ISSUE TITLE
Bloxstrap

### ISSUE THREAD

**Issue by DicksonKaiden** [pizzaboxer/bloxstrap#1856]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I cant install blox strap or when i had it installed it wont open roblox

**Comment by pizzaboxer** [comment]
Can you better clarify the problem please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
