### ISSUE TITLE
[BUG] bloxstrap errors about not being able to connect and refuses to reinstall

### ISSUE THREAD

**Issue by dataesucsdeek** [pizzaboxer/bloxstrap#1857]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240524T215256Z.log](https://github.com/pizzaboxer/bloxstrap/files/15440337/Bloxstrap_20240524T215256Z.log)

**Comment by pizzaboxer** [comment]
If this happens every time then check to make sure your antivirus isn't intefering
