### ISSUE TITLE
[BUG] start menu or menu is not working and not showing i have clicked the bloxstrap menu but its not working showing nothing

### ISSUE THREAD

**Issue by Hoyokei** [pizzaboxer/bloxstrap#1859]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

not opening

**Comment by Hoyokei** [comment]
nvm

**Comment by VoidNmbrZero** [comment]
hey @Hoyokei you should close this issue, so it gets marked as solved
