### ISSUE TITLE
suggestion for an alternative for the multi instance feature

### ISSUE THREAD

**Issue by Galaxy0Gamer** [pizzaboxer/bloxstrap#1860]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

can someone please suggest an alternative to the multi instance feature? other than the one by wearedevs, that one is bad compared to bloxstrap

**Comment by NimbusIzayoi** [comment]
Roblox Account Manager

**Comment by KorosAzolus** [comment]
True. Goated program.

**Comment by moyaimoment** [comment]
google is free
