### ISSUE TITLE
[BUG] Sorry roblox had to quit (FONT)

### ISSUE THREAD

**Issue by Glinguss** [pizzaboxer/bloxstrap#1861]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have been witnessing every time I would try to use a font for a game It would just not let me join, say "Sorry Roblox had to quit" but as I were to disable the font or get rid of it, I would be able to play game. It would happen for all of the font I had tried using

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
