### ISSUE TITLE
System.IO.IOException: Cannot create 'C:\Users\heath\AppData\Local\Bloxstrap\Modifications\content\fonts' because a file or directory with the same name already exists.[BUG] 

### ISSUE THREAD

**Issue by css9274cassius** [pizzaboxer/bloxstrap#1862]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i was trying to add a font when this popped up *
![Bloxstrap Exception 5_25_2024 4_59_59 PM](https://github.com/pizzaboxer/bloxstrap/assets/170834082/1c73b161-5b6f-4650-ab20-4aaa44655b2c)
*System.IO.IOException: Cannot create 'C:\Users\heath\AppData\Local\Bloxstrap\Modifications\content\fonts' because a file or directory with the same name already exists**

**Comment by pizzaboxer** [comment]
Send the log file
