### ISSUE TITLE
[BUG]  BLOXTRAP NO OPEN

### ISSUE THREAD

**Issue by TekuOfficial** [pizzaboxer/bloxstrap#1863]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My bloxtrap won't open, I've tried everything and tutorials, I've reinstalled it several times before and it was working normally

**Comment by moyaimoment** [comment]
Bloxstrap*

also you gave zero information.
If you meant the Menu, click the Windows key then type "Bloxstrap Menu". If it doesn't show there then click Windows Key + R and paste in `%LocalAppData%\Bloxstrap\Bloxstrap.exe -menu`

**Comment by pizzaboxer** [comment]
What happens when you try to open it?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
