### ISSUE TITLE
[REQ] Disable the annoying VR message

### ISSUE THREAD

**Issue by FanACYT** [pizzaboxer/bloxstrap#1864]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Is there anyway to disable the stupid VR thing that pops up
![2uopsvrqso](https://github.com/pizzaboxer/bloxstrap/assets/76235545/b1cc2430-413b-47ae-ae36-60ff2fc69f29)

**Comment by colezx5014** [comment]
Pretty sure uninstalling stuff like the Oculus app will remove that, since it worked for me. No clue if SteamVR causes that though.

**Comment by IMrCreepyI** [comment]
or add a option to disable the pop up. cause some people use the oculus app for pc vr so they cant just go uninstalling it because they dont want a unnecessary pop up to show every time when they start roblox.

**Comment by pizzaboxer** [comment]
No
