### ISSUE TITLE
[BUG] bloxstrap launch browser roblox

### ISSUE THREAD

**Issue by h9ll1** [pizzaboxer/bloxstrap#1866]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

**bloxstrap launch browser roblox** this my problem, bloxstrap just don't launch roblox launcher, he launch browser, but other's bloxstrap launch roblox launcher :/

**Comment by moyaimoment** [comment]
Turn this off if you want the Roblox app.
![image](https://github.com/pizzaboxer/bloxstrap/assets/51049688/b7e9e0b1-e750-4362-888b-7c12c9ae0cba)
