### ISSUE TITLE
[BUG] System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by L000OR** [pizzaboxer/bloxstrap#1867]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/170973381/eb0d3a2b-a06c-4d62-992a-cdfe9eda09b8)

**Comment by moyaimoment** [comment]
bro did not read anything

https://github.com/pizzaboxer/bloxstrap/wiki/"Signature-does-not-match!"-error-when-launching-Roblox
