### ISSUE TITLE
[BUG] Error 404, Page not Found when joining from a profile

### ISSUE THREAD

**Issue by Prioritizing** [pizzaboxer/bloxstrap#1869]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I try to join a player from their profile I encounter Error 404, (on the app, not web)
![image_2024-05-27_163457205](https://github.com/pizzaboxer/bloxstrap/assets/170985061/6041128f-e244-4a03-ae75-bf60ff3b6f07)
![image_2024-05-27_163511978](https://github.com/pizzaboxer/bloxstrap/assets/170985061/cd378750-f86a-4835-9947-cb40ad057c19)

**Comment by moyaimoment** [comment]
im pretty sure that has nothing to do with Bloxstrap
