### ISSUE TITLE
(SUGGESTION) - Saving fastflags when needed.

### ISSUE THREAD

**Issue by Shezmes** [pizzaboxer/bloxstrap#1870]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was playing a high quality game which i was interested but my fastflags removes most of the details to make it a realistic game... I would like to save the fastflags so i can change back when im done playing.

**Comment by KorosAzolus** [comment]
Sounds like you want a "loadout" type thing?

**Comment by Shezmes** [comment]
> Sounds like you want a "loadout" type thing?

Indeed indeed.

**Comment by pizzaboxer** [comment]
Duplicate of #1098.

Also, there might be a better solution to this than a profile system.
