### ISSUE TITLE
SSL PROBLEM WITH BLOXSTRAP

### ISSUE THREAD

**Issue by PeterPase** [pizzaboxer/bloxstrap#1872]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/139429952/47497058-b90d-4e7e-b62c-4541986e83a0)

**Comment by PeterPase** [comment]
this happened when i was downloading bloxstrap

**Comment by pizzaboxer** [comment]
If this happens every single time then check to make sure your antivirus isn't interfering.
