### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by vfgnbgf** [pizzaboxer/bloxstrap#1873]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.IO.FileNotFoundException: Could not find file 'C:\Users\Admin\Downloads\Bloxstrap-v2.5.4.exe'.
![image](https://github.com/pizzaboxer/bloxstrap/assets/171145072/f2350fd9-1264-40bd-b88d-e3a6cc9bb6bc)

**Comment by pizzaboxer** [comment]
If this is still happening, send the log file please

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
