### ISSUE TITLE
Bloxstrap isn't working.

### ISSUE THREAD

**Issue by Swagyee69420** [pizzaboxer/bloxstrap#1876]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So basically I turned on "Multiple Integrations" or whatever its called which supposedly allows you to launch multiple robloxes at once. It worked for a few weeks, then suddenly today or yesterday, it just stopped working. along with all my fast flags, and literally every single thing on bloxstrap. Everything is saved when I launch roblox tho so idk what's wrong.
![image](https://github.com/pizzaboxer/bloxstrap/assets/107046326/55c39884-2cae-4bcc-a2a9-3be0f80fe547)

**Comment by moyaimoment** [comment]
![Untitled812_20240528155055](https://github.com/pizzaboxer/bloxstrap/assets/51049688/a2b6f92d-78d1-4a05-b8c6-19a220c86370)

**Comment by Nova324321** [comment]
my bloxstrap isnt opening

**Comment by ItsEntDev** [comment]
> my bloxstrap isnt opening

This isn't your opening

**Comment by pizzaboxer** [comment]
> It worked for a few weeks, then suddenly today or yesterday, it just stopped working. along with all my fast flags, and literally every single thing on bloxstrap. Everything is saved when I launch roblox tho so idk what's wrong.

Do you see the Bloxstrap launcher show when you launch Roblox? If not, see https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap. You only need to run the shortcut once.
