### ISSUE TITLE
delay problem

### ISSUE THREAD

**Issue by RedBone0212** [pizzaboxer/bloxstrap#1877]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

basically ever since i downloaded bloxstrap i get this weird bug that makes everything i do on my computer have an almost 30 seconds delay but its worse when i try to play roblox i tried changing my settings or even remove them all but nothing seems to be working and roblox is basically unplayable with this and i now have alot of issues with m everyday quality of life with my computer

**Comment by moyaimoment** [comment]
you clearly have other issues on your computer

**Comment by moyaimoment** [comment]
> been happening ever since i downloaded bloxstrap everything was fine beforehand
Doesn't change the fact you still clearly have other issues with your computer lol, Bloxstrap wouldn't really affect it.

**Comment by pizzaboxer** [comment]
> ever since i downloaded bloxstrap i get this weird bug that makes everything i do on my computer have an almost 30 seconds delay 

I don't think this has any correlation. This doesn't make any sense and there isn't anything I can do or am supposed to do about this.
