### ISSUE TITLE
[BUG] bloxstrap immediately crashing after booting up

### ISSUE THREAD

**Issue by lmDaNooBy** [pizzaboxer/bloxstrap#1879]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

As soon as i open a game from bloxstrap it immediately says roblox crashed but the whole game still operates perfectly until i try to hop servers in-game then it just automatically closes the game. This doesn't happen in roblox player though it works perfectly fine with no crashes whatsoever

**Comment by Cludration** [comment]
same problume the same same same same same i need help now i have to play in normal roblox untill it fixes

(also it might be from patched fastflags or smth idk)

**Comment by mirroredissue** [comment]
Try deleting the flag: DFFlagVideoCaptureServiceEnabled

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
