### ISSUE TITLE
Server Location Feature[BUG]

### ISSUE THREAD

**Issue by FanumTaxxing** [pizzaboxer/bloxstrap#1881]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The See server location when joining a game feature doesn't work at all, And I don't know how to fix it.

**Comment by Itsyoboymoon** [comment]
i have problem that when i open bloxstrap my roblox shows error crash but roblox background is complete fine but when i try to join game it closes instantly??

**Comment by pizzaboxer** [comment]
Does rich presence work?

**Comment by FanumTaxxing** [comment]
> Does rich presence work
my fault I had to right click on bloxstrap for server details, I can see the region and all of that
Thanks!

**Comment by pizzaboxer** [comment]
Check your Windows notification settings to make sure that notifications aren't being suppressed (i.e. if you're on Do Not Disturb)
