### ISSUE TITLE
[BUG] Roblox crash error with bloxstrap

### ISSUE THREAD

**Issue by Itsyoboymoon** [pizzaboxer/bloxstrap#1882]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when ever i open roblox with bloxstrap it says error crash but roblox in back is working normally but when i try to hop on game it closes by itself and i dont know the fix for it but when i open roblox without bloxstrap it works normally.

![Screenshot (113)](https://github.com/pizzaboxer/bloxstrap/assets/171235874/c6ed149c-2473-4d25-89c2-72d00748dd9e)

**Comment by LFoxzx** [comment]
Try joining a game from web browser (the same error is happening to me, but its still playable if i join from web)

**Comment by Itsyoboymoon** [comment]
> Try joining a game from web browser (the same error is happening to me, but its still playable if i join from web)

i tryed didet work also

**Comment by LFoxzx** [comment]
do you use fast flags? if so, it might be the reason on the crashes

**Comment by mirroredissue** [comment]
Today this problem started happening with me, and i decided to check which flag was causing it by verifying groups of flags. Then, i decided to verify the last flags and realised the problem was (for me) DFFlagVideoCaptureServiceEnabled.

**Comment by Itsyoboymoon** [comment]
> Today this problem started happening with me, and i decided to check which flag was causing it by verifying groups of flags. Then, i decided to verify the last flags and realised the problem was (for me) DFFlagVideoCaptureServiceEnabled. ![image](https://private-user-images.githubusercontent.com/171286878/335409542-c4043f83-f40a-4571-bc2c-2522e1672dcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDI4MTUsIm5iZiI6MTcxNzE0MjUxNSwicGF0aCI6Ii8xNzEyODY4NzgvMzM1NDA5NTQyLWM0MDQzZjgzLWY0MGEtNDU3MS1iYzJjLTI1MjJlMTY3MmRjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwODAxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU0ZWQxMTRjYTRmNTEyNDE4ODQzYzY1ZWJhNGJiMThhZTgyMDg5N2U0ZWNhMzI1Mjk2N2U2Y2VkMGNlN2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XSfRWSpq0vyQ3fYUwGLISRHZPzPwEC03q1-JvuJKUZk)

YOOOOOOOOO THANK YOU DUDE ur truly a life saver i respect u alot bro

**Comment by mirroredissue** [comment]
> > Today this problem started happening with me, and i decided to check which flag was causing it by verifying groups of flags. Then, i decided to verify the last flags and realised the problem was (for me) DFFlagVideoCaptureServiceEnabled. ![image](https://private-user-images.githubusercontent.com/171286878/335409542-c4043f83-f40a-4571-bc2c-2522e1672dcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDI4MTUsIm5iZiI6MTcxNzE0MjUxNSwicGF0aCI6Ii8xNzEyODY4NzgvMzM1NDA5NTQyLWM0MDQzZjgzLWY0MGEtNDU3MS1iYzJjLTI1MjJlMTY3MmRjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwODAxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU0ZWQxMTRjYTRmNTEyNDE4ODQzYzY1ZWJhNGJiMThhZTgyMDg5N2U0ZWNhMzI1Mjk2N2U2Y2VkMGNlN2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XSfRWSpq0vyQ3fYUwGLISRHZPzPwEC03q1-JvuJKUZk)
> 
> YOOOOOOOOO THANK YOU DUDE ur truly a life saver i respect u alot bro

Glad to help! As a 12 years old finding the problem much faster than a lot of people that may be older than me, I honestly think we shouldn't be lazy to do things. Now, I am feeling so good helping a lot of people. It's incredible! And you're one of the first I helped. Honestly, it was also my fault. I just wanted to find the problem for myself to play and when I got the chance to maintain that information for myself only, I decided to comment on the video I got the FastFlags and even created a GitHub account lol 🤝👻

**Comment by mirroredissue** [comment]
> > > Today this problem started happening with me, and i decided to check which flag was causing it by verifying groups of flags. Then, i decided to verify the last flags and realised the problem was (for me) DFFlagVideoCaptureServiceEnabled. ![image](https://private-user-images.githubusercontent.com/171286878/335409542-c4043f83-f40a-4571-bc2c-2522e1672dcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDI4MTUsIm5iZiI6MTcxNzE0MjUxNSwicGF0aCI6Ii8xNzEyODY4NzgvMzM1NDA5NTQyLWM0MDQzZjgzLWY0MGEtNDU3MS1iYzJjLTI1MjJlMTY3MmRjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwODAxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGU0ZWQxMTRjYTRmNTEyNDE4ODQzYzY1ZWJhNGJiMThhZTgyMDg5N2U0ZWNhMzI1Mjk2N2U2Y2VkMGNlN2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XSfRWSpq0vyQ3fYUwGLISRHZPzPwEC03q1-JvuJKUZk)
> > 
> > 
> > YOOOOOOOOO THANK YOU DUDE ur truly a life saver i respect u alot bro
> 
> Glad to help! Not that I'm better than anyone, but as a 12 years old finding the problem much faster than a lot of people that may be older than me, I honestly think we shouldn't be lazy to do things. Now, I am feeling so good helping a lot of people. It's incredible! And you're one of the first I helped. Honestly, it was also my fault. I just wanted to find the problem for myself to play and when I got the chance to maintain that information for myself only, I decided to comment on the video I got the FastFlags and even created a GitHub account lol 🤝👻

**Comment by pizzaboxer** [comment]
> I honestly think we shouldn't be lazy to do things

the reason you had this problem in the first place is because you were blindly configuring things that you shouldnt have been touching: https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags
