### ISSUE TITLE
[BUG] Bloxstrap bypassed when launched, FastFlags and such not working.

### ISSUE THREAD

**Issue by Locke20041** [pizzaboxer/bloxstrap#1884]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

As of today, Bloxstrap (specifically the bootstrapper) has stopped working; any time I launch a game on Roblox, it brings up the default bootstrapper instead, and thus FastFlags like increased framerate limit don't work.

**Comment by pizzaboxer** [comment]
> it brings up the default bootstrapper instead

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Launch the shortcut once
