### ISSUE TITLE
Problems "TlsVerificationFail" Fatal fault!

### ISSUE THREAD

**Issue by KUNINSYT** [pizzaboxer/bloxstrap#1888]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I use Bloxstrap and want to play Roblox then I encounter the problem "TlsVerificationFail" and it only happens when I use Bloxstrap,
And the strangest thing is that sometimes it works and sometimes it doesn't.

**Please fix it urgently**

![Screenshot 2024-05-31 110857](https://github.com/pizzaboxer/bloxstrap/assets/160591554/b3aee811-6771-4039-b43a-b914ef322188)

**Comment by pizzaboxer** [comment]
>  And the strangest thing is that sometimes it works and sometimes it doesn't.

When this error does happen, does it happen consistently on subsequent launches or randomly?

**Comment by KUNINSYT** [comment]
@pizzaboxer Randomly

**Comment by pizzaboxer** [comment]
> @pizzaboxer Randomly

So then how do you know that this only happens with Bloxstrap? I'm pretty sure it doesn't.
