### ISSUE TITLE
[QUESTION] Fake websites ?

### ISSUE THREAD

**Issue by BlobIsBack** [pizzaboxer/bloxstrap#1889]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It's not really a bug but I found 2 websites, bloxstrap org and bloxstrap io, both seems really sketchy and have ads (not sure for the io one) are these real ?

**Comment by Itsyoboymoon** [comment]
neither are them real they are fake and this bloxstrap on their site is virus dont do it if u want real link to bloxstrap here: https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4
