### ISSUE TITLE
Roblox refusing to launch or crashing immediately after launching using Vulkan

### ISSUE THREAD

**Issue by NikoYTRBLX** [pizzaboxer/bloxstrap#189]
![image](https://user-images.githubusercontent.com/38755801/236281015-edbf3264-7124-4aea-8544-ab82fee1f759.png)
Unsure if this is due to my hardware, as I do not see anything in the log files I've analyzed. This only happens with Vulkan for some reason, while OpenGL and Direct3D11 run completely fine without hitches or crashes. When Roblox does manage to start, it crashes immediately and does not give further details in any of the log files.
DM me for the log file at Niko_#7808 if required.

**Comment by pizzaboxer** [comment]
There's not really anything I can do about this. This has to be reported directly to Roblox. By now I'm sure Roblox automatically sent a crash report, but if you have Devforum posting permissions, you can report the problem there.
