### ISSUE TITLE
Roblox crashes on startup

### ISSUE THREAD

**Issue by EscOndnd** [pizzaboxer/bloxstrap#1890]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

ive had my fastflags for a while now but it never crashed since yesterday i just cant play roblox anymore it just keeps crashing and idk how to solve it please find a solution i can maybe show u guys my flags and u guys can tell me what the problem is?

**Comment by Cooper133** [comment]
The same thing keeps on happening to me

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
