### ISSUE TITLE
Bloxstrap being flagged by Hyperion and crashing even if you uninstall

### ISSUE THREAD

**Issue by jagawatts** [pizzaboxer/bloxstrap#1891]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I installed bloxstrap, added a few fastflags, and when I opened the game, it instantly crashed and displayed a "A third party software is trying to interfere with the game." I uninstalled Roblox and Roblox Studio. I only fixed it after deleting the versions file in %appdata% 
![image](https://github.com/pizzaboxer/bloxstrap/assets/109644281/0d00f4a6-202e-49a2-80ba-7c0e2edc9668)

**Comment by jrhusker** [comment]
happening to me too

**Comment by jamesgarry1** [comment]
bloxstrap does not tampers with the roblox client, if you have something like x64dbg uninstall it

**Comment by kkkkkkkkkkkkkkkys** [comment]
bloxstrap indeed does tamper with the roblox client, the addition of resources eg. fonts and mods is now being detected by hyperion. no matter whatever pizzaboxer said it was against tos anyways - the server was raided yesterday but this could be on purpose
![image](https://github.com/pizzaboxer/bloxstrap/assets/112085554/8226cc0d-4cf4-479a-a584-65db14f11b7c)

**Comment by jamesgarry1** [comment]
Hey shut up krampus user!

**Comment by pizzaboxer** [comment]
> added a few fastflags

Okay, what did you add?

> the addition of resources eg. fonts and mods is now being detected by hyperion.

That's not what Hyperion detects. https://github.com/pizzaboxer/bloxstrap/wiki/Why-it's-not-reasonably-possible-for-you-to-be-banned-by-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
