### ISSUE TITLE
[BUG] An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Cookie1234567891011** [pizzaboxer/bloxstrap#1896]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Every time I try to reinstall it gives me "An exception occurred while running Bloxstrap" and it gives me and error code System.AggregateException: One or more errors occurred. (The file or directory is corrupted and unreadable. : 'C:\Users\user\AppData\Local\Bloxstrap\Versions\version-d6abc3b106a04c5c\RobloxPlayerBeta.exe')

[Inner Exception]
System.IO.IOException: The file or directory is corrupted and unreadable. : 'C:\Users\user\AppData\Local\Bloxstrap\Versions\version-d6abc3b106a04c5c\RobloxPlayerBeta.exe'

[Bloxstrap_20240531T225415Z.log](https://github.com/user-attachments/files/15519351/Bloxstrap_20240531T225415Z.log)

**Comment by pizzaboxer** [comment]
This is an issue with your system. I can't do anything about this. Do an SFC scan on your disk and see if it detects anything.
