### ISSUE TITLE
[BUG] Lag issue on BloxStrap

### ISSUE THREAD

**Issue by DamonYeo** [pizzaboxer/bloxstrap#1897]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hey, I set my FPS to 100 and when I joined other games it sometimes gave me 10-40 FPS is there any way to boost it up?
(On Bloxstrap)

**Comment by pizzaboxer** [comment]
Not in any ways that I'd officially recommend, no.
