### ISSUE TITLE
[BUG] Alright here we begin with the bug it crashesh everytime it open never want again will install bloxtrap

### ISSUE THREAD

**Issue by KirtilTsonev** [pizzaboxer/bloxstrap#1899]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\kiril\AppData\Local\Bloxstrap\Settings.json' is denied.
i can't still, fix it help me

**Comment by pizzaboxer** [comment]
Send the log file
