### ISSUE TITLE
rbxmultiple

### ISSUE THREAD

**Issue by ZorkIsEmo** [pizzaboxer/bloxstrap#19]
a option to turn off the prompt stoping you from running roblox if its already open, this would be helpfull for rbxmultiple users

**Comment by pizzaboxer** [comment]
I've just released [v1.4.4](https://github.com/pizzaboxer/bloxstrap/releases), which should now allow for this. Let me know if it works.

**Comment by ZorkIsEmo** [comment]
working wonderfully, and can confirm it works flawlessly with rbxmultiple. if you wanted to keep a "dont open new instance" option you could have the popup instead be "there is already a instance of roblox running, do you want to launch a new one?"

**Comment by pizzaboxer** [comment]
I probably won't add that as an *official* feature, especially since Multiple RBX already exists, but great to know that it works!
