### ISSUE TITLE
[BUG] FPS drop

### ISSUE THREAD

**Issue by Noorly** [pizzaboxer/bloxstrap#1900]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i used to get 700+ fps, now i'm barely getting 150. it started when roblox added the fps unlock feature, any fixes?
same game, same computer, less than a month between playing

![image](https://github.com/pizzaboxer/bloxstrap/assets/82147478/28c652ef-ee5c-4fc9-81d9-28d9a4edaae3)
![image](https://github.com/pizzaboxer/bloxstrap/assets/82147478/a1210150-f7a1-46b5-b6c2-b2dbba8e314c)

**Comment by Albinftw** [comment]
Same here the fps is fucked now i was getting like 500+ now it's like 120 to 180 even tried uninstalling bloxstrap but no roblox really fucked it up

**Comment by Mugetsu895** [comment]
There's nothing we can do 😔
