### ISSUE TITLE
[BUG] When joining the game the crash message pops up

### ISSUE THREAD

**Issue by 7v7n** [pizzaboxer/bloxstrap#1901]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I join a roblox game through bloxstrap, The crash popup appears, It doesn't close the game until I X it out or press "OK", when teleporting to a new place from within the game, Roblox closes.

![image](https://github.com/pizzaboxer/bloxstrap/assets/171415136/e4b32f98-4bc6-4d27-8db3-2b90068a9d16)

After uninstalling Bloxstrap and launching a Roblox game, there is no crash message, though I can't run roblox without Bloxstrap and am stuck with 20-30 fps at all times. I believe there is an FFlag that Byfron/Hyperion detects and crashes the game; Looking for this FFlag would be extremely time consuming and will most likely take hours to find which specific FFlag causes it due to the fact that I use alot of FFlags.

If there is an easier fix or the FFlag(s) that cause it are found hopefully the issue will go away.

**Comment by moyaimoment** [comment]
try removing the fastflag `DFFlagVideoCaptureServiceEnabled`

**Comment by 7v7n** [comment]
> try removing the fastflag `DFFlagVideoCaptureServiceEnabled`

thank you, that seems to have fixed the issue
