### ISSUE TITLE
[BUG] HUh error only with bloxstrap 💀 

### ISSUE THREAD

**Issue by Romasik1488** [pizzaboxer/bloxstrap#1902]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![RobloxPlayerBeta_p26OOdsSO8](https://github.com/pizzaboxer/bloxstrap/assets/171415396/a69ae436-acfd-49d9-880d-b2ab2cfb4bf5)
when i start roblox shows this error and clean temp and appdata in local folder delete roblox not work please fix this (if this our program error)

**Comment by moyaimoment** [comment]
try removing the fastflag `DFFlagVideoCaptureServiceEnabled`

**Comment by qualk** [comment]
Experienced the same issue and removing the FastFlag `DFFlagVideoCaptureServiceEnabled` worked for me.

**Comment by moyaimoment** [comment]
> Experienced the same issue and removing the FastFlag `DFFlagVideoCaptureServiceEnabled` worked for me.

i legit said that lol

**Comment by qualk** [comment]
> > Experienced the same issue and removing the FastFlag `DFFlagVideoCaptureServiceEnabled` worked for me.
> 
> i legit said that lol

And I confirmed that it worked for me.

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap? Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?
