### ISSUE TITLE
[BUG] bloxstrap takes a long time installing roblox what do i do?

### ISSUE THREAD

**Issue by riccardoo23171** [pizzaboxer/bloxstrap#1903]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

frist time downloading bloxstrap and when i try to install it, it gets stuck in the middle. i dont know what to do
![immagine_2024-06-02_005618182](https://github.com/pizzaboxer/bloxstrap/assets/171456222/cbbdb83a-3417-4b42-9307-99195fc52910)

**Comment by jamesgarry1** [comment]
did you apply a font during the installation process?

**Comment by riccardoo23171** [comment]
i didnt put in anything, was i supposed to put something and then install?

**Comment by jamesgarry1** [comment]
no but the reason why its stuck its prob because you have a outdated .NET

**Comment by riccardoo23171** [comment]
what does that mean

**Comment by DogeWasFound** [comment]
> what does that mean

install a newer version of the microsoft .NET runtime, [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.6-windows-x64-installer)

**Comment by riccardoo23171** [comment]
> install a newer version of the microsoft .NET runtime, [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.6-windows-x64-installer)

i downloaded it and installed that, and its still stuck like that

**Comment by moyaimoment** [comment]
It most likely wouldn't be a Bloxstrap issue, it states "Installing *Roblox*" so it could possibly be a Roblox issue

**Comment by riccardoo23171** [comment]
> It most likely wouldn't be a Bloxstrap issue, it states "Installing _Roblox_" so it could possibly be a Roblox issue

actually yea becouse whenever i install a roblox update (studio too) it just stops there and crashes with no error message, i think its that

**Comment by riccardoo23171** [comment]
well i got it working so i think its all fixed
