### ISSUE TITLE
fps is capped at the roblox maximum frame rate setting

### ISSUE THREAD

**Issue by RobloxFortniteMaster** [pizzaboxer/bloxstrap#1904]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my fps is capped at the maximum frame rate setting that roblox has and isnt capped to my bloxstrap fps setting

**Comment by vezqn** [comment]
same here

**Comment by pizzaboxer** [comment]
What FPS setting do you have configured in Bloxstrap?

**Comment by PoloGoSolo** [comment]
Yeah mine is doing the same thing

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
