### ISSUE TITLE
bloxstrap not opening

### ISSUE THREAD

**Issue by trulywes** [pizzaboxer/bloxstrap#1905]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to launch a game itll say opening bloxstrap but it never launches
and whenever i open bloxstrap a ton of "eurotrucks2" opens and freezes my task manager which im assuming is the issue

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
