### ISSUE TITLE
[BUG]Fps Decrease

### ISSUE THREAD

**Issue by naygel0g** [pizzaboxer/bloxstrap#1906]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[BUG]My roblox used to be over 60 FPS. After the recent update (Roblox Official FPS Unlocker), I am now at 30-40 FPS. Is there any way to fix this? Is this a roblox issue?

**Comment by naygel0g** [comment]
Without Bloxstrap, it is  way smoother for some reason,

**Comment by Bloonkyyyy** [comment]
Well you broke some setting.

**Comment by naygel0g** [comment]
Like what?

**Comment by naygel0g** [comment]
> Well you broke some setting.

Like what?

**Comment by moyaimoment** [comment]
> Like what?

You didn't break anything it's more of a roblox issue.

**Comment by pizzaboxer** [comment]
> Without Bloxstrap, it is way smoother for some reason,

In what way? What does your flag configuration look like?

**Comment by naygel0g** [comment]
> > Without Bloxstrap, it is way smoother for some reason,
> 
> In what way? What does your flag configuration look like?

FPS is smoother,

**Comment by pizzaboxer** [comment]
> FPS is smoother.

https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration
