### ISSUE TITLE
[BUG]  The "Force Future Lighting" Fastflag not working

### ISSUE THREAD

**Issue by FerdiNah** [pizzaboxer/bloxstrap#1908]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've set the "Preferred Lighting Technology" to Future and tested a lot of games, and the lighting method still doesn't apply to games.

**Comment by pizzaboxer** [comment]
How can you tell? If you press Shift+F2, what does it show under lighting technology?

**Comment by FerdiNah** [comment]
Nevermind. It's fixed now.
