### ISSUE TITLE
bloxstrap not working

### ISSUE THREAD

**Issue by fastflagsarethebest** [pizzaboxer/bloxstrap#1909]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i was using bloxstrap when suddenly my fast flags wasnt working can u fix it?

**Comment by pizzaboxer** [comment]
See sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter
