### ISSUE TITLE
i cant run roblox

### ISSUE THREAD

**Issue by luvluce** [pizzaboxer/bloxstrap#1913]
when i try to join a game it comes up saying that roblox has crashed

**Comment by luvluce** [comment]
![bloxstrap](https://github.com/pizzaboxer/bloxstrap/assets/171514026/dae05339-57ba-461b-a0e3-ee6013dd0742)

**Comment by moyaimoment** [comment]
try removing the fastflag `DFFlagVideoCaptureServiceEnabled`

**Comment by pizzaboxer** [comment]
Does this happen only when using Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
