### ISSUE TITLE
i cant open launcher with bronswer

### ISSUE THREAD

**Issue by umte1225** [pizzaboxer/bloxstrap#1914]
i want the bloxstap with bronswer but its not opening with bronswer its opens roblox app

**Comment by moyaimoment** [comment]
browser* you should get an autocorrect

also go to your Bloxstrap settings (Click the Windows Key and type `Bloxstrap Menu` and open it) and make sure it's set so the Roblox App is off.

**Comment by pizzaboxer** [comment]
Can you please better explain the problem?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
