### ISSUE TITLE
Error occuring when after installing bloxtrap

### ISSUE THREAD

**Issue by GOfdrey** [pizzaboxer/bloxstrap#1916]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

after I click install on bloxtrap menu after it installed it always says an exception occurred while running bloxtrap
![Screenshot (6008)](https://github.com/pizzaboxer/bloxstrap/assets/171663362/2f4c58d5-d974-4486-af7b-3850fffa7dad)

**Comment by brajesh00** [comment]
how to fix

**Comment by X1kera** [comment]
1. "Have you tried opening the Bloxstrap installer with 'Run as Administrator'? Your error message indicates: 
[ "...Bloxstap is denied" which suggests that you don't have permission to execute the script it uses to download Roblox. ]

2. Perhaps your User Account Control (UAC) settings are configured to 'Never Notify me when:'.
To find this setting, open the Windows search and type "UAC".
You should see an option like "Change User Account Control settings".
If your UAC is set to "Never Notify"' consider changing it to either:
"Notify me only when apps try to make changes to my computer (do not dim my desktop)"
or
"Notify me only when apps try to make changes to my computer (default)"

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
