### ISSUE TITLE
[BUG] Multi Instance sometimes Doesn't work

### ISSUE THREAD

**Issue by Indywasnotaken** [pizzaboxer/bloxstrap#1918]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It's annoying that this happened, After leaving the game while there another account is playing on another window the multi instance sometimes doesn't work So please fix this and thanks you if you did

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
