### ISSUE TITLE
On Bloxstrap, I use 240 FPS on FastFlags but it puts me to 50-60 FPS. What do I do to fix it? [BUG] 

### ISSUE THREAD

**Issue by redkhiem** [pizzaboxer/bloxstrap#1919]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image_2024-06-04_201427174](https://github.com/pizzaboxer/bloxstrap/assets/171751213/64abb851-048a-4465-b551-51efc5dee383)

**Comment by MrPIRY** [comment]
yeah other people are having the same problem but thay say putting FFlagTaskSchedulerLimitTargetFpsTo2402 to False fixes it but it hasnt for me i dont know

**Comment by pizzaboxer** [comment]
Does it happen only when setting it to 240 and above?

**Comment by redkhiem** [comment]
No, When I add it to 100 it doesn't work either.

**Comment by pizzaboxer** [comment]
Do you ever actually reach 60? The screenshot only shows you at 41.

**Comment by redkhiem** [comment]
Yes, I just cropped it pretty late.

**Comment by pizzaboxer** [comment]
What about in the Roblox escape menu? What's the limit in there set to?

**Comment by redkhiem** [comment]
The limit is 240.

**Comment by pizzaboxer** [comment]
That sounds like you're being limited externally by something. Can you confirm that it happens without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

If it still happens, then see this: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter

**Comment by yourecursed** [comment]
I don't know if this applies to anyone here, but it worked for me. if you have avast antivirus, try removing it and see if your frames get better
