### ISSUE TITLE
Roblox does not want to release at all.

### ISSUE THREAD

**Issue by TechMan06** [pizzaboxer/bloxstrap#192]
This issue has started yesterday, however it was only happening with the zwin and LIVE channels, however today it has been happening with all channels with the exception of "Zlive" (Which I have tested today and is working fine).

Every time I try to start a game using bloxstrap, one of these happen:
- Either the game doesn't start at all.
- Bloxstrap gets to the "Upgrading Roblox" screen, until suddenly it gets to this error:
![image](https://user-images.githubusercontent.com/132509305/236316789-f2fb4bed-3955-4a18-a32d-c6194bf04833.png)

As I have said, so far the only channel that is still working (and that I tested) is "Zlive"

Here are all logs from today and yesterday:
[Bloxstrap_20230504T200726Z.zip](https://github.com/pizzaboxer/bloxstrap/files/11401141/Bloxstrap_20230504T200726Z.zip)

A friend of mine may have already forwarded this issue for you but I didn't get any updates regarding it.
I'm currently using Windows 10, compilation 22H2

**Comment by pizzaboxer** [comment]
That's an SSL error. I don't really know what to do about this, because this has to be influenced by some OS-wide or network-wide configuration. See this: https://github.com/dotnet/runtime/issues/43682. This is something that I can't fix because it's not in my control.

**Comment by TechMan06** [comment]
Hi, sorry for taking a while to reply, I lack free time recently. I don't know how the dotnet link you sent could help me in my situation. Though I am able to access the link of the zip file you sent, why?

I also do not know what setting could be triggering this, however all channels on Bloxtrap no longer work, and I suppose I will be unable to play roblox permanently if I can't figure out how to fix this.

**Comment by pizzaboxer** [comment]
> I don't know how the dotnet link you sent could help me in my situation.

It was supposed to show someone else having the same problem at the framework level, as well as people talking about how it's an OS problem...
