### ISSUE TITLE
System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by ShinnyGamingYT** [pizzaboxer/bloxstrap#1920]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i dont know but i said The Signature does not match!

**Comment by willgithub143** [comment]
why i cant open blockstrap

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
