### ISSUE TITLE
[BUG] fps down to 30 after roblox new fps selecting feature

### ISSUE THREAD

**Issue by Mongoose0525** [pizzaboxer/bloxstrap#1921]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

joined server fps fell to 30, i have normal laptop set

**Comment by pizzaboxer** [comment]
Did you check to see what your framerate is set to in the escape menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
