### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MaxBigBrain** [pizzaboxer/bloxstrap#1922]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240605T204408Z.log](https://github.com/user-attachments/files/15596434/Bloxstrap_20240605T204408Z.log)

**Comment by moyaimoment** [comment]
thanks for telling what is wrong with your Bloxstrap very helpful

**Comment by pizzaboxer** [comment]
One-time bad request
