### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.[BUG] 

### ISSUE THREAD

**Issue by isacxrw** [pizzaboxer/bloxstrap#1923]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied. 
![imagem_2024-06-05_210954165](https://github.com/pizzaboxer/bloxstrap/assets/165173587/048f0e22-b935-47cf-b88d-9fb0590f6d4d)

**Comment by moyaimoment** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-error-when-trying-to-reinstall-Bloxstrap
https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-when-trying-to-remove-a-custom-font
figure out which one is yours
