### ISSUE TITLE
Roblox settings reset after i restart roblox

### ISSUE THREAD

**Issue by Tomloyo** [pizzaboxer/bloxstrap#1924]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Every time my roblox crashes or i just close it i have to join and set all settings manually:
Graphics quality on 21
Performance stats to off
UI Navigation tool to off
Volume to 4
etc.

**Comment by pizzaboxer** [comment]
Have you enabled the option to disable the desktop app?

**Comment by Tomloyo** [comment]
> Have you enabled the option to disable the desktop app?

No i didn't cause it does nothing only making my roblox crash after leaving.

**Comment by pizzaboxer** [comment]
Can you clarify that this happens only when using Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Tomloyo** [comment]
Sorry it was roblox error
![изображение](https://github.com/pizzaboxer/bloxstrap/assets/95727539/273bbee8-2fb0-4da1-a69c-5f0b64ece6cc)
