### ISSUE TITLE
[BUG] it wont work even when i downloaded desktop net thing

### ISSUE THREAD

**Issue by whatismewe** [pizzaboxer/bloxstrap#1925]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-06-05 201304](https://github.com/pizzaboxer/bloxstrap/assets/171893381/6430229c-96b2-4a4e-8a21-dc1f5811ff16)

help

**Comment by moyaimoment** [comment]
why did you download it multiple times

**Comment by pizzaboxer** [comment]
What happens when you try to open it?
