### ISSUE TITLE
 Trying to open roblox in every way, it does not open in any way, bloxstrap stays stuck in the background

### ISSUE THREAD

**Issue by UnLuckKing** [pizzaboxer/bloxstrap#1926]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Trying to open roblox in every way, it does not open in any way, bloxstrap stays stuck in the background

**Comment by Faf4a** [comment]
Same issue here.

After a while it says "Unexpected error [...] Roblox has to quit".


<details>
<summary>Details</summary>
Edition Windows 11 Pro <br />
Version 24H2 <br />
OS build 26120.751 <br /> <br />

Bloxstrap Version 2.5.4

FastFlags
DFFlagTextureQualityOverrideEnabled True
DFIntTextureQualityOverride 3
</details>

**Comment by Faf4a** [comment]
Update: fixed it by downgrading my graphics driver

**Comment by SneakyJaden05** [comment]
Faf4a which driver did you use? and was it nvidia rtx? im getting the same problem

**Comment by SneakyJaden05** [comment]
> Update: fixed it by downgrading my graphics driver

Faf4a which driver did you use? and was it nvidia rtx graphics card? im getting the same problem
