### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hanshu1202** [pizzaboxer/bloxstrap#1927]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240607T053443Z.log](https://github.com/user-attachments/files/15710739/Bloxstrap_20240607T053443Z.log)
System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.

**Comment by pizzaboxer** [comment]
Does this happen every time you launch?

**Comment by radith866** [comment]
i got that error too
