### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Bloxstrap\Logs\Bloxstrap_20240607T113900Z.log' is denied.

### ISSUE THREAD

**Issue by WHALLPHER** [pizzaboxer/bloxstrap#1929]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cant play roblox

**Comment by moyaimoment** [comment]
why is bloxstrap in your program files

**Comment by pizzaboxer** [comment]
Reinstall Bloxstrap without changing its install location.
