### ISSUE TITLE
[REQ] Black Theme 

### ISSUE THREAD

**Issue by Findyourlimit** [pizzaboxer/bloxstrap#1931]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Black theme for oled displays
![Screenshot 2024-06-07 181343](https://github.com/pizzaboxer/bloxstrap/assets/149321296/aeaf74ed-3752-4fdf-8de3-f5b1eaa1e19b)

**Comment by pizzaboxer** [comment]
The only reason you'd have a black theme for OLED displays is to save battery. You're not going to be having the menu open long enough for this to be meaningful. This is pointless.
