### ISSUE TITLE
uhm, arm64?

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [pizzaboxer/bloxstrap#1932]
Well in the download page it says this:![Screenshot_20240607-210646_Chrome.jpg](https://github.com/pizzaboxer/bloxstrap/assets/144390627/d80a42ef-980f-4659-9eaa-0dd8bed92604)

Does that mean it CAN be played on a raspberry pi with wine?(9.0 and forwards)

**Comment by moyaimoment** [comment]
That is a fake website, do not download from there. Use the GitHub.

**Comment by pizzaboxer** [comment]
That website isn't made by us.
