### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by davidverho** [pizzaboxer/bloxstrap#1937]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i tried to open bloxstrap but when i opened it, it did not open roblox i have uninstalled and reinstalled and everything

**Comment by pizzaboxer** [comment]
So what did it do? What did it open?

**Comment by fl8tio** [comment]
@pizzaboxer the issue is with msi afterburner with riva tuner, after i closed it my bloxstrap worked perfectly, idk if its because its outdated or what. I made an account purely to say this.

**Comment by AmateurProgrammerishere** [comment]
> @pizzaboxer the issue is with msi afterburner with riva tuner, after i closed it my bloxstrap worked perfectly, idk if its because its outdated or what. I made an account purely to say this.

well this is roblox fault not pizzaboxer an anti cheat called byfron block these programs.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
