### ISSUE TITLE
[BUG] Roblox crashes due to Bloxstrap forcing the DFIntTaskSchedulerTargetFps flag to be present

### ISSUE THREAD

**Issue by sv-du** [pizzaboxer/bloxstrap#1938]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bug is self-explainatory, this flag causes Roblox to crash (for me, just when I leave a game, but for others, makes Roblox unplayable)

**Comment by pizzaboxer** [comment]
> Bug is self-explainatory, this flag causes Roblox to crash

How do you know that's the one causing it? Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by sv-du** [comment]
> > Bug is self-explainatory, this flag causes Roblox to crash
> 
> How do you know that's the one causing it? Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

I tested with and without the flag and it crashed with the flag and worked fine without it

[Settings.json](https://github.com/user-attachments/files/15753109/Settings.json)
[State.json](https://github.com/user-attachments/files/15753110/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/15753111/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
That doesn't really make any sense because the flag is internally set to zero by default too. Having it set to zero shouldn't be causing anything. Are you sure of this?

**Comment by sv-du** [comment]
> That doesn't really make any sense because the flag is internally set to zero by default too. Having it set to zero shouldn't be causing anything. Are you sure of this?

In my fork of Bloxstrap where I removed the code that forced this flag, I no longer got any errors/crashes, so I'd quite sure that this flag is causing it. Also, since Roblox has added FPS changing from the game menu, removing this is already on the to-do list, no?

**Comment by pizzaboxer** [comment]
> removing this is already on the to-do list, no?

Not currently, because it's still the only way to set a specific framerate limit, and only way to set one below 60.

**Comment by sv-du** [comment]
> > removing this is already on the to-do list, no?
> 
> Not currently, because it's still the only way to set a specific framerate limit, and only way to set one below 60.

Could you make it where if the user doesn't configure the setting in bloxstrap, it just doesn't add the flag?

**Comment by pizzaboxer** [comment]
> Could you make it where if the user doesn't configure the setting in bloxstrap, it just doesn't add the flag?

Yeah, we should have done that a long time ago. Noted.
