### ISSUE TITLE
Cannot join games - error 268 (Kicked due to unexpected client behavior)

### ISSUE THREAD

**Issue by carter0nline** [pizzaboxer/bloxstrap#194]
![image](https://user-images.githubusercontent.com/83525455/236320284-5a8edb54-5f32-401a-859d-44f8bdd747fc.png)
Restarting my PC did nothing

**Comment by pizzaboxer** [comment]
Go to #193 since that person is reporting the same issue.

**Comment by carter0nline** [comment]
Oh, didn't see that
