### ISSUE TITLE
Project Delta ESP.

### ISSUE THREAD

**Issue by Yeano-rgb** [pizzaboxer/bloxstrap#1941]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Project delta made a new anti cheat that whenever ctrl+f8 is pressed (same as to activate ESP 1st stage) It starts to lag SO MUCH your FPS drops to 10 and you get kicked, and even if you dont its UNPLAYABLE so i suggest

**Comment by Yeano-rgb** [comment]
I suggest making it so that there is an option to change the starting button to ctrl+f7 or alt+f7-f8 so it cant be detected

**Comment by nodomw** [comment]
ehhhhhhh? 🤣

**Comment by GEOsaidi** [comment]
yeb, but how to change buttons? testing on other games and esp dont works there too for some reason

**Comment by bluepilledgreat** [comment]
this is not a cheating tool bud
