### ISSUE TITLE
Clipping with xbox game bar

### ISSUE THREAD

**Issue by drggflr** [pizzaboxer/bloxstrap#1942]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hey, so i have this issue and its so annoyingggggggggg. I clip with xbox game bar. And when i use alt+enter with bloxstrap the clips are frozen and its so annoying anyone know how to fix i tried everything

**Comment by moyaimoment** [comment]
This isn't Windows tech support and this is your 3rd post (including the two on Discord), quit asking.

**Comment by ShadowCodeX-debug** [comment]
Alt+Enter or Exclusive Fullscreen takes control and captures directly to your display but, since only the game is being captured, overlays will not work.

**Comment by pizzaboxer** [comment]
> And when i use alt+enter with bloxstrap the clips are frozen

Then don't use it. That's what using exclusive fullscreen does.
