### ISSUE TITLE
[BUG] roblox limiting my cpu 

### ISSUE THREAD

**Issue by hlosiiis** [pizzaboxer/bloxstrap#1943]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This issue isnt bloxstrap related, but i just need to know why roblox is doing this.
So Roblox is just limiting my cpu to 40-50 precent usage rate which leaves me with 40-50 fps. Its just roblox which does that since other games are fine. Please give me a explenation since this has been really annoying. This has started to happen after the recent roblox update where they uncapped the fps. I use to run games on 80fps and i still run R6 siege on 100fps on high graphics. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/109919700/9bf75d1b-9b4a-4ff6-8abc-133a285c6329)

**Comment by pizzaboxer** [comment]
I don't have an explanation for you unfortunately. This just isn't the best place to ask.
