### ISSUE TITLE
Idk what happend

### ISSUE THREAD

**Issue by Alennxxx** [pizzaboxer/bloxstrap#1944]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

im not no 20 year old who is smart with pcs so i dont know whats happening 
![Screenshot 2024-06-10 190100](https://github.com/pizzaboxer/bloxstrap/assets/172326286/09d098ed-2d74-4185-89d1-36e83e27fa97)

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
