### ISSUE TITLE
[BUG] not able to hide gui

### ISSUE THREAD

**Issue by winged3** [pizzaboxer/bloxstrap#1945]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cant disable/ hide ui 
plz fix

**Comment by pizzaboxer** [comment]
Are you given options for hiding GUIs at the bottom of the escape menu?

**Comment by winged3** [comment]
i had my adm software hotkeys was on had to change it 
sorry for that
