### ISSUE TITLE
Adding A Custom Death Sound Option[REQ] 

### ISSUE THREAD

**Issue by VoidTheNotSmart** [pizzaboxer/bloxstrap#1946]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I personally believe that custom death sounds would be a good feature for Blox Strap, it would be more of a quality of life feature overall, but it would also be extremely nice for you(as in the user) to be able to use a custom death sound on roblox.

**Comment by moyaimoment** [comment]
just replace the ouch.ogg file in `%LocalAppData%\Bloxstrap\Modifications\` go into the sounds folder then replace the ouch.ogg

**Comment by pizzaboxer** [comment]
^

https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

If you're talking about making it easier to do so, I agree, we plan to make that happen soon.

**Comment by Enzzo453** [comment]
Insert This Sound:
@pizzaboxer , add a Spidey shopping Web as Roblox Death Sound, Please?
