### ISSUE TITLE
[BUG] none of my settings and fastflags will work

### ISSUE THREAD

**Issue by Alexlimixone** [pizzaboxer/bloxstrap#1947]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

somehow my settings and fastflags wont work, i was trying to do this one thing where you could turn up the render distance without turning up the graphics, i did everything right, still wont work, i tried to use the JSON file, said it was invalid, if i could, may i have a solution for this? or possibly a JSON file i could use..

**Comment by pizzaboxer** [comment]
> i tried to use the JSON file, said it was invalid

Okay, what was the error?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
