### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden). [BUG] 

### ISSUE THREAD

**Issue by ikkqqstudio** [pizzaboxer/bloxstrap#1949]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i open *play roblox* to play and i got error popup like this. *System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).* can you fix this

**Comment by bluepilledgreat** [comment]
Send the log file

**Comment by ikkqqstudio** [comment]
[Bloxstrap_20240611T134410Z.log](https://github.com/user-attachments/files/15788890/Bloxstrap_20240611T134410Z.log)
here

**Comment by bluepilledgreat** [comment]
> [Bloxstrap_20240611T134410Z.log](https://github.com/user-attachments/files/15788890/Bloxstrap_20240611T134410Z.log) here

A fix to this is in the works.

**Comment by ikkqqstudio** [comment]
is it solved or should i uninstall bloxstrap

**Comment by pizzaboxer** [comment]
> is it solved or should i uninstall bloxstrap

You have two options:
1. Switch back to the stock launcher temporarily: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
2. Follow this fix: https://github.com/pizzaboxer/bloxstrap/wiki/Launching-from-different-accounts-always-forces-a-Roblox-upgrade

**Comment by ikkqqstudio** [comment]
> > is it solved or should i uninstall bloxstrap
> 
> You have two options:
> 
> 1. Switch back to the stock launcher temporarily until we release an update: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
> 2. Follow this fix: https://github.com/pizzaboxer/bloxstrap/wiki/Launching-from-different-accounts-always-forces-a-Roblox-upgrade

thanks

**Comment by terlexory** [comment]
> > is it solved or should i uninstall bloxstrap
> 
> You have two options:
> 
>     1. Switch back to the stock launcher temporarily until we release an update: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
> 
>     2. Follow this fix: https://github.com/pizzaboxer/bloxstrap/wiki/Launching-from-different-accounts-always-forces-a-Roblox-upgrade

Hey!

I'm having the same problems as the OP here, this doesn't seem to work with me tho.
Can you help me with the same problem?

**Comment by DergPH** [comment]
oh hi terlexory and yeah im having the same issue here now it started today

**Comment by kkeyy-hash** [comment]
got the same issue gg

**Comment by Paramythian** [comment]
Is there any way to fix this without returning to the latest version? i dont want to lose the multi-instance function

**Comment by jaysuna** [comment]
having the same issue here, im using 2.9.0 (latest version) any fixes?

**Comment by FluffyWolfLord** [comment]
im having this issue now any idea what why its back?

**Comment by bv662468-puntocom** [comment]
no puedo iniciar roblox con bloxtrao

**Comment by IMJOHNITTIRA** [comment]
i have this issue what should i do?
