### ISSUE TITLE
Notification Typo related to ReShade

### ISSUE THREAD

**Issue by builtbyvys** [pizzaboxer/bloxstrap#195]
## Error 
I received this error after trying to run ROBLOX with Bloxstrap while I still used ReShade before ROBLOX released 64bit officially, breaking ReShade.

Image:
![Image](https://user-images.githubusercontent.com/92237104/236323511-a74c0f24-818a-498d-86c0-27331d078b7a.png)

## How to Reproduce
- Had ReShade previously installed
- Run a roblox game
- Encounter the Typo

### Additional Comment(s)
Please fix this 🥺🙏

**Comment by pizzaboxer** [comment]
mfw
