### ISSUE TITLE
[BUG] Response 403 on startup

### ISSUE THREAD

**Issue by butterdogceo** [pizzaboxer/bloxstrap#1958]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I start Roblox via Bloxstrap, I get "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)." I've ensured this only happens on Bloxstrap, not on any official Roblox launchers.
![image](https://github.com/pizzaboxer/bloxstrap/assets/100174775/fe783cf1-1ceb-44af-8016-1225e4ba7f55)
Log file: [Bloxstrap_20240612T233534Z.log](https://github.com/user-attachments/files/15811985/Bloxstrap_20240612T233534Z.log)

**Comment by pizzaboxer** [comment]
Known bug. You can temporarily fix it for the meantime by either: 
- Switching back to the original launcher until the next Bloxstrap update comes out - https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
- Following these instructions: https://github.com/pizzaboxer/bloxstrap/wiki/Launching-from-different-accounts-always-forces-a-Roblox-upgrade

**Comment by LuauDev** [comment]
thank you i just opened roblox from another browser directly to a game with diff acc and it worked
@pizzaboxer
