### ISSUE TITLE
[BUG] Annoying crash when you click leave

### ISSUE THREAD

**Issue by WertyTT4** [pizzaboxer/bloxstrap#1959]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever i click "leave game" it gives me the classic "roblox crashed, were sorry" I know its not really much of a issue since if anyone else was getting this bug, you were probably about to leave anyways, i'm pretty sure "disable desktop app" is the reason why, because when i leave without the option on, it doesn't display the error, I know at best, its a inconvenience but i still want a way to fix this little bug.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-when-leaving-a-game
