### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Iheartcats24** [pizzaboxer/bloxstrap#1960]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it doesnt work like its not loading my cursor i picked, the oof sound is not working and the esc menu is back to normal roblox one

**Comment by pizzaboxer** [comment]
Is this still happening?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
