### ISSUE TITLE
[BUG] roblox crashing

### ISSUE THREAD

**Issue by pfvyie** [pizzaboxer/bloxstrap#1961]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

whenever i add a custom font, my roblox tend to crash but when i remove the font everything works completely fine. im not sure whether its the font that i chose or something but please help me find out about this issue

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pfvyie** [comment]
yes, but the issue here is only the fonts as i tried other bloxstrap things and they all work perfectly fine example like the cursor etc, its only when i add in the fonts then my roblox will crash

**Comment by pizzaboxer** [comment]
> but the issue here is only the fonts

Are you sure you read this section?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/86907315-faec-4b03-9d4a-a29805282fc6)

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
