### ISSUE TITLE
[BUG] roblox crash

### ISSUE THREAD

**Issue by Muhammad61169** [pizzaboxer/bloxstrap#1962]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

roblox warning crash when i ignore it roblox can still run but when i press the ok button on the warning it makes roblox exit

https://github.com/pizzaboxer/bloxstrap/assets/130255455/7391f665-a839-451d-bf88-153a6f7bd149

**Comment by Muhammad61169** [comment]
![Screenshot 2024-06-13 125936](https://github.com/pizzaboxer/bloxstrap/assets/130255455/0b6f6545-fc8f-43da-9963-de112fd95525)

**Comment by Muhammad61169** [comment]
@pizzaboxer i need ur help

**Comment by pizzaboxer** [comment]
Does it happen when you join or leave a game?

**Comment by Muhammad61169** [comment]
> Does it happen when you join or leave a game?

yes always

**Comment by pizzaboxer** [comment]
The video won't load for me, so I'll assume it happens only when you join. Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
