### ISSUE TITLE
[REQ] Allow us to use roblox's official fps unlocker

### ISSUE THREAD

**Issue by Vlad55432** [pizzaboxer/bloxstrap#1963]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

As roblox's official fps unlocker I mean this
![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/38476472-f4db-4994-ab79-1886a2bffeca)
As for now, I use dirty hack, so bloxstrap don't touches clientsettings, if there's no DFIntTaskSchedulerTargetFps fflag or it's just low than 100.
![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/127e8e79-5b85-4594-a7b4-f74b7fab0703)

**Comment by bluepilledgreat** [comment]
Just set it to 0 if you want to entirely disable it. You don't have to do that.

**Comment by Vlad55432** [comment]
> Just set it to 0 if you want to entirely disable it. You don't have to do that.

Oh damn. Didn't know that, thx!
