### ISSUE TITLE
Everytime i open up Roblox with bloxstrap it crashes or it gives me a white screen why is that?[BUG] 

### ISSUE THREAD

**Issue by Abdallah799** [pizzaboxer/bloxstrap#1966]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i re installed bloxstrap to see what problem it was but nothing was there

**Comment by pizzaboxer** [comment]
I'm only here to help with Bloxstrap problems, I can't help you much with this beyond just telling you to read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch, sorry.
