### ISSUE TITLE
[BUG] Health bar bug started disappearing

### ISSUE THREAD

**Issue by Blockysol** [pizzaboxer/bloxstrap#1967]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It starts to disappear more often than usual

**Comment by ryanthecomic** [comment]
im also having the same problem, and its different from the prescedent issues, where the health bar and the escape menu would disapear

**Comment by ryanthecomic** [comment]
i just played a game lobby that 4 people declared they couldnt see their own hp, it may be a Roblox problem

**Comment by pizzaboxer** [comment]
> where the health bar and the escape menu would disapear

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Confirmed as a Roblox bug. https://devforum.roblox.com/t/the-health-bar-has-stopped-working/3022420
