### ISSUE TITLE
[BUG] Bloxstrap not opening or not running correctly

### ISSUE THREAD

**Issue by redkhiem** [pizzaboxer/bloxstrap#1968]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/171751213/b9878cfb-c28a-4a2f-aa40-ca1e4ed53bff)

**Comment by pizzaboxer** [comment]
Closing this unless this issue happens again on the latest version
