### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Anoynonmous** [pizzaboxer/bloxstrap#1969]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.InvalidOperationException: 'ContentControl' TargetType does not match type of element 'DataGridColumnFloatingHeader'.

**Comment by pizzaboxer** [comment]
Duplicate of #1231
