### ISSUE TITLE
RCO FFlags

### ISSUE THREAD

**Issue by TheRealBooWasHere** [pizzaboxer/bloxstrap#197]
It would be nice if you could add the RCO FFlags and have them updated as well or make RCO detect roblox (make it compatible), because when I use Bloxstrap, RCO doesn't detect roblox and I can't use the FFlags they have, it would be much appreciated.
You could also make a Discord server to make communication/support better, because some people don't have GitHub account and it would make things easier

**Comment by pizzaboxer** [comment]
See #121.
