### ISSUE TITLE
[BUG] my healthbar wont show and im frustated rn.

### ISSUE THREAD

**Issue by CelestialPalace** [pizzaboxer/bloxstrap#1970]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i get hit in jjs my health bar wont show

**Comment by Legend-we** [comment]
Just use Chrome UI, it fixes the bug.

**Comment by CelestialPalace** [comment]
> Just use Chrome UI, it fixes the bug.

wat is chrome ui

**Comment by pizzaboxer** [comment]
> when i get hit in jjs my health bar wont show

Have you confirmed this happens only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by LegendMel** [comment]
No, this is a roblox bug.

**Comment by pizzaboxer** [comment]
Confirmed as a Roblox bug. https://devforum.roblox.com/t/the-health-bar-has-stopped-working/3022420
