### ISSUE TITLE
Make that all pop-ups have an "don't show again" option. It is bad when it shows again and again.

### ISSUE THREAD

**Issue by cuyamen** [pizzaboxer/bloxstrap#1971]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

just make a way to remove pop ups or an option to not show again.
![Captura de tela 2024-06-14 113436](https://github.com/pizzaboxer/bloxstrap/assets/172826564/641be7e2-ae9a-4b7b-abe8-1df8d26e932e)

![Captura de tela 2024-06-14 113657](https://github.com/pizzaboxer/bloxstrap/assets/172826564/1c1d633c-940b-4846-9c1f-8b7c78c5e825)

**Comment by pizzaboxer** [comment]
Doesn't apply to v2.6.0
