### ISSUE TITLE
[REQ] Add an option to disable the desktop app

### ISSUE THREAD

**Issue by SmolMiataYT** [pizzaboxer/bloxstrap#1972]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It would be great if you could disable the desktop app in the FastFlags. I think we all watched videos on how to disable it but they all seem to be fake. If people could disable it just by using Bloxstrap. Thank you for reading, sure do hope you and your team can make it real ;)

**Comment by pizzaboxer** [comment]
It's right there?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/d6197907-a30a-49a8-8faa-0249aa264de1)

**Comment by SmolMiataYT** [comment]
Thanks! My version was just outdated... I reinstalled it and now I disabled it! :D

**Comment by SmolMiataYT** [comment]
One other thing, is it possible to change the coregui elements to the pre-metaverse ones?
