### ISSUE TITLE
[BUG] Whenever I try to play a roblox game using bloxstrap, I get this error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by heyimskipper** [pizzaboxer/bloxstrap#1975]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240614T192039Z.log](https://github.com/user-attachments/files/15842625/Bloxstrap_20240614T192039Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
