### ISSUE TITLE
[BUG] an exception occurred while running bloxstrap [#403}

### ISSUE THREAD

**Issue by SomeProblems** [pizzaboxer/bloxstrap#1976]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
[Bloxstrap_20240614T192555Z.log](https://github.com/user-attachments/files/15842692/Bloxstrap_20240614T192555Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
