### ISSUE TITLE
[BUG]It says  "Bloxstrap exception: An exception occured while running bloxstrap"

### ISSUE THREAD

**Issue by 91Radars** [pizzaboxer/bloxstrap#1977]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It told me to report this exception through github or discord chat.
The discord server link provided is not functioning: 

![awer](https://github.com/pizzaboxer/bloxstrap/assets/172849215/389506a6-fd42-43b5-89fb-9f884d270b1c)

THE REAL PROBLEM IS THAT: 
![waesrtd](https://github.com/pizzaboxer/bloxstrap/assets/172849215/782451e1-35c5-4bd5-99bb-69e21361d21d)

It asks me to attach the log file so here is the log file;
[Bloxstrap_20240614T192705Z.log](https://github.com/user-attachments/files/15842716/Bloxstrap_20240614T192705Z.log)

And uh if something else im missing please notify me and solve this problem as fast as you could :> 
Thanks!

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
