### ISSUE TITLE
Support for DXVK

### ISSUE THREAD

**Issue by ThatOneOcto** [pizzaboxer/bloxstrap#198]
It would be super cool if you could add a feature or slider whatever that adds dxvk cause the vulkan roblox has sucks

https://www.reddit.com/r/pcgaming/comments/mlfcsc/a_guide_to_dxvk_on_windows/ if you need help for windows

**Comment by pizzaboxer** [comment]
The only problem is that this seems to work very similarly to how ReShade works, and as you know I've had to remove that because of complications with the new Hyperion update. Have you verified if it works?

**Comment by ThatOneOcto** [comment]
I think that the anticheat blocks it because if I try it, it doesn't launch

**Comment by pizzaboxer** [comment]
Yeah, I figured so. Oh well.
