### ISSUE TITLE
[BUG] Bloxtrap issue, an exception occured while running Bloxtrap 403 ( Forbidden ) 

### ISSUE THREAD

**Issue by g0230d** [pizzaboxer/bloxstrap#1981]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/172849715/9db657a5-cdb9-434a-9bd8-e6eb72ac3c08)

**Comment by sv-du** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox

**Comment by bluepilledgreat** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
This is fixed in 2.6.0, which should hopefully soon release.
