### ISSUE TITLE
[BUG]  403 (Forbidden)

### ISSUE THREAD

**Issue by Zagmeeboi** [pizzaboxer/bloxstrap#1982]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i tried opening up bloxstrap, it showed this error System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by hayderhadexplodedearlier** [comment]
exact same issue here

**Comment by shrektz** [comment]
me too

**Comment by tekkdat365** [comment]
me aswell

**Comment by bluepilledgreat** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
This is fixed in 2.6.0, which should hopefully soon release.
