### ISSUE TITLE
[BUG] bloxstrap is not opening and it keeps saying its a forbidden file, what do i do?

### ISSUE THREAD

**Issue by ThatDudeNymbol** [pizzaboxer/bloxstrap#1984]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it said it was a execption 
![bandicam 2024-06-14 16-17-40-261](https://github.com/pizzaboxer/bloxstrap/assets/172851591/ac68fe83-17bc-4fae-9dc7-0169d32466ee)

**Comment by sigmaluus** [comment]
yea bro mines doing that too idek what to do

**Comment by AmateurProgrammerishere** [comment]
the same happened to me and i thought it would be fixed by cleaning prefetch and temp and uninstalling roblox but not looks like pizzaboxer need to update it!!!! i did everything and still the same error.

**Comment by AmateurProgrammerishere** [comment]
looks like roblox changed something so bloxstrap cant detect the launcher i think?

**Comment by AmateurProgrammerishere** [comment]
> yea bro mines doing that too idek what to do

just uninstall it for now and use the default roblox launcher.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox

**Comment by sigmaluus** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox

i tried the thing u sent me but its still saying that 403 forbidden error
