### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jeremyvaughn519** [pizzaboxer/bloxstrap#1985]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240614T201553Z.log](https://github.com/user-attachments/files/15843042/Bloxstrap_20240614T201553Z.log)

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
