### ISSUE TITLE
[BUG] i cannot open roblox

### ISSUE THREAD

**Issue by robloxdebuged** [pizzaboxer/bloxstrap#1986]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240614T201553Z.log](https://github.com/user-attachments/files/15843160/Bloxstrap_20240614T201553Z.log)
i tried opening roblox and it just said error 404 https something pls help me fix this

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
