### ISSUE TITLE
[BUG] i cant open roblox

### ISSUE THREAD

**Issue by ryan4213** [pizzaboxer/bloxstrap#1987]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to open roblox it doesnt work and says an exeption occured while running bloxstrap and heres the code thing: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
