### ISSUE TITLE
[BUG] 403 error upon joining

### ISSUE THREAD

**Issue by maddilan6** [pizzaboxer/bloxstrap#1990]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by sigmaluus** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> ### What problem did you encounter?
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

i got that too idk what to do im new to this stuff

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
