### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GrapeJuice923** [pizzaboxer/bloxstrap#1991]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![obraz_2024-06-14_232944724](https://github.com/pizzaboxer/bloxstrap/assets/172855233/ea08cbc1-da35-40f1-80cf-112dc6cb2d49)

Forbidden

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
