### ISSUE TITLE
[BUG]  Doesn't let me use Bloxstrap when I join a Roblox Game 

### ISSUE THREAD

**Issue by LucaGamingYT** [pizzaboxer/bloxstrap#1992]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try to join a game, it pops up the connecting to Roblox loading screen but an error appears above that saying: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
![Bloxstrap Exception 14_06_2024 22_31_36](https://github.com/pizzaboxer/bloxstrap/assets/172855370/e673293f-974d-4e84-86e0-89c881078f15)

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0

**Comment by LucaGamingYT** [comment]
Ok thx
