### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EpicFitment** [pizzaboxer/bloxstrap#1993]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Error occurs while trying to join a roblox game.
![Screenshot 2024-06-14 223511](https://github.com/pizzaboxer/bloxstrap/assets/172854948/c788a4f1-e5be-425d-9f2e-e17dc87ae0ff)
Cannot join a game with bloxstrap

**Comment by MrNooberDude** [comment]
[Help Wiki Page](https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox)
Launch Roblox via the game client (enable the desktop app if disabled in Bloxstrap) after looking through the pages. You might need to make an alt though.

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
