### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by Pedrodimon** [pizzaboxer/bloxstrap#1994]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![imagem_2024-06-14_185242739](https://github.com/pizzaboxer/bloxstrap/assets/172856387/71a2bf5d-e5d9-4c9b-8c6c-2c46361a6bfa)
[Bloxstrap_20240614T214852Z.log](https://github.com/user-attachments/files/15844188/Bloxstrap_20240614T214852Z.log)

**Comment by MrNooberDude** [comment]
[Help Wiki Page](https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox)
Launch Roblox via the game client (enable the desktop app if disabled in Bloxstrap) after looking through the pages. You might need to make an alt though.

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
