### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by FanumTaxxing** [pizzaboxer/bloxstrap#1995]
Every time I try to join Roblox with Bloxstrap it doesn't work at all and it gives me this error, error 403
![Bloxstrap](https://github.com/pizzaboxer/bloxstrap/assets/171242947/1dbf2759-4bfd-483d-b149-54e2c6bc8db3)
But it works when I try to join from the Roblox player app
I don't know what to do to fix it honestly.

**Comment by AmateurProgrammerishere** [comment]
pizzaboxer need to update it you cant do anything about it i also tryed everything and it did not get fixxed

**Comment by MrNooberDude** [comment]
[Help Wiki Page](https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox)
Launch Roblox via the game client (enable the desktop app if disabled in Bloxstrap) after looking through the pages. You might need to make an alt though.

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
