### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by meki7a** [pizzaboxer/bloxstrap#1996]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by AmateurProgrammerishere** [comment]
everyone who use bloxstrap will encounter this error devs simply need to update it and fix it,

**Comment by MrNooberDude** [comment]
[Help Wiki Page](https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox)
Launch Roblox via the game client (enable the desktop app if disabled in Bloxstrap) after looking through the pages.

**Comment by MrNooberDude** [comment]
You might need to make an alt though.

**Comment by iiPythonx** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.6.0

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
