### ISSUE TITLE
PSA: Stop posting issues about the 403 error

### ISSUE THREAD

**Issue by MrNooberDude** [pizzaboxer/bloxstrap#1997]
Give pizzaboxer a break and look at some of the 30 other issues covering the _exact same thing_. I don't wanna be a minimod but jeez relax

**Comment by AmateurProgrammerishere** [comment]
yeah i agree but there is one issue the launcher hasnt been updated in really long time like 8 months ago. And this bug is critical since it makes the bootstraper completely useless and it should be fixed immediately. i guess roblox is getting kinda crazy now.

**Comment by AmateurProgrammerishere** [comment]
first roshade and then Bloxstrap :CCC
