### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LunxrDrive** [pizzaboxer/bloxstrap#1998]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My game was fine an hour ago now it looks like this:
![image](https://github.com/pizzaboxer/bloxstrap/assets/172856271/50f823d1-1c96-42b3-9ea4-531d5e8b7ba7)
This happens whenever i try to log onto bloxstrap
I've tried reinstalling the latest version of bloxstrap 
and i'm pretty sure all of my pc specs are up to date

This appears when I tried to press "Locate Log File"
![image](https://github.com/pizzaboxer/bloxstrap/assets/172856271/23cf150d-2636-42f7-95f1-69fe02b749bd)
I'd have no idea if this is useful but this is a random bug I found

**Comment by MrNooberDude** [comment]
[Help Wiki Page](https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox)
Launch Roblox via the game client (enable the desktop app if disabled in Bloxstrap) after looking through the pages.

**Comment by MrNooberDude** [comment]
You might need to make an alt though.

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
