### ISSUE TITLE
2010 and earlier bootstrapper style

### ISSUE THREAD

**Issue by PlayerValley** [pizzaboxer/bloxstrap#2]
You should add the 2010 and earlier bootstrapper style, and it should look like the image below.

![2010](https://cdn.upload.systems/uploads/thIQEPHh.png)

**Comment by pizzaboxer** [comment]
I was originally going to have this as part of the 1.0.0 release, but had to remove it for now due to [some difficulties](https://github.com/pizzaboxer/bloxstrap/blob/main/Bloxstrap/Dialogs/BootstrapperStyles/TaskDialogStyle.cs). If possible, it may be added back in the future.

**Comment by pizzaboxer** [comment]
[Added as part of the v1.2.0 update](https://github.com/pizzaboxer/bloxstrap/blob/main/Bloxstrap/Dialogs/BootstrapperStyles/VistaDialog.cs)
