### ISSUE TITLE
"failed to download or apply critical settings."

### ISSUE THREAD

**Issue by Instearstell** [pizzaboxer/bloxstrap#20]
Whenever i try to open bloxstrap, this error pops up, what do i do to resolve it? or do i just delete the old launcher.

![image](https://user-images.githubusercontent.com/114784532/193370232-7ec8df76-fa40-4b72-bb31-f3c709dd6395.png)

**Comment by pizzaboxer** [comment]
That doesn't seem like a Bloxstrap-related issue. Try uninstalling Bloxstrap to revert back to the stock launcher, and see if the issue still persists.

**Comment by Instearstell** [comment]
sorry for the delay, it works fine without bloxstrap, maybe i need to reinstall bloxstrap?

**Comment by pizzaboxer** [comment]
Sure, go ahead and try.

**Comment by Instearstell** [comment]
it works now, thanks for the help

**Comment by coolkide2** [comment]
but i am having trumble to play
