### ISSUE TITLE
Can't Play Roblox because of the 32Bit Client being removed

### ISSUE THREAD

**Issue by SorceryDestroyer** [pizzaboxer/bloxstrap#200]
When i try to play a game i get a disconnection error because of the 32Bit Client being removed/no longer supported 

![image](https://user-images.githubusercontent.com/100327708/236358640-fa817dcb-cdfa-4cc2-93d0-b0210f6421d1.png)

**Comment by ThatOneOcto** [comment]
update

**Comment by TaylorIsBlue** [comment]
You can fix this error by just removing the Revert Script form tampermonkey and re-install roblox using the RobloxPlayerluancher

**Comment by pizzaboxer** [comment]
You're on Windows 10. Are you sure you're using 32-bit Windows?

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/236409121-8ac6dc74-3a2f-41c3-ad6d-58cdb1c500c2.png)
I'm have the same issue

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/236409252-bac1c682-214b-4238-8f9d-6f3616268432.png)
This is my installation

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/236410340-ff4d27fd-39bc-463d-a9bd-ac7e29da7b77.png)
hey that's not right

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/236411442-0e8c8912-5d5c-4587-92bd-a79ae442ed06.png)
Using normal bootstrapper does this

**Comment by NikSavchenk0** [comment]
change channel ZLive.

**Comment by pizzaboxer** [comment]
> ![image](https://user-images.githubusercontent.com/68739273/236409252-bac1c682-214b-4238-8f9d-6f3616268432.png)
> This is my installation

Oh, that's weird. I've only seen this error happen on ZLive. That shouldn't be happening?

**Comment by pizzaboxer** [comment]
> ![image](https://user-images.githubusercontent.com/68739273/236410340-ff4d27fd-39bc-463d-a9bd-ac7e29da7b77.png)
> hey that's not right

lol just hover your mouse over them and they'll go away

**Comment by pizzaboxer** [comment]
> > You're on Windows 10. Are you sure you're using 32-bit Windows? Can I see what channel you have selected in the Installation tab?
> 
> I am using Windows 11 and i am on the ZNext channel @pizzaboxer 
> 
> 
> ![image](https://user-images.githubusercontent.com/100327708/236459735-bdca9620-a0ef-4e3c-9b1c-e114b098ab96.png)
> 

Do **not** use ZNext. Connections from ZNext are being rejected.

**Comment by Variable1485** [comment]
Everything is back to normal, I think it just needed patience ig

**Comment by FoxyelperroDJ** [comment]
> wha
> 
> ![image](https://user-images.githubusercontent.com/100327708/236461414-349d88f5-2036-40ee-ba60-4e1e7150c51e.png)

just wait a few hours, it worked for me ;) ( try to enter another game, if the other games work you must wait a few hours and it will be solved )

**Comment by EasternBloxxer** [comment]
> 

You need to join another server iirc as that is basically a server ban. I asked bitdancer but he left me on read...

**Comment by EasternBloxxer** [comment]
> > wha
> > ![image](https://user-images.githubusercontent.com/100327708/236461414-349d88f5-2036-40ee-ba60-4e1e7150c51e.png)
> 
> just wait a few hours, it worked for me ;) ( try to enter another game, if the other games work you must wait a few hours and it will be solved )

You need to join another server iirc as that is basically a server ban. I asked bitdancer but he left me on read...
