### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Santinox805** [pizzaboxer/bloxstrap#2000]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/172857279/114bd533-417e-4679-8a67-9593d250e253)

**Comment by AmateurProgrammerishere** [comment]
Remove bloxstrap for now or use the defult roblox game launcher

**Comment by Santinox805** [comment]
please help me

**Comment by AmateurProgrammerishere** [comment]
Open the control panel the click on uninstall programs and type in the seacrh Bloxstrap and uninstall it for now.

**Comment by Santinox805** [comment]
ok thanks

**Comment by AmateurProgrammerishere** [comment]
Glad i could help.

**Comment by iiPythonx** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.6.0

**Comment by bluepilledgreat** [comment]
Fixed with v2.6.0
