### ISSUE TITLE
Why was multi-instance launching removed?

### ISSUE THREAD

**Issue by Rayyore** [pizzaboxer/bloxstrap#2001]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I really want it back :(

**Comment by Rayyore** [comment]
yes

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
