### ISSUE TITLE
[BUG] New Disable Desktop App Method Inconsistency

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#2002]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The new method for Disabling the desktop app is heavily inconsistent, sometimes it works how it was supposed too, sometimes it takes a bit then works, and rarely it just doesn't work. The feature might need a small update.

**Comment by pizzaboxer** [comment]
Can you clarify?

**Comment by ShadowCodeX-debug** [comment]
I have Don't Exit to Desktop App on and it just does not work.

**Comment by WertyTT4** [comment]
true, sometimes the thing exits to desktop and doesnt work and then it closes a few seconds after

**Comment by abysswireless** [comment]
was the desktop app being fully disabled causing the crashes?
i prefer not using it at all cus it's super laggy on my computer and ig there's an extra step to doing that now

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer #2116 another post that would be nice if you can't do anything about this.

**Comment by pizzaboxer** [comment]
The next time you find that it doesn't work, can you send the latest log file from `%localappdata%\Bloxstrap\Logs`?

**Comment by pizzaboxer** [comment]
Discussion moved to #2049
