### ISSUE TITLE
[BUG] Bloxstrap can't install

### ISSUE THREAD

**Issue by tranuhrl** [pizzaboxer/bloxstrap#2003]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to install v2.6.0, an error pops up talking about how it doesn't support administrator mode. I haven't ran it in administrator mode as far as I know, just regularly.

![image](https://github.com/pizzaboxer/bloxstrap/assets/116113037/f9578f28-76b8-4bca-9d48-d1eac0705345)

**Comment by ImInsane1337** [comment]
True

**Comment by Jagaziela2** [comment]
True

**Comment by Jagaziela2** [comment]
Now What?

**Comment by desorz** [comment]
same

**Comment by Luknopc** [comment]
same here

**Comment by bluepilledgreat** [comment]
This is being fixed with v2.6.1. Please be patient.

**Comment by desorz** [comment]
i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"

**Comment by BLUDSTARP** [comment]
I tired that it still wouldnt let me

**Comment by BLUDSTARP** [comment]
> i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"

I tired that but it wont let me

**Comment by tranuhrl** [comment]
> i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"

nah it works now 2.6.1 came out

**Comment by desorz** [comment]
> > i downgraded to v2.5.4 and it works well, just dont use checkbox on "Automatically update Bloxstrap"
> 
> I tired that but it wont let me

Did you uncheck mark on "Automatically update Bloxstrap", because it updates bloxstrap to v2.6.0 on launch and i give you this error

**Comment by pizzaboxer** [comment]
Download v2.61 at https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.6.1. You'll need to manually download and run it.
