### ISSUE TITLE
[REQ] Materials and Extra Vulkan Flag Removal

### ISSUE THREAD

**Issue by CfwSky** [pizzaboxer/bloxstrap#2006]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

no point in keeping materials since roblox removed the ability to replace textures, and the extra vulkan flag named "FFlagRenderVulkanFixMinimizeWindow" doesnt exist in the client anymore (not declared error)

**Comment by pizzaboxer** [comment]
Those were supposed to be removed. I guess I forgot to remove them.

**Comment by pizzaboxer** [comment]
Fixed in 2.7.0
