### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Pinnok123** [pizzaboxer/bloxstrap#2007]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Error message: System.UnauthorizedAccessException: Access to the path 'C:\Users-\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

cant install it

**Comment by pizzaboxer** [comment]
Read the wiki
