### ISSUE TITLE
[BUG] when i want to open roblox, nothing opens.

### ISSUE THREAD

**Issue by cem6161** [pizzaboxer/bloxstrap#2008]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i am opening roblox and nothing is opening, it says "starting roblox" but nothing is opening.

**Comment by pizzaboxer** [comment]
Does it happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by cem6161** [comment]
yes only bloxtrap doesnt work, normal roblox works.

**Comment by cem6161** [comment]
i fixxed it, ty for you help!

**Comment by cem6161** [comment]
i fixxed it, ty for you help!
