### ISSUE TITLE
[BUG] i noticed something when trying to server Hop on Roblox servers!!

### ISSUE THREAD

**Issue by SrJubi** [pizzaboxer/bloxstrap#2011]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it says, "Roblox is currently running, and launching another instance will close it. are you sure you want to continue launching?"
![image](https://github.com/pizzaboxer/bloxstrap/assets/172860099/dacd9aa4-1f27-4143-83ce-283062299220)

it never asked it to me, when it got updated it started to do that, and it's kinda anoying having to mark check yes on this advice every time i try to server Hop with RoPro, i play bee swarm and sometimes i go server hopping to get some items faster, and other things... but since it updated it made the process way slower, and i was wondering if i can fix that, or you could maybe put an option on Bloxtrap to disable this message, or make it to agree without having to mark yes everytime, well, thank you for your attention.

**Comment by WertyTT4** [comment]
They already announced that they'd remove multi-instances before hand

**Comment by JohnFawkes** [comment]
this popup shows even with no instances of roblox open

**Comment by SrJubi** [comment]
Well, that is the first time it shows up to me, i had never got this problem before, so it started when the new update released, and i searched almost everywhere to see if i find something to make this go away but i didnt find out anything to solve this

**Comment by JohnFawkes** [comment]
yea i downgraded back to 2.5.4 for now

**Comment by SrJubi** [comment]
Thanks John, it worked! 😁
