### ISSUE TITLE
add a feature to disable the warning because it acounts roblox account manager as a roblox instance and people use it to run multi roblox[REQ] 

### ISSUE THREAD

**Issue by 0uriem** [pizzaboxer/bloxstrap#2012]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Roblox alt manager (roblox account manager) gets flagged as a roblox instance and the warning pops up. its annoying please add a option to disable the warning

**Comment by pizzaboxer** [comment]
Duplicate of #2011
