### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by System-XU** [pizzaboxer/bloxstrap#2013]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/172861476/03851d61-b056-4d9f-baaf-bef538c297ba)

**Comment by ShadowCodeX-debug** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
