### ISSUE TITLE
[BUG] Miscellaneous section missing

### ISSUE THREAD

**Issue by fvfawesome** [pizzaboxer/bloxstrap#2014]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried to launch multiple instances of roblox, but  I couldn't since I was getting warnings from bloxstrap that it would close the other one, so I checked bloxstrap, but when I scrolled down there was no miscellaneous section.
![Screenshot 2024-06-14 185837](https://github.com/pizzaboxer/bloxstrap/assets/172866060/b92ec55b-8e4f-4477-8024-94eae143d69b)

**Comment by Rayohgamer** [comment]
i just downloaded an older version of it

**Comment by mayawidjeskog-dev** [comment]
I can't find it
