### ISSUE TITLE
[BUG]  due to a glitch that couldnt let me open bloxstrap, reinstalled but i got this error:

### ISSUE THREAD

**Issue by pine715** [pizzaboxer/bloxstrap#2015]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.IO.DirectoryNotFoundException: Could not find a part of the path

**Comment by bluepilledgreat** [comment]
Send the log file

**Comment by pine715** [comment]
and how do i do log files? or is .txt or notepad okay?

**Comment by pine715** [comment]
if .txt is okay,
file:///C:/Users/theom/OneDrive/Documents/bloxstrap%20log.txt

**Comment by pine715** [comment]
working, mustve been a screw up. sorry i didnt do anything :(
