### ISSUE TITLE
[BUG] STOP MAKING ME SWITCH TO LIVE

### ISSUE THREAD

**Issue by burgerboxer** [pizzaboxer/bloxstrap#2016]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was on ZIntegration4 and it switched me to LIVE

bad update!

![image](https://github.com/pizzaboxer/bloxstrap/assets/166893422/4f791555-ae4d-4f2b-b19c-bc892bc4a16d)

**Comment by d44df016fe28bc8d5974** [comment]
true...
upgrade to 2.5.4
its better
