### ISSUE TITLE
[BUG] Can't connect to play Roblox

### ISSUE THREAD

**Issue by Lun4rLight** [pizzaboxer/bloxstrap#2017]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Here's a weird thing that says here: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).  I reset my computer it still the same please fix.

**Comment by bluepilledgreat** [comment]
Download the latest update (v2.6.1)
