### ISSUE TITLE
[BUG] An exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by bamtaked** [pizzaboxer/bloxstrap#2018]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/111577076/4a5d3d73-fcfa-43d7-9c5b-b91f2b2f5def)

**Comment by rafael2011reis** [comment]
Ok, i was trying to uninstall bloxtrap, but this mistake appears during the uninstall when i decided. Can you please help me please?
