### ISSUE TITLE
multiple roblox instances

### ISSUE THREAD

**Issue by Golden0713** [pizzaboxer/bloxstrap#2019]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i know this got removed but it made it alot more difficult for me to do stuff, i use alts in certain games to move stuff between like a bank of sorts or if i get stuff on that alt and i want to move to the game, or in other ways ill use it to help my friend test out his game with ablitys and see how they work on different player models but without this feature im unable to do that, so id like to ask for it to be put back into it, or have help finding a different way to get this feature without getting a virus or anything

**Comment by Rayohgamer** [comment]
i just downloaded an older version

**Comment by asskysve** [comment]
tbh i agree i want the multiple roblox insatnces added back

**Comment by burnkyasai** [comment]
how do you keep the older version from auto updating? it happens everytime i open roblox

**Comment by exurd** [comment]
> how do you keep the older version from auto updating? it happens everytime i open roblox

Disable the "Automatically update Bloxstrap" option in the Behaviour tab when installing.

**Comment by art2237** [comment]
> i just downloaded an older version

bro, I did this, but the blox strap menu still doesn't show the miscellaneous tab, is that why it updated? If so, I don't know why, when I downloaded and started it, I pressed not to update to the latest version

**Comment by art2237** [comment]
> > i just downloaded an older version
> 
> bro, I did this, but the blox strap menu still doesn't show the miscellaneous tab, is that why it updated? If so, I don't know why, when I downloaded and started it, I pressed not to update to the latest version

bro, now I see, the bloxstrap automatically updates to 2.61, but there is no option to disable it, it is automatic, what i do?
