### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Xzevi** [pizzaboxer/bloxstrap#2022]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my bloxstrap have no allows for having more than one Roblox game client instance open simultaneously 
![Screenshot 2024-06-15 144441](https://github.com/pizzaboxer/bloxstrap/assets/172882887/481151e3-b2d2-41c3-a3b9-ebc3a5411dba)

**Comment by someguy192** [comment]
Not an issue, they removed this sadly
