### ISSUE TITLE
[REQ] Sign exes from smartscreen warning

### ISSUE THREAD

**Issue by Vlad55432** [pizzaboxer/bloxstrap#2023]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Pretty annoying 
![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/8d7f4185-2a04-466b-a32d-d4269f99196c)

**Comment by bluepilledgreat** [comment]
We can't. It would cost us money.

**Comment by Vlad55432** [comment]
> We can't. It would cost us money.

Oh, didn't know
