### ISSUE TITLE
[BUG] Administrator Bug

### ISSUE THREAD

**Issue by spiritRBX** [pizzaboxer/bloxstrap#2025]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxstrap wont launch at all due to saying this cant run with administrator privilages however i didnt run it as administrator and it said redownload as lower privilages however it never asked to run as administrator with redownload and did the same exact thing and my bloxstrap starting doing this after i put a fast flag on then i removed the fast flag and it still did it and i cant open roblox or the bloxstrap menu whatever even after redownload due to it saying that its administrator

**Comment by AmateurProgrammerishere** [comment]
just download the 2.6.1 veRsion it sgould fix it

**Comment by bluepilledgreat** [comment]
Manually download v2.6.1. Sorry for the inconvenience.
