### ISSUE TITLE
[REQ] BRING BACK THE CHANNEL SWITCHER!

### ISSUE THREAD

**Issue by burgerboxer** [pizzaboxer/bloxstrap#2026]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

THIS FEATURE IS VERY USEFUL!

![image](https://github.com/pizzaboxer/bloxstrap/assets/166893422/8ad20140-75ee-4d5f-b0c0-ac65b462cfc1)

**Comment by d44df016fe28bc8d5974** [comment]
bump

**Comment by catb0x** [comment]
ijbol is it that hard to change one word in settings.json
