### ISSUE TITLE
actual mod menu?

### ISSUE THREAD

**Issue by BaconDave312** [pizzaboxer/bloxstrap#203]
would be cool
just collect 0 useful mods (maybe i missed any use of every mod but ok) because there arent any useful mods on the gamebanana
and make a mod menu out of that
`thats an enchancement and i dont know how to make tags cause there aint a button for that`

**Comment by TheRealBooWasHere** [comment]
No, because I think that would need to be injected into roblox so it would be bannable

**Comment by EasternBloxxer** [comment]
No

**Comment by BaconDave312** [comment]
i guess

**Comment by EasternBloxxer** [comment]
That aint a byfron bypass lmao its going to be on every channel soon

**Comment by pizzaboxer** [comment]
I am not going to take mods that other people have made and bundle them directly with Bloxstrap.
