### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Raksou** [pizzaboxer/bloxstrap#2030]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/172906097/e9abca24-a9f2-4475-a890-375eb5023f7e)

**Comment by bluepilledgreat** [comment]
Update to v2.6.1
