### ISSUE TITLE
[BUG] No multi-instance launching button

### ISSUE THREAD

**Issue by frostfairgr-10** [pizzaboxer/bloxstrap#2031]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I looked in the integrations menu, the "Multi-Instance launching" option is gone. (It does not launch multiple instances now)

**Comment by cinos12x** [comment]
same here multi instance got deleted

**Comment by baoothewalkingtitanic** [comment]
Yea same it's no longer there
