### ISSUE TITLE
why cant i open multi roblox anymore?

### ISSUE THREAD

**Issue by xxshiteaterxx** [pizzaboxer/bloxstrap#2032]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cant find the settings for it in the bloxstrap menu

**Comment by mel031106** [comment]
iirc its being patched, and it's buggy so it was removed

**Comment by xxshiteaterxx** [comment]
will it get added soon?

**Comment by Mayapixi** [comment]
IT WAS WORKING IN 2.5.4 NO BUG
