### ISSUE TITLE
[REQ] Add back MultiAccounting

### ISSUE THREAD

**Issue by maxylab** [pizzaboxer/bloxstrap#2033]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Multiaccounting was the only feature that kept your Bloxstrap relevant. You must be really dum dum to be removing it :))) xD

**Comment by Mayapixi** [comment]
yea pls add multi account back

**Comment by prodbyeagle** [comment]
yep
