### ISSUE TITLE
i cannot find Future by lighting? 

### ISSUE THREAD

**Issue by underscoreunderscore1** [pizzaboxer/bloxstrap#2034]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cannot find future by lighting.

**Comment by ShadowCodeX-debug** [comment]
![PictureYOU](https://github.com/pizzaboxer/bloxstrap/assets/93408587/f4f26d2f-7334-49da-ad60-3c52961da134)

**Comment by underscoreunderscore1** [comment]
oh

**Comment by underscoreunderscore1** [comment]
but sir it doesnt look like it changes my game
