### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by A0mmar** [pizzaboxer/bloxstrap#2035]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i download bloxstrap it says System.Net.Http.HttpRequestException: No such host is known. (clientsettings.roblox.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.

**Comment by pizzaboxer** [comment]
Internet connectivity issue. Try again.
