### ISSUE TITLE
[REQ]  Multi instance

### ISSUE THREAD

**Issue by ie0bork** [pizzaboxer/bloxstrap#2037]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

_So I understand why you have removed the feature, please do not reprimand me for asking for it back._ 

I'm working on a roblox game and need multiple accounts to see how its going. While I'm sure you wont be adding it back, I chose Bloxstrap as its a reliable source for modding and helping me get what I need to get.  **Unfortunately, ill have to ask if you can find another platform or launcher i could test out as I'm struggling to find on that wont get me banned.**  

While I understand your reasoning for removing it, and I'm not going to demand you to add it back. I simply downloaded it for the unique bypass that was removed. But thank you for you explaining why you removed it and I wont be removing your platform from my pc it as its still a **great modding platform**

**Comment by Mayapixi** [comment]
yea i never use it for anything bad i use it to see my avatar in another point of view or help me play games that need a second player

**Comment by ie0bork** [comment]
> yea i never use it for anything bad i use it to see my avatar in another point of view or help me play games that need a second player

So, the reason he removed it was it was difficult to keep on and he didnt want to gaina reputation for being a platform for letting people "cheat" Using a second player in some games would technically be cheating to some people if that makes sense

**Comment by Mayapixi** [comment]
DID I ASKED?
