### ISSUE TITLE
[BUG] Roblox launching into the app instead of the website

### ISSUE THREAD

**Issue by SpookieGames** [pizzaboxer/bloxstrap#2038]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The option that was available in previous versions is now missing. The option to disable the roblox app completely is not there. When launching roblox it launches the app and not the website like it used to. Is there a workaround to disable the roblox app so that the website launches?

**Comment by bluepilledgreat** [comment]
The ability to disable the desktop app was unstable and was causing crashes.
