### ISSUE TITLE
[BUG] keeps crashing and saying error 403

### ISSUE THREAD

**Issue by YNWDw** [pizzaboxer/bloxstrap#2039]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by bluepilledgreat** [comment]
Update to v2.6.1
