### ISSUE TITLE
[BUG] Exception Occured 403

### ISSUE THREAD

**Issue by whyads3** [pizzaboxer/bloxstrap#2040]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap cannot open 
[Bloxstrap_20240615T223250Z.log](https://github.com/user-attachments/files/15855526/Bloxstrap_20240615T223250Z.log)
![image](https://github.com/pizzaboxer/bloxstrap/assets/172939494/5bc24068-365e-4519-9fc4-4aa7ec7decc7)

**Comment by bluepilledgreat** [comment]
Update to v2.6.1
