### ISSUE TITLE
[BUG] MISCELLANEOUS GONE AKA MULTI WINDOW OPEN

### ISSUE THREAD

**Issue by ADYES-1** [pizzaboxer/bloxstrap#2042]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i opened blox strap bc i couldnt use my alt acc to play with my main in a game and i realized miscellaneous was gone from the integration tab
![image_2024-06-16_103427762](https://github.com/pizzaboxer/bloxstrap/assets/172945910/cc79c406-3c5e-44d6-a559-a35311724414)

**Comment by JackStrya** [comment]
(https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap)
