### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mintnv** [pizzaboxer/bloxstrap#2045]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
[Bloxstrap_20240616T040713Z.log](https://github.com/user-attachments/files/15856141/Bloxstrap_20240616T040713Z.log)

**Comment by bluepilledgreat** [comment]
Update to v2.6.1
