### ISSUE TITLE
[REQ] add shaders tab please like ropro shaders you would find i want my computer to expolde

### ISSUE THREAD

**Issue by underscoreunderscore1** [pizzaboxer/bloxstrap#2048]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

why is my computer getting hot

**Comment by Blue-Star-Technology** [comment]
r u tryna get shaders in roblox? if u are heres a tutorial:
https://www.youtube.com/watch?v=N4TEvEbEtxE

**Comment by underscoreunderscore1** [comment]
its not working for me
