### ISSUE TITLE
[BUG] Bloxstrap not closing Roblox menu, despite the setting "Don't exit to desktop app" being on

### ISSUE THREAD

**Issue by KayIaS** [pizzaboxer/bloxstrap#2049]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

If I close roblox or Alt F4 out of Roblox, it will put me in the desktop app, despite me having the setting "Don't exit to desktop app" turned on.

**Comment by Hyperiab** [comment]
I have this problem too. I have to reinstall Roblox and BloxStrap to fix it and it's soooo annoying

**Comment by pizzaboxer** [comment]
Does it happen consistently all the time? Also, send Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` here.

**Comment by KayIaS** [comment]
> Does it happen consistently all the time? Also, send Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` here.

it only happens when you close roblox during the loading phase now, or when it says stuff like "no permission to join this expirience" because its a private server for example. if you close roblox in that phase it wont close roblox but instead go to the roblox app. this also happens if i press the windows button and click on bloxstrap's "Play Roblox" app. this wont make me go to the roblox website anymore but instead also open the roblox 
[Bloxstrap_20240626T094758Z.log](https://github.com/user-attachments/files/16011739/Bloxstrap_20240626T094758Z.log)
[Bloxstrap_20240627T095827Z.log](https://github.com/user-attachments/files/16011746/Bloxstrap_20240627T095827Z.log)

**Comment by pizzaboxer** [comment]
> it only happens when you close roblox during the loading phase now, or when it says stuff like "no permission to join this expirience" because its a private server for example.

Unable to replicate the loading phase issue, but can replicate the error message issue. Thanks for letting me know.

> this wont make me go to the roblox website anymore but instead also open the roblox

Yes, that's intentional. That's why the option is now named "Don't ***exit***x to desktop app".

**Comment by pizzaboxer** [comment]
Try out this version and see if the issue persists: https://github.com/pizzaboxer/bloxstrap/actions/runs/9698130947/artifacts/1644937901

Just run Bloxstrap.exe and click yes when it prompts you to upgrade.

**Comment by KayIaS** [comment]
> Try out this version and see if the issue persists: https://github.com/pizzaboxer/bloxstrap/actions/runs/9698130947/artifacts/1644937901
> 
> Just run Bloxstrap.exe and click yes when it prompts you to upgrade.

the same problem still happens

**Comment by pizzaboxer** [comment]
> the same problem still happens

Show the latest log file from `%localappdata%\Bloxstrap\Logs`

**Comment by KayIaS** [comment]
[Bloxstrap_20240627T143108Z.log](https://github.com/user-attachments/files/16018610/Bloxstrap_20240627T143108Z.log)

**Comment by Hyperiab** [comment]
I am currently on a camping trip and I will respond on Sunday when I get
home

**Comment by pizzaboxer** [comment]
> [Bloxstrap_20240627T143108Z.log](https://github.com/user-attachments/files/16018610/Bloxstrap_20240627T143108Z.log)

@KayIaS You're not using the version I gave you. Download the version I linked, run it, click yes when it prompts you to upgrade, then launch Roblox.

**Comment by pizzaboxer** [comment]
> [Bloxstrap_20240627T143108Z.log](https://github.com/user-attachments/files/16018610/Bloxstrap_20240627T143108Z.log)

Can you privately send me this log file:

`%UserProfile%\AppData\Local\Roblox\logs\0.630.0.6300556_20240627T143111Z_Player_ED1A5_last.log`

Do it over Discord. [Join the server](https://discord.gg/nKjV3mGq6R) and send me a DM.

**Comment by pizzaboxer** [comment]
Problem should be fully fixed now as of 5a08086: https://github.com/pizzaboxer/bloxstrap/actions/runs/9733769691

**Comment by Hyperiab** [comment]
hey Pizza, I am finally home from my camping trip so can I show you my logs or is the ticket closed bc of Kayla

**Comment by pizzaboxer** [comment]
> hey Pizza, I am finally home from my camping trip so can I show you my logs or is the ticket closed bc of Kayla

Download and run https://github.com/pizzaboxer/bloxstrap/actions/runs/9733769691/artifacts/1653043792 and just check to see if the issue has been fixed

**Comment by pizzaboxer** [comment]
Fixed in 2.7.0
