### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by TheRjavisDev** [pizzaboxer/bloxstrap#205]
after v2.30's release, roblox decided to randomly crash

**Comment by Empyrlum** [comment]
i've been having crashes too after the full release of hyperion

**Comment by Variable1485** [comment]
![image](https://user-images.githubusercontent.com/68739273/236494426-911e601b-ece6-46f0-90d2-328f0ae6ca21.png)
![image](https://user-images.githubusercontent.com/68739273/236494438-37c9605b-92e1-4a87-90a5-41cd06792d35.png)
Same here and this one was kinda fatal, not only it crashed roblox but it also crashed my discord

**Comment by TheRjavisDev** [comment]
as the not smartest person on earth, it still seems that your device ran out of memory

**Comment by Variable1485** [comment]
i dont think so, i reattempted this and the same crash happened but i was at 80% mem

**Comment by pizzaboxer** [comment]
> after v2.30's release, roblox decided to randomly crash

Have you also considered the possibility that this is related to Hyperion? That's what a lot of people have been encountering recently. If you uninstall Bloxstrap and then try and play Roblox and it still ends up happening, that's definitely a Hyperion problem.

**Comment by EasternBloxxer** [comment]
You likely ran out of memory. Since the release of the 64 bit client Roblox can now take up as much memory as it wants

**Comment by pizzaboxer** [comment]
Oh, I should've asked. How exactly does Roblox crash? Does it show the Roblox crash dialog, or does it just close by itself?

**Comment by TheRjavisDev** [comment]
sometimes the dialog, sometimes just not responding

**Comment by pizzaboxer** [comment]
How often does it happen?

**Comment by Variable1485** [comment]
it seems like there is a memory limit set by windows?? it isn't going any higher

**Comment by pizzaboxer** [comment]
And you're sure that it doesn't happen at all without Bloxstrap being installed?

**Comment by TheRjavisDev** [comment]
Yes, I played a game completely without crashes after uninstalling Bloxstrap

**Comment by pizzaboxer** [comment]
Reinstall Bloxstrap, but make sure you have Discord Rich Presence, server details and multi-game instance launching disabled. See if it still happens then.

**Comment by TheRjavisDev** [comment]
rich presence was already disabled, server details and multi-game instance was disabled also, weird

**Comment by Variable1485** [comment]
I'll do all this when free

**Comment by TheRjavisDev** [comment]
nvm after another check, it crashes without bloxstrap

**Comment by Variable1485** [comment]
This seems to be a roblox x64 problem where it uses too much memory and it crashes? Some people not using bloxstrap also reported this

**Comment by TheRjavisDev** [comment]
that's why making roblox x64-bit for everyone was a mistake

**Comment by TheRjavisDev** [comment]
though, it seems that crashes have stopped after a restart, the crash reason was "1"
