### ISSUE TITLE
[BUG] Windows with security problems with the app (bloxstrap).

### ISSUE THREAD

**Issue by CrazyAgiota** [pizzaboxer/bloxstrap#2050]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Well, I don't know for sure, it could be because the new version of the application was released yesterday, I've already checked everything and it still shows this false warning on the Windows smartscreen.

**Comment by TheGitHubPlayer1** [comment]
Bloxstrap keeps crashing please fix this developer :(

**Comment by pizzaboxer** [comment]
> and it still shows this false warning on the Windows smartscreen.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/42edd74f-ee9c-4ef2-9d3d-5307112cb220)
