### ISSUE TITLE
[BUG] The Multi Instance Option Is Gone from menu.

### ISSUE THREAD

**Issue by NosokBobloxer** [pizzaboxer/bloxstrap#2051]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I Was playing roblox using Bloxtrap and then when i tried to use Multi Instance, it didn't work. I opened Bloxtrap menu but the Multi Instance option is gone and i can't do anything with it!!! I Believe somebody checks it or just answers what i gotta do right now.

**Comment by Flikter** [comment]
The multi-instance launching feature has been removed since v2.6.0. https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap

**Comment by gitRadostin** [comment]
i got this issue too

**Comment by NabHeyka22** [comment]
it's removed
use roblox account manager if you want multi instance
