### ISSUE TITLE
[BUG] Crashing me pc on launch

### ISSUE THREAD

**Issue by Pep8050** [pizzaboxer/bloxstrap#2052]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

It happened right when bloxstrap just updated. I tried to launch it but then my pc freeze and auto restarted it self, then the next time I try to open it up again, it asked me to download a deskstop runtime programm which I already did but it still don't launch, then i tried manually restart my pc and reinstall bloxstrap which somehow worked but then it crashes again after the next time I launch it again.
[And yes I did tried to open normal roblox without bloxstrap and it worked just fine]

**Comment by Coem1234** [comment]
Ello there and I am facing the same issue and like a month ago i belive the same thing happened but after a week it was working fine but now the problem has started agian

**Comment by pizzaboxer** [comment]
In what way does it crash? Do you get an error message?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
