### ISSUE TITLE
[BUG] Bloxstrap Exception

### ISSUE THREAD

**Issue by WNnitro** [pizzaboxer/bloxstrap#2053]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240616T110412Z.log](https://github.com/user-attachments/files/15857519/Bloxstrap_20240616T110412Z.log)

**Comment by pizzaboxer** [comment]
Check your antivirus to ensure it's not preventing Bloxstrap from connecting to the internet.
