### ISSUE TITLE
Bloxstrap is stopping all mutli-instance roblox apps..

### ISSUE THREAD

**Issue by kzyy** [pizzaboxer/bloxstrap#2054]
I can't use any ROBLOX account manager to open 2 ROBLOX's since Bloxstrap decided to get rid of their feature. Everytime I try and join myself or a different server Bloxstraps is asking me to close my game to open a new one. (Had to completely uninstall Bloxstraps for it work.)

**Comment by scamms** [comment]
yeah bloxstrap is useless now.

**Comment by scamms** [comment]
I found a fix, downgrade your bloxstrap to v2.5.4

**Comment by Beeblup** [comment]
@scamms can it work with v2.6.0?

**Comment by revelantion** [comment]
> I found a fix, downgrade your bloxstrap to v2.5.4

how would i do that?
