### ISSUE TITLE
Add mutli-instance back into bloxstrap

### ISSUE THREAD

**Issue by Beeblup** [pizzaboxer/bloxstrap#2055]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i dont see it and i want to play on two accounts but i guess you just gotta remove the best option ADD IT BACK EVERYONE WANTS IT

**Comment by Blue-Star-Technology** [comment]
if pizzaboxer doesnt do it just download the old version of bloxstrap

**Comment by Beeblup** [comment]
yeah but i dont want to
