### ISSUE TITLE
[REQ] different icons

### ISSUE THREAD

**Issue by Blue-Star-Technology** [pizzaboxer/bloxstrap#2056]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

if you cant bring back the old topbar can you give the option to change icons to like the old icons and stuff i did it on the original roblox once

**Comment by pizzaboxer** [comment]
> if you cant bring back the old topbar 

https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
