### ISSUE TITLE
error code 272

### ISSUE THREAD

**Issue by Polymecha** [pizzaboxer/bloxstrap#206]
It was working a couple hours ago. It worked with the 64 bit client before. Now it shows this:
![image](https://user-images.githubusercontent.com/73960880/236471193-0945ca87-a1c3-4c2c-8297-a635997f1ec0.png)

**Comment by EasternBloxxer** [comment]
What channel are ya on? (Show ss of installation tab in bloxstrap menu)

**Comment by EasternBloxxer** [comment]
![image](https://user-images.githubusercontent.com/54174182/236473300-20ede7d6-b82e-488b-a2f0-951605f8df5a.png)

**Comment by EasternBloxxer** [comment]
change it to just LIVE

**Comment by Polymecha** [comment]
Alright I'll try that.

**Comment by Polymecha** [comment]
Well now it keeps showing this no matter how many times I try it.
![image](https://user-images.githubusercontent.com/73960880/236474073-b722ad7e-b79f-4832-b2cf-b121c284c2ac.png)

**Comment by EasternBloxxer** [comment]
try closing any open instances of roblox from task manager

**Comment by EasternBloxxer** [comment]
Or join a different server/game because i think Roblox ip bans people from certain gameservers now for some reason because that happened to me too

**Comment by Polymecha** [comment]
Okay so it works on a different game, but not the game that I'm trying to join. How do I join said game without getting kicked?

**Comment by EasternBloxxer** [comment]
until that server shuts down try finding a different server i cant really help with that because thats a Roblox issue most likely
or you could always use an alternative account unless you have some progress on that game

**Comment by Polymecha** [comment]
So it's not a permanent issue then?

**Comment by EasternBloxxer** [comment]
Yeah it shouldnt be. You could always ask bitdancer on devforum. He probably knows.

**Comment by Polymecha** [comment]
Thank you, that should be enough to fix my problem.

**Comment by samdisk11** [comment]
bitdancer is probably watching anyways.

**Comment by EasternBloxxer** [comment]
yeah
