### ISSUE TITLE
[BUG] game effect that disapear

### ISSUE THREAD

**Issue by Ghosty-Hope** [pizzaboxer/bloxstrap#2061]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

with bloxstrap :
![image](https://github.com/pizzaboxer/bloxstrap/assets/172990196/4580b72f-4d1c-4e12-8d17-573046f6411a)
how is it supposed to be :
![image](https://github.com/pizzaboxer/bloxstrap/assets/172990196/89fd96c0-e485-4658-af88-035b7307ad86)

**Comment by bluepilledgreat** [comment]
Check your fast flags

**Comment by pizzaboxer** [comment]
^
Assuming this to have been resolved, will reopen if not
