### ISSUE TITLE
Bloxtrap says “an unexpected error occurred and Roblox needs to quit.”

### ISSUE THREAD

**Issue by zvcee** [pizzaboxer/bloxstrap#2062]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Once I click “play Roblox” on bloxtrap, it loads for about 3 seconds then crashes and says “an unexpected error has occurred and Roblox needs to quit.” I’ve tried every solution, including changing fps caps, disk cleanups, changing rendering mode, deleting my fast flags, restarting my pc, and nothing seems to help. Any help much appreciated.

**Comment by LordSaver** [comment]
i agree this is also happening to me please help

**Comment by LordSaver** [comment]
everytime i join a game it crashs roblox and i throught it was just roblox but instead it was bloxstap i found out by getting bloxstap out and using roblox and their are no crashs and turns out it was bloxstap but not to be mean or anything but bloxstap please do fix the problem please i beg of you please

**Comment by TOOKYOYKY** [comment]
Its because roblox patched some of the fflags so u need to change them

**Comment by Doomdoom876** [comment]
aw man that sucks
dum roblox is ruining our good client isnt it

**Comment by pizzaboxer** [comment]
@zvcee Does it happen only with Bloxstrap?

@LordSaver Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by zvcee** [comment]
Resolved randomly (i didnt change anything) thanks tho!
