### ISSUE TITLE
[BUG] It says here.. An Execptional occured while running bloxstrap and this is what it says..                  System.Runtime.InteropServices.COMException: OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))                     Please help fix this bug

### ISSUE THREAD

**Issue by Yowaki611** [pizzaboxer/bloxstrap#2063]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was changing my fast Flags and when i cliked Export Json Theres a pop up that shows and it says And execptional occured while running bloxstrap
and this is what it says..                  System.Runtime.InteropServices.COMException: OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))                     Please help fix this bug
![Screenshot 2024-06-17 021128](https://github.com/pizzaboxer/bloxstrap/assets/172997723/5608cdfc-178e-456e-949d-e1264c67a728)

![Screenshot 2024-06-17 021128](https://github.com/pizzaboxer/bloxstrap/assets/172997723/92b4ce90-de02-41b8-8fab-804fba498302)

**Comment by bluepilledgreat** [comment]
Something is preventing you from copying to the clipboard. I will add something to handle this.

**Comment by Vlad55432** [comment]
> Something is preventing you from copying to the clipboard. I will add something to handle this.

maybe it's disabled clipboard history

**Comment by pizzaboxer** [comment]
Fixed in 2.7.0
