### ISSUE TITLE
[REQ] Scan for Bloxstrap shortcuts instead of folder.

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#2064]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Can you make it scan if their is a shortcut of Bloxstrap in the Start Menu folder (%AppData%\Microsoft\Windows\Start Menu\Programs)? The reason is, Bloxstrap makes a new folder when it doesn't detect it while the shortcut of Bloxstrap is still present in the path. I like my All Apps Start Menu clean and rid of folders.

**Comment by pizzaboxer** [comment]
This isn't something we will explicitly "add support" for, as this behaviour should go away when we redo the installation system.
