### ISSUE TITLE
[BUG] Invisible menu 

### ISSUE THREAD

**Issue by Romasik1488** [pizzaboxer/bloxstrap#2066]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When im open menu i cant press any buttons like ''leave'' ''reset'' 
![image](https://github.com/pizzaboxer/bloxstrap/assets/171415396/4b0b54e0-db42-483e-ac69-fe787a490ddd)

**Comment by Romasik1488** [comment]
its happening if i press escape 2nd time

**Comment by bluepilledgreat** [comment]
Does this problem still occur if you delete all your fast flags?

**Comment by Romasik1488** [comment]
> Does this problem still occur if you delete all your fast flag
i dont have my custom fast flags

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
