### ISSUE TITLE
[BUG] Bloxstrap Crashing

### ISSUE THREAD

**Issue by AmeLooksSus** [pizzaboxer/bloxstrap#2070]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap is crashing upon opening and this is the notification that shows up when it crashes.
![image](https://github.com/pizzaboxer/bloxstrap/assets/119868491/798d7c58-7c31-432c-9837-e5cedad15c63)

**Comment by CoralDev0** [comment]
Try to reinstall bloxstrap or roblox itself if it dosent work then just goto this [this link #635](https://github.com/pizzaboxer/bloxstrap/issues/635)
