### ISSUE TITLE
[Bug] Some freezing bug

### ISSUE THREAD

**Issue by sqpeedyy** [pizzaboxer/bloxstrap#2073]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Ok so this problem has been happening to me from like a month but in the past week it has became worse the bug is like the game fully freezes for either 3-5 seconds or stutters then freezes and i have tried looking for fixes and nothing helped it just stayed

**Comment by elmarco12** [comment]
same issue

**Comment by pizzaboxer** [comment]
Does it happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
