### ISSUE TITLE
[REQ] Feature to re-enable multi-instance at our own risk.

### ISSUE THREAD

**Issue by TERIHAX** [pizzaboxer/bloxstrap#2074]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add back the feature to re-enable multi-instance at our own risk, even if it's sometimes a hit-and-miss, it has worked for me since the start with no error

I have read that it has been removed, please add it back with an option to enable it at our own risk.

**Comment by djphillovesyou** [comment]
Yes! I have never had one single error running 6+ accounts at once.

**Comment by AGuyNamedJens** [comment]
Won't happen, they clearly mentioned they do not want to be seen as a alt-account farming application creator..

**Comment by TERIHAX** [comment]
> Won't happen, they clearly mentioned they do not want to be seen as a alt-account farming application creator..

Well then using the Roblox Account Manager is the only option.
