### ISSUE TITLE
The True Full screen flag doesn't work.

### ISSUE THREAD

**Issue by cantagain** [pizzaboxer/bloxstrap#2075]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This Flag, "FFlagHandleAltEnterFullscreenManually": False" is now not working when it is put into the flags editor. It goes away every time it gets added and just doen't work. Please fix this because this gives me more fps when I play and so please fix this.

**Comment by pizzaboxer** [comment]
It's already there by default though? Why are you trying to add it? It tells you that too.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/32128e00-4f4d-44c6-9a50-26cfdad04e8a)
