### ISSUE TITLE
Nao abre

### ISSUE THREAD

**Issue by bolinhaHunter** [pizzaboxer/bloxstrap#2076]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

O meu windows esta protegendo quando eu executo

**Comment by Vlad55432** [comment]
Se você está falando de uma tela inteligente, tudo bem. Basta clicar nos botões "Saiba mais" e "Permitir".
