### ISSUE TITLE
[BUG] Whenever I open Blox Strap, it still opens the Desktop App even though I have it disabled

### ISSUE THREAD

**Issue by Hyperiab** [pizzaboxer/bloxstrap#2077]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have made sure many times to have Disable Desktop App enabled, and throughout all of that I still have the Roblox app opening whenever I ALT+F4 while in loading screen or press Play Roblox

So far the only solution I found was by completely reinstalling both BloxStrap and Roblox, but I personally believe I shouldn't have to do all that for a simple bug fix like making sure the settings actually save.

Attached is evidence that this is a bug

https://github.com/pizzaboxer/bloxstrap/assets/173094500/e2174f85-98d2-4351-b11f-c4470926d3d3

Normally when you press "Play Roblox" while having the desktop app disabled it should open "roblox.com/discover". 

Hopefully this dumb issue gets fixed because it's so annoying whenever it happens and sometimes even though I uninstall and reinstall everything. I still have the issue.

**Comment by bluepilledgreat** [comment]
Disabling desktop app has been removed due to instability
