### ISSUE TITLE
[REQ] Update winget release

### ISSUE THREAD

**Issue by Vlad55432** [pizzaboxer/bloxstrap#2078]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

that's all
![fb4c18a5-9367-4770-b99f-7518c72db482 5609c32e87a3110b734aad048bf9fe35-2326121291](https://github.com/pizzaboxer/bloxstrap/assets/78297186/dde1bee9-8478-4c21-a0c6-83688b566de3)

**Comment by bluepilledgreat** [comment]
@pizzaboxer

**Comment by WaviestBalloon** [comment]
@pizzaboxer

**Comment by pizzaboxer** [comment]
Give it a few days: https://github.com/microsoft/winget-pkgs/pull/157909
