### ISSUE TITLE
[BUG] Multi-instance launch not working

### ISSUE THREAD

**Issue by eduluz23** [pizzaboxer/bloxstrap#2081]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Multiple instance launcher isn't working. I open a game on my main browser with my account, then with an alt, on another browser, I open the same game (although not on the same server), and a warning immediately pops up asking me to confirm opening a new tab, and that opening said tab would make the current (open) tab close.

**Comment by t6rtar** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/155864427/7f447c82-6031-4e76-a923-2a12c827b2ed)
