### ISSUE TITLE
[BUG] connectivity error

### ISSUE THREAD

**Issue by Legacy-max** [pizzaboxer/bloxstrap#2082]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

this happend an hour ago and idk what to do i keep on getting this error System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:8080)

[Inner Exception]
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it. about connectivty and idk what to do
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/173113205/c22e9d6f-bc7c-413b-9ace-87e76e959494)

**Comment by Legacy-max** [comment]
any advice

**Comment by pizzaboxer** [comment]
https://us.battle.net/support/en/article/23664
