### ISSUE TITLE
[BUG]  escape menu in roblox

### ISSUE THREAD

**Issue by agoomy** [pizzaboxer/bloxstrap#2085]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i set the bloxstrap escape menu in roblox to 2015 and I saved it every time I launch blackstrap its the current escape menu I tried the other ones and it works perfectly fine.

**Comment by AttakDoge** [comment]
currently have this problem, using the flags as shown [here](https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version)

**Comment by agoomy** [comment]
i imported the flags from the copy button and is shows them in the fast flag editor and shows that there false but it still doesn't work I've tried saving a few times and made sure that its set to version 1 2015

**Comment by ShakeAndWiggle20** [comment]
Import this JSON into the FastFlags editor: 
`{
    "FFlagEnableInGameMenuChromeABTest3": "False",
    "FFlagEnableReportAbuseMenuRoactABTest2": "False"
}`

**Comment by agoomy** [comment]
tysm it worked finally

**Comment by agoomy** [comment]
also if you do this make sure these are the only scripts or it wont work
