### ISSUE TITLE
[REQ] add an option to remove the "roblox is currently running and launching another instance" prompt

### ISSUE THREAD

**Issue by kayceeayeue** [pizzaboxer/bloxstrap#2086]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

this just becomes tedious after a while as someone with only one monitor

**Comment by mlo12345** [comment]
It's doing this for me sometimes even after I've already closed the instance. It's getting really annoying & needs an option to disable

**Comment by TopZert** [comment]
what can i do to fix this?

**Comment by bluepilledgreat** [comment]
Duplicate issue

**Comment by tookender** [comment]
@bluepilledgreat Why will this not be added? It would greatly increase the user experience for me, as it is breaking some things on my end. For some reason the pop-up opens like 500 times when I lose internet and my program tries to reconnect.

**Comment by bluepilledgreat** [comment]
> @bluepilledgreat Why will this not be added? It would greatly increase the user experience for me, as it is breaking some things on my end. For some reason the pop-up opens like 500 times when I lose internet and my program tries to reconnect.

Never said this would not be added. This is a duplicate issue. There is already an option to toggle the warning in the main branch. Please be patient.
