### ISSUE TITLE
[BUG] I can't use the old Roblox Menu.

### ISSUE THREAD

**Issue by Hyperiab** [pizzaboxer/bloxstrap#2087]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2 hours ago it was working perfectly fine until Bloxstrap forced me to update to 2.6.1 and I suddenly couldn't use the 2015 menu.

The bug is I cannot use the Roblox 2015 menu even though I have it selected in the Bloxstrap Menu. I made sure to select "Version (2015) in "escape menu setting" and I even made sure to press "Play Roblox" to make sure the changes are saved. So far, everything else works but this one thing which has been bugging me everytime it auto updates to 2.6.1 and I have to manually download 2.5.4

Attached is evidence of this issue that is so annoying
https://github.com/pizzaboxer/bloxstrap/assets/173094500/07236339-98fa-4935-b62c-2524849cd024

Please tell me of a solution if there is any. Because the Roblox new 2024 menu is so unbearable and ugly to look at. I will literally go insane if I have to look at this new Roblox menu for any longer.

**Comment by TimMarvelHero** [comment]
This is the same thing happening to me

**Comment by CoalTheFirst** [comment]
I'm having the same problem.

**Comment by KitcatDreemurr** [comment]
I know this account is fresh, but I'm also experiencing the same issues with Roblox not allowing the Version 1 menu. I've tried setting the "FFlagEnableInGameMenuChromeABTest2" and "FFlagEnableReportAbuseMenuRoactABTest2" flags to false, as well as freshly installing Roblox, both of which had no effect on changing the Roblox menu that is used. I don't have any other Fast Flags changed, and something else I'd like to note is that I seemed to have the same issues on version 2.5.4 (before updating). Unless there's a new set of flags needed, I'm not sure what could be causing this.

**Comment by ShakeAndWiggle20** [comment]
You should use this instead:
`{
    "FFlagEnableInGameMenuChromeABTest3": "False",
    "FFlagEnableReportAbuseMenuRoactABTest2": "False"
}`

**Comment by KitcatDreemurr** [comment]
> You should use this instead: `{ "FFlagEnableInGameMenuChromeABTest3": "False", "FFlagEnableReportAbuseMenuRoactABTest2": "False" }`

Just realized I never replied, but this worked out. Hopefully this works out for everyone else.

**Comment by MagicDippyEgg** [comment]
no longer works anyone know how to fix it

**Comment by Logiebogieboo** [comment]
> You should use this instead: `{ "FFlagEnableInGameMenuChromeABTest3": "False", "FFlagEnableReportAbuseMenuRoactABTest2": "False" }`

whats the title?
