### ISSUE TITLE
i cant remove the custom like that hotbar with bloxstrap,i really want it off

### ISSUE THREAD

**Issue by Astornautjelly** [pizzaboxer/bloxstrap#2089]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

here is a foto of it
![Screenshot 2024-06-18 091520](https://github.com/pizzaboxer/bloxstrap/assets/149877784/6014fe23-974d-4e1e-9075-10a27dea553f)

**Comment by alexanton25** [comment]
You should try using the following FFlags:
```
{
  "FFlagEnableInGameMenuChrome": "False",
  "FFlagEnableInGameMenuChromeABTest2": "False"
}

```

**Comment by myusername450** [comment]
> You should try using the following FFlags:
> 
> ```
> {
>   "FFlagEnableInGameMenuChrome": "False",
>   "FFlagEnableInGameMenuChromeABTest2": "False"
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/56791645/340609974-9476ae26-50c1-4d63-abc4-aaf13867ea3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzEwOTUsIm5iZiI6MTcxODczMDc5NSwicGF0aCI6Ii81Njc5MTY0NS8zNDA2MDk5NzQtOTQ3NmFlMjYtNTBjMS00ZDYzLWFiYzQtYWFmMTM4NjdlYTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE3MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjBjMTg5YjRhZWVjN2VhMDQ2MTdkZGIzOWYzNDhiOTAyMmE3NzA4MTU0MjMxM2MxYTk4MDZlNzIyZTk4ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3aCFYukMYxqIkoZ5SVcBpw6Kmz3zEBEKEuhD14ypVXc) ![image](https://private-user-images.githubusercontent.com/56791645/340610263-38f27da1-5f8b-4c82-bf12-88cda2484851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzEwOTUsIm5iZiI6MTcxODczMDc5NSwicGF0aCI6Ii81Njc5MTY0NS8zNDA2MTAyNjMtMzhmMjdkYTEtNWY4Yi00YzgyLWJmMTItODhjZGEyNDg0ODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE3MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGQ2N2VhYWMyODE1N2EwOGFjOThlMWIzMjBiODk4YWIxM2M4OTcxYTNkMDYxM2QxNThlMzJiZmY4ZDc2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uipCukxwhEGJL9nrWpT5TTcDdphcmnb6JNdEd5AuC94) ![image](https://private-user-images.githubusercontent.com/56791645/340610426-1ff51093-f6d5-48b8-9d02-be573cd1e3dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzEwOTUsIm5iZiI6MTcxODczMDc5NSwicGF0aCI6Ii81Njc5MTY0NS8zNDA2MTA0MjYtMWZmNTEwOTMtZjZkNS00OGI4LTlkMDItYmU1NzNjZDFlM2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE3MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjA3ZGVjOWM2MmI1NzdiYTg2Y2MwNDk1MTAzOGRhYjBhZTYxOTE2NWMzZGJiZDhkNDZlYTdlZjI2MmIyZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjsER3XiwiOYkclty54pBlEYfS_I1PyVVSaC28zvV-g)

it didnt work

**Comment by CrescendoDecrescendo** [comment]
i also have the same issue and followed the steps above, it didnt work for me either.

**Comment by CrescendoDecrescendo** [comment]
Nvm I found a solution, credits to Sky (Sky
0100152000022000)

Use the following fastflag and it should fix it

{
  "FFlagEnableInGameMenuChromeABTest3": "False"
}

**Comment by alexanton25** [comment]
Oh I had an outdated list

**Comment by Astornautjelly** [comment]
thx
