### ISSUE TITLE
[BUG] Can't download bloxtrap

### ISSUE THREAD

**Issue by Pasha-code-callab** [pizzaboxer/bloxstrap#2093]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20240618T111018Z.log](https://github.com/user-attachments/files/15885237/Bloxstrap_20240618T111018Z.log)

**Comment by pizzaboxer** [comment]
Does the original launcher work?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
