### ISSUE TITLE
Escape menu not changing

### ISSUE THREAD

**Issue by DDDAV123** [pizzaboxer/bloxstrap#2097]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I obviously saved the settings to the 2015 escape menu and its still giving me the latest menu which is really annoying and i tried uninstalling  it and everything even roblox but it still doesnt work.

**Comment by CoalTheFirst** [comment]
how did you fix it?

**Comment by shurahgolden** [comment]
i found a temp solution:
turn pc on and off via holding the power button,
force reinstall roblox via bloxstrap's menu,
type 'Play Bloxstrap' via windows search bar, and quickly join a game,
and it'll likely work normally till you leave the game.

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
