### ISSUE TITLE
[REQ] please add multi instance again

### ISSUE THREAD

**Issue by bananapeel908** [pizzaboxer/bloxstrap#2098]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

it was the feature that was most useful and was so good, now i would have to download from somewhere sketchy and risk getting a virus, i dont know what programs to trust and maybe if you have a program you could recommend me that has multi instance launching that would be much appreciated

**Comment by shurahgolden** [comment]
![236662271-ce6bc2c8-7690-436a-97d0-1cfea56b541f](https://github.com/pizzaboxer/bloxstrap/assets/87254883/1812aed3-03b1-46d2-8131-5042b3a89e28)
it was likely removed due to Roblox Byfron developer warning users to not use it, as it **may** be considered malicious behavior.

**Comment by ilan0098** [comment]
so it's basically against their ToS now? imagine getting banned for playing on two account at the same time on the same machine
