### ISSUE TITLE
[BUG] i am not able to play roblox all of a sudden.

### ISSUE THREAD

**Issue by Bright1Darkness** [pizzaboxer/bloxstrap#2099]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

its giving me an error ""System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).""
and suddenly not letting me play :(
[Uploading Bloxstrap_20240618T162925Z.log…]()

**Comment by CfwSky** [comment]
update to 2.6.0 if you havent already

**Comment by pizzaboxer** [comment]
You're on an outdated version. [Install the latest version.](https://github.com/pizzaboxer/bloxstrap/releases/latest)
