### ISSUE TITLE
"Bloxstrap is already running. Please close any open Bloxstrap window."

### ISSUE THREAD

**Issue by Profility** [pizzaboxer/bloxstrap#21]
I have an extension called [RoGold](https://rogold.me/) installed on my browser that lets me pin certain games on my homepage
![unknown](https://user-images.githubusercontent.com/72250349/193376788-e92f2d5f-8014-4b3d-9b0f-cb9a3c22ad56.png)

But when I try to click the "play" button, this error pops up from Bloxstrap:
![unknown](https://user-images.githubusercontent.com/72250349/193376821-8da0f735-f365-44aa-a1fe-45fd4c3b70b7.png)

Is this the extension's fault? When I try to play games the normal way, it launches fine.

**Comment by pizzaboxer** [comment]
I've just released [v1.4.4](https://github.com/pizzaboxer/bloxstrap/releases), which should allow for more leniency in regards to multiple instances of Bloxstrap/Roblox being open. Try it, and if it still doesn't work then I'll investigate.

**Comment by Profility** [comment]
Newly released version has fixed the issue; thanks
