### ISSUE TITLE
Ive tried ZLive and zwinplayer64 but they dont work

### ISSUE THREAD

**Issue by CodeErrorVarString** [pizzaboxer/bloxstrap#210]
I try ZLIVE but ill it gives it the error 272
then I try zwinplayer64 it lets me into roblox but no 32-bit
Im on a Windows 10 
![Screenshot 2023-05-06 114418](https://user-images.githubusercontent.com/113734127/236585569-f8c9617c-3399-4af6-b279-d71f46ef008c.png)

**Comment by EasternBloxxer** [comment]
You can only play on 64 bit channels as of now. (Channels like live and zcanary)

**Comment by CodeErrorVarString** [comment]
oh ill try zcanary

**Comment by CodeErrorVarString** [comment]
Will there one day be a update that allows to change roblox to 32bit with a 64bit computer

**Comment by CodeErrorVarString** [comment]
Wait nvm there wont.
