### ISSUE TITLE
[BUG] using multi instance with RAM gives the warning at the opening of every instance, even the forst one

### ISSUE THREAD

**Issue by NukeThief** [pizzaboxer/bloxstrap#2100]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Basically, BS now has a feature that warns before an instance gets replaced. but it makes multi instance be kinda annoying to use, so please add an optiion to disable that warning.

**Comment by CfwSky** [comment]
it will be added in a future update (or you download an unreleased one from actions)

**Comment by pizzaboxer** [comment]
Duplicate of #2011
