### ISSUE TITLE
The hotbar and the escape menu isnt changing to the 2015 version

### ISSUE THREAD

**Issue by myusername450** [pizzaboxer/bloxstrap#2101]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Basically, whenever i launch roblox, i noticed that the hotbar and the escape menu has reverted back to the 2023 version, i even pasted a json code to fix this and it actually did nothing
![image](https://github.com/pizzaboxer/bloxstrap/assets/173188054/09b12b6f-733e-4413-a716-33851b1c62c1)
![image](https://github.com/pizzaboxer/bloxstrap/assets/173188054/e8357e1c-e9fe-4dbe-8d3f-bb5792d58dee)

I have also used the json script which are these things 
![image](https://github.com/pizzaboxer/bloxstrap/assets/173188054/9b0bcd97-6fac-4140-b462-538a556700a8)
![image](https://github.com/pizzaboxer/bloxstrap/assets/173188054/0fb37606-d983-4475-aedf-ccd99e39b519)

i dont know why the escape menu and the hotbar isnt changing before, and im also aware that other people had this same problem so yeah

**Comment by ShakeAndWiggle20** [comment]
Yeah that's Roblox with their stupid restrictions. You should try reinstalling Bloxstrap and then adding the `{
    "FFlagEnableInGameMenuChromeABTest2": "False",
    "FFlagEnableReportAbuseMenuRoactABTest2": "False"
}` to your FastFlags again. If it doesn't work, then Roblox might have patched this and then we are all cooked.

**Comment by ShadowCodeX-debug** [comment]
@ShakeAndWiggle20 do you need the second flag?

**Comment by CoalTheFirst** [comment]
alright so you have to renstall bloxstap but before you install it put these fast flags in to fix it { "FFlagEnableInGameMenuChromeABTest3": "False", "FFlagEnableReportAbuseMenuRoactABTest2": "False" }

**Comment by Logiebogieboo** [comment]
what version is this and if it still works

**Comment by nabheyka880** [comment]
you can't get older menus anymore

**Comment by FranciscoElHuevo** [comment]
I Need Help Where I Find Fast Flags

**Comment by nabheyka880** [comment]
it's gone because roblox removed almost all of them and the ones allowed are useless
