### ISSUE TITLE
[BUG] Huge fps decrease when installing bloxstrap for the first time

### ISSUE THREAD

**Issue by meat9483786** [pizzaboxer/bloxstrap#2102]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-06-17 213151](https://github.com/pizzaboxer/bloxstrap/assets/173116188/d987f51a-6e7a-41a7-ad25-a333f571a18c)
When i downloaded bloxstrap for the first time, my fps decreased tremendously. For example, in dahood i would average about 130 - 190 fps and now i average 40 - 90. Before downloading bloxstrap i would not have any problems with fps. After having this problem i deleted bloxstram but my fps was still nto fixed. One thing i should add is i pasted one of those "fast flags" that supposedly boost fps. This could be the reason of my fps drop but im not sure at this point. if this is the main reason please tell me how to fix it.

![Screenshot 2024-06-17 213232](https://github.com/pizzaboxer/bloxstrap/assets/173116188/26375f72-d58f-4bd2-b946-c56000a92ee2)

**Comment by pizzaboxer** [comment]
> One thing i should add is i pasted one of those "fast flags" that supposedly boost fps. 

Are you telling me you somehow managed to not see this massive warning that we shoved in your face?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/76ad31f0-671b-4701-a1a1-fb8b966280b9)

Did you not try removing everything you configured to see if that would change anything?

**Comment by meat9483786** [comment]
nah I saw it lol, other fastflags that I used the past worked so I assumed the one I pasted worked. I  did try to remove everything I configured by deleting them and then deleting bloxstrap but nothing changed. I get back from vacation tomorrow and I’ll try to see if ur suggestion works

**Comment by meat9483786** [comment]
I tried removing everything and nothing changed

**Comment by pizzaboxer** [comment]
> I tried removing everything and nothing changed

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by meat9483786** [comment]
alr here 
![Screenshot 2024-06-30 143824](https://github.com/pizzaboxer/bloxstrap/assets/173116188/8aa26328-a29a-427f-b7a7-8383ad6ad054)
![Screenshot 2024-06-30 143805](https://github.com/pizzaboxer/bloxstrap/assets/173116188/6c87e8db-7fad-4edf-8cc0-afaab7fbbda1)
![Screenshot 2024-06-30 143751](https://github.com/pizzaboxer/bloxstrap/assets/173116188/b3a5b29f-e827-496a-93fa-ce8c4947c14f)

**Comment by pizzaboxer** [comment]
> When i downloaded bloxstrap for the first time, my fps decreased tremendously. For example, in dahood i would average about 130 - 190 fps and now i average 40 - 90. Before downloading bloxstrap i would not have any problems with fps.

Since I've missed this earlier, you've also double-checked that this doesn't happen without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by meat9483786** [comment]
when i tried this i was averaging about 70 - 90 fps but it would drop back to 30 - 50 sometimes

**Comment by meat9483786** [comment]
when i tried this my average fps went up by a little but not how it used to be. It would also drop to around 40 - 50 at some times and go up to 1120+ for a second.

**Comment by pizzaboxer** [comment]
> my average fps went up by a little but not how it used to be.

I'm concluding that this isn't a Bloxstrap issue then.
