### ISSUE TITLE
[BUG] EMOJI PROBLEM.

### ISSUE THREAD

**Issue by 7-7what** [pizzaboxer/bloxstrap#2104]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

WHEN EVER SOMEONE, TYPES IN CHAT WITH AN EMOJI/WHEN EVER I TYPE A EMOJI, IT'D FREEZE.
Someone please fix this bug if you could find out what causes it, cause it gets annoying when mobile players use emojis.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by 7-7what** [comment]
Sorry for not responding!! i'll give my configurations now, give me a second @pizzaboxer

**Comment by 7-7what** [comment]
[Settings.json](https://github.com/user-attachments/files/17082417/Settings.json)
[State.json](https://github.com/user-attachments/files/17082419/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/17082420/ClientAppSettings.json)


here @pizzaboxer
