### ISSUE TITLE
acc manager

### ISSUE THREAD

**Issue by IamBoblo** [pizzaboxer/bloxstrap#2105]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/173205783/eee6c70d-e553-475f-b8f5-f770f649ca8a)
i am using roblox account manager and it wont work for this can anyone help me?

**Comment by bluepilledgreat** [comment]
Duplicate issue
