### ISSUE TITLE
Kicked out of every game bug[BUG] 

### ISSUE THREAD

**Issue by Powergized** [pizzaboxer/bloxstrap#2106]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So somehow, I can't play Roblox anymore because of an error on bloxstrap which kicks me out of every game I try to play, even the ones that I haven't played before. Hopefully they fix this, and I can play Roblox
![Screenshot 2024-06-18 192417](https://github.com/pizzaboxer/bloxstrap/assets/173212533/991a1380-e384-48cd-a282-99098236e3a0)
 again.

**Comment by bluepilledgreat** [comment]
Upgrade to v2.6.1
