### ISSUE TITLE
[BUG] I got a problem with some custom emojis

### ISSUE THREAD

**Issue by ilan0098** [pizzaboxer/bloxstrap#2107]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

There is an emoji font I want to use in my game, after days of trying I figured out how to extract the emoji fonts and it seems like I succeed getting them working in the game, however they aren't shown correctly as you guys can see in the image below : 
![image](https://github.com/pizzaboxer/bloxstrap/assets/56659227/41a966af-675d-4906-a1d2-953899005f89)
How do I fix this? please help me get these emojis working with the colors, I would really like to have them in my game.

**Comment by pizzaboxer** [comment]
I won't be able to help you here because I wouldn't know myself, sorry.

**Comment by NikSavchenk0** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> ### What problem did you encounter?
> There is an emoji font I want to use in my game, after days of trying I figured out how to extract the emoji fonts and it seems like I succeed getting them working in the game, however they aren't shown correctly as you guys can see in the image below : ![image](https://private-user-images.githubusercontent.com/56659227/340879289-41a966af-675d-4906-a1d2-953899005f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzQ5MTEsIm5iZiI6MTcyMTQzNDYxMSwicGF0aCI6Ii81NjY1OTIyNy8zNDA4NzkyODktNDFhOTY2YWYtNjc1ZC00OTA2LWExZDItOTUzODk5MDA1Zjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAwMTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjExMjJkOTU0NmE1NjUzOWZjMjU2M2U5OTM3MjI3Nzg1NDJhODA1NDgzZDgxZDU0OWE5ZDdlZmZjMDZjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XqtYGKTlfeCnSpIAc5kXXisjmxRM2WCeheNdbuMWi2o) How do I fix this? please help me get these emojis working with the colors, I would really like to have them in my game.

what's name emojifont?
