### ISSUE TITLE
[BUG] no import JSON only export

### ISSUE THREAD

**Issue by Noahfslol** [pizzaboxer/bloxstrap#2108]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when I went to import my JSON it only had an export option.

**Comment by pizzaboxer** [comment]
It was moved here.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/f7b14aee-41e2-4ea1-9f6c-94647487bf6d)
