### ISSUE TITLE
Unable to open Bloxstrap post-update

### ISSUE THREAD

**Issue by tlsctf2** [pizzaboxer/bloxstrap#211]
What it says on the tin. I tried to run my already-installed version of Bloxstrap after the last update, but it won't run (it opens the update screen for a split second but that closes without doing anything). I tried downloading the new installer to try and fix it, but that won't run either. I also tried running the v2.2.0 x86 installer, but that ALSO won't run (also does the "opens briefly but closes without doing anything" thing). I assume this is an issue with the whole 32-bit thing, but I'm not sure how to go about fixing it.

**Comment by pizzaboxer** [comment]
Run the v2.3.0 executable directly again, and send me the latest log file from the Bloxstrap Logs folder.

**Comment by tlsctf2** [comment]
assuming you mean the one in the releases tab, it does not create a log file. the program doesn't make any attempt to launch, even when I run it as administrator. the x64 version of 2.2.0 also did this, but I could fix the problem then by just using the x86 build instead.

**Comment by pizzaboxer** [comment]
Oh, this is sounding like a .NET runtime problem. Here, can I quickly check what versions of the .NET runtime you have installed? Just search "runtime" in Apps & features.
![image](https://user-images.githubusercontent.com/41478239/236612803-a168cf63-158b-4bec-b36a-f16e32bd1741.png)

**Comment by tlsctf2** [comment]
here's the ones I've got
![image](https://user-images.githubusercontent.com/23440256/236612885-3f19bdf4-7a98-4590-a32f-da1fd00270b6.png)
(idrk how GitHub issues work so hopefully that just pastes directly in, will reply again if not)

**Comment by pizzaboxer** [comment]
Yep, you don't have the latest version of the x64 runtime installed. [Here, install it](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer). While you're at it, after that's done, you can remove the old one for '6.0.0 (x64)'.

**Comment by tlsctf2** [comment]
looks like that did it. I like holding on to old runtimes just in case something crops up and something needs reverted, but the program works, so I'll take that and run with it. glad it was something easy and I'm not just cursed forever. thanks!

**Comment by pizzaboxer** [comment]
You can uninstall the older versions since any minor version (like 6.0.16) will automatically cover older minor versions (6.0.0 - 6.0.15).
