### ISSUE TITLE
[BUG] Allow Multi-Instance launching is gone and does not work. 

### ISSUE THREAD

**Issue by kyourandesu** [pizzaboxer/bloxstrap#2112]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Multi-Instance launching is gone and i cannot open more than 1 instances

![Screenshot 2024-06-19 211643](https://github.com/pizzaboxer/bloxstrap/assets/104125080/16ef5d23-bdba-4d9b-8df2-b2e19be158c2)

**Comment by Hydatos** [comment]
Multi-Instance launching was removed in Release V2.6.0. Please use a different app to open multiple Roblox instances.

**Comment by kyourandesu** [comment]
> Multi-Instance launching was removed in Release V2.6.0. Please use a different app to open multiple Roblox instances.

why was it removed? did roblox changed its TOS?

**Comment by Hydatos** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
Here.
