### ISSUE TITLE
[BUG] Bloxstrap doesn't open.

### ISSUE THREAD

**Issue by Kokki15** [pizzaboxer/bloxstrap#2113]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to open bloxstrap it stops at "Starting Roblox" and then it says : Roblox crash : An unexpected error occured and Roblox needs to quit. We're sorry. I can launch Roblox just fine, but not bloxstrap. How do I fix this?
![Screenshot 2024-06-19 170403](https://github.com/pizzaboxer/bloxstrap/assets/173280182/964c5632-9cc2-4922-bd70-232f9c2f8d32)

**Comment by Kokki15** [comment]
And when I try through the website, it shows a full white screen and the error in the middle.

**Comment by pizzaboxer** [comment]
Is this still happening?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
