### ISSUE TITLE
[WIKI SUGGESTION] A simple fix to the now patched fix for removing the Chrome UI

### ISSUE THREAD

**Issue by ShakeAndWiggle20** [pizzaboxer/bloxstrap#2114]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Two days ago Roblox rolled out a new version of the Chrome UI. This patched the fix to the Chrome UI mentioned in the Wiki:
![image](https://github.com/pizzaboxer/bloxstrap/assets/77622308/5520924d-95af-4130-a594-b376ec3760ec)

This is now incorrect, and there are many people adding issues because they get the Chrome UI and don't know how to get rid of it. I suggest updating the Wiki with the following code:

`{
    "FFlagEnableInGameMenuChromeABTest3": "False",
    "FFlagEnableInGameMenuChromeABTest2": "False",
    "FFlagEnableReportAbuseMenuRoactABTest2": "False"
}`.
This way, the Chrome UI gets removed again because the FastFlags are now active on the new version AND of the old one. So if someone still has the old Chrome UI for some reason, it also gets removed. The Report Menu has no new version, so I left that one unchanged.

**Comment by angeerey** [comment]
It works, thanks

**Comment by Sethilliano** [comment]
Epic!

**Comment by applegookle** [comment]
thanks man

**Comment by pizzaboxer** [comment]
Thanks.
