### ISSUE TITLE
[REQ] Readd Old Desktop App Disabling Method (As a subtoggle) +Extra

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#2116]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Title says it all; readd the old version of disabling the Desktop App but, as a sub-toggle underneath the new one.

Also I don't fully know how it the old method worked but I think it was adding a dummy Mobile.rbxl, which was probably the problem because when I fully remove the Mobile.rbxl, it works just fine; no errors. So I'm thinking, you could just make it remove it completely, if you can't add it back, make it say before you can enable the option, "Warning: This setting deletes a file and cannot be readded until Roblox is reinstalled."

**Comment by pizzaboxer** [comment]
Issue should be fixed as discussed in #2049
