### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Iheartcats24** [pizzaboxer/bloxstrap#2117]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it doesnt show the multi account launching thing

**Comment by ShadowCodeX-debug** [comment]
Bloxstrap Versions 2.6.0 and above will no longer have Multi-Instancing.

**Comment by ghostjira** [comment]
> Bloxstrap Versions 2.6.0 and above will no longer have Multi-Instancing.

why's that?

**Comment by pizzaboxer** [comment]
> why's that?

https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
