### ISSUE TITLE
2015 escape menu not working

### ISSUE THREAD

**Issue by gliblys** [pizzaboxer/bloxstrap#2118]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I use the 2015 escape menu, it does not show up anymore and is the the normal 2024 menu.

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
