### ISSUE TITLE
[BUG] Roblox shows the crash box while I can still play

### ISSUE THREAD

**Issue by TotallyAC0der** [pizzaboxer/bloxstrap#2120]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This only happens with the Bloxstrap bootstrapper too.

**Comment by TotallyAC0der** [comment]
nvm, i fixed it myself

**Comment by Doomdoom876** [comment]
how did u fix it
