### ISSUE TITLE
[BUG] XBOX Gmae bar recording lag

### ISSUE THREAD

**Issue by YoQuantum** [pizzaboxer/bloxstrap#2121]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to record a video using xbox gamebar on bloxstrap it gives me a huge fps drop, and i'm pretty sure that the issue is a bloxstrap setting that triggers the recording, because when i tried to record on the roblox normal player it didn't lag at all + no fps drop.

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
