### ISSUE TITLE
[BUG] when install sends an error (and launching)

### ISSUE THREAD

**Issue by nikita741852** [pizzaboxer/bloxstrap#2122]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (127.0.0.1:65123)

[Inner Exception]
System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

**Comment by pizzaboxer** [comment]
See this: https://us.battle.net/support/en/article/23664
