### ISSUE TITLE
[BUG] "Allow Multi-Instance Launching" doesn't appear

### ISSUE THREAD

**Issue by ghostjira** [pizzaboxer/bloxstrap#2124]
![image](https://github.com/pizzaboxer/bloxstrap/assets/173363369/b477b38b-6c66-4493-ba3e-dbebcf78a8a0)

**Comment by loadstring1** [comment]
it got removed in latest bloxstrap 2.6.0
https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.6.0

**Comment by Jenanimation344** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/173524041/2d78574c-a3d5-4681-86f7-a769e1d5c7fc)
why theres no multi-instance in here

**Comment by loadstring1** [comment]
like i said this feature was removed in latest release of bloxstrap

sob., 22 cze 2024 o 05:40 Jenanimation344 ***@***.***>
napisał(a):
