### ISSUE TITLE
[REQ]  Roblox released the new topbar globally, can it be reverted so we can use texture packs again?

### ISSUE THREAD

**Issue by FerdomWD** [pizzaboxer/bloxstrap#2125]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

title

**Comment by ari-party** [comment]
Likely duplicate #2118

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
