### ISSUE TITLE
[BUG] i have a bloxstrap error and it says that an exception has occured 

### ISSUE THREAD

**Issue by werethehel** [pizzaboxer/bloxstrap#2126]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/173388230/9a24cacc-1480-4fcb-b661-4e9bb144f42c)

[Bloxstrap_20240620T154435Z.log](https://github.com/user-attachments/files/15916773/Bloxstrap_20240620T154435Z.log)

**Comment by pizzaboxer** [comment]
Assuming to be fixed in 2.7.0
