### ISSUE TITLE
[BUG] VC Issue

### ISSUE THREAD

**Issue by johnroblox** [pizzaboxer/bloxstrap#2130]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I use Bloxstrap, my input device in my settings doesn't show up and I can't talk through my mic but I can hear others. I've uninstalled Bloxstrap and my mic works again.

FFlags I had whilst using Bloxstrap:
[john best fflag.txt](https://github.com/user-attachments/files/15919422/john.best.fflag.txt)

Screenshots of my issue:
![microblox](https://github.com/pizzaboxer/bloxstrap/assets/173404935/34cd1402-bb8f-4ead-9e8a-489b9d8dfc17)
![micbloxstrap](https://github.com/pizzaboxer/bloxstrap/assets/173404935/e0e8e07c-073d-4ebd-a3da-973db912f9fc)

**Comment by johnroblox** [comment]
Same issue and with new settings:

[newfflag.txt](https://github.com/user-attachments/files/15920062/newfflag.txt)

**Comment by pizzaboxer** [comment]
Did you check to see if this happened with all of your configured flags deleted?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
