### ISSUE TITLE
[BUG] Some buttons, strings might overlay text, if they too long.

### ISSUE THREAD

**Issue by Vlad55432** [pizzaboxer/bloxstrap#2131]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, I tested, how it would look like, if translations already got added, and some of them got overlapped by buttons & strings
Might explained bad, just look at pics & video under..

https://github.com/pizzaboxer/bloxstrap/assets/78297186/8a7111b9-3640-4466-bfbf-545420761b28

![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/17219162-6ac7-4085-8281-f5931dce3eb9)
![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/486338ae-731e-421e-b828-1769707ac73c)
![зображення](https://github.com/pizzaboxer/bloxstrap/assets/78297186/74411f24-5446-4331-9a4f-c977c7d26015)

**Comment by Vlad55432** [comment]
@pizzaboxer

**Comment by pizzaboxer** [comment]
I closed it because you opened an issue for a version that hasn't been released yet, and that I am already well aware of.

**Comment by Vlad55432** [comment]
Oh, alright
