### ISSUE TITLE
[BUG]  Bloxtrap wont update

### ISSUE THREAD

**Issue by jackboy100509** [pizzaboxer/bloxstrap#2132]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxtrap wont update for me even when i try reinstalling so i can't use multi launch

**Comment by pizzaboxer** [comment]
I'm confused, what's not updating exactly? What tells you there's something wrong?

**Comment by jackboy100509** [comment]
so like when i update bloxtrap it brings me back to the same version

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
