### ISSUE TITLE
[BUG] Viewports/models not rendering.

### ISSUE THREAD

**Issue by LudoKatz** [pizzaboxer/bloxstrap#2133]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have been unable to replicate this issue, but I have what it is supposed to look like. I am unsure how this happened, and I have no Fastflags that are conflicting, but anyhow, here you are.

Expected action:
![Screenshot 2024-06-20 190237](https://github.com/pizzaboxer/bloxstrap/assets/103847221/9fe2e974-9593-4a95-9aca-a9804806d26d)

Resulting action:
![RobloxScreenShot20240620_190222692](https://github.com/pizzaboxer/bloxstrap/assets/103847221/6c5ee8bd-93e6-4d13-b1fa-c4cbb654a112)
![RobloxScreenShot20240620_190231421](https://github.com/pizzaboxer/bloxstrap/assets/103847221/27038c56-1450-4ddc-a56d-0b46566d42a7)

**Comment by bluepilledgreat** [comment]
If you have any fast flags, remove them.

**Comment by LudoKatz** [comment]
This was caused by the Fast Flag, ForceMSAASamples. I had it set to 8. Whoops! XD
