### ISSUE TITLE
[BUG]  Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip  Got signature: 65a83e5e7ad532e83e805a96d75e547b  Package has been downloaded to C:\Users\Gustavo\AppData\Local\Bloxstrap\Downloads\8037acc754bb397ac89c8cb29a7ddb72  Please send the file shown above in a bug report. 

### ISSUE THREAD

**Issue by RandomGuy-nobody** [pizzaboxer/bloxstrap#2134]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was installing a roblox update, but it kept on cancelling it, with the same error: Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip

Got signature: 65a83e5e7ad532e83e805a96d75e547b

Package has been downloaded to C:\Users\Gustavo\AppData\Local\Bloxstrap\Downloads\8037acc754bb397ac89c8cb29a7ddb72

Please send the file shown above in a bug report.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox

**Comment by luis40589** [comment]
Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-f9977b146957492c-RobloxApp.zip

Expected hash: 06e19510c4cc4df3ba877f1a5f545d3c
Got hash: 8793a8bebda687f0d1864cc03ab08525

**Comment by luis40589** [comment]
deu isso ai não consegui instala
