### ISSUE TITLE
[BUG] Bloxstrap.Exceptions.ChecksumFailedException:

### ISSUE THREAD

**Issue by 0x642** [pizzaboxer/bloxstrap#2136]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip

Got signature: 85a1705903055d029a8dad9dadd6b631

Package has been downloaded to C:\Users\luis\AppData\Local\Bloxstrap\Downloads\8037acc754bb397ac89c8cb29a7ddb72

Please send the file shown above in a bug report.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox
