### ISSUE TITLE
My bug when starting a roblox game

### ISSUE THREAD

**Issue by Yaser2009** [pizzaboxer/bloxstrap#2137]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

description: A Issue when I start a roblos game

**Comment by bluepilledgreat** [comment]
What does https://clientsettings.roblox.com/v2/settings/application/PCClientBootstrapper return

**Comment by bluepilledgreat** [comment]
I'm guessing this is related to the maintenance that happened a couple of days ago. If this issue persists, please create another issue.
