### ISSUE TITLE
[BUG] bloxstrap exception keeps coming up idk why

### ISSUE THREAD

**Issue by tsyehw** [pizzaboxer/bloxstrap#2138]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

this coming up idk why

System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)

[Inner Exception]
System.Exception: Deserialised application settings is null!

**Comment by bluepilledgreat** [comment]
What does https://clientsettings.roblox.com/v2/settings/application/PCClientBootstrapper respond with

**Comment by bluepilledgreat** [comment]
I'm guessing this is related to the maintenance that happened a couple of days ago. If this issue persists, please create another issue.
