### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by senyasuper9** [pizzaboxer/bloxstrap#2139]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

whenever i want to enter a private server through a link / relaunch roblox when i have it opened, this message pops up: roblox is currently running and launching another instance will close it. are you sure you want to continue launching it?
I need help getting rid of that message, it really annoys me, if you have any tips comment them down below.
![image](https://github.com/pizzaboxer/bloxstrap/assets/173183980/94a0105a-cee5-41fb-806c-01adafd91586)

**Comment by bluepilledgreat** [comment]
An option to disable this in the works
