### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CatsGang585** [pizzaboxer/bloxstrap#2144]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

BloxStrap is not loading when i play roblox. my graphics quality isnt 1 - 21. pls help

**Comment by pizzaboxer** [comment]
Launch the "Play Roblox" shortcut that's on the desktop once.
