### ISSUE TITLE
[REQ] more fps over 240?

### ISSUE THREAD

**Issue by BROISHACKING** [pizzaboxer/bloxstrap#2146]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Is their any ways to get unlimited fps like before? The official 240 limit looks really bad with screen tearing and stuttering.

**Comment by gb799** [comment]
yes you definitely can, with fast flags you can set the frame rate limit to 9999 (limitless ig), if it does not set the fps to limitless and basically limiting it with 60, you can see that wiki here https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter

**Comment by pizzaboxer** [comment]
Does setting the option in the Fast Flags section of the menu not work?

**Comment by pizzaboxer** [comment]
```json
{
    "FFlagTaskSchedulerLimitTargetFpsTo240": "False",
    "FFlagTaskSchedulerLimitTargetFpsTo2402": "False"
}
```

Open the Fast Flag editor and import this ocnfiguration, see if anything changes.

**Comment by Steakchop** [comment]
The config does work (now goes past 240 fps), but it caps yet again at 360 fps. Might be because Roblox already has future plans for additional fps caps. I don't think it's a hardware issue on my part since it's capped even on a baseplate (and I have a 3080). I tried importing the same config but with "To360" instead, but it didn't seem to make a difference.

**Comment by pizzaboxer** [comment]
> but it caps yet again at 360 fps

Are you sure that's not an OS level cap? https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter

**Comment by Steakchop** [comment]
Shoot, you're right. I forgot to set my NVCP settings for Roblox, so it just followed my global settings (V-Sync, G-Sync On). Fixing that uncapped my fps.

**Comment by pizzaboxer** [comment]
Nice to see that the flags do something, though I wouldn't recommend using them since they cap to 240 for a reason.
