### ISSUE TITLE
[REQ] pls not let app ask for .Net pls its my dream

### ISSUE THREAD

**Issue by antploooer** [pizzaboxer/bloxstrap#2147]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

remove .Net asking thing pls becuse i cant download .net pls i want bloxstrap its my happy thing

**Comment by bluepilledgreat** [comment]
.NET is required to run Bloxstrap.

**Comment by antploooer** [comment]
> .NET is required to run Bloxstrap.

they can make it without .Net

**Comment by pizzaboxer** [comment]
> they can make it without .Net

unless you're buying me a macbook that isn't going to be happening right now

how hard is it to get your dad to put his password in just this one time to install the runtime

**Comment by antploooer** [comment]
i can download .Net but its crashing i couldn't find another way

**Comment by pizzaboxer** [comment]
> but its crashing

Can you elaborate specifically what it's doing? Does it show an error message? Does it just close?

**Comment by antploooer** [comment]
it just closes with no message when i try to install bloxstrap again it asks me for .net

**Comment by pizzaboxer** [comment]
What if you try and install it with Winget? Open a Command Prompt window and paste this command in:

`winget install Microsoft.DotNet.DesktopRuntime.6`

**Comment by antploooer** [comment]
i tried it before its the same problem it doesn't show an error
