### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\renta\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.[BUG] 

### ISSUE THREAD

**Issue by justmerj** [pizzaboxer/bloxstrap#2148]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it wont let me join in on another account from another browser?

**Comment by pizzaboxer** [comment]
Did you read any relevant Wiki pages?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
