### ISSUE TITLE
[BUG] bloxstrap not launching

### ISSUE THREAD

**Issue by Sebaamstart** [pizzaboxer/bloxstrap#2149]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxstrap is not launching when i open it help (the same for roblox player)

**Comment by pizzaboxer** [comment]
> the same for roblox player

Not Bloxstrap issue then. Read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
