### ISSUE TITLE
Preferred material versions

### ISSUE THREAD

**Issue by MehKako** [pizzaboxer/bloxstrap#215]
An option like the lighting technology but for materials versions (2022 and pre2022).

**Comment by pizzaboxer** [comment]
I see the relevant flags for this (`FStringPartTexturePackTable2022`, `FStringPartTexturePackTablePre2022`, `FStringTerrainMaterialTable2022`, `FStringTerrainMaterialTablePre2022`), but are these toggleable? @EasternBloxxer

**Comment by EasternBloxxer** [comment]
> I see the relevant flags for this (`FStringPartTexturePackTable2022`, `FStringPartTexturePackTablePre2022`, `FStringTerrainMaterialTable2022`, `FStringTerrainMaterialTablePre2022`), but are these toggleable? @EasternBloxxer 

Will do some testing when I'm home

**Comment by pizzaboxer** [comment]
Just tried using the flags for `FStringPartTexturePackTablePre2022` in `FStringPartTexturePackTable2022` and looks like it actually works!

![RobloxPlayerBeta_GMdhzaG7b4](https://user-images.githubusercontent.com/41478239/236627336-e8112ae0-0e19-4c8b-a16b-142c21ce5c31.jpg)
![RobloxPlayerBeta_n0eiDQS0NS](https://user-images.githubusercontent.com/41478239/236627337-08a1a38f-66d7-43c9-bd5a-ad17d10268f3.jpg)

Still wondering if there's an easier way to switch between the two texture sets, or if we'll just have to replace the flag contents.

**Comment by Facumdou** [comment]
> Just tried using the flags for `FStringPartTexturePackTablePre2022` in `FStringPartTexturePackTable2022` and looks like it actually works!
> 
> ![RobloxPlayerBeta_GMdhzaG7b4](https://user-images.githubusercontent.com/41478239/236627336-e8112ae0-0e19-4c8b-a16b-142c21ce5c31.jpg) ![RobloxPlayerBeta_n0eiDQS0NS](https://user-images.githubusercontent.com/41478239/236627337-08a1a38f-66d7-43c9-bd5a-ad17d10268f3.jpg)
> 
> Still wondering if there's an easier way to switch between the two texture sets, or if we'll just have to replace the flag contents.
Hey man, do u know how to do that textures with "FStringPartTexturePackTablePre2022"??
