### ISSUE TITLE
i dont see an option to add multiple roblox screeens

### ISSUE THREAD

**Issue by cheeseburgers98** [pizzaboxer/bloxstrap#2150]
Hi, i wanted to add multiple roblox screens to my moniter but the option doesnt show. On youtube and other platforms it shows that under miscellaneous there should be an option to turn it on but i dont see it at all. Pleash help. 
- best regards.

1st picture shows what it looks like on youtube and your helping guide 
![Screenshot 2024-06-22 192320](https://github.com/pizzaboxer/bloxstrap/assets/173578963/8120f0f5-85aa-4b11-8458-ac612a8da6c2)

2nd picture shows it not showing (ps i looked through all of the options and it wasnt there)
![Screenshot 2024-06-22 192354](https://github.com/pizzaboxer/bloxstrap/assets/173578963/9717d777-fffb-46d3-9ae9-e928817dbd0f)

**Comment by ClaytonTDM** [comment]
This was removed in the latest version of Bloxstrap.

**Comment by Meloomazy** [comment]
may i know why did they remove it?

> This was removed in the latest version of Bloxstrap.

**Comment by gioprogamertv123** [comment]
> may i know why did they remove it?
> 
> > This was removed in the latest version of Bloxstrap.

because they want to lose half of their downloaders (real reason is that they don't want people to use it for farming)

**Comment by gioprogamertv123** [comment]
who the hell are you
