### ISSUE TITLE
The given key 'zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by Abyss790** [pizzaboxer/bloxstrap#2151]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i was trying to put in a custom font in the mod menu and an error stating "The given key 'zip' was not present in the dictionary."

**Comment by bluepilledgreat** [comment]
Only TTF, OTF and TTC files are supported. Unzip the font from the ZIP file and import that.
A fix for being able to input any files will be fixed next update.

**Comment by Abyss790** [comment]
alr thx
