### ISSUE TITLE
[REQ] _PlaceFilter support

### ISSUE THREAD

**Issue by GoingCrazyDude** [pizzaboxer/bloxstrap#2152]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Support for _PlaceFilter. Don't say no cause roblox will be removing clientsettings loading. It hasnt happened in a while so why not add this.

Something like a textbox near the enable/disable button where you can enter placeid's of games you want it to work on.

**Comment by bluepilledgreat** [comment]
Just add it in yourself

**Comment by GoingCrazyDude** [comment]
> Just add it in yourself

buddy what

**Comment by GoingCrazyDude** [comment]
if i could do it myself i wouldnt be asking for support
