### ISSUE TITLE
[BUG] when me open bloxstrap player is crash

### ISSUE THREAD

**Issue by Prkbt9** [pizzaboxer/bloxstrap#2153]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Uploading Recording 2024-06-23 172419.mp4…

**Comment by Prkbt9** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> ### What problem did you encounter?
> is broken 

Uploading Recording 2024-06-23 172419.mp4…

**Comment by Prkbt9** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> ### What problem did you encounter?
> 
> 
[Bloxstrap_25670623T102231Z.log](https://github.com/user-attachments/files/15944163/Bloxstrap_25670623T102231Z.log)

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
