### ISSUE TITLE
[REQ] ADD BACK THE MULTIPLE INSTANCE thingy

### ISSUE THREAD

**Issue by gioprogamertv123** [pizzaboxer/bloxstrap#2154]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Hello, I have read the reasons for deletion for the mutliple roblox instances. The first reason is relevant as the owner might think that it's bugged. The second and last reason are irrelevant because the owner things that people must use for his intention for like developnig games and not the farming stuff. THAT IS LITERALLY WHY HALF OF THE PEOPLE USE BLOXSTRAP!! So, bring it back.

**Comment by bluepilledgreat** [comment]
![astrollc](https://github.com/pizzaboxer/bloxstrap/assets/97983689/2ffda422-3612-4b40-8323-f8c00997032b)

**Comment by gioprogamertv123** [comment]
????

**Comment by Goofyhooda** [comment]
yes it would not work anymore it say the key is not found and would not open roblox.
