### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MarJadenFranCar** [pizzaboxer/bloxstrap#2155]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

An expception occurred while running Bloxstrap

Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip

Got signature: 8f1127dbab08208b0c26fe7640c564ba

Package has been downloaded to D:\New folder (2)\Downloads\8037acc754bb397ac89c8cb29a7ddb72

Please send the file shown above in a bug report.
![image](https://github.com/pizzaboxer/bloxstrap/assets/152232911/e67b75ea-1770-48ec-9ca2-bdb5da0c278c)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox
