### ISSUE TITLE
[REQ] Please make a "Launch warning when roblox is already open" TOGGLE.

### ISSUE THREAD

**Issue by imkrizpy** [pizzaboxer/bloxstrap#2156]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

# FEATURE REQUEST

Please make a **toggle option** for the warning message after hitting play that shows when roblox is already running. It will help alot of people because I think now that Multi-Instance is removed, majority of people who use bloxstrap also use RAM, which is a utility to run multiple clients. If implimenting this toggle button feature would not be difficult for the developers, then may I request that it be added since it will ease our use of anything regarding multi-instance launching in the future?

**I hope the devs read this. Thanks a lot!**

**Comment by KornPlays** [comment]
**bump**, this is the exact reason I'm uninstalling bloxstrap, why remove a feature and then complain about it each time trying to launch roblox?

**Comment by bluepilledgreat** [comment]
Already implemented in v2.6.2. Please be patient.

**Comment by Voyager-TW** [comment]
where to turn off it
