### ISSUE TITLE
[BUG] Bloxstrap triggering Roblox anticheat

### ISSUE THREAD

**Issue by 21Legendz** [pizzaboxer/bloxstrap#2158]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When launching Roblox with Bloxstrap, it now shows this error every time and forces Roblox to crash. This doesn't happen with regular Roblox. I haven't configured anything in the last couple of days so I believe this is the result of an update they might've pushed out today, so it doesn't seem like this is the cause of any specific FFlags (i'm not using any custom ones apart from the ones provided in the launcher, either).

![Untitled](https://github.com/pizzaboxer/bloxstrap/assets/80059296/7e3f7b3e-4bed-4a34-94cf-520785f49191)

edit: just realized i should've put this in the megathread, sorry about that

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration
