### ISSUE TITLE
Input Latency within Roblox client

### ISSUE THREAD

**Issue by MyszekGlonojad** [pizzaboxer/bloxstrap#216]
this probably isn't an issue with Bloxstrap itself, but I can't seem to find an answer anywhere, the client has input latency with the camera, when I unlock my fps, or when my mouse polling rate is higher. When I have 60 fps the input latency is slightly lower. This happens on 64bit and never happened on 32bit, really strange problem. Do you know the potential cause perhaps? This does affect any gameplay that involves mostly camera/cursor manipulation.

**Comment by pizzaboxer** [comment]
Yeah, I've got basically nothing for you. Just to be sure, you've tried running Roblox without Bloxstrap installed, right? Otherwise, looks like it's something you'll have to bring up with Roblox somehow.

**Comment by MyszekGlonojad** [comment]
It's the same without Bloxstrap, how do I contact Roblox so that they do anything, or at least have a human respond to me instead of a bot?

**Comment by pizzaboxer** [comment]
I'll find a way...

**Comment by pizzaboxer** [comment]
Oh, seems like they probably already know about it.

https://devforum.roblox.com/t/update-to-input-processing/2232983/43?u=xtremeguy2256
https://devforum.roblox.com/t/switching-roblox-to-run-on-my-cpu-instead-of-gpu/2320773?u=xtremeguy2256

Just sit back and hang tight, I guess.
