### ISSUE TITLE
[BUG] Bloxstrap refuses to run showing error about needing lower priviliges despite not having administrative mode enabled

### ISSUE THREAD

**Issue by Icelogist** [pizzaboxer/bloxstrap#2161]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I keep getting this error when trying to run bloxstrap, I don't have administrative privileges enabled and I even tried using administrative privileges as a test and it still didn't work.
![image](https://github.com/pizzaboxer/bloxstrap/assets/111094215/13fd9f7b-b073-4a0c-acd3-bb05eb095a82)

**Comment by bluepilledgreat** [comment]
This check was removed in v2.6.1. Download it here: https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.6.1

**Comment by Icelogist** [comment]
Closing because issue has been resolved
