### ISSUE TITLE
[BUG] An exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by idk43124** [pizzaboxer/bloxstrap#2163]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I set up the settings and installing the changes, I get an error with the Bloxstrap_20240624T134846Z.log folder, namely Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-6b63ea89d2e54fd7-RobloxApp.zip

Got signature: a6f16aec97dba291a5eb492adab48602

Package has been downloaded to C:\Users\MyUserName\AppData\Local\Bloxstrap\Downloads\8037acc754bb397ac89c8cb29a7ddb72

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox
