### ISSUE TITLE
[BUG] I CANT UNINSTALL BLOXTRAP EVEN IN THE PANNEL

### ISSUE THREAD

**Issue by Saaaaaazazaza** [pizzaboxer/bloxstrap#2164]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cannot uninstall bloxtrap it does not show up on the pannel thing 
![image](https://github.com/pizzaboxer/bloxstrap/assets/173703698/634ed097-3e5d-47ed-9741-107f8ea7b388)

**Comment by sshonkk-win** [comment]
You can uninstall bloxstrap from the bloxstrap menu

**Comment by playervalley** [comment]
@sshonkk-win That links to the Wiki, which just tells you to go to the same page.

In the case that you don't see Bloxstrap on the Control Panel, you can uninstall Bloxstrap by the command line. Navigate to where Bloxstrap is installed, run a Command Prompt there and type:
```
Bloxstrap -uninstall
```

**Comment by pizzaboxer** [comment]
Open a Command Prompt window and run this command:

`%localappdata%\Bloxstrap\Bloxstrap.exe -uninstall`
