### ISSUE TITLE
[BUG] System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set. And expection occured while Running Bloxstrap.

### ISSUE THREAD

**Issue by Nate2971** [pizzaboxer/bloxstrap#2166]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i Encounter An expection while running an occupied Bloxstrap It Said it On My Screen.

**Comment by pizzaboxer** [comment]
Send the log file please

**Comment by pizzaboxer** [comment]
Something is preventing Bloxstrap from connecting to the internet. Likely your antivirus. Check it and make sure it isn't interfering with anything.
