### ISSUE TITLE
crash when i click on show desktop button

### ISSUE THREAD

**Issue by ceat-ceat** [pizzaboxer/bloxstrap#217]
whenever i click on the show desktop button in the taskbar, roblox immediately crashes and only after i click OK on the crash message will the desktop appear
happens 100% of the time and does not happen with bloxstrap uninstalled
no special error code or anything just the generic crash message
![image](https://user-images.githubusercontent.com/67209229/236655173-bf7f3520-5fd5-43f7-bbd8-f8e60f47e9cb.png)
[0.574.1.5740447_20230507T025335Z_Player_0F0F1_last.log](https://github.com/pizzaboxer/bloxstrap/files/11413791/0.574.1.5740447_20230507T025335Z_Player_0F0F1_last.log)
also unsure if it is related or intentional or not but the crash message also pops up when i exit roblox

**Comment by pizzaboxer** [comment]
That's a Roblox problem, not a Bloxstrap problem. I've been having the same thing.

**Comment by pizzaboxer** [comment]
I just did some quick testing and I found out that this only happens if I use the Vulkan renderer. Do you have it enabled too?

**Comment by EasternBloxxer** [comment]
I dont get a crash but a white screen when doing that with Vulkan renderer but enabling FFlagRenderVulkanFixMinimizeWindow seems to fix the issue for me

https://user-images.githubusercontent.com/54174182/236671519-7d264c44-b4b9-4fe8-9cc7-8e8b41fb64bb.mp4


https://user-images.githubusercontent.com/54174182/236671575-3ca37d57-177f-427f-a39a-cbac080eb107.mp4

**Comment by ceat-ceat** [comment]
yes i have vulkan renderer selected

**Comment by pizzaboxer** [comment]
Oh, there's a flag for it... god damn it.
