### ISSUE TITLE
[BUG] Problem after an account gets a ban.

### ISSUE THREAD

**Issue by Imbluecat** [pizzaboxer/bloxstrap#2170]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After I get a ban on one account I keep getting the error 403 even after I change account. It seems Bloxstrap saves the previous account and the Ban info stays.

**Comment by pizzaboxer** [comment]
> It seems Bloxstrap saves the previous account and the Ban info stays.

It's Roblox itself doing that. Open the `%localappdata%\Roblox` folder and delete the LocalStorage folder to clear your login data.
