### ISSUE TITLE
[BUG]  Custom launch arguments- OBS

### ISSUE THREAD

**Issue by Woosh9129** [pizzaboxer/bloxstrap#2171]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

If I set OBS for a custom integration with an argument it will show failure to find locale/en-us.ini

There is a few fixes to this problem, you can do: 

cd "C:\Program Files\obs-studio\bin\64bit\
start obs64.exe

(SOURCE: https://obsproject.com/forum/threads/bat-file-obs-failed-to-find-locale-en-us-ini-my-solution.131660/ ) 

(Add an option for OBS that you can first CD into the application and then it will start the application. ) 

And with this in the second line, I could automatically start clipping through this argument (--startreplaybuffer )
start obs64.exe --startreplaybuffer

Also, for some reason it only tried to start OBS for me if an argument was provided. Might just be OBS though.

**Comment by pizzaboxer** [comment]
Issue resolved as of v2.7.0
