### ISSUE TITLE
[BUG] roblox no start how fix

### ISSUE THREAD

**Issue by Botimppa** [pizzaboxer/bloxstrap#2172]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

help me  pls

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?
