### ISSUE TITLE
[BUG]  Chrome UI isn't overridden

### ISSUE THREAD

**Issue by REDACTED1039** [pizzaboxer/bloxstrap#2174]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I did import the necessary fast flag to override it, but it didn't seem to work, am I doing it wrong?
![Screenshot 2024-06-26 002036](https://github.com/pizzaboxer/bloxstrap/assets/173871255/a70e7396-5777-451a-939c-3b71e6b890ac)

**Comment by Memor22** [comment]
Can confirm, same problem here

**Comment by pizzaboxer** [comment]
Are you trying to enable it or disable it?

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version
