### ISSUE TITLE
[BUG] bloxstrap not showing Discord RPC

### ISSUE THREAD

**Issue by Gavin-TnT** [pizzaboxer/bloxstrap#2175]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Not sure when it started, but the Discord RPC no longer appears when I play any Roblox game
![image](https://github.com/pizzaboxer/bloxstrap/assets/80191175/1b1c3978-65f1-4470-91e1-eab5df45940a)
[Bloxstrap_20240626T054027Z.log](https://github.com/user-attachments/files/15982948/Bloxstrap_20240626T054027Z.log)
[Bloxstrap_20240626T054142Z.log](https://github.com/user-attachments/files/15982950/Bloxstrap_20240626T054142Z.log)

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Discord-Rich-Presence-does-not-work, let me know if your issue still persists and I'll reopen.

**Comment by Gavin-TnT** [comment]
It doesn't work. It worked fine when I used it before, but it doesn't work recently. I didn't modify anything.
I don't use Vencord, I use betterdiscord
![image](https://github.com/pizzaboxer/bloxstrap/assets/80191175/d5552654-f20d-4028-a870-c1a469d261db)
![image](https://github.com/pizzaboxer/bloxstrap/assets/80191175/aa039600-33bd-48f2-80a1-d90d586db206)

**Comment by pizzaboxer** [comment]
Are you sure Section 2 doesn't apply to you?

**Comment by Gavin-TnT** [comment]
> Oh sorry, I wasn't properly looking at the log files you sent.
> 
> Are you able to access https://games.roblox.com/v1/games?universeIds=903807016 in your browser? What does it show?

![image](https://github.com/pizzaboxer/bloxstrap/assets/80191175/559edb43-ef2f-4fe7-830f-2457ee8b9c6c)

**Comment by pizzaboxer** [comment]
Strange, I'll see if I can figure out what's going on.

Download this version, run it, click yes when it prompts you to upgrade, join a game, and send another log file:

files.pizzaboxer.xyz/bloxstrap-debug/2175/Bloxstrap.exe

**Comment by Gavin-TnT** [comment]
> Strange, I'll see if I can figure out what's going on.
> 
> Download this version, run it, click yes when it prompts you to upgrade, join a game, and send another log file:
> 
> https://files.pizzaboxer.xyz/bloxstrap-debug/2175/Bloxstrap.exe

[Bloxstrap_20240702T083002Z.log](https://github.com/user-attachments/files/16064745/Bloxstrap_20240702T083002Z.log)

**Comment by pizzaboxer** [comment]
When you were trying it in your browser, were you using a browser VPN?

**Comment by Gavin-TnT** [comment]
> When you were trying it in your browser, were you using a browser VPN?
> 
> Also, downgrade back to the latest release version because this will error when Roblox tries to upgrade: https://github.com/pizzaboxer/bloxstrap/releases/latest

I used V2rayN and enabled the global proxy because I live in China.

**Comment by pizzaboxer** [comment]
Does it apply only to your browser or to your entire system?

**Comment by Gavin-TnT** [comment]
> Does it apply only to your browser or to your entire system?

whole system

**Comment by pizzaboxer** [comment]
I have a feeling it may not be applying to Bloxstrap since it gets this error when trying to retrieve rich presence information:

```json
{"errors":[{"code":403,"message":"Roblox.com is not available"}]}
```

Can you double check that please?

**Comment by Gavin-TnT** [comment]
> I have a feeling it may not be applying to Bloxstrap since it gets this error when trying to retrieve rich presence information:
> 
> ```json
> {"errors":[{"code":403,"message":"Roblox.com is not available"}]}
> ```
> 
> Can you double check that please?

Thank you so much for contributing so much to my problem, it was indeed a VPN problem, I used software to proxy roblox and Bloxstrap, and now the Discord PRC can be displayed correctly
![image](https://github.com/pizzaboxer/bloxstrap/assets/80191175/141d29b0-18a3-4f89-a59e-31e841341a84)

**Comment by pizzaboxer** [comment]
You're welcome. Don't forget to downgrade back to the latest release version if you haven't yet.

**Comment by Sahakbunny009** [comment]
> Author

how do u fix it?

**Comment by Gavin-TnT** [comment]
> > Author
> 
> how do u fix it?

Most users who have this problem are from China. Discord is prohibited in China. You must ensure that all traffic on your computer uses a proxy, otherwise the Discord RPC will not be displayed.
