### ISSUE TITLE
[BUG] Help, i always have fps more than enough to play any game on roblox so far, but suddenly right now i have barely 5 fps, is there an issue with how its working?

### ISSUE THREAD

**Issue by gb799** [pizzaboxer/bloxstrap#2180]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i dont have a screenshot of the fps before but it was running constantly at 170 fps while i was playing a kinda heavy game, here is the fps right now

![image](https://github.com/pizzaboxer/bloxstrap/assets/173929397/7d03b3d6-c57b-4112-bfe5-0a199dcff191)

**Comment by gb799** [comment]
i would be pleased if someone knew how to fix this

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/6b27245f-350e-4c66-bf07-0cb19c6ba330)


https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by bluepilledgreat** [comment]
Are you sure your FPS cap isn't set to something low?

**Comment by gb799** [comment]
> Are you sure your FPS cap isn't set to something low?

yes, it isnt. but somehow the fps got locked into 5 fps, i tried checking the roblox fps unlocker and the fast flags one, but still got nothing. i searched all over the internet trying to find a cure to this but i have never seen someone having the same problem as me probably, or the same person tried doing the same but failed. something that caught my attention is that it is never crashing, with an fps like that it should crash because thats what it usually does before crashing, so maybe the fps is locked by something

**Comment by gb799** [comment]
update : its fixed! i dont know how but when i updated my video card driver, it fixed itself, i dont know what to say anymore, so... thanks for bloxstrap!
