### ISSUE TITLE
[BUG] Roblox won't open more than one window

### ISSUE THREAD

**Issue by s533537** [pizzaboxer/bloxstrap#2181]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've tried deleting and redownloading bloxstrap twice now and nothing seems to help. After a fresh download, the open to opne more than one roblox game is there but after I try to, I get the notification that doing so will shut down the first one. When I check the bloxstrap menu, the open to turn that on isn't even there anymore. Can someone help?

**Comment by oreo0cat201** [comment]
Download the old version here :https://www.mediafire.com/file/nv56swly13jvr9n/Bloxstrap-v2.5.4.exe/file

**Comment by pizzaboxer** [comment]
We announced this over a month ago. https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
