### ISSUE TITLE
[REQ] remove .net

### ISSUE THREAD

**Issue by antploooer** [pizzaboxer/bloxstrap#2182]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

please remove .net asking thing i cant download it please make bloxstrap from something else plss

**Comment by pizzaboxer** [comment]
You need to install it. No way around it.

**Comment by antploooer** [comment]
> You need to install it. No way around it.

you cant make it without .net?
