### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AuraIsMe** [pizzaboxer/bloxstrap#2183]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\wheat\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by pizzaboxer** [comment]
Did you read the relevant Wiki pages?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
