### ISSUE TITLE
THIS IS A THREAT ADD BACK MULTI NOW

### ISSUE THREAD

**Issue by jayripppp2** [pizzaboxer/bloxstrap#2184]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

WE WILL COME FOR YOU!

**Comment by red-hi** [comment]
didnt knew that using roblox account manager would be that hard

**Comment by jayripppp2** [comment]
> didnt knew that using roblox account manager would be that hard

but is better yk
