### ISSUE TITLE
[BUG] roblox doesnt open up when i use bloxstrap

### ISSUE THREAD

**Issue by alecisgoodatlua** [pizzaboxer/bloxstrap#2185]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

https://streamable.com/x1m6a1

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by alecisgoodatlua** [comment]
yup, still doesnt work. if i want to play roblox i have to run the roblox installer everytime.

**Comment by alecisgoodatlua** [comment]
yup

**Comment by pizzaboxer** [comment]
Upload your configuraton please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by alecisgoodatlua** [comment]
[Settings.json](https://github.com/user-attachments/files/16049303/Settings.json)
[State.json](https://github.com/user-attachments/files/16049304/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/16049309/ClientAppSettings.json)

**Comment by dizzyishigher** [comment]
bloxstrap doesn't work for me either everytime i try to download dotnet it takes me to a sight which is HTTP Error 500.30 - ASP.NET Core app failed to start

**Comment by wascertified** [comment]
> bloxstrap doesn't work for me either everytime i try to download dotnet it takes me to a sight which is HTTP Error 500.30 - ASP.NET Core app failed to start

Use the wayback machine on the .NET downloads site, and install version 6.0

Alternatively, try installing through [this link](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.423-windows-x64-installer)

**Comment by alecisgoodatlua** [comment]
i think for me its a problem with roblox, like bloxstrap turns on, runs normally then closes and the task remains running

**Comment by pizzaboxer** [comment]
This all seems good, you're definitely on a stock configuration. Have you also tried enabling the "Force Roblox Reinstallation" option under the "Behaviour" tab in the Bloxstrap Menu?

**Comment by alecisgoodatlua** [comment]
yup, still doesnt work

**Comment by pizzaboxer** [comment]
If you open the `%localappdata%\Bloxstrap\Versions` folder, open the other version folder, delete the ClientAppSettings folder and then run RobloxPlayerBeta directory, does the same thing happen?

**Comment by alecisgoodatlua** [comment]
yup, it doesnt open at all

**Comment by alecisgoodatlua** [comment]
okay, i got mad and reinstalled locally my windows and now it works normally, idk wtf happened

**Comment by alecisgoodatlua** [comment]
sorry for taking ur time
