### ISSUE TITLE
[BUG]  roblox crashes but game still works

### ISSUE THREAD

**Issue by eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegsdgre** [pizzaboxer/bloxstrap#2186]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

roblox like crashes like then when i open the game it stills works + when i play a game that requires teleporte it jsut kicks me out it closes that crash making it kick me out plz help 
![Screenshot 2024-06-27 231123](https://github.com/pizzaboxer/bloxstrap/assets/174063274/8165112c-911f-46be-8cc1-702becd82fdc)

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
