### ISSUE TITLE
[BUG] Crashing

### ISSUE THREAD

**Issue by oggizek** [pizzaboxer/bloxstrap#2187]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by pizzaboxer** [comment]
You're not using the latest version of Bloxstrap. Download the latest version here: https://github.com/pizzaboxer/bloxstrap/releases/latest
