### ISSUE TITLE
[REQ] Fast Flags on Android / Chromebooks

### ISSUE THREAD

**Issue by mcgamerguy** [pizzaboxer/bloxstrap#2188]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Would it be posible to make this an app as apk or on the play store, as chromebooks arent able to run exe's.
Also i would love there being like sets that you can make to quickly switch fastflags or other mods etc..

**Comment by pizzaboxer** [comment]
No

**Comment by mcgamerguy** [comment]
pls it will help alot of people
