### ISSUE TITLE
[BUG] bloxstrap wont start .NET download

### ISSUE THREAD

**Issue by Huggywuggyplavi** [pizzaboxer/bloxstrap#2189]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

bloxstrap wont start .NET download. so i wanted to use BLOXSTRAP until i tried downloading it and it kept saying "You Need .NET Desktop Runtime To Run This Application" and this needs to be fixed
![image](https://github.com/pizzaboxer/bloxstrap/assets/146106250/c314e9f5-a3fb-4538-aaba-1247f8a08877)

**Comment by GoingCrazyDude** [comment]
buddy. you have to install it. yourself. its not going to install it for you.

**Comment by Huggywuggyplavi** [comment]
> buddy. you have to install it. yourself. its not going to install it for you.

it normally automatically sends an download wizard

**Comment by pizzaboxer** [comment]
> it normally automatically sends an download wizard

If clicking the yes button doesn't do anything, then download it from here: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true
