### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fusionhere** [pizzaboxer/bloxstrap#2191]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried to add a font to my game and it won't let me.

**Comment by newbnoobhaha** [comment]
please elaborate

**Comment by pizzaboxer** [comment]
> I tried to add a font to my game and it won't let me.

Why not?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
