### ISSUE TITLE
An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Skibidiohio91** [pizzaboxer/bloxstrap#2192]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
![image_2024-06-28_134959841](https://github.com/pizzaboxer/bloxstrap/assets/174140338/f8cc4f60-39db-4969-833e-bd800fa38e83)

**Comment by Jenpol4** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/143454246/2d861273-a8a6-4fae-99c1-cb69bef94769)
 i have the same problem

**Comment by Jenpol4** [comment]
[Bloxstrap_20240628T184356Z.log](https://github.com/user-attachments/files/16035427/Bloxstrap_20240628T184356Z.log)
my log:

**Comment by pizzaboxer** [comment]
You're using an outdated version of Bloxstrap. Download the latest version: https://github.com/pizzaboxer/bloxstrap/releases/latest
