### ISSUE TITLE
bloxstrap asking if i want to join a game while roblox is already running one

### ISSUE THREAD

**Issue by newbnoobhaha** [pizzaboxer/bloxstrap#2194]
normally this would be a nice feature, but i play bee swarm simulator and use a macro for it and this interrupts the macro if it needs to rejoin the game. i want to know if there is an option to toggle this and if not, could you add it to the next update?

**Comment by pizzaboxer** [comment]
Duplicate of #gi

**Comment by newbnoobhaha** [comment]
> Duplicate of #gi

what does that mean? i dont use github much
