### ISSUE TITLE
[BUG] Textures arent loading. 

### ISSUE THREAD

**Issue by Semireq** [pizzaboxer/bloxstrap#2197]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello, i got issue that some textures arent loading. It is happening only on bloxstrap, on normal roblox is everything okay. I dont have any fflags or anything on pls help

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Semireq** [comment]
[Settings.json](https://github.com/user-attachments/files/16039254/Settings.json)
[State.json](https://github.com/user-attachments/files/16039255/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/16039256/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
All seems fine.

I can't really help you out here because it seems like your configuration should be identical to stock Roblox. There isn't really anything that should differ. Sorry.
