### ISSUE TITLE
Bloxstrap not running when RTSS is opened

### ISSUE THREAD

**Issue by IRFRX21** [pizzaboxer/bloxstrap#2200]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime i wanna open bloxstrap i have to close RTSS.
I have tried to make a profile for bloxstrap.exe in RTSS and making the detection level to "None" but nothing seems to change.

**Comment by TgamingFake** [comment]
System.UnauthorizedAccessException: Access to the path 'C:\Users\haiye\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by pizzaboxer** [comment]
> Everytime i wanna open bloxstrap i have to close RTSS.

I'm late, but this is a known issue, and this isn't specific to Bloxstrap. You would've known this had you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.
