### ISSUE TITLE
[REQ] Bring back the deployment channel switch prompt

### ISSUE THREAD

**Issue by JSkes** [pizzaboxer/bloxstrap#2202]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It keeps putting me into "zcreatemrdallocsreduc" no matter how many times I try setting it back to LIVE, it just automatically changes it now, I can't update right now because the download keeps failing, I can't download anything at the moment, haven't looked into why I can't download. I just want the old dialogue prompt that asks me if I want to switch channels when Roblox is trying to switch mine.

**Comment by pizzaboxer** [comment]
> I can't update right now because the download keeps failing,

I think there's another issue here that you're avoiding for some reason. Do you get an error message of sorts when it does this?

**Comment by JSkes** [comment]
It's a problem with either my PC or my adapter, because downloading anything on my phone works fine, it's only when I try downloading something on my PC, it gives me a 443 every time I try updating Roblox.

**Comment by pizzaboxer** [comment]
Can you show a picture of the error message please?

**Comment by JSkes** [comment]
Here, sorry for the late response, I just remembered about this issue
![image](https://github.com/pizzaboxer/bloxstrap/assets/71411219/1163510f-b478-4538-8251-1d99d69db562)

**Comment by pizzaboxer** [comment]
This is an internet connectivity issue. I'm not sure why you thought being able to change your channel would fix this. Check your antivirus.

**Comment by JSkes** [comment]
I know that changing my channel won't fix this, I'm only trying to stay on LIVE, which I already have the files for.

**Comment by pizzaboxer** [comment]
> I'm only trying to stay on LIVE,

That still wouldn't avoid this error because clientsettings.roblox.com is queried on every launch to check if an update is needed in the first place.

**Comment by JSkes** [comment]
> clientsettings.roblox.com is queried on every launch to check if an update is needed in the first place.

Querying clientsettings.roblox.com seems to work for me, it's just the download that either shows 443 or timed out.
