### ISSUE TITLE
[BUG] Selecting Vulkan for my GPU crashes roblox/GPU problems

### ISSUE THREAD

**Issue by verystupidlysimple** [pizzaboxer/bloxstrap#2203]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so i've configured my fast flags to disable direct3d since that makes me have input lag, turned off VR too. i ticked on re-install roblox on launch and then i get this error message
![Screenshot 2024-06-29 122453](https://github.com/pizzaboxer/bloxstrap/assets/173736615/b31f5bfb-0a5b-44a8-b4af-0dd33b249a4e)
the game window just displays white, and the "we had an unexpected error" box pops up too
and unrelated bloxstrap opens under Chrome in the task manager so i can't even kill the ram eater

but the thing is i don't even have OBS open?? i think it might be the weird anticheat roblox put out since it's checking for external stuff, upgrading to 32 bit has drained my computer's resources

i currently use a nvida gpu, i have my programs set to "high performance use gpu", roblox ignores that and uses all my RAM, i also set it to use nvidia in the Control Panel
and yes i set to Use Nvidia for the other PlayerBetas
![image](https://github.com/pizzaboxer/bloxstrap/assets/173736615/813ac3cf-db2c-47ec-b6df-972ae1ac1a0f)

![image](https://github.com/pizzaboxer/bloxstrap/assets/173736615/b022649b-7893-4efb-afe4-77f3fefb529d)
![image](https://github.com/pizzaboxer/bloxstrap/assets/173736615/1c1ddf8e-7040-4b31-a7d4-94df218e0e76)

and 92% memory usage? i upgraded my card just for more memory, so then roblox used all of that too. forgot to screenshot that

**Comment by Vlad55432** [comment]
Roblox might not work, if you try running with vulkan engine on PC. Can't fix, just use directx/opengl

**Comment by verystupidlysimple** [comment]
> Roblox might not work, if you try running with vulkan engine on PC. Can't fix, just use directx/opengl

openGL left me on 7 fps in the performance stats
the tracker also said it was running on the CPU

game i'm trying to play on is Arcane Odyssey, the inventory lag is a big problem in it

**Comment by Flames22** [comment]
try using direct3d 11 instead since vulkan is buggy on roblox it will obviously crash its never been stable in the first place since roblox haven't fully certified it yet set the prepferbulkan to false and disabledirect3d11 to false also

**Comment by verystupidlysimple** [comment]
> try using direct3d 11 instead since vulkan is buggy on roblox it will obviously crash its never been stable in the first place since roblox haven't fully certified it yet set the prefervulkan to false and disabledirect3d11 to false also and how much ram do you have since 8gb is not enough anymore in this 2024 16gb is the recommended in this year now and i find it weird how come your getting input lag with direct3d your using a nvidia gpu unless your nvidia gpu is not being used that might be the issue why you having a input lag i have no problem with my nvidia gpu with it its running smoothly never had a input lag issue when it comes to direct3d but make sure you run it at direct3d 11

can you speak english

**Comment by Vlad55432** [comment]
> game i'm trying to play on is Arcane Odyssey, the inventory lag is a big problem in it

Place/game (or what it is called in roblox) fault, I guess.

**Comment by verystupidlysimple** [comment]
> > game i'm trying to play on is Arcane Odyssey, the inventory lag is a big problem in it
> 
> Place/game (or what it is called in roblox) fault, I guess.
crazy how you need gaming pcs to play a kid's game now

how am i meant to afford a 4k dollar laptop here in europe
![image](https://github.com/pizzaboxer/bloxstrap/assets/173736615/81dd4dc1-93f5-495c-b62f-f91829bd211f)
16gb is luxury over here and i only have 8
i believe my old desktop computer had 32gb which is why it never lagged, however the power went out so much and i couldn't use the pc

**Comment by nakoyasha** [comment]
You've set *Bloxstrap* to use your GPU, not the *client.* That's why it's still running on your integrated graphics

Go to installation and click on "Open Installation Folder", then open the Versions folder and open the (hopefully) only "version-[hash]" folder. Then right click on RobloxPlayerBeta.exe while holding down shift and select "Copy as Path"

After that, go back to System > Display > Graphics in System Settings, and click the "Browse" button here:
![ApplicationFrameHost_GVTFdkK5Fo](https://github.com/pizzaboxer/bloxstrap/assets/96925398/aaf24784-36ea-412a-884e-ac3427749405)
In the "Open" window, find the "File name:" box, and paste the path you copied earlier.
![PickerHost_vQKKgMkuy7](https://github.com/pizzaboxer/bloxstrap/assets/96925398/c538cd64-f43f-419f-bf70-c19576c4fece)

This should *hopefully* add the client to the list. Although you'll probably have to do this on each update since the version folder always changes.

**Comment by verystupidlysimple** [comment]
> You've set _Bloxstrap_ to use your GPU, not the _client._ That's why it's still running on your integrated graphics.
> 
> Open Bloxstrap settings and go to installation and click on "Open Installation Folder", then open the "Versions" folder and open the (hopefully) only "version-[hash]" folder. Then right click on "RobloxPlayerBeta.exe" while holding down shift and select "Copy as Path"
> 
> After that, go back to System > Display > Graphics in System Settings, and click the "Browse" button here: ![ApplicationFrameHost_GVTFdkK5Fo](https://private-user-images.githubusercontent.com/96925398/344451971-aaf24784-36ea-412a-884e-ac3427749405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzU4NDcsIm5iZiI6MTcxOTczNTU0NywicGF0aCI6Ii85NjkyNTM5OC8zNDQ0NTE5NzEtYWFmMjQ3ODQtMzZlYS00MTJhLTg4NGUtYWMzNDI3NzQ5NDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA4MTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NGE5M2M4MDNjMzA3ZTkwMmM2NzVkMmYzYzUxOThhMDc3ZGVhOThjY2U5YmMxYjE0NTQ1YjkzNWUyOGExYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mn_SMhPVQk2K_boLWdvDoJv7F3jnp9CQtLwmTRmKGcw) In the "Open" window, find the "File name:" box, and paste the path you copied earlier. ![PickerHost_vQKKgMkuy7](https://private-user-images.githubusercontent.com/96925398/344452014-c538cd64-f43f-419f-bf70-c19576c4fece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzU4NDcsIm5iZiI6MTcxOTczNTU0NywicGF0aCI6Ii85NjkyNTM5OC8zNDQ0NTIwMTQtYzUzOGNkNjQtZjQzZi00MTlmLWJmNzAtYzE5NTc2YzRmZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA4MTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjMyNmI4NDE0MzY5OTYxODBiMjY1MGZjNGIwNmIxNTAyOWFkMmFiYzQzMzQwZGIwODFkNDMyZGJmOTI3NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eoSDn6Yv_c8Old4RrO9bJe6m9XhLQo73yJEHkB-a7NQ)
> 
> This should _hopefully_ add the client to the list. Although you'll probably have to do this on each update since the version folder always changes.

how can i check if it's actually using it in roblox
shift+f5 only displays the current fps
not exactly like a programmer

**Comment by nakoyasha** [comment]
> how can i check if it's actually using it in roblox

There should be two GPUs in the Performance tab of Task Manager, your integrated graphics and your dedicated GPU. One of them should have increased usage while Roblox is running.

**Comment by verystupidlysimple** [comment]
> > how can i check if it's actually using it in roblox
> 
> There should be two GPUs in the Performance tab of Task Manager, your integrated graphics and your dedicated GPU. One of them should have increased usage while Roblox is running.

alright give me a second to test your copy path suggesstion

**Comment by verystupidlysimple** [comment]
> > how can i check if it's actually using it in roblox
> 
> There should be two GPUs in the Performance tab of Task Manager, your integrated graphics and your dedicated GPU. One of them should have increased usage while Roblox is running.

![image](https://github.com/pizzaboxer/bloxstrap/assets/173736615/c898eaf9-957f-4dd0-bc97-17654919313c)
is it normal for bloxstrap to be under google
it's still using all my memory

**Comment by pizzaboxer** [comment]
You're not actually supposed to use Vulkan. That was added by back by accident. Don't use it. Don't use OpenGL either.
