### ISSUE TITLE
[BUG] Crosshair doesnt show when roblox fullscreened

### ISSUE THREAD

**Issue by hahahKVS** [pizzaboxer/bloxstrap#2206]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I use crosshair v2 when i play roblox and now then i open it and fullscreen roblox it doesnt show, like it gets put behind the roblox window when before i installed bloxtrap it would show even when fullscreen.
What should I disable/enable so that my crosshair shows when im fullscreened

**Comment by pizzaboxer** [comment]
How are you enabling fullscreen, since there's multiple ways to do it? Also, upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
