### ISSUE TITLE
[BUG] Folder location permanently stuck where I first put it, but now I'm having an issue and want to put it back to it's default

### ISSUE THREAD

**Issue by Rimururururururu** [pizzaboxer/bloxstrap#2207]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So I put the download location somewhere else, I tried uninstalling any related files I could, and reinstalling, but it just defaulted to the first selected spot, and I can't uninstall from control panel, please help or add a way to change the location from the menu or make it default to ask when opening an installer despite having already been installed in the past!!!

**Comment by pizzaboxer** [comment]
> So I put the download location somewhere else

If you moved the folder, you'll have to uninstall it first. Move it back to where it was, uninstall it from the Control Panel, then reinstall it at the new location.
