### ISSUE TITLE
lighting tecnology bug

### ISSUE THREAD

**Issue by TheRealBooWasHere** [pizzaboxer/bloxstrap#221]
When you use the Future mode in some games, everything looks very shiny as if it were a neon:
![image](https://user-images.githubusercontent.com/130320474/236705240-681a04c1-284a-46f9-a55a-b71aa2cb55ce.png)
![image](https://user-images.githubusercontent.com/130320474/236705289-a5b24c0c-282d-49b1-a41f-739f7fa234fe.png)

And if you use it in automatic mode, it looks good without any problem:
![image](https://user-images.githubusercontent.com/130320474/236705325-b8f0a6e0-9f48-4c03-88cd-e5146b10cb30.png)
![image](https://user-images.githubusercontent.com/130320474/236705348-fe3f78dd-e5b3-4d38-8229-aca2bccb905d.png)

**Comment by pizzaboxer** [comment]
That's just... that's what future lighting does...
