### ISSUE TITLE
Bloxstrap Crashing When Opening[BUG] 

### ISSUE THREAD

**Issue by Photiaxel** [pizzaboxer/bloxstrap#2210]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i try to open roblox it crashes. I have tested out and i can open the normal roblox app without any problems but when i try to open roblox through bloxstrap it crashes every time. I have uninstalled and reinstalled but it is still not working.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
