### ISSUE TITLE
[BUG] Bloxstrap installing webview2 and taking so long

### ISSUE THREAD

**Issue by CombiningBlox** [pizzaboxer/bloxstrap#2211]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Capture](https://github.com/pizzaboxer/bloxstrap/assets/174259458/573ba53f-f316-4b77-91e4-2b14a4a99d0f)

**Comment by pizzaboxer** [comment]
How long have you waited for? It depends on the speed of your internet connection.

**Comment by loadstring1** [comment]
i experienced same thing but updating edge webview2 with winget seems to work

or just manually download microsoft edge webview2 installer and run it

**Comment by CombiningBlox** [comment]
fixed or not?

**Comment by CombiningBlox** [comment]
what version?

**Comment by CombiningBlox** [comment]
i've waited for three hours

**Comment by pizzaboxer** [comment]
> i've waited for three hours

Open the `%temp%` folder, sort by date modified, and upload Bloxstrap's latest log file here.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
