### ISSUE TITLE
some sort of internet issue

### ISSUE THREAD

**Issue by BloxstrapPleaseWorkAgain** [pizzaboxer/bloxstrap#2213]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i boot up bloxstrap it shows me: 

**System.Net.Http.HttpRequestException: No such host is known. (clientsettings.roblox.com:443)**

**[Inner Exception]**
**System.Net.Sockets.SocketException: No such host is known.**

**Comment by pizzaboxer** [comment]
If it's an internet issue then I'm not sure what you want me to do about it. Ensure your internet connection is working properly..
