### ISSUE TITLE
[BUG] This is the error I get every time I try to open bloxstrap, I even uninstalled bloxstrap, downloaded it again. But I still get this error

### ISSUE THREAD

**Issue by Akpudhoor** [pizzaboxer/bloxstrap#2216]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-1088f3c8e4a44cc7-content-platform-fonts.zip

Got signature: 5df1dc6ef64bdc5bd857d4b8cf9f3df8

Package has been downloaded to C:\Users\AKPRR\AppData\Local\Bloxstrap\Downloads\8f379ec2b22ff106b837d79f7fdbf0d8

Please send the file shown above in a bug report.

**Comment by Akpudhoor** [comment]
Please someone explain to me, how do I fix this?

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox
