### ISSUE TITLE
[BUG] I can't uninstall bloxstrap

### ISSUE THREAD

**Issue by Kwatekj** [pizzaboxer/bloxstrap#2217]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hey, yesterday everything was ok, but today i can't open roblox, when i try to play a game it says to download .NET windows runtime, but when i go to the link it says: HTTP Error 500.30 - ASP.NET Core app failed to start. And when i try to uninstall it it says the same, to download .NET... i can't play roblox right now and even uninstalling it from control panel does the same. I don't know if you can, but you should change that if you want to uninstall roblox from control panel it doesn't open bloxstrap but like opens a wizard to install/uninstall it.

**Comment by pizzaboxer** [comment]
How did you install Bloxstrap if you don't have the .NET runtime installed?

If the download page is erroring for you then see if you can directly download it from here: https://download.visualstudio.microsoft.com/download/pr/a1da19dc-d781-4981-84e9-ffa0c05e00e9/46f3cd2015c27a0e93d7c102a711577e/windowsdesktop-runtime-6.0.31-win-x64.exe

**Comment by Kwatekj** [comment]
thanks
its working now
