### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by sbxnf** [pizzaboxer/bloxstrap#2218]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I can not run roblox (error 403). That's my first encounter of this "bug".

**Comment by pizzaboxer** [comment]
You're not using the latest version of Bloxstrap. https://github.com/pizzaboxer/bloxstrap/releases/latest
