### ISSUE TITLE
[REQ] change color of text

### ISSUE THREAD

**Issue by the9655a** [pizzaboxer/bloxstrap#2219]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Make the text and icons more readable with white text coloring or maybe a black background as well, it'd match the dark theme of bloxstrap better. Also im not sure if this is something on my end but the bottom text looks kind of dimm, making that a bit more visible would help as well.

![image](https://github.com/pizzaboxer/bloxstrap/assets/149513282/a115bd6d-988c-4d2e-8797-38d1a3541e5a)

**Comment by pizzaboxer** [comment]
Is it just in the popup alert that text readability is difficult or are there other areas you've noticed this in too?

**Comment by pizzaboxer** [comment]
Fixed in 2.7.0
