### ISSUE TITLE
Add custom Roblox Studio themes support 

### ISSUE THREAD

**Issue by RyanLua** [pizzaboxer/bloxstrap#222]
Add in integration for custom themes in Roblox Studio by having some form of integration with [Roblox Studio CustomTheme Patcher]()? 

You would probably need to somehow contact the owner for permission or make a new way to patch themes into Roblox Studio.

**Comment by pizzaboxer** [comment]
Bloxstrap doesn't support Roblox Studio. However, I'll guide you in the direction of (Roblox Studio Mod Manager)[https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager].

**Comment by RyanLua** [comment]
Can you delete this issue? I misinterpreted the program and now this will be stuck on my GitHub activity history.
