### ISSUE TITLE
[BUG] Bloxstrap doesn't finish installing itself at all

### ISSUE THREAD

**Issue by wathever-at** [pizzaboxer/bloxstrap#2223]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i open up Bloxstrap to install it, it's stuck at the "Configuring Roblox" loading screen.

**Comment by pizzaboxer** [comment]
Does it do this consistently every time you try to install it?

**Comment by wathever-at** [comment]
Well. Yes. That's the only issue I have.

**Comment by wathever-at** [comment]
Nothing else, it happens when I try to install it.

**Comment by pizzaboxer** [comment]
Open the %temp% folder, sort by date modified, and send Bloxstrap's latest log file here.

**Comment by wathever-at** [comment]
[Bloxstrap_20240702T224404Z.log](https://github.com/user-attachments/files/16089171/Bloxstrap_20240702T224404Z.log)

**Comment by wathever-at** [comment]
There is my lastest Bloxstrap log

**Comment by pizzaboxer** [comment]
In the %localappdata%\Bloxstrap\Downloads folder, there should be a file named `24c19f98d81b49479f07c330ed96be57`. Can you upload it somewhere and send a link to it here please?

**Comment by wathever-at** [comment]
hey pizza

**Comment by wathever-at** [comment]
pizzaboxer

**Comment by wathever-at** [comment]
I fixed it

**Comment by wathever-at** [comment]
its now working and it installed.

**Comment by wathever-at** [comment]
![Captura de pantalla 2024-07-04 140653](https://github.com/pizzaboxer/bloxstrap/assets/174383314/2c3a0162-c439-45c4-be31-cf2a0be7adfe)

**Comment by wathever-at** [comment]
![Captura de pantalla 2024-07-04 140704](https://github.com/pizzaboxer/bloxstrap/assets/174383314/0006ea96-f410-4bb9-b27d-98a5b6412271)

**Comment by wathever-at** [comment]
![Captura de pantalla 2024-07-04 140742](https://github.com/pizzaboxer/bloxstrap/assets/174383314/b23ffee1-051b-45e9-975e-44fbe71a7e95)
