### ISSUE TITLE
[BUG] When I try to launch a game I get a error message saying "an exeption occured while running Bloxstrap" and "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)." 

### ISSUE THREAD

**Issue by Joe-Da-Goon** [pizzaboxer/bloxstrap#2225]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Here are the log file
[Bloxstrap_20240702T123628Z.log](https://github.com/user-attachments/files/16068217/Bloxstrap_20240702T123628Z.log)

**Comment by Benja59** [comment]
Thanks

**Comment by pizzaboxer** [comment]
Update to the latest version: https://github.com/pizzaboxer/bloxstrap/releases/latest
