### ISSUE TITLE
blowstrap download bug

### ISSUE THREAD

**Issue by Tijn427** [pizzaboxer/bloxstrap#2226]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

An expection occured while running bloxstrap
Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-1088f3c8e4a44cc7-RobloxApp.zip

Got signature: 78ea1ef260f0a9bf7b662f2091ea50b1

Package has been downloaded to C:\Users\pc\AppData\Local\Bloxstrap\Downloads\60fefc61dcb1b9d3b999292673522e5c

Please send the file shown above in a bug report 

how to fix this

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox
