### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\RAMI\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by Quail942** [pizzaboxer/bloxstrap#2227]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\RAMI\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by toofastforboo** [comment]
read wiki.

https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-or-%22An-error-occurred-trying-to-start-process%22-regarding-RobloxPlayerBeta.exe

https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
