### ISSUE TITLE
[BUG] When I try to launch roblox, the game launches in the background.

### ISSUE THREAD

**Issue by xHASKOYLU** [pizzaboxer/bloxstrap#2228]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have tried nearly everything. I disabled all flags every single mod and tried, didn't work. I tried to delete all fflags and tried, didn't work. I reinstalled 5 times and none of the times did it work, but whenever I install normal roblox everything seems fine. I even went up to reseting my pc which contained over 300Gigs of useful stuff (that I had to reinstall) and still not working. When I first installed it opened the game but my cursor couldn't be seen and the game was really laggy for some reason. Normal roblox fflags are stupid and crazy hard to do since you have to also get the codes right or else absolutely nothing will work and you can't add codes like you can on bloxstrap. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/174506309/c06dd4f2-9a79-4d85-868f-55175605abb0)

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by w6snt** [comment]
this is happening to me and idk how to fix it ive redownloaded it a million times

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
