### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by PortFolio-Vinity** [pizzaboxer/bloxstrap#2229]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

YOU CANT CHANGE THE MODS YOU INSTAILED:

i dust downloaded it and now when i open bloxstrap it just opens Roblox and i cant install mods

**Comment by MarkGamez1** [comment]
theres an app called Bloxstrap Menu.. this isnt a bug?

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
