### ISSUE TITLE
[BUG] Whenever i launch Bloxstrap, It says "An exception occured while running Bloxstrap"

### ISSUE THREAD

**Issue by ezedubb** [pizzaboxer/bloxstrap#2230]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't know what to do, I tried to re launch it and it said the same thing, Can somebody help me?

**Comment by pizzaboxer** [comment]
Can you show the full error message please? Can you also send the log file?

**Comment by ezedubb** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/174546183/01f3554f-73fe-4f4a-a746-8ff9ba09e7f2)
