### ISSUE TITLE
[BUG] Whenever i launch Bloxstrap, It says "An exception occured while running Bloxstrap"

### ISSUE THREAD

**Issue by Benja59** [pizzaboxer/bloxstrap#2232]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried to enter Roblox and it didn't open, so I deleted Bloxstrap, reinstalled it and it didn't work, a sign appeared. Please fix that bug without Bloxstrap I can't play Roblox

**Comment by Benja59** [comment]
![Captura de pantalla 2024-07-02 210743](https://github.com/pizzaboxer/bloxstrap/assets/174554577/ab58f6b3-54f2-4223-9778-23809dab8ccc)

**Comment by pizzaboxer** [comment]
Did you read the relevant Wiki pages?

**Comment by pizzaboxer** [comment]
Read them if you haven't.
