### ISSUE TITLE
[BUG] Roblox crashes after some time

### ISSUE THREAD

**Issue by tranuhrl** [pizzaboxer/bloxstrap#2234]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I recently wiped my computer fresh but now after playing a roblox game for some time, it just freezes. Afterwards it unfreezes, but the freeze happens for awhile. Before I wiped my PC fresh, this problem didn't happen.

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/ee60b5af-b373-4a0e-8daf-55d3fd83a248)

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Madmaxispog** [comment]
I seem to have the same issue. I tried reverting to version 2.5.3, and it works just fine. This error only occurs for me when I minimize Roblox.

**Comment by pizzaboxer** [comment]
> I seem to have the same issue. I tried reverting to version 2.5.3, and it works just fine. This error only occurs for me when I minimize Roblox.

**Comment by Madmaxispog** [comment]
Thank you!
