### ISSUE TITLE
Context menu button to open log file

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#2237]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

This would open the current instances log file in your default text editor

**Comment by pizzaboxer** [comment]
oh yeah i dont know why i restricted this to only being available debug only

**Comment by EasternBloxxer** [comment]
> > oh yeah i dont know why i restricted this to only being available debug only
> 
> how do you even enable debug now

build in debug mode obviously

**Comment by EasternBloxxer** [comment]
???

**Comment by pizzaboxer** [comment]
Released in 2.7.0
