### ISSUE TITLE
[SUGGESTION] Add a feature to redirect ROBLOX to use the UWP version of it.

### ISSUE THREAD

**Issue by jLn0n** [pizzaboxer/bloxstrap#224]
becus yes yes yes (explained by the title)
the paragraph below is a generated using chatgpt on why you should add this feature

> Adding UWP redirection of ROBLOX can greatly enhance the user experience, increase user engagement and retention, differentiate an app from competitors, and future-proof an app. With so many benefits to adding UWP redirection, it's a smart business decision for anyone looking to improve their ROBLOX app and stand out in a crowded market.

**Comment by pizzaboxer** [comment]
What? Why don't you just install the UWP version then?

**Comment by jLn0n** [comment]
> What? Why don't you just install and use the UWP version then?

i just click play on a link instead of searching the frick out of it and figuring out where is the game if im using UWP

**Comment by pizzaboxer** [comment]
I can't really do anything about that, and it would defeat the entire purpose of Bloxstrap as it does not apply to the UWP version. Why are you using the UWP version anyway? What's wrong with just using the normal Windows version?
