### ISSUE TITLE
[REQ] Add this text to readme or similar and make it prominent

### ISSUE THREAD

**Issue by heavyutils** [pizzaboxer/bloxstrap#2240]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

It’s probably good to clear up this because I’ve seen Reddit posts not trusting it so I recommend this.

## Clarifying Misinformation about Bloxstrap
It has come to our attention that there are several rumors and misconceptions circulating about Bloxstrap, the Roblox launcher tool. We would like to take this opportunity to clear up any confusion and provide accurate information about the tool.

### What is Bloxstrap?

Bloxstrap is a third-party launcher tool designed to enhance the Roblox gaming experience. It offers various features such as setting startup parameters (flags), better customization options, and additional functionalities that are not available in the default Roblox launcher.

### Addressing Common Misconceptions

	1.	Safety and Security Concerns:
	•	False Rumor: Bloxstrap is unsafe and contains malware.
	•	Fact: Bloxstrap is developed by reputable developers who prioritize user safety. It does not contain any malicious code. As with any third-party software, it is important to download Bloxstrap from official sources to ensure its integrity.
	2.	Account Ban Risk:
	•	False Rumor: Using Bloxstrap can get your Roblox account permanently banned.
	•	Fact: Using Bloxstrap does not result in permanent bans. While a few users have experienced brief auto bans, these instances were rare and none were permanent or very long. Bloxstrap is designed to comply with Roblox’s terms of service and does not alter game code or give players an unfair advantage.
	3.	Performance Issues:
	•	False Rumor: Bloxstrap slows down your computer and causes game crashes.
	•	Fact: Bloxstrap is optimized to improve the Roblox gaming experience. Issues you encounter may be due to invalid flags or other factors such as system compatibility or conflicts with other Roblox modifications.

### Recommendations for Users

	•	Download from Official Sources: Always download Bloxstrap from this official repository to ensure you are getting the latest legitimate version.
	•	Stay Informed: Follow official announcements and updates from the Bloxstrap development team to stay informed about new features, security updates, and best practices.
	•	Report Issues Responsibly: If you encounter any problems while using Bloxstrap, open an issue in the designated repository to help improve the tool and ensure a safe experience for all users.

**Comment by heavyutils** [comment]
The code blocks near the numbered lists are unintentional. GitHub really is bugging me around.

**Comment by pizzaboxer** [comment]
Appreciate the effort. I like the descriptions and FAQ answers given here.

**Comment by pizzaboxer** [comment]
I've adapted the information to how I'd word them, but still, thanks.
