### ISSUE TITLE
[BUG] Roblox crash after minimizing

### ISSUE THREAD

**Issue by pompompur1nn** [pizzaboxer/bloxstrap#2243]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

This isnt bloxstraps fault, but most likely roblox's.
Roblox crashes when you set the renderer in bloxstrap as vulcan.

**Comment by pizzaboxer** [comment]
Don't set it as Vullkan. Keep it on Automatic or Direct3D.
