### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users--------\AppData\Local\Bloxstrap\Downloads\43c726b04ccfad6eb95e7ee2c25b33f0'.

### ISSUE THREAD

**Issue by eatmyfarts122** [pizzaboxer/bloxstrap#2244]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

iT KEEPS on showing me this issue about  
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\\AppData\Local\Bloxstrap\Downloads\43c726b04ccfad6eb95e7ee2c25b33f0'. whenever i tryto run it and i wanna use it 
![Screenshot 2024-07-04 085521](https://github.com/pizzaboxer/bloxstrap/assets/174692166/93bf96a4-40e8-4a67-bb12-919a8288d791)

**Comment by eatmyfarts122** [comment]
Anyone know how  to fix it ?

**Comment by eatmyfarts122** [comment]
Anyone know the issue ?

**Comment by SlightlyBright** [comment]
im having the same exact issue

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
