### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Belugaz290** [pizzaboxer/bloxstrap#2245]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: An attempt was made to access a socket in a manner prohibited by its access permissions. (clientsettings.roblox.com:443)

[InnerException]
System.Net.Sockets.SocketException: An attempt was made to access a socket in a manner prohibited by its access permissions

**Comment by Belugaz290** [comment]
![image_2024-07-04_112208133](https://github.com/pizzaboxer/bloxstrap/assets/174699267/ffce96fd-528e-41cb-aa58-5d653f7bdddb)

**Comment by pizzaboxer** [comment]
VPN/Antivirus issue.
