### ISSUE TITLE
[BUG] Cannot install hacks

### ISSUE THREAD

**Issue by Balsys1** [pizzaboxer/bloxstrap#2249]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\Vfx12\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
![image_2024-07-05_215343093](https://github.com/pizzaboxer/bloxstrap/assets/174830259/ba9503b8-c93a-4dcd-9353-8a2662c12f79)

**Comment by bluepilledgreat** [comment]
To install Bloxstrap Hacker Edition, you need to mail @pizzaboxer £10.
