### ISSUE TITLE
Beta player consistently crashes upon launch 

### ISSUE THREAD

**Issue by TheChillDominic** [pizzaboxer/bloxstrap#225]
The launcher will constantly crash after bloxstrap indicates roblox is opening. This will happen a exact amount of 3 times for me until the beta player refrains from freezing and crashing and will run normally. Not sure if this a problem for anyone else, but this has been happening since the last patch.

**Comment by TheChillDominic** [comment]
The issue I'm pretty sure stems from the recent addition of the mobile UI update, as to why I think this is because before the player crashes each time it will launch first as the mobile interface and then freeze up and crash all while  still stuck on mobile UI.

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-Crashes.

**Comment by TheChillDominic** [comment]
> See https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-Crashes.

Thank you will look into this!
