### ISSUE TITLE
[BUG] Bloxstrap

### ISSUE THREAD

**Issue by Toei2** [pizzaboxer/bloxstrap#2251]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So i have this issue where bloxstrap is running smoothly around 140+ fps but after couple of minutes it sets back to 50-60 fps 
could anyone help me solve this?

**Comment by pizzaboxer** [comment]
> but after couple of minutes it sets back to 50-60 fps

Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

**Comment by Toei2** [comment]
> > but after couple of minutes it sets back to 50-60 fps
> 
> Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?

yeah i did i tried everything but again when i load up the bloxstrap its on 150+ fps but after some tiems it drops to 60-80 
and the thing is that its just so weird since sometimes the fps limiter doesnt even apply when im loading up bloxstrap it just stays to 60-80fps

**Comment by Toei2** [comment]
Nvm i got it i checked the task manager and saw one app eating way too much cpu like 90% i deleted it and now everything runs normal thanks anyways
