### ISSUE TITLE
[BUG] theres an annoying bug that i get alot in games which is the potato graphics it makes my effects, icons and quality look worse and i dont have a mod or fflag that makes my graphics super bad for more preformance so id thank you if you fix this bug  if you dont notice the things well its the robux icon and notification icon and other games icons become kinda worse and more pixelated

### ISSUE THREAD

**Issue by DeltaruneAddict** [pizzaboxer/bloxstrap#2252]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![graphicissue](https://github.com/pizzaboxer/bloxstrap/assets/173432021/066d4116-143f-43e1-9686-96db519c4c7d)

![issuegraphic2](https://github.com/pizzaboxer/bloxstrap/assets/173432021/5b86bbf7-04ce-4bbc-95b7-b9bde8b426df)

**Comment by toofastforboo** [comment]
you probably have:
"DFFlagTextureQualityOverrideEnabled"
"DFIntTextureQualityOverride" enabled, which is:

"DFFlagTextureQualityOverrideEnabled" — **activates quality override**
"DFIntTextureQualityOverride": [number 0 - 3] — **will tell how blurry it will be**

0 - very very blurry
1 - blurry
2 - between good and blurry
3 - default by roblox and nothing blurry

so if it's:
{
"DFFlagTextureQualityOverrideEnabled": true,
"DFIntTextureQualityOverride": 3
}
should fix the icon

**Comment by pizzaboxer** [comment]
Upload your configuration please:

https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by DeltaruneAddict** [comment]
> Upload your configuration please:
> 
> https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration
[State.json](https://github.com/user-attachments/files/16115276/State.json)
[Settings.json](https://github.com/user-attachments/files/16115277/Settings.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/16115279/ClientAppSettings.json)

this?

**Comment by pizzaboxer** [comment]
Yes, thanks.

All looks good, you may just need to force your texture quality as @toofastforboo described, by opening the Fast Flag editor (at the bottom of the page), clicking "Add new", selecting "Import JSON", and pasting this in:

```json
{
    "DFFlagTextureQualityOverrideEnabled": true,
    "DFIntTextureQualityOverride": 3
}
```

**Comment by DeltaruneAddict** [comment]
> Yes, thanks.
> 
> All looks good, you may just need to force your texture quality as @toofastforboo described, by opening the Fast Flag editor (at the bottom of the page), clicking "Add new", selecting "Import JSON", and pasting this in:
> 
> ```json
> {
>     "DFFlagTextureQualityOverrideEnabled": true,
>     "DFIntTextureQualityOverride": 3
> }
> ```

thanks
