### ISSUE TITLE
[BUG] error code 277

### ISSUE THREAD

**Issue by SignorTumbler** [pizzaboxer/bloxstrap#2256]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I launch a game, it kicks me out of the game with a disconnection error 277 but it doesnt happen on normal Roblox app or website version.
![Screenshot 2024-07-06 171725](https://github.com/pizzaboxer/bloxstrap/assets/174890883/0c8cc7a8-9ffe-417a-8d06-5f99461655ba)

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by SignorTumbler** [comment]
[ClientAppSettings.json](https://github.com/user-attachments/files/16131713/ClientAppSettings.json)
[Settings.json](https://github.com/user-attachments/files/16131715/Settings.json)
[State.json](https://github.com/user-attachments/files/16131716/State.json)

**Comment by pizzaboxer** [comment]
You're sure this happens only with Bloxstrap?

**Comment by SignorTumbler** [comment]
Yes, I'm sure. I have followed every tutorial that addresses this bug, but none of them have worked. Thats why Im here.

**Comment by pizzaboxer** [comment]
What do you mean by "website version"?

**Comment by SignorTumbler** [comment]
I mean roblox.com. Bloxtrap isnt working for me rn, it keeps disconnecting me.

**Comment by pizzaboxer** [comment]
If this is still happening, it's almost certainly an antivirus issue that's firewalling network activity from Roblox because Bloxstrap is launching it. Check for anything that could be causing that.
