### ISSUE TITLE
[BUG] RobloxPlayerBeta

### ISSUE THREAD

**Issue by lolrevios** [pizzaboxer/bloxstrap#2259]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When u install the system into  revi os (https://revi.cc/) into u computer roblox doesnt wanna open.

**Comment by pizzaboxer** [comment]
What does this have to do with Bloxstrap?

**Comment by ShadowCodeX-debug** [comment]
@lolrevios please send the log file.
