### ISSUE TITLE
[BUG] can't tab out when fullscreened (ctrl + esc) using latest version

### ISSUE THREAD

**Issue by premedicc** [pizzaboxer/bloxstrap#2260]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

uhh so whenever im in a game when i press ctrl + esc it doesnt let me tab out, but when im not fullscreened in roblox it does.

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
