### ISSUE TITLE
npcs and players glitching and being like i have high ping while my ping is 100

### ISSUE THREAD

**Issue by zeyrox13** [pizzaboxer/bloxstrap#2261]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

thats my fflags : {
  "FFlagHandleAltEnterFullscreenManually": "False",
  "DFIntTaskSchedulerTargetFps": "150",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "DFIntDebugFRMQualityLevelOverride": "1",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "DFIntTextureQualityOverride": "3",
  "DFIntConnectionMTUSize": "900",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FFlagDebugDisableTelemetryPoint": "True",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "FFlagDebugDisableTelemetryV2Stat": "True",
  "FFlagDebugSkyGray": "True",
  "FFlagDebugDisplayFPS": "True",
  "FIntFRMMinGrassDistance": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FIntRenderGrassDetailStrands": "0",
  "FintRenderGrassHeightScaler": "0",
  "DFIntMaxFrameBufferSize": "1",
  "DebugGraphicsDisableVulkan": "True",
  "DebugGraphicsDisableVulkan11": "True",
  "DebugGraphicsDisableOpenGL": "True",
  "DebugGraphicPreferD3D11": "True",
  "FIntRobloxGuiBlurIntensity": "0",
  "FIntFullscreenTitleBarTriggerDelayMillis": "18000000",
  "FFlagFastGPULightCulling3": "True",
  "FFlagNewLightAttenuation": "True",
  "FFlagDisablePostFx": "True",
  "DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent": "0",
  "DFIntClientLightingEnvmapPlacementTelemetryHundredthsPercent": "100",
  "FIntMockClientLightingTechnologyIxpExperimentMode": "0",
  "FIntMockClientLightingTechnologyIxpExperimentQualityLevel": "7",
  "FFlagMSRefactor5": "False",
  "FLogNetwork": "7"
}

**Comment by pizzaboxer** [comment]
> thats my fflags

Delete all of these and I'm sure your problem will be resolved.

**Comment by ShadowCodeX-debug** [comment]
Remove the following:
- DFIntConnectionMTUSize
- DFIntMaxFrameBufferSize
