### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yusuf123qwe** [pizzaboxer/bloxstrap#2263]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![resim_2024-07-07_134056657](https://github.com/pizzaboxer/bloxstrap/assets/174937819/8ae0ca65-0aac-4f5b-9f91-91b9ffecc05c)

**Comment by Arlindk15** [comment]
i have this problem i cant fix  can anyone help us?

**Comment by pizzaboxer** [comment]
Send the log file

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
