### ISSUE TITLE
[BUG] Fps doesn't set to more than 240

### ISSUE THREAD

**Issue by lofinsxd** [pizzaboxer/bloxstrap#2265]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I set more than 240 fps in bloxstrap, it doesn't set it to the limit, for example 300, nor when I set the fps cap to 9999(unlimited), it just sets the fps cap to 240.
This is in no way related to my gpu or cpu, as I have a Ryzen 7 5700g and RTX 3060 which is definitely capable of handling more than 240 fps(I literally joined an empty baseplate and set the graphics to lowest possible). Also, the fastflags editor seems to work normally, targetfps is set to 9999.
I have checked nvidia control panel, everything, set power management mode to "Prefer Maximum Performance", set "High Performance" power plan in windows, the fps cap still can't go more than 240
![image](https://github.com/pizzaboxer/bloxstrap/assets/174957330/bdbf5060-754e-4922-93e6-e52cc91bcf23)
![image](https://github.com/pizzaboxer/bloxstrap/assets/174957330/be1247ec-f818-48aa-938f-7fac086ca3f7)
![image](https://github.com/pizzaboxer/bloxstrap/assets/174957330/5fa2f34f-b89d-40b1-bc3f-5386437fdc69)

**Comment by toofastforboo** [comment]
well, if you are facing problems related to the maximum amount of fps on your Roblox you can try two things:
1. [Checkout the wiki page about roblox still capped.](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter)
2. Go to your FFlag editor and add:
```json
{
    "FFlagTaskSchedulerLimitTargetFpsTo240": "False",
    "FFlagTaskSchedulerLimitTargetFpsTo2402": "False"
}
```

**Comment by lofinsxd** [comment]
Idk why yall closed this as "completed" because it seems like the fps is still capped at 240😂Even after adding the "FFlagTaskSchedulerLimitTargetFpsTo240": "False" fast flag
![image](https://github.com/pizzaboxer/bloxstrap/assets/174957330/7fcdc9f9-9159-4d59-871e-93ad2df08cfe)
![image](https://github.com/pizzaboxer/bloxstrap/assets/174957330/2ba00e4b-6e51-4862-95c2-027bef50296a)

**Comment by bluepilledgreat** [comment]
closed the wrong post

**Comment by ShadowCodeX-debug** [comment]
@lofinsxd send your flag list (export)

**Comment by pizzaboxer** [comment]
> When I set more than 240 fps in bloxstrap

You shouldn't be setting it to more than 240, Roblox caps to that for a reason, and you sure as hell don't need it. Ignore the subtext about setting it to 9999 for no limit, that information is outdated and I forgot to update it.

If you still want more than 240, use the flags that @toofastforboo provided. If they still don't work, there isn't much else you can do.

**Comment by Sithnix** [comment]
> > When I set more than 240 fps in bloxstrap
> 
> You shouldn't be setting it to more than 240, Roblox caps to that for a reason, and you sure as hell don't need it. Ignore the subtext about setting it to 9999 for no limit, that information is outdated and I forgot to update it.
> 
> If you still want more than 240, use the flags that @toofastforboo provided. If they still don't work, there isn't much else you can do.

Erm we sure as hell do, monitors go past 240hz, i have a 360hz monitor and wanna uncap my fps to get the max refresh rate, as well as uncapped fps is better for shooters. (gives the monitor a fresher and newer frame even if you refresh rate is low) We also have monitors that reach 540hz now and it will continue to increase so we "sure as hell" do need it.

**Comment by pizzaboxer** [comment]
this is the biggest cope ive ever seen

**Comment by PringleKitten** [comment]
Also useful for rhythm based games / lower latency

**Comment by sqpeedyy** [comment]
Did Roblox secretly add a cap, now the maximum i can get is 1250 fps.

**Comment by 7qz12** [comment]
for some reason now you cant get more than 240 i cant change it no more

**Comment by edit-rivals** [comment]
well just use the fflag  "DFIntTaskSchedulerTargetFps" :  "0" 
to uncap and its already inf
