### ISSUE TITLE
[BUG] An exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by Jackcial** [pizzaboxer/bloxstrap#2266]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![error](https://github.com/pizzaboxer/bloxstrap/assets/92947839/e5c90c70-66eb-4fc8-86d1-9f19890727d2)
[Bloxstrap_20240707T184354Z.log](https://github.com/user-attachments/files/16120354/Bloxstrap_20240707T184354Z.log)

**Comment by pizzaboxer** [comment]
Is this issue still happening?

**Comment by pizzaboxer** [comment]
Issue was addressed at https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-or-%22An-error-occurred-trying-to-start-process%22-regarding-RobloxPlayerBeta.exe
