### ISSUE TITLE
[BUG] Lag spike in Roblox

### ISSUE THREAD

**Issue by Missingno6** [pizzaboxer/bloxstrap#2269]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Ever since I downloaded Bloxstrap v2.6.1, after hearing about it. The program slowly starts having lap spikes upon entering the game. I uninstall it by uninstalling it as normal, but it still lag spikes after that.

**Comment by bluepilledgreat** [comment]
If this still happens after uninstalling Bloxstrap and going back to Roblox's bootstrapper, maybe its not a Bloxstrap issue.

**Comment by Missingno6** [comment]
I met it's happening before uninstalling it and after that it's still lag spiking

**Comment by pizzaboxer** [comment]
> I met it's happening before uninstalling it and after that it's still lag spiking

So then it's not a Bloxstrap problem.
