### ISSUE TITLE
[BUG] bloxtrap roblox not opening 

### ISSUE THREAD

**Issue by luke12345786** [pizzaboxer/bloxstrap#2272]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-07-08 141304](https://github.com/pizzaboxer/bloxstrap/assets/174984884/22379da3-ae5a-4aac-9733-ccc85231e185)
so when i try open play roblox it says starting roblox then opens nothing after that

**Comment by toofastforboo** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
