### ISSUE TITLE
[BUG] Log File Got denied

### ISSUE THREAD

**Issue by Frankie-Woz** [pizzaboxer/bloxstrap#2273]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

One of the Log Files got denied saying " System.UnauthorizedAccessException: Access to the path 'C:\Users\frwoz\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied. "

**Comment by toofastforboo** [comment]
Send the log file
