### ISSUE TITLE
[BUG] An exception occured while running bloxtrap

### ISSUE THREAD

**Issue by Angeelvxg** [pizzaboxer/bloxstrap#2274]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![imagen_2024-07-08_143749465](https://github.com/pizzaboxer/bloxstrap/assets/97472343/e54ee27f-e735-450e-9c97-c651a9252218)

**Comment by MinisInDaWall** [comment]
The same error you got. Got it today afternoon

**Comment by pizzaboxer** [comment]
You're not using the latest version. Go download it. https://github.com/pizzaboxer/bloxstrap/releases/latest
