### ISSUE TITLE
[BUG] Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-1088f3c8e4a44cc7-content-fonts.zip

### ISSUE THREAD

**Issue by kmrsyto** [pizzaboxer/bloxstrap#2275]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-1088f3c8e4a44cc7-content-fonts.zip

Got signature: 77ed28213bec3cbed79655943091c266
[Bloxstrap_20240708T221307Z.log](https://github.com/user-attachments/files/16134914/Bloxstrap_20240708T221307Z.log)

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox
