### ISSUE TITLE
[BUG] cant open roblox bloxstrap on web

### ISSUE THREAD

**Issue by kitsun6534** [pizzaboxer/bloxstrap#2279]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden). 
![image](https://github.com/pizzaboxer/bloxstrap/assets/169818856/fe957ee8-1aab-4ee3-8e91-e09ed2a1f8b4)

**Comment by pizzaboxer** [comment]
You're not using the latest version. Download it. https://github.com/pizzaboxer/bloxstrap/releases/latest
