### ISSUE TITLE
Custom Skyboxes [QUESTION]

### ISSUE THREAD

**Issue by sponkywonky** [pizzaboxer/bloxstrap#228]
How would I configure a custom skybox within bloxstrap, allowing for it to stay every roblox update?
I tried figuring out how the cursor texture worked, thinking it would be similar, but I can't figure it out.

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods?

**Comment by sponkywonky** [comment]
Smallest section for the most important part, wow
