### ISSUE TITLE
Bloxstrap limiting CPU usage?

### ISSUE THREAD

**Issue by bigbroke99** [pizzaboxer/bloxstrap#2280]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Lately I've been playing roblox with a lot of lag, when I checked task manager roblox only ever used 20%-30% CPU on my computer. Was wondering what was causing it since it was able to go up to 40%-50% before, I tried reinstalling roblox & bloxstrap but that didn't work so I tried deleting bloxstrap instead and it fixed the problem? I didn't have anymore lagspikes and the game was running smoothly, I'm just confused because I've had bloxstrap installed for a while now and only recently did I start getting issues with it. Does anyone have the same problem as me?

**Comment by pizzaboxer** [comment]
It isn't us limiting it, it's something else limiting it because it's seeing Roblox as being something else when being launched by Bloxstrap. If you turn of all the options in the integrations section of the Bloxstrap Menu, and then launch, does the issue go away?

**Comment by bigbroke99** [comment]
> It isn't us limiting it, it's something else limiting it because it's seeing Roblox as being something else when being launched by Bloxstrap. If you turn of all the options in the integrations section of the Bloxstrap Menu, and then launch, does the issue go away?

Turning off all of the options in the integrations section didn't work, alternatively instead of playing roblox through the website I played roblox through the "Play Roblox" shortcut and it fixed it

**Comment by pizzaboxer** [comment]
> alternatively instead of playing roblox through the website I played roblox through the "Play Roblox" shortcut and it fixed it

Oh.

Still, my point stands about it being something on your system seeing something differently. I can't really directly change anything about this.
