### ISSUE TITLE
[BUG] game doesnt load because of 'exception' ?

### ISSUE THREAD

**Issue by Noahfslol** [pizzaboxer/bloxstrap#2281]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when I go to press on bootstrap after downloading it and everything it just doesn't load up for me no matter how many times that I reinstall, it says that there was some sort of exception one time but I only got that once. it works on my other computer, but for some reason will not on this one, it used to work on this one though.

**Comment by pizzaboxer** [comment]
> it just doesn't load up for me no matter how many times that I reinstall

Have you read the relevant Wiki pages?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
