### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by KUNINSYT** [pizzaboxer/bloxstrap#2282]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

This is something that is in so many games! But in Roblox there is no -

Option to choose the game resolution for Dagoma 1200X720
So that Ladgoma can see more of the area of ​​the game as if you could see more of the map where you are located, by doing this you can increase the resolution/quality and then the game will be more central in seeing the area that will not be very limited.

**Comment by pizzaboxer** [comment]
Do you currently do this by simply resizing the window?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
