### ISSUE TITLE
[BUG] exception

### ISSUE THREAD

**Issue by David58120** [pizzaboxer/bloxstrap#2283]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[ERROR_LOG_39151777,0332.txt](https://github.com/user-attachments/files/16145669/ERROR_LOG_39151777.0332.txt)

**Comment by toofastforboo** [comment]
that's not even linked to bloxstrap
