### ISSUE TITLE
[BUG] Vulkan FastFlags cause "An unexpected error occured, and Roblox needs to quit. Sorry!"

### ISSUE THREAD

**Issue by purgat0r1um** [pizzaboxer/bloxstrap#2284]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Once I click play, Bloxstrap opens but it just goes to a white screen and the error message appears. I did some tweaking and found out that either one of these FastFlags cause the error, or both of them do.

FFlagDebugGraphicsPreferVulkan
FLogNetwork

![Screenshot 2024-07-10 003351](https://github.com/pizzaboxer/bloxstrap/assets/175144236/1fd846cc-ce6d-4661-b14d-90799446e167)

**Comment by toofastforboo** [comment]
in general, Vulkan causes problems, just remove it fflag(FFlagDebugGraphicsPreferVulkan) and leave it on automatic and you'll be fine.

**Comment by pizzaboxer** [comment]
Don't use Vulkan. I didn't mean to add it in the release. That was by accident. Keep it on automatic.
