### ISSUE TITLE
[BUG] Crashing roblox

### ISSUE THREAD

**Issue by LoiTheDonkey** [pizzaboxer/bloxstrap#2285]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I had bloxtrap on it would crash roblox but when i unistalled it it stopped crashing.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen

**Comment by LoiTheDonkey** [comment]
ohh I think I know why its crashing its because of byfron because I changed some setting on the terrain of the game that alerted byfron
