### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EchoMist** [pizzaboxer/bloxstrap#2286]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2024-07-09 122828](https://github.com/pizzaboxer/bloxstrap/assets/110472378/f849aee3-f9bd-41b5-82f5-12314bef96ad)

**Comment by pizzaboxer** [comment]
You're not using the latest version of Bloxstrap. https://github.com/pizzaboxer/bloxstrap/releases/latest
