### ISSUE TITLE
[BUG] Bloxstrap Menu still takes me to Roblox Player

### ISSUE THREAD

**Issue by IDontKnowWhyIamHer** [pizzaboxer/bloxstrap#2288]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap Menu, is one of the currently biggest problems right now. Here's why.
First up, when I open up Bloxstrap Menu, it starts loading Roblox Player and takes me there, instead of the ACTUAL Menu.
I used the search bar for Windows. I can't believe the only time I had access to the Menu was when I first installed Bloxstrap.
Please just fix this issue for my sake. It's starting to get annoying and out of hand.
Here's even MORE proof. When I try to find a way to uninstall, nothing works. I reinstall Bloxstrap, yet Menu takes me to Roblox Player.
Still don't believe me? Here's actual video evidence
Also this is my real computer.
https://github.com/pizzaboxer/bloxstrap/assets/169791544/eac8099b-ede2-4186-bd73-6b35d5e81a23

**Comment by pizzaboxer** [comment]
Send the latest log file from `%localappdata%\Bloxstrap\Logs` please

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
