### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DAIN90** [pizzaboxer/bloxstrap#2289]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap has been working fine until whenever im in a game and im taken to another server while in the game roblox closes with no error message or warning

**Comment by MHMHMHM121H** [comment]
yeah it keeps crashing

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
