### ISSUE TITLE
fat fps drop

### ISSUE THREAD

**Issue by BloomsEnd** [pizzaboxer/bloxstrap#229]
i get no more then 20 fps when playing with it installed.

**Comment by pizzaboxer** [comment]
Does anything change if you disable Discord Rich Presence and server details notifications?

**Comment by Boi2021Miceoos** [comment]
It probably because your have a weak PC, i have a PC that is old & installed bloxstrap runs only 30 fps

**Comment by WaviestBalloon** [comment]
> It probably because your have a weak PC, i have a PC that is old & installed bloxstrap runs only 30 fps

A bootstrapper shouldn't be making the client drop a large amount of frames

**Comment by pizzaboxer** [comment]
> A bootstrapper shouldn't be making the client drop a large amount of frames

Probably because of some of the features causing unintended side effects. The guy hasn't responded so I can't really track down what's happening, but I'm somewhat betting on it being the framerate limit FastFlag. Games that misuse RenderStepped can run into problems like this.

**Comment by Boi2021Miceoos** [comment]
im betting on the graphics card cause that what caused my low fps in my old pc even on a normal baseplate
Nvidia gtx 710

**Comment by pizzaboxer** [comment]
Yeah, but I'm assuming that always having low FPS isn't a problem for him and that it only ever happens with Bloxstrap/

**Comment by pizzaboxer** [comment]
Issue was made a month ago and has been awaiting clarification since, closing for now unless OP is able to provide more info.
