### ISSUE TITLE
[BUG] Takes too long for the app to start 

### ISSUE THREAD

**Issue by Cumpanasu1** [pizzaboxer/bloxstrap#2292]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/151031332/f755ab55-a3a9-470a-823d-77849f01f277)
![image](https://github.com/pizzaboxer/bloxstrap/assets/151031332/87c935c7-b287-4b96-9c5b-739c7028caad)

**Comment by pizzaboxer** [comment]
Okay, I'm not sure how it's possible that this can be happening. Is this still happening for you right now?

**Comment by Cumpanasu1** [comment]
> Okay, I'm not sure how it's possible that this can be happening. Is this still happening for you right now?

No its all fixed for me
