### ISSUE TITLE
[REQ] Move the FFlag Editor back to the top scrolling all the way down everytime is getting old.

### ISSUE THREAD

**Issue by ImMejor35** [pizzaboxer/bloxstrap#2296]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Move the FFlag editor button back to the top of the FFlag Tab.

**Comment by ImMejor35** [comment]
I get you don't make any money from this so no rush this was my only complaint but I also LOVED the new features you added <3

**Comment by pizzaboxer** [comment]
> Move the FFlag editor button back to the top of the FFlag Tab.

No, we moved it down there for a reason. Like 80% of the people using Bloxstrap shouldn't have such easy access to it.
