### ISSUE TITLE
[BUG] it seems as if roblox is overriding bloxstrap ability to uncap the fps because it's capped on 240 for some reason

### ISSUE THREAD

**Issue by userxfhq** [pizzaboxer/bloxstrap#2297]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it seems as if roblox is overriding bloxstrap ability to uncap the fps because it's capped on 240 for some reason

**Comment by pizzaboxer** [comment]
Yes, Roblox is doing that for a reason. You likely don't need more than 240.
