### ISSUE TITLE
[BUG] You must install.NET Desktop Runtime to run this application. Architecture: x64 App host version: 6.0.30 Would you like to download it now?               IT KEEPS SHOWING UP THIS WARNING AND I ALREADY HAVE IT INSTALLED AND IT WONT OPEN, PLEASE SOMEONE HELP ME

### ISSUE THREAD

**Issue by joaodwadsa** [pizzaboxer/bloxstrap#2299]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

You must install.NET Desktop Runtime to run this application.
Architecture: x64
App host version: 6.0.30
Would you like to download it now?

**Comment by pizzaboxer** [comment]
Open a Command Prompt window and run this command:

`dotnet --info`

Take a screenshot of what it shows, all of it, and send it here.

**Comment by joaodwadsa** [comment]
![imagem_2024-07-10_094841900](https://github.com/pizzaboxer/bloxstrap/assets/110791737/8cc8a1d5-a2f0-405e-bf07-193bd8fe8fda)
![imagem_2024-07-10_094856736](https://github.com/pizzaboxer/bloxstrap/assets/110791737/2d6a75e2-e829-4fb4-8369-132955880c27)
that is all it says

**Comment by pizzaboxer** [comment]
Can you check to make sure that your antivirus isn't placing any restrictions on Bloxstrap? Can you also show the contents of the `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.32` folder?

**Comment by 3isht** [comment]
> Can you check to make sure that your antivirus isn't placing any restrictions on Bloxstrap? Can you also show the contents of the `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.32` folder?

I got the same issue and here are pics of the folder.
![pic1](https://github.com/user-attachments/assets/6a9e6734-94e2-4885-9fe8-1f5f6e440403)
![pic2](https://github.com/user-attachments/assets/0655f085-cf58-4a24-9d50-176ab523d8b3)

**Comment by bloxdemon14** [comment]
so no one still fixed this cuz it is the same for me?

**Comment by StewTom14** [comment]
Is there any fix for this issue?

**Comment by 3isht** [comment]
> Is there any fix for this issue?

yes! I found a solution, download an older version of bloxstrap (2.4.7 if I'm not wrong) and then run it, it'll give the error but don't worry the link will work, just click on the link in the error and it'll take you to download the needed version of ".NET", after you download it just run it normally and it should work!

**Comment by 3isht** [comment]
> so no one still fixed this cuz it is the same for me?
> 

I found a solution, download an older version of bloxstrap (2.4.7 if I'm not wrong) and then run it, it'll give the error but don't worry the link will work, just click on the link in the error and it'll take you to download the needed version of ".NET", after you download it just run it normally and it should work!
