### ISSUE TITLE
RobloxLauncherBeta cant be found

### ISSUE THREAD

**Issue by Yoru-Yonaka** [pizzaboxer/bloxstrap#23]
I had the RobloxLauncherBeta, but it updated to RobloxPlayerLauncher, how do i fix this?

**Comment by pizzaboxer** [comment]
I'm sorry, could you please elaborate on the problem? What error does it show?

**Comment by Yoru-Yonaka** [comment]
it says an error occurred and that its searching for a file called
RobloxLauncherBeta
