### ISSUE TITLE
[Question] Doesn't support these several options anymore?

### ISSUE THREAD

**Issue by EnterUsername-design** [pizzaboxer/bloxstrap#2301]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

1. Anti Aliasing (MSAA)

Theres no OFF Option on Bloxstrap (start on 1X), I heard it can be off with fastflag

but any reason about not adding this? 

2. Rendering Mode : Vulkan (deleted)

Vulkan mode doesn't support Roblox anymore? 

Forcely Render Vulkan with FastFlag also no longer working?

**Comment by pizzaboxer** [comment]
> Theres no OFF Option on Bloxstrap (start on 1X), I heard it can be off with fastflag

Can it be? I haven't seen so.

> Vulkan mode doesn't support Roblox anymore?

No, it wasn't supposed to be added in 2.6. It had been added by accident. It's incredibly unstable and shouldn't be used.

**Comment by EnterUsername-design** [comment]
https://github.com/catb0x/Roblox-Potato-FFlags/tree/main 

theres fast flag 
{
  "FIntDebugForceMSAASamples": 0
}

<No, it wasn't supposed to be added in 2.6. It had been added by accident. It's incredibly unstable and shouldn't be used.>

That means vulkan rendering had bug and must not using nowtimes? (Because i thought thats the best rendering option before)
