### ISSUE TITLE
roblox not showing ; i tried opening the original roblox and it pops up but when i open play roblox (bloxstrap) it just shows in the taskbar tray (screenshot provided) ; also when i check my task manager roblox is there its just that i doesnt pop up/show on my screen

### ISSUE THREAD

**Issue by 3ndles5** [pizzaboxer/bloxstrap#2302]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/175193956/1f6711c5-8aed-41f1-b089-5e4616215ff3)

screenshot ^

**Comment by 3ndles5** [comment]
roblox not showing ; i tried opening the original roblox and it pops up but when i open play roblox (bloxstrap) it just shows in the taskbar tray (screenshot provided) ; also when i check my task manager roblox is there its just that i doesnt pop up/show on my screen

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/9wiki/Roblox-crashes-or-does-not-launch?

**Comment by 3ndles5** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/175193956/8479ec81-4e98-4eae-a58e-17e4bbffc8a8)

**Comment by pizzaboxer** [comment]
Sorry, wrong link: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
You ignore the preliminary instructions you were asked to read though if you haven't read this already.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
