### ISSUE TITLE
newest patch

### ISSUE THREAD

**Issue by MHMHMHM121H** [pizzaboxer/bloxstrap#2303]
in the newest update/patch some fflag i copy and pasted in no longer go in instead it asks if its a boolean or true or false which it cant be.

**Comment by MHMHMHM121H** [comment]
![Screenshot 2024-07-10 030419](https://github.com/pizzaboxer/bloxstrap/assets/156625947/9c568147-b999-4c0b-af94-f26c6f7a8bf0)

**Comment by pizzaboxer** [comment]
What's the point of censoring the name? I can't really debug this issue if I don't know what the flag name is.

**Comment by MHMHMHM121H** [comment]
sorry its, DFFlagDebugEnableInterpolationVisualizer when activating by pressing f8 it doesnt do anything is it patched or smth? (it was esp)

**Comment by d44df016fe28bc8d5974** [comment]
it has been patched
remove it
