### ISSUE TITLE
Account ban

### ISSUE THREAD

**Issue by cxc00123** [pizzaboxer/bloxstrap#2304]
审查时间: 24/07/10 GMT+8 17:23

管理员记录: Roblox does not permit the use of third-party software to modify the client.

Why？

**Comment by toofastforboo** [comment]
you should not use hack or scripter instead of complaining about it here.
https://github.com/pizzaboxer/bloxstrap/wiki/Why-it's-not-reasonably-possible-for-you-to-be-banned-by-Bloxstrap

**Comment by cxc00123** [comment]
i not use hack or scripter

**Comment by VAizenV** [comment]
> you should not use hack or scripter instead of complaining about it here. https://github.com/pizzaboxer/bloxstrap/wiki/Why-it's-not-reasonably-possible-for-you-to-be-banned-by-Bloxstrap

It's about third-party softwares not scripting
