### ISSUE TITLE
[BUG] Vulkan and OpenGL not avaible now?

### ISSUE THREAD

**Issue by Shavixinio** [pizzaboxer/bloxstrap#2305]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Only Direct3D 11 and 10 is avaible now. Was that an intentional removal? Vulkan really helped me with performance.

![image](https://github.com/pizzaboxer/bloxstrap/assets/54279284/2d0abf6c-3568-4660-bdfa-e1a56e276bc0)

**Comment by toofastforboo** [comment]
it's been some time since Vulkan was removed from that menu if im not mistaken, due to instability and various problems in general. 
its __VERY__ recommended not to use but you can just add this flag to use vulkan:
```json
{"FFlagDebugGraphicsPreferVulkan": "true"}
```

**Comment by Shavixinio** [comment]
I had auto updates on and it was just there yesterday, so it must have been removed recently, but I guess problem solved
