### ISSUE TITLE
[REQ] pls add vulkan and openGL renderer

### ISSUE THREAD

**Issue by SteveThe00** [pizzaboxer/bloxstrap#2308]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I want vulkan and openGL renderer

**Comment by Storm-930** [comment]
i'm gonna fucking scream

`FFlagDebugGraphicsPreferVulkan true`

**Comment by pizzaboxer** [comment]
We removed them because they're unstable and weren't actually supposed to be added in 2.6, that was by accident.
