### ISSUE TITLE
take down `bloxstrap.org`

### ISSUE THREAD

**Issue by VermeilChan** [pizzaboxer/bloxstrap#2310]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

^ _read title_
im not sure if you can but my friend today made the dumb mistake of downloading it from there and im not sure if its a malware or keylogger or even worst.

**Comment by pizzaboxer** [comment]
> im not sure if you can 

No, I can't. I've tried.

> but my friend today made the dumb mistake of downloading it from there and im not sure if its a malware or keylogger or even worst.

That website is safe (not that I'd recommend using any third party websites)
