### ISSUE TITLE
Moderation issues [BUG] 

### ISSUE THREAD

**Issue by speedy507MA** [pizzaboxer/bloxstrap#2311]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've been using Bloxstrap for a while now and, as the mention about not getting banned for it suggested, never got banned. When the new update rolled around, however I almost immediately got kicked and banned for a day because of it.
<img width="838" alt="Screenshot 2024-07-10 at 11 31 38 AM" src="https://github.com/pizzaboxer/bloxstrap/assets/77637194/b9126226-f775-4581-8804-20f89731d787">

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Why-it's-not-reasonably-possible-for-you-to-be-banned-by-Bloxstrap
