### ISSUE TITLE
[BUG] Discord RPC doesn't have join button.

### ISSUE THREAD

**Issue by puhbu** [pizzaboxer/bloxstrap#2312]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hey! Not sure if it's something on my end, but recently, even if i have the "Allow Activity joining" option checked, my RPC doesn't have any join buttons.
![image](https://github.com/pizzaboxer/bloxstrap/assets/78015856/32c8241c-d474-4747-bb3e-a4cefc7d91fd)
(ignore the game im playing i was testing)
![image](https://github.com/pizzaboxer/bloxstrap/assets/78015856/b57a7396-6fff-46ba-908a-b0ef80fa65e5)

**Comment by pizzaboxer** [comment]
It was working fine literally just yesterday, I hope Discord didn't make a breaking change to the RPC API?

**Comment by pizzaboxer** [comment]
Never mind, Discord just hides it from your own profile now. It'll still be visible to other people.

**Comment by puhbu** [comment]
oh alright, i see, discord moment
