### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by googoois** [pizzaboxer/bloxstrap#2314]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap stuck on configuring Roblox.
![image](https://github.com/pizzaboxer/bloxstrap/assets/175256634/92c9b95c-d5f5-4c21-ae1b-5c8e86820ef5)

**Comment by pizzaboxer** [comment]
Can you send Bloxstrap's latest log file please? If you're installing for the first time, it'll be at `%temp%`. If not, it'll be at `%localappdata%\Bloxstrap\Logs`

**Comment by googoois** [comment]
Its fixed now, Just had to installl widowns runtime.
