### ISSUE TITLE
puting json correctly but error

### ISSUE THREAD

**Issue by ShadowUsh** [pizzaboxer/bloxstrap#2317]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot_1](https://github.com/pizzaboxer/bloxstrap/assets/111083334/8d6bb9b6-dfdc-46e9-8ddd-7446c88a949b)

**Comment by pizzaboxer** [comment]
Your JSON isn't correct then. Post it here and let me see what it is.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
