### ISSUE TITLE
[BUG] bloxstrap crashes on opening 

### ISSUE THREAD

**Issue by random407** [pizzaboxer/bloxstrap#2318]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

bloxstrap crashing when i open it even when i open from website only happens with blox strap
![Screenshot 2024-07-11 042907](https://github.com/pizzaboxer/bloxstrap/assets/175311950/8b037d65-e1dc-494f-b181-368aa9668f44)

**Comment by pizzaboxer** [comment]
Thank you for unchecking the checkbox that says you read the instructions.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

I'll reopen it once you've done so.
