### ISSUE TITLE
My Bloxstrap Menu looks like a 480p png file

### ISSUE THREAD

**Issue by theproxd0-lua** [pizzaboxer/bloxstrap#2321]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

There is some proof of that and it is quite annoying ...
![image](https://github.com/user-attachments/assets/a3da3f74-7b92-4550-8ef5-4d799a3096c6)
Can't stand it man, it looks like a png I downloaded from a random google search.

**Comment by PeekoYT** [comment]
mines like that too! I have no idea why. It just started happening

**Comment by Danissohandsome** [comment]
Exactly how mine looks, and I can't change graphics nor interact with anything.

**Comment by pizzaboxer** [comment]
Open the Bloxstrap Menu, go to the Fast Flags tab, and set your texture quality to the highest.
