### ISSUE TITLE
[REQ] "Sort By" / "Sort From" Tab in FastFlag editor section

### ISSUE THREAD

**Issue by xbasvj** [pizzaboxer/bloxstrap#2323]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i know that you guys publicly announced that you're no longer taking suggestions as everything useful has already been implemented.. but i have a suggestion for something that is SUPER useful for people with a lot of fastflags (which is many)

my one and only suggestion is to add a "sort from"/"sort by"/"date created" tab in the fastflag editor section, so you can sort the date every individual fastflag was added, to keep track, since most ppl can't even read fastflags/jsons properly, it'll make it easy to troubleshoot which one is fucking up their gameplay if they can sort by when it was added

ty in advance pls put it into consideration

**Comment by pizzaboxer** [comment]
I'm not sure if that would be worth doing since that would take too much work to implement for a feature that's very likely going to be gone in the next few months, sorry.

**Comment by xbasvj** [comment]
lazy ass nigga

**Comment by EasternBloxxer** [comment]
> lazy ass nigga

Why dont you add it yourself you have the source

**Comment by Skylan031** [comment]
"hey add this to that" "no its probably going to be removed soon" "fuck you"

**Comment by EasternBloxxer** [comment]
> "hey add this to that" "no its probably going to be removed soon" "fuck you"

Wasnt really a fuck you just called him lazy

**Comment by GoingCrazyDude** [comment]
> Why dont you add it yourself you have the source

Can you shut up and let him speak? Thanks.

**Comment by xbasvj** [comment]
> Why dont you add it yourself you have the source

ykw.
u right

**Comment by EasternBloxxer** [comment]
> > Why dont you add it yourself you have the source
> 
> Can you shut up and let him speak? Thanks.

pajeet

**Comment by EasternBloxxer** [comment]
> > Why dont you add it yourself you have the source
> 
> Can you shut up and let him speak? Thanks.

The ragebait is wild. Do you really need attention that much?
