### ISSUE TITLE
[BUG] VC Issue

### ISSUE THREAD

**Issue by PatrycjuszGilZapas** [pizzaboxer/bloxstrap#2324]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I can hear everyone on voice chat, I can play binds and songs from the soundpad but not my voice. With uninstalled flags it still doesn't help.

**Comment by pizzaboxer** [comment]
![image](https://github.com/user-attachments/assets/0599451c-f79a-417a-bc3c-3a8aaec36553)

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I'll reopen this once you've confirmed this.
