### ISSUE TITLE
[BUG] Vulkan Rendering Option (And Other Rendering Options Other Than Direct3D11 and 10) Gone

### ISSUE THREAD

**Issue by notdonte** [pizzaboxer/bloxstrap#2326]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/ec3dce74-6926-4918-96c6-0826b2ec6b7f)
Not mentioned in the patch notes, but the rendering options are straight up missing despite working previously. Definitely unique to 2.7.0, as the previous version I was just using was on Vulkan for discord streaming bugs with my hardware.

**Comment by LivelyBadGod** [comment]
Experiencing this same problem! I have nothing more to add though.

**Comment by notdonte** [comment]
They were removed for a bit for being "buggy", but then added back into the rendering tab with a warning related to how buggy they were. Them being gone seems unintentional.

**Comment by icodebadthings** [comment]
> It got removed because they were buggy, Here are the Fast Flags to enable them
> 
> **OpenGL: `{ "FFlagDebugGraphicsPreferOpenGL": "True" }`** **Vulkan: `{ "FFlagDebugGraphicsPreferVulkan": "True" }`**

These fast flags dont apply for some reason

**Comment by icodebadthings** [comment]
yeah i do

**Comment by pizzaboxer** [comment]
> Them being gone again seems unintentional

Them being in v2.6.0 was unintentional*

**Comment by BlueTree242** [comment]
> > Them being gone again seems unintentional
> 
> Them being in v2.6.0 was unintentional*

The question is why you removed it? Vulkan is very stable, when you removed it i only realized when i got stuttering in some intensive games. If vulkan causes issues to some people, mainly those with low end hardware, it doesn't mean you should remove it. This is user's choice.
