### ISSUE TITLE
[REQ] Legacy Chat

### ISSUE THREAD

**Issue by vieir40** [pizzaboxer/bloxstrap#2327]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would to know if it is possible to use the old version of the Roblox chat ('/' instead of ';' to chat).
![Captura de Tela (587)](https://github.com/user-attachments/assets/47babdd9-51c7-402c-bb5b-3e736f7a8a77)

**Comment by pizzaboxer** [comment]
The key to chat depends on your system keyboard layout. It's still / for English keyboards.
