### ISSUE TITLE
[BUG] Graphics slider wont work.

### ISSUE THREAD

**Issue by retdefq** [pizzaboxer/bloxstrap#2328]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

If I try decreasing or increasing the graphics using the graphics quality slider, nothing happens. No increase in render distance or graphics. pls help

a video for demonstration: https://youtu.be/9eYXy884DXU?si=HZ8McRIPO9mAyCGd

**Comment by bill-lol** [comment]
> > im sorry but how do you actually do this
> 
>  2024-07-12-13-22-00.mp4

well for me that actually doesnt show yet i still have the issue

**Comment by bill-lol** [comment]
> > > im sorry but how do you actually do this
> > 
> > 
> > 2024-07-12-13-22-00.mp4
> 
> well for me that actually doesnt show yet i still have the issue

ive actually had the issue on normal roblox too after completely uninstalling bloxstrap and roblox from my pc and freshly installing them

**Comment by retdefq** [comment]
So the fflag DFIntDebugFRMQualityLevelOverride actually breaks ur graphics slider, forcing you to reinstall both bloxstrap and roblox. I hope pizza adds a feature similar to DFIntDebugFRMQualityLevelOverride fflag without breaking the graphics slider.

**Comment by retdefq** [comment]
accidentally closed the issue, sorry :p

**Comment by retdefq** [comment]
**UPDATE**: I think roblox is the issue here. Reinstalled bloxstrap and roblox and checked if it works, as soon as you join another game, roblox bugs the graphics forcing it to max. Btw the bloxstrap doesnt have any custom fflags whatsoever. 

pls help 😭

**Comment by apfeltee213** [comment]
maybe play on a different browser

**Comment by retdefq** [comment]
> maybe play on a different browser

YOO THANK YOU BRO, it finally works. Although im still confused why do I have to switch browsers, and I want to know the problem in more detail, im glad that it works rn. Again thank you :DDD
