### ISSUE TITLE
Bloxstrap 2.7.0 virus 

### ISSUE THREAD

**Issue by FartByte** [pizzaboxer/bloxstrap#2331]
when i downloaded bloxstrap 2.7.0 my pc detected that there is a virus in it. is  there really a virus in bloxstrap?

**Comment by FartByte** [comment]
bro what the sigma?

**Comment by pizzaboxer** [comment]
If you downloaded it from here or from https://bloxstrap.pizzaboxer.xyz then it's a false positive.
