### ISSUE TITLE
[BUG] Multiple accounts 

### ISSUE THREAD

**Issue by efsanreyiz** [pizzaboxer/bloxstrap#2332]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Why was the ability to play games with multiple accounts removed?

**Comment by negga599** [comment]
type https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.0  this is an version with this function

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
