### ISSUE TITLE
[BUG] unathurazied thingy

### ISSUE THREAD

**Issue by dumsthepublisher** [pizzaboxer/bloxstrap#2333]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

UNATHURAZED ERROR

**Comment by mvqna** [comment]
bru

**Comment by pizzaboxer** [comment]
Can you give any information please?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
