### ISSUE TITLE
the fast flags command is not working in the roblox game

### ISSUE THREAD

**Issue by looginas** [pizzaboxer/bloxstrap#2336]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I put DFFlagDebugEnableInterpolationVisualizer in the command code and it doesn't work, This basically serves to see the players inside the game

**Comment by d44df016fe28bc8d5974** [comment]
esp stopped working this week
just remove it

**Comment by Storm-930** [comment]
i swear dude people just keep handing themselves out

**Comment by looginas** [comment]
oh yes, thanks for your time

[Ícone "Verificada pela comunidade"]


________________________________
De: FanaticExplorer ***@***.***>
Enviado: sexta-feira, 12 de julho de 2024 13:37
Para: pizzaboxer/bloxstrap ***@***.***>
Cc: looginas ***@***.***>; Author ***@***.***>
Assunto: Re: [pizzaboxer/bloxstrap] the fast flags command is not working in the roblox game (Issue #2336)


#1321<https://github.com/pizzaboxer/bloxstrap/issues/1321>
no more flags bud

**Comment by looginas** [comment]
I don't understand, what did you mean?

[Ícone "Verificada pela comunidade"]


________________________________
De: Storm-930 ***@***.***>
Enviado: sexta-feira, 12 de julho de 2024 17:47
Para: pizzaboxer/bloxstrap ***@***.***>
Cc: looginas ***@***.***>; Author ***@***.***>
Assunto: Re: [pizzaboxer/bloxstrap] the fast flags command is not working in the roblox game (Issue #2336)


i swear dude people just keep handing themselves out

**Comment by looginas** [comment]
Oh yes, OK
________________________________
De: d44df016fe28bc8d5974 ***@***.***>
Enviado: sexta-feira, 12 de julho de 2024 16:32
Para: pizzaboxer/bloxstrap ***@***.***>
Cc: looginas ***@***.***>; Author ***@***.***>
Assunto: Re: [pizzaboxer/bloxstrap] the fast flags command is not working in the roblox game (Issue #2336)


esp stopped working this week
just remove it
