### ISSUE TITLE
An exception occurred while running Bloxstrap [BUG] 

### ISSUE THREAD

**Issue by XJayPlaysYT** [pizzaboxer/bloxstrap#2337]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So I am using version 2.5.4 for the multi instance since the removal of it and I got this error code while trying to start Roblox "Response status code does not indicate success: 403 (Forbidden)" Anyone else got this?

**Comment by derpzisonthehub** [comment]
same here

**Comment by pizzaboxer** [comment]
Might have to do with the fact that you're using a 9 month old version.
