### ISSUE TITLE
Bug when ı was starting roblox 

### ISSUE THREAD

**Issue by Soviet-user** [pizzaboxer/bloxstrap#2339]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).       I have no knowledge in programming and ı got locked out of discord. so ı  had to open a github account Goodluck

**Comment by pizzaboxer** [comment]
You're using an old version of Bloxstrap. https://github.com/pizzaboxer/bloxstrap/releases/latest
