### ISSUE TITLE
Bloxstrap Installer Not Opening

### ISSUE THREAD

**Issue by mvqna** [pizzaboxer/bloxstrap#2340]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I ran the Bloxtrap installer (the latest version 2.7.0) and when I opened it, nothing happened (I downloaded it from the official GitHub, so I don't think I got any malware). Then I tried running it as an administrator, and still nothing. I reinstalled it and still nothing. I have the .NET 6 Desktop Runtime, so I have the necessary dependencies. Honestly, I don't know what to do.

By the way, I don't get any message error or anything like that, it just doesnt open

And i have Windows 11

**Comment by mvqna** [comment]
plis anyone save my skibidi sigma rizz prbolemn

**Comment by mvqna** [comment]
fuck pizzabloxer frfr

**Comment by mvqna** [comment]
okay, soo i have this issue and nobody has help me

**Comment by pizzaboxer** [comment]
Still happening?

**Comment by mvqna** [comment]
nope, it was my windows 11, for some reason i deupgrated to 10 and it worked! windows 11 shitty!
