### ISSUE TITLE
When I install Bloxstrap, the installer shows this error.

### ISSUE THREAD

**Issue by senina4** [pizzaboxer/bloxstrap#2343]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When I install Bloxstrap, the installer shows this error:
![error](https://github.com/user-attachments/assets/cf2503d7-1085-42e1-912f-1ac6ca04888f)

**Comment by pizzaboxer** [comment]
Send the log file please

**Comment by senina4** [comment]
> Send the log file please

Sorry, I found the issue, this is my antivirus issue.
