### ISSUE TITLE
Why does the bloxstrap cilent need a mouse, What if I dont have a mouse? [BUG] 

### ISSUE THREAD

**Issue by ProOS11** [pizzaboxer/bloxstrap#2344]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Why do i have to click with two fingers and not one on the touch pad of my laptop in the bloxstrap client? you need a mouse but I dont, can you fix this?

**Comment by blueiicey** [comment]
skill issue

**Comment by pizzaboxer** [comment]
> Why do i have to click with two fingers

Where do you have to click with two fingers?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
