### ISSUE TITLE
[REQ] A setting similar to DFIntDebugFRMQualityLevelOverride

### ISSUE THREAD

**Issue by retdefq** [pizzaboxer/bloxstrap#2347]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

~~Right now, the fflag "**DFIntDebugFRMQualityLevelOverride**" breaks your graphics slider, making it unusable.~~

~~**To learn more about the issue, here:** https://github.com/pizzaboxer/bloxstrap/issues/2328~~

~~I want a setting that is similar to this fflag for better perfomance, maximizing the distance you can see without having to worry about the fps going down. (yes I literally use a device meant for workspace, not gaming)~~

The issue is fixed by switching browsers and/or reinstalling your browser.

**Comment by kelpist** [comment]
Same, let me know if you find a setting.
