### ISSUE TITLE
[BUG] PlaceFilter being blocked due to fflag being DFFlag

### ISSUE THREAD

**Issue by Itsappuru** [pizzaboxer/bloxstrap#2348]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/99830e16-0ea7-4c23-9cde-5999ae49e443)

**Comment by pizzaboxer** [comment]
Known bug, sorry about that.
