### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by 00000000000000000001ai** [pizzaboxer/bloxstrap#2352]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I clicked add new to **fast flags**, then import json, then clicked **ok**, confirmed the long flags click **ok** and i got 
```
System.NullReferenceException: Object reference not set to an instance of an object came out.
```
***LOG FILE***:
[Bloxstrap_20240713T142326Z.log](https://github.com/user-attachments/files/16202456/Bloxstrap_20240713T142326Z.log)

**Comment by pizzaboxer** [comment]
Can you also give a copy of the JSON list you tried to import?

**Comment by pizzaboxer** [comment]
Moved to #2468
