### ISSUE TITLE
[BUG] bloxstrap crashing out of nowhere

### ISSUE THREAD

**Issue by GordinTv** [pizzaboxer/bloxstrap#2353]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

My game normally runs with more than 100 fps on most Roblox servers using fflags, but from time to time the game simply crashes out of nowhere, stays stuck for about 5 seconds and returns to normal, and this happens regardless of the server I'm on

**Comment by pizzaboxer** [comment]
Check if it happens without Bloxstrap too: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

If it does, then upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
