### ISSUE TITLE
Bloxstrap is not going to open?

### ISSUE THREAD

**Issue by rybinmorski** [pizzaboxer/bloxstrap#2354]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I get an error code when launching bloxstrap, and just bloxstrap saying **System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).** How do i fix this?

**Comment by toofastforboo** [comment]
update your bloxstrap to 2.7.0

**Comment by pizzaboxer** [comment]
^
