### ISSUE TITLE
[BUG] gang why is my bloxstrap yellow

### ISSUE THREAD

**Issue by Sethjonas** [pizzaboxer/bloxstrap#2357]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

bro my bloxstrap is yellow and it wont stop being yellow

**Comment by Sethjonas** [comment]
its just like yellow

**Comment by pizzaboxer** [comment]
can you show a picture please

**Comment by pizzaboxer** [comment]
Someone else recently had this same issue, appears to be an issue with Nvidia relating to settings configured in the Nvidia control panel. You may want to check that.
