### ISSUE TITLE
manual uninstallation

### ISSUE THREAD

**Issue by LordFoogThe4rd** [pizzaboxer/bloxstrap#236]
what do I delete

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Uninstalling-Bloxstrap

**Comment by pizzaboxer** [comment]
Do you mean just delete the files for the game client only?

**Comment by bluepilledgreat** [comment]
> no I want to manually delete all the files I can't even start roblox now here's the crash log dump: https://send.portailpro.net/download/773e6870da192be3/#pmx9xptqX2ALNKghuYI8uQ expires after 30 days

this is roblox's fault. hyperion is acting up for certain systems, including mine.

**Comment by bluepilledgreat** [comment]
> guess I'll have to wait for an update then

the next update is also broken...

**Comment by pizzaboxer** [comment]
> everything related to bloxstrap. I know where to delete for roblox

I just told you how to do that...

**Comment by pizzaboxer** [comment]
Yeah, that's Roblox's crash handler.
