### ISSUE TITLE
[BUG] strange how bloxstrap is using wsappx and windows camera frame service

### ISSUE THREAD

**Issue by icomplaintoomuch** [pizzaboxer/bloxstrap#2362]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

what is this 
![Screenshot 2024-07-13 231833](https://github.com/user-attachments/assets/faeb2b91-91b0-46c9-b8ce-766fa67bf33d)

**Comment by icomplaintoomuch** [comment]
oh and this
![Screenshot 2024-07-13 232031](https://github.com/user-attachments/assets/bfd3578e-358a-4cff-8295-a8b137da70e2)

**Comment by BokBoy** [comment]
It could be Roblox's face thing that they have where the inbuilt character uses the camera to move your head.
Try checking with the normal roblox and see if the programs still are there.

**Comment by pizzaboxer** [comment]
xbox game bar and roblox facial animation feature

**Comment by icomplaintoomuch** [comment]
good point
