### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thiegoskip10** [pizzaboxer/bloxstrap#2363]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

**(this report was written by google translate)**
there's a bug that in any version the game won't open for some reason

**Comment by BokBoy** [comment]
Hello, 
Can we have a screenshot of what is there?
Thanks

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

Will reopen when you confirm you've read this
