### ISSUE TITLE
multi-instance mod gone from the menu.[BUG] 

### ISSUE THREAD

**Issue by memrman18** [pizzaboxer/bloxstrap#2364]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I have not played roblox in a hot minute, so I booted up the bloxtraps launcher and redownloaded it to the newest version and went to the menu, where I need to transfer some stuff to my alt and lo and behold, the multi-instance launcher option is gone. Please fix this as I don't have any other device that can run good enough to be able to transfer all my items 😭

**Comment by Nieznany237** [comment]
As far as I know, Bloxstrap developers have removed the "multi-instance" feature

**Comment by Nieznany237** [comment]
Here is why: https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
