### ISSUE TITLE
Bloxtrap need add last windowns versions

### ISSUE THREAD

**Issue by Brothers55** [pizzaboxer/bloxstrap#2366]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Because bloxtrap only work with windons 10 or normal system versions ı can only game version Windowns Wista 1 plase back add windows versions

**Comment by BokBoy** [comment]
Theres a couple reasons why thats not working. 
1. Windows Vista doesn't even support dotnet6. 
2. Vista computers.... unless you intentionally downgraded your pc, I don't think a Vista PC will run anything good.
Try using Linux and Vinegar
