### ISSUE TITLE
[BUG] this happens when i open bloxstrap

### ISSUE THREAD

**Issue by gigilovesapples23** [pizzaboxer/bloxstrap#2367]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by BokBoy** [comment]
"You're not using the latest version of Bloxstrap. https://github.com/pizzaboxer/bloxstrap/releases/latest"
-> Pizzaboxer
