### ISSUE TITLE
[BUG] Graphic didnt work

### ISSUE THREAD

**Issue by Marcelino40** [pizzaboxer/bloxstrap#2368]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/c9503809-8741-4978-b2c2-0ed1535d8af2)

*I already set the graphic till max but it doesn't change the graphic at all*

**Comment by pizzaboxer** [comment]
> I already set the graphic till max but it doesn't change the graphic at all

What are you comparing it to?

**Comment by Marcelino40** [comment]
I don't have anything to compare it with but, I set it to future phase 3 and nothing happened to the graphic after I set it to maximum graphic

**Comment by pizzaboxer** [comment]
Do you see no difference with minimum graphics? If so, then upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
