### ISSUE TITLE
For those who experiencing crashing without reason or "An unexpected error occured and Roblox needs to quit. We're sorry!"

### ISSUE THREAD

**Issue by RedyRT** [pizzaboxer/bloxstrap#237]
![изображение](https://github.com/pizzaboxer/bloxstrap/assets/64935439/fee78b27-0254-48c6-93af-b0f280b4c121)
Easy fix is do this:
1. Go to this path C:\Users\User\AppData\Local\Bloxstrap (where you installed bloxstrap)
2. Open Settings.json in this folder
3. You will see this
![изображение](https://github.com/pizzaboxer/bloxstrap/assets/64935439/8bee7627-230b-4391-a8f4-e090440e23d8)
4. all you had to do is change this settings
  "Channel": "LIVE",
  "ChannelChangeMode": 0,
  To this:
  "Channel": "zwinplayer64",
  "ChannelChangeMode": 1,
  Kinda like that:
![изображение](https://github.com/pizzaboxer/bloxstrap/assets/64935439/c9abfa44-dd23-4e91-a594-289667b8e096)
5. Then next time when you launch roblox you will see this:
![изображение](https://github.com/pizzaboxer/bloxstrap/assets/64935439/7f95e85a-73b4-4634-8190-24756c786245)
Press "No" and then the game should start up without problem.

**Comment by pizzaboxer** [comment]
You realize you could've just configured this in the menu, right?

**Comment by RedyRT** [comment]
> You realize you could've just configured this in the menu, right?

yeah, but when i configured this in the menu app, its just seems not work for me, so uhh yeah kinda like that

**Comment by pizzaboxer** [comment]
> its just seems not work for me

What do you mean by that?

**Comment by RedyRT** [comment]
> > its just seems not work for me
> 
> What do you mean by that?

the Channel change mode thing, didnt finded it in bloxstrap menu i

**Comment by pizzaboxer** [comment]
What? It was right here.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/c0c3931d-3b98-4642-a07b-3fe683382a79)

**Comment by RedyRT** [comment]
so i just make a edit through config

**Comment by RedyRT** [comment]
guh missclick

**Comment by RedyRT** [comment]
> If you had 'Always prompt' selected, it would definitely show that prompt.

oh really, i see

**Comment by RedyRT** [comment]
but another thing, how can you make it selecting that prompt just automatic?

**Comment by RedyRT** [comment]
to not answering Yes or No, just use it as standart

**Comment by pizzaboxer** [comment]
There's an option that says 'Never change'.

**Comment by kunnon** [comment]
![tokotoko](https://github.com/pizzaboxer/bloxstrap/assets/50902138/1ecb8127-cd79-41b9-bd17-d1701c68cc1c)

**Comment by RedyRT** [comment]
hmm for the first time its actually didnt worked for me i remember, but when i switched to never change it started working, maybe bug or something lmao

**Comment by pizzaboxer** [comment]
Either way, besides telling people to manually edit their configs and potentially breaking them when the menu is right there, I definitely do not want to be encouraging the use of old versions that'll only temporarily work for like a few days.

**Comment by RedyRT** [comment]
> Either way, besides telling people to manually edit their configs and potentially breaking them when the menu is right there, I definitely do not want to be encouraging the use of old versions that'll only temporarily work for like a few days.

yeah but what can we do actually with this, roblox is just breaking themself because of anticheat

**Comment by RedyRT** [comment]
btw this config actually applies to this app, so its nothing can do bad or break something

**Comment by RedyRT** [comment]
alr i just will edit the topic then
