### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KRAB14I88** [pizzaboxer/bloxstrap#2370]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

problem during the game, roblox starts showing artifacts, in this case the problem was captured on video, this problem only appears in bloxstrap, there is no such thing in the microsoft/original version. technical information about my PC:
1. gparhics card: Intel(R) HD Graphics 520
2. processor: Intel(R) Core(TM) i5-6300U CPU @ 2.40 GHz

video link: https://imgur.com/a/pMmeWyd

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
