### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by d6scent** [pizzaboxer/bloxstrap#2372]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

ever since 2.7 launched, my games been tweaking hard

clip: https://streamable.com/8x5trc?src=player-page-share

**Comment by pizzaboxer** [comment]
Does it happen without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

If not, upload your configuration. https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by d6scent** [comment]
it happens with roblox aswell.

**Comment by pizzaboxer** [comment]
Not a Bloxstrap issue then.
