### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Zorouki566** [pizzaboxer/bloxstrap#2373]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240714T185512Z.log](https://github.com/user-attachments/files/16228506/Bloxstrap_20240714T185512Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
