### ISSUE TITLE
Not a bug, but it kinda is

### ISSUE THREAD

**Issue by salahbrhs** [pizzaboxer/bloxstrap#2374]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Hello Bloxstrap team.
Whenever i try to open bloxstrap (im on the newest version) it says roblox starting then it just closes
Ive rebooted my pc alot of times and reinstalled the appilcation multiple times and yet my lovely bloxstrap doesn't work
I hope you guys can help me

Love, salah

**Comment by pizzaboxer** [comment]
Read the Wiki first and confirm that you've done so, then I'll reopen your issue.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
