### ISSUE TITLE
[REQ] Does bloxstrap work with Roblox account manager or multiple game instances?

### ISSUE THREAD

**Issue by Cheoo21** [pizzaboxer/bloxstrap#2376]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would like to know if bloxstrap work with Roblox account manager or multiple game instances and how I could do it.

**Comment by BokBoy** [comment]
Multiple game instances was dropped for roblox account manager recently.

**Comment by pizzaboxer** [comment]
> I would like to know if bloxstrap work with Roblox account manager or multiple game instances and how I could do it.

Just use it normally.

**Comment by All0m** [comment]
When i use Roblox Account Manager, bloxstrap denys the two roblox instances for some reason and i cant find a solution to this problem. It works perfectly when i dont have bloxstrap installed, but i want to use fastflags.
