### ISSUE TITLE
[REQ] Make the UI Customizable

### ISSUE THREAD

**Issue by TimMarvelHero** [pizzaboxer/bloxstrap#2379]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I want to change my UI to the old one when I'm inside games, old menu with 3 lines, old chat icon, old leaderboard look. I hope there's a possibility for this to be added.

**Comment by pizzaboxer** [comment]
Not possible.
