### ISSUE TITLE
Failed to load library: SensApi.dll

### ISSUE THREAD

**Issue by pokl1** [pizzaboxer/bloxstrap#238]
I get this error until I change whatever channel I'm using to another, forcing ROBLOX to reinstall
This happens every time I logon or reboot my PC

![image](https://github.com/pizzaboxer/bloxstrap/assets/15714472/5a44d061-459e-4d57-a002-7e47026ffb22)
[Bloxstrap_20230512T203554Z.log](https://github.com/pizzaboxer/bloxstrap/files/11467564/Bloxstrap_20230512T203554Z.log)

The Mediafire link directs to a download for the tmp file that got created from the error, Github prevents me from uploading it here
https://www.mediafire.com/file/86f9wi1frgxk1s3/HYP378.tmp/file

**Comment by pizzaboxer** [comment]
That's a Roblox problem. Run `sfc /scannow` in the Command Prompt as an Administrator as you should be good.

**Comment by pokl1** [comment]
Running the command did not work.

I've reformatted my drive, it works without using Bloxstrap. As soon as I use Bloxstrap the error pops up again preventing me from running Roblox

This was not an issue in V2.2.0 while using the zwinplayer64 channel, and no I'm not using the zwinplayer64 channel as it's deprecated

**Comment by pokl1** [comment]
I might have found a solution, but I want to be sure. I'll post an update in a day

**Comment by pizzaboxer** [comment]
> it works without using Bloxstrap. As soon as I use Bloxstrap the error pops up again preventing me from running Roblox

Oh? Do you know what channel the stock bootstrapper is using? You can find it by launching Roblox with it and then looking at the latest Roblox log file in %localappdata%\Roblox\logs.

**Comment by pokl1** [comment]
Sorry for the late response, ISP has been out for a few days.

> > it works without using Bloxstrap. As soon as I use Bloxstrap the error pops up again preventing me from running Roblox
> 
> Oh? Do you know what channel the stock bootstrapper is using? You can find it by launching Roblox with it and then looking at the latest Roblox log file in %localappdata%\Roblox\logs.

All I get from there is "production"
I'll provide the log here

https://www.mediafire.com/file/hz5v30peei27cw6/

**Comment by grant** [comment]
Hi there,

Can you please not mention @grant. I am not part of this project.

Thank you,
Grant

**Comment by EasternBloxxer** [comment]
Lmfao

**Comment by pizzaboxer** [comment]
And you've tried changing the channel to ZSocialTeam with Bloxstrap?

**Comment by pokl1** [comment]
The issue persists, I just won't use Bloxstrap

**Comment by 3UR** [comment]
> Hi there,
> 
> Can you please not mention @grant. I am not part of this project.
> 
> Thank you, Grant

do the thug shaker

**Comment by tfilteredc** [comment]
> > Hi there,
> > Can you please not mention @ grant. I am not part of this project.
> > Thank you, Grant
> 
> the @ grant shaker

Github actually mentioned someone in a code example, i cant anymore lmao
