### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\hello\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by 7hbl** [pizzaboxer/bloxstrap#2380]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\hello\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by pizzaboxer** [comment]
Read the Wiki.
