### ISSUE TITLE
[BUG] Bloxstrap client not installing

### ISSUE THREAD

**Issue by fakehundreds** [pizzaboxer/bloxstrap#2382]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Hello, so im having a issue with my bloxstrap installing/running and its just not working at all  when i download and run the  the installer it just puts bloxstrap on my tray but it does not install it, and i have not been able to resolve this issue

**Comment by slurinn** [comment]
![image](https://github.com/user-attachments/assets/97f6393c-058c-4081-8f21-0f5d05ee6f22)
this is what happens after i run the launcher to install bloxstrap does nothing at all 
![image](https://github.com/user-attachments/assets/4f76c8a0-5bcc-44d8-81b0-d1e525ab668f)

**Comment by slurinn** [comment]
[Bloxstrap_20240715T205502Z.log](https://github.com/user-attachments/files/16240286/Bloxstrap_20240715T205502Z.log)
bloxstrap error log file

**Comment by pizzaboxer** [comment]
You need to reinstall the .NET Windows Desktop Runtime. Uninstall it first (find it in add/remove programs by searching for "Windows Desktop Runtime"), then reinstall it here: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true
