### ISSUE TITLE
All characters gray in-game?

### ISSUE THREAD

**Issue by xSoundGodx** [pizzaboxer/bloxstrap#2386]
Was looking through YT for flag editor to change fps, and the one I found/pasted in works but made all characters (except mine) in the game completely gray. Anyone know where I go to change that as the YTer I got it from didn't specify?

**Comment by BokBoy** [comment]
Bloxstrap has an inbuilt FPS unlocker with ability to attempt to set max fps. Use that instead of your flag.

**Comment by ShadowCodeX-debug** [comment]
Please send your Fast flags (`%localappdata%\Bloxstrap\Modifications\ClientSettings\` and send the file **_ClientAppSettings.json_**)

**Comment by pizzaboxer** [comment]
> and the one I found/pasted in works but made all characters (except mine) in the game completely gray

Delete all flags you've set in the flag editor **and do not touch it again**. You can easily set your FPS cap from inside the Roblox escape menu, or in the Bloxstrap Menu under Fast Flag presets.
