### ISSUE TITLE
freezing for a few seconds/permanent white screen (2.7.0) [BUG] 

### ISSUE THREAD

**Issue by shadoricals** [pizzaboxer/bloxstrap#2388]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Recently reset my pc and reinstalled bloxstrap but this time it seems to have issues. I've tried on the sole roblox boostrapper and it ran smoothly which i tried this for a few days before downloading bloxstrap again. I do not use disable desktop app or any custom fastflags/fps values. I only use show game activity, see server location, 4x anti analysing quality and lvl 3 texture quality. I use a high-end pc which has not had any issues with roblox + bloxstrap in the future until after this reset

During the time of my roblox freezing it uses 0% of my pcs GPU + CPU

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
