### ISSUE TITLE
Log file is being used by another process error.

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#239]
I don't know why this occur often, but i found a solution i just delete everything inside the logs & it good to go.
Mind if you fix this error? 
![log file](https://github.com/pizzaboxer/bloxstrap/assets/86916029/201c3e5d-d40b-44b8-9354-7d691886996d)
I know You added to delete old logs file in the new update, but this error still appers.

**Comment by pizzaboxer** [comment]
Duplicate of #212. If you find anything new, then please comment there.

**Comment by Boi2021Miceoos** [comment]
i have no coding experinece yeah
