### ISSUE TITLE
can't start after it opens

### ISSUE THREAD

**Issue by subnerf** [pizzaboxer/bloxstrap#2390]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot 2024-07-16 185146](https://github.com/user-attachments/assets/cc841e23-4db8-41a7-8644-883e066fcc1d)

**Comment by pizzaboxer** [comment]
Can you send the log file please?
