### ISSUE TITLE
[BUG] Bloxstrap will not open on a specific account 

### ISSUE THREAD

**Issue by tmdragon2** [pizzaboxer/bloxstrap#2391]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden). 
blox strap doesn't work on 1 specific account

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/latest
