### ISSUE TITLE
An exception occured while running Bloxstrap (Launching problem)

### ISSUE THREAD

**Issue by Sivillaqz** [pizzaboxer/bloxstrap#2392]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

[Bloxstrap_20240716T195314Z.log](https://github.com/user-attachments/files/16256081/Bloxstrap_20240716T195314Z.log)

**Comment by ratio6969** [comment]
same shit happening to me xd

**Comment by BokBoy** [comment]
"Update to the latest version: https://github.com/pizzaboxer/bloxstrap/releases/latest"
-> Pizzaboxer, many times before
