### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tibbuhh** [pizzaboxer/bloxstrap#2394]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Schermafbeelding 2024-07-16 230950](https://github.com/user-attachments/assets/d6413124-e049-4f82-9006-5364f1258899)

**Comment by BokBoy** [comment]
"Update to the latest version: https://github.com/pizzaboxer/bloxstrap/releases/latest"
-> Pizzaboxer, many times before
