### ISSUE TITLE
[BUG] Response 403

### ISSUE THREAD

**Issue by terabaapma** [pizzaboxer/bloxstrap#2395]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I load roblox and the reponse I get is: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by BokBoy** [comment]
"Update to the latest version: https://github.com/pizzaboxer/bloxstrap/releases/latest"
-> Pizzaboxer, many times before
