### ISSUE TITLE
Bug when clicking on a game or avatar

### ISSUE THREAD

**Issue by ErikaXGH** [pizzaboxer/bloxstrap#2397]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When clicking the game or the avatar section, I see this avatar background:
![Screenshot 2024-07-16 174659](https://github.com/user-attachments/assets/fdbd21d8-59a7-45a1-9ee5-e0011d1ac6f6) and it doesn't stop. please fix this.

**Comment by vexnzo** [comment]
yeah this is happening with me as well

**Comment by ErikaXGH** [comment]
i think you need to disable the old avatar background to work
