### ISSUE TITLE
Disappearing screen [BUG] 

### ISSUE THREAD

**Issue by fernandosandov** [pizzaboxer/bloxstrap#2400]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When i enter in the icons of the left and when i try to click on the game that i want to play it just disappears randomly, i dont know why this happens but can you guys developers fix this bug plz.
![Captura de pantalla 2024-07-16 174324](https://github.com/user-attachments/assets/d7164474-a4dc-4b30-8445-42b86d01dc59)

**Comment by 7-7what** [comment]
i have this problem too, they need to fix this, seriously though.

**Comment by Encythe** [comment]
It has to do with the **Mobile.rbxl** place file, go into your Bloxstrap Menu, then Mods, and disable Use old Avatar Editor Background [or whatever it is in v2.7.0]

Confirm that the %localappdata%\Bloxstrap\Modifications\ExtraContent\places\Mobile.rbxl is deleted before launching, also try forcefully re-installing Roblox through Behavior --> Force Roblox Reinstallation

**Comment by gayloo** [comment]
for now you can use [this fixed version](https://github.com/CfwSky/bloxstrap/blob/main/Bloxstrap/Resources/Mods/OldAvatarBackground.rbxl) as a band-aid fix ig

**Comment by Alejandrix2456github** [comment]
i have that issue same :(

**Comment by Alejandrix2456github** [comment]
you can fix disabling it or changing it

**Comment by pizzaboxer** [comment]
Should be resolved now
