### ISSUE TITLE
[QUESTION??] Is bloxstrap on the newest version of roblox currently..?

### ISSUE THREAD

**Issue by 7-7what** [pizzaboxer/bloxstrap#2401]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

just wondering

**Comment by Alejandrix2456github** [comment]
i think

**Comment by ShadowCodeX-debug** [comment]
Bloxstrap automatically updates Roblox when Roblox has a new update ready for release. So yes, Bloxstrap is running the newest version of Roblox.
