### ISSUE TITLE
[BUG] Roblox Client App UI hides by opening Avatar or a Game

### ISSUE THREAD

**Issue by Alejandrix2456github** [pizzaboxer/bloxstrap#2402]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Hi i have this problem specifically with the Client (i use bloxstrap)
The Bug or Problem is GUI on App UI hiding and avatar behind of the UI hiding  when choosing avatar or a game
heres a screenshot
![RobloxPlayerBeta_AljWe7lYI5](https://github.com/user-attachments/assets/14bffa73-c5a5-42c1-8a90-778c4520ebd4)
i tried using Ctrl + Shift + G but it was still hidden

**Comment by Alejandrix2456github** [comment]
fied

**Comment by Alejandrix2456github** [comment]
fixed*

**Comment by ErikaXGH** [comment]
how did you fix it

**Comment by foursplaysroblox** [comment]
I have this bug also

**Comment by micdunn023** [comment]
How did you fix it i'm also having this issue

**Comment by whorlxd123** [comment]
i fixed it and heres how: turn off the feature "Use old avatar editor background"

**Comment by micdunn023** [comment]
> i fixed it and heres how: turn off the feature "Use old avatar editor background"

Thank you so much

**Comment by micdunn023** [comment]
Thank you so much

**Comment by Alejandrix2456github** [comment]
you can also get the fixed version

**Comment by micdunn023** [comment]
Thats possible?

**Comment by pizzaboxer** [comment]
Should be resolved now, sorry about that
