### ISSUE TITLE
[BUG] Roblox not launching or can't play a game

### ISSUE THREAD

**Issue by micdunn023** [pizzaboxer/bloxstrap#2403]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Everytime I open or try to play a game on roblox it goes to the avatar decoration where you customize your avatar and I don't know what's going on with this issue.
My user is Crafty_MemeNade on roblox and the file video that I was going to send is too big
![Roblox 7_16_2024 10_04_47 PM](https://github.com/user-attachments/assets/eabcc5b9-f496-4b0e-beb3-21ed4ebe9575)

**Comment by micdunn023** [comment]
I don't know if i installed the new version of this

**Comment by ShadowCodeX-debug** [comment]
Disable Old Avatar Menu (I think) in the Mods tab of the Bloxstrap Menu.

**Comment by pizzaboxer** [comment]
Should be resolved now, sorry about that
