### ISSUE TITLE
[BUG] main page disappears on viewing a game page if custom avatar menu mods are enabled

### ISSUE THREAD

**Issue by tlsctf2** [pizzaboxer/bloxstrap#2404]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Trying to view a game's page if you have a custom avatar menu, either through the "Use old avatar editor background" toggle or a different mod, causes the menu to disappear and become unusable, forcing you to close the program entirely.
I've seen plenty of issues opened in the last few hours that bring up the dedicated setting, but I wanted to provide the extra information that it happens with other mods to that menu too.
Just turning off the setting seems to work for others, so I would bet it has to do with trying to load any modified content on that screen right now.
I admittedly don't remember exactly what mod I'm using for this right now, but I _think_ it was this one: https://gamebanana.com/mods/497425

**Comment by ShadowCodeX-debug** [comment]
Then get rid of it if it's giving you problems.

**Comment by pizzaboxer** [comment]
Should be resolved now, sorry about that
