### ISSUE TITLE
[BUG] Windows notification sound when Alt + Enter out of Fullscreen Exclusive mode

### ISSUE THREAD

**Issue by SkyLLerGithub** [pizzaboxer/bloxstrap#2405]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

OS: Windows 11

https://github.com/user-attachments/assets/df1e2b4b-9950-4bf0-9da5-05e3b6cfd069

I'm not sure if this happens in Windows 10 as I don't have any issue with FSE in Windows 10.
When I Alt + Enter to fullscreen the game it works as intended. However when I try to Alt + Enter out of the game Windows will make a notification noise. (As shown in the video, the blackscreen occurs for a few second because of the game switching and switching out of Fullscreen mode in OBS)
thanks.

**Comment by ShadowCodeX-debug** [comment]
I can't help right now but, you can probably figure out what sound it's making as it's definitely not an actual notification sound. Go to your Audio Settings (You can do this by going into Settings -> System -> Audio -> More Audio Options and going to I think system sounds (I don't remember) and playing each one until you find the one you're hearing.

**Comment by SkyLLerGithub** [comment]
> I can't help right now but, you can probably figure out what sound it's making as it's definitely not an actual notification sound. Go to your Audio Settings (You can do this by going into Settings -> System -> Audio -> More Audio Options and going to I think system sounds (I don't remember) and playing each one until you find the one you're hearing.

I do know it's not the notification sound but more like something disconnecting, will update the issue asap once i get onto my computer.

**Comment by SkyLLerGithub** [comment]
> I can't help right now but, you can probably figure out what sound it's making as it's definitely not an actual notification sound. Go to your Audio Settings (You can do this by going into Settings -> System -> Audio -> More Audio Options and going to I think system sounds (I don't remember) and playing each one until you find the one you're hearing.

So I've checked and multiple of them shares the same sound file, so I'm just gonna list them all here.
-Asterisk
-Default Beep
-Exclamation
-Low Battery Alarm
-System Notification

**Comment by pizzaboxer** [comment]
> However when I try to Alt + Enter out of the game Windows will make a notification noise.
