### ISSUE TITLE
[BUG] b

### ISSUE THREAD

**Issue by BoBa9823** [pizzaboxer/bloxstrap#2406]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240717T124154Z.log] (https://github.com/user-attachments/files/16265803/Bloxstrap_20240717T124154Z.log)

**Comment by ShadowCodeX-debug** [comment]
> - [x] My answer given in the checkbox above is a lie.

You will not be given any help, begone. (Also not enough clarification and your problem has not been properly stated.)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/latest
