### ISSUE TITLE
[BUG] keybset change

### ISSUE THREAD

**Issue by iBeatrixx** [pizzaboxer/bloxstrap#2407]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

normally my keyset's AZERTY, and when i downloaded blox strap it's become QWERTY and since i have an AZERTY keyboard i can't play on roblox.

**Comment by GoingCrazyDude** [comment]
you might be the only azerty keyboard user i have heard of in my entire life

**Comment by Storm-930** [comment]
i. what.

**Comment by pizzaboxer** [comment]
> normally my keyset's AZERTY, and when i downloaded blox strap it's become QWERTY and since i have an AZERTY keyboard i can't play on roblox.

How does it behave on the original launcher? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
