### ISSUE TITLE
when click on the avatar/discover/friends profile/own profile, roblox will be frozen

### ISSUE THREAD

**Issue by d0vd** [pizzaboxer/bloxstrap#2408]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Uploading Screenshot 2024-07-17 205547.png…]()
it will freeze and u have to reopen bloxstrap and play

**Comment by d0vd** [comment]
nvm i found the issue, the old avatar editor will be freezing roblox so u got off it by going to the mods and off it

**Comment by ShadowCodeX-debug** [comment]
> - [x] My answer given in the checkbox above is a lie.
Its funny that people don't check what they are agreeing too; nobody reads anymore.

**Comment by pizzaboxer** [comment]
Problem should be resolved now
