### ISSUE TITLE
quality graphic [BUG] how to fix this pls

### ISSUE THREAD

**Issue by 1miy** [pizzaboxer/bloxstrap#2410]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

https://github.com/user-attachments/assets/5a9b34c6-f815-4bdb-bf09-9c78388fba7d

**Comment by ShadowCodeX-debug** [comment]
Kinda seems like you need a new graphics card, ngl.

**Comment by 1miy** [comment]
> Kinda seems like you need a new graphics card, ngl.

**Comment by ShadowCodeX-debug** [comment]
I didn't even see the lag; I was mainly focued on the background popping in and out.

**Comment by 1miy** [comment]
> I didn't even see the lag; I was mainly focused on the background popping in and out.

its because the bug

**Comment by nexpid** [comment]
> - [x] My answer given in the checkbox above is a lie.

we don't provide support for liars sorry..

**Comment by fantalhaydos** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  My answer given in the checkbox above is a lie.
> 
> ### What problem did you encounter?
>  robloxapp-20240717-2128302.mp4

WE HAVE A SAME PROBLEM

**Comment by 1miy** [comment]
> > * [x]  My answer given in the checkbox above is a lie.
> 
> we don't provide support for liars sorry..

wym

**Comment by Macredyps** [comment]
This is also happening to me! My graphics quality slider simply isn't doing anything!

**Comment by ShadowCodeX-debug** [comment]
@1miy you checked a box you shouldn't in your bug report.

**Comment by ShadowCodeX-debug** [comment]
@Macredyps you have 'DFIntDebugFRMQualityLevelOverride' in your FastFlags.

**Comment by Oyasumii14** [comment]
Whats your graphics card then?


You can check it via task manager (CTRL + SHIFT + ESC)

**Comment by TheFreshIce** [comment]
Yea, im having this same problem, I have no fastflags enabled and its bugged out very badly like his is

**Comment by Macredyps** [comment]
@Oyasumii14 I have a Nividia 1650 Geforce GTX, This problem has only just started happening around the time I posted my first reply, And this computer I've had this computer for a while so it can't be that.

**Comment by TheFreshIce** [comment]
@Macredyps It looks like there is no real fix for it right now, also it seems to be a roblox issue not a bloxstrap issue

**Comment by pizzaboxer** [comment]
@1miy Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
