### ISSUE TITLE
Bloxstrap Repository: Issue Templates changes

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#2412]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Make the templates add labels instead of having it add "[BUG]" or "[REQ]." Also since people **DO** have questions, make a new template for questions.

```diff
+ labels: "bug"
- title: "[BUG]"

+ labels: "enhancement"
- title: "[REQ]"
```

**Comment by pizzaboxer** [comment]
I only apply the bug label manually if it's valid, but I'll do it for suggestion requests.
