### ISSUE TITLE
[BUG] Can't open game pages, when clicking games (not play button) it gets rid of the UI and goes to or just shows the classic avatar area. (works for regular roblox)

### ISSUE THREAD

**Issue by Arodictus** [pizzaboxer/bloxstrap#2413]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image_2024-07-17_102156021](https://github.com/user-attachments/assets/9c61c48d-92ba-4c3e-8634-7589673963ee)

**Comment by Arodictus** [comment]
prob shouldve kept the title short

**Comment by BeansMP3** [comment]
this also happens to me too

**Comment by BeansMP3** [comment]
apparently someone got it fixed by disabling the old avatar editor background (it worked for me)
![image_2024-07-17_130109597](https://github.com/user-attachments/assets/6ef6c89c-0b63-49b3-8ed8-09b724db84d8)

**Comment by ShadowCodeX-debug** [comment]
Turn off "`Use old avatar editor background`."

**Comment by Arodictus** [comment]
nevermind they fixed it, but thanks for the suggestions
