### ISSUE TITLE
[REQ] If ever, add a mobile release

### ISSUE THREAD

**Issue by skibiditoilet255** [pizzaboxer/bloxstrap#2417]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

If you have enough time to do so, add a version for mobile players. It isn't really required, but you can if you want.

**Comment by ShadowCodeX-debug** [comment]
Wouldn't be possible and even if it is, pizzaboxer isn't going to do it.

**Comment by pizzaboxer** [comment]
Not (reasonably) possible
