### ISSUE TITLE
[BUG] Alt + enter just isnt working for me.

### ISSUE THREAD

**Issue by zaoic** [pizzaboxer/bloxstrap#2418]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Ive been using alt + enter for a while and today it just randomly stopped working any fixes? ive reinstalled roblox/bloxstrap and still doesnt work

**Comment by ShadowCodeX-debug** [comment]
Can you send the log file associated with that session and your Fast flags? (Windows Key + R: %localappdata%\Bloxstrap\Modifications\ClientSettings | Send the file named ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
> Ive been using alt + enter for a while and today it just randomly stopped working any fixes? ive reinstalled roblox/bloxstrap and still doesnt work

It just doesn't do anything when you press the key combo?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
