### ISSUE TITLE
Freezing Issue

### ISSUE THREAD

**Issue by CaughtU2** [pizzaboxer/bloxstrap#2419]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When I use the bloxstrap launcher only then my game will freeze I have uninstalled and reinstalled both roblox  and bloxstrap and no matter what I do it wont stop and no matter what game I play https://medal.tv/games/roblox/clips/ihyBTHumsZaJ5e2YS/d1337Rk5TiU8?invite=cr-MSxSbHQsMjUwMzk3NjMxLA

**Comment by ShadowCodeX-debug** [comment]
Can you send your Fast flags? (Windows Key + R: `%localappdata%\Bloxstrap\Modifications\ClientSettings` | Send the file named `ClientAppSettings.json`)

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen
