### ISSUE TITLE
add a language changing option [REQ] 

### ISSUE THREAD

**Issue by ImGreyCat** [pizzaboxer/bloxstrap#2420]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

so when 2.7.0 came out my language was changed to Russian and i'd really like to change it back to English, and some people may need that as well

**Comment by toofastforboo** [comment]
Appearance > Preferred Language > English

**Comment by ImGreyCat** [comment]
> Appearance > Preferred Language > English

oh my god im so blind sorry
