### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by Maxel431** [pizzaboxer/bloxstrap#2421]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
copy of the log file that was created

**Comment by toofastforboo** [comment]
update your bloxstrap to 2.7.0

**Comment by TNTUP** [comment]
I'm having the same issue and I am not updating to 2.7.0 due to the removal of multi-instancing :/

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/latest
