### ISSUE TITLE
InterpolationVisualizer Not Working

### ISSUE THREAD

**Issue by professionelstupid** [pizzaboxer/bloxstrap#2424]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

"DFFlagDebugEnableInterpolationVisualizer" Flag is not working anymore. Are they added a new keybind, or removed it?

**Comment by d44df016fe28bc8d5974** [comment]
it was patched
remove it

**Comment by professionelstupid** [comment]
> it was patched remove it

oh thanks
