### ISSUE TITLE
GUI Hiding 

### ISSUE THREAD

**Issue by DivineWz** [pizzaboxer/bloxstrap#2425]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I changed my cursor in the files and it seems to work, and with the help of the GUI hiding I can even turn off the in-game cursors like the gun cursor from Blox Fruits. But when I turn the GUI off for my cursor to also apply to guns, it turns my chat and leaderboard off. Could there be a way to turn off only cursors?

**Comment by pizzaboxer** [comment]
No
