### ISSUE TITLE
[BUG] cant download bloxstrap

### ISSUE THREAD

**Issue by sumobaby824** [pizzaboxer/bloxstrap#2426]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i litterily downloaded the latest version and it just says this.
![348436772-a025c565-912e-47fd-b0f5-2ef406a4c5b6](https://github.com/user-attachments/assets/d26cd2da-3345-4bca-ba21-ee4b8f380453)

**Comment by Kauan0090** [comment]
não consigo abaixar o blox trap no meu celular

**Comment by EasternBloxxer** [comment]
> não consigo abaixar o blox trap no meu celular

Bloxstrap only supports windows

Bloxstrap só suporta janelas

**Comment by pizzaboxer** [comment]
> i litterily downloaded the latest version

No you did not. https://github.com/pizzaboxer/bloxstrap/releases/latest
