### ISSUE TITLE
Z Fighting With The Air

### ISSUE THREAD

**Issue by FanOfWindowsCustomizationn** [pizzaboxer/bloxstrap#2427]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

This is happening pls help (might be a issue of the game if yes tell me
![image](https://github.com/user-attachments/assets/bbc283de-6021-407f-b161-31769cf9eeac)
)

**Comment by FanOfWindowsCustomizationn** [comment]
(Note:U can see the outline of the wall

**Comment by pizzaboxer** [comment]
> might be a issue of the game if yes tell me

Check for yourself. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
