### ISSUE TITLE
[BUG] Cannot unlock fps more than 240

### ISSUE THREAD

**Issue by iMusicDorian** [pizzaboxer/bloxstrap#2428]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I used it to unlock the fps in roblox for 360 fps, but the maximum fps is still 240.

**Comment by notorietyG** [comment]
alright this is not pizzaboxer but the fps limit depends on your display, if example you have 240 hz as your display your fps can only reach 240, reaching a higher amount than the limit can possibly destroy your monitor or have screen tears

**Comment by iMusicDorian** [comment]
> alright this is not pizzaboxer but the fps limit depends on your display, if example you have 240 hz as your display your fps can only reach 240, reaching a higher amount than the limit can possibly destroy your monitor or have screen tears

actually my monitor's refresh rate is 360 but the bloxstrap cannot change the refresh rate to 360 even I have set it already.

**Comment by pizzaboxer** [comment]
Do you need to go any higher than 240?

**Comment by iMusicDorian** [comment]
> Do you need to go any higher than 240?

Yes, as my monitor's highest refresh rate is 360.

**Comment by pizzaboxer** [comment]
The problem is that Roblox intentionally hard-caps the framerate at 240 for compatibiility reasons. There are workarounds that may remove it (such as setting both `FFlagTaskSchedulerLimitTargetFpsTo240` and `FFlagTaskSchedulerLimitTargetFpsTo2402` to `False` in the flag editor), but you may run into issues with games, and Roblox will likely remove the ability to configure those in the future.

**Comment by iMusicDorian** [comment]
> The problem is that Roblox intentionally hard-caps the framerate at 240 for compatibiility reasons. There are workarounds that may remove it (such as setting both `FFlagTaskSchedulerLimitTargetFpsTo240` and `FFlagTaskSchedulerLimitTargetFpsTo2402` to `False` in the flag editor), but you may run into issues with games, and Roblox will likely remove the ability to configure those in the future.

Thanks a lot, it works! I hope these flags will work for a long time as I play Arsenal in Roblox, an FPS game that needs a high refresh rate for a better experience.
