### ISSUE TITLE
IDK how to do it i tried using it but it didnt work

### ISSUE THREAD

**Issue by EisforEdude** [pizzaboxer/bloxstrap#2429]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when I did the tutorial i did everything correctly but it didn't work for some reason.
![RobloxScreenShot20220807_155203125](https://github.com/user-attachments/assets/c9017d86-03f2-46a7-ab6d-38a49db8a839)

**Comment by EisforEdude** [comment]
btw i just used a random pic that was the same as my problem

**Comment by pizzaboxer** [comment]
Can you explain the issue please?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
