### ISSUE TITLE
[BUG]  Bloxstrap Wont open

### ISSUE THREAD

**Issue by ayoGrox** [pizzaboxer/bloxstrap#2431]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I have reinstalled bloxstrap because some of its settings broke, After the reinstallation It wont open

https://github.com/user-attachments/assets/8e964623-50e6-4a41-9d72-5db48634074e

After Opening it as admin. This shi wont open. It says Launching Roblox but then nothing like its ignoring to open the RobloxPlayerBeta.exe

**Comment by pizzaboxer** [comment]
>     * [x]  My answer given in the checkbox above is a lie.

Thanks for that. Anyway, if you will: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
