### ISSUE TITLE
[BUG]  My fast flags are not working

### ISSUE THREAD

**Issue by Luthier2** [pizzaboxer/bloxstrap#2434]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I reinstalled bloxstrap to use a fastflag to make the reticle appear on roblox so I can aim but no matter what I do the flag just refuses to work

**Comment by nexpid** [comment]
send your fflags here

**Comment by Luthier2** [comment]
FFlagGamepadCursorDotDisappearsCorrectly2

**Comment by ShadowCodeX-debug** [comment]
There's another one `FFlagGamepadCursorDotDisappearsCorrectly`.
