### ISSUE TITLE
[BUG] when i tried to download bloxstrap, it keep saying This site can't be reached. I already tried on the official website. It still doesn't work. My wifi is completely fine. And I already checked the wiki.

### ISSUE THREAD

**Issue by XxitzmehAaronxX** [pizzaboxer/bloxstrap#2436]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot 2024-07-20 160526](https://github.com/user-attachments/assets/dbafde0b-188c-4361-9336-d534d403ab2d)

**Comment by BooleanInteger** [comment]
Try opening up CMD (assuming you use windows) and type the following commands;

ipconfig /release
ipconfig /renew
ipconfig /release

Your router will give your computer a new IP and flush the DNS cache. This may resolve your issue.

**Comment by ShadowCodeX-debug** [comment]
Also, not a Bloxstrap problem.

**Comment by pizzaboxer** [comment]
Open a Command Prompt window and run this command:

`ping objects.githubusercontent.com`

What does it show?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
