### ISSUE TITLE
[BUG] Bloxstrap Exception

### ISSUE THREAD

**Issue by MuhammedWasNotHere** [pizzaboxer/bloxstrap#2437]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i was opening BloxsTrap to Play roblox but its not coming and here is the log FLIE
[BullseyeCoverageError.txt](https://github.com/user-attachments/files/16319697/BullseyeCoverageError.txt)

**Comment by nakoyasha** [comment]
You've sent a log file from a completely unrelated app - Bloxstrap's logs should be in `%localappdata%/Bloxstrap/Logs`.

**Comment by ShadowCodeX-debug** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
> * [x]  My answer given in the checkbox above is a lie.

Thanks for that. I'll reopen this once you've confirmed that you've read this: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
