### ISSUE TITLE
[BUG] Avatar/Profile Bug

### ISSUE THREAD

**Issue by Drenchhh** [pizzaboxer/bloxstrap#2438]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Lags when I try to edit my avatar or view profiles. (only happens when on the website not through bloxstrap)

**Comment by ShadowCodeX-debug** [comment]
Then that's a "_you problems_."
