### ISSUE TITLE
[BUG] Can't exit in fullscreen mode

### ISSUE THREAD

**Issue by Oyasumii14** [pizzaboxer/bloxstrap#2439]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Im running on latest bloxstrap version and one time i tried going in fullscreen mode but after that i can't exit anymore

I tried pressing F11/ Turning fullscreen off via settings/ pressing alt + enter/ reinstalling bloxstrap

I don't like using fullscreen because it gives me tearing and im not used to t, please fix it

**Comment by ShadowCodeX-debug** [comment]
Check if you have any FastFlags involving Vulkan.

**Comment by Oyasumii14** [comment]
Thank you it works but i already did this few days ago after posting this
