### ISSUE TITLE
Failed to load library: SendApi.dll

### ISSUE THREAD

**Issue by voxj** [pizzaboxer/bloxstrap#244]
I had that error since the release of the anticheat.
![image](https://github.com/pizzaboxer/bloxstrap/assets/129677054/5cdcf83e-2f0d-4a56-8a54-81641eed1085)
![image](https://github.com/pizzaboxer/bloxstrap/assets/129677054/22934572-05ca-46bf-8536-97281947d503)

**Comment by pizzaboxer** [comment]
Duplicate of #238. Try out what I said over there.

**Comment by voxj** [comment]
Программа защиты ресурсов Windows обнаружила поврежденные файлы, но не
может восстановить некоторые из них.
Подробные сведения см. в файле CBS.Log, который находится по следующему пути:
windir\Logs\CBS\CBS.log. Например, C:\Windows\Logs\CBS\CBS.log. Подробные сведения
включены в файл журнала, предоставляемый флагом /OFFLOGFILE.

**Comment by voxj** [comment]
I still have the exact same error.

**Comment by pizzaboxer** [comment]
Well, don't really know how else to help you. This is a Roblox problem, not a problem with Bloxstrap.

**Comment by voxj** [comment]
Roblox Support couldn't help me too.
