### ISSUE TITLE
[BUG] HIGH MS (checked)

### ISSUE THREAD

**Issue by fvrydd** [pizzaboxer/bloxstrap#2440]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever bloxstrap is updated I have high ping problems, I checked by uninstalling bloxtrap and using roblox only and the problem disappears, any solution?

**Comment by ShadowCodeX-debug** [comment]
Please don't tell me you're using flags that "improve" ping... you're an idiot if you are.

**Comment by pizzaboxer** [comment]
Does it still happen if you reinstall?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
