### ISSUE TITLE
[BUG]what happened to launching multiple roblox accounts 

### ISSUE THREAD

**Issue by mr-redd403** [pizzaboxer/bloxstrap#2441]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

why did the multilaunching roblox account get removed?

**Comment by Gitarobo** [comment]
Yeah I also have this issue

**Comment by BooleanInteger** [comment]
Same issue here, developer adressed this at https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap

I'd really like to see it return the bloxstrap launcher, for me it was the main reason I used it to begin with.

**Comment by ShadowCodeX-debug** [comment]
It's gone, womp womp.
