### ISSUE TITLE
[BUG] Fast flags are crashing my game.

### ISSUE THREAD

**Issue by KingK318** [pizzaboxer/bloxstrap#2442]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So, I decided to turn on fast flags, but now for some reason, when I try to boot up the game it crashes. But when I turned off fast flags it now worked. I've had fast flags on before and it booted up completely normal. I'm not sure if my bloxstrap version is old or if it's my computer.

**Comment by toofastforboo** [comment]
- [x]  My answer given in the checkbox above is a lie.


fflags can become unstable or simply stop working and suddenly cause problems, it has been previously warned that the use of FFlags could cause something like it. Just go through your list little by little to see which one is causing the problem.

**Comment by yourecursed** [comment]
for me, removing the preset flag "FLogNetwork" worked

**Comment by ShadowCodeX-debug** [comment]
Provide your ClientAppSettings.json file (`%localappdata%\Bloxstrap\Modifications\ClientSettings`)

**Comment by pizzaboxer** [comment]
> * [x]  My answer given in the checkbox above is a lie.

Thanks for that. I'll reopen once you've confirmed that you've read these two pages:

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags
