### ISSUE TITLE
bloxstrap download error

### ISSUE THREAD

**Issue by kuro941** [pizzaboxer/bloxstrap#2443]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

as i download bloxstrap it says an exception occurred while running bloxstrap, i downloaded the .NET and etc. pretty sure i checked the wiki too. But I couldnt find anything to solve my issue. Maybe I didnt look clear enough but IDK how to fix this.

**Comment by ShadowCodeX-debug** [comment]
@pizzaboxer does Bloxstrap provide setup logs?

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
