### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RZS1223** [pizzaboxer/bloxstrap#2445]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: No such host is known. (clientsettings.roblox.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.

**Comment by pizzaboxer** [comment]
Internet connectivity issue.
