### ISSUE TITLE
[BUG] Bloxstrap FPS FFlag doesn't bypass Roblox's included unlocker

### ISSUE THREAD

**Issue by nighty524** [pizzaboxer/bloxstrap#2447]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I have Bloxstrap's FPS limit set to 600, yet in-game FPS is still hard-capped at 240 as per the escape menu's settings.

**Comment by ShadowCodeX-debug** [comment]
I'm not going to suggest FFlags that bypass the 240 hard limit, instead I'm going to give you a more easier way that doesn't involve FastFlags. Make sure your `DFIntTaskSchedulerTargetFps` is set to 0 (default). Go to `%localappdata%\Roblox` and open the file named 'GlobalBasicSettings_13.xml' and find the variable "FramerateCap." Changing this variable's value will change your in-game fps cap.

**Comment by pizzaboxer** [comment]
It's not supposed to go past 240.
