### ISSUE TITLE
[BUG] Playing games

### ISSUE THREAD

**Issue by Kaypleh** [pizzaboxer/bloxstrap#2448]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever i try to run roblox itll load then just close not giving a reason why.

**Comment by ShadowCodeX-debug** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
I'll reopen once you've confirmed you've read the above link.
