### ISSUE TITLE
I want to delay error 277

### ISSUE THREAD

**Issue by jo857294** [pizzaboxer/bloxstrap#2450]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

This isn't so much a _problem_ as it is a _request_. Disclaimer, I don't know how to well and truly use fastflags, but don't worry, I've mastered the fundamentals of coding and know whether I'm gonna brick something and how it's probably gonna brick something, and I'm 100% sure this won't brick anything, I just need the right syntax. I want to:

- change the amount of time it takes before my roblox client throws error 277 (the error message is "please check your internet connection and try again").

I want to change it to throw the error after 30 seconds of the server not responding, instead of the usual, what is it, 5? It's ~5. For context, I'm on vacation, and every ~60 seconds the internet stops working for ~10. All I really need is the fastflag that controls how long it takes before my client decides to throw error 277, if it exists. If it doesn't, I am ready to go to any lengths to delve into the files and change one number.

Please I straight up can't play roblox like this.

Edit: if you know a roblox fastflags expert and don't know the name of the fastflag (or know that there isn't one) I would appreciate being directed towards them.

**Comment by ShadowCodeX-debug** [comment]
This is a Roblox client issue. May I have to remind you, _**Bloxstrap cannot change or modify the Roblox client**_.

**Comment by ShadowCodeX-debug** [comment]
Also if you're trying to achieve this with FastFlags, don't bother; All the FastFlags that were previously thought to do this, didn't.

**Comment by pizzaboxer** [comment]
You can't "delay" it, no.
