### ISSUE TITLE
[BUG] The DFIntCSGLevelOfDetailSwitchingDistance value cannot be changed

### ISSUE THREAD

**Issue by RubenProSGR** [pizzaboxer/bloxstrap#2451]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When you are going to change the value of the DFIntCSGLevelOfDetailSwitchingDistance, be it L12, L23 or L34, it always returns to its original value, and you want to lower or raise it and it returns to the same value, even if only those fast flags are installed.

**Comment by TheHounouredOne** [comment]
just  server.script.service and make DFC true It worked for me

**Comment by RubenProSGR** [comment]
> just server.script.service and make DFC true It worked for me

How do i that brother?

**Comment by pizzaboxer** [comment]
Can you specifically state what value you're trying to set it to?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
