### ISSUE TITLE
Custom cursors

### ISSUE THREAD

**Issue by TacoWarLord** [pizzaboxer/bloxstrap#2452]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when I rename my specific custom cursors to ArrowCursor and ArrowFarCursor and launch the game, my custom cursors get reverted back to the default, the custom cursor never saves even when I delete and recreate the folder, are there any fixes?

**Comment by TacoWarLord** [comment]
Also, I never had an issue with this in the past and used custom cursors on older versions such as 2.6, but now, my custom cursors never work on any of the previous versions as well.

**Comment by ShadowCodeX-debug** [comment]
Please provide a log file.

**Comment by TacoWarLord** [comment]
![Screenshot_20230225_101637](https://github.com/user-attachments/assets/c31afc02-497e-4c63-a5c2-3aed87f2a92c)

**Comment by pizzaboxer** [comment]
I thought these would give you a clue, no?

![image](https://github.com/user-attachments/assets/fe537304-b8a1-40df-93b4-f46a6956449b)

Disable the mouse cursor preset first. Set it to defaults.

**Comment by JbefTeam** [comment]
this doesnt work
