### ISSUE TITLE
Bad Recommandation 

### ISSUE THREAD

**Issue by Testing494** [pizzaboxer/bloxstrap#2454]
The recommended alternative for multiple instances mentioned within the ("Attempted to teleport to a restricted place" error when using multiple instances) wiki post released a new version roughly 3 days ago. This version seemingly contains a virus, specifically a Trojan, within it's exe, which allows it to add a foreign administrator account to a users PC, giving the user full access to the PC. This new administrator account then takes ownership of the files, making it impossible to delete Roblox Account Manager files without removing the user first.  In which it will then attack the Users PC using it's Trojan as well as download hidden files using the administrator account to further attack the PC.

Please remove this recommendation from Bloxstrap's Wiki so new users that trust Bloxstrap don't become under risk of possibly losing their data.

**Comment by pizzaboxer** [comment]
I forgot to delete that page when releasing v2.6.0. Thanks for reminding me.
