### ISSUE TITLE
Mouse cursor lags, stutters while moving camera

### ISSUE THREAD

**Issue by jopek092** [pizzaboxer/bloxstrap#2456]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

While moving my mouse it starts to stutter like my pc was lagging? ( it wasnt I had no issue's with moving and stuff ) this is NOT a pc or roblox issue as when I uninstall bloxstrap its all fine but when I install it again the issue comes back. I didint had this issue while using older versions of bloxstrap.

**Comment by ShadowCodeX-debug** [comment]
I think this is a OS problem, there's another guy on Microsoft support forums that is having this problem as well.
https://answers.microsoft.com/en-us/windows/forum/all/mouse-cursor-lagging/884fd4d8-31c8-4d35-b37e-acd342bdbd25

**Comment by pizzaboxer** [comment]
Just to be clear, you only get this issue when running Roblox with Bloxstrap?

**Comment by jopek092** [comment]
> Just to be clear, you only get this issue when running Roblox with Bloxstrap?
yes I'm now running clean roblox withouth bloxstrap because of this issue

**Comment by pizzaboxer** [comment]
What about if you try disabling all the integration options in the Bloxstrap Menu?

**Comment by jopek092** [comment]
turned off the integrations on discord and stuff and it fixed
