### ISSUE TITLE
add styles for the leaderboard

### ISSUE THREAD

**Issue by KOSHAK05** [pizzaboxer/bloxstrap#2458]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

the same you did for the mouse/ESC menu

**Comment by DionBlox1** [comment]
It's not possible, although you can use a mod to change icons.

**Comment by KOSHAK05** [comment]
> It's not possible, although you can use a mod to change the leaderboard icons.

Alright, thanks for telling
