### ISSUE TITLE
PLEASE BRING BACK MULTI INSTANCE

### ISSUE THREAD

**Issue by TheHounouredOne** [pizzaboxer/bloxstrap#2459]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Please Devs Scriptors Builders anyone in the staff team to bring back multi instance. I cant afk grind anymore. I cant even use roblox account manager cuz  my vv blocked it. Yall just completely killed your app

**Comment by pizzaboxer** [comment]
>  I cant afk grind anymore

lol
