### ISSUE TITLE
Switching renderer to vulkan makes the cursor invisible while in fullscreen

### ISSUE THREAD

**Issue by nodomw** [pizzaboxer/bloxstrap#246]
Title, I would love to use Vulkan for multiple reasons, such as its more modern and better performance guarantees on AMD/ATI GPUs.

On the first launch, the cursor shows up fine in fullscreen, but every single launch after that and the cursor in fullscreen is invisible for some odd reason I could not find a solution to.

I know this isn't directly related to Bloxstrap but rather Roblox's implementation of Vulkan. I would like to know if there are any possible Flags that can fix this or workarounds and for them to be implemented into Bloxstrap if possible.

**Comment by pizzaboxer** [comment]
Don't think I've ever encountered that problem before, and I typically use Vulkan whenever I can being that I use AMD. I can't really find any flags that reference a fix for something like this, the only ones I can find were ones like `FFlagDebugGraphicsVulkanEnableMSAAPVR`, `FFlagRenderEnableGlobalInstancingVulkan`, `FFlagRenderMTLoadShaderVulkan` and `FFlagUseConstantBufferViewsVulkan`. You can try them out, but I don't think they'll do anything.

It's been known that Vulkan on Desktop is kind of a mess right now, especially with that whole window minimize crash thing, so I'm hoping its something that Roblox picks up on soon and fixes it. If you're also able to replicate this problem in Studio, then it'd make for a good bug report on the Devforum.
