### ISSUE TITLE
2022 escape menu being able to bypass certain things

### ISSUE THREAD

**Issue by x4rkeon** [pizzaboxer/bloxstrap#2462]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when using the 2022 escape menu, when resetting in a game like er:lc, you just freeze and die, even bypassing times in certain games where you may not reset.

**Comment by pizzaboxer** [comment]
This is known, though there isn't anything that we can really do about this.
