### ISSUE TITLE
[BUG] The "DFIntDebugFRMQualityLevelOverride" fastflag barely works.

### ISSUE THREAD

**Issue by notorietyG** [pizzaboxer/bloxstrap#2463]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So in previous versions of bloxstrap, (2.61, 2.60, etc) the "DFIntDebugFRMQualityLevelOverride" fastflag is a fastflag usually used for having a max graphics bar and render distance but the overall graphics only stays at whichever graphics value you apply (for example: DFIntDebugFRMQualityLevelOverride "1") . My problem is that on this latest version (2.70), the fastflag does work, but the max render distance isn't applying anymore with the max graphics bar.

P.S.
pizzaboxer if u dont understand my problem i can summarize it to you better on the comments

**Comment by pizzaboxer** [comment]
Roblox probably did something. We don't touch that flag whatsoever.

**Comment by notorietyG** [comment]
> Roblox probably did something. We don't touch that flag whatsoever.

thanks, it works now

**Comment by Owenvader** [comment]
@pizzaboxer @burgerboxer you fixed his and my problem, basically just remove the DFInt part from the front and now that flag works again, it must have been a rename, I'm curious though, how did you check this burger?
