### ISSUE TITLE
[BUG] Custom Font doesn't apply back to Default after removed it from the Menu

### ISSUE THREAD

**Issue by ohdamisury** [pizzaboxer/bloxstrap#2464]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So today i tried some custom fonts and encountered that even after remove apply custom font it still appears to my game no matter what i did until i have to enabled **Force Roblox Installation**.

I've checked the "mods" folder and though it looks empty 2 me i think it didn't reverting it back to the roblox "content" folder that does the purpose of applying my modifications

Here's the footage that I've replicated again: https://streamable.com/xpkw3t

*dunno if those logs files r worth mentioning so imma just putting them here*
[Bloxstrap_20240723T062303Z.log](https://github.com/user-attachments/files/16344707/Bloxstrap_20240723T062303Z.log)
[Bloxstrap_20240723T062508Z.log](https://github.com/user-attachments/files/16344708/Bloxstrap_20240723T062508Z.log)

**Comment by bluuboi123** [comment]
This also happened to me, hopefully it gets fixed soon...

**Comment by pizzaboxer** [comment]
One-off issue caused by the mod manifest not updating properly. It's expected that happens sometimes though rarely, and yeah, the "Force Roblox Reinstallation" option is there to help with solving that issue.
