### ISSUE TITLE
[BUG} "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)."

### ISSUE THREAD

**Issue by shxdxe** [pizzaboxer/bloxstrap#2466]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot 2024-07-23 082721](https://github.com/user-attachments/assets/fe61f67c-ae04-47ea-9759-e73a97a2bc61)
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)
other server is refusing to fullfill my request i.e roblox

**Comment by Mon4ik** [comment]
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x] **My answer given in the checkbox above is a lie.**

cmon

**Comment by Mon4ik** [comment]
[check wiki](https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/latest
