### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by shxdxe** [pizzaboxer/bloxstrap#2467]
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
![Screenshot 2024-07-23 082721](https://github.com/user-attachments/assets/d301f643-b7e8-4e35-b819-c124d7ac6ae2)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/latest
