### ISSUE TITLE
Roblox uses default launcher when I launch a game on the website

### ISSUE THREAD

**Issue by godlysaint** [pizzaboxer/bloxstrap#247]
Any fix besides opening the roblox app using bloxstrap and joining a game through there?

**Comment by pizzaboxer** [comment]
If you launch the Roblox app directly through the "Play Roblox" shortcut on the desktop or the start menu, it should reregister itself as the launcher for Roblox. Does launching through the website after launching the shortcut work?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month. Closed for inactivity.
