### ISSUE TITLE
Add the ability to add custom FPS integers

### ISSUE THREAD

**Issue by mathiameatie** [pizzaboxer/bloxstrap#2471]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Make it so we can set custom FPS presets, or change the existing ones
![image_2024-07-24_122235084](https://github.com/user-attachments/assets/64dba2f9-6357-4c93-a418-32c95562fa83)

**Comment by KabosuDoge** [comment]
If needed you can just set a custom one in the bloxstrap menu.

**Comment by mathiameatie** [comment]
> If needed you can just set a custom one in the bloxstrap menu.

You can't change the FPS in game

**Comment by pizzaboxer** [comment]
> Make it so we can set custom FPS presets, or change the existing ones

Not possible
