### ISSUE TITLE
Override resolution for custom settings?[REQ] 

### ISSUE THREAD

**Issue by KabosuDoge** [pizzaboxer/bloxstrap#2473]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add a function in Bloxstrap to add a custom resolution. This would be good for:

- Better Performance
- Using Magpie to increase FPS

**Comment by pizzaboxer** [comment]
Just resize the window to the size you want. Roblox will remember the size you last closed it with..

**Comment by hoovi1234** [comment]
if i shrink the window then the GUI gets scaled with it
