### ISSUE TITLE
[BUG] Roblox Map glitching

### ISSUE THREAD

**Issue by Jzxs0** [pizzaboxer/bloxstrap#2475]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When loading into a game the map around me will be flashing (showing and dissapearing) quickly and when uninstall bloxstrap and reinstall roblox it seems to be fixed but when reinstalling bloxstrap and using it, it starts to happen again

https://github.com/user-attachments/assets/e40ea7f4-895c-42d7-bc00-4f288a798918

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Jzxs0** [comment]
@pizzaboxer 
[ClientAppSettings.json](https://github.com/user-attachments/files/16405041/ClientAppSettings.json)
[Settings.json](https://github.com/user-attachments/files/16405042/Settings.json)
[State.json](https://github.com/user-attachments/files/16405043/State.json)

**Comment by pizzaboxer** [comment]
You failed to mention that you had added flags of your own to the flag editor. Can you remove them and see if the issue goes away?

**Comment by Jzxs0** [comment]
I've tried removing the fflags from the editor, reinstalling bloxstrap and roblox and the problem still occours without any modifications and it still occours

**Comment by pizzaboxer** [comment]
> I've tried removing the fflags from the editor,

Upload ClientAppSettings.json again just so I can see the current state of it

**Comment by Jzxs0** [comment]
[ClientAppSettings.json](https://github.com/user-attachments/files/16412879/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
You didn't remove anything, they're all still there.

**Comment by Jzxs0** [comment]
mb i sent the same one
[ClientAppSettings.json](https://github.com/user-attachments/files/16416459/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
If you switch to the original Roblox launcher, does it continue to happen? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Not a problem with Bloxstrap then
