### ISSUE TITLE
[BUG] game lags very hard before joining 

### ISSUE THREAD

**Issue by creationtesting** [pizzaboxer/bloxstrap#2476]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

blox strap lags my game for no reason its delayed by alot

**Comment by creationtesting** [comment]
it doesnt lag but it just takes a very long time to load into game 1-2 minutes i can join any pvp game cause ill already be dead

**Comment by pizzaboxer** [comment]
Does this happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by creationtesting** [comment]
with and without

**Comment by pizzaboxer** [comment]
Not a Bloxstrap issue then.
