### ISSUE TITLE
[REQ] Include a list of FFlags being used (if not default) with a one-way Bloxstrap API similar to RPC

### ISSUE THREAD

**Issue by imide** [pizzaboxer/bloxstrap#2477]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

(i do not work with roblox, but i am a dev. sorry if any info i've assumed is wrong!)

Due to the misuse of FFlags within the community (especially in comp. sports games), it would be helpful if Bloxstrap would report back the list of FFlags being used by each player using Bloxstrap. As FFlags (to my understanding) do not contain any personal/identifying information, I do not see a privacy concern here other than people leaking the fact you're using Bloxstrap which I guess is fingerprinting?
Each document should be stored within the ReplicatedStorage with the primary ID being the Roblox user ID. 
This can be used as an anticheat for many games affected by FFlag abuse (notably Football Fusion 2, where most leagues are outright banning the use of Bloxstrap and others while the game devs accidentaly banned every player to avoid fflags??)

**Comment by imide** [comment]
> hell nah we all disagree on this 👎

dude who tf are you
you aint a contributor lol

**Comment by CfwSky** [comment]
> hell nah we all disagree on this 👎

erm this is peak and funny actually

**Comment by axellse** [comment]
First of all, in my opinion this is a terrible idea. Second of all, Bloxstrap activity tracking is one way. The client or the game that your playing can send data to Bloxstrap, but not vice versa.

**Comment by bluepilledgreat** [comment]
Impossible
