### ISSUE TITLE
[BUG] The graphics quality slider bar moves but the graphic doesn't

### ISSUE THREAD

**Issue by Howplayz** [pizzaboxer/bloxstrap#2479]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

https://github.com/user-attachments/assets/a40aaf23-f75c-4264-8d94-5083935a9ea8

The graphics quality slider seems to be working but none of the graphics actually change

**Comment by Meowfoe** [comment]
> You might be using `DFIntDebugFRMQualityLevelOverride`
> 
> Do not import random flag lists that promise you for more **FPS**

this is happening to me as well, and i do not have any fast flags like that enabled

**Comment by FL1IP** [comment]
same thing even after reinstalling

**Comment by Howplayz** [comment]
I'll just have normal roblox ig bc bloxstrap keeps giving me problems for now

**Comment by Howplayz** [comment]
nvm it still doesnt work
maybe ill update my gpu's driver and check nvidia graphic thingy if it helps.

**Comment by SIIXz** [comment]
> same thing even after reinstalling UPDATE: Removing the Roblox folder from appdata/local helped.

u guy help me alot thx.

**Comment by haxrule** [comment]
same thing happened to me, but the quality shifts from time to time, as if its forcing auto graphics?

**Comment by haxrule** [comment]
same happened to me

**Comment by pizzaboxer** [comment]
> nvm it still doesnt work

Thanks for confirming
