### ISSUE TITLE
I got a issue

### ISSUE THREAD

**Issue by Ridunmo** [pizzaboxer/bloxstrap#2482]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240726T010026Z.log](https://github.com/user-attachments/files/16377488/Bloxstrap_20240726T010026Z.log)

**Comment by Ridunmo** [comment]
i forgot to mention that i got this problem while upgrading my bloxtrap

**Comment by pizzaboxer** [comment]
Does this happen every time? If not, it's a one-off internet connection issue.

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
