### ISSUE TITLE
[BUG] When i click install, nothing happens

### ISSUE THREAD

**Issue by reginliefx** [pizzaboxer/bloxstrap#2484]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When i click install on bloxstrap, nothing happen. i try to locate where bloxstrap will be install and theres nothing.

**Comment by reginliefx** [comment]
oh yeah and i find one folder that said "AppCrash_bloxstrap".

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
