### ISSUE TITLE
classic loading screen

### ISSUE THREAD

**Issue by s90630** [pizzaboxer/bloxstrap#2485]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

it would be nice if you could bring back the classic loading screen and if we could customize.
![Roblox classic loading](https://github.com/user-attachments/assets/4e8ee06a-3d81-4c47-be15-8db505124995)

**Comment by WertyTT4** [comment]
loading screen is hard coding so it aint possible

**Comment by pizzaboxer** [comment]
Not possible

**Comment by BrendanMakes** [comment]
Matthew 19:26
