### ISSUE TITLE
[REQ] ADD BACK MULTI INSTANCE FOR VERIFYING.

### ISSUE THREAD

**Issue by KurtCobainsDad** [pizzaboxer/bloxstrap#2486]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Yeah, i know that pizzaboxer removed multi instance launching. But i have a idea to bring back multiple instances for people. But you need to verify, then you will get multiple instances. 
If this get blocked, im not shocked then. 
So please, add back multiple instances launching by verifying.

**Comment by ShadowCodeX-debug** [comment]
Or here's an idea, lets not get pizzaboxer more angry than he already is with all these issue posts.

**Comment by BooleanInteger** [comment]
This could still be "abused" as the developer adressed earlier. I think a better integration would be to allow multi-instance launching ONLY WITH verified accounts. And maybe (if you want to be super-safe) only allow ROBLOX accounts to launch multi-instance when they have MFA enabled.

Unfortunately I don't think (even though clearly there is high demand) we are going to see the feature return, only time will tell.

**Comment by KurtCobainsDad** [comment]
Ok guys, i found out that WRD that was popular for making NOPDE Engine, it has a multi experience tool. So this is closed rn. Be a good boy and dont abuse it.
