### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Joelime21** [pizzaboxer/bloxstrap#2487]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Starting ROBLOX on acer nitro laptop and all i see is def ROBLOX i turned tracking and every thing on and still def i clicked force reinstall same issue still.

**Comment by Joelime21** [comment]
Also preview wont work it just loads endlessly

**Comment by pizzaboxer** [comment]
I don't understand, can you better explain please?

**Comment by Joelime21** [comment]
Nvm PC broke lol
