### ISSUE TITLE
Access to the path

### ISSUE THREAD

**Issue by sussybako** [pizzaboxer/bloxstrap#2488]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\secur\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied. how i can fix that?

**Comment by Mon4ik** [comment]
> * [x]  My answer given in the checkbox above is a lie.

😐
