### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path

### ISSUE THREAD

**Issue by Kaneshiro-Leywin** [pizzaboxer/bloxstrap#2489]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I simply can't install bloxtrap, it says it doesn't have permission or access to check or install itself in a folder on my PC, basically this error makes it impossible for me to install Roblox in the bloxtrap version
![imagem_2024-07-26_194631941](https://github.com/user-attachments/assets/802af710-0c02-44c0-8dcb-3af20dbd2980)

**Comment by Roblox-Thot** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
