### ISSUE TITLE
Why is it not opening? I tried 10 times...

### ISSUE THREAD

**Issue by idea-giver** [pizzaboxer/bloxstrap#249]
please RoShade... I want to open RTX in roblox.......

**Comment by pizzaboxer** [comment]
Is Roblox not launching?

**Comment by Boi2021Miceoos** [comment]
Roshade has Not been **Whitelisted** By Roblox, So Roshade Will not Work.
Altho the Reshade Injector loads in with the x64 version of Roblox and its new anti-cheat
Roblox blocks the overlay and graphics that ReShade provides. This means that you can load ReShade on Roblox, but you cannot see or use its effects and settings.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month. Closed for inactivity.
