### ISSUE TITLE
[BUG] My Bloxstrap Fast-flags stopped boosting my fps

### ISSUE THREAD

**Issue by klaireklaireklaire922** [pizzaboxer/bloxstrap#2491]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

2 days ago my fps was really high but i kept changing the fastflags looking for the best one that can boost my fps alot after awhile of deleting and changing my fastflags for my fps i opened roblox and got on a game i normally play it wont boost my fps anymore and ive been struggling with fps 50-60 and i havent gotten used to my fps cause i used to main 80 and higher. How can i fix this i have been reinstalling bloxstrap and tried to research about this but there nothing about this bug/issue.

**Comment by imide** [comment]
is your fps uncapped?
also dont fuck with the fflags, they are powerful and shouldnt be messed with for FPS... unless your on a 2013 chromebnook

**Comment by klaireklaireklaire922** [comment]
> is your fps uncapped? also dont fuck with the fflags, they are powerful and shouldnt be messed with for FPS... unless your on a 2013 chromebnook

yeah my fps is uncapped i use the fastflags for a fps boost cause my pc is really trash but idk why my fps wont go up anymore for some reason unlike 2 days ago

**Comment by pizzaboxer** [comment]
Configuring flags to give you an FPS boost are not guaranteed to keep giving you that same boost over time as updates happen and things change.
