### ISSUE TITLE
Bloxstrap is unable to connect to roblox

### ISSUE THREAD

**Issue by personthatislosingsanity** [pizzaboxer/bloxstrap#2492]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/63063188-e987-4638-ab93-6466a9cd1f27)
please help i've tried everything to fix, nothing works.

**Comment by pizzaboxer** [comment]
You were using Fiddler and didn't close it properly before you shut down your computer. https://www.linkedin.com/pulse/how-disable-proxy-step-by-step-guide-digital-guardian-innovations-cextf
