### ISSUE TITLE
Game freezes for a few seconds when clicking escape key

### ISSUE THREAD

**Issue by Zleezi** [pizzaboxer/bloxstrap#2493]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever i click the escape key in any roblox game my game freezes for a few seconds 

https://github.com/user-attachments/assets/b7382b9c-cbca-4944-8acf-94af4a81c2a6

**Comment by pizzaboxer** [comment]
Does this happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
If not, upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
