### ISSUE TITLE
[BUG] i cant find the bloxstrap menu

### ISSUE THREAD

**Issue by colaiiii-L** [pizzaboxer/bloxstrap#2495]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

ive had the version 2.5.4 and the most recent versions, and everytime i search the bloxstrap menu on my pc it doesnt show up
pls help

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu?
