### ISSUE TITLE
[BUG] Discord RPC not working

### ISSUE THREAD

**Issue by LabRatMime** [pizzaboxer/bloxstrap#2499]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I'm trying to use the Discord RPC but nothing seems to be working, I looked through a few old issues and every solution and whatnot doesn't seem to be working 4 me. I use better discord and not vencord and I don't have any plugins that block rpc anyways so I'm not sure why this wouldn't be working.
![img-2024-07-27-08-35-38](https://github.com/user-attachments/assets/64833008-4e8e-44dc-ab10-971db3fd468d)
![img-2024-07-27-08-35-24](https://github.com/user-attachments/assets/1921e3c2-2c88-4d25-bfef-0637546c5fd7)
![img-2024-07-27-08-32-27](https://github.com/user-attachments/assets/f6047f46-7631-4cf3-bb55-a899ad1dafe6)
![img-2024-07-27-08-34-43](https://github.com/user-attachments/assets/d73bfce8-6527-460a-963c-11a1769113fb)

**Comment by pizzaboxer** [comment]
Launch into a game, then send Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` here

**Comment by LabRatMime** [comment]
[Bloxstrap_20240728T200123Z.log](https://github.com/user-attachments/files/16405061/Bloxstrap_20240728T200123Z.log)

**Comment by pizzaboxer** [comment]
Okay, for once I actually can't tell why it isn't working.

http://files.pizzaboxer.xyz/DiscordRPCTest2.exe

Download and run this, and check to see if you have a test rich presence being applied. If not, copy and paste the whole command prompt output here.

When you close it, you may need to restart Discord to get rid of the rich presence.

**Comment by LabRatMime** [comment]
I received no rich presence 

Initializing...
INFO: Attempting a new connection
Initialized
Setting presence...
INFO: RPC Connection Started
TRACE: ============================
TRACE: Enqueue Command: DiscordRPC.RPC.Commands.PresenceCommand
TRACE: Assembly:             DiscordRPC, Version=1.1.3.18, Culture=neutral, PublicKeyToken=null
TRACE: Pipe:                 DiscordRPC.IO.ManagedNamedPipeClient
Presence set
TRACE: Platform:             Microsoft Windows NT 10.0.19045.0
TRACE: applicationID:        1005469189907173486
TRACE: targetPipe:           -1
TRACE: POLL_RATE:            1000
TRACE: _maxRtQueueSize:      512
TRACE: _maxRxQueueSize:      0
TRACE: ============================
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(-1)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to 'discord-ipc-0'
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 1 ()
INFO: Attempting to connect to 'discord-ipc-1'
ERR : Failed connection to discord-ipc-1. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 2 ()
INFO: Attempting to connect to 'discord-ipc-2'
ERR : Failed connection to discord-ipc-2. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 3 ()
INFO: Attempting to connect to 'discord-ipc-3'
ERR : Failed connection to discord-ipc-3. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 4 ()
INFO: Attempting to connect to 'discord-ipc-4'
ERR : Failed connection to discord-ipc-4. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 5 ()
INFO: Attempting to connect to 'discord-ipc-5'
ERR : Failed connection to discord-ipc-5. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 6 ()
INFO: Attempting to connect to 'discord-ipc-6'
ERR : Failed connection to discord-ipc-6. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 7 ()
INFO: Attempting to connect to 'discord-ipc-7'
ERR : Failed connection to discord-ipc-7. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 8 ()
INFO: Attempting to connect to 'discord-ipc-8'
ERR : Failed connection to discord-ipc-8. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 9 ()
INFO: Attempting to connect to 'discord-ipc-9'
ERR : Failed connection to discord-ipc-9. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
Failed to establish connection with Discord RPC
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 1095ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(-1)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to 'discord-ipc-0'
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 1 ()
INFO: Attempting to connect to 'discord-ipc-1'
ERR : Failed connection to discord-ipc-1. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 2 ()
INFO: Attempting to connect to 'discord-ipc-2'
ERR : Failed connection to discord-ipc-2. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 3 ()
INFO: Attempting to connect to 'discord-ipc-3'
ERR : Failed connection to discord-ipc-3. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 4 ()
INFO: Attempting to connect to 'discord-ipc-4'
ERR : Failed connection to discord-ipc-4. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 5 ()
INFO: Attempting to connect to 'discord-ipc-5'
ERR : Failed connection to discord-ipc-5. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 6 ()
INFO: Attempting to connect to 'discord-ipc-6'
ERR : Failed connection to discord-ipc-6. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 7 ()
INFO: Attempting to connect to 'discord-ipc-7'
ERR : Failed connection to discord-ipc-7. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 8 ()
INFO: Attempting to connect to 'discord-ipc-8'
ERR : Failed connection to discord-ipc-8. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 9 ()
INFO: Attempting to connect to 'discord-ipc-9'
ERR : Failed connection to discord-ipc-9. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
Failed to establish connection with Discord RPC
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 2285ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(-1)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to 'discord-ipc-0'
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 1 ()
INFO: Attempting to connect to 'discord-ipc-1'
ERR : Failed connection to discord-ipc-1. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 2 ()
INFO: Attempting to connect to 'discord-ipc-2'

**Comment by pizzaboxer** [comment]
Can you run that Powershell command again please? According to this log, nothing should show up when you run that command.

**Comment by LabRatMime** [comment]
![img-2024-07-29-11-35-58](https://github.com/user-attachments/assets/bdf43d85-f84e-4b06-8808-85b3649e4780)

**Comment by pizzaboxer** [comment]
Does anything change if you run the RPC test as an Administrator?

**Comment by LabRatMime** [comment]
Still nothin
Initializing...
INFO: Attempting a new connection
Initialized
Setting presence...
INFO: RPC Connection Started
TRACE: ============================
TRACE: Assembly:             DiscordRPC, Version=1.1.3.18, Culture=neutral, PublicKeyToken=null
TRACE: Enqueue Command: DiscordRPC.RPC.Commands.PresenceCommand
TRACE: Pipe:                 DiscordRPC.IO.ManagedNamedPipeClient
Presence set
TRACE: Platform:             Microsoft Windows NT 10.0.19045.0
TRACE: applicationID:        1005469189907173486
TRACE: targetPipe:           -1
TRACE: POLL_RATE:            1000
TRACE: _maxRtQueueSize:      512
TRACE: _maxRxQueueSize:      0
TRACE: ============================
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(-1)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to 'discord-ipc-0'
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 1 ()
INFO: Attempting to connect to 'discord-ipc-1'
ERR : Failed connection to discord-ipc-1. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 2 ()
INFO: Attempting to connect to 'discord-ipc-2'
ERR : Failed connection to discord-ipc-2. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 3 ()
INFO: Attempting to connect to 'discord-ipc-3'
ERR : Failed connection to discord-ipc-3. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 4 ()
INFO: Attempting to connect to 'discord-ipc-4'
ERR : Failed connection to discord-ipc-4. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 5 ()
INFO: Attempting to connect to 'discord-ipc-5'
ERR : Failed connection to discord-ipc-5. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 6 ()
INFO: Attempting to connect to 'discord-ipc-6'
ERR : Failed connection to discord-ipc-6. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 7 ()
INFO: Attempting to connect to 'discord-ipc-7'
ERR : Failed connection to discord-ipc-7. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 8 ()
INFO: Attempting to connect to 'discord-ipc-8'
ERR : Failed connection to discord-ipc-8. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 9 ()
INFO: Attempting to connect to 'discord-ipc-9'
ERR : Failed connection to discord-ipc-9. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
Failed to establish connection with Discord RPC
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 1095ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(-1)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to 'discord-ipc-0'
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 1 ()
INFO: Attempting to connect to 'discord-ipc-1'
ERR : Failed connection to discord-ipc-1. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 2 ()
INFO: Attempting to connect to 'discord-ipc-2'
ERR : Failed connection to discord-ipc-2. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
TRACE: Connection Attempt 3 ()
INFO: Attempting to connect to 'discord-ipc-3'

**Comment by pizzaboxer** [comment]
What about if you reinstall Discord? Just try it without BetterDiscord for now, see if it changes anything.

**Comment by LabRatMime** [comment]
Reinstalled discord without BetterDiscord and everything seems to be working fine
![img-2024-07-30-10-25-39](https://github.com/user-attachments/assets/3ee413de-408a-4b59-a3c7-77b4bda94a85)
![img-2024-07-30-10-26-23](https://github.com/user-attachments/assets/606c0bf2-868f-483e-95ea-9dbf9b484b0c)
After reinstalling BetterDiscord it still works
![img-2024-07-30-10-27-43](https://github.com/user-attachments/assets/1ddf168b-952c-46b5-aee1-4bcea4bb1eef)
I guess reinstalling should've been the first thing I did. Thanks and sorry for the trouble!
