### ISSUE TITLE
Bloxstrap Not launching on the First time

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#250]
Other than the Log File is being Used by another Process, Sometimes Bloxstrap Will not load on the first time
I have to launch bloxstrap another time in order to play roblox.

**Comment by pizzaboxer** [comment]
Does this happen whenever the log file error shows?

**Comment by Boi2021Miceoos** [comment]
Nah, it didn't appeer a log file

**Comment by pizzaboxer** [comment]
The next time this happens, before launching Bloxstrap again, can you get the latest log file? You can find it by navigating to `%localappdata%\Bloxstrap\logs` in your file browser.

**Comment by Boi2021Miceoos** [comment]
Ok, i wil go to the logs file if that happens, this happens often for some reason

**Comment by Boi2021Miceoos** [comment]
Also yes, i have the latest version of the .NET 6 Desktop Runtime Installed.
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it

**Comment by pizzaboxer** [comment]
That's not talking about the problem you're having. That's talking about people who encounter Bloxstrap not launching at all no matter how many times they try.

**Comment by Boi2021Miceoos** [comment]
just encountered this issue again here the log 
[Bloxstrap_20230529T010610Z.log](https://github.com/pizzaboxer/bloxstrap/files/11587407/Bloxstrap_20230529T010610Z.log)

**Comment by pizzaboxer** [comment]
> just encountered this issue again here the log
> [Bloxstrap_20230529T010610Z.log](https://github.com/pizzaboxer/bloxstrap/files/11587407/Bloxstrap_20230529T010610Z.log)

This log indicates that Roblox is launching just fine, and it was taken 12 minutes before you made this reply.

**Comment by Boi2021Miceoos** [comment]
again encoutered the issue, but the logs files are not generated

**Comment by pizzaboxer** [comment]
Are you getting any Bloxstrap crash dumps made in `%localappdata%\CrashDumps`?

**Comment by Boi2021Miceoos** [comment]
i have alot of Crash Dumps files

**Comment by pizzaboxer** [comment]
None for Bloxstrap? Weird. I have no idea what would be causing this since it seems like it never even makes an attempt to start in the first place - there should at least be something if it did. What browser are you using? Do you have it so a browser prompt shows up before launching Roblox, kind of like this?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/6dc28ecb-4ba6-4c88-b284-6579868cb6da)

**Comment by Boi2021Miceoos** [comment]
> None for Bloxstrap? Weird. I have no idea what would be causing this since it seems like it never even makes an attempt to start in the first place - there should at least be something if it did. What browser are you using? Do you have it so a browser prompt shows up before launching Roblox, kind of like this?
> 
> ![image](https://user-images.githubusercontent.com/41478239/242847382-6dc28ecb-4ba6-4c88-b284-6579868cb6da.png)
Im using google chrome & no pop up like the screenshot you provided

**Comment by pizzaboxer** [comment]
I think the best bet would be to re-enable the popup just to verify that it actually is trying to launch Roblox. The only problem is that you allowed for Roblox to always launch it unprompted, which is fine, but I can't figure out how to re-enable it in Chrome....

**Comment by pizzaboxer** [comment]
I know it's been nearly two months, but does this still happen?

**Comment by Boi2021Miceoos** [comment]
nope problem solved somehow
