### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by thiegoskip10** [pizzaboxer/bloxstrap#2501]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.InvalidOperationException: Cannot start process because a file name has not been provided.

**Comment by pizzaboxer** [comment]
Can you send the log file please?

**Comment by pizzaboxer** [comment]
Duplicate of #2315
If you're trying to find out why Roblox isn't launching, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
