### ISSUE TITLE
My FPS is not unlocking even though i set it to a higher value than roblox has made[BUG?] 

### ISSUE THREAD

**Issue by JakubSteinz** [pizzaboxer/bloxstrap#2502]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So. I have tried finding answers to the given but they don't happen to fix. I have unlocked the FPS on bloxstrap but roblox maxes it out at 240 FPS. I have even checked Nvidia's Max framerate settings and it's off. Honestly i don't know if i am an idiot or not.
![Screenshot 2024-07-28 024029](https://github.com/user-attachments/assets/490d47a0-adef-407a-8b71-18b23ca73a8a)

![Screenshot 2024-07-28 021558](https://github.com/user-attachments/assets/9f93c39d-570b-433d-8dfd-d001072b7026)
![Screenshot 2024-07-28 021647](https://github.com/user-attachments/assets/ee15137c-5436-45d9-aa2a-07315c6ed58d)
![Screenshot 2024-07-28 022851](https://github.com/user-attachments/assets/844e4b8c-4736-459b-a0b8-9db6fbc0455c)

**Comment by pizzaboxer** [comment]
It's not supposed to go past 240. They cap it at that for reasons.
