### ISSUE TITLE
[REQ] MULTIPLE INSTANCE

### ISSUE THREAD

**Issue by 4m3er** [pizzaboxer/bloxstrap#2505]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

# There used to be multiple instance option?
## Why did it got removed??

**Comment by Tom28281** [comment]
owner doesnt like us multi boxing or something. womp womp dude, im gonna use roblox account manager instead. fuck the owner

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
