### ISSUE TITLE
[REQ] Can you make the old roblox ui app

### ISSUE THREAD

**Issue by MediaCanterinWindows11** [pizzaboxer/bloxstrap#2506]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i mean i 2022 roblox has removed the old roblox ui app and make this laggy ui app, can you make a mod or costumaztion to bring back to the old one 
![Uploading hhhhh.PNG…]()

**Comment by AMD-Edits** [comment]
icl i agree with this but the thing is that the old roblox used to be website based meanin there is no actual app launcher. you will normally load into your game from wbesite. but by all means i think they can make the app to its original state

**Comment by AMD-Edits** [comment]
![image](https://github.com/user-attachments/assets/4abd455c-bdab-4478-80a2-b054d81cb44b)
i think this is what it used to look like

**Comment by AMD-Edits** [comment]
can u also resend the image u sent? it not showing up correctly

**Comment by pizzaboxer** [comment]
Not possible
