### ISSUE TITLE
[BUG] Misc. Tab Not Showing

### ISSUE THREAD

**Issue by georgelel** [pizzaboxer/bloxstrap#2507]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

why is the miscellanous section in the mod tab not showing for me as well as the option to join from many accounts at once?
please help
![image](https://github.com/user-attachments/assets/74b8bcb6-7884-4642-8b80-1115587ca1cd)

**Comment by Roblox-Thot** [comment]
The option to run multiple instances was removed a few updates ago, you can read on why they decided to here:
https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap

**Comment by georgelel** [comment]
> The option to run multiple instances was removed a few updates ago, you can read on why they decided to here: https://github.com/pizzaboxer/bloxstrap/wiki/Plans-to-remove-multi%E2%80%90instance-launching-from-Bloxstrap
> 
> And I think the misc tab was removed but i'm not 100% on that.

thanks bro now I know why it wasn't showing.
