### ISSUE TITLE
[BUG] Pause menu themes not working.

### ISSUE THREAD

**Issue by DamianAcosta** [pizzaboxer/bloxstrap#2508]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When i open the pause menu with a theme, it shows the normal menu. It used to work. Mods using: [Roldblox 2016](https://gamebanana.com/mods/507696)

**Comment by pizzaboxer** [comment]
See sections 2 and 3 of https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter. Let me know if that doesn't help and I'll reopen.
