### ISSUE TITLE
cant change graphics

### ISSUE THREAD

**Issue by kaiimeows** [pizzaboxer/bloxstrap#2510]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

graphics wont change no matter what i do need help ( this is my presets and flags ) 
![image_2024-07-29_061854788](https://github.com/user-attachments/assets/b6020831-473a-4642-81d1-41508545f680)

**Comment by pizzaboxer** [comment]
The only thing you've changed here is your font size and framerate cap (which will cap at 240). What's wrong here, what were you expecting to apply that isn't?

**Comment by kaiimeows** [comment]
nono sorry mustve said it wrong in game i can not change my graphics to go up or down it just stays the same

**Comment by kaiimeows** [comment]
see it doesnt change the graphics at all

**Comment by pizzaboxer** [comment]
Does this happen only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by kaiimeows** [comment]
yea

**Comment by kaiimeows** [comment]
hey so uh sorru i lied it doesnt work on normal roblox either do u know any soulution to this

**Comment by pizzaboxer** [comment]
Can't help you with that, sorry.
