### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DCHACKV3** [pizzaboxer/bloxstrap#2511]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\haric\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by lukaseds** [comment]
i have the same issue

**Comment by pizzaboxer** [comment]
Read the Wiki.
