### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dubbuwtf** [pizzaboxer/bloxstrap#2512]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

how can i open more than one roblox instance and how do i change the colors of the texts in the menu?

**Comment by lukaseds** [comment]
https://wearedevs.net/dinfo/Multiple%20Games

**Comment by lukaseds** [comment]
i acutaly dont know any other programm and i use this alredy since years and works

**Comment by Dubbuwtf** [comment]
> https://wearedevs.net/dinfo/Multiple%20Games

does it get detected by byfron?

**Comment by lukaseds** [comment]
no

**Comment by Dubbuwtf** [comment]
how are you replying so fast 😭

**Comment by Dubbuwtf** [comment]
does it work if i use blox strap

**Comment by lukaseds** [comment]
yes

**Comment by pizzaboxer** [comment]
> how do i change the colors of the texts in the menu?

What do you mean by that?

**Comment by Dubbuwtf** [comment]
Like on the website the client text was diffrent

**Comment by pizzaboxer** [comment]
I still don't understand what you mean, can you explain?

**Comment by Dubbuwtf** [comment]
never mind. How do I get multiple Roblox instances? The multiple Roblox
thing dosent work

**Comment by Error-Cezar** [comment]
Not a bug, it got removed in the most recent version

**Comment by Error-Cezar** [comment]
> https://wearedevs.net/dinfo/Multiple%20Games

WeAreDevs is compromised avoid from using that site

**Comment by Dubbuwtf** [comment]
oh

**Comment by Dubbuwtf** [comment]
ok. There’s no other way for multiple Roblox’s?

**Comment by pizzaboxer** [comment]
If you don't want to use Roblox Account Manager (either a latest or past version) then no
