### ISSUE TITLE
[BUG] O BLOXTRAP NAO ESTAO CONSEGUE SE CONECTAR AO ROBLOX 

### ISSUE THREAD

**Issue by nicolasx7** [pizzaboxer/bloxstrap#2515]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

meu bloxtrap nao esta conseguindo se conectar ao roblox ja verifiquei minha conecçao e nao e minha conecçao

**Comment by pizzaboxer** [comment]
Check your antivirus. It may be preventing Bloxstrap from connecting to the internet. Add an exception for Bloxstrap if you can.

**Comment by nicolasx7** [comment]
nao resolveu meu problema

**Comment by pizzaboxer** [comment]
Something on your system is preventing Bloxstrap from connecting to the internet. It's an issue on your end, you'll have to find out what it is.
