### ISSUE TITLE
i cant fix System.InvalidOperationException: Cannot start process because a file name has not been provided. and dont know what to do

### ISSUE THREAD

**Issue by theuniversesingstome** [pizzaboxer/bloxstrap#2516]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when trying to open bloxstrap ive been getting this error code System.InvalidOperationException: Cannot start process because a file name has not been provided.**** and i dont know what to do.

**Comment by pizzaboxer** [comment]
Duplicate of #2315
