### ISSUE TITLE
[BUG] Opening roblox results in a crash

### ISSUE THREAD

**Issue by CrackLover69420** [pizzaboxer/bloxstrap#2517]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

This happens every time i launch roblox, i already re-installed Bloxstrap, i dont have any programms running other than roblox
![bloxstrap](https://github.com/user-attachments/assets/527248cb-6e26-4b35-837a-09d0bd641e2a)

**Comment by CrackLover69420** [comment]
This started like 10 minutes ago, before i just played BCWO and my Roblox crashed with this message.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by CrackLover69420** [comment]
Issue already fixed by myself.
