### ISSUE TITLE
[BUG] I literally cannot open bloxstrap (I can open roblox, just not bloxstrap itsself)

### ISSUE THREAD

**Issue by netizensss** [pizzaboxer/bloxstrap#2518]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I literally cannot open bloxstrap, when I click it, it says "starting roblox" but then just never starts it.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
