### ISSUE TITLE
403[BUG] 

### ISSUE THREAD

**Issue by sparklymarmot** [pizzaboxer/bloxstrap#2519]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by pizzaboxer** [comment]
Read the Wiki.
