### ISSUE TITLE
My bloxstrap cant launch beacause Memory dump

### ISSUE THREAD

**Issue by crimxion** [pizzaboxer/bloxstrap#252]

**Comment by crimxion** [comment]
someone help me with this

**Comment by pizzaboxer** [comment]
Can I see a screenshot of the error that shows?

**Comment by Boi2021Miceoos** [comment]
here the log file before he edited the comment:
[Bloxstrap_20230521T014040Z.log](https://github.com/pizzaboxer/bloxstrap/files/11554185/Bloxstrap_20230521T014040Z.log)

**Comment by pizzaboxer** [comment]
I can't do anything with this because I'm fairly sure this error is coming from Roblox and not Bloxstrap. I need him to confirm first though.

**Comment by Boi2021Miceoos** [comment]
i just encountered this error using bloxstrap today

**Comment by pizzaboxer** [comment]
I can't really tell what's going on if you don't show me what it looks like.

**Comment by NikoYTRBLX** [comment]
i think this is what you're looking for?
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/42c00551-8669-4524-aa6d-17dd139b2d0b)

**Comment by pizzaboxer** [comment]
Yeah, that. If it looks like that, then that's definitely because of Roblox and I can't do anything about it.

**Comment by NikoYTRBLX** [comment]
Sucks, Roblox really do be breaking everything with the 64-bit update

**Comment by pizzaboxer** [comment]
Hey, if you're able to create a memory dump, I can send it to a Roblox staff member and hopefully get some resolution on it.

**Comment by NikoYTRBLX** [comment]
I think I have a file of a memory dump located somewhere, don't exactly know where though

**Comment by NikoYTRBLX** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/a87966b8-2e91-4e9c-8d43-8577dd5a9aac)
May this be it? If not, could you direct me to the correct directory?

**Comment by pizzaboxer** [comment]
Should be in `%localappdata%\Roblox\logs`? Also wow, I had no idea it generated them for Bloxstrap. That might be useful.

**Comment by NikoYTRBLX** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/b60b58ef-779e-458a-adf1-6afa94dcb584)
I don't think these are memory dumps but instead are log files

**Comment by pizzaboxer** [comment]
Dumps should usually show up there too though. At least, they do for me. The CrashDumps folder should be enough though.
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/a340c186-e6c1-48ff-b737-9bc8ce5af340)

**Comment by NikoYTRBLX** [comment]
Do I just drop the crashdump file in here?

**Comment by NikoYTRBLX** [comment]
Oh, the .dmp files were located deeper in the archive folder, no wonder

**Comment by NikoYTRBLX** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/7677a430-f62a-46f1-ae59-6dc38cb4daee)
Ah, I think it was this, but it's since been removed off my device, probably automatically

**Comment by NikoYTRBLX** [comment]
> Hey, if you're able to create a memory dump, I can send it to a Roblox staff member and hopefully get some resolution on it. Anyway, I'm assuming this post is talking about the Roblox memory dump error.
Well, since I cannot drag and drop a .dmp file in here, I might as well add it to my drive.
Link found here: https://drive.google.com/file/d/1fIyTWtg0-CVeEZJWvByKCtpLMxFz6pl6/view?usp=share_link

**Comment by Boi2021Miceoos** [comment]
> ![image](https://user-images.githubusercontent.com/38755801/241434853-7677a430-f62a-46f1-ae59-6dc38cb4daee.png) Ah, I think it was this, but it's since been removed off my device, probably automatically

hm i have the tmp file still on my pc: https://drive.google.com/file/d/1xM6Vhij0yZ0n2JVM5fPgg3BAgVIZNTN9/view?usp=drive_link

**Comment by pizzaboxer** [comment]
> Oh, the .dmp files were located deeper in the archive folder, no wonder

Did you also find a corresponding .ini file? The crash dump should be enough, but just wondering.

**Comment by NikoYTRBLX** [comment]
No, this file is straight from the CrashDumps folder.

**Comment by pizzaboxer** [comment]
I'm treating this as a Roblox problem, so I'll close this now.
