### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by 35o59** [pizzaboxer/bloxstrap#2520]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

it says "System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied."
[Bloxstrap_20240730T113043Z.log](https://github.com/user-attachments/files/16427032/Bloxstrap_20240730T113043Z.log)

**Comment by pizzaboxer** [comment]
Read the Wiki. Also, you're not using the latest version of Bloxstrap.
