### ISSUE TITLE
[BUG] Extreme FPS Drop ~5 Minutes After Opening Roblox

### ISSUE THREAD

**Issue by englnadd** [pizzaboxer/bloxstrap#2521]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Hello.
Recently, I have discovered a bug where around ~5 minutes after launching roblox, my fps will drop extremely low, normally into the 40s. I have a good laptop, and it normally runs roblox at 200+ fps.

The only way to fix this bug is to restart my entire pc. I have even tried Factory Resetting my computer to see if something was causing an issue, however this doesn't seem to be the case.
This is a bloxstrap issue, not a roblox issue. I have already brought this issue up with roblox support, and they cannot figure the bug out. When using the standalone roblox client, this bug does not occur, however since roblox standalone is really unoptimised my fps is always at around 50fps, making my main game unplayable due to it requiring high precision.

Here is an attached video documenting the issue: https://youtu.be/7ngODs9mUgg

If I can provide anything else, let me know.

**Comment by pizzaboxer** [comment]
> I have already brought this issue up with roblox support, and they cannot figure the bug out. When using the standalone roblox client, this bug does not occur

Don't contact Roblox support for issues that don't happen with the standalone client. I'm not sure why you would do that.

> however since roblox standalone is really unoptimised

There's something you're neglecting to tell me here. Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by englnadd** [comment]
> Don't contact Roblox support for issues that don't happen with the standalone client. I'm not sure why you would do that.

I contacted them before I figured out that the issue was with Bloxstrap. This was a fault on my part.
> There's something you're neglecting to tell me here. Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

Sorry, completely forgot to upload these files. I've attached them to this comment.

[Settings.json](https://github.com/user-attachments/files/16440894/Settings.json)
[State.json](https://github.com/user-attachments/files/16440895/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/16440898/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
> however since roblox standalone is really unoptimised my fps is always at around 50fps

Are you sure about this? You haven't configured anything in Bloxstrap at all that could affect performance (unless you just reinstalled Bloxstrap). Roblox and Bloxstrap should perform identically according to this configuration.

You're sure that with Roblox standalone you have the framerate limit raised higher than 60, right?

**Comment by englnadd** [comment]
Just checked and realised I didn’t have the fps unlocked in standalone. Unlocking the fps gives me around 110 fps. Sorry for the inconvenience.

Also in my original issue I did provide evidence that shows the bug, and this bug does not happen on standalone AFAIK. I’ve gone as far as factory resetting my pc to see if there was an issue with windows but that has provided no luck.

It is not my hardware as again, this is the only game this happens in.

**Comment by pizzaboxer** [comment]
One last test to fully exclude out Bloxstrap. Go to `%localappdata%\Bloxstrap\Versions`, open the version folder, delete the ClientAppSettings folder, and directly run RobloxPlayerBeta.exe. See if it still happens there.

**Comment by englnadd** [comment]
Just did this, and the bug still occurs which (i think) means this isn't a bloxstrap issue. I genuinely have no idea what is causing this issue, I've tried everything to fix it.

If this isn't a bloxstrap issue, do you have any idea of what may be causing this? Just something that I could look into to hopefully find this bug.

**Comment by pizzaboxer** [comment]
> If this isn't a bloxstrap issue, do you have any idea of what may be causing this? Just something that I could look into to hopefully find this bug.

Can't really help with that, sorry.
