### ISSUE TITLE
[BUG] Roblox download

### ISSUE THREAD

**Issue by MasterSword143** [pizzaboxer/bloxstrap#2522]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever I try and download roblox on my windows ten pc it doesn't work no more and i'm trying to fix that.

**Comment by pizzaboxer** [comment]
Can you describe the problem more specifically please?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
