### ISSUE TITLE
[BUG] Bloxstrap start 

### ISSUE THREAD

**Issue by Ansino224** [pizzaboxer/bloxstrap#2524]
When I open Roblox Bloxstraps, many Roblox open in a row without stopping

**Comment by pizzaboxer** [comment]
How are you opening it? From the desktop? From the website?

**Comment by Ansino224** [comment]
From the application but if I open it from the web browser it also happens to me

**Comment by pizzaboxer** [comment]
Can you show a video of it please?

**Comment by Ansino224** [comment]
I’m sending a screenshot of the Task Manager when I open Bloxtrap. I must mention that once I open it, it gets stuck in a loop trying to open Roblox continuously. If you’d like, I can share my screen on Discord so you can see it better.
![image](https://github.com/user-attachments/assets/1770e40b-c43c-44b8-acc4-2d8c8696818b)

**Comment by pizzaboxer** [comment]
Record a video and send it please since I'm just struggling to understand why it would be opening in a loop, and I've only seen you with this issue as far as I know

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
