### ISSUE TITLE
[BUG] Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zuadfrelease because it returned HTTP 401 (Unauthorized)

### ISSUE THREAD

**Issue by CalebQQQ** [pizzaboxer/bloxstrap#2525]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image_2024-07-30_154314645](https://github.com/user-attachments/assets/94d9322c-2b2e-43eb-86d9-fd7fa1ea734f)

**Comment by pizzaboxer** [comment]
You're not using the latest version of Bloxstrap. https://github.com/pizzaboxer/bloxstrap/releases/latest
