### ISSUE TITLE
blox strap not opping

### ISSUE THREAD

**Issue by sigma389** [pizzaboxer/bloxstrap#2526]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

blox strap not opping pls help me

**Comment by pizzaboxer** [comment]
Be more specific, are you trying to install Bloxstrap? If you're launching, do you see the Bloxstrap launcher show or not?

**Comment by pizzaboxer** [comment]
Issue has stale for over a month, and will be reopened if further information is given.
