### ISSUE TITLE
[BUG] BLOXTRAP NAO CONSEGUE SE CONECTAR COM O ROBLOX

### ISSUE THREAD

**Issue by nicolasx7** [pizzaboxer/bloxstrap#2529]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

o meu bloxtrap nao se conecta com o roblox,ja fiz de tudo,ja verifiquei o antivirus,ja verifiquei minha internet e nenhum resolve meu problema!!!!!!!!!
![importante](https://github.com/user-attachments/assets/ad12057c-4183-4b84-ac69-8c1f23848bc6)

**Comment by pizzaboxer** [comment]
You need to reinstall the .NET runtime. Uninstall it first by searching for "Windows Desktop Runtime" in add/remove programs, and then reinstall it here: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true
