### ISSUE TITLE
que

### ISSUE THREAD

**Issue by hydromorphine** [pizzaboxer/bloxstrap#253]
![image](https://github.com/pizzaboxer/bloxstrap/assets/81176188/125db597-f488-49ab-b58b-91b8f9d6265f)

**Comment by pizzaboxer** [comment]
Does this happen consistently? Also, is Roblox running in the background?

**Comment by pizzaboxer** [comment]
Can I get the latest Bloxstrap log file? You can find it by going to `%temp%` in the file browser, and searching for any files beginning with "Bloxstrap_" in the filename.

**Comment by pizzaboxer** [comment]
Still though, send a log file. I want to see how this happened.
