### ISSUE TITLE
[BUG] Roblox not opening when using Bloxstrap. I have no other roblox plugins/applications installed.

### ISSUE THREAD

**Issue by IceboundCat6** [pizzaboxer/bloxstrap#2530]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I've looked at the page of solutions to my problem, but none of them suit me, and most of them are solutions only because of something going wrong with Hyperion. I can open Roblox just fine by itself, but Bloxtrap just shows the "starting Roblox" window, minimizes to my taskbar, and then does nothing.

Here's my log file (I've replaced my name in the file directory with USERNAME)
[last.log.txt](https://github.com/user-attachments/files/16434034/last.log.txt)

**Comment by pizzaboxer** [comment]
Right...

![image](https://github.com/user-attachments/assets/a84283ae-3fd8-4b91-b1b7-368b8be656ae)

Did you read this section of the page of solutions you said none of them suited you?

![image](https://github.com/user-attachments/assets/fe0179d9-e974-4584-9dc1-53f6790872dd)

**Comment by IceboundCat6** [comment]
Woops, haha...
I uninstalled and reinstalled bloxstrap to try to solve the issue and neglected to check the fastflags again since I figured the uninstall would've removed them - my bad! Thanks for replying though.
As for me not seeing it in the log file... I didn't really look through it...
