### ISSUE TITLE
[BUG] Lookout failed, it keeps apearing that when the location notification appears on my screen, meaning that i can't see the location of the server i am.

### ISSUE THREAD

**Issue by SxpS1** [pizzaboxer/bloxstrap#2531]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Captura de tela 2024-07-30 204534](https://github.com/user-attachments/assets/30cd98bc-9145-4ed4-ac8a-5b60a1fbe60f)
This is the error.

**Comment by pizzaboxer** [comment]
Join a game, then get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs`, and upload it here

**Comment by SxpS1** [comment]
![Captura de tela 2024-07-31 190814](https://github.com/user-attachments/assets/7508ce71-b59d-4a4b-b418-2e8804e05400)

**Comment by SxpS1** [comment]
![Sem título](https://github.com/user-attachments/assets/19599416-aac4-4311-b0ad-0e9b87798fe7)
i censured my IP for obvious reasons, so this is the last log file i joined in

**Comment by SxpS1** [comment]
> Join a game, then get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs`, and upload it here
![Sem título](https://github.com/user-attachments/assets/fc7c515a-9d60-4252-8c98-06783bf99432)

**Comment by nakoyasha** [comment]
> i censured my IP for obvious reasons, so this is the last log file i joined in
FYI, you censored the server's IP, not yours. Also please send it as a file instead of a screenshot.

**Comment by pizzaboxer** [comment]
You seem to be joining games too quickly. Slow down and it'll work.
