### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GooseFRscripts** [pizzaboxer/bloxstrap#2535]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Idk whats wrong
![image](https://github.com/user-attachments/assets/6d258a8a-fdc5-423d-86a4-cf11af09fb65)

**Comment by Roblox-Thot** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
