### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\phanv\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied

### ISSUE THREAD

**Issue by Ronaldosiu1** [pizzaboxer/bloxstrap#2536]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\phanv\AppData\Local\Bloxstrap\Bloxstrap.exe' 
![Ảnh chụp màn hình 2024-08-01 000741](https://github.com/user-attachments/assets/4e038101-73ab-4568-9734-5f9d0dc2db8e)
is denied

**Comment by siquesiiiiiii** [comment]
you found a fix?

**Comment by siquesiiiiiii** [comment]
> Try to delete the Bloxstrap files and reinstall https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

i tried this but the same

**Comment by pizzaboxer** [comment]
> i tried this but the same

Are you sure? This error definitely would not be happening if you tried deleting Bloxstrap's appdata folder.
