### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kingnoobrse** [pizzaboxer/bloxstrap#2539]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i have a new roblox settings menu since i downloaded bloxtrap and i dont know how to get the old one back

**Comment by kingnoobrse** [comment]
i read everything

**Comment by pizzaboxer** [comment]
Are you talking about this? https://github.com/pizzaboxer/bloxstrap/wiki/A-guide-to-FastFlags#escape-menu-version

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
