### ISSUE TITLE
Alt tab Roblox Become White screen Issue

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#254]
Sometimes, When i Alt+Tab Roblox, the Roblox will become white screen of death
idk im using Vulkan Rendering

**Comment by EasternBloxxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-crashes#crashing-only-when-minimizing-roblox This might help

**Comment by Boi2021Miceoos** [comment]
i will update if it fixes that problem
im updated the .json file

**Comment by Boi2021Miceoos** [comment]
UPD: bruh it reseted to Automatic after changing that
also everything inside the FastFlags Section
eh i will use automatic untill this is fixed

**Comment by EasternBloxxer** [comment]
> UPD: bruh it reseted to Automatic after changing that also everything inside the FastFlags Section eh i will use automatic untill this is fixed

Show the file after you added them

**Comment by pizzaboxer** [comment]
yeah this is why we need a dedicated fastflag editor

**Comment by Boi2021Miceoos** [comment]
This is the Vulkan after i do the FFlagRenderVulkanFixMinimizeWindow thing:
![Vulkan json](https://github.com/pizzaboxer/bloxstrap/assets/86916029/05a1e6f6-6bb0-44b1-9859-2e9586f0a162)
This is the automatic render default:
![Automatic](https://github.com/pizzaboxer/bloxstrap/assets/86916029/419c0c0e-faab-43ed-89c0-d7c893237c1d)

**Comment by pizzaboxer** [comment]
yeah that's fine, but you definitely didn't edit the json file correctly the first time if it reset itself

**Comment by Boi2021Miceoos** [comment]
oh ok

**Comment by pizzaboxer** [comment]
are you still having the problem or does it work fine now?
