### ISSUE TITLE
[BUG] Background For 2015 Escape Menu Black

### ISSUE THREAD

**Issue by OrangeManPerson** [pizzaboxer/bloxstrap#2540]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image_2024-07-31_135343](https://github.com/user-attachments/assets/3439fe74-a518-4b98-8fe8-ca92d013004e)
I Have No Idea How To Make This Work Normally, Moderators, Please Fix This Or Help Me

**Comment by OrangeManPerson** [comment]
The Background is black please help me

**Comment by OrangeManPerson** [comment]
i am unable to adjust the background transparency

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by OrangeManPerson** [comment]
I can't adjust the background transparency

**Comment by pizzaboxer** [comment]
Can you please do what I've asked?

**Comment by OrangeManPerson** [comment]
Yes, I can. I Can't change the background transparency

**Comment by pizzaboxer** [comment]
Stop replying by email and look at the GitHub thread so you can properly see what I am asking you to do.

https://github.com/pizzaboxer/bloxstrap/issues/2540

Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
