### ISSUE TITLE
server location isnt showing

### ISSUE THREAD

**Issue by haileyy7777** [pizzaboxer/bloxstrap#2541]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

okay i might be slow but i downloaded the nvidia beta thing for my clips so i can get more fps and after i started using that my bloxstrap location doesn't show when i join servers, i turned it on & off and reinstalled it and it's just not working anymore. i'm not into tech and stuff like that so im not sure if the nvidia thing caused this or if i did something to bloxstrap?

**Comment by OrangeManPerson** [comment]
that is weird

**Comment by OrangeManPerson** [comment]
look at this tho

**Comment by OrangeManPerson** [comment]
wait

**Comment by OrangeManPerson** [comment]
it disappeared :O
