### ISSUE TITLE
can someone help me and check out why these settings arent opening roblox

### ISSUE THREAD

**Issue by Premired** [pizzaboxer/bloxstrap#2542]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[ClientAppSettings MAIN.json](https://github.com/user-attachments/files/16447309/ClientAppSettings.MAIN.json)

**Comment by pizzaboxer** [comment]
Did you read this warning at all or no

![image](https://github.com/user-attachments/assets/9b37eb27-e848-4ab8-87a2-e8271210c57f)

Just don't use this. Delete everything you've configured in the flag editor please.
