### ISSUE TITLE
[REQ] Force shiftlock

### ISSUE THREAD

**Issue by branxys** [pizzaboxer/bloxstrap#2543]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

An option to force shift lock. Idk if there is any fast flag about it but it would be great

**Comment by OrangeManPerson** [comment]
i agree

**Comment by OrangeManPerson** [comment]
to be honest

**Comment by OrangeManPerson** [comment]
but it would have to depent on the game

**Comment by OrangeManPerson** [comment]
in some FPS games it will force sprint which might be helpful

**Comment by pizzaboxer** [comment]
Not possible
