### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by uushichan** [pizzaboxer/bloxstrap#2544]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240801T032650Z.log](https://github.com/user-attachments/files/16449832/Bloxstrap_20240801T032650Z.log)

**Comment by pizzaboxer** [comment]
Seems like an improper install. You may want to try opening the Bloxstrap Menu, going to the Behaviour tab, and enabling the "Force Roblox Reinstall" option, and try launching again. See if that works.

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
