### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\Users\prave\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Bloxstrap' is denied.

### ISSUE THREAD

**Issue by 1mdxll** [pizzaboxer/bloxstrap#2545]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240801T042736Z.log](https://github.com/user-attachments/files/16450293/Bloxstrap_20240801T042736Z.log)

Ive tried reinstalling, restarting pc and disabled antivirus to see if its blocking but it just wont open

**Comment by pizzaboxer** [comment]
That's definitely an antivirus issue and it's still interfering with installation.

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
