### ISSUE TITLE
"an exception occurred while running bloxstrap" 

### ISSUE THREAD

**Issue by YoGlenn** [pizzaboxer/bloxstrap#2546]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

cant use bloxstrap
![image](https://github.com/user-attachments/assets/55a272f4-5594-4c12-b724-ea4d61c452f9)

**Comment by YoGlenn** [comment]
also heres the log file: 
[Bloxstrap_20240801T073535Z.log](https://github.com/user-attachments/files/16451928/Bloxstrap_20240801T073535Z.log)

**Comment by pizzaboxer** [comment]
Seems like an antivirus issue. Can you check whatever antivirus you may have isn't interfering?

**Comment by YoGlenn** [comment]
hey! thnx for reaching out! just reinstalled it and it worked out for me so
no worries!
