### ISSUE TITLE
[BUG] Cant rewrite my settings in bloxstrap

### ISSUE THREAD

**Issue by mudsouljah** [pizzaboxer/bloxstrap#2547]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Everytime i try changing it i cant and it automatically opens roblox and i cant change it at all.

**Comment by ShadowCodeX-debug** [comment]
> [!] My answer given in the checkbox above is a lie.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
