### ISSUE TITLE
An exception occured while running bloxstrap

### ISSUE THREAD

**Issue by uspwz** [pizzaboxer/bloxstrap#2548]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
![image](https://github.com/user-attachments/assets/496f0e39-4520-4483-ab76-2f6388ad09d4)

**Comment by ShadowCodeX-debug** [comment]
Please ensure that your Bloxstrap is updated to the latest (2.7.0)

**Comment by Jonathon-lgtm** [comment]
I am using the (2.7.0) bloxstrap and it still says "System.UnauthorizedAccessException: Access to the path 'C:\Users\Jonat\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied." and idk how to fix it I tried to clear out my disk and it didn't work

**Comment by pizzaboxer** [comment]
Read the Wiki
