### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LopsD01** [pizzaboxer/bloxstrap#2549]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![imagem_2024-08-01_160134026](https://github.com/user-attachments/assets/9677b817-28f3-4dff-828d-df9d474dd094)
I can't sign in and activate BloxStrap

**Comment by toofastforboo** [comment]
Update your bloxstrap to the latest version (2.7.0)

**Comment by pizzaboxer** [comment]
Read the Wiki
