### ISSUE TITLE
log file is still being used by "another" process

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#255]
A yes Another one of these Log file has just occurred
Sorry about that
I think you need this log:
[Bloxstrap_20230521T123654Z.log](https://github.com/pizzaboxer/bloxstrap/files/11524570/Bloxstrap_20230521T123654Z.log)
[Bloxstrap_20230521T123443Z.log](https://github.com/pizzaboxer/bloxstrap/files/11524573/Bloxstrap_20230521T123443Z.log)
Double errors weird
Anyway i will be Deleting everything in the logs files, after closing roblox cause that fixes the log problem for a week

**Comment by WaviestBalloon** [comment]
Tried at least rebooting? Myself I don't use bloxstrap but apparently just restarting resolves the issue, or even just reinstall bloxstrap.

**Comment by Boi2021Miceoos** [comment]
nah that ok solution is to just delete everything inside the log folder

**Comment by pizzaboxer** [comment]
> nah the ok solution is to just delete everything inside the log folder

That's definitely not a proper solution, but this is giving me a good idea on figuring out what's going wrong. Didn't respond to this one because this was a duplicate issue. Anyway, post anything you find out under #212. Marking this as duplicate.
