### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by malfume** [pizzaboxer/bloxstrap#2551]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by toofastforboo** [comment]
> - [x]  My answer given in the checkbox above is a lie.
> kinda funny icl

https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox

**Comment by pizzaboxer** [comment]
Read the Wiki
