### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by beytech12** [pizzaboxer/bloxstrap#2552]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

The see page or join buttons wont show up on my status
![image_2024-08-01_213521410](https://github.com/user-attachments/assets/9c1bb9bd-80e8-4413-bd55-0c503405a880)

**Comment by pizzaboxer** [comment]
They won't show for yourself. They'll show for other people.
