### ISSUE TITLE
[BUG] Error to connect roblox

### ISSUE THREAD

**Issue by nowkyy** [pizzaboxer/bloxstrap#2554]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/a7fd4a44-3b98-48ad-9402-880ad197a301)

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions before posting.

Please be sure that your Bloxstrap version is the latest (2.7.0)
