### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by paincox** [pizzaboxer/bloxstrap#2559]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I really search how to fix this problem and I cant find nothing in any web site,my problem is from the bloxstrap windows,i cant describe it but i have a capture

![image](https://github.com/user-attachments/assets/8b74f561-71e7-40d5-aee9-b9ff11e1f3e4)
you see this vertical bar right? IDK WHAT DO HELP PLIS.

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions before posting.

Is it the Bloxstrap Menu or the splash loading window?
