### ISSUE TITLE
[BUG] Roblox crashing when launching a game

### ISSUE THREAD

**Issue by weiliang011** [pizzaboxer/bloxstrap#2560]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

hey, i need help, what can i do if my roblox crashes almost everytime when i enter a game?
no, the crash is not because of the fflags, i disabled the fflags and still crashes
thanks
![Captura de pantalla 2024-08-03 160635](https://github.com/user-attachments/assets/2ab18605-c7a9-43a6-ad2b-94ff1151ad33)

**Comment by toofastforboo** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by weiliang011** [comment]
ok, nvm, it is a fflag, can someone check my fflags to know what is wrong?

**Comment by weiliang011** [comment]
Nevermind again, i started from 0 and now isnt crashing
