### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by davo392** [pizzaboxer/bloxstrap#2562]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot 2024-08-03 at 10 17 53 AM](https://github.com/user-attachments/assets/1970f357-372b-4f69-b644-b580af47efd3)

while downloading the file (i am on a macbook pro) a
 wierd thing pops up saying file cannot be opened because the developer is suspisious, its an easy fix but when i do an error pops up saying file cannot be decompressed or something. i dont know if its a mac thing or if its only for windows

**Comment by idonthaveoneatm** [comment]
only for windows

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions before posting.

Bloxstrap is made for Windows and only for Windows, do not try to use Bloxstrap on MacOS or any Linux distros.
