### ISSUE TITLE
[REQ] Need to add bloxstrap available for mac

### ISSUE THREAD

**Issue by I-T-LE** [pizzaboxer/bloxstrap#2563]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

we need bloxstrap on mac

**Comment by AngrySausage** [comment]
https://github.com/OrigamingWasTaken/appleblox

get the latest release here:

https://nightly.link/OrigamingWasTaken/appleblox/workflows/build/main?preview

**Comment by pizzaboxer** [comment]
Not currently supported.
