### ISSUE TITLE
[BUG] roblox crashes

### ISSUE THREAD

**Issue by oxriginal** [pizzaboxer/bloxstrap#2564]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

roblox screen turns white and crashes after switching tabs

**Comment by pizzaboxer** [comment]
Stop using Vulkan. Remove the flags for it in the flag editor.
