### ISSUE TITLE
[BUG] I installed the mods and everything but it doesn’t work 

### ISSUE THREAD

**Issue by LilCYPREZZZ** [pizzaboxer/bloxstrap#2566]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I installed Bloxstrap with some mods and fonts, but it's not working for me. My friend, who has the same mods, has no issues, and everything works fine for him. I followed the same steps, but I can't get it to work. I tried uninstalling and reinstalling the application, launching Bloxstrap as an administrator, and launching Roblox through Bloxstrap, but nothing has worked. It's really frustrating. Any ideas? Thanks!

**Comment by ShadowCodeX-debug** [comment]
Can you send a picture of your Modifications folder? `%localappdata%\Bloxstrap\Modifications`

**Comment by pizzaboxer** [comment]
What mods/fonts did you put in?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.

**Comment by Voicechatguyg** [comment]
did you extract the mod files into your mods folder? should be at C:\Users\[your user]\bloxstrap\Modifications
