### ISSUE TITLE
[BUG] BLOXTRAP STAYING IN TASK MANAGER

### ISSUE THREAD

**Issue by gzvenchy** [pizzaboxer/bloxstrap#2567]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i run bloxtrap and it sits in task manager but doesnt open

**Comment by gzvenchy** [comment]
it just sits in background processes and normal roblox player works. i uninsalled and reinstalled but still the same.

**Comment by ShadowCodeX-debug** [comment]
> * [x]  My answer given in the checkbox above is a lie.

Please be sure to read the preliminary instructions before posting. (In the preliminary instructions it mentions to check the wiki for your problem.)

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by gzvenchy** [comment]
none of them works

**Comment by pizzaboxer** [comment]
Just to clarify, do you see the launcher show?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
