### ISSUE TITLE
wont let download

### ISSUE THREAD

**Issue by zac1234566666666666667** [pizzaboxer/bloxstrap#2568]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

it wont let me download

**Comment by ShadowCodeX-debug** [comment]
> * [x]  My answer given in the checkbox above is a lie.

Please read the preliminary instructions before posting. Also insufficient detail.

**Comment by pizzaboxer** [comment]
> it wont let me download

Please clarify

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
