### ISSUE TITLE
The document is empty issue

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#257]
![unable to download](https://github.com/pizzaboxer/bloxstrap/assets/86916029/45fd5125-4e58-4621-8e52-da3003dffb06)
My internet is Working fine
This isssue keep poping up everytime i run Roblox even my old pc also encoutered the issue to (my little brother use my old pc)
What is going on.
Even the Roblox default launcher still have this issue

**Comment by pizzaboxer** [comment]
What does going to https://clientsettings.roblox.com/v2/client-version/WindowsPlayer in your browser show? Also, you never replied to me in the thread about the log file error.

**Comment by Boi2021Miceoos** [comment]
oh the link you have me gave me this:
{"version":"0.575.2.5750427","clientVersionUpload":"version-5c0a67db9ef4467a","bootstrapperVersion":"1, 6, 2, 5750427"}

**Comment by pizzaboxer** [comment]
Oh wait, meant this one: https://clientsettings.roblox.com/v2/settings/application/PCDesktopClient

**Comment by Boi2021Miceoos** [comment]
a bunch of code there
![among us](https://github.com/pizzaboxer/bloxstrap/assets/86916029/0cbb1105-4c63-4e5d-ab2a-cf356f244dbb)

**Comment by pizzaboxer** [comment]
Yeah, I've got basically nothing on why Roblox would be unable to fetch it. Sorry.

**Comment by Boi2021Miceoos** [comment]
Oh, then i will be unable to play roblox for a while then.

**Comment by Boi2021Miceoos** [comment]
as of today, the issue has resolved itself for some reason.
