### ISSUE TITLE
[REQ] Can I use any flagship to bypass Roblox Virtual Machine Detect?

### ISSUE THREAD

**Issue by iMusicDorian** [pizzaboxer/bloxstrap#2570]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I used VMware workstation Pro 17 to run Roblox, but whenever I launched the app, it would show me "Virtual Machine Detected! Roblox won't run on Virtual Machine!" and then crashed. Is there any method to resolve it with Bloxstrap? I'd appreciate it!

**Comment by ShadowCodeX-debug** [comment]
Bloxstrap doesn't modify the Roblox client. There isn't any FastFlags that turn off this restriction. Mods can't help.

**Comment by pizzaboxer** [comment]
No. You'll need to passthrough a GPU with KVM to use it in a VM.
