### ISSUE TITLE
[BUG] not installing and yes ive got the right net version.

### ISSUE THREAD

**Issue by tranect** [pizzaboxer/bloxstrap#2571]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

doesnt open anything at all when i try running bloxstrap(i just downloaded windows 11 it worked fine on windows 10)

**Comment by pizzaboxer** [comment]
Just to double check, open a Command Prompt window, run this command: `dotnet --info`, and take a screenshot of what it shows
