### ISSUE TITLE
Bloxstrap isn't affecting anything. (I never got a good answer)

### ISSUE THREAD

**Issue by Sumaesioso** [pizzaboxer/bloxstrap#2572]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So, I'm trying to use Bloxstrap, and I have a custom font installed and made the launcher look like a legacy version, pretty simple stuff. Nothing is happening though? It's just normal Roblox atm.

**Comment by MrJoneshere** [comment]
hello, you need to give the log when did this happen, otherwise no one can understand your problem.

**Comment by ShadowCodeX-debug** [comment]
[Please upload your configuration](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration). As well as the log file that was created the time this occured. (Also in the file path mentioned in the link.)

**Comment by pizzaboxer** [comment]
> Nothing is happening though? It's just normal Roblox atm.

Is the font not applying? Which font did you try to use?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
