### ISSUE TITLE
[BUG] Bloxstrap Unable To Connect Roblox.

### ISSUE THREAD

**Issue by MrJoneshere** [pizzaboxer/bloxstrap#2573]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when i try to open bloxstrap this happens, and the main problem is i have my antivirus closed, and heres the log paste
https://paste.ee/p/8ImCV
![image](https://github.com/user-attachments/assets/6b97f684-72c2-453c-8c88-821dac71bb98)

**Comment by ShadowCodeX-debug** [comment]
Please send your ClientAppSettings.json file. (`%localappdata%\Bloxstrap\Modifications\ClientSettings`)

**Comment by pizzaboxer** [comment]
This is most definitely an antivirus issue, there wouldn't really be any reason for this happening. Just to clarify, Roblox Player works fine, right?

**Comment by MrJoneshere** [comment]
> This is most definitely an antivirus issue, there wouldn't really be any reason for this happening. Just to clarify, Roblox Player works fine, right?


> Please send your ClientAppSettings.json file. (`%localappdata%\Bloxstrap\Modifications\ClientSettings`)

hello, im sorry for telling this too late, roblox was been blocked by my country that was why, i fixed it with a dns, thank you for trying to help me, im going to close this post :)
