### ISSUE TITLE
Could you guys fix the gamepad cursor disappearing when controllers are plugged in

### ISSUE THREAD

**Issue by Prim1o** [pizzaboxer/bloxstrap#2574]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Since roblox won't fix it maybe you guys could figure out a fast flag or mod or smth please
Here is a youtube video for reference it's not mine btw:
https://www.youtube.com/watch?v=3UYJkiRvZC8&pp=ygUkaG93IHRvIGZpeCB0aGUgZ2FtZXBhZCBjdXJzb3Igcm9ibG94

**Comment by ShadowCodeX-debug** [comment]
Not Bloxstrap's problem.

**Comment by pizzaboxer** [comment]
^
