### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden). Im in version 2.5.4 

### ISSUE THREAD

**Issue by Flamewastakenbysome1** [pizzaboxer/bloxstrap#2576]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by Queryer229** [comment]
![Screenshot 2024-06-21 180245](https://github.com/user-attachments/assets/d982faf6-b5bf-45a1-b930-d2b4c5c25541)

**Comment by Queryer229** [comment]
guys how to fix a a System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by sfthjw** [comment]
check ur installation channel. i changed it to live and it worked.

**Comment by ShadowCodeX-debug** [comment]
You need to update your Bloxstrap version.

**Comment by pizzaboxer** [comment]
don't use 2.5.4 then lol
