### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cosmo72-JJ** [pizzaboxer/bloxstrap#2578]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

it said my this..
System.UnauthorizedAccessException: Access to the path 'C:\Users\Cosmo\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions before posting.

The Pre Lim mentions to "read the wiki" before posting.

**Comment by pizzaboxer** [comment]
Read the wiki
