### ISSUE TITLE
Do it

### ISSUE THREAD

**Issue by user1126s** [pizzaboxer/bloxstrap#258]
![image](https://github.com/pizzaboxer/bloxstrap/assets/114283670/326a90b9-2e6a-4878-95d4-599a660f7134)
For the roshade presets, zeal can help you. also zeal wants to collab with you to make a cross platform bootstrapper. pls do it. it would be great! @pizzaboxer

**Comment by pizzaboxer** [comment]
I know, we've already been talking for about a month. But at this point, I'm never really expecting ReShade to come back.

**Comment by user1126s** [comment]
I'm not asking for reshade. But he still wants to help you make a cross platform bootstrapper

**Comment by user1126s** [comment]
@pizzaboxer

**Comment by pizzaboxer** [comment]
Because it would require rewriting the entirety of Bloxstrap from scratch? Of course I'm not going to be working on it right now.
