### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).[BUG] 

### ISSUE THREAD

**Issue by alex90ed** [pizzaboxer/bloxstrap#2580]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

unable to join roblox

**Comment by ShadowCodeX-debug** [comment]
Um... I think you're on an old version of Bloxstrap. (I don't remember what this code was for.)

**Comment by Niktofem** [comment]
I personally had the same issue and after reinstalling it was fine

**Comment by pizzaboxer** [comment]
Read the Wiki
