### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by exexic** [pizzaboxer/bloxstrap#2581]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Ekran görüntüsü 2024-08-07 172129](https://github.com/user-attachments/assets/320ceeb5-cc51-408d-a97c-ac06464e0087)

please help

**Comment by exexic** [comment]
Oh my god its because they randomly decided to ban roblox in my country

**Comment by 1xs1mplex1** [comment]
Im in Turkey, and i have same error i cant play roblox..

**Comment by exexic** [comment]
I can use vpn but a full solution would be way better as vpn lags my game

**Comment by pizzaboxer** [comment]
> but a full solution would be way better as vpn lags my game

Using a VPN is quite literally the only way here.
