### ISSUE TITLE
old materials

### ISSUE THREAD

**Issue by mietowycukierek** [pizzaboxer/bloxstrap#2583]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

so i saw in sharkblox's video something about old materials, but when i open bloxstrap i cant seem to find it anywhere even after looking in the same area as in the video

**Comment by pizzaboxer** [comment]
It was removed since it's not possible to do it anymore.

**Comment by mietowycukierek** [comment]
sad, but thanks for the info :P
