### ISSUE TITLE
[BUG] failed to load library: SansApi.dll

### ISSUE THREAD

**Issue by c1mh** [pizzaboxer/bloxstrap#2584]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![لقطة شاشة 2024-08-07 223938](https://github.com/user-attachments/assets/22ec20e0-ea9b-44e9-8fc4-2c7958d1ba02)

**Comment by pizzaboxer** [comment]
Not Bloxstrap issue. You may want to look through #540.
