### ISSUE TITLE
 The block strap does not work

### ISSUE THREAD

**Issue by zloi00** [pizzaboxer/bloxstrap#2586]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I wanted to go to the blocks strap and play roblox, but when I went in, I got a text " An unexpected error occured and Roblox needs to  quit" What should I do
![2024-08-08_03-38-07](https://github.com/user-attachments/assets/7a44b255-48ce-4b35-9d37-04ce3d6e06b7)

**Comment by ShadowCodeX-debug** [comment]
Now I might be wrong but please check your anti-virus if it's inflicting with Bloxstrap/Roblox. If not-

[Please upload your configurations](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration) and send the log file of when this error occured. (`%localappdata%\Bloxstrap\Logs\` give the latest log file.)

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
