### ISSUE TITLE
[BUG] An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Oneblueapple1** [pizzaboxer/bloxstrap#2587]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/7497e359-1883-40c2-8f47-843b27264029)

I need help ty

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions.

Update to the latest version of Bloxstrap. (2.7.0)
