### ISSUE TITLE
michbroz

### ISSUE THREAD

**Issue by michbroz** [pizzaboxer/bloxstrap#2588]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

.

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions.

Insufficient details, please clarify.

**Comment by pizzaboxer** [comment]
Closing unless something of substance is actually given
