### ISSUE TITLE
[BUG] Can't launch Bloxstrap.

### ISSUE THREAD

**Issue by Frit51** [pizzaboxer/bloxstrap#2589]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

For some apparent reason, out of nowhere, I try opening bloxstrap and I get this:
![Screenshot 2024-08-07 205355](https://github.com/user-attachments/assets/711e85c4-8d8d-4008-9260-a9e500d1ab65)

Log file: 
[Bloxstrap_20240807T234912Z.log](https://github.com/user-attachments/files/16535756/Bloxstrap_20240807T234912Z.log)

By the way, I am using the version 2.5.3 whilst writing. 
Thanks for the help!

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions.

You're literally the 7th person I've had to tell to **UPDATE TO THE LATEST VERSION OF BLOXSTRAP**.
