### ISSUE TITLE
not being able to open menu

### ISSUE THREAD

**Issue by BelleButCode** [pizzaboxer/bloxstrap#259]
So i might actually just be stupid, but I dont seem to be able to open that menu from the first install after installing it completely, is there a way to? and how would I uninstall it?
edit: by menu i mean the config menu for the application

**Comment by pizzaboxer** [comment]
Search "Bloxstrap Menu" in the Start menu. Also, you'd just uninstall it like [how you'd uninstall any other program](https://github.com/pizzaboxer/bloxstrap/wiki/Uninstalling-Bloxstrap) on your computer.
