### ISSUE TITLE
[BUG] Once i go into a roblox game, after 1-5 minutes my mouse and keyboard gets delayed, only on roblox/bloxstrap. Not on anywhere else.

### ISSUE THREAD

**Issue by Musooo233** [pizzaboxer/bloxstrap#2590]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Once i go into a roblox game, after 1-5 minutes my mouse and keyboard gets delayed, only on roblox/bloxstrap. Not on anywhere else.

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions.

Kinda sounds like ping latency too me.

**Comment by Musooo233** [comment]
No, even when i get about like 50 ping it happens.

**Comment by ShadowCodeX-debug** [comment]
Hmm...

[Please upload your configurations](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration).

**Comment by Musooo233** [comment]
????

**Comment by ShadowCodeX-debug** [comment]
What are you confused about?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
