### ISSUE TITLE
[BUG] A

### ISSUE THREAD

**Issue by TheLegendaryPeanut** [pizzaboxer/bloxstrap#2592]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

An exception occurred while running bloxstrap

**Comment by Roblox-Thot** [comment]
You may want to upload the logs or show the full error or you might not get help from some one, just a heads up

**Comment by ShadowCodeX-debug** [comment]
Upload the log file which this error has occurred. (`%localappdata%\Bloxstrap\Logs\` sort by newly created and send the latest log file.)

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
