### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Huisgood** [pizzaboxer/bloxstrap#2596]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240808T074018Z.log](https://github.com/user-attachments/files/16539482/Bloxstrap_20240808T074018Z.log)
Bloxstrap Exception

**Comment by pizzaboxer** [comment]
Read the Wiki
