### ISSUE TITLE
[BUG]  Version 2.5.0

### ISSUE THREAD

**Issue by Novirok** [pizzaboxer/bloxstrap#2598]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Same stuff as others:  System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
 Did not see anyone mention the version they are using so im just gonna say im on version 2.5.0
 
[Bloxstrap_20240808T113228Z.log](https://github.com/user-attachments/files/16542286/Bloxstrap_20240808T113228Z.log)

**Comment by Roblox-Thot** [comment]
All versions below version I think roughly v2.6.0 don't work do to updates that Roblox has made to launching the client.

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> Please read the preliminary instructions before posting.

Please update to the latest verison of Bloxstrap. (2.7.0)
