### ISSUE TITLE
stuck on the installation window

### ISSUE THREAD

**Issue by SydDeus** [pizzaboxer/bloxstrap#26]
after getting done with the preferences, the installation process for BloxStrap seems to go on forever.

**Comment by pizzaboxer** [comment]
On the "Installing Roblox" stage?

**Comment by SydDeus** [comment]
> On the "Installing Roblox" stage?

on the "Select cancel to return to preferences" stage.

**Comment by pizzaboxer** [comment]
You clicked the "Preview" button, which previews the look of the bootstrapper.

**Comment by SydDeus** [comment]
> 

ohh, yeah that explains it. thank you alot!
