### ISSUE TITLE
Don't see the roblox shaders

### ISSUE THREAD

**Issue by ShadowSlayer5432** [pizzaboxer/bloxstrap#260]
Why it's removed? I wanted to enhance my game :(

**Comment by EasternBloxxer** [comment]
What

**Comment by ShadowSlayer5432** [comment]
I was trying to find ReShade, but can't find it

**Comment by Boi2021Miceoos** [comment]
Roshade, it not Working right now
Due to Roshade not Whitelist by roblox
You can install Reshade but you cannot see or use its effects and settings

**Comment by pizzaboxer** [comment]
See [2.3.0's release notes](https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.3.0). You would've seen this before downloading it.
> ReShade has now been removed, as it does not work with the new 64-bit game client.
