### ISSUE TITLE
[ERROR] Versión 2.5.4

### ISSUE THREAD

**Issue by Dicito** [pizzaboxer/bloxstrap#2600]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Lo mismo que otros: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
uso una versión antigua exactamente la 2.5.4 para abrir diferentes roblox en mi pc pero ahora ultimo ya no puedo abrir mas de 1 roblox x culpa de este error 
dejare el log:
[Bloxstrap_20240808T140541Z.log](https://github.com/user-attachments/files/16549201/Bloxstrap_20240808T140541Z.log)

si pudiera poner nuevamente el allow multi-instance launching en una versión mas actual de bloxtrap para seguir jugando con mis multicuentas

**Comment by Storm-930** [comment]
La versión 2.5.4 ha sido así por mucho tiempo, simplemente actualice a la versión 2.7.0 y use la versión de Mircosoft Store junto con la aplicación web, o use Roblox Account Manager.

google translator goes brrrrrrrrr

**Comment by Dicito** [comment]
pero yo quiero usar 7+ cuentas

**Comment by pizzaboxer** [comment]
Read the Wiki
