### ISSUE TITLE
[BUG] Roblox made by BloxStrap keeps crashing

### ISSUE THREAD

**Issue by NickyST4R** [pizzaboxer/bloxstrap#2602]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Every time I enter a map, Roblox crashes, and I don't know what it is, I've tried every possible way and I couldn't.
![Captura de tela 2024-08-08 133910](https://github.com/user-attachments/assets/4589c84f-aa49-4c68-a123-9bf8c4ed9536)

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie

> [!WARNING]
> Please read the preliminary instructions before reading.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
