### ISSUE TITLE
[BUG] error 403

### ISSUE THREAD

**Issue by oudehenky** [pizzaboxer/bloxstrap#2603]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

[Bloxstrap_20240808T202328Z.log](https://github.com/user-attachments/files/16553103/Bloxstrap_20240808T202328Z.log)

**Comment by oudehenky** [comment]
likely a redundant report as updating bloxstrap and reinstalling roblox fixed the issue

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie

> [!WARNING]
> Please read the preliminary instructions before reading.

# UPDATE YOUR BLOXSTRAP TO THE LATEST VERSION.
