### ISSUE TITLE
[BUG] I am unable to use one of the hotkeys.

### ISSUE THREAD

**Issue by R0BFISHY** [pizzaboxer/bloxstrap#2604]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I am currently unable to use two of the Hotkeys in game. The game I am attempting to use the hotkeys on is Buckingham Palace I am able to use the following Hotkeys: 
- Ctrl + Shift + N
- Ctrl + Shift + B

The hotkeys I am able to use are:

- Ctrl + Shift + B
- Ctrl + Shift + N

I am not sure of the cause of the error but I am unable to take pictures which was the key feature why I download BloxStrap please assist.

**Comment by ShadowCodeX-debug** [comment]
Can I see your FastFlag configuration? (`%localappdata%\Bloxstrap\Modifications\ClientSettings\` Send the file in that folder.)

**Comment by pizzaboxer** [comment]
Not a problem on my side. You likely have some other software conflicting with the other two keybinds.
