### ISSUE TITLE
Quando eu movo o arquivo da fonte para as pastas de fontes o arquivo some!

### ISSUE THREAD

**Issue by NickyST4R** [pizzaboxer/bloxstrap#2606]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Eu estou tentando faz 1 semana tentando mover o arquivo pra pasta de fonte e ele simplesmente some, estou ficando louca por isso, tentei várias outras fontes, e todas somem

**Comment by NickyST4R** [comment]
![Captura de tela 2024-08-08 194714](https://github.com/user-attachments/assets/711e05a4-69bb-4a52-ad49-93b35d8cc1f5)

**Comment by pizzaboxer** [comment]
Which file are you specifically trying? Link it or upload it please

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
