### ISSUE TITLE
**Some Unstable Client and stuff when I join a game, Or it says something about BAC-ALpha**

### ISSUE THREAD

**Issue by rougath** [pizzaboxer/bloxstrap#2608]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### ![image](https://github.com/user-attachments/assets/21f567d2-657a-48dc-ab0b-73ae930cf89e)

This is what have been experiencing for the past week, I don't know if it is the fast flags I am using, Or bloxstrap it self. If anyone got any solutions help me out!!** ### :D**

**Comment by ShadowCodeX-debug** [comment]
Holy shit, what game is this? The fucking developer made it kick Bloxstrap users. xD

**Comment by pizzaboxer** [comment]
What game is this?

**Comment by bluepilledgreat** [comment]
Closed due to inactivity from OP.
