### ISSUE TITLE
[BUG] Weird Visual Glitch in bloxstrap menu??

### ISSUE THREAD

**Issue by WinAurora** [pizzaboxer/bloxstrap#2612]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I have installed Bloxstrap today, and for some reason the menu is having **visual glitches**, It's hard to control
Provided video:

https://github.com/user-attachments/assets/c544dde1-4c4e-4a04-86f7-dce0ba71f701

My pc is W11, RTX 2070 Super, Intel i7-9700k

**Comment by WinAurora** [comment]
My pc is W11, RTX 2070 Super, Intel i7-9700k

**Comment by WinAurora** [comment]
Sonic Suite turns out to be the cause of this issue.

**Comment by pizzaboxer** [comment]
if i had a nickel every time some shitty oem audio software caused this issue id have two which isnt a lot but is weird i have that much in the first place
