### ISSUE TITLE
[BUG] Bloxstrap Exeption 

### ISSUE THREAD

**Issue by Yugi6688** [pizzaboxer/bloxstrap#2617]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

idk wtf is this even mean i try to open roblox with bloxstrp new verison just not opening roblox pls help 
![Bloxstrap_15w4VrfXS0](https://github.com/user-attachments/assets/bcb84078-6a1c-4916-a874-7bffc3221f39)

**Comment by pizzaboxer** [comment]
Read the Wiki
