### ISSUE TITLE
Installed but nothings happening

### ISSUE THREAD

**Issue by emrvd** [pizzaboxer/bloxstrap#262]
I need clarification on how to use this, do i have to copy a file into another file? or what do i do because when i run roblox through the website as well as the app, the shaders dont work.

**Comment by pizzaboxer** [comment]
> the shaders dont work.

What? Where are shaders listed as a feature?

**Comment by emrvd** [comment]
> > the shaders dont work.
> 
> What? Where are shaders listed as a feature?

oh i got this link from someone for bloxburg lighting and shaders ? misunderstanding then

**Comment by Boi2021Miceoos** [comment]
is it Roshade? (roblox shaders)
