### ISSUE TITLE
[BUG] VR problems

### ISSUE THREAD

**Issue by Miguelxtrem** [pizzaboxer/bloxstrap#2620]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When I open the roblox game, everything opens correctly except that nothing is displayed on my headset, I only have the sound but not the game.

**Comment by Miguelxtrem** [comment]
i already have checked all the previous explanation but nothing works

**Comment by ShadowCodeX-debug** [comment]
[Please upload your configs](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration).
