### ISSUE TITLE
[BUG] Cant download

### ISSUE THREAD

**Issue by BRL26** [pizzaboxer/bloxstrap#2622]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

An Exeption occured while running bloxstrap: System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.

[Inner Exception]
System.EntryPointNotFoundException: Unable to find an entry point named 'FindMimeFromData' in DLL 'urlmon.dll'.

**Comment by pizzaboxer** [comment]
You need to reinstall the .NET runtime. Search for "desktop runtime" in add/remove programs, uninstall it, then reinstall it from https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win11-x64&apphost_version=6.0.16&gui=true.
