### ISSUE TITLE
[BUG]  Roblox process in Google Chrome process in task manager 

### ISSUE THREAD

**Issue by Kuiaza** [pizzaboxer/bloxstrap#2626]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Roblox process in Google Chrome process in task manager is it normal having bloxstrap/roblox in chrome processes

**Comment by ShadowCodeX-debug** [comment]
Well, if you are launching Roblox/Bloxstrap through Chrome, it is possible since it's launching Roblox.

**Comment by pizzaboxer** [comment]
Yes
