### ISSUE TITLE
An exception occured while running bloxstrap

### ISSUE THREAD

**Issue by Kensonsuthegoat** [pizzaboxer/bloxstrap#2628]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\iluvj\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie

> [!WARNING]
> Please read the preliminary instructions before reading.

https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
