### ISSUE TITLE
Option to set lighting to "Compatibility" + ShadowMap when only Having Voxel and FIB buttons

### ISSUE THREAD

**Issue by Nebelous555** [pizzaboxer/bloxstrap#263]
![image](https://github.com/pizzaboxer/bloxstrap/assets/120223163/6a808aa8-e548-4bfc-b56a-c2e12a3b7467)

I did that myself using flags but since my bloxstrap updates i forgot which one was for Compatibility, ShadowMap is FutureIsBright2 where Future is FutureIsBright3 flag, I forgot the compatibility one.

**Comment by bluepilledgreat** [comment]
There are no known flags that force Compatibility or Shadow Map lighting technologies.

**Comment by pizzaboxer** [comment]
huh am i crazy cuz i couldve sworn i only saw one future flag for phase 3 the last time i looked at the list
if you're able to find the flag for compatibility then that'd be great because i definitely can't find it
