### ISSUE TITLE
[BUG] wont open no matter what ive reinstalled about 5 times 

### ISSUE THREAD

**Issue by waltuh951** [pizzaboxer/bloxstrap#2630]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

the game will open normally but wont open thru bloxstrap ive reinstalled restarted and it just wont ive had someone help me i really think i need a dev to help

**Comment by ShadowCodeX-debug** [comment]
Please send the log file when this issue occured (`%localappdata%\Bloxstrap\Logs\`)

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?
