### ISSUE TITLE
Can i set font size in bloxstrap to 0,9 and below? 

### ISSUE THREAD

**Issue by Mirkarikari** [pizzaboxer/bloxstrap#2633]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I want to change the size form 1 to 0,5 cuz my font is too big. Can someone help me with that?

**Comment by toofastforboo** [comment]
You can't, the minimum value is 1. Try changing the font itself.

**Comment by pizzaboxer** [comment]
See #2631

You can't set it as a decimal, only a whole number, but you can set it to below 1 if you adjust the value of the flag preset in the flag editor
