### ISSUE TITLE
[REQ] Make BloxTrap available on Windows Store 

### ISSUE THREAD

**Issue by FrenchToastCat** [pizzaboxer/bloxstrap#2634]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Or make a setting that makes you play on WASD instead of ZQSD roblox always mistakes it

**Comment by Storm-930** [comment]
there's this neat little application called Microsoft PowerToys which allows you to, among other things, _rebind your keys_
also making bloxstrap for the windows store version would double the work that pizzaboxer would have to do, so no

**Comment by FrenchToastCat** [comment]
k imma try it out

**Comment by FrenchToastCat** [comment]
Doesnt work

**Comment by Storm-930** [comment]
search up how to rebind keys with powertoys on google...

**Comment by FrenchToastCat** [comment]
aight its either im stupid or its just too complicated for me

**Comment by Storm-930** [comment]
as someone to likes to have power over their OS like me i see this as an absolute disgrace

**Comment by pizzaboxer** [comment]
> Or make a setting that makes you play on WASD instead of ZQSD roblox always mistakes it

Not possible for us. Also, no.
