### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jayk045** [pizzaboxer/bloxstrap#2635]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

this only happens with bloxstrap, i have checked out some of the previous errors posted here and didnt find this one (i might have missed it if it was there)

what do i do to fix this, if its just a me problem

**Comment by ShadowCodeX-debug** [comment]
Please update your Bloxstrap to the latest version. (2.7.0)
