### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by mintnv** [pizzaboxer/bloxstrap#2637]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240812T105543Z.log](https://github.com/user-attachments/files/16580590/Bloxstrap_20240812T105543Z.log)

**Comment by ShadowCodeX-debug** [comment]
Please update your Bloxstrap to the lastest version. (2.7.0)

**Comment by whaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaat** [comment]
does this mean i wont be able to use 2.5.4 anymore for multi-instance cuz im getting the same error 😡

**Comment by bluepilledgreat** [comment]
> does this mean i wont be able to use 2.5.4 anymore for multi-instance cuz im getting the same error 😡

Use the latest version. Older versions of Bloxstrap are not supported and may break.
