### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users' is denied.

### ISSUE THREAD

**Issue by MrPorkun** [pizzaboxer/bloxstrap#2642]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I don't know what is this

**Comment by pizzaboxer** [comment]
How did you manage to install Bloxstrap to ***there***?

You're going to need to do a fresh reinstall. Delete Bloxstrap's install registration (shown at https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-stops-working-after-renaming-the-user-profile-folder), and reinstall normally without changing the install location.
