### ISSUE TITLE
I can't get roblox to use my resources. And can't get fps cap to exceed 240 fps.

### ISSUE THREAD

**Issue by Swaien** [pizzaboxer/bloxstrap#2643]
The game doesn't want to use my resources. When i first capped my fps to 165 on bloxstrap, it did cap the fps but my overall fps was 30-15 fps lower than 165 and experienced a lot of fps drops. Cpu and gpu usage didn't go over 30%. I tried capping the fps to 240 fps this time and it increased my fps but my overall fps was 30-15 fps lower than 240, i was going to use it like that but it occasionally went below 165 fps which is my refresh rate. it didn't use over 35% of my cpu and gpu this time. How can i make roblox use more of my resources to keep my fps steady at 165?

(Sorry for bad english.)

**Comment by ShadowCodeX-debug** [comment]
You need a flag to bypass the limit.

**Comment by Swaien** [comment]
> ShadowCodeX

Can you tell me what the fflag is?

**Comment by ShadowCodeX-debug** [comment]
FFlagTaskSchedulerLimitTargetFpsTo2402

**Comment by pizzaboxer** [comment]
I wouldn't recommend you use it, Roblox caps to 240 for a reason, and it's likely temporary. But yes, you can.
