### ISSUE TITLE
[BUG] avatar/meshes doesn't work

### ISSUE THREAD

**Issue by Rudistoy** [pizzaboxer/bloxstrap#2644]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When i downloaded bloxtrap at first time mod to change character was working fine, but after some time after i disabled it, and enabled it again, mod wasnt working, but everything other (like oof sound or old avatar stuff) was fine.

**Comment by Zekyel200** [comment]
How did you fix it bro It's happening to me aswell

**Comment by Leonistdeutscher** [comment]
![Image](https://github.com/user-attachments/assets/246b3791-01da-472f-abf7-6e547d39f47f)

> How did you fix it bro It's happening to me aswell
