### ISSUE TITLE
[BUG] CAN'T OPEN ROBLOX

### ISSUE THREAD

**Issue by Skibidimax** [pizzaboxer/bloxstrap#2648]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

https://github.com/user-attachments/assets/816ff0a6-fae5-4763-98e4-7bb1b9fb1471

**Comment by ShadowCodeX-debug** [comment]
> * [] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

> [!WARNING]
> PLEASE READ THE PRELIMINARY INSTRUCTIONS BEFORE POSTING.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
Will reopen once you've confirmed you've read
