### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bloxstraprider69** [pizzaboxer/bloxstrap#2649]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

[Bloxstrap_20240814T074559Z.log](https://github.com/user-attachments/files/16609317/Bloxstrap_20240814T074559Z.log)

uhh yaweh!!

**Comment by Roblox-Thot** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap

You will more than likely just have to delete the BloxStrap install ([more info](https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap))

If that doesn't fix it then just update bloxstrap (which you should do anyway)

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> PLEASE READ THE PRELIMINARY INSTRUCTIONS BEFORE POSTING.

Like he said.

**Comment by pizzaboxer** [comment]
Read the Wiki
