### ISSUE TITLE
[BUG] The recent issue with Roblox bans

### ISSUE THREAD

**Issue by homura-suki1003** [pizzaboxer/bloxstrap#2650]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

SINCE ABOUT THE EARLY HOURS OF THIS MORNING, THERE HAVE BEEN A LOT OF PEOPLE SPREADING THE NEWS ABOUT ROBLOX REGULATED INJECTORS/LAUNCHERS/THIRD-PARTY LAUNCHERS, AND MANY PEOPLE ARE SAYING THAT THESE TOOLS WILL BE BANNED WITHOUT EXCEPTION, RANGING FROM BANNING TO DELETING ACCOUNTS AND DATA, AND SOME OF THEM HAVE SAID THAT BLOXSTRAP USERS WILL ALSO BE BANNED, IS THIS TRUE?

**Comment by Roblox-Thot** [comment]
You can not get banned from BloxStrap as it doesn't interact with the client in any way.

More info on the wiki here: https://github.com/pizzaboxer/bloxstrap/wiki/Why-it's-not-reasonably-possible-for-you-to-be-banned-by-Bloxstrap

**Comment by rielmeow** [comment]
got banned for this along with my friends

**Comment by pizzaboxer** [comment]
Read the Wiki
