### ISSUE TITLE
[BUG] Response status code does not indicate success

### ISSUE THREAD

**Issue by salehdub** [pizzaboxer/bloxstrap#2651]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

fix it pls

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> PLEASE READ THE PRELIMINARY INSTRUCTIONS BEFORE POSTING.

Please update to the latest version of Bloxstrap. (2.7.0)
