### ISSUE TITLE
[BUG] cant open roblox on 1 Specific acc

### ISSUE THREAD

**Issue by mBence55** [pizzaboxer/bloxstrap#2652]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I usually have around 5-6 accounts running, and every one of them works perfectly except for one. I had no problems with it until today, when I couldn't open any games.

This is the error it gives:
![image](https://github.com/user-attachments/assets/fb3911ac-dead-4abd-a955-a9b9f82e1016)

And it keeps loading like this for eternity until I close the error
![image](https://github.com/user-attachments/assets/f44b1f72-baac-43a2-a73a-0dae8dde4114)

**Comment by Roblox-Thot** [comment]
If you are not using bloxstrap v2.7.0 then you will have to update

Otherwise make sure to upload your log file here.
It should be the newest file in `%localappdata%\Bloxstrap\Logs`  after the error

**Comment by mBence55** [comment]
I want to use multiacc so I cant really update

**Comment by Roblox-Thot** [comment]
There isn't really any option to keep it with Bloxstrap

You will have to find something else that can do it sadly

**Comment by mBence55** [comment]
but why only 1 acc? the others work perfectly

**Comment by mBence55** [comment]
I dont really know python so could you please explain what should I do with this?

**Comment by mBence55** [comment]
sry

**Comment by mBence55** [comment]
I have another problem as well: I can't open the menu. I tried searching for it, but nothing comes up.

**Comment by ShadowCodeX-debug** [comment]
Open the Run dialog (WindowsKey + R) and type in the following: `"%localappdata%\Bloxstrap\Bloxstrap.exe" -menu`

**Comment by ShadowCodeX-debug** [comment]
(If you have Bloxstrap located somewhere else, use that path instead.)
