### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by systemdealer** [pizzaboxer/bloxstrap#2653]

**Comment by ShadowCodeX-debug** [comment]
> * [X] My answer given in the checkbox above is a lie.

> [!WARNING]
> PLEASE READ THE PRELIMINARY INSTRUCTIONS BEFORE POSTING.

Oh my FUCKING GOD.
# UPDATE YOUR FUCKING BLOXSTRAP
(Please.)

**Comment by Roblox-Thot** [comment]
💀 you didn't have to say it like that lmao

**Comment by ShadowCodeX-debug** [comment]
> 💀 you didn't have to say it like that lmao

I've had to say this to 18 other people now.

**Comment by Roblox-Thot** [comment]
lol I know i have issue notifs on so i see all them pop up
