### ISSUE TITLE
[BUG] " still trying to reinstall Bloxstrap"

### ISSUE THREAD

**Issue by alee14z** [pizzaboxer/bloxstrap#2655]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Hello, yesterday i try to reinstall roblox because i got error 403 and my main got banned for 1 day, when I tried to install bloxstrap I got the bug "Access to the path is denied" i tried deleting bloxstrap and reinstall but didn't work anyways. i tried to deleted bloxstrap and roblox folder but anyways didn't work.

( I already read the Wiki but I didn't find a solution for me.)

**LOG:**

[Bloxstrap_08_14_24.log](https://github.com/user-attachments/files/16614811/Bloxstrap_08_14_24.log)

**Comment by ShadowCodeX-debug** [comment]
I saw that Bloxstrap could find the Bloxstrap folder, did you move it?

**Comment by alee14z** [comment]
actually I deleted all the bloxstrap folders because im trying to reinstall it. (I think)

**Comment by ShadowCodeX-debug** [comment]
Umm idk...

@pizzaboxer mind helping this man?

**Comment by pizzaboxer** [comment]
Looks like an antivirus issue. Check to make sure it isn't interfering.

**Comment by alee14z** [comment]
the only way to use it is " run into administrator " but anyways bloxstrap still not working.

**Comment by alee14z** [comment]
isn't interfering the antivirus

**Comment by alee14z** [comment]
I also deleted bloxstrap from the same application to reinstall it, and for some reason the two direct access apps were created for "play roblox" and "bloxstrap menu" which tell me that I do not have permission on this device. something like that.
![image](https://github.com/user-attachments/assets/fb48b15f-ce7c-44f4-8c5f-6d675eb62dd4)
![image](https://github.com/user-attachments/assets/efcc0a74-88a7-454f-adb0-efe4948e89d9)

**Comment by alee14z** [comment]
![image](https://github.com/user-attachments/assets/3ad8e8ba-5aae-41db-ac5b-9a821be4f0b2)
im speak spanish so mb if my english is awful but I also got this message what basically said " Windows Cannot Access Specified Device Path or File You May Not Have Appropriate Permissions "

**Comment by pizzaboxer** [comment]
> the only way to use it is " run into administrator " but anyways bloxstrap still not working.

You definitely have an issue with your antivirus or some other system permissions if you're unable to install to the AppData folder without admin permissions. Not a problem on my side.
