### ISSUE TITLE
[BUG] recently uninstalled it and roblox wont start up

### ISSUE THREAD

**Issue by D3ANZZ** [pizzaboxer/bloxstrap#2656]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

cant open roblox ever since i uninstalled bloxstrap

**Comment by Roblox-Thot** [comment]
Dumb question but have you tried to reinstall normal Roblox after uninstalling bloxstrap?

**Comment by pizzaboxer** [comment]
I can assure you there's no correlation between those two events. This issue isn't on our side. There isn't anything I can do about this.
