### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by breporter** [pizzaboxer/bloxstrap#2659]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

just trying to join a game, and that pops up... it usually gives me the error 403 but I just re open my browser but now that doesn't work...

**Comment by bluepilledgreat** [comment]
Update your Bloxstrap. We do not support older versions of Bloxstrap.

**Comment by d44df016fe28bc8d5974** [comment]
to fix 403 in 2.5.4 enable ohhey
%localappdata%\Bloxstrap\settings.json and set Ohheyyoufoundme to true
then open the bloxstrap menu and go to behaviour
change channel to live and automatic channel change action to never change
don't update if you dont want to
