### ISSUE TITLE
[BUG] Error while opening bloxstrap

### ISSUE THREAD

**Issue by mczjb** [pizzaboxer/bloxstrap#2660]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Ok so I am having the same issues as another post BUT his fix didnt fix mine as bloxstrap is not showing up in control panel. I also renamed my user file. 
https://github.com/pizzaboxer/bloxstrap/issues/2528#issue-2438685941
![image](https://github.com/user-attachments/assets/e69aafae-2a9e-4d23-86a7-e51cdfe5be99)

**Comment by pizzaboxer** [comment]
Read the Wiki. https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-stops-working-after-renaming-the-user-profile-folder
