### ISSUE TITLE
[BUG] Nvidia screwing up the menu

### ISSUE THREAD

**Issue by ToxicTDX** [pizzaboxer/bloxstrap#2661]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever I open the Bloxstrap menu, the 
![image](https://github.com/user-attachments/assets/d0876256-2682-4010-89d8-5ccf3fee6b45)
nvidia overlay thing thinks it is Roblox that has opened, and starts to screw up the menu.

Sometimes, it even just starts to become a yellow and orange mess. Tried reinstalling, didnt do anything. And ive noticed more frequent fps drops in-game. Any help?

CPU: Intel 14th generation 14650HX Core i7
GPU: RTX 4060 Laptop GPU

**Comment by ToxicTDX** [comment]
![image](https://github.com/user-attachments/assets/87710f78-6b27-4ca4-9622-2dc4e0f4798e)
it also starts to ramp up my gpu lol

**Comment by ShadowCodeX-debug** [comment]
Find settings relating to performance, power, etc. if Bloxstrap is in it then remove it or set it to a lower level.

**Comment by ToxicTDX** [comment]
> Find settings relating to performance, power, etc. if Bloxstrap is in it then remove it or set it to a lower level.

Ive set the settings in NVidia control panel to Roblox game client for it to use more DGPU, but I doubt that has to do something with the menu itself?

**Comment by ToxicTDX** [comment]
![image](https://github.com/user-attachments/assets/487a7492-46df-43cc-8c5e-76a2a98aae4e)
its starting to show the fps in getting in the bloxstrap menu 💀

**Comment by ToxicTDX** [comment]
![image](https://github.com/user-attachments/assets/e34cd018-2e05-4848-9d27-e83f5acfece6)
theree it is

**Comment by pizzaboxer** [comment]
I'm not sure what you want me to do about this. Since you're the only person in existence having this issue as far as I'm concerned, you configured something in the Nvidia control panel that ended up causing this. You'll have to find out what it is.

**Comment by ToxicTDX** [comment]
possibly its because i did this?? I did it just to improve the use of dgpu in Roblox. I dont really know how this would affect roblox if it clearly states robloxbetaplayer.exe 
![image](https://github.com/user-attachments/assets/c154aff1-8112-46da-9636-6e57e3129e18)
I mean i dont think this would bring any issues.

**Comment by xonthur** [comment]
i have the same issue and i noticed that my roblox is also labeled vr, maybe thats why
