### ISSUE TITLE
[BUG] the fabled unable to download.

### ISSUE THREAD

**Issue by alepalex** [pizzaboxer/bloxstrap#2663]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

the 2nd checkbox is true. anyway, i cant download rauh

**Comment by pizzaboxer** [comment]
The help page it told you to read specifically told you not to open an issue for this. Thank you for somehow ignoring the information I told you.

**Comment by alepalex** [comment]
thing is, i did as instructed. buteven when i restarted it refused
