### ISSUE TITLE
[BUG] Error 403 on launching

### ISSUE THREAD

**Issue by baget-underscore** [pizzaboxer/bloxstrap#2665]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Tried to launch the game, but the BloxStrap launch crashed before the roblox app even started.
Playing Roblox works fine if I don't use BloxStrap.

[Bloxstrap_20240815T181424Z.log](https://github.com/user-attachments/files/16628616/Bloxstrap_20240815T181424Z.log)

**Comment by Roblox-Thot** [comment]
Bloxstrap v2.5.4 is not supported, you _**have**_ to update to the newest version (v2.7.0)

**Comment by baget-underscore** [comment]
Aw alright, thanks.
