### ISSUE TITLE
[BUG]"An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by arnVR** [pizzaboxer/bloxstrap#2668]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

"An exception occurred while running bloxstrap"

System.Net.HttpRequestException: response status code does not indicate success: 403 (forbidden).

[Bloxstrap_20240815T225346Z.log](https://github.com/user-attachments/files/16631019/Bloxstrap_20240815T225346Z.log)

here's the log

**Comment by toofastforboo** [comment]
Update your bloxstrap to the latest version
https://bloxstrap.pizzaboxer.xyz/
