### ISSUE TITLE
[REQ] Add a toggle to get back the old topbar menu pre-2020

### ISSUE THREAD

**Issue by rayhanXD-hash** [pizzaboxer/bloxstrap#2669]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Something like this I hope? 
![image](https://github.com/user-attachments/assets/5872f357-2d1b-4f13-b1c5-a7b994b2c6e0)

**Comment by Hunterk1241** [comment]
I am unsure if this is possible because there doesn't seem to be any Fast Flags that can do this

**Comment by KlothoTheDev** [comment]
it could be possible if we modify the Topbar files
