### ISSUE TITLE
Roblox Crashing When Window Minimized

### ISSUE THREAD

**Issue by ST1NGERRR** [pizzaboxer/bloxstrap#267]
everytime i minimize a window to do something else, like watch yt or look something up, my roblox crashes.... any fixes?

**Comment by ST1NGERRR** [comment]
also it crashes when i close roblox too

**Comment by pizzaboxer** [comment]
Take a look at the Wiki first before opening an issue. https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-crashes
