### ISSUE TITLE
[BUG] problem when downloading

### ISSUE THREAD

**Issue by ruckusello** [pizzaboxer/bloxstrap#2672]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when i download bloxstrap it just comes up with jibberish and dosnt let me open it either 

![Screenshot 2024-08-16 180052](https://github.com/user-attachments/assets/4ef6be9e-92e9-4bdf-bc7f-6f9a18a66ff4)

i do also have windows desktop runtime downloaded as well

**Comment by bluepilledgreat** [comment]
Seems like your browser completely ignored the file name and named it something random. Try adding a .exe extension to the end of the file.

**Comment by ruckusello** [comment]
sorry didnt realized u replyed back, im guessing what u mean by that is when renaming it .exe at the end i did and it did not work and still cant open it but if u mean adding .exe at the end in a differant way then renamining it pls say and ill try it

**Comment by pizzaboxer** [comment]
> when i download bloxstrap it just comes up with jibberish and dosnt let me open it either

This is because your web browser isn't finishing the download. What web browser are you using and what's the status of the download?

**Comment by ruckusello** [comment]
I'm useing google chrome and when I check it, it just says the download is
done

**Comment by ruckusello** [comment]
Using*

**Comment by pizzaboxer** [comment]
And what happens if you open it from inside Google Chrome?

**Comment by ruckusello** [comment]
right i dk what happened but all of a sudden it fixed it self while i was away doing stuff and now it works 
![image](https://github.com/user-attachments/assets/6cadbd54-9c23-434b-929f-b0b073b8d812)

**Comment by ruckusello** [comment]
that wasnt becuase i opened it inside google chrome because normaly nothing would happen i just had my files left open from before and saw the name and clicked on it
