### ISSUE TITLE
[BUG] Cannot find the button to turn on Multiple Roblox Instances

### ISSUE THREAD

**Issue by MalwareMason** [pizzaboxer/bloxstrap#2674]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I've been using the Multiple Roblox Instances a lot to test my game on multiple accounts at once and all of a sudden it randomly stopped working. The button that let me turn on/off the feature is gone. Any help? :(

**Comment by toofastforboo** [comment]
was completely removed but it was warned to happen months before

**Comment by MalwareMason** [comment]
> was completely removed but it was warned to happen months before

oh alright, i dont really keep up with all the news i just downloaded it for certain stuff. is there any other way to get multiple roblox instances?? i saw this one where you have to like input ids of games and it loads in and its a lot more complicated then how bloxstrap just let you have multiple open at the same time
