### ISSUE TITLE
[BUG] it is giving me this error when i try to launch System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by maieo2010** [pizzaboxer/bloxstrap#2675]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

it is not letting me launch roblox

**Comment by maieo2010** [comment]
nvm i fixed it by myself

**Comment by IncrediDev** [comment]
> nvm i fixed it by myself

How?

**Comment by ImGreyCat** [comment]
> > nvm i fixed it by myself
> 
> How? I have the same issue

> [!IMPORTANT]
> Read this wiki page
> https://github.com/pizzaboxer/bloxstrap/wiki/403-(Forbidden)-error-when-launching-Roblox
