### ISSUE TITLE
Bloxstrap installer bug

### ISSUE THREAD

**Issue by lilondc** [pizzaboxer/bloxstrap#2676]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So I recently factory reset my pc. When I first got my pc there was a bug with Roblox that would automatically close the installer after being ran. So I resorted to Bloxstrap's force installation which worked. But ever since I factory reset my pc Bloxstrap has been having the same issue Roblox had (closing the installer after being ran). I went to the discord server for help but I did not get the bug fixed there. 

The file I want to attach is to big for github. The file I will attach is me running Bloxstrap as an admin (recommended from the discord server). The file that is too big is the whole process of me installing Bloxstrap. 

https://github.com/user-attachments/assets/5c8eea54-340f-4f28-8e3e-ece76ad09e94

**Comment by Naveandice** [comment]
> [!IMPORTANT]
> Issue resolved on Discord [(post)](https://discord.com/channels/1099468797410283540/1274163553464488021)
