### ISSUE TITLE
[BUG] helpppp

### ISSUE THREAD

**Issue by Musooo233** [pizzaboxer/bloxstrap#2677]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Joining into roblox, i get about 120 fps, BUT after playing like 1-4 minutes the fps unlocker stops working and the max frame rate goes to 60 which makes my game bad.

**Comment by Musooo233** [comment]
OK, hopefully this comment works.

**Comment by pizzaboxer** [comment]
That sounds like your PC is limiting your performance, and not an issue with Bloxstrap.
