### ISSUE TITLE
bloxstrap erorr 403

### ISSUE THREAD

**Issue by amabtukaammm** [pizzaboxer/bloxstrap#268]
when i open bloxstrap it gives error 403 i reset my computer but it's still like this
![Ekran görüntüsü 2023-05-27 175022](https://github.com/pizzaboxer/bloxstrap/assets/134792848/16bc3c58-8d02-4205-a6d0-6ac3b8e873a6)

**Comment by pizzaboxer** [comment]
Can I take a look at the log file? You can find the logs folder at `%localappdata%\Bloxstrap\Logs` if you already have it installed, or in `%temp%` if you're trying to install it.

**Comment by amabtukaammm** [comment]
> Günlük dosyasına bakabilir miyim? `%localappdata%\Bloxstrap\Logs`Zaten yüklediyseniz günlükler klasörünü adresinde veya `%temp%`yüklemeye çalışıyorsanız içinde bulabilirsiniz .

![Ekran görüntüsü 2023-05-27 182543](https://github.com/pizzaboxer/bloxstrap/assets/134792848/73c8c072-5b55-48be-9a51-f77ca5f0718d)

**Comment by pizzaboxer** [comment]
Send the file here.

**Comment by amabtukaammm** [comment]
![Uploading Ekran görüntüsü 2023-05-27 182543.png…]()

**Comment by pizzaboxer** [comment]
You didn't upload it correctly, and you were trying to upload an image.

**Comment by pizzaboxer** [comment]
That's still an image. Upload the entire file itself here.

**Comment by amabtukaammm** [comment]
[Bloxstrap_20230527T145008Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582435/Bloxstrap_20230527T145008Z.log)
[Bloxstrap_20230527T143823Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582436/Bloxstrap_20230527T143823Z.log)
[Bloxstrap_20230527T142304Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582438/Bloxstrap_20230527T142304Z.log)
[Bloxstrap_20230527T141823Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582439/Bloxstrap_20230527T141823Z.log)
[Bloxstrap_20230527T142133Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582440/Bloxstrap_20230527T142133Z.log)

**Comment by pizzaboxer** [comment]
I'm struggling to reproduce this, so let me try and get some more info. Download and run this version, and when it errors again, get the latest log file again.

files.pizzaboxer.xyz/bloxstrap-debug/268/Bloxstrap.exe

**Comment by amabtukaammm** [comment]
same 
![Ekran görüntüsü 2023-05-27 193740](https://github.com/pizzaboxer/bloxstrap/assets/134792848/c077dcb4-2337-4222-8639-833121fd6a08)

**Comment by amabtukaammm** [comment]
![Ekran görüntüsü 2023-05-27 193937](https://github.com/pizzaboxer/bloxstrap/assets/134792848/cb8da8eb-724d-4b7e-b80b-6caed0566f97)

**Comment by pizzaboxer** [comment]
Send the file itself. Don't send screenshots of the file.

**Comment by amabtukaammm** [comment]
[Bloxstrap_20230527T163703Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582616/Bloxstrap_20230527T163703Z.log)

**Comment by pizzaboxer** [comment]
Okay, try this one out and see if it works.

https://files.pizzaboxer.xyz/bloxstrap-debug/268/Bloxstrap.1.exe

If it works, then replace your currently installed version with this one. You can do that by replacing `Bloxstrap.exe` that's located in `%localappdata%\Bloxstrap`.

**Comment by amabtukaammm** [comment]
çok teşekkür ederim

**Comment by amabtukaammm** [comment]
d

**Comment by pizzaboxer** [comment]
> Ive been trying to get around 4 roblox tabs open at the same time but i constantly get this error code when roblox through chrome, if i try multible tabs on the roblox app it just closes the other. any fix to this code ](url)

That error is talking about something completely different to what this thread was talking about. That only happens if the Roblox app has difficulty authenticating you from a web launch, which since you're trying to launch multiple instances, that seems to be expected.

If you've enabled multi-instance launching with Bloxstrap, then new instances of the Roblox app shouldn't close older ones.

**Comment by PANDaz0427** [comment]
didnt mean to comment on this post but my issue is that i have it turned on and still causes this

**Comment by PANDaz0427** [comment]
should i launch roblox thorugh microsoft?

**Comment by madman9996** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/144431676/3be9465b-adad-49d4-a728-8ee9e018d1b2)
Getting errors and need help

**Comment by madman9996** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/144431676/644fb753-2745-4f8a-a90f-1c7596fdd63c)
I need help with this
