### ISSUE TITLE
[BUG] Every single icon is placed randomly

### ISSUE THREAD

**Issue by XimKa123** [pizzaboxer/bloxstrap#2680]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/3cf30ba5-8e4c-473a-8bf1-80c02421735b)

**Comment by bluepilledgreat** [comment]
One of your mods has an outdated image atlas.
