### ISSUE TITLE
[BUG] Blurry/Pixelated UI

### ISSUE THREAD

**Issue by Brixy2005** [pizzaboxer/bloxstrap#2681]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![Screenshot 2024-08-17 080301](https://github.com/user-attachments/assets/dc7ee53f-5df8-4a8b-a502-1989f73ac00e)
When launching blockstrap for the first time, i noticed that the ui was pixelated. I Relaunched it only for it to do nothing. Other than that. the program was great.

**Comment by bluepilledgreat** [comment]
Remove all your fast flags.

**Comment by Brixy2005** [comment]
Ty that worked, but is there any way to keep my fast flags?
