### ISSUE TITLE
[BUG] When I join the game on browser the game starts to crash but when i do on app it launches

### ISSUE THREAD

**Issue by C1TY17** [pizzaboxer/bloxstrap#2682]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Everytime when i join on app it always crashes but when i join on blosxstrap 2.7.0 on exe it works fine and it launches, of course on browser it will appear for me but it will stop the CPU usage and set it to 0%. so can anyone tell me why is this happen (tested on: firefox, opera gx, chrome and edge). Reinstalling Roblox and Bloxstrap Doesnt work (even when deleting the files after uninstall before the reinstallation doesnt work) when this issue began? two day ago and does it runs it fine without bloxstrap, it does fine without bloxstrap so this is very strange to me
![image](https://github.com/user-attachments/assets/a3ff7e84-4652-47c6-af65-7f3200f73158)

**Comment by ImGreyCat** [comment]
Please check that this problem hasn't been addressed before, as you stated that you did not.

**Comment by C1TY17** [comment]
where

**Comment by C1TY17** [comment]
i already checked it a hour ago and it didnt helped me

**Comment by ImGreyCat** [comment]
Okay, mind attaching your Bloxstrap "settings.json" file here?
It's located in %LocalAppData%\Bloxstrap.

**Comment by C1TY17** [comment]
[Settings.json](https://github.com/user-attachments/files/16645990/Settings.json)

**Comment by ImGreyCat** [comment]
Your settings seem to be fine, try to delete all contents of the Logs folder (%LocalAppData%\Bloxstrap\Logs) and join any game from your browser, after that attach your log file. It should be called something like Bloxstrap_20240817T..... .log

**Comment by C1TY17** [comment]
all logs have been deleted, im going to start testing

**Comment by C1TY17** [comment]
firefox: 
[Bloxstrap_20240817T183120Z.log](https://github.com/user-attachments/files/16646038/Bloxstrap_20240817T183120Z.log)

**Comment by ImGreyCat** [comment]
Your Bloxstrap version is pretty outdated, maybe you should update it

**Comment by C1TY17** [comment]
okay

**Comment by C1TY17** [comment]
[Bloxstrap_20240817T183922Z.log](https://github.com/user-attachments/files/16646096/Bloxstrap_20240817T183922Z.log)

**Comment by C1TY17** [comment]
this is 2.7.0 version

**Comment by ImGreyCat** [comment]
Yeah, but I have 2.8.0 which is the latest

**Comment by ImGreyCat** [comment]
Nevermind my logs just falsely said that, the 2.7.0 is actually the latest one, sorry
Back to the bug, can you try removing your Roblox folder (%localappdata%\Roblox) and joining the game like normal through Bloxstrap and send me the log again? It doesn't matter which browser you use, though

**Comment by C1TY17** [comment]
this file is important for roblox game app

**Comment by ImGreyCat** [comment]
Don't worry, you can delete it anyways. Bloxstrap will take care of it and will download a fresh installation of Roblox.
Also close your Roblox game before doing that.

**Comment by C1TY17** [comment]
"Force Roblox Installation" is enabled

**Comment by ImGreyCat** [comment]
No, turn it off, you can just delete the Roblox folder and it will install 100% fresh that way

**Comment by C1TY17** [comment]
![image](https://github.com/user-attachments/assets/c203a89b-d3f1-439d-9820-5c3f08d7199d)

**Comment by C1TY17** [comment]
look what we found, it setted to suspended

**Comment by ImGreyCat** [comment]
Now there's another question, what antivirus do you use?

**Comment by C1TY17** [comment]
Driver Easy 6.1.0, Gality Utilites 6.13

**Comment by C1TY17** [comment]
wait a minute
let me try to open resource montior

**Comment by C1TY17** [comment]
![image](https://github.com/user-attachments/assets/42641255-6470-490d-adcf-b600b5540e13)

**Comment by ImGreyCat** [comment]
Alright then, you can also try going to %localappdata%\Roblox\versions and then selecting the newest version in the list, and then launching RobloxPlayerBeta.exe from there. It seems to help a lot of people.

**Comment by C1TY17** [comment]
"versions" isnt listed on foldier

**Comment by C1TY17** [comment]
it used to be but its gone because you told me to delete it

**Comment by C1TY17** [comment]
"try removing your Roblox folder (%localappdata%\Roblox) and joining the game like normal through Bloxstrap"

**Comment by ImGreyCat** [comment]
Alright, then press Windows+S keys on your keyboard and type Play Roblox, the Bloxstrap icon should appear. Launch it. It will install Roblox back.

**Comment by C1TY17** [comment]
it froze again

**Comment by ImGreyCat** [comment]
Try to remove Bloxstrap, installing Roblox and installing Bloxstrap back after

**Comment by C1TY17** [comment]
okay reinstalled completed, clicked on "RobloxPlayerBeta.exe" and it reverted me to roblox version instead of bloxstrap version

**Comment by C1TY17** [comment]
oh, i forgot to enable one setting to verify

**Comment by C1TY17** [comment]
retesting

**Comment by ImGreyCat** [comment]
🤦‍♂️ i said for you to not reinstall bloxstrap yet

**Comment by C1TY17** [comment]
OHHHHH, okay

**Comment by C1TY17** [comment]
also i tested it with one enable setting and it reverted me back to roblox version

**Comment by C1TY17** [comment]
okay installed roblox only not bloxstrap yet

**Comment by C1TY17** [comment]
now what

**Comment by ImGreyCat** [comment]
First, try launching Roblox from browser like normal.
And please don't talk 2 words a comment

**Comment by C1TY17** [comment]
launching on roblox in browser works fine, doesnt set cpu usage to 0% and it doesnt suspended at all

**Comment by ImGreyCat** [comment]
Okay, now try installing Bloxstrap again. Don't try to be quick, read everything carefully.

**Comment by C1TY17** [comment]
Heres my settings, Check if i enabled one setting that causes a issue
Integrations:
![image](https://github.com/user-attachments/assets/da081238-89cb-42bc-9525-e974b9d6655b)
Mods:
![image](https://github.com/user-attachments/assets/b8c1f6be-ea5f-4cba-9943-1e3219b7cdc4)
Fastflag:
![image](https://github.com/user-attachments/assets/03441dcf-1ffc-4d4e-975e-97c94b757455)
![image](https://github.com/user-attachments/assets/36ec2a76-92ca-4b1a-a26c-d1062c9a0be4)
Fastflag Editor:
![image](https://github.com/user-attachments/assets/3a1e9f14-1bff-47d3-931a-c7c79887852a)
Appearnce:
![image](https://github.com/user-attachments/assets/cd68216a-a41a-4592-86f0-04a8253d6823)
Behaviour:
![image](https://github.com/user-attachments/assets/317242d4-7f6c-41e8-bf46-214f4b1ffbbb)
Installation:
![image](https://github.com/user-attachments/assets/ab75f80b-09ab-42f9-a98c-06379afb1490)

**Comment by C1TY17** [comment]
btw for the light mode i setted it to automatic, if you wounder why i set it to voxel, i accidentally scroll it without noticing it

**Comment by ImGreyCat** [comment]
Try disabling this option
Allow Bloxstrap to manage Fast Flags
and launching your game

**Comment by C1TY17** [comment]
"Allow Bloxstrap to manage Fast Flags" is disabled
installing started to being

**Comment by C1TY17** [comment]
![image](https://github.com/user-attachments/assets/ef31c17a-7805-4216-9293-bb3fa488824d)

**Comment by C1TY17** [comment]
also i noticed something, when the game is loaded, roblox starts to set it to suspended

**Comment by ImGreyCat** [comment]
Okay.. Someone just had a similar issue, here's the link to a post in Discord. Read through it, it should help.

**Comment by ImGreyCat** [comment]
https://github.com/pizzaboxer/bloxstrap/issues/2676#issuecomment-2294954770

**Comment by C1TY17** [comment]
this issue has to do with anti-cheat software, so im going back to roblox version so goodbye yall

**Comment by C1TY17** [comment]
issue has been fixed
