### ISSUE TITLE
[REQ] Can FFlags change topbar transparency?

### ISSUE THREAD

**Issue by dragonmertpro** [pizzaboxer/bloxstrap#2683]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

idk if FFlags can change topbar transparency, can anyone help me?
![download](https://github.com/user-attachments/assets/334a8cef-1cab-44ec-bcc1-7e3b3bfbedc4)

**Comment by pizzaboxer** [comment]
No
