### ISSUE TITLE
[REQ] Can you remove the dependency on the bloxstrap group

### ISSUE THREAD

**Issue by pavel355** [pizzaboxer/bloxstrap#2685]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Remove the dependency on the bloxstrap group

**Comment by pavel355** [comment]
because i want to have a clean profile

**Comment by pizzaboxer** [comment]
You need a dependency on ***a*** group. By default we make it depend on the Bloxstrap group for convenience. You can make it depend on your own group by going into the flag editor and changing the group ID there. You also would've found out this information had you read the wiki information about it.
