### ISSUE TITLE
[BUG] Microphone for Voice Chat is Hidden via Bloxstrap

### ISSUE THREAD

**Issue by KokumaMK1** [pizzaboxer/bloxstrap#2686]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Recently I've noticed that while using Bloxstrap, the ability to use Voicechat (Specifically: The Microphone) isn't available for me. I'm unable to actually use my microphone however I'm able to hear everybody normally,  I have checked my settings and it shows that my microphone is enabled
![image](https://github.com/user-attachments/assets/20fd3626-1bab-4568-8459-afc11e78aa63)

However when i'm ingame i am given no option to unmute (and presumably use my camera too). in fact in the menu my microphone is "turned off" 
![image](https://github.com/user-attachments/assets/906b39b2-bb31-4784-a3e6-c749a2a8c869)

However when i open up vanilla roblox, the issue is nonexistent so i'm unsure what the problem could be on bloxstraps end.
![image](https://github.com/user-attachments/assets/07eaa92c-3470-4c92-aa06-27b072133464)

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by KokumaMK1** [comment]
[Settings.json](https://github.com/user-attachments/files/16719781/Settings.json)

[State.json](https://github.com/user-attachments/files/16719785/State.json)

[ClientAppSettings.json](https://github.com/user-attachments/files/16719786/ClientAppSettings.json)

**Comment by pizzaboxer** [comment]
Try setting your preferred escap menu version to default, see if that changes anything.

**Comment by KokumaMK1** [comment]
Problem has been resolved with default & every other escape menu version, but persists with 2023 (V4 + New UI)

**Comment by pizzaboxer** [comment]
Does the Chrome UI not let you set your VC status in the topbar while the menu is closed?

**Comment by KokumaMK1** [comment]
![image_2024-08-22_190812395](https://github.com/user-attachments/assets/ab31f2bf-4bfe-4ea4-8c85-c6a042024e00)

 No, The V4 + New UI escape menu is the only one that hides my VC status in the topbar of my avatar. it completely deactivates my usage to VC whenever it's used.

**Comment by pizzaboxer** [comment]
These options don't show for you at all?

![image](https://github.com/user-attachments/assets/a9416a4f-797f-4b92-802d-530c6c58d7e0)

**Comment by KokumaMK1** [comment]
Yes, Looking back i'm unsure if this was here the whole time and i wasn't observant. I apologize for any inconvenience if this was the case.
