### ISSUE TITLE
roblox not opening

### ISSUE THREAD

**Issue by cuse02** [pizzaboxer/bloxstrap#2688]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

I open bloxstrap and nothing happens after it says Starting Roblox, it disappears and the logs just say, System.InvalidOperationException: Cannot start process because a file name has not been provided.

**Comment by pizzaboxer** [comment]
Read the Wiki
