### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by admim1234** [pizzaboxer/bloxstrap#2689]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by bluepilledgreat** [comment]
Update to the latest version. You are using a version that is nearly a year old now.
