### ISSUE TITLE
bloxstrap not installing

### ISSUE THREAD

**Issue by ihad11cats** [pizzaboxer/bloxstrap#269]
roblox wasnt working with bloxstrap so i reinstalled it multiple times and it didnt work like its stuck on the "please wait" stage and it dosent load  or do anything

**Comment by pizzaboxer** [comment]
Can I please take a look at the log file? You can find it located in `%temp%`. Get the latest file that begins with "Bloxstrap_" in the filename and send it here.

**Comment by ihad11cats** [comment]
[Bloxstrap_20230527T174444Z.log](https://github.com/pizzaboxer/bloxstrap/files/11582707/Bloxstrap_20230527T174444Z.log)
this is the newest one

**Comment by ihad11cats** [comment]
oh wait nevermind now it works i just had to restart my pc

**Comment by pizzaboxer** [comment]
> oh wait nevermind now it works i just had to restart my pc

Yeah, seems about right. Are you sure there was no instance running in the background or anything?

**Comment by ihad11cats** [comment]
i am not sure when i turned off my pc the only thing that stopping it was somthing with steam

**Comment by ihad11cats** [comment]
i am not sure when i restart my pc the only thing that was it stopping it from restarting was somthing with steam

**Comment by pizzaboxer** [comment]
Well, I don't really expect this to happen again.
