### ISSUE TITLE
[BUG] fps unlocker not working in roblox neither bloxtrap

### ISSUE THREAD

**Issue by bioniceast** [pizzaboxer/bloxstrap#2690]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

fps staying at 60 fps, i tried everything thats here, [FPS issues](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter), nothing worked.

**Comment by pizzaboxer** [comment]
Your system is limiting you externally in some way. This is for Bloxstrap specific issues only, please don't ask here.
