### ISSUE TITLE
bloxstrap "System.NullReferenceException: Object reference not set to an instance of an object" issue

### ISSUE THREAD

**Issue by jjsxvv** [pizzaboxer/bloxstrap#2691]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i was trying to paste a fast flag from an admin from a server. when i pasted the fast flag, an error showed up saying "An exception has occured while running bloxstrap." and then, the other words "System.NullReferenceException: Object reference not set to an instance of an object". i really want to fix this as i think i cannot paste anymore fflags with the bug on

**Comment by bluepilledgreat** [comment]
Can you send your Bloxstrap log file.

**Comment by jjsxvv** [comment]
sorry for the inconvenience, hours after i sent the email i manage to talk
to the guy who made the list and fix it.

sorry!

**Comment by bluepilledgreat** [comment]
Can you still send your log file? This is a bug with Bloxstrap.

**Comment by pizzaboxer** [comment]
Duplicate of #2468

I also advise that you don't use whatever list this guy gave you.
