### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by BlazingPheonix84** [pizzaboxer/bloxstrap#2693]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Good evening, 

I have just came across an exception error for bloxstrap. Attached below is the report I received regarding this error:

[Bloxstrap_20240820T001909Z.log](https://github.com/user-attachments/files/16667114/Bloxstrap_20240820T001909Z.log)

(Also if I don't respond, I might be heading to bed, because I've had a long day - if this is the case I'll respond as soon as possible! Many Thanks!)

**Comment by toofastforboo** [comment]
you just need to update your bloxstrap to the latest version (2.7.0 atm) and the error will be gone
download it through the releases page [here](https://github.com/pizzaboxer/bloxstrap/releases)
Also, if you're using that version for multiple instances, it got removed, but you can use Roblox Account Manager instead.

**Comment by mxcaqiz** [comment]
> you just need to update your bloxstrap to the latest version (2.7.0 atm) and the error will be gone download it through the releases page [here](https://github.com/pizzaboxer/bloxstrap/releases) Also, if you're using that version for multiple instances, it got removed, but you can use Roblox Account Manager instead.

I wanted to ask, Would Roblox Account Manager be safe to use? apparently it has malware on it, which is why I use bloxstraps multi instance running

**Comment by toofastforboo** [comment]
No, there's no malware or similar on it. You can install without worries
