### ISSUE TITLE
[BUG] Why i can't put the code/script into the Export JSON?

### ISSUE THREAD

**Issue by boblox69** [pizzaboxer/bloxstrap#2696]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

plz help

**Comment by Storm-930** [comment]
my face when "My answer given in the checkbox above is a lie"
_seriously man_

**Comment by Storm-930** [comment]
what i want you to do is the following:
- next time you open an issue, _read the preliminary instructions to make sure the bug is NOT known_
- when you do open one, _actually explain your issue, instead of saying "plz help"_
- next time this topic is brought up, call them FastFlags (or FFlags for short), _not "codes" or "scripts"_

**Comment by Storm-930** [comment]
actual solution to the issue
when you export your flag list as a JSON, it gets put on your clipboard, hold the Start button, and press V to see it, _if you for some reason that not even God knows, you have it disabled, please, for the sake of us, enable it_
if it is enabled, you can click it while a text box is selected to paste it in there, here's an example list with my personal FFlag choice
```
{
  "FFlagRenderCheckThreading": "True",
  "FLogNetwork": "7",
  "DFIntDebugFRMQualityLevelOverride": "2",
  "FFlagDebugGraphicsDisableVulkan": "False",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "FFlagDebugGraphicsDisableVulkan11": "True",
  "FFlagDebugGraphicsPreferVulkan": "True",
  "FFlagRenderVulkanFixMinimizeWindow": "True",
  "FFlagEnableBetterHapticsResultHandling": "True"
}
```

**Comment by pizzaboxer** [comment]
Issue will be reopened once clearer, more helpful details are given
