### ISSUE TITLE
Headset disconnected error everytime I try to use VR

### ISSUE THREAD

**Issue by RioluMax** [pizzaboxer/bloxstrap#270]
Since I installed Bloxstrap, anytime I try to play any game on VR mode, I immediately seem to get this error message, no matter what I do.
![image](https://github.com/pizzaboxer/bloxstrap/assets/29956871/4eb58ee5-e25f-488b-9abf-ec71ac5dad52)

**Comment by RioluMax** [comment]
I reinstalled Bloxstrap, and the problem seems to have fixed itself, but this time I renamed it to Roblox, instead of Bitchstrap. Maybe that might be the issue?

**Comment by pizzaboxer** [comment]
> but this time I renamed it to Roblox
What did you rename? The exe file before installing it?
