### ISSUE TITLE
[BUG] [HttpClientLoggingHandler::ProcessResponse] 403 Forbidden https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt

### ISSUE THREAD

**Issue by pompompur1nn** [pizzaboxer/bloxstrap#2703]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

403 forbidden whilst launching client on latest version.
[Bloxstrap_20240821T204845Z.log](https://github.com/user-attachments/files/16698620/Bloxstrap_20240821T204845Z.log)

**Comment by k-awn** [comment]
[Bloxstrap_20240821T205115Z.log](https://github.com/user-attachments/files/16698641/Bloxstrap_20240821T205115Z.log)
this my log

**Comment by SoyToni** [comment]
Happens to me too, it probably has something to do with roblox updating, since its wednesday

**Comment by pompompur1nn** [comment]
issue: https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt is a aws xml blank page

**Comment by bluepilledgreat** [comment]
The API does not respond with version-f0223159583b4054, I am confused on why it's trying to request version-f0223159583b4054.

**Comment by bluepilledgreat** [comment]
This seems to have been an issue with today's Roblox deployment.
