### ISSUE TITLE
System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by happyfnl** [pizzaboxer/bloxstrap#2704]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by k-awn** [comment]
[Bloxstrap_20240821T205115Z.log](https://github.com/user-attachments/files/16698641/Bloxstrap_20240821T205115Z.log)
this my log

**Comment by pizzaboxer** [comment]
This was a bug on Roblox's side which has been fixed now.
