### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Art221999** [pizzaboxer/bloxstrap#2705]
BloxStrap App isn't working when I try to open Roblox thru the Website. It's saying the thing in the link below help pls or do I reinstall BloxStrap?

[Bloxstrap_20240821T204636Z.log](https://github.com/user-attachments/files/16698632/Bloxstrap_20240821T204636Z.log)

**Comment by pompompur1nn** [comment]
same issue

**Comment by k-awn** [comment]
[Bloxstrap_20240821T205115Z.log](https://github.com/user-attachments/files/16698641/Bloxstrap_20240821T205115Z.log)
this my log

**Comment by xxtroop** [comment]
same cuh defo roblox doing sum

**Comment by Alphashrimp** [comment]
same
