### ISSUE TITLE
Bloxstrap Exception?

### ISSUE THREAD

**Issue by EpikDudee** [pizzaboxer/bloxstrap#2706]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] My answer given in the checkbox above is a lie.

### What problem did you encounter?

idk what does this mean but.. it says this:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
it said that there is an exception?

**Comment by EpikDudee** [comment]
is there any way to fix this?

**Comment by pompompur1nn** [comment]
same issue, https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt got cooked

**Comment by pompompur1nn** [comment]
no there is no way to fix it until bloxstrap updates

**Comment by EpikDudee** [comment]
oh damn, that was a fast reply

**Comment by k-awn** [comment]
there are already ten gazillion commnts everyone uses bloxstrap ig

**Comment by EpikDudee** [comment]
i guess we have to wait then

**Comment by EpikDudee** [comment]
update: bloxstrap is back

**Comment by pizzaboxer** [comment]
Duplicate of #2704
