### ISSUE TITLE
[BUG] bloxstrap won't let me play roblox

### ISSUE THREAD

**Issue by s0aperstartheyellow** [pizzaboxer/bloxstrap#2707]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

bloxstrap how do i fix this
![nooooo](https://github.com/user-attachments/assets/870c8240-9605-4fe7-9146-069d4be9df02)

**Comment by k-awn** [comment]
shut up

**Comment by s0aperstartheyellow** [comment]
what did i do???

**Comment by pompompur1nn** [comment]
https://setup.rbxcdn.com/channel/common/version-f0223159583b4054-rbxPkgManifest.txt got cooked

**Comment by s0aperstartheyellow** [comment]
??

**Comment by s0aperstartheyellow** [comment]
how do i fix it

**Comment by DiddypartyEnjoyer** [comment]
idk lol

**Comment by s0aperstartheyellow** [comment]
bruhh how do ur guyses bloxstraps work then???

**Comment by DiddypartyEnjoyer** [comment]
who said my bloxstrap works

**Comment by s0aperstartheyellow** [comment]
oh

**Comment by Abyxal** [comment]
I was playing fine awhile ago, then all of a sudden I can't play no more cause of this error message. It's told me to upgrade my bloxstrap but I'm already on the latest one.

**Comment by s0aperstartheyellow** [comment]
dude me too

**Comment by s0aperstartheyellow** [comment]
ask a moderator of bloxstrap about this i cant live without roblox

**Comment by DiddypartyEnjoyer** [comment]
same

**Comment by DiddypartyEnjoyer** [comment]
i might uninstal bloxstrap

**Comment by s0aperstartheyellow** [comment]
no, ask a moderator of bloxstrap

**Comment by pizzaboxer** [comment]
Duplicate of #2704
