### ISSUE TITLE
once used disable microsoft store, never worked again

### ISSUE THREAD

**Issue by splittable** [pizzaboxer/bloxstrap#271]
tried uninstalling several times, still doesnt work

**Comment by pizzaboxer** [comment]
"disable microsoft store"?

**Comment by splittable** [comment]
> "disable microsoft store"?

i meant disable microsoft roblox lol

**Comment by pizzaboxer** [comment]
Bloxstrap doesn't have any feature like that?

**Comment by splittable** [comment]
> Bloxstrap doesn't have any feature like that?

Desktop app

**Comment by splittable** [comment]
> So what's happening now? Roblox just doesn't launch?

Only for Microsoft Store Roblox.

**Comment by pizzaboxer** [comment]
I'm confused, by "Microsoft Store Roblox" do you actually mean the verison of Roblox that's on the Microsoft store, or do you mean the Roblox desktop app?

**Comment by splittable** [comment]
The version of roblox found and installed on Microsoft Store.

**Comment by pizzaboxer** [comment]
And launching it just doesn't work anymore? I'm not sure what correlation that would have with installing Bloxstrap, the two are completely separated and isolated.

**Comment by splittable** [comment]
> And launching it just doesn't work anymore? I'm not sure what correlation that would have with installing Bloxstrap, the two are completely separated and isolated.

Nope, doesnt work. Would you know anything?

**Comment by pizzaboxer** [comment]
Nope, wouldn't know. Assuming you've tried reinstaling the Microsoft store version, does it really just not show anything when you try to launch it? I guess you could try the Windows Store Apps troubleshooter, but I don't really know what else to suggest other than that.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/df23b153-dc8c-47c3-a352-cbf1f3c5e9a1)

**Comment by Sahelantrophus** [comment]
can yall fix this @microsoft

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by splittable** [comment]
never actually fixed

**Comment by splittable** [comment]
but, got it working again after reset. Thanks for trying though
