### ISSUE TITLE
[BUG] 403 forbidden fix found, force reninstall Roblox

### ISSUE THREAD

**Issue by pompompur1nn** [pizzaboxer/bloxstrap#2713]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/666163ed-76fa-42b5-9083-40e2cbdc30fd)

**Comment by pizzaboxer** [comment]
Duplicate of #2704
