### ISSUE TITLE
Idk what bug

### ISSUE THREAD

**Issue by skylin2** [pizzaboxer/bloxstrap#2714]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

So like, i was trying to launch roblox and this appeared.
![image](https://github.com/user-attachments/assets/35ebc1ed-9c08-4dbe-9da5-56c526d253a8)
idk what is this but i wanna play tsb lmao

**Comment by pizzaboxer** [comment]
Duplicate of #2704
