### ISSUE TITLE
[BUG] disconnect

### ISSUE THREAD

**Issue by opticftw** [pizzaboxer/bloxstrap#2721]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

i get disconected after 5 minutes in any game, is there a fastflag i can add or something to help this? i have good wifi speed and stuff, i seen a vid before saying its cus i lose connection for a split second so roblox just crashes instead of having a lag spike or something. they told me a fast flag to add aswell but it didnt work to well does someone have one that will?

**Comment by pizzaboxer** [comment]
No. FastFlag configs won't help you get around network connection issues.
