### ISSUE TITLE
[BUG] not starting due with joining to alt

### ISSUE THREAD

**Issue by pashamacho2010** [pizzaboxer/bloxstrap#2722]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
[Bloxstrap_20240822T123159Z.log](https://github.com/user-attachments/files/16710626/Bloxstrap_20240822T123159Z.log)

**Comment by pizzaboxer** [comment]
Read the Wiki
