### ISSUE TITLE
[BUG] Black screen for a few seconds when alt tabbing in or out, only happens with bloxstrap.

### ISSUE THREAD

**Issue by kohltic** [pizzaboxer/bloxstrap#2723]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Whenever I open up a game in roblox and alt + enter to make it fullscreen my screen goes black for a few seconds, same as alt entering out of the game. It only happens with bloxstrap, I've tried enabling full screen optimization on and off, issue still occurs with JUST bloxstrap. When I switch to roblox itself the black screen doesn't appear anymore.

**Comment by pizzaboxer** [comment]
Well yes, that's what using exclusive fullscreen is supposed to do. If it temporarily goes black when alt-tabbing then it's working correctly. It's a feature, not a bug.

**Comment by kohltic** [comment]
I see, thought this was a bug since I alt enter in and out of games a lot. Unfortunately whenever i try to screenshot it won't allow me and the black screen shows up, is it meant to do that too?

**Comment by pizzaboxer** [comment]
Yes

**Comment by kohltic** [comment]
Alright, thank you for explaining!
