### ISSUE TITLE
[BUG] Using rivertunes literally crashes roblox for some reason

### ISSUE THREAD

**Issue by Vendropen** [pizzaboxer/bloxstrap#2725]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

When I open roblox and then open msi afterburner and toggle the rivertunes overlay the game stops responding and i need to close roblox and msi afterburner for it to work again.
Also if i open msi afterburner first then roblox doesnt appear open at all but apparentally it does in the task manager so i have to close it through the task manager and then close msi afterburner for it to work

**Comment by pizzaboxer** [comment]
> [x]  My answer given in the checkbox above is a lie.

Thanks for that. If you had read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch, you would know that this is a well-known issue.
