### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by nebwulah** [pizzaboxer/bloxstrap#2726]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Bloxstrap not opening roblox

**Comment by pizzaboxer** [comment]
Will reopen when you confirm you've read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
