### ISSUE TITLE
Problem with textures

### ISSUE THREAD

**Issue by SoyB3lugaa1231** [pizzaboxer/bloxstrap#2729]
Hi, does anyone know the fflag to remove textures? I was given one called FIntDebugTextureManagerSkipMips, but it's not what I'm looking for. I know people who have a fflag that removes textures but still shows the avatars and the GUI (with the fflag I shared, it doesn't look like that).

![ApplicationFrameHost_aIJ6vpxZMl](https://github.com/user-attachments/assets/53ee6dbf-7fc4-41cc-af57-eab5a3901c93)
![chrome_xSqQb8hN9o](https://github.com/user-attachments/assets/85ddca43-4b2b-47d6-9d3d-03ad016053f0)
![Discord_XlOfyb1uF5](https://github.com/user-attachments/assets/9cacf107-b651-4f85-9b17-92be463beaa8)

**Comment by pizzaboxer** [comment]
How old are these screenshots?

**Comment by SoyB3lugaa1231** [comment]
> How old are these screenshots?

Two weeks, I took the screenshots when people were on discord and broadcasting their screen.

**Comment by pizzaboxer** [comment]
The only way I knew to remove default textures was removed a few months ago. I wouldn't know what's being used here, but it's interesting.
