### ISSUE TITLE
[BUG] Bloxstrap not working after getting banned

### ISSUE THREAD

**Issue by Trulyamoment** [pizzaboxer/bloxstrap#2735]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

After I get banned from Roblox, each time, Bloxstrap simply does not run and I have to reinstall.
Menu still works, but it doesn't matter what I do it simply does not run when I play Roblox, it launches the Roblox default launcher instead.

**Comment by pizzaboxer** [comment]
Read the Wiki. https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-launch-with-Roblox
