### ISSUE TITLE
Remove FPS preset

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [pizzaboxer/bloxstrap#2736]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

If you’re going to be supporting the “you shouldn’t go past 240 fps cap,” you might as well remove the preset for it.

**Comment by Mugetsu895** [comment]
what about the people who dont want to have set fps values

roblox only added 4 fps cap options but if people have monitors with the refresh rate of 75, 90, 165 (anything other than the values roblox implemented) then they'd have to set their framerate cap themselves

**Comment by pizzaboxer** [comment]
Well no, because some people may want to set their FPS to values that aren't in the given options.
