### ISSUE TITLE
[REQ] Change roblox's native FPS cap options

### ISSUE THREAD

**Issue by 34rdsseee** [pizzaboxer/bloxstrap#2737]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i'm gonna just say it instead of yapping.
so, bloxstrap can change the framerate and lock it, but you can't change it to a custom fps mid-game
when you use the framerate changer, it changes your default framerate and you can't change it, try to make it work

**Comment by pizzaboxer** [comment]
We can't change the FPS cap options, Sorry about that.
