### ISSUE TITLE
future lighting not working for me

### ISSUE THREAD

**Issue by ihad11cats** [pizzaboxer/bloxstrap#274]
i tried to turn on future lighting i even turned my graphics to the max and future lighting was on but it wasnt doing anything and idk what to do anymore

**Comment by ihad11cats** [comment]
its a game called "Greenville"

**Comment by pizzaboxer** [comment]
Open the rendering debug panels with Shift + F2. Under the Graphics section, what does it state the Technology as?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/347bf48f-1789-4dae-bd7f-05fde6de08b3)

**Comment by ihad11cats** [comment]
wait let me join the game

**Comment by pizzaboxer** [comment]
Open the menu again. What's the lighting mode set to?

**Comment by ihad11cats** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/1b61f055-56ba-4b9b-bea6-53501e2d2dc9)

**Comment by pizzaboxer** [comment]
Just so I can make sure, Bloxstrap is definitely showing up when you launch Roblox, right?

**Comment by ihad11cats** [comment]
yup

**Comment by pizzaboxer** [comment]
Go to the folder where Bloxstrap is installed (should be at `%localappdata%\Bloxstrap`), go to the Versions folder, go to the version-bunchofcharacters folder, and check if a folder named ClientSettings exists. If it does, go inside the folder, and send the contents of ClientAppSettings.json here.

**Comment by EasternBloxxer** [comment]
> ![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/d52b6685-bd12-4981-ab5b-c1eb807c46fb)
> ill send it like this because it wont allow me to send the file its self

Try using some other render mode

**Comment by ihad11cats** [comment]
ok

**Comment by pizzaboxer** [comment]
> ![image](https://user-images.githubusercontent.com/134803513/242046697-d52b6685-bd12-4981-ab5b-c1eb807c46fb.png) ill send it like this because it wont allow me to send the file its self

Just so I can confirm, where is this file located?

**Comment by ihad11cats** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/e65b5a8b-5b88-4017-a4c3-aaaf601413b1)

**Comment by ihad11cats** [comment]
(the user name has my name on it and i dont want to show it)

**Comment by ihad11cats** [comment]
okay one second

**Comment by ihad11cats** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/659474c3-5c19-4c97-9d99-32032820e45c)
![Screenshot 2023-05-30 203920](https://github.com/pizzaboxer/bloxstrap/assets/134803513/b3c20ae9-657c-42e4-b6a0-688188488bc4)

**Comment by pizzaboxer** [comment]
Okay, cool. Let me get you to try something else. Open up the menu again, go to the FastFlags tab, click 'Edit ClientAppSettings.json', and replace the contents of the file with the following:

```json
{
  "DFIntTaskSchedulerTargetFps": "9999",
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableInGameMenuV3": "False",
  "FFlagDebugForceFutureIsBrightPhase3": "True",
  "FFlagDebugGraphicsPreferD3D11": "True",
  "FStringDebugShowFlagState": "FFlagDebugForceFutureIsBrightPhase3"
}
```

Save the file, close the menu, and relaunch Roblox. Tell me what you see in the top left.

**Comment by ihad11cats** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/e4887772-4cfd-4096-a62a-08e671947c66)

**Comment by pizzaboxer** [comment]
Yeah, Future definitely should be taking effect then. Rejoin the game and check the debug panels again. If it still says ShadowMap, then I don't really know what to tell you.

**Comment by ihad11cats** [comment]
does this mean that it wont work for me?
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/c1a8b7f1-3099-4e31-af8f-8286f3a5eb5a)

**Comment by pizzaboxer** [comment]
Probably not. Future definitely should be taking effect by now. Seems like it's a Roblox problem. I don't know if Roblox is intentionally switching back to ShadowMap for some reason. I might be able to get some idea if you're able to send a Roblox log file privately, if you're fine with redacting your name in it.

**Comment by ihad11cats** [comment]
where can i find the roblox logs?

**Comment by pizzaboxer** [comment]
`%localappdata%\Roblox\logs`. Get the latest file from there. If you would like for me to look at it, send it over to me privately via email (pizzaboxer@pizzaboxer.xyz) or Discord (pizzaboxer#7142).

**Comment by ihad11cats** [comment]
i will send it over email

**Comment by EasternBloxxer** [comment]
If i remember correctly Future doesn't work with that rendering mode

**Comment by pizzaboxer** [comment]
> If i remember correctly Future doesn't work with that rendering mode

Why wouldn't Future work with D3D11?

**Comment by NikoYTRBLX** [comment]
Future works with D3D11, I can run it just fine with it

**Comment by bluepilledgreat** [comment]
There could be hardware checks changing lighting technology from future to shadow map. What are your specs?

**Comment by ihad11cats** [comment]
my specs arent the best i think they are very outdated
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/2d37ef57-9af7-4989-9dd1-d05f4239ec54)
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/d2870f43-1140-4b44-acb1-ef4c556e1647)
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/a3874cee-b61f-470a-adc3-2e73973f9008)

**Comment by EasternBloxxer** [comment]
Ok nvm that's opengl i remember wrong.

**Comment by NikoYTRBLX** [comment]
Oh damn, those are very old specifications, probably the reason why you can't run FiBv3

**Comment by ihad11cats** [comment]
> `%localappdata%\Roblox\logs`. Get the latest file from there. If you would like for me to look at it, send it over to me privately via email ([pizzaboxer@pizzaboxer.xyz](mailto:pizzaboxer@pizzaboxer.xyz)) or Discord (pizzaboxer#7142).

never mind i wont send it i changed my mind

**Comment by pizzaboxer** [comment]
Oh wow, yep, those specs probably explain why Roblox refuses to use Future. Not much else to say, so I'll close this now. Sorry.

**Comment by ihad11cats** [comment]
alright

**Comment by pizzaboxer** [comment]
By the way, to get rid of that stuff in the top left corner, edit ClientAppSettings.json through the menu again, and remove the line for `"FStringDebugShowFlagState"`.

**Comment by WaviestBalloon** [comment]
> my specs arent the best i think they are very outdated ![image](https://user-images.githubusercontent.com/134803513/242060304-2d37ef57-9af7-4989-9dd1-d05f4239ec54.png) ![image](https://user-images.githubusercontent.com/134803513/242060467-d2870f43-1140-4b44-acb1-ef4c556e1647.png) ![image](https://user-images.githubusercontent.com/134803513/242060505-a3874cee-b61f-470a-adc3-2e73973f9008.png)

**Future does not work on OpenGL as Roblox has dropped support for OpenGL entirely,** it will work but newer features will start to break if implemented or won't be implemented to work with OpenGL. (And it will fallback to ShadowMap)
Furthermore, using OpenGL, the `Highlight` feature that makes BaseParts stand out when `Highlight` is parented to it will partially work but will have this strange dotting effect.

Also, your iGPU is incredibly outdated, the only available drivers that Intel provides only go to Windows XP (https://www.intel.co.uk/content/www/uk/en/support/products/81511/graphics/legacy-graphics/graphics-drivers-for-intel-q45-express-chipset.html) but it also looks like Microsoft installed a generic driver as the XP drivers are incompatible with Windows 11.
Refer to https://www.intel.co.uk/content/www/uk/en/support/articles/000005524/graphics.html for supported Graphical APIs for your GPU and https://en.help.roblox.com/hc/en-us/articles/203312800-Computer-Hardware-Operating-System-Requirements for Roblox system specification recommendations.

**Looks like your iGPU only supports DirectX 10 or below and OpenGL 2 and below.** 
![image](https://github.com/pizzaboxer/bloxstrap/assets/31796727/9f4d22f1-5a68-49c0-8403-44422c0c9367)

**Roblox specifications: (Probably a bit outdated as they still recommend Windows 7)**
![image](https://github.com/pizzaboxer/bloxstrap/assets/31796727/f935f37e-d47b-4ed4-9c71-7a0074ab47a9)

**Comment by brenden7158** [comment]
Even if the Intel GMA integrated graphics could run future, it wouldn't perform well

**Comment by Lumati531** [comment]
I have a somewhat decent computer and before the future lights worked for me but they suddenly stopped working I have an amd a8 9600 Someone can help me?

**Comment by WaviestBalloon** [comment]
> I have a somewhat decent computer and before the future lights worked for me but they suddenly stopped working I have an amd a8 9600 Someone can help me?

We would need a bit more info than just that, have you checked if you have the correct drivers installed and not a generic one?

**Comment by FrostGamerTag** [comment]
Guys i need help, my future lighting used to work but i realised 2 days ago that it doesnt work and i tried everything like all the fast flags every single thing and it still not forcing future lighting pls tell how to fix this problem

**Comment by FrostGamerTag** [comment]
<img width="674" height="83" alt="Image" src="https://github.com/user-attachments/assets/61b32205-5448-45ee-aae5-a6f0e6be6e83" />

**Comment by FrostGamerTag** [comment]
this are my specs bro

**Comment by FrostGamerTag** [comment]
and it used to work too but now it just doesnt :(

**Comment by FrostGamerTag** [comment]
<img width="319" height="135" alt="Image" src="https://github.com/user-attachments/assets/61b3bc9a-b9bf-4fc2-bc06-a818ebfc45e2" />

**Comment by FrostGamerTag** [comment]
for some reason the technology is just "unified" for me

**Comment by FrostGamerTag** [comment]
<img width="1655" height="428" alt="Image" src="https://github.com/user-attachments/assets/1847dbbf-6a30-414f-9f94-ed5bcc96fe9e" />

**Comment by FrostGamerTag** [comment]
<img width="1658" height="345" alt="Image" src="https://github.com/user-attachments/assets/f383d740-bed2-423c-a79a-59d8e47f426d" />

**Comment by FrostGamerTag** [comment]
okay help me

**Comment by oijasd890uthf** [comment]
future lightning doesnt work you dumbfuck

**Comment by nabheyka880** [comment]
> okay help me

future is gone and dead

**Comment by krampuszc** [comment]
> > okay help me
> 
> unified is gone and dead

? I think ya meant future. Unified replaces it
Also recently you could still disable unified so it would use lighting technologies but im not sure if that's still possible

**Comment by nabheyka880** [comment]
> ? I think ya meant future. Unified replaces it

oops
my bad

**Comment by FrostGamerTag** [comment]
wait so its not a bug and future lighting is juts now gone or what?

**Comment by FrostGamerTag** [comment]
forever for everyone?

**Comment by Encythe** [comment]
Unified changes your lighting mode based on your graphics quality. Lighting technology itself is deprecated and is now a read-only property in game.Lighting.

Additionally, this is an old-as-fuck issue; maybe try opening a new issue in the future instead.

**Comment by FrostGamerTag** [comment]
so future lighting gone forever or no?

**Comment by FrostGamerTag** [comment]
THEN HOW DO I FIX IT OR MAKE THE FUTURE LIGHTING COME BACK ON EVERY GAME

**Comment by nabheyka880** [comment]
you don't buddy
