### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HotFloppa221** [pizzaboxer/bloxstrap#2740]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
![Screenshot_3](https://github.com/user-attachments/assets/2b67d1c3-2247-4026-9e48-c27aa7bf62d9)

**Comment by pizzaboxer** [comment]
Read the Wiki
