### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by whn-69** [pizzaboxer/bloxstrap#2741]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

when i tried to open another account it showed this error message 
![image](https://github.com/user-attachments/assets/77421e8d-650a-4669-b002-786fef870464)

**Comment by pizzaboxer** [comment]
Read the Wiki
