### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ilyqit** [pizzaboxer/bloxstrap#2742]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
Whenever I open up roblox on a different account that isnt my main account, roblox bloxstrapper doesnt work at all
nor wont let me play its just an error consistently.
whenever I open roblox up on my main account, it works but yeah.. what do I do??
[Bloxstrap_20240824T154820Z.log](https://github.com/user-attachments/files/16737211/Bloxstrap_20240824T154820Z.log)

**Comment by pizzaboxer** [comment]
Read the Wiki
