### ISSUE TITLE
[BUG] Launching from different accounts always forces a Roblox upgrade

### ISSUE THREAD

**Issue by wyascorn** [pizzaboxer/bloxstrap#2745]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Everytime I switch accounts it says upgrading roblox

**Comment by pizzaboxer** [comment]
Yep, Roblox will just do that. Nothing we can do about that.
