### ISSUE TITLE
[BUG] fast flags wont shut off

### ISSUE THREAD

**Issue by cakebill12** [pizzaboxer/bloxstrap#2748]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

my fast flags are still on. i removed them checked the thing that turns them off and they are still on.

**Comment by pizzaboxer** [comment]
How can you tell that they're still on?
