### ISSUE TITLE
[BUG] dont open

### ISSUE THREAD

**Issue by fidosesk** [pizzaboxer/bloxstrap#2756]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![immagine_2024-08-26_184131195](https://github.com/user-attachments/assets/93c696a3-8d3f-4c4c-be92-053400354081)

**Comment by fidosesk** [comment]
why you closed

**Comment by nexpid** [comment]
> why you closed

bloxstrap doesn't provide support for liars sorry

**Comment by fidosesk** [comment]
bro what

**Comment by bluepilledgreat** [comment]
> > why you closed
> 
> bloxstrap doesn't provide support for liars sorry

stop being an idiot

**Comment by bluepilledgreat** [comment]
@fidosesk relaunch roblox from the website. that should fix the issue.

**Comment by fidosesk** [comment]
btw bloxstrap is useless 💀

**Comment by gamerloch10** [comment]
how's it useless? if your using it to try to get better fps that makes sense but if your using it for it's intended use it's helpful

**Comment by nabheyka880** [comment]
> btw bloxstrap is useless 💀

then why did you download it
