### ISSUE TITLE
[BUG] Graphics Quality is stuck on max no matter what number its set at.

### ISSUE THREAD

**Issue by aqua8811** [pizzaboxer/bloxstrap#2759]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

My computer isn't too good so this was quickly noticeable, I usually run with two bars on the graphic quality scale which severely lowers the detail and noticeability with things like enchantments and auras, and especially shadows, which is shown in the provided screenshots.
![image](https://github.com/user-attachments/assets/6f741eeb-aa8c-413f-930e-391d728bb45a)
![image](https://github.com/user-attachments/assets/9cf6e292-453e-4fc6-bdfa-f2d1d3a13188)

**Comment by s0qo** [comment]
same problem here..

**Comment by Mugetsu895** [comment]
i had this exact problem but i fixed it by doing this 
![image](https://github.com/user-attachments/assets/44987eb9-430f-4bac-923c-00b692b15e45)

**Comment by gioprogamertv123** [comment]
> i had this exact problem but i fixed it by doing this ![image](https://private-user-images.githubusercontent.com/142404890/361676319-44987eb9-430f-4bac-923c-00b692b15e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTM5MzgsIm5iZiI6MTcyNDc1MzYzOCwicGF0aCI6Ii8xNDI0MDQ4OTAvMzYxNjc2MzE5LTQ0OTg3ZWI5LTQzMGYtNGJhYy05MjNjLTAwYjY5MmIxNWU0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMDEzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTA4MmRlY2YwZjVhMzFmNGY2OWM1NGRhMDg2M2NiY2EwZjJlOGQ2MTk4NmU4ZGI2NWJlNjNlOTBjNDkwZmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O-uJ2CvqyWCokYXWP5F0HSP4o6Lzc6_xMDHDXk3cSow)

not working

**Comment by Mugetsu895** [comment]
![image](https://github.com/user-attachments/assets/82280651-d5af-4908-828a-818728cf4996)

**Comment by gioprogamertv123** [comment]
> ![image](https://private-user-images.githubusercontent.com/142404890/361759722-82280651-d5af-4908-828a-818728cf4996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTQxNjUsIm5iZiI6MTcyNDc1Mzg2NSwicGF0aCI6Ii8xNDI0MDQ4OTAvMzYxNzU5NzIyLTgyMjgwNjUxLWQ1YWYtNDkwOC04MjhhLTgxODcyOGNmNDk5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMDE3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWVlZmIzMDFiMjMyZDg3YWRhNjI0M2NmYzQ0MDg3ZDk2OTIwOWIxZjBlMmNmODQzMDUzYmNjZmQ3M2FmNzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ckd720mUvI_smB1kWwVNHdEj2O_qrCFDrU4Nw2fuU4o)

what

**Comment by dinobob625** [comment]
I'm having the same issue and its really annoying

**Comment by NabHeyka22** [comment]
yeah you either need to wait or
![image_2024-08-27_191744417](https://github.com/user-attachments/assets/4a411a5d-46de-4ee6-9b03-1380e71580bd)

**Comment by 0miedo** [comment]
Dowload Roblox  + Bloxstrap , before a reinstal delete all archives from %appdata%, restart pc and reinstall. (Login in the app)

**Comment by 0miedo** [comment]
nvm, get broken again when u rejoin

**Comment by pizzaboxer** [comment]
This is known, and it's not an issue with Bloxstrap. It's an issue with Roblox. We don't really provide any ways of getting around this, so you'll have to wait it out. Sorry about that.
