### ISSUE TITLE
FPS Tab

### ISSUE THREAD

**Issue by ToxicTDX** [pizzaboxer/bloxstrap#2764]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

for Bloxstrap 2.80, you should make a separate tab, or indicators that "THESE CAN IMPROVE YOUR FPS", would take down many issues on the github, and also just overall improve the simplicity of the bootstrapper, instead of people ending up watching random youtube tutorials and screwing up their roblox version with fast flags. and that also, in return would cause more github "issue" requests.

**Comment by lilbeefaroni** [comment]
useless

**Comment by Mugetsu895** [comment]
> would take down many issues on the github
There's a warning when you first enter the fastflag editor to prevent these issues on the github but eh 💀

**Comment by NabHeyka22** [comment]
it's not pizzaboxer's problem
he put the warning. they don't read it? not our problem

also i want another answer to my question

**Comment by Mugetsu895** [comment]
> it's not pizzaboxer's problem he put the warning. they don't read it? not our problem
> 
> also i want another answer to my question

ngl its kinda cuz its longggg so people just go like too long not reading allat

**Comment by NabHeyka22** [comment]
buddy it's 1 cm tall what are you complaining about

**Comment by pizzaboxer** [comment]
>  instead of people ending up watching random youtube tutorials and screwing up their roblox version with fast flags. 

Why do you think we provide the presets we specifically provide?
