### ISSUE TITLE
[BUG] Render distance keeps going max, but the setting on roblox is set to 1.

### ISSUE THREAD

**Issue by ZadenFaline** [pizzaboxer/bloxstrap#2765]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

My render distance keeps going to max while my settings on roblox is 1 I checked my fflag and nothing seems to be the main problem, is this because of bloxstrap? I dont know, but it seems that it is, because the roblox without bloxstrap has the render distance and graphics to 1 and basically means it's normal. Please let me know if you fixed it or let me know on how to fix this render problem. It causes my fps to drop and makes my gameplay really, unsettling.

**Comment by RuthlessVerizon** [comment]
yes i've been facing the same problem. also the game is giving me wrong servers which causes me high ping

**Comment by Storm-930** [comment]
roblox issue, you've been set to a broken channel, no other fix than praying roblox gets you out of it
