### ISSUE TITLE
reinstalling did something

### ISSUE THREAD

**Issue by Malletspoopy** [pizzaboxer/bloxstrap#2766]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image_2024-08-28_084541628](https://github.com/user-attachments/assets/e4976560-4b10-4ac7-9a4a-6df00553bca9)

**Comment by Storm-930** [comment]
send logs

**Comment by Malletspoopy** [comment]
Nvm i fixed it
