### ISSUE TITLE
[BUG] "FIntDebugTextureManagerSkipMips -1" isnt working 

### ISSUE THREAD

**Issue by f6de** [pizzaboxer/bloxstrap#2769]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i use "FIntDebugTextureManagerSkipMips -1" to get better fps in games and today it just stopped working i deleted and reinstalled and nothing

**Comment by DylanChillin** [comment]
me too

**Comment by f6de** [comment]
> me too
check this video

https://youtu.be/j8i1KbAzsP0?si=GLGjm--88ou1sTZZ

**Comment by pizzaboxer** [comment]
That's to do with Roblox itself. Not sure what you want me to do about this.
