### ISSUE TITLE
[feature request?] roblox has a new menu

### ISSUE THREAD

**Issue by lokzz** [pizzaboxer/bloxstrap#277]
didnt see this in the patch notes for the new release so yea
![menu](https://github.com/pizzaboxer/bloxstrap/assets/50368061/fed61cdc-becf-4354-a5ac-92bb39654100)

**Comment by pizzaboxer** [comment]
Yeah, I know about this. This new menu was just added like two weeks ago.

**Comment by lokzz** [comment]
ok
