### ISSUE TITLE
[REQ] Add a (NEW) join servers in a specific region option.

### ISSUE THREAD

**Issue by RuthlessVerizon** [pizzaboxer/bloxstrap#2776]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

it will be great to add a button like this so that when roblox messes up by giving you wrong servers. you can fix it yourself

**Comment by Storm-930** [comment]
you know you can just
pay for a shiity extension that does this right

**Comment by RuthlessVerizon** [comment]
i dont wanna pay 🤷

**Comment by NabHeyka22** [comment]
skill issue

**Comment by NabHeyka22** [comment]
also how about you just rejoin and make your life easier

**Comment by pizzaboxer** [comment]
Not possible
