### ISSUE TITLE
[BUG] Volume issues!

### ISSUE THREAD

**Issue by RuthlessVerizon** [pizzaboxer/bloxstrap#2777]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

increasing or decreasing volume of device isn't affecting bloxstrap. volume is only getting affected by roblox (In game settings)

### Bloxstrap Log

N/A

**Comment by Storm-930** [comment]
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuurgh agaaaaaaaaaaaaaaain
im starting to feel like this is a problem with your device and not bloxstrap itself...
anyway send the logs

**Comment by pizzaboxer** [comment]
Can you clarify where you're trying to set the volume that it isn't working?

**Comment by RuthlessVerizon** [comment]
> Can you clarify where you're trying to set the volume that it isn't working?

it is now fixed. thank you. you may close this
