### ISSUE TITLE
Changing the menu doesn't work

### ISSUE THREAD

**Issue by enjajajafan32** [pizzaboxer/bloxstrap#278]
I'm trying to swap back to the old 2021 menu, but when I select it and load up Roblox, I still have the most recent menu. I've reinstalled Bloxstrap at least 3 times however it's still not changing. What can I check to make sure nothing's broken or how can I fix it?

**Comment by Boi2021Miceoos** [comment]
There is no fix to this

**Comment by enjajajafan32** [comment]
> The new menu overrides all the older menus, so you'll have to disable it first. I won't be out with another Bloxstrap update to add this as an option soon, so see this Wiki page: https://github.com/pizzaboxer/bloxstrap/wiki/Toggling-the-new-escape-menu

If possible, could you upload a video or gif or something to show exactly how I'm supposed to do it? Also, is it okay if I just use Notepad to edit the settings? I copied and pasted the disable menu section into the brackets and now the settings look like this: 

https://prnt.sc/Uww4KcJQwJdJ (it's a lightshot link)

However, my menu remains as the version 4 one. Could you point out what I did wrong?

**Comment by enjajajafan32** [comment]
Nevermind, I was able to revert to the V3 Menu by choosing the V1 option. Thank you for your help!

**Comment by pizzaboxer** [comment]
oh
