### ISSUE TITLE
[BUG] error 403

### ISSUE THREAD

**Issue by ywhfjeraxsurlru** [pizzaboxer/bloxstrap#2780]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### Bloxstrap Log

N/A
[Bloxstrap_20240830T101549Z.log](https://github.com/user-attachments/files/16815482/Bloxstrap_20240830T101549Z.log)

**Comment by NabHeyka22** [comment]
why do you put the checks like it's nothing
like there have been 10k posts of the same thing
it's written on the wiki, but you don't read it

UPDATE!!!

**Comment by ShadowCodeX-debug** [comment]
> [!Warning]
> Please read preliminary instructions before posting.

**Please update Bloxstrap to the latest/current version.**
