### ISSUE TITLE
[BUG] I can't install my Bloxstrap

### ISSUE THREAD

**Issue by Redavader** [pizzaboxer/bloxstrap#2781]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I was gonna download Bloxstrap on my PC until i stumble upon this issue:

Bloxstrap.Exceptions.ChecksumFailedException: Failed to verify download of http://setup.rbxcdn.com/version-ad321ed0d27f48b2-RobloxApp.zip

Expected hash: 5d93067558f80b65ca3fe321c9d8b75f
Got hash: 24c19b8d5753ffdf1690f656be5cd6cf

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
You are not using the latest version of Bloxstrap, so I'm not sure why you ticked that checkbox. Also, see https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-is-unable-to-download-Roblox.
