### ISSUE TITLE
[BUG] failed to load OnlineFix64.dll from the list error code 126

### ISSUE THREAD

**Issue by phth12** [pizzaboxer/bloxstrap#2782]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot 2024-08-30 173443](https://github.com/user-attachments/assets/8a3dd853-85ed-400e-8d5d-ecc5de998ab3)
I've already looked for several bug fixes but haven't found anything. In general I can't install onlinefix64.dll and all install sites are scams so I hope I can get help from someone I would really like to use bloxstrap

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
This error isn't coming from Bloxstrap. You installed something (seemingly a pirated game) that appears to be hooking into all .NET Core applications and it's causing this error. It's not an issue on my side, and I wouldn't know how to fix this.
