### ISSUE TITLE
[BUG] Fps cap at 60fps

### ISSUE THREAD

**Issue by Malletspoopy** [pizzaboxer/bloxstrap#2783]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image_2024-08-30_123743901](https://github.com/user-attachments/assets/e3595d22-3b32-4a67-b3da-c3d73eb2571b)
so i had blockstrap and i put a fastflag that is the fps unlocker and when i removed it it still did not go away i uninstall and reinstalled blockstap, i removed blockstrap still did not work, i remove roblox and reinstalled it did not work. so there is some code in my system that is doing crap to my roblox files

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
you know there's a built in fps unlocker, riiiiight?

**Comment by Malletspoopy** [comment]
also i forgot graphics mode is stuck to auto

**Comment by Malletspoopy** [comment]
![Screenshot 2024-08-30 172824](https://github.com/user-attachments/assets/df604b9c-3300-4ffb-8c98-9f983bd52fc1)
![Screenshot 2024-08-30 172855](https://github.com/user-attachments/assets/1173f90d-e392-4444-9670-2c2c842ef211)
![Screenshot 2024-08-30 173059](https://github.com/user-attachments/assets/775eb222-fc53-448e-97f2-063f733e46a8)
![Screenshot 2024-08-30 173112](https://github.com/user-attachments/assets/40ba7b29-3d25-4acb-adf2-64209c028ed0)

**Comment by pizzaboxer** [comment]
> so there is some code in my system that is doing crap to my roblox files

Then this isn't an issue with Bloxstrap.

Also, did you even read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter?
