### ISSUE TITLE
it can not download for some reason 

### ISSUE THREAD

**Issue by meowmeowmeow27** [pizzaboxer/bloxstrap#2784]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image_2024-08-30_162650613](https://github.com/user-attachments/assets/55a6005a-64d6-45e9-aa37-f30d3deb2221)

### Bloxstrap Log

im not sure if this issue is fixed but heres the file
[Bloxstrap_20240830T211942Z.log](https://github.com/user-attachments/files/16822158/Bloxstrap_20240830T211942Z.log)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
