### ISSUE TITLE
feature request: hotkey to cap fps at a certain number

### ISSUE THREAD

**Issue by yoyeet961** [pizzaboxer/bloxstrap#279]
ik this is so random, but i wish i was able to press a hotkey like right ctrl+/ in order to max out my fps at 4
it makes my character lag and overall i can react to every frame using it.
so like that's pretty much the ability to TAS on the go
(TAS stands for tool assisted superplay and tool assisted speedrun. pretty much what it means, is that someone went frame by frame with perfect inputs in-order to make something cool etc.)

**Comment by pizzaboxer** [comment]
Not possible, sorry. FPS cap can't be changed while the game client is running.
