### ISSUE TITLE
[REQ] Ability to override fonts loaded from the Roblox Marketplace

### ISSUE THREAD

**Issue by somefnfplayerlol** [pizzaboxer/bloxstrap#2793]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Some places use fonts that are from the Roblox Marketplace and I would like for Bloxstrap to have the ability to override those fonts with the custom font set. Y'know, for consistency with the custom font.

_feel free to call me based lol_

**Comment by bluepilledgreat** [comment]
Impossible
