### ISSUE TITLE
Unable to launch Roblox

### ISSUE THREAD

**Issue by RUvlad1** [pizzaboxer/bloxstrap#280]
When I click play either of these errors show up
![Bloxstrap 1_b1](https://github.com/pizzaboxer/bloxstrap/assets/60317461/66f3d051-aff3-4f66-b1ed-3ec9a39352a0)

![Error_b1](https://github.com/pizzaboxer/bloxstrap/assets/60317461/de752e9b-3d68-4787-a4f0-4713ef59eb7c)

I already tried reinstalling Roblox and it's still not working

**Comment by RUvlad1** [comment]
It's a different error now, it just immediately crashes
![Roblox Crash_b1](https://github.com/pizzaboxer/bloxstrap/assets/60317461/9e5aab42-0ac5-4802-8b50-a39a60fd71d9)

**Comment by RUvlad1** [comment]
same crash, but this time it actually shows the game window
![image](https://github.com/pizzaboxer/bloxstrap/assets/60317461/ae2aff22-4b8a-4efa-b53d-4537eb73dd6a)

**Comment by pizzaboxer** [comment]
Try this: https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-crashes

**Comment by RUvlad1** [comment]
> Try this: https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-crashes

i couldn't find anything related to my problem (though i may be blind so i'll look into that again) but after trying to play Roblox from the MS Store version, the game now shows a single frame of the loading screen, after which it crashes again

![image](https://github.com/pizzaboxer/bloxstrap/assets/60317461/4e1d08ec-15fb-4c7b-9c75-7dfab9626cc8)

**Comment by RUvlad1** [comment]
> > i couldn't find anything related to my problem
> 
> https://github.com/pizzaboxer/bloxstrap/wiki/Information-on-Roblox-crashes#hyperion-doesnt-like-some-of-your-cached-files

i tried that already, doesn't work

**Comment by pizzaboxer** [comment]
Yeah, I won't be able to help you much then, since this isn't a Bloxstrap problem. Though, I can forward your crash dump files to a Roblox staff member, and see if they're able to reach some sort of conclusion on them.

**Comment by RUvlad1** [comment]
i just tried manually removing the stuff in %temp% and now it just doesnt respond
![image](https://github.com/pizzaboxer/bloxstrap/assets/60317461/acb9e05e-da2d-47b0-8153-90e35e82526c)

**Comment by pizzaboxer** [comment]
`%localappdata%\Roblox\logs`, see if there's a .dmp file with a corresponding .log file and .ini file. If not, check `%localappdata%\Roblox\logs\archive`.

**Comment by RUvlad1** [comment]
> `%localappdata%\Roblox\logs`, see if there's a .dmp file with a corresponding .log file and .ini file. If not, check `%localappdata%\Roblox\logs\archive`.

i can't send it over github, can i dm you the file over discord in dms?

**Comment by pizzaboxer** [comment]
Yeah, go ahead.
