### ISSUE TITLE
[REQ] Guilded Game Overlay support

### ISSUE THREAD

**Issue by kalenhop9** [pizzaboxer/bloxstrap#2800]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Just like discord's rich presence I want bloxstrap to support game overlay by showing what game I'm in within my profile like this:
![image](https://github.com/user-attachments/assets/f6738765-2848-48f2-a866-6aad3f54b3b0)
This would be nice to have along side discord's rich presence!

**Comment by NabHeyka22** [comment]
and most likely will never make

**Comment by pizzaboxer** [comment]
Does Guilded even have support for Rich Presence? I'm looking through the docs and can't find anything relating to it.

**Comment by kalenhop9** [comment]
Does this count as one?
https://support.guilded.gg/hc/en-us/articles/19215248699287-Game-Overlay-β

**Comment by moyaimoment** [comment]
> Does this count as one?

The guide literally tells you to go and enable Game Overlay in the settings for your specific game yourself. Guilded doesn't have Rich Presence only Game Detection.
