### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by IS4ha** [pizzaboxer/bloxstrap#2801]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

not loading

### Bloxstrap Log

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by NabHeyka22** [comment]
are those checks a lie

**Comment by NabHeyka22** [comment]
send the logs real quick

you do that by clicking on locate log file and putting the selected here (idk how)

**Comment by IS4ha** [comment]
The issue sorted itself out adter re running roblox and bloxstrap

**Comment by NabHeyka22** [comment]
could you send the logs please

**Comment by NabHeyka22** [comment]
i meant the log file.

click locate log file when the error pops up, and put the selected here
