### ISSUE TITLE
[BUG] Discord Activity Integration is broken after recent Discord update

### ISSUE THREAD

**Issue by Jinx-DaCat** [pizzaboxer/bloxstrap#2805]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/bcc21c60-d66f-48ee-b131-d4a21e0b6aea)

After a recent Discord update that changed the layout and format of activities, it no longer shows the specific game youre playing nor the option to join your game from the activity box

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Works fine for me and others. Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Discord-Rich-Presence-does-not-work?

**Comment by Jinx-DaCat** [comment]
> Works fine for me and others. Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Discord-Rich-Presence-does-not-work?

I havent before but checking it now, none of the aforementioned solutions and recommendations on that page have solved this issue yet

**Comment by pizzaboxer** [comment]
Discord hides the button for your own profile. It'll show for other people.
