### ISSUE TITLE
[BUG] Cannot disable Bloxstrap's Rich Presence

### ISSUE THREAD

**Issue by goodlook2** [pizzaboxer/bloxstrap#2807]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I am unable to disable rich presence for specifically Bloxstrap. I am **NOT** looking to disable it for all programs on Discord, **only** Bloxstrap. I use and have the shader service Bloxshade installed, which involves masking Roblox as Euro Truck Sim (ETS2). I've already tried the following to disable Bloxstrap's RPC:

- Disabled toggle detection for both ETS2 and Bloxshade menu in Discord settings
- Disabled all fields for Discord RPC in Bloxshade Menu
- Went into the settings.json and confirmed RPC was set to 'false'

I found the specific files in the Code on github with the folder "BloxstrapRPC" but I cannot locate them in file explorer -- probably because they are rooted into the installation. Bear in mind I have never used github before nor do I have experience with targeting installation files.

![Screenshot_151](https://github.com/user-attachments/assets/e7fad970-f4af-4360-853f-92a3336b6895)
![Screenshot_22](https://github.com/user-attachments/assets/a536c237-315a-43c4-a029-e48ad76f3e1e)
![Screenshot_19](https://github.com/user-attachments/assets/c3617bab-cb48-43c6-ae28-62bd267afdd9)
![Screenshot_20](https://github.com/user-attachments/assets/0845d818-0569-4ac2-8b40-d43d580be56e)
![Screenshot_21](https://github.com/user-attachments/assets/e638270b-f9d6-4d96-876d-94c048b32f2e)

### Bloxstrap Log

N/A

**Comment by moyaimoment** [comment]
It's because you have Bloxshade, it states it in your first screenshot.

Also the DiscordRPC folder on the GitHub is the source, so yes it's in the application itself.
