### ISSUE TITLE
[REQ] Issue on opening Roblox

### ISSUE THREAD

**Issue by AYn0nyme** [pizzaboxer/bloxstrap#2808]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I just installed Tiny11 and found out that you need Edge to run Roblox on Windows, maybe add this in the wiki, it'll be usefull I think

**Comment by moyaimoment** [comment]
You don't need Edge to run Roblox.

**Comment by NabHeyka22** [comment]
you don't need edge to run roblox. i think that's just tiny11
might aswell just stick to windows 10

**Comment by pizzaboxer** [comment]
Bloxstrap should auto-install WebView2 which should also auto-install Edge. That's weird, but I'll note that.
