### ISSUE TITLE
raising the framerate limit does not work.

### ISSUE THREAD

**Issue by Bobsmith49** [pizzaboxer/bloxstrap#2809]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

raising the framerate limit does not work.

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
Can you elaborate? What are you trying to raise it to? What is it stuck at?

**Comment by Bobsmith49** [comment]
I am trying to raise it to 400 fps but it is stuck at 240.

**Comment by NabHeyka22** [comment]
you can't go over 240 fps

**Comment by Bobsmith49** [comment]
What does it do?

**Comment by NabHeyka22** [comment]
i forgot why you shouldn't go over 240 fps but it's explained on the wiki
i think it was related to physics? idk

**Comment by Bobsmith49** [comment]
The wiki said that roblox made that. I thought bloxstrap changed the physics calculations to what ever you put it as.

**Comment by NabHeyka22** [comment]
yeah roblox put it as that

**Comment by pizzaboxer** [comment]
> The wiki said that roblox made that

You know why the framerate limit can't be raised yet you're complaining about raising the framerate limit not working. Are you serious?
