### ISSUE TITLE
High Ping

### ISSUE THREAD

**Issue by fandemysterios** [pizzaboxer/bloxstrap#281]
Something with the ClientSettings folder made me start getting 500 ping

**Comment by pizzaboxer** [comment]
It might be the FPS unlimiter. Set the framerate limit to 0 (roblox treats it as setting it to defaults), and see if anything changes.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
