### ISSUE TITLE
[BUG] notabletoclicktheconfirmbuttonwhenbanned

### ISSUE THREAD

**Issue by aych101** [pizzaboxer/bloxstrap#2810]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

not able to click the confirm button when banned

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
What?

**Comment by pizzaboxer** [comment]
Duplicate of #1522
