### ISSUE TITLE
[BUG] report

### ISSUE THREAD

**Issue by pro-gaming09** [pizzaboxer/bloxstrap#2817]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Report

### Bloxstrap Log

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by NabHeyka22** [comment]
send the log file

**Comment by MIM-104** [comment]
same dude

**Comment by NabHeyka22** [comment]
since you're not gonna send the log file, i'm just going to tell you that you need to update
if you want multi instance use roblox account manager
if you don't want to update not our problem and we won't help you

also, STOP PUTTING CHECKS LIKE IT'S NOTHING!!!
