### ISSUE TITLE
[BUG] ERROR

### ISSUE THREAD

**Issue by cloudftw** [pizzaboxer/bloxstrap#2818]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zalloctrackwinquickfix because it returned HTTP 500 (Internal Server Error)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
One-off issue. Ignore and relaunch.
