### ISSUE TITLE
[BUG] Bloxstrap unable to connect to roblox 

### ISSUE THREAD

**Issue by kgamingxx** [pizzaboxer/bloxstrap#2819]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/48f1b7ff-7ba9-4a92-bb3d-93faa9a593ff)

says it all there

**Comment by pizzaboxer** [comment]
One-off issue. Ignore and relaunch.
