### ISSUE TITLE
feature request: channel ZLIVE

### ISSUE THREAD

**Issue by yoyeet961** [pizzaboxer/bloxstrap#282]
i went into the installation channels and noticed that ZLIVE isn't there.
pls add it its a real channel
ty

**Comment by pizzaboxer** [comment]
dude just type it in

**Comment by JoshifiedZone** [comment]
How to search or even find a channel in the latest version.  🧐 `<div><span style="color: #ff0000">J</span><span style="color: #ff4000">O</span><span style="color: #ff7f00">S</span><span style="color: #ffaa00">H</span><span style="color: #ffd400">I</span><span style="color: #ffff00">F</span><span style="color: #80ff00">I</span><span style="color: #00ff00">E</span><span style="color: #00ff55">D</span><span style="color: #00ffaa">Z</span><span style="color: #00ffff">O</span><span style="color: #0080ff">N</span><span style="color: #0000ff">E</span></div>` 
![Bloxstrap](https://github.com/pizzaboxer/bloxstrap/assets/152240879/a101836e-7e00-435e-b0b0-288745c2bd8c)

**Comment by TheMetalTechnet** [comment]
> How to search or even find a channel in the latest version
Bloxstrap will show you if it's outdated or not

**Comment by yoyeet961** [comment]
What about the rest of the channels? Where are they in bloxstrap?

**Comment by github-production-user-asset** [comment]
gone
roblox privated them all

**Comment by yoyeet961** [comment]
Roblox really sucks

**Comment by JoshifiedZone** [comment]
Yeah, fr I'm going to play sandbox, Roblox gave me a warning for putting
I'm a youtuber in me about section even after the amount of hacks I used to
use this is my first warning on my entire Roblox journey Jit tripping.
