### ISSUE TITLE
[REQ] a way to change the chat/menu icon on the top bar to older versions/custom icons

### ISSUE THREAD

**Issue by R2P2x** [pizzaboxer/bloxstrap#2824]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

read title

**Comment by pizzaboxer** [comment]
Are you just talking about only the icons, or the overall look and layout of it?

**Comment by R2P2x** [comment]
the icon would be enough for me as long as its the same size and stuff, if its the entire layout it would also be cool but accurate icons would be good enough (for me atleast)

**Comment by R2P2x** [comment]
and maybe the old player list if thats possible but thats not really relevant for this thread

**Comment by pizzaboxer** [comment]
I probably wouldn't add a preset option in the Menu for that, given it'll be a look that's half-baked at best. People have made mods like that though, if you see the #mods channel in the Bloxstrap discord server: https://discord.com/invite/nKjV3mGq6R
