### ISSUE TITLE
[REQ] CUSTOM EMOJIS

### ISSUE THREAD

**Issue by 7-7what** [pizzaboxer/bloxstrap#2826]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

so basically, you get to like, put in any image for the selected emoji u want to change, and it changes it through roblox!

**Comment by NabHeyka22** [comment]
i don't really think it's possible ngl

**Comment by pizzaboxer** [comment]
Doesn't work like that, sorry.

**Comment by 7-7what** [comment]
dang
