### ISSUE TITLE
[BUG] when i open bloxstrap it crashes instantly and in the log it gives me the error code or exit code 0 

### ISSUE THREAD

**Issue by Hea11ly** [pizzaboxer/bloxstrap#2829]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i already tried deleting cache and deleting  thumbnails and it just gives me a new log with exit code 0

### Bloxstrap Log

[Bloxstrap_20240905T190502Z.log](https://github.com/user-attachments/files/16899441/Bloxstrap_20240905T190502Z.log)

**Comment by toofastforboo** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
Does Roblox work without using Bloxstrap?

**Comment by Hea11ly** [comment]
> Does Roblox work without using Bloxstrap?

no it does not

**Comment by Hea11ly** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

it does not work i tried already

**Comment by NabHeyka22** [comment]
have you _actually_ read it?

**Comment by Hea11ly** [comment]
> have you _actually_ read it?

yes i have

**Comment by NabHeyka22** [comment]
so you have no programs running in the background, you don't have an insider preview of windows, and you're not using anything like AtlasOS

**Comment by Hea11ly** [comment]
> so you have no programs running in the background, you don't have an insider preview of windows, and you're not using anything like AtlasOS

nope i have issue c and it didnt work so im asking support from the community

**Comment by pizzaboxer** [comment]
> no it does not

This isn't a Bloxstrap issue then. I can't help you here, sorry.
