### ISSUE TITLE
Missing new in-game menu version

### ISSUE THREAD

**Issue by deprecatedbrain** [pizzaboxer/bloxstrap#283]
As of a couple days ago there's a new in-game menu that's missing from the Bloxstrap Menu. Choosing the default/v1 menu will cause it to show, v2 and v3 are how they normally are.

**Comment by pizzaboxer** [comment]
I'm aware of this. See https://github.com/pizzaboxer/bloxstrap/wiki/Toggling-the-new-escape-menu.

**Comment by deprecatedbrain** [comment]
Oops, I just checked the issues to see if you were aware, my bad!
