### ISSUE TITLE
[BUG] FPS UNLOCK

### ISSUE THREAD

**Issue by cloudftw** [pizzaboxer/bloxstrap#2832]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/97078d16-a2f4-40ee-a12a-fe0589d87f1c)
so uh yeah

### Bloxstrap Log

N/A

**Comment by toofastforboo** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter
