### ISSUE TITLE
[BUG] error 403

### ISSUE THREAD

**Issue by Mei6666** [pizzaboxer/bloxstrap#2833]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Getting error 403, was just trying to join a roblox game and it shows the error every time it launches bloxstrap. I have tried uninstalling and reinstalling, it didnt help. Not sure what would cause the problem since its worked up until now. 
Im using bloxstrap v2.5.4

### Bloxstrap Log

[Bloxstrap_20240905T235148Z.log](https://github.com/user-attachments/files/16901253/Bloxstrap_20240905T235148Z.log)

**Comment by toofastforboo** [comment]
- [x]  I did not answer truthfully to all the above checkboxes.

you are not even seeing what you are checking, look at the wiki and you will have your problem fixed

**Comment by Mei6666** [comment]
I checked that for the fact im not  running latest bloxstrap... wiki told me to make one of these,,,,,,,

**Comment by toofastforboo** [comment]
update your bloxstrap 
![Screenshot_20240905-215347-155](https://github.com/user-attachments/assets/5625c1b7-7ad5-45c7-9017-76e4d02c520f)

**Comment by Mei6666** [comment]
but it wouldnt make sense for it to just randomly stop working wayy after Jul 28.

**Comment by Mei6666** [comment]
I guess ill figure it out myself since this was useless.

**Comment by Mei6666** [comment]
v2.5.3 works perfectly fine so this is clearly on bloxshades side. For discords community channel: those who want multi instance back and were using 2.5.4, just downgrade once more.. also multi instance doesnt work with just bloxshade, but download another multi instance app with tthe feature enabled on bloxstrap, ur good to go.

**Comment by Mei6666** [comment]
bloxstrap*

**Comment by Storm-930** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
> * [x]  I am using the latest version of Bloxstrap.
> * [x]  I did not answer truthfully to all the above checkboxes.
> 
> ### What problem did you encounter?
> Getting error 403, was just trying to join a roblox game and it shows the error every time it launches bloxstrap. I have tried uninstalling and reinstalling, it didnt help. Not sure what would cause the problem since its worked up until now. Im using bloxstrap v2.5.4
> 
> ### Bloxstrap Log
> [Bloxstrap_20240905T235148Z.log](https://github.com/user-attachments/files/16901253/Bloxstrap_20240905T235148Z.log)

We know you haven't read any sort of wikis as you're using a downgraded version on purpose, and you remain adamant on using it, too bad for you, as older versions aren't supported. You also marked the 4th checkbox which means you didn't read shit (which you said you did) and shouldn't have opened the issue in the first place before reading what was supposed to be read.
