### ISSUE TITLE
[BUG]When I join a game the 21 graphics slider option doesn't apply to my game even though I have it enabled (I've tried redownloading bloxstrap an it hasn't fixed the issue) I've also tried reapplying it an unapplying it an rejoining multiple times to see if its any different but no luck it seems to be completely bugged for now.

### ISSUE THREAD

**Issue by tiger43434** [pizzaboxer/bloxstrap#2834]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/ad35c579-ce7e-4bbd-b2a7-1adef54e3167)
![image](https://github.com/user-attachments/assets/04c15ba3-542b-426e-86fd-5e735a8cecb1)

### Bloxstrap Log

N/A

**Comment by D4rkov** [comment]
Same issue for me.
