### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Toibidien191** [pizzaboxer/bloxstrap#2836]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

for some reason, bloxstrap does not working (i tried using fps unlocker on bloxstrap but its still using roblox's fps unlocker. yes i did restart my roblox) this also probably "the https://github.com/pizzaboxer/bloxstrap/issues/2825 reason"

### Bloxstrap Log

![e067bc81cd656a3b3374](https://github.com/user-attachments/assets/9e6d3881-e63e-49c9-9cf9-80e62cb4eae5)
![e03dbb90cd746a2a3365](https://github.com/user-attachments/assets/540c60e0-429f-43ac-ab38-4eb24a4e30a7)

**Comment by NabHeyka22** [comment]
spam that save button 👍

**Comment by Toibidien191** [comment]
> spam that save button 👍

i already did lol

**Comment by NabHeyka22** [comment]
then idk

**Comment by Toibidien191** [comment]
> then idk

im sorry but ur account description tell the reson why XD

**Comment by NabHeyka22** [comment]
i know
that's what i am

**Comment by pizzaboxer** [comment]
This sort of seems like your mods just aren't applying. Do you see the Bloxstrap launcher show when launching Roblox?

**Comment by Toibidien191** [comment]
> This sort of seems like your mods just aren't applying. Do you see the Bloxstrap launcher show when launching Roblox?

yes it show bloxstrap's logo when its launching

**Comment by Toibidien191** [comment]
i just relized i didnt try redownload my bloxstrap. so i did it and it fixed (im so dumb)
