### ISSUE TITLE
Merge Roblox Client Optimizer with Bloxstrap

### ISSUE THREAD

**Issue by Sahelantrophus** [pizzaboxer/bloxstrap#284]
https://github.com/L8X/Roblox-Client-Optimizer @pizzaboxer @EasternBloxxer @sitiom @nakoyasha @bluepilledgreat @Extravi

**Comment by EasternBloxxer** [comment]
We don't support pedophiles sorry

**Comment by pizzaboxer** [comment]
Damn how many telegrams did u have to send to get this issue opened

**Comment by stan2474** [comment]
Womp womp Womp

**Comment by nakoyasha** [comment]
boo womp

**Comment by Sahelantrophus** [comment]
> Damn how many telegrams did u have to send to get this issue opened

How many chicken tikkas did you burn in your lifetime?
