### ISSUE TITLE
[BUG] i set my graphics to 21 but is not showing. its only showing just 10

### ISSUE THREAD

**Issue by ErikaXGH** [pizzaboxer/bloxstrap#2844]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

please fix this

### Bloxstrap Log

N/A

**Comment by inuadicy** [comment]
im getting the same shi rn

**Comment by CosyHamster** [comment]
Roblox no longer supports the fast flag responsible for it. It'll probably be removed soon. 😔

**Comment by gabBC27** [comment]
fr bro

**Comment by pizzaboxer** [comment]
Read the Wiki. https://github.com/pizzaboxer/bloxstrap/wiki/'Use-advanced-graphics-quality-selector'-option-not-working

**Comment by gabBC27** [comment]
Bro is there any way to bring it back? That was the best part of bloxstrap
and the reason i downloaded it is to get that feature mann

**Comment by NabHeyka22** [comment]
no
