### ISSUE TITLE
[BUG]I enabled 21 graphics quality but only got 10 graphics quality in roblox

### ISSUE THREAD

**Issue by cyc-boop** [pizzaboxer/bloxstrap#2847]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

 Since roblox was updated yesterday, the quality of my images and text has suddenly dropped from 21 to 10. I had the quality set to 21, but when I entered the game it was directly reduced to 10. Please tell me what is going on.

### Bloxstrap Log

N/A
![Screenshot 2024-09-07 200721](https://github.com/user-attachments/assets/459a7b32-c7d0-4500-aaa0-5e14540da84e)
![Screenshot 2024-09-07 200933](https://github.com/user-attachments/assets/af5ba3be-335b-4ab1-b76f-6d42bd0b8c5d)

**Comment by NabHeyka22** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/'Use-advanced-graphics-quality-selector'-option-not-working
