### ISSUE TITLE
[BUG] advanced graphic quality selector not shown in game

### ISSUE THREAD

**Issue by NeroCries** [pizzaboxer/bloxstrap#2848]
### Acknowledgement of preliminary instructions

- [] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

https://github.com/user-attachments/assets/7b08869c-bcc6-4d02-b915-9b4dcabe14d0
so i renabled the graphic selector even if i reinstall bloxstrap, it wouldnt fix this problem

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/'Use-advanced-graphics-quality-selector'-option-not-working

**REMINDER: STOP PUTTING CHECKS LIKE YOU'RE APPLYING FOR A JOB**
