### ISSUE TITLE
[BUG] when i open my bloxstrap it says "waiting for other instances..."

### ISSUE THREAD

**Issue by darinyoo** [pizzaboxer/bloxstrap#2849]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so today i opened my bloxstrap and it just got stuck on "waiting for other instances..." i thought its normal but its been more then 20 mins im waiting for it and its still loading please fix this

### Bloxstrap Log

N/A

**Comment by darinyoo** [comment]
someone els reported that but it was installing and mine is lauching so im not sure if its the same issue

**Comment by pizzaboxer** [comment]
Can you open Task Manager, ensure that there's no Bloxstrap instances running, then try and launch again?

**Comment by darinyoo** [comment]
there is instances running and i did relunch it couple of times

**Comment by pizzaboxer** [comment]
> there is instances running

Then terminate them and try and launch again.

**Comment by darinyoo** [comment]
> > there is instances running
> 
> Then terminate them and try and launch again.

ight thanks it got fixed
