### ISSUE TITLE
bloxstrap tray icon duplicating

### ISSUE THREAD

**Issue by yoyeet961** [pizzaboxer/bloxstrap#285]
## the bloxstrap tray icon keeps duplicating every time roblox launches. but once I hover over one, it disappears.
![image](https://github.com/pizzaboxer/bloxstrap/assets/85292886/5f9e2d75-ec3e-43b4-9033-8f66ae70ce61)
please fix this issue in 2.4.0 ty

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/8378fced-a373-435e-9efa-4dffb463db05)
