### ISSUE TITLE
[BUG] when i go into my control panel then to programs i cant find bloxstrap

### ISSUE THREAD

**Issue by darinyoo** [pizzaboxer/bloxstrap#2850]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i checked my control panel and then to programs i couldnt find bloxstrap but i have the version files now i have to reinstall everytime i want to change my bloxstrap menu but now its gone too and i cant find any please fix this issue

**Comment by darinyoo** [comment]
i reinstalled bloxstrap alot of times and problem not solved :/

**Comment by pizzaboxer** [comment]
If you couldn't find it in the Control Panel programs list then how are you reinstalling it?

**Comment by darinyoo** [comment]
when u go in files u see the version i have to open it there
or delete this wasnt liek that before

**Comment by pizzaboxer** [comment]
Can you please clarify what you're doing? That doesn't explain how you're supposedly reinstalling it.

**Comment by darinyoo** [comment]
> Can you please clarify what you're doing? That doesn't explain how you're supposedly reinstalling it.
v.
better explanation: before when u dowlanded bloxstrap u would see the version in ur files example bloxstrap-v2.7.0 and when u go in control panel u would see bloxstrap (control panel then unistall programs) if i wanted unistall bloxstrap i had to delete it in files then go to control panel and delete there too, now i installed bloxstrap i see i have bloxstrap-v2.7.0 but when i go in control panel it isnt there (might be my pc problem im not sure) (enough or i should give better explanation?((sry for my bad grammer english isnt my first langauge)))

**Comment by pizzaboxer** [comment]
> if i wanted unistall bloxstrap i had to delete it in files then go to control panel and delete there too, 

Why would you do that? Why would you delete it from files before uninstalling from the Control Panel? It won't uninstall properly if you do that, and is what's causing your issue. Do you do this for every program you uninstall?

The easiest way to fix this is by enabling the "Force Roblox Reinstallation" option in the menu, and then launching Roblox. That should get it to show again.

**Comment by darinyoo** [comment]
> > if i wanted unistall bloxstrap i had to delete it in files then go to control panel and delete there too,
> 
> Why would you do that? Why would you delete it from files before uninstalling from the Control Panel? It won't uninstall properly if you do that, and is what's causing your issue. Do you do this for every program you uninstall?
> 
> The easiest way to fix this is by enabling the "Force Roblox Reinstallation" option in the menu, and then launching Roblox. That should get it to show again.

this only happens with bloxstrap and not any other programs and i did "force roblox installation" it still didnt appear in control panel and if i only  deleted bloxstrap from the control panel the file was still there (version)
