### ISSUE TITLE
[REQ] Add other FastFlags in order for unlimited FPS unlock to work

### ISSUE THREAD

**Issue by rainwashed** [pizzaboxer/bloxstrap#2851]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

These two flags are required for the FPS unlocker in Bloxstrap to function (i.e, unlimited FPS)

FFlagEnableVisBugChecks27 = False
FFlagEnableVisBugChecks27 = False

**Comment by NabHeyka22** [comment]
you can't go over 240 fps https://github.com/pizzaboxer/bloxstrap/wiki/Why-you-can't-(or-shouldn't)-go-faster-than-240-FPS

but, if you really need to, you can put this fflag in
{
  "FFlagTaskSchedulerLimitTargetFpsTo2402": "False"
}
