### ISSUE TITLE
[BUG] I have already enabled the 21 graphic slider but i doesn't work

### ISSUE THREAD

**Issue by coderPyCPP** [pizzaboxer/bloxstrap#2855]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The 21 grapich slider doesn't show and doesn't work

### Bloxstrap Log

N/A

**Comment by JuliaBecker19** [comment]
Roblox removed this Advanced Option sadly

**Comment by giaan11008** [comment]
me not 
![image](https://github.com/user-attachments/assets/ca3c9e5c-2636-468a-a890-2019c36c8860)
??

**Comment by NabHeyka22** [comment]
i can't understand shit in your image

**Comment by CactusTheGuy** [comment]
i can also confirm, 21 graphics slider is gone

**Comment by CactusTheGuy** [comment]
> me not ![image](https://private-user-images.githubusercontent.com/180534009/365433934-ca3c9e5c-2636-468a-a890-2019c36c8860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTg3MTUsIm5iZiI6MTcyNTc5ODQxNSwicGF0aCI6Ii8xODA1MzQwMDkvMzY1NDMzOTM0LWNhM2M5ZTVjLTI2MzYtNDY4YS1hODkwLTIwMTljMzZjODg2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMjI2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTI4ODVlMTcxOTE1ZTIyMWI1ZWU3Zjk3OGUwYjgzOWUzYTgyZjk0NDY3ZTI2NThmNjQxNmM4YzQ4YmNjNTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U9al-C7yapR1jOnGwCZqZCQPFNRgzUMbXU25j9CKE_8) ??

in translation of the image:
![image](https://github.com/user-attachments/assets/da2985f4-17ae-41a6-8486-6ca6f93cb744)
