### ISSUE TITLE
Can bloxstrap choose the server have low ping

### ISSUE THREAD

**Issue by doyouwanttobuildarotijohn** [pizzaboxer/bloxstrap#2856]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

In bedwars my ping so high,can bloxstrap choose the sever have low ping?

**Comment by NabHeyka22** [comment]
maybe just join servers in your region
or just get better wifi if it doesn't help you

**Comment by NabHeyka22** [comment]
"no." - Mr Storm with much love

**Comment by pizzaboxer** [comment]
No
