### ISSUE TITLE
[BUG] The advanced graphics quality selector is not working

### ISSUE THREAD

**Issue by IDontNeedAName0** [pizzaboxer/bloxstrap#2857]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The advanced graphics quality selector at Fast Flags is not working

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
so what you want to do is read the wiki carefully
