### ISSUE TITLE
New updated  version

### ISSUE THREAD

**Issue by skalBR** [pizzaboxer/bloxstrap#286]
I uploaded a new exe version  here:
shorturl.at/bBSU4

**Comment by xontron** [comment]
Do you think people will go tru that link? 😬

**Comment by nerdgh0st** [comment]
Yeah they're account history seems pretty sketchy
![image](https://github.com/pizzaboxer/bloxstrap/assets/68407522/ea8ca14b-5bc1-4f86-8695-d1e843fb62a4)

**Comment by nerdgh0st** [comment]
![notepad_AGjVwfvcWI](https://github.com/pizzaboxer/bloxstrap/assets/68407522/3e445ecb-cab4-4d43-9764-8b988b227913)
![WinRAR_7LHI4fCKX6](https://github.com/pizzaboxer/bloxstrap/assets/68407522/cb342c21-182a-4775-8718-f80e7ceadb63)
Comes with a ZIP file and it's likely malicious. I didn't run the "App" file for safety

**Comment by nerdgh0st** [comment]
And Windows Defender says it's malicious

**Comment by totallyphysicallypossible** [comment]
yeah no
![image](https://github.com/pizzaboxer/bloxstrap/assets/94307704/b4592fd4-6ac5-4ccc-92f4-b6fc8376d3a7)
https://www.virustotal.com/gui/file/17098a3f23cfd085c44d454a4ca5f300e068e8632fa895611722f16b07762bdb/detection

**Comment by pizzaboxer** [comment]
oh
