### ISSUE TITLE
Framerate Gone

### ISSUE THREAD

**Issue by ColinUndPuro** [pizzaboxer/bloxstrap#2861]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Why did you remove the Framerate Graphics because it is not in my bloxtrap
![image](https://github.com/user-attachments/assets/9c2fa24f-3fc4-4633-a211-b1446932c814)

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
What?
