### ISSUE TITLE
[BUG] FPS unlocker doesn't work with Bloxstrap.

### ISSUE THREAD

**Issue by minecraftman366** [pizzaboxer/bloxstrap#2866]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

FPS unlocker doesn't work with Bloxstrap. But it works fine with normal Roblox launcher. HELP!

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
so what you wanna do is read the wiki, find the error that you're occurring, and read the possible fixes

**Comment by minecraftman366** [comment]
> so what you wanna do is read the wiki, find the error that you're occurring, and read the possible fixes

Very helpful man. I 100% didn't search for it on the wiki or from other sources for the past 3 days to fix this issue.

**Comment by NabHeyka22** [comment]
sorry
it's just that people these days put checkmars like it's fucking nothing

**Comment by Encythe** [comment]
Can you send your entire FFlag list?

**Comment by minecraftman366** [comment]
> Can you send your entire FFlag list? Also, what FPS Unlocker are you trying to use? Is it the built-in Roblox one or the one bundled with Bloxstrap?

I currently don't use anything. No FastFlags or FPS unlockers. Only base roblox, downloaded from Bloxstrap. I tried reinstalling 5 times already

**Comment by Encythe** [comment]
Bloxstrap sets the `DFIntTaskSchedulerTargetFps` FFlag to your monitor's refresh rate by default, can you try checking it in the Bloxstrap Menu?

**Comment by minecraftman366** [comment]
> Bloxstrap sets the `DFIntTaskSchedulerTargetFps` FFlag to your monitor's refresh rate by default, can you try checking it in the Bloxstrap Menu? If it isn't 0, set it to 0 and relaunch Roblox using Bloxstrap.
> 
> ![image](https://private-user-images.githubusercontent.com/38755801/365788695-01c2f9af-a74a-406e-83e8-e27061513217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTEzNTEsIm5iZiI6MTcyNTkxMTA1MSwicGF0aCI6Ii8zODc1NTgwMS8zNjU3ODg2OTUtMDFjMmY5YWYtYTc0YS00MDZlLTgzZTgtZTI3MDYxNTEzMjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE5NDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGZkNTk1YTJiZmMxZTRhZWE0OWMyZjQ4MDkxNDRiMTVhMGYxY2M3MDU3MWU4MTllNzJjMmFmZGY3ODllN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VEA1ePAb9x2PCm9RrkQ-Ntx8Fd-K0AJpBA0kOlev_DU)

It's set to 0. I don't understand what's causing Bloxstrap to cap fps to 60 when in fullscreen. normal roblox doesn't have that problem.

**Comment by Encythe** [comment]
Well, I'm out of ideas then, I'll divert you to the wiki entry [Roblox is still capped to 60 FPS](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter) to give you an idea of where to start. If you have already checked the Wiki, I'm dry out of ideas.

**Comment by minecraftman366** [comment]
> Well, I'm out of ideas then, I'll divert you to the wiki entry [Roblox is still capped to 60 FPS](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-is-still-capped-to-60-FPS-after-raising-the-limiter) to give you an idea of where to start. If you have already checked the Wiki, I'm dry out of ideas.

Thank you for your time.

**Comment by NabHeyka22** [comment]
> > Bloxstrap sets the `DFIntTaskSchedulerTargetFps` FFlag to your monitor's refresh rate by default, can you try checking it in the Bloxstrap Menu? If it isn't 0, set it to 0 and relaunch Roblox using Bloxstrap.
> > ![image](https://private-user-images.githubusercontent.com/38755801/365788695-01c2f9af-a74a-406e-83e8-e27061513217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTEzNTEsIm5iZiI6MTcyNTkxMTA1MSwicGF0aCI6Ii8zODc1NTgwMS8zNjU3ODg2OTUtMDFjMmY5YWYtYTc0YS00MDZlLTgzZTgtZTI3MDYxNTEzMjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE5NDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGZkNTk1YTJiZmMxZTRhZWE0OWMyZjQ4MDkxNDRiMTVhMGYxY2M3MDU3MWU4MTllNzJjMmFmZGY3ODllN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VEA1ePAb9x2PCm9RrkQ-Ntx8Fd-K0AJpBA0kOlev_DU)
> 
> It's set to 0. I don't understand what's causing Bloxstrap to cap fps to 60 when in fullscreen. normal roblox doesn't have that problem.

are you trying to cap at more fps or like what's going on here?

**Comment by Encythe** [comment]
> are you trying to cap at more fps or like what's going on here?
It seems as though OP is trying to use the built-in Roblox FPS unlocker, but on Bloxstrap something is causing it to not surpass 60 FPS, even with the Framerate limit configured to `0` within the Bloxstrap Menu.

**Comment by minecraftman366** [comment]
> > are you trying to cap at more fps or like what's going on here?
> 
> It seems as though OP is trying to use the built-in Roblox FPS unlocker, but on Bloxstrap something is causing it to not surpass 60 FPS, even with the Framerate limit configured to `0` within the Bloxstrap Menu.

Nothing works. I tried EVERY. SINGLE. FPS. UNLOCKER.

**Comment by NabHeyka22** [comment]
are you on a laptop

**Comment by Encythe** [comment]
> are you on a laptop

It uncaps just fine as per the original post in an unmodified fresh install of Roblox without Bloxstrap, but launching with Bloxstrap causes the 60 FPS limit to be enforced for some ungodly reason

**Comment by minecraftman366** [comment]
> are you on a laptop

Yes. However, I'm plugged in AC with everything set to performance mode. Including the nvidia settings.

**Comment by minecraftman366** [comment]
I think I found the problem. Bloxstrap just doesn't want to disable exclusive Fullscreen.

**Comment by NabHeyka22** [comment]
and you made sure you modified your power settings right?

**Comment by minecraftman366** [comment]
> and you made sure you modified your power settings right?

Yes. I am sure

**Comment by minecraftman366** [comment]
> I think I found the problem. Bloxstrap just doesn't want to disable exclusive Fullscreen.

Anyone have this problem?

**Comment by Encythe** [comment]
> I think I found the problem. Bloxstrap just doesn't want to disable exclusive Fullscreen.

This is really only an issue if you use ALT + ENTER to enter Fullscreen. If you're pressing F11 then it shouldn't happen, yet it does, right?

**Comment by pizzaboxer** [comment]
Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by minecraftman366** [comment]
> Upload your configuration: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by minecraftman366** [comment]
I'm going to

**Comment by minecraftman366** [comment]
I'm going to close the issue

**Comment by TinLikesCode** [comment]
the bloxstrap fps unlocker isnt working for me, ive set it to 10000

**Comment by nabheyka880** [comment]
you shouldn't go over 240 fps for some roblox thing
also why do you need 10k fps

**Comment by TinLikesCode** [comment]
i dont? 10k is like unlocked

**Comment by nabheyka880** [comment]
oh my bad
but yeah roblox caps fps at 240 so stuff doesn't break
you can read this if you want
https://github.com/bloxstraplabs/bloxstrap/wiki/Why-you-can't-(or-shouldn't)-go-faster-than-240-FPS

**Comment by TinLikesCode** [comment]
so can you not? Welp even when I cap it at 165 it doesnt work

**Comment by nabheyka880** [comment]
you're capping at 60?

**Comment by TinLikesCode** [comment]
no i set the cap at 240 yet on bloxstrap i set it to 165, it still doesnt work

**Comment by nabheyka880** [comment]
so at how much are you capping at

**Comment by TinLikesCode** [comment]
165 on bloxstrap, 240 on roblox

**Comment by nabheyka880** [comment]
weird
