### ISSUE TITLE
[BUG] V2 Menu (2022 version) is not working.

### ISSUE THREAD

**Issue by razeorr** [pizzaboxer/bloxstrap#2867]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

V2 menu (2022) loads in as the classic menu.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
{"FIntNewInGameMenuPercentRollout3": "1000"} put this FFlag in for it to work

**Comment by razeorr** [comment]
> {"FIntNewInGameMenuPercentRollout3": "1000"} put this FFlag in for it to work

Fixed the menu visibly, but removed the option for the "advanced quality" option. I can only set it to ten. Is this actually happening or just a visual bug?

**Comment by razeorr** [comment]
> if you're talking about the advanced quality, roblox removed the fflag that made it work, so the option will be gone next update

I see, thank you.  I didn't realize the fflag was being removed. Resolved!

**Comment by razeorr** [comment]
Resolved.
