### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\marat\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by Hendarga** [pizzaboxer/bloxstrap#2868]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

idk

### Bloxstrap Log

N/A1

**Comment by NabHeyka22** [comment]
send the logs
