### ISSUE TITLE
[BUG] my fps isnt loading

### ISSUE THREAD

**Issue by darinyoo** [pizzaboxer/bloxstrap#2869]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

for example i had 35 fps before now i puted 90 fps and relunch roblox it doesnt work and stays on the same old fps, this issue happens with my fast flag settings too (not fast flag editor)

**Comment by NabHeyka22** [comment]
wdym you put 90 fps
that's not how it works

**Comment by darinyoo** [comment]
> wdym you put 90 fps that's not how it works

wym?

**Comment by NabHeyka22** [comment]
you said you "put 90 fps" but what do you mean

**Comment by darinyoo** [comment]
> you said you "put 90 fps" but what do you mean

frames per second?

**Comment by NabHeyka22** [comment]
no i meant by
"put 90 fps"
what do you by putting 90 fps

**Comment by darinyoo** [comment]
before i changed my fps to 35 fps then after couple some weeks i wanted to change the fps to 90 but it doesnt work and still on the old fps in game (i clicked save)

**Comment by NabHeyka22** [comment]
uuh
get a better pc

**Comment by darinyoo** [comment]
its not based on pc my pc can handle 90 fps. even if i low the fps to 30 its still 35 fps

**Comment by NabHeyka22** [comment]
aand have you checked the framerate limit in your bloxstrap menu

**Comment by darinyoo** [comment]
yes ofc

**Comment by darinyoo** [comment]
;-;

**Comment by darinyoo** [comment]
> You set your limit as 35 and now you're unable to change it?

ye, if i have to change the fps for example im 35fps and if i want to put on 30fps i need to put 30 in frames per second then enable "force roblox reinstallation" then it changes, it doesnt change normaly wich is kinda annoying (sorry for my bad grammer)

**Comment by darinyoo** [comment]
> > You set your limit as 35 and now you're unable to change it?
> 
> ye, if i have to change the fps for example im 35fps and if i want to put on 30fps i need to put 30 in frames per second then enable "force roblox reinstallation" then it changes, it doesnt change normaly wich is kinda annoying (sorry for my bad grammer)

i have to do that every time i want to change my frames per second

**Comment by bluepilledgreat** [comment]
Can you send your log file the next time modifications/flags are not applied?

**Comment by pizzaboxer** [comment]
>  then enable "force roblox reinstallation" then it changes,

That seems to imply that the mod check is being skipped becuase it thinks Roblox is still running. Like Matt said, upload your latest log file from `%localappdata%\Bloxstrap\Logs` the next time this happens.

**Comment by darinyoo** [comment]
> Can you send your log file the next time modifications/flags are not applied?

how can i do that?

**Comment by pizzaboxer** [comment]
Open the `%localappdata%\Bloxstrap\Logs` folder (copy and paste the path into the windows search bar), sort by date modified, send the latest file here.
