### ISSUE TITLE
I have downloaded the windowsdesktop runtime but it is still showing up, why?

### ISSUE THREAD

**Issue by Thatoneguy1432** [pizzaboxer/bloxstrap#287]
I have tried deleting both then downloading them both deleting one and it still doesn't work I have done it so many times and have no idea how to work the windowsdesktop thing and all you guys say in the how to download is just to install it which I have and it should work just fine but it is not if anyone could help me that would be greatly appreciated. 
Thanks, Thatoneguy1432

**Comment by Thatoneguy1432** [comment]
it doesn't show but I have them installed I swear

**Comment by Thatoneguy1432** [comment]
Do you have discord because I can screen share it to you

**Comment by Thatoneguy1432** [comment]
I don't know how to run it

**Comment by pizzaboxer** [comment]
You just run the .exe file?

**Comment by Thatoneguy1432** [comment]
it just set up

**Comment by pizzaboxer** [comment]
What? What does that mean?

**Comment by Thatoneguy1432** [comment]
okay now its installed what do I do konw

**Comment by pizzaboxer** [comment]
Now what happens if you try to run Bloxstrap?

**Comment by Thatoneguy1432** [comment]
the popup is still there

**Comment by pizzaboxer** [comment]
> Can I see the list of runtimes you have installed? Just search for them under Apps and Features in Settings.
> 
> ![image](https://user-images.githubusercontent.com/41478239/243783918-bb5a58af-a478-4079-bc81-093282fca4b6.png)

Let me see the list as I mentioned here.

**Comment by Thatoneguy1432** [comment]
![Settings 6_6_2023 12_54_01 PM](https://github.com/pizzaboxer/bloxstrap/assets/135738445/5c93fb94-8642-4969-95b2-b3d55f536c1b)

**Comment by Thatoneguy1432** [comment]
dont mind my name its a old account

**Comment by pizzaboxer** [comment]
Oh, I can't actually see the full name of it. Use this button here button to change to list view so I can see it.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/6a136f89-3e5e-4fd2-a58c-43c6f3d3f6d7)

**Comment by Thatoneguy1432** [comment]
![Settings 6_6_2023 12_58_15 PM](https://github.com/pizzaboxer/bloxstrap/assets/135738445/033b36d3-9c38-4a4a-966a-3e0a1766d960)

**Comment by pizzaboxer** [comment]
You're still getting the popup when trying to run Bloxstrap?

**Comment by Thatoneguy1432** [comment]
yes

**Comment by Thatoneguy1432** [comment]
![Bloxstrap-v2 3 0-x64 exe 6_6_2023 12_59_12 PM](https://github.com/pizzaboxer/bloxstrap/assets/135738445/64f725dd-7c13-4ea2-a2bf-c28bc5b08eb4)

**Comment by Thatoneguy1432** [comment]
for some reason won't show my whole screen but that is still popping up

**Comment by Thatoneguy1432** [comment]
I just deleted bloxstrap then re installed it and it did it again

**Comment by pizzaboxer** [comment]
Weird, that definitely should be working then. See if the [Program Install and Uninstall Troubleshooter](https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d) does anything. When you run it, choose "Installing", and then "Not Listed" if you're prompted to choose a program.

**Comment by Thatoneguy1432** [comment]
it just pops up nothing before or after and I can't access it at all and not my anti virus either because that doesn't go off without telling me

**Comment by Thatoneguy1432** [comment]
I can show you if you have discord but other than that I don't know how to explain (my discord: Audi#0900)

**Comment by Thatoneguy1432** [comment]
I will try again tomorrow

**Comment by UncappedLegacy** [comment]
hi my friend is having this same issue, his discord is aqua#4827 can you help him?

**Comment by Thatoneguy1432** [comment]
> hi my friend is having this same issue, his discord is aqua#4827 can you help him?

I haven't fixed this issue I think it is just an anti virus thing but I have stopped trying if he is having this issue there is no other way to install it you just can't sorry

**Comment by pizzaboxer** [comment]
> hi my friend is having this same issue, his discord is aqua#4827 can you help him?

We have a Discord server.

**Comment by pizzaboxer** [comment]
Forgot to mention this, but if you open the installer for the runtime again, it should give you the option to "repair". Does anything happen if you do that?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
