### ISSUE TITLE
[BUG] i try to open it and it doesnt open

### ISSUE THREAD

**Issue by DylanChillin** [pizzaboxer/bloxstrap#2871]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i open play roblox the bloxstrap shortcut and it says starting roblox then it closes and roblox doesnt open

https://github.com/user-attachments/assets/a6a869c9-5e18-4ca2-80f6-b97f459d2488

### Bloxstrap Log

[Bloxstrap_20240911T023222Z.log](https://github.com/user-attachments/files/16957122/Bloxstrap_20240911T023222Z.log)

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by Fixile76** [comment]
fermer rivatunner les gars

**Comment by Dreamwxve** [comment]
yeah same here, i clean installed a fresh copy of stock windows 11 with literally nothing changed (even no bloatware removed, nothing) and this persists. Normal roblox is fine to a degree

**Comment by pizzaboxer** [comment]
@Dreamwxve Upload your configuration please: https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration

**Comment by Dreamwxve** [comment]
[ClientAppSettings.json](https://github.com/user-attachments/files/17085976/ClientAppSettings.json)
[State.json](https://github.com/user-attachments/files/17085977/State.json)
[Settings.json](https://github.com/user-attachments/files/17085978/Settings.json)

Just to note  the issue persists even on default configs with nothing adjusted

**Comment by pizzaboxer** [comment]
> Just to note the issue persists even on default configs with nothing adjusted

Try disabling the option to allow Bloxstrap to manage Fast Flags, see if that does anything.

**Comment by DylanChillin** [comment]
oh i forgot to say i fixed it, it was because of vulkan
