### ISSUE TITLE
[BUG] Fast Flags presets not working.

### ISSUE THREAD

**Issue by Eattz** [pizzaboxer/bloxstrap#2877]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

After saving my flast flag presets, bloxstrap doesn't apply them whenever i open roblox.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
send the fflags

**Comment by Eattz** [comment]
> send the fflags

you want a screenshot?

**Comment by Eattz** [comment]
![Screenshot 2024-09-12 115238](https://github.com/user-attachments/assets/e1cf257c-7a95-41a5-ab7b-1044de487691)
![Screenshot 2024-09-12 115250](https://github.com/user-attachments/assets/1a2a35a1-fdb5-481e-b606-b2f114081985)

**Comment by Eattz** [comment]
> ![Screenshot 2024-09-12 115238](https://private-user-images.githubusercontent.com/181377083/366960650-e1cf257c-7a95-41a5-ab7b-1044de487691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTY3MTYsIm5iZiI6MTcyNjE1NjQxNiwicGF0aCI6Ii8xODEzNzcwODMvMzY2OTYwNjUwLWUxY2YyNTdjLTdhOTUtNDFhNS1hYjdiLTEwNDRkZTQ4NzY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDk3NGZjMmJiYTRhOTkxZjU0M2RiZWU3OWYyZDg5YzFjZjAxMjI3OWUxODcxNWQzYmNlOWU3OGU0ZGY5ODcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._fBuo5X2Fu5cjmDDJVxWb4ySVnkLFImxiifKgaUhkYc) ![Screenshot 2024-09-12 115250](https://private-user-images.githubusercontent.com/181377083/366960661-1a2a35a1-fdb5-481e-b606-b2f114081985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTY3MTYsIm5iZiI6MTcyNjE1NjQxNiwicGF0aCI6Ii8xODEzNzcwODMvMzY2OTYwNjYxLTFhMmEzNWExLWZkYjUtNDgxZS1iNjA2LWIyZjExNDA4MTk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDQwYmRjMGVhMWViNzFlNDkyMTdmM2EzODRjNTdkZmExMjcwNDFmM2EzYTc0OTRmOWY2Yzc4M2VjMzkzYjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cqp4svZfNzWcDve8a-w6VR0XrPcK1rvuco19wFx2-Zw)

the fast flags do not apply to my game when i launch roblox even after i saved them

**Comment by NabHeyka22** [comment]
for the framerate limit, you can't go over 240 fps, for the advanced quality sector, the fflag that made it work is now removed and you can't do anything

**Comment by Eattz** [comment]
> for the framerate limit, you can't go over 240 fps, for the advanced quality sector, the fflag that made it work is now removed and you can't do anything

oh so the adanced quality selector is permanently down?

**Comment by Eattz** [comment]
> yes

oh alright, thanks for the help.
