### ISSUE TITLE
[BUG] Im Getting The "BloxStrap Is Unable To Connect To Roblox" Error. (Regular Roblox Launcher Works Btw)

### ISSUE THREAD

**Issue by LexiRexi** [pizzaboxer/bloxstrap#2878]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image_2024-09-12_142225543](https://github.com/user-attachments/assets/ad2c8464-7fea-496d-8c43-fe822412b0d8)
I Saw Another Issue And You Said It Was An Issue With The Wifi But Its Not Because I Have Very Good Wifi. I Dont Know How To Fix This, Its Been About 1 Months Of Trying To Get It To Work. If You Know How To Fix This Please Tell Me :(.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
are you using a vpn

**Comment by LexiRexi** [comment]
> are you using a vpn

No

**Comment by NabHeyka22** [comment]
do you live in turkey by any chance

**Comment by LexiRexi** [comment]
> do you live in turkey by any chance

no im in canada

**Comment by LexiRexi** [comment]
wait i have a log file didnt know where it was before
[Bloxstrap_20240912T191329Z.log](https://github.com/user-attachments/files/16984542/Bloxstrap_20240912T191329Z.log)
idk if its useful or not

**Comment by pizzaboxer** [comment]
This is an issue from either an antivirus interfering or a VPN being used. Check to make sure there isn't anything like those described that would be messing with it.

**Comment by xiao4lifes** [comment]
did anyone figure out yet i have this error and now to this day is still cant fix it

**Comment by MrJoneshere** [comment]
i am getting the same error, im not using vpn or antivirus, this is really weird

**Comment by navdeep302** [comment]
any update??

**Comment by alper4343** [comment]
hello i live in turkey how do i fix it can someone help please?

**Comment by OmegaAce-xyro** [comment]
Bro check if you are using dns

**Comment by navdeep302** [comment]
> Bro check if you are using dns

I am using dns and I turned it off and it's the same

**Comment by cumulonimbush** [comment]
> hello i live in turkey how do i fix it can someone help please?

ik, it is too late, but if you use goodbye DPI Turkey fork along with it, it should probably work. I assume it is because Roblox is banned there. Sad to deal with these shenanigans just to be able to make kids play what they want
