### ISSUE TITLE
building shadows are real weird

### ISSUE THREAD

**Issue by lmaoooderek** [pizzaboxer/bloxstrap#288]
i have no idea why the building shadows are so wonky and weird with bloxtrap? but can we get a fix for this??
![image](https://github.com/pizzaboxer/bloxstrap/assets/84254036/3a0657ef-2cc0-4eec-8fae-7f4af430cfb2)

**Comment by pizzaboxer** [comment]
That's just how Roblox does lighting. There's nothing I can do about that.
