### ISSUE TITLE
[BUG] FFlags are not loading into roblox

### ISSUE THREAD

**Issue by Selfd0x** [pizzaboxer/bloxstrap#2880]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when i save FFlags in the bloxstrap menu everything is fine, but when i go to roblox through bloxstrap the FFlags dont load

### Bloxstrap Log

[Bloxstrap_20240913T072332Z.log](https://github.com/user-attachments/files/16990097/Bloxstrap_20240913T072332Z.log)

**Comment by NabHeyka22** [comment]
are you sure that bloxstrap is the one running and not the normal roblox

**Comment by Selfd0x** [comment]
ye i sure but 
![изображение](https://github.com/user-attachments/assets/5a3ecaaf-994a-4d5b-9988-788230ab6b2f)
![изображение](https://github.com/user-attachments/assets/7eeec521-b3fb-4661-a3a0-34f304d17c30)

**Comment by JoxZer** [comment]
this specific fflag got removed by roblox

**Comment by Selfd0x** [comment]
bruah

**Comment by user1126s** [comment]
same issue as #2885 and #2894. they don't work. issue closed
