### ISSUE TITLE
[BUG] FFlags dont work

### ISSUE THREAD

**Issue by L0cas123dk** [pizzaboxer/bloxstrap#2881]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

every time i click export JSON it says this
![Skærmbillede 2024-09-13 183425](https://github.com/user-attachments/assets/37117642-84c3-444f-9ed1-d604e570f693)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
...

**Comment by NabHeyka22** [comment]
are you fucking serious dude
like, THAT'S WHAT IT'S SUPPOSED TO SAY!!

**Comment by JoxZer** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
> * [x]  I am using the latest version of Bloxstrap.
> * [ ]  I did not answer truthfully to all the above checkboxes.
> 
> ### What problem did you encounter?
> every time i click export JSON it says this ![Skærmbillede 2024-09-13 183425](https://private-user-images.githubusercontent.com/132158838/367374407-37117642-84c3-444f-9ed1-d604e570f693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDY4NDMsIm5iZiI6MTcyNjI0NjU0MywicGF0aCI6Ii8xMzIxNTg4MzgvMzY3Mzc0NDA3LTM3MTE3NjQyLTg0YzMtNDQ0Zi05ZWQxLWQ2MDRlNTcwZjY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNjU1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzA5MmI1MjRjZjZmYmI1NmY3YmM1OTM3ZjY3OWViZGRkZGZiYWE2NTE3M2UyMWRjYTlhMWM0ZTRmZmJjZjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y9MmsL_uUU1HlSVFw62WHHCSbkeKy9d4jD5havdFgdQ)
> 
> ### Bloxstrap Log
> N/A

tried opening a notepad and clicking CTRL + V on your keyboard?

**Comment by EasternBloxxer** [comment]
And what exactly is the issue here? It is exporting the flags in json format to your clipboard.

**Comment by NabHeyka22** [comment]
> And what exactly is the issue here?
good question

**Comment by bluepilledgreat** [comment]
I am going to kill myself
