### ISSUE TITLE
'C:\Users\(username)\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by Cadenza2007** [pizzaboxer/bloxstrap#2882]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I tried looking for a similar fix, but have found nothing helpful at this time. 

### Bloxstrap Log

[Bloxstrap_20240913T220043Z.log](https://github.com/user-attachments/files/16999816/Bloxstrap_20240913T220043Z.log)

**Comment by ErikaXGH** [comment]
you must take ownership on the path
