### ISSUE TITLE
[REQ] Put the old purchasing a gamepass Ui in the mods section

### ISSUE THREAD

**Issue by ErikaXGH** [pizzaboxer/bloxstrap#2884]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I suggest I want to add the old Ui while purchasing a gamepass In the game

**Comment by pizzaboxer** [comment]
What does that look like?

**Comment by bluepilledgreat** [comment]
We can't magically restore old UI.
