### ISSUE TITLE
[BUG] Fast flags not working

### ISSUE THREAD

**Issue by RandomCandyCane** [pizzaboxer/bloxstrap#2885]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When bloxstrap updated it didn't show the 21 bars of graphics and i thought they changed it but no it didn't load in fast flags or nothing

### Bloxstrap Log

N/A

**Comment by RandomCandyCane** [comment]
Fast flags not working or anything

**Comment by darinyoo** [comment]
roblox removed it so u cant use it anymore

**Comment by user1126s** [comment]
issue #2894  and fflags dont work. issue closed
