### ISSUE TITLE
[BUG] Discord rpc

### ISSUE THREAD

**Issue by MCHAMSTERYT2** [pizzaboxer/bloxstrap#2887]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

For a while the discord rpc hasn't been working properly for me and all it shows is just the basic playing roblox status instead of the bloxstrap status and i've checked the wiki and none of the problem causes apply to me and i have discord rpc enabled in the bloxstrap settings and i have the latest version of bloxstrap (2.7.0) but this is all it shows as the status
![Discord_oGxnXcpjtp](https://github.com/user-attachments/assets/3ee39a06-729e-41bd-a576-aa3e72f844b3)

### Bloxstrap Log

[Bloxstrap_20240914T142621Z.log](https://github.com/user-attachments/files/17002807/Bloxstrap_20240914T142621Z.log)

**Comment by NabHeyka22** [comment]
so what i want you to do is actually read the wiki

**Comment by MCHAMSTERYT2** [comment]
> so what i want you to do is actually read the wiki

I already did that's why i said none of the problem causes apply to me as i don't have discord installed as administrator and i have activities enabled on discord

**Comment by NabHeyka22** [comment]
did you make sure bloxstrap is the one running and not the normal roblox

**Comment by MCHAMSTERYT2** [comment]
> did you make sure bloxstrap is the one running and not the normal roblox

Yeah it gives me the server information on launch and to check again i registered bloxstrap to be the web launcher again and the rpc still isn't showing as the bloxstrap one

**Comment by MCHAMSTERYT2** [comment]
Oh and also it seems bloxstrap is being registered as contextmenucontainer for some reason

**Comment by pizzaboxer** [comment]
Bloxstrap isn't detecting Discord. The Wiki page should've covered your issue. Are you using stock unmodified Discord?

**Comment by MCHAMSTERYT2** [comment]
> Bloxstrap isn't detecting Discord. The Wiki page should've covered your issue. Are you using stock unmodified Discord?

I do have modified discord but i don't have the norpc plugin enabled at all and i have the rpc settings enabled and i don't have it installed as administrator

**Comment by pizzaboxer** [comment]
I'm closing this because this is an issue with Discord, not with Bloxstrap. You may want to try installing stock Discord, or reinstalling and reconfiguring your modified Discord from scratch.
