### ISSUE TITLE
[BUG] System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by Virusthreatprotection** [pizzaboxer/bloxstrap#2889]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i am trying to download roblox on bloxstrap 2.5.4, and it keeps showing the error message "System.exception: signature does not match"
![{7CDAEA16-3304-43BC-837E-4E615E5E3416}](https://github.com/user-attachments/assets/55d422e5-7713-4ee0-836d-bc2a9a0f8ae7)

### Bloxstrap Log

[Bloxstrap_20240914T153427Z.log](https://github.com/user-attachments/files/17002992/Bloxstrap_20240914T153427Z.log)

**Comment by bluepilledgreat** [comment]
Read the warning on the download page moron

**Comment by Virusthreatprotection** [comment]
> Read the warning on the download page moron

kk
