### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by FrostedCryo** [pizzaboxer/bloxstrap#289]
my game isn't loading everything, like buildings, the map etc

**Comment by pizzaboxer** [comment]
Are you sure that's a Bloxstrap problem? What should it normally look like and what does it end up looking like?

**Comment by pizzaboxer** [comment]
Does using the normal Roblox bootstrapper fix your issue? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by FrostedCryo** [comment]
yes, i think so, it never had the problem when I was using the bloxstrap
launcher, I would have to rejoin a couple of times for it to be fixed.

**Comment by pizzaboxer** [comment]
Does this happen in any game or just one game in particular?

**Comment by FrostedCryo** [comment]
it's random, my assets and character don't load all the time in different
games i play, sometimes they fully load and sometimes they don't

**Comment by pizzaboxer** [comment]
You weren't that clear in your previous reply, so I'll ask again. Does it happen with Roblox's normal launcher?

**Comment by FrostedCryo** [comment]
no

**Comment by pizzaboxer** [comment]
Can I see your FastFlag list? Open the menu, go to the FastFlags tab, open ClientAppSettings.json, and paste the whole contents of the file here.

**Comment by FrostedCryo** [comment]
{
  "DFIntTaskSchedulerTargetFps": "9999",
  "FFlagDisableNewIGMinDUA": "True",
  "FFlagEnableInGameMenuV3": "False",
  "FFlagFixGraphicsQuality": "True",
  "FFlagDebugGraphicsPreferD3D11": "True",
  "FFlagHandleAltEnterFullscreenManually": "False"
}

**Comment by pizzaboxer** [comment]
Oh, forgot about this. If this is still happening, can you get Roblox's latest log file from %localappdata%\Roblox\logs and send it here?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
