### ISSUE TITLE
[BUG] hide gui thingy does not work at all

### ISSUE THREAD

**Issue by dustnuts7167** [pizzaboxer/bloxstrap#2890]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

yeah the title says it all, and yes i am in the roblox group

the weirdest part about it is the fact that it worked just ONCE, afterwards it just stopped working completely 😭😭

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment]
This isn't an issue with Bloxstrap, the issue here would be Roblox not recognizing the keystrokes for some reason. Can't really help you out there, sorry.
