### ISSUE TITLE
[BUG] advanced graphics quality selector is bugged . it doesn't work

### ISSUE THREAD

**Issue by exie132** [pizzaboxer/bloxstrap#2894]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

advanced graphics quality selector is bugged . it doesn't work

### Bloxstrap Log

N/A1

**Comment by user1126s** [comment]
Its not bloxstrap error, roblox has removed it and broken fastflags. issue closed
