### ISSUE TITLE
[BUG] Guys I'm using bloxstrap and bloxshade and my fps is stuck on 60 fps and i turned of max frame rate

### ISSUE THREAD

**Issue by H3RO-A** [pizzaboxer/bloxstrap#2895]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I just got Bloxshade I noticed that my fps was stuck at 60 when it used to be more without it with Bloxstrap.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
no wonder

**Comment by NabHeyka22** [comment]
you think your fps will be like the exact same with some shaders?

**Comment by H3RO-A** [comment]
> you think your fps will be like the exact same with some shaders?

Do u have a fix? I used to run over 100+ fps

**Comment by VeryCoolGuy-TSC** [comment]
check roblox settings.

**Comment by bluepilledgreat** [comment]
This is clearly not our problem then.
