### ISSUE TITLE
[BUG] No changes

### ISSUE THREAD

**Issue by oscrack-burnts-stepper** [pizzaboxer/bloxstrap#2896]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

(Translate this pls)Instalé Bloxstrap con todas las configuraciones del menú del mismo, lo instalé desde github (el oficial) y al ejecutarlo y guardar los cambios y luego iniciar el Roblox, no hay ni siquiera con cambio de aspecto, como por ejemplo lo de la opción de 21 niveles de gráfico en vez de 10, la activé y al ejecutar el Roblox, no aparecía ningún cambio, ni una opción diferente ni nada.

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Roblox has removed the 21 graphics quality flag.

**Comment by oscrack-burnts-stepper** [comment]
Oke
