### ISSUE TITLE
[BUG] downloading bloxtrap on mobile

### ISSUE THREAD

**Issue by Mhd39186** [pizzaboxer/bloxstrap#2898]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Sir,can I know how to download bloxtrap on mobile
I would be thankful if you answered..

**Comment by NabHeyka22** [comment]
bloxstrap is only available on windows

**Comment by user1126s** [comment]
issue closed

**Comment by bluepilledgreat** [comment]
bruh
