### ISSUE TITLE
[BUG] FFlag `FFlagFixGraphicsQuality` deprecation

### ISSUE THREAD

**Issue by headquarter8302** [pizzaboxer/bloxstrap#2902]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

On Roblox client version 642, the extended graphics quality FFlag setting doesn't seem to work. The setting is correctly applied to Bloxstrap's modification config, but it doesn't have an effect on Roblox anymore.

![image](https://github.com/user-attachments/assets/cefb7581-0b36-4875-9a1c-e40a896f5f5b)

Bloxstrap Version 2.7.9

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
how come you put a check on "I've read the Wiki" when there is literally a post saying the fix?

**Comment by headquarter8302** [comment]
The option is still there in the Bloxstrap menu. My thought is that the project maintainers would need to remove the toggle in the FFlag section as to not cause confusion

**Comment by headquarter8302** [comment]
It seems that I didn't do my due diligence because #2812 exists, apologies
