### ISSUE TITLE
[BUG] vc

### ISSUE THREAD

**Issue by sawtoothtulip86** [pizzaboxer/bloxstrap#2903]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

**help me everytime when i join to any roblox game my vc doesn't work idk why but help me
![لقطة شاشة 2024-09-18 154413](https://github.com/user-attachments/assets/fb5b60ff-4914-49cc-8775-846706b7b2f2)
**

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
not a bloxstrap issue

**Comment by sawtoothtulip86** [comment]
then why i can't hear vc when I use bloxtrap?

**Comment by NabHeyka22** [comment]
have you even tried using the regular roblox

**Comment by sawtoothtulip86** [comment]
i already did

**Comment by NabHeyka22** [comment]
and you can hear people with the regular roblox

**Comment by NabHeyka22** [comment]
and btw does the microphone work on the regular roblox

**Comment by sawtoothtulip86** [comment]
regular roblox yes but bloxtrap no idk why

**Comment by sawtoothtulip86** [comment]
the microphone word on regular roblox

**Comment by NabHeyka22** [comment]
do you have any fastflags? if so, try to delete them

**Comment by sawtoothtulip86** [comment]
no?

**Comment by NabHeyka22** [comment]
weird
idk how to help you i'm gonna be honest

**Comment by sawtoothtulip86** [comment]
is there a fastflag that i can hear vc or not

**Comment by NabHeyka22** [comment]
nno

**Comment by sawtoothtulip86** [comment]
then why i can't use vc when I use bloxtrap?

**Comment by NabHeyka22** [comment]
idfk dude
idk how to help you

**Comment by sawtoothtulip86** [comment]
how can i rest all the settings in bloxtrap manu?

**Comment by NabHeyka22** [comment]
bloxstrap menu, behaviour, enable Force Roblox reinstallation
then re open roblox

**Comment by sawtoothtulip86** [comment]
will that help me with vc?

**Comment by NabHeyka22** [comment]
idfk

**Comment by sawtoothtulip86** [comment]
and even flagfast codes will be rest?

**Comment by NabHeyka22** [comment]
maybe
but you said you didn't have any fastflags

**Comment by NabHeyka22** [comment]
btw call them fastflags only
they're not code

**Comment by sawtoothtulip86** [comment]
:C

**Comment by sawtoothtulip86** [comment]
still bug issue

**Comment by puppy65po** [comment]
how do you have that ui?

**Comment by bluepilledgreat** [comment]
Reset your fast flags. If the problem still persists, not our problem.

**Comment by sawtoothtulip86** [comment]
still not 
![Uploading لقطة شاشة 2024-09-24 135340.png…]()
