### ISSUE TITLE
[REQ] Add new language!

### ISSUE THREAD

**Issue by either14** [pizzaboxer/bloxstrap#2904]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I lived in Uzbekistan for many years and am fluent in the language and its grammar. Among the teenagers around me, many played Roblox, especially R6 games, but not all of them had powerful computers. I introduced them to Bloxstrap, but since many didn’t speak English, I had to explain everything and translate the functions for them. Bloxstrap became popular in my neighborhood, but most users struggled with the language barrier. I would like to request the addition of an Uzbek translation, and I’m willing to personally handle the translation work. It’s difficult to explain each function to every user individually.

**Comment by bluepilledgreat** [comment]
We do translations through Crowdin. Go talk to pizzaboxer about being added.
