### ISSUE TITLE
[BUG] 21 Graphics Bar setting isn't working anymore

### ISSUE THREAD

**Issue by mrjayden17** [pizzaboxer/bloxstrap#2905]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When the 21 graphics bar setting is on, it dosen't seem to be working in game only showing 10 graphics bars. However, the other features are working fine like hiding the GUI.

### Bloxstrap Log

N/A

**Comment by JoxZer** [comment]
roblox removed the fflag, there is nothing that can be done unless roblox does it themselves

**Comment by bluepilledgreat** [comment]
It has been removed by Roblox

**Comment by mrjayden17** [comment]
oh well that kinda sucks 😭

**Comment by Error340GTL** [comment]
dang
