### ISSUE TITLE
[REQ] PLS ADD BACK THE 2020 ESCAPE MENU I LOVED IT WHY IT GOT REMOVED

### ISSUE THREAD

**Issue by Yujeorblx** [pizzaboxer/bloxstrap#2906]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

plsplspls

**Comment by Yujeorblx** [comment]
pls add the 2020 escape menu back

**Comment by JoxZer** [comment]
my man, it got removed by roblox, bloxstrap cant do anything about it

**Comment by Yujeorblx** [comment]
> my man, it got removed by roblox, bloxstrap cant do anything about it

yeah but the 21 graphics bar settings is still in the bloxtrap menu even tho it doesnt works so why did they remove the 2020 esc menu from the bloxtrap menu

**Comment by JoxZer** [comment]
> > my man, it got removed by roblox, bloxstrap cant do anything about it
> 
> yeah but the 21 graphics bar settings is still in the bloxtrap menu even tho it doesnt works so why did they remove the 2020 esc menu from the bloxtrap menu

the 21 graphics bar setting will be gone in next update, 2020 esc menu got removed because the fflag was removed before bloxstrap updated

**Comment by Yujeorblx** [comment]
> > > my man, it got removed by roblox, bloxstrap cant do anything about it
> > 
> > 
> > yeah but the 21 graphics bar settings is still in the bloxtrap menu even tho it doesnt works so why did they remove the 2020 esc menu from the bloxtrap menu
> 
> the 21 graphics bar setting will be gone in next update, 2020 esc menu got removed because the fflag was removed before bloxstrap updated to 2.7.0

oh kk ty
