### ISSUE TITLE
[BUG]  blue screen of death

### ISSUE THREAD

**Issue by nofio321** [pizzaboxer/bloxstrap#2907]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

a few months ago. i decided to try bloxstrap out for fun, and after a few days of using bloxstrap. i had like 1 to 2 blue screens even though i didnt do anything on tthe bloxstrap menu itself. after one day i decided to wipe my data. and now its working just fine. can someone explain to me why did that happen?

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
your computer is bad

**Comment by SilverT4** [comment]
This doesn't sound like it's *explicitly* a Bloxstrap issue. Did you install anything else at the time of installing Bloxstrap?

**Comment by nofio321** [comment]
> This doesn't sound like it's _explicitly_ a Bloxstrap issue. Did you install anything else at the time of installing Bloxstrap?



> This doesn't sound like it's _explicitly_ a Bloxstrap issue. Did you install anything else at the time of installing Bloxstrap?

i didn't install anything when i was installing bloxstrap
