### ISSUE TITLE
[BUG] Advanced graphics quality selector doesn't working

### ISSUE THREAD

**Issue by Guestw5y** [pizzaboxer/bloxstrap#2908]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Advanced graphics quality selector isn't working, when i go to settings inside a game it still begin the default one with 10 (i have it activated)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
fflag that made it work got removed by roblox
can't do anything about it
option will be gone next update

**Comment by bluepilledgreat** [comment]
It has been removed by Roblox
