### ISSUE TITLE
[REQ] Return back multi-roblox in bloxstrap

### ISSUE THREAD

**Issue by ARS7236** [pizzaboxer/bloxstrap#2910]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Before updating bloxstrap there was feature multi-roblox and there works that:: open roblox and you can add more roblox windows with diffrient accounts

**Comment by NabHeyka22** [comment]
he most likely will NEVER bring back multi instance

**Comment by o0omega** [comment]
> > ### Acknowledgement of preliminary instructions
> > 
> > * [x]   I have read and acknowledged the preliminary instructions.
> > 
> > ### What idea do you have?
> > Before updating bloxstrap there was feature multi-roblox and there works that:: open roblox and you can add more roblox windows with diffrient accounts
> 
> if you want multi instancing, Roblox Account Manager exists

Why not integrate the legal functions from RAM into bloxstraps, including multi instance? This is the thing I don't undersatand
