### ISSUE TITLE
[REQ] Is it possible to make it possible to change your FPS in-game?

### ISSUE THREAD

**Issue by noideaforausername2000** [pizzaboxer/bloxstrap#2913]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I'm pretty sure it's possible to copy some code of an old popular roblox fps unlocker to make it so you can change fps in-game (only if it's possible tho)

**Comment by laprium** [comment]
Removing the fps cap at 240?

**Comment by noideaforausername2000** [comment]
> Removing the fps cap at 240

**Comment by noideaforausername2000** [comment]
> Removing the fps cap at 240?

No, I mean being able to change your fps in-game

**Comment by laprium** [comment]
Yes but how much u want?, that's the question.

**Comment by noideaforausername2000** [comment]
> Yes but how much u want?, that's the question.

Sorry for the late reply, I want 15 fps because that's the fps needed to peform a glitch thaat either makes you clip through walls or glide them

**Comment by laprium** [comment]
you go into Bloxstrap Menu and go Fast Flags

**Comment by noideaforausername2000** [comment]
> you go into Bloxstrap Menu and go Fast Flags

To change your fps with the default fps unlocker ONLY lets you change fps after a rejoin, or are you talking about using the ff editor?
