### ISSUE TITLE
Exclusive fullscreen setting monitor's refresh rate to 30Hz

### ISSUE THREAD

**Issue by NikoYTRBLX** [pizzaboxer/bloxstrap#292]
Tried using exclusive fullscreen with and without Fullscreen optimizations, but it still sets it to 30Hz for some unknown reason.

Could just be an issue on Roblox's side not knowing how to handle exclusive fullscreen or just my hardware, but it's annoying.

Images for comparison:
### **Standard fullscreen**
![20230607_182950](https://github.com/pizzaboxer/bloxstrap/assets/38755801/2ca05000-ba79-4625-85f0-c36446deb942)

### **Exclusive fullscreen (note the Refresh rate in the bottom left corner)**
![20230607_182711](https://github.com/pizzaboxer/bloxstrap/assets/38755801/87c0af2c-4c1c-474a-9e16-084a8e502f31)

Once again, this could be on Roblox's side or an issue with my hardware, so take this issue with a grain of salt.

Should also mention that I'm running W11, so that could make a difference.

**Comment by pizzaboxer** [comment]
Maybe try using Vulkan? That already does native fullscreen by default.

**Comment by NikoYTRBLX** [comment]
Didn't I mention in issue #189 that I cannot run Vulkan?

**Comment by NikoYTRBLX** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/38755801/458f7c86-90b4-4283-a499-c724c3977780)
Yeah, no, I can't run Vulkan

**Comment by pizzaboxer** [comment]
Oh, right. Yeah, it's entirely a Roblox problem. There's not much I can really help you with, sorry. You'll just have to use normal borderless fullscreen.

**Comment by NikoYTRBLX** [comment]
Alright, thanks for the insight!
