### ISSUE TITLE
[BUG] bloxstrap wont let me leave game or show player list in any escape menu version before 2023?

### ISSUE THREAD

**Issue by HELPMEHELPMEHELP** [pizzaboxer/bloxstrap#2922]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![2](https://github.com/user-attachments/assets/62a47794-5270-48ad-9d23-ee0a6adbe2e0)
![1](https://github.com/user-attachments/assets/27538f71-eec2-45cf-91a1-ae8c40cc0505)

I dont know whats happening? I did mess with some settings (i made it only use directx 10, and a fast flag i think for rotating items?)
![Untitled](https://github.com/user-attachments/assets/4814e64f-590b-4cd6-ab39-3d1d0170794c)

someone help

### Bloxstrap Log

N/A

**Comment by moosetwin0** [comment]
This is a duplicate of #2911, I recommend closing and talking there.

**Comment by HELPMEHELPMEHELP** [comment]
my bad i didnt know
