### ISSUE TITLE
[BUG] WHAT THE FUCK

### ISSUE THREAD

**Issue by alepalex** [pizzaboxer/bloxstrap#2925]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/2f427c9c-22c3-494f-9c8a-8c2d25af1027)
the roblox menu is broken. i have roblox app off, cause i like the website. so the house logo shouldn't show up. when i try to leave, it doesn't let me 
![image](https://github.com/user-attachments/assets/d353c22b-36aa-4510-8df8-1c084fc3654e)
i use esc l enter.  thing is when i do that, thats why the upper bar dissapears! i cant change my roblox setings (volume, graphics etc) or anything like that! and if i try to close roblox, because the menu is so bugged, i cant say no or such. i need to use task manager. 
i think roblox wants to force me to use their disgusting system of in-app website.

### Bloxstrap Log

N/A

**Comment by Fur7010** [comment]
it dont even close with alt f4, or clicking the X. i tried to re-install it but that dosent fix it. must be a roblox thing

**Comment by JoxZer** [comment]
try this

{
  "FFlagFixReportButtonCutOff": "False"
}

**Comment by ZxfoxZx** [comment]
I am having the same issue. Its not robloxs fault. Its a problem with bloxstrap. I even messed around and checked.

I first tried re-installing roblox, but no avail.
Then I went to re-installing bloxstrap, but still didn't solve it at all.
Then I just decided to uninstalling bloxstrap completely. Than it worked.

**Comment by Fur7010** [comment]
i fixed it, i changed the ui in bloxstrap menu to "V4 new ui"

**Comment by Fur7010** [comment]
![image](https://github.com/user-attachments/assets/4dccf12e-71ee-48e8-a405-23c4189a9d05)
my menu looks like this now

**Comment by alepalex** [comment]
> try this
> 
> { "FFlagFixReportButtonCutOff": "False" }

guys, will this work?

**Comment by alepalex** [comment]
> ![image](https://private-user-images.githubusercontent.com/89009606/369381917-4dccf12e-71ee-48e8-a405-23c4189a9d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzU5MTEsIm5iZiI6MTcyNjgzNTYxMSwicGF0aCI6Ii84OTAwOTYwNi8zNjkzODE5MTctNGRjY2YxMmUtNzFlZS00OGU4LWE0MDUtMjNjNDE4OWE5ZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEyMzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDQxZmU5YmE0NWFhMmI0YWJjMzg0MjI3OTEwZGEyYmFlNjhjMTA0MTkzZTI3MTQ1Njk0MjIzYmZkNTRhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.flElHpZ4Uprrc35W2h4ljYAd4Lt2otj9mDXft6zQRow) my menu looks like this now

 but i like the old one...

**Comment by alepalex** [comment]
but i cant choose because ofcourse not

**Comment by bluepilledgreat** [comment]
Duplicate issue

**Comment by alepalex** [comment]
DUPE ISSUE?

**Comment by NabHeyka22** [comment]
Indeed.
Your issue has been addressed multiple times but i guess you're just too lazy to search first.
