### ISSUE TITLE
[BUG] everytime i try to press on the bloxstrap file it says "Failed to open dlllist.txt for reading. Error code: 2," idk what to do 

### ISSUE THREAD

**Issue by stevers80** [pizzaboxer/bloxstrap#2926]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/92dd4e46-6628-4186-aa05-a22893fc1138)
keeps showing this every time i try to open and run the program and idk what to do, help will be appreciated

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
i found this on the bloxstrap discord server
thanks to skylan
![image_2024-09-20_182324132](https://github.com/user-attachments/assets/f7b50637-7b29-4066-b20c-eac93090d982)
