### ISSUE TITLE
[BUG] Roblox Audio not playing in vc games

### ISSUE THREAD

**Issue by RealFlippeh** [pizzaboxer/bloxstrap#2927]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when i join games with vc, as soon  as it gets connected to my headphones the audio just cuts out and i cant hear literally anything

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
are you installing something like voicemod

**Comment by RealFlippeh** [comment]
> are you installing something like voicemod

well i have voicemod but im not using it rn

**Comment by NabHeyka22** [comment]
ok but are you installing something while you're in roblox

**Comment by RealFlippeh** [comment]
> ok but are you installing something while you're in roblox

nah, im just joining normally and after a few secs the audio cutrs out

**Comment by NabHeyka22** [comment]
oh, then i don't know ngl

**Comment by RealFlippeh** [comment]
> oh, then i don't know ngl

alr ill try to find a solution

**Comment by bluepilledgreat** [comment]
Reset your fast flags. If the issue still persists, not our problem. We do not modify the Roblox client in any other way.
