### ISSUE TITLE
[REQ] Custom Avatar Meshes

### ISSUE THREAD

**Issue by SolaraeOfficial** [pizzaboxer/bloxstrap#2929]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i wouldn't say this is an idea or anything but there has been a new thing that has been kind of popping off on TikTok lately about modifying the characters mesh like the R6 model to give it some "suggestive" body features if anyone wants more info on this feel free to respond to this thank you.

**Comment by NabHeyka22** [comment]
you are a DISGUSTING organism
and you probably like roblox po**

**Comment by SolaraeOfficial** [comment]
as you can see all you guys read it wrong i wanted to see if there was a way to prevent this thats why i asked if you guys wanted more info on it 🤦

**Comment by SolaraeOfficial** [comment]
why would i post a req on it if i wanted it ☠️☠️☠️☠️

**Comment by NabHeyka22** [comment]
you posted a request feature, meaning a feature that you wanted bloxstrap to have
then you say that there was this thing on tiktok where R6 bodies had sensitive stuff
what the fuck are we supposed to understand, huh?

**Comment by SolaraeOfficial** [comment]
i contacted both the main people on this matter and never gotten a response so where else am i meant to go

**Comment by NabHeyka22** [comment]
not here????????
what do you think this is?????????

**Comment by SolaraeOfficial** [comment]
anywhere to get this shit of the platform??

**Comment by NabHeyka22** [comment]
buddy. this isn't roblox support.

**Comment by SolaraeOfficial** [comment]
why would i go to roblox support they dont give too shits
