### ISSUE TITLE
error when launching roblox

### ISSUE THREAD

**Issue by Unii1** [pizzaboxer/bloxstrap#293]
![image](https://github.com/pizzaboxer/bloxstrap/assets/135924980/d9934b1d-ca02-441e-892c-fa327b3d7c8b)

shows this every time I try to launch Roblox, just started happening today.

**Comment by pizzaboxer** [comment]
What permissions do you have on the D: drive? Right click on it in Windows Explorer, go to Security, and ensure that the group you're in (either Users or Administrators) has permissions for 'Read & execute.'

**Comment by Unii1** [comment]
on both Users and Administrators they both have permission to Read & Execute but I did reinstall and change folder locations to the default which was in my C: drive and it seemed to work not sure why it didn't work on my D: drive but i think it forcefully has to be installed in your C: drive to work.

**Comment by pizzaboxer** [comment]
If you reinstalled Windows and you had user permissions configured on your D: drive, that's no doubt going to cause problems. Anyway, it's resolved now.

**Comment by Unii1** [comment]
thank you I figured it out I changed the location to my D: Drive again then ran the exe again and it worked perfectly.
