### ISSUE TITLE
[BUG]  Roblox wont close

### ISSUE THREAD

**Issue by xoathesponge** [pizzaboxer/bloxstrap#2930]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Im using a pre set of fast flags from a youtuber for better ping and Fps, it worked great all the time but now i cant close roblox at all while using it, wont even show up in the task manager. Also happens without the fast lags 

### Bloxstrap Log

N/A

**Comment by Illusion288** [comment]
Are you by any chance using the "2015 (V1)" or "2022 (V2)" choices for the "Preferred escape menu version" fast flag? Both of those don't seem to be working anymore, and I've been having the same issues with closing Roblox until I switched to another escape menu version.

**Comment by bluepilledgreat** [comment]
> Im using a pre set of fast flags from a youtuber for better ping and Fps
Delete all your flags.

**Comment by xoathesponge** [comment]
> Are you by any chance using the "2015 (V1)" or "2022 (V2)" choices for the "Preferred escape menu version" fast flag? Both of those don't seem to be working anymore, and I've been having the same issues with closing Roblox until I switched to another escape menu version.
> 
> Edit: I've found a workaround for fixing this on a different issue. Here you go: [#2911 (comment)](https://github.com/pizzaboxer/bloxstrap/issues/2911#issuecomment-2364092668)

Thanks dude , rlly helped
