### ISSUE TITLE
[BUG] A opçao dos flags de aumentar o grafico até 21 não esta funcionando

### ISSUE THREAD

**Issue by lucas20190hk** [pizzaboxer/bloxstrap#2931]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

A opçao dos flags de aumentar o grafico até 21 não esta funcionando
![image](https://github.com/user-attachments/assets/f423521f-b672-437d-88c4-cf204946fc1a)
![image](https://github.com/user-attachments/assets/4b283288-1947-49a4-abe6-3090086aab1b)

### Bloxstrap Log

N/A

**Comment by internetzx** [comment]
Então, Roblox removeu o FFlag para a barra gráfica 21, desculpe, não podemos fazer nada a respeito.
Desculpe se eu tenho um português ruim, mas, estou usando um tradutor

**Comment by bluepilledgreat** [comment]
Roblox removeu a fflag de 21 barras gráficas
