### ISSUE TITLE
[BUG] I keep getting "System.InvalidOperationException: Cannot start process because a file name has not been provided." somehow

### ISSUE THREAD

**Issue by LilFatCat** [pizzaboxer/bloxstrap#2932]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

stupid stinky error logs, I might need someone to decode it

### Bloxstrap Log

[Bloxstrap_20240921T024219Z.log](https://github.com/user-attachments/files/17082551/Bloxstrap_20240921T024219Z.log)

**Comment by LilFatCat** [comment]
nevermind

**Comment by bluepilledgreat** [comment]
Duplicate of #2315
