### ISSUE TITLE
[BUG] my bloxstrap has deleted himself somehow.

### ISSUE THREAD

**Issue by Nikitnaum3** [pizzaboxer/bloxstrap#2934]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i do not sure but it might deleted himself. only the files but not folder. i woke today and launch app through shortcut. it doesn't launch because windows does not found bloxstrap launcher executable

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Are you sure your anti-virus software hasn't deleted it?

**Comment by Nikitnaum3** [comment]
> Are you sure your anti-virus software hasn't deleted it?

it may be but i think not. Anyways defender doesn't detecting any malwares in bloxstrap so i think it not anti-virus.

**Comment by bluepilledgreat** [comment]
Have you tried reinstalling Bloxstrap?

**Comment by Nikitnaum3** [comment]
> Have you tried reinstalling Bloxstrap?

Already reinstalled. This issue hasn't appeared again.
