### ISSUE TITLE
An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Alevaga** [pizzaboxer/bloxstrap#2935]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I tried to download bloxstrap after deleting it and this error popped up.

### Bloxstrap Log

[Bloxstrap_20240920T221830Z.log](https://github.com/user-attachments/files/17082924/Bloxstrap_20240920T221830Z.log)

**Comment by Wanwood1** [comment]
You have not answered truthfully above the checkboxes as you have neglected to read up on the wiki.

This page should give you information on your error: https://github.com/pizzaboxer/bloxstrap/wiki/%22Access-to-the-path-is-denied%22-error-when-trying-to-reinstall-Bloxstrap
