### ISSUE TITLE
[BUG] 2022 (V2) escape menu shows the 2015 (V1) menu

### ISSUE THREAD

**Issue by Dima24162** [pizzaboxer/bloxstrap#2937]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When i'm trying to use 2022 V2 version of escape menu, it shows the old one.
![image](https://github.com/user-attachments/assets/eb87a085-ab1a-486a-8f41-da0bf0507f2f)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
roblox removed the v2 menu
use something else like 2023

**Comment by bluepilledgreat** [comment]
Duplicate issue
