### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ToastyProto** [pizzaboxer/bloxstrap#2938]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

2015 (V1) and the Default to 2022 (V2) do NOT work on Roblox well anymore, its practically unplayable, there are no ways to close RobloxPlayer without using task manager because it just sends the "New to Roblox?" prompt, BUT IT DOESNT SHOW!!!
![image](https://github.com/user-attachments/assets/f5d8f4f9-def0-4b7d-a945-a79e4d1baee6)
![Screenshot 2024-09-21 124044](https://github.com/user-attachments/assets/37a118f7-ce03-4f2f-a4b0-7cb175819729)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
n.1 for the v1 menu, use something else or use this fflag
{
  "FFlagFixReportButtonCutOff": "False"
}
n.2 v2 got removed

**Comment by ToastyProto** [comment]
Im not saying V2 doesn't work, i know that, i'm just saying the defaulting from v2 (to v1) has the same problems

**Comment by NabHeyka22** [comment]
![image_2024-09-21_124537002](https://github.com/user-attachments/assets/6810888d-5525-4162-9f86-87e3be63ae74)
i see a "2015 (V1) and the Default to 2022 (V2) do NOT work on Roblox"
and just read what i said to fix it

**Comment by bluepilledgreat** [comment]
Duplicate issue, look at pinned.

**Comment by 7-7what** [comment]
this is a duplicate of #2911 please go to there for further help, or dont sence its not like someone posted how to fix it here.
