### ISSUE TITLE
[BUG] Attempting to close the game window or use the game menu does not work

### ISSUE THREAD

**Issue by IGOTTOKENLOG** [pizzaboxer/bloxstrap#2940]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When using the game menu, no players will show, when attempting to reset character or leave. it will show a grey overlay and do nothing. 
![image](https://github.com/user-attachments/assets/3e6d542e-f358-4686-9623-4fc8e3b1a426)
![image](https://github.com/user-attachments/assets/1489409e-da14-4413-8c41-8b9ad55b7855)

### Bloxstrap Log

N/A

**Comment by IGOTTOKENLOG** [comment]
Alt + F4 also triggers this, and i have to manually end the roblox process with task manager

**Comment by NabHeyka22** [comment]
1. problem has been addressed multiple times but you're just too lazy to do some research
2. to fix it add this flag {
  "FFlagFixReportButtonCutOff": "False"
} and if it doesn't work, change the menu to something like 2023
