### ISSUE TITLE
[BUG] ESC Menu Broken

### ISSUE THREAD

**Issue by IDontKnowWhyIamHer** [pizzaboxer/bloxstrap#2947]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I think it has something to do with Bloxstrap so that's why I'm posting this. Everytime I press ESC, the menu won't work, there's no leaderboard, no settings, NOTHING. Here's proof
![RobloxScreenShot20240921_213951888](https://github.com/user-attachments/assets/02fc8a8b-3544-458b-a42d-2c208e7c63ed)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
1. your problem has been addressed but you're just lazy to search
2. add this flag to possibly fix it "FFlagFixReportButtonCutOff": "False", and if it doesn't work, use another menu like 2023

**Comment by NabHeyka22** [comment]
Glad you checked the "I didn't answer truthfully" checkmark.
Your bug/issue has been addressed multiple times, but since you don't want to do any research, put this flag:
{
  "FFlagFixReportButtonCutOff": "False"
}
And if it doesn't work, change the escape menu to something like 2023 or something.
