### ISSUE TITLE
[BUG] Bloxstrap not opening V1 Roblox menu

### ISSUE THREAD

**Issue by styalos** [pizzaboxer/bloxstrap#2948]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

This could be just a setting that i changed that did this, but it does not open the menu (in-game) no matter what. I have to use Task Manager to close Roblox. Oh and also (if it really wasn't Bloxstrap's problem) don't come replying saying it's not Bloxstrap's problem then ghosting me (sorry lol)
![Screenshot 2024-09-21 203619](https://github.com/user-attachments/assets/86dc6dd7-6f1b-4e7b-ad33-0221fe2d7b12)
![Screenshot 2024-09-21 203635](https://github.com/user-attachments/assets/3b709594-8333-47d5-b090-bab920c426b1)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Read the pinned issue

**Comment by Urgamerboi2-0** [comment]
same issue goes for me
