### ISSUE TITLE
[BUG] Escape menu not loading

### ISSUE THREAD

**Issue by New7G** [pizzaboxer/bloxstrap#2949]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Error with Menu Rendering, problem only occurs when starting bloxstrap, i am on the release 2.7..0 
![Screenshot 2024-09-20 220842](https://github.com/user-attachments/assets/1cc7e72f-d556-4107-b7ed-3bb267096981)
heres the error, as i said previously this only happens with bloxstrap

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Read the pinned issue
