### ISSUE TITLE
Bloxstrap icons doesn't disappear in hidden icons after leaving a game

### ISSUE THREAD

**Issue by CatchFirez** [pizzaboxer/bloxstrap#295]
![image](https://github.com/pizzaboxer/bloxstrap/assets/71689963/51023514-b3af-4760-a713-7251a480cd18)

**Comment by user1126s** [comment]
its a bug in windows. it happended to fps unlocker when it was a integration. just hover over them. ( stollen this message from pizzaboxer on github. )

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/issues/183
