### ISSUE TITLE
[BUG] Advanced grpahics quality not changing when enabled

### ISSUE THREAD

**Issue by ooeoewooow** [pizzaboxer/bloxstrap#2954]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i tried to change my settings beacuse arsenal was laggy and noticed that i have 1-10 graphics and my adavanced ones are enabled. please fix this*

### Bloxstrap Log

*

**Comment by NemusCraft** [comment]
This bug happens to me aswell, should be fixed

**Comment by NabHeyka22** [comment]
FFlag that made the setting work got removed by Roblox. We can't do anything about it, since we're not Roblox Technicians.
