### ISSUE TITLE
[BUG] I cannot use GUI hiding option, even after updating my settings (Group ID)

### ISSUE THREAD

**Issue by NemusCraft** [pizzaboxer/bloxstrap#2956]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

So i am trying to press the hideGUI keybinds and it does nothing (Even after changing my bloxstrap settings)

![{8F0CB654-CA23-459D-B732-E15EA3687005}](https://github.com/user-attachments/assets/d10d3fbc-504e-43c6-b720-df8117909c3b)
As you can see it's enabled, but nothing happens to it (even including the advanced graphics setting)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Are you in their group?

**Comment by NemusCraft** [comment]
> Are you in their group?

I am not in their group, i used fastflags editor to change GroupID.

**Comment by NabHeyka22** [comment]
You know there's a text that says "Only works if you're in the Bloxstrap group".

**Comment by NemusCraft** [comment]
> You know there's a text that says "Only works if you're in the Bloxstrap group".

???
![{FE57F89A-2A83-43D1-8DCA-5EDA69630227}](https://github.com/user-attachments/assets/99128f5f-d511-4633-b1de-a17020bfd13f)

**Comment by NabHeyka22** [comment]
Yeah, it says "It can be made to work with **any group you're currently in**"
As you mentioned, you're not in the Bloxstrap group, and you need to join the group for the GUI hiding to work AND the fast flag to work.
Next time, please read carefully.

**Comment by NemusCraft** [comment]
> Yeah, it says "It can be made to work with **any group you're currently in**" As you mentioned, you're not in the Bloxstrap group, and you need to join the group for the GUI hiding to work AND the fast flag to work. Next time, please read carefully.

Are you not reading it correctly?

**Comment by NabHeyka22** [comment]
Let me quote it for you.
'This is a group-based FastFlag, **therefore you must be in a Roblox group for it to work.** It can be made to work **with any group you're currently in**'
And you said "I am not in their group, i used fastflags editor to change GroupID."
Therefore, the fflag needs to be set to the Bloxstrap group, but even if you set it to that, you still need to join it because the FFlag only works whenever you're IN that group.

**Comment by NemusCraft** [comment]
> It can be made to work **with any group you're currently in**

You forgot to read this dis thingy

**Comment by NabHeyka22** [comment]
I didn't. The bottom text of the setting in the Bloxstrap menu says "Only works if you're in the Bloxstrap group", and you've stated that you're NOT in the group. Therefore, you decided to put the FFlag, but with a different group ID. Therefore, yet again, the way that the setting possibly works is that if you put the FFlag in, but it's not set to Bloxstrap's group, then it won't work. So what you need to do, is join the Bloxstrap group, and put the FFlag in with Bloxstrap's group ID.

**Comment by NemusCraft** [comment]
https://github.com/user-attachments/assets/716c5625-296d-45ef-bffa-68215e47d94f

For some reasons, when i try to enable that fastflag, it just reset group ID

**Comment by NabHeyka22** [comment]
Have you tried spamming that save button? Sometimes there may be saving issues. And also, have you tried joining a game and seeing if it still works?

**Comment by NemusCraft** [comment]
> Have you tried spamming that save button? Sometimes there may be saving issues. And also, have you tried joining a game and seeing if it still works?

I have tried, and yet it doesn't work

**Comment by bluepilledgreat** [comment]
> Yeah, it says "It can be made to work with **any group you're currently in**" As you mentioned, you're not in the Bloxstrap group, and you need to join the group for the GUI hiding to work AND the fast flag to work. Next time, please read carefully.

what? it should work with whatever group id you input, bloxstrap doesnt force its own group on you.

**Comment by NemusCraft** [comment]
> > Yeah, it says "It can be made to work with **any group you're currently in**" As you mentioned, you're not in the Bloxstrap group, and you need to join the group for the GUI hiding to work AND the fast flag to work. Next time, please read carefully.
> 
> what? it should work with whatever group id you input, bloxstrap doesnt force its own group on you.

Just watch the video i uploaded above ^^
![Uploading {2112A989-2B47-4D5A-B93E-9DE6E0EC1E3E}.png…]()

**Comment by bluepilledgreat** [comment]
I see the problem.

**Comment by bluepilledgreat** [comment]
> 2024-09-22.19-32-50.mp4 
> For some reasons, when i try to enable that fastflag, it just reset group ID

This is intended. If you don't flip the "Enable ability to hide GUIs" option in the settings, it will keep the group ID you have input.
