### ISSUE TITLE
[BUG] .json changes not working properly 

### ISSUE THREAD

**Issue by Minecraf75** [pizzaboxer/bloxstrap#2957]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I managed to override the Montserrat Extra Bold weight using the .json file in the bloxstrap files, but there's a problem, the thickest the font would go to is the Bold weight, it's not calling the black weight nor is the proper weight being applied.
![Screenshot 2024-09-22 114527](https://github.com/user-attachments/assets/62c748fc-5877-40ce-8ea6-38c2b5f6bd9b)
![Screenshot 2024-09-22 121647](https://github.com/user-attachments/assets/9029e112-ab97-4285-aff3-bf08c98c8852)
![Screenshot 2024-09-22 122057](https://github.com/user-attachments/assets/4bb09df2-16f3-4d2f-ae16-5ac6dd62a291)
![Screenshot 2024-09-22 122112](https://github.com/user-attachments/assets/76ecd6b3-6de4-492e-9395-db319a437d8e)

As you can see, despite file modifications and the fonts corresponding in the code, the font weights are still messed up.

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
how is this our problem
