### ISSUE TITLE
[BUG] the menu buttons dont work

### ISSUE THREAD

**Issue by felip23** [pizzaboxer/bloxstrap#2959]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

the menu buttons dont work, i am using v1 menu and i need to force the roblox process to close

**Comment by ShadowCodeX-debug** [comment]
Try setting `FFlagFixReportButtonCutOff` to false.
