### ISSUE TITLE
Discord Overlay

### ISSUE THREAD

**Issue by OrphanObliterator** [pizzaboxer/bloxstrap#296]
for some reason when in a roblox game, discord ingame overlay refuses to work. i've tried seeing if this is a discord issue, but it appears to not be

i was thinking that bloxstrap may be causing the issue
would you know anything about this?

**Comment by pizzaboxer** [comment]
I don't think that's a Bloxstrap problem. It sounds more like a Hyperion thing to me, knowing that they've changed stuff relating to how rendering hooks function. It could only really be Bloxstrap's fault if it's somehow changing something with rendering, but I really doubt it.

If you temporarily switch back to Roblox's bootstrapper as [detailed here](https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap), you'll likely encounter the same thing.
