### ISSUE TITLE
[BUG] i cant leave or reset character, the menu theme is in 2015 even though i change it to 2022 (im using the latest bloxstrap)

### ISSUE THREAD

**Issue by nobitcoi** [pizzaboxer/bloxstrap#2961]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when I try to leave the game, I come across an empty menu on roblox
the leave and reset button do not work.
bloxstrap, pls fix this

### Bloxstrap Log

![RobloxScreenShot20240923_111127200](https://github.com/user-attachments/assets/9e1ff089-71f2-458f-ac02-322961414ccf)

**Comment by bluepilledgreat** [comment]
read pinned
