### ISSUE TITLE
[BUG] bloxstrap fastflags don't work

### ISSUE THREAD

**Issue by mymyself1** [pizzaboxer/bloxstrap#2963]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

the fastflags options don't work like removing texture...

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
By removing texture, do you mean the option "Remove terrain textures"? If so, the option is only supposed to disable the textures on terrains.

**Comment by ShadowCodeX-debug** [comment]
Please [upload your configuration](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration).

**Comment by mymyself1** [comment]
> By removing texture, do you mean the option "Remove terrain textures"? If so, the option is only supposed to disable the textures on terrains.

terrain

**Comment by mymyself1** [comment]
> Please [upload your configuration](https://github.com/pizzaboxer/bloxstrap/wiki/Uploading-your-Bloxstrap-configuration).

how to upload idk how
(i have seen this page and i don't know)
