### ISSUE TITLE
[BUG] my roblox menu isnt working

### ISSUE THREAD

**Issue by muffin-content** [pizzaboxer/bloxstrap#2964]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![RobloxScreenShot20240924_130746711](https://github.com/user-attachments/assets/5dae08d0-74fd-4a55-87da-b4ca5fae81fc)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
read pinned
