### ISSUE TITLE
[BUG] Bloxstrap isnt working

### ISSUE THREAD

**Issue by yunosharp** [pizzaboxer/bloxstrap#2965]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Everytime i wanna launch a game it crashes
![Screenshot 2024-09-24 013722](https://github.com/user-attachments/assets/aefa7091-e206-448f-b485-f329b4b2ad4e)

### Bloxstrap Log

N/A

**Comment by LymeLusy** [comment]
Open Bloxstrap menu, look for behavior and do image

![image](https://github.com/user-attachments/assets/fe75a112-791e-47eb-99b2-b689705db737)

**Comment by bluepilledgreat** [comment]
Update bloxstrap
