### ISSUE TITLE
[BUG] vc isn't work on bloxtrap

### ISSUE THREAD

**Issue by sawtoothtulip86** [pizzaboxer/bloxstrap#2966]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

my vc isn't working on bloxtrap
![لقطة شاشة 2024-09-24 135340](https://github.com/user-attachments/assets/631c6c6d-a1ca-40d4-b002-7f709b9f585c)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Send your fast flags

**Comment by KubaYT106Super** [comment]
I think your PC isnt registering your microphone.

**Comment by sawtoothtulip86** [comment]
here's my fast flags

{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "FFlagVoiceBetaBadge": "False",
  "FFlagTopBarUseNewBadge": "False",
  "FFlagEnableBetaBadgeLearnMore": "False",
  "FFlagBetaBadgeLearnMoreLinkFormview": "False",
  "FFlagControlBetaBadgeWithGuac": "False",
  "FStringVoiceBetaBadgeLearnMoreLink": "",
  "DFFlagFacialAnimationStreaming2": "False"
}

**Comment by sawtoothtulip86** [comment]
and it's not that my pc isn't registering my microphone
everytime when I join on any game on roblox by using bloxtrap
my vc still loading and it wouldn't finish

**Comment by ShadowCodeX-debug** [comment]
Remove `DFFlagFacialAnimationStreaming2`.

**Comment by sawtoothtulip86** [comment]
i'll try

**Comment by sawtoothtulip86** [comment]
> Remove `DFFlagFacialAnimationStreaming2`.

what does that do?

**Comment by sawtoothtulip86** [comment]
didn't work

**Comment by ShadowCodeX-debug** [comment]
Are you sure you have your mic selected in settings?

**Comment by sawtoothtulip86** [comment]
yea it is

**Comment by sawtoothtulip86** [comment]
which settings roblox settings or?

**Comment by ShadowCodeX-debug** [comment]
Roblox Settings, Audio Input (...or output, idr which).

**Comment by Siiphon** [comment]
I have the same problem 
![Screenshot 2024-09-25 215420](https://github.com/user-attachments/assets/11797fd3-824e-460c-af21-d7ad0f32f788)

**Comment by sawtoothtulip86** [comment]
how can this issue be fix?

**Comment by ShadowCodeX-debug** [comment]
Try reinstalling Bloxstrap.

**Comment by sawtoothtulip86** [comment]
ok

**Comment by Siiphon** [comment]
> Try reinstalling Bloxstrap.

thanks that worked im stupid

**Comment by sawtoothtulip86** [comment]
we thx

**Comment by pizzaboxer** [comment]
Resolved?

**Comment by sawtoothtulip86** [comment]
yea
