### ISSUE TITLE
[BUG] Unable to close client when using custom escape menu 

### ISSUE THREAD

**Issue by TheDoctor1977** [pizzaboxer/bloxstrap#2968]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I am using the 2015 (V1) preferred escape menu version from the Fast Flags settings, with no other Fast Flags applied. If I press escape, I see this menu. 
![image](https://github.com/user-attachments/assets/03a88f2f-28d4-43a5-a4fc-a2588b9ad1e8)
Pressing L to open the prompt to leave simply hides the options
![image](https://github.com/user-attachments/assets/a19bf96b-e83e-496a-a045-e80f64d5bd0d)
If I press alt+f4, the same completely blank version of the menu opens and the game does not close. I am forced to end the game with Task Manager if I want to leave, and even then, I have to press End Task twice before the game will quit.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Insert this fflag: 
{
  "FFlagFixReportButtonCutOff": "False"
}
And if it doesn't work, use another menu like the 2023 one.

**Comment by TheDoctor1977** [comment]
> Insert this fflag:
{
"FFlagFixReportButtonCutOff": "False"
}

This worked, although I will leave the issue open because this should probably get a fix that does not require its own flag.

**Comment by NabHeyka22** [comment]
There's no fix that pizzaboxer, nor devs, can do. Roblox theirselves broke the menu, and there's nothing we can do.

**Comment by Ezoiar** [comment]
How about just, automatically apply the flag automatically when you apply the custom menu?
