### ISSUE TITLE
[BUG] autoclicker doesnt work with bloxstrap 

### ISSUE THREAD

**Issue by kirboispog** [pizzaboxer/bloxstrap#2969]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

im using autoclicker 4.0, i tested it with 3.0 and had the same issue. im using the default roblox ui, so idk. my hotkey is set to ` so that could be why it opens the inventory, but idk.

**Comment by bluepilledgreat** [comment]
what the fuck does this have to do with bloxstrap

**Comment by kirboispog** [comment]
> what the fuck does this have to do with bloxstrap

i tested it on the normal client and it works so that's what it has to do with it dipshit

**Comment by ShadowCodeX-debug** [comment]
Not Bloxstraps problem.
