### ISSUE TITLE
Too many crashes.

### ISSUE THREAD

**Issue by user1126s** [pizzaboxer/bloxstrap#297]
Hi, i know you're annoyed with me. my roblox crashes when i launch it and after relaunching it 1 or 2 times it works. im on windows 10. 4 gb ram. intel HD graphics(can run shaders) and intel core i3. it didnt crash with normal roblox, even with shaders.

**Comment by pizzaboxer** [comment]
> even with shaders

You seem to be implying that this didn't happen before the Hyperion update.

**Comment by MaCrO093** [comment]
this is happening to me too it freezes after 5-20 seconds

**Comment by kryozor** [comment]
> this is happening to me too it freezes after 5-20 seconds

Happening for me as well.

**Comment by pizzaboxer** [comment]
> this is happening to me too it freezes after 5-20 seconds

Freezing or crashing? Either way, you should temporarily switch back to Roblox's bootstrapper to see if it's really a problem with Bloxstrap. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by noplsvacban** [comment]
> [...] switch back to Roblox's bootstrapper to see if it's really a problem with Bloxstrap.
I've switched to Roblox's bootstrapper and it no longer freezes (I have the same problem as them). I also don't get any errors.

> You seem to be implying that this didn't happen before the Hyperion update.
This type of freezing, for me, only started today (6/10/23), and it worked fine even after the Hyperion update (with the exception of this day of course).

**Comment by pizzaboxer** [comment]
Does it happen in one game or just any? Only thing I can think of at this point is a bad FastFlag.

**Comment by noplsvacban** [comment]
> Does it happen in one game or just any? Only thing I can think of at this point is a bad FastFlag.

I believe it happens in any game, but the time for it to freeze is different (from my experience). I've tested (right now) 5 games, and 4/5 froze (I think I stayed for 1 minute or so in Armored Patrol and it didn't crash, so I just left because there was nothing to do).
It also lags for some reason, but it may be due to my shitty PC (but for some reason it did save me for a bit from getting frozen??? or I'm just dumb, maybe that as well.)

**Comment by pizzaboxer** [comment]
Two things I'd like you to try: disable Discord rich presence and set the framerate limit to 0. See if that changes anything.

**Comment by noplsvacban** [comment]
> Two things I'd like you to try: disable Discord rich presence and set the framerate limit to 0. See if that changes anything.

I've disabled the rich presence and set the framerate limit to 0. I've tested the same 5 games, and 5/5 froze, with 2 freezing almost immediately (it still said "joining server" but nothing was working, even the glaring thing or whatever effect is has did not work), 1 of them froze after a max of 10 seconds and the other 2 froze after a longer time (but still under 30 or so seconds).

I'm also using the ZIntegration channel, if you'd like me to change it to "LIVE" or something else specific, let me know.

**Comment by pizzaboxer** [comment]
Have you been on ZIntegration the whole time? See if LIVE does anything different. Also, send your full ClientAppSettings list here just so I know I'm not missing anything.

**Comment by noplsvacban** [comment]
> Have you been on ZIntegration the whole time? See if LIVE does anything different. Also, send your full ClientAppSettings list here just so I know I'm not missing anything.

This is the 3rd time I'm writing this ~~(and the 3rd time I am sending the ClientAppSettings)~~ because I kept task ending my browser because the client loves to be inside my browser, so I am also slightly annoyed while writing this so I may have emitted some details.

I haven't been on ZIntegration before I started the conversation, but I did change, at ~8:35 AM UTC, to ZIntegration (dont ask why). Before the conversation, I was on ZProjectELiu for a few weeks (months or days, idk i have dementia apparently 🤡). I changed to LIVE and all of them froze at different times, but under 1-2 minutes (because reasons or i cannot count time).

> and the 3rd time I am sending the ClientAppSettings

actually, the 4th because I just decided to name the zip differently for you to not get confused, but you probably wouldn't have got confused.

[ClientAppSettings-noplsvacban.zip](https://github.com/pizzaboxer/bloxstrap/files/11712516/ClientAppSettings-noplsvacban.zip)

**Comment by pizzaboxer** [comment]
Oh, this is the RCO flag list. Try clearing that and see if anything changes. Just set the contents of the file to `{}` to reset it.

**Comment by noplsvacban** [comment]
I just did that and there's no more freezing. Thanks for the help.

Out of curiosity, is there anything specific (in the RCO flag list) that causes the freeze? or something else

**Comment by pizzaboxer** [comment]
>  Can it also be avoided (other than resetting the contents)?

Nope. Configures way too many flags arbitrarily for no reason.

**Comment by user1126s** [comment]
I've tried everything, yet still, my rblx keeps crashing.

**Comment by pizzaboxer** [comment]
The "even with shaders" part seems to imply that the last time you used Roblox's launcher was before Hyperion was added. Check to see if it's a problem that does correlate with Bloxstrap by switching back to Roblox's launcher: https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by kryozor** [comment]
My fix was the simple decision to clear the contents of ClientSettings.json, my friend told me that he had resolved his by disabling the switch that toggles the QualityLevel graphics sliders.

**Comment by pizzaboxer** [comment]
> My fix was the simple decision to clear the contents of ClientSettings.json

Out of curiosity, what did you have in your ClientAppSettings list? Bloxstrap keeps it very minimal, so if there's anything it does that really causes it, then I need to reconsider that option.

**Comment by totallyphysicallypossible** [comment]
> Out of curiosity, is there anything specific (in the RCO flag list) that causes the freeze? or something else? Can it also be avoided (other than resetting the contents)?

This is a bit late, but I had the same issue so I went and tried to find the specific FFlags causing it, after a while of testing, it ended with 2 FFlags, I'm not sure if this applies to everyone else or only me, but these are:

"FFlagSoundServiceUsePerfControlV2Api": true
"DFFlagEnablePerformanceControlSoundCache3": true 

The thing is that only using one of these flags are fine, but using both of them will cause the game to permanently freeze for me.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
