### ISSUE TITLE
Roblox doesnt start

### ISSUE THREAD

**Issue by pipinpispis** [pizzaboxer/bloxstrap#2970]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Im wanna play in Rivals in roblox. if i press play on roblox website roblox doesnt start 30 sec and i got a bloxtrap error  

### Bloxstrap Log

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

[Inner Exception]
System.TimeoutException: A task was canceled.

[Inner Exception]
System.Threading.Tasks.TaskCanceledException: A task was canceled.

**Comment by bluepilledgreat** [comment]
Can you send your whole log file?

**Comment by pizzaboxer** [comment]
Addressed in Wiki
