### ISSUE TITLE
[BUG] Bloxstrap updates to latest version even when auto-update turned off

### ISSUE THREAD

**Issue by 3Alphaa** [pizzaboxer/bloxstrap#2971]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I downloaded a downgraded bloxstrap and it still gives me the latest version even tho auto update is turned off.
![image_2024-09-25_121028751](https://github.com/user-attachments/assets/cd06bea6-6781-4ed5-9332-a6d46fd70b95)
![image](https://github.com/user-attachments/assets/0e851d7f-abde-4e9f-8321-a85a36197613)

### Bloxstrap Log

N/A

**Comment by 3Alphaa** [comment]
Also for some reason my bloxstrap is downloaded in downloads and not in the bloxstrap folder.

**Comment by ShadowCodeX-debug** [comment]
Why are you even trying to get another different version? If it's Multi-instancing, just use Roblox Account Manager.

**Comment by bluepilledgreat** [comment]
stop downgrading bloxstrap thx bai
