### ISSUE TITLE
[BUG] Discord Rich Presence Not Displaying Correctly

### ISSUE THREAD

**Issue by SuperSkilledGamer** [pizzaboxer/bloxstrap#2972]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

After the recent Discord updates, Rich Presence doesn't work anymore. I have read other solved issues here and followed the steps instructed and the problem sill persists

Things I have tried so far:
- Uninstalled and reinstalled Discord
- Disabled the rich presence option and re-enabled in both Discord and Bloxstrap

![Discord](https://github.com/user-attachments/assets/d90a4322-c030-41b4-b35a-396489666348)

### Bloxstrap Log

N/A

**Comment by ShadowCodeX-debug** [comment]
I think that's the default Roblox rich presence.

**Comment by SuperSkilledGamer** [comment]
> I think that's the default Roblox rich presence.

Exactly. So why is Discord not using Bloxstrap rich presence?

**Comment by pizzaboxer** [comment]
Join a game and upload Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` please

**Comment by SuperSkilledGamer** [comment]
> Join a game and upload Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` please

There you go!

[Bloxstrap_20240928T164522Z.log](https://github.com/user-attachments/files/17175602/Bloxstrap_20240928T164522Z.log)

**Comment by pizzaboxer** [comment]
Bloxstrap is working correctly. In fact, it's even able to connect to Discord RPC. Whatever issue you're having is on Discord's side. Could I have a quick look at your activity privacy settings? Also, are you using a custom Discord client or the stock one?

**Comment by SuperSkilledGamer** [comment]
After sending you the log I viewed it myself and noticed it was trying to hook to my secondary Discord account (I have 2 logged in on my PC at all times - one from the Discord stock one and one from the beta version, also stock). Starting the desired account first > Bloxstrap > secondary account fixed the issue.

Now I'm facing a new issue. RPC is now displaying correctly with the game logo and everything, but once I refresh the client (CTRL+R) it reverts back to the default RPC posted in the first screenshot. Is there anything I can do to fix that? since I need to regularly refresh my client and every time I do so I have to restart Bloxstrap for the RPC to show back

Thanks in advance!

**Comment by pizzaboxer** [comment]
> Is there anything I can do to fix that?

No. That's to be expected.
