### ISSUE TITLE
[BUG]How i delete a mod?

### ISSUE THREAD

**Issue by vZeNkinGx** [pizzaboxer/bloxstrap#2975]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

My bloxstrap theme mod its bug and i dont know how delete it

### Bloxstrap Log

N/A

**Comment by ShadowCodeX-debug** [comment]
`%localappdata%\Bloxstrap\Modifications\` delete all except ClientSettings folder.
