### ISSUE TITLE
Roblox not opening

### ISSUE THREAD

**Issue by lolxddddddddddddddddddddd** [pizzaboxer/bloxstrap#2976]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

[BUG] Roblox not opening 

![image](https://github.com/user-attachments/assets/1907087f-dc98-45ef-8e24-3559c86b07a6)

### Bloxstrap Log

[Bloxstrap_20240926T014222Z.log](https://github.com/user-attachments/files/17141664/Bloxstrap_20240926T014222Z.log)

**Comment by bluepilledgreat** [comment]
You are opening the log tracer before Roblox has fully initialised. A fix for this will soon be released. For now, I am closing this issue.
