### ISSUE TITLE
[BUG] Roblox Menu in Bloxstarp

### ISSUE THREAD

**Issue by Verkku** [pizzaboxer/bloxstrap#2977]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Hello fellow Players. I need help with Bloxstrap. In normal roblox the menu in game works but when i use bloxstrap the menu doesn't show players and if i click the settings side it just doesn't work at all. I need to close the whole app and open it again to swap games.

### Bloxstrap Log

No Errors

**Comment by NabHeyka22** [comment]
It's not a code, it's a fastflag. They're different from each other.
Open bloxstrap menu, fastflags section, scroll down, fastflag editor, read the warning, click add new, click import json, then paste that in.

**Comment by Verkku** [comment]
MAN THANKS IT WORKED, THANK YOU SO MUCH

**Comment by NabHeyka22** [comment]
Yw.
