### ISSUE TITLE
[BUG] when launching roblox you can't exit the game and change the game settings

### ISSUE THREAD

**Issue by mikitaliv** [pizzaboxer/bloxstrap#2979]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when launching roblox you can't exit the game and change the game settings

### Bloxstrap Log

N/A

**Comment by Wanwood1** [comment]
Are you still looking for a solution?

**Comment by bluepilledgreat** [comment]
Read the pinned issue.
