### ISSUE TITLE
Roblox Links Faster (Question)

### ISSUE THREAD

**Issue by lucarioHyuuga** [pizzaboxer/bloxstrap#298]
Are there ways to optimize the connection with roblox links?

I mean, there are some games where the use of private servers is very favored, and the use of mobile gives an advantage in this,
You can take the discord link and enter directly in the game, unlike the PC that has to open the browser page, afterwards load the command to open launcher and then the launcher opens

Is there a possibility to do this in roblox PC? or just optimize the current PC process?

**Comment by pizzaboxer** [comment]
Are you talking about deeplinks? If by "discord link" you mean the launch links that Bloxstrap uses for Discord rich presence, then yeah, that's what those are.

**Comment by lucarioHyuuga** [comment]
I don't know if it's the same thing, you know when they send you a link to the privates servers? in the case of roblox and discord, it directly opens the browser, and then the launcher, which takes a lot of time, in fact, I don't even know if it is possible to improve this since it depends on the link ,correct?

**Comment by lucarioHyuuga** [comment]
What I want to talk about is, Is there a way I can click on a roblox private server link and have it bypass the website and go straight to the launcher? if so, is there a way to make it work with any link? (or at least the reliable ones)

**Comment by pizzaboxer** [comment]
Oh, you're talking about optimizing private server links. So, turns out that Roblox deeplinks have a parameter for private server access codes, which you can use to join a private server.
`roblox://experiences/start?placeId=PLACE_ID_HERE&accessCode=ACCESS_CODE_HERE`

You can find the access code of a private server using this API:
`https://games.roblox.com/v1/games/ACCESS_CODE_HERE/private-servers`

That should allow you to make deeplinks that can be used to join private servers without having to go through the Roblox website first.

**Comment by lucarioHyuuga** [comment]
With your experience, would it be possible to do this automatically? as a Launcher Feature, (I don't think so, because it depends on the link)
maybe a browser extension that automatically does this? or an extension of discord?
Because although there is a way to do this, it's impractical when trying to quickly join someone else's server.

**Comment by pizzaboxer** [comment]
Not as a launcher feature, but yeah, a browser extension or something like that would be possible. Though, I thought the idea is that you shouldn't have to figure out what the deeplink is when joining, you should kind of just already know what it is?

**Comment by lucarioHyuuga** [comment]
I'm very layman in relation to this type of subject, at the time that I played "crafwars" I was very irritated with the fact of never being able to enter a server fast enough, then I discovered the mobile technique, in which you leave roblox opens in the background and enters a private discord link, and not only does it not open the browser (because it is mobile) but it also does not open the launcher because it is already open, so it goes straight to loading the game

And since I live in Brazil and the roblox servers are horrible, things take a long time to load, so the less things you have to load the better

**Comment by lucarioHyuuga** [comment]
but speaking of a possible browser addon, wouldn't it be possible to create a whitelist system? in which the player takes the ID of the experience he wants to bypass the web

**Comment by pizzaboxer** [comment]
Well, I'm not really sure what you mean by whitelist system. If you're able to elaborate further then that'd be great. The thing is, as far as I can tell, the only way to obtain the private server's access code is by getting it from Roblox's website in the first place. Private server access codes are static and don't change, so if you have it on you beforehand, you can just reuse that one link to join the server at anytime.

If you're talking about a situation where you don't have pre-defined access to a private server but someone gives you a link, to be honest, I'm not really sure how that would work.

**Comment by lucarioHyuuga** [comment]
In the case of the Whitelist, as not every game you need to quickly enter servers, you could manually put the game ID in the Whitelist, of course, if only the game ID was needed

Is there a way to make the launcher load another game or server without closing and opening again ?, this could speed up loading

**Comment by pizzaboxer** [comment]
> Is there a way to make the launcher load another game or server without closing and opening again ?, this could speed up loading

Isn't that what the Roblox desktop app is for?

**Comment by lucarioHyuuga** [comment]
Yes and no, the Desktop is good for entering and exiting experiences, however when talking about links it doesn't even work, because then it will load the browser, close the already active launcher, open another one to load the other game/server

**Comment by user1126s** [comment]
> Well, I'm not really sure what you mean by whitelist system. If you're able to elaborate further then that'd be great. The thing is, as far as I can tell, the only way to obtain the private server's access code is by getting it from Roblox's website in the first place. Private server access codes are static and don't change, so if you have it on you beforehand, you can just reuse that one link to join the server at anytime.
> 
> If you're talking about a situation where you don't have pre-defined access to a private server but someone gives you a link, to be honest, I'm not really sure how that would work.

I can elaborate and help you make the extension

**Comment by pizzaboxer** [comment]
Anyway, I'm going to close this since this isn't related to Bloxstrap. You can continue talking here though.

**Comment by sava123pop** [comment]
is there any way to join without acces code just with private server link?
