### ISSUE TITLE
[BUG] cant leave when i open escape menu when having (preffered escape menu version 2015 V1) 

### ISSUE THREAD

**Issue by javiiierza** [pizzaboxer/bloxstrap#2980]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

cant leave the game or exit out my desk top on roblox at all,I had to reinstalll still didnt work properly.Pls fix this issue

**Comment by beansmp3** [comment]
i also had this problem but disabling this fixed it apparently
![image](https://github.com/user-attachments/assets/45d4111b-9640-4da4-9578-f9c17aebb539)
