### ISSUE TITLE
[BUG] Fastflags and mods don't apply.

### ISSUE THREAD

**Issue by ExtremeDiscomfort** [pizzaboxer/bloxstrap#2984]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

So, the fastflags and mods don't apply, pretty straightforward. HOWEVER, when I launch it, it quite clearly shows the Bloxstrap launch interface, so I was hoping for some advice on what to do.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Did you put the folder for the mods, like content or ExtraContent, in the Modifications folder?

**Comment by ExtremeDiscomfort** [comment]
I don't have any custom mods installed, I'm merely using fastflags for better graphics quality control, and will maybe use the mods later on.

**Comment by NabHeyka22** [comment]
Then just say fastflags next time, please.
Anyways, for the 21 graphic bar, the FFlag that made it work is removed by Roblox. We can't do anything about it, as we aren't roblox engineers.

**Comment by ExtremeDiscomfort** [comment]
Ah. That explains it. Thank you. I assume that the FFlag that forced lighting technology is also removed? If so, that's fine.

**Comment by NabHeyka22** [comment]
I don't know about that one. Anyways, you're welcome.
