### ISSUE TITLE
[BUG] the graphics 21 isnt apearing for some reason

### ISSUE THREAD

**Issue by Poggers224** [pizzaboxer/bloxstrap#2986]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

the  setting is turned on but it seems its not apearing just up to max 10 for me

### Bloxstrap Log

N/A v u

**Comment by NabHeyka22** [comment]
FFlag that made it work is removed by Roblox. Please read the wiki carefully next time, and please search for other posts.
