### ISSUE TITLE
[BUG] when will the graphics settings function be returned to 21?

### ISSUE THREAD

**Issue by Gante9172** [pizzaboxer/bloxstrap#2989]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I read that function 21 was removed, when will it be added again or is this a bug that is being fixed?

### Bloxstrap Log

N/A

**Comment by Wanwood1** [comment]
Roblox has removed the fastflag that gives the option to have the 21 graphics bar, we are not roblox engineers and we cant create new flags or bring back deleted ones.
It will only be usable again if roblox adds it back.
