### ISSUE TITLE
Be Able to Change lighting settings with a selected key

### ISSUE THREAD

**Issue by youknewallalong** [pizzaboxer/bloxstrap#299]
This isn't an issue rather a suggestion, within some games. I would like to change between lightings within games as in some games I'd prefer default lighting. So, if you could please figure out a way to add something that would allow me to change the lighting version mid game.

**Comment by EasternBloxxer** [comment]
I dont think that is possible without injecting into the game-client

**Comment by EasternBloxxer** [comment]
That would also be very unstable hence Roblox disabled it

**Comment by pizzaboxer** [comment]
This isn't possible, sorry.
