### ISSUE TITLE
[BUG] an exception occurred while running Bloxstrap

### ISSUE THREAD

**Issue by jaok1n** [pizzaboxer/bloxstrap#2991]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

sawdsawdsawdsawdsa  wdsa r

### Bloxstrap Log

N/A sdkanwdsawd

**Comment by jaok1n** [comment]
efdsw

**Comment by jaok1n** [comment]
dsaw

**Comment by Wanwood1** [comment]
Okay can you tell me why you just carelessly ticked off the checkboxes and didnt even care to read the wiki for fixes?

**Comment by internetzx** [comment]
holy fuck this guys braindead

**Comment by Wanwood1** [comment]
> holy fuck this guys braindead

now now, lets be nice, maybe he doesnt speak english very well in that case hes not to blame

**Comment by internetzx** [comment]
ok im relaxing my shit, but, why is he saying random stuff, is he like a actual child?

**Comment by Wanwood1** [comment]
> ok im relaxing my shit, but, why is he saying random stuff, is he like a actual child?

probably, but lets wait for his response and if he doesnt make one, ill just give him the solution anyways

**Comment by Wanwood1** [comment]
> ### Acknowledgement of preliminary instructions
> * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> * [x]  I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
> * [x]  I am using the latest version of Bloxstrap.
> * [x]  I did not answer truthfully to all the above checkboxes.
> 
> ### What problem did you encounter?
> sawdsawdsawdsawdsa wdsa r
> 
> ### Bloxstrap Log
> N/A sdkanwdsawd

Okay i actually dont know how i can help you unless you provide a log file, so that can give us further information on what is possibly the problem

**Comment by bluepilledgreat** [comment]
sasdsasdfasdfdsdfgfsasdfdsdfghgADFDSASGFDSASDFSasasdfgfdsasdfgfdaqsdffgfdasfgfssdfdsasdfdsasdfdsadfdasdfdsasdf
