### ISSUE TITLE
[BUG] i cant leave the game

### ISSUE THREAD

**Issue by MHMHMHM121H** [pizzaboxer/bloxstrap#2992]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![{21B24B60-43C8-45A0-B21E-0BC10F4B8647}](https://github.com/user-attachments/assets/cda06370-b79c-4c19-9a3b-0907ca388e3e)
 the escape menu is stuck on the 2015 one and will not let me leave roblox.

**Comment by NabHeyka22** [comment]
I'm tired of these 10k duplicate posts man.
Add this fflag
{
  "FFlagFixReportButtonCutOff": "False"
}
if it doesn't work, use the 2023 menu.

**Comment by MHMHMHM121H** [comment]
> I'm tired of these 10k duplicate posts man. Add this fflag { "FFlagFixReportButtonCutOff": "False" } if it doesn't work, use the 2023 menu.

thank you it worked. also 10k duplicate posts? i saw no one put a similar post

**Comment by NabHeyka22** [comment]
Yeah because you're too lazy to search first. And also if you looked up, there was literally a post.
