### ISSUE TITLE
[BUG] FFlag makes me spike.

### ISSUE THREAD

**Issue by tilt67** [pizzaboxer/bloxstrap#2997]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

hey, dont know where else to ask this really but its frustrating

i have a specific set of FFlags for bladeball, they were working fine and now all of a sudden every 1-2 minutes i spike to crazy pings, mostly 1000 but can get higher, no other set of fflags does this for me, my friend uses the exact same flags and he doesnt have this problem, any help?

if this isnt the place for this question apologies

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
I hope you realize FFlags are not meant for an FPS boost.

**Comment by tilt67** [comment]
the fast flags i use aren’t used for fps boost, i don’t know where you got that from

**Comment by NabHeyka22** [comment]
Where did you find the "Blade Ball FFlags preset"?

**Comment by tilt67** [comment]
a friend gave it to me, only a few people have it from what i know

**Comment by NabHeyka22** [comment]
I'm just going to tell you this, you don't need a "FFlag preset".
All you need is a little bit of FFlags that can be based to your Bloxstrap Menu's settings and some added ones. You don't need a FFlag preset.

**Comment by tilt67** [comment]
what are you even saying lol???? my whole
post is how a specific set of fflags was working fine and now it spikes my ping to 1000,

**Comment by NabHeyka22** [comment]
Does this happen in every game?

**Comment by tilt67** [comment]
yes

**Comment by NabHeyka22** [comment]
Have you tried deleting your stupid FFlag Preset?

**Comment by tilt67** [comment]
??? as i said in the og post, my game is fine without the fflags, and it’s also fine with other fflags, just not that specific preset i use for blade ball

**Comment by NabHeyka22** [comment]
Maybe just delete that FFlag preset since it's fucking useless.
As i said, you don't need a FFlag preset.

**Comment by tilt67** [comment]
?? you don’t even know what it does, you’re so hostile for no reason lol, it isn’t useless :3

**Comment by NabHeyka22** [comment]
What does it do then?

**Comment by tilt67** [comment]
i’m not getting into specifics on the thread about my fflag because no one cares, i’m looking for a fix or something like, if you want to know add my discord: tilt67

**Comment by NabHeyka22** [comment]
> i’m not getting into specifics on the thread about my fflag because no one cares

I do. And for your fix, just delete your stupid FFlag Preset. Yes, i'm calling it stupid cause you won't tell me what that FFlag Preset does that is so good.

**Comment by tilt67** [comment]
add me on discord if you care so much about it man lol

**Comment by NabHeyka22** [comment]
Done.

**Comment by bluepilledgreat** [comment]
delete your flag config

**Comment by tilt67** [comment]
but is there a certain reason why this config makes my ping jump everytime but no one elses ?
