### ISSUE TITLE
[BUG] Used VPN and deactivated it, this happened

### ISSUE THREAD

**Issue by JJrD243** [pizzaboxer/bloxstrap#2998]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I was testing a vpn to use for roblox (I live in Malaysia as of now) and i set it to America (Accidentally). After i saw the login screen when i opened roblox again, i turned it off and opened roblox again. I logged in, closed it, and tried to open it from the bloxstrap shortcut, but then this error showed up.
![image](https://github.com/user-attachments/assets/7fdc73a9-da3c-4e4b-bd85-6616398ec37e)

### Bloxstrap Log

[Bloxstrap_20240929T070246Z.log](https://github.com/user-attachments/files/17178324/Bloxstrap_20240929T070246Z.log)

**Comment by NabHeyka22** [comment]
Update.
If you want multi instance, use Roblox account manager, no it's not a virus it's safe, yes it's a false positive.
If you don't want to use anything else but bloxstrap we won't help you, nor the devs will.

**Comment by JJrD243** [comment]
No, that’s not what happened, and no, I am using bloxstrap. I just
activated and deactivated a vpn.

**Comment by NabHeyka22** [comment]
> No, that’s not what happened, and no, I am using bloxstrap. I just
activated and deactivated a vpn.
You're using an outdated version of Bloxstrap.
