### ISSUE TITLE
Roshade support

### ISSUE THREAD

**Issue by MehKako** [pizzaboxer/bloxstrap#30]
If you install bloxstrap roshade does not detect roblox since its installed in another location. Add an option to auto install roshade like the fps unlocker.

**Comment by pizzaboxer** [comment]
This is an idea I have considered before, but there's a slight problem - I don't think Roshade is suitable for use in something like this.
Roshade is put behind a paywall, with the free tier having stuff like no auto-updating and ads before downloading to incentivise subscribing to a pro membership.
Adding Roshade as a Bloxstrap integration would (for better or for worse) eliminate those incentives, something which I can imagine the creator wouldn't be very happy with. Besides, their [license](https://github.com/bituq/Roshade/blob/main/LICENSE) reflects this too (permission required for redistribution).

As for making Bloxstrap work with Roshade, installing Bloxstrap to the Roblox folder in local appdata as a workaround should work fine without any issues.
