### ISSUE TITLE
[BUG] fflags not working ingame

### ISSUE THREAD

**Issue by ogbq** [pizzaboxer/bloxstrap#3001]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

It seems to have been like this for a while now, but when I join a game, the FFlags seem to not be there or work. I will show my clientappsettings down below.

{
  "FFlagHandleAltEnterFullscreenManually": "False",
  "FLogNetwork": "7",
  "DFIntTaskSchedulerTargetFps": "5588562",
  "FFlagDisablePostFx": "True",
  "FFlagFixGraphicsQuality": "True",
  "FIntFullscreenTitleBarTriggerDelayMillis": "3600000",
  "FIntUGCValidationLeftArmThresholdBack": "23",
  "FIntUGCValidationLeftlegThresholdBack": "40",
  "FIntUGCValidationLeftlegThresholdFront": "40",
  "FIntUGCValidationRightArmThresholdBack": "23",
  "FIntUGCValidationRightArmThresholdFront": "25",
  "FIntUGCValidationTorsoThresholdBack": "100",
  "FIntUGCValidationLeftArmThresholdFront": "27",
  "FIntUGCValidationLeftArmThresholdSide": "40",
  "FIntUGCValidationLeftlegThresholdSide": "36",
  "FIntUGCValidationRightLegThresholdBack": "40",
  "FIntUGCValidationRightArmThresholdSide": "40",
  "FIntUGCValidationRightLegThresholdSide": "38",
  "FIntUGCValidationTorsoThresholdFront": "100",
  "FIntUGCValidationTorsoThresholdSide": "100",
  "FIntUGCValidationRightLegThresholdFront": "40"
}

These are the FFlags being used currently. I will now show a screenshot of them not working.

![image (1)](https://github.com/user-attachments/assets/4c71425d-0e42-481d-908c-0a303a609e22)

0-21 graphics not working which determines the other fflags arent working either.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
The 21 advanced bar got removed by Roblox, no there's no fix, no bloxstrap can't fix it cause we aren't roblox engineers, and no again there's no fix.

**Comment by ogbq** [comment]
> The 21 advanced bar got removed by Roblox, no there's no fix, no bloxstrap can't fix it cause we aren't roblox engineers, and no again there's no fix.

So, any fast flag doesn't work anymore?
