### ISSUE TITLE
[BUG] V1 Escape menu bugged

### ISSUE THREAD

**Issue by Max-9632** [pizzaboxer/bloxstrap#3004]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

a recent bug thats been happening to me is the v1 preferred escape menu which i have set in bloxstrap isnt working as intended instead of it showing all the player list and that the ui is just bugged not letting you reset or leave the game please see the images below 
[Image 1](https://cdn.max9632.cc/RobloxPlayerBeta_Esrfiw7mpb.jpg)
[Image 2](https://cdn.max9632.cc/RobloxPlayerBeta_MsdzvgpOKa.jpg)
[Image 3](https://cdn.max9632.cc/RobloxPlayerBeta_osxlPLxSWV.jpg)
[Image 4](https://cdn.max9632.cc/Bloxstrap_7VMD5KGoPp.png)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Add this fflag
{
  "FFlagFixReportButtonCutOff": "False"
}
If it doesn't work, use another menu like the 2023 menu.

**Comment by Max-9632** [comment]
testing it now

**Comment by Max-9632** [comment]
> Add this fflag { "FFlagFixReportButtonCutOff": "False" } If it doesn't work, use another menu like the 2023 menu.

it worked thanks man

**Comment by NabHeyka22** [comment]
Yw.
