### ISSUE TITLE
[BUG] I can't leave with 2015-2022 escape menu.

### ISSUE THREAD

**Issue by maxjcreeper** [pizzaboxer/bloxstrap#3005]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

 when i press escape menu with 2015-2022 escape menu on, its just blank. i also can't leave from clicking the x in the corner.
reset character also doesn't work either.
example:
![Roblox 9_29_2024 11_59_18 AM](https://github.com/user-attachments/assets/67ea704c-ef54-4785-9b14-351ca86cad5c)
i have to task manager to leave.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Add this fflag
{
"FFlagFixReportButtonCutOff": "False"
}
If it doesn't work, use another menu like the 2023 menu.

**Comment by maxjcreeper** [comment]
how do i add fflags?

**Comment by NabHeyka22** [comment]
Bloxstrap menu, fastflags section, scroll down, fastflag editor, carefully read the warning, click add flag, click import json, then put the fflag in.

**Comment by maxjcreeper** [comment]
it won't let me change the text in there

**Comment by maxjcreeper** [comment]
TYSM
