### ISSUE TITLE
[REQ] Why was Muti instance launching removed(and if you can add it back then please do)

### ISSUE THREAD

**Issue by KiaantheGamer** [pizzaboxer/bloxstrap#3006]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Hello Pizzaboxer i wanted to launch mutiple instances for roblox and found that the option to enable it wasnt there and i saw that it got removed and people on youtube were saying download the older version so can you please add it back

**Comment by NabHeyka22** [comment]
Pizzaboxer removed multi instancing due to it being unstable. And most likely, pizzaboxer won't add this feature back.

**Comment by ultradev-coder** [comment]
people were using it for farming with multiple accounts

**Comment by Wanwood1** [comment]
> people were using it for farming with multiple accounts

This is not the reason, the actual reason is posted above by our great friend NabHeyka.

**Comment by pizzaboxer** [comment]
Addressed on the Wiki
