### ISSUE TITLE
[REQ] Add a restore to default button in flags editor tab

### ISSUE THREAD

**Issue by roblosplaya** [pizzaboxer/bloxstrap#3007]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

removes all added flags and restores preset flags to default

**Comment by Mugetsu895** [comment]
I swear this was suggested before 🤔

**Comment by Mugetsu895** [comment]
https://github.com/pizzaboxer/bloxstrap/issues/2865#issue-2514681390

**Comment by roblosplaya** [comment]
ok

**Comment by roblosplaya** [comment]
> [#2865 (comment)](https://github.com/pizzaboxer/bloxstrap/issues/2865#issue-2514681390)

ok

**Comment by pizzaboxer** [comment]
Duplicate of #2865
