### ISSUE TITLE
[BUG] Lookup the server failed with Cloudflare Network (1.1.1.1)

### ISSUE THREAD

**Issue by minh150909** [pizzaboxer/bloxstrap#3008]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

The feature "See server location when joining a game" is bugged at the location of the server, intrance ID with ping still normal.
This is only happen with 1.1.1.1, between WARP <-> DNS.
1.1.1.1 Cloudflare server location: Ho Chi Minh City, VN
![image](https://github.com/user-attachments/assets/8110ab28-53c0-4c46-b2fc-c6717e7d1c73)

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
You're being ratelimited by the IP lookup API because you're on a VPN.
