### ISSUE TITLE
[REQ] Nightly Update Channel

### ISSUE THREAD

**Issue by Zacgamingpro1234** [pizzaboxer/bloxstrap#3011]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would suggest that you add a nightly update channel for bloxstrap. Users can opt-in for using the nightly channel which can also be a benefit since these would act like testers.

**Comment by bluepilledgreat** [comment]
This has been discussed privately and this isn't happening for now.
