### ISSUE TITLE
Deleting custom sounds

### ISSUE THREAD

**Issue by SmellyBozoAce** [pizzaboxer/bloxstrap#3014]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When I add a custom player sound with emulate old character sounds on, it deletes the sound I added, and if I add the old character sounds back with emulate old character sounds off it deletes them but keeps the sound I added.

**Comment by pizzaboxer** [comment]
Okay, what's the problem here?

**Comment by SmellyBozoAce** [comment]
> Okay, what's the problem here? You're not explaining this clearly.

When I change one of the sounds that the emulate old character sound setting adds, it reverts it when I relaunch Roblox.

**Comment by SmellyBozoAce** [comment]
> > Okay, what's the problem here? You're not explaining this clearly.
> 
> When I change one of the sounds that the emulate old character sound setting adds, it reverts it when I relaunch Roblox.

Accidentally closed.

**Comment by pizzaboxer** [comment]
> When I change one of the sounds that the emulate old character sound setting adds, it reverts it when I relaunch Roblox.

Did you disable the preset first?

**Comment by SmellyBozoAce** [comment]
> > When I change one of the sounds that the emulate old character sound setting adds, it reverts it when I relaunch Roblox.
> 
> Did you disable the preset first?

Yes, and it works, but I want those sounds and the one I added. If I turn off the preset it removes the old character sounds if I add them back.

**Comment by pizzaboxer** [comment]
The next version of Bloxstrap (which should release in about a week or so) should address this
