### ISSUE TITLE
[REQ] New ROBLOX Installer Launcher

### ISSUE THREAD

**Issue by BaoCreata123** [pizzaboxer/bloxstrap#3017]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

When I install Roblox with the new launcher. It appeared like this.
![image](https://github.com/user-attachments/assets/32bc8003-f3f8-478d-be15-868738c6ed91)
That is so nice, not gonna lie.

**Comment by bluepilledgreat** [comment]
> That is so nice, not gonna lie.

Stop lying

**Comment by BaoCreata123** [comment]
HOW DO YOU KNOW THAT I AM LYING?

**Comment by BaoCreata123** [comment]
https://github.com/user-attachments/assets/704620e7-b8aa-48f6-8d33-d8653969ca26

**Comment by Wanwood1** [comment]
What is the point of this thread? Are you reporting an issue?

**Comment by NabHeyka22** [comment]
> What is the point of this thread? Are you reporting an issue?

He posted a feature request, possibly asking for this new loading screen to be added.

**Comment by BaoCreata123** [comment]
Oh. Alright then.
It would be nice if we can customize the launcher background by using Bloxstrap.

**Comment by pizzaboxer** [comment]
>  It would be nice if we can customize the launcher background by using Bloxstrap.

thanks for reminding me about that i actually completely forgot

**Comment by BaoCreata123** [comment]
oh lol
