### ISSUE TITLE
[BUG] I dont have the multi account option

### ISSUE THREAD

**Issue by stupidav2** [pizzaboxer/bloxstrap#3019]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I dont have the multiple accounts version, i searched everywhere
![image](https://github.com/user-attachments/assets/d7e956da-d4c2-4e2b-b2b3-e25693178deb)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
It has been removed.
If you want multi instance, use roblox account manager, no it's not a virus, source code is public, you can look at it.
If you don't want to use anything but bloxstrap, we, devs and members included, won't help you.
