### ISSUE TITLE
is there anyway to stop roblox from switching to shadowmap? (question)

### ISSUE THREAD

**Issue by ihad11cats** [pizzaboxer/bloxstrap#302]
hello again and i was wondering if there is any way for me to stop roblox from using shadowmap and start using future is bright or is my system is too outdated? (i was in the #274 and showed my specs there)

**Comment by pizzaboxer** [comment]
> or is my system is too outdated?

Yeah, we said in that thread that your specs definitely were not enough to be running Roblox with Future lighting.
