### ISSUE TITLE
[BUG] Bloxstrap does not start, uninstaller is also dead

### ISSUE THREAD

**Issue by Aleksszz** [pizzaboxer/bloxstrap#3024]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Lately my Bloxstrap has started erroring out with a Http.Timeout exception error. Once i get to the log thingy, it just completely crashes. I have tried uninstalling it but even the installer doesn't work. What am I supposed to do? I did all the plausible solutions from the wiki to no avail. Only thing that might be interfering with Bloxstrap is the fact that im on Windows 7.

### Bloxstrap Log

N/A

**Comment by TooLongIdling** [comment]
why are you not on windows 10/11, windows 7 has been out of commission since 2020

**Comment by Aleksszz** [comment]
> Any screenshots? You can't tell me there's an exception and then not tell me what it is. And what happens when you try to uninstall it?

The problem is the log doesn't generate because bloxstrap crashes before I can click to get the log. I can only give you a screenshot of the window which is down below:
As for what happens when i try to uninstall it, I can see the Bloxstrap process does start but does nothing. No window, no uninstaller, nothing
![01](https://github.com/user-attachments/assets/95f0aca3-8de7-472d-852e-108b8ea88b3c)
