### ISSUE TITLE
[BUG] Fps drop when reinstalling bloxstrap

### ISSUE THREAD

**Issue by maseeeee** [pizzaboxer/bloxstrap#3026]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I accidentally uninstalled bloxstrap, and when I reinstalled it my fps now goes to 30-60 fps. It used to be 130 fps when I had bloxstrap now its not.

**Comment by maseeeee** [comment]
I also deleted all my fastflags.

**Comment by Shavixinio** [comment]
Depends what game you join and how many players it has. It can't be affected by Bloxstrap

**Comment by pizzaboxer** [comment]
Did you have any settings configured before uninstalling it?

**Comment by maseeeee** [comment]
No i did not. I play evade and it used to run at 130 fps.

**Comment by maseeeee** [comment]
Hello? please respond if you can

**Comment by maseeeee** [comment]
I think I had game mode turned on

**Comment by Shavixinio** [comment]
If you think that somehow lowered your fps, then you can close this issue.

**Comment by maseeeee** [comment]
It turned it off and it's still the same and I downloaded the
latest version of Bloxstrap too.

**Comment by maseeeee** [comment]
I also don't use fastflags and I set all my bloxstrap settings to the way
they were, and its still not working.

**Comment by maseeeee** [comment]
Also every time whenever I run roblox it doesn't run with bloxstrap?

**Comment by maseeeee** [comment]
My roblox runs with bloxstrap and still doesn't work. I might even quit
roblox because of this.

**Comment by maseeeee** [comment]
The same thing happened to me when I first installed bloxstrap. I have no
idea how I even got it to work.

**Comment by maseeeee** [comment]
before

**Comment by maseeeee** [comment]
work before*

**Comment by maseeeee** [comment]
Please resolve this issue as soon as possible.Thank you :)

**Comment by Shavixinio** [comment]
Uninstall bloxstrap, and after that, go to %localappdata%, and delete the Roblox folder. This should do a real reset of Roblox (and will also uninstall Roblox).

Finally you can reinstall Roblox normally or install with Bloxstrap again. If that doesn't work, the performance issues is most likely something related to another software, or even hardware issue.

**Comment by maseeeee** [comment]
Ok, I will try this out. Thank you

**Comment by pizzaboxer** [comment]
> No i did not. I play evade and it used to run at 130 fps.

I'm struggling to see how "I reinstalled Bloxstrap and my performance is now somehow worse" is somehow a problem on my end. I didn't change anything, you're still using the same version of Bloxstrap, and I don't do anything (by default) that can affect Roblox's performance.

**Comment by maseeeee** [comment]
I tried this but sadly it didn't work. Thanks for the help though.
