### ISSUE TITLE
[REQ] Could the 2020 Menu Be Added Back?

### ISSUE THREAD

**Issue by paperboi31** [pizzaboxer/bloxstrap#3027]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I was using the new Bloxstrap update (2.7.0) and noticed that the 2020 menu option was removed, I enjoyed that menu and I'm wondering if it could be brought back, If it can't, i would like to know why. Thank you!

**Comment by pizzaboxer** [comment]
No because Roblox removed it

**Comment by paperboi31** [comment]
> No because Roblox removed it

Thank you!
