### ISSUE TITLE
Files missing after installing

### ISSUE THREAD

**Issue by TheEmeraldCreeperRB** [pizzaboxer/bloxstrap#303]
I Was about to create something in roblox Studio, Before finding all the models i had saved were missing after installing Bloxstrap. Is there a way to recover them?

**Comment by pizzaboxer** [comment]
Where did you install Bloxstrap to?

**Comment by TheEmeraldCreeperRB** [comment]
Think the files all actually moved to my downloads somehow

**Comment by TheEmeraldCreeperRB** [comment]
My Documents file
Everything else in there was deleted, too

**Comment by pizzaboxer** [comment]
I don't really know what to tell you, but I don't think this has any correlation with Bloxstrap. It only deletes directories inside where it has been installed to. From what you're saying, you set your install location as your programs folder (assuming inside C:\Program Files or %localappdata% as it does by default). There's no reason for it to touch your Documents folder whatsoever.
