### ISSUE TITLE
Is there any fastflags that changes your font size?

### ISSUE THREAD

**Issue by I-am-Sachi** [pizzaboxer/bloxstrap#3032]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I couldn't find any fflags where i can change my font sizes to below zero.

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Bloxstrap menu, FastFlags section, scroll down, font size.

**Comment by I-am-Sachi** [comment]
Thanks, I was new so you helped so much,

**Comment by NabHeyka22** [comment]
Yw.
