### ISSUE TITLE
[BUG] when i open bloxstrap it says you must install .NET Desktop Runtime to run this application so i downloaded it and it still says the same thing how to fix?

### ISSUE THREAD

**Issue by Darkmatter5627** [pizzaboxer/bloxstrap#3033]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Capture](https://github.com/user-attachments/assets/2dfa8fb9-c530-499a-bfe0-ba2692f8e533)

### Bloxstrap Log

N/A

**Comment by Darkmatter5627** [comment]
![image](https://github.com/user-attachments/assets/e740e9a5-1774-4f4a-aa1b-10b296d3f95f)

**Comment by NabHeyka22** [comment]
Just to make sure, you clicked yes on the first time when it popped up?

**Comment by Darkmatter5627** [comment]
i did

**Comment by NabHeyka22** [comment]
Idk then honestly.

**Comment by Darkmatter5627** [comment]
hold up

**Comment by Darkmatter5627** [comment]
maybe it's interfering with bloxstrap?

**Comment by Darkmatter5627** [comment]
let me delete it to see if it is

**Comment by Darkmatter5627** [comment]
nope

**Comment by Darkmatter5627** [comment]
i cant delete it 
![image](https://github.com/user-attachments/assets/658b4011-9e16-4e60-aba5-72cd96f54807)

**Comment by Darkmatter5627** [comment]
i fixed it
