### ISSUE TITLE
[BUG] Some of the fonts aren't changing using custom font

### ISSUE THREAD

**Issue by I-am-Sachi** [pizzaboxer/bloxstrap#3034]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/d03d3704-9171-483e-b960-e1eb9fc7cfb3)
Here's what's happening, you see there is a font that is applied (which is MSMincho.ttf on the changelog board)
and those fonts that aren't applied to the one that I want to change it. (You can see it on the top and the daily challenge section)

What's the problem causing this?

### Bloxstrap Log

N/A

**Comment by I-am-Sachi** [comment]
![image](https://github.com/user-attachments/assets/e32ec146-b702-4577-9e69-31eba207912c)
 here is another font that isn't changing

**Comment by I-am-Sachi** [comment]
apparently these fonts including montserrat are not changing
![image](https://github.com/user-attachments/assets/de4b946d-b049-46c1-8ce2-483980676914)
i guess this issue has to do with this json file
![image](https://github.com/user-attachments/assets/9859053d-dd47-49c7-9c28-67ea5bfbfc50)
but idk what's the issue with it

**Comment by I-am-Sachi** [comment]
here's my configuration if you need it
[Settings.json](https://github.com/user-attachments/files/17248474/Settings.json)
[State.json](https://github.com/user-attachments/files/17248475/State.json)
[ClientAppSettings.json](https://github.com/user-attachments/files/17248483/ClientAppSettings.json)

**Comment by I-am-Sachi** [comment]
uhh

**Comment by pizzaboxer** [comment]
Those are creator marketplace fonts. Bloxstrap is only able to replace locally-loaded fonts.
