### ISSUE TITLE
[BUG] pause screen (menu) is blank, only the Leave, reset and Resume button, doesnt let to leave!

### ISSUE THREAD

**Issue by Domxoxo** [pizzaboxer/bloxstrap#3035]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

ive installed bloxstrap, added a font, one mod (remodeling r6) and launched it, when i click Escape, the pause menu is blank! only the button at the bottom, lemme get a picture
![image](https://github.com/user-attachments/assets/bc74ea90-0f11-40d8-a55e-5d405e13c0c5)

### Bloxstrap Log

no log.

**Comment by NabHeyka22** [comment]
Are you kidding me man?
Add this fflag:
{
  "FFlagFixReportButtonCutOff": "False"
}
If it doesn't work, use something else like the 2023 menu.
If you're wondering how to add this, bloxstrap menu, fastflags section, scroll down, fastflags editor, read the warning, click the button, add new, import json, paste it there.
If it doesn't work and you don't want to switch menus, we won't help you.

**Comment by NabHeyka22** [comment]
Yw.
