### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by nihalious** [pizzaboxer/bloxstrap#3037]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Error 403 while already having the latest version of Bloxstrap (v2.7.0)

### Bloxstrap Log

[Bloxstrap_20241003T174343Z.log](https://github.com/user-attachments/files/17248026/Bloxstrap_20241003T174343Z.log)

**Comment by NabHeyka22** [comment]
This is possibly an issue Roblox made by doing something wrong.
Please wait until Roblox themselves fix this issue.

**Comment by nihalious** [comment]
I just checked Roblox itself, Roblox works but when I use Bloxstrap v2.7 it does not work (I have reinstalled Bloxstrap)

**Comment by NabHeyka22** [comment]
Yes, but i think it's because Roblox puts you into the channel directly but this channel switching broke Bloxstrap. I'm not sure tho and i may be wrong since i'm a dumbass

**Comment by Sweizzy** [comment]
I have the same problem now.

> I just checked Roblox itself, Roblox works but when I use Bloxstrap v2.7 it does not work (I have reinstalled Bloxstrap)

**Comment by NabHeyka22** [comment]
I would kindly ask you to read above please. And i would also kindly ask you to do some research on other GitHub posts.

**Comment by Sweizzy** [comment]
> I would kindly ask you to read above please. And i would also kindly ask you to do some research on other GitHub posts.

so what should we do? nothing works for me even after reinstallation.
