### ISSUE TITLE
In-Game GUI Preference Not Working.

### ISSUE THREAD

**Issue by NicTheBaller69** [pizzaboxer/bloxstrap#304]
I might be misunderstanding this feature but I would love the old in-game gui back. I changed the ingame gui to 2015 and it is the same as it is now. 

![image](https://github.com/pizzaboxer/bloxstrap/assets/136278285/045f2bd1-2681-486c-bfd8-80a9b15c37fa)
![image](https://github.com/pizzaboxer/bloxstrap/assets/136278285/b13305d3-9e1f-4cc4-a89c-45fbab479884)

**Comment by pizzaboxer** [comment]
> I might be misunderstanding this feature

It's talking about the escape menu, sorry for the confusion.

**Comment by NicTheBaller69** [comment]
thank you for the speedy response
