### ISSUE TITLE
BloxStrap Not Opening

### ISSUE THREAD

**Issue by blazek983** [pizzaboxer/bloxstrap#3040]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

I tried using the new version of blox straps but its gives me the same thing

### Bloxstrap Log

[Bloxstrap_20241003T175606Z.log](https://github.com/user-attachments/files/17248138/Bloxstrap_20241003T175606Z.log)

**Comment by NabHeyka22** [comment]
This is possibly an issue Roblox made by doing something wrong.
Please wait until Roblox themselves fix this issue.

Please search first before doing posts.
