### ISSUE TITLE
bloxstrap error Bloxstrap_20241003T175752Z

### ISSUE THREAD

**Issue by 2ogicle** [pizzaboxer/bloxstrap#3041]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/bd2c2297-6924-418b-a46e-c730a07052a8)
tried to install the most recent version after error (forbidden) 403 became a problem. installed 2.70 and still isnt letting me on

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
Send your log file
