### ISSUE TITLE
[BUG] i cant change a couple of settings what include: setting your graphics to 21 and changing the escape menu on roblox 

### ISSUE THREAD

**Issue by plug149m** [pizzaboxer/bloxstrap#3042]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

so when i ever do those settings it dose not save in roblox for some reason???? but with other settings it will save??

**Comment by NabHeyka22** [comment]
The FFlag for the 21 graphic bar is removed by Roblox. No, Bloxstrap can't do anything about it, no there's no other fix.

**Comment by plug149m** [comment]
what about the escape menu?
