### ISSUE TITLE
a 403 error code bug

### ISSUE THREAD

**Issue by Ignis12345** [pizzaboxer/bloxstrap#3045]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

According to the Bloxstrap wiki, error code 403 can occur if you don't have the latest version of Bloxstrap, but the thing is that i do, as of rn its v2.7.0

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Read. Other. Posts.

**Comment by Sweizzy** [comment]
WHT.

**Comment by NabHeyka22** [comment]
Basically, since you're too lazy to research, Roblox issue that bugged bloxstrap. Can't do anything about it. Wait until it's fixed.

**Comment by astralwww** [comment]
i got the same problem and bro how to fix it for real?????

**Comment by NabHeyka22** [comment]
> i got the same problem and bro how to fix it for real?????

You can't.

**Comment by Mightyrz** [comment]
i guess we gotta wait for  v2,8 .0

**Comment by aSpider32** [comment]
Found a fix for it (i guess it will work for other people)
on the bloxstrap settings file (Settings.json) change "Channel" to "LIVE"
