### ISSUE TITLE
fix error 403 on Bloxstrap

### ISSUE THREAD

**Issue by 9shan691** [pizzaboxer/bloxstrap#3046]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i am on the latest version of bloxstrap i unstillaed it multiple times restarted my pc and i checked thw wiki and alredy tryed and it still didnt work so idk what to do please help me thank you pizzaboxer 
[Bloxstrap_20241003T181036Z.log](https://github.com/user-attachments/files/17248387/Bloxstrap_20241003T181036Z.log)
[Bloxstrap_20241003T181312Z.log](https://github.com/user-attachments/files/17248388/Bloxstrap_20241003T181312Z.log)
[Bloxstrap_20241003T181806Z.log](https://github.com/user-attachments/files/17248389/Bloxstrap_20241003T181806Z.log)

### Bloxstrap Log

N/A

**Comment by astralwww** [comment]
Roblox issue that bugged bloxstrap. Can't do anything about it. Wait until it's fixed.
