### ISSUE TITLE
the error 403 is unsolvable

### ISSUE THREAD

**Issue by Lifeawaypdf** [pizzaboxer/bloxstrap#3048]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

everything i did it still does not work

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
One more post related to the same issue and i'm gonna break.

**Comment by astralwww** [comment]
> One more post related to the same issue and i'm gonna break.

yeah everyone asking about it now

**Comment by Lifeawaypdf** [comment]
Ty
