### ISSUE TITLE
An Exception occurred while running blox strap

### ISSUE THREAD

**Issue by pwumsii** [pizzaboxer/bloxstrap#3049]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I keep getting an error when i try to open a game through the website on roblox. everytime i try to run it, this pops up: 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

![Screenshot 2024-10-03 112146](https://github.com/user-attachments/assets/7ab1377d-b2dc-402b-a37e-31a5563b3554)

### Bloxstrap Log

[Bloxstrap_20241003T182258Z.log](https://github.com/user-attachments/files/17248435/Bloxstrap_20241003T182258Z.log)

**Comment by NabHeyka22** [comment]
READ OTHER POSTS. I'M FUCKING BEGGING YOU.

**Comment by pwumsii** [comment]
> READ OTHER POSTS. I'M FUCKING BEGGING YOU.

I DID.... AND IT DIDNT HELP AT ALL I ENDED UP FIGURING IT OUT AFTER HOURS ON MY OWN

**Comment by NabHeyka22** [comment]
No you didn't. You would have read the wiki and the solution would help you. But you just don't read it for some reason.
