### ISSUE TITLE
Exception error.

### ISSUE THREAD

**Issue by SoulHuntxr** [pizzaboxer/bloxstrap#3050]

**Comment by NabHeyka22** [comment]
READ OTHER FUCKING POSTS. I'M FUCKING BEGGING YOU.

**Comment by astralwww** [comment]
> READ OTHER FUCKING POSTS. I'M FUCKING BEGGING YOU.

they are just blind

**Comment by legodetpool** [comment]
> READ OTHER FUCKING POSTS. I'M FUCKING BEGGING YOU.

alright timmy
