### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by KayleighsStuffz** [pizzaboxer/bloxstrap#3052]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Every time I launch Bloxstrap/Roblox I get this error: "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden)."

I have upgraded Bloxstrap and the error still persists. 

I've attached all three of my attempts to launch.

### Bloxstrap Log

[Bloxstrap_20241003T182156Z.log](https://github.com/user-attachments/files/17248471/Bloxstrap_20241003T182156Z.log)
[Bloxstrap_20241003T182234Z.log](https://github.com/user-attachments/files/17248472/Bloxstrap_20241003T182234Z.log)
[Bloxstrap_20241003T182501Z.log](https://github.com/user-attachments/files/17248473/Bloxstrap_20241003T182501Z.log)

**Comment by NabHeyka22** [comment]
Can you people read other posts? Please.

**Comment by bluepilledgreat** [comment]
Roblox has broken their deployment. Please wait for Roblox to fix their error.

**Comment by astralwww** [comment]
![image](https://github.com/user-attachments/assets/5ce1bbd2-e4f8-43e5-be04-1bb6da3a21cb)
