### ISSUE TITLE
403 XD

### ISSUE THREAD

**Issue by Sweizzy** [pizzaboxer/bloxstrap#3054]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

now i to have this pronlem

### Bloxstrap Log

[Bloxstrap_20241003T182630Z.log](https://github.com/user-attachments/files/17248484/Bloxstrap_20241003T182630Z.log)

**Comment by NabHeyka22** [comment]
Read. Other. Posts.

**Comment by Sweizzy** [comment]
> Read. Other. Posts.

![Screenshot_2285](https://github.com/user-attachments/assets/25c078e9-b65f-4518-95b2-1c5867c3016f)
