### ISSUE TITLE
[BUG] Bloxstrap errors out with response code 403

### ISSUE THREAD

**Issue by komikazui** [pizzaboxer/bloxstrap#3055]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When launching an experience, Bloxstrap retuns a response code of 403. I assume this is due to a new client being pushed, but i could be wrong. Below attached is my logfile.

### Bloxstrap Log

[Bloxstrap_20241003T182557Z.log](https://github.com/user-attachments/files/17248506/Bloxstrap_20241003T182557Z.log)

**Comment by NabHeyka22** [comment]
DO SOME RESEARCH YOU ABSOLUTE GOOBERS. PLEASE.

**Comment by bluepilledgreat** [comment]
> DO SOME RESEARCH YOU ABSOLUTE GOOBERS. PLEASE.

be helpful.
Roblox has broken their deployment. Please wait for Roblox to fix their error.

**Comment by astralwww** [comment]
![image](https://github.com/user-attachments/assets/afc12a6c-fc0c-4019-a1cd-610b31d526b4) 

> DO SOME RESEARCH YOU ABSOLUTE GOOBERS. PLEASE.

they are just blind bro they cant look at news channel

**Comment by komikazui** [comment]
Please do not be rude. I have already done multiple troubleshooting steps and norhing works.

**Comment by bluepilledgreat** [comment]
> ![image](https://private-user-images.githubusercontent.com/183757014/373372060-afc12a6c-fc0c-4019-a1cd-610b31d526b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODA1ODYsIm5iZiI6MTcyNzk4MDI4NiwicGF0aCI6Ii8xODM3NTcwMTQvMzczMzcyMDYwLWFmYzEyYTZjLWZjMGMtNDAxOS1hMWNkLTYxMGIzMWQ1MjZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxODMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWU2ZTM3ZmViODQ0MWI3MTdhOGRiMzM3NjI2YzhhM2Q2NWZiMDJlNDNmMjhhM2U4NTZhODEwYTRhNDZiYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gK8jqlhb3FFxg-e_oLjXyR_fop9iNsrpll1zE-mtxXY)
> 
> > DO SOME RESEARCH YOU ABSOLUTE GOOBERS. PLEASE.
> 
> they are just blind bro they cant look at news channel

not everyone is in the discord??? idiot.

**Comment by astralwww** [comment]
> > ![image](https://private-user-images.githubusercontent.com/183757014/373372060-afc12a6c-fc0c-4019-a1cd-610b31d526b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODA1ODYsIm5iZiI6MTcyNzk4MDI4NiwicGF0aCI6Ii8xODM3NTcwMTQvMzczMzcyMDYwLWFmYzEyYTZjLWZjMGMtNDAxOS1hMWNkLTYxMGIzMWQ1MjZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxODMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWU2ZTM3ZmViODQ0MWI3MTdhOGRiMzM3NjI2YzhhM2Q2NWZiMDJlNDNmMjhhM2U4NTZhODEwYTRhNDZiYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gK8jqlhb3FFxg-e_oLjXyR_fop9iNsrpll1zE-mtxXY)
> > > DO SOME RESEARCH YOU ABSOLUTE GOOBERS. PLEASE.
> > 
> > 
> > they are just blind bro they cant look at news channel
> 
> not everyone is in the discord??? idiot.

well true but i think most of community is in discord

**Comment by NabHeyka22** [comment]
> be helpful.

I'm tired of all the duplicates man. I'm sorry.
