### ISSUE TITLE
Response status code does not indicate success

### ISSUE THREAD

**Issue by Gadery1** [pizzaboxer/bloxstrap#3057]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I am suddenly having trouble with joining any game, and by **any,** I mean it.

### Bloxstrap Log

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).

**Comment by bluepilledgreat** [comment]
Read the pinned post about this problem.

**Comment by Gadery1** [comment]
Update: Resolved :DDD
