### ISSUE TITLE
roblox

### ISSUE THREAD

**Issue by daniil10903** [pizzaboxer/bloxstrap#3058]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

play roblox

### Bloxstrap Log

N/A

**Comment by daniil10903** [comment]
play how

**Comment by bluepilledgreat** [comment]
Read the pinned post about this problem.
