### ISSUE TITLE
Bloxstrap Menu missing

### ISSUE THREAD

**Issue by Max56466** [pizzaboxer/bloxstrap#306]
I've searched up on the taskbar ''Bloxstrap Menu''. But it didnt pop up, i have looked my files but it's completely missing.

**Comment by pizzaboxer** [comment]
It doesn't appear in your Start menu's program list? Check to see if your antivirus did something with Bloxstrap.

**Comment by Max56466** [comment]
> 

Nope, doesn't appear in the start menu program list. What do i have to do?

**Comment by pizzaboxer** [comment]
> Check to see if your antivirus did something with Bloxstrap.

**Comment by Max56466** [comment]
Probably yes, but i don't see where they did smth with bloxstrap

**Comment by pizzaboxer** [comment]
Is Bloxstrap still located in `%appdata%\Bloxstrap`, assuming you didn't change where it was installed?

**Comment by Max56466** [comment]
> Is Bloxstrap still located in `%localappdata%\Bloxstrap`, assuming you didn't change where it was installed?

Yes it's still located in %localappdata%\Bloxstrap`. But i still don't understand why theres no menu.

**Comment by pizzaboxer** [comment]
Bloxstrap should try to reregister the menu shortcut whenever Roblox is launched. Can you check to see if there's a Bloxstrap folder in `%appdata%\Microsoft\Windows\Start Menu\Programs`?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
