### ISSUE TITLE
[BUG] [FIXED] top right circle menu, how to revert to old square menu?

### ISSUE THREAD

**Issue by Sunivana** [pizzaboxer/bloxstrap#3062]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

normally playing the game, and it just there, I have no fflags, its just there. Preferred menu is set to default, tried the other ones, no luck.
how do i get rid of the circle menu? I absolutely hate it and want the **square** menu thingy back!?!?!?

![MedalTVRoblox20241003151432](https://github.com/user-attachments/assets/c0e26e01-09f0-4bd7-93b8-643f2db14fb1)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
"FFlagEnableInGameMenuChromeABTest4": "False"

**Comment by Sunivana** [comment]
worked, ty!!!
