### ISSUE TITLE
[BUG] Cant even screenshot but when you set classic cursors from 2006 or 2014 when you set to normal cursor iit do not changes back anymore

### ISSUE THREAD

**Issue by astralwww** [pizzaboxer/bloxstrap#3065]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i explained problem in title

**Comment by astralwww** [comment]
Nvm thanks for discord people

**Comment by pizzaboxer** [comment]
FYI: enable the "Force Roblox reinstallation" option if something like this happens
