### ISSUE TITLE
Bloxstrap unable to install, stuck on Connecting to Roblox.

### ISSUE THREAD

**Issue by FredDoesStuff** [pizzaboxer/bloxstrap#307]
My brother can't seem to install Bloxstrap as it gets stuck on Connecting to ROBLOX. 
He's trying to run this on Windows 7, incase his OS is important and his computer is most certainly not weak, as it can run ROBLOX on max graphics. Heres a log
edit: log was a roblox log, and bloxstrap folder has no files at all.

**Comment by EasternBloxxer** [comment]
> My brother can't seem to install Bloxstrap as it gets stuck on Connecting to ROBLOX. He's trying to run this on Windows 7, incase his OS is important and his computer is most certainly not weak, as it can run ROBLOX on max graphics. Heres a log [0.578.0.5780566_20230613T025146Z_Player_E9766_last.log](https://github.com/pizzaboxer/bloxstrap/files/11730241/0.578.0.5780566_20230613T025146Z_Player_E9766_last.log)

That's a roblox log not bloxstrap

**Comment by FredDoesStuff** [comment]
> > My brother can't seem to install Bloxstrap as it gets stuck on Connecting to ROBLOX. He's trying to run this on Windows 7, incase his OS is important and his computer is most certainly not weak, as it can run ROBLOX on max graphics. Heres a log [0.578.0.5780566_20230613T025146Z_Player_E9766_last.log](https://github.com/pizzaboxer/bloxstrap/files/11730241/0.578.0.5780566_20230613T025146Z_Player_E9766_last.log)
> 
> That's a roblox log not bloxstrap

Whoops. My bad. Checked bloxstrap folder in appdata and there is no folders at all. So I can't send a log.

**Comment by pizzaboxer** [comment]
Check your %temp% folder.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
