### ISSUE TITLE
[BUG] broken In game escape menu

### ISSUE THREAD

**Issue by olzzon08** [pizzaboxer/bloxstrap#3070]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

When i change the escape menu to any other one included in bloxstrap, it does show up and all but the player list is completely gone and all of the buttons are broken and does literally nothing, the three other buttons "Reset, Leave and Resume" leads to a blank screen and cannot be used for some reason. im also completely unable to close the roblox client without the task manager to manually terminate the process. Ive also recently reinstalled my operating system since it was all broken and stuff and i have this issue still, had the same issue before the reinstallation of the operating system too

### Bloxstrap Log

N/A

**Comment by bluepilledgreat** [comment]
read pinned
