### ISSUE TITLE
Requesting source code for multi instances launching.

### ISSUE THREAD

**Issue by Cheoo21** [pizzaboxer/bloxstrap#3073]
Hey man, So recently I really need the source code for the multi instance launching but cant find it anywhere, I need the multi instances launching for various stuff but at the same time I don't want to lose the features in 2.7.0, so I wanted to ask if I can have the source code for the multi instance launching so that I can modify my bloxstrap and add that feature to my personal self.

**Comment by bluepilledgreat** [comment]
https://git-scm.com/

**Comment by Cheoo21** [comment]
not asking to redo but just want the source code. also how do you use it?

**Comment by bluepilledgreat** [comment]
you are retarded

**Comment by Zacgamingpro1234** [comment]
I think you can find it here in an older branch of the project: https://github.com/pizzaboxer/bloxstrap/tree/version-2.5.4

**Comment by Cheoo21** [comment]
> I think you can find it here in an older branch of the project: https://github.com/pizzaboxer/bloxstrap/tree/version-2.5.4

wheres the part where there's the multi launching code? i cant find it anywhere.
