### ISSUE TITLE
[BUG] Old escape menu bug

### ISSUE THREAD

**Issue by bow132542** [pizzaboxer/bloxstrap#3075]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Whenether you use an older version of an escape menu, the options never appear for Home, People, Settings, Captures, Report and Help. It would just be blank, and if you try leaving the game, you simply just can't, as the options for reseting your character or leaving the game do not function, and will just leave in a blank space with the menu open. If you tried Alt + F4, the same thing would occur, while also most of the UI dissapearing. Only way you can exit a game is through using the Task Manager.
![image_2024-10-05_185446762](https://github.com/user-attachments/assets/c9f6cc36-1f9c-4047-9807-50c9e9919ccb)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
Add this FFlag:
{
  "FFlagFixReportButtonCutOff": "False"
}
If it doesn't work, use the 2023 (V4) menu.

**Comment by bow132542** [comment]
It worked. Tysm for the help.

**Comment by somenormalperson** [comment]
wowie thank you

**Comment by somenormalperson** [comment]
i cant even close from task manager

**Comment by somenormalperson** [comment]
send help

**Comment by somenormalperson** [comment]
i restarted my computer then the menu reset to normal roblox menu without the graphic levls and the fps unlocker

**Comment by somenormalperson** [comment]
im pretty sure blox strap isnt running when i open roblox. it says opening blox strap but when i join theres no eidence of it being opened

**Comment by Wanwood1** [comment]
> im pretty sure blox strap isnt running when i open roblox. it says opening blox strap but when i join theres no evidence of it being opened

Check out the wiki

**Comment by somenormalperson** [comment]
ok

**Comment by somenormalperson** [comment]
do u know where the wiki is

**Comment by somenormalperson** [comment]
nvm
