### ISSUE TITLE
[BUG] i can't go back to settings or change it 

### ISSUE THREAD

**Issue by tesla583** [pizzaboxer/bloxstrap#3077]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i installed and some settings then i can't go back plsss fix this i need to change it

### Bloxstrap Log

N/A

**Comment by tesla583** [comment]
hey can you fix this bug plsss

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu
