### ISSUE TITLE
[BUG] help with custom ui

### ISSUE THREAD

**Issue by PopTart0053** [pizzaboxer/bloxstrap#3078]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

i just want to know how to get rid of a custom ui i added i just wanna get rid of it

### Bloxstrap Log

N/A

**Comment by DionBlox1** [comment]
Remove the UI you added, then reinstall Roblox by going to Behaviour > Force Roblox reinstallation and toggle it on. Save changes and launch Roblox. It will reinstall and remove the UI.

**Comment by pizzaboxer** [comment]
> i just want to know how to get rid of a custom ui i added i just wanna get rid of it

Delete the files from the mods folder
