### ISSUE TITLE
Make the play button launch you into the game the player is in

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#31]
Was trying to do this but couldnt figure out how to get the job id
roblox://experiences/start?placeId=PlaceId&gameInstanceId=JobId

**Comment by pizzaboxer** [comment]
Oh, didn't know you could supply a job ID as a parameter.
Anyway, I'm not really sure how I'd obtain the job ID besides having to read the game client log files, where things could very easily go wrong.
In the future, I might try it out, but right now it's not really something I'm looking to add.

**Comment by pizzaboxer** [comment]
Added in v1.5.3.
