### ISSUE TITLE
fix the vulkan render fullscreen issue

### ISSUE THREAD

**Issue by MTFGodzi** [pizzaboxer/bloxstrap#310]
ı choose vulkan and ı cant do fullscreen fix it

**Comment by pizzaboxer** [comment]
These details aren't really helping. What happens when you try to fullscreen? Does it crash? Does it just stay windowed? Anything?

**Comment by awesfdawe** [comment]
I don't think this is a bloxstrap problem since all bloxstrap does to run Roblox with Vulkan is edit the fflag.

**Comment by MTFGodzi** [comment]
how the fuck you send me mail

awesfdawe ***@***.***>, 15 Haz 2023 Per, 18:43 tarihinde şunu
yazdı:
