### ISSUE TITLE
Add the new 2023 ESC menu

### ISSUE THREAD

**Issue by Cyber2525** [pizzaboxer/bloxstrap#311]
Add the new 2023 roblox ESC menu to the bloxstrap menu options list as a v4 option, fast flags>in-game menu version>"version 4 (2023)"
![e68d7934f93a744134b08e77bfb7b86746e405f4](https://github.com/pizzaboxer/bloxstrap/assets/83342792/d0b93d47-33c3-44d7-8569-9b55c642bd43)
![Rbx menu V4](https://github.com/pizzaboxer/bloxstrap/assets/83342792/f441adc4-f874-4af0-b1c7-21891dc0e21b)

**Comment by pizzaboxer** [comment]
I already added this for the next version. Just put it in the checklist so it's clearer that it's been added.
