### ISSUE TITLE
You should add an option to replace the Xbox button textures with their Playstation equivalent

### ISSUE THREAD

**Issue by cataclysmism** [pizzaboxer/bloxstrap#313]
What the title says. I would replace the textures myself I'm too lazy + It seems that Roblox has native support for Dualshock 4 controllers, but the buttons in game represent an Xbox controller.

**Comment by pizzaboxer** [comment]
Oh, that might not be a bad idea. I'll consider that.

**Comment by cataclysmism** [comment]
I maybe partially wrong about this in the sense that Roblox may not have native support for DS4 controllers as I have DS4Windows and it's necessary prerequisites installed, but it wasn't open. If Roblox does not have native support for Playstation controllers, this may be still useful for that small group of people that use playstation controllers with an xbox controller emulator like DS4W.

**Comment by pizzaboxer** [comment]
Oh - right. I mean, if DS4Windows emulates an Xbox layout, I guess it could still be useful to have the corresponding buttons on screen? Or is there not really much point?

**Comment by cataclysmism** [comment]
Not completely sure to be honest, but trying to match Xbox buttons with a DualShock 4's layout is a little weird when playing a game. For example Y = X but they aren't in the same position on the controller, so this may still be useful.

**Comment by cataclysmism** [comment]
Just realized I had accidently closed this, not sure how GitHub works so

**Comment by pizzaboxer** [comment]
You mentioned Y = X? Shouldn't Y on an Xbox controller map to Triangle on a PlayStation controller?

**Comment by cataclysmism** [comment]
> You mentioned Y = X? Shouldn't Y on an Xbox controller map to Triangle on a PlayStation controller?

I have both a PS4 controller and Xbox Series X controller, I could check which buttons line up with each other if you'd like 

(also i have no idea how github works and it won't let me deselect close with comment so uhh if i close it just reopen it or something)

**Comment by pizzaboxer** [comment]
> I have both a PS4 controller and Xbox Series X controller, I could check which buttons line up with each other if you'd like

Yeah, please do. I know DS4Windows allows for different controller mappings, and I'm pretty sure the default mapping keeps the same button positions.

**Comment by cataclysmism** [comment]
(xbox - ps4) y = triangle, b = circle, a = x, x = square, and then the dpad n stuff are all the same

**Comment by pizzaboxer** [comment]
Yep, same positions. Thanks for confirming.

**Comment by pizzaboxer** [comment]
So I just did some research into this, and turns out that Roblox doesn't load Xbox image textures locally, it loads them online. There isn't actually a way to modify them. Sorry about that.
