### ISSUE TITLE
random Input delay ingame

### ISSUE THREAD

**Issue by tttMediumkey** [pizzaboxer/bloxstrap#318]
there is a random chance of experiencing a strange camera delay ingame which leads to a smooth yet bothering movement,
i recorded it on action in hopes of showcasing what i mean
https://steamusercontent-a.akamaihd.net/ugc/2014845430236235943/DCD975AC5AD7B2E4E9CC6022A5A49D7B01DE45EA/

**Comment by xM4rkHUN** [comment]
i got this too

**Comment by TheRealBooWasHere** [comment]
Yea me too

**Comment by pizzaboxer** [comment]
What flags do you have set? Also, check to see if it's a rendering related thing by setting the framerate limit to 0 so it's capped.

**Comment by tttMediumkey** [comment]
> a
my current fastflags are Rendering mode set to Direct3D 11
Exlucive Fullscreen
Alternative Graphics Quality selector
Ingame Menu : Default
Preferred lighting technology : Automatic

i tested the framerate limit by setting it to 0 and it seems to fix the issue

**Comment by pizzaboxer** [comment]
@xM4rkHUN @TheRealBooWasHere How about you two?

**Comment by xM4rkHUN** [comment]
> @xM4rkHUN @TheRealBooWasHere How about you two?

yo, i just saw it rn, i used these:
max fps: 120
lightning technology: auto, but i tried the voxel and it got worse
the v4 menu
rendering mode: direct3d 11
exclusive fullscreen

but actually it only happens if you have the v2.4.0 version, i switched back to v2.3.0 and it fixed. it was more common when the emulate old character sounds option was on.

**Comment by pizzaboxer** [comment]
> but actually it only happens if you have the v2.4.0 version, i switched back to v2.3.0 and it fixed. it was more common when the emulate old character sounds option was on.

I don't believe that to have any correlation, unless there were other flags you had set.
