### ISSUE TITLE
HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by M4XXIE** [pizzaboxer/bloxstrap#319]
I've been using Bloxstrap, and I seem to come across an issue when it comes to the [Asset Delivery](https://assetdelivery.roblox.com/) content.
Below is an error. I can launch ROBLOX like usual, but no textures, animations, or anything else related seems to load.

![image](https://github.com/pizzaboxer/bloxstrap/assets/99622085/1c657a0c-882b-4b19-a89f-0df74a1d960b)
![image](https://github.com/pizzaboxer/bloxstrap/assets/99622085/bdb72581-db27-4ace-90ad-65ea4a0228e5)

**Comment by builtbyvys** [comment]
I seem to be getting this issue too. I'm not completely sure why, but it seems to happen on my laptop (windows 10 pro, 22h2). My desktop is unaffected. I only have .NET 7, by the way
![image](https://github.com/pizzaboxer/bloxstrap/assets/92237104/1c05726b-a644-4bf0-a526-f8422c039a9a)

**Comment by M4XXIE** [comment]
Also, related to what @builtbyvys said, this seems to happen from time to time for me.

**Comment by pizzaboxer** [comment]
That isn't a Bloxstrap problem. That's just Roblox screwing up.
