### ISSUE TITLE
pls help my bloxstrap wont download bc of some system.10.10exception fail??

### ISSUE THREAD

**Issue by twiceisthebest12** [pizzaboxer/bloxstrap#321]
![image](https://github.com/pizzaboxer/bloxstrap/assets/137045078/37d5875a-23b5-41c7-a36a-79f8979ec828)

what does this mean?

**Comment by lokzz** [comment]
check internet.
(btw its not 10.10 its io.io)

**Comment by 20nomilius** [comment]
its maybe because of the host internet or of bloxstrap or your internet

**Comment by pizzaboxer** [comment]
Is this still happening? If it is, get the latest log file from `%localappdata%\Bloxstrap\Logs` or wherever you installed Bloxstrap to and send it here.

**Comment by xxc01** [comment]
Install this: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer
I had the same issue and installing that fixed it

**Comment by pizzaboxer** [comment]
That's definitely not the problem.

**Comment by xxc01** [comment]
Idk but when i installed that it started working

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
