### ISSUE TITLE
is there any other reason why roblox forces shadowmap?

### ISSUE THREAD

**Issue by ihad11cats** [pizzaboxer/bloxstrap#322]
is there any other reason that future is bright dosent work then my specs being outdated? because Voxel lighting works very well and it dosent switch to shadowmap when i use that but thats expected because Voxel is like normal lighting but a bit different (or atleast i didnt see much difference except for some shadows that it adds)

**Comment by pizzaboxer** [comment]
Yeah, I've kind of made this a bit confusing. The lighting modes go as this:
- Voxel (Future Is Bright Phase 1 - 2018)
- ShadowMap (Future Is Bright Phase 2 - 2019)
- Future (Future Is Bright Phase 3 - 2020)

What Bloxstrap calls "Future Is Bright" is actually Phase 3, and the proper name for it is just "Future". Voxel is the oldest of the three modes, so of course that's what your computer switches to with its low specs.

**Comment by ihad11cats** [comment]
alright thanks
