### ISSUE TITLE
Bloxstrap doesn't open

### ISSUE THREAD

**Issue by Wolkenklar** [pizzaboxer/bloxstrap#323]
Hello I just downloaded Bloxstrap and for me it doesn't open. It downloads just fine but when I try to open it nothing happens (I have CrashDump files but I don't have the Bloxstrap folder in my localappdata).

Would be great if someone could help me.

(I probably won't write back today!)

**Comment by pizzaboxer** [comment]
Where are the crash dump files and what are they named?

**Comment by Sahelantrophus** [comment]
I think you're getting Error 16

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
