### ISSUE TITLE
obs issues

### ISSUE THREAD

**Issue by ZhenChat** [pizzaboxer/bloxstrap#324]
obs cant capture bloxstrap roblox even though it can capture normal roblox

**Comment by TheNoobAlt** [comment]
Have you selected the Bloxstrap.exe? select the RobloxAppBeta.

**Comment by TheNoobAlt** [comment]
Bloxstrap\Versions\version-\RobloxPlayerBeta.exe

**Comment by ZhenChat** [comment]
im pretty sure i did select robloxplayerbeta.exe

**Comment by TheNoobAlt** [comment]
i don't know how to fix it

**Comment by pizzaboxer** [comment]
Did you change the rendering mode that Roblox uses?

**Comment by ZhenChat** [comment]
changed it to direct3d 11
turns out only vulkan works
perhaps thats it

**Comment by pizzaboxer** [comment]
What about if you leave it on Automatic?

**Comment by ZhenChat** [comment]
automatic doesnt capture

**Comment by pizzaboxer** [comment]
Weird, I guess you'll just have to leave it on Vulkan.
