### ISSUE TITLE
bloxtrap is not opening roblox

### ISSUE THREAD

**Issue by Twobigfoot1116** [pizzaboxer/bloxstrap#327]
my bloxtrap does not open roblox but this appears in the task manager
![image](https://github.com/pizzaboxer/bloxstrap/assets/114438253/34f50b5f-3f65-4098-be3f-694f027c632c)
it doesn't show that I'm playing
![image](https://github.com/pizzaboxer/bloxstrap/assets/114438253/067d2b2b-a5c3-4c3f-88e5-04c327e712ff)

**Comment by Danmccool** [comment]
happens to me to idk what it is

**Comment by pizzaboxer** [comment]
Roblox bug. You'll have to wait until they fix it. https://devforum.roblox.com/t/roblox-player-will-not-launch/2424667/58?u=xtremeguy2256

**Comment by Twobigfoot1116** [comment]
ok thx

**Comment by lokzz** [comment]
> Roblox bug. You'll have to wait until they fix it. https://devforum.roblox.com/t/roblox-player-will-not-launch/2424667/58?u=xtremeguy2256

is there a version/channel where it doesnt break?

**Comment by TheSkout** [comment]
@LordFoogThe4rd i've been playing roblox with it for months, lol. its completely fine

**Comment by TheSkout** [comment]
btw i got this issue too ((

**Comment by TheSkout** [comment]
> Roblox bug. You'll have to wait until they fix it. https://devforum.roblox.com/t/roblox-player-will-not-launch/2424667/58?u=xtremeguy2256

i hope they will fix it soon 
but only hopes (cuz its roblox)

**Comment by TheSkout** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/111308237/9ffeaf28-c512-49ab-a5d2-119c98944842)
