### ISSUE TITLE
In the latest roblox build, the menu v3 from 2021 doesn't work

### ISSUE THREAD

**Issue by Cyber2525** [pizzaboxer/bloxstrap#328]
The latest build of roblox deleted menu v3 from 2021 from the files
<img width="1280" alt="Roblox moment bug" src="https://github.com/pizzaboxer/bloxstrap/assets/83342792/3c9cd682-2fc5-4875-8d30-01807169aa35">
<img width="1280" alt="image" src="https://github.com/pizzaboxer/bloxstrap/assets/83342792/c1100d5b-1b4f-4bfa-a4b1-d4d65f0f8001">

**Comment by TheNoobAlt** [comment]
Same

**Comment by NikoYTRBLX** [comment]
Yeah I noticed this when I was running on the ZCanaryApps channel which was ahead by a couple of days.

**Comment by pizzaboxer** [comment]
Yep, I'm able to verify this too. Weird, I'll investigate later. Likely that they changed something about it since it doesn't seem like any of the flags for it have been removed.

**Comment by Cyber2525** [comment]
> Yep, I'm able to verify this too. Weird, I'll investigate later. Likely that they changed something about it since it doesn't seem like any of the flags for it have been removed.

Could you fix this for the v2.4.0?

**Comment by pizzaboxer** [comment]
Yes, of course I will. I'm not just going to knowingly leave it broken.

**Comment by Cyber2525** [comment]
pls fix this and launch now v2.4.0 pls, i lost my fav menu

**Comment by Al3cTh3L3afy** [comment]
> Yes, of course I will. I'm not just going to knowingly leave it broken.

thank you so much, your app is really good even without the V3 2021 menu :)

**Comment by Cyber2525** [comment]
> Entonces, resulta que Roblox lo eliminó por completo. Se ha ido ahora.
> 
> ![imagen](https://user-images.githubusercontent.com/41478239/248872320-947033fe-b2e7-45c0-99da-f480b4e1b14c.png)
> 
> Oh bien. Sin embargo, esto me hace preguntarme si el menú V2 también se eliminará pronto...

will you re-add the menus in the next version? it is my fav menu, pls bring it back!

**Comment by pizzaboxer** [comment]
> I'm sure that you will be able to re-integrate the menu of v3!

Nope, sorry.

**Comment by Cyber2525** [comment]
> > I'm sure that you will be able to re-integrate the menu of v3!
> 
> Nope, sorry.

i need the menu, if you dont try, I will have to do it myself

**Comment by pizzaboxer** [comment]
The code for the v3 menu was already there by default, and all Bloxstrap did was add the ability to enable it. Since Roblox completely removed the code for it, there's no way to enable it again. It's impossible, and you can try, but you won't be able to get anywhere.

**Comment by Cyber2525** [comment]
> The code for the v3 menu was already there by default, and all Bloxstrap did was add the ability to enable it. Since Roblox completely removed the code for it, there's no way to enable it again. It's impossible, and you can try, but you won't be able to get anywhere.

you can get the code of the v3 from an older version and integrate in the actual version

**Comment by NikoYTRBLX** [comment]
it doesn't work like that

**Comment by pizzaboxer** [comment]
> you can get the code of the v3 from an older version and integrate in the actual version

No you can't. It doesn't just work like that. The code is read-only and uneditable.

**Comment by lokzz** [comment]
> So, turns out that Roblox just completely removed it. It's gone now.
> 
> ![image](https://user-images.githubusercontent.com/41478239/248872320-947033fe-b2e7-45c0-99da-f480b4e1b14c.png)
> 
> Oh well. Though, this makes me wonder if the V2 menu is about to be axed soon too...

how did you get the /scripts folder?

**Comment by pizzaboxer** [comment]
> how did you get the /scripts folder?

They're available in Studio.

**Comment by Cyber2525** [comment]
> > you can get the code of the v3 from an older version and integrate in the actual version
> 
> No you can't. It doesn't just work like that. The code is read-only and uneditable.

I will try to do it, at least try to do yourself

**Comment by Kluts123** [comment]
When will the next update be where V3 Menu gets fixed.

**Comment by Kluts123** [comment]
so V3 will be removed...

**Comment by Kluts123** [comment]
... Is it complete like its been fixed or will be removed...

**Comment by lokzz** [comment]
has been removed.
v3 no longer exists in the roblox client

**Comment by Kluts123** [comment]
V2 also isnt working.
