### ISSUE TITLE
Windows Defender flagging something in Bloxstrap

### ISSUE THREAD

**Issue by carter0nline** [pizzaboxer/bloxstrap#33]
Attempting to download Bloxstrap results in a Windows Defender notification for a "severe" threat labelled as Behavior:Win32/DefenseEvasion.A!ml. The Microsoft Security Intelligence website is being glitchy so I can't get more details on that.
Opera GX refuses to continue download.
Windows 10 Pro 21H2, current Bloxstrap x64 download [here](https://github.com/pizzaboxer/bloxstrap/releases/tag/v1.5.0)

**Comment by carter0nline** [comment]
This notification shows up immediately after starting the download: 
![image](https://user-images.githubusercontent.com/83525455/196854305-ef450233-6e1f-40de-b95c-ada3a33ec95d.png)

**Comment by carter0nline** [comment]
Looking back at closed issues, it seems this isn't the first time Bloxstrap has had issues with Defender

**Comment by shiirudev** [comment]
![image](https://user-images.githubusercontent.com/106967223/197014250-a0f0c849-4090-496c-86f9-d295e89e434f.png)

**Comment by carter0nline** [comment]
I just tried again today, and now all that comes up is a SmartScreen warning. Must've updated its definitions overnight.
