### ISSUE TITLE
Game crashed when launching with Vulkan

### ISSUE THREAD

**Issue by jigguz** [pizzaboxer/bloxstrap#332]
Once upon a time in BC 233, a yung fello by the name of Felantrophosphorus was chillen by the balcony.

"Today is a good day" he exclaims with glee.

At a moments notice, he noticed a shadowy figure walk toward him

"STATE YOUR IDENTITY"

It is none other than Sir A$AP Rockilicious III Jr.

"All my A$AP killas got they pistols ready"

Felantrophosphorus notices a fleat of 110 men jump out of the mountains and village abodes

"These is my A$AP shooters" Sir A$AP Rockilicious III Jr. says

The shooters begin shooting at Felantrophosphorus in an attempt to assassinate him.

Felantrophosphorus jumps up and transforms into Super Felantrophosphorus and incinerates all of the A$AP shooters in one blast

"Hell na" A$AP exclaims

He then blows on his whistle, then 5 young men seemingly fade into the battle field.

"These the real a$ap killas i was talkin about"

5 young men introduce themselves as Pusha T, Kanye West, Big Sean, Yo Gotti, Chief Keef

They all gather their power together in a huge spirit bomb, all Felantrophosphorus could do was look at the giant light that betrothed upon his very eyes

"A$AP BOMB!!!" All 6 exclaim

The giant spirit bomb clashes into Felantrophosphorus and instantly kills him and eviscerates his entire body and atoms

"From this day forward, we shall rename this to the holy A$APVILLE" Sir A$AP exclaims

The villagers cheer

The end

**Comment by pizzaboxer** [comment]
ok
