### ISSUE TITLE
neither roblox, or bloxstrap is opening after launching a game

### ISSUE THREAD

**Issue by hqnestly** [pizzaboxer/bloxstrap#334]
this issue seems to appear out of nowhere, after pressing to launch a game in the roblox web app nothing seems to happen after the bloxstrap starting screen, only a roblox game client process 
![2023-06-22_19h36_45](https://github.com/pizzaboxer/bloxstrap/assets/74372759/c40cdc52-819f-43f3-92e3-247d37e02060)
i have runtime installed correctly 
![image](https://github.com/pizzaboxer/bloxstrap/assets/74372759/94de05e4-2858-4f17-84da-23747a601d67)

also not even the normal roblox player is opening, only the microsoft store verison is working

**Comment by hqnestly** [comment]
also, i tried installing through the LIVE channel and the zNext channel, but nothing seemed to change

**Comment by pizzaboxer** [comment]
Oh, forgot to pin the relevant issue. See #327. Make sure RTSS isn't running in the background. Also, how would Bloxstrap not be opening if Roblox is launching?

**Comment by hqnestly** [comment]
bro fr u are a life saver it worked

**Comment by hqnestly** [comment]
thank u
