### ISSUE TITLE
ROBLOX does not open but exists in task manager, log file spams "Could not find recent enough log file, waiting..."

### ISSUE THREAD

**Issue by ChatTillYouDie** [pizzaboxer/bloxstrap#335]
It has been doing this since yesterday. Yes, I'm aware that RTSS and MSI Afterburner are causing these issues, but closing them doesn't work for me. In the devforum post, none of them posted a log file so I couldn't pinpoint the problem. Here's mine.
![image](https://github.com/pizzaboxer/bloxstrap/assets/137489188/8032f092-ed4d-45bc-8893-9b04bef58af3)

**Comment by ChatTillYouDie** [comment]
After 5 hours of occasionally retrying, it suddenly found the log file it needed..
![image](https://github.com/pizzaboxer/bloxstrap/assets/137489188/6b9294ce-e5b6-420c-a7e9-ace8e6aa9c3d)
![image](https://github.com/pizzaboxer/bloxstrap/assets/137489188/9e3c0053-69ff-45cf-9e02-7a7efd853173)

**Comment by ChatTillYouDie** [comment]
Seems like this issue is still occurring, randomly. It sometimes launches, sometimes not.
Reinstalled both Bloxstrap and ROBLOX, it still does not detect the log file.

**Comment by ChatTillYouDie** [comment]
The log file exists, don't know why Bloxstrap can't find it.
![image](https://github.com/pizzaboxer/bloxstrap/assets/137489188/3b08285e-9e81-42d5-a7d1-56847557cab0)

**Comment by Goldam2** [comment]
I have the same issue but dont know how to fix it, can you tell me how?

**Comment by pizzaboxer** [comment]
You yourself mentioned that Roblox isn't opening. Are you sure that Roblox is even creating a log file in the first place?

> The log file exists, don't know why Bloxstrap can't find it. ![image](https://user-images.githubusercontent.com/137489188/248379414-3b08285e-9e81-42d5-a7d1-56847557cab0.png)

That Roblox log file was created at 07:23:27 PM UTC. That Bloxstrap log file was created at 07:24:27 PM UTC. That's one whole minute later. That's definitely not the log file that corresponds to the instance it just tried to launch.

**Comment by ChatTillYouDie** [comment]
The Roblox log file was created when it successfully launched the first time (after I reinstalled), when I went to restart Bloxstrap the second time, it just stops finding that previous Roblox log file.

**Comment by ChatTillYouDie** [comment]
Wow.. found the issue.
Seems like launching Bloxstrap.exe directly instead of launching it from Steam as a non-steam game made it work. Don't know why it suddenly happens now, it worked before.
