### ISSUE TITLE
Bloxstrap uninstalled, "used in another process."

### ISSUE THREAD

**Issue by Cathectical-dev** [pizzaboxer/bloxstrap#338]
So, due to the fact that Byfron blocks Bloxstrap at the moment, i wanted to uninstall it and get the regular ROBLOX version until its unblocked, now it comes up with the error: 

Unable to open file for writing: C:/ProgramData/Roblox/Downloads/.part - Another process is accessing this file. 

I already tried deleting the things etc, is there another thing that i have to do, since i have deleted bloxstrap the normal uninstall way.

**Comment by 1011025m** [comment]
Did you install Bloxstrap into a custom directory?

Open up task manager and kill any Bloxstrap processes, then you'll be able to continue.

**Comment by Cathectical-dev** [comment]
> Did you install Bloxstrap into a custom directory?
> 
> Open up task manager and kill any Bloxstrap processes, then you'll be able to continue.

Did those things and it wasnt in a custom directory.

**Comment by 1011025m** [comment]
Bloxstrap is installed into `%LOCALAPPDATA%\Bloxstrap` by default. If your Bloxstrap installation wasn't in a custom directory, then the folder you mentioned would be from an official Roblox installation. I doubt this is related to Bloxstrap at all if that's the case.

**Comment by Cathectical-dev** [comment]
Okay nvm fixed it, deleted the HKEY Registry Keys of Bloxstrap and now roblox is working again, ty anyway. :)

**Comment by pizzaboxer** [comment]
Are you sure that error was coming from Bloxstrap? Doesn't seem like it. Also, Byfron doesn't block Bloxstrap? Where does that statement come from?
