### ISSUE TITLE
Bloxstrap Sensapi.dll is missing

### ISSUE THREAD

**Issue by GV322** [pizzaboxer/bloxstrap#339]
even i put the sensapi.dll into the bloxstrap version something still doesnt work 
![image](https://github.com/pizzaboxer/bloxstrap/assets/137593409/171beffb-ba44-4218-8097-95b93be75f4d)
![image](https://github.com/pizzaboxer/bloxstrap/assets/137593409/21e719f5-18f9-4016-a251-8c8bfeb9eedc)

**Comment by pizzaboxer** [comment]
This is a problem with Roblox itself, not Bloxstrap.

**Comment by SeeFj** [comment]
I get the same problem everytime that roblox updates, the fix that worked for me was copy this dll file to the roblox version folder.
[sensapi.zip](https://github.com/pizzaboxer/bloxstrap/files/11857209/sensapi.zip)
![image](https://github.com/pizzaboxer/bloxstrap/assets/81432202/0dbee374-777d-41f5-952f-63492fa66a18)
