### ISSUE TITLE
return of OG roblox loading screen

### ISSUE THREAD

**Issue by Cyber2525** [pizzaboxer/bloxstrap#340]
I want an option to return the old game loading screen in the mods section (for version 2.4.0)
![23ca6a7df610e3070a8805e2b984641249b1b193](https://github.com/pizzaboxer/bloxstrap/assets/83342792/d9ae6d01-00c8-44d0-afe0-ff38e2d32509)

**Comment by lokzz** [comment]
omg yes

**Comment by stan2474** [comment]
this is impossible

**Comment by popbob2** [comment]
> this is impossible

it is kinda possible, you could change the loading screen's textures but that is all

**Comment by cootshk** [comment]
> not possible, sorry

github.com/roblox the old scripts are there

**Comment by EasternBloxxer** [comment]
> > not possible, sorry
> 
> github.com/roblox the old scripts are there

Bloxstrap does not modify the client nor its core-scripts
so that is not possible

**Comment by OrphanObliterator** [comment]
Yeah, this is possible; however, it is somewhat  _buggy_. It will erase your player list icons as well as the universal app if you use it. **If you don't mind, go ahead and utilize it.**

Go to modifications, then go to ExtraContent, models, go to the folder DataModelPatch, and then replace the RBXM file with this RBXM file: 

https://drive.google.com/file/d/1r9xXO_Qt56VzqhpILV6J0G6hkmW6fdFh/view

**Comment by OrphanObliterator** [comment]
https://github.com/pizzaboxer/bloxstrap/assets/108492285/3caab229-cf85-4882-8a5a-cdef3c6be92d

A video of me showcasing it

**Comment by lokzz** [comment]
the drive link is private

**Comment by OrphanObliterator** [comment]
fixed
