### ISSUE TITLE
Old menus dont work

### ISSUE THREAD

**Issue by cootshk** [pizzaboxer/bloxstrap#341]
Menu version: v1

What shows in game:
![What shows](https://github.com/pizzaboxer/bloxstrap/assets/83678457/6aa975ca-d21c-40bc-92d1-4a1e11b13d8e)
log:
[Bloxstrap_20230626T011555Z.log](https://github.com/pizzaboxer/bloxstrap/files/11861552/Bloxstrap_20230626T011555Z.log)

**Comment by pizzaboxer** [comment]
It means the in-game escape menu.
