### ISSUE TITLE
preferred emoji type dont work

### ISSUE THREAD

**Issue by xM4rkHUN** [pizzaboxer/bloxstrap#342]
so basically, when i switched the preferred emoji type to something else than the twemoji then it didnt start the roblox and just gave me a error code

**Comment by pizzaboxer** [comment]
you're using an unreleased version that's far from ready and you don't even provide any details about the error lol

**Comment by xM4rkHUN** [comment]
uh yeah, i forgot cuz it was late night to me, heres the error code
![image](https://github.com/pizzaboxer/bloxstrap/assets/108871771/a923f182-372c-429b-a307-53cca0866724)

**Comment by pizzaboxer** [comment]
you're not even showing what the path is

**Comment by NikoYTRBLX** [comment]
This error occurs when selecting anything other than the default (Twemoji) for some reason.

**Comment by NikoYTRBLX** [comment]
It fails before creating the directory for the fonts, now that I put the fonts folder in %localappdata%\Bloxstrap\Modifications\content it launches just fine (wrong order of code?)
