### ISSUE TITLE
Crash after RFTI round finish

### ISSUE THREAD

**Issue by WaviestBalloon** [pizzaboxer/bloxstrap#345]
This, is a very weird issue that I thought was a global issue, after contacting the developers, apparently nobody have reported about it.

After every round of a RFTI game, the client will freeze and crash, a friend tested this out for me who also uses Bloxstrap and the result in replicatable.
We both uninstalled Bloxstrap and the crashes no longer happen.

I suspect that it is due to the `DFIntTaskSchedulerTargetFps` FFlag, I will try to do more testing but it's like 1 AM lol!!

Game link: https://www.roblox.com/games/11195100561/RUNNING-FROM-THE-INTERNET
My private server if you want to replicate it without players in-game: https://www.roblox.com/games/11195100561?privateServerLinkCode=10345036430113298086389799019984

![image](https://github.com/pizzaboxer/bloxstrap/assets/31796727/38b17b4a-efcc-4ea5-ac08-ce7be530638a)

https://github.com/pizzaboxer/bloxstrap/assets/31796727/95653e5c-b78f-4e77-99b0-f509a7feca39

**Comment by NikoYTRBLX** [comment]
Did not manage to replicate this with an uncapped framerate of 2147483647.

**Comment by WaviestBalloon** [comment]
> Did not manage to replicate this with an uncapped framerate of 2147483647. [ClientAppSettings.txt](https://github.com/pizzaboxer/bloxstrap/files/11888415/ClientAppSettings.txt) ClientAppSettings for reference

Capped at 60 FPS, my client didn't crash after a match.
Retrying the "uncapped" FPS value

**Comment by WaviestBalloon** [comment]
My client is no longer crashing at all! For some really odd reason, reinstalling Bloxstrap has resolved this strange issue.
I'll close this but if @pizzaboxer wants to look deeper into this if they have a older version of Bloxstrap than be my guest.
