### ISSUE TITLE
The volume thing don't move

### ISSUE THREAD

**Issue by WayBackToHeaven** [pizzaboxer/bloxstrap#347]
Hi, when I move the volume thing, it don't move

https://github.com/pizzaboxer/bloxstrap/assets/138042536/8395d0eb-edfa-44a6-95e5-a0f4a403de4b

**Comment by pizzaboxer** [comment]
That's just a bug with the v2 menu. Nothing I can do about that, unfortunately.

**Comment by xM4rkHUN** [comment]
if you like that sidebar design, then use the v3, its the v2 but less bugs

**Comment by pizzaboxer** [comment]
v3 is broken right now - just use v1.
