### ISSUE TITLE
Bloxstrap for linux, or work on Q4Wine?

### ISSUE THREAD

**Issue by davi123211211** [pizzaboxer/bloxstrap#349]
You guys can try make this work on Linux or Q4Wine?

**Comment by 1011025m** [comment]
Ever since the release of Hyperion anticheat on Roblox it is no longer possible. This is a Roblox issue, and there is no way around it.

**Comment by pizzaboxer** [comment]
Roblox itself doesn't evven work on Linux.

**Comment by Sahelantrophus** [comment]
use windows u bum

**Comment by Henry-Hiles** [comment]
> Ever since the release of Hyperion anticheat on Roblox it is no longer possible. This is a Roblox issue, and there is no way around it.

It is now possible again

**Comment by davi123211211** [comment]
> > Ever since the release of Hyperion anticheat on Roblox it is no longer possible. This is a Roblox issue, and there is no way around it.
> 
> It is now possible again

How?

**Comment by Henry-Hiles** [comment]
> > > Ever since the release of Hyperion anticheat on Roblox it is no longer possible. This is a Roblox issue, and there is no way around it.
> > 
> > 
> > It is now possible again
> 
> How?

Roblox re-enabled support
