### ISSUE TITLE
Suggestion lists

### ISSUE THREAD

**Issue by BeyondThe5D** [pizzaboxer/bloxstrap#35]
Dunno where else to post this but I just have a couple suggestions that would be pretty cool to see in a update:

1. Custom client icon
Pretty sure most people have suggested this before and maybe there is a reason for it not to be added so I won't go on about it for to long but basically just allow an option to change the actual client logo

2. Custom launcher icon
Similar to custom client icon except with the launcher, the launcher uses the bloxstrap icon when loading a game in the taskbar, it would be pretty cool if we could change that, it would make it more seamless

3. Multi-clients mod
I can see this not being added but maybe add a mod that allows us to open multiple clients

4. Choose to use desktop mode
When closing a Roblox client it will usually prompt us are we sure and will send us to the desktop app, would be cool to have an **option** to toggle this, I haven't actually tested how it works on BloxStrap (I forgor 💀) but I'm pretty sure it automatically removes this pop-up so having an option for it to appear would be interesting if possible

5. Game specific mods
So certain mods will only load in certain games, could potentially be done by making a folder in the "Modifications" folder and giving it the name of a place ID

I hope you like my ideas :)

**Comment by pizzaboxer** [comment]
I've dismissed idea 1 before as I don't want to modify the game client executable, and idea 2 seems like a really niche thing. Also, I don't make this clear, but you can open the desktop app through the "Play Roblox" shortcut in the start menu. I guess I could add a launch option for it too. Ideas 3 and 5 do seem interesting, though not sure what use idea 5 would have to warrant adding.

If I ever feel like working on Bloxstrap again, I might add some of these. Thank you!

**Comment by BeyondThe5D** [comment]
I thought of idea 5 (Game specific mods) when playing [RetroStudio](https://www.roblox.com/games/5846386835/RetroStudio) and they are trying to simulate the old Roblox clients and a pretty annoying feature of Roblox is they are uncapable of removing the CoreGui (And even if they did it would violate the Roblox TOS) so I thought it would be cool to personally modify my Roblox files to remove the pause menu however having to keep reinstalling and uninstalling a mod when I wanna play a difference game would be annoying which is why I suggested it
Would love if you could add it :)
