### ISSUE TITLE
An error occurred while starting Roblox

### ISSUE THREAD

**Issue by 20xray** [pizzaboxer/bloxstrap#350]
![Снимок экрана (280)](https://github.com/pizzaboxer/bloxstrap/assets/138196176/112b02f0-0b04-46f2-ab49-f7e86330aa70)
Hello.
Yesterday everything was working fine, but today I got this. Does anyone know how to solve such a problem?

**Comment by pizzaboxer** [comment]
HTTPS error? Get the latest log file from `%localappdata%\Bloxstrap\logs` and send it here. I'll see if I can figure out what's going on.

**Comment by 20xray** [comment]
> HTTPS error? Get the latest log file from `%localappdata%\Bloxstrap\logs` and send it here. I'll see if I can figure out what's going on.
[Bloxstrap_20230630T070248Z.log](https://github.com/pizzaboxer/bloxstrap/files/11913888/Bloxstrap_20230630T070248Z.log)

**Comment by pizzaboxer** [comment]
Oh, this doesn't really clear things up that much. Hold on, I'll get back to you in a moment with something, if this is still happening.

**Comment by 20xray** [comment]
> Oh, this doesn't really clear things up that much. Hold on, I'll get back to you in a moment with something, if this is still happening.

Okay! I'll wait!

**Comment by pizzaboxer** [comment]
Just made a version which should help me get a better idea of what's going on. 

https://github.com/pizzaboxer/bloxstrap/suites/14006915878/artifacts/781710566

Download the zip and run Bloxstrap.exe. If the error happens again, send the latest log file here.

**Comment by musmus2531** [comment]
> Just made a version which should help me get a better idea of what's going on.
> 
> https://github.com/pizzaboxer/bloxstrap/suites/14006915878/artifacts/781710566
> 
> Download the zip and run Bloxstrap.exe. If the error happens again, send the latest log file here.

Hi! 
I got that problem too, still doesnt work 
![image](https://github.com/pizzaboxer/bloxstrap/assets/120372433/50c6306c-e0a6-460e-93c9-a0fd85fa534f)

**Comment by musmus2531** [comment]
I was trying to install it, but it dont work

**Comment by pizzaboxer** [comment]
This is a completely different problem, open an issue for it so I can help you there.

**Comment by 20xray** [comment]
> 

Hello. Now the same error occurs, but during installation. And now because of this I can't send the log file. :(

**Comment by 20xray** [comment]
> Just made a version which should help me get a better idea of what's going on.
> 
> https://github.com/pizzaboxer/bloxstrap/suites/14006915878/artifacts/781710566
> 
> Download the zip and run Bloxstrap.exe. If the error happens again, send the latest log file here.

Hello. Now the same error occurs, but during installation. And now because of this I can't send the log file. :(

**Comment by pizzaboxer** [comment]
> And now because of this I can't send the log file. :(

Why not?

**Comment by 20xray** [comment]
> > And now because of this I can't send the log file. :(
> 
> Why not?

![Screenshot](https://github.com/pizzaboxer/bloxstrap/assets/138196176/9619d982-75ab-46ef-a367-2b972cc855ba)
Because of this.

**Comment by pizzaboxer** [comment]
You know the exception dialog has a button to locate the log file for you, right?

**Comment by 20xray** [comment]
> You know the exception dialog has a button to locate the log file for you, right?

Oh? I didn't understand you, my English is bad.

**Comment by pizzaboxer** [comment]
Well, do you have it?

**Comment by pizzaboxer** [comment]
I'm going to close this issue since a few other people are having this same problem, and in order to figure out what's going on I need to be able to communicate with those people. Given how long winded these response times have been, I won't keep this open as I don't expect to be solving the problem here.

It should be fixed eventually, but this issue being open will not help.

**Comment by Jaklasd** [comment]
Hello, today i got a problem with my bloxstrap, i tried all like uninstall and then reinstall but dont fix
![image](https://github.com/pizzaboxer/bloxstrap/assets/149709302/8e091d31-4f15-46ef-a2fb-43ce2d841202)
