### ISSUE TITLE
Roblox players both bloxstrap and microsoft store versions fail to load all interfaces. 

### ISSUE THREAD

**Issue by TheChillDominic** [pizzaboxer/bloxstrap#351]
![image-3](https://github.com/pizzaboxer/bloxstrap/assets/83438655/cdb45f3e-02a7-4268-bf61-4e247c8ec37a)
So I'm not really sure who else to go to about this, about 2 weeks ago I started having this issue and it has not since been fixed. I have tried everything from doing a complete manual Uninstall of both bloxstrap and roblox itself, even went as far as to reinstalling my graphic drivers. The interface will load up but none of the assets will load in, games won't launch and everything from the Microsoft store version to the unaltered windows player is giving me this issue. After about 10-20 seconds the player will proceed to crash. Anyone have any idea how to fix this?

**Comment by pizzaboxer** [comment]
See this: https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by TheChillDominic** [comment]
Will try these out, thank you!

**Comment by TheChillDominic** [comment]
Yeah didn't work sadly, probably a roblox issue. Just gonna have to wait it out. Seems like the platform has been bugging ever since this hyperion update came out SMH.
