### ISSUE TITLE
CONCEPT: App Themes (legacy)

### ISSUE THREAD

**Issue by sha4owz** [pizzaboxer/bloxstrap#353]
this is just an idea but add themes to the app like a legacy theme which would maybe change the icons and color on the apps interface. Image below.

![dwndnf](https://github.com/pizzaboxer/bloxstrap/assets/138281770/15439741-88c0-4c28-919a-b8e0e24207dd)

------------------------------------------------------------------------------------------------------
EXTRA:
Some other ideas, Ill include concept pictures just in case:
-Optional profile picture and text saying "Hello, ____!" (photo below)
![image](https://github.com/pizzaboxer/bloxstrap/assets/138281770/c1557c81-2146-42b5-9453-59a364749f16)

- old avatar editor (photo below)
![image](https://github.com/pizzaboxer/bloxstrap/assets/138281770/25224a39-95b7-4a43-91a1-71ba65cbad32)
old avatar editor background place: https://www.roblox.com/games/10573352129/Roblox-Old-Avatar-Customization

-old avatar editor background 
![image](https://github.com/pizzaboxer/bloxstrap/assets/138281770/c7dbbd79-c0e9-45a2-9c2e-310bbbd364cd)

**Comment by pizzaboxer** [comment]
Not possible, sorry.

**Comment by pizzaboxer** [comment]
Modding only really goes so far, the only thing you can really do is change any content files that Roblox uses. I can't really do anything like adding text, or pictures, or colors. About that avatar editor screenshot background - what file did you replace for that?

**Comment by OrphanObliterator** [comment]
No, it isn't actually an old screenshot. You can edit it however you want.
ExtraContent --> Places --> Mobile

You just modify the mobile file.

**Comment by pizzaboxer** [comment]
Oh, Mobile.rbxl is used only to hold the avatar editor place. I thought it did more than just that given the app crashes completely without it. Anyway, that's a really cool idea, and it might be the only thing from this that I can really add.

**Comment by sha4owz** [comment]
> Oh, Mobile.rbxl is used only to hold the avatar editor place. I thought it did more than just that given the app crashes completely without it. Anyway, that's a really cool idea, and it might be the only thing from this that I can really add.

Yay, i did put a link where you can download the place incase u do decide to do it. Do you think icons on the home page would be possible? I have seen in the files "sheets" which have a bunch of icons on them

**Comment by pizzaboxer** [comment]
I could, but I guess I just don't really see why?

**Comment by sha4owz** [comment]
> I could, but I guess I just don't really see why?

idk 😭, why not lol

**Comment by pizzaboxer** [comment]
> idk 😭, why not lol

I mean, maybe, but it just doesn't really feel like much without those text labels beneath.

**Comment by sha4owz** [comment]
> > idk 😭, why not lol
> 
> I mean, maybe, but it just doesn't really feel like much without those text labels beneath.

Like in the orignal?
