### ISSUE TITLE
An error occurred while starting Roblox

### ISSUE THREAD

**Issue by musmus2531** [pizzaboxer/bloxstrap#357]
![image](https://github.com/pizzaboxer/bloxstrap/assets/120372433/62a9b4f5-9921-4330-b2a5-8ec660bb96bb)
Hi! 
I got this problem when i tried to install bloxstrap

**Comment by pizzaboxer** [comment]
Can you please get the latest log file? It should be located in your Temp folder at %localappdata%\Temp - just sort by date modified.

**Comment by musmus2531** [comment]
[RBX-A64B007B.log](https://github.com/pizzaboxer/bloxstrap/files/11931098/RBX-A64B007B.log)
this?

**Comment by pizzaboxer** [comment]
The filename should begin with "Bloxstrap_".

**Comment by Dogethebestdoggo** [comment]
hi there i got a issue as well so like i been using this bloxtrap thingy and now in anny game i go on roblox after i join and play for few seconds it freezes then goes back to normal anny help??...

**Comment by musmus2531** [comment]
> The filename should begin with "Bloxstrap_".

There is no file with beginning Bloxstrap

**Comment by musmus2531** [comment]
only rbx

**Comment by pizzaboxer** [comment]
Does a folder exist at %localappdata%\Bloxstrap?

**Comment by musmus2531** [comment]
> Does a folder exist at %localappdata%\Bloxstrap?

No

**Comment by pizzaboxer** [comment]
Looks like you'll have to try out a beta version which should help me get a better idea of what's going wrong.

https://github.com/pizzaboxer/bloxstrap/suites/14007826702/artifacts/781770401

Download the zip, open it, then run Bloxstrap.exe, installing it as normal. When the error dialog appears, obtain the log as instructed and send it here.

**Comment by musmus2531** [comment]
there is no log, even at temp

**Comment by pizzaboxer** [comment]
Show the exception prompt that appears.

**Comment by musmus2531** [comment]
> Show the exception prompt that appears.

Wait a sec

**Comment by pizzaboxer** [comment]
It has been much longer than a second.

**Comment by Sahelantrophus** [comment]
BRO HURRY UP

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
