### ISSUE TITLE
roblox opens but the screen turns white them black, and them a crash

### ISSUE THREAD

**Issue by herber4cr43** [pizzaboxer/bloxstrap#358]
i tried using the browser and i got http error also tried the 3 diferent renderers and nothing, also tried normal roblox without bloxstrap and still the same, reinstaled and did various fixes but still

**Comment by pizzaboxer** [comment]
> also tried normal roblox without bloxstrap and still the same

It's a problem with Roblox, there's not really anything I can do about this. Sorry.

**Comment by herber4cr43** [comment]
damm, well thanks
