### ISSUE TITLE
What is the difference between roblox ZCanary and ZCanaryApps channels? (unrelated)

### ISSUE THREAD

**Issue by user1126s** [pizzaboxer/bloxstrap#359]
i know you have lots of knowledge so can you tell the diffrence between these, also what are the other channels which are not in the dropdown menu. i cant find anywhere

**Comment by pizzaboxer** [comment]
Different builds of the Roblox game client. Some are undergoing testing, some are just alternate configurations, etc. I won't provide anything else given it's best to not mess around with it if you don't really know what it's about.
