### ISSUE TITLE
Roblox Studio Support

### ISSUE THREAD

**Issue by so1ehee** [pizzaboxer/bloxstrap#36]
This is just some suggestion since roblox studio is also part of roblox so y not

Same thing but with built-in 
-Roblox studio mod manager
-Fps Unlocker
-RPC (show how long we have been in studio)
-etc

**Comment by pizzaboxer** [comment]
I think it would be a better idea to propose having Discord Rich Presence be part of RSMM directly, and not have Bloxstrap be a launcher for a launcher.
