### ISSUE TITLE
unexpected error occured

### ISSUE THREAD

**Issue by LuckyMan09668** [pizzaboxer/bloxstrap#363]
I was starting Roblox with Bloxstrap but then i got the "an unexpected error occurred and roblox needs to quit" message but when i use the normal Roblox launcher it works fine... 

![error](https://github.com/pizzaboxer/bloxstrap/assets/84479490/bb25cbef-c733-4f36-baca-8e9841e3b50d)

**Comment by pizzaboxer** [comment]
Are you joining a game directly or are you trying to open the desktop app?

**Comment by pizzaboxer** [comment]
Are you joining a game directly or are you trying to open the desktop app?

**Comment by LuckyMan09668** [comment]
I was trying to open the desktop app

**Comment by pizzaboxer** [comment]
What about directly joining a game?

**Comment by LuckyMan09668** [comment]
Like by a link or

**Comment by pizzaboxer** [comment]
Like, by clicking the play button on a game's webpage.

**Comment by LuckyMan09668** [comment]
Oh right…that didn’t work as well…

**Comment by pizzaboxer** [comment]
Have you configured any FastFlags or mods?

**Comment by LuckyMan09668** [comment]
Yes , I think I changed it to the “into the future” I believe its called ?

**Comment by pizzaboxer** [comment]
Is that the only one? Let me take a look at the full list, you can view it by opening ClientAppSettings.json. Just copy and paste the whole thing here.

**Comment by JUBEB003** [comment]
that also happens to me, its not fixable

**Comment by pizzaboxer** [comment]
> i use the normal Roblox launcher it works fine...

Thinking about it a bit more, chances are it's down to files not being installed properly. If you're still there and you're still having this problem, let me know, and I can find out what's going on.

**Comment by JUBEB003** [comment]
> > i use the normal Roblox launcher it works fine...
> 
> Thinking about it a bit more, chances are it's down to files not being installed properly. If you're still there and you're still having this problem, let me know, and I can find out what's going on.

still having the problem

**Comment by pizzaboxer** [comment]
> still having the problem

Are you having it where Bloxstrap doesn't work but Roblox's launcher does?

**Comment by JUBEB003** [comment]
> > still having the problem
> 
> Are you having it where Bloxstrap doesn't work but Roblox's launcher does?

no, bloxstrap isnt the problem, roblox is

**Comment by JUBEB003** [comment]
it says that it found an unrecoverable error or just crashes when launching

**Comment by pizzaboxer** [comment]
> no, bloxstrap isnt the problem, roblox is

So then this issue doesn't apply to you. See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

**Comment by JUBEB003** [comment]
> > no, bloxstrap isnt the problem, roblox is
> 
> So then this issue doesn't apply to you. See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

already tried everything

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
