### ISSUE TITLE
Unable to type in chat (temp fix found)

### ISSUE THREAD

**Issue by pingusurmars** [pizzaboxer/bloxstrap#366]
The Bug : unable to type anything in the chat. works inside of the normal roblox player but the issue is only visible on bloxstrap.

Temp fix : change install channels from live to anything else and go back in live (which fixes it until the next roblox update)

How it came : it came randomly i don't really know

**Comment by EasternBloxxer** [comment]
What

**Comment by pingusurmars** [comment]
sorry for long response
basically when i click in the chatbox i just cant type. even if i press ! it still doesnt let me

**Comment by pizzaboxer** [comment]
Anything else? What about changing to ZFlag? That should be the exact same as LIVE, so I'm wondering if this is really something to do with channels. Also, what's the option for automatic channel changing currently set to?

**Comment by pingusurmars** [comment]
Auto Channel change is set to Always ask ans I also don't think it's about channels. (Maybe an issue on Roblox's side)

**Comment by pizzaboxer** [comment]
Is it the chatbox only? What about typing inside any other GUI textbox? Try [this game](https://www.roblox.com/games/13307536247/bloxstrap-message-testing), it has a textbox at the bottom of the screen.

**Comment by EasternBloxxer** [comment]
Could maybe have something to do with #395?

**Comment by pizzaboxer** [comment]
Could be, that's why I'm checking if it affects other textboxes first.

**Comment by pingusurmars** [comment]
I only saw it in the chat box, rest worked fine

**Comment by pizzaboxer** [comment]
Chatbox could be erroring out somehow? Let me take a look at Roblox's latest log file, you can find them at %localappdata%\Roblox\logs.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
