### ISSUE TITLE
Bloxstrap crashing when changing settings

### ISSUE THREAD

**Issue by DanGamingBlue** [pizzaboxer/bloxstrap#37]
Bloxstrap is crashing when i trying to change settings, (like enabling old cursor or change instalation folder)

https://user-images.githubusercontent.com/75522691/199046118-5e048fd2-a774-48d6-889b-82002bd544a4.mp4

I tried everything, (like download both x86 and x64, reinstall) and nothing helped.

Anyone can help?

**Comment by pizzaboxer** [comment]
Thanks for reporting! Try out [this build](https://pizzaboxer.xyz/temp/Bloxstrap-v1.5.1-x64.exe), and let me know if it still crashes (ignore if it asks you to update).

**Comment by DanGamingBlue** [comment]
Thank you so much! It works!
