### ISSUE TITLE
Cannot change FastFlags

### ISSUE THREAD

**Issue by kirowaii** [pizzaboxer/bloxstrap#370]
![image](https://github.com/pizzaboxer/bloxstrap/assets/138977635/fb8438a5-e22f-4e25-9db5-00b906e7d268)

An error was encountered while starting roblox  Details: SystemComponentModel.Win32Exception

I cannot seem to edit FastFlags in any way, if i select presets it  just does back to default and doesn't apply

**Comment by pizzaboxer** [comment]
> An error was encountered while starting roblox Details: SystemComponentModel.Win32Exception

Oh, I thought Windows would prompt for an application to open if no default exists? I'll add a special check for that.

> I cannot seem to edit FastFlags in any way, if i select presets it just does back to default and doesn't apply

Make sure you're following proper JSON format. Every item except the last should end with a comma.

**Comment by kirowaii** [comment]
I fixed the fast flags presets error thing bc i was stupid and had true fullscreen enabled, but the  first error still happens and I cannot edit it in any way it just closes and crashes bloxstrap

**Comment by pizzaboxer** [comment]
> I fixed the fast flags presets error thing bc i was stupid and had true fullscreen enabled, 

Oh, you weren't manually editing the file, nevermind.
