### ISSUE TITLE
can't uninstall bloxstrap

### ISSUE THREAD

**Issue by JaxOrSmthng** [pizzaboxer/bloxstrap#371]
pretty much the title, i have done the same thing as in wiki. it just opens up the bloxstrap

**Comment by pizzaboxer** [comment]
What does it do when you try to uninstall it?

**Comment by JaxOrSmthng** [comment]
it opens up bloxstrap

**Comment by pizzaboxer** [comment]
Which part? The menu or the launcher?

**Comment by pizzaboxer** [comment]
The button in the bottom right, what does it say? "Install" or "Save"?

**Comment by JaxOrSmthng** [comment]
It's basically the same menu that opens when you normally open the bloxstrap menu, settings and everything. It says save most likely but I don't have my pc rn

**Comment by pizzaboxer** [comment]
> It's basically the same menu that opens when you normally open the bloxstrap menu, settings and everything. 

I know that. The menu appears before installation too. If the button shows "Install" then it likely did not uninstall properly.

**Comment by ZeldasMxZ** [comment]
I'm having the same problem with the menu. It just sends me to the menu that pops up when you install bloxstrap. I deleted every file and it still does the same thing.

**Comment by pizzaboxer** [comment]
> I'm having the same problem with the menu. It just sends me to the menu that pops up when you install bloxstrap. I deleted every file and it still does the same thing.

Sounds like it didn't uninstall properly. To fix that, you'd also need to delete the registry key for `HKEY_CURRENT_USER\Software\Bloxstrap`

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
