### ISSUE TITLE
Error 403 on alt account

### ISSUE THREAD

**Issue by ItsJustBlaze** [pizzaboxer/bloxstrap#372]
I'm trying to play some random ACS games, but when I press play it just gives me error 403. I've never had this problem before, so i'm pretty sure it's because i'm on an alt, but idrk.

![Screenshot (539)](https://github.com/pizzaboxer/bloxstrap/assets/139030582/41a6b00d-2c4d-43fc-9dfd-652999efccd5)

**Comment by EasternBloxxer** [comment]
Open the Roblox app by Search play roblox and log out of it if logged in

**Comment by ItsJustBlaze** [comment]
respectfully bro I have no idea what that comment means, I'm trying to play on the ALT, because my main got false banned for a couple days. I'm not trying to log out of the account.
