### ISSUE TITLE
[Suggestion] A debug console that shows live logs from the latest roblox log file

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#375]
Would be useful for things.
Maybe one for bloxstrap logs too

**Comment by pizzaboxer** [comment]
Yeah, why not.

**Comment by pizzaboxer** [comment]
Abandoned (for now) because of https://github.com/pizzaboxer/bloxstrap/issues/186#issuecomment-1636834575.

**Comment by pizzaboxer** [comment]
lol
