### ISSUE TITLE
process cannot access the file

### ISSUE THREAD

**Issue by LaggyGlitch0779** [pizzaboxer/bloxstrap#376]
![image](https://github.com/pizzaboxer/bloxstrap/assets/74420805/18a96821-f372-40b0-bd80-c9fa4c7f26e1)
The logs are not open on my computer and I have already rebooted my pc twice

**Comment by pizzaboxer** [comment]
Are you using RoGold?

**Comment by LaggyGlitch0779** [comment]
that must be why

yes i am using rogold

**Comment by pizzaboxer** [comment]
The error happens because it tries launching two instances at the same time. You're seeing the error come from the second one. It doesn't affect anything, so you can just ignore it for now. I've made it so this doesn't show up in the next version. #212
