### ISSUE TITLE
SensApii.dll 

### ISSUE THREAD

**Issue by DefoNotFlee** [pizzaboxer/bloxstrap#379]
After I try to join a game, there’s a pop up saying Sensapii failed to load. 

Any help?

**Comment by Twobigfoot1116** [comment]
I uninstalled and installed again and it worked but I'm 100%, may be that the error comes back

**Comment by DefoNotFlee** [comment]
Yes, uninstalling does have a temporary fix, but you constantly have to uninstall it and install it.

**Comment by pizzaboxer** [comment]
Not a Bloxstrap problem, sorry.
