### ISSUE TITLE
Add an updater to the bloxstrap launcher

### ISSUE THREAD

**Issue by unexp** [pizzaboxer/bloxstrap#38]
Instead of directing users to the newest release's page, it could just upgrade the bloxstrap version

**Comment by unexp** [comment]
add enhancement tag to this pls

**Comment by pizzaboxer** [comment]
I considered this when creating the v1.5.0 update, but ultimately decided not to as if Windows Defender falsely identified the downloaded update as malware, then it would mess up the update process entirely. I might try to add it again as it probably isn't that much of an issue, but I'll only add it if I need to do another major update.

**Comment by sitiom** [comment]
You can use something like https://github.com/Romanitho/Winget-AutoUpdate when #47 is resolved.
