### ISSUE TITLE
Bloxstrap not working at all for me

### ISSUE THREAD

**Issue by K1rbbyyy** [pizzaboxer/bloxstrap#380]
This morning when I started playing Roblox I noticed something was off, My shaders wernt working, along with the mods I had with it,I tryed resetting, and restarting the app but nothing was working, and I have never had an issue with bloxstrap, ever So I'm wondering is it like this for others?

**Comment by GoingCrazyDude** [comment]
no external dlls work with roblox due to byfron

**Comment by pizzaboxer** [comment]
> My shaders wernt working, along with the mods I had with it

Does Bloxstrap even show when launching Roblox?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
