### ISSUE TITLE
bringing back the old roblox loading screens

### ISSUE THREAD

**Issue by AlphaGr33n** [pizzaboxer/bloxstrap#381]
options should be from 2014-2017 (or lower) to 2018

also by loading screens i mean stuff like this for example
![maxresdefault](https://github.com/pizzaboxer/bloxstrap/assets/71393743/9d5a4a6a-b328-4c9b-9347-2186d3232765)

**Comment by EasternBloxxer** [comment]
Not possible. Sorry.
