### ISSUE TITLE
Bloxstrap Adminstrator Mode Bug?

### ISSUE THREAD

**Issue by Plasmapea987** [pizzaboxer/bloxstrap#382]
I'm trying to disable bloxstrap from running in admin mode so I can use my auto clicker but any attempts to remove the permissions break the program is there a workaround for this?

**Comment by pizzaboxer** [comment]
It doesn't run in administrator mode though?

**Comment by Plasmapea987** [comment]
Evrey time I reinstalled it automatically goes into administrator mode ill see if I can find a fix.

**Comment by pizzaboxer** [comment]
How do you know it runs in administrator mode?

**Comment by Plasmapea987** [comment]
It asks me to give it permission to run it in administrator mode every time I launch Roblox

**Comment by Plasmapea987** [comment]
Configured exactly like in that photo why?

**Comment by pizzaboxer** [comment]
Did you first install Bloxstrap as an Administrator? Assuming you've kept the default installation location, open the properties of Bloxstrap.exe at %localappdata%\Bloxstrap, go to the Compatibility tab, and see if it's set to run as administrator.

**Comment by Plasmapea987** [comment]
![Screenshot 2023-07-13 105207](https://github.com/pizzaboxer/bloxstrap/assets/62024706/1e750a8b-1f25-4db9-b5f1-cd02f932f1cf)

This is the error I get when Launching Roblox with that setting on
![Screenshot 2023-07-13 104906](https://github.com/pizzaboxer/bloxstrap/assets/62024706/e68123c2-4ba7-4968-89e1-d44ae7d479bf)

**Comment by pizzaboxer** [comment]
Oh, Roblox itself has been marked to run as Administrator. Check that.

**Comment by Plasmapea987** [comment]
Yeah I just fixed it LOL i didn't notice what the directory was thanks for the help pizzaboxer :)
