### ISSUE TITLE
so there was a guy with the v1.5 of the roblox menu like v3 and v2 but not on the side basicaly v1 but better

### ISSUE THREAD

**Issue by ruby-the-maxwell-lover** [pizzaboxer/bloxstrap#383]
can you guys add this
its a issuee cuz like everyone has it but it might be annoying for people without it
if it is added please tell me how to get it

**Comment by OrphanObliterator** [comment]
are you talking about v4

**Comment by totallyphysicallypossible** [comment]
definitely talking about v4

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Toggling-the-new-escape-menu
