### ISSUE TITLE
Occured while starting roblox

### ISSUE THREAD

**Issue by agus967** [pizzaboxer/bloxstrap#386]
![Screenshot (36)](https://github.com/pizzaboxer/bloxstrap/assets/139638743/d4907be2-369a-4000-be43-1974a815e078)

**Comment by pizzaboxer** [comment]
Seems like an SSL error. Just so I can get a better idea of what's going on, try and install a beta version. [Download this zip](https://github.com/pizzaboxer/bloxstrap/suites/14322842414/artifacts/805927434), and just run Bloxstrap.exe.

**Comment by agus967** [comment]
Alright Thanks for helping me

Pada tanggal Sab, 15 Jul 2023 pukul 23.25 pizzaboxer <
***@***.***> menulis:

**Comment by pizzaboxer** [comment]
Did that just fix it?

**Comment by agus967** [comment]
Yes, it worked!

Pada tanggal Jum, 21 Jul 2023 pukul 02.54 pizzaboxer <
***@***.***> menulis:

**Comment by pizzaboxer** [comment]
Oh, it wasn't supposed to do that. Okay then. Anyway, some things probably just changed since you first reported the problem.
