### ISSUE TITLE
How do I redo the installation?

### ISSUE THREAD

**Issue by TrevorBMemes** [pizzaboxer/bloxstrap#39]
I installed on the version that had a broken installation menu, and now I'm unable to bring it up to change the settings even after I updated.
I tried deleting all files relating to Bloxstrap and reinstalling Roblox, but it still doesn't bring the menu up.
If there is currently no way to preview, what are all the update channels? I want to see the hidden ones I couldn't view due to the broken menu buttons.

**Comment by carter0nline** [comment]
yea v1.5.1 nuked my Configure Bloxstrap thing as well, pls fix

**Comment by pizzaboxer** [comment]
What specifically isn't working? Is the dialog still crashing or are you just not able to select certain options?

**Comment by carter0nline** [comment]
> 

For me, the Configure Bloxstrap button is just nowhere to be found

**Comment by pizzaboxer** [comment]
Does the Bloxstrap folder just not show in the start menu at all?

**Comment by TrevorBMemes** [comment]
The install dialog doesn't appear and the folder shortcut isn't created, but it works fine otherwise.

**Comment by pizzaboxer** [comment]
That's really weird, it should attempt to create the start menu folder every time it launches Roblox.
By install dialog, do you mean the preferences menu or the dialog that asks you to update your installed version?

**Comment by TrevorBMemes** [comment]
the preferences menu that crashed the previous version.

**Comment by TrevorBMemes** [comment]
nvm i was being an idiot and forgot to use control panel
