### ISSUE TITLE
Overlay Isnt Appearing :/

### ISSUE THREAD

**Issue by GAYFUCK222222** [pizzaboxer/bloxstrap#392]
even my laptops built in overlay isnt showing up i never had these issues before

**Comment by EasternBloxxer** [comment]
what overlay

**Comment by OrphanObliterator** [comment]
i think they mean discord overlay which doesnt work because of hyperion

**Comment by pizzaboxer** [comment]
What overlay?

**Comment by Guestywow1** [comment]
I believe he is talking about the UI of bloxstrap, I'm having the same issue too
![image](https://github.com/pizzaboxer/bloxstrap/assets/128289442/b362fd3b-4b5d-40ab-b631-5fb1c441ab9c)

**Comment by pizzaboxer** [comment]
> I believe he is talking about the UI of bloxstrap, I'm having the same issue too (you can see in the image that there is just a black line) ![image](https://user-images.githubusercontent.com/128289442/254876074-b362fd3b-4b5d-40ab-b631-5fb1c441ab9c.png)

Open a separate issue for this. Also, they mentioned "even my laptops built in overlay isnt showing up".

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
