### ISSUE TITLE
Everytime I try opening it says this

### ISSUE THREAD

**Issue by NightyyPlayer800** [pizzaboxer/bloxstrap#393]
![image](https://github.com/pizzaboxer/bloxstrap/assets/139729389/1334576f-f9fc-4145-8743-a7af04f83fe7)

**Comment by pizzaboxer** [comment]
You have an N edition of Windows installed. See this article: https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a
