### ISSUE TITLE
v2.4.0 always downloads the v2.3.0 version

### ISSUE THREAD

**Issue by loltomi** [pizzaboxer/bloxstrap#394]
everytime i start roblox it always gets the latest bloxstrap version and downloads the v2.3.0

**Comment by pizzaboxer** [comment]
Can't replicate. Where'd you download 2.4.0 from?

**Comment by shawnjb** [comment]
I don't see 2.4.0 on the releases.

**Comment by NightPlay** [comment]
yeah downloads 2.3.0 because 2.4.0 isnt released yet

**Comment by shawnjb** [comment]
> yeah downloads 2.3.0 because 2.4.0 isnt released yet

Are you having issues with your installation of Roblox?

**Comment by xM4rkHUN** [comment]
> Can't replicate. Where'd you download 2.4.0 from?

he means he downloaded the v2.4.0 from the actions and when he opened it then the bloxstrap updates and downloads back the v2.3.0, even if he deleted the 2.3.0 version

**Comment by NightPlay** [comment]
is 2.4.0 even available now? because i dont think it is

**Comment by xM4rkHUN** [comment]
> is 2.4.0 even available now? because i dont think it is

its not, but you can download it

**Comment by pizzaboxer** [comment]
Oh, just figured out what the problem was. Try the latest build, see if it still happens there.

**Comment by xM4rkHUN** [comment]
> Oh, just figured out what the problem was. Try the latest build, see if it still happens there.

yeah, it fixed
