### ISSUE TITLE
Roblox icon and healthbar are missing ONLY when Bloxstrap is running

### ISSUE THREAD

**Issue by Guestpwl** [pizzaboxer/bloxstrap#395]
![RobloxScreenShot20230717_191546774](https://github.com/pizzaboxer/bloxstrap/assets/139764695/13247b25-2a49-40c6-a042-4b0021ceffca)
![RobloxScreenShot20230717_191853889](https://github.com/pizzaboxer/bloxstrap/assets/139764695/269b8e83-5947-4c87-adca-c7895dd53f4f)
Whenever I run Bloxstrap, the roblox home icon and in-game health bar **disappears** (as shown in the images with the one on the top being a reinstalled version of the Roblox player, and the image on the bottom being the player **WITH** bloxstrap installed), the only modifications I did was set my FPS to 9999, enable the old Roblox death sound, turn on the pre-2016 cursor and changing the in-game menu version from V1 to V3 and back. Other than that, no other FFlag modifications were made. ClientSettings were modified with the help of EasternBloxxer to remove the removed V3 line of code 
![aaaaaa](https://github.com/pizzaboxer/bloxstrap/assets/139764695/fb475224-c4fc-48b2-9c14-b43cc1b15042)
This is not just a single issue **btw,** this has been a reoccurring issue since around the 5th of July and only happens when I have bloxstrap installed.
Also no other modifications have been installed with it.

**Comment by Guestpwl** [comment]
Hi, sorry for the delay. There are two versions, do I send both or send just one?

**Comment by pizzaboxer** [comment]
Whichever one is last modified.

**Comment by Guestpwl** [comment]
[TopBar.zip](https://github.com/pizzaboxer/bloxstrap/files/12069891/TopBar.zip)

**Comment by pizzaboxer** [comment]
Okay, those are definitely corrupted.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/a0b0cb75-1dec-405e-8c33-f0ff015e17e9)

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/f170f289-2dbe-4008-bf76-53a3f62f9d5b)

I'll try and find out what's happening, see what I can do to fix it. Thanks for reporting.

**Comment by pizzaboxer** [comment]
That being said, try and force a reinstsallation by changing your preferred channel in the menu's Installation tab to `ZFlag`, and then launching Roblox.

**Comment by Guestpwl** [comment]
Okay, thanks. I'll give it a try.

**Comment by Guestpwl** [comment]
Hello, doing this appears to have fixed the bug. Thank you for your help!
