### ISSUE TITLE
[REQ] I need you guys to help me find a way to display Ping on screen similar to the code "FFlagDebugDisplayFPS"

### ISSUE THREAD

**Issue by Duy845** [pizzaboxer/bloxstrap#3954]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I tried all the codes that Chat GPT but it doesn't show even though it is valid and successfully entered FAST FLAG :(

**Comment by PikachuWolverine** [comment]
There probably doesn’t exist a flag that does that. Just press shift + f3 to show network?
