### ISSUE TITLE
microsoft roblox

### ISSUE THREAD

**Issue by JUBEB003** [pizzaboxer/bloxstrap#398]
ok so i tried to install bloxstrap on the microsoft roblox and i couldnt for some reason, is it possible or not? if its possible i need to know asap

**Comment by EasternBloxxer** [comment]
???

**Comment by EasternBloxxer** [comment]
Bloxstrap does not support UWP Roblox.

**Comment by JUBEB003** [comment]
> Bloxstrap does not support UWP Roblox.

i got this weird error that doesnt let me play roblox

**Comment by JUBEB003** [comment]
so i have to use the microsoft roblox

**Comment by EasternBloxxer** [comment]
> > Bloxstrap does not support UWP Roblox.
> 
> i got this weird error that doesnt let me play roblox

Peep [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)

**Comment by JUBEB003** [comment]
> > > Bloxstrap does not support UWP Roblox.
> > 
> > 
> > i got this weird error that doesnt let me play roblox
> 
> Peep [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)

i tried everything but it doesnt work

**Comment by EasternBloxxer** [comment]
> > > > Bloxstrap does not support UWP Roblox.
> > > 
> > > 
> > > i got this weird error that doesnt let me play roblox
> > 
> > 
> > Peep [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)
> 
> i tried everything but it doesnt work

What is the error you are getting

**Comment by JUBEB003** [comment]
> > > > > Bloxstrap does not support UWP Roblox.
> > > > 
> > > > 
> > > > i got this weird error that doesnt let me play roblox
> > > 
> > > 
> > > Peep [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)
> > 
> > 
> > i tried everything but it doesnt work
> 
> What is the error you are getting

it crashes when i try to open it whether its the website version or the desktop version

**Comment by EasternBloxxer** [comment]
> > > > > > Bloxstrap does not support UWP Roblox.
> > > > > 
> > > > > 
> > > > > i got this weird error that doesnt let me play roblox
> > > > 
> > > > 
> > > > Peep [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)
> > > 
> > > 
> > > i tried everything but it doesnt work
> > 
> > 
> > What is the error you are getting
> 
> it crashes when i try to open it whether its the website version or the desktop version

You could make a bug report on devforum if you have the member role or try to get the member role and do that

**Comment by pizzaboxer** [comment]
Check if it's a Bloxstrap problem first by switching back to Roblox's bootstrapper for a moment. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by JUBEB003** [comment]
> > it crashes when i try to open it whether its the website version or the desktop version
> 
> Check if it's a Bloxstrap problem first by switching back to Roblox's bootstrapper for a moment. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

its not a bloxstrap problem

**Comment by pizzaboxer** [comment]
Oh, okay. Anyway, Bloxstrap doesn't support the Microsoft Store version of Roblox. It's completely separate. Sorry.
