### ISSUE TITLE
Alternate way of accessing the settings

### ISSUE THREAD

**Issue by PlayerValley** [pizzaboxer/bloxstrap#4]
Currently the only way of accessing the settings is in the readme: **open up Apps and Features, look for Bloxstrap and select Modify.** The problem is that some users (such as myself) can't locate "Bloxstrap" in "Apps and Features". And no, the "Apps" section in the modern Settings app can't locate it either.

Normally, Bloxstrap should be somewhere in the list, but it isn't.
![explorer_MAKjD9OGcl](https://user-images.githubusercontent.com/58902624/185055961-3d2c6091-d93b-4636-be80-1b856e590c4b.png)
![ApplicationFrameHost_ESSdvsfmSw](https://user-images.githubusercontent.com/58902624/185055901-16f7a53a-1cb7-43e6-b619-7d7df45eb2c3.png)

Perhaps a command-line parameter such as **--settings** could be done?

**Comment by pizzaboxer** [comment]
That's weird... it should be there if you have it installed.
Anyway, as of v1.1.0, Bloxstrap adds an entry to your Start Menu, so maybe you haven't updated yet?
![explorer_NsHAiz6g6L](https://user-images.githubusercontent.com/41478239/185068921-e339b72a-4abd-49cd-8996-c19c4bfe02d2.png)

**Comment by PlayerValley** [comment]
I did and it was there, seems like Windows Defender is auto-deleting the file :p

**Comment by PlayerValley** [comment]
update: did a reinstall of Bloxstrap, excluded %localappdata%\Bloxstrap from Defender, and it works like normal now.
