### ISSUE TITLE
launching bloxstrap as of november 9th launches the roblox desktop app

### ISSUE THREAD

**Issue by unexp** [pizzaboxer/bloxstrap#40]
apparently something happened and the roblox client won't launch with the browser anymore

**Comment by carter0nline** [comment]
Experiencing same problem

**Comment by bloxstrapusr** [comment]
i am also experiencing this problem

**Comment by TrevorBMemes** [comment]
also experiencing this problem.

**Comment by RobloxDevs** [comment]
Looks like roblox just deleted `--app` argument and always launch as InApp mode...
I don't think I can patch this new version because now it's not problem of arguments but entire RobloxPlayerBeta.exe (not RobloxLauncherBeta.exe) program

**Comment by TrevorBMemes** [comment]
roblox moment

:(

**Comment by SWG64** [comment]
i have this issue aswell

un roblox momento T_T

**Comment by pizzaboxer** [comment]
Just checked, and looks like Roblox just completely removed support for appless launching with the --play arg. Disappointing, I guess I should've seen it coming.
I'll release v1.5.2 shortly to fix this, but this will mean that Bloxstrap is forced to launch Roblox in the desktop app mode now.
Sorry to you guys in other timezones for not getting a fix out earlier.

**Comment by pizzaboxer** [comment]
Should be fixed now, sorry again!

**Comment by 1011025m** [comment]
Hey, thanks for tagging me in this issue. You can rename or remove the `Mobile.rbxl` file in the `./ExtraContent/places` folder to temporarily prevent Roblox from launching into the in-app homepage. Note that if you do not launch the player client with the --app flag it will either just launch into the homepage immediately or nothing will happen if you renamed/removed the place file.

Here's [my implementation](https://github.com/1011025m/RobloxHomePatcher/commit/fcacd4960d2f6ae3e2351e8cd87865233486b6a5).

**Comment by DaEnder** [comment]
the app isnt even that bad smh... why not launch the app....

**Comment by 1011025m** [comment]
> the app isnt even that bad smh... why not launch the app....

Adding features that interfere with an old one which has always worked will almost always cause some community backlash, it's unavoidable. Wouldn't blame people for not liking it :)

**Comment by pizzaboxer** [comment]
> Hey, thanks for tagging me in this issue. You can rename or remove the `Mobile.rbxl` file in the `./ExtraContent/places` folder to temporarily prevent Roblox from launching into the in-app homepage. Note that if you do not launch the player client with the --app flag it will either just launch into the homepage immediately or nothing will happen if you renamed/removed the place file.
> 
> Here's [my implementation](https://github.com/1011025m/RobloxHomePatcher/commit/fcacd4960d2f6ae3e2351e8cd87865233486b6a5).

Oh, nice job on finding out the current cause! I had a feeling it wasn't that drastic of an internal change...

At this point, I think it's better to just embrace the desktop app anyway, since I don't doubt they're eventually going to get rid of standalone browser launching altogether.

The only somewhat legitimate concern I've seen against the use of the desktop app is degraded performance (i guess due to the use of multiple datamodels?), but I haven't seen much substance of that, and Roblox has been doing it on their mobile app for years by this point, so it's likely negligible.

Embracing the desktop app is a bit annoying on my part since it makes implementing Discord Rich Presence reliably a bit harder, but I'll find a way :D

**Comment by 1011025m** [comment]
> Embracing the desktop app is a bit annoying on my part since it makes implementing Discord Rich Presence reliably a bit harder, but I'll find a way :D

Try pulling ROBLOSECURITY from windows credentials (not sure if that exists for player client, appears to be studio only?), use it to query the user presence endpoint from Roblox every so often. Not sure if this is possible though, never worked with it. It's also a very extreme solution, so maybe other ones are better.

**Comment by pizzaboxer** [comment]
Right now I'm thinking of tracking the log file for game joins/disconnects. No idea how reliable it will be, but definitely seems like a safer solution as opposed to silently grabbing the player's auth cookie.

**Comment by 1011025m** [comment]
Yeah you're right, my idea is quite extreme.
