### ISSUE TITLE
Vr issue

### ISSUE THREAD

**Issue by Theo2473** [pizzaboxer/bloxstrap#404]
It doesn't seem to be able to boot into vr. Whenever I start roblox with my vr headset on it should open robklox in vr. But with bloxstrap it doesn't open up in vr. Could you fix this issue and is there a temp solution rn?

**Comment by pizzaboxer** [comment]
Someone else mentioned this issue to me a while back, and I don't really know if there's much I can do about it. I don't own a VR headset, so I can't really make and test a fix for it. You'll just have to stick to using Roblox's original bootstrapper for VR support, unfortunately. Maybe I'll figure out a way to get SteamVR working without a real VR headset, but it's not my priority right now. I'll keep this open for the meantime though.

**Comment by pizzaboxer** [comment]
After some debugging, I have one question to ask. Do you happen to have Vulkan as your selected rendering mode?

**Comment by Theo2473** [comment]
> 

I do have vulkan as renderer might that actually be the issue I will try changing renderer to see if vr will work.
