### ISSUE TITLE
Custom mods depending on the game

### ISSUE THREAD

**Issue by ImMejor35** [pizzaboxer/bloxstrap#405]
I would like to be able to have custom FFlags and other mods depending on the Game/Place Id here is how i would implement it:

First of all Place Id can be grabbed at launch time like from the launch URL "roblox-player://launchinfothings"

Then have a default mods folder and optionally be able to add place id in the GUI and it automatically adding a folder named the Place Id  in the background. If a folder with the place id exists it would auto load that mod folder instead. There is probably a bunch of kinks to how it would work but I would really appreciate this feature being added in the next update.

**Comment by pizzaboxer** [comment]
> First of all Place Id can be grabbed at launch time like from the launch URL "roblox-player://launchinfothings"

That doesn't work if you're changing what place you're in while the app is open. This isn't possible, sorry.

**Comment by ImMejor35** [comment]
> That doesn't work if you're changing what place you're in while the app is open. This isn't possible, sorry.

But it would still be an useful option especially for FFlags

**Comment by pizzaboxer** [comment]
> But it would still be an useful option especially for FFlags

In practice it would end up confusing a whole bunch of people. A better variant of this idea has been suggested numerous times, which I am considering implementing. #1098

**Comment by ImMejor35** [comment]
> > But it would still be an useful option especially for FFlags
> 
> In practice it would end up confusing a whole bunch of people. A better variant of this idea has been suggested numerous times, which I am considering implementing. #1098

#1098 Ability to select a Profile to be chosen automatically depending on the game would be nice.
