### ISSUE TITLE
support RCO

### ISSUE THREAD

**Issue by MaxxusX** [pizzaboxer/bloxstrap#409]
add a switch to enable [RCO](https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/ClientAppSettings.json) and automatically update it, because the normal Roblox and Bloxstrap version's ClientAppSettings are separate files, so [RCO](https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/ClientAppSettings.json)'s installer doesn't work on it.

**Comment by totallyphysicallypossible** [comment]
it's kinda very slightly extremely unstable
