### ISSUE TITLE
Can't launch Roblox using Bloxstrap, related to rbxfpsunlocker

### ISSUE THREAD

**Issue by junnlives** [pizzaboxer/bloxstrap#41]
Whenever I try to install Bloxstrap or play a game, I get this error (refer to uploaded image)
![image](https://user-images.githubusercontent.com/69032098/201108739-a75d2300-68cd-43d8-9d92-a053e9cff62e.png)
This could be because of rbxfpsunlocker getting an update recently.

**Comment by pizzaboxer** [comment]
Can you check the properties for rbxfpsunlocker.exe in the `%localappdata%\Bloxstrap\Integrations\rbxfpsunlocker` folder, and see if the `Read-only` option is enabled?

**Comment by purplux** [comment]
Nope, not enabled.

**Comment by pizzaboxer** [comment]
Can you also check if rbxfpsunlocker is running in the background? Check your system tray or task manager.

**Comment by purplux** [comment]
This seems to have fixed it, thanks!
