### ISSUE TITLE
discord rich presence

### ISSUE THREAD

**Issue by xM4rkHUN** [pizzaboxer/bloxstrap#411]
the discord rich presence always shows that im playing doors

**Comment by pizzaboxer** [comment]
Oh, this bug actually does affect people. Weird thing with this, I'm not sure how I'm able to fix it, since chances are that it could be a Discord bug, or something like that. I'll try taking a deeper look though.

**Comment by xM4rkHUN** [comment]
and one more thing, after clicking on the "View Details" that takes me to this not existing place
![image](https://github.com/pizzaboxer/bloxstrap/assets/108871771/5d71e8db-5f70-4f4b-b02a-70f7f3d02040)

**Comment by pizzaboxer** [comment]
How quickly did you join and leave the game?

**Comment by xM4rkHUN** [comment]
> How quickly did you join and leave the game?

it stays on that

**Comment by xM4rkHUN** [comment]
and im not even playing doors, that see details always takes me to that /0 place
