### ISSUE TITLE
random error after closing roblox

### ISSUE THREAD

**Issue by xM4rkHUN** [pizzaboxer/bloxstrap#412]
![image](https://github.com/pizzaboxer/bloxstrap/assets/108871771/5edac0b6-0684-432a-b794-c32733050871)

**Comment by pizzaboxer** [comment]
How am I supposed to do anything about this if you don't even bother to provide a log file?

**Comment by xM4rkHUN** [comment]
uhh yea

**Comment by xM4rkHUN** [comment]
[Bloxstrap_20230722T112351Z.log](https://github.com/pizzaboxer/bloxstrap/files/12138197/Bloxstrap_20230722T112351Z.log)
here
