### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by chvrisx** [pizzaboxer/bloxstrap#413]
When I'm trying to open Bloxstrap, this thing appears
![thing](https://github.com/pizzaboxer/bloxstrap/assets/92259838/6a158e39-205f-493f-b9bf-8b12a4838a33)
![thingg](https://github.com/pizzaboxer/bloxstrap/assets/92259838/f0f09690-7555-4b03-86cb-87a80658aa9b)

**Comment by pizzaboxer** [comment]
What version of Windows 11, and what do the logs show? Logs should be in %temp% since you're installing for the first time, just sort by newest.

**Comment by chvrisx** [comment]
2023-07-22T23:18:32Z [App::OnStartup] Starting Bloxstrap v2.3.0
2023-07-22T23:18:32Z [App::OnStartup] Running first-time install
2023-07-22T23:18:32Z [Logger::Logger] Initialized at <UserProfileFolder>\AppData\Local\Temp\Bloxstrap_20230722T231832Z.log
2023-07-22T23:18:32Z [JsonManager<Dictionary`2>::Load] Loading JSON from ClientSettings\ClientAppSettings.json...
2023-07-22T23:18:32Z [JsonManager<Dictionary`2>::Load] Failed to load JSON! (Could not find a part of the path '<UserProfileFolder>\Downloads\ClientSettings\ClientAppSettings.json'.)
2023-07-22T23:18:32Z [FastFlagManager::SetValue] Value change for 'DFIntTaskSchedulerTargetFps' to '9999' is pending
2023-07-22T23:18:32Z [MainWindow::MainWindow] Initializing menu

**Comment by chvrisx** [comment]
Win 11 pro

**Comment by chvrisx** [comment]
2023-07-22T23:09:17Z [App::OnStartup] Starting Bloxstrap v2.3.0
2023-07-22T23:09:17Z [App::OnStartup] Running first-time install
2023-07-22T23:09:17Z [Logger::Logger] Initialized at <UserProfileFolder>\AppData\Local\Temp\Bloxstrap_20230722T230917Z.log
2023-07-22T23:09:17Z [JsonManager<Dictionary`2>::Load] Loading JSON from ClientSettings\ClientAppSettings.json...
2023-07-22T23:09:17Z [JsonManager<Dictionary`2>::Load] Failed to load JSON! (Could not find a part of the path '<UserProfileFolder>\Downloads\ClientSettings\ClientAppSettings.json'.)
2023-07-22T23:09:17Z [FastFlagManager::SetValue] Value change for 'DFIntTaskSchedulerTargetFps' to '9999' is pending
2023-07-22T23:09:17Z [MainWindow::MainWindow] Initializing menu
2023-07-22T23:09:25Z [App::OnStartup] Installation cancelled!

**Comment by pizzaboxer** [comment]
> Win 11 pro

What version specifically, and what version of the .NET 6 desktop runtime do you have installed? Open a Command Prompt window, run `dotnet --info`, and show me what appears.

**Comment by chvrisx** [comment]
I actually think I have windows 10, not 11.

.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21996
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.16
  Architecture: x64
  Commit:       1e620a42e7

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by pizzaboxer** [comment]
No, that's definitely 11. Anyway, I'm able to replicate the issue on that version of Windows 11. I can fix it, though there's one thing I should mention.

You're using the first ever version of Windows 11 that was leaked online like over two years ago, and you haven't updated whatsoever since. You should probably update. It would also fix the problem.

cc @Guestywow1

**Comment by chvrisx** [comment]
no, I cant even update

**Comment by pizzaboxer** [comment]
Why not?

**Comment by chvrisx** [comment]
It says that my computer does not meet Windows 11 system requirements.

**Comment by pizzaboxer** [comment]
Yeah, that's what you get for going out of your way to bypass the requirement checks on installation. You can just google how to get around it for updates. Anyway, I'm working on a fix.

**Comment by chvrisx** [comment]
I didnt do anything I just installed the update and I didnt bypass anything but whatever 




On Sunday, July 23, 2023, 10:18 PM, pizzaboxer ***@***.***> wrote:




Yeah, that's what you get for going out of your way to bypass the requirement checks on installation. You can just google how to get around it for updates. Anyway, I'm working on a fix.

**Comment by sabaasa** [comment]
> I didnt do anything I just installed the update and I didnt bypass anything but whatever 
> 
> 
> 
> 
> On Sunday, July 23, 2023, 10:18 PM, pizzaboxer ***@***.***> wrote:
> 
> 
> 
> 
> Yeah, that's what you get for going out of your way to bypass the requirement checks on installation. You can just google how to get around it for updates. Anyway, I'm working on a fix.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
> 
> 
> 
> 

you didn't get this build as an "update", you would need to be a Microsoft employee for that to happen, you or someone else went out of their way to install this leaked build of windows 11. Not to mention it's not even safe to use since Microsoft has given out multiple Microsoft account bans for using this build and I strongly suggest you reinstalled using an USB made with Rufus which allows you to bypass every requirement easily
