### ISSUE TITLE
Minimize Closing

### ISSUE THREAD

**Issue by ChunkieKat** [pizzaboxer/bloxstrap#414]
When I'm playing any games when I minimize the app the whole game closes and starts saying Error.

**Comment by pizzaboxer** [comment]
Are you using the Vulkan renderer?

**Comment by pizzaboxer** [comment]
Assuming that the cause of this is Vulkan being used as the renderer. If not, comment and I'll be happy to reopen.

**Comment by ChunkieKat** [comment]
Sorry for not responding. I have completely forgotten to check my emails,
thank you for helping me find out what's the problem because it has been
annoying me for a while.
