### ISSUE TITLE
BloxStrap Is Acting Strange For Me :(

### ISSUE THREAD

**Issue by ProteusMEMES** [pizzaboxer/bloxstrap#415]
So i just downloaded bloxstraps today and, i opened studio (i only downloaded this program because it "makes the graphics better in roblox studio). I open up studio, open up a game, and all the rigs that are in the game, have parts in them, i dont know why, theres a part, on each part of the rig, like glitched inside of each of the parts. And I deleted BloxStrap hoping this would be fixed but it didnt fix the issue i have. If anyone knows how to fix what problem im having please tell me. i dont want to see parts on each part in my rigs (the normal R6 and R15 rigs)
:((

**Comment by pizzaboxer** [comment]
You should ask this somewhere else since this has nothing to do with Bloxstrap. It does nothing with studio whatsoever.
