### ISSUE TITLE
Ability to disable "DFIntTaskSchedulerTargetFps" / Fps Cap

### ISSUE THREAD

**Issue by prrf** [pizzaboxer/bloxstrap#418]
You should add the ability to disable the FPS cap to enable use for outside fps unlockers.

programs such as rbxfpsunlocker allow for changing fps while the client is running

**Comment by Encythe** [comment]
rbxfpsunlocker does the same thing as bloxstrap does, the only difference is that you don't have to go into the bloxstrap menu to change a single setting

**Comment by pizzaboxer** [comment]
Just set the cap as 0 in the menu. That'll effectively disable it.

**Comment by prrf** [comment]
alr
