### ISSUE TITLE
i just got this error while trying out some features in the new version

### ISSUE THREAD

**Issue by ihad11cats** [pizzaboxer/bloxstrap#420]
![image](https://github.com/pizzaboxer/bloxstrap/assets/134803513/6274761a-fa57-4703-916b-1bb71ce3cdd2)
i got this error while trying some stuff out and the roblox desktop app is very very laggy too and constantly freezes almost and it just started doing that

**Comment by ihad11cats** [comment]
[Bloxstrap_20230724T103613Z.log](https://github.com/pizzaboxer/bloxstrap/files/12144906/Bloxstrap_20230724T103613Z.log)
here is the bloxstrap log also

**Comment by pizzaboxer** [comment]
Are you using the latest build?

**Comment by pizzaboxer** [comment]
See if it happens with https://github.com/pizzaboxer/bloxstrap/commit/d1861262fc35d521119ad7ce6cffaf7d425b0fd3 (https://github.com/pizzaboxer/bloxstrap/actions/runs/5643942500).

**Comment by ihad11cats** [comment]
alright ill try it out

**Comment by ihad11cats** [comment]
its fine now

**Comment by ihad11cats** [comment]
oh also the rendering mode keeps randomly switching

**Comment by ihad11cats** [comment]
i had it set to direct3d 10 and it switched to automatic

**Comment by pizzaboxer** [comment]
Anything else keep switching or is it just that?

**Comment by ihad11cats** [comment]
its just that

**Comment by pizzaboxer** [comment]
Doesn't do that for me. Does it always do that? A look at the latest log file would be nice too.

**Comment by ihad11cats** [comment]
alright

**Comment by ihad11cats** [comment]
[Bloxstrap_20230724T110223Z.log](https://github.com/pizzaboxer/bloxstrap/files/12145122/Bloxstrap_20230724T110223Z.log)

**Comment by ihad11cats** [comment]
oh and i dont think it always does that it mostly does it randomly in my opinion

**Comment by pizzaboxer** [comment]
Did it only do it once?

**Comment by ihad11cats** [comment]
nope multiple times

**Comment by ihad11cats** [comment]
like 3 times or 2 times

**Comment by pizzaboxer** [comment]
Next time it happens, before saving any settings, send a copy of ClientAppSettings.json here. Should be located at %localappdata%\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json.

**Comment by ihad11cats** [comment]
alright
