### ISSUE TITLE
Old character sounds don't turn off

### ISSUE THREAD

**Issue by draker585** [pizzaboxer/bloxstrap#424]
After turning on old character sounds, going into a game, then turning them back off after leaving said game, the old character sounds do not get reverted. This occurs even after a full restart.

**Comment by pizzaboxer** [comment]
Can't replicate, can I see content\sounds inside your mods folder?

**Comment by draker585** [comment]
![image_2023-07-24_194404002](https://github.com/pizzaboxer/bloxstrap/assets/124410415/74131300-1fed-41c1-a695-7ed0cc185ae1)

Even without the sounds in the folder, the old sounds remain, as seen in this clip i took of Football Fusion.
https://medal.tv/games/roblox/clips/1lhtZ7W73lUSf1/d1337PZpwFsa?invite=cr-MSxKQWssMTY0NjExMDks

**Comment by pizzaboxer** [comment]
Oh, weird, looks like it didn't correctly register the sounds in the mod manifest when you first enabled them. Doesn't really help that I neglected to add proper logs for this part of the app. Either way, you can force it by just forcing a Roblox reinstall. Entering `roblox-player:1+launchmode:app+channel:zlive` in your browser's URL bar should do just that.
