### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by Zombiotic** [pizzaboxer/bloxstrap#425]
System.UnauthorizedAccessException: Access to the path 'C:\Users\Zomb\AppData\Local\Bloxstrap\Modifications\content\textures\Cursors\KeyboardMouse\ArrowCursor.png' is denied.
[Bloxstrap_20230724T224433Z.log](https://github.com/pizzaboxer/bloxstrap/files/12153153/Bloxstrap_20230724T224433Z.log)

**Comment by pizzaboxer** [comment]
Can you go to `C:\Users\Zomb\AppData\Local\Bloxstrap\Modifications\content\textures\Cursors\KeyboardMouse\` in the file browser and show a screenshot of what's in there?

**Comment by Zombiotic** [comment]
![image_2023-07-24_183319803](https://github.com/pizzaboxer/bloxstrap/assets/140459431/0d2e2804-3e54-4cbd-bb33-9dbdefddc8c5)

**Comment by Zombiotic** [comment]
nvm i have managed to fix it on my own

**Comment by Pheryos** [comment]
help my windows says its a virus and i cant launch it nor can download it i have windows defender only

**Comment by pizzaboxer** [comment]
> nvm i have managed to fix it on my own

What did you do? Did it just fix it by itself?

**Comment by pizzaboxer** [comment]
Nevermind, seems like it's an antivirus problem.
