### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by TheEmeraldCreeperRB** [pizzaboxer/bloxstrap#426]
System.UnauthorizedAccessException: Access to the path 'moon.jpg' is denied.

**Comment by SeizureSaladd** [comment]
Add more clarification. You just posting an exception message won't help us a lot. Try running BloxStrap/Roblox as administrator.

**Comment by 1011025m** [comment]
DO NOT run Bloxstrap as administrator. It may cause more permission issues.

Do you have Norton Antivirus installed? The new release seems to be tripping it.

**Comment by TheEmeraldCreeperRB** [comment]
I Do have norton installed. What should i do to fix it?

**Comment by TheEmeraldCreeperRB** [comment]
I Managed to fix it with a quick uninstall and reinstall

**Comment by carter0nline** [comment]
> I Managed to fix it with a quick uninstall and reinstall

Then you should probably close this issue

**Comment by pizzaboxer** [comment]
You really should've provided a log file as this looked more like a bug than anything, but oh well.
