### ISSUE TITLE
Roblox crashes on exit, cannot end task.

### ISSUE THREAD

**Issue by imanimal** [pizzaboxer/bloxstrap#428]
Leaving or closing roblox sometimes hard crashes the program to the extent where I can't even close it using task manager.

**Comment by pizzaboxer** [comment]
Isn't that just a Roblox problem?

**Comment by imanimal** [comment]
Unsure. That issue in particular may have something to do with forcing the roblox app to not open after closing.
I also have another issue with the application freezing a few seconds after startup? Perhaps an issue with the rendering systems?

**Comment by pizzaboxer** [comment]
> That issue in particular may have something to do with forcing the roblox app to not open after closing.

Oh yeah, doing that will make intentionally Roblox crash, but it shouldn't stick around in task manager?

**Comment by pizzaboxer** [comment]
Anyway, Roblox should just silently close immediately. You mentioned that you couldn't end the task, which seems to imply that it had already ended, but just wasn't updated in the list, or was in the middle of trying to stop.
