### ISSUE TITLE
"exception"

### ISSUE THREAD

**Issue by AmazoonPrime** [pizzaboxer/bloxstrap#429]
[Bloxstrap_20230725T030312Z.log](https://github.com/pizzaboxer/bloxstrap/files/12156741/Bloxstrap_20230725T030312Z.log)

**Comment by AmazoonPrime** [comment]
Ok, I reinstalled the launcher and now it’s stuck on “please wait”

**Comment by AmazoonPrime** [comment]
Fixed I think

**Comment by AmazoonPrime** [comment]
Just had to restart pc

**Comment by pizzaboxer** [comment]
Antivirus.
