### ISSUE TITLE
Bloxstrap mutes Voice chat

### ISSUE THREAD

**Issue by Mielesgames** [pizzaboxer/bloxstrap#43]
When you try to use voicechat with the Bloxstrap launcher it will fully mute everyone.
I had to uninstall Bloxstrap just to play with voicechat once, I will reinstall it as soon as I stop using voicechat or when its fixed.

**Comment by pizzaboxer** [comment]
I don't have voice chat (yet) so I can't confirm, but I'll check with people who do, and get it fixed soon. Thank you for reporting.

**Comment by pizzaboxer** [comment]
Got voice chat and just checked, and I'm unable to reproduce. Are you sure you have the correct output device selected in settings?

**Comment by Mielesgames** [comment]
> Got voice chat and just checked, and I'm unable to reproduce. Are you sure you have the correct output device selected in settings?

yes, I tried the same settings in the "Normal" roblox application and there it did work.
Mabye I will just have to reïnstall Bloxstrap

**Comment by pizzaboxer** [comment]
I'm less inclined to believe this is a bug with Bloxstrap... checked with some other friends and they say that audio output works just fine. Besides, I don't really see what Bloxstrap would be doing to cause such an oddly specific change.
I can only really see this issue coming from some misconfigured audio setting somewhere.

**Comment by EasternBloxxer** [comment]
Are you on a specific channel or have you modified the FFlags?

**Comment by Mielesgames** [comment]
> I'm less inclined to believe this is a bug with Bloxstrap... checked with some other friends and they say that audio output works just fine. Besides, I don't really see what Bloxstrap would be doing to cause such an oddly specific change. I can only really see this issue coming from some misconfigured audio setting somewhere.

I guess thats the problem, if I still have the problem I will reopen the issue.
