### ISSUE TITLE
Mica not on the bootloader

### ISSUE THREAD

**Issue by RyanLua** [pizzaboxer/bloxstrap#431]
For some reason whether intentionally or not, the bootloader doesn't use Mica whereas the menu uses mica.

Why does this have mica:
![image](https://github.com/pizzaboxer/bloxstrap/assets/80087248/71b0fb39-73bd-4fc5-a1b3-8a2db6d79918)

But not this:
![image](https://github.com/pizzaboxer/bloxstrap/assets/80087248/e18573da-a30f-4b00-868a-8122c6ec18db)

For being "Fluent" I expect Mica or Acrylic.

**Comment by pizzaboxer** [comment]
It's only on the menu now.
