### ISSUE TITLE
cant play roblox

### ISSUE THREAD

**Issue by lotus7372** [pizzaboxer/bloxstrap#432]
![image](https://github.com/pizzaboxer/bloxstrap/assets/140494451/9cf12c16-50bc-42ac-ac04-be0c7c408128)
get this every time bloxstrap is updating
reinstall works but it keeps happening again

**Comment by pizzaboxer** [comment]
What channel do you have configured?

**Comment by lotus7372** [comment]
zbisect2, it says it's out of date. But when i try to switch to another and save, it switched back

**Comment by pizzaboxer** [comment]
What does https://clientsettings.roblox.com/v2/user-channel?binaryType=WindowsPlayer show?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
