### ISSUE TITLE
System.UnauthorizedAccessException:

### ISSUE THREAD

**Issue by Greenbulb** [pizzaboxer/bloxstrap#437]
![image](https://github.com/pizzaboxer/bloxstrap/assets/62176500/81d90f40-5096-4d3c-a628-386323fa059f)
[Bloxstrap_20230725T110029Z.log](https://github.com/pizzaboxer/bloxstrap/files/12160425/Bloxstrap_20230725T110029Z.log)
I've never had this issue before. It occured after upgrading Roblox and happens everytime I try joining a game.
I tried going to the Modifications folder and unsetting the "Read Only" permission, which stopped the crashing however now keeps deleting the images in the folder specified in the image.

(censored part is my first name btw)

**Comment by pizzaboxer** [comment]
It's likely an antivirus problem. Do you have one installed?

**Comment by Greenbulb** [comment]
No, only Windows Defender.

**Comment by pizzaboxer** [comment]
> No, only Windows Defender.

Well, it's definitely Windows doing something weird. Anyway, I should be able to better handle this.

**Comment by pizzaboxer** [comment]
> I tried going to the Modifications folder and unsetting the "Read Only" permission

Okay, I just realized that this probably doesn't prove much, since you checked the properties of the folder and not the actual files themselves.

**Comment by pizzaboxer** [comment]
Anyway, is it still happening right now?

**Comment by pizzaboxer** [comment]
Assuming that it's been fixed by now, or the latest version fixes this. If not, comment and I'll be happy to reopen.
