### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by bennytrt** [pizzaboxer/bloxstrap#442]
System.UnauthorizedAccessException: Access to the path 'C:\Users\user69\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

did i do something wrong?

**Comment by 1011025m** [comment]
If you have Norton installed, make an exception.

**Comment by pizzaboxer** [comment]
Are you using an antivirus?

**Comment by bennytrt** [comment]
no i dont have any anti virus except for windows defender

**Comment by pizzaboxer** [comment]
Go to %localappdata%\Bloxstrap in the file browser, and show the file properties for Bloxstrap.exe.

**Comment by bennytrt** [comment]
![Screenshot (190)](https://github.com/pizzaboxer/bloxstrap/assets/83654600/35321b61-762b-47aa-b4bb-e54c8ea1c10b)
![Screenshot (192)](https://github.com/pizzaboxer/bloxstrap/assets/83654600/678164ec-c7a6-4d98-966b-9e48a180ddf2)
didnt really know what u meant with file properties so i just took these 2 screenshots

**Comment by pizzaboxer** [comment]
Does it happen if you try to launch Bloxstrap now?

**Comment by bennytrt** [comment]
the menu? or like a game on roblox

**Comment by pizzaboxer** [comment]
Playing a game, since that should trigger the auto updater.

**Comment by bennytrt** [comment]
i still get the error, idk if i specified this but it occurs when trying to install

**Comment by bennytrt** [comment]
well yes, but no.
the error occurs, but i can open bloxstrap's menu and try to go in game

**Comment by bennytrt** [comment]
ok i fixed it, but now roblox crashes when trying to play.

**Comment by pizzaboxer** [comment]
> ok i fixed it, but now roblox crashes when trying to play.

Does it happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by bennytrt** [comment]
it does happen without Bloxstrap Yeah

**Comment by pizzaboxer** [comment]
Can't help you on that one, but see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch. Anyway, at least the main problem is fixed now.
