### ISSUE TITLE
DRP doesn't work and closes bloxstrap

### ISSUE THREAD

**Issue by Robustloris** [pizzaboxer/bloxstrap#445]
upon launching roblox through bloxstrap then playing a game, the bootstrapper closes and the rich presence doesn't show at all
here's a video for demonstration [https://youtu.be/Ieqx6ypblWI](url)

as for the logs, bloxstrap seemingly established a connection with discord for the rich presence, but upon updating it, it closes.
[Bloxstrap_20230725T145935Z.log](https://github.com/pizzaboxer/bloxstrap/files/12163143/Bloxstrap_20230725T145935Z.log) (attempt associated with the video above)

[Bloxstrap_20230725T150153Z.log](https://github.com/pizzaboxer/bloxstrap/files/12163149/Bloxstrap_20230725T150153Z.log)
[Bloxstrap_20230725T150753Z.log](https://github.com/pizzaboxer/bloxstrap/files/12163150/Bloxstrap_20230725T150753Z.log)
[Bloxstrap_20230725T154351Z.log](https://github.com/pizzaboxer/bloxstrap/files/12163151/Bloxstrap_20230725T154351Z.log) (attempts after the video)

**Comment by Robustloris** [comment]
yes there seems to be 2 errors relative to the crash, one with .NET and the other with bloxstrap. the 3rd is not an error but more of an insight of windows reporting it
[error_1.txt](https://github.com/pizzaboxer/bloxstrap/files/12163263/error_1.txt)
[error_2.txt](https://github.com/pizzaboxer/bloxstrap/files/12163264/error_2.txt)
[windows_error_reporting.txt](https://github.com/pizzaboxer/bloxstrap/files/12163265/windows_error_reporting.txt)

**Comment by pizzaboxer** [comment]
Oh, it's actually throwing an exception, it just isn't being logged. Turns out it's because it can't fetch the server location, for some reason. ISP might be blocking your connection to https://ipinfo.io or something. I'll add better handling for this, and take a look into why it didn't show an error window.

**Comment by Robustloris** [comment]
yes you're right, i can't access ipinfo and upon turning server notifications off, bloxstrap is working fine.
thanks for the help.
