### ISSUE TITLE
Add a search feature for fastflags

### ISSUE THREAD

**Issue by catb0x** [pizzaboxer/bloxstrap#446]
sorry but i have to keep using notepad if there isnt a search feature. PLEASE OMG how dod u not think about this i NEED a serach feature,, pls,, :((

**Comment by pizzaboxer** [comment]
Search feature where? What are you even using notepad for? I don't know what you're trying to do.

**Comment by rooispoop** [comment]
i think they use notepad to search for certain fastflags with ctrl+f
i guess they want to do the same but with the built-in fastflag editor instead of notepad

**Comment by pizzaboxer** [comment]
But like, what would they be searching in? They said that they're currently using notepad, but with what?

**Comment by pizzaboxer** [comment]
> i need a search feature for fastflags,,, for the fastfllags menu,,, i dont wanna scroll down till i find the flag i wanna change.i want something like ctrl+f

Okay, now I see what you mean, but how many FastFlags do you have set for this to be necessary???

**Comment by catb0x** [comment]
tysm
