### ISSUE TITLE
OptionalMSAALevelOverride FastFlag slider for MSAA (1-16x)

### ISSUE THREAD

**Issue by nerdgh0st** [pizzaboxer/bloxstrap#448]

**Comment by xM4rkHUN** [comment]
sound good

**Comment by pizzaboxer** [comment]
Using what flag?

**Comment by GoingCrazyDude** [comment]
pretty sure its this one
FIntDebugFRMOptionalMSAALevelOverride

**Comment by pizzaboxer** [comment]
I also see FIntDebugForceMSAASamples, would probably be a good idea to first clear up what each one does.

**Comment by nerdgh0st** [comment]
yep it's DebugForceMSAASamples for antialiasing
MSAALevelOverride appears to be for something else

**Comment by pizzaboxer** [comment]
> yep it's DebugForceMSAASamples for antialiasing

One question - does it actually do anything? [Before](https://github.com/pizzaboxer/bloxstrap/assets/41478239/935c4706-14f1-4138-a991-f5ec36191d54) and [after](https://github.com/pizzaboxer/bloxstrap/assets/41478239/9f0e3306-6cb4-413c-a3e7-919664f9a70e) between defaults and the flag set as 8 show no difference.

**Comment by nerdgh0st** [comment]
It does work - as long as the graphics slider bar isn't on a level with MSAA (e.g lowest graphics setting)
Another thing is that if you set this value to 1 on maximum graphics... it basically gives you that but without SSAO

**Comment by pizzaboxer** [comment]
After some quick testing, seems like 8 is as far as it can go.
