### ISSUE TITLE
"An unexpected error occurred and roblox needs to quit. We're sorry!"

### ISSUE THREAD

**Issue by zzahkaboom24** [pizzaboxer/bloxstrap#449]
I've seen issues like this and people got helped, so I will try my chances here too. Since the anti-cheat update I am getting this issue on both Roblox and Bloxstrap and I cannot play Roblox normally anymore unless I launch Roblox in admin mode.
Launching Roblox in admin mode fixes this issue, but because Roblox is running on admin mode, my PC can BSOD at any time, which makes it unplayable still. 

I've looked through the faq, and it does happen in the first few seconds after launching a Roblox game but I do not think there is any app that is causing the issue. MSI Afterburner and RTSS I am not using at all.

I am willing to send any files, logs, or something if you're able to find out what's causing it? I am currently stuck with using the Microsoft Store version of Roblox because of it, and besides that, I was using Bloxstrap for the features it had, so at the moment I am unable to use it at all. 

Help is very much appreciated xd

**Comment by pizzaboxer** [comment]
> I've seen issues like this and people got helped, so I will try my chances here too

I hope you've noticed that I wasn't really able to help people any further if the Wiki page wasn't able to help them.

**Comment by zzahkaboom24** [comment]
Yes. Its okay if its impossible. Figured I could perhaps take chances xd

**Comment by pizzaboxer** [comment]
Sorry, not really much I can do for you.

**Comment by zzahkaboom24** [comment]
Nvm I fixed it xd. It was actually Magic Borderless causing this issue. So for anyone using apps like Magic Borderless or Borderless Gaming, this might be the cause.

**Comment by pizzaboxer** [comment]
Noted, I'll add that to the wiki. Was it both of them or just Magic Borderless?

**Comment by zzahkaboom24** [comment]
At the moment it was only Magic Borderless (it's an app from Steam btw.), but I will try Borderless Gaming too. I guess it has something to do with Magic Borderless trying to detect the apps and this detection causes the anticheat to go nuts. But its just an assumption and out of scope of this.

**Comment by pizzaboxer** [comment]
Okay, thanks for clarifying.
