### ISSUE TITLE
IDEA: add the old loading screen back (the 2017+ one i think)

### ISSUE THREAD

**Issue by sha4owz** [pizzaboxer/bloxstrap#451]
So, this can be done by altering a certain file called PatchModelData, which can be accessed by going ExtraContent>models>DataModelPatch> and then there should be a file called "DataModelPatch.rbxm". This file updates every time the client updates. To get the old loading screen back, simply just take the "DataModelPatch.rbxm" from a 2021 client where they still use it, and use that file to replace the newer one. Also make sure to delete places after adding the new one or some thing will mess up.

There might be a easier way, but I'm not sure.

**Comment by OrphanObliterator** [comment]
yeah this disables the desktop app im pretty sure

**Comment by sha4owz** [comment]
i think so, depends what version you pick

**Comment by pizzaboxer** [comment]
> simply just take the "DataModelPatch.rbxm" from a 2021 client where they still use it

Won't that negatively affect other things?

**Comment by sha4owz** [comment]
> 

I'm not sure

**Comment by nakoyasha** [comment]
I've tried doing this and the only thing I got is all CoreGUI missing (loading screen, notifications, dev console, topbar, etc)

So unless I messed something up (which I doubt), I think it's safe to say that this should not be considered.
