### ISSUE TITLE
bloxstrap

### ISSUE THREAD

**Issue by popbob2** [pizzaboxer/bloxstrap#452]
bloxstrap is getting flagged as Behavior:Win32/DefenseEvasion.A!ml

![image](https://github.com/pizzaboxer/bloxstrap/assets/76769061/efaeb081-cf98-41d5-9c10-5519ca936640)

**Comment by pizzaboxer** [comment]
There's not really anything I can do about that. Just allow it and it'll be fine.

**Comment by popbob2** [comment]
i made a exclusion instead
