### ISSUE TITLE
Graphics is not working

### ISSUE THREAD

**Issue by sha4owz** [pizzaboxer/bloxstrap#453]
The graphics selector is not working, was like this in previous update.
![image](https://github.com/pizzaboxer/bloxstrap/assets/138281770/096f071b-5562-4258-ba9d-466194ae4dae)

**Comment by pizzaboxer** [comment]
Works for me. Do you have it enabled in the menu?

**Comment by sha4owz** [comment]
Yep, think i might just be my ROBLOX client not Bloxstrap because its the same even when turned off.

**Comment by ToxicTDX** [comment]
Its on automatic lol make it manual

**Comment by sha4owz** [comment]
O-oh
