### ISSUE TITLE
Download says it has a virus

### ISSUE THREAD

**Issue by IKIRK101** [pizzaboxer/bloxstrap#454]
![Screenshot 2023-07-26 131247](https://github.com/pizzaboxer/bloxstrap/assets/140615787/b8e9a3e1-05ef-4438-913c-fdd9a23c35b8)
![Screenshot 2023-07-26 125950](https://github.com/pizzaboxer/bloxstrap/assets/140615787/731ee2b6-5713-4eb8-8960-c339b92aa472)

**Comment by Sahelantrophus** [comment]
Delete it as soon as you can

**Comment by xM4rkHUN** [comment]
bro dont delete it, its a false positive
turn off you anti virus and download it, it causes no harm to your device

**Comment by xM4rkHUN** [comment]
plus download sometimes says false things

**Comment by Sahelantrophus** [comment]
Don't listen to this bozgor's lies he's trying to get your PC killed

**Comment by xM4rkHUN** [comment]
bro what

**Comment by pizzaboxer** [comment]
False positive, not much I can do about that. This usually happens whenever a new update is released. You'll have to add it as an exception in your antivirus if it keeps happening.
