### ISSUE TITLE
Bloxtrap isnt working

### ISSUE THREAD

**Issue by dollydelrry** [pizzaboxer/bloxstrap#455]
System.Net.Http.HttpRequestException: No such host is known. (clientsettingscdn.roblox.com:443)

===== Inner Exception =====
System.Net.Sockets.SocketException: No such host is known.

**Comment by pizzaboxer** [comment]
DNS issue. Does going to https://clientsettingscdn.roblox.com in your browser work?

**Comment by pizzaboxer** [comment]
Assuming that the latest release fixes this. If it doesn't, comment and I'll reopen.

**Comment by faridy69** [comment]
i doesnt for me

**Comment by pizzaboxer** [comment]
Are you getting the same error?

**Comment by pizzaboxer** [comment]
Connectivity error. Check to make sure your antivirus isn't blocking it fron connecting to the internet, or just try launching again

**Comment by A0mmar** [comment]
**It still does work when i open https://clientsettingscdn.roblox.com/ it says {"message":"OK"} but still doesn't download**

**Comment by A0mmar** [comment]
`whothehellares?`

**Comment by A0mmar** [comment]
#### Yo, i checked my firewall it still no work :(

**Comment by erhtert** [comment]
> DNS issue. Does going to https://clientsettingscdn.roblox.com in your browser work?

no
