### ISSUE TITLE
Windows Defender flags Bloxstrap as malicious

### ISSUE THREAD

**Issue by AVeryBrokenNPC** [pizzaboxer/bloxstrap#456]
![image](https://github.com/pizzaboxer/bloxstrap/assets/95186111/fae55522-dd01-48af-8c0d-a1f0942330a2)
A temporary fix for this is 1. disabling Windows Defender 2. adding bloxstrap install folder to exclusions

**Comment by xM4rkHUN** [comment]
dw
we cant do anything with that name

**Comment by pizzaboxer** [comment]
duplicate of #454
