### ISSUE TITLE
Bloxstrap has a seizure

### ISSUE THREAD

**Issue by idontyboi** [pizzaboxer/bloxstrap#459]
Hi, new here. I went around and downloaded Bloxstrap, and resized it to see all the options it has to offer. Bloxstrap immediately had seizures.
The window frame resizes before the application itself and sits there until the window frame catches up:
![image](https://github.com/pizzaboxer/bloxstrap/assets/36737188/5b24d898-dd09-4827-b51b-a60959550bd9)
The application outright flashes at ridiclous speeds on resize (Can't get a image when it resizes, it looks something like this):
![image](https://github.com/pizzaboxer/bloxstrap/assets/36737188/978e3d5e-9e86-4e8c-91b2-596431e38724)

It only gets worse the bigger the window of Bloxstrap is.

## Specifications
**I know, I know.**
CPU: Pentium E6500 - 2C/2T 2.93 GHz
GPU: Integrated (Intel G41 Express Chipset DX10), 798MB shared VRAM
RAM: 1981 MB
Operating System: Windows 7 (Build 7601.24546) 64-Bit
Storage Device: HDD, sadly...
# Workaround
- **The seizure does not happen when disabling the Windows Aero effects.** But then some applications demand Aero, and then some other application functionality breaks (Discord makes every non-Roblox application screenshared have a literal seizure)
### Question
Is Bloxstrap meant to work on these PC specifications?

**Comment by pizzaboxer** [comment]
The problem is just that it's a little slow when resizing, and that's it?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
