### ISSUE TITLE
Bloxstrap uses an outdated version of fps unlocker

### ISSUE THREAD

**Issue by thriftydoge** [pizzaboxer/bloxstrap#46]
The fps unlocker was given a patch for the november 9th update but still errors when opened with bloxstrap, leading me to believe that the one integrated into bloxstrap may be an outdated version.

**Comment by pizzaboxer** [comment]
Bloxstrap automatically updates FPS unlocker though, what's the last modified date for rbxfpsunlocker.exe in `%localappdata%\Bloxstrap\Integrations\rbxfpsunlocker` ?

**Comment by thriftydoge** [comment]
It says it was last modified on 2022-03-02 while being created at 2022-11-09.
<img width="204" alt="image" src="https://user-images.githubusercontent.com/87211537/201544122-6c76e882-b5c1-4d55-9c88-2a4fa207e0ba.png">

**Comment by pizzaboxer** [comment]
That seems like it should be automatically updating without a problem...
If you're sure that it's still out of date when launching, then [try this debug build](https://pizzaboxer.xyz/temp/Bloxstrap-v1.5.3-x64-rfudebug.exe) to see where it goes wrong

**Comment by pizzaboxer** [comment]
Actually, nevermind! Just added a better way to handle updating rbxfpsunlocker which should basically fix your issue.

**Comment by pizzaboxer** [comment]
Just released v1.5.3, please let me know if it fixes this issue.

**Comment by thriftydoge** [comment]
Works perfectly.
