### ISSUE TITLE
Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by LF5Github** [pizzaboxer/bloxstrap#460]
Hey there. I just found out about Bloxstrap and I thought about the features of the program and how useful these features are.

Unfortunately, I just so happen to run into some kind of error: "System.UnauthorizedAccessException: Attempted to perform an unauthorized operation." I also tried running it with admin perms but to no avail. It's the same, it isn't able to apply roblox modifications.
[Bloxstrap_20230727T000006Z.log](https://github.com/pizzaboxer/bloxstrap/files/12178203/Bloxstrap_20230727T000006Z.log)

**Comment by pizzaboxer** [comment]
Why is it unable to write to the Windows registry? Do you have an antivirus or something that could be blocking it from doing that?

**Comment by LF5Github** [comment]
I paused my antivirus to see if it was the antivirus. But I still couldn't get through. I'm not sure whats causing this

( I accidentally closed this btw)

**Comment by pizzaboxer** [comment]
According to the log, it's failing to set either `HKEY_CURRENT_USER\SOFTWARE\Classes\roblox` or `HKEY_CURRENT_USER\SOFTWARE\Classes\roblox-player`. If you open the registry editor, and check the permissions for those two keys, under your user account, what do they show?

**Comment by LF5Github** [comment]
All but "ALL APPLICATION PACKAGES" and "RESTRICTED" do not have full control.

**Comment by LF5Github** [comment]
It started roblox and everything worked now. Thank you!
