### ISSUE TITLE
Crashing without an error

### ISSUE THREAD

**Issue by Slayercorpps** [pizzaboxer/bloxstrap#461]
it crashes every 10 mins for some reason and i cant get it to do anything else as ive uninstalled and reinstalled but also changed settings, help

**Comment by HeroboyPehi** [comment]
> it crashes every 10 mins for some reason and i cant get it to do anything else as ive uninstalled and reinstalled but also changed settings, help

To be fair, it happens everytime Roblox got a sudden shutdown on their server or they updated and pizzaboxer did explain that issue in the Wiki, something about the anti cheat just mistaken the app for third party and then just instant shutdown your game
It is currently happening to me right now, kinda annoying but I suggest you to try UWP Roblox from Microsoft store while Pizzaboxer fixing this issue or Roblox fixing their anti cheat

**Comment by pizzaboxer** [comment]
> it crashes every 10 mins for some reason and i cant get it to do anything else as ive uninstalled and reinstalled but also changed settings, help

What's crashing? Roblox or Bloxstrap?

**Comment by Slayercorpps** [comment]
both, im not sure if its roblox or bloxstrap but when i check i dont see the logo

**Comment by Slayercorpps** [comment]
after a bit of testing it seems that it happens at random times, yesterday in the morning and after waiting an hour i was able to play till 2, weird

**Comment by pizzaboxer** [comment]
> both, im not sure if its roblox or bloxstrap but when i check i dont see the logo

What? Which logo? Also, it would be easy to tell. Roblox crashing would show a dialog box, or refuse to launch.

**Comment by Slayercorpps** [comment]
bloxstrap logo

**Comment by pizzaboxer** [comment]
Where? In the taskbar's notification area?

**Comment by Slayercorpps** [comment]
yup

**Comment by Slayercorpps** [comment]
mb, it launches with bloxsttap but does not show the notification

**Comment by pizzaboxer** [comment]
Let me see the latest log file, you can find them at %localappdata%\Bloxstrap\Logs in the file browser.

**Comment by Slayercorpps** [comment]
[Bloxstrap_20230727T025844Z.log](https://github.com/pizzaboxer/bloxstrap/files/12188236/Bloxstrap_20230727T025844Z.log)

**Comment by Slayercorpps** [comment]
this was yesterday when it was supposedly crashing

**Comment by Slayercorpps** [comment]
[Bloxstrap_20230727T205435Z.log](https://github.com/pizzaboxer/bloxstrap/files/12188261/Bloxstrap_20230727T205435Z.log)

**Comment by Slayercorpps** [comment]
this is the latest as of right now

**Comment by pizzaboxer** [comment]
Do you have activity tracking enabled?

**Comment by Slayercorpps** [comment]
no

**Comment by pizzaboxer** [comment]
Yeah, so then it's not supposed to show the icon in the taskbar while Roblox is running. This is exactly how this is supposed to be functioning.

**Comment by Slayercorpps** [comment]
oh ok

**Comment by Slayercorpps** [comment]
thank you for your help
