### ISSUE TITLE
Problem With Permission

### ISSUE THREAD

**Issue by Sacinyan** [pizzaboxer/bloxstrap#462]
It keeps saying this when I try applying any changes in the bloxstrap menu:

System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (clientsettingscdn.roblox.com:443)

===== Inner Exception =====
System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions.

here is the log btw
[Bloxstrap_20230727T122938Z.log](https://github.com/pizzaboxer/bloxstrap/files/12183428/Bloxstrap_20230727T122938Z.log)

**Comment by pizzaboxer** [comment]
Do you have anything on your computer that could be blocking Bloxstrap from connecting to the internet?

**Comment by Sacinyan** [comment]
Could a vpn be doing it?

**Comment by pizzaboxer** [comment]
Probaby. Try disabling that and see if anything changes.

**Comment by Sacinyan** [comment]
wait, my vpn isn't on, so what should i do?

**Comment by Sacinyan** [comment]
I just don't really know how to or where i could find something blocking my internet for the app.

**Comment by pizzaboxer** [comment]
Antivirus, maybe?

**Comment by Sacinyan** [comment]
that's what im looking at

**Comment by Sacinyan** [comment]
right now

**Comment by Sacinyan** [comment]
yep my antivirus was being goofy, thanks for putting up with my dumbness
