### ISSUE TITLE
Cursor disappearing.

### ISSUE THREAD

**Issue by dyban** [pizzaboxer/bloxstrap#464]
![image](https://github.com/pizzaboxer/bloxstrap/assets/58275197/dabcd344-1a32-4431-9bf7-4e7668988c28)
When the Modified cursor images are deleted or modified incorrectly they tend to be marked as "deleted" and will no longer display.

Fix: Make bloxstrap check for cursor files on launch and if missing or corrupted, put them in a "Saved" or "Corrupted" folder and then replace with originals inside KeyboardMouse folder.

**Comment by pizzaboxer** [comment]
> When the Modified cursor images are deleted or modified incorrectly they tend to be marked as "deleted" and will no longer display.

Are you sure? What does the version folder show?

**Comment by totallyphysicallypossible** [comment]
i just did the same thing myself and it just used the default roblox cursor

i feel like their original cursor images got corrupted (or something), as im pretty sure bloxstrap only replaces files with what it finds in the modifications folder, and if it doesnt find anything it'll just use the default from roblox

**Comment by pizzaboxer** [comment]
> i feel like their original cursor images got corrupted (or something)

They might've, since it's happened to someone else before, which is why I want them to check the version folder.

**Comment by pizzaboxer** [comment]
Strongly assuming this to be fixed, since Roblox would've updated by now, which would've fixed the mouse cursors not showing. If not, respond and I'll reopen.
