### ISSUE TITLE
no bloxstrap menu

### ISSUE THREAD

**Issue by f1h3d** [pizzaboxer/bloxstrap#465]
i was trying to change fps unlocker but there were no bloxstrap menu i tried to search it and i dont have it

**Comment by pizzaboxer** [comment]
What does the programs list show?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by jakeiscool797979** [comment]
hey! I'm having the same menu, my bloxstrap menu is not showing up in the start menu but bloxstrap itself is. when I open  bloxstrap it just opens a new Roblox tab in google. Please respond and thank you

**Comment by pizzaboxer** [comment]
>  my bloxstrap menu is not showing up in the start menu

Check your installed applications list instead of using Windows Search it.

> when I open bloxstrap it just opens a new Roblox tab in google. 

You opted to disable the desktop app when installing Bloxstrap.

**Comment by jorikmahorik228** [comment]
Same problem , but it doesn't show up in search
