### ISSUE TITLE
Alt+Enter crashes while using low resolutions

### ISSUE THREAD

**Issue by zekicode** [pizzaboxer/bloxstrap#466]
I was playing on 1024x768 resolution for fps, and as soon as I did alt+enter the game crashed. I tried playing on my monitor's highest resolution (1600x900) and it didn't crash, but I got this message.
![image](https://github.com/pizzaboxer/bloxstrap/assets/140855787/74c4e97c-1a96-4890-990d-d32dffd7b499)

This didn't happen in the previous update btw.

Here are some logs that I found:
[Bloxstrap_20230728T211235Z.log](https://github.com/pizzaboxer/bloxstrap/files/12198562/Bloxstrap_20230728T211235Z.log)
[Bloxstrap_20230728T211548Z.log](https://github.com/pizzaboxer/bloxstrap/files/12198563/Bloxstrap_20230728T211548Z.log)

**Comment by zekicode** [comment]
Nvm, old version is crashing for some reason too, i'll restart my pc

**Comment by pizzaboxer** [comment]
Are you using the Vulkan renderer?

**Comment by zekicode** [comment]
Nope, i'm using direct3d 11

**Comment by pizzaboxer** [comment]
Yeah, I wouldn't know why that happens.

> Here are some logs that I found:
> [Bloxstrap_20230728T211235Z.log](https://github.com/pizzaboxer/bloxstrap/files/12198562/Bloxstrap_20230728T211235Z.log)
> [Bloxstrap_20230728T211548Z.log](https://github.com/pizzaboxer/bloxstrap/files/12198563/Bloxstrap_20230728T211548Z.log)

These are logs for Bloxstrap, not Roblox.

**Comment by zekicode** [comment]
My bad, thought I had to send those
[0.587.0.5870056_20230728T213908Z_Player_901B6_last.log](https://github.com/pizzaboxer/bloxstrap/files/12198650/0.587.0.5870056_20230728T213908Z_Player_901B6_last.log)

**Comment by pizzaboxer** [comment]
Anyway, it's a Roblox problem, nothing I can really do about it. Sorry.

**Comment by zekicode** [comment]
Hello, im back. After the recent roblox update im now able to play with alt+enter again.
