### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NightyyPlayer800** [pizzaboxer/bloxstrap#471]
![image](https://github.com/pizzaboxer/bloxstrap/assets/139729389/644896f4-3fbf-4307-863d-10ad58943743)

I'm trying to open roblox and says this

**Comment by pizzaboxer** [comment]
Not a Bloxstrap problem. https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
