### ISSUE TITLE
Make the "Exclusive Fullscreen" feature optional

### ISSUE THREAD

**Issue by BlackxNerm** [pizzaboxer/bloxstrap#472]

**Comment by pizzaboxer** [comment]
Already in the works for the next version. Though I'm not exactly making it "optional", I'm making sure it's only enabled for Direct3D, as it messes with Vulkan and OpenGL.

**Comment by sha4owz** [comment]
> Already in the works for the next version. Though I'm not exactly making it "optional", I'm making sure it's only enabled for Direct3D, as it messes with Vulkan and OpenGL.

question: what lighting did 2016 roblox use? I Always noticed it to be greyish
