### ISSUE TITLE
The FPS goes to inf/s and crash

### ISSUE THREAD

**Issue by i-Dummys** [pizzaboxer/bloxstrap#473]
[](url)
![inf](https://github.com/pizzaboxer/bloxstrap/assets/140934098/7ad400d5-ecc3-486b-a933-45ae6b80e991)

**Comment by pizzaboxer** [comment]
First time I've heard of this happening, would probably be a good idea to limit your framerate a little bit to something lower than 999.

**Comment by bainchild** [comment]
I am having a very similar issue where the framerate slows to about 2/s (and shift+f5 shows inf/s), if the flag is present at all (even at the default, 60, and with 0 it just crashes on launch). The normal roblox player works fine, and Bloxstrap has no way to stop it adding the fint in the client settings file.

**Comment by pizzaboxer** [comment]
the issue in a nutshell:

https://github.com/pizzaboxer/bloxstrap/assets/41478239/b1b6a374-75f3-443f-9a9d-cfaabddf5551

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
