### ISSUE TITLE
An Exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by vishw4k** [pizzaboxer/bloxstrap#475]
why is this error coming?
[Bloxstrap_20230730T091744Z.log](https://github.com/pizzaboxer/bloxstrap/files/12208841/Bloxstrap_20230730T091744Z.log)

someone fix it idk

**Comment by pizzaboxer** [comment]
Your ISP is blocking access to https://raw.githubusercontent.com. You can either choose to disable the emoji mod preset you've selected, or [use a beta build of the next version](https://github.com/pizzaboxer/bloxstrap/suites/14668303369/artifacts/832425136) which gets around this.

**Comment by vishw4k** [comment]
thanks it worked 👍
