### ISSUE TITLE
idea: Add old navigation icons to app (READ)

### ISSUE THREAD

**Issue by sha4owz** [pizzaboxer/bloxstrap#476]
I'm _NOT_ exactly sure if I've asked this before. My apologies if I have and also sorry for asking twice on the loading screen.

Basically just the old icons for the side bar of the app, another small idea would be adding the old 2016+ robux logo!

**Comment by pizzaboxer** [comment]
You have, but my main concern was whether they'd look "right", as I feel like they'd heavily clash with the overall look of the desktop app. I'll try them out though.

**Comment by sha4owz** [comment]
> You have, but my main concern was whether they'd look "right", as I feel like they'd heavily clash with the overall look of the desktop app. I'll try them out though.

Yay! Also try the ROBUX logo, I really feel it will add a legacy feel

**Comment by sha4owz** [comment]
> You have, but my main concern was whether they'd look "right", as I feel like they'd heavily clash with the overall look of the desktop app. I'll try them out though.

Reply when you have tried them, im really curious what it would look like!

**Comment by pizzaboxer** [comment]
Taking a further look, doing this might not be a good idea. The thing is that none of these icons are stored individually, they're stored among many other icons within the same image file, That makes modding this questionable, as any changes Roblox makes to those icon sheets won't apply anymore. Because of that, this isn't really practical. Sorry.

**Comment by sha4owz** [comment]
> Taking a further look, doing this might not be a good idea. The thing is that none of these icons are stored individually, they're stored among many other icons within the same image file, That makes modding this questionable, as any changes Roblox makes to those icon sheets won't apply anymore. Because of that, this isn't really practical. Sorry.

Ok, all goods. Would the old robux logo be possible or are you talking about all the icons?
