### ISSUE TITLE
Certain windows are broken sometimes

### ISSUE THREAD

**Issue by alpharetzy** [pizzaboxer/bloxstrap#478]
When i want to add a FastFlag, the window is just broken and the accent color goes to the window. Even when disabled it still shows the broken window. The textboxes and the buttons would not show unless you hover it. Pictures:

![image](https://github.com/pizzaboxer/bloxstrap/assets/112749084/4c20d738-d8ab-4e37-a1a7-02a3922df0b9)

This is what it supposed to look like.

![image](https://github.com/pizzaboxer/bloxstrap/assets/112749084/5a7420fe-d4cf-49d1-baf4-f781f43316f6)

Sometimes appears like this,

![image](https://github.com/pizzaboxer/bloxstrap/assets/112749084/609915a1-aabc-41a0-853b-b94b6ce02c69)

And this is where the window is fully broken. Anything won't show until you hover a textbox or button.

![image](https://github.com/pizzaboxer/bloxstrap/assets/112749084/ee279fef-8767-46cc-a206-949af2973f7d)

Uh oh... It's now affecting the server details window 😱😱😱

**Comment by pizzaboxer** [comment]
Seems more like a WPF bug than anything. There wouldn't really be any way for me to fix it. Does this only happen with this dialog, and not any other dialogs, like message boxes?

**Comment by alpharetzy** [comment]
> Seems more like a WPF bug than anything. There wouldn't really be any way for me to fix it. Does this only happen with this dialog, and not any other dialogs, like message boxes or the bootstrapper?

Unfortunately, yes because the server details window is also broken

**Comment by alpharetzy** [comment]
> > Seems more like a WPF bug than anything. There wouldn't really be any way for me to fix it. Does this only happen with this dialog, and not any other dialogs, like message boxes or the bootstrapper?
> 
> Unfortunately, yes because the server details window is also broken

It only affects the add fastflag & server details window, but not everything else

**Comment by pizzaboxer** [comment]
How often does this happen? Anyway, try out this build, which disables the custom borders on those dialog boxes. Just run Bloxstrap.exe and choos "Yes" when it asks you to upgrade.

https://github.com/pizzaboxer/bloxstrap/actions/runs/5737618344

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
