### ISSUE TITLE
keeps saying error code 429 and failed to load sensapi.dll

### ISSUE THREAD

**Issue by Persven** [pizzaboxer/bloxstrap#479]

**Comment by Persven** [comment]
> But the thing about sensapi.dll is that when i delete bloxstrap roblox is fine and the 429 looks like    Error code 429
                                                                                                                                                                
an error was encountered during authentication roblox

**Comment by pizzaboxer** [comment]
That's Roblox ratelimiting you, not a Bloxstrap problem.

**Comment by Persven** [comment]
But what do I do?

**Comment by pizzaboxer** [comment]
You wait a while. Back to this.

> and failed to load sensapi.dll

Does this happen without Bloxstrap?

**Comment by Persven** [comment]
Nope only with bloxstrap

**Comment by pizzaboxer** [comment]
Let me clear up something - are you getting both errors with Bloxstrap? The message for Error Code 429 wouldn't show if the one for SensApi.dll shows. Either way, it might be worth forcing a Roblox reinstall? Try setting your channel to 'ZNext', and see if that changes anything.

**Comment by Persven** [comment]
Yeah those errors only happen with blox strap

**Comment by Persven** [comment]
where do i set my channel to znext

**Comment by pizzaboxer** [comment]
Does it work?

**Comment by Persven** [comment]
Yeah fixed thanks
