### ISSUE TITLE
Is there a FastFlag for disabling the Microphone Pop-up?

### ISSUE THREAD

**Issue by OrangeZXZ** [pizzaboxer/bloxstrap#483]
Hi i would like to know if there is a FastFlag to disable the Microphone Pop-up that you see on top of your caracter because I hate it but I don't want to disable voice chat just for this.
Thx in advance.

**Comment by pizzaboxer** [comment]
I've just did some testing, and there doesn't appear to be, not without completely disabling voice chat. Sorry.
