### ISSUE TITLE
allow us to use custom emoji fonts (kinda bug kinda enchancement)

### ISSUE THREAD

**Issue by catb0x** [pizzaboxer/bloxstrap#486]
i want 2 test apple emojis but when i paste it into modifications\content\fonts it gets replaced by the emoji font that was choosed in the bloxstrap menu. can u pls enable us to use custom emoji fonts

**Comment by pizzaboxer** [comment]
> it gets replaced by the emoji font that was choosed in the bloxstrap menu

Set it as default.
