### ISSUE TITLE
Roblox won't start

### ISSUE THREAD

**Issue by catb0x** [pizzaboxer/bloxstrap#487]
im rlly sorry 4 bombarding u with bugs but,,, i wanna play roblox,,,
![image](https://github.com/pizzaboxer/bloxstrap/assets/77354428/e5c9fc61-3182-4fd5-a7cd-6fc150fd345f)
when i open roblox from the website bloxstrap does its thing and the bloxstrap window appears (as it should normally) but the roblox window doesnt open. it stays as a background prosses hogging up memory. is it a problem with my programs? idk
[Bloxstrap_20230801T190735Z.log](https://github.com/pizzaboxer/bloxstrap/files/12233179/Bloxstrap_20230801T190735Z.log)

**Comment by catb0x** [comment]
update: roblox does open if i use the app but lets be fr who uses taht thing

**Comment by catb0x** [comment]
uodate: it works again? i will close this until i have more info

**Comment by Sahelantrophus** [comment]
whoever marked my comment as off-topic you a bitch and that's on 55th
