### ISSUE TITLE
Is Bloxstrap safe?

### ISSUE THREAD

**Issue by iamdanygit** [pizzaboxer/bloxstrap#489]
I am always sketchy when downloading stuff from the internet.
I know it's open source and virustotal says it's clean. But I still want some confirmation.

Does it steal cookies or something?

**Comment by EasternBloxxer** [comment]
how would it do that lmao

**Comment by EasternBloxxer** [comment]
Check the source

**Comment by iamdanygit** [comment]
I trust it but I want to be sure, thats how I am lol

**Comment by pizzaboxer** [comment]
> Does it steal cookies or something?

Open-source. Over ten thousand downloads. Over 400 stars. Eight different contributors. If there was something malicious in the code, you'd bet that someone would've at least said something by now.

**Comment by iamdanygit** [comment]
I had another question tho, does the v2 menu still work? I saw people saying it got nerfed too

**Comment by pizzaboxer** [comment]
The v3 menu got nerfed, but v2 still works.

**Comment by iamdanygit** [comment]
Thanks!

**Comment by Kaixon986** [comment]
Virus total says Gridinsoft (no cloud)                                    [Trojan.Win64.AsyncRAT.tr](javascript:void(0);)
