### ISSUE TITLE
Bloxstrap cannot connect to the internet upon launch.

### ISSUE THREAD

**Issue by infradragon** [pizzaboxer/bloxstrap#490]
![image](https://github.com/pizzaboxer/bloxstrap/assets/72665124/9208daab-177a-4946-ba47-c7c7edc3fd5c)
```
System.Net.Http.HttpRequestException:` An error occurred while sending the request.

===== Inner Exception =====
System.IO.IOException: The read operation failed, see inner exception.
```
This happened overnight. I dont know what troubleshooting steps to take to provide more information. I can connect to the roblox website just fine.

**Comment by infradragon** [comment]
Here is some basic system info, along with all the bloxstrap logs
System Info [https://pixeldrain.com/u/KNXxk9bh](https://pixeldrain.com/u/56ZvAFLS)
Logs [https://pixeldrain.com/u/KNXxk9bh](https://pixeldrain.com/u/KNXxk9bh)

**Comment by pizzaboxer** [comment]
Bloxstrap throws that error if it's unable to connect to https://detectportal.firefox.com. If you want to check, go to that URL in your browser, it should prompt for a file download.

The error message doesn't seem to be showing properly (oops), so try out this version (just run Bloxstrap.exe) and show me the error message from that. 

https://github.com/pizzaboxer/bloxstrap/suites/14755064807/artifacts/838830777

**Comment by infradragon** [comment]
installing the latest version fixed it. odd that it didnt auto update. thank you very much for your help!

**Comment by infradragon** [comment]
out of curiosity, i tried installing v2.5.0 release, and it gave the same error when i tried the installer. whatever secret sauce you used in the version you gave me should probably be merged to main.

**Comment by pizzaboxer** [comment]
> out of curiosity, i tried installing v2.5.0 release, and it gave the same error when i tried the installer. whatever secret sauce you used in the version you gave me should probably be merged to main.

Yeah, give it about a week.

**Comment by infradragon** [comment]
:3
