### ISSUE TITLE
Bloxstrap : An exception occured while running Bloxstrap

### ISSUE THREAD

**Issue by TonSon464** [pizzaboxer/bloxstrap#492]
System.IO.FileFormatException: The image decoder cannot decode the image. The image might be corrupted.

===== Inner Exception =====
System.Runtime.InteropServices.COMException: The image is unrecognized. (0x88982F60)
It's says this while i was going into bootstrapper

**Comment by pizzaboxer** [comment]
Where's the log file?

**Comment by TonSon464** [comment]
[Bloxstrap_20230802T132854Z.log](https://github.com/pizzaboxer/bloxstrap/files/12240547/Bloxstrap_20230802T132854Z.log)
Try read at 2023-08-02T13 : 29 : 01Z to 2023-08-02T13 : 29 : 11Z
 It's starting to open log file itself and i get an error

**Comment by pizzaboxer** [comment]
Are you sure this is the correct log? This isn't showing any error.

**Comment by pizzaboxer** [comment]
Well?
