### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zack123341** [pizzaboxer/bloxstrap#493]
![image](https://github.com/pizzaboxer/bloxstrap/assets/141202750/f5868100-018a-427f-857d-e3e6ab5575dd)

How to fix this?

**Comment by pizzaboxer** [comment]
See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

Have you modified any of Roblox's files?

**Comment by Zack123341** [comment]
No, I haven't.

**Comment by pizzaboxer** [comment]
Does this happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/switching-between-Roblox-and-Bloxstrap

**Comment by Zack123341** [comment]
Yes, it does. I tried using normal roblox launcher and still...

**Comment by pizzaboxer** [comment]
It's a Roblox problem, and not a problem with Bloxstrap, so I can't really help you. Sorry. Besides, have you tried any of the suggested solutions on the wiki page?
