### ISSUE TITLE
[IDEA2] menu buttons

### ISSUE THREAD

**Issue by T-Sean2** [pizzaboxer/bloxstrap#498]
[again i dont know if it is possible 100%]It would be cool if you could add the old roblox topbar from 2016-2019ish
![416d08bc2e6162c66780a4160e31a6cb7ff14cfd](https://github.com/pizzaboxer/bloxstrap/assets/111915451/719ffe04-2f0d-4da9-b800-1c5252129728)
This would be a cool feature

**Comment by T-Sean2** [comment]
ALSO - i know the playerlist is not possible, im just talking about the top bar

**Comment by pyhlou** [comment]
You cant

**Comment by pizzaboxer** [comment]
The top bar isn't possible either.

**Comment by Egor2011Georg** [comment]
> [again i dont know if it is possible 100%]It would be cool if you could add the old roblox topbar from 2016-2019ish
> 
> ![416d08bc2e6162c66780a4160e31a6cb7ff14cfd](https://github.com/pizzaboxer/bloxstrap/assets/111915451/719ffe04-2f0d-4da9-b800-1c5252129728)
> 
> This would be a cool feature
> 
>

**Comment by Blue-Star-Technology** [comment]
i wanted this feature too i will never be able to bring back old roblox :(
