### ISSUE TITLE
"An error occurred while starting Roblox" error when trying to install Bloxstrap

### ISSUE THREAD

**Issue by RhysRJJ** [pizzaboxer/bloxstrap#5]
So I've been trying to install Bloxstrap and I keep running into the same "An error occurred while starting Roblox" error
Roblox works fine outside of this but whenever I try to install Bloxstrap it just gives me an error

Error:
![error](https://user-images.githubusercontent.com/102009519/185923736-e5f026bd-4a38-4dc8-9c72-008069f1bb79.png)

**Comment by pizzaboxer** [comment]
Do you have an antivirus/firewall program installed? Looks like it's being prevented from communicating with the internet.

**Comment by RhysRJJ** [comment]
That seemed to have been the issue, thank you!
