### ISSUE TITLE
Search for app in the Store? Error.

### ISSUE THREAD

**Issue by GelloMello** [pizzaboxer/bloxstrap#500]
Trying to install Bloxstrap on a new Windows 11 setup. I get dropped with this upon launching the exe. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/73411588/8497c7ea-1770-451c-9ba5-2e26c3a0ee0b)
Any way to fix this?

**Comment by EasternBloxxer** [comment]
Have you installed the  .NET 6 Desktop Runtime?

**Comment by pizzaboxer** [comment]
This only happens with Bloxstrap? What version of Windows are you running? Go to Windows Settings and show me the "System > About" view.

**Comment by GelloMello** [comment]
Actually, it seems to be an issue I have gotten whenever I have tried downloading any app now. I think it's somehow Windows missing it's SmartScreen pop-up and has just decided to do this. I had to disable a setting within Windows Defender and got it installed. Apologies. However, I am running 22H2 and this was installed on the 1st.

**Comment by EasternBloxxer** [comment]
💀

**Comment by GelloMello** [comment]
ikr

**Comment by GelloMello** [comment]
Also for context, yeah I had already downloaded .NET hours prior to use a different program and yet it would give me this error.
![image](https://github.com/pizzaboxer/bloxstrap/assets/73411588/8f859373-104a-4765-8801-e4729dab63c6)
Had to do this in order to install the program.
