### ISSUE TITLE
Bloxstrap Menu program UI is broken

### ISSUE THREAD

**Issue by LordSuperSucc** [pizzaboxer/bloxstrap#501]
I don't know what exactly caused this.
I have no idea where to even begin looking into the cause of the issue.

https://github.com/pizzaboxer/bloxstrap/assets/99555982/ef4cb1b2-4588-48c7-8250-398e909035cb

**Comment by pizzaboxer** [comment]
Awesome, WPF corruption! Here, you should check this thread out: https://github.com/dotnet/wpf/issues/707

tl:dr - caused by garbage OEM software (Realtek Sonic Suite, Nahimic, etc)
