### ISSUE TITLE
What are the use cases of integrating BLoxstrap into a game? Are there any games that do so?

### ISSUE THREAD

**Issue by YousufSSyed** [pizzaboxer/bloxstrap#503]
I came across this https://github.com/pizzaboxer/bloxstrap/wiki/Integrating-Bloxstrap-functionality-into-your-game, and I wonder why a game would integrate Bloxstrap.

**Comment by 1011025m** [comment]
If game developers see fit, they can set the Discord rich presence of users who use Bloxstrap to reflect their activity in game. Sort of like how other games outside of Roblox put rich presence that reflect the players' activity in game (such as being in a match)

**Comment by pizzaboxer** [comment]
The purpose of that rich presence integration especially is to give games control over what shows on the rich presence. By default, it's entirely up to Bloxstrap, and as you may know, typically looks like this: 

![](https://user-images.githubusercontent.com/41478239/255904503-7ba35223-9115-401f-bbc1-d15e9c5fd79e.png)

However, with this, games can control the text, the images, and the timestamp that's shown. Oh, and I'm planning to add more things too.

I think that should answer your question?
