### ISSUE TITLE
Bloxstrap not starting roblox vr

### ISSUE THREAD

**Issue by spidercraft** [pizzaboxer/bloxstrap#504]
If you are using the oculus app ( not steam vr ). Starting roblox with the bloxstrap launcher won't launch your game in vr mode.

**Comment by spidercraft** [comment]
> If you've noticed, when does Oculus VR start? When the Roblox launcher opens, or when the actual game client itself opens?

it is when the actual game start

**Comment by pizzaboxer** [comment]
> it is when the actual game start

Just to make sure, you're on either Automatic or Direct3D rendering, right?

**Comment by spidercraft** [comment]
> 

should i? im on vulkan right now. Oh i just saw that you need it, sorry for bothering
