### ISSUE TITLE
"Bloxstrap will not load window on ARM64" More help required.

### ISSUE THREAD

**Issue by BokBoy** [pizzaboxer/bloxstrap#505]
"Hi there. I've been using my MacBook Air with the M2 chip for a while now. Recently, I've heard about Bloxstrap, a Roblox client that was for windows only. I decided to use it on my VM but somehow, it doesn't load with the .NET ARM64 version 6. It tells me to use .NET x64 Version 6 even though I have ARM64 version of it in.
I tried using x64 version hoping that there was something like Rosetta in Windows like Mac, to run the older Intel apps but however many times I tried, it would always start Roblox but not show the window after loading.
I can tell it does work because Task Manager says it's open (in background) and Bloxstrap Menu says that it is running but I cannot open anything because the Roblox menu is not there.

If you want a full detail.
I open Play Roblox.
Roblox loads.
Roblox finishes loading but doesn't show menu.
I quit with task manager.

Thanks in advance."
- Me

"You have to keep in mind that ever since around May, Roblox has been [designed to intentionally not work in virtual machines](https://devforum.roblox.com/t/the-application-encountered-an-unrecoverable-error/2419033/4?u=xtremeguy2256). So, this behaviour seems about right."
-Pizzaboxer

Wait, I ran Roblox on my VM before... Can somebody help me about how I got it working then and not now with Bloxstrap??
(It didn't really work well because I forgot to install drivers...)
It was after May, Just saying.

**Comment by pizzaboxer** [comment]
> Wait, I ran Roblox on my VM before... Can somebody help me about how I got it working then and not now with Bloxstrap??

Have you checked if Roblox even runs without Bloxstrap?
