### ISSUE TITLE
Ping is skYYYYYYYYYYYYYYYrocketing.

### ISSUE THREAD

**Issue by iJAJAxD** [pizzaboxer/bloxstrap#507]
Soon as installing Bloxstrap, I noticed that my ping went from 60 to freaking 400 - 500. Did a speedtest and my internet is 90 Mbps. Need a fix ASAP because Bloxstrap is freaking cool.

**Comment by pizzaboxer** [comment]
How can you tell that it's because of Bloxstrap?

**Comment by iJAJAxD** [comment]
Really sorry for making this "issue". turns out it was Roblox all this time.
