### ISSUE TITLE
Can't launch and play Bloxstrap

### ISSUE THREAD

**Issue by MrLogop** [pizzaboxer/bloxstrap#508]
Before this I can launch and play bloxstrap.But right now,when I run my bloxstrap,my bloxstrap just "Starting Roblox" and after that it dissappear and won't launch.I face this problem 2 months ago until now.

**Comment by pizzaboxer** [comment]
Have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by MrLogop** [comment]
I see but there no one solution to fix my problem that I face right now :(

**Comment by pizzaboxer** [comment]
Does it happen without Bloxstrap? If it does, then it's a Roblox issue and there isn't much else I can do to help you.

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by MrLogop** [comment]
It's happen with Bloxstrap and without Bloxstrap.

**Comment by pizzaboxer** [comment]
It's a problem with Roblox, not Bloxstrap, so there isn't much I can do to help. Sorry.
