### ISSUE TITLE
8x MSAA causes visual elements to go missing

### ISSUE THREAD

**Issue by Re17k** [pizzaboxer/bloxstrap#511]
I messed around with GUI hidden and now some parts of the game is missing even though I re-enable and disable it. Is there any toggle menu for me to do it? because cannot figure it out
example: Cutscene and gun models

**Comment by pizzaboxer** [comment]
Are you on ZIntegration?

**Comment by Re17k** [comment]
Ultimate meters and cutscene missing in Socrcerors battlegrounds

Gun models do not show during death can in Phantom forces

**Comment by pizzaboxer** [comment]
What's your antialiasing quality set to in the Bloxstrap menu?

**Comment by Re17k** [comment]
After reinstall and even toggle off feature of GUI  hidden in bloxstrap. It doesn't work, the only way to fix seems to be not using it. I would like to know how to revert it. Thanks

**Comment by Re17k** [comment]
> 

8X

**Comment by pizzaboxer** [comment]
Try setting it to default and see if it changes anything.

**Comment by Re17k** [comment]
I'm off rn. Will try it tmrw, I will let you know as soon as I get on my pc.

**Comment by Re17k** [comment]
8X seems to be the only option that breaks it. I use this opportunity to try 1X 2X and 4X but they are working fine

**Comment by Re17k** [comment]
I will stick with the 4X now ty for the help

**Comment by pizzaboxer** [comment]
No problem, I just became aware of this problem a few days ago. This option will be removed by the next version.

**Comment by NovaCraftYT** [comment]
> Ultimate meters and cutscene missing in Socrcerors battlegrounds
> 
> Gun models do not show during death can in Phantom forces

@pizzaboxer @Re17k  i used robloxs normal antianalising and it still breaks it, its not bloxstrap that breaks it, its the mesh-type that phantom forces use.

**Comment by pizzaboxer** [comment]
Even so, there were cases where we 100% confirmed that the MSAA option was causing rendering issues.

**Comment by NovaCraftYT** [comment]
@pizzaboxer will it be added backlater?

**Comment by jakaco** [comment]
it worked perfectly on amd why remove it?

**Comment by Vlad55432** [comment]
@pizzaboxer bro, why you removed must have feature and for next update removed it?
Better will be limit anti alasing to 4, there's no diff with 8 (exclude models breaking)

**Comment by EasternBloxxer** [comment]
You can always use the FFlag editor...........

**Comment by Vlad55432** [comment]
> You can always use the FFlag editor...........

I know, but remove this - meh

**Comment by Diaxbond76** [comment]
> You can always use the FFlag editor...........

But idk how to use it, It could be added back but make it unavailable for Nvidia users (im an intel user)

**Comment by lilrod1** [comment]
> You can always use the FFlag editor...........

how
