### ISSUE TITLE
stuck on "upgrading roblox" screen

### ISSUE THREAD

**Issue by ItsJustBlaze** [pizzaboxer/bloxstrap#512]
no clue why, but over the past few days ( i just now noticed ) that Bloxstrap hasn't actually been on, and I've just been playing with normal lighting. so i go to try and open Roblox through Bloxstrap, but it just gets stuck on the upgrading Roblox screen, and never loads, it doesn't even start to update, tried seeing if anybody else has had this problem, but it seems not.

![Screenshot (572)](https://github.com/pizzaboxer/bloxstrap/assets/139030582/dfde1b0b-2be4-4528-80a8-337749719f47)

**Comment by pizzaboxer** [comment]
Can I see the latest log file from %localappdata%\Bloxstrap\Logs?

**Comment by Axelanse** [comment]
> Seems like you pressed the cancel button but it didn't cancel properly. I'll take a look into that later.

managed to recreate this by closing the bootstrapper window while "configuring roblox" and then starting bloxstrap again.
