### ISSUE TITLE
[Feature suggestion] Ability to customize the Discord Rich Presence

### ISSUE THREAD

**Issue by decryptionite** [pizzaboxer/bloxstrap#513]
I think there should be a way to customize the discord presence.
Some ideas I had are either -
- Allow the user to write whatever they want in each line, with variables such as for example %player%, %place% or %client%.
- Have preset options such as, Line 1: "Playing Jailbreak" Line 2: "Logged in as %player% / ExampleUsername.

<hr />

Something for reference is the modified client for Minecraft, Meteor Client allowing you to set customizations:
![image](https://github.com/pizzaboxer/bloxstrap/assets/71681649/dea69998-4af2-4bce-b460-d50b9023eaf1)
![image](https://github.com/pizzaboxer/bloxstrap/assets/71681649/f86474ca-7884-42e0-80bc-2aea476d9511)

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Integrating-Bloxstrap-functionality-into-your-game
