### ISSUE TITLE
ingame avatar preview issues

### ISSUE THREAD

**Issue by tttMediumkey** [pizzaboxer/bloxstrap#514]
![image](https://github.com/pizzaboxer/bloxstrap/assets/64014071/79b00051-62bc-4f0a-bcb2-07386e785b92)
i am not entirely sure if this is a bloxstrap issue but games like catalog avatar creator or any game that uses a avatar previewer seems to be not loading at all.

**Comment by pizzaboxer** [comment]
What's your antialiasing quality set to? If it's set to 8x, change it to either be 4x or Automatic.

**Comment by tttMediumkey** [comment]
yeah that fixed it.
