### ISSUE TITLE
Getting a "decryption operation failed" error? See this!

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#515]
I've been getting this error from a handful of people over the past few months, and I've had some real difficulty figuring out what's causing it, because it's not actually a bug with Bloxstrap, but I believe it to actually be a bug with Microsoft .NET Core.

Reason why I think that is because whenever Bloxstrap tries to download a large file (like RobloxApp.zip), at some point through the download .NET can't decrypt the HTTPS data and so that error happens. In fact, Bloxstrap retries the download five times before giving up and throwing that error, so if you're getting it then you're especially screwed.

Because it only happens for like 0.005% of all users, and with there being no way to reproduce it whatsoever, I need contact with people having this issue so I can try a bunch of stuff and figure out what's going on, and maybe make a workaround for it.

I've made this post so that I can gather round as many people as I can that are having issue. So if you're getting this error and you're willing to help out, just respond here.

**Comment by WaviestBalloon** [comment]
> Reason why I think that is because whenever Bloxstrap tries to download a large file (like RobloxApp.zip), at some point through the download .NET can't decrypt the HTTPS data and so that error happens.

Use curl as a fallback. 
![9702-hestrollingyouknow](https://github.com/pizzaboxer/bloxstrap/assets/31796727/c159e9f2-c6c7-4ef1-b6ef-172aedd6b19b)

**Comment by Jpssz** [comment]
yeah i am having the same problem

**Comment by pizzaboxer** [comment]
> yeah i am having the same problem

Here, can you try out this test program and tell me what it reports at the end? Press 'Y' when it asks you to use compression.

https://files.pizzaboxer.xyz/RobloxDownloadDebugger.exe

**Comment by Jpssz** [comment]
> > yeah i am having the same problem
> 
> Here, can you try out this test program and tell me what it reports at the end? Press 'Y' when it asks you to use compression.
> 
> https://files.pizzaboxer.xyz/RobloxDownloadDebugger.exe

Hey i think i actually found a solution. What i did was install Bloxstrap without doing any modifications. After that, i opened the Menu and made the modifications i wanted and it worked fine!

**Comment by pizzaboxer** [comment]
> It looks like by doing modifications, it wont install. If you install without any modifications and after that do the modifications, it will work fine.

I can assure you doing that has absolutely zero correlation to fixing it.

**Comment by Jpssz** [comment]
I mean, atleast it works now

**Comment by Osaynt** [comment]
> > > yeah i am having the same problem
> > 
> > 
> > Here, can you try out this test program and tell me what it reports at the end? Press 'Y' when it asks you to use compression.
> > https://files.pizzaboxer.xyz/RobloxDownloadDebugger.exe
> 
> Hey i think i actually found a solution. What i did was install Bloxstrap without doing any modifications. After that, i opened the Menu and made the modifications i wanted and it worked fine!
> 
> It looks like by doing modifications, it wont install. If you install without any modifications and after that do the modifications, it will work fine.

i was having the same issue and tried the same thing u did and it works now, thanks.
