### ISSUE TITLE
Integration with programs

### ISSUE THREAD

**Issue by Lucas559-noob** [pizzaboxer/bloxstrap#518]
Is it possible to integrate with programs or scripts(like autohotkey)? And when Roblox closes, they close too.

If yes, how do we do that?

**Comment by pizzaboxer** [comment]
Yes, that's exactly what the custom integrations section is for. It's at the bottom of the Integrations tab in the Bloxstrap Menu. Keep in mind that if you're using scripts, you have to provide the location of the executable that's supposed to run it. For AutoHotKey, that would be in `C:\Program Files\AutoHotkey\UX\AutoHotkeyUX.exe`. The path to the script would typically be the only launch arg provided, wrapped in quotes.
