### ISSUE TITLE
(SUGGESTION) Reset Bind

### ISSUE THREAD

**Issue by tpopbpmg** [pizzaboxer/bloxstrap#523]
basically if you press "K" for example, your character automatically resets (not sure if this is possible but it would be amazing)

**Comment by 1-1-8-7** [comment]
Not possible, sorry.

**Comment by JustConey15** [comment]
i don't believe this is possible, unless you create a macro specifically for this, for example if you press K you can make it so it presses escape R enter and instantly kills you
