### ISSUE TITLE
Bloxstrap doesn't let me join roblox

### ISSUE THREAD

**Issue by gobbah** [pizzaboxer/bloxstrap#526]
basically when i try joining any
roblox game a small popup shows up, what do i do to fix it?
![image](https://github.com/pizzaboxer/bloxstrap/assets/141811094/154c2008-50cc-487b-8219-747a9bc24857)

**Comment by pizzaboxer** [comment]
Oh, you're enrolled in the Mac ARM channel. I kind of forgot that existed. Anyway, you can stop this from happening by opening the menu, going to the Behaviour tab, setting your channel to LIVE, and setting the channel change action to "Never change".

**Comment by gobbah** [comment]
yeah that worked thank you!

**Comment by lokzz** [comment]
why does this not tell the user that the channel was changed back to LIVE?

**Comment by pizzaboxer** [comment]
> why does this not tell the user that the channel was changed back to LIVE?

Does it need to? If you're getting this error in the first place then you probably didn't even know that your channel was changed.
