### ISSUE TITLE
2015 menu gone..?

### ISSUE THREAD

**Issue by sha4owz** [pizzaboxer/bloxstrap#528]
WHAT HAPPENED. ITS GONE

**Comment by pizzaboxer** [comment]
Set these flags to `False` in the flag editor:

```
FFlagEnableV3MenuABTest3
FFlagEnableMenuControlsABTest
FFlagEnableMenuModernizationABTest
FFlagEnableMenuModernizationABTest2
```

**Comment by Prkbt9** [comment]
so talk about true the reshade overlay not working please reshade back roblox please pizzaboxer

**Comment by obvRedwolf** [comment]
> so talk about true the reshade overlay not working please reshade back roblox please pizzaboxer

this will not happen due to byfron being scummy and not doing its job right

**Comment by pizzaboxer** [comment]
> this will not happen due to byfron being scummy and not doing its job right

Actually, it's doing its job very well by blocking ReShade.
