### ISSUE TITLE
SteamVR opens when playing any game

### ISSUE THREAD

**Issue by octoqi** [pizzaboxer/bloxstrap#53]
Only just started happening today; when trying to play any game with Bloxstrap, the SteamVR status window will open along with it

**Comment by pizzaboxer** [comment]
Does this happen without Bloxstrap too? I've had a friend who's been experiencing this same issue for a long time, before I even made Bloxstrap.

**Comment by octoqi** [comment]
After uninstalling Bloxstrap and trying to use the basic Roblox Launcher, the issue happens there too. Only at specific points at night for some reason
