### ISSUE TITLE
Cant open roblox

### ISSUE THREAD

**Issue by krxs12** [pizzaboxer/bloxstrap#530]
i cant open roblox it doesnt show up the roblox after the instalation

**Comment by pizzaboxer** [comment]
Does it show without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
