### ISSUE TITLE
Text using custom fonts show up small in chat.

### ISSUE THREAD

**Issue by TheMan8116** [pizzaboxer/bloxstrap#531]
I used comic sans and the font is half the size.
![font issue](https://github.com/pizzaboxer/bloxstrap/assets/137003266/111052c8-97d1-46a6-9912-be3c12fd8b06)

**Comment by pizzaboxer** [comment]
The original font that would've been used for the chat would've been a little bigger. There isn't really any way to correct the sizing when replacing the fonts, so you'll kind of just have to stick with it, disable it, or somehow find a larger font. Sorry.

**Comment by TheMan8116** [comment]
alright, thanks!
