### ISSUE TITLE
random crashing for no reason at all

### ISSUE THREAD

**Issue by PurpleNeoKeith** [pizzaboxer/bloxstrap#532]
each time i boot into a game it crashs after a few seconds of launch ive tried changing my graphics thing but it hasnt worked

**Comment by pizzaboxer** [comment]
Have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by PurpleNeoKeith** [comment]
hm i have been using vulken alot
so maybe thats probably why

**Comment by PurpleNeoKeith** [comment]
it seems to be running fine no crashs yet
