### ISSUE TITLE
fastflag not working

### ISSUE THREAD

**Issue by Malletspoopy** [pizzaboxer/bloxstrap#533]
![Screenshot (20)](https://github.com/pizzaboxer/bloxstrap/assets/141880431/06822c9a-093b-4b5d-b5aa-89a42a9513e7)

so i play roblox an i want to remove tall grass
![download](https://github.com/pizzaboxer/bloxstrap/assets/141880431/87895b39-b2b3-4ddf-8f46-648fc69c02a2)
 
btw the codes were right and they work but not for me idk why help

**Comment by Malletspoopy** [comment]
dm me in discord at LeTroller 
this is not an troll this is my fr username

**Comment by pizzaboxer** [comment]
Did you not try setting the distance flags to 0?

**Comment by Malletspoopy** [comment]
There still grass but it's not covering the entire map because of rendered distance I think for grass

**Comment by Malletspoopy** [comment]
![Screenshot (21)](https://github.com/pizzaboxer/bloxstrap/assets/141880431/89d3a6f6-4095-4b06-b540-9ef8ba393f46)

**Comment by pizzaboxer** [comment]
I guess it might be worth double checking to see if the flags are being applied. Add this, join a game. tell me if anything shows in the top right:

Flag name: `FStringDebugShowFlagState`
Flag value: `FIntFRMMaxGrassDistance`

**Comment by Malletspoopy** [comment]
FIntFRMMaxGrassDistance= C++

**Comment by pizzaboxer** [comment]
The flag is indeed being applied, it's not a Bloxstrap problem. Anyway, you can delete the flag for `FStringDebugShowFlagState` now.

**Comment by Malletspoopy** [comment]
ok
