### ISSUE TITLE
Error I get when opening multiple instances

### ISSUE THREAD

**Issue by 7upman2017** [pizzaboxer/bloxstrap#537]
System.IO.IOException: The process cannot access the file 'C:\Users\SECRET\AppData\Local\Bloxstrap\Versions\version-2c1290f04f784d9a\content\fonts\TwemojiMozilla.ttf' because it is being used by another process.

**Comment by pizzaboxer** [comment]
Where's the log file?

**Comment by 7upman2017** [comment]
Hello! I did not know where the log file was when I experienced the error, but it seems to be fixed now!
