### ISSUE TITLE
Join link from RPC launches game with wrong account

### ISSUE THREAD

**Issue by purplux** [pizzaboxer/bloxstrap#54]
Tried to join my friend in a game, and it launched one of my alt accounts instead of my main account. Unsure how this happened

**Comment by pizzaboxer** [comment]
What Roblox account are you logged into in your default browser?

**Comment by purplux** [comment]
Sorry for the late response, logged in with my main account

**Comment by pizzaboxer** [comment]
And Discord opens your default web browser when you click the join button?

**Comment by purplux** [comment]
Yep

**Comment by pizzaboxer** [comment]
What Roblox account are you logged into in the Desktop app?
