### ISSUE TITLE
A setting/do not show again button for this prompt

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#542]
Annoying sometimes when Roblox takes a while to close ¯\_(ツ)_/¯
![image](https://github.com/pizzaboxer/bloxstrap/assets/54174182/e25bea8e-9781-4271-be46-df9e76c2b32d)

**Comment by pizzaboxer** [comment]
Yeah, I might be able to find a way around it.

**Comment by pizzaboxer** [comment]
hi i changed my mind about adding this lol
