### ISSUE TITLE
Automatic uploading of exception information

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#544]
Despite my best efforts to make it straightforward as I can, I think the frequent mishandling of exception reports warrants this being added, as it would help make my life as well as the user's life so much easier.

Like, seriously. The exception dialog says "please send a copy of the log file", along with a button at the bottom that says "Locate log file". You can't miss it. And yet most of the time, when people report an exception, they don't send me a log file. In some cases, I've had people **asking me** how to find the log file. And by that time it's too late as they likely don't encounter the exception anymore. If there's any way to help improve the reporting experience, I think this is the way to go.

Anyway, the simplest thing to do would be to just upload the log file online to somewhere that I can access it. Log files already have user profile paths stripped out, so anonymization there is great. Though, some other identifiable information (e.g. rich presence registration) will also need to be stripped out. I might remove those entirely anyway.

Minidumps are another option, and are what I would rather prefer, though I don't even know if they're possible in C#, and the chances of them containing potentially identifiable information that I can't strip out would be likely. I'll see how feasable this is though.

It should be worth mentioning that I won't make this fully automatic. I'll make it kind of like Windows error reporting, where it will ask you if you want to upload it online. Good to at least have the user in the know.

**Comment by WaviestBalloon** [comment]
Basically telemetry? Do you think you will ever properly implement telemetry and have it opt-out by default?

**Comment by pizzaboxer** [comment]
> It should be worth mentioning that I won't make this fully automatic. I'll make it kind of like Windows error reporting, where it will ask you if you want to upload it online. Good to at least have the user in the know.

**Comment by WaviestBalloon** [comment]
> make it into a option for automatic error reporting

pizzaboxer stated it would be like Windows error reporting on if you want to send it or not.
![article-2531601-1A5B89D300000578-768_634x397](https://github.com/pizzaboxer/bloxstrap/assets/31796727/1ae49ee0-ef41-4d61-b381-6151ad486685)

**Comment by Cristiano100** [comment]
Firebase's free tier comes with ["Crashlytics"](https://firebase.google.com/products/crashlytics/)
