### ISSUE TITLE
roblox not opening

### ISSUE THREAD

**Issue by chalk7495** [pizzaboxer/bloxstrap#545]
https://drive.google.com/file/d/1N7KYTo_XtDMoEB_aG_vb8bgQmMFL1mtP/view?usp=sharing

this is log file

**Comment by pizzaboxer** [comment]
This is a Hyperion error, not a Bloxstrap error. The support website the error talks about is Roblox's support website. See https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.
