### ISSUE TITLE
roblox won't launch, no errors

### ISSUE THREAD

**Issue by coolpeter98** [pizzaboxer/bloxstrap#547]
whenever i launch roblox using Bloxstrap, it refuses to launch; using the default roblox launcher fixes it
restarting my PC fixes it, however it only fixes it on 1st launch

https://github.com/pizzaboxer/bloxstrap/assets/103730479/b4081839-68ed-4722-a269-b152b8f3c801
[Bloxstrap_20230815T135629Z.log](https://github.com/pizzaboxer/bloxstrap/files/12344887/Bloxstrap_20230815T135629Z.log)
[My settings](https://github.com/pizzaboxer/bloxstrap/files/12344892/Settings.txt)

**Comment by pizzaboxer** [comment]
Can I see Roblox's latest log file from %localappdata%\Roblox\logs?

**Comment by coolpeter98** [comment]
> Can I see Roblox's latest log file from %localappdata%\Roblox\logs?

[0.589.0.5890596_20230815T144912Z_Player_B6156_last.log](https://github.com/pizzaboxer/bloxstrap/files/12345299/0.589.0.5890596_20230815T144912Z_Player_B6156_last.log)

**Comment by pizzaboxer** [comment]
Oh, it's just completely stalled. That's great. Yeah, I don''t know how to say this, but Roblox kind of just does that sometimes. I'm not sure what specifically fixes this, but I've noticed it mostly happening when tools like RTSS/MSI Afterburner are open.

Just a few suggestions, does undoing the "Disable desktop app" option change anything? What about forcing a fresh Roblox reinstall? The option for that one is in the behaviour tab.

**Comment by pizzaboxer** [comment]
One last thing, can I see the FastFlags you have set? Just show me a picture of the FastFlag editor.

**Comment by pizzaboxer** [comment]
I said show me a picture of the editor.

**Comment by coolpeter98** [comment]
> I said show me a picture of the editor.


https://github.com/pizzaboxer/bloxstrap/assets/103730479/70a21fbc-6a3b-4f34-a5e3-2e99e5844d33

**Comment by coolpeter98** [comment]
> Delete all of those flags (ctrl+a), save, try and join a game, and see if it works.

it worked, thank you so much :D

**Comment by pizzaboxer** [comment]
Word of warning, you probably shouldn't use the RCO flag list.
