### ISSUE TITLE
No, just please help me, i tried playing combat warriors, but it keeps crashing, like force crash, not even southwest florida beta!

### ISSUE THREAD

**Issue by USERNAMEDELETED1** [pizzaboxer/bloxstrap#549]
just help me please, i cant play like this, its really raging._

**Comment by pizzaboxer** [comment]
Have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
