### ISSUE TITLE
RPC unable to be launched

### ISSUE THREAD

**Issue by ForgottenDebt** [pizzaboxer/bloxstrap#55]
RPC is turned on [from the screenshot below]
![image](https://user-images.githubusercontent.com/120201399/206748485-759d52c3-49f1-4795-aa2d-41d580b4107c.png)

Game is being played with RPC on
![image](https://user-images.githubusercontent.com/120201399/206749296-b4475f16-aefb-4721-af54-5d874bef85d4.png)

**Comment by ForgottenDebt** [comment]
There's no join button to begin with 💀

**Comment by pizzaboxer** [comment]
Yep, was definitely able to see that before you edited your post...
I can think of two causes to this, but first I just want to check one of them. Are you okay with privately sending me your latest Roblox log file in `%localappdata%\Roblox\logs`?

**Comment by ForgottenDebt** [comment]
Yes, I'm fine with sending you my latest log file, Bloxstrap is also running in the background

**Comment by ForgottenDebt** [comment]
'bout to go to sleep so expect a very late response

**Comment by pizzaboxer** [comment]
DM me via Discord - pizzaboxer#7142

**Comment by Nebelous555** [comment]
I have the same issue, Mind helping me out? (the same happens as it did for ForgottenDebt)
it's late so I'll prob respond tmr.
![image](https://user-images.githubusercontent.com/120223163/206800414-3c99b71c-9f89-4739-887f-3a92f78ef29d.png)

**Comment by pizzaboxer** [comment]
I'll help you once I've narrowed down the cause with @ForgottenDebt, sorry to keep you waiting.

**Comment by Nebelous555** [comment]
> I'll help you once I've narrowed down the cause with @ForgottenDebt, sorry to keep you waiting.

All Good, keep up the good work!

**Comment by ForgottenDebt** [comment]
Accept my FR as i'm unable to message you

**Comment by Nebelous555** [comment]
Same, Mine's Neb#1800
I think he will respond later cuz timezones @ForgottenDebt
