### ISSUE TITLE
In the latest roblox/bloxstrap build, the menu v2 from 2020 doesn't work

### ISSUE THREAD

**Issue by Kluts123** [pizzaboxer/bloxstrap#550]
There seems to be a problem where the V2 menu dosent work anymore, same thing happened with V3.

**Comment by pizzaboxer** [comment]
Works for me. You should probably see https://github.com/pizzaboxer/bloxstrap/wiki/Selected-escape-menu-version-does-not-work.

**Comment by Kluts123** [comment]
> Works for me. You should probably see https://github.com/pizzaboxer/bloxstrap/wiki/Selected-escape-menu-version-does-not-work.

Where could I find FastFlag Editor

**Comment by pizzaboxer** [comment]
You open the Bloxstrap menu and go to the FastFlags tab.

**Comment by Kluts123** [comment]
oh nvm my version was outdated, i updated it. thx
