### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by berberrrr** [pizzaboxer/bloxstrap#552]
It crashes after 3 minutes of opening it, help.

**Comment by pizzaboxer** [comment]
Have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
