### ISSUE TITLE
low quality textures in other rendering modes and pixellated auras in the opengl rendering mode

### ISSUE THREAD

**Issue by goofus1** [pizzaboxer/bloxstrap#553]
the low quality textures only happen in other rendering modes like automatic,vulkcan,etc except for opengl
but opengl is sometimes very buggy due to making auras pixellated plus making you cant chat at all when the chat bar disappears
the chatbar disappearing only happens when i switch to applications like discord or etc

**Comment by pizzaboxer** [comment]
What's your antialiasing quality set to?

**Comment by goofus1** [comment]
2x msaa
i think

**Comment by goofus1** [comment]
let me go check again

**Comment by goofus1** [comment]
yup its 2x msaa

**Comment by goofus1** [comment]
hold on brb for like 5 minutes

**Comment by goofus1** [comment]
back
you uh there pizza?

**Comment by pizzaboxer** [comment]
Oh, sorry. What other flags do you have set? Show me a picture of the flag editor, with preset flags shown.

**Comment by goofus1** [comment]
alright

**Comment by goofus1** [comment]
give me a minute or so hold on

**Comment by goofus1** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142567556/c6d51d0f-40a6-442d-891b-184e1183c04b)

**Comment by goofus1** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142567556/3dabd660-3444-4bc7-83a1-d77a8593f0fb)

**Comment by goofus1** [comment]
i mean you could maybe add in a low quality textures fix thingy into bloxstrap right?

**Comment by pizzaboxer** [comment]
A picture of the flag editor.

**Comment by goofus1** [comment]
oh wait

**Comment by goofus1** [comment]
hold on

**Comment by goofus1** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142567556/48a4f753-42e4-4167-8068-a4b73c8c3463)

**Comment by pizzaboxer** [comment]
Have you checked if this happens without Bloxstrap too? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by goofus1** [comment]
yeah if i dont use bloxstrap it happens alot like almost everytime i play roblox

**Comment by goofus1** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142567556/a4b394a3-d1ab-4456-841b-c6a555d1d4b4)
without opengl it will look like this

**Comment by goofus1** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142567556/aed3a7de-ae7f-43e7-b188-b178c5032d01)

**Comment by goofus1** [comment]
and now with opengl
![image](https://github.com/pizzaboxer/bloxstrap/assets/142567556/ff60b0b9-8374-4d5a-a783-53a6dea3541c)

**Comment by goofus1** [comment]
the other screenshot with the low quality textures was taken like 5 hours ago i think

**Comment by pizzaboxer** [comment]
If it happens without Bloxstrap too, then it's a problem with Roblox. There isn't really anything I can do to fix that. Sorry.

**Comment by goofus1** [comment]
alright
