### ISSUE TITLE
Roblox character dont display in GUI, and while pressing WASD playing error sound.

### ISSUE THREAD

**Issue by RipliNoir** [pizzaboxer/bloxstrap#554]

**Comment by pizzaboxer** [comment]
Roblox input issue. Alt-tab to another program and focus the Roblox window again. Has nothing to do with Bloxstrap.

**Comment by RipliNoir** [comment]
Thanks

пт, 18 авг. 2023 г., 18:48 pizzaboxer ***@***.***>:

**Comment by pizzaboxer** [comment]
> Though, what do you mean your character doesn't display in the GUI?

?

**Comment by RipliNoir** [comment]
I mean 3d GUI. But i dont know how, but this problem is gone. Sorry for
disturbing.

пт, 18 авг. 2023 г., 18:57 pizzaboxer ***@***.***>:
