### ISSUE TITLE
Roblox Textures not loading when forcing the Anti-Alias to any value

### ISSUE THREAD

**Issue by Clyde-Timonera** [pizzaboxer/bloxstrap#557]
![image](https://github.com/pizzaboxer/bloxstrap/assets/78290310/e71a4a55-5a0e-470a-81dc-aea35279fca9)
Weirdly the textures that are bigger than a tiny square don't load, the material textures load fine except for minor things like Profile Icons, Icons bigger than squares and some specific icons too (Affects all games)

**Comment by Clyde-Timonera** [comment]
Weirdly it also affects some specific icons too, and I am sure my internet is fine since it runs at 600 mbps.
![image](https://github.com/pizzaboxer/bloxstrap/assets/78290310/2ac3b2b2-39b7-4a95-bde4-823572506cee)

**Comment by pizzaboxer** [comment]
>  Weirdly the textures that are bigger than a tiny square don't load, the material textures load fine except for minor things like Profile Icons, Icons bigger than squares and some specific icons too (Affects all games)

Keep it on Automatic. There are some known issues with it right now.
