### ISSUE TITLE
Cant use custom skyboxes because of bloxstrap file override.

### ISSUE THREAD

**Issue by genstarhimms** [pizzaboxer/bloxstrap#559]
bloxstrap overrides any sky_512.tex in the client files taking away the ability to have a custom skybox. Is there a fix or work around ?

**Comment by OrphanObliterator** [comment]
Are you sure? I'm able to have a custom skybox with no problems.

**Comment by pizzaboxer** [comment]
Where exactly are you placing the file?

**Comment by genstarhimms** [comment]
im placing my 6 sky512.tex files them in the sky file in my roblox client files, I've talked to 2 of my friends who use bloxstrap and they both haven't been able to figure out skyboxes with bloxstrap.
![skyboxbloxstrap](https://github.com/pizzaboxer/bloxstrap/assets/142708121/e0137a6a-235e-4cb3-ad7b-e2fdf3c7eb50)

**Comment by GoingCrazyDude** [comment]
The mods feature:

**Comment by pizzaboxer** [comment]
> im placing my 6 sky512.tex files them in the sky file in my roblox client files,

https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

**Comment by genstarhimms** [comment]
@GoingCrazyDude @pizzaboxer you guys are goats, thank you gentlemen! 🫶🏼

**Comment by Jes-debug** [comment]
hello i did the modifications thing correctly but my sky box is still default
