### ISSUE TITLE
Game-specific mods

### ISSUE THREAD

**Issue by GitHubUser3721** [pizzaboxer/bloxstrap#56]
I saw somebody suggested this a while back and I decided I would suggest it again because it seems to have been forgotten and it's a pretty interesting idea!

The idea is that in the preference menu you could set a game's Place ID to load a specific mod folder instead of the universal one.

**Comment by BeyondThe5D** [comment]
I was the one who originally suggested this but yeah I think it's a good idea

**Comment by pizzaboxer** [comment]
The only problem is that you wouldn't be able to dynamically change mods while the game client is running.

**Comment by BeyondThe5D** [comment]
> The only problem is that you wouldn't be able to dynamically change mods while the game client is running.

I see, because of that will this feature not be added?

**Comment by pizzaboxer** [comment]
Yes, sorry.
