### ISSUE TITLE
bloxtrap not really Force roblox reinstalling

### ISSUE THREAD

**Issue by Jayden18769** [pizzaboxer/bloxstrap#560]
when is start the game i notice that my fps are not unlocked and the graphics quality 10 is and i have to manually reinstall bloxtrap

**Comment by pizzaboxer** [comment]
Have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
