### ISSUE TITLE
add hotkeys for performance stats

### ISSUE THREAD

**Issue by jerichomlg** [pizzaboxer/bloxstrap#561]
Just like how the graphics setting has it's own hotkey, make one for it. Something like how when you press SHIFT + F5, a menu opens up showing your fps, ping and whatnot, why not make a hotkey for performance stats? that little menu that shows you your ping, gpu, cpu, network & memory usage. I would appreciate it a lot

**Comment by OrphanObliterator** [comment]
> Just like how the graphics setting has it's own hotkey, make one for it. Something like how when you press SHIFT + F5, a menu opens up showing your fps, ping and whatnot, why not make a hotkey for performance stats? that little menu that shows you your ping, gpu, cpu, network & memory usage. I would appreciate it a lot

Not possible, sorry. Although, if you really want, you can enable it, and then with GUI Hiding, you can press CTRL + SHIFT + G to disable CoreGuis. This will toggle the performance stats on and off. although it also toggles things like the menu and topbar. If you're okay with that, then use it.

**Comment by pizzaboxer** [comment]
^
