### ISSUE TITLE
i keep getting error code 279 or failed to join connected server. can anyone help me?

### ISSUE THREAD

**Issue by Nikoman55** [pizzaboxer/bloxstrap#562]
help 
 idk how to fix this
![sadsadsadsadsadsa](https://github.com/pizzaboxer/bloxstrap/assets/142732016/d12da17a-6b0b-48fe-a337-0462024030d1)

**Comment by pizzaboxer** [comment]
(resolved over discord)

**Comment by Pakashi9** [comment]
And how we can get the link of the discord server ???
