### ISSUE TITLE
UI 3d assets not loading in

### ISSUE THREAD

**Issue by kakh444** [pizzaboxer/bloxstrap#564]
was playing project delta and wanted to check out my appearance but my avatar didnt load and the other items when i clicked inspect on them. it also happens in every other game that has 3d items in the UI

**Comment by GoingCrazyDude** [comment]
Do you have anti aliasing on?

**Comment by kakh444** [comment]
> Do you have anti aliasing on?

yea i had 8x msaa, i just tested it out with 4x msaa and now it seems to work

**Comment by kakh444** [comment]
well a small thing to pay a big price for but i guess i gotta stick with the 4xmsaa now
