### ISSUE TITLE
bloxstrap not letting me do anything AT ALL

### ISSUE THREAD

**Issue by ej2kwick** [pizzaboxer/bloxstrap#565]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142774639/0ef536a3-fe00-48e9-b38d-fd57dd993ecc)

**Comment by pizzaboxer** [comment]
Send the log file.

**Comment by ej2kwick** [comment]
[Bloxstrap_20230821T184436Z.log](https://github.com/pizzaboxer/bloxstrap/files/12399735/Bloxstrap_20230821T184436Z.log)

**Comment by pizzaboxer** [comment]
Why'd you install Bloxstrap to your Downloads folder?

**Comment by ej2kwick** [comment]
cuz

**Comment by ej2kwick** [comment]
was that a bad idea?

**Comment by pizzaboxer** [comment]
Uninstall it and reinstall it **without changing your install location**. You'll have to clear out your logs folder first.

**Comment by ej2kwick** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142774639/016a2e93-ebf5-4472-bf89-b5e72c24270f)

**Comment by WaviestBalloon** [comment]
> ![image](https://user-images.githubusercontent.com/142774639/262204890-016a2e93-ebf5-4472-bf89-b5e72c24270f.png)

Look in task manager and kill any instances of Bloxstrap running

**Comment by ej2kwick** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142774639/c2ea4e9e-b05f-4935-9cbe-52ef1a2cecb6)

**Comment by pizzaboxer** [comment]
Click "More details" and look through the process list

**Comment by ej2kwick** [comment]
alright, perfect. thanks!

**Comment by WaviestBalloon** [comment]
At least you didn't install it on a FTP server
