### ISSUE TITLE
can't start bloxstrap

### ISSUE THREAD

**Issue by AnkariAsami** [pizzaboxer/bloxstrap#567]
https://github.com/pizzaboxer/bloxstrap/assets/138742094/bf6ea8a2-599c-4c59-a30a-b4117c314605

**Comment by AnkariAsami** [comment]
even those wait 2-3 minutes nothing happen i through win have problem so reinstall but that sane issue

**Comment by pizzaboxer** [comment]
Have you seen https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by AnkariAsami** [comment]
not yet :D

**Comment by AnkariAsami** [comment]
man i don't get it? how to fix???

**Comment by AnkariAsami** [comment]
yeah but i dont understand how to fix?

**Comment by pizzaboxer** [comment]
> Keep the following in mind: This page is not a definitive guide, but it merely outlines everything that I know. From what I have personally seen, these were the most common solutions that worked. It's possible that these solutions may not apply to you, in which case, I can't really help.

> Is Roblox crashing instantly on startup, but the problem of running software doesn't seem to apply to you? Well, maybe this could be your fix. [A lot of people have noticed](https://devforum.roblox.com/t/resolved-roblox-instantly-crashes-on-launch/2335822/6?u=xtremeguy2256) that clearing the Windows thumbnail cache turns out to fix any Hyperion related crashes. You can do this by opening Windows Disk Clean-up (cleanmgr.exe), choosing your Windows drive, and opting to clean up thumbnails.

> Software running on your computer is conflicting with Roblox
> Known cases
> MacType - this can be avoided by adding RobloxPlayerBeta.exe to MacType's blacklist. (sources: [1](https://github.com/pizzaboxer/bloxstrap/assets/41478239/7d96250c-a365-4faf-b623-b8393be5319f), [2](https://github.com/pizzaboxer/bloxstrap/assets/41478239/462738e2-bcc0-4616-8787-3e5539b05f95))
 > GPU tweaking tools, specifically RTSS or MSI Afterburner - this can be avoided by making sure they are not active when launching Roblox. They can be reopened after Roblox launches.
 > Magic Borderless - [(source)](https://github.com/pizzaboxer/bloxstrap/issues/449#issuecomment-1652463552)

**Comment by IDDQD1337** [comment]
Most likely the ZIntegration channel started crashing, try changing the channel to Live or ZCanary, it helped me

**Comment by LolloDev5123** [comment]
Same issue, no overclocking program, running on an HP Omen, closed all OMEN related gaming services. Might be Xbox Game Bar or GeForce Experience doing stuff like magic borderless.

**Comment by pizzaboxer** [comment]
> Might be Xbox Game Bar or GeForce Experience doing stuff like magic borderless.

I kind of doubt it, since the reason Magic Borderless gets flagged is because it likely isn't code signed. Those services you describe should be 100% fine.

**Comment by LolloDev5123** [comment]
![immagine](https://github.com/pizzaboxer/bloxstrap/assets/26120324/6a00fc9c-2b45-43b3-9fc6-e736787a02f7)
![immagine](https://github.com/pizzaboxer/bloxstrap/assets/26120324/4e39cb0d-a4b6-45d1-9264-a36bf777290b)
![immagine](https://github.com/pizzaboxer/bloxstrap/assets/26120324/ea2a72ab-c010-4d84-9d61-d5541a92078e)
![immagine](https://github.com/pizzaboxer/bloxstrap/assets/26120324/cd30f416-c36c-4a7b-9c2d-4ab6eb56c890)
![immagine](https://github.com/pizzaboxer/bloxstrap/assets/26120324/49bc1cd4-029b-4c05-96e8-bb68714a1fef)

These are all of the services running after restarting my PC. I'll try killing OMEN System Optimizer and see if that does anything again

**Comment by AnkariAsami** [comment]
just create dump file

**Comment by AnkariAsami** [comment]
bloxsrrap can't automatic create dumpfile

**Comment by AnkariAsami** [comment]
not the bloxstrap fault

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
