### ISSUE TITLE
Bloxstrap suddenly stopped working

### ISSUE THREAD

**Issue by salemlovesconstants** [pizzaboxer/bloxstrap#57]
My bloxstrap client suddenly stopped working, I couldn't launch the game neither the configuration executable. I couldn't even uninstall it, so I had to use BCuninstaller to force remove it. Now I cannot even install bloxstrap - the installation file launches correctly, but once I press Install the window disappears and nothing happens.

**Comment by pizzaboxer** [comment]
I'm wondering if there's some misconfigured setting that's causing Bloxstrap to crash. Can you check if there's still a settings file at `%localappdata%\Bloxstrap\Settings.json`, and a registry key located at `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap`?

**Comment by salemlovesconstants** [comment]
Hey, just got on my PC and the issue is gone. I think what happened
yesterday, is I simply exceeded githubs api rate limit as I was launching
multiple clients at once to qa test a game. Sorry for the hassle, this
issue was entirely on my end.

pon., 19 gru 2022, 10:14 użytkownik pizzaboxer ***@***.***>
napisał:

**Comment by pizzaboxer** [comment]
Oh... that actually kind of makes sense now that I think about it. I should handle what happens in case the update check fails. Thanks for reporting!
