### ISSUE TITLE
Bootstrap loading incredibly slow, outta nowhere.

### ISSUE THREAD

**Issue by WertyTT4** [pizzaboxer/bloxstrap#570]
Just this morning, Bloxstrap just started being slow for no reason, whenever i press the play button, it usually takes 30 - 3 minutes to actually play a game.  This just started happening, i got no idea why, I  deleted bloxstrap mulitple times, but that did nothing lol

**Comment by pizzaboxer** [comment]
Sounds like it's having difficulty trying to connect to a deployment server. It tries to connect to three of them and has a 30-second timeout period for each of them. Send me the latest log from `%localappdata%\Bloxstrap\Logs`.

**Comment by WertyTT4** [comment]
Weirdly enough, the problem went away, i really dont understand why that kept happening, but the problem seems like its gone, and bloxstrap is working normally now.

**Comment by WertyTT4** [comment]
Weirdly enough, the problem went away, i really dont understand why that kept happening, but the problem seems like its gone, and bloxstrap is working normally now.

**Comment by pizzaboxer** [comment]
Likely was a bad internet connection

**Comment by WertyTT4** [comment]
I tried Mobile hotspot, and resetting my connection, so maybe not or maybe yes
