### ISSUE TITLE
fps capped at 80 in game despite being set to 240 in launcher

### ISSUE THREAD

**Issue by GoldKing7** [pizzaboxer/bloxstrap#571]
Any number I set to above 80 will get set to 80 only on roblox, the number in the launcher doesnt get set to 80, its just roblox which is weird.

**Comment by NovaCraftYT** [comment]
> Are you on a laptop?

@GoldKing7 is right, im on pc and the fps cant go upwards more than 80 fps

**Comment by pizzaboxer** [comment]
And you're sure there's no application you have installed that could be limiting it?

**Comment by NovaCraftYT** [comment]
> And you're sure there's no application you have installed that could be limiting it?

@pizzaboxer if ur asking me then, yes, i have rbxfpsunlocker, but i dont use it since i downloaded bloxstrap

**Comment by kirbix12** [comment]
What kind of computer hardware you have?
Did you set the FPS cap before or after you launched Roblox with Bloxstrap?

**Comment by pizzaboxer** [comment]
> i have rbxfpsunlocker, but i dont use it since i downloaded bloxstrap

As kirbix mentioned, what's your hardware like? Also, have you checked to make sure rbxfpsunlocker isn't running in the background when launching with Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by kudosbro** [comment]
im having this issue too, no matter what i set the fps to in the launcher, it's always capped at 80 in game
