### ISSUE TITLE
can't change bloxstrap icon

### ISSUE THREAD

**Issue by nebulaHUN** [pizzaboxer/bloxstrap#572]
my file is 128x128 and a .ico file but it doesn't change the icon

**Comment by pizzaboxer** [comment]
How did you create the .ico file?

**Comment by nebulaHUN** [comment]
well i just renamed a .png/jpg file, i don't know how to create one, so i
renamed it

pizzaboxer ***@***.***> ezt írta (időpont: 2023. aug. 22., K,
14:41):

**Comment by pizzaboxer** [comment]
https://cloudconvert.com/png-to-ico

**Comment by nebulaHUN** [comment]
ty

pizzaboxer ***@***.***> ezt írta (időpont: 2023. aug. 24.,
Cs, 23:40):
