### ISSUE TITLE
Can't play Roblox VR

### ISSUE THREAD

**Issue by AroCodeScavanger** [pizzaboxer/bloxstrap#573]
When the Oculus app and SteamVR are open, and my Oculus/Meta Quest 2 is ready for play, it shows the VR place loading model, but launches to the normal screen mode. I am using [OculusKiller](https://github.com/LibreQuest/OculusKiller) and i don't know if this issue exists while using the normal app.

**Comment by AroCodeScavanger** [comment]
OpenGL

**Comment by GoingCrazyDude** [comment]
first, why are you using opengl, second, vr only works on directx

**Comment by OrphanObliterator** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/108492285/22567f59-0e4d-402a-8d3a-37d1d9506e69)
