### ISSUE TITLE
Bloxstrap/Default Roblox client random crashes under 35m

### ISSUE THREAD

**Issue by Ardaninho** [pizzaboxer/bloxstrap#577]
This has been bugging me out, but when I play ANY game, I get crashes from 3-10m up to 30m of gameplay
I receive no error window, aka "An unexpected error occurred and Roblox needs to quit. We're sorry!" exit error.

This is one of the log files of the last game I have played before sending this issue:
[0.591.0.5910633_20230824T183932Z_Player_835E9_last.log](https://github.com/pizzaboxer/bloxstrap/files/12432657/0.591.0.5910633_20230824T183932Z_Player_835E9_last.log)

No matter what I try, I deleted the entirety of Roblox, cleared the cache, installed RCO, updated graphics driver, restarted computer, tested Bloxstrap and default client; it won't work.

Anything needed for this operation I am happy to ablige and thank you for answering.

**Comment by pizzaboxer** [comment]
> No matter what I try, I deleted the entirety of Roblox, cleared the cache, installed RCO, updated graphics driver, restarted computer, tested Bloxstrap and default client; it won't work.

Well, you seem to have already done the things that I would have suggested, so I'm not really sure what more I can tell you.
Just to confirm, you've tried without RCO flags too?

**Comment by Ardaninho** [comment]
Thanks for still trying to help me, but this got fixed automatically today which I find it weird.
