### ISSUE TITLE
Antianalising gone.

### ISSUE THREAD

**Issue by NovaCraftYT** [pizzaboxer/bloxstrap#579]
The only reason i downloaded Bloxstrap because it had this feature, without this, its useless. (for me)

**Comment by GoingCrazyDude** [comment]
It causes major glitches and bugs, you can use 2.5.0 and add the FLogNetwork flag with the value 7 (fixes rpc)

**Comment by GoingCrazyDude** [comment]
also you can just, yk, add the msaa flag...

**Comment by pizzaboxer** [comment]
> The only reason i downloaded Bloxstrap because it had this feature, without this, its useless. (for me)

Did you read the release notes?

**Comment by Sahelantrophus** [comment]
use DSR if you really want antialiasing
