### ISSUE TITLE
Bloxstrap flat-out not opening

### ISSUE THREAD

**Issue by BirdOfBlueJays** [pizzaboxer/bloxstrap#580]
@pizzaboxer Hello, I just wanted to point out this issue that I've been having with 2.5.1 and 2.4.0, with 2.5.0 just having the internet connection error. When I run the Bloxstrap installer or even run it as administrator, it just doesn't open at all. Please help!

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it

**Comment by BirdOfBlueJays** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it

This did not work.

**Comment by pizzaboxer** [comment]
What version do you have installed?

**Comment by BirdOfBlueJays** [comment]
> What version do you have installed?

6.0.21.

**Comment by pizzaboxer** [comment]
When you try to run it, does it stay running in the background?

**Comment by BirdOfBlueJays** [comment]
> When you try to run it, does it stay running in the background?

No.

**Comment by pizzaboxer** [comment]
Open Windows Event Viewer, go to Windows Logs -> Application, and tell me if there's any 'Error' entries at the top.

**Comment by BirdOfBlueJays** [comment]
> Open Windows Event Viewer, go to Windows Logs -> Application, and tell me if there's any 'Error' entries at the top.

Yes, the third from the top down. It says:

Faulting application name: LockApp.exe, version: 10.0.19041.2193, time stamp: 0x0fad9c1c
Faulting module name: ntdll.dll, version: 10.0.19041.3324, time stamp: 0xda4a9f63
Exception code: 0xc0000409
Fault offset: 0x000000000008c6bf
Faulting process id: 0x63c0
Faulting application start time: 0x01d9d735fea8bee6
Faulting application path: C:\Windows\SystemApps\Microsoft.LockApp_cw5n1h2txyewy\LockApp.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: d88d777f-aabf-40f3-9754-e3542c32b548
Faulting package full name: Microsoft.LockApp_10.0.19041.1023_neutral__cw5n1h2txyewy
Faulting package-relative application ID: WindowsDefaultLockScreen

**Comment by pizzaboxer** [comment]
I just realized that you said 2.5.0 showed fine. Run 2.5.1 again, and get the log file from it. It should be in %temp%, assuming you haven't yet been able to do an install. Sort by date modified and look for files beginning with `Bloxstrap_`.

**Comment by BirdOfBlueJays** [comment]
> 

I can confirm that it is not in there at all.

**Comment by BirdOfBlueJays** [comment]
> I just realized that you said 2.5.0 showed fine. Run 2.5.1 again, and get the log file from it. It should be in %temp%, assuming you haven't yet been able to do an install. Sort by date modified and look for files beginning with `Bloxstrap_`.



> I just realized that you said 2.5.0 showed fine. Run 2.5.1 again, and get the log file from it. It should be in %temp%, assuming you haven't yet been able to do an install. Sort by date modified and look for files beginning with `Bloxstrap_`.

**Comment by BirdOfBlueJays** [comment]
Sorry, I accidentally closed this. I don't use GitHub much lol

**Comment by pizzaboxer** [comment]
> I can confirm that it is not in there at all.

You're sure that the %localappdata%\Bloxstrap folder doesn't exist, right?

**Comment by BirdOfBlueJays** [comment]
> You're sure that the %localappdata%\Bloxstrap folder doesn't exist, right?

Yes, I can confirm that it does not exist.

**Comment by pizzaboxer** [comment]
I don't get it, there isn't any reason for 2.5.1 to not work when 2.5.0 does. What about if you try installing 2.4.0 with Winget?

`winget install bloxstrap -v "2.4.0"` in a command prompt window.

**Comment by BirdOfBlueJays** [comment]
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/69612741/f84cf66e-8095-4571-949f-731b4cd5bc69)

**Comment by BirdOfBlueJays** [comment]
> I don't get it, there isn't any reason for 2.5.0 to work, while 2.5.1 and 2.4.0 don't. What about if you try installing 2.4.0 with Winget?
> 
> `winget install bloxstrap -v "2.4.0"` in a command prompt window.

![image2](https://github.com/pizzaboxer/bloxstrap/assets/69612741/7229da6f-cb92-4cbc-90f0-551b9242ab35)
![image](https://github.com/pizzaboxer/bloxstrap/assets/69612741/8c761a4a-c137-432c-8bfc-efd2640deced)

**Comment by pizzaboxer** [comment]
What version of Windows are you using? Run `dotnet --info` and show the whole output here.

**Comment by BirdOfBlueJays** [comment]
I managed to run 2.4.0 by reinstalling winget from the Microsoft repository. With the help of unexp, we managed to fix it! Thank you.

**Comment by pizzaboxer** [comment]
with the help of who now

**Comment by BirdOfBlueJays** [comment]
> with the help of who now

nothing

**Comment by Sahelantrophus** [comment]
> With the help of unexp, we managed to fix it!
you're lying your ass off

**Comment by Sahelantrophus** [comment]
> With the help of unexp, we managed to fix it!

you're lying your ass off

**Comment by BirdOfBlueJays** [comment]
> > With the help of unexp, we managed to fix it!
> 
> you're lying your ass off

no

**Comment by I-Have-An-Issue** [comment]
> with the help of who now

unexp solos

**Comment by Sahelantrophus** [comment]
"unexp solos" but his PC is so bad he can't run super meat boy 😭

**Comment by unexp** [comment]
> "unexp solos" but his PC is so bad he can't run super meat boy 😭

Take a chill pioll

**Comment by pizzaboxer** [comment]
hey maybe Sahelantropus got a point yknow

**Comment by unexp** [comment]
> hey maybe Sahelantropus got a point yknow

Thats straight up mean

**Comment by Sahelantrophus** [comment]
ok fine you can run super meat boy... but your PC can't handle the blood effects so you turn them off HAHAHAHAHA
