### ISSUE TITLE
Bloxstrap stuck at "Getting the latest bloxstrap"

### ISSUE THREAD

**Issue by kubshit** [pizzaboxer/bloxstrap#581]
The title says everything.
![image](https://github.com/pizzaboxer/bloxstrap/assets/91030527/a5a5083d-544b-4c80-a8cb-40105d73d1d8)

**Comment by julianpoelmann** [comment]
had this 3 times, now it works suddenly

**Comment by pizzaboxer** [comment]
Bad internet connection, I'll fix this to show a proper error. Download and run the latest version manually.

**Comment by pizzaboxer** [comment]
This issue is actually a lot more complicated and stupid than it appears to be, but I think I've fixed it. Though, I won't truly know until 2.6.0 is released. I'll close this for now though, and see if it happens again then.
