### ISSUE TITLE
is there a way to force roblox to a certain window height and width?

### ISSUE THREAD

**Issue by ihad11cats** [pizzaboxer/bloxstrap#582]
is there any way to force roblox to use a certain window height and width or is this not possible?

**Comment by pizzaboxer** [comment]
Not reliably. Shouldn't Roblox remember its position though?

**Comment by ihad11cats** [comment]
i mean it does but i am wondering if u could go lower because roblox limits it to 800 x 599

**Comment by pizzaboxer** [comment]
Oh, that's what you mean. I don't really think it is, because those restrictions are imposed by Roblox checking the size whenever it's changed. Sorry.
