### ISSUE TITLE
the second time i opened bloxstrap got a error

### ISSUE THREAD

**Issue by funnikid65** [pizzaboxer/bloxstrap#583]
i wanted to check this update for bloxstrap, putted some configurations and stuff, the first time i opened to test these was good, the second time i just got a error
![image](https://github.com/pizzaboxer/bloxstrap/assets/104434894/c20716f5-d17b-47a8-8098-bdd1975b6c1e)

what could it be?

also forgot to send this
[Bloxstrap_20230825T132913Z.log](https://github.com/pizzaboxer/bloxstrap/files/12439619/Bloxstrap_20230825T132913Z.log)

**Comment by pizzaboxer** [comment]
Mistake on my part, will be fixed in a hotfix that's coming soon.

**Comment by KlothoTheDev** [comment]
soy habla espanol
