### ISSUE TITLE
Roblox crashes with the error "Roblox Game Client has stopped working" after either exiting the game or getting teleported to a different place

### ISSUE THREAD

**Issue by fq0e** [pizzaboxer/bloxstrap#584]
https://github.com/pizzaboxer/bloxstrap/assets/90973963/39242eab-4bd0-4df8-8e45-5dc4ab68df6c

**Comment by pizzaboxer** [comment]
Does this happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Lucas559-noob** [comment]
I guess is because the desktop program thing is disabled? Same happens to me when leaving game

**Comment by fq0e** [comment]
> Does this happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

It only happens when I use Bloxstrap

**Comment by pizzaboxer** [comment]
Can I see your flag list? Open the Bloxstrap menu and show the FastFlag editor. Make sure preset flags are shown too.

**Comment by fq0e** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/90973963/d1e25fad-c82f-400f-8cc2-3a80eb577e69)
![image](https://github.com/pizzaboxer/bloxstrap/assets/90973963/aedb2089-4aeb-4ca9-ac92-dec7784ab32f)
![image](https://github.com/pizzaboxer/bloxstrap/assets/90973963/78a12fae-19cc-492b-bf2a-f06db1f779eb)

**Comment by pizzaboxer** [comment]
Do you have the desktop app disabled?

**Comment by fq0e** [comment]
it's not disabled, how would i disable it?

**Comment by pizzaboxer** [comment]
Was just asking, as that's the only other thing I can really think of. Send me Roblox's latest log file from %localappdata%\Roblox\logs, I'll try and spot anything wrong if I can.

**Comment by fq0e** [comment]
alright,
[0.591.0.5910633_20230826T112759Z_Player_DA5CD_last.log](https://github.com/pizzaboxer/bloxstrap/files/12445254/0.591.0.5910633_20230826T112759Z_Player_DA5CD_last.log)

**Comment by pizzaboxer** [comment]
You sure you didn't disable the Desktop app? Show me what the option is set to, it's in the Mods tab of the Bloxstrap Menu.

**Comment by fq0e** [comment]
It is disabled

![image](https://github.com/pizzaboxer/bloxstrap/assets/90973963/3c2e8616-17a9-47f0-89ac-63de02f5fca1)

**Comment by pizzaboxer** [comment]
> it's not disabled, how would i disable it?

???

**Comment by fq0e** [comment]
I thought you were referring to something else (I woke up 5 minutes ago when you said that)

**Comment by fq0e** [comment]
okay i actually didn't know disabling it would cause the crash so that's my bad
https://github.com/pizzaboxer/bloxstrap/assets/90973963/b6487753-38ce-4713-a925-823ae4d2a517
