### ISSUE TITLE
how i can fix this please help

### ISSUE THREAD

**Issue by LordLey** [pizzaboxer/bloxstrap#585]
![image](https://github.com/pizzaboxer/bloxstrap/assets/143241174/ec0f3a58-03e5-4247-8554-9dc2c8b2cf72)

**Comment by LordLey** [comment]
I need help so bad right now I want use bloxstraps but doesnt work

**Comment by pizzaboxer** [comment]
You have the desktop app disabled. When it's disabled, the "Play Roblox" shortcut just opens the Roblox games page in your web browser, which is what this is trying to do. Just use the website.

**Comment by pizzaboxer** [comment]
On another note - how do you not have a default browser selected?
