### ISSUE TITLE
"An exception occurred when running Bloxstrap"

### ISSUE THREAD

**Issue by yu-kiat** [pizzaboxer/bloxstrap#588]
I got an error when opening Roblox through Bloxstrap.

System.ComponentModel.Win32Exception: Access is denied.

The log file is included.
[Bloxstrap_20230826T022933Z.log](https://github.com/pizzaboxer/bloxstrap/files/12445095/Bloxstrap_20230826T022933Z.log)

**Comment by pizzaboxer** [comment]
Duplicate of #583
