### ISSUE TITLE
Low Quality Textures And Clothing

### ISSUE THREAD

**Issue by ChinZhiHong** [pizzaboxer/bloxstrap#589]
I've been experiencing this bug since last year, it happened when I was using the normal Roblox client. I found out about Bloxstrap and it solved the issue for a while until recently it happened again. I tried everything but it's still the same. Is this a Roblox problem or just my PC? 
![image](https://github.com/pizzaboxer/bloxstrap/assets/85738305/78430721-4832-4d8f-bf8e-63235dbcaab6)
![image](https://github.com/pizzaboxer/bloxstrap/assets/85738305/3f852a4f-3222-41be-84bc-5f98a4c67dd0)

**Comment by pizzaboxer** [comment]
Yeah, Roblox just does this sometimes. I doubt it's because of Bloxstrap, but if you want to confirm then you can temporarily switch back to using Roblox's bootstrapper. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ChinZhiHong** [comment]
Thanks, will update once I've tried it.

**Comment by ChinZhiHong** [comment]
Nope, it didn't work. They both look the same. Any other solutions?

**Comment by pizzaboxer** [comment]
Nope, not really. It's a Roblox problem, so I can't really do anything about it. Sorry.
