### ISSUE TITLE
Custom mouse doesn't appear in-game.

### ISSUE THREAD

**Issue by Xxxsusx** [pizzaboxer/bloxstrap#593]
Already tried doing things like uninstalling bloxstrap and even roblox. even though on the desktop app seems normal it doesn't appear custom mouses in-game.

Like MM2 (Murder Mystery 2) when equipping the knife/gun as murder/sheriff

Even though i still didn't have tested it without bloxtrap i suspect that is a bug/issue. (gotta test without bloxstrap later and see if anything happens.)

**Comment by pizzaboxer** [comment]
> Like MM2 (Murder Mystery 2) when equipping the knife/gun as murder/sheriff

Don't those use custom crosshairs? You can't override those. You can only override the mouse pointer that Roblox usually shows.
