### ISSUE TITLE
Launcher uninstalled itself

### ISSUE THREAD

**Issue by jigguz** [pizzaboxer/bloxstrap#595]
![image](https://github.com/pizzaboxer/bloxstrap/assets/85911584/168bc285-cb5c-47bd-8e61-4dfff938ca44)

**Comment by pizzaboxer** [comment]
![thedoginmyhands](https://github.com/pizzaboxer/bloxstrap/assets/41478239/29585b37-4b8c-4256-a2da-6ea369b16e6d)
