### ISSUE TITLE
Discord rich presence not working 

### ISSUE THREAD

**Issue by Thefurious031** [pizzaboxer/bloxstrap#597]
I'm trying to use the option where your roblox games shows up as your activity on discord, I have everything turned on but for some reason it not working, please help.

![image_2023-08-26_173812382](https://github.com/pizzaboxer/bloxstrap/assets/143294960/cf34fb08-0e39-4348-8512-c97f9211f039)

![image_2023-08-26_173845977](https://github.com/pizzaboxer/bloxstrap/assets/143294960/775ef0b9-aa88-4c79-8fb3-a64d2e31b45c)

![image_2023-08-26_174029199](https://github.com/pizzaboxer/bloxstrap/assets/143294960/a5e7871d-ae9f-4d49-b1a9-361afd0497e3)

**Comment by pizzaboxer** [comment]
You're not using the latest version of Bloxstrap.

**Comment by Thefurious031** [comment]
thank you for resolving this issue man, have a good weekend :)

**Comment by Thefurious031** [comment]
Hey man I've got another question, is there a mod that allows you to resize the roblox game window as you like,cuz on the web version of roblox there is a limit but on the microsoft store version there isnt, here's an image of the roblox web version (with bloxstrap) on the left and the Microsoft store version of roblox on the right






















![image_2023-08-26_175823526](https://github.com/pizzaboxer/bloxstrap/assets/143294960/8b5a34fa-fe34-4c93-b39e-964a656fd6bc)

**Comment by pizzaboxer** [comment]
Nope, minimum size can't really be overriden.
