### ISSUE TITLE
alt enter dont work for me

### ISSUE THREAD

**Issue by vurpeldgocrazy** [pizzaboxer/bloxstrap#599]
when I do alt enter dosent go black and the shit dont work

**Comment by pizzaboxer** [comment]
What's your rendering mode set to?

**Comment by Jpssz** [comment]
same problem. I am using Direct 3D 11 for a lot of time but recently Alt Enter doesn't work. I cant remove from the exclusive fullscreen mode!

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by nazv5** [comment]
Having the same problem
