### ISSUE TITLE
no version of .net allows me to use bloxstrap 

### ISSUE THREAD

**Issue by gaming128** [pizzaboxer/bloxstrap#6]
Installed bloxstrap and saw that i didnt had .net runtime, so i went and downloaded the latest, and it did not remove the warning, so i checked the warning and saw that it wanted 6.0.5, so i downgraded from 6.0.8 to 6.0.5 and it **still** did not got rid of the warning, so i reinstalled the bloxstrap installer to see if it just didnt register .net runtime. Nope, it _**still**_ doesn't let me use bloxstrap
![image](https://user-images.githubusercontent.com/39526474/186301907-02a0d3af-7b98-4f48-8640-fa31e5bb9d09.png)

**Comment by pizzaboxer** [comment]
You sure you have the x86 version of the runtime downloaded? A download is provided in the README.
