### ISSUE TITLE
last question, would i have to delete my other fps unlocker?

### ISSUE THREAD

**Issue by amkzm** [pizzaboxer/bloxstrap#603]

**Comment by GoingCrazyDude** [comment]
you can keep it if you want no need to delete it, just dont use it alongside bloxstrap

**Comment by amkzm** [comment]
also to revert all the changes, i would just have to delete bloxstrap correct?

**Comment by pizzaboxer** [comment]
> would i have to delete my other fps unlocker?

If you want to avoid conflicts, it would be best to do that.

**Comment by pizzaboxer** [comment]
> also to revert all the changes, i would just have to delete bloxstrap correct?

Yeah, just uninstall and you'll be good.

**Comment by amkzm** [comment]
i have the client settings fps unlocker, if i delete the folder (for the fps unlocker) is that enough or do i have to also delete the json file on my pc

**Comment by pizzaboxer** [comment]
Just the unlocker itself is fine.
