### ISSUE TITLE
How to disable this garbage

### ISSUE THREAD

**Issue by Mimibienv** [pizzaboxer/bloxstrap#605]
Hi! Does anyone know how to remove this ? Thanks.
![image](https://github.com/pizzaboxer/bloxstrap/assets/82171237/d963db2d-4bd5-45e3-9186-09663d18d068)

**Comment by GoingCrazyDude** [comment]
oh
setting FFlagInGameMenuV1FullScreenTitleBar to false should do it

**Comment by Mimibienv** [comment]
alr tysm
