### ISSUE TITLE
Feature Request - "Do you *actually* want to play this game?" if an instance of Roblox is open

### ISSUE THREAD

**Issue by exurd** [pizzaboxer/bloxstrap#606]
There have been so many times I misclicked the green play button by accident and lost loads of progress on a game. It would be great if it prompted me before it forcibly closed the instance and ruined my day.

**Comment by GoingCrazyDude** [comment]
Pizza is working on something to combat this. Also for now, if you turn on multi instances, and accidentally click the button, the game will not quit but the new window will not join. So that is the fix for now.

**Comment by pizzaboxer** [comment]
Someone has already suggested this idea, but it is a good idea.
