### ISSUE TITLE
crashing every 5 mins

### ISSUE THREAD

**Issue by Cyber2525** [pizzaboxer/bloxstrap#607]
since the new update of bloxstrap, it crashes every 5 mins, so i will stop using bloxstrap until you fix this

**Comment by pizzaboxer** [comment]
Does it happen without Bloxstrap too?

**Comment by RYINS** [comment]
No

**Comment by pizzaboxer** [comment]
Who are you? I don't know if you're having the same issue that OP describes.

**Comment by RYINS** [comment]
Yes I'm having the same issues

**Comment by pizzaboxer** [comment]
Send me Roblox's latest log file from `%localappdata%\Roblox\logs`. Sort by date modified, get the latest one, and send it to me via email at [pizzaboxer@pizzaboxer.xyz](mailto:pizzaboxer@pizzaboxer.xyz)

**Comment by RYINS** [comment]
And how am I suppose to do that?

**Comment by ZerodeathTheVictime** [comment]
> And how do I do that?

Windows + R

Type in **%localappdata%\Roblox\logs**

Find the latest file and copy it

**Comment by RYINS** [comment]
0.592.0.5920587_20230831T064010Z_Player_C3E0D_last

**Comment by GoingCrazyDude** [comment]
you didnt send the log lmao

**Comment by pizzaboxer** [comment]
> 0.592.0.5920587_20230831T064010Z_Player_C3E0D_last

I said send it to me via email. Also, all you did was copy the filename.

**Comment by RYINS** [comment]
Ah sorry I'll check again

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
