### ISSUE TITLE
FF Editor confirmation overflow

### ISSUE THREAD

**Issue by MaxxusX** [pizzaboxer/bloxstrap#608]
when importing a big FF file like RCO, the overwrite confirmation window is too big to see the title, yes/no buttons, and most of the FFs

maybe add a scrollbar and limit the size of the window?

![image](https://github.com/pizzaboxer/bloxstrap/assets/66540504/e800d8f1-3969-46fc-a3be-66a37a845e60)

**Comment by GoingCrazyDude** [comment]
roblox crash optimizer

**Comment by pizzaboxer** [comment]
I'll add a limit. Keep in mind, this will only happen if you're importing the same list twice.

**Comment by saba273** [comment]
hey can you help me with this?

**Comment by malekelmogy** [comment]
> when importing a big FF file like RCO, the overwrite confirmation window is too big to see the title, yes/no buttons, and most of the FFs
> 
> maybe add a scrollbar and limit the size of the window?
> 
> ![image](https://private-user-images.githubusercontent.com/66540504/263776239-e800d8f1-3969-46fc-a3be-66a37a845e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTc2MjEsIm5iZiI6MTcyMDc1NzMyMSwicGF0aCI6Ii82NjU0MDUwNC8yNjM3NzYyMzktZTgwMGQ4ZjEtMzk2OS00NmZjLWEzYmUtNjZhMzdhODQ1ZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA0MDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjI3ZGRhNDk4ZTlkMzNlN2M5ODRiYjJlNGYyMDMxNWJkYmExN2QyMDZhYTg2MjJmYmQ4NTc2ZDUzNjUyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPQN_AX8W2p1CDRIEVzAL1bs_yO7si3R3g4N2ux7xTs)

Cool

**Comment by malekelmogy** [comment]
> when importing a big FF file like RCO, the overwrite confirmation window is too big to see the title, yes/no buttons, and most of the FFs
> 
> maybe add a scrollbar and limit the size of the window?
> 
> ![image](https://private-user-images.githubusercontent.com/66540504/263776239-e800d8f1-3969-46fc-a3be-66a37a845e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTc2NDYsIm5iZiI6MTcyMDc1NzM0NiwicGF0aCI6Ii82NjU0MDUwNC8yNjM3NzYyMzktZTgwMGQ4ZjEtMzk2OS00NmZjLWEzYmUtNjZhMzdhODQ1ZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA0MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWIzNjY5MGQyN2RlYjg5MTE1YzVkYmY4MmQxOTQwOGI0MDI3ZGM1ZDE3MTcxM2YxZTk4ZTVmYjU2ODk3OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.44ZdLw6eMhQerOeFjRlnhRyfNzUZ0feocYS9ixe6UOE)

Can you sent a link pls to the FastFlags editor page plsss
