### ISSUE TITLE
BUG - Bloxstrap opening themself in Chromium based browser process

### ISSUE THREAD

**Issue by Zaptyp** [pizzaboxer/bloxstrap#611]
I noticed that bloxstrap does something that is a little unusual for an application ie it opens in the same process as the browser and doesn't behave like roblox. Which it doesn't do that at all it just creates a separate process and doesn't plug into the browser like some spyware. After further investigation it appears that Bloxstrap only does this when the browser is based on the Chromium engine (This was tested on: Opera GX, Microsoft Edge Beta Preview and on Google Chrome) and it does not do so in the case of the Firefox browser. I recorded this phenomenon in the recording below in the following recording I used 3 browsers based on this engine and one on Gekko engine and the software I used to monitor the processes was Process Monitor from SysInternals.

# Video:

https://github.com/pizzaboxer/bloxstrap/assets/43276401/7e54077b-22d4-43a9-9259-31b71c72f06f

**Comment by pizzaboxer** [comment]
I don't get it, what is this trying to prove? Isn't that just how browsers launch applications?

**Comment by WaviestBalloon** [comment]
This is intended behavior, you are launching from the browser, so the browser is launching it. Does this affect gameplay or usage at all?

**Comment by Zaptyp** [comment]
> It's not "plugging into the browser", procexp is showing that it was started from the browser process.
So how do you explain that since ROBLOX uses its original bootstraper roblox starting as a separate process and cannot be found in the browser process?
>Does this affect gameplay or usage at all?
So it affects the performance and convenience when roblox hangs because then I do not have to dig into what process it is hidden and sometimes it happens that after closing the viewer roblox just closes because the viewer process is clogged.

**Comment by pizzaboxer** [comment]
> So how do you explain that since ROBLOX uses its original bootstraper roblox starting as a separate process and cannot be found in the browser process?

...but it does?

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/97b80db5-41c5-4a0e-8d3f-b61212d1a073)

**Comment by Thelolguy1** [comment]
Malware would run regardless of whether it is in a separate process or not...

@Zaptyp If you're paranoid about bloxstrap, you can read the source all you want and compile from source

**Comment by MakeSureDudeDies** [comment]
furschizo!!!

**Comment by Sahelantrophus** [comment]
boy ur dumb as hell

**Comment by jigguz** [comment]
Tell this nigga my nutsack is spyware cuz its lookin at him 😭🤝🤝🙏🥀✝️✝️

**Comment by WaviestBalloon** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/31796727/2c519879-738e-4952-b1e6-0d39e61be47d)

APPLEJUICE IS SPYWARE, DO NOT USE, SAME WITH ANY BROWSER

**Comment by MakeSureDudeDies** [comment]
> Tell this nigga my nutsack is spyware cuz its lookin at him 😭🤝🤝🙏🥀✝️✝️

ON GANG BRO

**Comment by GoingCrazyDude** [comment]
bro the entire source code is available to the public and he calls it spyware 😭

**Comment by Sahelantrophus** [comment]
> Tell this nigga my nutsack is spyware cuz its lookin at him 😭🤝🤝🙏🥀✝️✝️

ur banned kid

**Comment by nakoyasha** [comment]
the only spyware here is opera gx
