### ISSUE TITLE
discord issue

### ISSUE THREAD

**Issue by xM4rkHUN** [pizzaboxer/bloxstrap#613]
i literally cant speak anywhere

**Comment by GoingCrazyDude** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/67791946/1b3f53fb-86aa-4494-8d12-0973e5a73951)
wow i wonder why

**Comment by xM4rkHUN** [comment]
yea, i saw that too, but why did i get those?

**Comment by xM4rkHUN** [comment]
like am i allowed to know what i did to get those?
