### ISSUE TITLE
Roblox drops connection at random times

### ISSUE THREAD

**Issue by tacomaster1720** [pizzaboxer/bloxstrap#615]
This all started since I have started using bloxstrap. The game doesn't really crash, it just freezes and everything stops but I can still walk around in game but most stuff is not operational.

**Comment by FV101** [comment]
same issue, i made a support thread on this in bloxstrap's discord. its called "any flags for this issue?" by bc(ecause)

**Comment by Mugetsu895** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
> This all started since I have started using bloxstrap. 

Did you check if it happens without it too? @FV101 does have the same issue, but he mentioned that he's been having it ever since Hyperion rolled out back in April. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by FV101** [comment]
these are some samples of my issue, 
https://cdn.discordapp.com/attachments/1146173160123809812/1146174467610001448/game_dies.mp4
https://cdn.discordapp.com/attachments/1146173160123809812/1146173320996327446/2023-08-16_23-56-18.mp4
@Mugetsu895 does this match with your case, the game freezes and receives no updates from the server. The fan in the first video should be spinning, but it's frozen.

**Comment by ZerodeathTheVictime** [comment]
> these are some samples of my issue, https://cdn.discordapp.com/attachments/1146173160123809812/1146174467610001448/game_dies.mp4 https://cdn.discordapp.com/attachments/1146173160123809812/1146173320996327446/2023-08-16_23-56-18.mp4 @Mugetsu895 does this match with your case, the game freezes and receives no updates from the server. The fan in the first video should be spinning, but it's frozen.

its a roblox issue, the same happened to my friends.

**Comment by FV101** [comment]
any fixes?

**Comment by WaviestBalloon** [comment]
> these are some samples of my issue, https://cdn.discordapp.com/attachments/1146173160123809812/1146174467610001448/game_dies.mp4 https://cdn.discordapp.com/attachments/1146173160123809812/1146173320996327446/2023-08-16_23-56-18.mp4 @Mugetsu895 does this match with your case, the game freezes and receives no updates from the server. The fan in the first video should be spinning, but it's frozen.

These are not crashes, this is your client dropping connection to the server or vise-versa. What is your network setup? Wireless, wired?

**Comment by FV101** [comment]
> dawg the client still sends data to the server

https://cdn.discordapp.com/attachments/1146173160123809812/1146175068163027155/image.png

my friends tell me that they can still see me moving when it happens. so the client sends data while it doesnt recieve any updates

**Comment by pizzaboxer** [comment]
Yeah, I know.

**Comment by Mugetsu895** [comment]
been having the same issue recently, mainly when i turn my vpn on, this is probably a roblox issue

**Comment by WaviestBalloon** [comment]
We have no idea how this could happen, have you tested this with the normal Roblox Player?
https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

This seems like a internal issue, not a Bloxstrap one.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
