### ISSUE TITLE
cannot find Preffered lighting technology.

### ISSUE THREAD

**Issue by DenouementEfflorescence** [pizzaboxer/bloxstrap#616]
Basically i want to use this feature. its the only reason i got bloxstrap. however, i cant find it, even in older versions. why is thatß
I want to use future is bright but cant find it

**Comment by pizzaboxer** [comment]
What do you mean? It's in the FastFlags tab of the Bloxstrap Menu.

**Comment by DenouementEfflorescence** [comment]
> What do you mean? It's in the FastFlags tab of the Bloxstrap Menu.

Basically i cannot find Future is bright Like in the tutorial. idk why

**Comment by GoingCrazyDude** [comment]
Go to the fastflags tab and then click on "Preferred Lighting Technology" and then choose future is bright

**Comment by pizzaboxer** [comment]
> Basically i cannot find Future is bright Like in the tutorial. idk why

Future (Phase 3) is the same thing, just under a different name.
