### ISSUE TITLE
The "Preserve Rendering Quality" option doesnt always function

### ISSUE THREAD

**Issue by Zedz1ig** [pizzaboxer/bloxstrap#617]

**Comment by pizzaboxer** [comment]
Any more details? Like, what's your display scaling set to? When have you noticed it not happening?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by xFrostyxt** [comment]
I activated the option to see what it was, but when I launched Roblox the browser closed and when I closed Roblox the browser re opened, I deactivated the option , but that problem continues to happen, I tried to uninstall and reinstall but it doesn't work
