### ISSUE TITLE
Horrible lag with bloxstrap

### ISSUE THREAD

**Issue by xe6h** [pizzaboxer/bloxstrap#618]
When I use bloxstrap I either get horrible input lag in games or just overall games are super laggy and slow. 

Is there a way to fix this? or should I just not use bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by DamonYeo** [comment]
Hey is there any tip to get better FPS? I set mine to a 100 but it only gave me 8-50. Is there any way to increase my FPS?

**Comment by moyaimoment** [comment]
> Hey is there any tip to get better FPS? I set mine to a 100 but it only gave me 8-50. Is there any way to increase my FPS?

why did you comment on a closed thread, from almost a year ago

**Comment by DamonYeo** [comment]
And I have to problem for almost a year and I have got it fixed at a computer store because my computer is really slow but the Roblox didn't change.

**Comment by DamonYeo** [comment]
oh

**Comment by DamonYeo** [comment]
what abes

**Comment by 32bitx64bit** [comment]
> what abes

Lol, you're hardware just sucks if you're getting under 60 fps.

Simple fix is get a new computer. As you can't fix bad hardware.

**Comment by AnonymousUserInthisGithub** [comment]
im getting this problem too, this pc can easily runs roblox at 5k fps but since i got bloxstrap it lags me to 40-50 fps

**Comment by Vixsa66** [comment]
so bad

**Comment by FundipYT** [comment]
w

**Comment by FundipYT** [comment]
way more emails
