### ISSUE TITLE
Bloxstrap outright freezes Roblox after some time. Can't play with Bloxstrap installed. (Turned into troubleshooting discord rich presence)

### ISSUE THREAD

**Issue by FluffyKat43** [pizzaboxer/bloxstrap#619]
I've had a non-issue with Roblox ever since I've been playing that has caused the game to freeze for a few seconds after running for a bit and then continue as if it never froze but installing Bloxstrap now makes that freeze indefinite. If it dosen't freeze, the screen keeps flashing white, hurting my eyes. Definitely uninstalled until this is mended.

By the way, how the heck do you make the Discord Rich Presence work? Everyone says it works out of the box but it didn't for me.

And on top, how can you force the new v4 menu without Bloxstrap until we can get this fixed? I really liked that menu and Roblox took it away from me the other day.

**Comment by GoingCrazyDude** [comment]
What version of bloxstrap are you using? RPC should work

**Comment by GoingCrazyDude** [comment]
Set FFlagEnableV3MenuABTest3, FFlagEnableMenuModernizationABTest2, FFlagEnableMenuModernizationABTest, FFlagEnableMenuControlsABTest, FFlagEnableInGameMenuControls to force the V4 Menu

**Comment by FluffyKat43** [comment]
> Set FFlagEnableV3MenuABTest3, FFlagEnableMenuModernizationABTest2, FFlagEnableMenuModernizationABTest, FFlagEnableMenuControlsABTest, FFlagEnableInGameMenuControls to false to force the V4 Menu

Thank you - What file is this in?

**Comment by FluffyKat43** [comment]
> What version of bloxstrap are you using? RPC should work

latest. it just straight up dosen't work for some reason. 🤷

**Comment by GoingCrazyDude** [comment]
> > Set FFlagEnableV3MenuABTest3, FFlagEnableMenuModernizationABTest2, FFlagEnableMenuModernizationABTest, FFlagEnableMenuControlsABTest, FFlagEnableInGameMenuControls to false to force the V4 Menu
> 
> Thank you - What file(s) is/are this/these in? I'm not familiar with going into Roblox's file structure.

go to %USERPROFILE%\AppData\Local\Bloxstrap\Modifications, copy the clientsettings file, and put in the normal roblox directory, and you will have the V4 menu.

**Comment by GoingCrazyDude** [comment]
> > What version of bloxstrap are you using? RPC should work
> 
> latest. it just straight up dosen't work for some reason. 🤷 I don't know where the problem is and I don't really care to look as it's not important.

Go to the fflags list, click on show presets, and send a ss of all the flags

**Comment by FluffyKat43** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142940244/093a096e-98af-4172-a5b2-1bcee851a01c)
This is all I see

> > > What version of bloxstrap are you using? RPC should work
> > 
> > 
> > latest. it just straight up dosen't work for some reason. 🤷 I don't know where the problem is and I don't really care to look as it's not important.
> 
> Go to the fflags list, click on show presets, and send a ss of all the flags

**Comment by FluffyKat43** [comment]
**The main issue seems to have been solved with a reinstall of Bloxstrap, but I will keep the thread open because we're troubleshooting Rich Presence.**

**Comment by GoingCrazyDude** [comment]
can you list your pc specs

**Comment by FluffyKat43** [comment]
> 

All I know:

16GB DDR4 RAM
Intel i7
Nvidia GeForce RTX 2060 Mobile
144hz 1080P integrated monitor

**Comment by GoingCrazyDude** [comment]
try setting the framerate limit to 0 and see what happens

**Comment by FluffyKat43** [comment]
> try setting the framerate limit to 0 and see what happens

That was actually something I tried. Sadly, that did not affect the outcome.

**Comment by GoingCrazyDude** [comment]
disable graphics quality and try

**Comment by FluffyKat43** [comment]
I'm currently playing with Bloxstrap uninstalled, but with all of these flags set. It seems to be the specific fact of using Bloxstrap over just natural Roblox as all flags work correctly when Bloxstrap is not installed but I have that one major issue when it is installed.
I can't quite explain it, it works without but dosen't with

**Comment by FluffyKat43** [comment]
I will try to troubleshoot using these tips later, though

**Comment by GoingCrazyDude** [comment]
A tip for you: Copy the clientsettings folder from your bloxstrap directory after you set the preferences you want in the bloxstrap menu, paste them in the roblox directory, and the fflags will work with normal roblox

**Comment by GoingCrazyDude** [comment]
sad that bloxstrap is causing issues for you

**Comment by FluffyKat43** [comment]
Yeah, it does suck - I'd love to use the systems but it just simply dosen't work.
Gladly, all I really needed was the new menu at the end of the day.

(I'll leave the issue open as I do plan to try troubleshooting later)

**Comment by pizzaboxer** [comment]
Where do you have Bloxstrap installed to? You can find where it's installed by going to the Installation tab, and clicking "Open installation folder".

**Comment by FluffyKat43** [comment]
> Where do you have Bloxstrap installed to? You can find where it's installed by going to the Installation tab, and clicking "Open installation folder".
> 
> Also, some other things to try:
> 
>     * Try setting your framerate limit to 0
> 
>     * Try disabling activity tracking
> 
> 
> See if doing one of those two things change anything.
> 
> By the way, about rich presence, send me Bloxstrap's latest log file. It's in the Logs folder of wherever you installed it. Sort by date modified, get the latest one, and send it here.

I never thought to change Bloxstrap's install location so it just goes to appdata/local
Is there a more optimal location for it?

**Comment by FluffyKat43** [comment]
I tried running Roblox with Vulkan and it wouldn't even load the main menu :(
Oh well, back to automatic.

I checked my latest log file and it seems like the rich presence is working as intended on Bloxstrap's end, as it is connecting to and updating the presence. It just dosen't show up in Discord.

**Comment by pizzaboxer** [comment]
> [Bloxstrap_20230831T183027Z.log](https://github.com/pizzaboxer/bloxstrap/files/12489229/Bloxstrap_20230831T183027Z.log)

This looks like it isn't detecting Discord. Check something for me real quickly, open a PowerShell window and run the following command:

```ps
(Get-ChildItem \\.\pipe\).FullName -match "discord"
```

If you don't see `\\.\pipe\discord-ipc-0`, then something's wrong with Discord. I don't expect rich presence to be working at all for any app let alone Bloxstrap.

**Comment by FluffyKat43** [comment]
I actually found out that installing and uninstalling bloxstrap so many times seems to have fixed the random freeze thing only when not using bloxstrap.

Also, PowerShell is correctly identifying Discord. I use a custom rich presence app which quit working a bit back too.

**Comment by pizzaboxer** [comment]
> I use a custom rich presence app which quit working a bit back too.

Say what now?

I'm still not really sure what would be causing the freezes. Like I said, disabling both of those options makes it behave exactly like the normal launcher.

> I actually found out that installing and uninstalling bloxstrap so many times seems to have fixed the random freeze thing only when not using bloxstrap.

Yeah, the correlation isn't looking too strong here.

**Comment by FluffyKat43** [comment]
> Yeah, the correlation isn't looking too strong here.
I agree. It happened during my install/uninstall of Bloxlink so maybe one of the roblox reinstalls made it stop happening. 🤷 

> Say what now?
customrpc is cool
but yeah, rich presence as a whole seems to be not working. I only put two and two together last night.

**Comment by pizzaboxer** [comment]
> but yeah, rich presence as a whole seems to be not working. I only put two and two together last night.

Mind if I try helping out with rich presence while we're here?

**Comment by FluffyKat43** [comment]
Perhaps? I don't really know where to start sincrle everything is in order on both ends

**Comment by pizzaboxer** [comment]
I first want to check something with Discord. Open Task Manager, go to the Details tab, right click the table header, choose "Select columns", scroll down to the bottom, find the checkbox for "Elevated", enable it, then click OK.

Then, find Discord.exe in the process list, and show me what it says for it under Elevated.

**Comment by FluffyKat43** [comment]
Oh, I just saw this. I'm setting up a Minecraft server right now but I'll get back to you ASAP.

**Comment by FluffyKat43** [comment]
Alright, finally got time to do this. There are six Discord processes in here, and all six have "Elevated" set to "Yes".

**Comment by pizzaboxer** [comment]
> There are six Discord processes in here, and all six have "Elevated" set to "Yes".

Why is Discord being run as an Administrator?

**Comment by FluffyKat43** [comment]
> Why is Discord being run as an Administrator?

Would crash on boot without it

**Comment by pizzaboxer** [comment]
Well, that's your problem here. It won't work if Discord is being run as an Administrator. I don't really know what's going on in your situation, but if you want it to work, you'll have to figure out what's going on.

**Comment by FluffyKat43** [comment]
> Well, that's your problem here. It won't work if Discord is being run as an Administrator. I don't really know what's going on in your situation, but if you want it to work, you'll have to figure out what's going on.

ah, alright. good to know

**Comment by FluffyKat43** [comment]
> Well, that's your problem here. It won't work if Discord is being run as an Administrator. I don't really know what's going on in your situation, but if you want it to work, you'll have to figure out what's going on.

I decided to turn off administrator and Discord is working now. However, rich presence continues to not work. :shrug:

**Comment by pizzaboxer** [comment]
You've checked what it says under "Elevated" in Task Manager, right?

**Comment by FluffyKat43** [comment]
Not yet. Will check tomorrow.

**Comment by FluffyKat43** [comment]
Discord is no longer listed as Elevated, so it worked

**Comment by pizzaboxer** [comment]
For one, retry that Powershell command I posted earlier. For another, you could also try this debug tool I made. Let me know what the output of it says.

https://files.pizzaboxer.xyz/tools/DiscordRPCDebugger.exe

**Comment by FluffyKat43** [comment]
So I checked a couple days and yes, elevated is "no" now.

RPC is working now, too. Discord updated recently which made it start working again.

**Comment by FluffyKat43** [comment]
I'm going to close the issue since everything has been resolved.

I'm happy we went through this, I would have never been so determined to get it working
