### ISSUE TITLE
When I click install, nothing happens.

### ISSUE THREAD

**Issue by LibDevv** [pizzaboxer/bloxstrap#62]
I've downloaded the bootstrapper and enabled the settings I wanted to enable, but when I click install it opens the games page for roblox and doesn't install. I tried turning off windows defender and running as administrator but nothing worked, and it's especially annoying because I can't find a fix anywhere since literally nowhere else over than like 2 reddit posts cover this.

**Comment by pizzaboxer** [comment]
oh wow, i'm stupid... 
if you leave "Disable desktop app" unticked, does it work?

**Comment by LibDevv** [comment]
Yep thanks man that worked!

**Comment by pizzaboxer** [comment]
got it, i'll release a hotfix for this
