### ISSUE TITLE
Roblox crashes when I minimize the game with Bloxstrap on it.

### ISSUE THREAD

**Issue by UndeadMemegamer** [pizzaboxer/bloxstrap#621]
Whatever I minimize my game, the game crashes with the message saying An unexpected error occured and Roblox needs to quit. We're sorry

**Comment by GoingCrazyDude** [comment]
are you using vulkan?

**Comment by UndeadMemegamer** [comment]
yes

**Comment by UndeadMemegamer** [comment]
> are you using vulkan?
yes i am using vulkan to improve performance on my laptop

**Comment by GoingCrazyDude** [comment]
yeah so minimizing on vulkan causes a crash, cant be prevented cause its a roblox problem
just dont minimize lol

**Comment by UndeadMemegamer** [comment]
like opengl directx

**Comment by GoingCrazyDude** [comment]
yeah they wont but i recommend not using opengl
also the difference between directx and vulkan isnt huge

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

Keep it on automatic
