### ISSUE TITLE
Preffered Lighting Technology not working?

### ISSUE THREAD

**Issue by Hasninai** [pizzaboxer/bloxstrap#626]
I have compared it a few times but I see no difference in anything. Lighting stays the same and I can't see anything that would stand out. 

Ive used Voxel, Future, ShadowMap. 

ShadowMap has worked but is now refusing to work.

**Comment by GoingCrazyDude** [comment]
Press shift + f2 and check if its being set in the first place

**Comment by Hasninai** [comment]
I have done shift + f2, no difference.

**Comment by Hasninai** [comment]
On the dropdown? yes

**Comment by GoingCrazyDude** [comment]
Im asking in game

**Comment by Hasninai** [comment]
How do I check that?

**Comment by GoingCrazyDude** [comment]
I told you, Shift + F2

**Comment by GoingCrazyDude** [comment]
press shift f2 in a game and send a screenshot please

**Comment by GoingCrazyDude** [comment]
What lighting technology are you using?

**Comment by Hasninai** [comment]
Im using Future

**Comment by Hasninai** [comment]
They were already at max

**Comment by GoingCrazyDude** [comment]
Then they are working

**Comment by Hasninai** [comment]
Im comparing and theres 0 differences

**Comment by GoingCrazyDude** [comment]
The game itself is saying its using future, so it probably is

**Comment by Hasninai** [comment]
I'll try a different game then

**Comment by Hasninai** [comment]
Got it working, just needed to reinstall roblox for whatever reason.
