### ISSUE TITLE
Why are some text gone

### ISSUE THREAD

**Issue by Lifinitx** [pizzaboxer/bloxstrap#627]
when i play games some of the text are not there
![Screenshot (423)](https://github.com/pizzaboxer/bloxstrap/assets/143779497/82b35386-a3d5-4b6e-be19-0616c7bc1dd2)

**Comment by GoingCrazyDude** [comment]
does this happen when using normal roblox?

**Comment by Lifinitx** [comment]
idk

**Comment by Lifinitx** [comment]
i'll use normal

**Comment by Lifinitx** [comment]
it does also happen in normal roblox

**Comment by GoingCrazyDude** [comment]
yeah so its not bloxstrap, its a roblox bug

**Comment by GoingCrazyDude** [comment]
most probably the game itself

**Comment by Lifinitx** [comment]
can i fix it

**Comment by Lifinitx** [comment]
![sap2](https://github.com/pizzaboxer/bloxstrap/assets/143779497/682d4a2d-6402-488b-bd9d-12201af732cb)

**Comment by pizzaboxer** [comment]
Someone else reported this same issue a few hours ago, and they fixed it by adjusting the performance settings of their GPU. They were using Intel integrated graphics, and they had to change their 3D preferences to prioritize quality over performance, so it might be that in your case, or something similar at least.
