### ISSUE TITLE
why doesnt it show the game im playing in my status? 

### ISSUE THREAD

**Issue by JITFOLKFR5656** [pizzaboxer/bloxstrap#628]
![image](https://github.com/pizzaboxer/bloxstrap/assets/143780207/0263a572-b2c4-446e-ace1-d50591045228)

**Comment by GoingCrazyDude** [comment]
dude i asked you to send the log file in the discord server

**Comment by pizzaboxer** [comment]
Still waiting...

**Comment by cattotaco** [comment]
this also happens to me for some reason, game details are not present, it just shows that im playing Roblox and thats it

**Comment by pizzaboxer** [comment]
Alright, glad you've let me know about this. Can you send Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` here please?
