### ISSUE TITLE
bloxstrap doesn't open at all

### ISSUE THREAD

**Issue by billybob843** [pizzaboxer/bloxstrap#630]
i just downloaded it, and when i try to open it, it opens for 1 second and instantly crashes
i have tried turning on antiviruses and anything else but it doesn't work at all

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it ?

**Comment by DAMIOSKIDEV** [comment]
I have the same issue, I get a "Starting Roblox" screen and then nothing. I have some information on Event Viewer and the official version of Roblox doesn't work either.

```
Faulting application name: RobloxPlayerBeta.exe, version: 0.592.0.22347, time stamp: 0x87d20afb
Faulting module name: RobloxPlayerBeta.dll, version: 0.0.0.0, time stamp: 0x905d37fd
Exception code: 0xc0000005
Fault offset: 0x0000000002895b97
Faulting process id: 0x0x3BC8
Faulting application start time: 0x0x1D9DD2B55B9813D
Faulting application path: C:\Users\enzoz\AppData\Local\Roblox\Versions\version-2543a73b8b7d4e40\RobloxPlayerBeta.exe
Faulting module path: C:\Users\enzoz\AppData\Local\Roblox\Versions\version-2543a73b8b7d4e40\RobloxPlayerBeta.dll
Report Id: 3375eba5-6c06-44f9-99b8-e0903629745a
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by pizzaboxer** [comment]
> I have the same issue, I get a "Starting Roblox" screen and then nothing. 

This is not the same issue. They're saying Bloxstrap doesn't open at all. By the way, see https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch.

**Comment by billybob843** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it ?

nope. doesnt work

**Comment by pizzaboxer** [comment]
> nope. doesnt work

Can you just clarify on your issue for a second - is it Bloxstrap that doesn't open, or is it Roblox that doesn't open?

**Comment by billybob843** [comment]
> > nope. doesnt work
> 
> Can you just clarify on your issue for a second - is it Bloxstrap that doesn't open, or is it Roblox that doesn't open?

it is bloxstrap.

**Comment by DAMIOSKIDEV** [comment]
> > nope. doesnt work
> 
> Can you just clarify on your issue for a second - is it Bloxstrap that doesn't open, or is it Roblox that doesn't open?

It's a Roblox problem, not a Bloxstrap one.

**Comment by pizzaboxer** [comment]
> it is bloxstrap.

Were you able to install it?

**Comment by billybob843** [comment]
> > nope. doesnt work
> 
> Can you just clarify on your issue for a second - is it Bloxstrap that doesn't open, or is it Roblox that doesn't open?

it is bloxstrap

**Comment by altacountbabi** [comment]
> I have the same issue, I get a "Starting Roblox" screen and then nothing. I have some information on Event Viewer and the official version of Roblox doesn't work either.
> 
> ```
> Faulting application name: RobloxPlayerBeta.exe, version: 0.592.0.22347, time stamp: 0x87d20afb
> Faulting module name: RobloxPlayerBeta.dll, version: 0.0.0.0, time stamp: 0x905d37fd
> Exception code: 0xc0000005
> Fault offset: 0x0000000002895b97
> Faulting process id: 0x0x3BC8
> Faulting application start time: 0x0x1D9DD2B55B9813D
> Faulting application path: C:\Users\enzoz\AppData\Local\Roblox\Versions\version-2543a73b8b7d4e40\RobloxPlayerBeta.exe
> Faulting module path: C:\Users\enzoz\AppData\Local\Roblox\Versions\version-2543a73b8b7d4e40\RobloxPlayerBeta.dll
> Report Id: 3375eba5-6c06-44f9-99b8-e0903629745a
> Faulting package full name: 
> Faulting package-relative application ID: 
> ```

same issue

**Comment by pizzaboxer** [comment]
> it is bloxstrap

Well, okay. What if you try installing with Winget? Open a Command Prompt window and type in `winget install bloxstrap`, see if that works.

**Comment by billybob843** [comment]
> > it is bloxstrap
> 
> Well, okay. What if you try installing with Winget? Open a Command Prompt window and type in `winget install bloxstrap`, see if that works.

it installed and it works, thank you

**Comment by Tr3yWay996** [comment]
> > it is bloxstrap
> 
> Well, okay. What if you try installing with Winget? Open a Command Prompt window and type in `winget install bloxstrap`, see if that works.

Man how the fuck ive been doing this from the start and nothing changed ahhhhh pelase help
