### ISSUE TITLE
lightning system doesnt work

### ISSUE THREAD

**Issue by cellat1** [pizzaboxer/bloxstrap#633]
when i choose the voxel and future nothing changes v2.5.2

**Comment by GoingCrazyDude** [comment]
Press shift + f2 in a game and send a screenshot

also stop opening so many issues

**Comment by cellat1** [comment]
Tezos Biswa Borah ***@***.***>, 1 Eyl 2023 Cum, 23:16
tarihinde şunu yazdı:

**Comment by GoingCrazyDude** [comment]
Excuse me what?

**Comment by cellat1** [comment]
you wanted screenshot

1 Eyl 2023 Cum 23:33 tarihinde Tezos Biswa Borah ***@***.***>
şunu yazdı:

**Comment by GoingCrazyDude** [comment]
Yeah but you attached nothing

**Comment by cellat1** [comment]
can you see now
1 Eyl 2023 Cum 23:35 tarihinde Tezos Biswa Borah ***@***.***>
şunu yazdı:

**Comment by GoingCrazyDude** [comment]
You have still sent nothing. Go to this link https://github.com/pizzaboxer/bloxstrap/issues/633 and drag and drop the image on the textbox

**Comment by cellat1** [comment]
![Ekran Görüntüsü (14)](https://github.com/pizzaboxer/bloxstrap/assets/68362042/5cb3767d-10de-4f48-99b1-35e5229398ed)

**Comment by GoingCrazyDude** [comment]
Lighting is working fine, You can see Voxel is being used.

**Comment by cellat1** [comment]
yeah but i choose future

**Comment by GoingCrazyDude** [comment]
Use Direct3D11 and set the lighting to future and see if that fixes it.

**Comment by cellat1** [comment]
didnt work

**Comment by GoingCrazyDude** [comment]
Can you send a screenshot?

**Comment by cellat1** [comment]
YAY FİXED OMG THANK YOU
