### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by MaaVrickE** [pizzaboxer/bloxstrap#637]
The menus (version 4 ,version3 and more) dont work …so should i use the browser roblox or desktop or microsoft store??

**Comment by GoingCrazyDude** [comment]
Bloxstrap cant use the microsoft store version, launch bloxstrap from the "Play Roblox" shortcut.
Search for "Play Roblox" in windows search and click the one with the bloxstrap icon

**Comment by MaaVrickE** [comment]
What about the chrome?

**Comment by GoingCrazyDude** [comment]
See [this](https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap)

**Comment by MaaVrickE** [comment]
Alr thx
