### ISSUE TITLE
What is the best display options?

### ISSUE THREAD

**Issue by MaaVrickE** [pizzaboxer/bloxstrap#638]
What are the best options as im completely new to bloxstrap and downloaded it yesterday,so i have no idea what are the best options

**Comment by MaaVrickE** [comment]
Can someone pls answer?

**Comment by pizzaboxer** [comment]
> Can someone pls answer?

I just give the options, I wouldn't know what works best for you. Maybe someone else would be able to provide some input.

**Comment by MaaVrickE** [comment]
> > Can someone pls answer?
> 
> I just give the options, I wouldn't know what works best for you. Maybe someone else would be able to provide some input.

I would take any which r good so pls tell

**Comment by Mugetsu895** [comment]
2013 mouse cursor looks pretty good to me u can also use the 2020 escape menu its a little better imo
if this is what u mean by display options u can just test the bloxstrap features out

**Comment by MakeSureDudeDies** [comment]
> 2013 mouse cursor looks pretty good to me u can also use the 2020 escape menu its a little better imo if this is what u mean by display options u can just test the bloxstrap features out

2008 cursor was the best fr fr ong?

**Comment by Mugetsu895** [comment]
2013 cursor just looks more precise tbh

**Comment by MaaVrickE** [comment]
> What are the best options as im completely new to bloxstrap and downloaded it yesterday,so i have no idea what are the best options

Im talking abt display options btw

**Comment by Mugetsu895** [comment]
display options?
![image](https://github.com/pizzaboxer/bloxstrap/assets/142404890/7ff2c405-392c-401c-87ac-214a92496dbb)

**Comment by MaaVrickE** [comment]
I mean the things which affect ur display performance On 4 Sep 2023, at 16:33, Mugetsu895 ***@***.***> wrote:﻿
display options?

**Comment by MaaVrickE** [comment]
> display options?
> ![image](https://user-images.githubusercontent.com/142404890/265500480-7ff2c405-392c-401c-87ac-214a92496dbb.png)

I meant things which affect ur performance

**Comment by Mugetsu895** [comment]
idk try messing with the rendering mode and the lighting technology

**Comment by pizzaboxer** [comment]
I'll drop in here and say Voxel lighting should give you the best performance
