### ISSUE TITLE
Windows Tab Help Required

### ISSUE THREAD

**Issue by IntelligentKek** [pizzaboxer/bloxstrap#639]
Guys My Win Key is not working at all and Bloxstrap Menu Cant be Opened (Tried with Mouse and still no). Can you guy make an alternative method of Opening bloxstrap menu ?

**Comment by pizzaboxer** [comment]
What? I don't get it. Why can't you open it?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
