### ISSUE TITLE
It doesn't preview the pictures?

### ISSUE THREAD

**Issue by NKDaiyamondo** [pizzaboxer/bloxstrap#640]
![RobloxScreenShot20230903_184252636](https://github.com/pizzaboxer/bloxstrap/assets/136238096/ba0a3cb8-2081-4e4e-9eb2-6112a8eb9712)
Idk what to say but when without Bloxstrap It can be preview

**Comment by PrivateDataStorage** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/139368347/3fa8b6eb-1b55-46ba-96eb-14382becb1ca)
i don't know if this is the same issue, but on the left side where it says "DE, US" and more, normally there are country flags but once i installed bloxstrap it shows it like in the image above.

**Comment by Mugetsu895** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/142404890/a9f294f9-2452-4c21-8840-1852cca485b9)
maybe u use this flag too

**Comment by altacountbabi** [comment]
> ![image](https://user-images.githubusercontent.com/142404890/265271055-a9f294f9-2452-4c21-8840-1852cca485b9.png) maybe u use this flag too

Can confirm that that flag can break viewports, its very annoying

**Comment by PrivateDataStorage** [comment]
> ![image](https://user-images.githubusercontent.com/142404890/265271055-a9f294f9-2452-4c21-8840-1852cca485b9.png) maybe u use this flag too

nope

**Comment by Mugetsu895** [comment]
does it happen in other games

**Comment by PrivateDataStorage** [comment]
> does it happen in other games

to my knowledge, no. it doesn't. however i have contacted people that do not use Bloxstrap and for them it works perfectly fine.

**Comment by Mugetsu895** [comment]
hmmmm idk then lol

**Comment by PrivateDataStorage** [comment]
> ![image](https://user-images.githubusercontent.com/139368347/265265487-3fa8b6eb-1b55-46ba-96eb-14382becb1ca.png) i don't know if this is the same issue, but on the left side where it says "DE, US" and more, normally there are country flags but once i installed bloxstrap it shows it like in the image above.

![image](https://github.com/pizzaboxer/bloxstrap/assets/139368347/6becebdc-a4b0-4c2c-8c81-d229ed54a348)
Okay, i have found out why it isn't working. seems like Windows 11 Emojis doesnt have country flags yet

**Comment by Mugetsu895** [comment]
oh that makes sense bruh

**Comment by pizzaboxer** [comment]
> nope

Are you sure? Can you show a picture of your FastFlag list through the FastFlag editor?

**Comment by PrivateDataStorage** [comment]
> > nope
> 
> Are you sure? Can you show a picture of your FastFlag list through the FastFlag editor?

![image](https://github.com/pizzaboxer/bloxstrap/assets/139368347/43b1ade4-e239-446c-a480-1863c04c42f0)

**Comment by pizzaboxer** [comment]
Show the whole list.

**Comment by PrivateDataStorage** [comment]
> Show the whole list.

![image](https://github.com/pizzaboxer/bloxstrap/assets/139368347/2cf61d3a-640b-426f-81f5-01700d528520)
![image](https://github.com/pizzaboxer/bloxstrap/assets/139368347/4a0c2d04-6351-4bd4-a3f9-37b547e63c97)
thats all

**Comment by pizzaboxer** [comment]
Delete the flag for DebugForceMSAASamples completely, save, see if that changes anything.

**Comment by PrivateDataStorage** [comment]
> Delete the flag for DebugForceMSAASamples completely, save, see if that changes anything.
sorry for the late respond, nope it does not change anything

**Comment by PrivateDataStorage** [comment]
> > Delete the flag for DebugForceMSAASamples completely, save, see if that changes anything.
> > sorry for the late respond, nope it does not change anything

nothing changed, sorry for the late reply

**Comment by pizzaboxer** [comment]
Oh wait, I thought you were OP.

🤦‍♀️This is what happens when you start talking about your issues in threads that have nothing to do with your problem.

**Comment by PrivateDataStorage** [comment]
> Oh wait, I thought you were OP.
> 
> 🤦‍♀️This is what happens when you start talking about your issues in threads that have nothing to do with your problem. Go and open a new one.

as i have said in the top reply i was not sure if it was the same issue but it was very similar (atleast to me) but okay.

will open a new one later

**Comment by pizzaboxer** [comment]
> will open a new one later

Actually, nevermind, you already found the cause.

>  Okay, i have found out why it isn't working. seems like Windows 11 Emojis doesnt have country flags yet

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
