### ISSUE TITLE
Roblox wont open

### ISSUE THREAD

**Issue by VillivnarXD** [pizzaboxer/bloxstrap#645]
Roblox wasnt opening (opening as background process) i fixed it somehow but "play roblox" bloxstrap just wont open it shows the loading thing but it dosent open no matter what

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch ?

**Comment by VillivnarXD** [comment]
bro roblox was opening but when i installed bloxstrap it stopped working

**Comment by pizzaboxer** [comment]
Even when you try using the normal launcher?

**Comment by VillivnarXD** [comment]
Yes when i installed bloxstrap bloxstrap wouldnt open now normal dosent too..

**Comment by danrhodes-idk** [comment]
Similar case, but just wait till roblox updates because it's their fault

**Comment by VillivnarXD** [comment]
Any fixes pls? Im not using rtss or afterburner

**Comment by danrhodes-idk** [comment]
Patience I guess

**Comment by CaptainJokes** [comment]
ughhhh. same thing, its just showing me Connecting To ROBLOX, sometimes it launches.

**Comment by BokBoy** [comment]
@VillivnarXD Architecture of CPU?? ARM64 doesn't work (it took me and pizzaboxer a while)

**Comment by pizzaboxer** [comment]
No, your problem was that you were running it in a virtual machine.

**Comment by BokBoy** [comment]
How do we know it’s just virtual machines??
Have we tried in the sq chip??
Besides, arm isn’t gonna work well because it is requesting for the .net x64 but not arm64.
I wish I could try it but I gave up on dual booting windows on m2 mac

**Comment by Cyber2525** [comment]
windows 11 canary chanel

**Comment by pizzaboxer** [comment]
> How do we know it’s just virtual machines??

Because that's what part of Hyperion's job is?

**Comment by pizzaboxer** [comment]
I'll close this since there isn't really anything I can do here, and discussion should've moved to #635 anyway.
