### ISSUE TITLE
Fps isnt working for me

### ISSUE THREAD

**Issue by Ilikeissues** [pizzaboxer/bloxstrap#646]

**Comment by Ilikeissues** [comment]
Yes

**Comment by Ilikeissues** [comment]
i put it too 240 and am still at 31-21 fps

**Comment by lx11m** [comment]
Ur pc isn't that good than
Sorry

> i put it too 240 and am still at 31-21 fps

**Comment by pizzaboxer** [comment]
> i put it too 240 and am still at 31-21 fps

The option is named framerate ***limit***. The framerate you get depends on how good your PC is.
