### ISSUE TITLE
major fps drops

### ISSUE THREAD

**Issue by exexic** [pizzaboxer/bloxstrap#647]
whenever i play a game my fps drops to 60-70-80 (im on 90 fps)

**Comment by pizzaboxer** [comment]
Okay? Depending on your hardware, that's probably to be expected. What's your PC specs?

**Comment by ImLoadingUuU** [comment]
i guess he changed graphics into FIB. maybe you can try change graphics into ShadowMap or Voxel?

**Comment by pizzaboxer** [comment]
Oh, good point, I forgot to ask them for their FastFlag configuration.

So anyway, open the Bloxstrap menu and show a picture of the FastFlags tab.

**Comment by exexic** [comment]
> Okay? Depending on your hardware, that's probably to be expected. What's your PC specs?

Firstly, im sorry for not responding for a long time lol, anyway

cpu: intel i5 4590
gpu: 1050 ti
ram: 8gb

**Comment by exexic** [comment]
> Oh, good point, I forgot to ask them for their FastFlag configuration.
> 
> So anyway, open the Bloxstrap menu and show a picture of the FastFlags tab.

![faaaax](https://github.com/pizzaboxer/bloxstrap/assets/144358552/0e5a8f7b-3d22-4c03-b87b-7e0dc1d94d1f)
![ggggggga](https://github.com/pizzaboxer/bloxstrap/assets/144358552/757622c3-bd3a-4996-860d-a8d977bd0ff6)

**Comment by pizzaboxer** [comment]
Sorry for not getting back to you earlier on this one. 

> cpu: intel i5 4590
> gpu: 1050 ti

Yeah, if I'm being honest, that seems about right for your hardware. I don't really see anything wrong.

**Comment by ImLoadingUuU** [comment]
Try change render to DirectX. And in Nvidia control panel select "Nvidia GPU Only"

**Comment by pizzaboxer** [comment]
> Try change render to DirectX.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/6670dd30-da3a-4827-bba9-a63e9ee5528e)
