### ISSUE TITLE
bloxstrap menu not opening

### ISSUE THREAD

**Issue by rlxck** [pizzaboxer/bloxstrap#648]
so i was installing this and i needed to install that .NET 6.0 Desktop Runtime thingy so i installed it and it keeps giving me the same error
![image](https://github.com/pizzaboxer/bloxstrap/assets/144382214/54c7e98b-9453-4cd0-a003-feeae6abda6c)
i have literally installed this thing like 4-5 times already and it isnt doing anything
![image](https://github.com/pizzaboxer/bloxstrap/assets/144382214/4bfc8977-d052-41e1-8743-a5e46cefb93c)

**Comment by GoingCrazyDude** [comment]
try this
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.20-windows-x64-installer

**Comment by pizzaboxer** [comment]
> so i was installing this and i needed to install that .NET 6.0 Desktop Runtime thingy so i installed it and it keeps giving me the same error ![image](https://user-images.githubusercontent.com/144382214/266415234-54c7e98b-9453-4cd0-a003-feeae6abda6c.png) i have literally installed this thing like 4-5 times already and it isnt doing anything ![image](https://user-images.githubusercontent.com/144382214/266415456-4bfc8977-d052-41e1-8743-a5e46cefb93c.png)

Seems like a bad .NET install. Open a Command Prompt window, enter `dotnet --info`, show me what appears.

**Comment by rlxck** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/144382214/aea02171-0f73-48d1-a65a-4f2b371e3133)
this
tell me if i did anything wrong cuz i have no knowledge of coding and stuff

**Comment by pizzaboxer** [comment]
...Are you sure you installed it?

**Comment by rlxck** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/144382214/186b065e-1655-4093-9dbd-88faf98ec110)
it is literally right there

**Comment by pizzaboxer** [comment]
All you're showing is that you downloaded it. Did you actually install it?

**Comment by rlxck** [comment]
yea but i deleted and reinstalled it and now it works fine for some reason idk
