### ISSUE TITLE
A problem with vulkan rendering 

### ISSUE THREAD

**Issue by Albinftw** [pizzaboxer/bloxstrap#651]
Whenever i use vulkan as the rendering it acts kind of like an overlay instead of fullscreen. so basically you can't open the windows menu or see any programs beside the game. Is there any possible fix or work around?

**Comment by pizzaboxer** [comment]
> so basically you can't open the windows menu or see any programs beside the game

Yeah, because it always operates in exclusive fullscreen. Your only way around it is to just not use fullscreen or use Direct3D/Automatic.
