### ISSUE TITLE
Big fps drops

### ISSUE THREAD

**Issue by Catplayz2011** [pizzaboxer/bloxstrap#652]
hi when i installed bloxtrap i was getting big fps drops before bloxtrap my fps in roblox is 10-50 but. Now it higher but i get fps drops. before bloxtrap i get no fps drops plss heeellppp

**Comment by pizzaboxer** [comment]
Can I see what settings you have configured? Open the Bloxstrap menu and show the FastFlags tab.

**Comment by Spygaming9865** [comment]
My fps is like 30 to 20 went I play criminality is like 20 so my was like 120 but now is broken pls help me fix it acc spygaming9865 this account is like 40 year now so like a hidden I make so pls help me fix it

**Comment by Spygaming9865** [comment]
I was wrong you can't fix it

**Comment by Spygaming9865** [comment]
Sorry

**Comment by ImLoadingUuU** [comment]
![MO0QEnuzEM](https://github.com/pizzaboxer/bloxstrap/assets/69704016/47061a1c-5ba6-4593-8dc9-a70b140c750d)
Please change to Voxel might make your boblox faster0

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
