### ISSUE TITLE
"An exception occurred while running bloxstrap" & System.exception: Unable to find an accessible roblox deploy mirror!"

### ISSUE THREAD

**Issue by Exorium** [pizzaboxer/bloxstrap#653]
[Bloxstrap_20230909T142626Z.log](https://github.com/pizzaboxer/bloxstrap/files/12566043/Bloxstrap_20230909T142626Z.log)
 it said to report this so here I am.

**Comment by pizzaboxer** [comment]
This is simply it just not being able to connect to the internet. Though, to be fair, it did tell you to report this. I'll fix this so it shows a connection error instead of an exception instead.
