### ISSUE TITLE
roblox refuses to go above 60FPS regardless of DFIntTaskSchedulerTargetFps

### ISSUE THREAD

**Issue by T-am3** [pizzaboxer/bloxstrap#655]
https://github.com/pizzaboxer/bloxstrap/assets/72304947/99916d21-eadb-49b2-9e99-20442239d92b

makes it LITERALLY unplayable with input delay

**Comment by pizzaboxer** [comment]
Are any of your other flag changes applying (e.g. future lighting)?

**Comment by T-am3** [comment]
those apply

**Comment by T-am3** [comment]
![Bloxstrap_TH4yXjMgPm](https://github.com/pizzaboxer/bloxstrap/assets/72304947/35ebab1a-0581-4032-99fb-e67d887d4001)
and before you ask, yes this is set to automatic (non vulkan)

**Comment by pizzaboxer** [comment]
Let me see your latest Bloxstrap log file from %localappdata%\Bloxstrap\Logs just so I can make sure.

**Comment by T-am3** [comment]
[Bloxstrap_20230909T173331Z.log](https://github.com/pizzaboxer/bloxstrap/files/12566693/Bloxstrap_20230909T173331Z.log)

**Comment by pizzaboxer** [comment]
Well, that shows you opening the menu. Join a game first, then send the log from that.

**Comment by T-am3** [comment]
[Bloxstrap_20230909T211140Z.log](https://github.com/pizzaboxer/bloxstrap/files/12566704/Bloxstrap_20230909T211140Z.log)
![RobloxPlayerBeta_epObeNvxbt](https://github.com/pizzaboxer/bloxstrap/assets/72304947/416efefb-2a11-4e5e-b996-e078174041d2)

capped at 60 fps, no issues with nvidia ctrl panel settings or bloxstrap itself

**Comment by T-am3** [comment]
![RobloxPlayerBeta_pDESjDgF1F](https://github.com/pizzaboxer/bloxstrap/assets/72304947/30b97a3d-d2f0-452f-8d7e-478c54d82850)
wild 🤯🤯🤯

**Comment by pizzaboxer** [comment]
Are you using a laptop?

**Comment by T-am3** [comment]
games unite testing place, i censored it with X cus i didnt want people to join me or anything

**Comment by T-am3** [comment]
obv the place ID was still present and i dont really care if someone joins me now lol

**Comment by pizzaboxer** [comment]
Do you happen to be using a laptop?

**Comment by T-am3** [comment]
yea i am

sometimes the MUX switch gets silly but no, roblox is running on my 3070

**Comment by pizzaboxer** [comment]
Have you checked to make sure you don't have any power/performance settings that could be throttling the framerate?

**Comment by T-am3** [comment]
![Uploading RobloxPlayerBeta_jpXkE8Qvim.png…]()

could be armory crate and its shitty ahh drivers fucking with me, ill let you know

**Comment by T-am3** [comment]
![RobloxPlayerBeta_gqUxnrQcpT](https://github.com/pizzaboxer/bloxstrap/assets/72304947/f2cb1871-8c12-4dcd-9761-eec81555f204)

ok yep, we up

ty idk why i didn't think about checking, usually i can change my performance settings from my keyboard but this time armory crate literally uninstalled itself. been having stability issues with my laptop anyways, specifically after some driver updates

don't remember which tho
