### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by aetherii** [pizzaboxer/bloxstrap#656]
![image](https://github.com/pizzaboxer/bloxstrap/assets/144575932/e854a01e-e306-49b9-a971-5919e80fee71)
I have that windows thing already installed, I'm not sure why it's happening

**Comment by pizzaboxer** [comment]
What's the latest version of it you have installed? 

![236800920-7fdb9cac-ffab-42d7-a786-5d669afb86a4](https://github.com/pizzaboxer/bloxstrap/assets/41478239/f3e910f6-748a-4066-b7b8-cf3a4f8f1591)

**Comment by aetherii** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/144575932/0aefec31-372d-4ac3-87f2-c06eacb06f55)

**Comment by pizzaboxer** [comment]
Try installing this one: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.21-windows-x64-installer?cid=getdotnetcore

**Comment by Mugetsu895** [comment]
> Try installing this one: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.21-windows-x64-installer?cid=getdotnetcore

he has both 6.0.21 and an older one

**Comment by pizzaboxer** [comment]
> he has both 6.0.21 and an older one

They have the .NET runtime for 6.0.21, not the desktop runtime for 6.0.21.

**Comment by Mugetsu895** [comment]
oh my bad then

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
