### ISSUE TITLE
ReShade options wont show up

### ISSUE THREAD

**Issue by CaptainJokes** [pizzaboxer/bloxstrap#660]
How do i fix this? i want to use shaders with Roblox.

**Comment by GoingCrazyDude** [comment]
Reshade doesnt work due to byfron and hence bloxstrap doesnt support it

**Comment by CaptainJokes** [comment]
but when did Bloxstrap stop supporting reshade?

**Comment by GoingCrazyDude** [comment]
around v2.2.0

**Comment by CaptainJokes** [comment]
ok then i will instal the older version

**Comment by GoingCrazyDude** [comment]
Did you not read what I said? Reshade will not work on roblox anymore due to byfron

**Comment by pizzaboxer** [comment]
> ok then i will instal the older version

It hasn't worked with Roblox since May. That's why it was removed from Bloxstrap.

**Comment by CaptainJokes** [comment]
also im the person who joined you (MrRainbowGuy)

**Comment by pizzaboxer** [comment]
Wow, no wonder you're annoying.
