### ISSUE TITLE
can you make the  settings menu be installed separately as a different application with bloxstrap?

### ISSUE THREAD

**Issue by domlolz** [pizzaboxer/bloxstrap#662]
my dumbass somehow didn't make a file location for it and everything so i didn't get the menu, so whenever i try to boot it up it automatically starts up roblox
![image](https://github.com/pizzaboxer/bloxstrap/assets/144637345/4acb6569-86c0-4025-8acf-11e6616bce13)
dont know if the image posted but theres no menu 
thanks

**Comment by pizzaboxer** [comment]
That's... what it's supposed to do though? Look through your application list in the Start menu instead of searching for it.

**Comment by hishro1** [comment]
> That's... what it's supposed to do though? Look through your application list in the Start menu instead of searching for it.

is it fat

**Comment by kek1ich** [comment]
Having same problem here, but instead i can't just open win-tab (tried clicking it, not worked). So would ask for A Menu to Be Different File, Separated from Usual Bloxstrap

**Comment by pizzaboxer** [comment]
> but instead i can't just open win-tab

What? What does that have to do with opening the menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
