### ISSUE TITLE
Bloxstrap Menu not opening

### ISSUE THREAD

**Issue by KJrobo809** [pizzaboxer/bloxstrap#663]
i search for the bloxstrap menu and it doesn't show up, only with the actual app itself to open up roblox. (https://prnt.sc/Jq2D3Cy9uRL-)
after reinstalling bloxstrap many times the menu wont appear.

**Comment by pizzaboxer** [comment]
Instead of using the search utility, try looking it for it by scrolling down through the application list.

**Comment by KJrobo809** [comment]
> Instead of using the search utility, try looking it for it by scrolling down through the application list.

yeah I found it now, thank you for the help.
