### ISSUE TITLE
An exeption occurred while running Bloxtrap, System.Exception: Signature does not match!

### ISSUE THREAD

**Issue by Ixlie** [pizzaboxer/bloxstrap#666]
Hey i dont know how to fix this cause when I launch Bloxtrap it upgrades and stops and then the issuse pops up and i cant open roblox or blox trap,
![image](https://github.com/pizzaboxer/bloxstrap/assets/144950346/34d23509-cfb2-4178-8b22-4500d9d73dc9)
thats the issuse and i really want to still be using Bloxtrap cause of the amazing and clean fps so please help me with this!

**Comment by OnAChromebookRn** [comment]
send the log file

**Comment by pizzaboxer** [comment]
Only thing I can suggest you do is that you restart your PC. Let me know if you're still having issues after that.

**Comment by Ixlie** [comment]
> Only thing I can suggest you do is that you restart your PC. Let me know if you're still having issues after that.

Hey its working now after I uninstalled it and reinstalled it and restarted because I launch it with 144 fps and then updated to setting for higher fps and now its working! thank you and I will let u know if it happens again:)

**Comment by andaubuoi** [comment]
![Capturek](https://github.com/pizzaboxer/bloxstrap/assets/129636774/61a708f1-1f87-4373-8ed5-c140e454dc0e)
how can i fix it bro

**Comment by pizzaboxer** [comment]
>  how can i fix it bro

Open a new thread, do not just comment in some random one.

**Comment by PROLERXZ** [comment]
same problem i got that error few hours ago then after i fixed things then it stopped but my roblox says its running even tho it isnt in the task manager

**Comment by zenooooooooooooo** [comment]
bro it wont work Atal I tried resetting my pc and I tried to redownload it nothing works and please fix this issue

**Comment by lkasdhi1** [comment]
![image](https://github.com/user-attachments/assets/a6369961-2266-4b54-9a25-cba048c11b0c)
why does this happen
