### ISSUE TITLE
Alternate Graphic Quality selector isn't working.

### ISSUE THREAD

**Issue by Surfurr** [pizzaboxer/bloxstrap#669]
I selected this option when I was installing bloxstrap but when I log into games it doesn't seem to be working and since its gone, I have tried to reinstall it yet to no avail.

**Comment by pizzaboxer** [comment]
Do any of your other options apply, like the FPS limiter?

**Comment by Surfurr** [comment]
> Do any of your other options apply, like the FPS limiter?
I will be closing the issue since I've fixed it by simply restarting the system idk why, but yeah its fine now
