### ISSUE TITLE
[feature request] Linux support!

### ISSUE THREAD

**Issue by tawnylure** [pizzaboxer/bloxstrap#670]
Seeing as roblox now works on linux, it would be nice to have bloxstrap as a bootstrapper for linux, I know things like vinegar and grapejuice exist but they don't really provide a good gui for easy customization. 

Just something to consider as more and more users start using linux over windows.

**Comment by pizzaboxer** [comment]
That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.

**Comment by 32bitx64bit** [comment]
> That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.

Ah I see, I was redirected here by the comment you sent.

I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.

Hopefully we can get support sooner or later for linux, cheerio :D

**Comment by Sahelantrophus** [comment]
use windows like a normal person

**Comment by 32bitx64bit** [comment]
> use windows like a normal person

Uh why? Why would I whiling use a worse OS, that is not to mention filled with adware and spyware.

Like yes! I love being stalked not only on the internet but by my own operating system too!

**Comment by PrivateDataStorage** [comment]
> > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> 
> Ah I see, I was redirected here by the comment you sent.
> 
> I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> 
> Hopefully we can get support sooner or later for linux, cheerio :D

"windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.

"and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?

Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.

Just pick once which fits you better. Linux for work and Windows for games.

**Comment by tawnylure** [comment]
> > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > 
> > 
> > Ah I see, I was redirected here by the comment you sent.
> > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > Hopefully we can get support sooner or later for linux, cheerio :D
> 
> "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> 
> "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> 
> Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> 
> Just pick once which fits you better. Linux for work and Windows for games.

Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.

And you want to know how many people play roblox  on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux.
Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.

Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be.
Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.

Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.

Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.

**Comment by WaviestBalloon** [comment]
I've been working on a project called Applejuice, it's like Grapejuice but it bootstraps and uses Proton (VALVE's Wine fork) instead of Wine, I hope to also add features just like what Bloxstrap has, including it's own RPC which pizza has been helping me with!

The project is super new and the current benefits are that it uses Proton over Wine, installing deployments are much much faster than using Roblox's bootstrapper, RPC (uncomplete), light-weight (CLI binary is under 10 MB), full-control (you can decide if you want to update Roblox if there is one available or just stick to being out-dated + the ability to downgrade to different deployment versions) and more to come hopefully.
We plan to write a interface for it after we finish the CLI. :3

https://github.com/WaviestBalloon/ApplejuiceCLI

**Comment by GoingCrazyDude** [comment]
> I've been working on a project called Applejuice, it's like Grapejuice but it bootstraps and uses Proton (VALVE's Wine fork) instead of Wine, I hope to also add features just like what Bloxstrap has, including it's own RPC which pizza has been helping me with!
> 
> The project is super new and the current benefits are that it uses Proton over Wine, installing deployments are much much faster than using Roblox's bootstrapper, RPC (uncomplete), light-weight (CLI binary is under 10 MB), full-control (you can decide if you want to update Roblox if there is one available or just stick to being out-dated + the ability to downgrade to different deployment versions) and more to come hopefully. We plan to write a interface for it after we finish the CLI. :3
> 
> https://github.com/WaviestBalloon/ApplejuiceCLI

SHAMELESS PLUG ALERT!!!!!!
Jokes aside looks like a really cool project. Will definitely try it out :D

**Comment by WaviestBalloon** [comment]
> SHAMELESS PLUG ALERT!!!!!! Jokes aside looks like a really cool project. Will definitely try it out :D

I think pizza is fine with it :3

**Comment by Sahelantrophus** [comment]
> > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > 
> > > 
> > > Ah I see, I was redirected here by the comment you sent.
> > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > Hopefully we can get support sooner or later for linux, cheerio :D
> > 
> > 
> > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > Just pick once which fits you better. Linux for work and Windows for games.
> 
> Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> 
> And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> 
> Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> 
> Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> 
> Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.

they having a nerdoff

**Comment by WaviestBalloon** [comment]
> > > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > > 
> > > > 
> > > > Ah I see, I was redirected here by the comment you sent.
> > > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > > Hopefully we can get support sooner or later for linux, cheerio :D
> > > 
> > > 
> > > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > > Just pick once which fits you better. Linux for work and Windows for games.
> > 
> > 
> > Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> > And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> > Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> > Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> > Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.
> 
> they having a nerdoff

https://www.reddit.com/r/linuxsucks/

**Comment by GoingCrazyDude** [comment]
> > > > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > > > 
> > > > > 
> > > > > Ah I see, I was redirected here by the comment you sent.
> > > > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > > > Hopefully we can get support sooner or later for linux, cheerio :D
> > > > 
> > > > 
> > > > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > > > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > > > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > > > Just pick once which fits you better. Linux for work and Windows for games.
> > > 
> > > 
> > > Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> > > And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> > > Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> > > Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> > > Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.
> > 
> > 
> > they having a nerdoff
> 
> https://www.reddit.com/r/linuxsucks/

Imma make this quote reply chain longer

**Comment by Sahelantrophus** [comment]
https://github.com/pizzaboxer/bloxstrap/assets/135360571/878ebcee-4192-4925-8a5c-dc48097bc002

**Comment by PrivateDataStorage** [comment]
> > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > 
> > > 
> > > Ah I see, I was redirected here by the comment you sent.
> > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > Hopefully we can get support sooner or later for linux, cheerio :D
> > 
> > 
> > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > Just pick once which fits you better. Linux for work and Windows for games.
> 
> Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> 
> And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> 
> Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> 
> Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> 
> Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.

I never meant to be hostile, me myself likes linux, i just use windows because it has more support. oh yeah and also because im lazy to download an entirely new OS and switch my files over haha

you adding a dislike emoji to my reply really shows how you like my post! i appreciate it! 😀

"to support xbox yet not linux." 
Roblox has already said that they're adding Linux Support. if not, it already has been added. (SoUrce: Bitdancer on DevForum)

"Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games."

Where did you get that number from?? Literally almost every Open-Source program i go to does NOT support linux.

"Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across"

quite ironic as you basically just shitted on my reply lol


Nerdoff out!!!!! i will not reply any further :)

**Comment by LanSchooI** [comment]
KW - God Got Me Freestyle (Track Ref 210513)
https://krakenfiles.com/view/VzksdzhAXv/file.html

**Comment by GoingCrazyDude** [comment]
> KW - God Got Me Freestyle (Track Ref 210513) https://krakenfiles.com/view/VzksdzhAXv/file.html

Thanks man I couldnt find this

**Comment by jigguz** [comment]
Come to Life random guitar version stems https://we.tl/t-5rM34Qg5Jr

**Comment by WaviestBalloon** [comment]
https://niko.wav.blue/

**Comment by tawnylure** [comment]
what the fuck has this become, my email has just been blown up.

**Comment by tawnylure** [comment]
> > > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > > 
> > > > 
> > > > Ah I see, I was redirected here by the comment you sent.
> > > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > > Hopefully we can get support sooner or later for linux, cheerio :D
> > > 
> > > 
> > > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > > Just pick once which fits you better. Linux for work and Windows for games.
> > 
> > 
> > Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> > And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> > Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> > Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> > Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.
> 
> I never meant to be hostile, me myself likes linux, i just use windows because it has more support. oh yeah and also because im lazy to download an entirely new OS and switch my files over haha
> 
> you adding a dislike emoji to my reply really shows how you like my post! i appreciate it! 😀
> 
> "to support xbox yet not linux." Roblox has already said that they're adding Linux Support. if not, it already has been added. (SoUrce: Bitdancer on DevForum)
> 
> "Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games."
> 
> Where did you get that number from?? Literally almost every Open-Source program i go to does NOT support linux.
> 
> "Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across"
> 
> quite ironic as you basically just shitted on my reply lol
> 
> Nerdoff out!!!!! i will not reply any further :)



> > > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > > 
> > > > 
> > > > Ah I see, I was redirected here by the comment you sent.
> > > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > > Hopefully we can get support sooner or later for linux, cheerio :D
> > > 
> > > 
> > > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > > Just pick once which fits you better. Linux for work and Windows for games.
> > 
> > 
> > Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> > And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> > Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> > Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> > Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.
> 
> I never meant to be hostile, me myself likes linux, i just use windows because it has more support. oh yeah and also because im lazy to download an entirely new OS and switch my files over haha
> 
> you adding a dislike emoji to my reply really shows how you like my post! i appreciate it! 😀
> 
> "to support xbox yet not linux." Roblox has already said that they're adding Linux Support. if not, it already has been added. (SoUrce: Bitdancer on DevForum)
> 
> "Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games."
> 
> Where did you get that number from?? Literally almost every Open-Source program i go to does NOT support linux.
> 
> "Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across"
> 
> quite ironic as you basically just shitted on my reply lol
> 
> Nerdoff out!!!!! i will not reply any further :)

Number comes from how many applications work on WINE, it would be pretty easy to pickup on that context.

And dev forum said Wine support, they said they had ZERO plans on adding N A T I V E linux support, they added wine support back.

do research, please. its making my brain huurt

**Comment by tawnylure** [comment]
also jesus, this reply thread is getting too long

**Comment by jigguz** [comment]
SHUT UP NIGGA NOBODY CARES BOUT LINUX OR DAT NERD SHIT REAL TRAPPERS USE WINDOWS IMAGINE BEING PUSSY CUZ WINDOWS "HAS HELLA BLOAT AND SPYWARE" I THOUGHT YALL WASNT PUSSY BUT APPARENTLYY NOT HAHAHAHAHHA NIGGER

**Comment by PrivateDataStorage** [comment]
> > > > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > > > 
> > > > > 
> > > > > Ah I see, I was redirected here by the comment you sent.
> > > > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > > > Hopefully we can get support sooner or later for linux, cheerio :D
> > > > 
> > > > 
> > > > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > > > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > > > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > > > Just pick once which fits you better. Linux for work and Windows for games.
> > > 
> > > 
> > > Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> > > And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> > > Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> > > Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> > > Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.
> > 
> > 
> > I never meant to be hostile, me myself likes linux, i just use windows because it has more support. oh yeah and also because im lazy to download an entirely new OS and switch my files over haha
> > you adding a dislike emoji to my reply really shows how you like my post! i appreciate it! 😀
> > "to support xbox yet not linux." Roblox has already said that they're adding Linux Support. if not, it already has been added. (SoUrce: Bitdancer on DevForum)
> > "Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games."
> > Where did you get that number from?? Literally almost every Open-Source program i go to does NOT support linux.
> > "Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across"
> > quite ironic as you basically just shitted on my reply lol
> > Nerdoff out!!!!! i will not reply any further :)
> 
> > > > > > That's definitely not happening anytime soon. I don't even support Mac yet. I'd only consider this if I'm ever working on a full-blown rewrite or something completely new, and I definitely do not have the time for that right now.
> > > > > 
> > > > > 
> > > > > Ah I see, I was redirected here by the comment you sent.
> > > > > I can see your point, just something to consider in the future, especially sense windows gets more shit every day, and more people decide to say "screw this" and switch to linux.
> > > > > Hopefully we can get support sooner or later for linux, cheerio :D
> > > > 
> > > > 
> > > > "windows gets shit more every day" is literally an invalid argurment, sometimes u see really cool features that are being released.
> > > > "and more people decide to say "screw this" and switch to linux." honestly. why. i wouldn't switch to linux because most games and programs (like bloxstrap) don't support it. also.. did you know that only around 200k people use linux for roblox?
> > > > Most windows vs linux argurments don't even make sense nowdays. all i heard so far is "more customization!!!!!!!", "no bloatware or spyware!!!" n stuff which are pretty much invalid.
> > > > Just pick once which fits you better. Linux for work and Windows for games.
> > > 
> > > 
> > > Windows getting shittery by the day isn't a invalid argument because they release the 1 good feature to fix their terrible launch of windows 11, it is a shitty operating, invalidating a argument without any good reason just makes your entire point worthless. And doesn't help push your point as its actively being hostile, and calling the person wrong.
> > > And you want to know how many people play roblox on xbox? about 500 - 700k, so that 200k linux user base seems pretty big considering they are whiling to support xbox yet not linux. Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games.
> > > Most windows arguments? Its almost like its true, in linux you have ultimate control over your os, you choose your theme, or even MAKE your own theme to fit your style, not to mention linux doesn't have spyware to the extent of windows, some distro's do have data collection solely for helping the developers debug. But its much better then windows will ever be. Have you ever RAN a debloated, despywared windows? it legit runs 3x faster, microsoft is purposefully making their OS bad.
> > > Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across, and do atleast a hint of research, most of what you said was just blatantly wrong, or was correct but looks good for linux in context.
> > > Anyways I probably wont respond further, as I don't see the need in wasting time arguing over if linux or windows is better, its pretty obvious the better OS is indeed linux, it just needs software support (native software support) and game support (Native) to realize that.
> > 
> > 
> > I never meant to be hostile, me myself likes linux, i just use windows because it has more support. oh yeah and also because im lazy to download an entirely new OS and switch my files over haha
> > you adding a dislike emoji to my reply really shows how you like my post! i appreciate it! 😀
> > "to support xbox yet not linux." Roblox has already said that they're adding Linux Support. if not, it already has been added. (SoUrce: Bitdancer on DevForum)
> > "Also you saying that most apps just dont work on linux is blatantly wrong, and clearly comes form someone with zero knowledge of the topic, about 80% - 90% of apps actually do work on linux, and its about the same if not higher for games."
> > Where did you get that number from?? Literally almost every Open-Source program i go to does NOT support linux.
> > "Like jesus, if you're going to make a argument to use windows atleast provide a good one, invalidating other peoples points isn't the best way to get your point across"
> > quite ironic as you basically just shitted on my reply lol
> > Nerdoff out!!!!! i will not reply any further :)
> 
> Number comes from how many applications work on WINE, it would be pretty easy to pickup on that context.
> 
> And dev forum said Wine support, they said they had ZERO plans on adding N A T I V E linux support, they added wine support back.
> 
> do research, please. its making my brain huurt

"Number comes from how many applications work on WINE, it would be pretty easy to pickup on that context."

what are you even replying to

"And dev forum said Wine support, they said they had ZERO plans on adding N A T I V E linux support, they added wine support back."

ah my bad.

"do research, please. its making my brain huurt"

have u ever heard of people making mistakes??? goshdamn ur so butthurt
