### ISSUE TITLE
Bloxtrap launches but roblox desktop app doesn't show up and remains running in the background

### ISSUE THREAD

**Issue by Eletroclip** [pizzaboxer/bloxstrap#671]
https://github.com/pizzaboxer/bloxstrap/assets/49120766/3bbcca8b-fefe-4dc6-9218-11e836f90456

**Comment by Langovskyy** [comment]
I changed renderer to Automatic and it works again (was using Vulkan before)

**Comment by Eletroclip** [comment]
Thanks it worked! But I want to use Vulkan because it works better with my gpu. Any ideias how to solve this issue so I can continue to use Vulkan?

**Comment by Eletroclip** [comment]
Note: Vulkan works with Regular Roblox Bootstrapper! Only with Bloxstrap that it doesn't!

**Comment by ZintSqulp** [comment]
issue might be caused by recent nvidia driver update, happened to me after update.

**Comment by Eletroclip** [comment]
Thanks for the info! I will try to rollback the update and see if it works!

**Comment by pizzaboxer** [comment]
Yep, you'll have to stay on Vulkan.

**Comment by Eletroclip** [comment]
Tried to rollback the drivers but the issue persists!
