### ISSUE TITLE
Mouse becoming invisible

### ISSUE THREAD

**Issue by Mevillius** [pizzaboxer/bloxstrap#673]
when im on fullscreen its just invisible, dont know why

**Comment by Mevillius** [comment]
https://hastebin.com/share/ayisenatav.json

my current fflags

**Comment by pizzaboxer** [comment]
Are you using exclusive fullscreen?

**Comment by Mevillius** [comment]
I assume i am not, since i don't even see the setting in bloxstrap

**Comment by Mevillius** [comment]
Also could you please make a direct shortcut for bloxstrap settings in desktop? its impossible to open them again for people that disabled search for performance (for example it eats tons of cpu randomly, around 90% most of the times)

**Comment by pizzaboxer** [comment]
> disabled the search function just for performance

are you kidding me wtf do you guys keep doing to your pc
anyway literally just scroll through the start menu to find it. [the wiki page tells you to do that too](https://github.com/pizzaboxer/bloxstrap/wiki/Opening-the-Bloxstrap-menu).

**Comment by pizzaboxer** [comment]
about the missing mouse cursor, stop using vulkan. stay on the automatic rendering mode.

**Comment by Mevillius** [comment]
it wasnt just with vulkan, this issue randomly happens when using ANY render mode, i just have to uninstall and install bloxstrap again until it fixes

**Comment by drewsbro2** [comment]
Hey im having the same issue, if you fixed it with this "f.lux" where do i find it so i could too.

**Comment by Mevillius** [comment]
> Hey im having the same issue, if you fixed it with this "f.lux" where do i find it so i could too.

no no, i was talking about the issue being caused by "f.lux"
