### ISSUE TITLE
Stops responding upon booting up a game.

### ISSUE THREAD

**Issue by Buggyboi01** [pizzaboxer/bloxstrap#674]
Dunno if theres anything more to say. When attempting to boot up a game such as FNAF: Coop, Typical Colors 2, or nico's nextbots, it freezes up and displays the default microsoft not responding message. it boots perfectly fine, and i can roam around the roblox menu normally, but the moment i try to play anything, its dead.

I have been having a few problems with roblox lately otherwise, such as it opening only in the background - one that other people have fixed by removing 3rd party programs like rtss, but i dont have any of those.

if anyone could come up with any ideas on how these problems could be solved, that would be great thanks.

**Comment by GoingCrazyDude** [comment]
Does this happen with normal roblox? i.e. Roblox with no modifications at all.
If it doesn't, can you send a list of your FFlags and a Roblox log?

**Comment by Buggyboi01** [comment]
> Does this happen with normal roblox? i.e. Roblox with no modifications at all. If it doesn't, can you send a list of your FFlags and a Roblox log?

No, it doesnt happen in normal roblox. theres no FFlags 
![image](https://github.com/pizzaboxer/bloxstrap/assets/145107969/8b9496bc-4b7f-458e-9dc1-3c714aaa765f), and heres the log.
[0.594.0.5940525_20230915T094305Z_Player_48FE8_last.log](https://github.com/pizzaboxer/bloxstrap/files/12617980/0.594.0.5940525_20230915T094305Z_Player_48FE8_last.log)

**Comment by GoingCrazyDude** [comment]
Try setting rendering mode to automatic instead of vulkan and see if that fixes it

**Comment by Buggyboi01** [comment]
> Try setting rendering mode to automatic instead of vulkan and see if that fixes it

and now its working, thanks mate.
