### ISSUE TITLE
Bug? I start bloxstrap but whenever I start Roblox through the website BloxsTrap will launch instead of roblox.

### ISSUE THREAD

**Issue by TailsTheAviationMaster** [pizzaboxer/bloxstrap#676]
Not much of explaining to do as most of it is in the titles. have no idea what is causing this issue.

**Comment by GoingCrazyDude** [comment]
wdym by Roblox will launch instead of roblox
thats not very descriptive of your issue

**Comment by pizzaboxer** [comment]
"Roblox will launch instead of roblox"??? What????

**Comment by TailsTheAviationMaster** [comment]
Edit: I fixed the title and realized it was because of my sister. so no bug here ;3
