### ISSUE TITLE
Roblox does not open with Bloxstrap

### ISSUE THREAD

**Issue by Dameskii** [pizzaboxer/bloxstrap#677]
Hello! It's been a while since I have posted a thread on here but sadly it's not about a feature this time rather.
Roblox really doesn't like the modifications I have made with Bloxstrap, I've tried disabling my custom FFlag modifications
These are my Custom FFlags
![image](https://github.com/pizzaboxer/bloxstrap/assets/112464024/57e36270-9057-4672-ad6c-d9d8808e4a05)
and these are the Preset FFlags I've enabled
![image](https://github.com/pizzaboxer/bloxstrap/assets/112464024/a2473175-b4a0-4325-aabc-24f398cd8fac)

![image](https://github.com/pizzaboxer/bloxstrap/assets/112464024/2ac4cbaf-d541-4264-a619-33c609784402)
It's really weird that it opens up two game instances instead of one.
Oh and I've also went and tried the original bootstrapper and it works just fine, Bloxstrap is the only one doing this.
I really love using Bloxstrap so this just sets me back a bit, I'll be of aid if more clarification is needed though expect late replies, school and whatnot is getting in the way as always.

**Comment by Dameskii** [comment]
I've went and did somethings and sadly, The Vulkan rendering does not work anymore, all it does is not open roblox and leave it running in the background, i'm gonna keep this open incase anyone else comes across this issue using Vulkan

**Comment by pizzaboxer** [comment]
> i'm gonna keep this open incase anyone else comes across this issue using Vulkan

Just woke up, I've added a section in the Wiki help page for this. https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch#youre-using-the-vulkan-renderer
