### ISSUE TITLE
Bloxstrap is not working

### ISSUE THREAD

**Issue by Sologod2k** [pizzaboxer/bloxstrap#678]
One day I tried to open Bloxstrap but it didn't open for some reason, BUT the regular Roblox client was working, F.I.X I.T

**Comment by GoingCrazyDude** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by nvthane** [comment]
Today I had the same problem, I was formerly using Vulkan renderer, but I switched to Dx11 and it works. Try it as said according to the [doc](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch#roblox-launches-but-crashes-on-window-minimize).

Normally, it didn't happen, but somehow it did today.

**Comment by gigamans442** [comment]
I had a similar problem, I fixed it by turning off the option to hide the app entirely.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
