### ISSUE TITLE
roblox not opening

### ISSUE THREAD

**Issue by newbnoobhaha** [pizzaboxer/bloxstrap#679]
when i use bloxstrap roblox doesnt start, even when i followed the guide for this problem
also when i open the bloxstrap menu it says roblox is already running

**Comment by GoingCrazyDude** [comment]
Open task manager and see if Roblox is running.
also see [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)

**Comment by newbnoobhaha** [comment]
> Open task manager and see if Roblox is running. also see [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)

thats the exact guide i followed

**Comment by newbnoobhaha** [comment]
> Open task manager and see if Roblox is running. also see [this](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)

thats the guide i followed and roblox isnt running in task manager

**Comment by GoingCrazyDude** [comment]
See if Bloxstrap is running in the background

**Comment by newbnoobhaha** [comment]
> See if Bloxstrap is running in the background

it isnt

**Comment by GoingCrazyDude** [comment]
run
``` taskkill /F /IM robloxplayerbeta.exe ```
and try playing roblox and see if you get the "Roblox is Running" prompt
