### ISSUE TITLE
Building/Publishing from Source Error: 

### ISSUE THREAD

**Issue by cj1705** [pizzaboxer/bloxstrap#680]
Hello, I'm trying to build the source code in VS2022 and I'm getting the error "The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)". However, when doing a normal build, it works perfectly fine.

I've been trying to use my "custom" version of the code with my own loading screen but it also does the same from the original code.

I've tried to manually add in different dependencies and frameworks to try and resolve it but to no avail. 
 
![image](https://github.com/pizzaboxer/bloxstrap/assets/58826886/3a10187f-7b26-4156-968b-b078d4a80144)

I could be missing something simple but, I'm not sure.

**Comment by pizzaboxer** [comment]
Yeah, I don't really know why but publishing from inside VS is broken. Publish from the command line instead.
