### ISSUE TITLE
bloxstrap not launching

### ISSUE THREAD

**Issue by isacxx** [pizzaboxer/bloxstrap#681]
i have the correct .net and runtioome version ive been trying for the past week to find a way to bypass this, i install latest version of bloxstrap and run it it loads but doesnt appear in task manager or on my screen pls help

**Comment by ha4r** [comment]
its the font you have on

**Comment by isacxx** [comment]
> its the font you have on

no the problem was that my .net runtime was corrupted

**Comment by PrivateDataStorage** [comment]
> > > its the font you have on
> > 
> > 
> > no the problem was that my .net runtime was corrupted
> 
> MAN please for god sake tell me what u did and what u installed its driving me fucking crazy

i think he reinstalled his microsoft .net thingy

**Comment by Tr3yWay996** [comment]
> > > > its the font you have on
> > > 
> > > 
> > > no the problem was that my .net runtime was corrupted
> > 
> > 
> > MAN please for god sake tell me what u did and what u installed its driving me fucking crazy
> 
> i think he reinstalled his microsoft .net thingy

its been a billion time i re install this shit and some times change version de test of its because of an update idfk wtf did the dev done to this shit aahhhhhhhhhhhh, getting to think that he cnaged the code to steal account and not run roblox anymore ffs (jk but still)
