### ISSUE TITLE
Frame limit above 60 makes gpu usage 90%

### ISSUE THREAD

**Issue by Jeffison2005** [pizzaboxer/bloxstrap#683]
it's kinda weird, if i have the fps cap at 60 it's completly fine, but if i put my fps cap above 60 (it could be 61) it will just ramp up my gpu usage to around 90%

**Comment by GoingCrazyDude** [comment]
It's a roblox issue. It maxes out my gpu too. Nothing bloxstrap can do to fix it.

**Comment by pizzaboxer** [comment]
Yeah, that just sounds like a Roblox problem. If it's that big of an issue, you can set the limit as 0 to reset it back to defaults. Weird, since I don't think I've encountered anyone else having this problem.
