### ISSUE TITLE
it wont let me launch roblox with bloxstrap

### ISSUE THREAD

**Issue by Spong1e** [pizzaboxer/bloxstrap#685]
i cant launch roblox with blox strap. it does let me launch roblox without bloxstrap and idk how to fix it

**Comment by Spong1e** [comment]
this is what happens when i do and i cant tab into it. it also doesnt let me close it in task manager as it does not appear that its running. 

![image](https://github.com/pizzaboxer/bloxstrap/assets/145270233/da85c92e-df5c-499c-83bd-7055e25ad56b)

**Comment by PrivateDataStorage** [comment]
> this is what happens when i do and i cant tab into it. it also doesnt let me close it in task manager as it does not appear that its running.
> 
> ![image](https://user-images.githubusercontent.com/145270233/268504951-da85c92e-df5c-499c-83bd-7055e25ad56b.png)

whats ur rendering mode at?

**Comment by Spong1e** [comment]
where do i check that

**Comment by Spong1e** [comment]
rendering mode is on automatic

**Comment by Spong1e** [comment]
> > this is what happens when i do and i cant tab into it. it also doesnt let me close it in task manager as it does not appear that its running.
> > ![image](https://user-images.githubusercontent.com/145270233/268504951-da85c92e-df5c-499c-83bd-7055e25ad56b.png)
> 
> whats ur rendering mode at?

automatic

**Comment by PrivateDataStorage** [comment]
> > > this is what happens when i do and i cant tab into it. it also doesnt let me close it in task manager as it does not appear that its running.
> > > ![image](https://user-images.githubusercontent.com/145270233/268504951-da85c92e-df5c-499c-83bd-7055e25ad56b.png)
> > 
> > 
> > whats ur rendering mode at?
> 
> automatic

try playing around with different rendering mode settings then

if its not working either, well idk then

**Comment by PrivateDataStorage** [comment]
oh yeah, what channel are u in?

**Comment by Spong1e** [comment]
> oh yeah, what channel are u in?

wdym

**Comment by PrivateDataStorage** [comment]
> > oh yeah, what channel are u in?
> 
> wdym

go to Behaviour and tell me which channel you're in

**Comment by Spong1e** [comment]
live

**Comment by PrivateDataStorage** [comment]
> live

idk then

**Comment by pizzaboxer** [comment]
Did you check to see if this only happens with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by oudehenky** [comment]
> Did you check to see if this only happens with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I have and I can confirm it's only with bloxstrap

**Comment by pizzaboxer** [comment]
Well, you're not OP, but a few things. Make sure your rendering mode is set to automatic, try setting your FPS limit to 0, and try enabling the "Force Roblox Reinsallation" option under the behaviour tab.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
