### ISSUE TITLE
anti-afk implementation

### ISSUE THREAD

**Issue by jigguz** [pizzaboxer/bloxstrap#686]
add an option for anti-afk, seems useless but on my moms life its more usefull then you think

-----
Mm-mm-mm-mm-mm, a lot of people out for self
Mm-mm-mm-mm-mm, a lot of people are for sale
Pullin' like, mm-mm-mm-mm-mm
A lot of people run and tell, mm-mm-mm-mm-mm
Time oughta tell, judge Black males
Crawlin' across all the rails to stop clientele
Let me take you 'round, 'round, 'round
This a new town, town, town
This the new ten, ten, tеn
We're goin' in, in, in
No doubt, I can't cool it
Good job for a student
Nicе car for a student
Nice shoes for a student
New bag goin' stupid
Show me how you do it
Show me how you, errr
[?] how you foolin', in the SKRR
![ye](https://t2.genius.com/unsafe/425x425/https%3A%2F%2Fimages.genius.com%2Ffac2b5ca47394de2eb78a51928d0b73c.945x945x1.jpg)

**Comment by Mugetsu895** [comment]
FFlagDebugDisableTimeoutDisconnect ? dk if it works 🤷‍♂️ it is a flag tho

**Comment by jigguz** [comment]
MY NUTS WORK DOE LMAOOOOOOOOOO HALF COPPPIN A LOUIE VUITTON PURSE DATS MY MONEY BACK ON A MAY BACKS HAY BACK - REAL ARTISTS DONT FUCK WITH THIS - WHAT YOU LIKE I LIKED 5 YEARS AGO

**Comment by Mugetsu895** [comment]
Nawh wtf 😭
