### ISSUE TITLE
i cant open bloxstrap or roblox

### ISSUE THREAD

**Issue by eagledjeff** [pizzaboxer/bloxstrap#689]
idk il just leave the files 
[Bloxstrap_20230919T062916Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660571/Bloxstrap_20230919T062916Z.log)
[Bloxstrap_20230919T063004Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660572/Bloxstrap_20230919T063004Z.log)
[Bloxstrap_20230919T082444Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660573/Bloxstrap_20230919T082444Z.log)
[Bloxstrap_20230919T095547Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660574/Bloxstrap_20230919T095547Z.log)
[Bloxstrap_20230919T095724Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660575/Bloxstrap_20230919T095724Z.log)
[Bloxstrap_20230919T103455Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660576/Bloxstrap_20230919T103455Z.log)
[Bloxstrap_20230919T122455Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660577/Bloxstrap_20230919T122455Z.log)
[Bloxstrap_20230919T125534Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660578/Bloxstrap_20230919T125534Z.log)
[Bloxstrap_20230919T125637Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660579/Bloxstrap_20230919T125637Z.log)
[Bloxstrap_20230919T125707Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660580/Bloxstrap_20230919T125707Z.log)
[Bloxstrap_20230919T125732Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660581/Bloxstrap_20230919T125732Z.log)
[Bloxstrap_20230919T125746Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660582/Bloxstrap_20230919T125746Z.log)
[Bloxstrap_20230919T125754Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660583/Bloxstrap_20230919T125754Z.log)
[Bloxstrap_20230919T125811Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660584/Bloxstrap_20230919T125811Z.log)
[Bloxstrap_20230919T130227Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660585/Bloxstrap_20230919T130227Z.log)
[Bloxstrap_20230919T130406Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660586/Bloxstrap_20230919T130406Z.log)
[Bloxstrap_20230919T130607Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660587/Bloxstrap_20230919T130607Z.log)
[Bloxstrap_20230919T130738Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660588/Bloxstrap_20230919T130738Z.log)
[Bloxstrap_20230919T130824Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660589/Bloxstrap_20230919T130824Z.log)
[Bloxstrap_20230919T130858Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660590/Bloxstrap_20230919T130858Z.log)
[Bloxstrap_20230919T131004Z.log](https://github.com/pizzaboxer/bloxstrap/files/12660591/Bloxstrap_20230919T131004Z.log)

**Comment by GoingCrazyDude** [comment]
send the latest log.................

**Comment by pizzaboxer** [comment]
Seems like a bad internet connection. Try it again and it should work.
