### ISSUE TITLE
Cannot install Bloxstrap

### ISSUE THREAD

**Issue by RickGotTaken** [pizzaboxer/bloxstrap#692]
[Bloxstrap_20230919T195730Z.log](https://github.com/pizzaboxer/bloxstrap/files/12665962/Bloxstrap_20230919T195730Z.log)

System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.

**Comment by GoingCrazyDude** [comment]
Probably internet issue. Try installing again. If you still get an error, try using a VPN and see if it still occurs.

**Comment by RickGotTaken** [comment]
> Probably internet issue. Try installing again. If you still get an error, try using a VPN and see if it still occurs.

I think it was an internet issue, I've installed it now!

**Comment by GoingCrazyDude** [comment]
Nice
