### ISSUE TITLE
Roblox won't open

### ISSUE THREAD

**Issue by Mevillius** [pizzaboxer/bloxstrap#694]
it simply won't open while bloxstrap is installed, gotta uninstall it then reinstall roblox for it to work

**Comment by Mevillius** [comment]
specifically it wont open normally, it just opens as a background process

**Comment by pizzaboxer** [comment]
See #635, and also https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch if you haven't yet. I'll close this since it'll be better if you talk in that other issue.
