### ISSUE TITLE
Bloxstrap not launching

### ISSUE THREAD

**Issue by stooormys** [pizzaboxer/bloxstrap#695]
trying start bloxstrap after waiting 10 mins he does not work, im not understand logs so i need help please
[Bloxstrap-v2.5.2_d3d9.log](https://github.com/pizzaboxer/bloxstrap/files/12671764/Bloxstrap-v2.5.2_d3d9.log)
[Bloxstrap_20230727T000006Z.log](https://github.com/pizzaboxer/bloxstrap/files/12671765/Bloxstrap_20230727T000006Z.log)

**Comment by GoingCrazyDude** [comment]
Bloxstrap_20230727T000006Z.log is an old log. Send the latest log.
Also are you trying to use DXVK?

**Comment by stooormys** [comment]
[Bloxstrap-v2.5.2_d3d9.log](https://github.com/pizzaboxer/bloxstrap/files/12671841/Bloxstrap-v2.5.2_d3d9.log)
this is latest log and i dont know what is DXVK

> Bloxstrap_20230727T000006Z.log is an old log. Send the latest log. Also are you trying to use DXVK?

**Comment by GoingCrazyDude** [comment]
Go to %localappdata%/Bloxstrap/ and send a screenshot of the contents

**Comment by stooormys** [comment]
i dont have Bloxstrap folder

**Comment by GoingCrazyDude** [comment]
uh where did you install bloxstrap?

**Comment by stooormys** [comment]
i installed it from github, then search it from start menu and launched



> uh where did you install bloxstrap?

**Comment by GoingCrazyDude** [comment]
How the fuck did you make bloxstrap generate a directx log

**Comment by stooormys** [comment]
if i know how

**Comment by pizzaboxer** [comment]
> [Bloxstrap-v2.5.2_d3d9.log](https://github.com/pizzaboxer/bloxstrap/files/12671764/Bloxstrap-v2.5.2_d3d9.log)

What? Where did this log come from? Why are you using DXVK???

**Comment by stooormys** [comment]
> > [Bloxstrap-v2.5.2_d3d9.log](https://github.com/pizzaboxer/bloxstrap/files/12671764/Bloxstrap-v2.5.2_d3d9.log)
> 
> What? Where did this log come from? Why are you using DXVK???

Can you please explain what is DXVK?

**Comment by GoingCrazyDude** [comment]
> > > [Bloxstrap-v2.5.2_d3d9.log](https://github.com/pizzaboxer/bloxstrap/files/12671764/Bloxstrap-v2.5.2_d3d9.log)
> > 
> > 
> > What? Where did this log come from? Why are you using DXVK???
> 
> Can you please explain what is DXVK?

DXVK is a translation layer to translate DirectX instructions to Vulkan. Whats crazy is HOW did you make Bloxstrap load DXVK.

**Comment by stooormys** [comment]
> > > > [Bloxstrap-v2.5.2_d3d9.log](https://github.com/pizzaboxer/bloxstrap/files/12671764/Bloxstrap-v2.5.2_d3d9.log)
> > > 
> > > 
> > > What? Where did this log come from? Why are you using DXVK???
> > 
> > 
> > Can you please explain what is DXVK?
> 
> DXVK is a translation layer to translate DirectX instructions to Vulkan. Whats crazy is HOW did you make Bloxstrap load DXVK.

You mean its impossible Bloxstrap to load DXVK but I somehow done that?

**Comment by TurboYANEK** [comment]
Why do you even have DXVK in the first place?

**Comment by TurboYANEK** [comment]
> Maybe I accidentally install it? If it bad I think i can try delete it
DXVK was meant to be used on Linux if I know correctly, so it's not needed on windows

**Comment by Henry-Hiles** [comment]
> > Maybe I accidentally install it? If it bad I think i can try delete it
> 
> DXVK was meant to be used on Linux if I know correctly, so it's not needed on windows

It can be used on windows too, it can sometimes garnish extra performance, or can be used for other purpouses

**Comment by isacxx** [comment]
this happened to me it was because my .net version was corrupted  if you havent already install latest version of net 6.0 and try running it again

**Comment by stooormys** [comment]
> this happened to me it was because my .net version was corrupted if you havent already install latest version of net 6.0 and try running it again

Ok thank you I will try

**Comment by stooormys** [comment]
> this happened to me it was because my .net version was corrupted if you havent already install latest version of net 6.0 and try running it again

sorry but its dont helped me

**Comment by pizzaboxer** [comment]
The problem here just seems like you're using DXVK, which, you somehow don't appear to be aware of what it is. If you try setting your rendering mode to either Vulkan or OpenGL, and then try launching Roblox, does that change anything?
