### ISSUE TITLE
Sensapi.dll not allowing me to open any sort of Roblox application

### ISSUE THREAD

**Issue by SkaarChill** [pizzaboxer/bloxstrap#696]
I've been researching this error for the past 8 days, and I've yet to find a solution to this problem. 
It happens on Bloxtrap and normal Roblox, but not on the windows store version. Replacing the dll file doesn't work, clearing thumbnail doesnt work, doing sfc scans and restore images doesnt work, it isn't caused by a background program, since I opened another user clean from any background applications, that only had windows processes in the background, also not work. I am going to lose my grip on sanity if this keeps happening any longer, and before you say it, the windows store version sucks, it eats half of your supposed fps, and your cursor jumps, and you get disconnected a lot. Now you know my story, any fixes yall have?

**Comment by SkaarChill** [comment]
PS: Issue 696, it's a sign either of bad or good, hopefully the latter. Help me

**Comment by Mugetsu895** [comment]
> I've been researching this error for the past 8 days, and I've yet to find a solution to this problem. It happens on Bloxtrap and normal Roblox, but not on the windows store version. Replacing the dll file doesn't work, clearing thumbnail doesnt work, doing sfc scans and restore images doesnt work, it isn't caused by a background program, since I opened another user clean from any background applications, that only had windows processes in the background, also not work. I am going to lose my grip on sanity if this keeps happening any longer, and before you say it, the windows store version sucks, it eats half of your supposed fps, and your cursor jumps, and you get disconnected a lot. Now you know my story, any fixes yall have?

i tried everything you tried and the only thing that fixed it for me was a full reset of my pc

**Comment by SkaarChill** [comment]
> > I've been researching this error for the past 8 days, and I've yet to find a solution to this problem. It happens on Bloxtrap and normal Roblox, but not on the windows store version. Replacing the dll file doesn't work, clearing thumbnail doesnt work, doing sfc scans and restore images doesnt work, it isn't caused by a background program, since I opened another user clean from any background applications, that only had windows processes in the background, also not work. I am going to lose my grip on sanity if this keeps happening any longer, and before you say it, the windows store version sucks, it eats half of your supposed fps, and your cursor jumps, and you get disconnected a lot. Now you know my story, any fixes yall have?
> 
> i tried everything you tried and the only thing that fixed it for me was a full reset of my pc

I can't afford to reset my pc, sadly.

**Comment by Mugetsu895** [comment]
I heard it was cuz of corrupted files and i had some so yeah sfc couldn't repair the corrupted files but resetting my pc would, so idk if thats the case for you but just hope something fixes it, i also heard doing a windows update might help idk though, hope you can fix it 🙏

**Comment by SkaarChill** [comment]
> I heard it was cuz of corrupted files and i had some so yeah sfc couldn't repair the corrupted files but resetting my pc would, so idk if thats the case for you but just hope something fixes it, i also heard doing a windows update might help idk though, hope you can fix it 🙏

Thanks man
