### ISSUE TITLE
Bloxstarp saying "System.Exception: Signature does not match!"

### ISSUE THREAD

**Issue by HelloKerem** [pizzaboxer/bloxstrap#698]
Idk why every roblox update did this to my computer
![image](https://github.com/pizzaboxer/bloxstrap/assets/98821815/a985b637-f25a-4a23-9dbe-4da558474543)

**Comment by HelloKerem** [comment]
and the log file
[Bloxstrap_20230920T180834Z.log](https://github.com/pizzaboxer/bloxstrap/files/12676319/Bloxstrap_20230920T180834Z.log)

**Comment by HelloKerem** [comment]
+ restarted the pc

**Comment by HelloKerem** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/98821815/3d355a1a-27be-4d89-94f1-295ddd9bf997)
nvm i just need delete thumbnails

**Comment by HelloKerem** [comment]
plus not my image only showcase

**Comment by HelloKerem** [comment]
can someone close this? after close this say "wish granted"
thank you

**Comment by pizzaboxer** [comment]
wish granted

**Comment by Sahelantrophus** [comment]
> wish granted

good slave

**Comment by pizzaboxer** [comment]
THE FUCK
