### ISSUE TITLE
what's this "builds channel" in the installation tab of the configure bloxstrap app

### ISSUE THREAD

**Issue by dropier** [pizzaboxer/bloxstrap#7]
title says it all

**Comment by pizzaboxer** [comment]
Channels are basically the Roblox client equivalent to GitHub repository branches, where each branch is the same project but entirely independent, allowing for development and experimentation. For example, ZCanary is used by Roblox for testing new features added to the game engine and stuff.

tl;dr it allows you to select development builds and you don't really have to worry about it, you can keep it set to LIVE

**Comment by dropier** [comment]
oh alright. thanks pizzaboxer, very cool 👍👍👍👍👍👍👍👍
