### ISSUE TITLE
reshade is not working

### ISSUE THREAD

**Issue by Sploiter13** [pizzaboxer/bloxstrap#70]
i installed reshade and its not working

**Comment by pizzaboxer** [comment]
In what way did you install ReShade?

**Comment by Sploiter13** [comment]
> In what way did you install ReShade?

installed it normally then saw it was not working so i copied it and put it in the modifications folder but still dosent work

**Comment by Sploiter13** [comment]
> Bloxstrap ignores any files put in the root mod folder. I'm already adding ReShade support in the next version, and solving that issue.

alr thx
