### ISSUE TITLE
Bloxstrap says it's denying it's self

### ISSUE THREAD

**Issue by MrSaxton** [pizzaboxer/bloxstrap#700]
[Bloxstrap_20230921T022650Z.log](https://github.com/pizzaboxer/bloxstrap/files/12679469/Bloxstrap_20230921T022650Z.log)
Error :
System.UnauthorizedAccessException: Access to the path '%userpath%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

**Comment by pizzaboxer** [comment]
Go to `%localappdata%\Bloxstrap\` in the file browser, check the file properties for Bloxstrap.exe, and make sure that it's not set to read-only. Unset it if it is.
