### ISSUE TITLE
Roblox crashing after minimizing Roblox tab

### ISSUE THREAD

**Issue by Nostalgia83** [pizzaboxer/bloxstrap#701]
Hello!

I've been starting to have a problem with roblox after I installed bloxstrap. But i have no idea if's an option i enabled and i didn't notice. Thank you!

**Comment by Nostalgia83** [comment]
eveything else is great!

**Comment by GoingCrazyDude** [comment]
Do not use Vulkan. It crashes when you minimize.

**Comment by Nostalgia83** [comment]
> Do not use Vulkan. It crashes when you minimize.

Alright, thank you.

**Comment by pizzaboxer** [comment]
[Don't use Vulkan.](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch)
