### ISSUE TITLE
Add no telemetry flag preset

### ISSUE THREAD

**Issue by bluepilledgreat** [pizzaboxer/bloxstrap#702]
https://gist.github.com/bluepilledgreat/c4307f927fef66628c423b9e208fa9cd

**Comment by EasternBloxxer** [comment]
Add it Then.

**Comment by popbob2** [comment]
👍

**Comment by Vlad55432** [comment]
they exist??? damnnn

**Comment by Carlolu23** [comment]
Excuse my ignorance, what exactly does this flag do? Does it affect the in-game performance?

**Comment by bluepilledgreat** [comment]
closed because of recent updates
