### ISSUE TITLE
Fake Headless Exposed

### ISSUE THREAD

**Issue by i-ruin** [pizzaboxer/bloxstrap#704]
So basically I'm using a fake headless. Now when I launch on normal roblox, it works and it appears as though I have headless. However when I use Bloxstrap and launch through there it makes it normal head. Fix this please

**Comment by pizzaboxer** [comment]
Not related to Bloxstrap.

**Comment by WaviestBalloon** [comment]
> So basically I'm using a fake headless. Now when I launch on normal roblox, it works and it appears as though I have headless. However when I use Bloxstrap and launch through there it makes it normal head. Fix this please

This is probably related to your render API you are using, some UGC creators thought it'd be amazing idea to use shaders that are not available/compiled for other render APIs
In Bloxstrap, change the renderer that you're using and see if that changes

**Comment by Sahelantrophus** [comment]
brokie
