### ISSUE TITLE
[Feature Request] GPU Override

### ISSUE THREAD

**Issue by kirbix12** [pizzaboxer/bloxstrap#705]
Add an option where you can override which GPU (if the user has multiple) Roblox should utilize.

(read this before commenting: https://github.com/pizzaboxer/bloxstrap/issues/705#issuecomment-1732358740)

**Comment by TurboYANEK** [comment]
Windows already has this feature

**Comment by kirbix12** [comment]
However: Before you guys say "Just go to Settings > Display > Graphics > Browse then add Roblox onto the list and override from there", **Roblox refuses to listen to that order,** and instead go for GPU 1.


https://github.com/pizzaboxer/bloxstrap/assets/80133246/f47b2f9f-62f2-4620-8f1b-f158fdb24da4

**Comment by pizzaboxer** [comment]
If Windows isn't even able to do it, how am I supposed to do it?

**Comment by kirbix12** [comment]
Maybe not so.

**Comment by kirbix12** [comment]
Not really sure if Roblox does have a FFlag for this or not, only assuming so since Roblox does not listen to the override.

**Comment by TheMetalTechnet** [comment]
I think that's just an issue with windows, as it probably recognises Bloxstrap as a separate program (thought windows should probably still count it as Roblox)

**Comment by kirbix12** [comment]
No I think I was overlooking into this and it's probably just a Roblox issue on how the client is coded.
