### ISSUE TITLE
UnauthorizedAccessException

### ISSUE THREAD

**Issue by MarioKart33e333** [pizzaboxer/bloxstrap#706]
[This issue still occurs when i run the app as administrator]

System.UnauthorizedAccessException: Access to the path 'C:\Users\alexo\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

[Bloxstrap_20230923T184233Z.log](https://github.com/pizzaboxer/bloxstrap/files/12707071/Bloxstrap_20230923T184233Z.log)

**Comment by kirbix12** [comment]
Interesting that access got denied...

![Screenshot_20230923-193555.png](https://github.com/pizzaboxer/bloxstrap/assets/80133246/c8798204-2e37-4569-b1f2-f6e9901001aa)

**Comment by MarioKart33e333** [comment]
r u being sarcastic or not bc this is so confusing but i think it works now lmao

**Comment by pizzaboxer** [comment]
> Interesting that access got denied...

Windows is stupid and sets the exe to read-only for no reason sometimes.
