### ISSUE TITLE
BlackTextures

### ISSUE THREAD

**Issue by bababeo** [pizzaboxer/bloxstrap#707]
this happens when i use vulkan, game: all star tower defense
![RobloxScreenShot20230924_042323805](https://github.com/pizzaboxer/bloxstrap/assets/145874666/e0912e99-d226-4184-9f4e-4c601737c584)

**Comment by pizzaboxer** [comment]
Only when you use Vulkan?

**Comment by pizzaboxer** [comment]
^ That is the solution indeed.
