### ISSUE TITLE
loading problems

### ISSUE THREAD

**Issue by paranoidreal** [pizzaboxer/bloxstrap#708]
whenever i try to join a game or go from one different game to another, it takes really slow to load. my game either freezes and takes forever to load or roblox just straight up crashes. ive used rco before and didnt experience this so i know its not my pc. anyone know any solutions?

**Comment by kirbix12** [comment]
I was going to first assume your PC is not powerful enough. However since you assume that's not the case, I won't either.

There could be several factors to this:
- Your internet is slow 
- Roblox is attempting to deload cached assets 
- The game is attempting to fetch so many assets (which can stack with slow internet)
- Rendering issues

**Comment by pizzaboxer** [comment]
First things first, check if it happens with normal Roblox too. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

If it doesn't, then I'll try looking at some things to see what could be causing it.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by OpticalRainbowz** [comment]
Hey, I am having the same issue. I have checked this with the normal Roblox client and it seems to be fine there. On Bloxstrap however I have longer loading times for some reason.

**Comment by pizzaboxer** [comment]
Are you sure that there's a difference between the two? How have you checked?

**Comment by OpticalRainbowz** [comment]
Yes, after I cleared the cache I measured the time of how long it takes to get into the game after I press play. On the Roblox client it was around 15 seconds. On Bloxstrap it was 40 seconds. I ran the test 3 times for each client so it's pretty consistent.

**Comment by pizzaboxer** [comment]
What's your framerate limit set to on Bloxstrap? Try setting it to 0, see if anything changes.

**Comment by OpticalRainbowz** [comment]
I had my limit on 240. Setting it to 0 did not change anything

**Comment by pizzaboxer** [comment]
At this point I'm trying to get you as close to stock Roblox as possible. If you go into the installation folder, into the version folder, and just run RobloxPlayerBeta.exe directly, does the same thing happen?

**Comment by OpticalRainbowz** [comment]
I ran RobloxPlayerBeta.exe but nothing opened or anything. It appeared on my task manager for a few seconds and then disappeared.

**Comment by OpticalRainbowz** [comment]
I found out that after uninstalling Bloxstrap, the browser version also has the same issue. So it must be some kind of Roblox update that caused it a week ago or so.

**Comment by 1011025m** [comment]
> I ran RobloxPlayerBeta.exe but nothing opened or anything. It appeared on my task manager for a few seconds and then disappeared.

If you have the disable desktop app option turned on, it wouldn't launch (for obvious reasons). Just saying.

**Comment by OpticalRainbowz** [comment]
No, disabling the desktop app option didn't change anything.

**Comment by AsrielDreemurr2015** [comment]
Does future (phase 3) work with direct 3d 10? Thanks!

**Comment by pizzaboxer** [comment]
no

**Comment by AsrielDreemurr2015** [comment]
That's okay! Games are supposed to be fun, not appealing! (y'know like look good?)

**Comment by OpticalRainbowz** [comment]
Quick update! The issue was that whenever I started Roblox the VR Server process would pop up in task manager. All I had to do was to uninstall SteamVR

**Comment by NotAdrixnn** [comment]
This is happening to me also please help

**Comment by pizzaboxer** [comment]
@NotAdrixnn As I originally asked OP, is this only happening with Bloxstrap?

**Comment by NotAdrixnn** [comment]
@pizzaboxer  I fixed the problem i uninstalled and reinstalled and now good.
