### ISSUE TITLE
Bloxstrap crashes upon any key pressed

### ISSUE THREAD

**Issue by ThatRandomGuye** [pizzaboxer/bloxstrap#710]
When I click any key (esc, w, a, s, d, etc.), whether in a game, or in the home menu, my game crashes! Only the mouse buttons work.

**Comment by pizzaboxer** [comment]
Does it happen without Bloxstrap too> https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by ThatRandomGuye** [comment]
> Does it happen without Bloxstrap too> https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

It does not happen without Bloxstrap

**Comment by pizzaboxer** [comment]
What flags do you have configured in the menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by ThatRandomGuye** [comment]
Sorry for the **long** wait. Anyways, here are the flags configured in the menu:

- Framerate Limit: 120
- Preferred Lighting Technology: _Chosen by game_
- Preferred Escape Menu: V4 (2023)
- Ability to hide GUIs: false
- Old material textures: false
- Rendering mode: _Automatic_
- Preserving Rendering Quality: false
- Alternate Graphics Quality Selector: true

**Comment by pizzaboxer** [comment]
What about if you try setting your framerate limit to zero?

**Comment by ThatRandomGuye** [comment]
That sadly did not work.

**Comment by pizzaboxer** [comment]
A few things I want you to try out:
- Show me the *full list* of flags you have configured, by showing a picture of the FastFlag editor.
- Try disabling all enabled integrations
- Open Bloxstrap's installation folder, typically located at `%localappdata%\Bloxstrap`, go to the Versions folder and open RobloxPlayerBeta.exe directly. See if it happens there.
  - If it does happen with a direct launch, then delete the 'ClientSettings' folder, and try launching again
  
Let me know about the results you got, I'm just trying to narrow down what differing factors could be causing this.

**Comment by Alvin-Yu628** [comment]
I'm also having the same issue. I have tried changing the configurations that were provided by @ThatRandomGuye and also the solutions that were provided above. However, nothing seemed to work for me. It still has the same issue with running the client, whether running on Roblox Client or Bloxstrap. It usually lags or crashes (screen freezing for a few seconds) when clicking on the Roblox Icon located on the top left while in-game or clicking on the escape key. I have tried contacting Roblox about this issue, but their solutions doesn't solve the problem.

**Comment by pizzaboxer** [comment]
> whether running on Roblox Client or Bloxstrap

It's a problem with Roblox itself then, which I can't really help with. This person states that their issue only ever occurs with Bloxstrap, so it's not exactly the same thing.

**Comment by Alvin-Yu628** [comment]
it's weird that I'm experiencing this issue for both of the clients but then he is experiencing the problem only with Bloxstrap. This sucks.

**Comment by pizzaboxer** [comment]
Closing again due to inactivity.
