### ISSUE TITLE
A button to end the roblox player process in tray context menu

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#711]
this would be useful if it starts in the background. i dont want to have to open task manager every time it happens (https://discord.com/channels/1099468797410283540/1153324634624757831)
![image](https://github.com/pizzaboxer/bloxstrap/assets/54174182/6763b228-4eda-4aad-87dc-15108cbd854a)

**Comment by WaviestBalloon** [comment]
Eastern, you should know C#.... Do it yourself >:(

**Comment by popbob2** [comment]
taskkill /f /im RobloxPlayerBeta.exe

**Comment by WaviestBalloon** [comment]
> taskkill /f /im RobloxPlayerBeta.exe

Go back to v3rm.

**Comment by popbob2** [comment]
no

**Comment by EasternBloxxer** [comment]
> taskkill /f /im RobloxPlayerBeta.exe

Go back to your skid site.
