### ISSUE TITLE
Discord Rich presence not working.

### ISSUE THREAD

**Issue by Maltrap** [pizzaboxer/bloxstrap#713]
I have it enabled I re-installed bloxstrap I wounded it doesn't appear because I have a discord Client on (Vencord) Would that change if it allows it to appear?

**Comment by pizzaboxer** [comment]
Do you have any other programs that use rich presence which work?

**Comment by Blessedsolaris** [comment]
with vencord you must go into the settings folder, open settings.json and set the notrack plugin to false, and it should fix it. or at least that worked for me. also disable roblox from showing up as a registered application.

**Comment by Maltrap** [comment]
how do I open vencord  settings folder

**Comment by Maltrap** [comment]
is it because I use vencord with discord it's not allowing me to use rich presence???

**Comment by Maltrap** [comment]
even without vencord it still does it

**Comment by WaviestBalloon** [comment]
> I have it enabled I re-installed bloxstrap I wounded it doesn't appear because I have a discord Client on (Vencord) Would that change if it allows it to appear?

Can you try to use the official unmodified version of Discord to confirm that official works but not modded?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by AgentPlayz** [comment]
> Do you have any other programs that use rich presence which work?

The same issue is happing with me, i have vencord and i tried the settings.json method, i am using spotify and medal in the background, i tried reinstalling discord and bloxstrap and even tried it without vencord, but nothing worked. (also im on windows 10 if that matters)

**Comment by jamesgarry1** [comment]
you need to be on online status

**Comment by AgentPlayz** [comment]
> you need to be on online status

Nope didnt work

**Comment by moyaimoment** [comment]
> Nope didnt work

Make sure:
1. You are Online/Idle/DND on Discord.
2. Have DiscordRPC toggled on in your Bloxstrap settings.
3. In your Discord settings that Activity Privacy > "Share your detected activities with others" is toggled on.
4. Check in your Discord settings > Registered Games that Roblox doesn't have "Toggle Detection" (the eye icon) isn't Red, if it is Red then you need to click it again to make it a Light Grey.

**Comment by Voidisss** [comment]
^
man, at this points i dont even know what could it be even if i did all said on the comment on top.
ill just maybe wait for an new bloxtrap version and pray so it can be fixed.
