### ISSUE TITLE
I have a problem because when I launch Roblox, Bloxstrap does not launch

### ISSUE THREAD

**Issue by Nisepp** [pizzaboxer/bloxstrap#714]

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap ?

**Comment by Tr3yWay996** [comment]
> https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap ?

this iant the issue MAte

**Comment by pizzaboxer** [comment]
Wrong page, my bad.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch ?

**Comment by Tr3yWay996** [comment]
> Wrong page, my bad.
> 
> https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch ?

ye nah too, been some hours i fight with this sorry if i seem crazy at some moment, dont want to annoy you in your beatifull work for your comunity

**Comment by Justinfrfr** [comment]
i encounter the same problem so this is what happen. When you launch the normal bootstrapper(non bloxstrap) after the loading screen"ur game is launching" is done loading on the website, the normal bootstrapper will launch(which will allow u to play the game) but for bloxstrap, the bloxstrap launcher does not launch after the text"ur game is launching" is done loading and i have no idea why but this could be a fix. literally just restart ur PC, i am using a custom OS(XOS) and the first like 2 days bootstrapper works fine, even on windows but after that, it just doesnt launch at all.

**Comment by stackofshit** [comment]
i know right. 2 days ago the same thing happened to me but i reinstalled, restarted my pc and it worked fine. Now today I couldn't seem to launch it so I used the same method and absolutely nothing happened. Just gives you the normal popup and doesn't do jackshit after that.

**Comment by pizzaboxer** [comment]
Did either of you read the Wiki page I linked above, and check to see if it happens without Bloxstrap?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
