### ISSUE TITLE
Really high ping when playing roblox with bloxstrap installed

### ISSUE THREAD

**Issue by bznel** [pizzaboxer/bloxstrap#715]
When i install bloxstrap with all the default settings, i get around 300-1000 ping constantly in any roblox games, then when i uninstall it, im fine with 30-60 ping

**Comment by BokBoy** [comment]
This shouldn't be an issue...
Bloxstrap should not effect the Wi-fi speed.
To me, it sounds like a bad luck when you tried it.
Make sure that it is the ping not FPS.

**Comment by ImLoadingUuU** [comment]
Internet issue.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
