### ISSUE TITLE
Path does not exist?

### ISSUE THREAD

**Issue by Bobnest** [pizzaboxer/bloxstrap#716]
When I opened Bloxstrap it gave me this error
![image](https://github.com/pizzaboxer/bloxstrap/assets/121069855/84e84e47-92df-4d05-8585-3c8df9b5e7db)
It popped out after the "Starting Roblox..." loading bar thing

When I opened it from the shortcut folder (C:\Users\river\AppData\Local\Bloxstrap)
It gave me this error:
![image](https://github.com/pizzaboxer/bloxstrap/assets/121069855/21a24909-5626-43dc-a747-2588f2fc477a)

I think its looking for the "Modifications/content" folder from %localappdata%/Bloxstrap/

**Comment by Bobnest** [comment]
Mods I currently have is the old oof death sound and a custom font (.otf)

**Comment by GoingCrazyDude** [comment]
which channel are you using currently

**Comment by Bobnest** [comment]
> which channel are you using currently

I'm using ZIntegration

**Comment by Bobnest** [comment]
Got it working now, I switch to ZCanary. Thank you!

**Comment by pizzaboxer** [comment]
jsyk i removed the channel selector dropdown because of people like you

**Comment by Mugetsu895** [comment]
> Got it working now, I switched to ZCanary. Thank you!

y not use the live channel
