### ISSUE TITLE
"The path "C:\Windows\System32\content" does not exist" when roblox loads

### ISSUE THREAD

**Issue by Mattem300** [pizzaboxer/bloxstrap#717]
Every time I join a game, Roblox loads normally but then an error called "The path "C:\Windows\System32\content" does not exist." I already tried to reinstall Roblox and Bloxstrap but it still doesn't work

The error:

<img width="290" alt="image" src="https://github.com/pizzaboxer/bloxstrap/assets/118678848/037bf22a-bc11-450a-8469-26d43011c93e">

**Comment by PrivateDataStorage** [comment]
Are you on the channel "zintergration"? if so, change to LIVE

**Comment by pizzaboxer** [comment]
Stay on LIVE/production. I'll publish a fix for this later.
