### ISSUE TITLE
Not even trying to launch, NICE

### ISSUE THREAD

**Issue by Tr3yWay996** [pizzaboxer/bloxstrap#719]
Ye it just give up instatly as i start this mfo, its driving me crazy and i just  been aware of its existence for a bout an hour on reddit for laggy asf roblox xD
Theres the logs, as empty as my hope for it now fr

[Bloxstrap_20230927T143807Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740012/Bloxstrap_20230927T143807Z.log)
[Bloxstrap_20230927T143924Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740014/Bloxstrap_20230927T143924Z.log)
[Bloxstrap_20230927T143932Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740016/Bloxstrap_20230927T143932Z.log)
[Bloxstrap_20230927T143955Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740018/Bloxstrap_20230927T143955Z.log)
[Bloxstrap_20230927T144006Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740019/Bloxstrap_20230927T144006Z.log)
[Bloxstrap_20230927T144048Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740020/Bloxstrap_20230927T144048Z.log)
[Bloxstrap_20230927T143551Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740021/Bloxstrap_20230927T143551Z.log)
[Bloxstrap_20230927T143614Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740022/Bloxstrap_20230927T143614Z.log)
[Bloxstrap_20230927T143752Z.log](https://github.com/pizzaboxer/bloxstrap/files/12740023/Bloxstrap_20230927T143752Z.log)

**Comment by pizzaboxer** [comment]
Interesting, seems like it's instantly crashing. Did you see https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

**Comment by Tr3yWay996** [comment]
> Interesting, seems like it's instantly crashing. Did you see https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

i will do thanks, because i dont know if i did already fr

**Comment by Tr3yWay996** [comment]
> Interesting, seems like it's instantly crashing. Did you see https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-doesn't-run-when-opening-it?

oh ye i already did a thousand times and nothing changed, cant even run the fliping exe

**Comment by pizzaboxer** [comment]
Open Event Viewer, go to Windows Logs -> Application. Any error entries at the top?

**Comment by Tr3yWay996** [comment]
> Open Event Viewer, go to Windows Logs -> Application. Any error entries at the top?

well yes but its in baguette language i dont think you would understand, but still leme grab a screenshot

**Comment by pizzaboxer** [comment]
Show the error details.

**Comment by Tr3yWay996** [comment]
> Open Event Viewer, go to Windows Logs -> Application. Any error entries at the top?

![image](https://github.com/pizzaboxer/bloxstrap/assets/112483771/58367680-7a24-4b57-afc6-9d6b12d2be81)

**Comment by pizzaboxer** [comment]
It's saying that atiumd64.dll failed. That's for AMD's DirectX driver. Figure out what's going on with that, because this definitely isn't a problem with Bloxstrap.

**Comment by Tr3yWay996** [comment]
> Show the error details.

doing an sfc/scannow thig because idk why but it point to system 32 driver thing

**Comment by Tr3yWay996** [comment]
> It's saying that atiumd64.dll encountered a memory violation. That's for AMD's DirectX driver. Figure out what's going on with that, because this definitely isn't a problem with Bloxstrap.

for fuck sake AMD, thank man i apreciate the troubleshooting tho

**Comment by pizzaboxer** [comment]
Try reinstalling the driver or whatever else you can think of to fix it. I'll mark this as resolved.

**Comment by Tr3yWay996** [comment]
> Try reinstalling the driver or whatever else you can think of to fix it. I'll mark this as resolved.

well ye if only i knew what this was xD, going to google it up real quick

**Comment by Tr3yWay996** [comment]
> Try reinstalling the driver or whatever else you can think of to fix it. I'll mark this as resolved.

i tried in safe mode and it worked, and now it completly refuse to, wtf
