### ISSUE TITLE
Option to launch multiple roblox instances

### ISSUE THREAD

**Issue by rollingmoai** [pizzaboxer/bloxstrap#72]
https://github.com/ic3w0lf22/ROBLOX_MULTI exists, but I don't want another program open, like rbxfpsunlocker (which is thankfully integrated into Bloxstrap). Can you integrate this to Bloxstap? Thanks.

**Comment by 6ixfalls** [comment]
If you need the relevant code snippet to implement this, I've added it to my fork of bloxstrap:
https://github.com/6ixfalls/bloxstrap/commit/197d01f6b8d106cfcebeb76124fec7201f62c350

**Comment by BeyondThe5D** [comment]
> Sure! I remember someone suggested this a while ago, but I guess I forgot about it.

I was the one who suggested it lol
