### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Zafri12345** [pizzaboxer/bloxstrap#721]
"System.IO.FileNotFoundException: Could not find file 'C:\Users\AdamZafri\Downloads\Programs\Bloxstrap-v2.5.2.exe'."

**Comment by pizzaboxer** [comment]
Where's the log file?

**Comment by Sahelantrophus** [comment]
idk what that is

**Comment by Tr3yWay996** [comment]
> "System.IO.FileNotFoundException: Could not find file 'C:\Users\AdamZafri\Downloads\Programs\Bloxstrap-v2.5.2.exe'."

well now we know ur named A**m if its not a nickname xD and post a log file instead of just asking "Gneeuu what it isss"
anyway, cya

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
