### ISSUE TITLE
Bloxstrap Failing to Load after "Starting Roblox"

### ISSUE THREAD

**Issue by DivineLiberty** [pizzaboxer/bloxstrap#723]
I think this issue may be connected in some way with roblox clients failing to load recently. However, when starting Bloxstrap, it will open, just like Roblox, the "Starting Roblox" window, before closing it and remaining a background process. Attached is my most recent log. I've verified that my runtimes are also up to date.

[Bloxstrap_20230929T051258Z.log](https://github.com/pizzaboxer/bloxstrap/files/12756335/Bloxstrap_20230929T051258Z.log)

**Comment by DivineLiberty** [comment]
[Bloxstrap_20230929T053104Z.log](https://github.com/pizzaboxer/bloxstrap/files/12756387/Bloxstrap_20230929T053104Z.log)

This is my most recent log after reinstalling the program.

**Comment by pizzaboxer** [comment]
I'm somewhat confused, because this is showing Bloxstrap itself crashing too. Can you open Event Viewer, go to Windows Logs -> Application, and show any Error entries that are listed at the top?

**Comment by DivineLiberty** [comment]
A more recent log:
[Bloxstrap_20230929T104012Z.log](https://github.com/pizzaboxer/bloxstrap/files/12764353/Bloxstrap_20230929T104012Z.log)

All of my events in event viewer:
![EV](https://github.com/pizzaboxer/bloxstrap/assets/146412468/23d8f320-d5ee-4332-a269-eae6cbfb886a)

There are no errors in the viewer at all.

**Comment by pizzaboxer** [comment]
> I don't know if me forcefully closing it via task manager is causing the crash state in the log, because it will run forever if I let it. It will just remain a background process.

Yes, that is exactly why. Thanks for clarifying.

Seems like Roblox is starting up and creating a log file though. Can you privately send Roblox's latest log file from `%localappdata%\Roblox\logs`? Send it to me through Discord or something.

**Comment by DivineLiberty** [comment]
Sent in Discord DMs

**Comment by pizzaboxer** [comment]
What's your rendering mode set to?

**Comment by DivineLiberty** [comment]
From what I've tried myself, its currently set to automatic, but none of the rendering models has any different effect.

**Comment by pizzaboxer** [comment]
What about your framerate limit? Try setting it to 0.

**Comment by DivineLiberty** [comment]
So I did a lot of trial and error with this. Primarily playing with drivers. I reinstalled the GeForce drivers for my GPU by downloading the driver from the website and installing it that way. Everything now functions properly.

**Comment by pizzaboxer** [comment]
Oh, cool. Good to know it's fixed.

**Comment by xyzayd** [comment]
> From what I've tried myself, its currently set to automatic, but none of the rendering models has any different effect.

i have the same problem when i load bloxtrap for loading roblox nothing pops up and it goes to background process

**Comment by pizzaboxer** [comment]
> i have the same problem when i load bloxtrap for loading roblox nothing pops up and it goes to background process

Is this happening only with Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by xyzayd** [comment]
Both it was a issue I used to have with roblox only after I downloaded
bloxtrap before it worked now all of a sudden few weeks later non of them
work I uninstall both of them and tried it again dident work just doesn’t
load anything it’s either when I load roblox that goes to background
process or when I load bloxtrap that goes to background process and roblox
doesn’t open

**Comment by MikeyUsersREC** [comment]
@xyzayd

Refer [this Wiki page](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch) for debugging these issues, as it happens for both Bloxstrap and Roblox for you.
