### ISSUE TITLE
Simple Ideas

### ISSUE THREAD

**Issue by DANKIBOIOREAL** [pizzaboxer/bloxstrap#724]
- Add the shortcuts to hide GUIS in the help tab of the GUI
![image](https://github.com/pizzaboxer/bloxstrap/assets/129652478/2ffd067c-7e9d-4d23-a45f-16dc13ccf824)

- Add "old character" option which adds the little stud thingies at the top of arms & stuff 
![image](https://github.com/pizzaboxer/bloxstrap/assets/129652478/59390a4b-5060-484d-99a5-45d453616c31)

**Comment by pizzaboxer** [comment]
Not possible.
