### ISSUE TITLE
bloxtrap error

### ISSUE THREAD

**Issue by Vortiez** [pizzaboxer/bloxstrap#725]
System.Net.Http.HttpRequestException: An error occurred while sending the request.

[Inner Exception]
System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by pizzaboxer** [comment]
Sounds like a problem with your internet connection.. Does it happen every time you try to start it up, or has this only happened once?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
