### ISSUE TITLE
After changing deployment channel to live my Roblox Player began to crash

### ISSUE THREAD

**Issue by Terrosort** [pizzaboxer/bloxstrap#728]
I used to use admin version of roblox player but I think sometime around today it became outdates, so I decided changing to normal version, but after trying to so do my roblox player starts for about 20 seconds and crashes afterwards

**Comment by popbob2** [comment]
admin version? what was the channel

**Comment by pizzaboxer** [comment]
What? What's the "admin version"?

**Comment by ExtremePandaaYT** [comment]
Bro same I just opened an issue about this, and i think he means he was using the IMGUI build (not LIVE) but some people started getting error code 280 when it got patched. We are having the same issue.

**Comment by ExtremePandaaYT** [comment]
The channel for IMGUI is ZFeatureSoundworks-Testing

**Comment by pizzaboxer** [comment]
> We are having the same issue.

okay i dont care enough to help you then lol

**Comment by regisispoggerslmao** [comment]
> Bro same I just opened an issue about this, and i think he means he was using the IMGUI build (not LIVE) but some people started getting error code 280 when it got patched. We are having the same issue.

whats the IMGUI build, could you send me a link/download to it?

**Comment by yoyeet961** [comment]
i also want the imgui build
