### ISSUE TITLE
bring back 2016 top bar :3

### ISSUE THREAD

**Issue by gothprayer** [pizzaboxer/bloxstrap#730]
please

**Comment by retree1** [comment]
thats impossible bro

**Comment by gothprayer** [comment]
nah

**Comment by retree1** [comment]
> nah

yuh huh its impossible the top bar is in the coregui you cant edit it

**Comment by ImLoadingUuU** [comment]
Its possible but you need executor.

**Comment by Sahelantrophus** [comment]
stfu bruh

**Comment by pizzaboxer** [comment]
Find god

**Comment by Vaporboard** [comment]
You can use DataModelPatch and replace the corescripts and everything with the 2016 coregui

**Comment by popbob2** [comment]
download

**Comment by Vaporboard** [comment]
what?
