### ISSUE TITLE
BIG BIG BIG FPS DROPS

### ISSUE THREAD

**Issue by Catplayz2011** [pizzaboxer/bloxstrap#731]
when even i play every 10-15 sec my fps drops down to 15 or even 10 and my highest fps is like 70-90
my PC specs:
Processor | Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Video Card | Intel(R) HD Graphics 5500
Operating System | Windows 10
RAM | 12 GB

3x FPS DROPS IS 23s

https://github.com/pizzaboxer/bloxstrap/assets/144529766/f039618e-39dd-4557-b903-35da238877a6

my settings : 
![image](https://github.com/pizzaboxer/bloxstrap/assets/144529766/ceb63a0b-6048-404f-85b9-17be6d64ece1)

![image](https://github.com/pizzaboxer/bloxstrap/assets/144529766/a306d158-cbf8-4358-8329-ca3660076696)

thanks or helping this fps drop makes roblox unplayable i even deleted bloxtrap bec getting 20-40 fps with some light drop is better than getting every 10 sec big fps drops.

**Comment by Catplayz2011** [comment]
And btw how to change everything to black this white theme literally hurts my eyes

**Comment by Catplayz2011** [comment]
https://github.com/pizzaboxer/bloxstrap/assets/144529766/f76cea80-b088-4c94-a081-542851cc6d3d

here is the fps drop shown again

**Comment by pizzaboxer** [comment]
You have your rendering mode set to Vulkan. Does keeping it on Automatic do the same thing?

**Comment by Sahelantrophus** [comment]
integrated gpus are far too weak and using vulkan will do more bad than good. switch back to direct3d or automatic

**Comment by Catplayz2011** [comment]
ok i willl try

**Comment by Catplayz2011** [comment]
> You have your rendering mode set to Vulkan. Does keeping it on Automatic do the same thing?




I UPDATED my setting and my FPS DROPS are still there. They are now instead of every 8-15 sec, every 30-50 sec.
These FPS DROPS are still not gone...
![image](https://github.com/pizzaboxer/bloxstrap/assets/144529766/e1679f5c-8df3-4906-9ce5-0f5e12264684)
![image](https://github.com/pizzaboxer/bloxstrap/assets/144529766/7427831f-f339-44bd-87b0-1273559393a6)

**Comment by Catplayz2011** [comment]
> integrated gpus are far too weak and using vulkan will do more bad than good. switch back to direct3d or automatic

I overclocked my cpu so will it change something ?

**Comment by AeEn123** [comment]
**I suggest checking background processes with Task Manager** _(Ctrl+Shift+Esc)_ **since it may be caused by a background process.**

If it is not try checking your FastFlags in the FastFlags editor, and check if it affects the native version of roblox without launching it through bloxstrap.

**Comment by Sahelantrophus** [comment]
> I overclocked my cpu so will it change something ?

maybe, but you're still held back by your gpu, so any gains would be marginal. it could also lead to instability, or maybe it gets throttled since laptop cpus get hot

**Comment by pizzaboxer** [comment]
> I UPDATED my setting and my FPS DROPS are still there.

What about if you try setting your framerate limit to 0?

**Comment by Catplayz2011** [comment]
> > I UPDATED my setting and my FPS DROPS are still there.
> 
> What about if you try setting your framerate limit to 0?

Il try it + i overclocked my gpu so i hope it will change something

**Comment by Catplayz2011** [comment]
> > I overclocked my cpu so will it change something ?
> 
> maybe, but you're still held back by your gpu, so any gains would be marginal. it could also lead to instability, or maybe it gets throttled since laptop cpus get hot

So i know how to overclock i hit the sweet spot its my hobby when im bored lol I overclocked my GPU too, anyways i don't have fps drops anymore, i set fps limit to 0 as default so thanks for the support i will inform you guys if there is still any issue : D 👍
