### ISSUE TITLE
Crashing when opening Roblox using Bloxstrap.

### ISSUE THREAD

**Issue by ExtremePandaaYT** [pizzaboxer/bloxstrap#732]
![a64390d3153dd3cd72c909493ff3891c](https://github.com/pizzaboxer/bloxstrap/assets/83830854/7acc059f-4393-4f54-800b-5a61bc72fa6d)
![79b30ab50ee4d0d8aa80de43f6a6bb44](https://github.com/pizzaboxer/bloxstrap/assets/83830854/106ce0e6-6734-4115-8964-7571017f18a1)
![98d2953f434554e2086b8a3ef81ce28d](https://github.com/pizzaboxer/bloxstrap/assets/83830854/73e265db-5c05-4a27-91d2-6f90cbf02be8)
I hope someone can help me with this issue.

**Comment by ExtremePandaaYT** [comment]
The channel I used to use was ZFeatureSoundworks-Testing to use IMGUI but ever since 2 days ago it started giving me error code 280. I'm pretty sure it has to do with going back to an old version to use IMGUI again. But I cannot find a way to revert back to normal files and just bloxstrap, no IMGUI files.

**Comment by popbob2** [comment]
Roblox error code 280 occurs when the current version of the Roblox app being used is out of date.
Zfeaturesoundworks-testing is outdated
stop using it

**Comment by ExtremePandaaYT** [comment]
Yes I know, look at the picture, I switched to LIVE and roblox crashes now. I need to get back to normal Roblox files and I don't know how.

**Comment by popbob2** [comment]
did you save the changes

**Comment by ExtremePandaaYT** [comment]
Yep

**Comment by popbob2** [comment]
delete the version files and launch roblox

**Comment by ExtremePandaaYT** [comment]
Ok, thank you. I ended up deleting the entire bloxstrap file and redownloading it because I think I had like 4 different versions mixed together
