### ISSUE TITLE
Reshade built in to Bloxstrap?

### ISSUE THREAD

**Issue by M1dnight-ofcl** [pizzaboxer/bloxstrap#733]
I was tinkin we could add native support for reshade. I think there was suipport before but it got removed. Is there a way to force the dll onto roblox or something?

**Comment by popbob2** [comment]
impossible

**Comment by TheMetalTechnet** [comment]
> I was tinkin we could add native support for reshade. I think there was suipport before but it got removed. Is there a way to force the dll onto roblox or something?

Not possible because of Hyperion

**Comment by M1dnight-ofcl** [comment]
I forgot that exists...

**Comment by pizzaboxer** [comment]
> Is there a way to force the dll onto roblox or something?

If there was a way, there would still be an option for it in the menu.
