### ISSUE TITLE
the game not open 

### ISSUE THREAD

**Issue by Plokjoy** [pizzaboxer/bloxstrap#735]
so yeah i download this and add everything like the graphic and set to what i like, i clicked save abd tries to open the app and it is opening, i tried to restart my system but still nothing

**Comment by pizzaboxer** [comment]
> and add everything like the graphic and set to what i like

What'd you set your rendering mode to?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
