### ISSUE TITLE
Bloxstrap Menu as Separated version from Bloxstrap Itself

### ISSUE THREAD

**Issue by kek1ich** [pizzaboxer/bloxstrap#736]
Since i cannot use Start button (Do not question me please) I cannot get access to Bloxstrap menu as well!

**Comment by Sahelantrophus** [comment]
why can't you use the start button

**Comment by pizzaboxer** [comment]
> Since i cannot use Start button

Excuse me?

**Comment by kek1ich** [comment]
> > Since i cannot use Start button
> 
> Excuse me?

OS Issue, I literally can't do anything with it, Literally everything i tried was not fixing the Problem, But yeah it'll be for real cool if you would make the Menu as separated ver. of Regular Bloxstrap

**Comment by pizzaboxer** [comment]
Create a shortcut for `%localappdata%\Bloxstrap\Bloxstrap.exe -menu` on your desktop. Right click -> New -> Shortcut, paste it in.
