### ISSUE TITLE
Roblox Ramdomly Closing

### ISSUE THREAD

**Issue by ABoredGamingPlayer** [pizzaboxer/bloxstrap#737]
it started to happening in build a boat for a treasure i dont have soo many details sorry

**Comment by pizzaboxer** [comment]
Can I see the list of flags you have configured in the menu?

**Comment by OEMunlag** [comment]
I can confirm the same happens, Roblox freezes and then a "Roblox has just crashed. We're sorry!" dialog appeared
![image](https://github.com/pizzaboxer/bloxstrap/assets/87287937/ab104005-5574-4fdf-9974-15c87c68e022)
those are the only default FFlags I modified, I added no custom fflag

**Comment by pizzaboxer** [comment]
This isn't the same issue though, you're being shown a crash dialog. Open a separate issue for this.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
