### ISSUE TITLE
Roblox opening in background

### ISSUE THREAD

**Issue by gdsade** [pizzaboxer/bloxstrap#738]
sometimes it opens sometimes it doesnt i dont have rtss nor afterburner

**Comment by gdsade** [comment]
it works if i open normal roblox

**Comment by gdsade** [comment]
vulkan

**Comment by gdsade** [comment]
it works if i do automatic

**Comment by pizzaboxer** [comment]
> it works if i do automatic

Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch at all before opening this?
