### ISSUE TITLE
Version 1 Escape Menu not working

### ISSUE THREAD

**Issue by kotencja3** [pizzaboxer/bloxstrap#740]
![image](https://github.com/pizzaboxer/bloxstrap/assets/138238775/2c388690-3edf-4bea-9f52-2ccfe215a43c)
![image](https://github.com/pizzaboxer/bloxstrap/assets/138238775/1ec19838-b668-4f2c-8efb-2b6e0ed87bbe)

**Comment by pizzaboxer** [comment]
Just made a Wiki page for this. See https://github.com/pizzaboxer/bloxstrap/wiki/Selected-escape-menu-version-does-not-work.
