### ISSUE TITLE
Menu not switching properly

### ISSUE THREAD

**Issue by dontknowhattoputhere** [pizzaboxer/bloxstrap#742]
when i switched it to the 1st menu version it was still the 4th  menu version

**Comment by AngryRico** [comment]
Also having this issue, when i switch my preferred escape menu version to Version 1 (2015), it stays on the newest version which is the one with the dark theme.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Selected-escape-menu-version-does-not-work
