### ISSUE TITLE
error code 403 on an ALT

### ISSUE THREAD

**Issue by KayYourself** [pizzaboxer/bloxstrap#743]
So I wanted to play in an ALT but it doesnt let me and it shows me the error code 403

**Comment by KayYourself** [comment]
Ok i wanna say sorry for this "Issue" because i already fixed it. 
I love the fps unlocker btw

**Comment by codesdumb** [comment]
how did fix it i have the same problem

**Comment by icymanred** [comment]
> how did fix it i have the same problem

delete RobloxPlayer.dll in the folder roblox is in

**Comment by codesdumb** [comment]
> > how did fix it i have the same problem
> 
> delete RobloxPlayer.dll in the folder roblox is in 

im not sure where to find that

**Comment by pizzaboxer** [comment]
> how did fix it i have the same problem

Open the `%localappdata%\Roblox` folder path, delete the `LocalStorage` folder, then launch Roblox from either the desktop app or the website..
