### ISSUE TITLE
The top bar no longer works.

### ISSUE THREAD

**Issue by userminer2** [pizzaboxer/bloxstrap#744]
This issue legit just poped up tonight and I can't get the top bar to work. The buttons and menu are gone.

**Comment by pizzaboxer** [comment]
Try forcing a reinstallation through the Bloxstrap menu, it's in the behaviour tab at the bottom.

**Comment by Yell038** [comment]
done that twice, nothing happened.
i've disabled my fastflags and even tried pressing esc (i have to alt+f4 to leave the game)

**Comment by JordanTheFoxrety** [comment]
it probably broke due to the new menu that roblox put out recently, at least that's what i think on what the cause of the error is

**Comment by pizzaboxer** [comment]
> i've disabled my fastflags and even tried pressing esc (i have to alt+f4 to leave the game)

Oh, is it okay if you show a screenshot of what the game client window looks like?

**Comment by Yell038** [comment]
> > i've disabled my fastflags and even tried pressing esc (i have to alt+f4 to leave the game)
> 
> Since you're not OP, I need to see if you're actually having the same problem. Is it okay if you show a screenshot of what the game client window looks like?

![image](https://github.com/pizzaboxer/bloxstrap/assets/86011612/8cc61bf2-3f10-41be-b9b9-ba04aa36a441)

**Comment by pizzaboxer** [comment]
Open the Developer Console with F9. What does it show? If you can't see it, then privately send me Roblox's most recent log file from `%localappdata%\Roblox\logs`.

**Comment by Yell038** [comment]
> Open the Developer Console with F9. What does it show? If you can't see it, then privately send me Roblox's most recent log file from `%localappdata%\Roblox\logs`.

![image](https://github.com/pizzaboxer/bloxstrap/assets/86011612/ae232e7f-3312-4741-aba5-423e3b3439e4)
![image](https://github.com/pizzaboxer/bloxstrap/assets/86011612/add546dc-3abe-412f-8e63-bfaceb85802a)

**Comment by pizzaboxer** [comment]
What verison of the client are you using? Open the Bloxstrap menu, go to the Behaviour tab, and post what it shows under the Channel section.

**Comment by Yell038** [comment]
apologies, i just found out my issue was really from a texture pack that the new roblox menu broke

**Comment by pizzaboxer** [comment]
@userminer2 How about you?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
