### ISSUE TITLE
R15 Bug

### ISSUE THREAD

**Issue by D00MIY** [pizzaboxer/bloxstrap#746]
Everytime I open up and use a r15 character it just glitches out.
![RobloxScreenShot20231005_221138740](https://github.com/pizzaboxer/bloxstrap/assets/147119041/c5f0c0e7-f152-4c2c-8f59-8b7ae23c6430)

**Comment by pizzaboxer** [comment]
Have you checked if this happens without Bloxstrap too? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by D00MIY** [comment]
Roblox Player works perfectly fine but when I do it on BloxStrap is just bugs out, I don't know why it just started happened yesterday. I changed no settings and it just bugged on other games too that does r15 animation

**Comment by D00MIY** [comment]
I fixed it, It was just a bug with chibi and other games. It needs a restart and change to default settings and leave it for a day for is to correct is self. ty for reaching out though :)
