### ISSUE TITLE
Feature request: Allow ignoring the "connecting to roblox"

### ISSUE THREAD

**Issue by wilsontulus** [pizzaboxer/bloxstrap#75]
Also known as check for updates. Should be in the config. Good option if it's causing huge slowdowns to Roblox's update server or you just want to race through a private server link faster than ever before. 
It's actually not really a good idea for Roblox to check for updates every game launches in the first place, since either Roblox can have an auto-updater in the background, or they can just use the game client to compare between the server and client version and then, only need to alert the update in-game anyway.
Only caveat is that you might encounter the "Your roblox client is out of date" if another roblox client update just released, but still a good idea though!
Remember the reasons why this project exists: To improve the Roblox's bootstrapper and make it better than ever!

**Comment by pizzaboxer** [comment]
I'm not entirely sure I see the usefulness of this. Checking for updates only takes like one second, there's really no detriment whatsoever. Unless you mean not having Roblox automatically update so you're not stuck waiting for an update to install when trying to join a game as quickly as possible. That I can understand, and I can add an option to prompt on launch for that.

Also - not a good idea for Roblox to check updates whenever launching a game? That's how everyone does it and it's objectively the best way to do it. Having an auto-updater in the background would require a process to constantly be running in the background at all times, which obviously is not great.

**Comment by wilsontulus** [comment]
> Also - not a good idea for Roblox to check updates whenever launching a game? That's how everyone does it and it's objectively the best way to do it. Having an auto-updater in the background would require a process to constantly be running in the background at all times, which obviously is not great.
Well while that's also a good idea, remember that some people have issues in the check for updates session while their Roblox client is working great. And also you know about some people will be using this to enter private servers faster (as like this bootstrapper is way faster than Roblox's due to it's open-source nature..) so I think the checkbox should be implemented then

**Comment by pizzaboxer** [comment]
Yeah, I just meant not a good idea in comparison to a background updater. I do see a use for the option, and I'll consider adding it.
