### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XPIREDPIRED5** [pizzaboxer/bloxstrap#752]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i press alt+enter, the fullscreen option in setting turns on and when i try to add the FFlagHandleAltEnterFullscreenManually fflag in bloxstrap and press save and open it again its not in fflags. my rendering mode is vulkan

**Comment by pizzaboxer** [comment]
> when i try to add the FFlagHandleAltEnterFullscreenManually fflag in bloxstrap and press save and open it again its not in fflags. my rendering mode is vulkan

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/1fea71b5-f105-46f4-bab9-afd6d535cc27)
