### ISSUE TITLE
[BUG] Inventory doesn't open

### ISSUE THREAD

**Issue by bxcp** [pizzaboxer/bloxstrap#754]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

roblox inventory doesn't open with the keybind §, works without bloxstrap. tested in multiple games

**Comment by Sahelantrophus** [comment]
blud got his keyboard from the sims wdym §

**Comment by bxcp** [comment]
> blud got his keyboard from the sims wdym §

wtf are you saying im js european its where the inventory bind is on my keyboard, bloxstrap breaks that n it works without lol

**Comment by pizzaboxer** [comment]
Can I see the flags that you have configured in the Bloxstrap menu?

**Comment by bxcp** [comment]
I only have the default flags, and the one that changes the escape menu

**Comment by pizzaboxer** [comment]
I'm not entirely seeing the correlation here, and this sounds like something to do more with input than actually with Roblox? Still, a list of the flags would be nice.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
