### ISSUE TITLE
[BUG] Discord Rich Presence problem

### ISSUE THREAD

**Issue by OhsJol** [pizzaboxer/bloxstrap#755]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When you join an experience and teleport into another one (for example, teleporting from one experience to another with a teleporter) this happens:

> Joining into the game

![Discord_aSGIYb4ALh](https://github.com/pizzaboxer/bloxstrap/assets/147272672/0da825d1-abcb-4f05-a025-7f0f075a3b45)

> After teleporting to VC server with ingame button:

![Discord_O2Tq5NikBa](https://github.com/pizzaboxer/bloxstrap/assets/147272672/76c3421d-4895-42a7-b1f1-df5b5a0ec1b3)

**Comment by pizzaboxer** [comment]
Interesting, I can't replicate this myself. Try doing it again, and then please send me Bloxstrap's latest log file from `%localappdata%\Bloxstrap\logs` here.

**Comment by OhsJol** [comment]
> Interesting, I can't replicate this myself. Try doing it again, and then please send me Bloxstrap's latest log file from `%localappdata%\Bloxstrap\logs` here.

I also think I mischaracterized the situation. In short:
It's like story games:
You enter the game and you get into a lobby, and through that lobby you get into gameplay with a teleporter. BloxTrap probably doesn't detect this

I think you need this one
[Bloxstrap_20231008T092104Z.log](https://github.com/pizzaboxer/bloxstrap/files/12840279/Bloxstrap_20231008T092104Z.log)

**Comment by pizzaboxer** [comment]
> BloxTrap probably doesn't detect this

It's definitely supposed to. Does it happen with other games too? Try DOORS, go into an elevator and see if it detects the transition into the actual game.

**Comment by OhsJol** [comment]
> Does it happen with other games too? Try DOORS, go into an elevator and see if it detects the transition into the actual game.

I checked in another game and the situation was the same

**Comment by pizzaboxer** [comment]
Send me Roblox's latest log file from `%localappdata%\Roblox\logs` privately to me, either via email or via Discord.

**Comment by pizzaboxer** [comment]
I'm going to close this since I have a feeling this should be fixed by now, it's been a long while since I've seen any problems relating to the activity tracker.
