### ISSUE TITLE
[BUG] Bloxstrap not opening

### ISSUE THREAD

**Issue by PANCAKE-NOT** [pizzaboxer/bloxstrap#756]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So recently, ive encountered this problem, whenever i try to join a game or just launch roblox, it just doesnt open, but in the Resource Monitoring (Doesnt show in the Task Manager for some reason) shows that the RobloxPlayerBeta.exe is running.

My channel is "LIVE" and rendering mode is set to "Automatic" and i have latest .NET 6 Desktop Runtime installed and i never touched "Mods", also i always cleared the "Thumbnails", but that still didnt work.

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by PANCAKE-NOT** [comment]
Yes, i opened roblox without bloxstrap and it worked fine

Also on the issue, i tried playing today while i had this issue, and it suddenly worked, it can sometimes open and sometimes not and its really strange

**Comment by PANCAKE-NOT** [comment]
Uhh, its started working normal again, no idea how this even happened, but its fixed for now
