### ISSUE TITLE
[BUG] Bloxstrap Crashing.

### ISSUE THREAD

**Issue by YayaPlaysThis** [pizzaboxer/bloxstrap#757]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime I open bloxstrap it crashes with a error.

"An unexpected error occurred and Roblox needs to quit. We're sorry!"
![image](https://github.com/pizzaboxer/bloxstrap/assets/125162053/fa51d7f4-8df9-4773-8add-2cbd1da0418f)

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/5b75c609-e76c-4d46-9106-28a969362f20)

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by YayaPlaysThis** [comment]
i found out it's a roblox issue and for some reason it only works when i use a diff device/pc

**Comment by YayaPlaysThis** [comment]
also ms store lets me play roblox expect for web
