### ISSUE TITLE
[BUG] using bloxstrap, roblox textures take a long time to load

### ISSUE THREAD

**Issue by circunsicion** [pizzaboxer/bloxstrap#758]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was testing how bloxtrap works, I realized that, when activated, the textures take about 5 minutes to fully load
![image](https://github.com/pizzaboxer/bloxstrap/assets/147293106/bfe4ca29-17c2-4921-b0df-ebddf6775b97)
![image](https://github.com/pizzaboxer/bloxstrap/assets/147293106/27f8c0ce-cdc0-4b46-8678-965e9f4865f8)

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/49ae0691-2c44-42a1-8b7d-1ef179478883)

**Comment by Rolboxfan** [comment]
do u know when i try to download it says u need trust for bloxstrap how do u get trust

**Comment by CodingWithAnxiety** [comment]
> do u know when i try to download it says u need trust for bloxstrap how do u get trust

Not related to this issue, Please do not clutter.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
