### ISSUE TITLE
2015 escape menu not working

### ISSUE THREAD

**Issue by offdathc** [pizzaboxer/bloxstrap#759]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

2015 escape menu not working. When I choose the 2015 option for the escape menu and went into game it shows the default 2023 escape menu.

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/c79f3805-91b8-4079-afab-d1e359be2229)

https://github.com/pizzaboxer/bloxstrap/wiki/Selected-escape-menu-version-does-not-work
