### ISSUE TITLE
Feature Request: Able to add other integrations (except RFU)

### ISSUE THREAD

**Issue by Dameskii** [pizzaboxer/bloxstrap#76]
For example, if I wanted to make a certain application launch through .exe or shortcut I would simply make another folder in the Bloxstrap/Integrations/ folder. (as shown)
![dopus_an3CkC2vvJ](https://user-images.githubusercontent.com/112464024/215314052-630c91ec-b2ae-46fb-bf80-838cf8021af1.png)
and it would open the application, though it's just a concept, I'd like to see it happen!

**Comment by pizzaboxer** [comment]
That's an interesting idea. The thing with integrations right now is that they're hardcoded into the launcher, and each one has their own specific functionality (the RFU integration does more than just autolaunch with Roblox - it also preconfigures it and auto updates it). I think if you're just looking for a way to autostart a program when another program has launched, there would be a better way to do it that's not specific to Bloxstrap. But if there isn't, then I could consider this.

**Comment by Dameskii** [comment]
Thanks a whole lot for the response! you do reply pretty fast, though I was thinking of being able to add the applications through the Bloxstrap GUI as well. though doing little-to-no research, it is possible doing this even without installing another program through task scheduler though it is a hassle doing. then again I don't really see a way of doing this in such a simple way.

(This is what I found https://superuser.com/questions/745318/how-to-start-a-program-when-another-one-is-started)

**Comment by pizzaboxer** [comment]
Yeah, I was thinking of using Task Scheduler, but didn't realize how complex it was. I do see some possible use to this, so I'll definitely consider this as being a possible feature.

**Comment by Dameskii** [comment]
Thanks for considering it! I do believe it would make the integrations part of bloxstrap much more useful! sorry for the very late response, timezones and whatnot had to get in the way.

**Comment by shawnjb** [comment]
This would be awesome, then I can actually use my Synapse X auto-launch with this.
