### ISSUE TITLE
[BUG] custom icon doesn't work

### ISSUE THREAD

**Issue by 7CP77** [pizzaboxer/bloxstrap#760]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i made sure that i got the icon to the right sizes and when i saved it and relaunched, it was still the regular bloxstrap icon
https://github.com/pizzaboxer/bloxstrap/assets/142828959/1ed18266-35be-4212-901a-32eb54987e71

**Comment by pizzaboxer** [comment]
What did you use to create the icon?

**Comment by 7CP77** [comment]
> What did you use to create the icon?

i used a convert to ICO website

**Comment by pizzaboxer** [comment]
My bad, I didn't actually fully watch the video. It's actually working largely as intended, as the icon is only supposed to take effect only while launching, and it didn't really make sense to fit custom icons into the Hyperion bootstrapper style as it was only ever originally designed to use the one logo. Hope that clears it up.
