### ISSUE TITLE
TrueFullcreen capping FPS

### ISSUE THREAD

**Issue by michaelgaseosa** [pizzaboxer/bloxstrap#761]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### When i use true Fullscreen, my fps get randomly capped at 40-45 FPS and i dont know why, i have the FPS capped at 120, if i use windowed mode i get the regular cap, but if i use true fullscreen, 40-45 no matter what. I have this issue since the first of october and i dont know how to fix it. I am using a system booster and when i disable it, it does not do anything so it isnt the booster.
Now im gonna add the logs

[Bloxstrap_20231008T125840Z.log](https://github.com/pizzaboxer/bloxstrap/files/12840875/Bloxstrap_20231008T125840Z.log)
[0.597.1.5970668_20231008T134218Z_Player_66369_last.log](https://github.com/pizzaboxer/bloxstrap/files/12840876/0.597.1.5970668_20231008T134218Z_Player_66369_last.log)

Also the FlagList

{
  "FLogNetwork": "7",
  "DFIntTaskSchedulerTargetFps": "120",
  "DFIntCanHideGuiGroupId": "32380007",
  "FFlagDebugGraphicsPreferVulkan": "True",
  "FFlagRenderVulkanFixMinimizeWindow": "True",
  "FStringPartTexturePackTablePre2022": "",
  "FStringTerrainMaterialTable2022": "",
  "FStringTerrainMaterialTablePre2022": "",
  "FStringPartTexturePackTable2022": "",
  "FIntDebugForceMSAASamples": "1",
  "DFFlagTextureQualityOverrideEnabled": "True",
  "DFIntTextureQualityOverride": "0",
  "DFIntCSGLevelOfDetailSwitchingDistance": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL12": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL23": "0",
  "DFIntCSGLevelOfDetailSwitchingDistanceL34": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FIntFRMMinGrassDistance": "0",
  "FIntRenderShadowIntensity": "0",
  "FFlagDisablePostFx": "True",
  "FFlagDebugDisableTelemetryEphemeralCounter": "True",
  "FFlagDebugDisableTelemetryEphemeralStat": "True",
  "FFlagDebugDisableTelemetryEventIngest": "True",
  "FFlagDebugDisableTelemetryPoint": "True",
  "FFlagDebugDisableTelemetryV2Counter": "True",
  "FFlagDebugDisableTelemetryV2Event": "True",
  "FFlagDebugDisableTelemetryV2Stat": "True"
}

**Comment by 021josh021** [comment]
Y7ES BRO IM GETTING THE SAME THING LOOK https://streamable.com/713mo3

**Comment by pizzaboxer** [comment]
> When i use true Fullscreen, my fps get randomly capped at 40-45 FPS

Yeah, that's a weird quirk of exclusive fullscreen. Nothing much that I can really do anything about, that's just how it is. Though, I just realized I haven't mentioned that in the Wiki page, which I'll do now.

**Comment by 021josh021** [comment]
how do i disable true full screen than i dont wanna hve this bug

**Comment by pizzaboxer** [comment]
Since you're using Vullkan you'll just have to not use it.
