### ISSUE TITLE
[REQ] custom gun cursors 

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [pizzaboxer/bloxstrap#762]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

a feature to change the gun cursor  
![26c83ed6cb6c4495c32ec065ada4cb5476ea3efd](https://github.com/pizzaboxer/bloxstrap/assets/115115978/69bf4c6e-e860-494f-8113-78b986a805e3) what im talking about is this cursor , a feature that could change this cursor would be good , sorry for my bad explanation

**Comment by DrKoneko** [comment]
that'd be sick

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods
