### ISSUE TITLE
my roblox no longer says "error teleport to restricted area" anymore when i have 2 robloxes open

### ISSUE THREAD

**Issue by sweaterbruh** [pizzaboxer/bloxstrap#765]
i read ur comment to someones issue and u said "yes this is what roblox does with multiple instances not a bloxstrap problem roblox just does that", i was wondering if there was any way to make roblox do it again? please answer if u see cus i was really helped by that message error.

**Comment by pizzaboxer** [comment]
I'm confused. You want to intentionally show an error message?

**Comment by sweaterbruh** [comment]
> I'm confused. You want to intentionally show an error message?

Yes. It was a very easy way to play this game i play that auto kicks every 40 mins if im not always at the pc. Please help if u can cus i cant do it anymore

**Comment by pizzaboxer** [comment]
It was a bug that was fixed, so you can't really get it to show again. But now I'm even more confused. what does this error message have anything to do with avoiding being autokicked?

**Comment by sweaterbruh** [comment]
> It was a bug that was fixed, so you can't really get it to show again. But now I'm even more confused. what does this error message have anything to do with avoiding being autokicked?

When i would get the error message, it would make it to where i cant tp out of the server because my account was technically logged out, so i was able to stay in the server for a very long time without getting autokicked if i went afk at the 40 minute mark
