### ISSUE TITLE
[BUG] Response status code does not indicate succes

### ISSUE THREAD

**Issue by OfficialCommonly** [pizzaboxer/bloxstrap#766]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Attempted to play a Roblox game but encountered this error:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).

Log File: [Bloxstrap_20231011T032426Z.log](https://github.com/pizzaboxer/bloxstrap/files/12864488/Bloxstrap_20231011T032426Z.log)

**Comment by pizzaboxer** [comment]
Does this happen everytime you launch Roblox?
