### ISSUE TITLE
[BUG] Mouse cursor disappearing when pressing ALT + ENTER

### ISSUE THREAD

**Issue by bartlomidzier** [pizzaboxer/bloxstrap#768]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

the mouse cursor is disappearing whenever I press alt + enter for FSE which is useful for me and also when you're running on vulcan.

**Comment by pizzaboxer** [comment]
This only occurs for some people, and that's sort of just how FSE is. There isn't really anything that can be done to fix this, sorry.
