### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brickybattler** [pizzaboxer/bloxstrap#769]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

fps unlocker doesnt work

**Comment by pizzaboxer** [comment]
Are you using a laptop?

**Comment by RaveVitality** [comment]
Same thing is happening to me, on PC. The new version has been released and my microsoft firewall and nortron get set off by it. Not sure why this is only now starting to happen even though I have been using it fine for about a month.

**Comment by pizzaboxer** [comment]
...I don't think that's what they're talking about

> Not sure why this is only now starting to happen 

Because I released an update. This always happens for like a few days whenever I release an update for some reason.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
