### ISSUE TITLE
Intergrate Special K

### ISSUE THREAD

**Issue by captainaxron** [pizzaboxer/bloxstrap#77]
Basically texture packs in Roblox.
* Injects custom textures into Roblox
Issues
* Roblox might regognize it as a hack with AC

**Comment by pizzaboxer** [comment]
Oh, interesting, never heard of this before. I'll take a look at this later and see if there's any issues or conflicts with it.

**Comment by pizzaboxer** [comment]
Took me two weeks to actually get around to trying this! Would've been cool, but uh.....
![image](https://user-images.githubusercontent.com/41478239/218733953-6ee0996a-76fb-454b-9847-0ead91a80f90.png)

Thanks for the suggestion though, never knew this was a thing.

**Comment by he3als** [comment]
Sadly Special K doesn't work, I tried using OpenGL and DirectX on Roblox, but it still failed with that message.

It is a very good tool though.
