### ISSUE TITLE
[REQ] Add Mobile Highlight support (FFlagHighlightOutlinesOnMobile)

### ISSUE THREAD

**Issue by IxGamerXL** [pizzaboxer/bloxstrap#770]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I've found a FastFlag which fixes the issue which some computers have: Highlight instances have limited transparency and/or the outlines don't appear.

This flag is called `FFlagHighlightOutlinesOnMobile`, and it is a boolean defaulted to False. It makes highlight outlines more visible and highlight fill transparency solid rather than a checkered pattern. I would abbreviate this flag as "Highlight Render Compatibility" in the FastFlag menu.

Including a built-in FastFlag setting for this could really help some people, as some games rely on highlights too heavily, making gameplay quite impaired for some. One such game is DOORS, specifically room 50, as all the books are outline-only. A more minor example is Slap Battles, where higher phases of Killstreak and Reaper don't have outlines when they should.

**Comment by IxGamerXL** [comment]
Quite honestly, Roblox needs to add this fastflag as a dedicated visual setting in the escape menu as well as a studio setting. If anyone has the ability to create a feature request on the devforums to add this officially, please do

**Comment by CodingWithAnxiety** [comment]
I'll actually look into this for you soon, sound good?

**Comment by pizzaboxer** [comment]
This seems very borderline on giving people an advantage. How big is the difference in outline thickness between having it off and on?

**Comment by IxGamerXL** [comment]
> This seems very borderline on giving people an advantage. How big is the difference in outline thickness between having it off and on?

Someone would have to check other than me since my outlines are too thin to be visible by default, but I don't see how thicker outlines would make an advantage. You could make it so it only works under a certain resolution by simply checking the screen resolution and applying the flag if the resolution is too low and the setting for the flag is enabled, which should prevent unneeded/unfair use.

**Comment by nakoyasha** [comment]
> fill transparency solid rather than a checkered pattern. 
 
the checkered pattern only appears if you have a GPU that does ***not*** support DX11 and has to rely on DX10 instead, which afaik isn't even supported by roblox and could be removed at any moment
there's no point in adding a dedicated option for something that barely anyone relies on when it's something they can already enable manually with the fflag editor

> You could make it so it only works under a certain resolution by simply checking the screen resolution and applying the flag if the resolution is too low and the setting for the flag is enabled, which should prevent unneeded/unfair use.

they can still enable it with the fflag editor and bypass the restriction. the best move here is to not add the option at all

**Comment by CodingWithAnxiety** [comment]
If we'r enot adding this, it should be closed.

**Comment by IxGamerXL** [comment]
Now that I think about it, the flag probably doesn't be changing the thickness of the outline, since it already looks like it uses a different rendering method that supports a larger variety of devices. In order for us to know whether or not it does change thickness, we would need someone with already-functional Highlights to find the differences of the flag being on and the flag being off.

If it doesn't change thickness as I originally thought, then there should be no issues adding this.

**Comment by pizzaboxer** [comment]
What game is this best visible in so I can test this out?

**Comment by IxGamerXL** [comment]
> What game is this best visible in so I can test this out?

@pizzaboxer You can execute this Luau snippet in the developer console when playing one of your own games.

```lua
local name = "IxGamerXL" -- Replace string contents with your roblox username

local player = game:GetService("Players")[name]
local hl = player.Character:FindFirstChild("Highlight") or Instance.new("Highlight", player.Character)
hl.FillColor = Color3.new(0,.5,1)
hl.OutlineColor = Color3.new(1,0,0)
hl.FillTransparency = 0.5
hl.OutlineTransparency = 1
```

Using this, you can easily add a highlight to yourself and directly check the differences. The highlight fill will appear in blue and the highlight outline will appear in red.

**Comment by IxGamerXL** [comment]
> EDIT: excuse my non-alcohol-induced drunkness, outline transparency was 1 for some dumb reason.

Update on the snippet if you didn't notice and tried it out before I fixed it.
