### ISSUE TITLE
Bloxstrap doesn't seem to have a way to work with Roblox Studio

### ISSUE THREAD

**Issue by IxGamerXL** [pizzaboxer/bloxstrap#771]
I'm seeing suggestions to include Roblox Studio and all of them are resolved, and there's even a pull request which seems to have been merged with Bloxstrap's directory. The only problem is that there doesn't seem to be a visible way to actually use Roblox Studio with Bloxstrap.

Is there a visible and viable method to using Roblox Studio with Bloxstrap or is the method to using Roblox Studio just not there? _Is there even a way to wrap Roblox Studio with Bloxstrap?_

I decided to use a blank issue template since this doesn't seem to be a bug nor a feature request. It's just that it seems like there is no actual way to use Roblox Studio with Bloxstrap, yet it looks like there is code which handles this.

First relevant suggestion for Studio Support: #36
Pull request which merged Studio support to main thread: #739

**Comment by pizzaboxer** [comment]
> and there's even a pull request which seems to have been merged with Bloxstrap's director

Yes... on a branch that hasn't been released yet.
