### ISSUE TITLE
[BUG] Byfron banned (?)

### ISSUE THREAD

**Issue by essentialsasset** [pizzaboxer/bloxstrap#775]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![RobloxPlayerBeta_Ulnd7bmop6](https://github.com/pizzaboxer/bloxstrap/assets/139980767/282dd74b-7d9b-4ead-a8ef-8ffe4ef86f68)

got kicked after 25 minutes of playing. reverted back to the default bootstrapper the same happens after reinstalling roblox

**Comment by essentialsasset** [comment]
nvm this is a problem with roblox

**Comment by essentialsasset** [comment]
nvm

**Comment by CodingWithAnxiety** [comment]
**Please mark this as closed.**

**Comment by essentialsasset** [comment]
the issue is still here

**Comment by essentialsasset** [comment]
issue resolved
