### ISSUE TITLE
Bloxstrap folder isn't created [BUG] 

### ISSUE THREAD

**Issue by Rblxlover** [pizzaboxer/bloxstrap#776]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I download Bloxstrap the folder doesn't create

**Comment by CodingWithAnxiety** [comment]
Could you give a bit more detail?

**Comment by pizzaboxer** [comment]
> Whenever I download Bloxstrap the folder doesn't create

What folder? Also, what do you mean whenever you download it? Do you mean whenever you install it?

**Comment by Rblxlover** [comment]
Aight so basically when i download bloxstrap it pops up with an error saying that the Bloxstrap Folder in local isnt there
therefore i cant use it

**Comment by Rblxlover** [comment]
Aight so basically when I install Bloxstrap I open it right? Well when I open it there's an error that says the folder named "Bloxstrap" in Appdata\Local isnt there bc it wasnt created or smth

**Comment by Rblxlover** [comment]
wait nvm its working now

**Comment by pizzaboxer** [comment]
> Well when I open it there's an error that says the folder named "Bloxstrap" in Appdata\Local isnt there bc it wasnt created or smth

...It would've helped to show what the error was actually saying.
