### ISSUE TITLE
[BUG] Fps unlocker is not working

### ISSUE THREAD

**Issue by Safisbro** [pizzaboxer/bloxstrap#777]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The fps unlocker isnt working i hae downloaded the blox trap 5 times but it isnt working

**Comment by Safisbro** [comment]
fix the problem

**Comment by pizzaboxer** [comment]
Are any of your other flag changes applying (escape menu version, lighting mode, etc)?

**Comment by 021josh021** [comment]
> Are any of your other flag changes applying (escape menu version, lighting mode, etc)?

i use a no texture fast flag could that be causing the problem?

**Comment by pizzaboxer** [comment]
> i use a no texture fast flag could that be causing the problem?

I asked if they are applying, and if they work or not.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by JaydenvsmRBLX** [comment]
sadly, if you use bloxstrap it doesnt work

**Comment by JaydenvsmRBLX** [comment]
i got an error while doing it to and it said it was in the bloxstrap client settings folder, there was a note for fps unlocker and i tried erasing it but everytime i launched bloxstrap it came back again

**Comment by pizzaboxer** [comment]
What was the error?
