### ISSUE TITLE
[BUG] Can't Open Play Roblox because New Roblox Update

### ISSUE THREAD

**Issue by adiglows** [pizzaboxer/bloxstrap#778]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was just playing normally, and I saw there's a **Roblox** update, so I updated it, and after that, I couldn't open **Play Roblox** anymore, I actually **could**, and it shows in **Task Manager**, but it shows **nothing**. Hopefully you understand me. English isn't my first Language. Like everything seems to work fine except that it shows **Roblox** or anything. I can **_still change_** **Bloxstrap Settings** and open **Bloxstrap Menu.** Actually, I forgot to mention that the Normal Roblox still Opens. So yea...
I hope you guys can help me!

**Comment by mikess729** [comment]
ye cant play roblox and keep crashing 
![image](https://github.com/pizzaboxer/bloxstrap/assets/147807827/bb384067-5f71-4569-8e64-0ebf31cf7565)

**Comment by TheMetalTechnet** [comment]
> ye cant play roblox and keep crashing ![image](https://user-images.githubusercontent.com/147807827/274842528-bb384067-5f71-4569-8e64-0ebf31cf7565.png)

This is a Roblox error, 85% not related to bloxstrap

**Comment by adiglows** [comment]
> ye cant play roblox and keep crashing ![image](https://user-images.githubusercontent.com/147807827/274842528-bb384067-5f71-4569-8e64-0ebf31cf7565.png)

Uhh, That's totally different from I had, I didn't crash, but it doesn't matter because It's not really even related to bloxstrap because it is just a normal Roblox error screen 💀

**Comment by adiglows** [comment]
I hope this is going to get some knowledge soon. Because i finally wanna play with bloxstrap again!

**Comment by pizzaboxer** [comment]
Did you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

**Comment by pizzaboxer** [comment]
Are you using Vulkan?

**Comment by adiglows** [comment]
> Are you using Vulkan?

_Yes_ **_I_** do.

**Comment by adiglows** [comment]
Dude, I littearly switched it to something else, and it started working again 💀

**Comment by adiglows** [comment]
wait i think it might be i need to update my uhh, you know

**Comment by adiglows** [comment]
imma see if i have updates

**Comment by adiglows** [comment]
idk why but vulkan doesnt work for me anymore, it used to, but not anymore. i had updates but it did absouletuly nothing.

**Comment by adiglows** [comment]
i guess imma just use Automatic for now.

**Comment by pizzaboxer** [comment]
I didn't link you to the wiki article for no reason, mind you.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/3c183167-6039-46ed-bf63-a93b5a6c3e96)

**Comment by adiglows** [comment]
Thank you for the Help!
