### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zwqrk** [pizzaboxer/bloxstrap#779]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cannot see the chat, i only see chat bubbles but i can still send a message but still i cant see the chat
![RobloxScreenShot20231013_180051433](https://github.com/pizzaboxer/bloxstrap/assets/147816098/3fde45a7-4cff-457f-ad8f-039e6caad3f2)

**Comment by zwqrk** [comment]
![Screenshot 2023-10-13 180331](https://github.com/pizzaboxer/bloxstrap/assets/147816098/8b1a83fc-8ca2-42e1-9220-c2814d3bbefa)
this is the chat on a normal roblox

**Comment by pizzaboxer** [comment]
Can I see the flags you have configured in the Bloxstrap menu?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
