### ISSUE TITLE
BIGGEST BUG EVER

### ISSUE THREAD

**Issue by xMatti12** [pizzaboxer/bloxstrap#780]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

its says System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\grima\AppData\Local\Temp\Bloxstrap-v2.5.3.exe' with working directory 'C:\WINDOWS\system32'. The specified executable is not a valid application for this OS platform.

**Comment by pizzaboxer** [comment]
Try manually updating by downloading v2.5.3 at https://github.com/pizzaboxer/bloxstrap/releases/latest
