### ISSUE TITLE
[BUG] unable to launch roblox browser version with bloxstrap

### ISSUE THREAD

**Issue by spacewill678** [pizzaboxer/bloxstrap#781]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when bloxstrap was downloaded i was trying to launch the browser version of roblox and it was going pretty well until it said "installing roblox" and it didnt launch any roblox tabs. i then uninstalled bloxstrap then launched roblox again without bloxstrap this time and it launched fine. but if i install bloxstrap again i would not be able to launch roblox again but using bloxstrap on the desktop version of roblox works perfectly fine

**Comment by pizzaboxer** [comment]
> until it said "installing roblox" and it didnt launch any roblox tabs.

What did it do after it said that? Did it move onto starting it?

**Comment by spacewill678** [comment]
> > until it said "installing roblox" and it didnt launch any roblox tabs.
> 
> What did it do after it said that? Did it move onto starting it?

no it didnt start at all. after the "installing roblox" appeared nothing would launch and no error messages appeared

**Comment by pizzaboxer** [comment]
Did you two read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by spacewill678** [comment]
ive seem to figured out the issue of this, it may have to do with what browser you are using. when i launched bloxstrap using the firefox browser roblox wouldnt launch but when i switched to chrome it launched perfectly

**Comment by pizzaboxer** [comment]
> when i launched bloxstrap using the firefox browser roblox wouldnt launch but when i switched to chrome it launched perfectly.

That shouldn't have any correlation. A launch is a launch. Can you confirm if it's working on both?

**Comment by spacewill678** [comment]
working on chrome not working on firefox

**Comment by pizzaboxer** [comment]
In Firefox, if you enter `roblox-player:1+launchmode:app` into the address bar, what does it do?

**Comment by spacewill678** [comment]
installs roblox then doesnt do anything else

**Comment by pizzaboxer** [comment]
Okay, so then Bloxstrap does launch. What about Chrome?

**Comment by spacewill678** [comment]
chrome asks to "open bloxstrap" does "starting roblox..." but doesnt launch

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by Grovvy6456** [comment]
why not microsoft edge
