### ISSUE TITLE
[REQ] Custom Cursors!

### ISSUE THREAD

**Issue by JSkes** [pizzaboxer/bloxstrap#782]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Can you add a feature to use your own Roblox custom cursors instead of the 2013/2006 cursors, I've made my own edited version of the 2006 cursors and would like to use them.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Adding-custom-mods

**Comment by JSkes** [comment]
Sorry for the late response, a few hours after I posted this, I figured out that I could already do that, so yeah, sorry about that.
