### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Gelaxiz** [pizzaboxer/bloxstrap#783]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I just launched roblox then saw this
![Capturee](https://github.com/pizzaboxer/bloxstrap/assets/130848366/8585f169-aeab-4c43-a9dc-5e14bfdd2cd9)
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/130848366/7de66b75-530b-49f5-aa80-aff5d9556fdd)

it does launch but just shows this

**Comment by pizzaboxer** [comment]
Recent Roblox issue, has nothing to do with Bloxstrap. See #774.
