### ISSUE TITLE
[BUG] unable to connect to roblox

### ISSUE THREAD

**Issue by IMTHECOOLEST** [pizzaboxer/bloxstrap#784]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

so, i was trying to play a game but bloxstrap gave me a error, heres what it gave me,System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:8888)

[Inner Exception]
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.

**Comment by pizzaboxer** [comment]
Are you using a proxy?

**Comment by pizzaboxer** [comment]
Took me a moment to realize why this is happening. Just clear your Windows proxy settings. Also, stop using Fiddler for things you probably shouldn't be using it for.
