### ISSUE TITLE
Suggestion; Add a feature that removes textures & a feature that lets you change the default font

### ISSUE THREAD

**Issue by AnaIytics** [pizzaboxer/bloxstrap#79]
Suggestion; Add a feature that removes textures & a feature that lets you change the default font

**Comment by Extravi** [comment]
It's not possible to remove the textures Roblox made them server side.

**Comment by pizzaboxer** [comment]
If you want to change the default fonts, look into how to make your own custom mods. There's a README file in the mod folder that explains how to apply your own custom mods, where you can do stuff like change fonts.

**Comment by AnaIytics** [comment]
> If you want to change the default fonts, look into how to make your own custom mods. There's a README file in the mod folder that explains how to apply your own custom mods, where you can do stuff like change fonts.

Figured that out, just need textures but apparently as the reply above says, they're serversided and can't be removed
