### ISSUE TITLE
[REQ] 

### ISSUE THREAD

**Issue by wlshedd** [pizzaboxer/bloxstrap#790]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

if its possible an option to fix the camera bug when using a controller on PC with high FPS would be pretty cool :)

**Comment by pizzaboxer** [comment]
Camera bug? Can you elaborate more on this please?

**Comment by wlshedd** [comment]
> Camera bug? Can you elaborate more on this please?

when using a controller on PC with high FPS the camera is WAY too fast for some reason. and changing it in the settings doesn’t make a difference.

**Comment by pizzaboxer** [comment]
I've looked through the flag list, and I don't believe that there is an option available to alter this. Sorry.
