### ISSUE TITLE
[BUG] Access is denied.

### ISSUE THREAD

**Issue by CoolSoulz** [pizzaboxer/bloxstrap#791]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try to install Bloxstrap, I get the following error: System.UnauthorizedAccessException: Access to the path 'C:\Users\username\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
[Bloxstrap_20231018T142107Z.log](https://github.com/pizzaboxer/bloxstrap/files/13029721/Bloxstrap_20231018T142107Z.log)

**Comment by pizzaboxer** [comment]
Delete the folder at `%localappdata%\Bloxstrap` before trying to reinstall. Bug is known, it has been fixed, I just haven't pushed it out yet.

**Comment by jaynardd** [comment]
Yeo! how do i fix this problem? 
![image](https://github.com/pizzaboxer/bloxstrap/assets/148675748/b743a700-3dba-4297-aa1f-08d29f02754d)

**Comment by jaynardd** [comment]
> Yeo! how do i fix this problem? ![image](https://user-images.githubusercontent.com/148675748/277149398-b743a700-3dba-4297-aa1f-08d29f02754d.png)

I just redownload it cuz my roblox is not launching at first then when i tried to install it it says that

**Comment by pizzaboxer** [comment]
Check to make sure Roblox isn't running in the background, then install.
