### ISSUE TITLE
[BUG] Bloxstrap is unable to connect to Roblox

### ISSUE THREAD

**Issue by lugolol** [pizzaboxer/bloxstrap#793]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (127.0.0.1:8888)

[Inner Exception]
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.

**Comment by pizzaboxer** [comment]
stop using fiddler lol
