### ISSUE TITLE
[BUG] Fixed width fonts cause cutoffs in the Bloxstrap Menu

### ISSUE THREAD

**Issue by RUvlad1** [pizzaboxer/bloxstrap#797]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've noticed that text gets cut off when using a fixed width font like JetBrains Mono as your system font

![image](https://github.com/pizzaboxer/bloxstrap/assets/60317461/d7cbbae1-6769-4cfd-80a9-23f119ec88c9)

![image](https://github.com/pizzaboxer/bloxstrap/assets/60317461/7843ce5a-3c0a-4720-9e69-26d319e1c066)

![Bloxstrap_b1](https://github.com/pizzaboxer/bloxstrap/assets/60317461/57180171-29c3-4d39-92ee-47ef020e774d)

It's not that big of an issue as you can still sometimes guess what the rest of the text says, but this would still probably be appreciated by other people who customize their Windows install

**Comment by pizzaboxer** [comment]
About those descriptions, I'm working on redoing those in the next update to be more conscise. Especially important as internationalization will mean varying text lengths.

Can't do much about the others though, that's just something you'll have to deal with. Not my problem.
