### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by carsten34** [pizzaboxer/bloxstrap#798]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cant installed Bloxstrap with the error code

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE because it returned HTTP 503 (Service Unavailable)

**Comment by CinnamonLambda** [comment]
Roblox is currently down. https://status.roblox.com/

**Comment by carsten34** [comment]
oh ok thx

**Comment by pizzaboxer** [comment]
The error message literally tells you that Roblox is down.
