### ISSUE TITLE
[REQ] Allow to change unchoosable languages in app.

### ISSUE THREAD

**Issue by cub-has-injected** [pizzaboxer/bloxstrap#799]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

# How do I run it?
1. Join any place, for example.
2. Get the command line in Process Hacker or System Informer and immediately close process of Bloxstrap. (You should close it to avoid a 403 error because the session is already used/joined)
![image](https://github.com/pizzaboxer/bloxstrap/assets/83903792/059da5fd-2096-418b-9181-f7bb18e8d503)
3. Modify the latest arguments to "**robloxLocale:en_us**+gameLocale:en_us+channel:+LaunchExp:InApp"
*You can change "en_us" to another one, examples of working ones are: de, en-us, es, es-es, fr, id, it, ja, ko, pt, pt-br, ru, th-th, zh-cn, zh-tw, zh-cjv*
4. Open it again in any browser.
4. Enjoy the official localization.

## It is located along the path: *\ExtraContent\translations\CoreScriptLocalization.csv*
It contains working localizations that have not yet been used, for example: 
Russian, Indonesian, and others.
![image](https://github.com/pizzaboxer/bloxstrap/assets/83903792/1bf113a0-7e2a-4316-b7c8-7061da54cc58)

It would be amazing if you could select them rather than catch them through a third-party program and open them in the browser.

**Comment by TheMetalTechnet** [comment]
If you have to use third party program for that maybe Roblox just doesn't want you to use it (yet)

**Comment by pizzaboxer** [comment]
Oh, I didn't even think about this. This is a good idea.

**Comment by TheMetalTechnet** [comment]
v2.6.0 should be called "The Language Update" lol

**Comment by mishafreddi** [comment]
I DID NOT UNDERSTAND ANYTHING AT ALL
I DON'T UNDERSTAND HOW TO DO THIS
HOW TO OPEN THE PROCCES HACKER COMMAND LINE
AND I DON’T UNDERSTAND PROBABLY BECAUSE OF MY KNOWLEDGE OF ENGLISH AND THE TRANSLATION OF DAMN MICROSOFT EDGE

**Comment by cub-has-injected** [comment]
> I DID NOT UNDERSTAND ANYTHING AT ALL I DON'T UNDERSTAND HOW TO DO THIS HOW TO OPEN THE PROCCES HACKER COMMAND LINE AND I DON’T UNDERSTAND PROBABLY BECAUSE OF MY KNOWLEDGE OF ENGLISH AND THE TRANSLATION OF DAMN MICROSOFT EDGE

Right-click on any program and click properties. It should pop up "Command Line:" 🥱

**Comment by moyaimoment** [comment]
> I DID NOT UNDERSTAND ANYTHING AT ALL I DON'T UNDERSTAND HOW TO DO THIS HOW TO OPEN THE PROCCES HACKER COMMAND LINE AND I DON’T UNDERSTAND PROBABLY BECAUSE OF MY KNOWLEDGE OF ENGLISH AND THE TRANSLATION OF DAMN MICROSOFT EDGE

why are you yelling

**Comment by cub-has-injected** [comment]
> > I DID NOT UNDERSTAND ANYTHING AT ALL I DON'T UNDERSTAND HOW TO DO THIS HOW TO OPEN THE PROCCES HACKER COMMAND LINE AND I DON’T UNDERSTAND PROBABLY BECAUSE OF MY KNOWLEDGE OF ENGLISH AND THE TRANSLATION OF DAMN MICROSOFT EDGE
> 
> > Right-click on any program and click properties. It should pop up "Command Line:" 🥱
>
>For some reason I don't get any pop-ups about the command line.
>Should I use the full version or the portable one?

По идее, ты должен использовать [System Informer](https://systeminformer.sourceforge.io/), там все есть, ибо Process Hacker уже перестали обновлять, хоть и некоторые интересные функции в нем остались. Full или Portable не имеет значения.

**Sorry for using a different language, just trying to help him in his language.**

**Comment by pizzaboxer** [comment]
I'm working on adding this, but I've just discovered there's some pretty big limitations with this. The biggest one is that this only works when you're in a game. The desktop app doesn't get translated for some reason. Another issue is that it only works for Roblox website launches. Deeplinks/direct app opening will not work here.

So, this feature won't work exactly as people expect.

**Comment by pizzaboxer** [comment]
I've also noticed that at this point it's only just Russian that still isn't listed. The option will be specific to that then, and will likely become irrelevant in the future.

**Comment by pizzaboxer** [comment]
Released in 2.7.0
