### ISSUE TITLE
suggestion: make a discord server

### ISSUE THREAD

**Issue by dropier** [pizzaboxer/bloxstrap#8]
you should make a discord server about the plugin for ease of use and for people to get better help if you're inactive but a member knows the solution but can't comment since they don't have a github account, i mean, that's not a good reason but i still think a discord server would be useful

**Comment by pizzaboxer** [comment]
Really not worth it for a small project like this, GitHub issues are practically the standard way for providing feedback to repositories.

**Comment by dropier** [comment]
oh ok

**Comment by dropier** [comment]
i have a last suggestion i will write
