### ISSUE TITLE
Feature Request: Option to have a confirmation prompt before launching Roblox

### ISSUE THREAD

**Issue by Chedski** [pizzaboxer/bloxstrap#80]
Essentially, just have a dialog asking "Do you want to launch Roblox?" before actually starting the game.  
This can be very useful if you work with a lot of VIP server links, and helps prevent getting kicked out of a server because you accidentally reloaded a game page with a VIP link in it

**Comment by BeyondThe5D** [comment]
bump

**Comment by pizzaboxer** [comment]
Alternative solution: by default, browsers should prompt you whenever you want to launch an external application. Many people tend to disable it as it gets annoying quick, but it seems like a good solution to your problem.

For instance, with Microsoft Edge, it typically looks something like this:
![image](https://user-images.githubusercontent.com/41478239/217904082-fa840e67-febd-4598-98b0-92939e856845.png)

If you've checked that "always do this" checkbox, which you likely have, you can undo it in your browser settings.
![image](https://user-images.githubusercontent.com/41478239/217904383-93575fc2-f7c9-4cbc-bb4f-8c8264632e35.png)

This goes for any browser, not just Edge. Just look online for how to re-enable application launch prompting for your browser.

**Comment by Chedski** [comment]
That is a decent solution for many situations, but there are a few cases where it can cause issues - some browsers prevent you from switching tabs or interacting with the page while one of these prompts are open

**Comment by pizzaboxer** [comment]
Do any browsers do this? Just checked Firefox and Edge and they don't, and even then pressing the escape key to close them is quick and easy.

**Comment by Chedski** [comment]
I remember Firefox doing this at some point, although it might just be a platform specific thing (or just changed since then).
This could still be useful in some other niche cases, such as launching Roblox from scripts.
