### ISSUE TITLE
[REQ] Adding a Motion Blur option when shaders are turned on.

### ISSUE THREAD

**Issue by Mattem300** [pizzaboxer/bloxstrap#802]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

_(This is being asked once again on this **Github** page because that issue is very old and since then **Reshade** hasn't existed as a thing for **Roblox** because of the **Anti-Cheat and 64-bit update**, I hope this doesn't really cause some issues making this not a **valid request**.)__                                                                     

So once I was thinking about getting **Roblox Motion Blur** without having a **244hz monitor**. And since I have been a **Bloxstrap** user since **January of 2023** (about when the **anti-cheat** was added) I wanted that back because of the **anti-cheat** removing **Reshade** as a **shader platform for Roblox**... And then I just remembered that I used the **MotionBlur on Reshade**, I wanted it back but this will not work because of the **Anti-Cheat and the 64-bit update**, and that made me a bit upset over why **Roblox** just didn't add an **Anti-Cheat** that would not block any time of **Game Shaders** that a lot of players wanted as a normal function in **Roblox**. This is once again why I started using **Bloxstrap** as my driver for playing **Roblox**...      

Anyway thanks for implementing this feature back into **Roblox** (if it even gets added)
Thanks, -Matthew (My real name is Matthew but since I am from the Czech it is completely different.)

**Comment by pizzaboxer** [comment]
This isn't possible. I can't do this. Sorry.
