### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wowreal** [pizzaboxer/bloxstrap#803]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Everytime i open bloxstrap in full screen and then close it, it freezes.(Apps can still run in the background, and the win(Windows) button doesn't work) This is not a bug i find in the roblox you install on the website. Does anyone have a solution?

**Comment by pizzaboxer** [comment]
What's your rendering mode set as?

**Comment by andor22** [comment]
when i put my commend like:"the old backround avatar creator" it doesnt woork when  i press changes bc when i start "play roblox"noothing changes

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
