### ISSUE TITLE
[BUG] Bloxstrap doesn't launch the client

### ISSUE THREAD

**Issue by nick1buns** [pizzaboxer/bloxstrap#804]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I try to play a game on Roblox, Bloxstrap loads up the client, but never opens it.
I have already checked the wiki article for this problem, and I've tried all the solutions on there, but nothing is working.
Before this problem occurred, the client crashed frequently, which was annoying, but it wasn't too bad.
Now, with this new problem, I can't play Roblox at all. **This is not a problem with the Roblox client too, it's only a Bloxstrap problem.** 

I haven't been able to play Roblox for days now, and it's getting very annoying. Please help!

NOTE: I have also tried to open the Roblox app (not website) thru the Bloxstrap "Play Roblox" shortcut app. It also doesn't work.

**Comment by pizzaboxer** [comment]
Can I see the flags you have configured?

**Comment by nick1buns** [comment]
here you go
![image](https://github.com/pizzaboxer/bloxstrap/assets/131322760/68255510-1d23-4335-9688-bd2240750cdb)
![image](https://github.com/pizzaboxer/bloxstrap/assets/131322760/1397f7ff-5288-4da7-9f4d-f86a2abe2f49)

**Comment by pizzaboxer** [comment]
You could try setting the framerate limit as zero, and see if that changes anything. Let me know if it doesn't.

**Comment by nick1buns** [comment]
Nothing changed. It kind of had more loading time than before, but it still didn't launch the client.

**Comment by pizzaboxer** [comment]
If you don't mind, can you send me your whole installation folder? (except for the Downloads folder, just delete it or something)

**Comment by nick1buns** [comment]
i'm not sure if this is the right folder, but here it is: https://mega.nz/file/HAVEmS7K#iO2EvsoUbC-4B8HcGG0O0wAoyRrDxlxanfli-e2KID4

**Comment by pizzaboxer** [comment]
Seems like a bad installation. If you go into the menu, go to the Behaviour tab, enable the "Force Roblox reinstallation" option, and then try and launch it should work.

**Comment by nick1buns** [comment]
thank you, this worked!
