### ISSUE TITLE
[BUG] How can I prevent Roblox from crashing down when I minimize the window (I'm using Vulkan)

### ISSUE THREAD

**Issue by renovat3** [pizzaboxer/bloxstrap#805]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I minimize the Roblox window, it stops responding and it crashes. Also this one works when you switch to Vulkan rendering mode. How can I prevent this from happening?

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/20283fbd-a462-4237-8a9c-75fe97040cc0)
