### ISSUE TITLE
[BUG] unable to launch roblox browser version and bloxstrap version

### ISSUE THREAD

**Issue by nichooo6** [pizzaboxer/bloxstrap#808]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

everytime i opened roblox browser version or bloxstrap, it wont pop out the roblox game, its just like getting exit by own it self ive been cant play for almost like a week now i try uninstall both of them and restart pc but still cant opened roblox. please help!

**Comment by pizzaboxer** [comment]
Does it happen without Bloxstrap too?

**Comment by MlodyDryna** [comment]
For me no. Only with bloxstrap

**Comment by pizzaboxer** [comment]
For you, try forcing a reinstallation through the Bloxstrap Menu. Should be under the Behaviour tab. Also, make sure you're not using Vulkan.

**Comment by bighead23** [comment]
im having the same issue and not working

**Comment by bighead23** [comment]
i already force reinstallation but i dont even use vulkan

**Comment by Boi2021Miceoos** [comment]
Same Issue Here, But For My Situation Both Roblox Bootstrapper And Bloxstrap Won't Even Open Even Force Reinstalling And Reinstalling Everything And ` DISM /Online /Cleanup-Image /RestoreHealth` `sfc /scannow` it won't work i disabled msi afterburner already and it won't open

I'll Send A Log For Bloxstrap Hopefully You Can't Figure What Going On.
[Bloxstrap_20231026T071507Z.log](https://github.com/pizzaboxer/bloxstrap/files/13174129/Bloxstrap_20231026T071507Z.log)

**Comment by Boi2021Miceoos** [comment]
After Further Digging Into The Developers Fourms, I Have Seem To Found The Solution But I Don't Get It What He is Saying About "Clean Disk"
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/86916029/dbf265e9-8d36-4bc0-b6be-a374da635991)

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
