### ISSUE TITLE
[BUG] Couldn't find file

### ISSUE THREAD

**Issue by EricShipshin** [pizzaboxer/bloxstrap#809]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

this has started happening a month ago, i think it can't find it because my laptop is on russian and "Users" is named "Пользователи" instead
[Bloxstrap_20231024T125742Z.log](https://github.com/pizzaboxer/bloxstrap/files/13114897/Bloxstrap_20231024T125742Z.log)

**Comment by pizzaboxer** [comment]
Seems like this happens because you're running it directly through your browser. Download it to your Downloads first, then run it, and it should work.
