### ISSUE TITLE
[BUG] My roblox instantly crashes if i click anything else when roblox is minimized.

### ISSUE THREAD

**Issue by aki121g** [pizzaboxer/bloxstrap#812]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, when i play roblox with bloxstrap, everytime i want to check something like my discord etc, if i click anything else but go back to roblox (while roblox is minimized) it instantly crashes.

**Comment by pizzaboxer** [comment]
Are you using Vulkan?

**Comment by aki121g** [comment]
> Are you using Vulkan?

yes, i heared its the best one. If thats the problem, whats the alternate rendering i can use thats also provides more fps?

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/ec83da1a-71d8-4161-b04f-19092de4f920)

Read the instructions that were given to you before opening this issue next time.
