### ISSUE TITLE
[BUG] Bloxstrap Not Installing

### ISSUE THREAD

**Issue by NotDrxnqk** [pizzaboxer/bloxstrap#815]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I tried installing Bloxstrap, but it just closes the window, and doesn’t even install the modifications I’ve selected! There’s also no error message popping up, which is a very weird situation. What seems to be the problem?

**Comment by pizzaboxer** [comment]
What do you mean by "it just closes the window"? What window?

**Comment by NotDrxnqk** [comment]
I mean that the Bloxstrap Menu closes whenever I click install.

**Comment by pizzaboxer** [comment]
Whenever you click install? Are you sure? Can I take a look at Bloxstrap's log file that gets produced? You can find it in %temp%, sort by newest and you'll find it in there.

**Comment by AngryRico** [comment]
The original poster seems to be inactive and not responding, shouldnt this be closed?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
