### ISSUE TITLE
[BUG] Game keep crashing within 20 seconds of me opening it

### ISSUE THREAD

**Issue by dreztbh** [pizzaboxer/bloxstrap#817]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So I am indeed a very fond user of bloxstrap, and about 20 minutes ago I decided to join a football fusion 2 priv server and it crash on me so I have aready clear my dns cache, and restarted I tried to update my bloxstrap, and lastly restart my pc but none of these methods have worked fo yet so I decided that I would come to the community for help. I have made custom adjustments with my owns mods to blox strap and here they are. Im not sure if these have any relevance towards my game crashing but I have not seen anyone else post about this game crashing error yet so I am assuming its somethign I did. Please let me know how to fix this. Thanks.

![image](https://github.com/pizzaboxer/bloxstrap/assets/149021448/69f532b1-1787-439e-a9fa-7f618358354c)

**Comment by Just1an** [comment]
Same w/ me prob a bug with roblox byfron (maybe)

**Comment by dreztbh** [comment]
> Same w/ me prob a bug with roblox byfron (maybe)

yo bro turn ur rendering thing to direct11 it doesnt crash at all

**Comment by dreztbh** [comment]
all good vulkan and opengl just crash ur game

**Comment by Dragoo1v1** [comment]
same problem is with me it is crashing under 10min when i play ANY game 
Plzzzzzz fix ittt

**Comment by Dragoo1v1** [comment]
> all good vulkan and opengl just crash ur game

but Vulkan is the best rendering mode it gives the best amount of FPS
