### ISSUE TITLE
VR unable to init with Bloxstrap

### ISSUE THREAD

**Issue by septichacker** [pizzaboxer/bloxstrap#82]
due to the bloxstrap assumedly not checking for steamvr, vr is rendered useless with bloxstrap.

**Comment by pizzaboxer** [comment]
Usually the Roblox game client should be checking for VR, not the launcher. Does Roblox just not detect anything?

**Comment by septichacker** [comment]
Roblox client does not start in VR mode with steamVR open, i assume it is the launcher that sets roblox in vr mode

**Comment by pizzaboxer** [comment]
If you uninstall Bloxstrap to revert to the original Roblox launcher, does it work?

**Comment by septichacker** [comment]
how do i uninstall bloxstrap? do i just remove the files from appdata?

**Comment by pizzaboxer** [comment]
Uninstall it like how you would normally uninstall any program, from your PC settings.

**Comment by septichacker** [comment]
huh, without bloxstrap, still no vr!
it is an issue with me, sorry for wasting your time

**Comment by pizzaboxer** [comment]
No problem, glad I could help.
