### ISSUE TITLE
[BUG] Roblox opens in vr mode automatically, causing steam and steamvr to open as well

### ISSUE THREAD

**Issue by KonoKore** [pizzaboxer/bloxstrap#820]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

upgraded roblox and it has now started to open in vr mode, automatically opening steam and steamvr

**Comment by pizzaboxer** [comment]
Roblox just does that. Actually, it's normally always done that, so I'm not sure why it just started happening for you not. There's a proposed solution coming soon to get around this as described in #548.
