### ISSUE TITLE
[BUG] System. Exception:  Singnature does not match!

### ISSUE THREAD

**Issue by Arman-0909** [pizzaboxer/bloxstrap#821]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm Getting a error after re-installing.
[BUG] System. Exception:  Singnature does not match!

**Comment by pizzaboxer** [comment]
i thought you read the preliminary instructions

https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
