### ISSUE TITLE
Bloxstrap's Bootstrapper works but ROBLOX stays as a background process.

### ISSUE THREAD

**Issue by MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWM** [pizzaboxer/bloxstrap#822]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello everyone, i don't know if this is mainly related to Bloxstrap but i have been having for the past 2 hours an issue where roblox would open Bloxstrap's bootstrapper when trying to play a game on the website but then would make ROBLOX a background process and if i don't manually end the task, it would stay and not close itself, this is very frustrating and here's what i tried:

- Updating my GPU Drivers ( figured it wouldn't do anything because i'm using an integrated gpu )
- System Restore
- Using the normal ROBLOX Bootstrapper
- Completely removing anything related to both ROBLOX and Bloxstrap with "Everything" ( free software )
- Disk Cleanup and Cleaning the thumbnails

and i think that's pretty much everything i tried, note that i'm not using RTSS or MSI Afterburner, here is a video of my issue:

https://streamable.com/k5ohui

**Comment by pizzaboxer** [comment]
#828
