### ISSUE TITLE
[BUG] Tried to open roblox but an error came up and it said something closed it

### ISSUE THREAD

**Issue by kazidus** [pizzaboxer/bloxstrap#823]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20231026T022922Z.log](https://github.com/pizzaboxer/bloxstrap/files/13172420/Bloxstrap_20231026T022922Z.log)

it jus says something forebly closed it
![image](https://github.com/pizzaboxer/bloxstrap/assets/149030936/e1cde1ca-3738-426f-9dd7-adf3c956a0a4)

**Comment by pizzaboxer** [comment]
Does this happen every time you try to use it?

**Comment by BokBoy** [comment]
@kazidus I've seen similar issues on Roblox (not Bloxstrap) and it was because of a Firewall. Check that your computer allows it past the firewall (see https://www.digitalcitizen.life/how-change-windows-firewalls-list-allowed-blocked-apps/ for help on how to do it), or check your router for Parental Controls that disallow it.

**Comment by thulasikan14** [comment]
> @kazidus I've seen similar issues on Roblox (not Bloxstrap) and it was because of a Firewall. Check that your computer allows it past the firewall (see https://www.digitalcitizen.life/how-change-windows-firewalls-list-allowed-blocked-apps/ for help on how to do it), or check your router for Parental Controls that disallow it.

i dont see the bloxstrap app on my firewall

**Comment by pizzaboxer** [comment]
> i dont see the bloxstrap app on my firewall

...Are you having the same issue?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
