### ISSUE TITLE
[BUG] Roblox doesnt start

### ISSUE THREAD

**Issue by annualpurges** [pizzaboxer/bloxstrap#824]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When ever I try to start up roblox with or without bloxstrap it dont launch its like well id say exactly the same. #251 

https://github.com/pizzaboxer/bloxstrap/assets/149032848/a248d88a-9fc2-40ca-bf63-d274717dd114

**Comment by annualpurges** [comment]
please help..

**Comment by XPIREDPIRED5** [comment]
This happened to me too

**Comment by annualpurges** [comment]
do you know how to fix?

**Comment by hktouristbackup** [comment]
This just somehow worked for me right now.

If any of you have Bitdefender installed, the solution is to turn off Advanced Threat Protection then access Roblox (RobloxPlayerBeta.exe). If you don't have Bitdefender, I'm out of luck.

**Comment by catb0x** [comment]
> This just somehow worked for me right now.
> 
> If any of you have Bitdefender installed, the solution is to turn off Advanced Threat Protection then access Roblox (RobloxPlayerBeta.exe). If you don't have Bitdefender, I'm out of luck.

TYSM!!

**Comment by pizzaboxer** [comment]
#828

Also thanks for that solution @hktouristbackup, I'll note that down.

**Comment by annualpurges** [comment]
TY

**Comment by XPIREDPIRED5** [comment]
It still doesn't work for me and I don't use bitdefender I tried this and it also didn't work https://www.youtube.com/watch?v=mKIHSqiGBC8

**Comment by Infinitegotbanned** [comment]
how you fix? @annualpurges
