### ISSUE TITLE
[REQ] Better Save Button (for paranoid people)

### ISSUE THREAD

**Issue by 0xFE0F** [pizzaboxer/bloxstrap#825]
### Acknowledgement of preliminary instructions

- [x] I have read and acknowledged the preliminary instructions.

### What idea do you have?

The current save button will save and then close the Bloxstrap menu, this makes it difficult for those who have a tendency to save constantly out of habit, or just out of the worry of data being lost.

I'd really appreciate if you consider adding an option, alternative button, or change the default behavior of the save button to allow for constant use.

### (also I wasn't sure what to call the title of the feature request, sorry!)

**Comment by AmbassadorLaZer** [comment]
I hope @pizzaboxer adds this into Bloxstrap it'll be a nice QOL improvement for people who click the save button very often.

I somewhat have a habit of saving stuff after I do something (I think I got that from using Notepad alot), and it somewhat bothers me whenever I save on the Bloxstrap menu it just closes it out and I have to reopen the menu again lol. I feel like it being a setting (Either letting you pick if you want an alternative button or to change the default behavior of the save button.) inside the Bloxstrap menu would be a good idea. Hopefully this becomes a feature in a future version of Bloxstrap.

**Comment by CodingWithAnxiety** [comment]
@pizzaboxer 

We could have it such that clicking the save button doesn't close the client (as it currently does?) Alternatively, it could pop up a dialogue saying something to the swing of, 'Options have been saved!', or whatever?

**Comment by OrphanObliterator** [comment]
its on the to do list lets goo
