### ISSUE TITLE
[BUG] I Do Not Know How Too not have the custom lighting

### ISSUE THREAD

**Issue by MrReap3r** [pizzaboxer/bloxstrap#827]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I want regular lighting like the normal roblox stuff but also my bloxstrap settings is there anyway i can turn that feature off?

**Comment by IxGamerXL** [comment]
`FastFlags > Preferred Lighting Technology > Chosen by game`, which should make it so lighting is defaulted to the game's preference. Also, this is not a bug report, you should be using a blank issue template when you're not reporting a bug or suggesting a feature.
