### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FFFadal** [pizzaboxer/bloxstrap#829]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

after opening roblox from bloxstrap it crashed with an error called "roblox needs to quit we're sorry"

**Comment by Obirma311** [comment]
Got the same problem too

**Comment by PakinDeReal** [comment]
same here too

**Comment by PakinDeReal** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/87290041/7d506978-4a59-4481-8961-6cbf65b248d8)

**Comment by pizzaboxer** [comment]
Are you using Vulkan?

**Comment by FFFadal** [comment]
> Are you using Vulkan?
> 
> Also @PakinDeReal, what are you using to get that Windows theme?

Yes

**Comment by PakinDeReal** [comment]
@pizzaboxer i use this thing
![image](https://github.com/pizzaboxer/bloxstrap/assets/87290041/819804fd-3e2f-425e-bd06-a6dc0312922a)
and this is the theme i use https://www.deviantart.com/niivu/art/Catppuccin-for-Windows-21H2-908988670

**Comment by PakinDeReal** [comment]
i use opengl option and future as lighting
