### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FFFadal** [pizzaboxer/bloxstrap#832]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Every render option doesnt work and crashes with an error except for directx11 after october 25

**Comment by HemlockGlove** [comment]
Mine too, I have set it to automatic, OpenGL and Directx10 (other options crash for me normally because of my weak PC) 
Yesterday it worked fine on OpenGL but today I cant even play a single game, it works on normal Roblox but crashes after a minute or so in bloxstrap.

**Comment by Vezlortix** [comment]
I can't play any game not even a single one as i cant use directx11 shaders or i cant run the game

**Comment by 9wd** [comment]
Yeah me too It crashes on OpenGL and Vulkan yesterday was fine.

**Comment by pizzaboxer** [comment]
Stay on Automatic. Do not change from using Automatic.
