### ISSUE TITLE
[BUG] Roblox crashing every time I open it with bloxtrap

### ISSUE THREAD

**Issue by Vaaaporr** [pizzaboxer/bloxstrap#834]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My Roblox was working until yesterday's Roblox update, my Roblox started crashing every time I tried to open it using bloxtrap. I'm almost sure it's bloxtrap that's the problem, I tested Roblox without opening it with bloxtrap and it didn't crash once. And when I opened roblox with bloxtrap it started crashing after 10-20 seconds.
![Roblox Crash Bloxtrap](https://github.com/pizzaboxer/bloxstrap/assets/149098307/de1a478a-40eb-4b22-aa78-17d8d3be0a43)

**Comment by pizzaboxer** [comment]
Are you using Vulkan?

**Comment by Vaaaporr** [comment]
I think so, how do I go back to bloxtrap settings? Do I need to uninstall and install again?

**Comment by Vaaaporr** [comment]
Thank you very much.
