### ISSUE TITLE
[BUG] Roblox keeps crashing after 1-2 minutes

### ISSUE THREAD

**Issue by JSkes** [pizzaboxer/bloxstrap#835]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I play any game it runs fine for the first 1-2 minutes then freezes for a couple seconds, then it throws me the default unexpected error dialog, I've tried reinstalling, changing renderer, changing lighting technology, menu version even, still same result, I've noticed that these crashes started happening after Roblox 600, 598 worked fine with 0 crashing, plus I've checked using the default Roblox bootstrapper, still works fine no crashes, What could be the issue?

**Comment by sscrt** [comment]
wdym by roblox 600 and 598?

**Comment by HemlockGlove** [comment]
Same situation with me

**Comment by AfterlifeSkedaddle** [comment]
same issue for me, im guessing roblox doesnt like fps unlockers and engine improvments anymore (could definitely just be a renamed asset or something equally stupid though)

**Comment by WaviestBalloon** [comment]
Currently issues with `version-faaebc838e2e45f6` and `version-7cc666219b484414`, reverting to `version-57e2dd886e0e42a5` *used* to fix it but RCCS is now refusing clients older than newest.

**Comment by pizzaboxer** [comment]
Are you sure the default bootstrapper works? If you don't mind, you could send me a copy of your installation folder that's located at `%localappdata%\Bloxstrap` here, and I'll take a look to see if I can find anything wrong.

**Comment by MineDer23** [comment]
same issue with me

**Comment by JSkes** [comment]
> Are you sure the default bootstrapper works? If you don't mind, you could send me a copy of your installation folder that's located at `%localappdata%\Bloxstrap` here, and I'll take a look to see if I can find anything wrong.

Yeah I'm sure that default bootstrapper works, tried it twice. And I don't mind sending you a copy of the installation folder, where should I send it?

**Comment by pizzaboxer** [comment]
Upload it to any file sharing service, send the link to it here.

**Comment by JSkes** [comment]
Here it is, sorry for being almost an hour late, I don't exactly have a good internet connection [Bloxstrap installation folder (zipped)](https://mega.nz/file/fmJAyazJ#LYemotjuuP58J7Zq1aQpxDovQUNZNSnY35yqF1lIccE)

**Comment by pizzaboxer** [comment]
Seems to work fine for me. Can you just first try setting everything back to their defaults, and then try setting the framerate limit to zero? 

Go into the flag editor, make sure presets are shown, select everything and delete them all. Then, go back out and ensure the framerate limit is set to zero. Save, then try and launch.

**Comment by JSkes** [comment]
I haven't set fully everything back to default, only the FastFlags, would that still work?

**Comment by JSkes** [comment]
It appears that the problem has resolved itself, I have all my settings back to what I normally use.

**Comment by JSkes** [comment]
The problem is back, can it be Direct3D causing the issue?

**Comment by WaviestBalloon** [comment]
> The problem is back, can it be Direct3D causing the issue?

Shouldn't be the issue, have you tried changing your channel to `zavatarteam` or `zavatarteam2`?

**Comment by JSkes** [comment]
> > The problem is back, can it be Direct3D causing the issue?
> 
> Shouldn't be the issue, have you tried changing your channel to `zavatarteam` or `zavatarteam2`?

No, I'm gonna try that.

**Comment by JSkes** [comment]
Update: no crashes so far but I'm scared of changing my renderer for now, It's gonna be at Automatic.
