### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SpiderCruncher** [pizzaboxer/bloxstrap#837]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox crashes within seconds of launch

**Comment by HemlockGlove** [comment]
Just the launcher or when you enter a game? for me its when I enter a game

**Comment by WaviestBalloon** [comment]
Currently issues with `version-faaebc838e2e45f6` and `version-7cc666219b484414`, reverting to `version-57e2dd886e0e42a5` *used* to fix it but RCCS is now refusing clients older than newest.

**Comment by pizzaboxer** [comment]
Unless you have any further information to add, read #828.
