### ISSUE TITLE
[BUG] Bloxtrap seems to have problem to connect the Zlive server.

### ISSUE THREAD

**Issue by ToastPOW** [pizzaboxer/bloxstrap#838]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The error created a log file: 
Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/ZLive because it returned HTTP 401 (Unauthorized)
![image](https://github.com/pizzaboxer/bloxstrap/assets/133332897/73566778-b3fb-4860-889f-36ad3b0e8214)

**Comment by cookdsteaak** [comment]
switch to "LIVE", zlive doesnt work for me either, or any of the other channels

**Comment by ToastPOW** [comment]
i will try

**Comment by ToastPOW** [comment]
alr it worked thanks
