### ISSUE TITLE
[BUG]  after like 10 to 20 seconds it freezes and crashes

### ISSUE THREAD

**Issue by iloveroblox1029** [pizzaboxer/bloxstrap#840]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i tried playing a game and it crashes right after i get to game.

**Comment by iloveroblox1029** [comment]
basically it crashes after 10 seconds and it repeats if i do it again pls fix

**Comment by iloveroblox1029** [comment]
![Screenshot 2023-10-27 065035](https://github.com/pizzaboxer/bloxstrap/assets/149132605/bdba7e07-c4ee-4bc4-9f85-6e2165c1a41f)

**Comment by MildilyAcidic** [comment]
bump happening to me too

**Comment by HemlockGlove** [comment]
Been happening to me since yesterday too

**Comment by Aiichirooo** [comment]
if u change renderer to vulkan or opengl it will crash, i think cause a new roblox version

**Comment by iloveroblox1029** [comment]
> if u change renderer to vulkan or opengl it will crash, i think cause a new roblox version

So if I change it to auto will it crash again?

**Comment by Aiichirooo** [comment]
change it to directd 11 or directx 10

**Comment by Aiichirooo** [comment]
that will not crash

**Comment by iloveroblox1029** [comment]
> that will not crash

Ok thanks
