### ISSUE TITLE
[BUG] Can't start bloxstrap

### ISSUE THREAD

**Issue by 0ryz** [pizzaboxer/bloxstrap#842]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try running it it shows this error:

System.Net.Http.HttpRequestException: No such host is known. (clientsettings.roblox.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.

**Comment by pizzaboxer** [comment]
Internet connectivity error. Just start it again and it should work.
