### ISSUE TITLE
[BUG] Roblox closes in less than 1 second

### ISSUE THREAD

**Issue by tweeks14** [pizzaboxer/bloxstrap#843]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I try to start bloxstrap everything is fine, but after bloxstrap closes - roblox does not open, or rather it opens but for a very small time, in the task manager it is always there but has a small amount of memory usage.
Log file:
[Bloxstrap_20231027T073832Z.log](https://github.com/pizzaboxer/bloxstrap/files/13186292/Bloxstrap_20231027T073832Z.log)

**Comment by pizzaboxer** [comment]
#828
