### ISSUE TITLE
[BUG] Roblox Crashing while using bloxstrap

### ISSUE THREAD

**Issue by coolfriedpotato24** [pizzaboxer/bloxstrap#845]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever i open Roblox with Bloxstrap, it runs normally for 1-10 mins. Then it freezes and crashes saying "An unexpected error occurred and Roblox needs to quit. We're Sorry!"

Using roblox without Bloxstrap, it works completely fine without freezing or crashing.

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by coolfriedpotato24** [comment]
bloxstrap seems to work normal after changing the rendering mode. Thanks for the help
