### ISSUE TITLE
[BUG] Roblox can't run

### ISSUE THREAD

**Issue by DellXD37462** [pizzaboxer/bloxstrap#846]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I was trying to join roblox from the website but bloxstrap have an error or an **exception**. 
Here is the log file:
[Bloxstrap_20231027T114501Z.log](https://github.com/pizzaboxer/bloxstrap/files/13188548/Bloxstrap_20231027T114501Z.log)

**Comment by pizzaboxer** [comment]
Change your configured channel in the menu to LIVE.
