### ISSUE TITLE
[BUG] Roblox Crashing

### ISSUE THREAD

**Issue by CoolerHub** [pizzaboxer/bloxstrap#847]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My roblox keeps crashing. When I launch roblox it launches for around 2 minutes and immediatly crashes. After uninstalling roblox and reinstalling the issue proceeded and I uninstalled bloxstrap. I tried and it still isnt working.

**Comment by bodoEnd90** [comment]
I uninstalled Bloxstrap and the issue has been solved, so it's def. some kind of a bug.

**Comment by pizzaboxer** [comment]
Have you read https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?
