### ISSUE TITLE
[BUG] Deployment Channel returns an error

### ISSUE THREAD

**Issue by VibeRBLX** [pizzaboxer/bloxstrap#849]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Selecting any deployment channel results in an error "Failed to fetch information! (HTTP 401 - Unauthorized)
![image](https://github.com/pizzaboxer/bloxstrap/assets/149176557/140e08d3-0022-4976-9ec1-447a881b1b72)
![image](https://github.com/pizzaboxer/bloxstrap/assets/149176557/e29934bc-7f56-434b-b5cf-84cc32a5b6e3)

**Comment by popbob2** [comment]
change your channel to LIVE

**Comment by VibeRBLX** [comment]
Fixed it,
