### ISSUE TITLE
[BUG] Roblox keeps crashing after some time

### ISSUE THREAD

**Issue by CoolerHub** [pizzaboxer/bloxstrap#850]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After launching roblox, Bloxstrap opens and then it launches roblox perfectly fine. Roblox launches and then after playing for a while it crashes leaving in message. The weird part is that I can still hear the game sounds and it is open IN THE BACKGROUND, in OPERA GX BROWSER category. When I installed bloxstrap the issue started. When I uninstalled bloxstrap it didnt work aswell. When I launched using the Windows app it said "Experienced launched from another device". I cant play roblox rn for more than idk 5 mins?? Please help pizzaboxer.

Thank you.

**Comment by pizzaboxer** [comment]
> When I installed bloxstrap the issue started.

Did you opt to use Vulkan when you installed it?

**Comment by CoolerHub** [comment]
> > When I installed bloxstrap the issue started.
> 
> Did you opt to use Vulkan when you installed it?

What do you mean  did I opt to use Vulkan when I installed it?

btw I made an error it crashes without leaving a message which is frustrating.

**Comment by CoolerHub** [comment]
Just reinstalled windows, Still doesnt work. Probably roblox or my pc's problem.

Can you provide help??

**Comment by pizzaboxer** [comment]
> When I uninstalled bloxstrap it didnt work aswell.

Oh, I didn't look at this part carefully. It's a Roblox problem then. If you read #828 you would've found this out.
