### ISSUE TITLE
[BUG] Roblox Game Client has stopped working after 2 - 15 minutes of playing

### ISSUE THREAD

**Issue by AsherHeist** [pizzaboxer/bloxstrap#852]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox Game Client has stopped working is the message I get after playing for around 2 - 15 minutes, I've changed bloxstrap settings and nothing works, please help

**Comment by pizzaboxer** [comment]
Are you using Vulkan?

**Comment by AsherHeist** [comment]
> Are you using Vulkan? What did you change in the settings?

I am using Direct3D 11 and I modified some settings that make the menu go back to the 2015 one, 2013 cursor, custom font, old oof sound, disable desktop app, and alternate graphics quality selector

**Comment by pizzaboxer** [comment]
I've just realized that you're talking about the error message that shows when Windows detects a frozen process. Are you sure this doesn't happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
