### ISSUE TITLE
FPS not in normal levels

### ISSUE THREAD

**Issue by BokBoy** [pizzaboxer/bloxstrap#853]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Follow up from #816 I normally get better fps than 60 and below. Bloxstrap has done 500+ (varies but never constantly below 60) but now, it stopped doing that. FPS is set to 9999 and drivers are installed.

**Comment by BokBoy** [comment]
Also, using almost exact same settings as before fps drop

**Comment by pizzaboxer** [comment]
Are you using an Intel CPU?

**Comment by BokBoy** [comment]
No,
Flags are 9999 FPS,  Future Phase 3, Version Four, Off, Off, Automatic, off, on
Full pc specs - 
https://au.pcpartpicker.com/list/dsWyWt (now don't ask about radeon GPU. Didn't know what NVIDIA was when I made it)

I had trouble uploading images before so I didn't want to try now.

**Comment by pizzaboxer** [comment]
First, see if you get below 60 without Bloxstrap. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

Second, try setting your lighting mode to Automatic and see if anything changes.

**Comment by BokBoy** [comment]
@pizzaboxer 
Should I try Ms Store or the Web version??

**Comment by pizzaboxer** [comment]
Do what I've asked you to do please.

**Comment by Lucas559-noob** [comment]
> Web version

but... isn't this the version bloxtrapper use? lol

**Comment by BokBoy** [comment]
> > Web version
> 
> 
> 
> but... isn't this the version bloxstrap use? lol

It is...
Just asking the question because I use Ms store but bloxstrap uses Web. I'll check back tonight

**Comment by BokBoy** [comment]
Yo guys,
Progress update...
Sorry for the 2-3 day delay. I've had issues on my MacBook so it'll take some more time.
Thanks!!

**Comment by BokBoy** [comment]
Hey, @pizzaboxer I have the time right now, (it is 8 pm for me) and I started by installing the Roblox MS Store version, where it runs better, the average FPS is higher than Bloxstrap. 
I have just uninstalled Roblox on MS Store, an installed the

**Comment by BokBoy** [comment]
Oops clicked wrong button sorry

**Comment by pizzaboxer** [comment]
> but slightly better than Bloxstrap.

By how much?

**Comment by BokBoy** [comment]
Like roughly 5 fps

**Comment by pizzaboxer** [comment]
So they're practically the same. It's not a problem with Bloxstrap then.

**Comment by BokBoy** [comment]
Then its prob a roblox update so ig that I need to figure out what they did. ty

**Comment by BokBoy** [comment]
@pizzaboxer for some reason, My HacOS works better than windows, an increase of 15fps however fluctuates a lot
any explanation??
