### ISSUE TITLE
[BUG] Bloxstrap not launching/Running as a background App

### ISSUE THREAD

**Issue by th3death** [pizzaboxer/bloxstrap#854]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

For some reason this happened to me out of nowhere, I even tried going back to Windows 10 (I was previously using W11) which I've also formatted my PC twice trying to fix the error, already tried the methods of uninstalling, cleaning the files via CMD using the commands cd AppData\Local but nothing works till so, if I try to launch it again it'll end up just stacking as a background process
![image](https://github.com/pizzaboxer/bloxstrap/assets/149211523/57531b2c-13b4-413d-a60a-7837d9dcbf8f)

**Comment by DragonKillerz** [comment]
read #828

**Comment by th3death** [comment]
> read #828

Already did like hours ago when I was looking for solutions

**Comment by CoolerHub** [comment]
Same issue here for me roblox doesnt launch and runs as a background app.

**Comment by pizzaboxer** [comment]
> Already did like hours ago when I was looking for solutions

I don't know what further information you're expecting to receive by opening an issue. You also didn't mention if it happens without Bloxstrap, because I'll only care about this issue if so.

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by th3death** [comment]
Oh yes, my bad, it does happen without Bloxstrap too.

**Comment by pizzaboxer** [comment]
Not a Bloxstrap problem then. You'll have to wait for Roblox to fix it.
