### ISSUE TITLE
[REQ] Raster + TrueType [*.ttc] supported as TrueType [Add file format]

### ISSUE THREAD

**Issue by Vad1mCSO2** [pizzaboxer/bloxstrap#855]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

![image](https://github.com/pizzaboxer/bloxstrap/assets/76803825/a9c0ba0c-f7ea-4f91-a5a4-5409dc7aa7c2)
[msgothic.zip](https://github.com/pizzaboxer/bloxstrap/files/13194437/msgothic.zip)
MS Gothic is .ttc (TrueType Combo font file) and now supports the bloxstrap

**Comment by pizzaboxer** [comment]
Oh, can't believe I missed that out. Thanks for telling me.
