### ISSUE TITLE
[REQ] Change FPS Cap while in game

### ISSUE THREAD

**Issue by Zacgamingpro1234** [pizzaboxer/bloxstrap#860]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So I suggest that you have the ability to change your fps cap while in game like rbxfpsunlocker. I also made some fan art of what it should or could look like. Once you right click that will pop up and you change your fps cap.
![tempsnip-transformed](https://github.com/pizzaboxer/bloxstrap/assets/140814307/2baf8ae8-5767-4049-8004-2cbe52ca388f)

**Comment by pizzaboxer** [comment]
Not possible, sorry.
