### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Janer-r** [pizzaboxer/bloxstrap#861]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20231028T095147Z.log](https://github.com/pizzaboxer/bloxstrap/files/13195432/Bloxstrap_20231028T095147Z.log)
Well, i did some custom mods, and i tried to change my cursor. so i replaced something and i think i broke it. then i found another file where it was MUCH more easier to do. just take the files there so please like fix it or something

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
