### ISSUE TITLE
[BUG] My roblox keep crashing after a few mins

### ISSUE THREAD

**Issue by MineDer23** [pizzaboxer/bloxstrap#862]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My Roblox keep crashing after a few second. at first it was fine but after around 30-45 second it crashes, idk why

**Comment by pizzaboxer** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/8c45e558-3760-41be-bc91-d14782f00f8e)

Look through these two articles then get back to me.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Username404-59** [comment]
> ### Acknowledgement of preliminary instructions
> 
>     * [x]  I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
> 
> 
> ### What problem did you encounter?
> 
> My Roblox keep crashing after a few second. at first it was fine but after around 30-45 second it crashes, idk why

This is a bug in the latest roblox update
Try setting the roblox channel to `zavatarteam2` in bloxstrap (this branch doesn't have it)
