### ISSUE TITLE
[BUG] My bloxtrap keeps crashing 

### ISSUE THREAD

**Issue by RayNazarly** [pizzaboxer/bloxstrap#863]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My bloxtrap keeps crashing when I try to go to the avatar, or when I try to play. But it doesn't crash when I'm playing with the normal roblox client

**Comment by pizzaboxer** [comment]
Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by RayNazarly** [comment]
I did

**Comment by pizzaboxer** [comment]
Read the preliminary instructions next time.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/a36df196-bc50-4818-aed4-8556d1d132c9)

**Comment by RayNazarly** [comment]
tysm
