### ISSUE TITLE
Fps is really low when using Bloxstrap

### ISSUE THREAD

**Issue by epicdsoafhsadfcsda** [pizzaboxer/bloxstrap#864]
Whenever I use Bloxstrap my fps rarely goes above 20 fps and when it does it almost immediatly goes below. FPS is normal(60fps) when I use normal Roblox

**Comment by pizzaboxer** [comment]
Can I see the flags you have configured in the menu?

**Comment by epicdsoafhsadfcsda** [comment]
> Can I see the flags you have configured in the menu?

Yeah
![image_2023-10-28_223446927](https://github.com/pizzaboxer/bloxstrap/assets/149252886/5e7ff911-9486-4dea-b6ce-569c52faa39a)

**Comment by pizzaboxer** [comment]
Scroll up and let me see the top, too.

**Comment by epicdsoafhsadfcsda** [comment]
> Scroll up and let me see the top, too.

![image](https://github.com/pizzaboxer/bloxstrap/assets/149252886/d90a5607-a59d-4d0d-aee6-1dc70738dce7)

**Comment by pizzaboxer** [comment]
Not seeing much here. Does setting the framerate limit as 0 change anything?

**Comment by epicdsoafhsadfcsda** [comment]
> Not seeing much here. Does setting the framerate limit as 0 change anything?

nope

**Comment by cub-has-injected** [comment]
### Try to set the channel to "live" or "znext" in the Behaviour tab.
![image](https://github.com/pizzaboxer/bloxstrap/assets/83903792/0bd2fa5a-91c1-4511-89e5-6c428605a8cb)

### Also, you can try to use forced rendering mode on "OpenGL" or "Direct3D":
_You can use Vulkan, but it's often lagging on slow computers._
![image](https://github.com/pizzaboxer/bloxstrap/assets/83903792/28f015c6-6d1c-49db-a0ca-5028e9854679)

**Comment by epicdsoafhsadfcsda** [comment]
> ### Try to set the channel to "live" or "znext" in the Behaviour tab.

> ### Also, you can try to use forced rendering mode on "OpenGL" or "Direct3D":
> _You can use Vulkan, but it's often lagging on slow computers

Was already on Direct 3D 11 and I tried OpenGL which fixed the low fps issue(besides fps drops) but now Roblox crashes in less than 2 minutes

**Comment by pizzaboxer** [comment]
What CPU/GPU are you using?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
