### ISSUE TITLE
Error when start up Bloxstrap

### ISSUE THREAD

**Issue by CHIPnotFLAKE** [pizzaboxer/bloxstrap#865]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20231028T175220Z.log](https://github.com/pizzaboxer/bloxstrap/files/13196445/Bloxstrap_20231028T175220Z.log)

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized)

**Comment by BokBoy** [comment]
Hello
401 is an HTTP error that means not enough credentials or invalid credentials were sent.
Was this when you were installing (incl. first try after installing) or was it sudden - You've played with it before this happened and didn't give any errors?
To isolate Bloxstrap from the issue, try installing Roblox again and see if it works, Make sure it isn't blocked from the network (some schools and workplaces block games, try a VPN to check), and install Bloxstrap again.

P.S. I just thought I might help but I do not know the exact reason, Pizzaboxer may.

**Comment by pizzaboxer** [comment]
Read the Wiki next time. https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
