### ISSUE TITLE
[BUG] Doesnt launch bloxstrap

### ISSUE THREAD

**Issue by hcjk** [pizzaboxer/bloxstrap#866]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i tried to do anything i found on wiki with problems of not launching bloxstrap
but i cant launch it still

![image](https://github.com/pizzaboxer/bloxstrap/assets/149293038/9c159d5d-e9fb-4816-857b-56caafafe220)

i also cleared temp, cache and prefetch but still no luck even i tried uninstalling it but the unninstaller also didnt launched
soo i manually uninstalled but also installer doesnt launch too soo i give up and now i need your help!

**Comment by BokBoy** [comment]
Uninstall your .net runtime and reinstall.
Try redownload the installer exe and run it.
Otherwise, wait for Pizzaboxer to get online again.

**Comment by hcjk** [comment]
> Uninstall your .net runtime and reinstall. Try redownload the installer exe and run it. Otherwise, wait for Pizzaboxer to get online again.

Didnt worked but i will wait for pizzaboxer

**Comment by pizzaboxer** [comment]
> i tried uninstalling it but the unninstaller also didnt launched

What did you try uninstalling? If you're talking about Bloxstrap, you didn't mention if it was working prior at all.

**Comment by hcjk** [comment]
> > i tried uninstalling it but the unninstaller also didnt launched
> 
> What did you try uninstalling? If you're talking about Bloxstrap, you didn't mention if it was working prior at all.

i tried uninstalling bloxstrap and installing it again
but everything doesnt work soo i manually uninstalled

**Comment by pizzaboxer** [comment]
> i tried uninstalling bloxstrap and installing it again

So it was working prior?

This is confusing, do you mean to say that Roblox isn't launching?

**Comment by hcjk** [comment]
> > i tried uninstalling bloxstrap and installing it again
> 
> So it was working earlier if you were able to install it?
> 
> This is confusing, do you mean to say that Roblox isn't launching?

Alright this is what is happening to me
when i try to launch bloxstrap it doesnt do anything
when i try to uninstall bloxstrap it doesnt do anything also
soo i tried uninstalling it manually
then when i tried installing bloxstrap it also doesnt do anything

something like that

**Comment by pizzaboxer** [comment]
Okay, I see now. Try and run it again. If it doesn't launch, open Event Viewer, go to Windows Logs -> Application, and see if there's any error entries at the top. Show me if there are.

**Comment by hcjk** [comment]
> Okay, I see now. Try and run it again. If it doesn't launch, open Event Viewer, go to Windows Logs -> Application, and see if there's any error entries at the top. Show me if there are.

Sorry if i will lately reply

here is the error  i found: `Application: Bloxstrap-v2.5.3.exe
CoreCLR Version: 6.0.2423.51814
.NET Version: 6.0.24
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load.

 ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.Runtime.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at .cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Application.ApplicationInit()
   at System.Windows.Application..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Application..ctor()
   at Bloxstrap.App..ctor()
   at Bloxstrap.App.Main()
`

**Comment by BokBoy** [comment]
> ---> .ModuleLoadException: The C++ module failed to load.
Uninstall Cpp module and reinstall??

**Comment by hcjk** [comment]
> > ---> .ModuleLoadException: The C++ module failed to load.
> 
> Uninstall Cpp module and reinstall??

i dont really know how to do it

**Comment by pizzaboxer** [comment]
Seems like you need to reinstall .NET. Uninstall it from your PC (it should show up as "Windows Desktop Runtime"), then reinstall it. https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.24-windows-x64-installer?cid=getdotnetcore

**Comment by hcjk** [comment]
> Seems like you need to reinstall .NET. Uninstall it from your PC (it should show up as "Windows Desktop Runtime"), then reinstall it. https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.24-windows-x64-installer?cid=getdotnetcore

Thank you it is fixed
