### ISSUE TITLE
[REQ] More Precise Quality Control

### ISSUE THREAD

**Issue by BokBoy** [pizzaboxer/bloxstrap#867]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So... This might sound weird...
I don't know if roblox might restrain this but,
It would be nice if Bloxstrap could manually control each aspect of quality.
So instead of one slider that controls shaders, material and render distance but 3 sliders that control each. 
If Roblox restrains it, I understand but it would be cool, especially on large and dark maps that lower shaders might make it more visible.

**Comment by pizzaboxer** [comment]
Not possible, sorry.

**Comment by BokBoy** [comment]
@pizzaboxer if I requested it to Roblox do you think they can try??
