### ISSUE TITLE
Bloxstrap v2.0.0 release notes

### ISSUE THREAD

**Issue by pizzaboxer** [pizzaboxer/bloxstrap#87]
Bloxstrap v2.0.0 is out! A lot changes in this version, and I'm expecting a bunch of bugs. So, if you find any, feel free to open an issue!
Note: 'Configure Bloxstrap' has been renamed to 'Bloxstrap Menu' in the Start menu.

### Features
- Added automatic updating. This is (hopefully) the last time you'll be asked to update!
   - #38
   - #67
- A complete overhaul of the preferences menu... again! 
- Added support for ReShade, including Extravi's ReShade Presets 
   - #30
   - #64
   - #85
- Added support for custom integrations, where you can have other programs launch alongside Roblox 
   - #76
- Added support for having multiple client instances open
   - #35 
   - #72
- Added Fluent bootstrapper style to match the new look 

### Fixes and improvements
- Readme information on modding has been moved online
- Fixed a bug with rbxfpsunlocker not uninstalling properly
- Install location changing is now more reliable
- All issues regarding DPI scaling have been fixed
- Logo icons no longer appear as blurry or low-quality
- Install cancelling should be more reliable
- Free disk space is now checked before installing/updating Roblox
- Fixed problems with Discord Rich Presence reading the wrong log file - improved reliability 
- Fixed launcher URI not properly cleaning up after uninstalling
- Installer progress is now more accurate, reflecting total bytes downloaded
- Added an option for whether Bloxstrap should prompt if Roblox forces a channel change
- Added a desktop shortcut to launch Roblox from the desktop

### Codebase
- Project base has been migrated from WinForms to WPF (this was a major enough change to warrant bumping the version to from 1.7 to 2.0.0)
- Bootstrapper functionality is no longer tied to the dialog, making quiet launching completely dialogless and improving overall reliability
- All icons are now stored in multisize ico format
- Mod manifest and Bootstrapper state information are now stored in State.json
- Application logging has been added for easier debugging
- Config file saving (for Settings and State) is now handled under a generic handler and is actually done properly now

**Comment by brenden7158** [comment]
pizzaboxer done it again with the fire update

**Comment by TargetAc** [comment]
how do i use reshade with bloxstrap?

**Comment by TheMetalTechnet** [comment]
> how do i use reshade with bloxstrap?
> 

That's the neat part, you don't
