### ISSUE TITLE
[BUG] Some Deployment channels dont work anymore

### ISSUE THREAD

**Issue by Findyourlimit** [pizzaboxer/bloxstrap#870]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever you try to use them, you get error 401
[Bloxstrap_20231029T162553Z.log](https://github.com/pizzaboxer/bloxstrap/files/13198616/Bloxstrap_20231029T162553Z.log)

**Comment by Findyourlimit** [comment]
Turns out it only happens with ZCANARY and ZINTEGRATION

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
