### ISSUE TITLE
[BUG] Roshade Bug

### ISSUE THREAD

**Issue by kek1ich** [pizzaboxer/bloxstrap#871]
Hello devs, it's me again, Tried launching Roshade, and turns out it automatically changes Deployment Channel to zlive which shows HTTP 401 (Unauthorised) . I tried making the live channel permanent but then Roshade just doesn't works by it's keybinds, and instead keeps trying to change deployment channel to zlive

**Comment by SmokeyPlayz** [comment]
i thought roblox stopped Roshade....

**Comment by pizzaboxer** [comment]
>  I tried making the live channel permanent but then Roshade just doesn't works by it's keybinds, and instead keeps trying to change deployment channel to zlive

**Comment by kek1ich** [comment]
> > I tried making the live channel permanent but then Roshade just doesn't works by it's keybinds, and instead keeps trying to change deployment channel to zlive
> 
> What? What version of Bloxstrap are you using????

version-faaebc838e2e45f6

**Comment by OrphanObliterator** [comment]
> version-faaebc838e2e45f6, tried reinstalling, still doesn't works

i unfortunately cannot tell if you are joking or not

**Comment by pizzaboxer** [comment]
> version-faaebc838e2e45f6, tried reinstalling, still doesn't works

I asked what version of Bloxstrap are you using.

**Comment by kek1ich** [comment]
> > version-faaebc838e2e45f6, tried reinstalling, still doesn't works
> 
> I asked what version of Bloxstrap are you using.

I thought i already said it?

**Comment by pizzaboxer** [comment]
> I thought i already said it?
