### ISSUE TITLE
[BUG] Bloxstrap crashing when using Vulkan

### ISSUE THREAD

**Issue by ThatOneDude447343534543** [pizzaboxer/bloxstrap#872]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When i enter a game using vulkan, a few seconds later my game crashes. How can i fix this?

**Comment by hornykitty** [comment]
use automatic rather than vulkan, its a very alpha/beta option that hardly works so using automatic will pick the best

**Comment by pizzaboxer** [comment]
> When i enter a game using vulkan, a few seconds later my game crashes. How can i fix this?

Read the preliminary instructions next time.

https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch
