### ISSUE TITLE
[BUG] my roblx does not launch

### ISSUE THREAD

**Issue by XPIREDPIRED5** [pizzaboxer/bloxstrap#873]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap loads the bootstrapper but Roblox doesn't open or opens as a background process. Same thing happens when I switch back to the normal Roblox bootstrapper. The only way I can play Roblox is by going into Users>user>AppData>Local then deleting the Roblox folder, then I open RobloxPlayerInstaller.exe as administrator and it opens the Roblox app and shows a login page, it doesn't work without opening as admin

**Comment by hornykitty** [comment]
getting same issue

**Comment by pizzaboxer** [comment]
Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

This is largely sounding like a Roblox problem, but that note about admin privileges is interesting. You can try the same thing with Bloxstrap by going into its installation folder, into its version folder, and then running RobloxPlayerBeta.exe as admin and seeing if it does anything there.

**Comment by XPIREDPIRED5** [comment]
> Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?
> 
> This is largely sounding like a Roblox problem, but that note about admin privileges is interesting. You can try the same thing with Bloxstrap by going into its installation folder, into its version folder, and then running RobloxPlayerBeta.exe as admin and seeing if it does anything there.

Yes i read it and tried everything and none works. I just now tried opening robloxplayerbeta in the bloxstrap version folder and it did nothing. this issue has been going on for around 4 days now

**Comment by pizzaboxer** [comment]
Yeah, it's purely a Roblox problem then. Actually, you've already mentioned how this mostly happens with the original launcher too. Can't really suggest anything else to help you. Sorry.
