### ISSUE TITLE
[BUG] Roblox opens on a White Screen/In the Background

### ISSUE THREAD

**Issue by Matthew-MBG** [pizzaboxer/bloxstrap#874]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Vulkan:
Extremely often, when I open Roblox.  It opens a White screen with what I'd say is a 3:4 aspect ratio around the top left of my display with no audio.  When it doesn't do that, the Roblox client opens in the background with no way to bring it to the foreground and no audio.  The game probably only opens around once every 15 tries.
Automatic:
Roblox opens with a white screen, lets me play after around 10 seconds, and crashes around 5 seconds later.

I've been having these issues for around 2 months.

**Comment by pizzaboxer** [comment]
Sounds like some weird rendering issue. Though, does it hapen without Bloxstrap too? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
