### ISSUE TITLE
[REQ] Multi-Instance Settings

### ISSUE THREAD

**Issue by Zacgamingpro1234** [pizzaboxer/bloxstrap#876]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Multi-Instance is a great feature. But it would be better if you can give each instance a name or settings different that the other. Like I can set instance 1 to 60 FPS and instance 2 to 120 FPS. Or name instance 1 (something) and instance 2 (something else). Goes on and on with every other feature Bloxstrap has included.

**Comment by pizzaboxer** [comment]
i do not care to add features to just facilitate farming
