### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by Lazuski** [pizzaboxer/bloxstrap#877]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. [Inner Exception] System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. [Inner Exception] System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.

exception ss>
![Screenshot (3082)](https://github.com/pizzaboxer/bloxstrap/assets/111620355/ae045ece-44a3-4b7f-9b65-fa09e21de7e0)

Log>[Bloxstrap_20231031T134521Z.log](https://github.com/pizzaboxer/bloxstrap/files/13217180/Bloxstrap_20231031T134521Z.log)

**Comment by SoL4RFLOWV** [comment]
Having the same bug too, hopefully they can fix it soon.

**Comment by pizzaboxer** [comment]
> Having the same bug too, hopefully they can fix it soon.

...This is a completely different issue. And you should've looked at the Wiki first. https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox

Anyway @Lazuski does this happen everytime you try to launch? This seems like a one-off thing.

**Comment by Lazuski** [comment]
> > Having the same bug too, hopefully they can fix it soon.
> 
> ...This is a completely different issue. And you should've looked at the Wiki first. https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
> 
> Anyway @Lazuski does this happen everytime you try to launch? This seems like a one-off thing.

sorry for long respond but i think its just a one off thing cuz when i tried to installed it again it works without any issues

**Comment by Lazuski** [comment]
but why sometimes i got error code 403?
