### ISSUE TITLE
[BUG] Unauthorized

### ISSUE THREAD

**Issue by PaulD2009** [pizzaboxer/bloxstrap#878]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized)

**Comment by PaulD2009** [comment]
![Screenshot 2023-10-31 212327](https://github.com/pizzaboxer/bloxstrap/assets/125788675/de85c49b-acbb-44dd-b032-d19758f91efa)

**Comment by popbob2** [comment]
change your channel to live

**Comment by WaviestBalloon** [comment]
This is normal, read: https://devforum.roblox.com/t/keep-the-zcanary-and-zintegration-channels-semi-public-if-theyre-about-to-be-closed-down/2487241/7?u=waviestballoon

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
