### ISSUE TITLE
[BUG]  Roblox crashes suddenly

### ISSUE THREAD

**Issue by HolyImmortal** [pizzaboxer/bloxstrap#879]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So whenever I use Bloxstrap to play Roblox, all of a sudden my game crashes.

**Comment by Vlad55432** [comment]
Maybe I have same issue
Join any game
When it loads, press shift + f2
And send screenshot

**Comment by pizzaboxer** [comment]
> So whenever I use Bloxstrap to play Roblox, all of a sudden my game crashes.

Have you read the possible fixes provided? Does it happen without Bloxstrap?

**Comment by Aiichirodesu** [comment]
@Vlad55432 what version bloxstrap u download?

**Comment by Vlad55432** [comment]
> what version u download?
Before, just 2.5.3
For now, I just builded for myself 2.5.4 with nvidia trick
Is this still happening?

**Comment by Aiichirodesu** [comment]
How u do that, pls teach me...i wanna play roblox with vulkan renderer bcs thats make my roblox not stuttering

**Comment by Vlad55432** [comment]
> How u do that, pls teach me...i wanna play roblox with vulkan renderer bcs thats make my roblox not stuttering

uh, you can't. roblox updated and BROKE it. Switch to directx

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by admin-elvistrujanovic** [comment]
I need this feature since this new version of Roblox have an bug with Exception code: 0xc0000005 for a very long time and it's not yet fixed for Windows - both appx version and Roblox official version. If we can move to that channel where this bug is not there we can play Roblox without running an Android VM just to run Roblox at all.

**Comment by admin-elvistrujanovic** [comment]
@pizzaboxer Please, re-open this case since it's needed - we need channel switcher feature back

**Comment by pizzaboxer** [comment]
What the hell are you going to do with the channel switcher? What channel would you be switching to?

**Comment by admin-elvistrujanovic** [comment]
> What the hell are you going to do with the channel switcher? What channel would you be switching to?

Well I found some post that someone is hosting an channel that provides older versions of Roblox where this bug that Windows users have doesn't exist yet - I'm not sure exactly the version number of that Roblox but I'm sure that someone who is hosting that channel knows very well those details

**Comment by admin-elvistrujanovic** [comment]
> > someone is hosting an channel that provides older versions of Roblox
> 
> What's the name of it?

zavatarteam2 channel

**Comment by pizzaboxer** [comment]
You can't use that channel. All channels were made private months ago. That's why the selector doesn't exist anymore. Go figure.
