### ISSUE TITLE
Path to rbxfpsunlocker keeps getting set to read-only

### ISSUE THREAD

**Issue by purplux** [pizzaboxer/bloxstrap#88]
Might be user error but every time I update Bloxstrap I get this error and I'm not sure what exactly causes it.
![image](https://user-images.githubusercontent.com/69032098/219809888-2d48b7d4-715e-4c11-ad1a-9b82af910360.png)

My solution is to just disable the "Read-only" property for the entire path of Bloxstrap. Not tedious to do but I decided posting it here would be somewhat helpful.

**Comment by pizzaboxer** [comment]
This is a fix I just added as part of v2.0.0, and it sounds like this only happens when updating, so hopefully it shouldn't happen anymore? Let me know if it happens in a future update.

**Comment by purplux** [comment]
Sounds good, will do. Thanks for the speedy reply!

**Comment by purplux** [comment]
![image](https://user-images.githubusercontent.com/69032098/233679202-fceb1b88-c548-4663-ba95-4cca5dc2e7e9.png)
Still occuring as of v2.2

**Comment by pizzaboxer** [comment]
Yeah, that's normal for whole folders. It's not normal for individual files to be read-only though.

**Comment by purplux** [comment]
Got it, thank you!
