### ISSUE TITLE
[BUG] cant use bloxstrap without it crashing every 40 seconds i launch it

### ISSUE THREAD

**Issue by xtcko** [pizzaboxer/bloxstrap#881]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

cant use bloxstrap without it crashing every 40 seconds i launch it. i went back to the normal roblox launcher and it seems to work fine idk why bloxstrap was crashing if anyone has a fix please let me know.

**Comment by 1011025m** [comment]
Have you tried some of the troubleshooting methods listed here? https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch

If you use the Vulkan renderer, try setting it to Automatic. (Bloxstrap Menu -> FastFlags -> Rendering mode)

**Comment by Helpme9032** [comment]
@1011025m 
I Have A Different problem i cant even launch roblox when im launching bloxtrap nothing happen roblox just stay as a background process

**Comment by pizzaboxer** [comment]
Just to confirm, have both of you read the information provided?

**Comment by Helpme9032** [comment]
@pizzaboxer 
Oh yeah sorry my roblox is working fine now

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
