### ISSUE TITLE
[BUG] zlive because it returned HTTP 401 (Unauthorized) help me

### ISSUE THREAD

**Issue by balenvuitton** [pizzaboxer/bloxstrap#883]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

cannot open bloxtrap bc of this notification 

> 
![Screenshot 2023-11-02 111221](https://github.com/pizzaboxer/bloxstrap/assets/149648113/e5349b85-099b-4a21-849d-840ad915035b)
[Bloxstrap_20231102T041141Z.log](https://github.com/pizzaboxer/bloxstrap/files/13234176/Bloxstrap_20231102T041141Z.log)

**Comment by Vlad55432** [comment]
just read wiki, please
https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
