### ISSUE TITLE
[BUG] when i keep holding right click to move my camera the cursor just moves with it and i can't find a fix for it even if i use another mouse

### ISSUE THREAD

**Issue by krarloa5** [pizzaboxer/bloxstrap#884]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

it just keeps moving or teleporting around where I move my camera please help

**Comment by pizzaboxer** [comment]
Does this happen without Bloxstrap too? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
> I tried switching to normal roblox still didn't fixed

It's a problem with Roblox itself then, I can't really help you with that. Sorry.

**Comment by Claydude33** [comment]
Im having the same problem please help

**Comment by LostInTheBlu** [comment]
Today I was trying to find a way to on youtube, but nothing seems to help

**Comment by LostInTheBlu** [comment]
everything here is word to word the same thing happening to my pc

**Comment by LostInTheBlu** [comment]
perhaps its because the windows model?
