### ISSUE TITLE
Bloxstrap Not Launching Issue.

### ISSUE THREAD

**Issue by ActuallE** [pizzaboxer/bloxstrap#885]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello pizzabloxer! I am a player who really enjoyes Bloxstrap and its fps boost. You have made a really good product - Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized)good product and I love it. But recently, it has been getting an issue when I'm trying to play I really hope you can solve this problem:

**Comment by Vlad55432** [comment]
just read wiki, please
https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox

**Comment by ActuallE** [comment]
Thank you for your assistance. Now I am able to use bloxstrap as usual
again! Thank you so much
