### ISSUE TITLE
[BUG] An exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Yallasez** [pizzaboxer/bloxstrap#886]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/ZLIVE because it returned HTTP 401 (Unauthorized)
[Bloxstrap_20231102T092329Z.log](https://github.com/pizzaboxer/bloxstrap/files/13237174/Bloxstrap_20231102T092329Z.log)

**Comment by Vlad55432** [comment]
just read wiki, please
https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
