### ISSUE TITLE
[BUG] I don't have the thing for the font

### ISSUE THREAD

**Issue by N0rmal-Dude** [pizzaboxer/bloxstrap#888]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I don't have it
![image](https://github.com/pizzaboxer/bloxstrap/assets/149694066/1c2bc18a-3d3d-473a-a001-6965974e6227)

**Comment by Vlad55432** [comment]
huhhh?
which version?

**Comment by pizzaboxer** [comment]
known bug, addressed here

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/d4d0f2a1-c8e8-4e21-8822-7aba14fbc490)

**Comment by carlosmarqus12-commits** [comment]
Ligh

**Comment by carlosmarqus12-commits** [comment]
Quero robux
