### ISSUE TITLE
When I try use a font it breaks and I get kicked from a game.[BUG] 

### ISSUE THREAD

**Issue by Oothan0** [pizzaboxer/bloxstrap#891]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I try enter a game nothing happens and I get kicked out.

**Comment by pizzaboxer** [comment]
What font are you using?

**Comment by Oothan0** [comment]
a minecraft one from dafont.com and you search up minecraft click on the first one thats mine sorry for the wait

**Comment by pizzaboxer** [comment]
Just link or upload the specific one you used here. Also, can you confirm that Roblox works fine if you choose not to use the font?

**Comment by pizzaboxer** [comment]
I've just tried the font you've mentioned, I can confirm that it causes Roblox to not launch. I didn't know incompatible fonts could cause Roblox to stop launching entirely. 
It seems like luck is better with .otf files, so try this one out, which I've checked works for me: https://candyfonts.com/font/minecraft-regular-2.htm
