### ISSUE TITLE
[REQ] remove the channel switch thing because its now useless 

### ISSUE THREAD

**Issue by Findyourlimits** [pizzaboxer/bloxstrap#892]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

this feature is useless the only channel you can access is LIVE so it might as well be removed

**Comment by pizzaboxer** [comment]
acknowledged

**Comment by Findyourlimits** [comment]
holy you replied fast

**Comment by uhokay4** [comment]
what about zfeatureharmony?

**Comment by Findyourlimit** [comment]
That exists?

**Comment by Findyourlimit** [comment]
I'll try on old version of bloxstrap and let you know at some point
