### ISSUE TITLE
idk what is this:

### ISSUE THREAD

**Issue by sebieg** [pizzaboxer/bloxstrap#893]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zfeature600-public-ure-testing because it returned HTTP 401 (Unauthorized)

**Comment by Encythe** [comment]
Issue already addressed, refer to https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
