### ISSUE TITLE
[REQ] Add DX12 to Bloxstrap

### ISSUE THREAD

**Issue by viberblx83** [pizzaboxer/bloxstrap#894]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

directx10 lags directx11 too my pc up to directx12 its performs good

**Comment by TheMetalTechnet** [comment]
> directx10 lags directx11 too my pc up to directx12 its performs good

Roblox would have to add it, so no
