### ISSUE TITLE
no reshade?

### ISSUE THREAD

**Issue by Danilmikhan** [pizzaboxer/bloxstrap#896]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i remember it had a reshade option in integrations but i dont seem to find it now

**Comment by pizzaboxer** [comment]
It was removed in May because the Hyperion anticheat update rendered it unusable.

**Comment by Danilmikhan** [comment]
oh yeah when i tried to add it myself it broke roblox
