### ISSUE TITLE
Roblox Opening As Background App

### ISSUE THREAD

**Issue by rngzenny** [pizzaboxer/bloxstrap#897]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When launching roblox from bloxstrap it says "launching roblox" then just stops and when i check the task manager after it says its running in the background.

**Comment by sscrt** [comment]
ive been dealing with this for 4 days and have no solution

**Comment by pizzaboxer** [comment]
Does it happen without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by goofinglor** [comment]
> Does it happen without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

I cant even open roblox. Cant even use bloxstrap. Something must be wrong.

**Comment by XPIREDPIRED5** [comment]
same happening to me since october 25

**Comment by sscrt** [comment]
Neither Roblox or Bloxstrap is working idk what to do ig

**Comment by rngzenny** [comment]
> Does it happen without? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

yes, ive tried everything ive even reset my whole pc. yesterday it worked without bloxstrap but today EVEN WITHOUT BLOXSTRAP it doesnt work

**Comment by pizzaboxer** [comment]
> but today EVEN WITHOUT BLOXSTRAP it doesnt work

It's a problem with Roblox itself then. That's not a problem on my end and I can't do anything about that. I assume you've read through the Wiki page about Roblox crashing?

**Comment by goofinglor** [comment]
> It's a problem with Roblox itself then.
Huh. The only fix itself is by playing the buggy Microsoft Store version of roblox. If you play on it for a while, roblox might start working again. Or just uninstall bloxstrap and wait a day to reinstall it.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
