### ISSUE TITLE
[BUG] Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/ZSocialTeam because it returned HTTP 401 (Unauthorized)

### ISSUE THREAD

**Issue by ItzExvirnity** [pizzaboxer/bloxstrap#898]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I just launched **Bloxstrap** and this error appeared out of nowhere
`Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/ZSocialTeam because it returned HTTP 401 (Unauthorized)`

It says **ZSocialTeam** so maybe **ZSocialTeam** broke but it also says "Unauthorized" so the authentication failed.
**Wikipedia:**
`Similar to 403 Forbidden, but specifically for use when authentication is possible but has failed or not yet been provided. The response must include a WWW-Authenticate header field containing a challenge applicable to the requested resource. See Basic access authentication and Digest access authentication.`

**Comment by Encythe** [comment]
Issue already addressed, refer to https://github.com/pizzaboxer/bloxstrap/wiki/'HTTP-401-(Unauthorized)'-when-trying-to-launch-Roblox
