### ISSUE TITLE
[BUG] I cant launch roblox either i restart my pc 10 times and it still doesnt work sometimes it does and mostlikely it doesnt can someone help me

### ISSUE THREAD

**Issue by PrettyFastLearner1** [pizzaboxer/bloxstrap#899]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cant launch my roblox :(

**Comment by pizzaboxer** [comment]
Does it happen without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by PrettyFastLearner1** [comment]
it happens with both of the roblox versions

**Comment by pizzaboxer** [comment]
Not my problem then. The best I can really do is point you to [the information article](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch) which outlines everything I know, but is not guaranteed to solve your problem. Sorry.

**Comment by PrettyFastLearner1** [comment]
i guess i just have to wait for them to fix this problem
