### ISSUE TITLE
suggestion: make the app icon modifiable

### ISSUE THREAD

**Issue by dropier** [pizzaboxer/bloxstrap#9]
is there a way to modify the roblox app icon/bloxstrap's icon on the taskbar when loading a game? i have a 2016 pack installed on the mods folder together with a theme on the roblox website, and the only finishing touches i need are the ability to change the app icon on the taskbar when loading a game, and when inside a game

**Comment by flight112** [comment]
pizzaboxer told me that it's impossible unless you actually modify the client itself
the launchers icon does change (iirc) but not the clients icon

**Comment by pizzaboxer** [comment]
Yes, it requires directly modifying the RobloxPlayerBeta executable. I've tested this myself before and it doesn't appear to set off the anticheat. However, I'd rather not do it. If someone wants to implement this in a fork or something then they can do so there as I'm not comfortable adding this as a feature.

**Comment by dropier** [comment]
it would be wonderful if someone did that
