### ISSUE TITLE
Process priority configuration

### ISSUE THREAD

**Issue by FoxyelperroDJ** [pizzaboxer/bloxstrap#900]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add DXVK D3D ;)

**Comment by pizzaboxer** [comment]
Would've been really cool to have, but Hyperion is not letting that fly any time soon.

**Comment by FoxyelperroDJ** [comment]
Could you add an option to start with different Priorities? like "high priority", "normal" n "below normal".
I think it would be a nice feature (I hate opening Task Manager and doing it manually) ty, ty!

**Comment by pizzaboxer** [comment]
That's an interesting idea, I can consider that.

**Comment by Vlad55432** [comment]
I think making priorities for games/apps - useless
Like, why? For high fps? It's an old myth.

**Comment by pizzaboxer** [comment]
Turns out there's no point in doing this. Roblox seems to be taking control over the process priority for itself. Any attempt to change it manually just results in Roblox automatically changing it back itself.
