### ISSUE TITLE
[REQ] Bring back the Renderer Selection Menu, but now use a warning pop-up before using the menu.

### ISSUE THREAD

**Issue by wilsontulus** [pizzaboxer/bloxstrap#902]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I understand that most people are experiencing some issues because of the Vulkan renderer being "unstable", But here's the thing: 
**it also depends on the GPU, driver, and the OS you're using.** 

If you're using an AMD GPU with Vulkan 1.3 support, it will run perfectly like it's being run on Direct3D11. It also lowers the CPU usage a bit (3-10%) thanks to the nature of Vulkan itself. This is probably going to be useful on battery-powered or "more cores lower clockspeed" type of CPUs.

Also some Linux guys (like me) are setting up Bloxstrap itself for Roblox player instead (so Grapejuice is only for Studio), **because currently Bloxstrap itself have more features than Grapejuice and Vinegar**. OpenGL and Vulkan drivers on Linux is completely MUCH better than Windows drivers, because on Windows, DirectX is more preferrable than the other two rendering methods.

And one thing, OpenGL driver is 99.9% stable at all times and never crashes for me, playing on my main PC with an old enough Radeon HD GPU that's unfortunately not Vulkan-capable. (while on Linux though - on Windows, Direct3D11 is preferred)

I played Roblox Player with Vulkan for more than 2 hours and never have any issues. 
(GPU specs: AMD Vega 8 Vulkan 1.3 Linux (my brother's laptop). and Intel HD 4400 Vulkan 1.1 Linux (my own laptop)).
Intel HD 4400 sometimes crash on "Roblox App Menu", but it was very stable while playing actual games, but that's because Haswell's Vulkan driver is buggy and kind of incomplete anyways. 
But the AMD Vega 8 almost never crash at all; it only crashes if you're scouring on the in-app Catalog for too long.

So the conclusion is, just at least bring back the renderer menu, but this **there's should be a warning that the renderers were experimental and may not work on some HW configurations.**. Don't just remove an useful feature because of some people just 100% hoping that everything is stable; at least mark this as Experimental or something so more people will understand.

**Comment by 1011025m** [comment]
Hey there, thanks for bringing this up!

Almost all of the feedback that we get are from users who are on Windows, and we haven't come across any considerable amount of users who use Bloxstrap on Linux. (I've seen probably less than a dozen on the Discord server, mostly relating to the desktop runtime not being able to install - i.e. Bloxstrap does not run)

There is also the fact that we don't officially support Linux, so there is the risk that you are taking.

I'm surprised you are able to get it running at all. You seem to imply that there is an easy script to set up the environment for Bloxstrap to run. If you are able to, are you able to share? I personally run a home server which has an AMD GPU (RX 5600 XT) installed, it'd be very beneficial for us to test things out!

Now, you say that we shouldn't remove "experimental" settings. The reality is that if we make them too easily accessible then we get a LOT (like A LOT) of uninformed users who think those settings could magically improve their framerate, and then turn to us when things are breaking apart. To balance things out, we remove the option in the GUI but you are still able to add the FFlags by yourself. (so the chances are, if you add the FFlag you probably know what you are doing and are aware of the negatives it brings... unless not)

We'll evaluate this. Thank you, again.

**Comment by wilsontulus** [comment]
Hello there, I understand that Bloxstrap is not officially supported on non-windows platforms, but the fact that Bloxstrap has more features than Grapejuice and Vinegar gives many Roblox on Linux players tempting to use Bloxstrap instead of Grapejuice for Roblox Player.

I'm not mentioning that there's an easy script to straight up get Bloxstrap up and running, they've done it manually by using custom wine-ge fork and XDG desktop entries to launch from the web browser.

1. You might need to use a Wine-GE fork: https://github.com/GloriousEggroll/wine-ge-custom/releases
2. Install .NET Desktop 6.0 Runtime as usual.
3. Because Microsoft Edge installer is broken on wine, you need to deny every access to `$prefix/drive_c/Program Files (x86)/Microsoft` directory by using `chmod 000`. If the "Microsoft" folder isn't there, create the folder with the mentioned name in `$prefix/drive_c/Program Files (x86)/Microsoft` directory.
4. Then install Bloxstrap as usual. It should open properly, take your time to configure it, and install.
5. Make sure it doesn't stuck on WebView2 process, it should continue till Starting Roblox.
6. After Roblox finally opens, make your own `.desktop` entry file pointing to Bloxstrap with custom environment variables (e.g. `WINE` and `WINEPREFIX`) and custom working directory (at the bin folder of the custom wine-ge fork).
7. Done, it should launch from the web or the app itself.

About the renderer thing, the warning should be clear and obvious that it will only give positive affects on some hardware and operating systems.

**Comment by pizzaboxer** [comment]
I was considering just adding a warning, but given the userbase I'm dealing with here, I figured it would be better for everyone if it was just temporarily removed completely. If you still want to use Vulkan, you can just set the flag for it directly with `FFlagDebugGraphicsPreferVulkan`, nothing will be stopping you.
