### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Clearprototype7** [pizzaboxer/bloxstrap#903]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![error](https://github.com/pizzaboxer/bloxstrap/assets/110124911/c3a42dc4-6923-481f-aab8-da3643deb816)

**Comment by pizzaboxer** [comment]
One-off problem. Just launch again and it should work. If it doesn't, it's likely your antivirus preventing it from connecting to the internet.
