### ISSUE TITLE
[BUG] No Channel change thing

### ISSUE THREAD

**Issue by DragonKillerz** [pizzaboxer/bloxstrap#904]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The Bloxstrap Channel change is not a thing for some reason 
![image](https://github.com/pizzaboxer/bloxstrap/assets/85683446/f4aa2756-ff7b-43f3-85d9-95cc0a721d17)

**Comment by RyanLua** [comment]
Hey @DragonKillerz,

In the latest release as of now, [v.2.5.4](https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4), it mentions that the channel selector being removed.

> The channel selector has been (likely temporarily) removed, and using a restricted channel will auto- switch you to the default one.

Therefore it is expected behavior to not have the channel selector as it has been temporarily removed.

**Comment by DragonKillerz** [comment]
i also didnt have this prior 2.5.4

**Comment by DragonKillerz** [comment]
> Hey @DragonKillerz,
> 
> In the latest release as of now, [v.2.5.4](https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4), it mentions that the channel selector being removed.
> 
> > The channel selector has been (likely temporarily) removed, and using a restricted channel will auto- switch you to the default one.
> 
> Therefore it is expected behavior to not have the channel selector as it has been temporarily removed.

how will i use roblox now?

**Comment by pizzaboxer** [comment]
> how will i use roblox now?

What do you mean?

**Comment by DragonKillerz** [comment]
> > how will i use roblox now?
> 
> What do you mean?

i cant use the zavatar thing and cant play

**Comment by pizzaboxer** [comment]
zavatarteam hasn't been usable for like the past five days?
