### ISSUE TITLE
[REQ] Please Bring back the Renderer mode Selector.

### ISSUE THREAD

**Issue by Zane14P** [pizzaboxer/bloxstrap#906]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Please Bring it back. My **Laptop** has _**9-15 FPS**_ in **Roblox** games, But after i use **Bloxstrap** and using _**OpenGL**_ **Renderer mode** the _**FPS**_ increased so much, its _**24-50 FPS**_ then i was so happy. But why in the lastest Version of **Bloxstrap** is deleted that Feature?. That feature was so useful, **Bloxstrap Team** please bring it back. Thank You.

~Zane

**Comment by pizzaboxer** [comment]
We'll consider re-adding the option at a later time, and thank you for letting us know about a case where the option may be needed. If you want to still use OpenGL, you can go into the FastFlag editor and add new with the following options:

Name: `FFlagDebugGraphicsPreferOpenGL`
Value: `True`

**Comment by SanUwU** [comment]
how bout direct3d 10 ?

**Comment by pizzaboxer** [comment]
FFlagDebugGraphicsPreferD3D11FL10

**Comment by Zane14P** [comment]
TYSM!
