### ISSUE TITLE
[REQ] Can you Please add the change api option again?

### ISSUE THREAD

**Issue by FFFadal** [pizzaboxer/bloxstrap#907]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

i get way higher frames in vulkan rather than directx 11, to be specific i get 100 fps more :(

**Comment by TheMetalTechnet** [comment]
> i get way higher frames in vulkan rather than directx 11, to be specific i get 100 fps more :(

If you had done a little bit of research you would know that this option was removed due to Direct3D 11 being the only rendering API that isn't broken. Vulkan and OpenGL trigger Hyperion and D3D 10 works only with low graphics quality

**Comment by pizzaboxer** [comment]
If Vulkan works just fine for you, then you can manually add the `FFlagDebugGraphicsPreferVulkan` flag in the editor, and set it to `True`. If Roblox breaks sometime in the future, just be mindful about the fact that you have it enabled.

**Comment by FFFadal** [comment]
> If Vulkan works just fine for you, then you can manually add the `FFlagDebugGraphicsPreferVulkan` flag in the editor, and set it to `True`. If Roblox breaks sometime in the future, just be mindful about the fact that you have it enabled.

ill definitely use that command, thanks!
