### ISSUE TITLE
Roblox using around 35% of my CPU while Bloxstrap is installed, but only around 17% when Bloxstrap isn't installed

### ISSUE THREAD

**Issue by ImaginativeLAA** [pizzaboxer/bloxstrap#908]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Whenever I have Bloxstrap enabled, Roblox will sometimes use 35% of my CPU and cause major FPS drops. I tested this, and it only happens while Bloxstrap is installed.

There's a temporary fix for this problem, which is restarting my PC.

**Comment by pizzaboxer** [comment]
Can I see the list of FastFlags you have configured? Open the menu, go to the editor, and show the list.

**Comment by ImaginativeLAA** [comment]
> Can I see the list of FastFlags you have configured? Open the menu, go to the editor, and show the list. Oh also, are you using a CPU with integrated graphics?

I have no FastFlags configured. My CPU is 11th Gen Intel(R) Core(TM) i5-1135G7. Sorry, I'm not really good with CPUs so I don't know what exactly "integrated graphics" means.

**Comment by pizzaboxer** [comment]
Oh, you're using a laptop. Well I'm not sure what the correlation between the two would be, but you can try the following two things separately: set your framerate limit to zero, and disable any integrations you have enabled. See if those change anything.

**Comment by ImaginativeLAA** [comment]
> Oh, you're using a laptop. Well I'm not sure what the correlation between the two would be, but you can try the following two things separately: set your framerate limit to zero, and disable any integrations you have enabled. See if those change anything.

Thank you, it actually kinda fixed my problem. Just a few lag spikes here and there but I think that's a different problem

**Comment by pizzaboxer** [comment]
Which one of those specifically fixed it?

**Comment by ImaginativeLAA** [comment]
> Which one of those specifically fixed it?

I did both.

**Comment by pizzaboxer** [comment]
I received one other report relating to the same issue, and it turned out to be because of the framerate limit flag. You should be able to re-enable your integrations.
