### ISSUE TITLE
Can someone now how to fix unapproved third party in roblox HELP me pls I want to play roblox again

### ISSUE THREAD

**Issue by ganang2321** [pizzaboxer/bloxstrap#909]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

help me pls
![image](https://github.com/pizzaboxer/bloxstrap/assets/149892170/e06fe4e3-db77-4c49-93ff-640035ffc5fc)

**Comment by pizzaboxer** [comment]
Nothing I can do anything about, see #774. It should eventually go away by itself though.
