### ISSUE TITLE
[System.Exception: Signature does not match!]

### ISSUE THREAD

**Issue by Ginger1ninga** [pizzaboxer/bloxstrap#910]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

"System.Exception: Signature does not match!" this issue is happening alot even with me restarting pc is there any other fix to try?
[Bloxstrap_20231104T163312Z.log](https://github.com/pizzaboxer/bloxstrap/files/13257182/Bloxstrap_20231104T163312Z.log)

**Comment by pizzaboxer** [comment]
Not really, since otherwise it should sort of just fix itself eventually. For now, you can simply manually update Roblox with the following steps:

- Download the latest version of Roblox from https://rdd.latte.to/?channel=LIVE&binaryType=WindowsPlayer&version=version-6f0b02756d914e3e
- Go to `%localappdata%\Bloxstrap` in the file explorer
- Extract the contents of the zip archive to `Versions\version-6f0b02756d914e3e` (create a new folder for it)
- Open `State.json` in a text editor and update the `VersionGuid` field with a value of `version-6f0b02756d914e3e`
- Launch Roblox and it should just work

If you need some help, be sure to let me know.

**Comment by Ginger1ninga** [comment]
> Not really, since otherwise it should sort of just fix itself eventually. For now, you can simply manually update Roblox with the following steps:
> 
> * Download the latest version of Roblox from https://rdd.latte.to/?channel=LIVE&binaryType=WindowsPlayer&version=version-3aba366803e44f0e
> * Go to `%localappdata%\Bloxstrap` in the file explorer
> * Extract the contents of the zip archive to `Versions\version-3aba366803e44f0e` (create a new folder for it)
> * Open `State.json` in a text editor and update the `VersionGuid` field with a value of `version-3aba366803e44f0e`
> * Launch Roblox and it should just work
> 
> If you need some help, be sure to let me know.

**Comment by Ginger1ninga** [comment]
> Not really, since otherwise it should sort of just fix itself eventually. For now, you can simply manually update Roblox with the following steps:
> 
> * Download the latest version of Roblox from https://rdd.latte.to/?channel=LIVE&binaryType=WindowsPlayer&version=version-3aba366803e44f0e
> * Go to `%localappdata%\Bloxstrap` in the file explorer
> * Extract the contents of the zip archive to `Versions\version-3aba366803e44f0e` (create a new folder for it)
> * Open `State.json` in a text editor and update the `VersionGuid` field with a value of `version-3aba366803e44f0e`
> * Launch Roblox and it should just work
> 
> If you need some help, be sure to let me know.

i tried this today but still it doesnt work i tried also restarting pc and turning off the antivirus+firewall

**Comment by pizzaboxer** [comment]
Well in the two weeks it took to you to respond, Roblox has updated about two times, so yeah it won't work anymore.
Are you really still getting the same error? If you [launch Roblox with the official launcher](https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap) and check the About page, what version does it report you as being on?

**Comment by Ginger1ninga** [comment]
> Well in the two weeks it took you to respond, Roblox has updated about two times, so yeah it won't work anymore. Are you really still getting the same error? If you [launch Roblox with the official launcher](https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap) and check the About page, what version does it report you as being on?

i did got it working in the last 2 weeks by disabling my anti virus btw im Rayan 1.0 in discord

**Comment by pizzaboxer** [comment]
Closing this since I'm classifying this as unsolvable
