### ISSUE TITLE
i cant start my roblox[BUG] 

### ISSUE THREAD

**Issue by shaiden1** [pizzaboxer/bloxstrap#911]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

i cant not start my roblox it wont open

**Comment by TheMetalTechnet** [comment]
Do you by any chance are using a FFlag for deferent rendering API?

**Comment by pizzaboxer** [comment]
Does it happen without Bloxstrap too? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by Craxa** [comment]
btw roblox will not open [BUG] also happens when using bloxstrap

**Comment by TheMetalTechnet** [comment]
> btw roblox will not open [BUG] also happens when using bloxstrap

Roblox issue, can't really do anything about it

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
