### ISSUE TITLE
[BUG] voxel lighting not working

### ISSUE THREAD

**Issue by boogawooga3** [pizzaboxer/bloxstrap#914]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i join certain games with voxel lighting on, it automatically goes into realistic lighting

**Comment by pizzaboxer** [comment]
If you press Shift+F2 when in a game, what does it say under "Graphics > Technology"?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
