### ISSUE TITLE
[BUG] Fastflags editor not working

### ISSUE THREAD

**Issue by xL1ll** [pizzaboxer/bloxstrap#915]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When trying to edit the "Show preset flags" it doesn't work, for example if I try to change "FFlagHandleAltEnterFullscreenManually" from false to true, the changes are reverted or just not saved, any idea what should I do?

**Comment by pizzaboxer** [comment]
FFlagHandleAltEnterFullscreenManually is always force-set to False.
