### ISSUE TITLE
Does bloxstrap compatible with Roshade?

### ISSUE THREAD

**Issue by reick3rmd** [pizzaboxer/bloxstrap#916]
Just a question, cause I tried combining roshade with bloxstrap and it's doesn't work.

**Comment by HardBucks** [comment]
Roblox anti-cheat dosent like roshade or reshade, just uninstall it.

If you wanna use them, no it's not possible.

**Comment by pizzaboxer** [comment]
Roshade hasn't worked with Roblox for the past six months because of Roblox's anticheat.
