### ISSUE TITLE
Please add back the channel feature

### ISSUE THREAD

**Issue by sscrt** [pizzaboxer/bloxstrap#917]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Please add back the channel feature and please add back the feature to use Z channels like ZAVATARTEAM2 or ZCANARY it was the only working way to fix Roblox opening as a background process and make it actually playable, but now since it is removed alot of people are still dealing with the issue with Roblox opening as a background process.

**Comment by popbob2** [comment]
upgrade to 2.5.3

**Comment by Findyourlimits** [comment]
it was removed for a reason they are unusuable now

**Comment by pizzaboxer** [comment]
Those channels aren't usable anymore, and haven't been for a few days. I didn't remove the option for no reason.

**Comment by Findyourlimit** [comment]
Exactly its basically the V3 menu. **Gone**
