### ISSUE TITLE
[REQ] Removal of the ability to change your deployment channel

### ISSUE THREAD

**Issue by WaviestBalloon** [pizzaboxer/bloxstrap#918]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Roblox has now locked all of the non-production deployment channels, `LIVE` is now the only available channel for normal users, making the feature in Bloxstrap redundant.

**Comment by 1011025m** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/37438176/7dec2330-65cc-4839-9b9d-f61fbd03bc2f)

**Comment by 1011025m** [comment]
oh wait, you're from latte. is this just trolling -_-

**Comment by WaviestBalloon** [comment]
> oh wait, you're from latte. is this just trolling -_-
> 
> <sup>im sorry</sup>

![Screenshot_20231103-222617.png](https://github.com/pizzaboxer/bloxstrap/assets/31796727/fe8d1881-46f4-4c58-8938-8f41142d8242)
