### ISSUE TITLE
[BUG] failed to download or apply critical settings please check your internet connection. Error info: HttpError: Connecfail

### ISSUE THREAD

**Issue by Devaraz1** [pizzaboxer/bloxstrap#919]
I tried Everything on youtube and still can't run
i've tried via browser and still the same
![image](https://github.com/pizzaboxer/bloxstrap/assets/145520560/bc1dc714-c8a9-4347-b637-d872328b81c9)

**Comment by pizzaboxer** [comment]
This is a problem with connecting to Roblox. Bloxstrap has nothing to do with this.
