### ISSUE TITLE
[BUG] cant join any roblox game with bloxstrap, even tho i downloaded latest desktop runtime. works fine with normal roblox.

### ISSUE THREAD

**Issue by fellowpal** [pizzaboxer/bloxstrap#920]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![error](https://github.com/pizzaboxer/bloxstrap/assets/149997369/38ce6171-9a6d-4bee-81c1-107091872d44)

**Comment by pizzaboxer** [comment]
Run `dotnet --info` in a Command Prompt window and show what it outputs here.

**Comment by fellowpal** [comment]
> Run `dotnet --info` in a Command Prompt window and show what it outputs here.
![cmd](https://github.com/pizzaboxer/bloxstrap/assets/149997369/5e7675a9-da11-423f-a6fd-1c538facd93d)

**Comment by pizzaboxer** [comment]
Well, you definitely do have it installed.  The only two things I can think of is that either something is sandboxing it (some antiviruses do that when suspicious of something), or it just didn't install properly, in which case you can try reinstalling it.

**Comment by fellowpal** [comment]
> Well, you definitely do have it installed. The only two things I can think of is that either something is sandboxing it (some antiviruses do that when suspicious of something), or it just didn't install properly, in which case you can try reinstalling it.

if i reinstall it, settings will be reset?

**Comment by pizzaboxer** [comment]
> if i reinstall it, settings will be reset?

What settings? Just reinstall it.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
