### ISSUE TITLE
Bloxstrap crashes my PC everytime I open it, but roblox player doesn't

### ISSUE THREAD

**Issue by ish4rk** [pizzaboxer/bloxstrap#921]
It just does that for some reason, I don't think its my hardware since I just upgraded it 3 months ago

**Comment by pizzaboxer** [comment]
What do you mean by it crashes your PC?

**Comment by BokBoy** [comment]
If you get a blue screen, check what the error says and search it up.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
