### ISSUE TITLE
[BUG] I cant open up roblox, if i try to do, this error code shows up: System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\ehsan\AppData\Local\Bloxstrap\Versions\version-6f0b02756d914e3e\RobloxPlayerBeta.exe' with working directory 'C:\Users\ehsan\Downloads'. The requested operation requires elevation.

### ISSUE THREAD

**Issue by SomeoneWithBadFPS803** [pizzaboxer/bloxstrap#922]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Screenshot 2023-11-06 172546](https://github.com/pizzaboxer/bloxstrap/assets/150060083/34d19bb6-f9b3-4bf1-a7cb-91ca43063aac)

**Comment by BokBoy** [comment]
@SomeoneWithBadFPS803 There's potentially private data on the title and picture.

**Comment by SomeoneWithBadFPS803** [comment]
> At the path indicated in the error message (`%localappdata%\Bloxstrap\Versions\version-6f0b02756d914e3e`), open the file properties for RobloxPlayerBeta.exe, check the Compatibility tab, and see if it's marked to run as Administrator. Disable it if it is.

oh ok thanks pizzaboxer :) Ill try

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

**Comment by brooooooooooks** [comment]
disable as admin in roblox properties then itll work

**Comment by GODCHOMP** [comment]
> Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.

It did not work, cuz it wasn't even ticked

**Comment by Arcadex110** [comment]
I have the same issue, but when I look in the folder identified, there isn't the file I need to change, and when I try to do it through the bloxstrap settings it says to install first before. Leading to the same error every time. helllllop

**Comment by huhwhy21** [comment]
It kinda the same to mine. Mine was 


  System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

  I think you just need to get the latest bloxstrap or disable admin for roblox.
