### ISSUE TITLE
[REQ] Ability to Export FFlag JSON from the FFlag Editor

### ISSUE THREAD

**Issue by loustact** [pizzaboxer/bloxstrap#923]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Simple request, ability to export FFlag JSON from FFlag Editor as the import function only exists.

This feature would be useful if you want to share your FFlag list to someone else, or doing reinstallations (like uninstalling to switch to using package managers like Scoop, which what I did just a while ago) without manually copy-pasting your list. If you want to pass this list to your other computer if you do have one, having an easy way of exporting the JSON would be convenient. It could also help out smooth brains like me who don't know where the JSON file is usually stored at for these kinds of use cases.

I understand if this won't get added as these are pretty much rare cases, especially reinstallation, for everyday users that haven't encountered any problems. There is really no point in reinstalling if no issues arise to begin with, for example. Though, it would be great to have it in moments in which these cases do arise.

**Comment by pizzaboxer** [comment]
Open the Mods folder. Go to the ClientSettings folder. It'll be there.

**Comment by loustact** [comment]
> Open the Mods folder. Go to the ClientSettings folder. It'll be there.

Thank you :)

Sorry for causing a bit of a trouble.

**Comment by pizzaboxer** [comment]
I mean, I agree with you that it should probably be more easily accessible, but I'm just pointing out that's where they're stored.

**Comment by loustact** [comment]
Ah, I misunderstood. Sorry about that.

Anyways, I do hope you consider this in the future :)

**Comment by bluepilledgreat** [comment]
#1158

**Comment by boblox69** [comment]
guy why i cant put the code/script into export JSON
