### ISSUE TITLE
Is Bloxstrap Safe??

### ISSUE THREAD

**Issue by Prcent** [pizzaboxer/bloxstrap#924]
I tried installing bloxtrap but windows defender didnt let me open it because it says my pc may be at risk after opening it. I dont want to have something mallicious in my pc. Please reply and tell me if its safe and how to install it without Windows Defender blocks it. Thanks

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap#installing
> It's not unlikely that Windows Smartscreen will show a popup when you run Bloxstrap for the first time. This happens because it's an unknown program, not because it's actually detected as being malicious. To dismiss it, just click on "More info" and then "Run anyway".

All the code for it is publicly available here. It's not possible for me to distribute malicious code without somebody noticing, so someone would have called me out on it by now. VirusTotal detections show it as completely clean (besides one ai detection from a russian company nobody has ever heard of).
