### ISSUE TITLE
i got a roblox crash client when i open bloxstrap but i had an error called : Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized).

### ISSUE THREAD

**Issue by Khylethecolonia** [pizzaboxer/bloxstrap#925]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

can you fix this error pls is this one error poped up : Bloxstrap.Exceptions.HttpResponseException: Could not connect to https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zlive because it returned HTTP 401 (Unauthorized)

**Comment by 1011025m** [comment]
Hi,

Please update to the latest Bloxstrap version (v2.5.4). This error will be automatically handled for you.

You can do this by enabling the "Automatically update Bloxstrap" option in Bloxstrap Menu > Behaviour.

**Comment by Findyourlimit** [comment]
It's because all the channels apart from live are restricted by Roblox right now, and your using ZLIVE, which is one of the channels, the latest version of bloxstrap removed this feature likely temporarily
