### ISSUE TITLE
[BUG] Roblox always closes every time i play a game whenever i apply a font. I used multiple websites and none of them have worked, is it the device im using? (MSI Laptop) (Edit: I downloaded the other thing that is vital before Bloxstrap) [BUG] 

### ISSUE THREAD

**Issue by BuzzTheSearcher** [pizzaboxer/bloxstrap#928]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When joining a game with literally any font, roblox decides to just close and always does this when i have a font on but however, when I turn the fonts off, it's working perfect and fine. I have an MSI Laptop and I've used many websites for fonts but none work, Is it because of the device I am using? The image with the clear text is without the font activated and the other image is with the font on. When I join a game without the font, its perfectly fine. Opposite for when the font is on. It just closes.
![image](https://github.com/pizzaboxer/bloxstrap/assets/150404095/afac97a0-beb9-4cf4-ae3b-8efd8269accc)
![image](https://github.com/pizzaboxer/bloxstrap/assets/150404095/318d47c0-faec-4085-bbd1-ee96e67e40fb)

**Comment by pizzaboxer** [comment]
Using fonts that aren't 100% compatible with Windows will cause them to not render. For good measure, just try and see if [Comic Sans](https://www.wfonts.com/font/comic-sans-ms) works.
