### ISSUE TITLE
[BUG]My roblox dont open no matter what i try to do.

### ISSUE THREAD

**Issue by CUBRILAHNT** [pizzaboxer/bloxstrap#929]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I cant open roblox, when i start it clicking at the green button on the site it shows bloxstrap interface and roblox dont open, i tried to use the normal roblox or enable/disable the desktop app but it didnt work too, i tried to search for everyting that i could to solve my problem, but roblox dont want to open, it just shows at the task manager that bloxstrap and roblox are open as second plane.

**Comment by IngravedSoul** [comment]
Same here

**Comment by pizzaboxer** [comment]
> i tried to use the normal roblox or enable/disable the desktop app but it didnt work too

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/9a92dddb-e2d8-48de-b9f3-1dc2a009a3b8)

This is a problem with Roblox itself. I can't do anything about this. Sorry.
