### ISSUE TITLE
Rendering mode is not available

### ISSUE THREAD

**Issue by skyfrost77** [pizzaboxer/bloxstrap#930]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I watched a lot of tutorials on youtube about this app, but i noticed every single one of them has the rendering mode, but when i use the app it does not have the rendering mode. Is there something wrong with my laptop or the application?
<img width="716" alt="Screenshot_2" src="https://github.com/pizzaboxer/bloxstrap/assets/137393969/0388f2e2-b6b4-4b6b-9e2b-d7b95afcb8ab">

**Comment by pizzaboxer** [comment]
See the release notes listed on the page where you downloaded it.
> "Removed option for choosing the rendering mode. It's now just extremely unstable."

If you absolutely ***need*** to change it (which you shouldn't have to), you can configure it manually according to these instructions.

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/593d0262-6af5-49e2-afff-42bf82e7035a)

**Comment by popbob2** [comment]
stupid excuse "extremly unstable", i can play roblox with direct3D 11 for hours without any issues

**Comment by skyfrost77** [comment]
I'll definitely considering this, thanks!
