### ISSUE TITLE
I can't add in custom cursors inside of the Modification tab.

### ISSUE THREAD

**Issue by mintsoverhere** [pizzaboxer/bloxstrap#931]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

As you already know, you can replace cursors and sounds in the modification tab (from what ive heard), but. Whenever i try to do so, it just doesn't work. It doesnt show up and it resets it back to the default roblox cursor.

**Comment by TheMetalTechnet** [comment]
Make sure that folder structure is correct and files have correct names

**Comment by pizzaboxer** [comment]
> It doesnt show up and it resets it back to the default roblox cursor.

Where did you place the files? Can you show what cursor you see instead?

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
