### ISSUE TITLE
Version 4 of Escape Menu Not Applying

### ISSUE THREAD

**Issue by eizen85** [pizzaboxer/bloxstrap#933]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Idk if they just changed it to the default version but I want my escape menu to look like the version 4 as shown in this image: https://github-production-user-asset-6210df.s3.amazonaws.com/41478239/253800786-a04fe3bb-c279-4850-b60a-83da32c242d6.png but it doesn't change anything it's just the default escape menu

**Comment by github-production-user-asset** [comment]
change your Preferred escape menu version to Default

**Comment by pizzaboxer** [comment]
> but it doesn't change anything it's just the default escape menu

Does the default menu not look like that?

**Comment by eizen85** [comment]
> > but it doesn't change anything it's just the default escape menu
> 
> Does the default menu not look like that?

yeah its not supposed to be transparent

**Comment by pizzaboxer** [comment]
They updated it to be transparent. That image is from April.

**Comment by eizen85** [comment]
> They updated it to be transparent. That image is from April.

Ohh ok
