### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LukaGamer19** [pizzaboxer/bloxstrap#934]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).

This message pops up when i start running roblox.

**Comment by pizzaboxer** [comment]
Does this show every time you launch Roblox? Provide a log file please.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
