### ISSUE TITLE
[BUG] Some games make the ping extremely high and makes the FPS counter not match the current FPS

### ISSUE THREAD

**Issue by mrjayden17** [pizzaboxer/bloxstrap#936]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

With BloxStrap, I had a couple of issues while playing SOME games.
For example, the ping goes extremely high and over the limits that it makes the game unplayable + if the game has a FPS unlocker the FPS does not match the counter.

BloxStrap causes it, my internet doesn't suck and I tried playing the same game without BloxStrap. 
![image](https://github.com/pizzaboxer/bloxstrap/assets/147157817/b66f4b49-718d-4d99-8d52-afe4b9fd4f29)
![image](https://github.com/pizzaboxer/bloxstrap/assets/147157817/8fe95cf7-b540-4bec-94a2-58ec05926baa)
![image](https://github.com/pizzaboxer/bloxstrap/assets/147157817/15618b71-4802-461e-88b7-a44423fa36f3)

**Comment by pizzaboxer** [comment]
> For example, the ping goes extremely high and over the limits that it makes the game unplayable

Known problem with unlocking FPS. See #816. If it's that big of an issue, you'll just have to not use it, and keep it set to zero for defaults.
