### ISSUE TITLE
[BUG] bloxtrap file doesnt show as an executable

### ISSUE THREAD

**Issue by LulamoonLover** [pizzaboxer/bloxstrap#937]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I downloaded .NET 6 Desktop Runtime and then proceeded to download bloxtrap v2.5.4 using both the link and with winget. Each time they show that the file has been successfully downloaded but when I check to see it, it's not even an exe and I can't run it.

the file's name shows as "f7a2b9c1-a8f5-4bca-ba61-c22271e1f1ff"
its file type is "file"
and its size is 7,781kb

**Comment by TheMetalTechnet** [comment]
Are you sure you downloaded it correctly?

**Comment by pizzaboxer** [comment]
If you've used Winget, then by now it should already be installed? Is it not there in your application list?
