### ISSUE TITLE
[PROBLEM] FPS UNLOCKER WORKED ONCE WONT WORK NOW

### ISSUE THREAD

**Issue by OmarKhaledThePilot** [pizzaboxer/bloxstrap#938]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello there! Today i got BloxStrap to unlock my fps on roblox for the first time that i got it, it unlocked fps very very well but i got a little mad when the Gui was the old one and the "Oof sound" was also the old one and so i went to change stuff and then the fps unlocker stopped and it just wont work now, i did uninstall and all but still nothing. hope to get an answer soon!!

**Comment by pizzaboxer** [comment]
Whenever you go to launch Roblox, avoid launching it through the "Roblox Player" shortcut as that will launch Roblox through the official launcher. Launch it through the "Play Roblox" shortcut instead. You can read more about it here. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap
