### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'D:\New folder\Modifications\ClientSettings\ClientAppSettings.json' is denied.

### ISSUE THREAD

**Issue by Botrity** [pizzaboxer/bloxstrap#940]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When I try to open roblox this error comes up- System.UnauthorizedAccessException: Access to the path 'D:\New folder\Modifications\ClientSettings\ClientAppSettings.json' is denied.

**Comment by pizzaboxer** [comment]
Did you ever delete the folder that it was installed to?

**Comment by Botrity** [comment]
> Did you ever delete the folder that it was installed to?

Uh yes I reinstalled in my C drive it works now! :)
