### ISSUE TITLE
[SUGGESTION] add separate font option for chat

### ISSUE THREAD

**Issue by PoopieInMyIceCream** [pizzaboxer/bloxstrap#941]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I would like a separate font option for chat to have more user choice, if it's possible. 

This hypothetical option will be next to the current font option if it's implemented.

**Comment by pizzaboxer** [comment]
Not possible. We can only globally apply fonts.
