### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by reick3rmd** [pizzaboxer/bloxstrap#942]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

there are two bloxstrapper in my hidden icons and its roblox not opening and really no i tried roblox bootstrapper method
its there anyway to fix that or that the problem of my roblox not launching??
![Screenshot 2023-11-17 082912](https://github.com/pizzaboxer/bloxstrap/assets/149942397/1f310dee-68f3-417d-8e68-89d0356395d0)

**Comment by reick3rmd** [comment]
update there are three now it add more every time i tried to launch bloxstrap shortcut

**Comment by reick3rmd** [comment]
bloxstrap and roblox game client open as background processes than apps

**Comment by pizzaboxer** [comment]
> or that the problem of my roblox not launching

Yeah, this is caused by if Roblox is stuck running in the background. You've mentioned that Roblox doesn't launh even without Bloxstrap?

**Comment by pizzaboxer** [comment]
Yep, that's why the icons are stuck there. It's not really a bug, it's working fine as Roblox is still there in the background, just not doing anything.
