### ISSUE TITLE
[BUG] when i open it, it js closes gng

### ISSUE THREAD

**Issue by ilovenickers** [pizzaboxer/bloxstrap#943]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i open it, it js closes gng without even opening roblox or bloxstrap. like i cant even boot that ho

**Comment by pizzaboxer** [comment]
If your problem is with Roblox itself, [check to see if it happens without Bloxstrap](https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch). Please only open an issue if your problem only happens with Bloxstrap, as anything else is out of my control.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
