### ISSUE TITLE
add the option to disable automatic chat translation

### ISSUE THREAD

**Issue by Boi2021Miceoos** [pizzaboxer/bloxstrap#944]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

![Capture](https://github.com/pizzaboxer/bloxstrap/assets/86916029/803f93b0-2f93-4728-9718-6fdb1c2d87d2)
Yes yes i know, there is already a option to disable it but i want it to disable everytime roblox starts

**Comment by pizzaboxer** [comment]
`FFlagChatTranslationUIEnabled`, `FFlagUserIsChatTranslationEnabled2`, and `DFFlagEnableTCSChatTranslation` are three flags that you could try configuring by adding them in the FastFlag editor and setting their values to 'False'.

**Comment by Boi2021Miceoos** [comment]
Thanks
