### ISSUE TITLE
Crashing in the middle of playing ONLY in bloxstrap [BUG] 

### ISSUE THREAD

**Issue by Joshua079** [pizzaboxer/bloxstrap#945]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I've switched to regular roblox without bloxstrap and I get no crashes yet in bloxstrap I get a crash once every few minutes, to once every 30 minutes or so. I've reinstalled several times and even made extra sure with the voidtool "everything" that everything of "bloxstrap" was absolutely gone (besides prefetch) and it's still crashing at the interval described. I'm on the latest version of bloxstrap and roblox, and my computer specs are an intel 10700k, rtx 3070, 32 gigs of ram. No memory errors and I have nothing open that has known issues with Roblox and it's anticheat. I'm kind of desperate at this point for answers so I'm just going to post this in hopes something comes of it because I'd like to use bloxstrap without issues lol. 

Bloxstrap FastFlags: 
![image](https://github.com/pizzaboxer/bloxstrap/assets/107670738/08ab310a-c0ea-4db4-9dd8-cc314eea5908)
Everything else, 
![image](https://github.com/pizzaboxer/bloxstrap/assets/107670738/87e1cb38-cf87-475b-b27a-5f4e06336651)
![image](https://github.com/pizzaboxer/bloxstrap/assets/107670738/11538e6d-c909-4c85-9ab8-e2155bf3f6f2)
![image](https://github.com/pizzaboxer/bloxstrap/assets/107670738/252a82bd-ac75-4818-b70d-d066fd2d232b)
![image](https://github.com/pizzaboxer/bloxstrap/assets/107670738/e0a490d0-4c31-46af-b81c-67fbd7949334)
![image](https://github.com/pizzaboxer/bloxstrap/assets/107670738/6b493e45-dd48-44ff-9308-4d3db60b31d8)

**Comment by pizzaboxer** [comment]
For one, try setting your framerate limit to zero. For another, are there any mods that you've manually placed into your mods folder?

**Comment by Joshua079** [comment]
I will try setting the framerate limit to zero but I cannot guarantee this will be the issue as before this I was using rbxfpsunlocker (also open source on github) and I was never experiencing crashes then. I ofc don't use it anymore and it doesn't run when I'm using bloxstrap (Its not set to run on startup and it has no task scheduler task attached to it) so this can't be the issue. 

For the mods used, I have none and the only thing in the mods folder is your clientsettings folder and looking at what's in that it's all that should be expected, one file that I'll upload here for you to see, 
[ClientAppSettings.json](https://github.com/pizzaboxer/bloxstrap/files/13388969/ClientAppSettings.json)

I would upload log files for you right now but I'm unsure if log files are ok to upload here and I'm concerned of what may be in them and how detailed the logs are. If you request them I'll send them but without request I'll avoid sending them here publicly just in case.

**Comment by pizzaboxer** [comment]
> it has no task scheduler task attached to it

Sounds like you were using memory injection? Bloxstrap does it a different way.

**Comment by Joshua079** [comment]
Huh so just an update.... when I was talking about rbxfpsunlocker it was more of a useless mention of me saying I've used fps unlockers before and they never crash me but actually your suggestion worked.... I'm not crashing anymore strangely enough. Could be spoken too soon but probably not because I just finished two movies while multitasking. I played in a lobby that used to crash a lot within 15 minutes and I went quite a few hours without any crashes. Now I just question why I can't use Bloxstrap's fps limit setting thing 🤔 maybe you'd have an idea?

**Comment by pizzaboxer** [comment]
> Now I just question why I can't use Bloxstrap's fps setting thing 🤔 maybe you'd have an idea?

Nothing I can do. rbxfpsunlocker manually handles framerate unlocking whereas I configure a debug option to so Roblox itself handles it. Though, it's a debug option because it's not entirely stable for everyone (#816).

You'll simply just have to not use it if it's causing problems for you, or use rbxfpsunlocker when you can. Sorry.
