### ISSUE TITLE
Can't uninstall bloxstrap

### ISSUE THREAD

**Issue by AKAYFORTYSEVENS** [pizzaboxer/bloxstrap#946]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/82162755/9d34ae0a-99d3-4546-b9aa-370266934c87)

whenever I try to uninstall it, this pops up

**Comment by Dev1292** [comment]
Restart your Computer and Try to delete it from the files, Hope That helps!

**Comment by pizzaboxer** [comment]
> whenever I try to uninstall it, this pops up

Try reinstalling the .NET desktop runtime first. If you run the installer, it'll let you uninstall it. Afterwards, you can run it again to reinstall it. Then the error message should be fixed.

**Comment by AKAYFORTYSEVENS** [comment]
Still won't let me uninstall it

**Comment by pizzaboxer** [comment]
Are you seeing the same message?

**Comment by AKAYFORTYSEVENS** [comment]
yup

**Comment by pizzaboxer** [comment]
If you want to uninstall it manually, delete the folder at `%localappdata%\Bloxstrap`, and then open the Registry Editor and delete these two keys:
- `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap`
- `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap`

**Comment by AKAYFORTYSEVENS** [comment]
Thanks for the help it worked
