### ISSUE TITLE
[BUG] Graphics bug?

### ISSUE THREAD

**Issue by Neissprro73** [pizzaboxer/bloxstrap#948]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Since I installed Bloxstrap I have had some problems with the graphic quality, I don't know if it is due to the configuration or if I should add or modify something, when I enter a game the sky looks grayish yellow, some vital meshes do not load well and it seems as if I were playing a bugged and polygonal game (the game is Wings of Glory). Help me improve the loading quality or if I have to modify something I will do so. Thank you (ignore the bad stats i learned with this)
![imagen_2023-11-18_004133486](https://github.com/pizzaboxer/bloxstrap/assets/151330004/efe9fe23-b08b-4981-a001-13ee621e11fa)

**Comment by pizzaboxer** [comment]
Mind if I see the list of flags you have configured in the FastFlag editor?

**Comment by ShadowCodeX-debug** [comment]
@Neissprro73 Your probably have FastFlags named

`DFIntCSGLevelOfDetailSwitchingDistance`
(This is probably the polygon problem you described. There are probably multiple of them.)

`FFlagDebugSkyGray`
(This is probably the gray sky problem you described.)

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
