### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by relasdas** [pizzaboxer/bloxstrap#949]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

pls help me as it keeps saying System.Exception: Signature does not match! while donwloading
[Bloxstrap_20231118T104818Z.log](https://github.com/pizzaboxer/bloxstrap/files/13400062/Bloxstrap_20231118T104818Z.log)

**Comment by pizzaboxer** [comment]
The preliminary instructions told you to read the Wiki. Read it next time. https://github.com/pizzaboxer/bloxstrap/wiki/%22Signature-does-not-match!%22-error-when-launching-Roblox
