### ISSUE TITLE
Idea: Custom launcher title bar

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#95]
It would be really cool if when you launch a Roblox game, instead of it saying Bloxstrap while using the Fluent design, it would be nice for there to be an option to change the tile bar to "Roblox" for example, or some custom text that you wanna have as your title.

**Comment by pizzaboxer** [comment]
I wanted the launcher to always at least keep some Bloxstrap branding, but I guess the status text shows it occasionally anyway. Sure, I can add this. Seems like a great complement to #94.

**Comment by idkthegithub** [comment]
Thanks!
