### ISSUE TITLE
Does roblox vc work the same on bloxstrap?

### ISSUE THREAD

**Issue by ThatOneDude447343534543** [pizzaboxer/bloxstrap#952]
I feel like bloxstrap doesnt work the same with roblox vc, can someone confirm that it works the same as the actual roblox?

**Comment by RyanLua** [comment]
I believe that Bloxstrap shouldn't change anything related to Roblox voice chat as it's just a launcher unless you have some specific flags/settings changing the behavior.

**Comment by pizzaboxer** [comment]
> I feel like bloxstrap doesnt work the same with roblox vc, can someone confirm that it works the same as the actual roblox?

It should. Why don't you just try it yourself?
