### ISSUE TITLE
[BUG] my pc crashes when i use bloxstrap

### ISSUE THREAD

**Issue by chellnuke** [pizzaboxer/bloxstrap#953]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

my pc crashes when i use bloxstrap

**Comment by pizzaboxer** [comment]
Your PC crashes? Can you elaborate please? What specifically happens? What do you see, or what doesn't work properly?

**Comment by chellnuke** [comment]
> Your PC crashes? Can you elaborate please? What specifically happens? What do you see, or what doesn't work properly?

like my screen gets dark and yea it just crashes. (it does when i like open another window. but iam not sure

**Comment by pizzaboxer** [comment]
When specifically does it happen? When Roblox opens?

**Comment by chellnuke** [comment]
> When specifically does it happen? When Roblox opens?

Like after 1-2 min after i join to server. Forgot to say that it crashes when i set hz to 144(maybe im not sure but it crashes)

**Comment by pizzaboxer** [comment]
> maybe im not sure

If that's your suspicion then you can try setting your framerate limit to zero in the Bloxstrap menu which will re-lock it to 60, see if it still crashes then.

**Comment by chellnuke** [comment]
> > maybe im not sure
> 
> If that's your suspicion then you can try setting your framerate limit to zero in the Bloxstrap menu which will re-lock it to 60, see if it still crashes then.

Ok

**Comment by chellnuke** [comment]
> > maybe im not sure
> 
> If that's your suspicion then you can try setting your framerate limit to zero in the Bloxstrap menu which will re-lock it to 60, see if it still crashes then.
I checked it. It crashes anyways. So i was wrong

**Comment by chellnuke** [comment]
> > maybe im not sure
> 
> If that's your suspicion then you can try setting your framerate limit to zero in the Bloxstrap menu which will re-lock it to 60, see if it still crashes then.

Yo i checked it. It crashes. So i was wrong. What should I do

**Comment by pizzaboxer** [comment]
Since you mentioned that it happens after you join a game, can you try playing without Bloxstrap, see if the same thing happens? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
