### ISSUE TITLE
bloxstrap is launched but dosen't operate with roblox[BUG] 

### ISSUE THREAD

**Issue by Matijal123** [pizzaboxer/bloxstrap#954]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i try to launch roblox with bloxstrap it dosen't load any changes to roblox
![image](https://github.com/pizzaboxer/bloxstrap/assets/125040182/b2237b31-efc6-4342-828b-02805d48590a)
like here, i turn on my alternative slider but it dosen't add that option

**Comment by Matijal123** [comment]
CAN ANYONE HELP
😥😥😥

**Comment by pizzaboxer** [comment]
For one, do you see the Bloxstrap launcher before Roblox opens? For another, make sure Roblox isn't running in Task manager first before you launch it, since it probably thinks Roblox is already running which will skip mod application.

**Comment by Matijal123** [comment]
1. no
2. it wasn't running

**Comment by pizzaboxer** [comment]
Launch Roblox using the "Play Roblox" shortcut that's located in the Start menu. https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

You should only have to do this once.

**Comment by Matijal123** [comment]
it didn't work

**Comment by pizzaboxer** [comment]
> it didn't work + i used this shortcut multiple times

You said that you don't see the Bloxstrap launcher before Roblox opens though. When you launch it with that shortcut, do you see it?

**Comment by Matijal123** [comment]
CASE CLOSED
all i had to do is restart the computer
