### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (Checksum of RobloxPlayerBeta.exe post-extraction did not match manifest

### ISSUE THREAD

**Issue by 5h1b** [pizzaboxer/bloxstrap#955]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Inner Exception]
Bloxstrap.Exceptions.AssertionException: Checksum of RobloxPlayerBeta.exe post-extraction did not match manifest

[Bloxstrap_20231119T155816Z.log](https://github.com/pizzaboxer/bloxstrap/files/13403742/Bloxstrap_20231119T155816Z.log)

I don't know why it is happening, but i can't play Roblox.

**Comment by pizzaboxer** [comment]
This sounds like a one-off error. Does it happen whenever you try to launch?

**Comment by 5h1b** [comment]
yes

**Comment by pizzaboxer** [comment]
Try deleting all the files located in `%localappdata%\Bloxstrap\Downloads` first, then launch Robloz.

**Comment by 5h1b** [comment]
still getting the same thing

**Comment by 5h1b** [comment]
BTW normal Roblox seems to launch ok

**Comment by pizzaboxer** [comment]
If you go to the `%localappdata%\Bloxstrap\Versions\version-72b95a99cfcf4b7d` folder, you should see a file named RobloxPlayerBeta.exe. Can you send that file here please?

**Comment by 5h1b** [comment]
github don't seem to let me


We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

**Comment by pizzaboxer** [comment]
Upload it somewhere else and send a link to it here.

**Comment by 5h1b** [comment]
https://drive.google.com/file/d/1JEVp46t2vasJYmqUVPVyYgUbj37hIO2V/view?usp=sharing

**Comment by pizzaboxer** [comment]
One last thing, in the `%localappdata%\Bloxstrap\Downloads` folder, there should be a file named `f4e3bbb16912e6ca6c62104515102696`. Can you also send that to me please?

**Comment by 5h1b** [comment]
https://drive.google.com/file/d/1bu8azjcvNXbvlQ9tqYqjL6unapLbhdqG/view?usp=sharing

**Comment by pizzaboxer** [comment]
This is strange, I can only really assume this to be a problem with .NET. What version of the runtime do you have installed? Open a Command Prompt window, run `dotnet --info`, show the output of it here?

**Comment by 5h1b** [comment]
global.json file:
  Not found

Host:
  Version:      6.0.24
  Architecture: x64
  Commit:       e7b8488daf

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by pizzaboxer** [comment]
Can you try uninstalling the one for 6.0.24 (search Windows Desktop Runtime in Add or remove programs), and then [install 6.0.25](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.25-windows-x64-installer?cid=getdotnetcore)?

**Comment by 5h1b** [comment]
okay did that now what

**Comment by pizzaboxer** [comment]
Then try and launch, see if you get the same thing.

**Comment by 5h1b** [comment]
here is the dotnet --info as proof
and i run bloxstrap and still getting the same error
global.json file:
  Not found

Host:
  Version:      6.0.25
  Architecture: x64
  Commit:       492abbeef0

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by 5h1b** [comment]
still same error

**Comment by 5h1b** [comment]
you still there?

**Comment by 5h1b** [comment]
@pizzaboxer

**Comment by pizzaboxer** [comment]
I'll be honest, I have no idea what could be causing this, since everything should be perfectly fine. It's just that for some reason .NET is screwing up zip extraction, which is completely out of my control. In the next version we're reworking it so it doesn't rely on .NET since I know it sucks, but that's the next version, and unfortunately I can't say that'll be coming soon.

Random thing I'm just throwing out there, have you tried restarting your PC?/

**Comment by bluepilledgreat** [comment]
No response for 3 months

**Comment by pizzaboxer** [comment]
Kept this open because of the 'needs investigation' label, but this is expected to be fixed sometime in the future when we move to a different zip processing library.
