### ISSUE TITLE
Can't install or open it[BUG] 

### ISSUE THREAD

**Issue by 000o000accheretoo** [pizzaboxer/bloxstrap#956]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Since I've downloaded bloxstrap, it worked for like a month then it started to crash and normal roblox too, if I use another windows acc it works, but it's annoying to switch between windows accounts

**Comment by pizzaboxer** [comment]
> if I use another windows acc it works, but it's annoying to switch between windows accounts

You've been flagged by Hyperion. You've already said that this happens with normal Roblox too. Not my problem.
