### ISSUE TITLE
*Bloxstrap doesnt open*

### ISSUE THREAD

**Issue by bjgdavid** [pizzaboxer/bloxstrap#957]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Bloxstrap itself doesnt work doesnt show up or anything it doesnt work on google or microsoft roblox when i deleted it roblox still didnt work, also deleted the windows desktop runtime still didnt work, redownloaded roblox still didnt work, restarted pc still didnt work. Thanks! Now i cant play anymore

**Comment by pizzaboxer** [comment]
> it doesnt work on google or microsoft roblox when i deleted it roblox still didnt work

So it's a problem with Roblox itself then. As per the preliminary instructions that you read before opening this, have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

**Comment by bjgdavid** [comment]
> > it doesnt work on google or microsoft roblox when i deleted it roblox still didnt work
> 
> So it's a problem with Roblox itself then, which is entirely out of my control. Have you read through https://github.com/pizzaboxer/bloxstrap/wiki/Roblox-crashes-or-does-not-launch?

Yes i read through it i tried the roblox player and it works, but sometimes it doesnt there but it still doesnt work on google

**Comment by pizzaboxer** [comment]
> i tried the roblox player and it works, but sometimes it doesnt there

How often does that happen?

> but it still doesnt work on google

When you launch from your browser, do you see the Bloxstrap launcher, or do you just see nothing at all?

**Comment by dran1x** [comment]
I'm opening from the website and the desktop launcher, both crash shortly after opening.
![image](https://github.com/pizzaboxer/bloxstrap/assets/48390633/2ebe755c-a968-4334-bf7b-cb2f04cb541c)

**Comment by bjgdavid** [comment]
> > i tried the roblox player and it works, but sometimes it doesnt there
> 
> How often does that happen?
> 
> > but it still doesnt work on google
> 
> When you launch from your browser, do you see the Bloxstrap launcher, or do you just see nothing at all?

i see bloxtrap for a second it dissapears and nothing happens

**Comment by pizzaboxer** [comment]
> bloxtrap opens for a second it dissapears and nothing happens

How often does it actually work without Bloxstrap though? I'm asking because I'm just not entirely seeing the correlation here, especially when you've said that this always happens whenever you launch from the website with stock Roblox.

**Comment by IngravedSoul** [comment]
the same thing happens to me it works on it's own but when i install bloxstrap it just does nothing

**Comment by bjgdavid** [comment]
> > bloxtrap opens for a second it dissapears and nothing happens
> 
> How often does it actually work without Bloxstrap though? I'm asking because I'm just not entirely seeing the correlation here, especially when you've said that this always happens whenever you launch from the website with stock Roblox.

for google it doesnt work at all but for roblox player it opens everytime now
