### ISSUE TITLE
[BUG] takes too long to load but it doesnt on normal roblox

### ISSUE THREAD

**Issue by randomstuff69** [pizzaboxer/bloxstrap#958]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

when i launch roblox it takes long to load into the game but doesnt do it in normal roblox and its annoying

**Comment by pizzaboxer** [comment]
> when i launch roblox it takes long to load into the game

What part does it get stuck on? What do you see?

**Comment by randomstuff69** [comment]
it gets stuck on "connecting to roblox" but i can still get into the game

**Comment by pizzaboxer** [comment]
Oh, I know why that's happening. It's a bug where connectivity checking is performed extremely inefficiently when the first check fails (because it can't contact setup.rbxcdn.com). That's an issue we have fixed in the next upcoming version. I wouldn't expect for it to be happening all the time though. Has this always been happening since you first installed it?

**Comment by randomstuff69** [comment]
yes

**Comment by pizzaboxer** [comment]
If you don't mind, send me Bloxstrap's latest log file from `%localappdata%\Bloxstrap\Logs` - latest should be right at the top.

**Comment by randomstuff69** [comment]
[Bloxstrap_20231120T002621Z.log](https://github.com/pizzaboxer/bloxstrap/files/13405135/Bloxstrap_20231120T002621Z.log)

**Comment by pizzaboxer** [comment]
Yep, you're encountering the bug. And it happens because for some reason you're failing to connect to both https://setup.rbxcdn.com and https://setup-ak.rbxcdn.com. What happens if you try to access them in your browser?

**Comment by randomstuff69** [comment]
it does do access denied

**Comment by pizzaboxer** [comment]
Hm, I'm wondering why they're timing out. What if you open a Command Prompt window and then run this:
`curl https://setup.rbxcdn.com/version`
You should get instantly back a version ID.

**Comment by randomstuff69** [comment]
the id is version-6552be68b05d41a5

**Comment by pizzaboxer** [comment]
Okay, I'm not getting anywhere with this. Though, try out this custom build I just made which prioritizes the mirrors that should work for you. https://files.pizzaboxer.xyz/bloxstrap-debug/958/Bloxstrap.exe

**Comment by pizzaboxer** [comment]
For anyone else recently coming across this issue:

![image](https://github.com/pizzaboxer/bloxstrap/assets/41478239/ce5bda63-bf83-4dda-b848-b0bd1f5b2934)
