### ISSUE TITLE
[BUG] Not appearing the rendering mode option on fastflags

### ISSUE THREAD

**Issue by Lonlks** [pizzaboxer/bloxstrap#959]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Wanted to change the rendering mode but it just disappeared, i cant find it, did it got removed or something?

**Comment by Lonlks** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/151569803/df068dbc-3be2-4c39-9b6f-e2e9e23fe032)
this is what i see

**Comment by ShadowCodeX-debug** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4

**Comment by Lonlks** [comment]
oh, thanks
