### ISSUE TITLE
Bug or not? Progress bar error.

### ISSUE THREAD

**Issue by idkthegithub** [pizzaboxer/bloxstrap#96]
Something thats kinda weird is that when the loading bar is shown, the rounded corners become squared? Heres some screenshots.
![unte](https://user-images.githubusercontent.com/59868100/219948328-3b063d38-789a-41c3-b2b0-a7c6f10fcc33.png)
![the](https://user-images.githubusercontent.com/59868100/219948341-1d1433ef-a07e-4265-a4f2-27fc1900f33b.png)
This is how it looks when its not filled.
![lol](https://user-images.githubusercontent.com/59868100/219948353-a612a819-4308-40ef-ab81-83db61453263.png)
Is this a bug or not? I really like the Fluent design, so i would like this to be fixed if its a bug.

**Comment by pizzaboxer** [comment]
Yeah, I've noticed that. Unfortunately, it's not exactly something in my control: see lepoco/wpfui#319.
At some point I might fork the UI library to try and fix the issues with it, but I definitely don't have time for that right now.

**Comment by idkthegithub** [comment]
Thanks for letting me know!

**Comment by bluepilledgreat** [comment]
This has been fixed
