### ISSUE TITLE
[BUG] Can't use 2015 UI

### ISSUE THREAD

**Issue by kotencja3** [pizzaboxer/bloxstrap#960]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![image](https://github.com/pizzaboxer/bloxstrap/assets/138238775/826ef67e-7f26-49d0-a69a-93be825445b2) the top bar stuff is changed too

**Comment by GoingCrazyDude** [comment]
Having the same issue, but with the added side effect of there being 2 beta badges for some reason.

**Comment by pizzaboxer** [comment]
Does adding `{"FFlagEnableInGameMenuChromeABTest": "False"}` to your FastFlag list fix it?

**Comment by kotencja3** [comment]
> Does adding `{"FFlagEnableInGameMenuChromeABTest": "False"}` to your FastFlag list fix it?

Yes it works 
![image](https://github.com/pizzaboxer/bloxstrap/assets/138238775/bb5e6917-b2c9-4e3c-ad2e-b64afb2e45fe)

**Comment by kotencja3** [comment]
It's solved then

**Comment by pizzaboxer** [comment]
Keeping as open until I release an update that fixes this.

**Comment by welcometogithub23** [comment]
> {"FFlagEnableInGameMenuChromeABTest": "False"}

huh its not working

**Comment by pizzaboxer** [comment]
> huh its not working

Can I see how you added it?

**Comment by pooperscooper20243** [comment]
same with welcometogithub23, it doesn't work. i went in the fastflag menu and i pressed the editor then i pressed add new then i named it "ui bug fixer" then put {"FFlagEnableInGameMenuChromeABTest": "False"} in its value. did i do it wrong?

**Comment by pizzaboxer** [comment]
> did i do it wrong?

Yes you did. Import it as JSON. It's a JSON string.

**Comment by pooperscooper20243** [comment]
oh

**Comment by Luximoz** [comment]
The "FFlagEnableInGameMenuChromeABTest" FFlag no longer works, so you can no longer go back to the previous CoreGUI that was thousands of times better :/

**Comment by pizzaboxer** [comment]
Yep, it's gone. I'm having serious doubt about whether there's even another way to disable it.

**Comment by bluepilledgreat** [comment]
closed because of recent updates
