### ISSUE TITLE
anyway to increase fps

### ISSUE THREAD

**Issue by ThatOneDude447343534543** [pizzaboxer/bloxstrap#961]
Is there any way to increase my fps on bloxstrap? the other renders got removed so, and im on a low end computer too.

**Comment by ShadowCodeX-debug** [comment]
Try asking this in the discord server, or in the RBXFlags Discord (I recommend this one if you're going to ask about flags.)

**Comment by pizzaboxer** [comment]
Most I can really do is suggest you to use Voxel lighting. We'll be adding (or re-adding) a bunch of options in the future which aim to help with this too.
