### ISSUE TITLE
[BUG] I cant open the shift lock after turn off then turn on it back

### ISSUE THREAD

**Issue by djnotnoob** [pizzaboxer/bloxstrap#962]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

this bug randomly happen when i turn off then turn it on back,i try press shift and the shiftlock not work(just a reminded i press right shift also and not work too)

**Comment by pizzaboxer** [comment]
Does this happen all the time? What about without Bloxstrap? https://github.com/pizzaboxer/bloxstrap/wiki/Switching-between-Roblox-and-Bloxstrap

**Comment by BokBoy** [comment]
In the game you are playing, are you sure that it isn't control? Some games (such as Bedwars) rebind their shiftlock key so that the shift key can be used for something else such as sprint.
Try another game, one that isn't well developed such as a cart game and see if it works there.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
