### ISSUE TITLE
[REQ]  (2015-2020) Old Top Bar UI?

### ISSUE THREAD

**Issue by kotencja3** [pizzaboxer/bloxstrap#963]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Couldn't find a request for this
![image](https://github.com/pizzaboxer/bloxstrap/assets/138238775/6dda4f5b-d259-40ee-8132-60a77504ef2a)

**Comment by pizzaboxer** [comment]
Not possible, sorry.
