### ISSUE TITLE
[BUG] Enabling the ability to hide GUIs and changing the group ID sets the toggle to off

### ISSUE THREAD

**Issue by B00ie23** [pizzaboxer/bloxstrap#964]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Normally when changing the group ID to anything other than Bloxstrap's group ID, the toggle would still be shown as on.

However, in a past update (v2.5.1 flying blind,) changing the group ID from that point on would always set the toggle back to off regardless of whether there was an ID present or not.

Despite the toggle being shown as off, you are still granted the ability to hide GUIs for as long as the flag is saved.

**Comment by pizzaboxer** [comment]
Oh, I forgot about this. I'm aware of this, I just forget to actually put this down as something that needs doing whenever I work on a version. I won't forget this time, hopefully.

**Comment by bluepilledgreat** [comment]
closed because of recent updates
