### ISSUE TITLE
[BUG] new roblox ui glitched the ui setting and no longer uses the ui u choose

### ISSUE THREAD

**Issue by welcometogithub23** [pizzaboxer/bloxstrap#965]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

new roblox ui glitched the ui setting and no longer uses the ui u choose

**Comment by pizzaboxer** [comment]
Duplicate of #960
