### ISSUE TITLE
[BUG] for some reason when im playing, the features that i enabled weren't there.

### ISSUE THREAD

**Issue by pooperscooper20243** [pizzaboxer/bloxstrap#966]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?
i installed it how i should've, but the settings just aren't working.
a image of the cursor setting enabled:
![fhgvcd](https://github.com/pizzaboxer/bloxstrap/assets/151673234/775cbf06-39fa-44ff-a259-d76baa4b85d5)
a image of the menu setting enabled:
![kjvrg](https://github.com/pizzaboxer/bloxstrap/assets/151673234/ba4e090d-2ece-4db3-9bc6-17bc1b08c53e)
how they look ingame: (i couldn't get a pic of the cursor)
![bngh](https://github.com/pizzaboxer/bloxstrap/assets/151673234/79479a21-533a-4f1b-a83a-4196019ac98a)
also the oof thing doesn't work.

**Comment by TheMetalTechnet** [comment]
It seems that you launched Roblox without bloxstrap. Try running "Play Roblox"

**Comment by pooperscooper20243** [comment]
well, i've done that already but it still didn't work.

**Comment by pizzaboxer** [comment]
> @TheMetalTechnet well, i've done that already but it still didn't work.

Roblox is likely running in the background when you launch, which will skip the mod check. Make sure it's not running first in Task Manager and then launch.

**Comment by pooperscooper20243** [comment]
> > @TheMetalTechnet well, i've done that already but it still didn't work.
> 
> Roblox is likely running in the background when you launch, which will skip the mod check. Make sure it's not running first in Task Manager and then launch.

alright, next time ill try that.
