### ISSUE TITLE
[REQ] Please add more optimisations for low end pc users

### ISSUE THREAD

**Issue by MasterZombieYT** [pizzaboxer/bloxstrap#967]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

please add much more fast flags or things to boost fps for low end pc users
im a user of a laptop that uses only 1.7ghz and so slow and has a very old gpu and cpu and im always trynna enjoy roblox but no matter what i always try and try and keep getting :
---
AVG of 10-7 fps in "Slap Battles"&"Pet Simulator X"
AVG of 6-13 fps in "Arsenal"&"Murder Mystery"
AVG of 11-14 fps in "Ability Wars"&"Hours"
AVG of 5-9 fps in "EVADE"&"Blox Fruits"
---

and i cant afford a new laptop or something and i really want to feel good once in my life and get a bit of fps
i would really like 25-30 fps i bet its gonna be *AMAZING!* so yeah.. please add more optimisations and fps boost things into the game i've tried EVERYTHING and i mean EVERYTHING i could..

---
-Thank you
---

**Comment by TheMetalTechnet** [comment]
Bloxstrap is just a bootstrap, so it cannot modify game clients code (other wise Hyperion would block it), but you can take a look at FastFlags channel on discord, there is a list of FFlags that might optimise the game a little bit

**Comment by pizzaboxer** [comment]
We're already planning to add a bunch of options in the next version that can help to improve performance on low end hardware. Though, thank you for letting us know that you'd like for this to happen.
