### ISSUE TITLE
[BUG] Bloxstrap Download Error

### ISSUE THREAD

**Issue by ArtiOva** [pizzaboxer/bloxstrap#968]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Bloxstrap_20231122T013939Z.log](https://github.com/pizzaboxer/bloxstrap/files/13432628/Bloxstrap_20231122T013939Z.log)
![image](https://github.com/pizzaboxer/bloxstrap/assets/151697641/ca4ae1ff-f8b0-4ee1-a64e-12373dc0665d)

**Comment by pizzaboxer** [comment]
Manually delete the folder at `%localappdata%\Bloxstrap` before reinstalling.
