### ISSUE TITLE
Windows Security False Positive Behavior:Win32/DefenseEvasion.A!ml

### ISSUE THREAD

**Issue by Ultrasonic1209** [pizzaboxer/bloxstrap#97]
Hi, Windows Security has just tried to quarantine Bloxstrap for some reason.
I realise there may not be much you can do but I thought I should let you know regardless.

![image](https://user-images.githubusercontent.com/44583181/220432466-23d73161-d997-400a-a2f8-8268fd278138.png)

**Comment by pizzaboxer** [comment]
Yeah, I already know about it. Tried to send it for analysis, says it's clean. I don't even know.
