### ISSUE TITLE
[BUG] Some cursors don't show up while using the 2013 or 2006 cursors.

### ISSUE THREAD

**Issue by Pipnormal** [pizzaboxer/bloxstrap#970]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

While I use one of these 2 cursors, some don't show up like the rocket launcher crosshair.

**Comment by pizzaboxer** [comment]
Works fine for me. Does it work if you use the default cursor? Also, just to confirm, we're talking about the classic brickbattle rocket launcher used in games like Crossroads, right?

**Comment by Pipnormal** [comment]
Yes, I just tested it and it works just fine now. Maybe it was my gpu's fault before.
