### ISSUE TITLE
[BUG] I can't uninstall the bloxtrap in control panel

### ISSUE THREAD

**Issue by Savica1** [pizzaboxer/bloxstrap#971]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I cant uninstall it in control panel, i tried every single way, ive installed .NET 6.0.25 X64 but it still dosent let me uninstall it, here is an image of how it looks like when i try to uninstall it.
![huhhhh](https://github.com/pizzaboxer/bloxstrap/assets/151779909/bc7e105c-5e4e-49aa-8703-efaf35828d89)

**Comment by pizzaboxer** [comment]
Did you uninstall it at some point? You wouldn't have been able to install it without it.

Anyway, follow the instructions for manual installation [detailed here](https://github.com/pizzaboxer/bloxstrap/issues/946#issuecomment-1820407641).
