### ISSUE TITLE
[REQ] FFlag preset to enable latest (rounded) in-game menu bar

### ISSUE THREAD

**Issue by carter0nline** [pizzaboxer/bloxstrap#973]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

This is the latest menu shown in #960.
![image](https://github.com/pizzaboxer/bloxstrap/assets/83525455/0c3dacd1-8367-4fb6-ab45-5002e0a852f4)
It seems to be in A/B testing now, but can be manually enabled with the following FastFlags, which I found in [this DevForum post](https://devforum.roblox.com/t/how-to-get-the-newest-roblox-menu-ui/2573086):

```json
"FStringInGameMenuChromeForcedUserIds": "UserId",
"FStringInGameMenuModernizationForcedUserIds": "UserId",
"FFlagEnableV3MenuABTest": true,
"FFlagEnableV3MenuABTest2": true,
"FFlagEnableInGameMenuV3": true
```

Of course, with this, there will need to be a way for Bloxstrap to know the player's UserId. Also, the wording of "UserId**s**" makes me think multiple could be put in, if someone uses multiple accounts, but I also don't really know how JSON works, and haven't tested this

**Comment by pizzaboxer** [comment]
> Of course, with this, there will need to be a way for Bloxstrap to know the player's UserId. 

Literally all you need is the one flag of `FFlagEnableInGameMenuChrome`. In fact, it's the one flag that I demo the use of [in the showcase screenshots](https://github.com/pizzaboxer/bloxstrap#screenshots).

**Comment by carter0nline** [comment]
Oh, okay

**Comment by github-production-user-asset** [comment]
maybe also include the pinned chat fflag for this

**Comment by bluepilledgreat** [comment]
closed because of recent updates
