### ISSUE TITLE
yooo [BUG] 

### ISSUE THREAD

**Issue by ilovenickers** [pizzaboxer/bloxstrap#976]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

System.UnauthorizedAccessException: Access to the path 'C:\Users\sorry\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

what do i do??

**Comment by pizzaboxer** [comment]
Manually delete the folder at `%localappdata%\Bloxstrap` before you reinstall.
