### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sattrsd** [pizzaboxer/bloxstrap#977]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

application error
![Capture](https://github.com/pizzaboxer/bloxstrap/assets/151924400/f9afd3ec-b362-4873-a7c0-fc7398584d5a)

**Comment by BokBoy** [comment]
Please do some research before coming here.
However, run the .net framework repair tool,
https://www.microsoft.com/en-gb/download/details.aspx?id=30135
If it comes with an error, try uninstalling and reinstalling.

**Comment by pizzaboxer** [comment]
Try reinstalling the [.NET desktop runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.25-windows-x64-installer?cid=getdotnetcore).

**Comment by BokBoy** [comment]
> > how off topic?? literally saying reinstall .net
> 
> 
> 
> That's the wrong tool for something completely different.

That's what Microsoft said however ig u know more than me.

**Comment by pizzaboxer** [comment]
> That's what Microsoft said however ig u know more than me.

.NET Framework and .NET Core (what Bloxstrap uses) are two completely different things.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
