### ISSUE TITLE
Graphics Optimiser?? [REQ] 

### ISSUE THREAD

**Issue by BokBoy** [pizzaboxer/bloxstrap#978]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Hey Pizzaboxer, its me again...
My issue with FPS didn't turn out well and something in roblox keeps doing it so I gave up.
Anyways, Does bloxstrap have an inbuilt graphics optimiser?? Like how Minecraft has optifine and things like that, does bloxstrap have one?? I'm thinking about low end pcs and how much faster they could get.
Thanks.
Also, it says dont ask support for linux or mac, would compiling bloxstrap from source make it work?? This is not the main issue, ill try it by myself later.

**Comment by pizzaboxer** [comment]
> Does bloxstrap have an inbuilt graphics optimiser

No.

> would compiling bloxstrap from source make it work?

No, because it doesn't support those platforms.

In the next version, we already have plans for adding additional options for manually controlling graphics settings, which could then be used for graphics optimization. So, we have this in the works. Don't worry.

**Comment by BokBoy** [comment]
Got it thx
