### ISSUE TITLE
Ability to enable proper fullscreen

### ISSUE THREAD

**Issue by he3als** [pizzaboxer/bloxstrap#98]
You can enable proper fullscreen when pressing `Alt` + `Enter` by setting the `FFlagHandleAltEnterFullscreenManually` flag to false, which greatly improves input latency, smoothness and the FPS of your game.

I explained why in my guide for it here: https://rentry.co/roblox-performance

It would also be nice to have a toggle for disabling Windows 10/11's 'Fullscreen Optimisations' feature for even better latency, which is done using a compatibility option, which is stored in the Windows Registry.

**Comment by pizzaboxer** [comment]
Yeah sure, I could add this. I could also add a bunch of other FFlag presets too if necessary.

**Comment by he3als** [comment]
As a note, here's what the registry looks like for disabling Fullscreen Optimisations:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Users\\he3als\\AppData\\Local\\Bloxstrap\\Versions\\version-8c3e105625324213\\RobloxPlayerBeta.exe"="~ DISABLEDXMAXIMIZEDWINDOWEDMODE"

```

**Comment by pizzaboxer** [comment]
Thanks, this'll be useful.

**Comment by he3als** [comment]
> Yeah sure, I could add this. I could also add a bunch of other FFlag presets too if necessary.

Could be nice to add a graphics API selector as well (in case people want to test the FPS difference). You can select Vulkan, DirectX 11 and OpenGL.

**Comment by pizzaboxer** [comment]
Oh, that's definitely an interesting idea, I'll definitely consider it.
