### ISSUE TITLE
[BUG] Escape menu bug

### ISSUE THREAD

**Issue by TGBPass** [pizzaboxer/bloxstrap#980]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I can reset my character in game BUT that game cant reset your character. Please fix this thanks

**Comment by pizzaboxer** [comment]
What?

**Comment by dexter-xyz** [comment]
can you link to the game you've been playing? you probably joined a game/server that rejects character resets

**Comment by BokBoy** [comment]
Thats not a Bloxstrap problem, thats the game's problem. 
Some games restrict usage of certain buttons, reset being one of them. 
If it is grayed out or you cannot click it, it means that the creator of the game disabled it. Try another game, such as driving empire that does have it enabled.

**Comment by pizzaboxer** [comment]
Issue has been awaiting clarification for over a month, closing as stale. If you have anything further to add, just respond and I'll reopen.
