### ISSUE TITLE
[REQ] When inserting a flag add FFlag to the start of it if no valid flag type is at the start of the flag

### ISSUE THREAD

**Issue by EasternBloxxer** [pizzaboxer/bloxstrap#981]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

This would be useful when pasting flags from the CoreScripts as often times those aren't there.

**Comment by pizzaboxer** [comment]
i won't do this because this can very easily just not work as intended but i already have other plans for overhauling the ux for adding flags, including actually validating flag names/values
