### ISSUE TITLE
[BUG] the features that i putted in my game doesn't work

### ISSUE THREAD

**Issue by Everyonechil** [pizzaboxer/bloxstrap#982]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

![Web capture_25-11-2023_22457_discord com](https://github.com/pizzaboxer/bloxstrap/assets/152011984/de8b0a0e-1309-4d0c-ba0a-48105206b664)
i did press save
![image](https://github.com/pizzaboxer/bloxstrap/assets/152011984/1f564494-6382-4567-96b2-ef7165663e4c)
![image](https://github.com/pizzaboxer/bloxstrap/assets/152011984/3b860448-5a09-4f29-862c-9f8106f80547)
not working

**Comment by Everyonechil** [comment]
and i started from 
![image](https://github.com/pizzaboxer/bloxstrap/assets/152011984/b866da36-372c-42b4-8699-26f50aade30f)

**Comment by pizzaboxer** [comment]
Check to make sure that Roblox isn't running in the background (with task manager) first before launching.
