### ISSUE TITLE
[BUG] The features I added are not in the game. I opened via play roblox and made sure it wasnt running in the backround.

### ISSUE THREAD

**Issue by shamrockzz** [pizzaboxer/bloxstrap#984]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I added the 2008 cursor and saved it and when i joined the game i did not have it. Same for the old avatar editor. But when i am luanching Roblox via play roblox, i have the custom logo.

**Comment by shamrockzz** [comment]
> Roblox is already running in the background, which is skipping the mod application check. Ensure Roblox is not running in Task Manager first, then launch Roblox.

I checked and roblox is not running in the backround at all.

**Comment by pizzaboxer** [comment]
Send Bloxstrap's latest log file here. You can find it in `%localappdata%\Bloxstrap\Logs`. The newest log should be right at the top.

**Comment by shamrockzz** [comment]
i just got on today and i dident change anything and it is working now. Thanks for this awsome mod!
