### ISSUE TITLE
[REQ] Hey pizzaboxer, i wonder where the feature is where you can choose vulkan direct etc.

### ISSUE THREAD

**Issue by SomeoneWithBadFPS803** [pizzaboxer/bloxstrap#985]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

the option between direct vulkan etc. isnt there,it should be there but it isnt, why?
![Screenshot 2023-11-26 190307](https://github.com/pizzaboxer/bloxstrap/assets/150060083/1f547410-a587-4c85-b7e4-79c3c5a29bd1)

**Comment by FooqX** [comment]
![image](https://github.com/pizzaboxer/bloxstrap/assets/65967000/ec613e11-7c9d-4631-985a-f563c77a3f5c)

**Comment by pizzaboxer** [comment]
[Read the release notes for the latest version.](https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4)
