### ISSUE TITLE
(question) how do I translate? 

### ISSUE THREAD

**Issue by user1126s** [pizzaboxer/bloxstrap#987]
I'm new to translation stuff, how can I add translation for Hindi and Punjabi?

**Comment by break-core** [comment]
I suggest not doing translation stuff yet. pizzaboxer stated that [translation support is not finalized](https://discord.com/channels/1099468797410283540/1105150081482629130/1176934764456980673).

If you wanted to do it (for practice), then you need to get a copy of [Strings.resx](https://github.com/pizzaboxer/bloxstrap/blob/main/Bloxstrap/Resources/Strings.resx) and modify the file name on your device to be "Strings.[language-COUNTRY].resx". (example: "Strings.en-US.resx")

For Hindi, I believe the code is "hi-IN" (Hindi India) but there's also "hi-PK" (Hindi Pakistan).
For Punjabi, I think the code is "pa-IN" (Punjabi India), but also there's "pa-PK" (Punjabi Pakistan).

Then, you need to edit every value (info inside of <value></value>) to be supported in your desired language. The name of the data is what tells you the purpose of the value. Don't edit the data name, only edit what's in <value> for that specific piece of data.

If there are names for products (or companies), you probably shouldn't translate these. Leave these as is. Various examples include:
- Bloxstrap
- Discord
- Byfron
- GitHub
- Roblox
- Hyperion
- ReShade
- Windows (or Windows Media Foundation)
- JSON

Abbreviations should also not be translated. For example, "UDMUX" or "ID". These are general terms that cannot necessarily be translated into a language and should be left in

This is a pretty basic guide, but hopefully this helps you enough.
