### ISSUE TITLE
Multi Instance Launching inconsistent

### ISSUE THREAD

**Issue by joeyman2525** [pizzaboxer/bloxstrap#99]
The Multi Instance launching that was added in 2.0.0 is extremely inconsistent, and I was only able to get it to work once. I already set the Bloxstrap.exe executable to run as administrator all the time, so I'm not sure if there's anything else I'm supposed to do.

**Comment by pizzaboxer** [comment]
Yeah, I'm aware there's some issues with it right now. I'm hoping to have them ironed out by the next release. (https://github.com/pizzaboxer/bloxstrap/commit/b5250e29dcbc7705f0719116920a55210ba24f75 / https://github.com/pizzaboxer/bloxstrap/commit/222006fa6ac6b1a66aac814657f886bf01b7ce4a)
