### ISSUE TITLE
[REQ] The ''gone'' feature.

### ISSUE THREAD

**Issue by SomeoneWithBadFPS803** [pizzaboxer/bloxstrap#990]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So pizzaboxer, where is the feature that says ''Rendering mode'', where you were able to change from Direct11 to vulkan etc.
![Screenshot 2023-11-26 190307](https://github.com/pizzaboxer/bloxstrap/assets/150060083/05db4e85-87a7-4411-8239-3379550e20e3)

**Comment by FooqX** [comment]
can you actually read

**Comment by FooqX** [comment]
the release notes?

**Comment by TheMetalTechnet** [comment]
> ### Acknowledgement of preliminary instructions
> 
>     * [x]  I have read and acknowledged the preliminary instructions.
> 
> 
> ### What idea do you have?
> 
> So pizzaboxer, where is the feature that says ''Rendering mode'', where you were able to change from Direct11 to vulkan etc. ![Screenshot 2023-11-26 190307](https://private-user-images.githubusercontent.com/150060083/285965926-05db4e85-87a7-4411-8239-3379550e20e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDkyNjMsIm5iZiI6MTcwMTEwODk2MywicGF0aCI6Ii8xNTAwNjAwODMvMjg1OTY1OTI2LTA1ZGI0ZTg1LTg3YTctNDQxMS04MjM5LTMzNzk1NTBlMjBlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxODE2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzI3M2ZmYTc5ZjNiOGUxZThlNWYyZTk5YzRhOTZiZWU1ZTk5MThlMGU4NmE2YTJiNGQ4MWE4ZjlhYmNiYmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hit3HwL39dbAruHZfWRz9HWQR7Ix8qinmz1vpblcJ_A)

If you bothered to take a look at patch notes you would know that it was removed, reason is fact that Automatic was the only usable API (Vulkan wasn't working on old GPUs and recently Hyperion started to detect it as a malicious program, OpenGL just sucks, and DirectX 10 breaks a lot of effects, and DirectX 11 is used automatically)
