### ISSUE TITLE
I found a way to play on roblox on google but u have to uninstall bloxtrap

### ISSUE THREAD

**Issue by bjgdavid** [pizzaboxer/bloxstrap#992]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

1. delete bloxtrap from contol panel
2. delete the dekstop runtime from control panel
3. delete roblox player from control panel
4. go on google roblox and try to join a game 
5. download roblox like normal
6. when installed go into roblox player and then try playing on google
   np still sad i couldnt use bloxstrap

**Comment by Strongmanavai** [comment]
_Not working_

**Comment by pizzaboxer** [comment]
Instead of asking for help with your issue, you're instead just telling people to uninstall it?
