### ISSUE TITLE
Roblox Not Opening

### ISSUE THREAD

**Issue by Strongmanavai** [pizzaboxer/bloxstrap#993]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

_Roblox Doesn't Open After Deleting Bloxstrap and Installing Normal Roblox Roblox Doesn't Open Because of Bloxstrap Please How Can I Solve It?_

**Comment by pizzaboxer** [comment]
You've just said yo uninstalled Bloxstrap. If you have it uninstalled, how would Roblox be unable to open because of it?

**Comment by Strongmanavai** [comment]
_Roblox Doesn't Open Even If I Delete Bloxstrap And Even If I Install Bloxstrap, Roblox Doesn't Open_

**Comment by Strongmanavai** [comment]
_then i won't be able to play roblox anymore_

**Comment by Strongmanavai** [comment]
_Thank you very much for telling me that there is a problem with Roblox. As a result of my efforts, I can play Roblox and now I will download Bloxstrap._
