### ISSUE TITLE
[REQ] Custom Installation Path

### ISSUE THREAD

**Issue by HumangasROBLOX** [pizzaboxer/bloxstrap#997]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

So, what I want to do is to be able to change the installation path of roblox. For example, since there is a way of using reshade now (with NVIDIA gpu's), you need the RobloxBetaPlayer name to be changed to eurotrucks2 (im assuming its just changing the name to a game that is compatible with NVIDIA's filter feature) but, every time I do this with the bloxstrap installation it just installs a new roblox and ignores my last one

![image](https://github.com/pizzaboxer/bloxstrap/assets/59004170/2867f22e-f7ca-49c7-83d3-f9730626dfc8)
-Example of it just ignoring the renamed roblox

**Comment by pizzaboxer** [comment]
This is already planned, but the new update won't be out for a while. What you can do in the meantime is disable automatic updates, and install this test build that I made which just tested this functionality out. https://github.com/pizzaboxer/bloxstrap/suites/17761020689/artifacts/1017388973

**Comment by texwt** [comment]
> This is already planned, but the new update won't be out for a while. What you can do in the meantime is disable automatic updates, and install this test build that I made which just tested this functionality out. https://github.com/pizzaboxer/bloxstrap/suites/17761020689/artifacts/1017388973

Hello, the link for the test build doesnt work anymore

**Comment by pizzaboxer** [comment]
Works fine for me? You need to be logged into GitHub to access it.

**Comment by Shanemakesscripts** [comment]
oh nevermind your right thank you

**Comment by zaafaazaa** [comment]
> This is already planned, but the new update won't be out for a while. What you can do in the meantime is disable automatic updates, and install this test build that I made which just tested this functionality out. https://github.com/pizzaboxer/bloxstrap/suites/17761020689/artifacts/1017388973

the link doesnt work anymore, i have login allready

**Comment by BokBoy** [comment]
> > This is already planned, but the new update won't be out for a while. What you can do in the meantime is disable automatic updates, and install this test build that I made which just tested this functionality out. https://github.com/pizzaboxer/bloxstrap/suites/17761020689/artifacts/1017388973
> 
> 
> 
> the link doesnt work anymore, i have login allready
> 
> 

This is an old issue the link has expired.

**Comment by pizzaboxer** [comment]
> the link doesnt work anymore, i have login allready

Oh, right.

Actually, I'll create a 2.5.4 variant in a moment, since I might as well, and it'll just take a few minutes.

**Comment by pizzaboxer** [comment]
https://github.com/pizzaboxer/bloxstrap/actions/runs/7854168779/artifacts/1235392896

You'll still need to disable automatic updates when using this.

Mirror is available at https://files.pizzaboxer.xyz/bloxstrap-debug/release/version-2.5.4-nvidia.zip.

**Comment by lukas27892** [comment]
How do i use this version to make sure that "eurotrucks2.exe" (renamed roblox) can be used?

 Do I have to uninstall Bloxstrap and re-install it in order to receive the prompt to change the executable being run?

 If that is the case, will there eventually be a change so that you can change the executable without the need to uninstall Bloxstrap?

**Comment by BokBoy** [comment]
> How do i use this version to make sure that "eurotrucks2.exe" (renamed roblox) can be used?
> 
> 
> 
>  Do I have to uninstall Bloxstrap and re-install it in order to receive the prompt to change the executable being run?
> 
> 
> 
>  If that is the case, will there eventually be a change so that you can change the executable without the need to uninstall Bloxstrap?

How does have any relationship with custom install paths??

**Comment by pizzaboxer** [comment]
> Do I have to uninstall Bloxstrap and re-install it in order to receive the prompt to change the executable being run?

...No, just run the thing.

**Comment by S1m1B1lly** [comment]
i swapped the bloxstrap exe on my install with this one, it installs the game as eurotrucks2, but when i run it via bloxstrap, nvidia doesn't recognize the game as supported, unless i run the game manually from its exe

**Comment by pizzaboxer** [comment]
> but when i run it via bloxstrap, nvidia doesn't recognize the game as supported

Try disabling all the integrations given in the Bloxstrap Menu.

**Comment by raidenperfume** [comment]
Hey, I finally did it and achieved the Nvidia Filters for Roblox, but now it seems like the FPS unlocker feature of Bloxstrap don't seem to work (while other work well).
Is there a way to fix this so you have both filters and unlimited FPS together ?

**Comment by pizzaboxer** [comment]
Are you using https://bloxshade.com?

**Comment by kajie123** [comment]
yeah

**Comment by aaravisop** [comment]
the link is not working
