### ISSUE TITLE
Is there a FFLAG that brings back the old topbar?

### ISSUE THREAD

**Issue by Nooby-Hub** [pizzaboxer/bloxstrap#998]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

is there a way to get it?

**Comment by canarydiscord** [comment]
no

**Comment by pizzaboxer** [comment]
no

**Comment by Nooby-Hub** [comment]
okay
